### ISSUE TITLE
VirtualMachine>>#documentPath is wrong

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#10007]
**Bug description**
VirtualMachine>>#documentPath is not clear and returns a "random" value 

**To Reproduce**
1. open a playground
2. evaluate `Smalltalk vm documentPath`
4. you should see `--interactive`

**Expected behavior**
This method should probably be deprecated and then removed since it refers to the second argument given to the image but we cannot ensure this second argument will be a document path.

**Comment by jordanmontt** [comment]
We evaluated with @hernanmd  `Smalltalk vm documentPath "'--interactive'"` and we have `--interactive` as a Result. We don't understand this issue. Is it still relevant? @demarey

**Comment by demarey** [comment]
I think the issue is still relevant!
Do you find "--interactive" a right answer to `Smalltalk vm documentPath` ?

**Comment by hernanmd** [comment]
What is documentPath? I understand it should return a path to a directory with documents of?

**Comment by demarey** [comment]
it is exactly the point: I do know what this method should return. If you look at the implementation, it returns the second argument passed to the VM ...

**Comment by guillep** [comment]
I think we should just remove this method.

It does not make sense to deprecate a method that is wrong.

**Comment by MarcusDenker** [comment]
I close this for the newer https://github.com/pharo-project/pharo/issues/15574
