### ISSUE TITLE
Cleanup deprecated methods

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#10014]
After integration of https://github.com/pharo-project/pharo/pull/10013, there are still a couple of deprecated methods to remove/review that do not have deprecation annotations.

- FluidClassBuilder>>#uses:, FluidTraitBuilder>>#uses: https://github.com/pharo-project/pharo/issues/10065
- IceRepository>>#branchesForMerge: https://github.com/pharo-vcs/iceberg/issues/1540
- RGElementDefinition>>#theNonMetaParentName: https://github.com/pharo-project/pharo/issues/10062
- StDebugger class>>#taskbarIconName https://github.com/pharo-spec/NewTools/issues/298
- Trait class>>#named:uses:category: https://github.com/pharo-project/pharo/issues/10066
- Trait class>>#named:uses:slots:category: 
- Trait class>>#named:uses:slots:category:env: 
- Trait class>>#named:uses:category:env:

We should study case per case and either add a stronger deprecation, replace  users, and potentially remove them.

**Comment by MarcusDenker** [comment]
I opend issue for all of them, this way this can be closed
