### ISSUE TITLE
[Feature Request] Pragma should gave a #sourceNode method

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#10027]
All Pragmas (<these: #things>) result in instances of Pragma that you can get from the method (e.g. "(Behavior>>#basicNew) pragmas"

What is not easy is to get from those pragma instances to the AST that created them. "(Behavior>>#basicNew) pragmas first sourceNode" does not exist.

Take care: 

- there can be multiple pragmas that are the same
- RBPragmaNode does not store the pragma instance

**Is your feature request related to a problem? Please describe.**
I wanted to highlight the pragma in the Pragma inspector pane, no way to get the text offset now.

**What needs to be done**
RPParseNode should store the Pragma instance, not the information to create one (see senders of #asPragma how they are now created).

After that, we can easily check which RBPragmaNode has the pragma, and thus implement #sourceNode very easily.

**Comment by MarcusDenker** [comment]
I think one idea can be to treat RBPragmaNode a bit the same as a variable: the semantic analysis could annotate the RBPragmaNode with the Pragma instance. 

Looking at #asPragma senders, this would reduce the places where we create pragmas to be just that one place in the semantic analysis and would simplify the code related to reading the compilerOptions Pragma, which we already have to do in Semantic analysis.

see OCASTSemanticAnalyzer>>#visitPragmaNode:

**Comment by MarcusDenker** [comment]
This is sadly right now not possible. Due to the AdditionalMethodState>>#copyWith: being called in the compiler and it copying Pragmas, too, when the compiler finally sets the compiledMethod in the pragma of the method, that pragma is nor the instance that the RBProgramNode references.

We thus need to first do the cleanup we wanted to do in Pharo9: Pragmas should be stored in a property called #pragmas.
This would avoid relying on AdditionalMethodState to store them directly, thus copyWith:  would not copy them.

**Comment by astares** [comment]
Yes - having them as properties would be good.
