### ISSUE TITLE
Pharo10 system version does not report that it is "alpha"

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10024]
The welcome window and the system version of a Pharo 10 image do not say it is alpha. This is due to the missing **suffix** "alpha" in the system version object.

![image](https://user-images.githubusercontent.com/5980033/134421582-cd583151-0c16-49bd-8ea5-ddcea3673af4.png)

**Comment by astares** [comment]
If the **suffix** would have been set correctly (as in the past) also the welcome window would fit. I guess it has been changed when Pharo 9 was released and forgotten to reintroduce when Pharo 10 was started:

![image](https://user-images.githubusercontent.com/5980033/134421875-d443c253-5c80-4bdd-8a87-5ad8090ec384.png)

Basically we have "alpha" or "beta" during the development phase of the iteration (with all intermediary daily release builds) and an empty suffix for the final release.

**Comment by MarcusDenker** [comment]
can be closes as Pharo10 is not alpha anymore
