### ISSUE TITLE
Cannot use Iceberg - Pharo 10 Windows 64bits FFI

### ISSUE THREAD

**Issue by terpon** [guillep/pharo-core#10026]
**Bug description**
On clean image launch, two debugger windows pop.
First one is "Error: Can't find the requested origin". Looks like some system settings error.
Second one is "#substrings: was sent to nil". It comes from libgit2_init FFI call.

**To Reproduce**
  1. Open Iceberg
  2. Try to repair pharo repository
  3. Point to existing repo on hard drive
  4. Debugger pops up.

On the second try, just opening Iceberg triggers the error.

**Call stack**

UndefinedObject>>doesNotUnderstand: #substrings:
FFIWindowsLibraryFinder(FFILibraryFinder)>>ldLibraryPaths
FFIWindowsLibraryFinder(FFILibraryFinder)>>paths
[...]
LGitRepository(Object)>>ffiCall:options:
LGitRepository>>repository_open:bare_path:

**Additional informatio**
Last stack level is ```FFILibraryFinder>>ldLibraryPaths
	^ (OSEnvironment current at: 'LD_LIBRARY_PATH' ifAbsent: [ '' ]) substrings: ':'```

Inspecting `OSEnvironment current`  Meta is is a PlatformIndependentEnvironment (right-click on browse open Browser on Undefined Object though).
at:ifAbsent: returns nil. But it probably should be a Win32Environment?

**Version information:**
 - OS: Window10 64bits
 - Pharo 10 64bits

**Comment by JanBliznicenko** [comment]
Confirm with current Pharo 10 image on Windows. Problem is there since commit 6ec3988 (merge d0cfb50, PR #10008)

**Comment by guillep** [comment]
Yes, this may be my fault. I'm looking at this right now.

**Comment by Ducasse** [comment]
Thanks jan
