### ISSUE TITLE
TextAnchors with morphs do not render in Rubric

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#10035]
**Bug description**
Inspecting this piece of code:

```smalltalk
circle := CircleMorph new extent: 50 @ 50;color: Color blue.
(String value: 1) asText addAttribute: (TextAnchor new anchoredMorph: circle asForm).
```

correctly shows:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/17723745/134630552-fd6d7a27-5b82-4a3c-82e6-05a25d461c5f.png">

However, if one just tries to anchor the morph itself:
```smalltalk
circle := CircleMorph new extent: 50 @ 50;color: Color blue.
(String value: 1) asText addAttribute: (TextAnchor new anchoredMorph: circle).
```
no circle is shown.

The crucial method doing something wrong seems to be `RubDisplayScanner>>placeEmbeddedObject:`. In that method there is this piece of code:

```smalltalk
        anchoredMorph isMorph ifTrue: [
		anchoredMorph position: ((destX - anchoredMorph width)@lineY) - morphicOffset.
	] ifFalse: [
		destY := lineY.
		baselineY := lineY + anchoredMorph height..
		runX := destX.
		anchoredMorph 
			displayOn: bitBlt destForm 
			at: destX - anchoredMorph width @ destY
			clippingBox: bitBlt clipRect
			rule: Form blend
			fillColor: Color white 
	].
```

I am no expert in morph, but is seems like the morph is **not** drawn on the bitBlt destForm. I have no idea of how to do that, or is the problem is elsewhere. But adding a `haltOnce` in the true-part and inspecting the text do bring us here.

**Comment by Ducasse** [comment]
Yes it would be good to be able to first being able to display a morph. 
Did you try to move the ifFalse code out of the false branch?
(writing report all week-end no fun allowed).

**Comment by kasperosterbye** [comment]
I did try various things, but it boils down to me not knowing how to draw a morph onto a Form. Morphs like to be drawn on a Canvas, but I cannot figure out how to bridge Form and Canvas in a good manner.
Perhaps it should just be done by converting the Morph into a Form - which works. All properties of the morph is lost though when it is converted into a form. Perhaps that would be the case anyway.

**Comment by Ducasse** [comment]
I do not know but once I just tried to convert the morph into a form (asForm) so that we can pass a morph.
Of course doing this is not nice because the event and all the rest are not handled correctly.

**Comment by kasperosterbye** [comment]
I have now made a PR so Rubrics do show Morphs embedded in TextAnchor. The solution attacks the problem in `RubAbstractTextArea`.

**Comment by Ducasse** [comment]
Oh this is cool.
