### ISSUE TITLE
Enhance Help System to be Microdown based

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#10042]
There are several ways in which this can be done. My proposal is to:

- Export the existing help into Microdown files in the doc (or docs folder)
- The status of the [NewTools-DocumentationReader](https://github.com/pharo-spec/NewTools-DocumentationReader) is that it is actually able to present Microdown files in a manner rather similar to the existing help system, so once the files exist, then can be presented.
- In the existing help system, the help topics are ordered. A simple index.txt file should allow to give both order and to load the documents from github directly. The current NewTools-DocumentationReader reads files, so some extension is needed
- Maintenance of help is done in the Microdown files in the doc folder, which gives versioning and pull-requests

I have made an exporter which seems to work. 

It required a bit of refactoring to the existing help system, and I want to hear if the above would be a way to go.
If so, I will make a PR which adds the exporter to `HelpSystem-Core` so we can start using it.

If there are other plans for the help system, please just comment and close this issue.

**Comment by astares** [comment]
Some thoughts:

1. Managing the documentation and guides outside of image is a good idea (and would not bloat the image)
   Independent from that it would be nice to still edit it using in-image tools.
 
2. Did you see https://github.com/pharo-project/pharo/tree/Pharo10/doc which I guess was created by @Ducasse to host the documentation now externally in the future
   So I doubt we need to add the exporter now to the image. Maybe it is better to
       a) finish the documentation reader and integrate it and then 
       b) export the current in-image docu one time to external files

But I guess @Ducasse can better comment about the actual plan and steps


<blockquote><img src="https://repository-images.githubusercontent.com/64123480/451beb80-d08b-11e9-9ade-21d166d787d9" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">pharo/doc at Pharo10 · pharo-project/pharo</a></strong></div><div>Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk. - pharo/doc at Pharo10 · pharo-project/pharo</div></blockquote>

**Comment by Ducasse** [comment]
We should go over the help subclasses that I did not convert and convert them (usually I rewrite them because many are obsolete).

**Comment by kasperosterbye** [comment]
I now believe the right thing to do is this two step procedure.

- A change to the existing help system to allow different implementations of the formatting methods implemented in 'CustomHelp' - this change belong to the Pharo system. An upcoming PR will should close this.

- The HelpExporter should be maintained as part of the NewTools-DocumentationReader. I put an issue there (in NewTools-DocumentationReader) to solve this.

**Comment by Ducasse** [comment]
kasper you see once we will have migrated the help class within Pharo and move them as file on the disc we can just simply remove the class. 
For the customHelp I plan to remove it. We do not need multiple format. 
I would like to have two things
- browsing help files
- support for displaying packages with class comments. (we did a prototype with leo this summer).

**Comment by kasperosterbye** [comment]
There is now a PR (#10048). It includes both the help exporter, and the generated files (I put them in the doc folder).
