### ISSUE TITLE
Cleanup Ring. Deprecate the #baseClass

### ISSUE THREAD

**Issue by olekscode** [guillep/pharo-core#10046]
**Describe the problem**
We deprecated #baseClass in the kernel, but Ring still uses this methods

Proposal
To keep Ring in sync with the kernel model, we need to deprecate all implementations of #baseClass in Ring and fix the senders.

This is part of another issue #9971.
In PR #10045, I have deprecated #theMetaClass and #theNonMetaClass.

I did not deprecate #baseClass because I was not sure if #instanceSide is doing the same thing

**Comment by MarcusDenker** [comment]
I checked: baseClass in Ring2 is just implemented in the stategy and has another meaning, it has nothing to do with #baseClass on Behavior --> can be closed
