### ISSUE TITLE
cannot save method when it contains a breakpoint

### ISSUE THREAD

**Issue by j-brant** [guillep/pharo-core#10059]
Saving a method from the browser when that method contains a breakpoint does not save the method. The text appears to be saved, but switching to another method and back shows the original source.

**To Reproduce**
1) Add a method to Object: 

```
asdf
	^self printString size
```
2) Set a breakpoint on the method.
3) Change the method by adding `+ 1` to the end of the method and save.
4) Switch to another method in the browser.
5) Switch back to the `asdf` method you just compiled.

**Expected behavior**
The method's source should be `^self printString + 1`, but it shows original source of `^self printString` instead. Furthermore, evaluating `1 asdf` returns 1 instead of the expected value of 2.

**Version information:**
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1552.sha.bb3e3cf017734294df2b83bb1eb394e195846d43 (64 Bit)

**Comment by guillep** [comment]
Seems duplicated of https://github.com/pharo-project/pharo/issues/9768 but yet to confirm
