### ISSUE TITLE
Review NullTextStyler

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10069]
Why do we have
- NullTextStyler>>#environment: 
- NullTextStyler>>#classOrMetaClass:

as empty methods?

**Comment by kasperosterbye** [comment]
I'll be brave and show my ignorance.
Basically all methods of that class are empty - why did you single out those two?
There are no usages (class ref) of that class in image (Pharo10 build 209) btw.

**Comment by astares** [comment]
These were just two examples. Not all methods are empty (see the getters).

NullTextStyler seems to mock API of SHTextStyler (which is also not referenced). According to the class comment it is a "styler NullObject" - but unfortunately not very clear why it is there, hot it is used and if still needed.
