### ISSUE TITLE
Calypso/Roassal issue when developing a yet incomplete BaselineOf class

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10075]
- start to implement a BaselineOf subclass 
```Smalltalk
BaselineOf subclass: #BaselineOfMyKillerApp
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'BaselineOfMyKillerApp'
```
and accept a first version of a #baseline method:
```Smalltalk
baseline: spec
	<baseline>
	
	spec for: #'common' do: [ 
		self 
			sqlite: spec.		
	]
```
**where the #sqlite: method is not yet implemented.**
 
When clicking on the method Calypso now wants to display/visualize the BaselineOf class already 
using Roassal extensions. For this it seems to internaly evaluate the #baseline: method and as it 
is yet incomplete one gets a debugger "BaselineOfMyKillerApp did not understand #sqlite:

If one looks at the stack this all comes from RSBaselineCalypso>>#buildUmlCanvas where the 
canvas is built. We should make this method more robust - possibly by adding an exception handler.

![image](https://user-images.githubusercontent.com/5980033/135214577-377dbaf6-4d95-4ada-b124-1a677539524f.png)

**Comment by akevalion** [comment]
Hello, is this issue still valid with the new baseline visualization?

**Comment by astares** [comment]
No -seems to work with incomplete ones. So we can close the issue

![image](https://user-images.githubusercontent.com/5980033/192759168-32dd8d70-792d-4981-afe2-928fa2374efc.png)
