### ISSUE TITLE
Beginner question

### ISSUE THREAD

**Issue by tripleo1** [guillep/pharo-core#10143]
hello. I am going to start my first project in Pharo and I need some help. I think Iceberg is just downloading (ie push and pull to git server), but what if I want others to collaborate.  Basically what is Metacello, and Baselines and do I need it?

**Comment by tesonep** [comment]
Hello, welcome. 
As you said Iceberg is used to manage the smalltalk code: load it, save it and share it through Git. You can check a nice booklet about Iceberg in http://books.pharo.org/booklet-ManageCode/pdf/2019-03-24-ManageCode.pdf.

Metacello and its Baselines is a way of handling projects and dependencies. In a Metacello Baseline, you describe the packages in your project and what other projects it depends on. You can check chapter 9 of the book Deep into Pharo, http://files.pharo.org/books-pdfs/deep-into-pharo/2013-DeepIntoPharo-EN.pdf 
Please refer to the section talking about Baselines, as nowadays is mostly recommended to use Baselines over Configurations 

Usually, you will be using both tools at the same time. As Iceberg is to manage the source code and Metacello to handle the resolution of dependencies. 

Other comment, you can find faster help in our Discord server. I highly recommend you to make questions there, as you will usually get faster responses, more information and a link in https://pharo.org/community.html.

Welcome again and please fell free to ask any problem.
