### ISSUE TITLE
Adopt testNoUtilsMethods

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10166]
We are down to 4 instead of 7

**Comment by demarey** [comment]
I do not see the rationale beside this rule: it only checks for #utils protocol. What about utility, utilities, etc ?
The target should be discussed.

**Comment by astares** [comment]
@demarey This will be addressed too - some patience is required. First the PR https://github.com/pharo-project/pharo/pull/10171 needs to get in as then we just have to define the idioms

**Comment by demarey** [comment]
@astares Yes, it is a huge work to get protocols rights. My concern is more : what is the plan? Is there a list of protocols we should use, not use?

**Comment by astares** [comment]
@demarey we already improve step by step.

The rough plan is to 
 - remove and avoid typos
 - use well known categories when appropriate ("accessing", "visiting", "utilities", "private" or combinations like "private - accessing")
 - avoid different writing styles (fixing more spaces than needed, different casing, etc.) 
 - allow people to find methods more easily with more proper categorization
 - get more consistent in the usage of categories
    (for instance #tearDown and #setUp should be in "running" while test methods should be in category similar to
     "tests" or "tests - something")
 - ...

Meanwhile a lot have been cleaned/improved already (compared to P8/P9) - as you can see in the predefined **list that Calypso provides** (which is built from categories in the system) to the user when he creates a protocol:

![image](https://user-images.githubusercontent.com/5980033/137901368-19a7144a-6b8a-4dfa-91d2-7062e746390a.png)

The Pharo is now also telling you for common bad idioms what is wrong:

![image](https://user-images.githubusercontent.com/5980033/137900470-5359f689-49f8-4620-890e-088c54a38635.png)

and allow you to autofix them easily using a refactoring (as Stef wished on the mailinglist to get some more support from system side)

![image](https://user-images.githubusercontent.com/5980033/137900788-44e30431-334e-4137-995d-75f9cfae1440.png)

The autofix is now also available for other stuff like unreferenced ivars (see #10125)
