### ISSUE TITLE
Put QuotedPrintableMimeConverter>>#newline: into initialization category

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10173]
Put QuotedPrintableMimeConverter>>#newline: into initialization category

**Comment by IAMPHARO** [comment]
I don't understand how this works .Also why am I not included in anything with the pharo project.I am told from the United States IRS That I had inherited an international software corporation in my surname .Apon further review and research and documented information the federal government has they say I owe all of these taxes developerment hubs complaining I haven't paid developers .invitations from WILDAPRICOT As the administrator of the organization pharo that I'm supposed to address.But I have no real personal  proof never received a dime.or acknowledgment of any of this I write the board not once gave they written back even
THE MIT LICENSE IS IN MY NAME THAT I STILL HAVE NOT TOTALLY CLAIMED AND WILL CHANGED THE LICENSE proprietary stadings if I have to.The license gifted to me from the free software foundation that all should have to read as it talks about the free software foundation but this licence is not totally about software but about FREEDOM.Please help me to be included please teach me of the legacy please understand that everything you have about me is fraud and is still being run and created by fraud actors using my identity .

**Comment by Ducasse** [comment]
Pharo is the name of our project and it has nothing to do with you.
Simple.

**Comment by IAMPHARO** [comment]
I can accept that .I actually prefer it. BUT I need you to explain that to the United States IRS the .minneasota judicial and finatual divisions of international commerce that states that I inherited pharo.org or associations in my surname and that I am liable to all such actions and agreements .Also please explain it to the DEPT OF COMERSE .THR FTC AND THE EU DATA PROTECTIONS CLAUSE 10 OF PROTECTIONS

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Ducasse** [comment]
You can point them to us. And we have nothing to do with any US organisation. And we are not doing any commerce.

**Comment by MarcusDenker** [comment]
Yes, just point everyone to us (if Pharo related, there are other things called Pharo, too).

for WILDAPRICOT, we got a request for a student membership. I will remove it as it seems it was not the intent to join.
