### ISSUE TITLE
In the debugger Implementors is broken when the class is defining an instance variable with the same name as the method

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#10198]
<img width="1015" alt="Capture 2021-10-20 at 10 02 09" src="https://user-images.githubusercontent.com/432549/138052771-d4362f62-43ce-49da-a41b-71b913c72ce1.png">

**Comment by guillep** [comment]
We were working on this yesterday with @MarcusDenker, and it should be fixed by https://github.com/pharo-spec/Spec/pull/1179

And still, after merging that PR we should wait until it is integrated in Pharo.

**Comment by Ducasse** [comment]
Ah I remembered seeing something around but it was unclear.

**Comment by MarcusDenker** [comment]
PR is now merged
