### ISSUE TITLE
Class Side Fluid syntax does not return a builder

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#10196]
See #8179

**Comment by Ducasse** [comment]
For the fluid class builder on class side

We should return a builder prefilled with information from the instance side.

For this we should

Object << #Point

=>

Object class << #Point class
slots: {#uniqueInstance}
traits: {TFlying + }
package: ....
The steps to get there are:

grab the instance (Point)
create a class side builder to prefilled itself from the instance side
then fill up the slots

**Comment by MarcusDenker** [comment]
This is fixed, a builder is returned
