### ISSUE TITLE
Instance of SpMultipleSelectionMode did not understand #selectedIndex

### ISSUE THREAD

**Issue by j-brant** [guillep/pharo-core#10201]
**Bug description**
The SpAbstractMorphicLIstAdapter>>triggerActivationAction method sends #selecedIndex to a SpMultipleSelectionMode object.

**To Reproduce**
1. Open "Spec2 Examples" from Help menu.
2. Select the Lists example.
3. Click an item in the "Multi selection/Sorting" list.
4. Hit "return" or "enter" on the keyboard.

**Expected behavior**
Not opening a debugger.

**Version information:**
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1564.sha.f5f541cb35c8609abfec418e35d5506715c7987d (64 Bit)

**Comment by Ducasse** [comment]
@estebanlm
