### ISSUE TITLE
Cannot inline method if the code to inline is not an immediate node

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#10208]
**Bug description**
shouldInlineExpression: uses the default behavior in initializeRefactoringOptions that returns an error.

**To Reproduce**
1. Go to HEInstaller >> buildTrait:
2. Try to inline buildTraitCompositionFor: in the method
3. See error

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/4706329/138132221-26398448-51c4-4da6-afaf-6c38a83497d1.png)

**Version information:**
 - OS: win
 - Version: [e.g. 1.6.1]
 - Pharo Version
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1564.sha.f5f541cb35c8609abfec418e35d5506715c7987d (64 Bit)

**Expected development cost**
?

**Additional context**
Lifeware tag

**Comment by Ducasse** [comment]
Thanks. Now we lost the person working on refactorings so it will take time before we fix it. (sadly)
