### ISSUE TITLE
Fluid API question: trait: TEmpty vs traits: {} and its implication

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#10212]
In fluid class parser we use trait: and it can be an empty array or a trait (composition). 
This is really bad to have a such difference because from a user perspective we
get slots: {} and we are adding a slot inside which is coherent 

```
slots: {};
slots: {#a . #b};
```
we have the same for sharedPools:, shareVariables:...

But for traits we go from 

```
trait: {}
``` 
to 
```
trait: T1 + T2
``` 
yes this can be confusing that this is not multiple traits but yes it is multiple traits expressed as a composition.

For example 

```
Object << #MyClass
	layout: FixedLayout;
	trait: {};
	slots: {};
	sharedVariables: {};
	sharedPools: {};
	tag: '' ;
	package: 'Kernel-Traits'
```

With Pablo we started to change trait: into traits: 
so that we have 

```
Trait << #TMyTrait
	traits: {};
	slots: {};
	tag: '' ;
	package: 'Kernel-Traits'
```

and 
```
Trait << #TMyTrait
	trait: T1 + T3;
	slots: {};
	tag: '' ;
	package: 'Kernel-Traits'
```
It is working on a PR. 

But I wonder if this is good (even if I prefer to say that a class can use multiple traits and get a list).
May be the following is better

```
Trait << #TMyTrait
	trait: TEmpty;
	slots: {};
	tag: '' ;
	package: 'Kernel-Traits'
```

and 

```
Trait << #TMyTrait
	trait: T1 + T2 + T3;
	slots: {};
	tag: '' ;
	package: 'Kernel-Traits'
```

So please let us know what you think.

S

**Comment by demarey** [comment]
ah, this is funny! I was about to open an issue on this topic last week!
I first though Fluid API was not consistent: `slots` VS `trait` but I then realized that we are dealing with a Trait composition and not a list of traits. If we still go into that direction, I think `trait: {}` is wrong. we should use: `trait: TEmpty`.
If we want to be even more clear, I would use `traitComposition:`
Also, we should remember to allow to unplug traits if we do not want them (e.g. special version of Pharo, bootstrap).

**Comment by dionisiydk** [comment]
Hi.
I don't have concrete suggestion but it would be nice to think also about the consistency with "traits API" on the class level:
```Smalltalk
ClyClassWithTraits traits "==>an OrderedCollection(ClyTraitChild1 ClyTraitChild2Child)"
```
If definition will include a singular #trait then what we should use here?

**Comment by dionisiydk** [comment]
> Trait << #TMyTrait
> 	trait: T1 + T2 + T3;
> 	slots: {};
> 	tag: '' ;
> 	package: 'Kernel-Traits'

Could you write an example of complex trait composition (not just with +)? 

I wonder if we can change the "composition syntax" to something like:
```Smalltalk
 Trait << #TMyTrait
 	traits: {T1 . T2 . T3} rules: {"some composition modifiers for first group of traits"};
 	traits: {T4 . T5 } rules: {"some composition modifiers for second group of traits"};
        ..
```
Where every #traits message works as + for previous group of traits .

**Comment by Ducasse** [comment]
We will not change the composition clause.

**Comment by Ducasse** [comment]
@dionisiydk I'm currently fixing the class level and trait class level. I have nearly a solution (with printer, parser and class builder).
