### ISSUE TITLE
Copy (as in copy paste) a class definition reparses the class definition!!!

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#10210]
Put an halt in the method of CDClassDefinitionParser and press copy once you have selected a class...
And boum the class parser is invoked while we JUST want to copy the text.

**Comment by MarcusDenker** [comment]
if you put a halt in ClyClassDefinitionEditorToolMorph>>#selectedSourceNode you can see who is calling it

**Comment by Ducasse** [comment]
Thanks I could not reproduce it. I'm puzzled.
