### ISSUE TITLE
Image build by the CI sometimes is too large (128MB)

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#10215]
**Bug description**
The build on the CI should result in an image slighly smaller than 60MB. But often, it is 128 MB.

**To Reproduce**
Just have a look at http://files.pharo.org/image/100/ 

Compresses the zip is often 38MB (which is the 128MB image), sometimes correct 22MB (that is the 60M image)

** More infos **

I did a space tally analysis (full file attached). This does not show any problems, the image thinks it has just 65MB of allocated instances.
[STspace.txt](https://github.com/pharo-project/pharo/files/7387206/STspace.txt)

**Comment by MarcusDenker** [comment]
Saving this image does *not* shrink it (even more strange)

**Comment by astares** [comment]
If I remember correctly there somewhere was a kind of image inspector tool (maybe in @carolahp's work on bootstrap)

**Comment by MarcusDenker** [comment]
One theory that we had while discussing: it could be a pinned object that makes compaction impossible.

**Comment by carolahp** [comment]
[Here](https://github.com/carolahp/PharoImageInspector) is the image inspector @astares mentioned, but it works only with 32-bit images

**Comment by astares** [comment]
@carolahp unfortunately this one does not load. Looks like some dependencies are missing:

![image](https://user-images.githubusercontent.com/5980033/150230753-c5f91410-6f82-4040-bebd-9ebd3786838a.png)

**Comment by astares** [comment]
OK - found it:  https://github.com/pharo-project/opensmalltalk-vm/blob/pharo-9/smalltalksrc/VMMaker/LittleEndianBitmap.class.st

<blockquote><img src="https://opengraph.githubassets.com/561ffb1ab3dd9b67c81a6ef330b1e98455c0d81f24b5a2afcca89ce73fc7bf14/pharo-project/opensmalltalk-vm" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/opensmalltalk-vm">opensmalltalk-vm/LittleEndianBitmap.class.st at pharo-9 · pharo-project/opensmalltalk-vm</a></strong></div><div>This is the VM used by Pharo. Contribute to pharo-project/opensmalltalk-vm development by creating an account on GitHub.</div></blockquote>

**Comment by MarcusDenker** [comment]
merged https://github.com/pharo-project/pharo/pull/10972
