### ISSUE TITLE
Looking in source for TEmpty brings strange results 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#10213]
<img width="869" alt="Capture 2021-10-21 at 07 46 11" src="https://user-images.githubusercontent.com/432549/138218799-9473f66b-4d58-4cd2-a3c7-6cbdc6060be0.png">

**Comment by MarcusDenker** [comment]
it machtes tEmpty of #ifNotEmpty.

(the search is case insensitive by default)

**Comment by Ducasse** [comment]
ah yes. I could not see it. Tx

**Comment by MarcusDenker** [comment]
I did not see it either... had to start debugging to see it ;-)
