### ISSUE TITLE
Screen canvas is corrupted after a change of screen size via RDP

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#10216]
**Bug description**
If you switch computer (opening an image in local and reconnecting through RDP), you get this issue:
![image](https://user-images.githubusercontent.com/4706329/138239928-0eefe25e-c313-4f17-8769-559233b1a5d0.png)

**To Reproduce**
1. Open pharo
2. Disconect from the windows session
3. Reconnect from RDP with a different computer (preferably with a different screen size)

**Expected behavior**
No canvas corruption

**Version information:**
 - OS: Win10
 - Version: [e.g. 1.6.1]
 - Pharo Version 9

**Expected development cost**
Not that much

**Additional context**
Following of #8170 and #10179

**Comment by guillep** [comment]
Question: if after that you resize the window manually, does the canvas redraw properly?

**Comment by VincentBlondeau** [comment]
Yes. it is redrawing when resizing the main window. It should be fine at some point if it you are lucky to find the right size.
Also, I use a scaling factor in pharo options. Maybe it could have an impact.

**Comment by VincentBlondeau** [comment]
Closing. Cannot reproduce
