### ISSUE TITLE
SpExecutableLayout and many of its subclasses are missing class comments

### ISSUE THREAD

**Issue by refactoringdr** [guillep/pharo-core#10240]
**Describe the problem**
SpExecutableLayout and many of its subclasses are missing class comments. Trying to figure out the new spec2 stuff is difficult enough. Undocumented key classes like these make it more difficult.

**Classes involved**
SpExecutableLayout and many of its subclasses

**Proposal**
Add class comments.

**Version information:**
 - Version Pharo 9.0

**Comment by MarcusDenker** [comment]
The Pharo10 version has comments

For more suggestions of how to improve them, there is an issue on the spec tracker:  https://github.com/pharo-spec/Spec/issues/702
