### ISSUE TITLE
Browse on the 'meta' tab of the inspector opens a browser on UndefinedObject

### ISSUE THREAD

**Issue by refactoringdr** [guillep/pharo-core#10241]
**Bug description**
browse on the 'meta' tab of the inspector opens a browser on UndefinedObject

**To Reproduce**
1. Open an inspector
2. Switch to the 'meta' tab
3. Right-click on a class in the class hierarchy and select 'Browse'

**Expected behavior**
A class browser on the selected class should open.

**Version information:**
 - OS: MacOS
 - Version: 11.6
 - Pharo Version 9.0

**Comment by MarcusDenker** [comment]
https://github.com/pharo-spec/NewTools/issues/297 has more information about the cause and a possible fix
