### ISSUE TITLE
Fix lint in Array>>#copyWithDependent:

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10251]
![image](https://user-images.githubusercontent.com/5980033/138357553-0c690fea-0aa7-4e98-b983-8c08872b0752.png)

**Comment by kasperosterbye** [comment]
Funny - I thought there was a rule that would activate saying you should then change `isEmpty ifTrue:` with `ifEmpty`.

**Comment by astares** [comment]
@kasperosterbye Yes - funny. We should open a ticket to provide this. Can you open one and link? Thanks!

**Comment by kasperosterbye** [comment]
I am not the great fan of most of these suggestions so I would not like to do that :-/

In the case you brought up here, it might very well be that the original developer wanted to be more efficient and use the primitive size method directly. I am not sure which compiler optimisations are done - will `ifEmpty:` be inlined as well? How do I find out?

**Comment by MarcusDenker** [comment]
I think we decided in the past against a rule for ifEmpty:, it is not use that much and some people do not like it from a style perspective (to add yet another special kind of #if )

**Comment by kasperosterbye** [comment]
OK - thanks.
