### ISSUE TITLE
Improving Debugger with "Large" Objects

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#10256]
The debugger is slow to update when there are "large" objects in the inspector.
- [ ] Very slow operations when using long strings / bytearrays
- [ ] Showing object in the inspectors is slow
- [ ] PrintString limiting is too long
- [ ] Receivers with many instance variables.

**Comment by carolahp** [comment]
Solved in [PR](https://github.com/pharo-spec/NewTools/pull/322) for Pharo 10

**Comment by VincentBlondeau** [comment]
Tested on Lifeware image on Pharo 10. Working well!

**Comment by MarcusDenker** [comment]
Then we close the issue!
