### ISSUE TITLE
Improving Inspector when inspecting "large" objects

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#10255]
- [ ] Printing object with long printOn: result
- [ ] Selecting some text in the inspector, highlights all occurrences.
- [ ] Long Strings / Objects (with a lot of elements or instance variables)

**Comment by guillep** [comment]
Try with `String loremIpsum: 10 ** 5`

**Comment by carolahp** [comment]
We have to port this solution to Pharo 9.0

**Comment by carolahp** [comment]
Backported to Pharo 9.0 in [PR](https://github.com/pharo-spec/NewTools/pull/327)

**Comment by VincentBlondeau** [comment]
Tested on Lifeware image on Pharo 10. Working well!

**Comment by MarcusDenker** [comment]
Great! I close the issue
