### ISSUE TITLE
Senders / Implementors in Large images.

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#10254]
- [x] Senders / Implementors is slow
- [ ] Searching Implementors / Senders does not give feedback
- [ ] Symbol Hashing?

**Comment by MarcusDenker** [comment]
For the standard image:

- implementors 2% speedup: https://github.com/pharo-project/pharo/pull/10309
- sendersOf 11% speedup: https://github.com/pharo-project/pharo/pull/10311

**Comment by MarcusDenker** [comment]
I use a tribal benchmark:

[#asdfasdfasfdsdf implementors] bench

**Comment by guillep** [comment]
A 2% speedup is within an usual range of hardware/software noise (OS, CPU heat, other open apps...).
I don't think making the code less readable is worth it.

The 11% seems a more noticeable improvement, but still, these benchmarks would require a more systematic approach. Otherwise they could be really meaningless.

**Comment by MarcusDenker** [comment]
the code with the 2% speedup is more to have the same code in all the #scanFor: methods: all but two used #==, now they all use the same style.

**Comment by guillep** [comment]
> the code with the 2% speedup is more to have the same code in all the #scanFor: methods: all but two used #==, now they all use the same style.

Ah, well then that's a better justification.

The 2% performance improvement was not IMHO, because hashed collection performance requires to look at best/worst/average placements, collisions... If we are looking for improving performance, that we should do it in a more systematic way.

**Comment by VincentBlondeau** [comment]
Seems to be fixed with using Aleph (no loading time perceptible)

**Comment by MarcusDenker** [comment]
Then we can close this!
