### ISSUE TITLE
Improve Code Completion in Large Images

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#10253]
- [ ] Keyboard input freezes and queues events until the lookup ends.
- [ ] Frozen looking for non-existing symbols as receivers
- [ ] Widowing and Narrowing of queries.

Continuation of Issue #6311

**Comment by MarcusDenker** [comment]
CoPackageImplementedMessagesFetcher>>#entriesDo: could be slow for a package with lots of classes.

**Comment by guillep** [comment]
> CoPackageImplementedMessagesFetcher>>#entriesDo: could be slow for a package with lots of classes.

Yes, but in practice it is not, even for large images in lifeware, so no need to optimise there. The bottleneck is somewhere else: when no matches are found and all collections should be iterated for nothing.
