### ISSUE TITLE
[Spotter] Query more results when scroll

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#10267]
When there are more results, the scroll should show more.

**Comment by carolahp** [comment]
Simple solution implemented in [PR](https://github.com/pharo-spec/NewTools/pull/332)

**Comment by VincentBlondeau** [comment]
Not fixed on Pharo 10. There is still a limit

**Comment by carolahp** [comment]
Search heuristic improvement proposed in [PR](https://github.com/pharo-spec/NewTools/pull/347).
Query results are more precise. However, the number of results displayed is still limited.

**Comment by carolahp** [comment]
Spotter default limit increased to 10.000 in [PR](https://github.com/pharo-spec/NewTools/pull/348) 
(Limit can be changed in Pharo>Settings>Number of nested results by category)

**Comment by fedemennite** [comment]
Can be closed,
Thanks
