### ISSUE TITLE
Improve Breakpoints

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#10265]
- [x] Working in methods
- [x] Working in blocks
- [x] Adding / Removing does not alter the timestamp
- [x] Removing returns to the previous method without affecting the code

**Comment by MarcusDenker** [comment]
For the third point it seems to already work like that (timestamp is not changed).  I added a test: https://github.com/pharo-project/pharo/pull/10324

**Comment by carolahp** [comment]
@MarcusDenker I leave here the first UI improvements we just spoke about

- [x] **Improve Debugging submenu**

    When inserting a breakpoint, using the current debugging submenu, it is hard to know where the breakpoint will be inserted. 
    For example:

    <img src="https://user-images.githubusercontent.com/4822303/149376915-ca34ffd3-e189-4d10-953c-4d18902b73e3.png" width=50% height=50%>


    To solve this, the submenu should display the code section where the breakpoint will be inserted, similarly to:

    <img src="https://user-images.githubusercontent.com/4822303/149371780-03f3268e-475e-463f-bc46-9bf720b7cf3e.png" width=50% height=50%>


- [x] **Prevent accidental breakpoint insertion**

    A single click on the bar of the code editor inserts a breakpoint, and no confirmation is asked (this can freeze the system in core methods).
    
    A single click should open the debugging menu (as I just discovered is currently the case when right-clicking).
    And breakpoints should be inserted using double click (@MarcusDenker what do you think?)

**Comment by MarcusDenker** [comment]
all TODOs are done, so we can close this issue
