### ISSUE TITLE
[Pharo 9] Spotter throws exception when clicking on the arrow to see more

### ISSUE THREAD

**Issue by jordanmontt** [guillep/pharo-core#10276]
When you search something add want to see more results 

![Capture d’écran 2021-10-26 à 11 33 59](https://user-images.githubusercontent.com/33934979/138852022-8b7c25ac-5af0-4d57-9b16-76dcdf7f99a2.png)

An exception is raised. This has been fixed for Pharo 10, but no for Pharo 9

![Capture d’écran 2021-10-26 à 11 34 10](https://user-images.githubusercontent.com/33934979/138852039-95bceda3-5407-471a-8314-11c3d7626757.png)

**Comment by guillep** [comment]
Fixed in Pharo10. We should backport it to P9.

**Comment by MarcusDenker** [comment]
As nobody backported it since last December, I think we can close the issue.

(of course, if someone does the work to backport, we will of course merge it)
