### ISSUE TITLE
CoAvoidRepeatedFetcher>>hasAlreadyReturned: fails when editing any method

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#10286]
**Bug description**
The method: 
```smalltalk
CoAvoidRepeatedFetcher >>hasAlreadyReturned: anEntry

	^ elements includes: anEntry contents asSymbol
```
fails when trying to edit any method. It fails with `#asSymbol was sendt to nil`.

**To Reproduce**
1. Go to any class, but reproducible from `ZnClient>>addPathSegment:`
2. Try to type `request foo` in the empty line just after the method comment

**Expected behavior**
No error should happen

**Version information:**
 - OS: [macOS version 11.6]
 - Pharo Version [Pharo10.0.0 build: 233, commit: 6f901cd, date: 28 October 2021]

**Comment by MarcusDenker** [comment]
problem was introduced by #10278, I revert it
