### ISSUE TITLE
undefinedIdentifier is missing in SHRBTextStyler

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#10294]
```
resolveStyleFor: aVariableNode
	aVariableNode binding ifNil: [^#default].
	aVariableNode isArgumentVariable ifTrue: [ ^#methodArg].
	aVariableNode isTempVariable ifTrue: [ ^#tempVar].
	aVariableNode isGlobalVariable ifTrue: [ ^#globalVar].
	"here we should add support for #classVar"
	aVariableNode isClassVariable ifTrue: [ ^#globalVar].
	aVariableNode isInstanceVariable ifTrue: [ ^#instVar]. 
	"for now we use temp variable here, we could now color them with their own color"
	aVariableNode isWorkspaceVariable ifTrue: [ ^#tempVar]. 
	
	(self class formatIncompleteIdentifiers and: [ aVariableNode hasIncompleteIdentifier ]) 
		ifTrue:[ ^#incompleteIdentifier] .

	^#invalid.
```

it is missing ...

```
	aVariableNode isUndeclaredVariable ifTrue: [ ^#undefinedIdentifier ].
```

**Comment by MarcusDenker** [comment]
This is not that easy.... aVariableNode isUndeclaredVariable is true for all the cases where "aVariableNode hasIncompleteIdentifier" is true, too.

So if we add the #isUndeclaredVariable check before checking for incomplete identifiers, we would loose that. If we add it after, only vars that are not prefixes of other vars would be #undefinedIdentifier.

I think we need to somehow distinguish the case "we are typing and highlight for that" from "we highlight an already compiled method".

**Comment by kasperosterbye** [comment]
@MarcusDenker 
> I think we need to somehow distinguish the case "we are typing and highlight for that" from "we highlight an already compiled method".

In that case I accidentally did the right solution by making a special subclass of `SHRBTextStyler` which is used to highlight pharo code in microdown. 
The need in microdown rich text rendering is to be able to:
1. Tell if something is a full method or a code fragment (to make the header bold if it is a method decl)
2. The code fragment is "out of context" and should have no variables coloured red.

I was not able to automate 1), and the person writing the documentation must manually choose, and I am then able to repurpose the workspace flag of `SHRBTextStyler`. I "solved" 2. by overriding all the red-variable cases to not be red.
