### ISSUE TITLE
Error when parsing date and time with a timezone at the end

### ISSUE THREAD

**Issue by chisandrei** [guillep/pharo-core#10330]
The following two expressions raise an error starting with Pharo9.0-SNAPSHOT.build.1543.sha.0934b1e.arch.64bit.image

'05 October 2011 14:48 UTC' asDateAndTime. 
'04 Dec 1995 00:12:00 GMT' asDateAndTime

The change that made this fail happened in https://github.com/pharo-project/pharo/pull/9098. Now the Time parser does not expect the timezone as the end. Before the timezone at the end was ignored.  Maybe the current solution is better, but would be nice to have ways to also parse dates like that.

**Comment by svenvc** [comment]
The actual time format supported by DateAndTime>>#readFrom: is a Date, an optional Time and an optional TimeZone offset.

So it should be +Z or +hh or +hh:mm not UTC and GMT.

Parsing and using time zone abbreviations is not supported. It is also not stored as such, only the offset.

Note also that the actual offset varies with the time in a particular time zone.

ZTimezone in the ZTimestamp package knows a lot more about those identifiers, based on the standard Olsen database, and does real offset calculations.

  http://en.wikipedia.org/wiki/Tz_database
  https://www.iana.org/time-zones


<blockquote><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/2017a.png/1200px-2017a.png" width="48" align="right"><div><strong><a href="http://en.wikipedia.org/wiki/Tz_database">tz database - Wikipedia</a></strong></div></blockquote>
<blockquote><img src="/_img/bookmark_icon.ico" width="48" align="right"><div><strong><a href="https://www.iana.org/time-zones">Time Zone Database</a></strong></div></blockquote>

**Comment by chisandrei** [comment]
This change in date and time seems good, as before the timezone was parsed but ignored. The confusing part was that this got changed in Pharo 9 after release. 

Maybe this could be documented as a change between Pharo 9 and Pharo 10.
