### ISSUE TITLE
P9 backport: Pharo does not work on network drive on Windows

### ISSUE THREAD

**Issue by JanBliznicenko** [guillep/pharo-core#10333]
Hello, it will help greatly if solution of this issue was backported to Pharo 9: https://github.com/pharo-project/pharo/issues/10085

PR for original Pharo 10 issue: https://github.com/pharo-project/pharo/pull/10138

Thank you

**Comment by Ducasse** [comment]
Thanks jan for the notice!

**Comment by tesonep** [comment]
It has been backported #10137

**Comment by tesonep** [comment]
@JanBliznicenko are you still having the issue?

**Comment by JanBliznicenko** [comment]
@tesonep Ah, you are right, it seems I had too old image, sorry, it is fixed in P9 as well :)
