### ISSUE TITLE
STONZnUrl source code problem

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10356]
1. Source code of STONZnUrl is in package "STON-Core" with two methods

![image](https://user-images.githubusercontent.com/5980033/142054947-a744c1e8-a0e1-49ce-a9a7-45c9e7043e9b.png)

2. but the **same source code** is managed as a second file adding an extension to STONZnUrl in the exact same package

![image](https://user-images.githubusercontent.com/5980033/142055016-bddd2e66-9994-41c3-8cfc-8d0543ba33a1.png)

**Comment by guillep** [comment]
@tesonep  says "Tonel/Iceberg do not detect *ston-core as an extension because the casing is wrong"

**Comment by guillep** [comment]
@astares I assume this is fixed by #10360? I'll close it, we can reopen it if not.

**Comment by astares** [comment]
Yes. Fixed by #10360 automagically too

![image](https://user-images.githubusercontent.com/5980033/145116708-8394da4b-b280-4df2-a749-dc4b66e1a21d.png)

there is no STONZnUrl.extension.st anymore - so this is fixed

![image](https://user-images.githubusercontent.com/5980033/145116811-946f60c8-8a88-4b19-be86-dd52ba3a653b.png)
