### ISSUE TITLE
Cleanup: Metacello extensions should use correct casing / package name

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10368]
We do have extensions that do not follow correctly the package name. So for instance we have "*metacello-cypress" instead of "*Metacello-Cypress" and other.

Cases could be found using

```Smalltalk
badExtensions := CompiledMethod allInstances select: [:each | each protocol notNil and: [ each protocol beginsWith: '*metacello']]	
```
Basically we have the following protocol wrong:

![image](https://user-images.githubusercontent.com/5980033/142081401-e09091fb-174d-41c9-857e-b783834ebe4d.png)

**Comment by MarcusDenker** [comment]
This was merged
