### ISSUE TITLE
Cleanup zinc extensions should use correct casing (package name)

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10360]
In Pharo standard image we have some extensions (protocol name on extension method with a leading *) left that use not the name of the package correctly (wrong casing). This was fixed for Metacello-Core, STON, OpalCompiler and Renraku packages already (see #10343, #10337, #10356 and others)

This ticket here is for **Zinc** specifically. Having this as a separate PR will hopefully also allow @svenvc to reintragrate this change back into the original Zinc framework.

Details:
This extension issues seem to be a leftover from times (old pharo versions or even back from Squeak times) where the extension have been manually entered with a * following the name. Back then the casing and package name was not checked - so this is now a leftover in source code.

Later when Calypso was used as system browser there was a better way: a package selection dialog  was introduced to  to select the exact package when defining an extension.

We can pick out the cases from Zinc using:
```Smalltalk
badExtensions := CompiledMethod allInstances select: [:each | each protocol notNil and: [ each protocol beginsWith: '*zinc-']]
```

if we want to check which extensions do not use an uppercase package name we can use the following script to check
the whole image:

```Smalltalk
| condition |
condition := [:protocol | (protocol beginsWith: '*') and: [ protocol second isLowercase  ]].
casesToFix := CompiledMethod allInstances select: [:each | each protocol notNil and: [ condition value: each protocol ]].
badExtensionProtocols := (wrong collect: [:each | each protocol ]) asSet asSortedCollection
```

**Comment by astares** [comment]
Following extension methods have been identified for Zinc to be fixed where the extension is not following the package name properly:

![image](https://user-images.githubusercontent.com/5980033/142064492-0186c2e8-f98a-46a1-9914-f93f67757540.png)

**Comment by svenvc** [comment]
Thanks, taken over upstream https://github.com/svenvc/zinc/commit/6046f96176cad79cdc10320511bb378076912826
