### ISSUE TITLE
Changing font size from small to medium causes extremely large text to appear in method-pane tabs

### ISSUE THREAD

**Issue by Shaping** [guillep/pharo-core#10371]
In Settings, changing the font size from small to medium causes extremely large text to appear in method-pane tabs.  The text in the Finder is also extremely large.   

OS: Windows 10
Pharo version: 9.0

1. In Settings' Standard fonts, select medium.
2. Set default font to Source Sans Pro Regular 13.
3. Select Force All.
4. Click on System Browser (to update it; it does not update automatically and should), or open a System Browser.
5. Note the extremely large, almost impossible to read text in the method-pane tabs.

![image](https://user-images.githubusercontent.com/12146957/142093168-d7017ec1-ab8b-4ac0-bfb7-193675561d89.png)

**Comment by Shaping** [comment]
Can someone suggest places in the code to look for the bug?  Both System Browser and Finder are affected.

**Comment by svenvc** [comment]
I can confirm that this also happens on Pharo 10 on macOS.

It is very annoying.

In my case, even simple Playgrounds had this huge font that I did not ask for.

We have never been good in the area of font changes, but it got worse in Pharo 10.

**Comment by Shaping** [comment]
Indeed--very annoying.   I currently can't use Pharo.

I'm trying to figure out why this kind of bug isn't just noticed in passing by those who do the builds.  There must be a very limited script of GUI exercises (or none at all) for testing, and changing the font from small to medium (not really that big anyway) isn't one of them.

That's why I suggested automatic GUI testing with a tool like Leapwork, which is ready to go and fun to use.  I suspect Expecco, the St/X GUI testing tool, has its little bugs and problems.  A Pharo-GUI tester-person doesn't need this kind of inhibition/frustration when he's composing his first round of tests, and learning how to do visually scripted GUI testing.  I used Leapwork five years ago.  It's excellent and worth the cost.  The tech support is excellent.  I suggest investing in it for a few years, mastering and falling in love with it, and then possibly copying its functionality in Pharo.  A Pharo Leapwork expert would at least, at that point, be in a good position to compare Leapwork scripting productivity to that of Expecco, which would need to be ported to Pharo anyway for comparative testing.

This is an important issue.  Witness the time wasted writing e-mails and Git issues about this silly unexpected change-of-font bug.  This is where a good bit of the time and bandwidth go.  Is that what we want in the Pharo dev experience?

**Comment by Shaping** [comment]
I just tested the Pharo 10 release from 2022-04-05, and this bug persists.

**Comment by Shaping** [comment]
![image](https://user-images.githubusercontent.com/12146957/168647901-c9e7ba31-b657-44a8-9e95-3c19b09ae874.png)

More of the same.   If someone can suggest the general scope of classes to study to find the problem, I will see what I can do.  Many of the tools are unusable because the font is so big.  Why is this being pushed back and slated for later Pharo versions?  It prevents efficient use of Pharo in many cases.

**Comment by Shaping** [comment]
Above the font size in the class browser package pain (small) is supposed to be the same size as that in the tabs and in Finder window, which is topmost.

**Comment by Shaping** [comment]
The above problem happens in the latest Pharo 11.   It does not seem to be happening (so far) in Pharo 10 64-bit (stable). 
Does this mean that we fixed the problem in 10 and then broke it again in 11?

**Comment by Shaping** [comment]
Correction: the problem is still present in 10.  It happens when a medium font is selected.   Apparently the Display scale factor can be used to compensate for this, but the resulting font rending is not as sharp.

**Comment by Shaping** [comment]
Another related bug is that switching font size from medium back to small will change the current font style, resetting it to the default style.  The font style should remain unchanged when the gross size (small, medium, etc) is changed.

**Comment by Ducasse** [comment]
Hi I do not really understand the problem. Is it that the fonts are too large or that the text is then too large?

**Comment by Ducasse** [comment]
Are you talking about the label of the pane in the method browser.

**Comment by Shaping** [comment]
>

**Comment by Shaping** [comment]
> Are you talking about the label of the pane in the method browser.

In the last example, the most forward window has very large text because somehow (bug) the specified default font size was increased relative to that used in the background for the class browser.  In the tabs, also for some unknown reason, the jump in size is even more extreme.

**Comment by Shaping** [comment]
> Are you talking about the label of the pane in the method browser.

Compare the difference in size of all of the text in the inspector and all of the text in the browser behind it.

**Comment by Shaping** [comment]
The issue is not closed.   I did that accidentally.  I don't see a way to reopen.
