### ISSUE TITLE
Iceberg breaks when committing an extension method

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#10378]
**Bug description**
When trying to commit a set of changes which include an extension method iceberg breaks with a DNU.

```smalltalk
IceCritiquesVisitor>>visitExtensionDefinition: anIceExtension 
	
	^ anIceExtension definition accept: self
```
it is the `definition` method which is not known for the argument of type `IceExtensionDefinition`.

The error occurs independent of the flag to use the critiques:
<img width="204" alt="image" src="https://user-images.githubusercontent.com/17723745/142361593-34868f7d-8ec4-4dde-b2c8-f0db9d2e7a87.png">
pointing to an other error (of running the critique no matter what).

**To Reproduce**
Create a method `foo` in class `String` and mark it as extension method of project A. Commit project A 

**Version information:**
 - OS: [MacOs]
 - Version: [11.6
 - Pharo Version [Pharo10.0.0 build: 267, commit: 040211a, date: 17 November 2021]

**Expected development cost**
I am not sure if this is the root of the problem, but this might be a workaround, making the checkbox work so critiques can actually be disabled.

The implementation of `IceTipCommitBrowser>>doCommit` runs the critiques always, and then at the end checks to see if the user wants to see the critiques.
Inserting an exit in the style of 
```smalltalk
IceTipCommitSettings critiquesOnCommit 
		ifFalse: [ 
			self
				doCommit: selectedItems
				message: message
				pushing: isPushing
				saving: isSaving.
				^self ].
```
before running the critiques makes it possible to get around the problem with the critique visitor. I am not too sure about inserting the above exit into the code - this is the first time I look into Iceberg.

**Comment by tesonep** [comment]
Thanks a lot @kasperosterbye

**Comment by kasperosterbye** [comment]
You are welcome! - I still find it odd that you run the critiques even if you do not present them - but you are the one who knows the big picture.
