### ISSUE TITLE
Changes in blank/newline removals are not shown in Iceberg/DiffMorph

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10397]
We have many methods inside of the image with an unnecessary newline at the end. 
(see #10396 for more details and a query)

For example in method AColorSelectorMorph>>#drawOn: we have a "cr" at the end of the sourcecode

![image](https://user-images.githubusercontent.com/5980033/143136754-94b67b75-332d-4962-8e48-335b1e128135.png)

If one removes this newline manually from the source code and accepts

![image](https://user-images.githubusercontent.com/5980033/143136182-bed9b2c9-f612-4b52-b995-dfe9becf1f8e.png)

then Iceberg finds out that the method has been changed. But it does not highlight the difference in the commit dialog comparing the changes:

![image](https://user-images.githubusercontent.com/5980033/143136311-49c6773e-2572-4b23-ad51-da094c6cf3ec.png)

**Comment by astares** [comment]
One could simulate the effect using

```Smalltalk 
| method oldSource newSource refactoring|
method   := AColorSelectorMorph>>#drawOn:.
oldSource := method sourceCode copy.
newSource := method sourceCode trimRight.
refactoring := RBAddMethodChange compile: newSource in: method methodClass for: nil.				 
refactoring execute				 
```

**Comment by astares** [comment]
It is not an Iceberg issue per se. Actually I think this goes back to the DiffMorph not showing these differences in the strings:
```Smalltalk
 
| method oldSource newSource refactoring|
method   := AColorSelectorMorph>>#drawOn:.
oldSource := method sourceCode copy.
newSource := method sourceCode trimRight.
refactoring := RBAddMethodChange compile: newSource in: method methodClass for: nil.				 
refactoring execute.
(DiffMorph from: oldSource to: newSource) openInWorld
```

**Comment by astares** [comment]
The GitHub differ for instance (as well as other diff tools around git) would show such changes with a specific color:

see https://github.com/astares/pharo/commit/4cced078f0987a66a34ef893573bebb0461360b8

![image](https://user-images.githubusercontent.com/5980033/143137928-ba751ee9-219b-4eb1-a252-f34c3984aeb8.png)

**Comment by astares** [comment]
Maybe it is related to https://github.com/pharo-spec/Spec/issues/1203

**Comment by astares** [comment]
Strange enough it shows when getting changes in:

![image](https://user-images.githubusercontent.com/5980033/143233137-e1c0edc8-ca62-4cc0-8e43-91b99b17c2ec.png)

**Comment by estebanlm** [comment]
well, this is not related, he :P

**Comment by astares** [comment]
Works in commit dialog in latest Pharo 10:

![image](https://user-images.githubusercontent.com/5980033/143326686-22890aa9-fd9b-488f-82f3-5b8ce46cf6b6.png)
