### ISSUE TITLE
Behavior>>#allCallsOnIn: sends unimplemented methods

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10391]
![image](https://user-images.githubusercontent.com/5980033/143093765-b025c25e-a9fb-474e-ab66-44bd3efd9777.png)

**Comment by astares** [comment]
The method #instanceSide is implemented in ClassDescription using a subclassResponsibility which is then fulfiled in the subclasses Class and Metaclass.

![image](https://user-images.githubusercontent.com/5980033/143094333-5ed458e1-89de-4484-957f-c2b952a8ce62.png)


Maybe we should move ClassDescription>>#instanceSide up into Behavior to fix this.

@MarcusDenker: any comments?

**Comment by MarcusDenker** [comment]
We should move it to ClassDescription..

**Comment by astares** [comment]
@MarcusDenker It already is at ClassDescription. So we should pull up to Behavior, no?

**Comment by MarcusDenker** [comment]
I mean allCallsOnIn, instanceSide makes no sense on a Behavior... that concept is only added by ClassDescription

**Comment by astares** [comment]
OK - so it can be fixed by pushing #allCallsOnIn: from Behavior down into ClassDescription
