### ISSUE TITLE
Cleanup newlines and blanks in "ConfigurationCommandLineHandler" packages

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10422]
see https://github.com/pharo-project/pharo/issues/10396 and fix it for "ConfigurationCommandLineHandler" related packages:

```Smalltalk
badCases := SystemNavigation default allMethodsSelect: [ :each | each sourceCode trimRight size ~= each sourceCode size ].

fixInPackage := badCases select: [:each | each package name beginsWith: 'ConfigurationCommandLineHandler' ].

fixInPackage do: [:each |
	| refactoring |
	refactoring := RBAddMethodChange compile: each sourceCode trimRight in: each methodClass for: nil.				 
	refactoring execute	
]
```

**Comment by Ducasse** [comment]
Pay attention that compile the code will lose all the formatting.

**Comment by astares** [comment]
@Ducasse Compilation is done with same source string, only trimmed at the end to remove blanks/whitespaces. This should keep the formatting, no?

**Comment by Ducasse** [comment]
It depends :) but marcus says that it does not reformat the code so this is good.

**Comment by astares** [comment]
@Ducasse Depends on what?

As you can see on the diffs in the GitHub PR's linked for the issues mentioned in https://github.com/pharo-project/pharo/issues/10396 there is no formatting lost. At least I have not seen a single case from all what I compared yesterday.

So maybe you can ellaborate more in detail about concern. I would like to understand where you fear it could happen or if already a case was spotted.
