### ISSUE TITLE
Review T2OverloadingOfMethodsInTraitedClassTest

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10432]
we should possibly ban this lint rule for the two test methods or the whole test class

![image](https://user-images.githubusercontent.com/5980033/143244773-bacb1c2b-c5b5-44e6-986f-db741ac5f109.png)

**Comment by MarcusDenker** [comment]
There are lots of examples like that, we will fix them in the context of https://github.com/pharo-project/pharo/issues/10834
