### ISSUE TITLE
Wrong completion in keyword selectors

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#10437]
**Bug description**
When completing keyword selectors, under some conditions the selector is duplicated.

**To Reproduce**
Imagine I’m trying to autocomplete #asStringOn:delimiter:.

Case 1) if we do not type the colon, it works ok

1 asStringOn
=complete=>
1 asStringOn:  delimiter: .

Case 2) if we type the colon, it will complete duplicating the first keyword altogether

1 asStringOn:
=complete=>
1 asStringOnasStringOn:  delimiter: 

Case 3) if we start typing the second keyword, it will complete duplicating the first keyword separated by a colon

1 asStringOn:de
=complete=>
1 asStringOn:asStringOn:  delimiter: 

We can start by writing some tests based on this :)

Similar problems happens with more than one keyword.

**Comment by Ducasse** [comment]
I will check once the changes is integrated if my breaking scenario is fixed else I will report it. 
Basically

```
transform:| + completion
=> 
transformtransform:....
```

**Comment by guillep** [comment]
Hi @Ducasse , were you able to test this?

**Comment by Ducasse** [comment]
Yes and it worked :) I will continue to test but P10 looks to be in the right direction. 
implementors and senders are getting much better and completion too.
