### ISSUE TITLE
Do we need doWhileFalse: 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#10430]
Do we need doWhileFalse: when we have whileFalse: 
and we have one user and the logic look the same.

```
BlockClosure >> doWhileFalse: conditionBlock
	"Evaluate the receiver once, then again as long the value of conditionBlock is false."
 
	| result |
	[result := self value.
	conditionBlock value] whileFalse.

	^ result
```

```
BlockClosure >> whileFalse: aBlock 
	"Ordinarily compiled in-line, and therefore not overridable.
	This is in case the message is sent to other than a literal block.
	Evaluate the argument, aBlock, as long as the value of the receiver is false."

	self value ifFalse: [ aBlock value. self whileFalse: aBlock ].
	^ nil
```

**Comment by Ducasse** [comment]
In anycase it deserves tests

**Comment by MarcusDenker** [comment]
I think it can be deprecated, it is only used by one package.

**Comment by Ducasse** [comment]
My comment got lost.
In fact the flow of control is nice
we can express

```
	[ currentNode := stack pop.
	currentNode popped.
	stronglyConnectedComponent add: currentNode ]
		doWhileFalse: [ currentNode = aTarjanNode ].
```

**Comment by Ducasse** [comment]
So we should discuss :)

**Comment by gcotelli** [comment]
The first version returns the result of evaluating the receiving block and evaluates the block at least once, so they are not exactly the same. How useful it is to have this variant is a discussion point :smile: .
One can simulate it by using a temp, so if there are few senders of `doWhileFalse:` we can try to search for code using the temp pattern and `whileFalse:` that can be replaced by using the other method.

**Comment by pavel-krivanek** [comment]
That would mean deprecation of `doWhileTrue:` too which is used much more.
