### ISSUE TITLE
[CI] Failing randomly: UDPSocketTest>>testUDPFaultySend

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#10467]
**Bug description**
 UDPSocketTest>>testUDPFaultySend failed with:

```
Error
Block evaluation took more than the expected 0:00:00:00.02
```

This was on the mac in #10451

**Comment by svenvc** [comment]
Test seems OK.

Could be a slow CI, after all, less than 20ms does not give much room for slowdowns.

**Comment by MarcusDenker** [comment]
this seems to be fixed by https://github.com/pharo-project/pharo/issues/10538

(I re-open if I see it again)
