### ISSUE TITLE
Cleanup newlines and blanks in "Fuel" packages

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10483]
see #10396 and fix it for all "Fuel" related packages:

```Smalltalk
badCases := SystemNavigation default allMethodsSelect: [ :each | each sourceCode trimRight size ~= each sourceCode size ].

fixInPackage := badCases select: [:each | each package name beginsWith: 'Fuel' ].

fixInPackage do: [:each |
	| refactoring classOrTrait |
	classOrTrait := each traitSource ifNil: [ each methodClass ] ifNotNil: [ each traitSource innerClass ].
	refactoring := RBAddMethodChange compile: each sourceCode trimRight in: classOrTrait for: nil.				 
	refactoring execute	
]
```

**Comment by astares** [comment]
I doubt we can change that with a PR agains Pharo as "Fuel" is managed externally by @theseion

So I guess the way forward is to open a ticket for Fuel so @theseion can run the script and provide a new cleanup up release version to include:

https://github.com/theseion/Fuel/issues/258

**Comment by astares** [comment]
Mmhhh ... strange: Fuel source code seems to be part of Pharo source code. Did that change recently from being managed externally (in "thesion/Fuel" repo) to internally (in "pharo-project/pharo" repo)?

![image](https://user-images.githubusercontent.com/5980033/143611175-eba3cfa1-b070-4e7c-935f-04ba69b10aa4.png)

I'm confused

**Comment by theseion** [comment]
No, it's been that way for a long time. Fuel is used by parts of the bootstrapping process (or something thereabouts) I believe and there are some internal dependencies, which is way it's part of the core code. It's technically still an external project.
