### ISSUE TITLE
Add rule for accessing/removing category

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10503]
Using "adding/removing" instead of "adding-removing" should be prefered

![image](https://user-images.githubusercontent.com/5980033/143656163-2af02b8b-4bd8-4828-8490-b3d90ecf7a9e.png)

we should provide a lint rule with an autofix

![image](https://user-images.githubusercontent.com/5980033/143656243-f0cc70c7-5888-4964-aaa0-5247d6dbf1ee.png)

![image](https://user-images.githubusercontent.com/5980033/143656265-be8506f6-6aea-4933-ad50-ec80df126a21.png)

**Comment by astares** [comment]
- also add a release test #testProperAddingRemovingProtocolIsUsedand 
- and fix the two remaining violating cases in ClyNotebookMorph und ClyNotebookPageMorph to unify and use "adding/removing" like all other

**Comment by guillep** [comment]
Hi @astares, we are discussing here with some of the guys and we would prefer to use adding-removing instead of adding/removing. So we vouch for:

- adding-removing
- adding-removing protocols
- adding-removing methods
- adding-removing users

**Comment by astares** [comment]
@guillep No problem. It's fine for me as long as we then convert the existing cases (to be homogenous and consistent) over the provided Pharo image.

If "adding-removing" is preferred then 
 - we can close this issue here as well as corresponding PR #10504 
 - we should followup in https://github.com/pharo-project/pharo/issues/10621 (which is fixed with PR #10622) and 
 - but be aware that we need to fix then the cases also in externally managed: Roassal, Spec2 and NewTools

**Comment by guillep** [comment]
Sure! I think that goes in a good direction.
