### ISSUE TITLE
Pharo 9+ unresponsive with large Roassal diagram open

### ISSUE THREAD

**Issue by JanBliznicenko** [guillep/pharo-core#10515]
**Bug description**
When large Roassal 2 or 3 diagram is open, Pharo 8 is a little slow, but overall responsive and usable. Pharo 9 and 10 is WAY more unresponsive - processing mouse actions like dragging sometimes takes over 10 seconds.

**To Reproduce**
1. Take two images: Clean Pharo 8 one and 9 (or 10) one. In both, do following:
2. Load Roassal2:
```
SystemVersion current major = 10 ifTrue: [ Object subclass: #ComposableModel
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Spec-Deprecated-Obsolete'.
].

Metacello new
    baseline: 'Roassal2';
    repository: 'github://ObjectProfile/Roassal2:bb7c95e/src';
    load: 'NoGlamour'.
```
3. Open large Roassal diagram:
```
v := RTView new.

1 to: 20000 do: [ :i | b1 := b2. b2 := RTBox new element. b2 translateTo: (i*5)@(i*5). v add: b2. b1 ifNotNil: [v add: ( RTLine edgeFrom: b1 to: b2 )] ].

v @ RTDraggableView.

v open.
```
4. Use mouse drag to move the canvas around for ~3 seconds (keep one long dragging in circles for 3 seconds)

**Issue**
In Pharo 8, it is quite slow (like 2-5 FPS), but usable.
In Pharo 9 and 10, it usually does not update anything during the dragging itself and after you let go of the mouse (end the drag) it either does nothing or does the action after 5-15 seconds.

I originally thought it might be Roassal bug, but the difference is in Pharo version, so I put it here, because I presume it is more about something like graphics library, mouse event processing, VM...? Or maybe not, IDK :)

OS: Tested on Windows and Linux

**Comment by Ducasse** [comment]
Hi jan 
can you open an issue on the roassal project and link this one there because it means that roassal developers should have a look. 

S

**Comment by Ducasse** [comment]
@akevalion

**Comment by JanBliznicenko** [comment]
I can move the issue there, I am just not sure it actually is fault of Roassal2, that's why I put it here.

Also, something similar happens in latest Roassal3 (last commit in master).
```
c := RSCanvas new.
1 to: 100000 do: [ :i | 
	b1 := b2.
	b2 := RSBox new
		position: (i * 5) @ (i * 5);
		@ RSDraggable;
		yourself.
	c add: b2.
	b1 ifNotNil: [ c add:
		(RSLine new
			from: b1;
			to: b2;
			yourself) ] ].

c @ RSDraggableCanvasInteraction.
c @ RSZoomableCanvasInteraction.
c open
```
Then try to zoom in once with scroll wheel. It happens in ~1 second in Pharo 8, but it completely freezes Pharo 9 image for 10-15 seconds before it happens.

**Comment by Ducasse** [comment]
So Milton should check and we will see if this is our problem.

**Comment by akevalion** [comment]
Hi I will check this issue with roassal2 and roassal3 in pharo9 and pharo10

**Comment by Ducasse** [comment]
Thanks milton let us know if we have a problem from our side.

**Comment by JanBliznicenko** [comment]
@akevalion Hello, thank you for looking into the problem. Any news regarding that? It is impairing OpenPonk quite severly (unable to work with larger diagrams since moving to Pharo 9)

**Comment by akevalion** [comment]
Hello @JanBliznicenko  for the moment I could not find the solution for this problem, maybe is related to SDL, because pharo9 use it but pharo 8 not.
But this is only a guest

**Comment by JanBliznicenko** [comment]
@akevalion @Ducasse I see, I will revert OpenPonk back to Pharo 8 until resolved

**Comment by guillep** [comment]
Hi all, probably @akevalion can confirm, I think the issue happens because from Pharo version 9 on we use SDL, and we have much more events than before. I believe this is a roassal issue that tries to do some work on each event. Either roassal should ignore some events, or optimise its work. I'll close it for now.
