### ISSUE TITLE
[CI] Failing randomly: StPlaygroundPageTest>>testContents

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#10519]
**Bug description**
StPlaygroundPageTest>>testContents sometimes fails randomly:

```
Error
Got '' instead of 'test 2'.
Stacktrace
TestFailure
Got '' instead of 'test 2'.
StPlaygroundPageTest(TestAsserter)>>assert:description:resumable:
StPlaygroundPageTest(TestAsserter)>>assert:description:
StPlaygroundPageTest(TestAsserter)>>assert:equals:

StPlaygroundPageTest(TestCase)>>performTest
```

seen on win  #10504

**Comment by maxwills** [comment]
I created a PR for this issue here: https://github.com/pharo-spec/NewTools/pull/318
I have a question though. When contributing, should I create the pull request targeting Pharo9.0 or Pharo10 branch?

**Comment by MarcusDenker** [comment]
PR was merged upstream
