### ISSUE TITLE
Cleanup newlines and blanks in "LibGit" packages

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10542]
see #10396 and fix it for all "LibGit" related packages:

```Smalltalk
badCases := SystemNavigation default allMethodsSelect: [ :each | each sourceCode trimRight size ~= each sourceCode size ].

fixInPackage := badCases select: [:each | each package name beginsWith: 'LibGit' ].

fixInPackage do: [:each |
	| refactoring classOrTrait |
	classOrTrait := each traitSource ifNil: [ each methodClass ] ifNotNil: [ each traitSource innerClass ].
	refactoring := RBAddMethodChange compile: each sourceCode trimRight in: classOrTrait for: nil.				 
	refactoring execute	
]
```

**Comment by astares** [comment]
We need to fix that in https://github.com/pharo-vcs/libgit2-pharo-bindings repository

<blockquote><img src="https://opengraph.githubassets.com/aea29eda97254bb698cea9b72dd28159707a9d58400806bf52a2939c0eaf5d3a/pharo-vcs/libgit2-pharo-bindings" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-vcs/libgit2-pharo-bindings">GitHub - pharo-vcs/libgit2-pharo-bindings: libgit2 bindings for Pharo</a></strong></div><div>libgit2 bindings for Pharo. Contribute to pharo-vcs/libgit2-pharo-bindings development by creating an account on GitHub.</div></blockquote>

**Comment by astares** [comment]
@tesonep, @estebanlm: If possible someone needs to double check and merge https://github.com/pharo-vcs/libgit2-pharo-bindings/pull/58 to fix https://github.com/pharo-project/pharo/issues/10542

Thanks in advance!

**Comment by tesonep** [comment]
I have integrated the changes in libGit. Thanks a lot for the PR.
