### ISSUE TITLE
iceberg commit window is cutting "commit" button

### ISSUE THREAD

**Issue by estebanlm** [guillep/pharo-core#10559]
**Bug description**
When you open a commit window and the active branch is other than "master" (or other small name), the window contents is larger than the window size, pushing the button out (and giving a bad look and feel).

**To Reproduce**
1. Create a pharo branch bigger than master (e.g. "issue-X-iceberg-commit-window-is-cutting-commit-button").
2. make a random change and open commit window

**Expected behavior**
Contents should be arranged taking into account the window size (and in the case of the branch size, it should be cut to a maximum of chars to allow regular size to be shown).

**Screenshots**
![image](https://user-images.githubusercontent.com/513630/144191789-9e5bd95b-f5d8-4290-81e7-2e5ca4cf0247.png)

**Comment by guillep** [comment]
Maybe we should add an ellipsis for now to limit the size of the branch label?
Something like `issue-X-iceberg-...mmit-button`

**Comment by estebanlm** [comment]
yep, that's what was thinking on.

**Comment by kasperosterbye** [comment]
This has a very simple solution I am ashamed not to have seen before - place the Commit button to the left.
<img width="583" alt="image" src="https://user-images.githubusercontent.com/17723745/202492847-0b1d756a-8943-4c84-9e4b-2f86d73e197e.png">

Code change in `IceTipCommentPanel>>#intializePresenters` by adding `placeAtStart`:
```smalltalk
actionButtonBar := self newButtonBar.
	actionButtonBar placeAtStart; add: (commitButton := sel...
```
The issue already exist in Icebert repository: https://github.com/pharo-vcs/iceberg/issues/1571

**Comment by kasperosterbye** [comment]
There is a PR on the iceberg repo (https://github.com/pharo-vcs/iceberg/pull/1627)

**Comment by MarcusDenker** [comment]
This is now fixed
