### ISSUE TITLE
Cleanup: Fix single "access" -> "accessing" for method category

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10619]
There is a single case to use "access" as category name instead of accessing:

![image](https://user-images.githubusercontent.com/5980033/145118520-7c514add-bdba-4886-baa1-f035834b2328.png)

![image](https://user-images.githubusercontent.com/5980033/145118620-a93330a6-de72-4d22-af31-756693cf93fd.png)

**Comment by astares** [comment]
We should not only fix that single case in MicInlineParserTest but we should also add "access" as a negative example into ReProperMethodProtocolNameForAccessingRule to get:

![image](https://user-images.githubusercontent.com/5980033/145119374-eeebaa35-d593-4be4-9f92-eaf0a8863bf2.png)

**Comment by astares** [comment]
First part need to be fixed by merging https://github.com/pillar-markup/Microdown/pull/316

**Comment by MarcusDenker** [comment]
This is now fixed: no "access" category suggested anymore (and the upstream PR was merged)
