### ISSUE TITLE
Add visitPragmasNodes: as we have visitTemporaryNodes:

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#10612]
```
visitMethodNode: aMethodNode
	self visitArgumentNodes: aMethodNode arguments.
	aMethodNode pragmas do: [ :each | self visitNode: each ].
	self visitNode: aMethodNode body
```

what about 

```
visitMethodNode: aMethodNode
	self visitArgumentNodes: aMethodNode arguments.
	aMethodNode pragmas do: [ :each | self visitPragmaNode: each ].
	self visitNode: aMethodNode body
```

**Comment by Ducasse** [comment]
I would like to discuss this point.

**Comment by guillep** [comment]
Isn't visitNode the starting point of a double dispatch that will call
visitPragmaNode?

**Comment by Ducasse** [comment]
I do not know. Do you imply that using visitPragmaNode: we would have a loop?

**Comment by Ducasse** [comment]
```
visitNode: aNode
	^ aNode acceptVisitor: self
```

Now I can understand it for case like 

```
visitReturnNode: aReturnNode
	^ self visitNode: aReturnNode value
```
because the value is any node. 
But in case we know that a pragmas are pragmaNode.

**Comment by Ducasse** [comment]
This is the same idea than

```
visitSequenceNode: aSequenceNode
	self visitTemporaryNodes: aSequenceNode temporaries.
	aSequenceNode statements do: [ :each | self visitNode: each ]
```

we could have 

```
visitSequenceNode: aSequenceNode
	aSequenceNode temporaries do: [ :each | self visitNode: each ].
	aSequenceNode statements do: [ :each | self visitNode: each ]
```

But when we override visitNode: and want to treat temps we will have find a way to identify them as such

**Comment by MarcusDenker** [comment]
For cases like that, where it is clear what the structure is fixed, yes, I think we can just call #visitPragmaNode:

the visitTemporaryNodes: is different: here we add another method that one can override. For the pragmas this would mean
adding #visitPragmasNode:, a method that would be called *once* even if there are multiple pragmas.

**Comment by Ducasse** [comment]
Ok we should discuss more. :) Guille tried to tell me something but I need a black board in front of me

**Comment by Ducasse** [comment]
Now I got it :)
I will write that in the next lectures :)

**Comment by MarcusDenker** [comment]
So I guess we can close this?

**Comment by Ducasse** [comment]
Keep it so that we add it or not.

**Comment by MarcusDenker** [comment]
I changed the title to make clearer what the result of the discussion was:

It would be nice to have a method in the visitor that gets called *once* for all pragmas, just as we have already #visitTemporaryNodes: that get called once for all definitions of temps.

This is for Pharo11

**Comment by jecisc** [comment]
I think P11 is too late for that
