### ISSUE TITLE
iceberg throws a DNU #definitions when checking out a different version of Spec 

### ISSUE THREAD

**Issue by estebanlm** [guillep/pharo-core#10623]
**Bug description**

**To Reproduce**
1. Add a location to pharo-spec
2. repair the repository by selecting "discard image changes and load repository version".

For the moment I workarounded the issue by implementing: 
```Smalltalk
MCPackageLoader >> definitions [
	
	^ MCDefinitionIndex definitions: #()
]
``` 
and seems to be working but I cannot be sure this is the intended behavior.

**Expected behavior**
It should not raise a DNU

**Stack trace**

MCPackageLoader(Object)>>doesNotUnderstand: #definitions
IceClassDefinition>>removeFromPatcher:
IceMCSnapshotPatchVisitor>>visitRemoval:
IceRemoval>>accept:
[ 
		anIceNode value accept: self ] in IceMCSnapshotPatchVisitor(IceTreeVisitor)>>visitTreeNode: in Block: [ ...
FullBlockClosure(BlockClosure)>>ensure:
IceMCSnapshotPatchVisitor(IceTreeVisitor)>>withNode:do:
IceMCSnapshotPatchVisitor(IceTreeVisitor)>>visitTreeNode:
IceNode>>accept:
[ :each | each accept: self ] in IceMCSnapshotPatchVisitor(IceTreeVisitor)>>visitChildrenOf: in Block: [ :each | each accept: self ]
Array(SequenceableCollection)>>do:
IceNode(IceAbstractNode)>>childrenDo:
IceMCSnapshotPatchVisitor(IceTreeVisitor)>>visitChildrenOf:
IceMCSnapshotPatchVisitor>>visitNoModification:
IceNoModification>>accept:
[ 
		anIceNode value accept: self ] in IceMCSnapshotPatchVisitor(IceTreeVisitor)>>visitTreeNode: in Block: [ ...
FullBlockClosure(BlockClosure)>>ensure:
IceMCSnapshotPatchVisitor(IceTreeVisitor)>>withNode:do:
IceMCSnapshotPatchVisitor(IceTreeVisitor)>>visitTreeNode:
IceNode>>accept:
IceWorkingCopyPatcherVisitor>>visitPackage:
IcePackageDefinition>>accept:
IceWorkingCopyPatcherVisitor>>visitNoModification:
IceNoModification>>accept:
[ 
		anIceNode value accept: self ] in IceWorkingCopyPatcherVisitor(IceTreeVisitor)>>visitTreeNode: in Block: [ ...
FullBlockClosure(BlockClosure)>>ensure:
IceWorkingCopyPatcherVisitor(IceTreeVisitor)>>withNode:do:
IceWorkingCopyPatcherVisitor(IceTreeVisitor)>>visitTreeNode:
IceNode>>accept:
[ :each | each accept: self ] in IceWorkingCopyPatcherVisitor(IceTreeVisitor)>>visitChildrenOf: in Block: [ :each | each accept: self ]

**Comment by MarcusDenker** [comment]
Seems to be the same as

- https://github.com/pharo-vcs/iceberg/issues/1528
- https://github.com/pharo-vcs/iceberg/issues/1561

**Comment by MarcusDenker** [comment]
IceWorkingCopyPatcherVisitor>>#visitPackage: explicitly hand over a loader as a patcher:

```
visitPackage: anIcePackageDefinition
	
	(self repository packageNamed: anIcePackageDefinition name) isLoaded
		ifFalse: [ ^ self ].
	
	currentNode accept: (IceMCSnapshotPatchVisitor new
		patcher: loader;
		yourself).
```

So it seems to be intended that it can play that role. (but I know nothing about this at all)

**Comment by chisandrei** [comment]
Would it be an option to also backport this to Pharo 9?

**Comment by MarcusDenker** [comment]
Backports do not need to be done by specific people... *you* can do PRs. *you* can review PRs...

**Comment by MarcusDenker** [comment]
So I think I will not spend my time to backport this... of course if someone does it, there is no problem to merge the change.
