### ISSUE TITLE
Cleanup: no fecal category names in Microdown

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10620]
Pharo10.0.0
Build information: Pharo-10.0.0+build.339.sha.dff582c56c004538749c3829cf17db5d6a030e4f (64 Bit)
--------------------------------------------------------------------------------------------------------------------------------------------------------------

Someone seems to have been in a "mood" to introduce bad method categories like:

![image](https://user-images.githubusercontent.com/5980033/145123567-83521e11-648e-4e48-a0da-7bcf92f77acc.png)
...
![image](https://user-images.githubusercontent.com/5980033/145123597-e82be584-4f4d-49ae-ad95-447dba6a36f8.png)

I would propose
- that we fix this by using a proper method category name
- that the person who introduced this should avoid such fecal words in the code of Pharo in the future and be more serious
   (it also shows that we do not follow the review process of contributions, I doubt someone would have approved this)

**Comment by guillep** [comment]
Thanks for looking into it, I'm sure this was a typo :^). We'll fix it soon.

**Comment by astares** [comment]
Side note:

A part of Microdown seems managed in Pharo (see https://github.com/pharo-project/pharo/tree/Pharo10/src)

![image](https://user-images.githubusercontent.com/5980033/145408125-beb995f4-4f74-4b6f-b4ae-a7b311ab8dfb.png)

and another part is managed externally in https://github.com/pillar-markup/Microdown

I'm pretty sure there are reasons to do it like that - but could be leading to side effects and is not obvious in the first place when one wants to fix such a typo.


<blockquote><img src="https://repository-images.githubusercontent.com/64123480/451beb80-d08b-11e9-9ade-21d166d787d9" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">pharo/src at Pharo10 · pharo-project/pharo</a></strong></div><div>Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk. - pharo/src at Pharo10 · pharo-project/pharo</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/9a49a757dac92020fc5d7bb43c57cbeeac3b76a42bc5771c6704fb27dd34cc9c/pillar-markup/Microdown" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pillar-markup/Microdown">GitHub - pillar-markup/Microdown: Microdown is a cleaned and simpler markdown but with more powerful features such as extensions.</a></strong></div><div>Microdown is a cleaned and simpler markdown but with more powerful features such as extensions. - GitHub - pillar-markup/Microdown: Microdown is a cleaned and simpler markdown but with more powerfu...</div></blockquote>

**Comment by Ducasse** [comment]
We clean it in Microdown.

**Comment by astares** [comment]
Thanks!
