### ISSUE TITLE
Double click on an item of the debugger stack could open the browser for this one method

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#10638]
**Describe the request**
Double clicking on an item of the list of the stack would open a browser to the method of the stack.
![image](https://user-images.githubusercontent.com/4706329/145609718-479bcf74-37c8-49e9-b98c-db0f50c89e75.png)

**Expected development cost**
Low

**Version information:**
 - OS: win10
 - Pharo Version Pharo 9.0.0
Build information: Pharo-9.0.0+build.1573.sha.0e09d756fc99383cbb498565200d9e5e9841ce11 (64 Bit)

**Additional context**
@Lifeware

**Comment by astares** [comment]
Double clicking (by accident or when Pharo is slow due to debugged action) when going through the list could easily let you end up in many windows, no?

Basically the functionality is already available in context menu directly:

![image](https://user-images.githubusercontent.com/5980033/145611852-d298d6a0-d0ab-42db-b0f7-1e159749ebf7.png)

**Comment by VincentBlondeau** [comment]
Then it is the slowness that should be fixed. The context menu is slow to reach. You have 2 clicks more and need to change the position of the mouse.
We have this feature in the VW image and it had never rose any issue.

**Comment by astares** [comment]
@VincentBlondeau I did not say it is slow. But you might be able to bring yourself into a situation with own code (also in VW) where UI gets slow in response.

BTW: 
- menu is defined in StDebuggerStackCommandTreeBuilder>>#stackContextNavigationCommands, 
- invocation happens in StDebugger>>#doBrowseClass
- the table showing the stack is created in StDebugger>>#initializeStack

**Comment by astares** [comment]
You have to modify StDebugger>>#initializeStack and add two more lines (see selected in screenshot):

```Smalltalk
initializeStack

	stackTable := self newTable.
	stackTable 
		activateOnDoubleClick;
		whenActivatedDo: [ :selection | self doBrowseClass ].
	stackTable
		addColumn: ((SpImageTableColumn
				  title: ''
        ...
```

![image](https://user-images.githubusercontent.com/5980033/145659192-4d2189ff-e986-4e62-aff9-5462267051c5.png)

But the change needs to be done in NewTools Project: https://github.com/pharo-spec/NewTools 

<blockquote><img src="https://opengraph.githubassets.com/4b80fd9f9007c6592a063c64493df09e0c2a1f15c23c1c79b186ba3c277258d6/pharo-spec/NewTools" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-spec/NewTools">GitHub - pharo-spec/NewTools: All development tools for Pharo, developed with Spec</a></strong></div><div>All development tools for Pharo, developed with Spec - GitHub - pharo-spec/NewTools: All development tools for Pharo, developed with Spec</div></blockquote>

**Comment by StevenCostiou** [comment]
I did a PR here https://github.com/pharo-spec/NewTools/pull/460
@astares Thank you for the proposition, I took it directly.
I think the feature should go through approval, but I find it nice.

**Comment by Ducasse** [comment]
Yes it is a good idea! Tx for implementing it.
