### ISSUE TITLE
Make class parser more robust

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#10642]
for example 

```
Object < #ImdbFilm
	slots: { #name };
       package: 'FFFoo'
```
raises an error because it is wrong. 
We should capture errors and later also do some validation.

**Comment by MarcusDenker** [comment]
As the browser compiles a Doit, you get a DNU as you would get it with a wrong ST80 style class definition.

The behavior when e.g. trying to get a menu for a definition like that is already good, no DNU.

I wonder what still needs to be done

**Comment by MarcusDenker** [comment]
I think it is good for now: I get exactly the same behavior then we see with the old class definition: you get a DNU
