### ISSUE TITLE
Cannot rename method in Pharo 10

### ISSUE THREAD

**Issue by jordanmontt** [guillep/pharo-core#10650]
When you try to rename a method in Pharo 10 is impossible to edit the name of the new method
![Capture d’écran 2021-12-13 à 14 09 47](https://user-images.githubusercontent.com/33934979/145818546-461d3f70-10e3-4dbf-a0ef-e9a75435f1d8.png)

For example in the picture I cannot change the name of the method (`maxErrorActual:expected:`) that I am trying to rename.

**Comment by MarcusDenker** [comment]
this looks similar to the issue fixed here: https://github.com/pharo-project/pharo/pull/10390

**Comment by jordanmontt** [comment]
Ah yes, my Pharo 10 image was old. I downloaded a new one and it's working now.
