### ISSUE TITLE
Remove ZnUrlCopy

### ISSUE THREAD

**Issue by svenvc** [guillep/pharo-core#10664]
The latest image contains ZnUrlCopy. I read the class comment.

This is horrible and incomplete as well.

More than a year ago https://github.com/svenvc/zinc/commit/7a42881f14144e0d9dcc2b3aa98a075f189eae69 added the preservation of URL query parameter order.

Of course, merging all of Zinc is hard because the many cosmetic changes that took place. I want to do it, but I can't do it alone.

The problem at hand can be fixed easily by changing the superclass of ZnMultiValueDictionary to OrderedDictionary. That's it.

Then ZnUrlCopy can be removed and the 2 users can revert back to ZnUrl.

I'll try to do a PR.

**Comment by Ducasse** [comment]
Sven this is part of an old version of Microdown. So I would not worry.

**Comment by svenvc** [comment]
OK then, but it should be fixed for the 10.0 release IMHO.

**Comment by MarcusDenker** [comment]
the class is gone
