### ISSUE TITLE
Installed breakpoints not shown in UI after AST cache reset during image saving

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#10667]
**Bug description**
If you have a modified (and saved) method and save the image, and, on image restart, you try to install the breakpoint, the breakpoint looks like installed (you may try to remove it in the context menu with cursor at the breakpoint position) but no indication of it (the red circle) is shown in the bar left of the editor. You need to modify and save the image again to be able to see the installed breakpoint.

The breakpoint is, in fact, not installed. The execution of the code will rise one. 

It clearly has something to do with the ASTCache reset during image saving because if you try to just do the cache reset without full image saving, the effect is the same.

**To Reproduce**
1. create or use some existing method
2. modify the method (like adding whitespace) and save it
3. save the image or perform `ASTCache reset`
4. move the text cursor to some reasonable position inside the method and install a breakpoint (from the context menu or by clicking on the left bar)
5. status bar will probably change, but the breakpoint will not be installed (but it can be "uninstalled" from the context menu)

![FkxtDeeEVm](https://user-images.githubusercontent.com/572494/146332811-98c71cc7-7d9e-42c2-9dac-424360058ed7.gif)

**Comment by MarcusDenker** [comment]
I will check! 

(and yes, the whole ASTCache stuff needs a rethinking...)

**Comment by pavel-krivanek** [comment]
I think that the problem is that the Calypso remembers the old AST nodes because if you jump to other method and back, installation works... 

I think that at that time, `sourceNode` in `ClyAddBreakpointCommand>>#execute` is obsolete

**Comment by MarcusDenker** [comment]
This seems to work (need to check it a bit more):

add method to ClyMethodCodeEditorToolMorph

```
triggerASTCacheReset
	"when the AST cache is cleared, we have to rescue the AST we are looking at"
	ASTCache default at: ast compiledMethod ifAbsentPut: ast

```

and a line to ClyMethodCodeEditorToolMorph>>#attachToSystem

```
SystemAnnouncer uniqueInstance when: ASTCacheReset send: #triggerASTCacheReset to: self
```
