### ISSUE TITLE
Iceberg's commit window has non-functional horizontal scroll bars

### ISSUE THREAD

**Issue by lopezca** [guillep/pharo-core#10666]
**Bug description**
When looking at a diff using iceberg's commit window, the horizontal scrollbar has incorrect bounds and does not allow for scrolling, therefore it's impossible to see the changes in long lines.

**To Reproduce**
1. Go to Iceberg
2. Click on: a repository where you'd like to do a commit.
3. Click on commit.
4. Select a change with a long line
5. Try to scroll horizontally to see the changes.

**Expected behavior**
Window should allow looking at all the code in the diff sections.

**Screenshots**
<img width="596" alt="image" src="https://user-images.githubusercontent.com/27969022/146285970-29b57e43-0e73-4f30-9386-000ddc7e4400.png">

**Version information:**
 - OS: Windows
 - Version: 10
 - Pharo Version:
    - Pharo-9.0.0+build.1573.sha.0e09d756fc99383cbb498565200d9e5e9841ce11 (64 Bit)

**Expected development cost**
🤷‍♂️

**Comment by bouraqadi** [comment]
Same with compare two commits. Scroll bars are either hidden or don't go far envough
<img width="1088" alt="Screenshot 2022-02-16 at 17 50 30" src="https://user-images.githubusercontent.com/435343/154315336-7db6bddd-4506-4d06-a798-f414abf55388.png">

**Comment by fmqa** [comment]
It seems like `RubAbstractTextArea` & friends do not offer any kind of "size to fit" method, causing issues like this. Devising a fix is not so easy, but can be done by performing a rudimentary implementation of this functionality:

```smalltalk
RubAbstractTextArea >> maxLineWidth [
	| w |
	w := 0.
	self string linesDo: [ :line | w := w max: (self font widthOfString: line) ].
	"check this later, not really sure about this calculation"
	^ w * 6 // 5
]
```

```smalltalk
RubAbstractTextArea >> handleEdit: editBlock [
	"Ensure that changed areas get suitably redrawn"

	editBlock value.
	"Fit to width on edit"
	(self grow isNotNil & self grow) ifTrue: [
		self width: (1 max: self maxLineWidth + self margins left + self margins right)
	].
	self selectionChanged	"Note new selection"
]
```

```smalltalk
RubAbstractTextArea >> grow

	^ grow
```

```smalltalk
RubAbstractTextArea >> grow: aBool

	grow := aBool
```

```smalltalk
RubScrolledTextMorph >> defaultScrollTarget
	| textArea |
	textArea := self textAreaClass new.
	textArea grow: true. "Ensure morph width tracks line width"
	textArea backgroundColor: Color lightGray veryMuchLighter.
	^ textArea
```

This might not be exactly the cleanest solution, but it does resolve the issue for the most part and makes viewing changesets in Iceberg (and Epicea) less tedious.
