### ISSUE TITLE
Completion results can accidentally contain Contexts

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#10672]
We got this bug completion bug:

![unknown](https://user-images.githubusercontent.com/572494/146796257-af63bf0b-2808-40d6-b314-f740e8ce8757.png)

It looks like completion results may contain Contexts besides regular method items. Maybe full closures related issue?

It was not possible to reproduce it.

Here it the results should be filled:
`CoNarrowHistoryItem class>>#forFetcher:results:hasFinished:`

and this is the standard results collection:
![Pharo_DA3TqkQS3q](https://user-images.githubusercontent.com/572494/146796059-ef98e96d-a970-4521-aa97-deee05d74b6d.png)

Quite big one :-)

**Comment by Ducasse** [comment]
Hi pavel 
we tried to fix it this afternoon and we could not really understand. 
We could get it when we defined a method in the debugger.

**Comment by pavel-krivanek** [comment]
nothing like that seen in wild in last months, closing
