### ISSUE TITLE
Step Over fails for leaving simple accessors

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#10678]
**Bug description**
When you step into a simple accessor method and the leave it using "step over", bad things happen.

**To Reproduce**
1. Load this simple class with one instance variable, accessor and a method with halt that calls the accessor
   [TstClass.zip](https://github.com/pharo-project/pharo/files/7793737/TstClass.zip)
2. call `TstClass new msg`
3. in the debugger, do two times "Into"
4. you are now in the `accessor` method, do "Over`
5. `PrimitiveFailed: primitive #objectAt: in CompiledMethod failed`

![image](https://user-images.githubusercontent.com/572494/147769977-fe4197b6-c266-4294-b82a-25d2c3aa5169.png)

**Version information:**
Pharo 10.0.0
Build information: Pharo-10.0.0+build.354.sha.37934d7c40480f096548689ab93d4cad88f0344b (64 Bit)

**Comment by MarcusDenker** [comment]
The bytecode it tries to decode is actually not a bytecode, but part of the trailer (the source pointer).

it seems that we are (correctly) at offset 28 (push ivar). Then the step executes #stepToFirstInterestingBytecodeIn:, which in turn executes #updatePCForQuickPrimitiveRestart. 

This now sets the PC to "PC +3" (the size of a quick method primitive). But that makes no sense here, as we are already past the execution of that primitive. We are in the code after (push ivar, method return).

If we would just run without the PC change, it would correctly execute the return bc and it would work.

If I un-comment the send of #updatePCForQuickPrimitiveRestart in #stepToFirstInterestingBytecodeIn:, the example works fine

**Comment by MarcusDenker** [comment]
But then #testUnwindAndRestartToQuickMethodContext fails, this seems to be from  #9185

**Comment by MarcusDenker** [comment]
I think we need to guard #updatePCForQuickPrimitiveRestart and only call it if we are at the start of the bytecode, as the primitive bc that it skips is always right at the beginning. The skip makes no sense if the PC is already further.

in #stepToFirstInterestingBytecodeIn: this means to check in addition for initialPC

```
(suspendedContext method isQuick and: [ suspendedContext pc ==  suspendedContext method initialPC ])
		ifTrue: [ ^ suspendedContext updatePCForQuickPrimitiveRestart ].
	

```

Debugger model tests are green and the bug is gone

**Comment by guillep** [comment]
That's odd.. `updatePCForQuickPrimitiveRestart` ' s name implies it is only being called for a restart. We should check its senders. And also, if that check is ok, maybe it makes sense to put it **inside** that method, right?

**Comment by MarcusDenker** [comment]
yes, I just put is there as the #isQuick check was there already.

And yes, I want to check a bit because that looks indeed odd...
