### ISSUE TITLE
ProfStef "broken" in light mode

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#10674]
Ubuntu 20.04.3

Pharo-9.0.0+build.1573

I am a noob just getting started with Pharo.

After tuning some System preferences (e.g. switching to Pharo Light theme, etc.) the lessons in “Learn Pharo” available from the “Welcome” window are near black and unreadable.

When I click on “Learn Pharo” the initial page is okay (black or blue type on a black background) but doing ‘ProfStef go.’ messages opens the next lesson where all text has such a black background it is unreadable. Doing ‘ProfStef next.’ or ‘ProfStef previous.’ on subsequent pages opens a new page similarly illegible.

I’ve searched through all the System prefs but can’t figure out which one affects the lesson pages.

Regards, Hedley

**Comment by Ducasse** [comment]
I checked on P10 and it is working. So probably we will close this issue.

**Comment by bsene** [comment]
Hello,
I checked it with P10 (on Ubuntu 20.04.3 LTS) and all works properly :)
