### ISSUE TITLE
Pressing cmd+m tries to access the senderes instead of the implementations in Pharo 10

### ISSUE THREAD

**Issue by jordanmontt** [guillep/pharo-core#10671]
![Capture d’écran 2021-12-20 à 16 00 22](https://user-images.githubusercontent.com/33934979/146787767-c9f3eb90-fd95-4929-a1d8-2b4fff0f55d2.png)

I the screenshot I am pressing `cmd+m` put but is showing me that are no senders.

On Mac, Pharo 10

**Comment by MarcusDenker** [comment]
maybe related to https://github.com/pharo-spec/Spec/issues/1180

**Comment by MarcusDenker** [comment]
Ah... I found it. *if* the debugger is opened from a Playground, it will end up defining a playground variable in 

browseSelectedSelectorIfGlobal:ifNotGlobal:

and thus it tries to browse that variable.

Solution: use lookupVar:define: false.


The real solution is that we *have* to remove the auto-define of vars in the playground, there is another issue tracker entry tofr that (but that is for Pharo11)

**Comment by MarcusDenker** [comment]
PR is here: https://github.com/pharo-spec/Spec/pull/1220
