### ISSUE TITLE
DNU in MessageTally>>#displayStringOn:

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#10673]
**Bug description**
`MessageTally>>#displayStringOn:` contains send of unimplemented method `displayIdentifierOn:`.

**To Reproduce**
1. evaluate `(MessageTally spyOn: [ self notNil ]) inspect`

**Comment by Ducasse** [comment]
In fact in P9 I do have 

```
MessageTally >> displayIdentifierOn: aStream
	class displayStringOn: aStream.
	self method methodClass ~~ class 
		ifTrue: [ aStream nextPut: $(; print: self method methodClass; nextPut: $) ].
	aStream 
		nextPutAll: '>>';
		store: self method selector
```

@Carohp so may be this is definition is enough?
