### ISSUE TITLE
Possibility to display sequence diagrams to visualize object interactions

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10699]
Remember the "Tell, Don't Ask" approach to OO design? See https://www.youtube.com/watch?v=cVAfjfikhzI

Class diagrams have already been added to Calypso using Roassal3. Maybe adding sequence diagrams (also visualized using Roassal3) would be a good idea too to more easily see the interactions of objects and spot possible problems and find ways to optmize object interactions and improve. 

It was already possible back then in Squeak:

![image](https://user-images.githubusercontent.com/5980033/148731292-0287c3e6-563c-43d6-92ed-dca8c4b7d08e.png)

@bergel @akevalion @estebanlm @MarcusDenker @Ducasse @guillep @tesonep @pavel-krivanek @massimo-nocentini 

Other references:
 - http://gsoc2010.esug.org/projects/uml-from-smalltalk
 - https://www.researchgate.net/figure/Integration-of-a-class-collaboration-chart-in-the-Squeak-Smalltalk-IDE_fig1_224342406

**Comment by astares** [comment]
See chapter 4.6 in:

https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.89.8425&rep=rep1&type=pdf

**Comment by kasperosterbye** [comment]
I have a PlantUML based version, it displays it in an external web-browser though (or inline as an image). It is possible to click the identifiers in the browser-diagram to view the code in Pharo (It has a Teapot server in Pharo to listen to the clicks in the browser).
I agree that it would be useful to have and Roassal3 is the way to do it.

The key problem to be solved is how to keep the size of the diagram under control if you implement
`[MyClass start] drawAsDiagram`
Suddenly you have a collection or a loop and you end up with a drawing with dozens of not interesting objects.

I have updated it (https://github.com/kasperosterbye/pharo-elucidator) to run under Pharo10. Examples on class side of `Elucidator`.

**Comment by guillep** [comment]
This issue looks more like a small project than an actionable issue.
I propose we move it to a wiki with potential projects for people to contribute.
I'm collecting all these.
Could be a great basis for GSOC.

**Comment by pavel-krivanek** [comment]
@massimo-nocentini is able to render the sequence diagrams. If you want to start such project, sync with him, please.
