### ISSUE TITLE
Text inspection breaks

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#10690]
**Bug description**
```smalltalk
'foo' asText inspect
```

produces `#- was sent to nil` and opens the debugger.

if the debugger is closed and the expression done again, it produces:

produces `#scaledValue was sent to nil`

**To Reproduce**
1. Open a playground
2. Enter the expression at top
3. Doit
4. Debugger comes up

**Expected behavior**
An inspector should open

**Version information:**
- Pharo10.0.0, build: 359, commit: 9a68076, date: 5 January 2022

**Comment by estebanlm** [comment]
it will be in next integration

**Comment by kasperosterbye** [comment]
I tried it the newest version of spec. It works, as do fonts. Thanks a lot @estebanlm.
