### ISSUE TITLE
Cmd+Browse raise a DNU

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#10695]
And now I have a reproducible case in latest Pharo10.

- Type a class name of a class that does not exist eg. Poin
- Cmd+Browse
- in the pop up list pick Point
- Boum

```
visitVariableNode: aVariableNode
	| var |	
	var := self resolveVariableNode: aVariableNode.
	var analyzeRead: aVariableNode by: self
```
analyzeRead: was sent to nil

**Comment by MarcusDenker** [comment]
Cmd-B is fundamentally broken: it compiles the selection in interactive mode. This is not a good idea...

see https://github.com/pharo-project/pharo/issues/9644

**Comment by MarcusDenker** [comment]
I will try to first do the workaround to compile in non-interactive mode. But compilation itself is just not a good idea

This e.g. leads to the fun thing that if you have a line

Smalltalk snapshot: true andQuit: true

and you out the cursor on "Smalltalk" 

->cmd-b quits the image (see https://github.com/pharo-project/pharo/issues/8515 )
