### ISSUE TITLE
Extract method refactoring is broken

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#10702]
**Bug description**

**To Reproduce**
1. Select some instructions to extract in a method
2. Click on Source  code / Extract Method
3. You will get  `Error: Instances of UndefinedObject are not indexable` 

**Expected behavior**
No error and extraction done

**Expected development cost**
It looks like SycMethodNameEditorPresenter class is not implemented correctly. The #initializeDialogWindow: method expect to find a current method name where there is no. Also, fixing this issue by avoiding nil valu for the title, the new methid name validation is broken and does not accept anything.

**Comment by demarey** [comment]
![Capture 2022-01-10 at 20 04 52](https://user-images.githubusercontent.com/2494203/148903726-334b25ff-020e-4edb-beab-85f1919ad5e5.png)

**Comment by MarcusDenker** [comment]
The PR #10713 fixed this issue
