### ISSUE TITLE
NewFile without different extensions

### ISSUE THREAD

**Issue by lgrangaud** [guillep/pharo-core#10714]
I would be great to be able to do 

```
/foo/bar.md asFileReference withExtension:'html'
>>>
/foo/bar.html
```

hints
(self parent / (self basenameWithoutExtension:'md'), '.html') asFileReference

**Comment by dionisiydk** [comment]
> I would be great to be able to do
> 
> ```
> /foo/bar.md asFileReference withExtension:'html'
> >>>
> /foo/bar.html
> ```

But #withExtension: already works this way. Do you mean something else?

**Comment by Ducasse** [comment]
Ok when I tried it did not but now I retried and it works. So I will migrate the tests to use it.

**Comment by dionisiydk** [comment]
Tests are there as well :) (see #testWithExtentionReplacesExtension)

чт, 13 янв. 2022 г. в 08:38, StéphaneDucasse ***@***.***>:
