### ISSUE TITLE
<cr> (and Modifier Keys) - No Keystrokes, Only KeyUp/Down

### ISSUE THREAD

**Issue by seandenigris** [guillep/pharo-core#10729]
**Bug description**
It seems there is a change in Morphic keyboard events sent due to keypresses between P8 and P9. Namely, <cr> presses do not result in `keystroke`s, only keyup/down. I discovered this because I was porting [PTerm](https://github.com/lxsang/PTerm) to P9 and <ENTER> was not working, but it works in P8. It turned out that PTerm was handling keystrokes (not keyup/down), and one never comes for <cr>

**To Reproduce**

1. Add logging statement as follows:
```smalltalk
sendFocusEvent: anEvent to: focusHolder clear: aBlock
    "Send the event to the morph currently holding the focus"
    | result w transformedEvent |
    "..."
    w becomeActiveDuring:[
        ((focusHolder isKindOf: TextMorph) and: [ (focusHolder contents beginsWith: 'hi') and: [ anEvent isKeyboard ] ]) ifTrue: [ 
            Transcript 
                "show: 'contents: ', focusHolder contents;"
                crShow: '; event: ', anEvent printString.
             ].
        result := focusHolder handleFocusEvent: transformedEvent.
    ].
    "..."
```
2. Open a TextMorph via:
```smalltalk
(TextMorph new contents: 'hi') openInWorld
```
3. Click to give the text morph focus at the end of the contents and type `s` and then `<ENTER>`.

**Expected behavior**
On P8 Transcript:
```
event: [keyDown '']
event: [keystroke 's']
event: [keyUp '']
event: [keyDown '']
event: [keystroke '<cr>']
event: [keyUp '']
```
On P9 Transcript:
```
event: [keyDown 's']
event: [keystroke 's']
event: [keyUp 's']
event: [keyDown '<cr>']
event: [keyUp '<cr>']
```

Observations: very cool that the key value has been fixed on key down and key up, but why no keystroke for <cr>?

________

Same i.e. no keystroke for other modifier keys on P9 (left then right; ttached as a picture because I was having problems copy/pasting). Shift keys also may not have the correct key value (or are not printing it). I wonder if this could be related to our problems with "stuck" modifier keys... cc @girba

<img width="384" alt="Screen_Shot_2022-01-13_at_11 44 29_AM" src="https://user-images.githubusercontent.com/184176/149534736-f32e1ece-03d6-43d1-aaa4-bf6ed932ae6a.png">

Here is what the shift keydown event looks like vs. cr:

![Screen_Shot_2022-01-13_at_11 48 35_AM](https://user-images.githubusercontent.com/184176/149534764-cfcb31ac-88ab-4c16-af89-a46a3e1b57b9.png)

**Version information:**
 - OS: macOS 12.0.1 on M1 Max (ARM)
 - Pharo Version: Pharo9.0.0 Build information: Pharo-9.0.0+build.1573.sha.0e09d756fc99383cbb498565200d9e5e9841ce11 (64 Bit)
 - VM: stable released on 1/13/21 - CoInterpreter * VMMaker-tonel.1 uuid: 3430c3a7-d791-0d00-a7a8-5685080601e8 Jan 13 2022
StackToRegisterMappingCogit * VMMaker-tonel.1 uuid: 3430c3a7-d791-0d00-a7a8-5685080601e8 Jan 13 2022
v9.0.11 - Commit: 0d043b74 - Date: 2022-01-13 10:51:48 +0100

Pharo 9.0.11 built on Jan 13 2022 13:36:53 Compiler: Apple LLVM 12.0.5 (clang-1205.0.22.9)
VMMaker versionString v9.0.11 - Commit: 0d043b74 - Date: 2022-01-13 10:51:48 +0100
CoInterpreter * VMMaker-tonel.1 uuid: 3430c3a7-d791-0d00-a7a8-5685080601e8 Jan 13 2022
StackToRegisterMappingCogit * VMMaker-tonel.1 uuid: 3430c3a7-d791-0d00-a7a8-5685080601e8 Jan 13 2022

**Expected development cost**
Not sure.

**Comment by guillep** [comment]
Hi Sean,

Indeed, this was changed last year (see https://github.com/pharo-project/pharo/pull/8156). The fact that non-printable keys and key combinations such as shortcuts were arriving as keystrokes was not ok (as in: no other UI toolkit does that). That added lot of complexity in the old VM that was transforming keyups/downs to strokes so morphic could keep alive without change.

Last year, when we moved to SDL and window management moved to the image side, all that crappy code was added to the image side. But it was producing problems with non english inputs (e.g., how to differentiate a german character inserted by doing ALT+o from a shortcut ALT+o?). The system already manages that, and using properly the events is the way to go.

Please, check the issue https://github.com/pharo-project/pharo/pull/8156 and its related issues.
I think your application should be updated to use keyup/press when it corresponds.

**Comment by seandenigris** [comment]
Thanks for the explanation and pointer, @guillep! I read the issue and it all makes sense for modifier keys, backspace, etc. 

However, I wonder if <cr> isn't different - doesn't it stand on its own (unlike modifiers) and have print equivalent (unlike backspace, but like a regular space). I know little about the domain, so if you're saying that <cr> does not emit a keystroke on most/all other platforms, I am good with that. I just wanted to make sure <cr> didn't get accidentally lumped in with the rest.

**Comment by guillep** [comment]
> Thanks for the explanation and pointer, @guillep! I read the issue and it all makes sense for modifier keys, backspace, etc.
> 
> However, I wonder if isn't different - doesn't it stand on its own (unlike modifiers) and have print equivalent (unlike backspace, but like a regular space). I know little about the domain, so if you're saying that does not emit a keystroke on most/all other platforms, I am good with that. I just wanted to make sure didn't get accidentally lumped in with the rest.

Actually, what we are doing right now, is just forwarding the events that SDL is sending us, no transformation in the middle as it was the case before.

CRs are managed on keydowns/ups. The fact that CR is also a control ascii character just dates from (ascii) and **old** dummy terminals :).

See some examples,
https://stackoverflow.com/questions/2752424/detecting-enter-keypress-on-vb-net
https://stackoverflow.com/questions/28927717/enter-handler-in-gwt

Also, think that many applications will use ENTER/RETURN keys as shortcuts and not as text (even for text inputs!!).

**Comment by seandenigris** [comment]
Okay, thanks again for talking me through this.
