### ISSUE TITLE
Porting WatchesWindow to Spec2 and remove Spec1 version

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#10720]
I added a first version of the migration I started.

**Comment by Ducasse** [comment]
[WatchesWindowPresenter.st.zip](https://github.com/pharo-project/pharo/files/7857229/WatchesWindowPresenter.st.zip)

**Comment by MarcusDenker** [comment]
merged https://github.com/pharo-project/pharo/pull/10761
