### ISSUE TITLE
Improve comments in Kernel package for better understanding object behavior

### ISSUE THREAD

**Issue by ErikOnBike** [guillep/pharo-core#10730]
**Describe the problem**
Some method comments in Object and Behavior are not fully accurate or reveal too much implementation detail. Especially newcomers might have difficulties understanding the true behavior of these methods.

For example `Object >> #respondsTo:` has as comment `"Answer whether the method dictionary of the receiver's class contains aSymbol as a message selector"`. This is implemented by calling a class side method `#canUnderstand:`. So comment refers to the implementation of another method which is being called. It is also inaccurate since the described implementation does not check for method presence in the class' method dictionary only, but possibly in superclasses as well.

**Classes and methods involved**
```Smalltalk
Object >> #respondsTo:
Behavior >> #canPerform:
Behavior >> #canUnderstand:
```

**Proposal**
See PR https://github.com/pharo-project/pharo/pull/10728

**Version information:**
 - Version: Pharo 8, 9, 10

**Comment by MarcusDenker** [comment]
merged
