### ISSUE TITLE
Expand should be bound to a shortcut

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#10747]
With the new fluid class parser you can expand a class definition.
For example image you have 

```
TestCase << #MicMicrodownTextualBuilderTest
	slots: { #factory . #parser . #builder };
	tag: 'Builder';
	package: 'Microdown-Tests'
```

and you want to add a pool
you can select MicMicrodownTextualBuilderTest
and bring the menu and show expand option.

You get 
```
TestCase << #MicMicrodownTextualBuilderTest
	layout: FixedLayout;
	traits: {};
	slots: { #factory . #parser . #builder };
	sharedVariables: {};
	sharedPools: { };
	tag: 'Builder';
	package: 'Microdown-Tests'
``` 
and you can edit it to add your Pool.

Now I would like to create a short cut to do the expansion automatically. 
I tried but I failed.

@dionisiydk I need you help :)
Could you help me. (BTW could you send me an email because I lost your email :(

**Comment by dionisiydk** [comment]
You have to annotate the expand command with a shortcut activation:
```Smalltalk
ClyExpandClassDefinitionCommand class>>sourceCodeShortcutActivation
   <classAnnotation>
   ^CmdShortcutActivation by: $j meta for: ClyClassDefinitionContext
```

**Comment by Ducasse** [comment]
Thanks I will try!!!

**Comment by Ducasse** [comment]
It works :).
I will do a PR.
