### ISSUE TITLE
Missing expandedClassDefinitionString for OldPharoClassDefinitionPrinter

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#10740]
This is strange but we lost it.
- Select a class in the class pane
- Select the class name in the definition
- Bring the menu and choose expand.
- It breaks.

**Comment by Ducasse** [comment]
Dnu was just calling the wrong method: it should be 

expandedDefinitionStringFor: aPrinter

	^ aPrinter expandedDefinitionString

and not 

expandedDefinitionStringFor: aPrinter

	^ aPrinter expandedClassDefinitionString

**Comment by Ducasse** [comment]
In fact this is not correct but this is not important for this issue. 
I will fix it in another one.

**Comment by MarcusDenker** [comment]
This is fixed, the method exists:

OldPharoClassDefinitionPrinter>>#expandedDefinitionString

**Comment by Ducasse** [comment]
In fact the method does not expand the definition but we decided not to do it :).
