### ISSUE TITLE
Breakpoints are not shown on debugger view

### ISSUE THREAD

**Issue by PalumboN** [guillep/pharo-core#10766]
When adding a breakpoint in a method on the system browser (windows at left) and then run a test, so the debugger stop on it, the breakpoint does not appear in debug view (windows at right).

![image](https://user-images.githubusercontent.com/4098184/150752219-d5cad1f2-c559-4c65-87c5-3d62b2dbd7f0.png)

**Comment by MarcusDenker** [comment]
We have a very old issue about that: https://github.com/pharo-project/pharo/issues/5211

**Comment by PalumboN** [comment]
Oohh ok, @carolahp I don't know if finally you are planning to do it, but maybe you want to change the issue in your project (CaroTooling) by the #5211 and close this as duplicated.
Sry for the noise!

**Comment by carolahp** [comment]
@PalumboN yes, I will work on it... Don't worry, I just changed the issue in CaroTooling and it took no time ;)

**Comment by MarcusDenker** [comment]
I close this as it is a duplicate
