### ISSUE TITLE
keyboard arrow key are not properly managed in Morphic

### ISSUE THREAD

**Issue by rvillemeur** [guillep/pharo-core#10764]
**Bug description**
The arrow key are not detected in Morphic (tested with with latest Pharo VM and Pharo 9 and 10). It works properly in Pharo 8. The arrow key are however properly managed within Pharo tools in Pharo 9 and 10 (e.g. I can move between method definition using arrow key in System Browser)

**To Reproduce**
1. Load or reproduce the CrossMorph example given in Pharo By Example book. The method to handle keystroke should be part of your code. in particular:
handleKeystroke: anEvent
| keyValue |
keyValue := anEvent keyValue.
keyValue = 30 "up arrow"
ifTrue: [self position: self position - (0 @ 1)].
keyValue = 31 "down arrow"
ifTrue: [self position: self position + (0 @ 1)].
keyValue = 29 "right arrow"
ifTrue: [self position: self position + (1 @ 0)].
keyValue = 28 "left arrow"
ifTrue: [self position: self position - (1 @ 0)]
2. Open the morph and put your mouse on it
3. Push your arrow key. The morph doesn't move. The keystroke is not even detected in the method. Other key (like $+ and $-) are correctly detected and handled.

**Expected behavior**
The arrow keystroke should be detected and the morph react accordingly to the code. The behavior is correct with Pharo 8 (Same code has been tested with Pharo 8, 9 and 10, the problem only appears in Pharo 9 and 10 with latest VM)

**Version information:**
 - OS: Windows
 - Version: 11
 - Pharo Version: 9 and 10, with latest VM (as of 18 of january 2022)

**Comment by guillep** [comment]
Hi,

This is not a bug, but a proper re-implementation of events.
I invite you to read the discussion in https://github.com/pharo-project/pharo/issues/10729.

**Comment by Ducasse** [comment]
Argh it means that probably we should revise the code of the Pharo by example 9 book. 
@rvillemeur if you have the solution in P10 please send it because I'm more than busy right now.

**Comment by rvillemeur** [comment]
@Ducasse working on it. Should I send a patch directly to PharoByExample9 repository ?

**Comment by rvillemeur** [comment]
@Ducasse I have a solution. Should I send a patch directly to PharoByExample9 morphic chapter ?

you have to split your method into 2:
One to handle character text:
```smalltalk
handleKeystroke: anEvent

	| keyValue |
	keyValue := anEvent keyCharacter.
	keyValue = $+ ifTrue: [ self startStepping ].
	keyValue = $- ifTrue: [ self stopStepping ]
```
One to handle shortcut (this include another example to handle ctrl shortcut)
```smalltalk
handleKeyDown: anEvent

	| keyValue |
	keyValue := anEvent keyCharacter.
	keyValue = Character arrowUp ifTrue: [ 
		self position: self position - (0 @ 10) ].
	keyValue = Character arrowDown ifTrue: [ 
		self position: self position + (0 @ 10) ].
	keyValue = Character arrowRight ifTrue: [ 
		self position: self position + (10 @ 0) ].
	keyValue = Character arrowLeft ifTrue: [ 
		self position: self position - (10 @ 0) ].

	anEvent controlKeyPressed ifTrue: [ 
		anEvent keyCharacter == $d ifTrue: [ 
			self position: self position + (0 @ 10) ] ]
```

**Comment by guillep** [comment]
> @Ducasse I have a solution. Should I send a patch directly to PharoByExample9 morphic chapter ?
> 
> you have to split your method into 2: One to handle character text:
> 
> ```smalltalk
> handleKeystroke: anEvent
> 
> 	| keyValue |
> 	keyValue := anEvent keyCharacter.
> 	keyValue = $+ ifTrue: [ self startStepping ].
> 	keyValue = $- ifTrue: [ self stopStepping ]
> ```
> 
> One to handle shortcut (this include another example to handle ctrl shortcut)
> 
> ```smalltalk
> handleKeyDown: anEvent
> 
> 	| keyValue |
> 	keyValue := anEvent keyCharacter.
> 	keyValue = Character arrowUp ifTrue: [ 
> 		self position: self position - (0 @ 10) ].
> 	keyValue = Character arrowDown ifTrue: [ 
> 		self position: self position + (0 @ 10) ].
> 	keyValue = Character arrowRight ifTrue: [ 
> 		self position: self position + (10 @ 0) ].
> 	keyValue = Character arrowLeft ifTrue: [ 
> 		self position: self position - (10 @ 0) ].
> 
> 	anEvent controlKeyPressed ifTrue: [ 
> 		anEvent keyCharacter == $d ifTrue: [ 
> 			self position: self position + (0 @ 10) ] ]
> ```

Yes, this solution goes in the right direction. If I may, a cleaner solution is to use key objects and not character objects (as not all keys have character representations!). Imagine you wanted to make a shortcut on backspace for example.

Events understand the `key` message, returning the pressed key object. Then you can use `KeyboardKey` instances to compare. For example,

```smalltalk
key := anEvent key.

key = KeyboardKey up ifTrue: [ ... ].

"	KeyboardKey down
	KeyboardKey left
	KeyboardKey right
	KeyboardKey D"
```
Check the KeyboardKey class side to see a list of supported keys
