### ISSUE TITLE
Missing name in a command

### ISSUE THREAD

**Issue by PalumboN** [guillep/pharo-core#10767]
When doing `command + T` on a variable (see `SycSourceCode...`) 

![image](https://user-images.githubusercontent.com/4098184/150108483-61ccd0be-5d6c-4bfd-ba50-33668138051b.png)

**Comment by MarcusDenker** [comment]
might be related to https://github.com/pharo-project/pharo/issues/9947

**Comment by PalumboN** [comment]
Yes, It's duplicated, closing this.
