### ISSUE TITLE
Failing on CI: ZnHTTPSTest>>testSNIPage: SSL Exception: connect failed [code:-5]

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#10760]
**Bug description**
ZnHTTPSTest>>testSNIPage started failing on the CI on all three platforms with:

SSL Exception: connect failed [code:-5]

*

**Comment by MarcusDenker** [comment]
The tests tries to load

https://www.mnot.net/blog/2014/05/09/if_you_can_read_this_youre_sniing

which is blocking even in a browser

**Comment by MarcusDenker** [comment]
The web page is now readable again in a browser, but the test still fails. I committed PR to, for now, skip it in the CI

**Comment by demarey** [comment]
@svenvc Do you know a URL we could use in the SSL SNI test? The current one is not anymore available

**Comment by svenvc** [comment]
I am now also skipping this test: https://github.com/svenvc/zinc/commit/aad0c509f68775c5d744dfd45618618e4c5e92ea

I see that server switched to HTTP/2 probably with much newer SSL, which no longer works.

All the tests in ZnHTTPSTest are high level functional tests, they are far from perfect. But all this indicates that we are regressing on compatibility at the TLS/SSL level, which is not good.
