### ISSUE TITLE
FTP client>>getDataInto, lost returned information

### ISSUE THREAD

**Issue by angelaclan** [guillep/pharo-core#10774]
#FTPClient
  >> getDataInto: dataStream

this method is activated with a WriteStream param.
it ends the method sending the message reset to the given WriteStream.

When we ask WriteStream to get its content, it copies the inside collection from
1 up to "position", which has been reseted.
Not sure what would be the good behaviour, if Writestream returning like it does now (but not resetting) or the other way around.
By the time being, the ftp client does not really work.

**Comment by riverdusty** [comment]
I believe this is the same problem I reported in the Discord.
Image attached as demonstration of consequences.
![Pharo_FTP_Bug](https://user-images.githubusercontent.com/572263/154267046-f7ebf123-41ef-434b-a2f5-5ec3005f2d12.png)

**Comment by Ducasse** [comment]
Thanks for the report. 
Could you try with P10?

**Comment by riverdusty** [comment]
> Thanks for the report. Could you try with P10?

![image](https://user-images.githubusercontent.com/572263/154469591-35c86fcc-c7da-4d35-81d5-d16af5cf47a8.png)
 

Exactly the same behaviour as 9.

**Comment by riverdusty** [comment]
Pharo 10 officially released. None of the FTP montecello repositories are working. FTP is still broken.

**Comment by MarcusDenker** [comment]
FTP is not used a lot anymore, mostly because it is unsecured. All Browsers have stopped supporting it, for example. I don't think there are a lot of users, as a FTP server for code would not be what people want to use.

(Just as a reason why nobody fixed this)

**Comment by riverdusty** [comment]
> FTP is not used a lot anymore, mostly because it is unsecured. All Browsers have stopped supporting it, for example. I don't think there are a lot of users, as a FTP server for code would not be what people want to use.
> 
> (Just as a reason why nobody fixed this)

This means that Montecello is broken (at least one aspect of it).
Also, we use it, simply because its quick and easy internally.
Also, how did it break in the first place? Surely there are regression tests to prevent that?
I can understand why nobody has fixed it. I can't understand how it got broken in the first place. For something that is 'not used a lot anymore' someone fiddled with it and broke it.

**Comment by riverdusty** [comment]
Also, fix is simple, just delete the reset line.

**Comment by MarcusDenker** [comment]
I somehow missed the description of the fix in the discussion before (it is a good idea to make descriptions of fixes extremely obvious...)

**Comment by MarcusDenker** [comment]
@riverdusty PR ready for review: https://github.com/pharo-project/pharo/pull/11466
