### ISSUE TITLE
Spotter crashes in Pharo 9

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#10780]
**Bug description**
I'm trying to migrate my projects to Pharo 9 but when I'm using Spotter I get crashes on this method:
Collection>>#spotterItemsFor:

It is calling another method that is not implemented in Pharo 9 but is in Pharo 10. 

It would be nice to backport this in Pharo 9 to avoid crashing the Spotter. 

**To Reproduce**

I open the spotter then click on the right arrow of the World section

**Version information:**
 - OS: Windows
 - Version: 11
 - Pharo Version 9

**Expected development cost**

Should be pretty straightforward since it works in P10

**Comment by jecisc** [comment]
It' just adding:

```st
Collection>>#collectionSizeThreshold 
	^ 3000
```

**Comment by Ducasse** [comment]
Tx cyril. 
I wonder why this is not crashing in my P9 version because I use it regularly.

**Comment by MarcusDenker** [comment]
PR merged
