### ISSUE TITLE
Pharo 9 vm fails at opening image on Mac OS 10.14

### ISSUE THREAD

**Issue by bocasti** [guillep/pharo-core#10788]
**Bug description**
I downloaded a pharo image and a pharo vm with these scripts:

curl get.pharo.org/64/90 | bash
curl get.pharo.org/64/vm90 | bash

Then I tried to open my image (as usually do)

./pharo-ui ./myimage.image

But the image wont open.
From what I see in the first messages, some vm plugins may have been built for mac os 10.15.
I was running 10.14. 
Here are some traces I got from the console:

download image
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3444  100  3444    0     0  10600      0 --:--:-- --:--:-- --:--:-- 10629
Downloading the latest 90 Image:
    http://files.pharo.org/get-files/90/pharoImage-x86_64.zip
overwrite Pharo9.0-64bit-6f28d0a.sources? (y/n [n]) not overwritten
remove old vm files
downlaod vm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5351  100  5351    0     0   131k      0 --:--:-- --:--:-- --:--:--  133k
Downloading the latest pharoVM:
	http://files.pharo.org/get-files/90/pharo-vm-Darwin-x86_64-stable.zip
pharo-vm/Pharo.app/Contents/MacOS/Pharo
Creating starter scripts pharo and pharo-ui
rename Pharo.image
open image and install
dyld: lazy symbol binding failed: Symbol not found: _objc_alloc_init
  Referenced from: /Users/cdelaunay/Work/repositories/active-grid/backend/pharo-vm/Pharo.app/Contents/MacOS/Plugins/libSDL2.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_alloc_init
  Referenced from: /Users/cdelaunay/Work/repositories/active-grid/backend/pharo-vm/Pharo.app/Contents/MacOS/Plugins/libSDL2.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

Abort trap: 6 Fri Jan 21 09:55:45 2022

/Users/cdelaunay/Work/repositories/active-grid/backend/pharo-vm/Pharo.app/Contents/MacOS/Pharo
PharoVM version:5.0-Pharo 9.0.11 built on Jan 13 2022 13:51:00 Compiler: 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.29) 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.29) [Production Spur 64-bit VM]
Built from: CoInterpreter * VMMaker-tonel.1 uuid: abd2fed7-d791-0d00-a7b9-52020f2acd2a Jan 13 2022
 With:StackToRegisterMappingCogit * VMMaker-tonel.1 uuid: abd2fed7-d791-0d00-a7b9-52020f2acd2a Jan 13 2022
 Revision: v9.0.11 - Commit: 0d043b74 - Date: 2022-01-13 10:51:48 +0100

C stack backtrace & registers:
	rax 0x0000000002000209 rbx 0x0000000000000000 rcx 0x00007ffee8143948 rdx 0x00007ffee8143db0
	rdi 0x0000000000000006 rsi 0x0000000000000006 rbp 0x00007ffee8143990 rsp 0x00007ffee8143948
	r8  0x00007ffee81439b0 r9  0x0000000000000000 r10 0x00000000000000ad r11 0x0000000000000246
	r12 0x00000000000000ad r13 0x00007ffee8143db0 r14 0x0000000000000004 r15 0x0000000000000006
	rip 0x000000010d23a436
*0   ???                                 0x000000010d23a436 0x0 + 4515406902
1   libPharoVMCore.dylib                0x0000000107b3db51 reportStackState + 305
2   libPharoVMCore.dylib                0x0000000107b3d9ee doReport + 190
3   libPharoVMCore.dylib                0x0000000107b3dd19 sigsegv + 25
4   libsystem_platform.dylib            0x00007fff61decb3d _sigtramp + 29
5   ???                                 0x000000010d25b8a8 0x0 + 4515543208
6   ???                                 0x000000010d239c5f 0x0 + 4515404895
7   ???                                 0x000000010d1f7aea 0x0 + 4515134186
8   ???                                 0x000000010d1f7c17 0x0 + 4515134487
9   libdyld.dylib                       0x00007fff61bedbde dyld_stub_binder + 282
10  libSDL2.dylib                       0x000000010ccf7640 _dyld_private + 0
11  libSDL2.dylib                       0x000000010cc878dc Cocoa_CreateDevice + 12
12  libSDL2.dylib                       0x000000010cc56525 SDL_VideoInit_REAL + 501
13  libSDL2.dylib                       0x000000010cb9c0dc SDL_InitSubSystem_REAL + 172
14  libffi.dylib                        0x0000000107c58665 ffi_call_unix64 + 85
15  ???                                 0x00007ffee8144d40 0x0 + 140732792065344
16  ???                                 0x0000000000000000 0x0 + 0

All Smalltalk process stacks (active first):
Process        0x112776fb8 priority 79
    0x7ffee814eae8 M TFSameThreadCall>executeOn:withArguments: 0x10de18380: a(n) TFSameThreadCall
    0x7ffee814eb28 M TFSameThreadRunner>invokeFunction:withArguments: 0x10dbee0f0: a(n) TFSameThreadRunner
    0x7ffee814eb78 M SDL2 class>initSubSystem: 0x10f4da850: a(n) SDL2 class
    0x7ffee814ebd0 M TFCalloutAPI(FFICalloutAPI)>function:library: 0x10de05f80: a(n) TFCalloutAPI
    0x7ffee814ec18 M SDL2 class(Object)>ffiCall:library:options:fixedArgumentCount: 0x10f4da850: a(n) SDL2 class
    0x7ffee814ec68 M SDL2 class(Object)>ffiCall:library:options: 0x10f4da850: a(n) SDL2 class
    0x7ffee814ecb0 M SDL2 class(Object)>ffiCall: 0x10f4da850: a(n) SDL2 class
    0x7ffee814ecf8 I SDL2 class>initSubSystem: 0x10f4da850: a(n) SDL2 class
    0x7ffee814ed40 I SDL2 class>initEverything 0x10f4da850: a(n) SDL2 class
    0x7ffee814ed80 I OSSDL2Driver>initialize 0x10dd9da20: a(n) OSSDL2Driver
    0x7ffee814edb0 M OSSDL2Driver class(Behavior)>new 0x10f4d4710: a(n) OSSDL2Driver class
    0x7ffee8148940 I OSWindowDriver class>current 0x10f4aa088: a(n) OSWindowDriver class
    0x7ffee8148980 I OSWorldRenderer>pickMostSuitableWindowDriver 0x10dd96620: a(n) OSWorldRenderer
    0x7ffee81489d0 I OSWorldRenderer>doActivate 0x10dd96620: a(n) OSWorldRenderer
    0x7ffee8148a10 I OSWorldRenderer(AbstractWorldRenderer)>activate 0x10dd96620: a(n) OSWorldRenderer
    0x7ffee8148a50 I WorldState>worldRenderer: 0x10edacf48: a(n) WorldState
    0x7ffee8148aa0 I MorphicUIManager>activate 0x10dd95860: a(n) MorphicUIManager
    0x7ffee8148ae8 I UIManager class>default: 0x10e8e6da0: a(n) UIManager class
    0x7ffee8148b20 M UIManagerSessionHandler>startup: 0x10ebe2ba8: a(n) UIManagerSessionHandler
    0x7ffee8148b60 M [] in WorkingSession>runStartup: 0x10d2d4000: a(n) WorkingSession
    0x7ffee8148ba8 M [] in WorkingSession>runList:do: 0x10d2d4000: a(n) WorkingSession
    0x7ffee8148bd8 M FullBlockClosure(BlockClosure)>on:do: 0x10dd94918: a(n) FullBlockClosure
    0x7ffee8148c20 M [] in WorkingSession>runList:do: 0x10d2d4000: a(n) WorkingSession
    0x7ffee8148c68 M Array(SequenceableCollection)>do: 0x10d2d7940: a(n) Array
    0x7ffee8148cb0 I WorkingSession>runList:do: 0x10d2d4000: a(n) WorkingSession
    0x7ffee8148d00 I WorkingSession>runStartup: 0x10d2d4000: a(n) WorkingSession
    0x7ffee8148d48 I WorkingSession>start: 0x10d2d4000: a(n) WorkingSession
    0x7ffee8148da0 I SessionManager>launchSnapshot:andQuit: 0x10e95e4d0: a(n) SessionManager
       0x112777ab8 s [] in SessionManager>snapshot:andQuit:
       0x112777da8 s [] in FullBlockClosure(BlockClosure)>newProcess

processes at priority 70
Process        0x10d9e80a8 priority 70
       0x10d9e7ff0 s [] in FullBlockClosure(BlockClosure)>newProcess

processes at priority 60
Process        0x10d2d40f8 priority 60
       0x10d2d80a0 s [] in FullBlockClosure(BlockClosure)>newProcess

processes at priority 50
Process        0x10daa13c0 priority 50
       0x10daa1308 s [] in FullBlockClosure(BlockClosure)>newProcess

processes at priority 40
Process        0x1117072b8 priority 40
       0x111710360 s MorphicRenderLoop>doOneCycleWhile:
       0x11170a3e0 s [] in MorphicUIManager>spawnNewProcess
       0x111706980 s [] in FullBlockClosure(BlockClosure)>newProcess

Process        0x1117071f8 priority 40
       0x1126e5b98 s Process>resume
       0x1127774b0 s FullBlockClosure(BlockClosure)>forkAt:
       0x1127779b8 s SessionManager>snapshot:andQuit:
       0x112777cc0 s [] in SmalltalkImage>snapshot:andQuit:
       0x112777e60 s CurrentExecutionEnvironment class>activate:for:
       0x112777f78 s DefaultExecutionEnvironment(ExecutionEnvironment)>beActiveDuring:
       0x1127781a0 s DefaultExecutionEnvironment class>beActiveDuring:
       0x112778030 s SmalltalkImage>snapshot:andQuit:
       0x112778258 s ImageCleanerCommandLineHandler>activate
       0x112778310 s ImageCleanerCommandLineHandler class(CommandLineHandler class)>activateWith:
       0x1127783c8 s [] in PharoCommandLineHandler(BasicCommandLineHandler)>activateSubCommand:
       0x112778480 s FullBlockClosure(BlockClosure)>on:do:
       0x1117076c8 s PharoCommandLineHandler(BasicCommandLineHandler)>activateSubCommand:
       0x1117077a0 s PharoCommandLineHandler(BasicCommandLineHandler)>handleSubcommand
       0x112777288 s PharoCommandLineHandler(BasicCommandLineHandler)>handleArgument:
       0x112777848 s [] in PharoCommandLineHandler(BasicCommandLineHandler)>activate
       0x112777c08 s FullBlockClosure(BlockClosure)>on:do:
       0x1117078b8 s [] in PharoCommandLineHandler(BasicCommandLineHandler)>activate
       0x111707998 s [] in FullBlockClosure(BlockClosure)>newProcess

processes at priority 10
Process        0x10d2d4148 priority 10
       0x10d2d8158 s [] in FullBlockClosure(BlockClosure)>newProcess

suspended processes
Process        0x111707308 priority 80
    0x7ffee814ad58 I DelayMicrosecondTicker>waitForUserSignalled:orExpired: 0x10ebd6ff8: a(n) DelayMicrosecondTicker
    0x7ffee814adb0 I [] in DelaySemaphoreScheduler>runBackendLoopAtTimingPriority 0x10ebd6480: a(n) DelaySemaphoreScheduler
       0x112777900 s FullBlockClosure(BlockClosure)>ensure:
       0x11170a2a0 s DelaySemaphoreScheduler(DelayBasicScheduler)>runBackendLoopAtTimingPriority
       0x1127771d0 s [] in DelaySemaphoreScheduler(DelayBasicScheduler)>startTimerEventLoopPriority:
       0x11170a1b0 s [] in FullBlockClosure(BlockClosure)>newProcess

Process        0x10edacff8 priority 60
       0x10edb5d88 s InputEventFetcher>waitForInput
       0x10edc0d78 s InputEventFetcher>eventLoop
       0x10edc50d0 s [] in InputEventFetcher>installEventLoop
       0x10edcaa80 s [] in BlockClosure>newProcess

Process        0x10fb143e0 priority 40
       0x10fb173d0 s AtomicSharedQueue>waitForNewItems
       0x10fb18d40 s AtomicSharedQueue>next
       0x10fb19738 s TKTWorkerProcess>privateNextTask
       0x10fb19ff0 s [] in TKTWorkerProcess>workerLoop
       0x10fb1a0a8 s BlockClosure>repeat
       0x10fb1a180 s TKTWorkerProcess>workerLoop
       0x10fb1a238 s MessageSend>value
       0x10fb1a2f0 s [] in TKTPharoProcessProvider>createProcessDoing:named:
       0x10fb1a3c8 s [] in BlockClosure>newProcess

Most recent primitives
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
class
wait
**StackOverflow**
basicNew:
basicNew:
signal
class
stringHash:initialHash:
stringHash:initialHash:
basicNew
stringHash:initialHash:
basicNew
stringHash:initialHash:
**StackOverflow**
class
class
stringHash:initialHash:
findSubstring:in:startingAt:matchTable:
indexOfAscii:inString:startingAt:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
findSubstring:in:startingAt:matchTable:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
compare:with:collated:
newMethod:header:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
objectAt:put:
objectAt:put:
objectAt:put:
objectAt:put:
objectAt:put:
objectAt:put:
objectAt:put:
objectAt:put:
objectAt:put:
stringHash:initialHash:
stringHash:initialHash:
objectAt:put:
basicNew:
instVarAt:
instVarAt:put:
instVarAt:
instVarAt:put:
objectAt:put:
basicNew:
instVarAt:
instVarAt:put:
instVarAt:
instVarAt:put:
objectAt:put:
flushCache
basicIdentityHash
basicIdentityHash
at:
new:
at:
at:
at:
at:
at:
basicIdentityHash
at:
basicIdentityHash
at:
at:
at:
basicIdentityHash
at:
new:
at:
at:
at:
at:
at:
at:
at:
at:
at:
at:
tempAt:
withArgs:executeMethod:
primFillType
primitiveByteSize
primDefineFunctionWith:returnType:
size
findFirstInString:inSet:startingAt:
primLoadSymbol:module:
invokeFunction:withArguments:
findNextUnwindContextUpTo:
terminateTo:
basicNew
basicNew
findSubstring:in:startingAt:matchTable:
basicNew
findSubstring:in:startingAt:matchTable:
class
basicIdentityHash
stringHash:initialHash:
compare:with:collated:
stringHash:initialHash:
compare:with:collated:
stringHash:initialHash:
compare:with:collated:
stringHash:initialHash:
compare:with:collated:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
**StackOverflow**
stringHash:initialHash:
stringHash:initialHash:
basicNew
**StackOverflow**
stringHash:initialHash:
compare:with:collated:
compare:with:collated:
compare:with:collated:
compare:with:collated:
compare:with:collated:
stringHash:initialHash:
compare:with:collated:
stringHash:initialHash:
**StackOverflow**
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
**StackOverflow**
stringHash:initialHash:
compare:with:collated:
stringHash:initialHash:
compare:with:collated:
compare:with:collated:
stringHash:initialHash:
compare:with:collated:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
basicNew
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
wait
**StackOverflow**
basicNew:
basicNew:
basicIdentityHash
basicIdentityHash
signal
stringHash:initialHash:
stringHash:initialHash:
shallowCopy
stringHash:initialHash:
stringHash:initialHash:
**StackOverflow**
stringHash:initialHash:
findSubstring:in:startingAt:matchTable:
indexOfAscii:inString:startingAt:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
findSubstring:in:startingAt:matchTable:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
stringHash:initialHash:
stringHash:initialHash:
stringHash:initialHash:
compare:with:collated:
newMethod:header:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
at:put:
objectAt:put:
objectAt:put:
objectAt:put:
objectAt:put:
objectAt:put:
objectAt:put:
objectAt:put:
objectAt:put:
objectAt:put:
stringHash:initialHash:
stringHash:initialHash:
objectAt:put:
basicNew:
instVarAt:
instVarAt:put:
instVarAt:
instVarAt:put:
objectAt:put:
basicNew:
instVarAt:
instVarAt:put:
instVarAt:
instVarAt:put:
objectAt:put:
flushCache
basicIdentityHash
at:
at:
at:
~=
=
tempAt:
withArgs:executeMethod:
primDefineFunctionWith:returnType:
findFirstInString:inSet:startingAt:
primLoadSymbol:module:
invokeFunction:withArguments:

stack page bytes 8192 available headroom 5576 minimum unused headroom 6032

	(Abort trap: 6)

**Comment by MarcusDenker** [comment]
Can you try in a newer version and report? 

I did run Pharo9 on MacOS 14.1.1 with no problem
