### ISSUE TITLE
ZeroConf broken for ARM VM

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10804]
I use a Raspberry pi with a fresh "Raspberry Pi OS" installation and try to install Pharo using

```sh
curl https://get.pharo.org | bash
```
but I get an error:

![image](https://user-images.githubusercontent.com/5980033/150982244-cc3ebea0-f454-487a-a736-71720e4c1f1a.png)

**Comment by astares** [comment]
I guess it is broken as there is no "pharoImage-armv**6**l.zip" - but already a newer "pharoImage-armv**7**l.zip 

![image](https://user-images.githubusercontent.com/5980033/150982308-33e4c6f6-e6fe-4bbd-a8a0-f8c03b1318a5.png)


So I guess ZeroConf requires some adoptions to use the "7" instead of the "6" VM

**Comment by guillep** [comment]
I migrated the issue to the VM repo
