### ISSUE TITLE
Calypso browser does not resize correctly

### ISSUE THREAD

**Issue by carolahp** [guillep/pharo-core#10827]
**Bug description**
When resizing under a certain width, the right most positioned buttons disappear.
Also the source code does not wrap correctluy

**To Reproduce**
Browse a method with long lines in calypso and shrink its width as much as possible, see buttons disappear

**Comment by carolahp** [comment]
Solved in [PR](https://github.com/pharo-project/pharo/pull/10838)

**Comment by MarcusDenker** [comment]
PR was merged
