### ISSUE TITLE
SpDialogWindowPresenter DNU #modalRelativeTo: 

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#10831]
- using Pharo9 without having SSH credentials for GitHub defined
- forked PharoJS into an own repo under my user on GitHub and used the Metacello load script to load from my own fork

![image](https://user-images.githubusercontent.com/5980033/151835308-45c8f013-8312-4aea-9fdd-2e6a2fc1c22f.png)

**Comment by astares** [comment]
I guess this is when system opens this dialog:

![image](https://user-images.githubusercontent.com/5980033/151835546-87fc3892-c917-4e5b-873b-68e4817a9f61.png)

**Comment by astares** [comment]
Also when cancel is hit on that dialog it stops LGitNoCredentialsProvided exception:

![image](https://user-images.githubusercontent.com/5980033/151835735-cbe3cb7c-bcf8-46f9-bb86-2003805aa908.png)

**Comment by astares** [comment]
I'm not sure it is a Spec or Iceberg issue - that why I open it here. I do not want to give SSH in that case - I have a token (as password replacement) from GitHub.

**Comment by MarcusDenker** [comment]
#modalRelativeTo: has no implementors and just this one sender

**Comment by MarcusDenker** [comment]
See issue on iceberg issue tracker https://github.com/pharo-vcs/iceberg/issues/1555 (just so we remember to close both when it is fixed)

**Comment by MarcusDenker** [comment]
This is fixed as there is no sender of modalRelativeTo:  anymore
