### ISSUE TITLE
Cleanup Behavior>>#protocols should return a Protocol, not symbol

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#10856]
**Describe the problem**
Ring adds an extension method Behavior>>#protocols which has some problems:

- it sends a message not implemented in Behavior, it should be moved to ClassDestriptiom
- it should not be in the Ring package (it is used a lot everywhere)
- it is not good that it returns a category symbol... on the organizer is implemented to return a *Protocol* object instead.

**Classes involved**
Behavior

```
protocols
	
	^ self organization categories copy
```

ClassOrganization

```
protocols 
	^ self protocolOrganizer protocols.

categories
	^ self protocolOrganizer protocolsNames
```

**Proposal**
make sure the API is unified.

**Comment by jecisc** [comment]
Not for P11 I think
