### ISSUE TITLE
 RoassalSpecTest>>#testBasic calls deprecated method

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#10869]
**Describe the problem**

```
DeprecationPerformedNotification: Automatic deprecation code rewrite: The method SpAbstractPresenter>>#openWithSpec called from RoassalSpecTest>>#testBasic has been deprecated. Please use #open instead
```

**Comment by MarcusDenker** [comment]
@akevalion

**Comment by akevalion** [comment]
Hello this should be fixed in last version. But maybe not loaded because by roassal3 baseline. Currently I am uploading a new PR to solve this issue and the baseline issue.

https://github.com/pharo-project/pharo/pull/10819
