### ISSUE TITLE
Debugger hightlights the wrong line in test for asserts inside two identical blocks

### ISSUE THREAD

**Issue by bouraqadi** [guillep/pharo-core#10860]
**Bug description**
Debgger highlights the first line that has the same code as the one where it is actually halted. This is happens only when assertion is tested inside a block

**To Reproduce**
Run the following tests
```st
1) testWrongHeightlightWithCollections

2)	| array |
3)	array := { 0. 0. 0 }.
4)	array do: [ :each | self assert: each equals: 0 ].
5)	array at: 2 put: 1.
6)	array do: [ :each | self assert: each equals: 0 ]
```

``` st
testWrongHeightlightSingleValue

	| value |
	value := 0.
	10 timesRepeat: [self assert: value equals: 0].
	value := 1.
	10 timesRepeat: [self assert: value equals: 0].
```

```

**Expected behavior**
In both tests, the debugger should highlight  line 6, but instead it highlights line 4.
Very weird. It took me a lot of time to figure it out.

**Version information:**
 - OS: MacOs 
 - Version: 12.1
 - Pharo Version 9

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 
In addition, are you willing to help because after all Pharo is yours too?

**Additional context**
Add any other context about the problem here.

**Comment by StevenCostiou** [comment]
I have seen that before, I thought it was fixed (or not?).
I think the problem is that the code lines are represented by two ASTs that are equal, because they represent two "equal codes". And then, somehow, the first AST that corresponds is selected in the tree when looking for the node to highlight, even if we just executed another equal AST.
It becomes super confusing in the debugger.

Possible sources I can think about (which I cannot check at this hour):
- AST mapping, when it stores mappings into a dictionary (where it might compares equal nodes)?
- Code editor, at the morph level, when it looks for the source code to highlight (where it might compare two equal strings)?

**Comment by MarcusDenker** [comment]
Ah, yes, this has to do with equality.  We right now even do not compile two CompiledBlock objects.
(they are stored in the literal frame and #literalEqual: falls back to equality).

**Comment by MarcusDenker** [comment]
Some more analysis:

1) we store blocks only once that are #literalEqual:

But even fixing that (#literalEqual: should return false always), we have another problem.

2) CompiledBlock>>#pcInOuter returns the first block where we get true for:
EncoderForSistaV1 class>>#isCreateFullBlock:code:at:, but this check the block, it ignores the PC, thus it finds the first block even if there are two.

**Comment by MarcusDenker** [comment]
I added  https://github.com/pharo-project/pharo/issues/10889 as a first step

**Comment by MarcusDenker** [comment]
It seems that as soon as we store both compiledBlocks, changing the comparison in #isCreateFullBlock:code:at:  to use #== solves the problem.

**Comment by MarcusDenker** [comment]
Here is a test:

```
testPcInOuter
	| methodToTest compiledBlocks |
	methodToTest := self class compiler compile: 'testWrongHeightlightSingleValue

	| value |
	value := 0.
	10 timesRepeat: [self assert: value equals: 0].
	value := 1.
	10 timesRepeat: [self assert: value equals: 0].'.
	
	compiledBlocks := methodToTest literals select: [ :each | each isCompiledBlock ].
	self assert: compiledBlocks size equals: 2.
	"we should find different pcs for the blocks in the outer method"
	self deny: compiledBlocks first pcInOuter equals: compiledBlocks second pcInOuter

```
