### ISSUE TITLE
equal CompiledBlocks in the literal frame stored only once

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#10889]
**Bug description**
We store only those objects in the literal frame that are not already #literalEqual: to another object there.

Now this leads to an interesting over-optimization in the case of CompiledBlocks: if there are two blocks that are #=, we store
only one CompiledBlock.

At first, this looks like a nice memory optimization. From a pure execution point of view, this is even true. But it leads to problems for mapping execution to the AST and thus e.g. text highlights in the debugger.

**Proposal** 
implement in CompiledCode

```
literalEqual: other
	^false
```

With a nice comment describing why this is a good idea.

**Comment by dionisiydk** [comment]
> implement in CompiledCode
> 
> ```
> literalEqual: other
> 	^false
> ```

I think it should be "^self == other"
