### ISSUE TITLE
DrTest raises an error when rerun an error

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#10887]
buildReRunConfigurationFrom: aDrTests
	"Builds a configuration for the plugin by reading the information held by the UI (aDrTests) and the last value of results."

	^ DTReRunConfiguration new
		originalConfiguration: aDrTests testsConfiguration;
		previousResult: aDrTests pluginResult;
		configurationToRun: (DTTestsRunnerConfiguration items: aDrTests resultSelected contentForReRun);
		yourself

expression 
aDrTests  testsConfiguration
raises DTTestsRunnerPlugin does not understand testsConfiguration

**Comment by Ducasse** [comment]
I added the following method in DefaultPluginPresenter but I'm not it is the right way to fix it. 
```
DTDefaultPluginPresenter >> pluginResult
	"not sure that it is good to have this delegation but without reruning a tests fails."
	^ self owner pluginResult

DTDefaultPluginPresenter >>testsConfiguration
	"not sure that it is good to have this delegation"
	^ self owner testsConfiguration
```
And 

```
DTRerunCommand >> execute
	self context owner 
runPluginFor: (self plugin buildReRunConfigurationFrom: self context)
```

May be it is enough to redefine 
DTRerunCommand >> execute
	self context owner 
runPluginFor: (self plugin buildReRunConfigurationFrom: self context owner)
but it did not work

**Comment by MarcusDenker** [comment]
fixed by merging https://github.com/pharo-project/pharo/pull/11510
