### ISSUE TITLE
Infinite loop when computing uml diagrams of baselines

### ISSUE THREAD

**Issue by Inao0** [guillep/pharo-core#10892]
**Bug description**
We duplicated a baseline (right clic copy). Pharo became unresponsive. Doing cmd + . showed a stack trace with an infinite loop.

![image](https://user-images.githubusercontent.com/37711386/153889252-6d994478-b0e5-40a1-b564-47df5104048b.png)

We worked around it by disabling the UML diagram in settings

**Comment by akevalion** [comment]
Going to review this

**Comment by akevalion** [comment]
@Inao0 I could not reproduce this issue. On pharo10 with roassalv0.9.9f, copying BaselineOfIDE with the new name BaselineOfIDE2

**Comment by guillep** [comment]
Seems to be fixed, let's reopen it if it happens again.
