### ISSUE TITLE
Wrong example in Dictionary>>#associationsDo: comment

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#10927]
**Bug description**
The example given in the method comment of Dictionary >> associationsDo: uses keysAndValuesDo:.

We should check if we can use an executable example (then we would have found it). But for methods like this executable examples get quite hard to read.

**Comment by vonbecmann** [comment]
see pull request [https://github.com/pharo-project/pharo/pull/10931](https://github.com/pharo-project/pharo/pull/10931)
