### ISSUE TITLE
Graphic UI selection glitch with selected text on large screens

### ISSUE THREAD

**Issue by labordep** [guillep/pharo-core#10929]
Hi,
I have a large screen (5120x1440) and I display the Pharo Window on all the available surface.
This is great but I have a funny bug :D when I select a text (from a source-code, or anything) the selection rectangle render is not visible.

See some screenshots after.

My Pharo desktop : 
![image](https://user-images.githubusercontent.com/49183340/154481104-9d3e5f88-6756-4f5e-9762-c7e1c849b4a6.png)

And the selection bug in differents cases :
![DirtySelection](https://user-images.githubusercontent.com/49183340/154482029-cd2d9ea8-4a1c-4be3-baf7-6ae196bddecc.gif)

On this gif we can see that there is "an invisible line", at the left off it the render is visible and at the right the render is cutted. May be this is the same problem for the vertical axe.

This is a problem when my selection is completely at the left of this line, I don't see the selection :S 
![InvisibleSelection](https://user-images.githubusercontent.com/49183340/154482799-45e7a775-81c9-4a83-ab10-9b65831a3463.gif)

This invisible line appear to be at 4095 pixels of the beginning of my screen (with a measure app), is the render clipped outside 4096 pixels ?

My config : 
Pharo 10.0.0
Build information: Pharo-10.0.0+build.399.sha.c4426366e83c26b8a002ef0680abe3a89a0b1a99 (64 Bit)
On Windows 10 Pro 64bits.

**Comment by labordep** [comment]
Same problem using multiple screens, the bug appears when the size of the Pharo Window is more than 4096px. Try to expand the window to reproduce it.

**Comment by labordep** [comment]
Same problem with a breakpoint once insertion : 
![image](https://user-images.githubusercontent.com/49183340/221418538-74acc4d6-b755-4e32-b334-3625c9d22f72.png)

**Comment by labordep** [comment]
And in text fields : 
![image](https://user-images.githubusercontent.com/49183340/221419529-e1d2d924-956b-4afc-8fb8-1017ed1b8170.png)

**Comment by labordep** [comment]
The concerned class is probably `RubScrolledTextMorph`, and the sub morph which manage the selection rectangle is probably `RubPrimarySelectionMorph`

When I'm inspecting the `RubPrimarySelectionMorph`, the problem not appears in the inspector : 
![image](https://user-images.githubusercontent.com/49183340/221422671-41a889a1-eb0e-493f-9e1c-13f3d096a8b5.png)

Same with inspecting the father Morph : 
![image](https://user-images.githubusercontent.com/49183340/221422781-efc1556b-3190-4c97-83e8-0b27b177e2c7.png)

**Comment by labordep** [comment]
The problem can be here : 
```
RubSegmentMorph>>drawOn: aCanvas
	"Display the receiver, a spline curve, approximated by straight
	line segments."
	|  |
	aCanvas drawPolygon: self getVertices fillStyle: self fillStyle.
	self drawBorderOn: aCanvas
```

I place a break point for the concerned identityHash and I found that by debugging : 

![image](https://user-images.githubusercontent.com/49183340/221423641-31f0d5ac-01c1-4219-ae90-afe60555812d.png)

There is a Bitmap of 4096 items in the `BalloonEngine`.

`BalloonEngine` contains an `initialize` method with : 

```
initialize
	| w |
	super initialize.
	w := Display width > 2048 ifTrue: [ 4096 ] ifFalse: [ 2048 ].
	externals := OrderedCollection new: 100.
	span := Bitmap new: w.
	self
		bitBlt:
			((BitBlt toForm: Display)
				destRect: Display boundingBox;
				yourself).
	forms := #().
	deferred := false
```

The 4096 is probably the problem, this is a magic number :), I will test if this is the source of the problem.

**Comment by labordep** [comment]
This is OK, I will propose a fix in a PR to have the size of the display and not a magic number.
Sorry for the long thread but it help for my reflexion.

**Comment by Ducasse** [comment]
Thank pierre. I would really like to know why the size are multiple. I hope that the primitives are not coded with this in mind.

**Comment by labordep** [comment]
Hi @Ducasse ,
Yes me too. I prefer to set a default size in case of bad width to have a behavior similar than before my fix.

**Comment by tinchodias** [comment]
That's a wide Pharo!

**Comment by labordep** [comment]
Working very fine :D
![image](https://user-images.githubusercontent.com/49183340/222899041-3b7a991d-faef-4b46-be41-3878da0c1137.png)
5120x1440
