### ISSUE TITLE
Saving of the method does not close completion in debugger

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#10925]
**Bug description**
When, in the debugger, a method is saved while a completion morph is opened, it gets broken to the red square of death

**To Reproduce**
1. Create a class `MyClass` with class-side method:
```smalltalk
msg 
    self halt.
    1 yourself
```
2. in the debugger, delete last `f`  from `yourself` and write it back, it will show the completion morph that will stay opened
3. press `Ctrl+S` to save the method
4. RSOD

![Pharo_qvcTHoqQ5M](https://user-images.githubusercontent.com/572494/154253465-42584ec1-6388-42ab-a10c-df20df19d81a.gif)

**IMPORTANT**
It behaves this way only on Windows. On Mac, the pressing of `Cmd` already closes the completion.

**Comment by pavel-krivanek** [comment]
The closing on Command key is implemented at the end of this method: `CompletionEngine>>#handleKeyDownBefore:editor:`

The basic problem is that if you press `Ctrl`, the `controlKeyPressed` returns `false`! Only if you press `Ctrl` for longer time and repeated keyboard events are produced, they have the `Ctrl` flag set (so the completion morph disappears).

A quick patch for Windows is:

```smalltalk
KeyboardEvent>>#controlKeyPressed

controlKeyPressed

	super controlKeyPressed ifTrue: [ ^ true ].
	
	^ (scanCode = 224) or: [ scanCode = 228 ]
```

**Comment by Alisu** [comment]
Pressing shortly the ctrl key on windows produce a keyboard ctrl event with the buttons variable sets to 0 (instead of 16 in my mac).
Then in the following method
```
controlKeyPressed
	"Answer true if the control key on the keyboard was being held down when this event occurred."

	"The mask for control bit pressed"
	^ buttons anyMask: 2r00010000
```
 applies  the mask to 0 answering that the key was not pressed.

**Comment by pavel-krivanek** [comment]
seems to be fixed
