### ISSUE TITLE
[Memory] commentSourcePointer is not needed for MetaClasses

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#10958]
**Bug description**
the source pointer to comments is stored in ClassOrganization. Now both the class and the metaclass have a ClassOrganization instance, but the source pointer for the comment is only needed once.

**Why is this a problem?**
It is not a severe problem (else this would have already been fixed a loooong time ago). But it wastes a little bit of memory.
(just some ~75Kb in the current Pharo10).

**What needs to be done**
The reason why this is stored in the ClassOrganization is just that it was too hard to change Class itself without the bootstrap way back when it was added (ST80 did not save class comments in the .sources/changes).

That means: we just need to move the commentSourcePointer to Class, then MetaClass will not waste space with it anymore,

**Comment by Ducasse** [comment]
Yes!

**Comment by astares** [comment]
Cool! 

Yes bootstrap allows for things that would not have been possible back at the time in Squeak. Pharo rocks!

**Comment by MarcusDenker** [comment]
merged https://github.com/pharo-project/pharo/pull/11449

**Comment by MarcusDenker** [comment]
merged!
