### ISSUE TITLE
[Memory] sharedPools OrderedCollections waste memory

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#10957]
**Describe the problem**
Class>>#sharedPools instantiates an OrderedCollection. But almost no class actually imports a shared pool:

```
(Smalltalk allClasses select: [ :each | each sharedPools isEmpty  ]) size  "9530"
```

This wastes quite some memory:

```
OrderedCollection new sizeInMemory "32"
(OrderedCollection new instVarNamed: #array) sizeInMemory "88"

(9530 * (32+88)) / 1024 / 1024.0 "1.0906219482421875"

```

==> we could save some memory if we would lazy initialize the sharedPools ivar

**Comment by Ducasse** [comment]
Yes good idea. Or we could share an empty one and on first usage set a new one. 
But it can produce more subtle setup.
