### ISSUE TITLE
ReClassSideResetMethodProtocolRule is not checking for class side

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#10960]
**Bug description**
ReClassSideResetMethodProtocolRule is missing a #isClassSide check

**To Reproduce**
add a method #reset on the instance side. See the rule falsely complaining.

**How to fix**

ReClassSideResetMethodProtocolRule>>#basicCheck: miising a isClassSide check

**Comment by astares** [comment]
Introduced in https://github.com/pharo-project/pharo/pull/10182
