### ISSUE TITLE
Underscore in class name breaks text completion

### ISSUE THREAD

**Issue by sonibla** [guillep/pharo-core#10986]
**To Reproduce**
1. Create a class named `My_Class`
```
Object subclass: #My_Class
	instanceVariableNames: ''
	classVariableNames: ''
	package: ''
```
2. In a playground, type `My_`
3. First issue: no text completion entries are showing up
![phIssue_1](https://user-images.githubusercontent.com/49032546/157849101-2074178b-f728-4042-8e86-64aaea125a3c.png)

4. Type fastly `Class` so that playground content is `My_Class`
5. Second issue: text completion is showing up for classes starting with `Class` instead of `My_Class`
![phIssue_2](https://user-images.githubusercontent.com/49032546/157849115-2a1ee357-1246-4a9b-9efc-8f933b2f3056.png)

6. Go back to `My`, then type slowly `_Clas` so that playground content is `My_Clas`
7. When `My_Class` text completion shows up, press enter
8. Third issue: now the playground contents is `My_My_Class` instead of `My_Class`
![phIssue_3](https://user-images.githubusercontent.com/49032546/157849144-bc7b1a7d-3a6a-4f16-93dd-6864601a05a7.png)

**Version information:**
 - OS: Win10 and Linux Debian 11
Pharo 10.0.0
Build information: Pharo-10.0.0+build.473.sha.a073a65d1153db338c3be8764da632e2ce71d901 (64 Bit)

**Comment by astares** [comment]
Its possible to use "_" - but not a good style.

**Comment by MarcusDenker** [comment]
merged
