### ISSUE TITLE
Indent (Ctrl+Shift+R) stopped working

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#10984]
**Bug description**
The key combination to indent the code (Ctrl+Shift+R) stopped working (the opposite one, Ctrl+Shift+L, still works).

This combination now selects content of the closest parentheses.

**Comment by pavel-krivanek** [comment]
The collision comes from here: `SycOpenReflectivityMenuCommand class>>#methodEditorShortcutActivation`

**Comment by MarcusDenker** [comment]
after the merge it works on the mac

**Comment by MarcusDenker** [comment]
The problem is that *removing* this method now disables the CMD-t shortcut.

**Comment by MarcusDenker** [comment]
pavel says: fixes on win, too.
