### ISSUE TITLE
Spotter x button doesn't close the window

### ISSUE THREAD

**Issue by Inao0** [guillep/pharo-core#10993]
**To Reproduce**
1. Open Spotter
2. Try to close it with the cross

**Expected behavior**
Close the spotter

**Version information:**
 - OS: Mac OS Monterey 
 - Pharo Version: 10

**Comment by maxwills** [comment]
I though it was a close button too!. But upon further inspection, I know now that if you press it, it will clear the text field.

![Screen Shot 2022-03-17 at 15 49 27](https://user-images.githubusercontent.com/1684221/158830968-97da0739-ff7c-405a-8462-ecd84d5f67ef.png)

Just as a side comment, I stopped using the Spotter. I feel it has a somewhat erratic behavior, and sometimes doesn't show what I am looking for. The button also looks like a close button. 
What I want to say is that, may be it would be worth to put some time into its design.
(Don't get me wrong, its a nice tool, but I found more effective ways of accessing classes and methods using the Playground+browse, senders and implementors shortcuts, for example)

**Comment by Inao0** [comment]
I didn't know about that behavior! I created this issue because I saw someone stuck inside spotter trying to quit it using that cross. Maybe it should be another symbol? Or maybe outlining the field could make clear that the cross is related to the field?

**Comment by estebanlm** [comment]
yeah, because this is not to close the window but to remove the text.
is not the functionality that fails but the icon that is not good (still a bug)

**Comment by DanielCamSan** [comment]
Implemented a UI solution in:
https://github.com/pharo-spec/NewTools/pull/421

**Comment by MarcusDenker** [comment]
merged the PR https://github.com/pharo-spec/NewTools/pull/421
