### ISSUE TITLE
isPrime does not work for large numbers

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#11007]
**Bug description**
`(105850338e131072+1) isPrime` is causing an error `Error: Cannot truncate this number` after a while.

**Comment by johnhwoods** [comment]
Numbers this big use #isProbablyPrime and this algorithm (Miller/Rabin) multiplies LargePositiveIntegers by Floats.  The maximum value of a 64bit float is a bit under 1.797694e308 --- above that the product will be Float infinity, which cannot be truncated, hence the error.

This suggests that isPrime cannot be used for LPIs that are much bigger than the maximum Float size.   We could just return an error if it's called with a value bigger than 1e308.  Or we could convert the multiplication to an integer operation by converting the float to a fraction.  That allows you to go a bit further but on a normal PC you'll be taking over a minute by the time you get to 1e10000, and, as it looks like about O(n³) to me I reckon you're looking at days of computation to get answers to calculations of the vast magnitude here.  (For reference, number of atoms in observable universe is probably about 1e80 or so).

**Comment by johnhwoods** [comment]
![isProbablyPrimeTime](https://user-images.githubusercontent.com/4273151/158810405-f4e80f99-d1ec-4ee0-be5d-b4013793b0b8.png)

**Comment by johnhwoods** [comment]
My own suggestion is we convert the reference floats to fractions.  The purpose of this is surely mainly cryptographic and therefore we are interested in numbers of about 2**8k or so which are about 1e2500.  I can change the code but we need someone with a better crypto brain to give the nod.

**Comment by pavel-krivanek** [comment]
Let's have a more reasonable example for this issue ;-)

```smalltalk
((Float fmax asInteger * 101) + 25) isPrime
```

To convert the floats to fractions makes it work. We should do it only above some given threshold (I'm not sure if `Float fmax` is good enough)

**Comment by pavel-krivanek** [comment]
If someone wants to play with more crazy large numbers, expecting that the standard library will provide an optimal solution is, kindly said, very optimistic :-)

**Comment by pavel-krivanek** [comment]
another example: which does not look too crazy: `(171 factorial + 397) isPrime`

**Comment by johnhwoods** [comment]
Can't agree.  :-) Smalltalk is the perfect place for playing with very large numbers, because it's so easy to understand what's going on in the code, performance improvements are trivial.  So, changing the key method:
```Smalltalk
Interger>>isProbablyPrimeWithK: k andQ: q randomIndex: aRandomFloat
	"..."

	| x j y minusOne |
	"P1"
	x := ((self - 2) * aRandomFloat "a pregerated random number") asInteger + 1.
	" rest of method ..."
```
by inserting `asFraction` after the `aRandomFloat` gives the figures above.  However, the same 25 pregenerated floats are used throughout the process, so changing the initial method so that these are 25 pregenerated fractions gives you a massive speed boost, because you only do the float to fraction conversion once per float.  I reckon I can get your initial number done in an hour rather than days by doing this.

**Comment by johnhwoods** [comment]
![isProbablyPrimeTimeB](https://user-images.githubusercontent.com/4273151/158877013-ae2884b9-4fdc-4f5a-b870-5130b3c410fd.png)

**Comment by johnhwoods** [comment]
This is your new `Integer>>isProbablyPrime` method.  I basically just converted all the floats in the original method into Fractions.   Let me know how you get on with it ...

```Smalltalk
isProbablyPrimeB
	"See isProbablyPrimeWithK:andQ:randomIndex: for the algoritm description."
	
	| k q randomNumbers |
	self <= 1 ifTrue: [ ^false ].
	self even ifTrue: [ ^self = 2 ].
	"Factor self into (2 raisedTo: k) * q + 1, where q odd"
	q := self bitShift: -1.
	k := q lowBit.
	q := q bitShift: 1 - k.
	"Repeat the probabilistic until false (the probability of false negative is null) or until probability is very low."
	
	"Array of pregenerated 25 random fractions"
	randomNumbers := {(7358707628525929/9007199254740992). (4476672520736517/4503599627370496).
(4599362334273073/9007199254740992). (6794991761377285/36028797018963968).
(3521097546400983/4503599627370496). (7149434852003007/18014398509481984).
(2256749684852993/9007199254740992). (138798294760569/140737488355328).
(7561030569146735/18014398509481984). (1168422440815961/4503599627370496).
(3963174916991225/9007199254740992). (6738728495079853/72057594037927936).
(3458098951393855/4503599627370496). (5263539441067603/18014398509481984).
(6805352233327325/9007199254740992). (8277697662472459/18014398509481984).
(8039661477371919/9007199254740992). (5594429820223541/9007199254740992).
(8436167510585677/9007199254740992). (8687763071023859/18014398509481984).
(8534015346516809/18014398509481984). (4439971299560515/144115188075855872).
(3595168640502675/4503599627370496). (7413480251763979/9007199254740992).
(7101202260194563/36028797018963968)}.
	
	randomNumbers do: [:rnd | (self isProbablyPrimeWithK: k andQ: q randomIndex: rnd ) ifFalse: [ ^false ] ].
	"The probability of false positive after 25 iterations is less than (1/4 raisedTo: 25) < 1.0e-15"
	^true
```

**Comment by pavel-krivanek** [comment]
please, make a PR

**Comment by johnhwoods** [comment]
yep will do.  I've also noticed that `SmallInteger>>isPrime` has got a 2x inefficiency, so i've written a faster one.
```Smalltalk
(Time microsecondsToRun: [ 1152921504606846883 isPrime ]) / 1.0e6. "10.098984"
(Time microsecondsToRun: [ 1152921504606846883 isPrimeB ]) / 1.0e6. "5.80872"
```
I'll make that a separate issue and separate PR

**Comment by johnhwoods** [comment]
PR raised for LargeInteger>>isPrime just needs testing and review.
