### ISSUE TITLE
Stateful Traits: Adding One Corrupts Existing Instances

### ISSUE THREAD

**Issue by seandenigris** [guillep/pharo-core#11001]
**Bug description**
Adding a stateful trait leads to corrupt existing instances

**To Reproduce**
1. Create a class and a stateful trait:
```smalltalk
Object subclass: #MyClass
	instanceVariableNames: 'var'
	classVariableNames: ''
	package: ''.
Trait named: #TMyTrait
	instanceVariableNames: 'tvar'
	package: ''.
TMyTrait compile: 'tvar
	^ tvar'
```
1. Inspect an instance: `MyClass new`
1. Add the trait to the class:
```smalltalk
Object subclass: #MyClass
	uses: TMyTrait
	instanceVariableNames: 'var'
	classVariableNames: ''
	package: ''.
```
1. From the inspector open on the instance variable, try to inspect the state of the trait: `self tvar`

**Expected behavior**
You would expect the result to be nil, but the result is a float. I have managed to crash the VM in certain cases, but don't have a reproducible case for that.

**Screenshots**
<img width="697" alt="Screen Shot 2022-03-15 at 10 54 05 AM" src="https://user-images.githubusercontent.com/184176/158405566-30493046-a57a-4c95-86e3-a2bd86217241.png">

**Version information:**
 - OS: macOS 12.2.1 on M1
 - Pharo 9

**Expected development cost**
I don't know; wish I could be more helpful here!

**Comment by johnhwoods** [comment]
I got tvar of nil, but an attempt to inspect it caused the VM to exit immediately.

**Comment by tesonep** [comment]
@seandenigris Thanks a lot of the instructions to reproduce it, it was nice and easy to write a test and fix it.

**Comment by seandenigris** [comment]
Awesome! Glad to help. Can we back port to P9? This is driving my crazy

**Comment by seandenigris** [comment]
FTR it’s been exported to P9 :)
