### ISSUE TITLE
Zinc-Resource-Meta-Core dirty package

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#11028]
In a fresh Pharo image connected to "Pharo10" branch the "Zinc-Resource-Meta-Core" package is dirty:

![image](https://user-images.githubusercontent.com/5980033/159459600-0c5b1940-d922-4322-b69f-337abd6976fb.png)

Maybe related to being out of synch between image and source for the following changes:

![image](https://user-images.githubusercontent.com/5980033/159459392-bcb41df1-1602-465f-ae0a-fd9310cbb505.png)

**Comment by MarcusDenker** [comment]
Yes, this is more difficult to fix than you would think, there is  PR to do the complete sync that if merged then has a failing windows test that first has to be fixed.

https://github.com/pharo-project/pharo/pull/10955

As I say: I do not believe in doing big changes and syncing back... people argue it is simpler, but I have never seen a case where it did not make everything even harder than continuous integration.

**Comment by astares** [comment]
@MarcusDenker I'm with you in this:

Big changes with synching back creates more/lot of effort. If done wrong it can revert other changes and have negative side effects.
Small steps quickly merged allows to stay more easy in control and have less impact when done...
