### ISSUE TITLE
CmdCommand should implement #isUsed 

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11023]
If you browse a subclass of CmdCommand, the system says that the class is not used.

But this hierarchy discovers subclasses reflectively --> they are all used

**Comment by demarey** [comment]
This change is surprising. Why would all commander commands be used?
Some of them are referenced directly and not discovered reflectively.
To solve #11023, I would rather define a `ClyCommand` class with a method `isUsed` returning true.
