### ISSUE TITLE
Morphic events

### ISSUE THREAD

**Issue by akevalion** [guillep/pharo-core#11031]
**Bug description**
some events from Morphic does not work properly across different OS platforms.

**To Reproduce**
1. Inspect this code in pharo
```
canvas := RSCanvas new.
canvas when: RSMouseClick do: [ :evt |
	'happy' traceCr.
	 ].
canvas.
```
2. You will have a windows, click on it
3. You will see in transcript the message: `happy`.
4. Now try with alt, option key combination and mouse click.
5. Now try with control+click.

You do not see the message.
But if you try shift +click or command + click in mac or windows key + click.
You will see the message.

**Expected behavior**
- click + control
- click + alt

should work and trigger the events for morphs

**Version information:**
 - OS: macOs monterrey, windows10, linux ubuntu.
 - Pharo Version 10

**Additional context**
This issue some important classes here are OSWindowMorphicEventHandler and SDL_KeyDownEvent.

**Comment by MarcusDenker** [comment]
PR was merged
