### ISSUE TITLE
StringMorph doesn't draw border according to border style when set

### ISSUE THREAD

**Issue by StewMacLean** [guillep/pharo-core#11050]
**Bug description**
If a border style is set on a StringMorph, the drawOn: method doesn't use it.

**To Reproduce**
1. Set a border style on a StringMorph and observe that no border is drawn according to the style

**Expected behavior**
The morph should be drawn with a border according to the set style.

**Screenshots**
TBA

**Version information:**
 - OS: MacOs Monterey
 - Version: 12.0.1
 - Pharo Version 9

**Expected development cost**
Nil - please see fix below:

StringMorph>>drawOn: aCanvas

	"SIM 16/3/22 - Draw according to border style if set."
	
	aCanvas
		fillRectangle: self bounds 
		fillStyle: self backgroundColor
		borderStyle: self borderStyle; "So that it draws the border, if one is set."
		
		drawString: self contents 
		in: self stringBounds 
		font: self fontToUse 
		color: self stringColor
		underline: (emphasis bitAnd: 2r100) ~~ 0
		underlineColor: self underlineColor 
		strikethrough: (emphasis bitAnd: 2r10000) ~~ 0
		strikethroughColor: self strikethroughColor

**Comment by jordanmontt** [comment]
Hello @StewMacLean Did you test your solution? Because now we tried to use it and it breaks the image like this:

![Capture d’écran 2022-03-25 à 10 59 29](https://user-images.githubusercontent.com/33934979/160098984-96d4846d-8fcf-4848-8927-bd7ddab94d77.png)

It is a Pharo 10 image.

**Comment by Ducasse** [comment]
We checked and the canvas does not support the drawing of string with border. 
To have bordered string morph a string morph should be nested inside a borderedMorph. 
BTW this is important when you propose code to say if it was working with you. 
So we will close this issue

**Comment by StewMacLean** [comment]
Ouch! That is truly broken :)

Thanks for the suggestion of embedding the morph. I'm a Pharo newbie, and
didn't think of that!

Actually, I came across this whilst trying to put a border around an
embedded Roassal canvas using Spec. I've raised this with them.

Can you please tell me how I get access to Pharo 10? I've looked at
https://github.com/pharo-project/pharo, but not really sure what to do.

I've heard that Pharo10 will support/use native widgets? Can you please
point me towards more information regarding this?

I have used Smalltalk for years (since the 80s!) and have spent years on a
personal project using VisualWorks. Sadly it looks like they are losing
interest and there is no current support for the Mac M1, and no sign of it
coming anytime soon. So I really appreciate the work the Pharo People are
doing to provide a viable alternative - thanks!

Cheers,

Stewart

**Comment by Ducasse** [comment]
You can get Pharo 10 simply using the PharoLauncher this is the simplest way to get Pharo in all its version.

**Comment by Ducasse** [comment]
with Pharo 10 you can use the GTK backend to access native GTK widgets. You can ask on the spec channel on discord. 
Thanks for your encouragements.

**Comment by StewMacLean** [comment]
You're welcome! I haven't used the Launcher as yet, will check it out. Thanks

**Comment by Ducasse** [comment]
The launcher is save you some pain because it identifies and update vm when new ones are released. So you can do everything  using the zeroconf scripts (see the deep into pharo books) and access the file server hosting our files but the launcher is made to simplify our lives and it does it.
