### ISSUE TITLE
Calypso's hierarchy should not be reversed by default when compiling an overriden method

### ISSUE THREAD

**Issue by hogoww** [guillep/pharo-core#11052]
**Bug description**
When you select a method from a class that is different from your current class, a menu giving a reversed hierarchy of classes is provided.
I consider (and @Inao0 as well) that this is error prone, because we always have a normal hierarchy.
I am installing methods in the wrong class on a daily basis.
This is a setting with the (arguably) wrong default behavior.

**To Reproduce**
1. Go to a class with methods in the super class
2. Click on the checkbox to have methods inherited by the current class
3. Select a method
4. Change something
5. Try to save
6. A dialog appears showing you the reversed hierarchy

**Expected behavior**
The hierarchy should be in the regular order

**Screenshots**
Current default
![Screenshot 2022-03-25 at 11 19 20](https://user-images.githubusercontent.com/21278554/160102368-63c08649-6663-4d97-958c-1bb1610162ba.png)

Expected
![Screenshot 2022-03-25 at 11 18 59](https://user-images.githubusercontent.com/21278554/160102321-0da62856-af69-4c5b-9603-fe102000542f.png)

**Version information:**
Pharo 10

**Expected development cost**
Trivial, it's a default setting to update.

**Additional context**
The class to preselect in the list is another issue, that we will open later.

**Comment by hogoww** [comment]
Preselection issue explained in a mail on the dev list: https://lists.pharo.org/empathy/thread/HTIE7ZPSIUTBWL5T5SBAVTWZKCU2VN7H


<blockquote><img src="/empathy/images/em.png" width="48" align="right"><div><strong><a href="https://lists.pharo.org/empathy/thread/HTIE7ZPSIUTBWL5T5SBAVTWZKCU2VN7H">Empathy List Archives</a></strong></div><div>Empathy mailing list archives</div></blockquote>

**Comment by StephanEggermont** [comment]
Does that scroll correctly with a deep hierarchy?

**Comment by hogoww** [comment]
I do not know.
One of the ways to paliate such an issue though would be to preselect the current class

**Comment by Ducasse** [comment]
Indeed.

**Comment by hernanmd** [comment]
I cannot reproduce in Pharo 11 because of this:

> 2\. Click on the checkbox to have all methods

Which checkbox?

**Comment by hogoww** [comment]
The checkbox showing the methods that are inherited.
I'll edit.

**Comment by hogoww** [comment]
<img width="416" alt="Screenshot 2022-12-06 at 14 28 39" src="https://user-images.githubusercontent.com/21278554/205925093-319242b5-5648-4f82-9d95-34f79991ec60.png">
