### ISSUE TITLE
Cleanup: protocol "accessing-delegated" should be "accessing - delegated"

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#11061]
The only one for the accessing protocols that is not in the "pimary - secondary" notation.

![image](https://user-images.githubusercontent.com/5980033/160218853-cb4934fb-0d52-4f82-ae7b-4d15c7ea8591.png)

need to be fixed in MicSameStartStopMarkupBlock from Microdown

**Comment by astares** [comment]
![image](https://user-images.githubusercontent.com/5980033/160218887-76cc7da5-32f0-4949-93dd-fe8062064e1a.png)

**Comment by MarcusDenker** [comment]
fixed by https://github.com/pillar-markup/Microdown/pull/667
