### ISSUE TITLE
ExternalChangesBrowser>>buildMenu: should use selectedItemsSorted

### ISSUE THREAD

**Issue by StewMacLean** [guillep/pharo-core#11063]
**Bug description**
File in all selected menu item uses selectedItems which causes problems filing in as dependencies are not honoured.
It should use selectedItemsSorted.

**To Reproduce**
1. Place a breakpoint in buildMenu: and inspect selectedItems
2. Observe that the order of the items is not the same as on the UI

**Expected behavior**
Code should be filed in in order to honour dependencies.

**Version information:**
 - OS: [MacOS]
 - Version: [12.0.1]
 - Pharo Version [9]

**Expected development cost**
Nil - Change the code to use selectedItemsSorted.

**Comment by Ducasse** [comment]
Hello
we do not really use this tool so sorry for the glitch. Can you let us know if this is working or not in P10
because we only fix in P9 showstoppers.

S

**Comment by StewMacLean** [comment]
Hi,
Yes, the only reason I'm using it is for importing code from VisualWorks which I guess is not that common.

Anyway, it is not working in P10. The method has been renamed to buildMenu (no argument) and still uses selectedItems. It should use selectedItemsSorted as below.

Thanks,

Stewart

buildMenu

	| aMenu |

	aMenu := self newMenu.

	aMenu 	addItem: [ :item | 
			item
				name: 'File in all selected';
				action: [ self fileIn: changes selectedItemsSorted "selectedItems" ] ].

	aMenu 	addItem: [ :item | 
			item
				name:  'Compare method to current';
				enabled: [ self canCompareToCurrent ];
				action: [ self compareToCurrent: changes selectedItem ] ].

	^ aMenu

**Comment by MarcusDenker** [comment]
@StewMacLean PR for review: https://github.com/pharo-project/pharo/pull/11156
