### ISSUE TITLE
Pharo X Segmentation fault in macOS

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#11077]
**Bug description**

The [Pharo-WebView TFFI binding](https://github.com/eftomi/Pharo-Webview) can provide a window for rendering HTML components from Pharo in a separate window. The attached script test this behavior (can also be found in the BasicTest class of Pharo-WebView). A segmentation fault crashes the Pharo VM process.

**To Reproduce**

1. Download Pharo X

```bash
curl https://get.pharo.org/100+vm | bash
```
2. Run Pharo with the attached script: [PharoX-tffi-crash-macos-29-03-2022.txt](https://github.com/pharo-project/pharo/files/8374939/PharoX-tffi-crash-macos-29-03-2022.txt)

```bash
mv PharoX-tffi-crash-macos-29-03-2022.txt PharoX-tffi-crash-macos-29-03-2022.st
./pharo-ui Pharo.image PharoX-tffi-crash-macos-29-03-2022.st
```

3. See error in generated crash.dmp (also attached [here](https://github.com/pharo-project/pharo/files/8374943/crash.txt)))

**Version information:**
 - OS: macOS BigSur 
 - Version: 11.6.1
 - Pharo Version: 10

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 

This at least requires an understanding of libPharoVMCore for macOS so I cannot estimate.

In addition, are you willing to help because after all Pharo is yours too?

Of course

**Comment by estebanlm** [comment]
I am sorry, but this looks more like a problem in Pharo-WebView than a FFI problem.
The stacktrace you provided seems to indicate there is a problem with the parameters `WebView>ffiCreate` uses.

Please, reopen if I am wrong :)
