### ISSUE TITLE
List do not unset their color on mouse move

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11093]
![Capture 2022-04-03 at 16 10 09](https://user-images.githubusercontent.com/432549/161432043-978580ac-6406-4682-9032-d6d47b75e912.png)

in 

Pharo 10.0.0
Build information: Pharo-10.0.0+build.508.sha.1e4c1916f4942ea445651c3790e7dae36e4fa4d0 (64 Bit)

**Comment by demarey** [comment]
I took a fresh Pharo image (Pharo-10.0.0+build.508.sha.1e4c1916f4942ea445651c3790e7dae36e4fa4d0 (64 Bit)
and I cannot reproduce the pb.
Do you have a way to reproduce?

**Comment by Ducasse** [comment]
may be this is a monterrey problem 
but to reproduce I just open any window with list

**Comment by Ducasse** [comment]
Ok I found it. It is a package of Steven
