### ISSUE TITLE
Setting a setting is broken 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11092]
```
keepSettingTreeNode: aSettingNode 
	^ (({aSettingNode methodClass name asUppercase. aSettingNode selector asUppercase}
			collect: [:e | e ifNil: ['']])
			includesSubstringAnywhere: self token asUppercase)
		or: [self keepSettingDeclaration: aSettingNode settingDeclaration]
```

aSettingNode methodClass is returning nil in 

How to reproduce: type Spotter in the search bar

**Comment by Ducasse** [comment]
Pharo 10.0.0
Build information: Pharo-10.0.0+build.508.sha.1e4c1916f4942ea445651c3790e7dae36e4fa4d0 (64 Bit)

**Comment by estebanlm** [comment]
I can't reproduce a problem here either. 
Aren't you running with a zombie UI process?

**Comment by Ducasse** [comment]
Ok I found it. It is a package of Steven
