### ISSUE TITLE
PharoLauncher: List Pharo10 as stable

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11102]
**Bug description**
We got multiple questions of the kind:

"Will the stable version be available in the PharoLauncher soon"

"there's no 10 Stable available in the Launcher yet."

What do we need to do here?

**Comment by demarey** [comment]
was already done here: https://github.com/pharo-project/pharo-launcher/commit/5407ecbba9f5be98651ac2e81c392b085b97e8d2
