### ISSUE TITLE
Changing the package of a class sets a wrong package name

### ISSUE THREAD

**Issue by hogoww** [guillep/pharo-core#11111]
**Bug description**
When changing the package of a class with a tag written in fluid syntax, the tag is put in the package name rather than as a tag

**To Reproduce**
1) Create a new class with a tag
2) Save it
3) edit the package to a new name, of a non existing package
4) the name should be wrong.

exemple: 
Object << #MyClass
	slots: {};
	tag: 'bugReport'; 
	package: 'AAAA'
Edit to 
Object << #MyClass
	slots: {};
	tag: 'bugReport'; 
	package: 'AAAA1'
The package name is wrong and the tag is lost
Object << #MyClass
	slots: {};
	package: 'AAAA1-bugReport'

**Expected behavior**
The tag should stay, and the package name should be the one specified.

**Version information:**
Saw on the latest pharo 10 image.
MacOS

**Expected development cost**
I am unsure whether the problem comes from fluid, calypso, or something else, so I cannot say.

**Comment by Ducasse** [comment]
thanks. Tag implementation is so bad. ...

**Comment by MarcusDenker** [comment]
This is now working correctly
