### ISSUE TITLE
primitiveChangeClassTo: fails for sibling classes that have the same shape

### ISSUE THREAD

**Issue by StewMacLean** [guillep/pharo-core#11125]
**Bug description**
Primitive fails for sibling classes that have the same shape

**To Reproduce**
File in the attached package and execute:
ChangeClassToTest new runTest.
The primitive fails!

**Expected behavior**
The source object should change class to the sibling class.

**Screenshots**
N/A

**Version information:**
 - OS: MacOS M1 Monterery
 - Version: 12.0.1
 - Pharo Version: 10

**Expected development cost**
This requires a VM change - out of my league I'm afraid!

[SIM-TestChangeClass.st.zip](https://github.com/pharo-project/pharo/files/8485811/SIM-TestChangeClass.st.zip)

**Comment by MarcusDenker** [comment]
Strangely the APi is a bit odd: #primitiveChangeClassTo: wants to have an instance, not a class:

```
SubclassFrom new primitiveChangeClassTo: SubclassTo new
```

It works for me if I add the #new as shown above.

**Comment by StewMacLean** [comment]
Hi Marcus,

Duh! Should have read the comment!!!. I was converting VW code, so just
read the selector.

My now redundant workaround was:

becomeA: aClass

| new |

new := ShiftClassInstaller new copyObject: self to: aClass.

{self} elementsForwardIdentityTo: {new} copyHash: true.

^new

Thanks,

Stew

**Comment by StewMacLean** [comment]
Maybe it should be renamed to primitiveChangeClassToClassOf:

???

**Comment by MarcusDenker** [comment]
And maybe having a primitive that does not need an instance could be nice to avoid the useless instantiation.
