### ISSUE TITLE
Fuel: 283 failing tests on the CI: "FLPharo11Platform had the subclass responsibility to implement #fileNamed:writeStreamDo:"

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11130]
**Bug description**

```
FLPharo11Platform had the subclass responsibility to implement #fileNamed:writeStreamDo:
```

**Comment by MarcusDenker** [comment]
I have no idea what is happening.

if I load v4 from https://github.com/theseion/FuelPlatform, I do get the method. But it is not loaded in Pharo. It seems that what is loaded in Pharo is "stable":

```
fuelPlatform: spec		
	spec 
		baseline: 'FuelPlatform' 
		with: [ 
			spec
				repository: 'github://theseion/FuelPlatform:stable/repository';
  				loads: 'default' ]
```

<blockquote><img src="https://opengraph.githubassets.com/e58dbe95b7bc4f6a256ac9d449f103b9529cc22d09e1274ff08f9f2a01bb7781/theseion/FuelPlatform" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/theseion/FuelPlatform">GitHub - theseion/FuelPlatform: Platform abstractions for Fuel</a></strong></div><div>Platform abstractions for Fuel. Contribute to theseion/FuelPlatform development by creating an account on GitHub.</div></blockquote>

**Comment by theseion** [comment]
The issue appears to be that the old code isn't being replaced. It loads the correct platform package but `FLPlatform` is still from the pre v4 "stable" branch. Same with the Fuel code itself, it's still 3.0.3. I don't know why this is happening, I never have any issues with my builds. However, it could be fixed by running some kind of pre-load script to unload Fuel completely.

**Comment by theseion** [comment]
That's my fault. I forgot that Pharo 10 still used Fuel v3 and copied the wrong version of Pharo 10 platform. I'll update the platform for Pharo 11 on the stable branch now.

**Comment by theseion** [comment]
Done and tested. Metacello still reports `pharo10.x` for Pharo11, so it will also load the Pharo 10 platform but that is ok (it will just be an unused class).

**Comment by MarcusDenker** [comment]
Looks good! Ci managed to build Pharo11 without the failing tests
