### ISSUE TITLE
Right click context menu in Help Browser right pane doesn't work

### ISSUE THREAD

**Issue by mldavis99** [guillep/pharo-core#11131]
The right click context menu in the right hand pane of the help browser in both Pharo 10 64 bit on Windows 11 and the current build of Pharo 11 does not open.  However the pane otherwise functions.  

Steps to repeat:
In the World Help menu select Pharo Tutorials
In Browse tutorials left pane select Pharo Syntax Tutorial then Welcome 
In the right hand pane highlight ProfStef next. Right click the mouse.
Note that the context menu pop up does not open.
With ProfStef next. still highlighted, click Ctrl-D on the keyboard.
Note that the tutorial command is executed and the window moves to the next screen.

**Comment by MarcusDenker** [comment]
Help Browser is being replaced by a new version which does not have this problem
