### ISSUE TITLE
Object>>#asOrderedCollection should be deprecated

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#11146]
**Bug description**
In my code, I was getting in an instance variable (`shapes`) this content: `#(nil)` wondering where it comes from. In the end, I realized that it was caused by this code: 

```smalltalk
newShapes := shapes copy asOrderedCollection.
```` 

The problem was, of course, that the instance variable was not properly initialized and then `nil asOrderedCollection` returns an OrderedCollection with nil. 

I propose that the `Object>>#asOrderedCollection` should be deprecated and replaced with something with more explicit name. I'm not sure what the name should be (`withinOrderedCollection` or something like that). 

Notice that there is no `Object>>#asArray` nor `Object>>#asSet`

**Comment by Ducasse** [comment]
I would remove asOrderedCollection from Object as well as asArray and asSet :).
We want a smaller Object.
