### ISSUE TITLE
TestRunner >> classNamesNotUnderTest is sent but not implemented

### ISSUE THREAD

**Issue by aboubacardiawara** [guillep/pharo-core#11142]
```smalltalk
excludeClassesNotUnderTestFrom: methods
	classesSelected
		do: [ :class | 
			(class class includesSelector: #classNamesNotUnderTest)
				ifTrue: [ 
					class classNamesNotUnderTest
						do: [ :className | 
							| theClass |
							theClass := Smalltalk globals classNamed: className.
							theClass
								ifNotNil: [ 
									theClass methods do: [ :each | methods remove: each  ifAbsent: [  ] ].
									theClass class methods do: [ :each | methods remove: each  ifAbsent: [  ] ] ] ] ] ]
```

**Comment by MarcusDenker** [comment]
I think the idea is that this is a method that a class can implement but does not have to. If it is implemented, the test coverage feature does not take this class into account.

It might be useful when using test coverage (and I do use the test coverage feature of the test runner).

Maybe it could assign #classNamesNotUnderTest to a temp and use perform, to not have a hard send of a non-existing selector.

This code is of course not perfect.. but I wonder if we should clean that up now (other than using perform).

Later
- it could use Class Pragmas/Annotations but we do not have that yet.
- the whole coverage tool might better not be part of the test runner but a standalone tool (part of a code coverage tool)

**Comment by MarcusDenker** [comment]
I propose to close this, as it is useful as soon as you use coveragetools. The send is checked (includesSelector:) before being done, so not DNU possible
