### ISSUE TITLE
Very big and very small numbers don't add up well

### ISSUE THREAD

**Issue by olekscode** [guillep/pharo-core#11152]
Here is a fun example 😃
```st
superBig := 1e20.
superSmall := 1e-20.

superSmall = 0. "false"

superBig + superSmall = superBig. "true"
superBig - superSmall = superBig. "true"
```

This breaks the math because `a + b = a` and `a - b = a` **if and only if** `b = 0`

And because of that, we have some bugs in PolyMath: https://github.com/PolyMathOrg/PolyMath/issues/221

**Comment by olekscode** [comment]
There is the same problem in Python:
```Python
superBig = 1e20
superSmall = 1e-20

superSmall == 0 # False

superBig + superSmall == superBig # True
superBig - superSmall == superBig # True
```

**Comment by SergeStinckwich** [comment]
This is not a bug IHMO, this is a normal behavior for real.

**Comment by olekscode** [comment]
Yes, I agree
So we can close this issue and just add a workaround to PolyMath

**Comment by nicolas-cellier-aka-nice** [comment]
This is not a normal behavior for real as real would refer to mathematics, but it is for limited precision floating point arithmetic which is precisely what `Float` is.

You can further see this case of catastrophic cancellation:

    superBig - superBig + superSmall ~= (superBig + superSmall - superBig)

which illustrates that arithmetic operations are not associative on Float, which is another property differing from real arithmetic.

In floating point, arithmetic operations behaves like this:

    (floatA op: floatB) = (floatA asReal op: floatB asReal) roundTo: (floatA asReal op: floatB asReal) floatUlp.

which means that the result of floating point operation equals the result of real operation, rounded to a representable floating point value (two consecutive float values being separated by float ulp - unit of least precision - which is a floating value depending on the magnitude of the float).

By default, Squeak/Pharo round to nearest float, tie to even (round to even significand with last bit = 0 in case of exact tie between 2 floats), which is the default rounding mode in IEEE 754.

**Comment by olekscode** [comment]
Thank you for the explanation @nicolas-cellier-aka-nice 
This is very interesting!
