### ISSUE TITLE
EpInverseVisitor>>#visitTraitModification: is not implemented

### ISSUE THREAD

**Issue by hellerve** [guillep/pharo-core#11157]
**Describe the request**
The method for visiting trait modifications in the inverse visitor is not implemented, meaning trait modifications cannot be reverted.

**Expected behavior**
When selecting a change set with trait modifications, it should behave like all the other changes and emit an inverse trait modification.

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 

It should not be particularly hard to implement.

In addition, are you willing to help because after all Pharo is yours too?

I will happily add a PR.

**Screenshots**
None applicable.

**Version information:**
Tested on:
 - OS: macOS
 - Version: 12.3.1
 - Pharo Version 9

**Additional context**
None.

**Comment by MarcusDenker** [comment]
A PR would be nice

**Comment by hellerve** [comment]
Done!
