### ISSUE TITLE
Error while committing a class where we added a variable in classSide

### ISSUE THREAD

**Issue by aboubacardiawara** [guillep/pharo-core#11170]
**Bug description**
I create some class, where there was an instance variable in class side.
```smalltalk
SimpleTestResourceCopy class
	instanceVariableNames: 'preventAvailability'
```
When i tried to commit it using Iceberg, An error occurred (i loose the error description :(.  ).

**To Reproduce**
1. create a class
2. add an instance variable in class side
3. Save and try to commit it using Iceberg.

**Expected behavior**
Commit without any error.

**Version information:**
 - OS: Windows
 - Version: 11
 - Pharo Version 10

**Comment by jordanmontt** [comment]
We tested this in Windows 11 and MacOS and does not produce any error. I propose to close this issue
