### ISSUE TITLE
Enhance calypso browser: Menu for creating an empty new project

### ISSUE THREAD

**Issue by akevalion** [guillep/pharo-core#11201]
Currently calypso browser does not support a menu when you want to create an empty new project

**Describe the request**
In order to create new packages, users of calypso need to use the class definition, or the context menu.
But if you use the filter, the list of packages will be empty.
And you can not use anymore the context menu

**Expected behavior**
A context menu should appear when the list of packages is empty.

**Expected development cost**
This should be easy issue

Here is a video of the error:

https://user-images.githubusercontent.com/10532890/167130803-18135421-40b0-4de1-a854-eac03fcc5344.mov

**Comment by hernanmd** [comment]
It looks like this issue has been successfully [implemented](https://github.com/pharo-project/pharo/pull/12048) and can now be closed.

<img width="370" alt="Screenshot 2023-08-25 at 12 12 46" src="https://github.com/pharo-project/pharo/assets/4825959/9496f82a-3338-4732-b585-1edb885de745">

There is a detail whereby if you create a package and then delete the window title is not updated, nor is the definition template, which still refers to the deleted package. But I will open another issue for this.
