### ISSUE TITLE
categorize ZnStaticFileDecoratorDelegate class>>#decorate:servingFilesFrom:

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11216]
ZnStaticFileDecoratorDelegate class>>#decorate:servingFilesFrom: needs to have a category

Note: needs to be done upstream in Zinc and in the image

**Comment by svenvc** [comment]
https://github.com/svenvc/zinc/commit/0165f9a2855d23e3bc62b23931806cba9cf86326

**Comment by MarcusDenker** [comment]
sometimes I think we should just make "public" the default category and make it "ok" to not have to decide for every method a good category (the fact that there are so many uncategorized methods in real code is a hint that this is ok...)

**Comment by svenvc** [comment]
I never thought of it that way, it is a sensible idea.

I think that in real production code, good/consistent method categories make a lot of sense.

In this case it is a small example, and a bit of a weird one at that, I could not decide what to do, the method does create an instance but it is named oddly. I also don't remember writing that code, maybe it was contributed.

**Comment by astares** [comment]
@MarcusDenker Dislike the idea - because we might end up with classes with all methods in single category "public" as people are lazy and it would not really solve the problem of having intention revealing method categorization.
