### ISSUE TITLE
Don't let putting breakpoints on methods in Inspector on an OCDBox

### ISSUE THREAD

**Issue by DanielCamSan** [guillep/pharo-core#11213]
**Bug description**

**To Reproduce**
1. Go to 'inspector in a OCDBox instance'
2. Click on 'Meta'
3. Click on OCDBox in class hierarchy
4. Right Click on any method
5. See error

**Expected behavior**
A contextual menu with 3 options:  install a halt on call through, Inspect it and Browse it

**Screenshots**
![image](https://user-images.githubusercontent.com/45604840/167638797-749be644-fcff-49ae-b2cb-4936d0183c64.png)

**Version information:**
 - OS: Windows 10
 - Pharo Version 10

**Expected development cost**
To solve the issue i have to  remove the canBeExecuted method from class StBreakpointCommand.

**Comment by StevenCostiou** [comment]
This problem is due to https://github.com/pharo-spec/NewTools/issues/349 @MarcusDenker

**Comment by MarcusDenker** [comment]
I did a PR with a fix: https://github.com/pharo-spec/NewTools/pull/387
