### ISSUE TITLE
[CleanBlocks] Announcements defined via # when:do:

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11220]
**Bug description**
when:do:  with a CleanBock as a parameter does not work.

**To Reproduce**
1. Set the cleanblock option in the compiler Setting
2. Do "OpalCompiler recompileAll"
3. run #testHandleSubscriberClass

**More...**

It calls #receiver on the block, in AnnouncementSubscription>>#valuable:

```
valuable: aValuable
	"Used when subscriber should be extracted from valuable object"
	self action:  aValuable.
	self subscriber: aValuable receiver.
	
```

receiver is now exactly what a clean block does *not* know. 

The problem now is that yes, the static case is trivial to solve: We can just disable clean
blocks for now (for a transition period) in all methods that send when:do: with a static block. 

But that does not help if the when:do: parameter is not the block statically, but a variable or result of some expression. The cases should be happening not that often, though,

We know the method statically where the block comes from (via the outerCode pointer), so we can make a good
Transcript output for that case to warn users.

**Comment by MarcusDenker** [comment]
The static case can be solved, when the when:do: has the block directly, we can just walk up the stack to find the sender:

```
valuable: aValuable
	"Used when subscriber should be extracted from valuable object"
	| receiver |
	self action:  aValuable.
	receiver := aValuable receiver.
	"Clean blocks do not know the receiver"
	(receiver isNil and: [aValuable isBlock and: [ aValuable isClean ]]) ifTrue: [
		"A clean block was passed. In most cases, the block is defined statically, in this case we can discover
		the receiver. This fails if the block is defined in another method, we print a Warning"
		| contextOfSubsriptionSend |
		contextOfSubsriptionSend := thisContext sender sender.
		(contextOfSubsriptionSend method == aValuable compiledBlock method) 
			ifTrue: [ receiver := contextOfSubsriptionSend receiver ] 
			ifFalse: [ self traceCr: 'WARNING: can not find the receiver, use #when:do:for: in' ,contextOfSubsriptionSend method displayString ] ].
	self subscriber: receiver

```

But this does not work for method like e.g. SpExecutableLayout>>#whenChildrenAddedDo:

```
whenChildrenAddedDo: aBlock

	self announcer
		when: SpChildrenAdded
		do: aBlock

```

In practice, the blocks are never clean, as they at least do self sends or reference a temp...

What we could do:
- refactor in the system these cases to use when:do:for:  
- have the code above with the Transcript output for external code 
- document it well in the release notes

**Comment by dionisiydk** [comment]
I wonder how well it is known and expected behaviour that when:do: subscription extracts a subscriber from given block?
I always thought it does not allow the further unsubscription due to the lack of subscriber.
Now your finding looks cool. But I doubt anybody knows about it.
So my point is to simply remove this hidden feature. #when:do: does not need a subscriber at all. It will use nil or some better undefined value for this.

**Comment by Ducasse** [comment]
Where the receiver is coming from? Who is setting it in the block? I'm confused. 
In any case the use of context above is out of question because it is insane. 

```
valuable: aValuable
	"Used when subscriber should be extracted from valuable object"
	self action:  aValuable.
	self subscriber: aValuable receiver.
```

**Comment by Ducasse** [comment]
```
when: anAnnouncementClass send: aSelector to: anObject
	"Declare that when anAnnouncementClass is raised, anObject should receive the message aSelector.
    When the message expects one argument (eg #fooAnnouncement:) the announcement is passed as argument.
    When the message expects two arguments (eg #fooAnnouncement:announcer:) both the announcement and 
    the announcer are passed as argument"

	^ self
		when: anAnnouncementClass
		do: (MessageSend receiver: anObject selector: aSelector)
```

and I do not even understand why a block accept receiver?

```
[  ] receiver
```

**Comment by MarcusDenker** [comment]
The tests test for it... but indeed, the code is bad.

It would be nice to just remove this feature and make it explicit: Use  when:do:for: if you need the receiver.

**Comment by MarcusDenker** [comment]
tests are:

- AnnouncerTest>>#testAccessingSubscribers
- AnnouncerTest>>#testHandleSubscriberClass
