### ISSUE TITLE
GitHub Rate limiting for CI

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11222]
**Bug description**

Depending on usage, we get this:

```
	IceGitHubError: API rate limit exceeded for <IP of Inria cloud gateway server>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

```

**Comment by kasperosterbye** [comment]
Yes, I ran into this one in connection with a github interface for downloadning microdown documents from github directly.
I was not able to find any obvious way around the issue. For microdown I do some caching which seems to help somewhat.

For projects which just distribute binaries, it might be possible to use a project wide key which ups the number of calls per hour from 50 to 5000 or so. But the manuals explicitly states not to distribute the key. 

Perhaps one should write to github and ask for their suggestion?

**Comment by kasperosterbye** [comment]
I copied the issue to Iceberg. https://github.com/pharo-vcs/iceberg/issues/1588.
Perhaps close it here @MarcusDenker.

**Comment by MarcusDenker** [comment]
Duplicate of https://github.com/pharo-project/pharo/issues/12285
