### ISSUE TITLE
String>> copyReplaceAll:with: is not working as expected

### ISSUE THREAD

**Issue by jordanmontt** [guillep/pharo-core#11221]
I would expect that this code:

```st
'#( #( 13421525235235235235 ) #( 3 ) #( 0.1 ) #( 0.000005 ) #( 241241241124124124 ) #( 6412412412414 ) #(45345) #(5) #(53) #(5) #(3) #(1) #(2) #(1) #(0.09) #(0.4) #(0.0009) #(5) #(234242342423423) #(0.9888) #(0.0000009) )' copyReplaceTokens: '#(' with: '['
```

produces this result: `[ [ 13421525235235235235 ) [ 3 ) [ 0.1 ) [ 0.000005 ) [ 241241241124124124 ) [ 6412412412414 ) [45345) [5) [53) [5) [3) [1) [2) [1) [0.09) [0.4) [0.0009) [5) [234242342423423) [0.9888) [0.0000009) )`

but instead, it produces this one: `[ [ 13421525235235235235 ) [ 3 ) [ 0.1 ) [ 0.000005 ) [ 241241241124124124 ) [ 6412412412414 ) #(45345) #(5) #(53) #(5) #(3) #(1) #(2) #(1) #(0.09) #(0.4) #(0.0009) #(5) #(234242342423423) #(0.9888) #(0.0000009) )`

Pharo 11

**Comment by guillep** [comment]
Be careful, you're using in your code `copyReplaceTokens:with:` instead of `copyReplaceAll:with:`. If I try your example with that it works properly.

```
'#( #( 13421525235235235235 ) #( 3 ) #( 0.1 ) #( 0.000005 ) #( 241241241124124124 ) #( 6412412412414 ) #(45345) #(5) #(53) #(5) #(3) #(1) #(2) #(1) #(0.09) #(0.4) #(0.0009) #(5) #(234242342423423) #(0.9888) #(0.0000009) )' copyReplaceAll: '#(' with: '[' .
		
	"'[ [ 13421525235235235235 ) [ 3 ) [ 0.1 ) [ 0.000005 ) [ 241241241124124124 ) [ 6412412412414 ) [45345) [5) [53) [5) [3) [1) [2) [1) [0.09) [0.4) [0.0009) [5) [234242342423423) [0.9888) [0.0000009) )'"
```

**Comment by jordanmontt** [comment]
Haha... didn't read properly, sorry
