### ISSUE TITLE
[Pharo 11] Calypso class comment code highlighting colors are not readable in dark theme

### ISSUE THREAD

**Issue by jordanmontt** [guillep/pharo-core#11232]
If you enable dark theme, the code in a class comment, using microdown parser, is not readable

<img width="1329" alt="Capture d’écran 2022-05-13 à 16 49 19" src="https://user-images.githubusercontent.com/33934979/168309356-e3195b37-c19e-45f4-a74d-b393263327c1.png">

**Comment by kasperosterbye** [comment]
Indeed that is the case.
It is fixed in the development version of the code, but not integrated into the Pharo release.

**Comment by Ducasse** [comment]
Ok then I will close this issue

**Comment by MarcusDenker** [comment]
this is fixed
