### ISSUE TITLE
Test Runner list selections are very slow

### ISSUE THREAD

**Issue by Shaping** [guillep/pharo-core#11236]
OS: Windows 10
Pharo version: 10 64-bit (stable)

1. Open Test Runner.
2. Select all packages, and note selection is not indicated for a very long time, about 20 seconds.
3. Select all TestCases, and note selection is not indicated for a very long time., about 20 seconds.

![image](https://user-images.githubusercontent.com/12146957/168661703-fa5f784a-fb7b-4c0c-b3b6-a134ef61fee6.png)

The above image shows a run of all tests in the image.  It took about 10 minutes.   The GUI should be more responsive.  There should also be some indication that the testing is ongoing besides the sometimes change test counts, which can be unchanging for long periods.  Would an hourglass cursor work?  The Test Runner window seems effectively modal, and responses happen in windows outside Test Runner.

**Comment by jordanmontt** [comment]
We tried to reproduce this and we saw that this problem is only when you select all with `cmd + a`. If you right click and select "select all" it does not take time to load

**Comment by hernanmd** [comment]
This issue can be closed now as #14534 has been merged into Pharo 12.

**Comment by jordanmontt** [comment]
Yes, this is fixed on Pharo 12. I will close this issue
