### ISSUE TITLE
Inspector Extensions for Zinc in P10/P11

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#11233]
With the new capabilities of inspector extensions using Spec2 it would be nice to have 
more additional custom inspector extensions - for instance for Zinc.

**Comment by astares** [comment]
```Smalltalk
inspectionHeaders: aBuilder
	<inspectorPresentationOrder: 10 title: 'Headers'>
	
	^ aBuilder newTable 
		addColumn: (SpStringTableColumn 
			title: 'Key'
			evaluated: [ :each | StObjectPrinter asTruncatedTextFrom: each key ])
			beSortable;
		addColumn: (SpStringTableColumn 
			title: 'Value' 
			evaluated: [ :each | StObjectPrinter asTruncatedTextFrom: each value ])
			beSortable;
		items: (self headers headers associations collect: [:e | StInspectorAssociationNode hostObject: e ]);
		yourself
```
allows to directly see the headers on the **ZnResponse** instances:

![image](https://user-images.githubusercontent.com/5980033/168552857-fc27c2fb-0dd9-4f08-bcac-109154f166fd.png)

**Comment by astares** [comment]
```Smalltalk
inspectionEntity: aBuilder
	<inspectorPresentationOrder: 10 title: 'Entity'>
	 
	^ aBuilder newText
		text: self entity contents asString;
		yourself
```
allows to browse the response contents directly:

![image](https://user-images.githubusercontent.com/5980033/168553022-9898f4bd-5856-42a2-989d-cf5e7c818cec.png)

**Comment by astares** [comment]
@svenvc / @MarcusDenker 

As Zinc is externally hosted the questions is in which repo / package we can put them and how to load.

Following what NewTools provide it would make sense to have them in a "Zinc-HTTP-Inspector-Extensions":

![image](https://user-images.githubusercontent.com/5980033/168553242-15615b1b-11e6-4f05-816d-08dc95875520.png)

**Comment by svenvc** [comment]
Yes this would be very nice to have, it is missing right now.

I agree, it is an add-on that would best go into "Zinc-HTTP-Inspector-Extensions"

**Comment by astares** [comment]
@svenvc / @estebanlm / @MarcusDenker / @demarey 

So how could we introduce this? 

Is it better to place them in Zinc repo (Option 1) or would it better fit to provide inspector extensions in NewTools repo (Option 2) ? I personally think that it would be better with option 1 as the tool extensions belong to the code they extend

I do not know how Zinc contributions are handled at the moment? 

a) is such new code added in svens repo first and then introduced into Pharo repo
b) can it be introduced in Pharo repo and then resynched to your repo

**Comment by svenvc** [comment]
If you want, do a PR to zinc first, then we can test it a bit, after that it can simply be loaded to pharo

**Comment by demarey** [comment]
> @svenvc / @estebanlm / @MarcusDenker / @demarey
> 
> So how could we introduce this?
> 
> Is it better to place them in Zinc repo (Option 1) or would it better fit to provide inspector extensions in NewTools repo (Option 2) ? I personally think that it would be better with option 1 as the tool extensions belong to the code they extend

I agree: option 1 is better. It should be loadable independently of core Zinc packages. Thanks

**Comment by astares** [comment]
Done Zinc repo. See https://github.com/svenvc/zinc/issues/93

**Comment by hernanmd** [comment]
I think this issue can be closed then.
