### ISSUE TITLE
Fluid and Trait tests create class that are not clean up

### ISSUE THREAD

**Issue by Alisu** [guillep/pharo-core#11246]
**Describe the problem**
Fluid tests create a Point3 class for test that is not clean up.
Same for Trait tests that create Trait 1 2 3 4 5 .

**Proposal**
Create the classes on setup and remove them on tearDown.

**Additional context**
Half a sprint.

**Comment by MarcusDenker** [comment]
Point3 has been fixed, the Trait 1-4 are there already in a fresh image, Tait5 does not exist.

So this seems to be fixed

**Comment by jecisc** [comment]
I've fixed a lot of things in Fluid cleaning recently so it's highly possible that all of those are now fixed
