### ISSUE TITLE
Underscore in class name breaks text completion (2)

### ISSUE THREAD

**Issue by sonibla** [guillep/pharo-core#11265]
(https://github.com/pharo-project/pharo/issues/10986 is fixed, this is another issue)

**Bug description**
Text completion doesn't show up after "_"

**To Reproduce**
Create a class named My_Class

Before "_", no issue
![1](https://user-images.githubusercontent.com/49032546/169828178-48b7ad16-19dd-437e-a5b7-da01f84fc15a.PNG)

Once you type "_" no entries are showing up
![3](https://user-images.githubusercontent.com/49032546/169828206-542e91ef-7773-4e1f-9a7a-5fadb9b77a7f.PNG)

Example with another character: (expected behavior)
![2](https://user-images.githubusercontent.com/49032546/169828188-c2337d99-552e-46ac-8483-fc578f52218e.PNG)

**Version information:**
Windows 10 
Pharo 10.0.0
Build information: Pharo-10.0.0+build.519.sha.180dea8d1995a5199e3c7f6ffcae4b9880ffad77 (64 Bit)

**Comment by hogoww** [comment]
fix available, currently preparing test case & PR

**Comment by guillep** [comment]
Woo, super cool!
