### ISSUE TITLE
Cleanup: could we simplify RGMethodDefinition>>#isExtension

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#11272]
I guess we could substitute the marked part in the method RGMethodDefinition>>#isExtension 

![image](https://user-images.githubusercontent.com/5980033/169890595-67d09276-32ba-4525-aff8-f5b4f3e57537.png)

with 
```Smalltalk
self isExtensionMethod
```
as #isExtensionMethod is implemented as:

```Smalltalk
isExtensionMethod
	^ category beginsWith: '*'
```

**Comment by jordanmontt** [comment]
We just checked with @hernanmd and we saw that the temp variable `prot` is a `ByteString` so we cannot use `isExtensionMethod`. We propose to close this issue
