### ISSUE TITLE
Changing font size from small to medium causes extremely large text to appear in method-pane tabs 

### ISSUE THREAD

**Issue by Shaping** [guillep/pharo-core#11294]
In Settings, changing the font size from small to medium causes extremely large text to appear in method-pane tabs. The text in the Finder is also extremely large.

OS: Windows 10
Pharo version: 9.0

In Settings' Standard fonts, select medium.
Set default font to Source Sans Pro Regular 13.
Select Force All.
Click on System Browser (to update it; it does not update automatically and should), or open a System Browser.
Note the extremely large, almost impossible to read text in the method-pane tabs.
image:

![image](https://user-images.githubusercontent.com/12146957/170155320-6d0aef70-7c32-4548-b0c8-e476f67ba486.png)
![image](https://user-images.githubusercontent.com/12146957/170155422-6fe9f4d4-5c84-41ae-b332-24cb59164996.png)

**Comment by Shaping** [comment]
If someone can direct me to the relevant font-related classes, I will try to fix this bug.

**Comment by Shaping** [comment]
I am trying to port to Pharo (for about 16 years).  I want to do that now.  The problem above practically prevents the port.  Is the problem above fixed yet?

**Comment by Ducasse** [comment]
Do you use SpStyle? And yes this should be improved. Now money/time is always a concern.
I will let esteban reply when he is back from vacation.

**Comment by estebanlm** [comment]
To be honest, changing the font size is not the right way to affect your world.
Scaling the UI is.
Yes, it is there so *it should* work, but so many things are complex when dealing with fonts that many other systems (e.g. macOS) have adopted the scaling solution, and I am more for remove that option in the future than to try a heavy work to fix it.

This, however has nothing to do with Spec and you should not change the font on settings browser and expect it works on your application. Instead, you should create an application and add your styles there, later apply the style to your components. 

Some documentation for styles : 

https://thepharo.dev/2021/10/25/using-styles-in-spec-applications/ 


<blockquote><img src="https://masteringobjects.files.wordpress.com/2021/10/capture-decc81cran-2021-10-22-acc80-19.04.52.png" width="48" align="right"><div><img src="https://masteringobjects.files.wordpress.com/2020/03/cropped-icon-lighthouse-512x512-1-1.png?w=192" height="14"> The Pharo Dev: Mastering Objects</div><div><strong><a href="https://thepharo.dev/2021/10/25/using-styles-in-spec-applications/">Using styles in Spec applications</a></strong></div><div>In this post we will see how to use custom styles in Spec applications. We will start to present styles and then build a little editor as the one displayed hereafter. We will show that an applicati…</div></blockquote>

**Comment by estebanlm** [comment]
btw you can change the scale by looking for "display scale factor" in the settings browser.
