### ISSUE TITLE
Fuel update causes DNU in iceberg

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#11322]
**Bug description**
Here is an example to reproduce:
```smalltalk
IceCredentialStore current
		storeCredential: (IcePlaintextCredentials new 
			username: 'foo';
			password: 'bar';
			host: 'github.com';
			yourself).
```
After the evaluation of the code snippet, you get:
`Instance of FLMaterializer class did not understand #materializeFromFileNamed:`

**Expected behavior**
No error

**Version information:**
 since Pharo 11 f14f93ce19af5dce174fcabf7fae6a488eaa19d3
related to https://github.com/pharo-project/pharo/pull/11133

@theseion any idea?

**Comment by MarcusDenker** [comment]
It seems to be used by Roassal, too, see #11324

**Comment by theseion** [comment]
That is an accident. I'm sure that I had changed that too. I'll open a new PR with the fix.

**Comment by demarey** [comment]
Thanks @theseion

**Comment by kasperosterbye** [comment]
I have something similar, it is in pharo 11, build 74,75,76, but absent in 73. I get these notifications on startup, and cannot use iceberg.
![Pharo-11-build74](https://user-images.githubusercontent.com/17723745/172545108-74832d41-41dc-497d-b470-727f607297eb.png)

**Comment by theseion** [comment]
Thanks @kasperosterbye, we're working on it.

**Comment by astares** [comment]
Still happening in recent Pharo 11:

![image](https://user-images.githubusercontent.com/5980033/172712845-dd3718aa-c010-45b3-bbfa-35d7f6cba9ba.png)

Image
-----
/home/kiwi/pharo/pharo11/build/Pharo.image
Pharo11.0.0
Build information: Pharo-11.0.0+build.76.sha.540ecb28a2c790b3ce5a862c735bd3b6a14ce0a0 (64 Bit)
Unnamed

**Comment by theseion** [comment]
That would suggest that that build doesn't use the newest Iceberg version yet. The code is clearly there: https://github.com/pharo-vcs/iceberg/blob/ba4da3970c4db52e78e7d97e4a6ea2c69ddc2ca2/Iceberg/IceCredentialStore.class.st#L112.

<blockquote><img src="https://opengraph.githubassets.com/1dc46bddc266ca83ac3bdb3fdc4595a089e8ace60d720f14708c56ba9227b2e6/pharo-vcs/iceberg" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-vcs/iceberg">iceberg/IceCredentialStore.class.st at ba4da3970c4db52e78e7d97e4a6ea2c69ddc2ca2 · pharo-vcs/iceberg</a></strong></div><div>Iceberg is the main toolset for handling VCS in Pharo. - iceberg/IceCredentialStore.class.st at ba4da3970c4db52e78e7d97e4a6ea2c69ddc2ca2 · pharo-vcs/iceberg</div></blockquote>
