### ISSUE TITLE
Fuel 5: update Roassal needs to be merged

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11324]
**Bug description**
We have a test failing RSMonitorEventsTest>>testWriteToFile

```
Error
Message not understood: FLSerializer class >> #serializeToByteArray:
Stacktrace
MessageNotUnderstood
Message not understood: FLSerializer class >> #serializeToByteArray:
FLSerializer class(Object)>>doesNotUnderstand: #serializeToByteArray:
RSMonitorEventsTest>>testWriteToFile
```

**Comment by MarcusDenker** [comment]
This is fixed by https://github.com/ObjectProfile/Roassal3/pull/439 which has been merged, but it is not yet in Pharo

**Comment by MarcusDenker** [comment]
@akevalion

**Comment by akevalion** [comment]
I will produce a release

**Comment by akevalion** [comment]
It will take time because materializeFromFileNamed: is missing in pharo11

**Comment by MarcusDenker** [comment]
This is a problem for other clients, too, see https://github.com/pharo-project/pharo/issues/11322

Maybe we should add it back?

**Comment by akevalion** [comment]
Roassal3 does not depend on  materializeFromFileNamed:, but Iceberg does. I will try to produce the the release in pharo10

**Comment by theseion** [comment]
This PR fixes the issue in Iceberg: https://github.com/pharo-vcs/iceberg/pull/1593

**Comment by MarcusDenker** [comment]
This will be done by https://github.com/pharo-project/pharo/issues/11327, I close this issue
