### ISSUE TITLE
DAPackageRelationGraphDiffTest raises PotentialOutDatedDependencyWarning

### ISSUE THREAD

**Issue by estebanlm** [guillep/pharo-core#11334]
**Bug description**
The execution of `DAPackageRelationGraphDiffTest` now fails.

**To Reproduce**
1. Open calypso in `DAPackageRelationGraphDiffTest`
2. Click on the test execution button

**Expected behavior**
Test should pass :)

**Additional context**
I wonder how is possible that this is broken?

**Comment by MarcusDenker** [comment]
It seems that this does not fail but instead raises an Exception (PotentialOutDatedDependencyWarning)

The result is that we get an error when running it interactively, but on the CI it I think just prints out the warning and does not fail
