### ISSUE TITLE
Dead code in RBMethodChange

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11339]
- class:protocol:source:
- accept:notiying:
do not seem to be invoked. 

Tx CB2

**Comment by MarcusDenker** [comment]
- #class:protocol:source: is called by RBAddMethodChange>>#accept:notifying:
- #accept:notifying: is a method called by the Editor when accepting code, see RubPluggableTextMorphExample>>#newScrolledTextMorph

**Comment by MarcusDenker** [comment]
(The CB2 tool analyses *extension methods* just as local methods of the class, but the analysis is restricted to the defined model. This leads to many false positives)
