### ISSUE TITLE
Pharo 10: Backport MiniDrTests raise error #11180

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#11333]
Open Pharo 10 and run tests in DrTest UI gives a DNU:

![image](https://user-images.githubusercontent.com/5980033/172680905-333ed152-d1f8-4987-8f69-686f8bc0ce13.png)

**Comment by astares** [comment]
@estebanlm / @MarcusDenker I guess this needs to be tagged to be fixed either for an P10 update or for at least Pharo 11
(unfortunately I do not have the permission to tag the issue)

**Comment by MarcusDenker** [comment]
This has ben fixed in Pharo11: https://github.com/pharo-project/pharo/pull/11180

**Comment by MarcusDenker** [comment]
This was merged
