### ISSUE TITLE
Tests failing on CI: RSDSMTest>>testLabelsTopPosition on Linux

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11359]
**Bug description**
After merging , https://github.com/pharo-project/pharo/pull/11328, RSDSMTest>>testLabelsTopPosition is failing often on the Linux CI

```
Error
Assertion failed
Stacktrace
TestFailure
Assertion failed
RSDSMTest(TestAsserter)>>assert:description:resumable:
RSDSMTest(TestAsserter)>>assert:description:
RSDSMTest(Object)>>assert:
[ :box : label | 
		| x x1 x2 |
		x := label encompassingRectangle bottomRight x.
		x1 := box encompassingRectangle topLeft x.
		x2 := box encompassingRectangle topRight x.
		self assert: (x between: x1 and: x2)
		 ] in RSDSMTest>>testLabelsTopPosition
Array(SequenceableCollection)>>with:do:
RSDSMTest>>testLabelsTopPosition
RSDSMTest(TestCase)>>performTest
```

**Comment by MarcusDenker** [comment]
@akevalion

**Comment by akevalion** [comment]
Hi I will check it

**Comment by akevalion** [comment]
I have change the test, will be present in next roassal3 release

**Comment by MarcusDenker** [comment]
@akevalion it would be good to not wait too long: this test fails for *every* run, which means we have to manually check every PR run just to check if indeed just this one tests failed or more.

**Comment by akevalion** [comment]
I will fix it now

**Comment by akevalion** [comment]
@MarcusDenker I have created a pull request, I am waiting the CI results

**Comment by MarcusDenker** [comment]
Fixed by merge
