### ISSUE TITLE
Cleanup: Wrongly named Icons

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11356]
**Describe the problem**
If you put a traceCr into the #ifPresent: case at the end of ThemeIcons>>#iconNamed:ifNone:, you see a lot of cases where
we use the old style name for icons and Forms.

We should change all the places where we run into the slow backward compatibility case.

**Comment by astares** [comment]
Good catch!

**Comment by MarcusDenker** [comment]
More to do:

- Roassal uses strings: https://github.com/ObjectProfile/Roassal3/issues/456
-

**Comment by akevalion** [comment]
Can we close this issue?
