### ISSUE TITLE
Cannot commit when adding a class instance variable

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#11370]
**Bug description**
When you defined a class instance variable (not a class variable), it is impossible to commit with Iceberg.
The modification definition is nil leading to a DNU.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a class variable on one class.
2. Open Iceberg
3. Commit and see the error message

**Version information:**
  - Pharo Version 11.0
  -

**Comment by jordanmontt** [comment]
We tried now with @guillep and we were not able to reproduce the issue.

**Comment by jordanmontt** [comment]
Update

We were able to reproduce. These are the updated steps:

1. Clone pharo repository
2. Add a class instance variable (not a class variable) in the class `RBNode`
3. Commit and see the error message

<img width="1387" alt="Capture d’écran 2022-06-24 à 14 40 05" src="https://user-images.githubusercontent.com/33934979/175537750-7d9937cb-cd96-410a-a1b0-f70c807ad99d.png">
