### ISSUE TITLE
Loading changes on IRBytecodeGenerator crash the VM

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#11386]
I use

IMAGE: Pharo11.0.0 Build information: Pharo-11.0.0+build.94.sha.2058cf22ed1e66f15547039b84ea9c97704d68b9 (64 Bit)
and

VM
pharo
CoInterpreter * VMMaker-tonel.1 uuid: aa6234f4-799d-0d00-90d1-c90e092bce84 Jun 10 2022
StackToRegisterMappingCogit * VMMaker-tonel.1 uuid: aa6234f4-799d-0d00-90d1-c90e092bce84 Jun 10 2022
v9.0.15 - Commit: b487900 - Date: 2022-06-02 09:48:57 +0200

Pharo 9.0.15 built on Jun 10 2022 15:52:11 Compiler: 5.4.0 20160609
VMMaker versionString v9.0.15 - Commit: b487900 - Date: 2022-06-02 09:48:57 +0200
CoInterpreter * VMMaker-tonel.1 uuid: aa6234f4-799d-0d00-90d1-c90e092bce84 Jun 10 2022
StackToRegisterMappingCogit * VMMaker-tonel.1 uuid: aa6234f4-799d-0d00-90d1-c90e092bce84 Jun 10 2022

Meanwhile @MarcusDenker has merged the changes for: https://github.com/pharo-project/pharo/pull/11383/files
but the CI build of  a fresh image is not yet ready.

So I loaded manually the next commit:

![image](https://user-images.githubusercontent.com/5980033/174596898-6639356f-fd4a-41b5-92f6-22df7a644a13.png)

and this crashed the VM:
-------------------------------------------------------------------------------------------
PharoVM version:5.0-Pharo 9.0.15 built on Jun 10 2022 15:52:10 Compiler: 5.4.0 20160609 5.4.0 20160609 [Production Spur 64-bit VM]
Built from: CoInterpreter * VMMaker-tonel.1 uuid: aa6234f4-799d-0d00-90d1-c90e092bce84 Jun 10 2022
 With:StackToRegisterMappingCogit * VMMaker-tonel.1 uuid: aa6234f4-799d-0d00-90d1-c90e092bce84 Jun 10 2022
 Revision: v9.0.15 - Commit: b487900 - Date: 2022-06-02 09:48:57 +0200

C stack backtrace & registers:
	rax 0x00000000 rbx 0x00000002 rcx 0x00000000 rdx 0x17e5fc00
	rdi 0x00000000 rsi 0x00000000 rbp 0x7ffd96ba0a20 rsp 0x7ffd96ba0930
	r8  0x7f6f0e0f5ec0 r9  0x00000008 r10 0x00000000 r11 0x00000000
	r12 0x00000000 r13 0x16945dc9 r14 0x7ffd96bb4550 r15 0x001d4320
	rip 0x7f6f0de99a90
*/home/kiwi/pharo/pharo11/build/pharo-vm/lib/libPharoVMCore.so(+0x87a90)[0x7f6f0de99a90]
/home/kiwi/pharo/pharo11/build/pharo-vm/lib/libPharoVMCore.so(+0xc41ec)[0x7f6f0ded61ec]
/home/kiwi/pharo/pharo11/build/pharo-vm/lib/libPharoVMCore.so(doReport+0xb5)[0x7f6f0ded64d5]
/home/kiwi/pharo/pharo11/build/pharo-vm/lib/libPharoVMCore.so(sigsegv+0x14)[0x7f6f0ded6544]
/lib/x86_64-linux-gnu/libc.so.6(+0x43090)[0x7f6f0dc63090]
/home/kiwi/pharo/pharo11/build/pharo-vm/lib/libPharoVMCore.so(+0x87a90)[0x7f6f0de99a90]
/home/kiwi/pharo/pharo11/build/pharo-vm/lib/libPharoVMCore.so(interpret+0x8163)[0x7f6f0dec7813]
/home/kiwi/pharo/pharo11/build/pharo-vm/lib/libPharoVMCore.so(+0xbadd2)[0x7f6f0deccdd2]
/home/kiwi/pharo/pharo11/build/pharo-vm/lib/libPharoVMCore.so(interpret+0x5f6)[0x7f6f0debfca6]
/home/kiwi/pharo/pharo11/build/pharo-vm/lib/libPharoVMCore.so(+0x25d8e)[0x7f6f0de37d8e]
/home/kiwi/pharo/pharo11/build/pharo-vm/lib/libPharoVMCore.so(vm_main_with_parameters+0x278)[0x7f6f0de38018]
/home/kiwi/pharo/pharo11/build/pharo-vm/lib/libPharoVMCore.so(vm_main+0xb8)[0x7f6f0de38278]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f6f0dc44083]
/home/kiwi/pharo/pharo11/build/pharo-vm/lib/pharo[0x400619]
[0x0]

All Smalltalk process stacks (active first):
Process         0x1a6c9340 priority 40
    0x7ffd96bb4550 I IRBytecodeGenerator>pushConsArray: 0x171dfc70: a(n) IRBytecodeGenerator
    0x7ffd96bb4588 M IRTranslator>visitPushArray: 0x171dfc10: a(n) IRTranslator
    0x7ffd96bb45c0 M IRPushArray>accept: 0x171df548: a(n) IRPushArray
    0x7ffd96bb45f8 M IRTranslator(IRVisitor)>visitNode: 0x171dfc10: a(n) IRTranslator
    0x7ffd96bb4630 M IRTranslator>visitInstruction: 0x171dfc10: a(n) IRTranslator
    0x7ffd96bb4668 M [] in IRTranslator>visitSequence: 0x171dfc10: a(n) IRTranslator
    0x7ffd96bb46b0 M OrderedCollection>do: 0x171deb00: a(n) OrderedCollection
    0x7ffd96bb46e8 M IRSequence>do: 0x171deae0: a(n) IRSequence
    0x7ffd96bb4720 M IRTranslator(IRVisitor)>visitSequence: 0x171dfc10: a(n) IRTranslator
    0x7ffd96bb4758 M IRTranslator>visitSequence: 0x171dfc10: a(n) IRTranslator
    0x7ffd96bb4790 M IRSequence>accept: 0x171deae0: a(n) IRSequence
    0x7ffd96bb47c8 M IRTranslator(IRVisitor)>visitNode: 0x171dfc10: a(n) IRTranslator
    0x7ffd96bb4800 M [] in IRTranslator>visitNodes: 0x171dfc10: a(n) IRTranslator
    0x7ffd96bb4848 M SortedCollection(OrderedCollection)>do: 0x171e1350: a(n) SortedCollection
    0x7ffd96bb4880 M IRTranslator(IRVisitor)>visitNodes: 0x171dfc10: a(n) IRTranslator
    0x7ffd96bb48b8 M IRTranslator>visitSequences: 0x171dfc10: a(n) IRTranslator
    0x7ffd96bb48f0 M IRTranslator>visitMethod: 0x171dfc10: a(n) IRTranslator
    0x7ffd96bb4928 M IRMethod>accept: 0x171de628: a(n) IRMethod
    0x7ffd96bb4960 M IRTranslator(IRVisitor)>visitNode: 0x171dfc10: a(n) IRTranslator
    0x7ffd96bb49a8 M IRMethod>generate: 0x171de628: a(n) IRMethod
    0x7ffd96bb49e0 M IRMethod>compiledMethodWith: 0x171de628: a(n) IRMethod
    0x7ffd96bb4a18 M RBMethodNode>generate: 0x171d8a08: a(n) RBMethodNode
    0x7ffd96bba500 I RBMethodNode>generateWithSource 0x171d8a08: a(n) RBMethodNode
    0x7ffd96bba548 I OpalCompiler>compileDoit 0x171d42e8: a(n) OpalCompiler
    0x7ffd96bba588 M [] in OpalCompiler>evaluate 0x171d42e8: a(n) OpalCompiler
    0x7ffd96bba5b8 M FullBlockClosure(BlockClosure)>on:do: 0x171d4c00: a(n) FullBlockClosure
    0x7ffd96bba610 I OpalCompiler>evaluate 0x171d42e8: a(n) OpalCompiler
    0x7ffd96bba650 I OpalCompiler>evaluate: 0x171d42e8: a(n) OpalCompiler
    0x7ffd96bba698 I MCClassDefinition>traitCompositionCompiled 0x1b820580: a(n) MCClassDefinition
    0x7ffd96bba6f0 I [] in MCClassDefinition>createClass 0x1b820580: a(n) MCClassDefinition
    0x7ffd96bba738 I ShiftClassInstaller>make: 0x171cef58: a(n) ShiftClassInstaller
    0x7ffd96bba780 I ShiftClassInstaller class>make: 0x17e76458: a(n) ShiftClassInstaller class
    0x7ffd96bba7c0 M [] in MCClassDefinition>createClass 0x1b820580: a(n) MCClassDefinition
    0x7ffd96bba7f0 M FullBlockClosure(BlockClosure)>on:do: 0x171ced90: a(n) FullBlockClosure
    0x7ffd96bba848 I MCClassDefinition>createClass 0x1b820580: a(n) MCClassDefinition
    0x7ffd96bba888 I MCClassDefinition>load 0x1b820580: a(n) MCClassDefinition
    0x7ffd96bba8c0 M [] in MCPackageLoader>loadClassDefinition: 0x1688d7b8: a(n) MCPackageLoader
    0x7ffd96bba8f0 M FullBlockClosure(BlockClosure)>on:do: 0x171ceb90: a(n) FullBlockClosure
    0x7ffd96bba930 M MCPackageLoader>loadClassDefinition: 0x1688d7b8: a(n) MCPackageLoader
    0x7ffd96bba968 M [] in MCPackageLoader>basicLoadDefinitions 0x1688d7b8: a(n) MCPackageLoader
    0x7ffd96bba9d0 M [] in OrderedCollection>do:displayingProgress:every: 0x1688da70: a(n) OrderedCollection
    0x7ffd96bbaa18 M OrderedCollection>do: 0x1688da70: a(n) OrderedCollection
    0x7ffd96bbc380 M [] in OrderedCollection>do:displayingProgress:every: 0x1688da70: a(n) OrderedCollection
    0x7ffd96bbc3b8 M FullBlockClosure(BlockClosure)>cull: 0x1688dd08: a(n) FullBlockClosure
    0x7ffd96bbc3f0 M [] in Job>run 0x1688d9f8: a(n) Job
    0x7ffd96bbc438 M [] in CurrentJob>value:during: 0x17f3ac98: a(n) CurrentJob
    0x7ffd96bbc478 M FullBlockClosure(BlockClosure)>ensure: 0x1688dd80: a(n) FullBlockClosure
    0x7ffd96bbc4c0 M CurrentJob(DynamicVariable)>value:during: 0x17f3ac98: a(n) CurrentJob
    0x7ffd96bbc500 M CurrentJob class(DynamicVariable class)>value:during: 0x17f2f708: a(n) CurrentJob class
    0x7ffd96bbc540 M [] in Job>run 0x1688d9f8: a(n) Job
    0x7ffd96bbc580 M FullBlockClosure(BlockClosure)>ensure: 0x1688dfb8: a(n) FullBlockClosure
    0x7ffd96bbc5c8 I Job>run 0x1688d9f8: a(n) Job
    0x7ffd96bbc608 I MorphicUIManager(UIManager)>displayProgress:from:to:during: 0x1b60ff00: a(n) MorphicUIManager
    0x7ffd96bbc668 I ByteString(String)>displayProgressFrom:to:during: 0x180eddd8: a(n) ByteString
    0x7ffd96bbc6d0 I OrderedCollection(Collection)>do:displayingProgress:every: 0x1688da70: a(n) OrderedCollection
    0x7ffd96bbc728 I OrderedCollection(Collection)>do:displayingProgress: 0x1688da70: a(n) OrderedCollection
    0x7ffd96bbc778 I MCPackageLoader>basicLoadDefinitions 0x1688d7b8: a(n) MCPackageLoader
    0x7ffd96bbc7a8 M [] in MCPackageLoader>basicLoad 0x1688d7b8: a(n) MCPackageLoader
    0x7ffd96bbc7e0 M [] in SourceFileArray>deferFlushDuring: 0x17e70078: a(n) SourceFileArray
    0x7ffd96bbc820 M FullBlockClosure(BlockClosure)>ensure: 0x1688e258: a(n) FullBlockClosure
    0x7ffd96bbc868 I SourceFileArray>deferFlushDuring: 0x17e70078: a(n) SourceFileArray
    0x7ffd96bbc8b0 I MCPackageLoader>basicLoad 0x1688d7b8: a(n) MCPackageLoader
    0x7ffd96bbc8e0 M [] in MCPackageLoader>load 0x1688d7b8: a(n) MCPackageLoader
    0x7ffd96bbc920 M FullBlockClosure(BlockClosure)>ensure: 0x1688e420: a(n) FullBlockClosure
    0x7ffd96bbc978 I MCPackageLoader>useChangeSetNamed:during: 0x1688d7b8: a(n) MCPackageLoader
    0x7ffd96bbc9c8 I MCPackageLoader>useNewChangeSetNamedLike:during: 0x1688d7b8: a(n) MCPackageLoader
    0x7ffd96bbca18 I MCPackageLoader>useNewChangeSetDuring: 0x1688d7b8: a(n) MCPackageLoader
    0x7ffd96bd64a8 I MCPackageLoader>load 0x1688d7b8: a(n) MCPackageLoader
    0x7ffd96bd64e8 I IceWorkingCopyPatcherVisitor>load 0x1688f7e8: a(n) IceWorkingCopyPatcherVisitor
    0x7ffd96bd6520 M [] in IceWorkingCopy>loadChangesInWorkingCopy: 0x19d8b758: a(n) IceWorkingCopy
    0x7ffd96bd6560 M FullBlockClosure(BlockClosure)>ensure: 0x1688f808: a(n) FullBlockClosure
    0x7ffd96bd65b0 I IceWorkingCopy>ignoreNotificationsDuring: 0x19d8b758: a(n) IceWorkingCopy
    0x7ffd96bd6600 I IceWorkingCopy>loadChangesInWorkingCopy: 0x19d8b758: a(n) IceWorkingCopy
    0x7ffd96bd6648 I IceCheckoutAlreadyLoadedPackages>checkoutOn: 0x1b7586a0: a(n) IceCheckoutAlreadyLoadedPackages
    0x7ffd96bd6690 I IceWorkingCopy>checkout: 0x19d8b758: a(n) IceWorkingCopy
    0x7ffd96bd66d8 I IceLibgitRepository(IceRepository)>checkout: 0x19d548e0: a(n) IceLibgitRepository
    0x7ffd96bd6720 I IceGitLocalBranch(IceCommitish)>checkout: 0x1b7881c0: a(n) IceGitLocalBranch
    0x7ffd96bd6768 I IceTipCheckoutModel>checkout 0x1b74e3e0: a(n) IceTipCheckoutModel
    0x7ffd96bd6798 M [] in IceTipCheckoutModel>executeCheckoutActionAndThen: 0x1b74e3e0: a(n) IceTipCheckoutModel
    0x7ffd96bd67d8 M [] in MorphicUIManager>informUser:during: 0x1b60ff00: a(n) MorphicUIManager
    0x7ffd96bd6818 M [] in MorphicUIManager>informUserDuring: 0x1b60ff00: a(n) MorphicUIManager
    0x7ffd96bd6850 M FullBlockClosure(BlockClosure)>cull: 0x1688ef58: a(n) FullBlockClosure
    0x7ffd96bd6888 M [] in Job>run 0x1688ddf8: a(n) Job
    0x7ffd96bd68d0 M [] in CurrentJob>value:during: 0x17f3ac98: a(n) CurrentJob
    0x7ffd96bd6910 M FullBlockClosure(BlockClosure)>ensure: 0x1688fa00: a(n) FullBlockClosure
    0x7ffd96bd6958 M CurrentJob(DynamicVariable)>value:during: 0x17f3ac98: a(n) CurrentJob
    0x7ffd96bd6998 M CurrentJob class(DynamicVariable class)>value:during: 0x17f2f708: a(n) CurrentJob class
    0x7ffd96bd69d8 M [] in Job>run 0x1688ddf8: a(n) Job
    0x7ffd96bd6a18 M FullBlockClosure(BlockClosure)>ensure: 0x1688fbe8: a(n) FullBlockClosure
    0x7ffd96bce590 I Job>run 0x1688ddf8: a(n) Job
    0x7ffd96bce5d0 I MorphicUIManager(UIManager)>displayProgress:from:to:during: 0x1b60ff00: a(n) MorphicUIManager
    0x7ffd96bce630 I MorphicUIManager>informUserDuring: 0x1b60ff00: a(n) MorphicUIManager
    0x7ffd96bce678 I MorphicUIManager(UIManager)>informUser:during: 0x1b60ff00: a(n) MorphicUIManager
    0x7ffd96bce6c8 I IceTipStandardAction>basicExecute 0x1688f180: a(n) IceTipStandardAction
    0x7ffd96bce6f8 M [] in IceTipStandardAction>execute 0x1688f180: a(n) IceTipStandardAction
    0x7ffd96bce728 M FullBlockClosure(BlockClosure)>on:do: 0x1688f1b0: a(n) FullBlockClosure
    0x7ffd96bce778 I IceTipStandardAction(IceTipAction)>withErrorHandlingDo: 0x1688f180: a(n) IceTipStandardAction
    0x7ffd96bce7c0 I IceTipStandardAction(IceTipAction)>execute 0x1688f180: a(n) IceTipStandardAction
    0x7ffd96bce800 I IceTipStandardAction>execute: 0x1688f180: a(n) IceTipStandardAction
    0x7ffd96bce848 I IceTipCheckoutModel>executeCheckoutActionAndThen: 0x1b74e3e0: a(n) IceTipCheckoutModel
    0x7ffd96bce890 I IceTipCheckoutPreviewBrowser>doCheckout 0x1b7880e0: a(n) IceTipCheckoutPreviewBrowser
    0x7ffd96bce8d0 I [] in IceTipCheckoutPreviewBrowser>newActionButton 0x1b7880e0: a(n) IceTipCheckoutPreviewBrowser
    0x7ffd96bce918 I SpButtonPresenter>performAction 0x168832a8: a(n) SpButtonPresenter
    0x7ffd96bce950 M SpMorphicButtonAdapter>action 0x1688f5f8: a(n) SpMorphicButtonAdapter
    0x7ffd96bce990 I PluggableButtonMorph>performAction: 0x16889068: a(n) PluggableButtonMorph
    0x7ffd96bce9d0 M [] in PluggableButtonMorph>mouseUp: 0x16889068: a(n) PluggableButtonMorph
    0x7ffd96bcea18 M Array(SequenceableCollection)>do: 0x1688e6a0: a(n) Array
    0x7ffd96bca488 I PluggableButtonMorph>mouseUp: 0x16889068: a(n) PluggableButtonMorph
    0x7ffd96bca4d0 M PluggableButtonMorph(Morph)>handleMouseUp: 0x16889068: a(n) PluggableButtonMorph
    0x7ffd96bca508 M MouseButtonEvent>sentTo: 0x1688e768: a(n) MouseButtonEvent
    0x7ffd96bca540 M PluggableButtonMorph(Morph)>handleEvent: 0x16889068: a(n) PluggableButtonMorph
    0x7ffd96bca578 M PluggableButtonMorph(Morph)>handleFocusEvent: 0x16889068: a(n) PluggableButtonMorph
    0x7ffd96bca5c8 M [] in HandMorph>sendFocusEvent:to:clear: 0x185e6fb0: a(n) HandMorph
    0x7ffd96bca5f8 M FullBlockClosure(BlockClosure)>on:do: 0x1688e7c8: a(n) FullBlockClosure
    0x7ffd96bca640 M WorldMorph>becomeActiveDuring: 0x185bf348: a(n) WorldMorph
    0x7ffd96bca690 M HandMorph>sendFocusEvent:to:clear: 0x185e6fb0: a(n) HandMorph
    0x7ffd96bca6e0 M HandMorph>sendEvent:focus:clear: 0x185e6fb0: a(n) HandMorph
    0x7ffd96bca728 M HandMorph>sendMouseEvent: 0x185e6fb0: a(n) HandMorph
    0x7ffd96bca780 M HandMorph>handleEvent: 0x185e6fb0: a(n) HandMorph
    0x7ffd96bca7c0 M [] in OSWindowMorphicEventHandler>dispatchMorphicEvent: 0x1b6ac4b0: a(n) OSWindowMorphicEventHandler
    0x7ffd96bca800 M WorldState>runStepMethodsIn: 0x185cc588: a(n) WorldState
    0x7ffd96bca838 M WorldMorph>runStepMethods 0x185bf348: a(n) WorldMorph
    0x7ffd96bca868 M WorldState>doOneCycleFor: 0x185cc588: a(n) WorldState
    0x7ffd96bca8a0 M WorldMorph>doOneCycleNow 0x185bf348: a(n) WorldMorph
    0x7ffd96bca8d0 M WorldMorph>doOneCycle 0x185bf348: a(n) WorldMorph
    0x7ffd96bca908 M [] in WorldMorph class>doOneCycle 0x185502f8: a(n) WorldMorph class
    0x7ffd96bca948 M FullBlockClosure(BlockClosure)>ensure: 0x1688ece0: a(n) FullBlockClosure
    0x7ffd96bca980 M WorldState class>doDrawCycleWith: 0x18550dc8: a(n) WorldState class
    0x7ffd96bca9b8 M WorldMorph class>doOneCycle 0x185502f8: a(n) WorldMorph class
    0x7ffd96bca9e8 M MorphicRenderLoop>doOneCycle 0x1a782f80: a(n) MorphicRenderLoop
    0x7ffd96bcaa18 M MorphicRenderLoop>doOneCycleWhile: 0x1a782f80: a(n) MorphicRenderLoop
        0x1a788b20 s [] in MorphicUIManager>spawnNewProcess
        0x1a789288 s [] in FullBlockClosure(BlockClosure)>newProcess

processes at priority 10
Process         0x1b60f7a8 priority 10
    0x7ffd96bd0a20 M ProcessorScheduler class>idleProcess 0x17e74f68: a(n) ProcessorScheduler class
        0x1b6ab610 s [] in ProcessorScheduler class>startUp
        0x1b6b57a0 s [] in FullBlockClosure(BlockClosure)>newProcess

suspended processes
Process         0x1b60fba0 priority 50
    0x7ffd96bd4a20 I WeakArray class>finalizationProcess 0x17e75c90: a(n) WeakArray class
        0x1b8143c0 s [] in WeakArray class>restartFinalizationProcess
        0x1b8249f8 s [] in FullBlockClosure(BlockClosure)>newProcess

Process         0x1a6c9390 priority 80
    0x7ffd96ba69d8 M DelayMicrosecondTicker>waitForUserSignalled:orExpired: 0x18293cf0: a(n) DelayMicrosecondTicker
    0x7ffd96ba6a20 M [] in DelaySemaphoreScheduler>runBackendLoopAtTimingPriority 0x1828f708: a(n) DelaySemaphoreScheduler
        0x1b395858 s FullBlockClosure(BlockClosure)>ensure:
        0x1a7893b8 s DelaySemaphoreScheduler(DelayBasicScheduler)>runBackendLoopAtTimingPriority
        0x1b3956a8 s [] in DelaySemaphoreScheduler(DelayBasicScheduler)>startTimerEventLoopPriority:
        0x1a789498 s [] in FullBlockClosure(BlockClosure)>newProcess

Process         0x19cddca0 priority 40
        0x19ce1588 s AtomicSharedQueue>waitForNewItems
        0x19ce2448 s AtomicSharedQueue>next
        0x19ce2e30 s TKTWorkerProcess>privateNextTask
        0x19ce3640 s [] in TKTWorkerProcess>workerLoop
        0x19ce3718 s FullBlockClosure(BlockClosure)>repeat
        0x19ce37f8 s TKTWorkerProcess>workerLoop
        0x19ce38b0 s MessageSend>value
        0x19ce3968 s [] in TKTPharoProcessProvider>createProcessDoing:named:
        0x19ce3a40 s [] in FullBlockClosure(BlockClosure)>newProcess

Process         0x1b60f758 priority 60
        0x1b696380 s SmalltalkImage>lowSpaceWatcher
        0x1b6ab558 s [] in SmalltalkImage>installLowSpaceWatcher
        0x1b6b56c0 s [] in FullBlockClosure(BlockClosure)>newProcess

Process         0x1b6966b0 priority 70
    0x7ffd96ba89e0 I [] in TFCallbackQueue>forkCallbackProcess 0x1b60fb38: a(n) TFCallbackQueue
    0x7ffd96ba8a20 I [] in FullBlockClosure>newProcess 0x1b6b58e0: a(n) FullBlockClosure

Process         0x1707c050 priority 40
    0x7ffd96bc88e8 M [] in Delay>wait 0x170bb758: a(n) Delay
    0x7ffd96bc8928 M FullBlockClosure(BlockClosure)>ifCurtailed: 0x170e8318: a(n) FullBlockClosure
    0x7ffd96bc8960 M Delay>wait 0x170bb758: a(n) Delay
    0x7ffd96bc89a0 I Duration>wait 0x1b6ac238: a(n) Duration
    0x7ffd96bc89e0 I [] in OmDeferrer>runMessageProcess 0x1b696a70: a(n) OmDeferrer
    0x7ffd96bc8a20 I [] in FullBlockClosure>newProcess 0x1707be90: a(n) FullBlockClosure

Process         0x1b6106e0 priority 60
    0x7ffd96bac8e8 M [] in Delay>wait 0x171cc7f8: a(n) Delay
    0x7ffd96bac928 M FullBlockClosure(BlockClosure)>ifCurtailed: 0x171cca70: a(n) FullBlockClosure
    0x7ffd96bac960 M Delay>wait 0x171cc7f8: a(n) Delay
    0x7ffd96bac9a0 M OSSDL2Driver>eventLoopProcessWithoutPlugin 0x1b610730: a(n) OSSDL2Driver
    0x7ffd96bac9e0 I [] in OSSDL2Driver>setupEventLoop 0x1b610730: a(n) OSSDL2Driver
    0x7ffd96baca20 I [] in FullBlockClosure>newProcess 0x1b814118: a(n) FullBlockClosure

Most recent primitives
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
indexOfAscii:inString:startingAt:
nextPut:
stringHash:initialHash:
size
at:
compare:with:collated:
at:
startsWithDigit
compare:with:collated:
basicNew
stringHash:initialHash:
findInterned:
\\
\\
compare:with:collated:
\\
stringHash:initialHash:
compare:with:collated:
stringHash:initialHash:
compare:with:collated:
stringHash:initialHash:
compare:with:collated:
findSubstringViaPrimitive:in:startingAt:matchTable:
indexOfAscii:inString:startingAt:
findSubstringViaPrimitive:in:startingAt:matchTable:
indexOfAscii:inString:startingAt:
findSubstringViaPrimitive:in:startingAt:matchTable:
indexOfAscii:inString:startingAt:
findSubstringViaPrimitive:in:startingAt:matchTable:
indexOfAscii:inString:startingAt:
findSubstringViaPrimitive:in:startingAt:matchTable:
indexOfAscii:inString:startingAt:
perform:
class
basicNew
perform:
isPoolImport
findSubstringViaPrimitive:in:startingAt:matchTable:
indexOfAscii:inString:startingAt:
findSubstringViaPrimitive:in:startingAt:matchTable:
indexOfAscii:inString:startingAt:
findSubstringViaPrimitive:in:startingAt:matchTable:
indexOfAscii:inString:startingAt:
findSubstringViaPrimitive:in:startingAt:matchTable:
indexOfAscii:inString:startingAt:
findSubstringViaPrimitive:in:startingAt:matchTable:
indexOfAscii:inString:startingAt:
perform:
size
basicNew
basicNew
basicNew
shallowCopy
basicIdentityHash
stringHash:initialHash:
at:
at:
class
value:
scanFor:
value:
value:
value
class
stringHash:initialHash:
optionParseErrors
optionParseErrors
optionParseErrors
optionParseErrors
optionParseErrors
optionParseErrors
stringHash:initialHash:
basicNew
basicNew
basicNew
**StackOverflow**
**StackOverflow**

position
position
**StackOverflow**
basicNew
basicNew
**StackOverflow**
**StackOverflow**
**StackOverflow**
copyReplaceFrom:to:with:
removeProperty:ifAbsent:
removeProperty:ifAbsent:
indexOfAscii:inString:startingAt:
removeProperty:ifAbsent:
removeProperty:ifAbsent:
value
basicNew
propertyAt:ifAbsent:
propertyAt:ifAbsent:
indexOfAscii:inString:startingAt:
isSpecial
basicNew
basicNew
stringHash:initialHash:
compare:with:collated:
basicNew
**StackOverflow**
basicNew
basicNew
**StackOverflow**
basicNew
at:put:
**StackOverflow**

class
basicNew
isEmpty
**StackOverflow**
indentString
indentString
timesRepeat:
at:
value:value:
indentExtraSpaces:around:
indentExtraSpaces:around:
**StackOverflow**
at:put:
at:put:
**StackOverflow**
formatCommentCloseToStatements
formatCommentCloseToStatements
do:
-
basicNew
basicNew
**StackOverflow**
basicNew
basicNew
**StackOverflow**
**StackOverflow**
**StackOverflow**
basicNew
**StackOverflow**
basicNew
**StackOverflow**
basicNew
detect:ifFound:ifNone:
**StackOverflow**
basicNew
>
**StackOverflow**
assert
<=
growTo:
growTo:
growTo:
growTo:
grownBy:
class
size
size
basicNew
basicNew
basicNew
basicNew
basicNew
basicNew
basicNew
basicNew
**StackOverflow**
basicNew
basicNew
basicNew
basicNew
**StackOverflow**
basicNew
basicNew
class
**StackOverflow**
basicIdentityHash
stringHash:initialHash:
basicNew
basicIdentityHash
at:
at:
\\
\\
basicNew
basicNew
basicNew
basicNew
basicNew
**StackOverflow**
basicNew
basicNew
basicIdentityHash
value
value
value
value
value
basicNew
basicNew
stringHash:initialHash:
value:value:

stack page bytes 8192 available headroom 5576 minimum unused headroom 5992

	(Segmentation fault)
-------------------------------------------------------------------------------------------

**Comment by MarcusDenker** [comment]
This can happen: Some changes require a full bootrap.

**Comment by MarcusDenker** [comment]
The reason is that code loading is not done in an atomic way. 

Changes deep in the system can quickly rely on order of changes where the intermediate steps where done but the PR does not reflect them anymore, nor does it use the same order.

This is why I tend to do compiler related changes in very small steps instead of batching them into bigger changes that do multiple things together...

**Comment by MarcusDenker** [comment]
(this is not really fixable outside of making reflective change transactional, so I close it)
