### ISSUE TITLE
Browsing implementors/senders from source code editors doesn't browse expected selector

### ISSUE THREAD

**Issue by sonibla** [guillep/pharo-core#11390]
**Bug description**
![Pharo_bvVjhjRDpy](https://user-images.githubusercontent.com/49032546/174760325-f095bddc-59c4-41f9-9e24-a9a9e65b49a9.gif)
In the screen recording, I want to browse implementors of `#readParametersFromContext:`, but Pharo instead looks for `#prepareNewCommand:readParametersFromContext:` (which doesn't exist)
It works when explicitly selecting the selector, but it shouldn't be needed

**To Reproduce**
1. Create CmdMenuGroup1, subclass of CmdMenuGroup
2. On class side, define
```
sourceCodeMenuActivation

	<classAnnotation>
	^ SycSourceCodeMenuActivation
		  byItemOf: ClyQueryMenuGroup
		  for: ClySourceCodeContext
```
4. Right click in a source code editor > debug

**Version information:**
 - OS: Windows/Linux
 - Version: Pharo-11.0.0+build.95.sha.554b538cd430662e26bd8ae330e02a5743283451 (64 Bit) (and pharo 10)

**Comment by MarcusDenker** [comment]
Interestingly it works if I used they shortcuts (cmd m). And *after that* it even works via the menu.

Maybe the error leads to some initialisation not done correctly for the menu?

**Comment by hogoww** [comment]
Investigated and fixed.
PR pending
