### ISSUE TITLE
Can't resize debugger columns in the inspector

### ISSUE THREAD

**Issue by sonibla** [guillep/pharo-core#11391]
![Pharo_Z8yVtHmS25](https://user-images.githubusercontent.com/49032546/174762936-a5ede2db-0cbc-438e-ae0a-998f7fd292df.gif)

**Describe the request**
Would be nice to be able to resize those columns, particularly if the class name or ivar name is too long to fit in the default view

**Version information:**
 - OS: Windows/Linux
 - Version: Pharo-11.0.0+build.95.sha.554b538cd430662e26bd8ae330e02a5743283451 (64 Bit) (and pharo 10)

**Comment by MarcusDenker** [comment]
could be related to https://github.com/pharo-project/pharo/issues/9828

**Comment by MarcusDenker** [comment]
fixed by merging 9828-Inspector-columns-cannot-be-resized #11262
