### ISSUE TITLE
 Debugger-Actions removal

### ISSUE THREAD

**Issue by hogoww** [guillep/pharo-core#11406]
**Describe the problem**
The full Debugger-Actions package seem ready to be cleaned up, it doesn't seem used anywhere anymore

**Proposal**
Removing the  Debugger-Actions package, and possibly similar ones.

**Version information:**
Pharo11

**Expected development cost**
Trivial.
The real cost is knowing if it's indeed removable or kept for some reason.

Probably of interest for @StevenCostiou

**Comment by StevenCostiou** [comment]
This package was used by the older debuggers: Spec1 and GT.
It can be removed.

**Comment by hogoww** [comment]
Cool, that'll be a quick sprint PR

**Comment by MarcusDenker** [comment]
fixed by merging https://github.com/pharo-project/pharo/pull/11485

**Comment by MarcusDenker** [comment]
un-fixed by revertion
