### ISSUE TITLE
Website Pharo enterprise  book: Direct Chapter Links broken

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11414]
**Bug description**
if you check https://books.pharo.org/enterprise-pharo/ , the direct links to the chapters do not work

**Comment by svenvc** [comment]
Yes, very annoying, I reported this before.

**Comment by jgfoster** [comment]
Should this issue be moved to https://github.com/SquareBracketAssociates/EnterprisePharo/? Can you give more details on how to reproduce the problem?

<blockquote><img src="https://opengraph.githubassets.com/9a17617683e167d52c5d89b541a0b0a2ba3a91b337fd5b0d2fa4f38c18109a04/SquareBracketAssociates/EnterprisePharo" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/SquareBracketAssociates/EnterprisePharo">GitHub - SquareBracketAssociates/EnterprisePharo: A new book describing Pharo librairies to make business.</a></strong></div><div>A new book describing Pharo librairies to make business. - GitHub - SquareBracketAssociates/EnterprisePharo: A new book describing Pharo librairies to make business.</div></blockquote>

**Comment by Ducasse** [comment]
It is reported there so I close it here.
