### ISSUE TITLE
Unload package Spec2-Deprecated10

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11427]
**Describe the problem**
We should think if we can unload Spec2-Deprecated10 in Pharo11

**Comment by jecisc** [comment]
This is not in my image anymore

**Comment by astares** [comment]
@MarcusDenker 
Yes. It is not in a fresh P11 image. I guess we can close

**Comment by guillep** [comment]
Yes :)

**Comment by guillep** [comment]
Thanks for verifying it
