### ISSUE TITLE
Cannot remove a referenced method

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#11432]
**Bug description**

**To Reproduce**
1. Open a browser on `AIGraphAlgorithm`class
2. select the `#addNodeFor:`method
3. right-click 'remove'
4. Click on 'remove it'
5. Click no in the Warning pop-up asking if you want to browser references

**Expected behavior**
When clicking on 'remove it' at step 4, I expect no other dialog and the methods to be removed.
Even if step 5 show a warning, clicking `no`should remove the method

**Version information:**
 - Pharo Version : 11, build 116

**Comment by MarcusDenker** [comment]
Fixes by reverting
