### ISSUE TITLE
Enable public archive for new VM development list

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#11434]
There is a new Pharo VM mailinglist as announced in https://pharoweekly.wordpress.com/2022/07/01/new-pharo-vm-mailing-list/

https://lists.pharo.org/empathy/list/pharo-vm.lists.pharo.org

Unfortunately one can not see the archive as in the other public mailinglists:

![image](https://user-images.githubusercontent.com/5980033/177041097-6d8c1ac6-dbc9-414a-939d-5c0ce1715859.png)

It would be good to enable the archive

**Comment by guillep** [comment]
Hi @astares , archives are enabled, but there was yet no message there.
I just sent a message to test and the archive should be there.
Please reopen if needed.

**Comment by astares** [comment]
@guillep OK - works thanks!
