### ISSUE TITLE
UI becomes unresponsive when blocked on a custom semaphore

### ISSUE THREAD

**Issue by isCzech** [guillep/pharo-core#11454]
UI becomes unresponsive when running this example in the Playground:
```
s := Semaphore new.
[1/0. s signal] fork.
s wait
```
There's no reason to expect the UI to freeze yet it freezes because when opening the debugger the system won't make sure a functional unsuspended and unblocked UI is available... Fixing this would mean a better user experience when running experiments from the Playground.

The idea is to open a new UI when the current UI is blocked and add an "exit condition" to the UI loop to allow a former UI process to finish its last cycle and terminate automatically; e.g. like this:
`... doOneCycleWhile: [ UIManager default uiProcess isActiveProcess ]`
You can then safely open a new UI anytime without the need to explicitly terminate the old one because the previous UI will stop cycling automatically and terminate once it's replaced by a new one (which you do by assigning the new UI process to the UIManager default uiProcess instance variable).

These examples would evaluate identically regardless of whether they run in the UI or otherwise (simulated here by running forked), and don't freeze the UI :)
```
s := Semaphore new.
[[1/0] ensure: [s signal]] fork.
s wait.
self error: 'error'
```
```
[s := Semaphore new.
[[1/0] ensure: [s signal]] fork.
s wait.
self error: 'error'] fork
```
The issue has been also discussed here: https://github.com/pharo-project/pharo/pull/11310#issuecomment-1179710109

Sending a PR as a starting point for your consideration. Any corrections and comments welcome!

**Comment by Ducasse** [comment]
I guess that we can close this one. Tell me otherwise
