### ISSUE TITLE
Push Down Class Variable Refactoring simply removes it

### ISSUE THREAD

**Issue by refactoringdr** [guillep/pharo-core#11489]
**Bug description**
Push Down Class Variable Refactoring simply removes it. It does not correctly identify subclasses that reference the class variable

**To Reproduce**
1. Select a superclass with a Class variable that is referenced in subclasses (but not the superclass). 
2. In the class definition right click on the class variable and select "Push Down"3. 
3. The resulting refactoring will simply remove the class variable leaving undeclared bindings in the subclasses

**Expected behavior**
The class variable should be pushed into the referring subclasses definitions.

**Version information:**
 - Pharo Version 10

**Expected development cost**

To fix it, change `RBAbstractClass>>bindingOf:` to: 

```
bindingOf: aString
	^ self realClass bindingOf: aString
```

**Comment by hernanmd** [comment]
Closing since this is already fixed in Pharo 13:

![Image](https://github.com/user-attachments/assets/9f022201-6665-4e19-85d1-85eb774a08a2)

![Image](https://github.com/user-attachments/assets/d7f99634-1ae5-43fc-898a-77fc6fe65084)
