### ISSUE TITLE
No OBS build provided for Ubuntu Jammy (22.04)

### ISSUE THREAD

**Issue by fmqa** [guillep/pharo-core#11518]
**Bug description**
No packages are provided in OBS for the latest Ubuntu LTS release

**To Reproduce**
1. Go to http://download.opensuse.org/repositories/devel:/languages:/pharo:/latest/
2. Inspect package listing
3. Observe that the newest available version is "21.10"

**Expected behavior**
Packages are provided for the latest Ubuntu LTS release

**Screenshots**
N/A

**Version information:**
 - OS: Ubuntu
 - Version: 22.04 LTS (Jammy Jellyfish)
 - Pharo 9

**Expected development cost**
Since packages are already provided for the pre-LTS release 21.10, providing an OBS build for 22.04 likely requires minimal effort.

**Additional context**
N/A

**Comment by estebanlm** [comment]
I added it.

https://build.opensuse.org/package/show/devel:languages:pharo:latest/pharo9
https://build.opensuse.org/package/show/devel:languages:pharo:latest/pharo9-ui

can you test it?


<blockquote><img src="https://build.opensuse.org/assets/obs-logo_meta-0cc940130a6cceea822bfa0c5eaf466d900a2ed4df7eb7fe6936a24b188852ff.png" width="48" align="right"><div>openSUSE Build Service</div><div><strong><a href="https://build.opensuse.org/package/show/devel:languages:pharo:latest/pharo9">The Pharo VM</a></strong></div></blockquote>
<blockquote><img src="https://build.opensuse.org/assets/obs-logo_meta-0cc940130a6cceea822bfa0c5eaf466d900a2ed4df7eb7fe6936a24b188852ff.png" width="48" align="right"><div>openSUSE Build Service</div><div><strong><a href="https://build.opensuse.org/package/show/devel:languages:pharo:latest/pharo9-ui"> The Pharo VM with full dependencies </a></strong></div></blockquote>

**Comment by fmqa** [comment]
> I added it.

Thanks, however the dependency on `libgit2` is misnamed, therefore installation fails:

```
$ LANG=C sudo apt install pharo9-ui
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pharo9-ui : Depends: libgit2 (= 1.0.1-1) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Checking the Ubuntu package index, the correct name for the dependency is [libgit2-1.1](https://packages.ubuntu.com/jammy/libgit2-1.1) (note the version suffix) since 21.10

Also, I'm not sure about the version constraint: `= 1.0.1-1` implies that pharo requires this exact version of libgit2. However the official repositories only include 1.1.0. Perhaps a simple unconstrained dependency on `libgit2-1.1` is sufficient, since the library packages are already segmented by version?

**Comment by astares** [comment]
Same here:

```
kiwi@box:~$ cd pharo
kiwi@box:~/pharo$ mkdir pharo9
kiwi@box:~/pharo$ cd pharo9/
kiwi@box:~/pharo/pharo9$ echo 'deb http://download.opensuse.org/repositories/devel:/languages:/pharo:/latest/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/devel:languages:pharo:latest.list
curl -fsSL https://download.opensuse.org/repositories/devel:languages:pharo:latest/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/devel_languages_pharo_latest.gpg > /dev/null
sudo apt update
sudo apt install pharo9-ui
deb http://download.opensuse.org/repositories/devel:/languages:/pharo:/latest/xUbuntu_22.04/ /
Hit:1 http://de.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://de.archive.ubuntu.com/ubuntu jammy-backports InRelease        
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease           
Get:5 http://download.opensuse.org/repositories/devel:/languages:/pharo:/latest/xUbuntu_22.04  InRelease [1.563 B]
Get:6 http://download.opensuse.org/repositories/devel:/languages:/pharo:/latest/xUbuntu_22.04  Packages [753 B]
Fetched 2.316 B in 1s (3.194 B/s) 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pharo9-ui : Depends: libgit2 (= 1.0.1-1) but it is not installable
E: Unable to correct problems, you have held broken packages.
kiwi@box:~/pharo/pharo9$ 
```

**Comment by estebanlm** [comment]
what about now?

**Comment by fmqa** [comment]
Just gave it another go, same issue as earlier. The dpkg control file seems unchanged:

```
$ wget https://download.opensuse.org/repositories/devel:/languages:/pharo:/latest/xUbuntu_22.04/amd64/pharo9-ui_9.0.6-1_amd64.deb
--2022-08-14 15:26:06--  https://download.opensuse.org/repositories/devel:/languages:/pharo:/latest/xUbuntu_22.04/amd64/pharo9-ui_9.0.6-1_amd64.deb
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2001:67c:2178:8::13
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1620 (1.6K) [application/x-download]
Saving to: 'pharo9-ui_9.0.6-1_amd64.deb'

pharo9-ui_9.0.6-1_amd64.deb           100%[========================================================================>]   1.58K  --.-KB/s    in 0s      

2022-08-14 15:26:06 (347 MB/s) - 'pharo9-ui_9.0.6-1_amd64.deb' saved [1620/1620]

$ dpkg --info pharo9-ui_9.0.6-1_amd64.deb 
 new Debian package, version 2.0.
 size 1620 bytes: control archive=596 bytes.
     503 bytes,    10 lines      control              
     155 bytes,     2 lines      md5sums              
 Package: pharo9-ui
 Version: 9.0.6-1
 Architecture: amd64
 Maintainer: Esteban Lorenzano <estebanlm@netc.eu>
 Installed-Size: 13
 Depends: pharo9, libgit2 (= 1.0.1-1), libsdl2-2.0-0, libcairo2, libfreetype6
 Section: devel
 Priority: optional
 Homepage: https://github.com/pharo-project/opensmalltalk-vm
 Description: Pharo is a pure object-oriented programming language and a powerful environment, focused on simplicity and immediate feedback (think IDE and OS rolled into one). PACKAGE WITH FULL DEPENDENCIES.
 ```

**Comment by fmqa** [comment]
OTOH, the `pharo9` package seems to install correctly ... however - the dependencies for it seem to be slightly broken as well:

* It suggests `libgit2 (= 1.0.1-1)` instead of `libgit2-1.1`, but this does not prevent installation as "Suggests" denotes an optional dependency, as opposed to "Depends" (which implies a required dependency)
* However, `pharo` does not seem to work with the default image - which exits with the following error:

```
$ pharo Pharo10-SNAPSHOT-64bit-14f5413.image 
Cannot locate any of #('libgit2.1.0.0.so' 'libgit2.so.1.0.0' 'libgit2.so.1.0' 'libgit2.so.1.1' 'libgit2.so.1.2' 'libgit2.so.1.3' 'libgit2.so.1.4' 'libgit2.so.0.25.1'). Please check if it installed on your system
FFIUnix64LibraryFinder(Object)>>error:
FFIUnix64LibraryFinder(FFILibraryFinder)>>findAnyLibrary:
FFIUnix64LibraryFinder class(FFILibraryFinder class)>>findAnyLibrary:
LGitLibrary>>unix64LibraryName
Unix64Platform>>ffiLibraryName:
LGitLibrary(FFILibrary)>>libraryName
TFCalloutMethodBuilder(FFICalloutMethodBuilder)>>libraryName
TFCalloutMethodBuilder>>createFFICalloutLiteralFromSpec:
TFCalloutMethodBuilder>>generateFFICallout:spec:ffiLibrary:
...
```

I assume this happens because the the image internally calls out to libgit2 via FFI, therefore having "libgit2" as a suggested dependency makes sense in theory for the base VM package, since a customized image may not necessarily require this library. However, the dependency's name should be fixed here as well.

**Comment by estebanlm** [comment]
I removed the version number requirement, can you try again now?

**Comment by fmqa** [comment]
@estebanlm I did, it doesn't help:

```
$ (LANG=C && date && sudo apt update && sudo apt install pharo9-ui)
Sun Aug 14 15:51:31 CEST 2022
Hit:1 http://de.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu jammy-updates InRelease                                                    
Hit:3 http://de.archive.ubuntu.com/ubuntu jammy-backports InRelease                                                  
Get:4 http://download.opensuse.org/repositories/devel:/languages:/pharo:/latest/xUbuntu_22.04  InRelease [1563 B]    
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease                                                     
Hit:6 https://ppa.launchpadcontent.net/sebastian-stenzel/cryptomator/ubuntu jammy InRelease
Fetched 1563 B in 4s (398 B/s)                             
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
16 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pharo9-ui : Depends: libgit2 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

The issue is that there is no `libgit2` package under Ubuntu 21.10/22.04 - the package is literally called `libgit2-1.1` as seen [here](https://packages.ubuntu.com/jammy/libgit2-1.1)

So, the fix would have to be something like this:

```patch
--- debian-xUbuntu_22.04.control	2022-08-14 15:53:59.900926386 +0200
+++ debian-xUbuntu_22.04.control.fix	2022-08-14 15:55:53.507645955 +0200
@@ -8,5 +8,5 @@
 
 Package: pharo9-ui
 Architecture: amd64 arm64 armhf
-Depends: ${shlibs:Depends}, ${misc:Depends}, pharo9, libgit2, libsdl2-2.0-0, libcairo2, libfreetype6
+Depends: ${shlibs:Depends}, ${misc:Depends}, pharo9, libgit2-1.1, libsdl2-2.0-0, libcairo2, libfreetype6
 Description: Pharo is a pure object-oriented programming language and a powerful environment, focused on simplicity and immediate feedback (think IDE and OS rolled into one). PACKAGE WITH FULL DEPENDENCIES.
```

**Comment by estebanlm** [comment]
no, I think the real problem is that is not taking into account the xUbuntu_22.04.control file, as you see here: 

![image](https://user-images.githubusercontent.com/513630/184540727-d2475668-1c71-47e4-b041-0a032013ef42.png)

It took the regular control file, not the 22.04 specific). This may be a problem, since we cannot modify the control file for the previous versions...

**Comment by fmqa** [comment]
@estebanlm 

In that case, would it be possible to specify multiple alternatives for this dependency to make it satisfiable on new(er) systems? I understand the need to maintain backwards-compatibility, so would something like this be an acceptable compromise?

```diff
--- debian.control	2022-08-14 16:10:21.945253866 +0200
+++ debian.control.fix	2022-08-14 16:10:43.749806115 +0200
@@ -8,5 +8,5 @@
 
 Package: pharo9-ui
 Architecture: amd64 arm64 armhf
-Depends: ${shlibs:Depends}, ${misc:Depends}, pharo9, libgit2 (=1.0.1-1), libsdl2-2.0-0, libcairo2, libfreetype6
+Depends: ${shlibs:Depends}, ${misc:Depends}, pharo9, libgit2 (=1.0.1-1) | libgit2-1.1, libsdl2-2.0-0, libcairo2, libfreetype6
 Description: Pharo is a pure object-oriented programming language and a powerful environment, focused on simplicity and immediate feedback (think IDE and OS rolled into one). PACKAGE WITH FULL DEPENDENCIES.
```

**Comment by estebanlm** [comment]
that may have been worked, can you try again?
(sorry for using you as guinea pig, but I am working blindly here: I am on holidays and I cannot install a 22.04 box from here to test it myself :P)

**Comment by fmqa** [comment]
That seemed to do the trick:
```
$ LANG=C sudo apt install pharo9-ui 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  pharo9-ui
0 upgraded, 1 newly installed, 0 to remove and 16 not upgraded.
Need to get 1638 B of archives.
After this operation, 13.3 kB of additional disk space will be used.
Get:1 http://download.opensuse.org/repositories/devel:/languages:/pharo:/latest/xUbuntu_22.04  pharo9-ui 9.0.6-1 [1638 B]
Fetched 1638 B in 0s (5275 B/s)     
Selecting previously unselected package pharo9-ui.
(Reading database ... 219058 files and directories currently installed.)
Preparing to unpack .../pharo9-ui_9.0.6-1_amd64.deb ...
Unpacking pharo9-ui (9.0.6-1) ...
Setting up pharo9-ui (9.0.6-1) ...
$ LANG=C sudo apt show pharo9-ui
Package: pharo9-ui
Version: 9.0.6-1
Priority: optional
Section: devel
Maintainer: Esteban Lorenzano <estebanlm@netc.eu>
Installed-Size: 13.3 kB
Depends: pharo9, libgit2 (= 1.0.1-1) | libgit2-1.1, libsdl2-2.0-0, libcairo2, libfreetype6
Homepage: https://github.com/pharo-project/opensmalltalk-vm
Download-Size: 1638 B
APT-Manual-Installed: yes
APT-Sources: http://download.opensuse.org/repositories/devel:/languages:/pharo:/latest/xUbuntu_22.04  Packages
Description: Pharo is a pure object-oriented programming language and a powerful environment, focused on simplicity and immediate feedback (think IDE and OS rolled into one). PACKAGE WITH FULL DEPENDENCIES.
```

I would suggest  doing something similar for the `pharo9` package as well so that it has a dependency specification like `Recommends: libcairo2, libsdl2-2.0-0, libgit2 (=1.0.1) | libgit2-1.1, libfreetype6` so the appropriate libgit2 would get installed automatically as well.

Other than that, it seems to work fine. There are some differences compared to the bundled distribution at https://files.pharo.org/pharo-launcher/linux64 - namely the initial scaling factor seems to be set to a suboptimal value (see screenshot below), resulting in large UI controls & fuzzy/blurry fonts. This can be somewhat rectified by setting the "Display Scale Factor" to `0.75` or a similar value. I assume this may be an issue with the native libSDL2 or perhaps missing HiDPI support. 

On the other hand, full screen mode finally works under both X11 & Wayland without any issues, so in general I prefer the deb-packaged distribution.

![pharo9_native_sdl2](https://user-images.githubusercontent.com/7354509/184541595-2fa3f72d-7629-4df7-906c-d232a998a75f.png)

**Comment by estebanlm** [comment]
yeah, I am adding that also to pharo9 package. 
i general, in linux, you should prefer the packaged version over the zeroconf version (the one used by pharo launcher), we are trying to figure out how to modify PL to take that into account.
And yes, there is still no HiDPI support.

**Comment by estebanlm** [comment]
but I guess we can close this now :)
