### ISSUE TITLE
Esc does not close Spotter

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#11511]
**Bug description**
When you open Spotter and want to leave it without doing something, `Esc` key worked for that but it stopped to work recently

**To Reproduce**
1. Open Spotter
2. press Esc
3. nothing happens

**Version information:**
- OS: Windows 10
 - Pharo Version: 11

**Comment by pavel-krivanek** [comment]
introduced in build 118, 116 works well, 117 is missing

**Comment by pavel-krivanek** [comment]
introduced by https://github.com/pharo-project/pharo/pull/11418

**Comment by pavel-krivanek** [comment]
introduced by this commint of NewTools: https://github.com/pharo-spec/NewTools/commit/cff0b7b8a1ca7f05f7029b965fd49936a8e4683e

**Comment by pavel-krivanek** [comment]
PR: https://github.com/pharo-spec/NewTools/pull/410

**Comment by MarcusDenker** [comment]
PR is merged
