### ISSUE TITLE
RBReplacePreview should be packaged in a new package named Refactoring-UI

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11515]
- This class is a UI (subclass of SpPresenter)
- It should be packaged outside of the Refactoring-Core
- Now it is not referenced in P11. So may be we can delete it.

**Comment by balsa-sarenac** [comment]
Was this fixed with https://github.com/pharo-project/pharo/pull/11765?

**Comment by hernanmd** [comment]
I think the idea was to be used like this but it doesn't work and also has no users:

```smalltalk
RBReplacePreview new
	change: (RBRefactoryChangeFactory instance addPackageNamed: 'Prueba3');
	accept: (SpPresenter new asDialogWindow okAction: [ self halt accept ]);
	open
```

I would remove it from Pharo 11

**Comment by Ducasse** [comment]
I think that balsa introduced a preview widget. Do you confirm balsa?
So yes let us remove dust

**Comment by balsa-sarenac** [comment]
Yes, it's been added. It might require some additional work so it can be reused in multiple places.
