### ISSUE TITLE
Copy class refactoring should copy the class comment

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11520]
When copying a package the classes lose their comments.

**Comment by MarcusDenker** [comment]
We changed this already 2 times (maybe even more often): we changed to  copy the comment, then we decided that it is bad and removed it again.

Maybe we should add a checkbox to the dialog, then people can copy the comment if they are sure it is what they want.

**Comment by MarcusDenker** [comment]
see https://github.com/pharo-project/pharo/pull/5390

**Comment by Ducasse** [comment]
I do not see why not copying is needed. 
Losing information is always bad. After when we copy this is either to remove the original ones or to modify 
the result and in this case we should go over the comment but going over a comment is better than Oops there is not comment.

**Comment by Ducasse** [comment]
I strongly disagree with #5390.
