### ISSUE TITLE
Should remove Refactoring-Help from the file system

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11530]
And probably Refactoring2-Core once this is integrated https://github.com/pharo-project/pharo/pull/11529

**Comment by MarcusDenker** [comment]
was this already done with https://github.com/pharo-project/pharo/pull/11521 ?

**Comment by MarcusDenker** [comment]
yes, I checked: no package Refactoring-Help in Pharo11

**Comment by Ducasse** [comment]
Yes but we should do it on the command line or something like that in the git repo.
Did you check on the repo?

**Comment by MarcusDenker** [comment]
No, just the image
