### ISSUE TITLE
AIGraphAlgorithm should be abstract

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#11577]
AIGraphAlgorithm is an abstract superclass. We should implement #isAbstract to return true

**Comment by astares** [comment]
This needs to be fixed in github://pharo-ai/graph-algorithms

**Comment by astares** [comment]
Maybe @jordanmontt can add it in the original repo and if the next iteration is included in standard image it is fixed.

**Comment by jordanmontt** [comment]
Hello, yes I will make it abstract and update the release version of the graph-algorithm library

**Comment by astares** [comment]
Thanks!

**Comment by jordanmontt** [comment]
Hello, I added the abstract method as you can see in: https://github.com/pharo-ai/graph-algorithms/commit/5e434d086320e08b19fb069381f456df880acf82

I propose to close this issue.

**Comment by astares** [comment]
@jordanmontt 

Thanks! Not yet part of the P11 image but we can close already
