### ISSUE TITLE
Implementors search in the Debugger interprets selector as a variable

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#11584]
**Bug description**
Pressing Ctrl-M for implementors search in the Debugger probably tries to work with the selector as if it would be a variable and thus shows UndefinedObject class.

**To Reproduce**
1. in a Playground, type `Integer maxValue` and try to print it (it is wrong expression)
2. The Debugger opens (Instance of Integer class did not understand #maxValue)
3. select `maxValue` selector 
4. press Ctrl+M (or a platform alternative)
5. a browser on `UndefinedObject` is opened

**Version information:**
 - Version: Pharo 10 and 11 but worked correcty in Pharo 9

**Comment by MarcusDenker** [comment]
merged after review
