### ISSUE TITLE
[Feature Request][Debugger] Disable/Enable all debug breakpoints

### ISSUE THREAD

**Issue by labordep** [guillep/pharo-core#11599]
Hi,

This would very cool to disable in one click all breakpoint but without lost them.
From a user point of view, a solution can be a toggle button in the main Pharo Debug menu (and also inside the debugger) to switch breakpoints on/off : 
![image](https://user-images.githubusercontent.com/49183340/186666227-8ec6d5a7-f1ad-4584-a283-8088ac00a114.png)

This function exists in some IDE but most of the time user can be confused because he don't remember states of the activation (or not) : The debug menu can be display the state of breakpoints activation with a color or an icon when they are not active for the garanted that users doesn't believe that there are active. 
![image](https://user-images.githubusercontent.com/49183340/186669194-0f43bcba-3345-448b-94cf-318772882207.png)

This features is very usefull when you debug, particularly graphical loops and i/o events.

Thanks.

Sorry I cannot set that this topic is related to "debugger" tag :(

**Comment by Ducasse** [comment]
Yes Max Zurbriggen will work on this and more. 
I want to have more search/filter/ scripting breakpoints
like put on all the green breakpoints and disable the others

**Comment by StevenCostiou** [comment]
```Smalltalk
Breakpoint all do: #disable.
Breakpoint all do: #enable.
```
When disabled you see in the method browser:
<img width="187" alt="Capture d’écran 2022-08-26 à 14 11 47" src="https://user-images.githubusercontent.com/26929529/186900686-4be5789e-8353-434b-be8b-3b6cdb6ccf6c.png">

<img width="288" alt="Capture d’écran 2022-08-26 à 14 11 56" src="https://user-images.githubusercontent.com/26929529/186900717-75472acc-6a34-4c2b-b14a-b51f0783c92b.png">

Just add a menu entry, @adri09070? 

Enabling/disabling of single breakpoint is available through  checkboxes in the breakpoint inspection (in an inspector on  a given object or class) or in the debugger extension (if not broken).

**Comment by StevenCostiou** [comment]
It would even work on halts, but it requires either to scan the image for single halt enabling/disabling (this is already present in the system but dormant) or to add some logic to the `Halt` class.

**Comment by astares** [comment]
Setting breakpoints in a debugged method directly within the debugger (with a click on the line at the left side of the debugger codepane) would be nice too

**Comment by StevenCostiou** [comment]
Indeed, but this is difficult and requires to commit some energy to it.
The issue itself is discussed here https://github.com/pharo-project/pharo/issues/5211

Basically it requires on-stack replacement, or to simulate the execution when doing breakpoint stuff in the debugger.
I'm leaving the details for later, but this is definitely something that we could explore this autumn.

With Marcus we had a prototype of breakpoints installable directly from the debugger, tests were green but there  was some instability (sometimes image freeze, sometimes the execution did break twice instead of one, or even sometimes the stack disappeared).
So there is something still eluding us ;)

**Comment by astares** [comment]
@StevenCostiou Thanks for the info. Cool that this route is already part of exploration!

**Comment by adri09070** [comment]
Ok, I think I'll add a menu entry in the "debug" world menu to disable/enable all breakpoints
