### ISSUE TITLE
 We should use PolyMath random numbers generator instead of the Pharo #1 

### ISSUE THREAD

**Issue by jordanmontt** [guillep/pharo-core#11598]
[copy issue from pharo-ai]
Esteban experimented on this with a galaxy generator. We found that the random numbers generator in PolyMath performs better that the default one in Pharo. We should use PolyMath one

@estebanlm can you confirm that PolyMath random numbers are better?

**Comment by estebanlm** [comment]
in stress conditions, the randomizer present by default in Pharo is indeed not distributing results as expected. The Lehmer implementation in PolyMath was indeed doing a good job instead (at the price of being slower).
Nevertheless, I would analyse in more detail before jumping to replace it (maybe we affect others?)

**Comment by Ducasse** [comment]
No that there were other randomiser in Squeak and that I packaged them in POlymath and I collected some others. For example Andreas or other at that time introduced MersenneTwisterRandom because the default one was bad. I would replace and see because if someone would use Random for real it would see that it is not working well.

**Comment by estebanlm** [comment]
maybe we start by adding it, and in next version replace?

**Comment by Ducasse** [comment]
Yes!

**Comment by jordanmontt** [comment]
I am investigating this. As a first step, I am generating 1000 random numbers using the different generators and then graphing the numbers. These are the first results:

![Capture d’écran 2022-09-02 à 15 20 14](https://user-images.githubusercontent.com/33934979/188154875-f620c826-d2a5-4be3-8ff2-d0af80b7d771.png)

So, in this first test I found those generators that perfom well. As it can be seen, the distribution looks uniform. Now, I will search, implement and apply some statistical metrics to have other criticeria to say that a random number generator is good enough or not. I found for example  The Kolmogorov-Smirnov test.

I will you keep you posted

**Comment by estebanlm** [comment]
how are you testing?

**Comment by jordanmontt** [comment]
Like this:

```st
random := Random new.

randomGeneratedNumbers := OrderedCollection new.
1000 timesRepeat: [ randomGeneratedNumbers add: (random next) ].
x := randomGeneratedNumbers allButLast.
y := randomGeneratedNumbers allButFirst.

chart := RSChart new.
plot := RSScatterPlot new x: x y: y.
chart
	add: plot;
	title: 'Pharo Default Number Generator'.
chart open.
```

and also:

```st
{ PMBernoulliGenerator . PMBinomialGenerator . PMExponentialGenerator .
PMGaussianGenerator . PMPoissonGenerator  . PMMarsagliaKissRandomGenerator . PMCombinedRandomGenerator . PMExplicitInverseCongruentialRandomGenerator . PMFishmanMooreRandomGenerator . PMLehmerRandomGenerator . PMLinearCongruentialRandomGenerator . PMMarsagliaKissRandomGenerator . PMMersenneTwisterRandomGenerator . PMParkMillerMinimumRandomGenerator } do: [ :randomGeneratorClass | 
	random := randomGeneratorClass new.
	randomGeneratedNumbers := OrderedCollection new.
	1000 timesRepeat: [ randomGeneratedNumbers add: (random next) ].
	x := randomGeneratedNumbers allButLast.
	y := randomGeneratedNumbers allButFirst.
	
	chart := RSChart new.
	plot := RSScatterPlot new x: x y: y.
	chart
		add: plot;
		title: random class asString.
	chart open ]
```

But I need also to run some stats

**Comment by jordanmontt** [comment]
Hello @Ducasse and @estebanlm I am coming with some news. I was investigating and running tests and I propose to close this issue.

I run the [Kolmogorov-Smirnov Test](https://en.wikipedia.org/wiki/Kolmogorov%E2%80%93Smirnov_test) for 1 million randomly generated numbers and it rejected the null hyphotesis for a significance of 5%.
That means that the random numbers generated by the Pharo Random seem to be uniformly distributed. I also created several visual representations of the numbers, like the ones in my previous comment, but for also 1 million numbers. That also indicates that the numbers are uniformly distributed.

The Pharo Random uses the Park and Miller algorithm https://www.firstpr.com.au/dsp/rand31/p1192-park.pdf. With a little of research, that algo seems also to be a good one. It is widely used. Of course, for doing advanced stuffs one will may need to use other algorithm for generated the numbers. But there is no good response for that, it highly depends of the problem that one wants to solve and the mathematical properties that one wants for the numbers.

For most use cases, one only wants that the numbers are uniformly distributed and that they are random :)
Pharo already does that with the default Random generator. And it does it good enought (according to my tests).

My conclusion is that the Pharo random generator generates uniformly the numbers and that is behaves good enough for most use cases and that there is no apparent reason for changing it. I will close this issue by the end of tomorrow if I get no responses.
