### ISSUE TITLE
primitiveHighResClock not implemented on macOS ARM

### ISSUE THREAD

**Issue by marschall** [guillep/pharo-core#11609]
**Bug description**
primitiveHighResClock is not implemented on macOS ARM

**To Reproduce**
1. Evalue `Smalltalk highResClock isZero`. 
2. Answer is `true`.

**Expected behavior**
Answer is `false`.

**Version information:**
 - OS: macOS on Apple M1 Pro
 - Version: 12.5.1
 - Pharo Version 10

**Expected development cost**
> As you know nothing happens magically, so do you have an idea of the development effort required? 

Probably the biggest effort is reaching consensus what to do. Then implement here:

https://github.com/pharo-project/pharo-vm/blob/2585c2d71e030a88746ed6f0834855ed2f3e2a53/extracted/vm/src/common/heartbeat.c#L227

Besides the options listed there maybe `mach_absolute_time` / ` clock_gettime_nsec_np(CLOCK_UPTIME_RAW)` may also work.

> In addition, are you willing to help because after all Pharo is yours too?

Sure, if there's consensus on what to do.

**Additional context**
This is required to make `AndreasSystemProfiler` work on Apple Silicon.

**Comment by MarcusDenker** [comment]
was fixed by merging https://github.com/pharo-project/pharo-vm/pull/510
