### ISSUE TITLE
[Image Build Pharo11] Bootrap broken since Build

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11605]
**Bug description**
The CI can not build the image or run CI checks. The reason is that some PR that we merged broke the boostrap

It fails since Build 171: https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo11/171/

Changes merged:

- Optimize setting of initial position in PositionableStream>>on:  #11555
- Removed empty abstractCompletionEngine class  #11562
- Improve #basicSize documentation and add tests   #11590
- Cleanup ReferenceFinder>>#searchIndicesIn: #11592

Maybe we merged one of those without waiting for a successful CI run?

**Comment by MarcusDenker** [comment]
The error message is:

```
..donecreating initial Objects needed by the VM
Error: adaptToNumber:andSend: not found in UndefinedObject
EPASTInterpreter(Object)>>error:
[ self error: selector, ' not found in ' , class name ] in EPASTInterpreter>>lookupSelector:in: in Block: [ self error: selector, ' not found in ' , class n...etc...
EPASTInterpreter>>lookupFrom:until:ifNone:
EPASTInterpreter>>lookupSelector:in:
```

**Comment by MarcusDenker** [comment]
experiment to revert https://github.com/pharo-project/pharo/pull/11555 done as https://github.com/pharo-project/pharo/pull/11606

**Comment by astares** [comment]
®Marcus seems to be fixed.  But what caused it to fail?
