### ISSUE TITLE
Opening & closing Find+Replace dialog multiple times in succession results in dialog opening progressively slower

### ISSUE THREAD

**Issue by fmqa** [guillep/pharo-core#11603]
**Bug description**
Discovered this issue while working on #11601 

**To Reproduce**
1. Go to any editor e.g. in the system browser
2. Click on the editor area
3. Open the find/replace dialog using Ctrl+f
4. Close it by hitting ESC or using the cancel button
5. Repeat steps 3-4 up to 6-8 times

**Expected behavior**
Find/replace dialog appears immediately 

**Observed behavior**
Find/replace dialog opens after progressively longer delays after each repetition

**Version information:**
 - OS: Ubuntu
 - Version: 22.04.1 
 - Pharo version 10.0.0 (64-bit)

**Expected development cost**
Not sure where to look/debug 🤷‍♂️. My hunch is that some resources aren't getting freed when the dialog is closed.

**Additional context**
Reloading the editor/view (by switching to another editable object e.g. a method or class in the system browser) seems to release some resources. The dialog appears quickly again (at least initially).

**Comment by fmqa** [comment]
One interesting observation: The number of `SpRubFindReplaceService` instances increases continuously with each iteration. After the dialog is opened & closed 5 times, the total instance count reaches ~493

**Comment by Ducasse** [comment]
Good catch! There is a leak!

**Comment by fmqa** [comment]
I think I have a rough idea why it happens now. `SpRubFindReplaceService>>#textArea:` is called multiple times, causing multiple subscriptions to the `RubFindReplaceWindowRequired` topic. This seems to be triggered by `SpRubFindReplaceService>>#whenTextAreaGotFocus:` which is called by the system multiple times.

I'm not sure whether `SpRubFindReplaceService>>#whenTextAreaGotFocus:` is supposed to be fired multiple times, but generally it's not a bad idea to make `SpRubFindReplaceService>>#textArea:` idempotent. This can be done e.g. by a simple (shallow) reference check gateway. I will prepare a PR with a proposed fix and maybe somebody more experienced could suggest a better way to resolve this.

**Comment by fmqa** [comment]
@Ducasse PR #11608 is a fix that would resolve the leak. It's a bit verbose though, and there might a better way to do this.
