### ISSUE TITLE
Cancel button in find an replace does not clean the selection

### ISSUE THREAD

**Issue by akevalion** [guillep/pharo-core#11601]
Currently the Find and Replace tool highlights a selection for a given query.
But when you cancel the tool the highlighting remains.

**Description**
- in a work space write something
- press keys: cmd + f
- a new window will appear highlighting the code.
- press the buton cancel
- and the highlighted text remains.

**Expected behavior**
- cancel button should clean the highlighted text.

**Version information:**
 - OS: macOs
 - Pharo Version 11

**Comment by fmqa** [comment]
PR #11602 would change this behavior to clear the search buffer as suggested by OP. Would be a simple change if the Pharo maintainers are interested in it.

**Comment by Ducasse** [comment]
We are interested by any good changes (simple or more :)
We just need time to go over the PRs.
