### ISSUE TITLE
Review RBLiteralNode class>>#value:

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#11613]
- RBLiteralNode class>>#value: checks for the class using equality

shouldnt it check for #isArray or #isByteArray to find out if it should use RBLiteralArrayNode or RBLiteralValueNode?

I know that the #isByteArray is not yet in the image, but we can easily add it.

**Comment by MarcusDenker** [comment]
the problem is that there are subclasses of ByteArrray that are not supposed to be a RBLiteralArrayNode. it is really just that class.
