### ISSUE TITLE
Can not start Pharo: "receiver of "destroy" is nil

### ISSUE THREAD

**Issue by fmqa** [guillep/pharo-core#11616]
**Bug description**
We made an unfortunate mistake in #11610. When Pharo is initialized, `OSSDL2FormRenderer#texture` is `nil`, so sending it a `destroy` message results in a predictable DNU:

```
receiver of "destroy" is nil
UndefinedObject(Object)>>doesNotUnderstand: #destroy
UndefinedObject>>doesNotUnderstand: #destroy
OSSDL2FormRenderer>>createTexture
OSSDL2FormRenderer>>validate
...
```

**To Reproduce**
1. Run Pharo

**Expected behavior**
Pharo window with IDE appears

**Observed behaviior**
Pharo window with black screen/content appears. DNU backtrace is printed to console.

**Version information:**
 - OS: Ubuntu x64
 - Version: 22.04.1
 - Pharo (= 0445e5b23385ef258210b3709d28abf588dcf914)

**Expected development cost**
Minimal. The destroy message sender must be placed under a `nil` guard

**Additional context**
Caused by #11610 which was merged in 0445e5b23385ef258210b3709d28abf588dcf914

**Comment by fmqa** [comment]
@tesonep Sorry for unintentionally creating this issue 😥
Anyway, we really need this nil check or we risk bricking the `Pharo11` branch. #11617 should fix it & I also tested with a clean image.

**Comment by tesonep** [comment]
It is ok, who do things make mistakes. Also, I checked it and let it pass, it was a kind of vicious situation. 
Thanks a lot for the contribution and the fix, it is really important for us.
