### ISSUE TITLE
AndreasProfiler / TimeProfiler GUI does not work: No binding for ProfilerTreeAdapter found

### ISSUE THREAD

**Issue by fmqa** [guillep/pharo-core#11611]
**Bug description**
In #11532, a new menu entry for AndreasProfiler/TimeProfiler was added. However this menu entry is non-functional due to a missing binding

**To Reproduce**
1. Use Pharo10 (>= 05426434504c5d651b7a2dba7468a2264f1f959b)
2. Click on Debug → Andreas & Time Profiler

**Expected behavior**
The profiler UI is displayed

**Observed behavior**
Debugger is shown with "Error: No binding for ProfilerTreeAdapter found"

**Version information:**
 - OS: Ubuntu
 - Version: 22.04.1
 - Pharo Version 05426434504c5d651b7a2dba7468a2264f1f959b

**Expected development cost**
Minimal. The symbol should just be corrected.

**Additional context**
Can be fixed by modifying `ProfilerTreeTablePresenter class >> adapterName` so that it returns `#SpMorphicProfilerTreeTableAdapter` which I assume is the correct symbol.

**Comment by fmqa** [comment]
Note that this profiler is - at the time of writing - only merged into the `Pharo10` branch

**Comment by Ducasse** [comment]
Indeed I have the impression that it was merged to the wrong branch. It should be Pharo11.

**Comment by MarcusDenker** [comment]
This should be fixed with the revert
