### ISSUE TITLE
Unimplemented message send in FT2Face>>#emboldenOutline:

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#11634]
![image](https://user-images.githubusercontent.com/5980033/188073797-352f84dc-3d75-4438-b6e2-7231f737ad9d.png)

**Comment by astares** [comment]
![image](https://user-images.githubusercontent.com/5980033/188074306-5bd4ba9e-8872-4934-a22a-d5513ff59852.png)

**Comment by astares** [comment]
Also in FT2Face>>#glyphOfCharacter:
and FT2Face>>#glyphOfCharacter:pixelSize:
...

**Comment by fmqa** [comment]
`FT2Face>>#validate` was removed from the `FT2Handle` superclass in https://github.com/pharo-project/pharo/commit/5d782df422db7eec49883c7c5f840196abe99541 - but even then, it had an empty implementation. So it seems like this is just some forgotten leftover code 
![image](https://user-images.githubusercontent.com/7354509/188188122-6281a488-a7c0-471b-b74c-ba7f5305891d.png)

**Comment by Ducasse** [comment]
FreeType is from Squeak time and we never really looked at it but yes it is full of dust.

**Comment by MarcusDenker** [comment]
a simple fix for now could be to just remove all the "self validate" sends.

**Comment by MarcusDenker** [comment]
The empty method was removed in the superclass, but a subclass still implements it...
