### ISSUE TITLE
Enhance package/class trees in system browser to allow expanding/collapsing groups using the keyboard

### ISSUE THREAD

**Issue by fmqa** [guillep/pharo-core#11643]
The package tree & class hierarchy in the system browser is only partially navigable using the keyboard.
Moving the selected row up/down using the arrow keys is possible. However, it is not possible to expand/collapse parent nodes using the keyboard.

**Describe the request**
Improve keyboard navigation by allowing expansion/collapse of rows using arrow keys. This mirrors the behavior seen in other common GUI environments.

**Expected behavior**
GIVEN I am running the Pharo IDE
AND I start the System Browser (i.e. Calypso)
AND the package navigation pane on the left is focused
AND I navigate using the up/down arrows to a *collapsed* node with children
AND I press the *right arrow* key
THEN the node is expanded and its immediate children are shown

GIVEN I am running the Pharo IDE
AND I start the System Browser (i.e. Calypso)
AND the package navigation pane on the left is focused
AND I navigate using the up/down arrows to an *expanded* node with children
AND I press the *left arrow* key
THEN the node is collapsed and all of its children are hidden

**Expected development cost**
Minor. Can be done by adding some additional announcement types to `FTTableMorph`

**Version information:**
 - OS: Ubuntu x64
 - Version: 22.04.1
 - Pharo 10

**Additional context**
Related to #11618, where we attempt to complete the missing pieces of Pharo's keyboard navigation support

**Comment by NSUSpray** [comment]
I propose to supplement this functionality with the following. When the list item located inside the expanded node is selected, then on the pressing the Left key, move the selection to the *parent* node. At least this is the behavior in Windows tree lists.

**Comment by fmqa** [comment]
> When the list item located inside the expanded node is selected, then on the pressing the Left key, move the selection to the parent node

You are right but some problems with Calypso need to be addressed first before this works.
`ClyFullBrowserMorph>>#newClassView` unfortunately does not create a tree structure, which prevents us from querying the parent node, so even if this is implemented in FTTableMorph, it will have no effect in the class hierarchy viewer.

I prefer extending `ClyFullBrowserMorph>>#newClassView` in a separate PR in order to retain this changeset's locality of behavior. Multiple small PRs with incremental additions of functionality are likely easier & faster to review/merge.

**Comment by StephanEggermont** [comment]
I’m not sure the selection expansion on left arrow is correct. Does it behave like that when not all sibling nodes (or child nodes of siblings) are selected? Expansion is supposed to happen with shift/ctrl(cmd). It would be good to compare detailed behavior on all platforms. Otherwise, great initiative!

**Comment by fmqa** [comment]
@StephanEggermont  The GTK and Win32 treeview components follow the behavior described in Gherkin in the ticket. For OSX I have no idea but I assume it should be the same (would be great if somebody checked).

The expansion happens using the *right* arrow. The left arrow has the effect of collapsing an expanded node.

**Comment by StephanEggermont** [comment]
Ah, good. Let’s fully describe the wanted behavior, so there are no ambiguities
