### ISSUE TITLE
Can't format a new method before compiling it

### ISSUE THREAD

**Issue by sonibla** [guillep/pharo-core#11640]
**Bug description**
Error when formatting a method that isn't yet compiled

**To Reproduce**
1. Browse any class in Calypso browser
2. Go on the tab "+ Inst. side method"
3. Write anything (but don't compile)
4. Press ctrl+shift+F to format
5. Instance of ClyTextEditorContext did not understand #methodEditor

**Version information:**
 - OS: Windows
 - Pharo-11.0.0+build.182.sha.160dedc341254e1e1ec8a0dc0a2776c615834b15 (64 Bit)

**Comment by Ducasse** [comment]
I see. So we should compile it first.

**Comment by sonibla** [comment]
I'm not sure what's the best solution
Maybe we shouldn't get a ClyTextEditorContext instance but a source editor instead
