### ISSUE TITLE
Pharo CI fails with "MCPrivateHostableRepository class had the subclass responsibility to implement #basicDescription"

### ISSUE THREAD

**Issue by fmqa** [guillep/pharo-core#11657]
**Bug description**
After https://github.com/pharo-vcs/iceberg/commit/c65b0fdb3e4a319272d6e2f715467a1e8624a522 in pharo-vcs/iceberg, all CI jobs fail with the following backtrace:

https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-11655/1/pipeline/

https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-11564/9/pipeline

The relevant part is:

```
MetacelloNotification: Evaluating -> baseline [BaselineOfIceberg] >> postLoadWithDirective:projectSpec:
SubclassResponsibility: MCPrivateHostableRepository class had the subclass responsibility to implement #basicDescription
MCPrivateHostableRepository class(Object)>>subclassResponsibility
MCPrivateHostableRepository class(MCGitBasedNetworkRepository class)>>basicDescription
[ :e | e basicDescription = self class type ] in IceGithubRepositoryType(IceProviderRepositoryType)>>mcRepositoryClass in Block: [ :e | e basicDescription = self class type ]
```

**To Reproduce**
1. Trigger any CI job in the `pharo` repository

**Expected behavior**
The CI jobs run, MC and Git repositories are cloned & initialized correctly

**Version information:**
 - OS: Any
 - Version: Current git HEAD
 - Pharo 11

**Expected development cost**
Very minimal. `MCPrivateHostableRepository` must implement the message handler. Implementations in other subclasses just answer with a static descriptive string.

**Additional context**
`#basicDescription` is marked as `subclassResponsibility` here https://github.com/pharo-project/pharo/blob/Pharo11/src/Metacello-GitBasedRepository/MCGitBasedNetworkRepository.class.st#L22

An implementation of `#basicDescription` is required here: https://github.com/pharo-project/pharo/blob/Pharo11/src/Metacello-GitBasedRepository/MCPrivateHostableRepository.class.st

**Comment by MarcusDenker** [comment]
This seems to be fixed: CI is running again
