### ISSUE TITLE
Enhance text editor with menu key binding

### ISSUE THREAD

**Issue by fmqa** [guillep/pharo-core#11658]
When a text editor is in focus, pressing the menu (≣) key should open the context menu, similar to what a right click in the editing area would do.

This mirrors the behavior seen in native OS widget toolkits.

**Describe the request**
An additional key binding for the menu key (≣) is added, which - when pressed - would have the effect of opening the context menu

**Expected behavior**
GIVEN a text area is focused
AND I press the menu ≣ button on the keyboard
THEN a context menu appears

**Expected development cost**
Minor. An additional keybinding is to be added.

**Version information:**
 - OS: Ubuntu x64
 - Version: 22.04.1
 - Pharo 10

**Additional context**
Part of #11618

**Comment by NSUSpray** [comment]
In Windows, an alternative for the `Menu` key is the `Shift` `F10` shortcut. What is the situation in other operating systems? Is it worth adding this combination to the current issue?

**Comment by fmqa** [comment]
The `Menu` key is well-defined across platforms that offer it, therefore it is safe to bind. I am fairly sure that this will be an uncontroversial addition, since the behavior is uniform across Win32 and all Linux DEs.

It's been a while since I used OSX, but AFAIK - a normal Mac keyboard doesn't have a menu key. I'm not sure what the replacement is - probably "application defined".

`Shift+F10` can probably be added in `RubTextEditor class >> buildShortcutsOn` - I will see if it can be included & added to the PR
