### ISSUE TITLE
BytecodeToASTCache provides way to map program counters (=offsets) to AST nodes but it doesn't provide a way to map AST nodes to offsets 

### ISSUE THREAD

**Issue by adri09070** [guillep/pharo-core#11650]
**Describe the request**
`OCBytecodeToASTCache`provides a way to easily map a `pc` to an AST node, which is practical to go from a bytecode interpreter to an AST interpreter, which is more intuitive.

However, it does not provide an easy way to easily map an AST node to program counters, which would be practical to go from an AST interpreter to a bytecode interpreter.

This would be pratical because, to manipulate the program flow, we have to change the pc of the context which doesn't recognize AST nodes.

**Expected behavior**
I think that `OCBytecodeToASTCache` should provide an API to easily map an AST node to a list of pcs. We could also provide an API to know what are the first and last pcs that are mapped to an AST node. (Because, correct me if I'm wrong, but I think that all bytecodes mapped to an AST node are contiguous ?)

**Expected development cost**
Fairly easy.

**Comment by MarcusDenker** [comment]
merged https://github.com/pharo-project/pharo/pull/11651
