### ISSUE TITLE
ExternalAddress>>#fromCString should return raw bytes

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#11665]
**Bug description**
Currently `ExternalAddress>>#fromCString` returns a byte array utf8 decoded.
It works in case the content is utf8 encoded but it fails when the content has another encoding (e.g. Windows).
`#fromCString` should return raw bytes to let the user choose the appropriate decoder to read the String.
`ExternalData>>#readString`uses `ExternalAddress>>#fromCString` and also always returns an utf8 string.
It should also return raw bytes

We should see the impact on users of these methods: maybe define a new API to get raw bytes and add a deprecation rule

**Comment by astares** [comment]
![image](https://user-images.githubusercontent.com/5980033/189418390-b670382c-a8ba-472e-96f9-aa730128f89b.png)

**Comment by astares** [comment]
Agree - the #utf8Decoded should not be there. I guess this had been added there to fix issues when
reading win32 environment parts- Just check the current senders:

![image](https://user-images.githubusercontent.com/5980033/189418869-e66a83f4-de1e-4266-894a-ebd871194e5b.png)


We could have a #byteArrayFromCString or #asByteArray method and deprecate the method.
