### ISSUE TITLE
[CI] CI does not build 

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11677]
**Bug description**
Somehow the CI stopped building, last Pharo11 build is from 12/09 18:24

https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo11/

PRs are not building, either

**Comment by MarcusDenker** [comment]
I tried to start a Pharo11 build via the "Build now" button and nothing happens
(this is https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo11/)

Thus: it seems the github trigger works, but Jenkins just does not react.

<blockquote><img src="/pharo-ci-jenkins2/static/95cc14de/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo11/">Pharo11 [Pharo] [Jenkins]</a></strong></div></blockquote>

**Comment by MarcusDenker** [comment]
java.io.IOException: No space left on device

(I tried to download an update and got that)

**Comment by fmqa** [comment]
Jenkins signals this when the build artifact storage and/or build workspace consumes all disk space.

**Comment by MarcusDenker** [comment]
The CI now can build again, but due to mac executor probems, builds get stuck (see https://github.com/pharo-project/pharo/issues/11685)

**Comment by MarcusDenker** [comment]
Ci is up and running
