### ISSUE TITLE
Spelling error in pharo-core/EpiceaBrowsers.package/EpSettings.class/class/system settings/

### ISSUE THREAD

**Issue by grondak** [guillep/pharo-core#11674]
**Describe the problem**
This is a minor spelling error.
The word "recoveries" is spelled as "recovegin"

**Classes involved**
pharo-core/EpiceaBrowsers.package/EpSettings.class/class/system settings/ 's description selector

**Proposal**
correct the spelling
was: 'Check if current Epicea log has events that were not applied in this image (useful for recovegin changes when the image crashed)'
will be: 'Check if current Epicea log has events that were not applied in this image (useful for recovering changes when the image crashed)'

**Version information:**
Pharo 11.0.0
Build information: Pharo-11.0.0+build.196.sha.2c5288b1a96a3ea846b9a709ac60caa7250d3f56 (64 Bit)

**Expected development cost**
nothing; I will fix this myself

**Additional context**
This is my first Issue and will be my first PR. Thanks for the consideration! I'm on your discord now, too.

**Comment by MarcusDenker** [comment]
PR merged

**Comment by grondak** [comment]
Thanks, @MarcusDenker - I'll fix more if I find more.
