### ISSUE TITLE
Fresh Pharo10 image shows "red screen of death" in Welcome window

### ISSUE THREAD

**Issue by JanBliznicenko** [guillep/pharo-core#11692]
Most recent Pharo 10 image shows "red screen of death" drawing error in Welcome window opened at the start - not very welcoming :)
The error does not happen before image built from commit b6f4b11 (merge of commit c34fb46).
In previous builds (before these commits), it never happened. In this new build, it shows like that every time (does not seem random from my point of view, but it might have been caused by randomly ocurring error during building on CI/CD).
The error does not happen any other time when working with the image and it actually does not happen even if I open the same help/welcome screen any time later.
It happens on Windows 10 and Linux Mint (other not tested).

![obrazek](https://user-images.githubusercontent.com/9571633/190636062-47ae354c-b1e0-4e45-979c-a324c97b1552.png)

**Comment by MarcusDenker** [comment]
I triggered a build, this will most likely then not have this

(we should really find out what the cause is)

**Comment by JanBliznicenko** [comment]
Yes, the new build is ok. Thank you, @MarcusDenker.
I will close this issue as I believe the FreeType problem is well known and issue probably already exists (somewhere).
