### ISSUE TITLE
FileList signals a FileDoesNotExistException when opened on a directory containing a ‘dangling’ symbolic link

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#11694]
**Bug description**
`FileList` signals a `FileDoesNotExistException` when opened on a directory containing a ‘dangling’ symbolic link

**To Reproduce**
In the following example, the inspector is opened and shows the contents of the directory, but opening the `FileList` signals a `FileDoesNotExistException`:

```smalltalk
command := 'mkdir /tmp/testdir && ln -s /tmp/testdir/file /tmp/testdir/link'.
(LibC system: command) = 0 ifFalse: [ Error signal ].
fileReference := '/tmp/testdir' asFileReference.
StInspector openOn: fileReference.
FileList openOn: fileReference
```

**Version information:**
> Pharo 11.0.0
> Build information: Pharo-11.0.0+build.213.sha.ecf04188c6ad2a3c2480ca3fe3b9a2988baa1b7a (64 Bit)

**Comment by guillep** [comment]
This is not an issue anymore with the new file list

```
command := 'mkdir /tmp/testdir && ln -s /tmp/testdir/file /tmp/testdir/link'.
(LibC system: command) = 0 ifFalse: [ Error signal ].
fileReference := '/tmp/testdir' asFileReference.
fileReference inspect.
fl := Smalltalk tools fileList new.
fl openFolder: fileReference.
fl open.
```

**Comment by Rinzwind** [comment]
OK! There’s still a problem though: the file list does not show the link at all (the inspector does show the link; tested using Pharo 13 build 406).
