### ISSUE TITLE
[CI] Failing test in build: ReleaseTest>>testUndeclared

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11710]
**Bug description**
After merging https://github.com/pharo-project/pharo/pull/11704, ReleaseTest>>testUndeclared fails for every CI run.

Found undeclared Variables: RSUMLCalypsoSettings in: PharoDarkTheme>>#classBoxBackgroundColor

**Comment by akevalion** [comment]
Thank you I will work on this
