### ISSUE TITLE
RSThemedMapBuilder>>highlight sends #add: to an array

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#11712]
Open latest Pharo 11, click on a #baseline: method like BaselineOfBeacon>>#baseline: and in the "Graph" tab use the mouse to hover over a shape:

![image](https://user-images.githubusercontent.com/5980033/191727775-b10c897c-c8da-4420-b835-30831ac7909a.png)

**Comment by astares** [comment]
@akevalion I guess this is an issue to be fixed in Roassal

**Comment by akevalion** [comment]
Yes I will check it

**Comment by akevalion** [comment]
I have created a pull request, to pharo

**Comment by Ducasse** [comment]
Cool

**Comment by MarcusDenker** [comment]
please check, PR is not in the mail Pharo repo
