### ISSUE TITLE
Improve ReUtilityMethodsRule

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11720]
List methods that have one or more arguments and do no refer to self or an instance variable. These methods might be better defined in some other class or as class methods.

report error for 
```
Point >> isInRectangle: aRectangle

     ^ aRectangle containtsPoint: self
```
while clearly the method do use self!!!

**Comment by MarcusDenker** [comment]
I personally would like to remove the "Utility Methods" Rule. I not *once* acted on it and changed the code.

**Comment by MarcusDenker** [comment]
the reason for ignoring the self is that this rule checks for self messages, not self access:

```
aMethod selfMessages isEmpty ifFalse: [ ^ false ].
```

**Comment by Ducasse** [comment]
I would either fix it or remove it. 
Now marcus you have 15 years of dev in Pharo while newbies do not have it so I would fix it and we should tag the rules for newbies and expert and be able to configure the system.

**Comment by MarcusDenker** [comment]
I am looking at bad code a lot. That rule *never* lead me to improve the system *ever*. 

 Would the beginner not instead be very confused?

"the system tells me this is bad, but I do not get why". 

Expert "System is wrong". Beginner "I am wrong but I do not undestand why".

**Comment by Ducasse** [comment]
The description should be improved.
