### ISSUE TITLE
Startup Slow in OSX previous to Monterrey

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#11725]
OSX is slow to resolve the local address (it performs a DNS request for the hostname).
That takes around 5 seconds.
Pharo should not relly on the local address in the startup.
Ombu and GlobalIdentifier uses it.

https://apple.stackexchange.com/questions/175320/why-is-my-hostname-resolution-taking-so-long

**Comment by svenvc** [comment]
Yes, this is not good.

And even worse, on macOS, NetNameResolver>>#localHostAddress is basically broken (it returns nothing useful, hence 127.0.0.1 is used). So we pay this price for nothing.

AFAIK the socket plugin code for macOS is still the very old version that was written even before macOS existed. I also believe that several attempts have been done for improving this situation but I no idea what the state is. In any case, macOS should be treated like any Unix style OS, like Linux, which would simplify the code.

**Comment by svenvc** [comment]
Just a reminder: a machine can have multiple hostnames and IP addresses, which can change depending on the network you are on. Also, DNS resolution is a moving target, depending on the network you are on. Global DNS providers like Google or Cloudflare work very well, but obviously don't know anything about your local network.

This is not an easy subject.
