### ISSUE TITLE
Double click and drag does not select whole words

### ISSUE THREAD

**Issue by privat** [guillep/pharo-core#11727]
**Bug description**

You can double-click on a word to select it.
But if you drag, the word is unselected and dragging around selects characters instead of whole words.

This behavior is inconsistent with most UI elements of common applications that deals with text (text editors, web browsers, terminal emulators, pdf viewers, etc.)

**To Reproduce**
1. Open a playground
2. Write `hello world`
3. Double click between the two `l` of `hello` and keep the mouse button down
4. See that the whole world `hello` is selected (this is good)
5. Move the cursor towards the `r` of `world` while maintaining the mouse button down
6. See that `hel` is unselected, only `lo` remains selected (this is bad)
7. See also that only `wor` is selected and that `ld` is unselected (this is also bad)

extra: try the same scenario in non pharo applications where there is selectable text.

**Expected behavior**

step 6: `hello` should remain selected
step 7: when entering `world` the whole word should be selected.

**Remark**

Using shift+control and selecting with arrows, have a whole-word behavior consistent with other application.

**Version information:**
 - OS: Debian testing 
 - Pharo Version: 11

**Comment by StephanEggermont** [comment]
I don’t understand step 3. Double click ends with a mouse up. What is the exact behavior you see?

**Comment by akevalion** [comment]
I got the the same result, also I compared with vscode, atom, html textarea editor.

**Comment by privat** [comment]
@StephanEggermont 3.1. press left mouse button, 3.2. quickly release it, 3.3 quickly press it again. 3.4 keep it pressed (do not release it)

**Comment by akevalion** [comment]
Another thing,

- Open a playground
- Write hello world
- Double click between the two l of hello and keep the mouse button down
- See that the whole world hello is selected (this is good)
- Move the cursor towards the r of world while maintaining the mouse button down
- you also can press `ESC` to cancel the cut event.

**Comment by akevalion** [comment]
After review rubric code, Mouse double click only works after the second mouse up.
Then we have to modify the mouse double click event process to detect mouse double click with drag and drop events
Please check this class
`MouseClickState`

**Comment by akevalion** [comment]
I have fixed the MouseClickState, then now it accepts doubleclick drag state, but the text editor still does not recognise the drag selection word

**Comment by Ducasse** [comment]
Thanks a lot. 
This usability glitches are important!!!!

**Comment by jordanmontt** [comment]
Hi, so as this issue was solved in #11838 , we should close it and also #11744 
@akevalion
