### ISSUE TITLE
Enhance RBRefactoringChangeTest to support fluid syntax 

### ISSUE THREAD

**Issue by PalumboN** [guillep/pharo-core#11740]
The tests in `RBRefactoringChangeTest` use `oldDefinition` message, so they are testing on _non-fluid-definition_.

Should be nice to support the fluid definition as well.

**Comment by Ducasse** [comment]
Indeed we should use the fluid version of the class definition.

**Comment by MarcusDenker** [comment]
RBRefactoringChangeTest does not use oldDefinition anymore, so this is fixed
