### ISSUE TITLE
Cannot resize the "Raw" tab in an inspector.

### ISSUE THREAD

**Issue by PierreLouisPAUGAM** [guillep/pharo-core#11742]
**Bug description**
Resizing a "Raw" tab in a inspector is impossible, thus reading certain variable names is impossible.

**To Reproduce**
1. Inspect an object
2. Go to the "Raw" tab
3. Drag the vertical line between the "Variable" and the "Value" columns

**Expected behavior**
The "Variable" and "Value" columns should resize.

**Screenshots**

![Bug redimensionnement](https://user-images.githubusercontent.com/58030198/193516754-144c1fb3-01cf-4920-a0b4-136b9096c603.gif)

**Version information:**
 - OS: Windows 11 Home
 - Version: 22H2
 - Pharo Version: 10.0 - 64bit (stable)

**Comment by MarcusDenker** [comment]
This is fixed in Pharo11 already I think

**Comment by MarcusDenker** [comment]
I checked: fixed in the current development branch
