### ISSUE TITLE
Enhance Breakpoint API with "enabled:" method

### ISSUE THREAD

**Issue by Max-Zurbriggen** [guillep/pharo-core#11753]
Add the `enabled:` method to make breakpoints easier to work with when creating a UI, so that `breakpoint enabled: newState` can be used instead of an ifTrue/ifFalse block.
Change the `enable `and `disable `methods to use this new method to have a single method which changes this variable.

**Comment by Max-Zurbriggen** [comment]
This is just a small issue to work on myself and test the pull workflow with @MarcusDenker

**Comment by MarcusDenker** [comment]
PR merged
