### ISSUE TITLE
Zeroconf web page contains old information

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11752]
We should update the web page.

http://get.pharo.org/

**Comment by astares** [comment]
Yes and maybe insecure

 http://get.pharo.org (HTTP)

which shows that it has no valid certificate **could forward to secure HTTP version** 

 https://get.pharo.org (HTTPS)
 
 which provides the certificate

see https://stackoverflow.com/questions/16200501/how-to-automatically-redirect-http-to-https-on-apache-servers

**Comment by MarcusDenker** [comment]
I tried already to forward the non-https version, but that breaks clients.
(our CI stopped working, too)

**Comment by astares** [comment]
Is ci using HTTP and not HTTPS? 🤔

**Comment by guillep** [comment]
Hi, coming to this.

The zeroconf webpage seems up to date to me, it shows the Pharo11 (latest stable) download.
If there are more concrete ways to improve it, I'd be glad to do it :)

Regarding the HTTP/HTTPS I think we should do the redirection and fix the clients.
@MarcusDenker could we try it again?
We should also announce it properly so people can adapt.

In any case, I think this issue can be closed as it is.
