### ISSUE TITLE
Form fromUser not working

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#11756]
**Bug description**
`Form fromUser` does not work correctly because `Display` is not providing correct form data anymore. 

**To Reproduce**
1. eval `Form fromUser asMorph openInWindow`
2. it will open empty form of correct size

**Possible fix**
In the `Form>>#fromDisplay:`, we should use `World imageForm` instead of `Display`. However, this method and all the related ones need to then be packaged in Morphic packages because it breaks dependencies.

**Comment by guillep** [comment]
This is now working as

```smalltalk
Screenshot new formScreenshotFromUserSelection asMorph openInWindow 
```
