### ISSUE TITLE
Cannot view .ST file content with Code-File Browser

### ISSUE THREAD

**Issue by bouraqadi** [guillep/pharo-core#11762]
**Bug description**
Cannot view contents of an .ST file exported using code-file browser.
It seems to be an issue with Spec2

**To Reproduce**
- Export a class using the "Extra>File Out" menu, you get an .ST file
- Drag and drop the .st file into a fresh Pharo 10 image
- Select menu "Code-File Browser"
- Select a class in the browser
- Exception: **Instance of Set did not understand #at:ifAbsent:**

**Expected behavior**
We should be able to browse the content of the .ST files and load it into the image

**Comment by kasperosterbye** [comment]
I have been trying to look into this one.
- The DNU is reproducible.
- It has its origin in a Set which should be converted to sortedCollection in `ExternalBrowser>#refreshProtocols:`.

But then I get errors which I so far trace back to some issues with old and new ring systems. I will continue to look into this one.

**Comment by kasperosterbye** [comment]
Fixed by PR #11924

**Comment by MarcusDenker** [comment]
thanks! merged
