### ISSUE TITLE
[Debugger] Variables inspecting causes SubscriptOutOfBounds

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#11766]
**Bug description**
Certain configuration of nested blocks can break inspecting of block argument in the debugger, see bellow

**To Reproduce**
Create a class and methods like this:
```smalltalk
Object subclass: #AAA
	instanceVariableNames: 'filesByNodeId'
	classVariableNames: ''
	package: 'AAA'.

---

run 
	filesByNodeId := Dictionary newFrom: { 
		1 -> { (Dictionary newFrom: {  }) }.
	}.
	self moveFilesForNodeId: 1 fromHistoryId: 2 to: 3

---

moveFilesForNodeId: aNodeId fromHistoryId: oldHId to: newHId
	filesByNodeId at: aNodeId ifPresent: [ :arrayOfDict | 
		arrayOfDict 	do: [ :e |
			e ifNotNil: [ :dictForFileId |
				self halt.
				(dictForFileId removeKey: oldHId ifAbsent: [  ]) ifNotNil: [ :ccFile | 
				]
			]
		]
	]
```
Or install this code: [AAA.zip](https://github.com/pharo-project/pharo/files/9734736/AAA.zip)

1. run `AAA new run`
2. it will stop on a halt, do one `Step Through` so the debugger state looks like this:

![image](https://user-images.githubusercontent.com/572494/194577650-58170b6d-2d78-4fde-aabb-003b882a8044.png)

3. select the inst var `dictForFileId` and inspect it
4. `SubscriptOutOfBounds: 3`

**Version information:**
 - Pharo Version: 11
 - Build information: Pharo-11.0.0+build.244.sha.d3c55044db9f5de96a458371bf930d486dda7933 (64 Bit)

**Comment by MarcusDenker** [comment]
So we found the problem: #astScope on Context returns the wrong scope if we are just pushing a block.

```
astScope
	"Return the scope of the method or the block of this context. 
	Note: we can not just use #sourceNode as this ignores optimized blocks.
	We instead use sourceNodeExecuted and then get the the block or methodnode on the AST level.
	For the topmost context, sourceNodeExecuted is off by one but that is not a problem as 
	we still end up getting the scope  we want"

	^ self sourceNodeExecuted methodOrBlockNode scope
```

So if sourceNodeExecuted returns a block, it give that scope. In the bug case, this is the [] of the ifAbsent:.

But the block there is just pushed, we do not care about it's scope. We want the outer block of any statements,
even if that statement is a block creation.

If on the level of the AST we would not model OptimizedScope, we could just use "self method ast scope". But this omits all optimzied scope.

We had this idea: we can detect that case, as #methodOrBlockNode is the right thing to ask if the node is *not* a blocknode.

Thus this code fixes the bug.

A PR should add some tests for this, of course:



```
astScope
	"Return the scope of the method or the block of this context. 
	Note: we can not just use #sourceNode as this ignores optimized blocks.
	We instead use sourceNodeExecuted and then get the the block or methodnode on the AST level.
	For the topmost context, sourceNodeExecuted is off by one but that is not a problem as 
	we still end up getting the scope  we want"

	| node |
	node :=  self sourceNodeExecuted.
	"if we get back a block, this is a block that just got pushed. We are not interested in
	that but it's outer block"
	^node isBlock 
		ifTrue: [ node parent methodOrBlockNode scope ]
		ifFalse: [node methodOrBlockNode scope ] 
```
