### ISSUE TITLE
Dependency Tab is updated *every* time you select a new method

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11797]
**Bug description**
There is a Dependency tab now in the browser.

The problem is that it is updated (showing a progress bar) *every* time you change which method you look at.

This slows down things *a lot* and is very ugly

**Comment by maxwills** [comment]
I've been experiencing this issue to. It's very annoying. In some cases, taking more than one second for the update to complete.

It is a little tricky to reproduce. This is how I manage to do it:

1. Browse a class with numerous dependencies:
   - Do this (DelayNullScheduler browse). 
   - It should open a System Browser with the class. Notice that the Dependency tab is not present, so changing methods is instantaneous.
2.   With the class DelayNullScheduler selected in in System Browser, now click directly in the 'Kernel' package. The class should still be selected, but now the Dependencies tab is visible.
3. Select any method from the class and experience the delay.

![Screen Shot 2022-11-02 at 11 13 55](https://user-images.githubusercontent.com/1684221/199504017-8067b561-fb5e-4efa-ba3b-c86b9525e285.png)

**Comment by Ducasse** [comment]
Indeed and this is worse than that the all the note panes are all refreshed even when they are not visible.

**Comment by demarey** [comment]
With @Ducasse, we investigated this issue.
In Calpyso, tools (what is inside tabs) are created lazily. This is good.
The bad news is that any change on the selection triggers a rebuild of all tools.
It is triggered by `ClyBrowserMorph>>#changeStateBy:` (see https://github.com/pharo-project/pharo/blob/Pharo11/src/Calypso-Browser/ClyBrowserMorph.class.st#L228) that will call #rebuildAllTools.
We then get to #basicUpdateAllTools (see https://github.com/pharo-project/pharo/blob/Pharo11/src/Calypso-Browser/ClyNotebookManager.class.st#L95-L106). 
You can reproduce by putting a halt in some tool (ex: halt in `DABrowserToolMorph>>#daPackageFor:`.

We should revisit this to discard tools no more relevant to the context, inform tools of the change and let them decide if they need an update (e.g. new model) or not, and add new tools relevant to the context.

<blockquote><img src="https://repository-images.githubusercontent.com/64123480/451beb80-d08b-11e9-9ade-21d166d787d9" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">pharo/ClyBrowserMorph.class.st at Pharo11 · pharo-project/pharo</a></strong></div><div>Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk. - pharo/ClyBrowserMorph.class.st at Pharo11 · pharo-project/pharo</div></blockquote>
<blockquote><img src="https://repository-images.githubusercontent.com/64123480/451beb80-d08b-11e9-9ade-21d166d787d9" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">pharo/ClyNotebookManager.class.st at Pharo11 · pharo-project/pharo</a></strong></div><div>Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk. - pharo/ClyNotebookManager.class.st at Pharo11 · pharo-project/pharo</div></blockquote>
