### ISSUE TITLE
[Cleanup] move the creation of the condition of a breakpoint to the breakpoint class

### ISSUE THREAD

**Issue by Max-Zurbriggen** [guillep/pharo-core#11806]
The creation of the condition block for breakpoints is handled in ClyAddConditionalBreakpointCommand. Since it is directly related to Breakpoints and might be used to redefine the condition of an existing breakpoint it should be moved to the Breakpoint class.
Discussed with @MarcusDenker 

There should be no impact.

Version:
Pharo 11

The code is not very nice and should probably be revisited in the future.

**Comment by Ducasse** [comment]
Thanks. Indeed "Move Behavior to the Right Place" is always better.

**Comment by Max-Zurbriggen** [comment]
Pull request: https://github.com/pharo-project/pharo/pull/11807

**Comment by MarcusDenker** [comment]
Merged https://github.com/pharo-project/pharo/pull/11807
