### ISSUE TITLE
Inconsistent Error message or inconsistent validation in Time 

### ISSUE THREAD

**Issue by SabineMa** [guillep/pharo-core#11802]
**Bug description**

`Time hour: 24 minute: 0 second: 0 `

raises debugger with the error message "An hour must be 24 or less". But it is exactly 24. 
So, the error message should be "An hour must be less than 24"
Same for Minutes.

Why then, is seconds allowed to have 60 seconds?

![Bildschirmfoto 2022-10-18 um 12 51 39](https://user-images.githubusercontent.com/13763544/196410435-059c281a-9291-4387-a3c7-5649a1cf5159.png)

Error message does not fit to the logic.

I dont like that limitation. In Pharo 8, there was no restriction like that and it was possible to make things like:

`(Time hour: 15 minute: 120 second: 10) printString -> "'5:00:10 pm'"`

which is correct 

**Version information:**
 - OS: iOS Mac M1
 - Pharo Version [10]

**Comment by kasperosterbye** [comment]
This was changed around two years ago in #9098.
In any case, your observation that it is both inconsistent and that the error messages are misleading is correct.

The class comment of Time says:
![image](https://user-images.githubusercontent.com/17723745/201530010-0e0341f7-86f8-4b65-aac5-715e44270f95.png)

So I believe the restrictions on hour and minute are correct, but error messages wrong. And restrictions on seconds is wrong, as is the error message.

Also, it is checked that hour is not to large, while negative numbers are allowed.

Also, there is no prevention of making `Time seconds: 24*60*60`.

Hmm, at the moment the consistent way to handle would likely be to remove the half-baked tests introduced by #9098

**Comment by SabineMa** [comment]
I share your option, Kasper

**Comment by SabineMa** [comment]
fixed with [#11889](https://github.com/pharo-project/pharo/pull/11889)

**Comment by Ducasse** [comment]
This is not closed yet.
The PR was not integrated. 
For the record https://bloggie.io/@kinopyo/github-tip-closing-issue-automatically-when-the-pull-request-is-merged

<blockquote><div>Bloggie</div><div><strong><a href="https://bloggie.io/@kinopyo/github-tip-closing-issue-automatically-when-the-pull-request-is-merged">Github Tip: Closing Issue Automatically When the Pull Request Is Merged — kinopyo — Bloggie</a></strong></div><div>Suppose you send a Pull Request to fix a bug or implement a feature that is raised as an "issue" on Github. It would be tedious to remember to close it after...</div></blockquote>
