### ISSUE TITLE
Return value of inspect should be the receiver and not a SpWindowPresenter 

### ISSUE THREAD

**Issue by SabineMa** [guillep/pharo-core#11803]
a long time ago....nearly 10 years now, there was a discussion in nabble:

http://forum.world.st/inspect-returns-iOf-SystemWindow-and-not-receiver-td4692399.html#a4692587

I was very surprised about a change in pharo - > inspect did not return the receiver itself but  an instance of SystemWindow.

We are moving from Pharo 8 to Pharo 10 this days. And what do I see today?

inspect did not return the receiver itself but  an instance of SpWindowPresenter.
Who is interested in the SpWindowPresenter when doing an inspect?

I will not repeat my arguments here, they are all discussed in the dabble thread.
Most people did accept my opinion and it was changed in 2013.

I will change this in my code by creating my own inspect method but I think the community should discuss this again. I think this is a bad solution. (I start to repeat my arguments...other Smalltalk dialects, debugging etc...)

I am amused about the code carousel/Back into Future.

I did not change my opinion. 

Code as it is:
```
inspect
	"Create and schedule an Inspector in which the user can examine the receiver's variables."
	 ^ Smalltalk tools inspector inspect: self.
```

Code as it should be:

```
inspect
	"Create and schedule an Inspector in which the user can examine the receiver's variables."
	  Smalltalk tools inspector inspect: self.
     ^ self
```

**Comment by Ducasse** [comment]
Thanks sabina.
I agree with you :).

**Comment by Ducasse** [comment]
Send a PR.

**Comment by jordanmontt** [comment]
+1 (first time seeing this). I liked Marcus answer on the forum:

> So maybe we can
        -> add #inspector that returns the tool
        -> make inspect be like it was before (with documentation).
        Marcus

so,

```st
inspect
    "Create and schedule an Inspector in which the user can examine the receiver's variables."
    Smalltalk tools inspector inspect: self.
    ^ self
```

and

```st
inspector
    "Create and schedule an Inspector in which the user can examine the receiver's variables."
    ^ Smalltalk tools inspector inspect: self
```

**Comment by SabineMa** [comment]
I just got a new pharo 11 image to write the test as Stephane suggested. Then I could not reproduce the problem. 
3 inspect returns 3. Everything is fine, I can not explain what I did yesterday.
It seems that I was confused yesterday. Or I did an inspect on an inspect. 
(3 inspect inspect returns the window presenter).
So, this PR should NOT be integrated. SORRY for the noise (I'm embarrassed)

**Comment by jordanmontt** [comment]
Hello @SabineMa I just downloaded a Pharo 11 image and tried. `3 inspect` returns an instance of `SpWindowPresenter`and not `self`. So I think that the PR is still valid.

Looking at the current (19-oct-2022) Pharo 11 implementation, all the `inspect`methods return a `SpWindowPresenter`. : https://github.com/pharo-project/pharo/blob/Pharo11/src/Tool-Base/Object.extension.st

I think we should refactor all that and not only `inspect` and `inspector` 

So if can please re-open the issue and the PR :)

**Comment by SabineMa** [comment]
Hi @jordanmontt ,

did you type `3 inspect `and than do an inspect on that?
Like this?

![Bildschirmfoto 2022-10-19 um 15 44 17](https://user-images.githubusercontent.com/13763544/196708672-116ae0e8-130d-42de-84e2-bfa8119ae0b0.png)

I think this is the way I did yesterday. I am so used to use command -I that I made this mistake.

![Bildschirmfoto 2022-10-19 um 15 45 23](https://user-images.githubusercontent.com/13763544/196708908-f3e86cd3-fb92-4fc6-9e1e-db153cec876e.png)

Like this it returns an inspector on 3 which is ok.

I tried with a new Pharo 10 and a new Pharo 11 image.

Pharo11: Pharo-11.0.0+build.265.sha.89225f67e7b73b50d943da1546e70cc411c2222d (64 Bit)

**Comment by jordanmontt** [comment]
Hello @SabineMa 
If you run the command "Inspect it", you will:
- if the expresson is `3 inspect`you will open an inspector with the result of evaluating `3 inspect`which is a spec window.
- If the expression is `3` you will open an inspector with a number.

If you look at the implementation of `inspect` , `basicInspect` and `inspectOnce` you will see that the three of them return an instance of a `SpWindowPresenter`.

Look for example:
<img width="275" alt="Capture d’écran 2022-10-19 à 16 55 26" src="https://user-images.githubusercontent.com/33934979/196727343-dd94b4e3-71bd-48fd-aa95-25813df1ffe9.png">

So, I think your PR is still valid and needs to be re-opened. I also think that we should add this two things to the PR:
- deprecate `basicInspect`and renamed it to `basicInspector`. We still return the spec window.
- refactor `inspectOnce` to always return `self`.
