### ISSUE TITLE
Bad description for shortcuts in the source code

### ISSUE THREAD

**Issue by DanielCamSan** [guillep/pharo-core#11816]
**Describe the problem**
When you right click in a selected code in a method in system browser you can access to Source code option (cmd + t), then you can access to a menu to do action with the sources code, nevertheless the description of the shortcuts are not so clear and good for doing that actions for example: For "select method package" the shortcut is "cmd + e, cmd + p", but actually the right shortcut is "cmd + e + p" that do the action.
**Proposal**
I am expecting that the shortcuts that require more than one key should be written like cmd(or Ctrl for windows) + FirstKey + SecondKey + .... .  and not cmd(Ctrl for windows) + FirstKey, cmd(Ctrl for windows) + SecondKey + .... .
 - Version [e.g. Pharo 11.0]

<img width="614" alt="image" src="https://user-images.githubusercontent.com/45604840/197204818-ae9f6e3d-770a-4185-8df3-241ad1047607.png">

**Comment by demarey** [comment]
maybe we should also revisit the keymapping model to better model this use case? @guillep WDYT?
