### ISSUE TITLE
Inspector: inspected object name is truncate

### ISSUE THREAD

**Issue by LABSARI** [guillep/pharo-core#11813]
**Describe the request**
![image](https://user-images.githubusercontent.com/75275113/197166527-28d2408b-88d0-497f-aebd-db4b0aa5474d.png)
There is a lot of available space to display the name of the inspected object. 
**Expected behavior**
It should use that free space ?

**Comment by Ducasse** [comment]
We should post this issue to http://github.com/pharo-spec/newtools

**Comment by LABSARI** [comment]
> We should post this issue to [http://github.com/pharo-spec/newtools](https://github.com/pharo-spec/newtools)

I moved it to that repo, thank you.
