### ISSUE TITLE
Installing of a breakpoint in two browsers can lead to unprintable literal value

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#11823]
**Bug description**
When working with breakpoints in multiple browsers, it can break a method source code link and cause unprintable breakpoints literal. I have finally found a reproducible case

**To Reproduce**
1. create an empty standard class with one message on instance side like this:
```smalltalk
msg 

	| known | 
	known :=42.
	^ Object new + 42.
```
2. open this method in two browsers side by side.
3. move cursor in the middle of 'Object' word and install a breakpoint in one of the browsers by double clicking on the left bar next to that line
4. no breakpoint in the second browser will appear
5. do the very same thing in the second browser
6. ```smalltalk
msg

	| tmp1 |
	tmp1 := 42.
	'<an unprintable nonliteral value>'
		breakInContext: thisContext
		node: '<an unprintable nonliteral value>'.
	^ Object new + 42 ```

![Pharo_X1rAO2xPov](https://user-images.githubusercontent.com/572494/197459663-6e53d1b2-54a2-4596-850b-e24a01521457.gif)

**Comment by MarcusDenker** [comment]
This is now working
