### ISSUE TITLE
Window with 'Broken methods' opens on test run

### ISSUE THREAD

**Issue by PalumboN** [guillep/pharo-core#11834]
Running the test `RBMoveInstanceVariableToClassParametrizedTest >> testRefactoring` opens a "Broken methods" window.

This is because at the end of `RBVariableRefactoring >> transform` method the refactor opens the window.

So I propose to change the test to not have Broken methods at the end (because it is only testing the basic case).

After that, we can improve (or at least question ourselves) if it is ok that a method `transform` from a refactor opens a window. And how to test it.
It is related to @balsa-sarenac work.

 - Version: Pharo 11.0

**Comment by jordanmontt** [comment]
@Ducasse

**Comment by Ducasse** [comment]
Fixed
