### ISSUE TITLE
Forget repository Iceberg error on windows

### ISSUE THREAD

**Issue by ELePors** [guillep/pharo-core#11832]
When click on "Forget repository" in iceberg repository list contextual menu, in pharo 10.0
(Pharo 10.0.0 Build information: Pharo-10.0.0+build.532.sha.d9f862003a88bfc9a17ff12ab7a11abf1fe154a9 (64 Bit))

a Dialog proposes "Are you sure to remove your repository (...) from your image?"
a checkbox proposes to "also remove repository from file system" (which is the most often case... would be checked by default i think).
I check the box... and i click on "Ok"

i get a "CannotDeleteFileException" error... a file created by libGit blocks the deletion of the iceberg sub directory...
Even if i try it manually using my windows explorer.

When i close the Pharo image, the deletion of iceberg directory become possible.

Maybe releasing libGit ressources temporarily is a solution to remove this repository ?

**Comment by tesonep** [comment]
Fixed in https://github.com/pharo-vcs/iceberg/issues/1624
