### ISSUE TITLE
Selecting code in backwards sense produces wrong behavior in text editors.

### ISSUE THREAD

**Issue by maxwills** [guillep/pharo-core#11848]
**Bug description**
Selecting code in backwards sense produces wrong behavior of the text editors.

**To Reproduce**
1. Open a Playground
2. Write: Hello World
3. Put cursor right after the 'd', then click and drag until the word World is fully selected.
4. Press the delete key (or try to perform any action with the selected text, like copying to the clipboard).
5. See error: Nothing is deleted (Or copied).

**Expected behavior**
The selected text should be deleted (Or whatever action was performed)

**Version information:**
  - Pharo 11

**Additional context**
I identified the pr that introduced the bug and the related code. I'll propose a fix in a few minutes, which seems to work, but I'm not sure of the side effects.
Also, maybe other people are not experiencing this issue, can someone else confirm?

**Comment by adri09070** [comment]
I don't think it's only backward, is it ?

For example; when, I write in a playground: `1 / 0` and if I select forward `1` and do DoIt/PrintIt/InspectIt, it evaluates the entire line. This is so annoying

**Comment by Ducasse** [comment]
Adrien can you tell us if the partial selection is still broken because I use it often.

**Comment by adri09070** [comment]
I tried it and now  it works

**Comment by Ducasse** [comment]
THX!!!!
