### ISSUE TITLE
What is <inline:>?

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11853]
rgbMap: sourcePixel from: nBitsIn to: nBitsOut
	"NOTE: This code is copied verbatim from BitBltSimulation so that it
	may be removed from the system"

	"Convert the given pixel value with nBitsIn bits for each color component to a pixel value with nBitsOut bits for each color component. Typical values for nBitsIn/nBitsOut are 3, 5, or 8."

	<inline: true>
	| mask d srcPix destPix |
	^ (d := nBitsOut - nBitsIn) > 0
		ifTrue: [ "Expand to more bits by zero-fill"
			mask := (1 << nBitsIn) - 1.	"Transfer mask"
			srcPix := sourcePixel << d.
			mask := mask << d.
			destPix := srcPix bitAnd: mask.
			mask := mask << nBitsOut.
			srcPix := srcPix << d.
			destPix + (srcPix bitAnd: mask) + (srcPix << d bitAnd: mask << nBitsOut) ]
		ifFalse: [ "Compress to fewer bits by truncation"
			d = 0 ifTrue: [ ^ sourcePixel ].	"no compression"
			sourcePixel = 0 ifTrue: [ ^ sourcePixel ].	"always map 0 (transparent) to 0"
			d := nBitsIn - nBitsOut.
			mask := (1 << nBitsOut) - 1.	"Transfer mask"
			srcPix := sourcePixel >> d.
			destPix := srcPix bitAnd: mask.
			mask := mask << nBitsOut.
			srcPix := srcPix >> d.
			destPix := destPix + (srcPix bitAnd: mask) + (srcPix >> d bitAnd: mask << nBitsOut).
			destPix = 0 ifTrue: [ ^ 1 ].	"Dont fall into transparent by truncation"
			destPix ]

encodeBytesOf: anInt in: ba at: i
	"Copy the integer anInt into byteArray ba at index i, and return the next index"

	<inline: true>
	<var: #ba declareC: 'unsigned char *ba'>
	
	0 to: 3 do:
		[:j | ba at: i+j put: (anInt >> (3-j*8) bitAnd: 16rFF)].
	^ i+4

encodeInt: anInt in: ba at: i
	"Encode the integer anInt in byteArray ba at index i, and return the next index.
	The encoding is as follows...
		0-223	0-223
		224-254	(0-30)*256 + next byte (0-7935)
		255		next 4 bytes"		

	<inline: true>
	<var: #ba declareC: 'unsigned char *ba'>
	
	anInt <= 223 ifTrue: [ba at: i put: anInt. ^ i+1].
	anInt <= 7935 ifTrue: [ba at: i put: anInt//256+224. ba at: i+1 put: anInt\\256.  ^ i+2].
	ba at: i put: 255.
	^ self encodeBytesOf: anInt in: ba at: i+1

**Comment by MarcusDenker** [comment]
the comment says that these methods where slang methods copied over.

Maybe we an just remove the slang pragmas?

**Comment by Ducasse** [comment]
We should ask pablo and remove it if necessary.

**Comment by Ducasse** [comment]
@hernanmd hernan can you have a look?

**Comment by hernanmd** [comment]
> @hernanmd hernan can you have a look?

I just removed the method, ran the tests (all green), nothing happened. 
It seems the method can be safely removed.
I will check a bit more and make a PR

**Comment by Ducasse** [comment]
Tx!

**Comment by Ducasse** [comment]
I was wondering if removing it does not break SLang.

**Comment by guillep** [comment]
The slang pragmas should have no effect. The VM does not pay attention to these methods. They were copied to other classes, so removing the pragma is safe.
