### ISSUE TITLE
ConstantBlockClosure: raise error if called with wrong number of args

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#11901]
**Bug description**
ConstantBlockClosure right now implements all of value, value:... to return the constant.  We should not check for number of args, as the secret of speed is that #value is a quick return method here. (for BlockClosure, it does the error handling in the fail code of the value primitive, thus not slowing it down).

Failing tests:

```
testBind – MacOSX64.Collections.Sequenceable.Tests.Ordered.OrderedCollectionTest
testCull – MacOSX64.Kernel.Tests.Methods.BlockClosureTest
testCullCull – MacOSX64.Kernel.Tests.Methods.BlockClosureTest
testCullCullCull – MacOSX64.Kernel.Tests.Methods.BlockClosureTest
testCullCullCullCull – MacOSX64.Kernel.Tests.Methods.BlockClosureTest
```

Solution: we should add 5 subclasses, zero to 4 args, with the incorrect eval methods raising the exception. Clean constant blocks with more than 4 (or even 3) args we should compile as normal CleanBlocks, they are  not used often and thus optimizing that case is not important.

**Comment by MarcusDenker** [comment]
Some numbers:

```
allBlocks := Smalltalk globals allMethods flatCollect: [:meth | meth ast blockNodes ].

currentFullBlocks := allBlocks select: [:blockNode | blockNode isInlined not].


"What we can compiler as clean Blocks"
cleanBlocks := currentFullBlocks select: [:blockNode | blockNode isClean].
cleanBlocks size "11093". 

"the clean blocks are actually just constant"
constantBlocks := cleanBlocks select: [:blockNode | blockNode isConstant].
constantBlocks size "3200".

constantBlocks count: [ :block | block arguments size = 0 ]. "2732"
constantBlocks count: [ :block | block arguments size = 1 ].  "353"
constantBlocks count: [ :block | block arguments size = 2 ].  "91"
constantBlocks count: [ :block | block arguments size = 3 ].   "14"
constantBlocks count: [ :block | block arguments size = 4 ]. "6"
constantBlocks count: [ :block | block arguments size >4 ] "4"
```

**Comment by MarcusDenker** [comment]
From the stats, we should do just 
-> use ConstantBlockClosure for 0-arg blocks
-> add a subclass for 1 and 2 args each.

The others will then be still compiled as normal Clean Closures, which means we get still the same speedup for creation, just evaluation will stay the same as it is now.

**Comment by guillep** [comment]
I like the idea of having clean blocks specialized for 0/1/2/3 args (or the most common actually) :)
