### ISSUE TITLE
Pharo compound shortcuts (e.g. #windowMaximizeShortcut) let the last character bleed onto text editor in focus

### ISSUE THREAD

**Issue by ironirc** [guillep/pharo-core#11915]
**To Reproduce**
1. Open any window with a text editor in focus. (transcript, method editor, ...)
2. Use a compound shortcut, such as windowMaximizeShortcut  =>   $w shift meta , $s
3. Observe that the shortcut has had it's desired effect.
4. The bug: Observe that the last char 's' has been added to the currently edited texteditor

**Version information:**
 - OS: Windows 10
 - Pharo 10/11

**I propose following edit**
```Smalltalk
Morph>>#handleKeyDown: anEvent
    "System level event handling."

    anEvent wasHandled ifTrue:[ ^ self ].
    
    self shortcutsHandler ifNotNil: [:handler | 
        handler handleKeystroke: anEvent inMorph: self.
        anEvent wasHandled ifTrue: [
                    "ADD THIS =>" anEvent supressNextKeyPress: true. 
                     ^ self]].
    
    (self handlesKeyDown: anEvent) ifFalse:[ ^ self ].
    anEvent wasHandled: true.
    self keyDown: anEvent.
    ^ self eventHandler ifNotNil: [ :handler | handler keyDown: anEvent fromMorph: self 
```

**Comment by Ducasse** [comment]
Thanks!
did you run the pharo tests? Did you try some other key binding?

**Comment by ironirc** [comment]
In a fresh unmodified Pharo10 image I ran ALL tests, resulting in: 
28069 ran, 27987 passed, 129 skipped, 62 expected failures, 9 failures, 11 errors, 0 passed
[tests_Pharo10.0.0_2022-11-19_22-23-39.txt](https://github.com/pharo-project/pharo/files/10056019/tests_Pharo10.0.0_2022-11-19_22-23-39.txt)

Then I patched method `Morph>>#handleKeyDown:` and ran all tests again:
28069 ran, 27982 passed, 129 skipped, 62 expected failures, 16 failures, 9 errors, 0 passed 
[tests_Pharo10.0.0_2022-11-20_13-34-15.txt](https://github.com/pharo-project/pharo/files/10056018/tests_Pharo10.0.0_2022-11-20_13-34-15.txt)

Ideally there wouldn't have been any problems in the first run, or at least both results should be the same, but second time there are some extra problems, even though they seem unrelated to the change.
Should I try another strategy?

I tried several key binding combinations, and they al work fine after applying the proposed patch.

**Comment by Ducasse** [comment]
Thanks some tests are not well done and cannot be repeated. We should identify them and fix them but this is another issue.

**Comment by Ducasse** [comment]
Can you do a PR for P11?
Do you need help or explanation?

**Comment by ironirc** [comment]
I just posted the PR. Keeping fingers X.
I see now in the comparison there are many differences in the edited method, but this is due to reformatting. (auto-format)

**Comment by Ducasse** [comment]
Thanks!

**Comment by ironirc** [comment]
Looking at:
https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-11954/1/pipeline/46

What does this mean exactly?  Is there a problem on unix os? 

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-11954/1/pipeline/46">Jenkins</a></strong></div></blockquote>

**Comment by MarcusDenker** [comment]
Unix somehow did not finish and was aborted, I re-started the CI run to see... most likely this is not related to the change (as Mac and Win are green)
