### ISSUE TITLE
Code file in raises an error

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11938]
- Drop one st file on the image
- Select Code file in
- click on the class -> boum

**Comment by MarcusDenker** [comment]
I can not reproduce this 

- do you have the code that you tried to file in?

**Comment by Ducasse** [comment]
May be the recent fix of kasper fixed this. 
I just checked with the two files of yesterday and it was recently fixed. Strange because yesterday I used the latest version of yesterda.

**Comment by Ducasse** [comment]
I just hope that we have tests for this.
