### ISSUE TITLE
EpHasImpactVisitor>>visitProtocolRemoval: incorrectly marks event as having an impact

### ISSUE THREAD

**Issue by akgrant43** [guillep/pharo-core#11941]
**Bug description**
EpHasImpactVisitor>>visitProtocolRemoval: incorrectly answer true for protocols that only have trait inherited methods. In this case removing the protocol doesn't have any impact since no methods are removed and the protocol will be kept anyway due to the trait method(s).

**To Reproduce**
RBSmalllintTestLocalMethodsSameThanTraitObject's `private` protocol contains only trait methods, so the protocol removal will have no affect (this can be tested by removing it in Calypso, the protocol will still exist and all methods will be present).

The following script should pass:

```
self assert: ((RBSmalllintTestLocalMethodsSameThanTraitObject methodsInProtocol: #private) allSatisfy: #isFromTrait).
event := EpProtocolRemoval
	behavior: RBSmalllintTestLocalMethodsSameThanTraitObject asRingDefinition 
	protocol: #private.
visitor := EpHasImpactVisitor inEnvironment: self class environment.
self assert: (event accept: visitor) not.
```

however the final assertion will fail.

**Expected behavior**
The above script passes.

**Version information:**
 - OS: Ubuntu
 - Version: 22.04
 - Pharo Version: 10 & 11

**Expected development cost**
PR on the way.

**Comment by Ducasse** [comment]
Thanks Alistair!
