### ISSUE TITLE
Quick method search in classes stopped working

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#11943]
**Bug description**
In Calypso, in the methods list, it was possible to start to write method beginning to jump to it (while the written text was shown in a small input field under the list). It stopped work but can sometimes work if you do search (Ctrl+F) and close it immediatelly with Esc.

**To Reproduce**
1. Go to class 'Announcement'
2. Click on the first method (`affectsClass:`)
3. press the key `E`
4. nothing happends

**Working case (with extra search)**
1. Go to the class `Announcement`
2. Click on the first method (`affectsClass:`)
3. press `Ctrl+F`
4. press `Esc`
5. press `E`
6. the selection jumps to the `emit` method, input field is show and `e` written into it

**Comment by Ducasse** [comment]
agreed and we need it back

**Comment by fmqa** [comment]
Which version/platform? Is this on Pharo11 HEAD?

**Comment by pavel-krivanek** [comment]
> Which version/platform? Is this on Pharo11 HEAD?

yes

**Comment by tesonep** [comment]
Duplicated #11724
