### ISSUE TITLE
Remove ChangeSet and changeSetSorter and other

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11940]
- This is legacy and broken 
- Remove it please.

**Comment by jecisc** [comment]
First step would be to remove NewTools-ChangeSorter from NewTools since it is using it

**Comment by MarcusDenker** [comment]
We should think about if this is for now or not better for after Pharo11 is released.

**Comment by MarcusDenker** [comment]
Done by merging https://github.com/pharo-spec/NewTools/pull/634
