### ISSUE TITLE
Better description "packages unloaded packages"

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#11969]
Confusing errror message. Can we get a better message/description for this dialog (and maybe a button to select all packages) here?

Also better say "wish to load them into the image" and not "which to load them in the image"

![image](https://user-images.githubusercontent.com/5980033/203762682-a0985560-0028-41ee-9def-aa4c770d8236.png)

**Comment by hernanmd** [comment]
I implemented a command to select all packages. However I wanted to test it, but I'm not sure under which conditions the dialog appears.

Could you provide a way to reproduce this issue?

**Comment by astares** [comment]
Unfortunately not - it is the 100$ question. Cant remember which project I had trouble with..

**Comment by hernanmd** [comment]
In https://github.com/pharo-vcs/iceberg/pull/1672

**Comment by jecisc** [comment]
To reproduce:
- Create a branch in your project and do a commit removing a package (removing from the repository AND the image)
- Checkout original branch

It'll add you which removed packages you want to load back in the image

**Comment by hernanmd** [comment]
Thanks @jecisc I've sent a PR so I hope it gets integrated, maybe @guillep could help with the review?

**Comment by guillep** [comment]
I'll close this issue, as the PR/issue that counts lives in iceberg (https://github.com/pharo-vcs/iceberg/pull/1672).
I'll comment in there.
