### ISSUE TITLE
Cleanup STON classes who show lint issue on categorization of #initialize

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#11963]
fix lint

![image](https://user-images.githubusercontent.com/5980033/203670743-b79cefda-80a3-4e47-b2b6-14fbd134a8ba.png)

**Comment by astares** [comment]
Also:
 - STONReader>>#initialize
 - STONTestUser>>#initialize
and other. Would be good to fix them all

**Comment by svenvc** [comment]
Tracked upstream https://github.com/svenvc/ston/commit/e49b179a330740f7b274fd66fa421a71514810c5
