### ISSUE TITLE
"Copy stack to clipboard" doesn't copy the whole stack

### ISSUE THREAD

**Issue by ValentinBourcier** [guillep/pharo-core#11973]
**Describe the request**

The functionality "Copy stack to clipboard" accessible from the right click contextual menu when hovering a stack is not copying the whole stack. 

**Expected behavior**

As it was reported by Éric Le Pors and Pierre Laborde (from Thales), the user expects the whole stack to be copied. 

**Observations + Expected development cost**

According to the tooltip on the menu, it is voluntary to copy only a part of the stack. 
By looking in the code, we can observe that only the first 30 elements can be copied to the clipboard.

As it seems not possible to select exactly what to copy, nor to copy the stack entirely, some of the information that the user wants to extract may be missing. This limit is therefore irrelevant and has to be deleted.

Time estimated: less than an hour.

**Version information:**

 - OS: MacOS
 - Version: 12.2.1
 - Pharo Version: 11

**Future work ?**

When digging more into the accesses to the stack data, I've found several locations in the code where there is a limit (30, 100, 9999, 100 000) of the number of elements to fetch from the context when building the stack. They look arbitrary and are not documented. Its out of the scope of this enhancement, but may be the starting point for future work of improvement of the codebase.

**Comment by MarcusDenker** [comment]
We merged both

- https://github.com/pharo-project/pharo/pull/11983
- https://github.com/pharo-spec/NewTools/pull/442

What needs to be done?

I tried it now in the lastest image, and it copies almost nothing, like 20 lines.

So something still needs to be done

**Comment by MarcusDenker** [comment]
this was fixed
