### ISSUE TITLE
Fix lint issue in LGitDiffHunk class>>#initialize

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#11976]
fix lint issue in LGitDiffHunk class>>#initialize, I guess it is a separate project

**Comment by hernanmd** [comment]
Could you clarify which specific lint? I only see a "Inconsistent method classification"

**Comment by astares** [comment]
![image](https://user-images.githubusercontent.com/5980033/215174606-84f59af3-a990-426a-bcad-8f26b742eafc.png)

@hernanmd Yes this one.

It's a critique on method categories. The class side method #initialize should be put into "class initialization". One can use the autofix.

**Comment by MarcusDenker** [comment]
or is here: https://github.com/pharo-vcs/libgit2-pharo-bindings/pull/72
