### ISSUE TITLE
Creating a package that already exist raises an exception

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11995]
ClySystemEnvironment>>createPackageNamed: packageName should capture the exception RPackageConflictError and select the correct package instead.

```
ClySystemEnvironment>>createPackageNamed: packageName
	^packageOrganizer createPackageNamed: packageName
```

**Comment by fmqa** [comment]
Hello Dr @Ducasse I attempted to fix this in #12048 
I also tried to add a bit of test coverage
