### ISSUE TITLE
Removing more help classes

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11994]
We can nearly finish the removal of help classes....

**Comment by MarcusDenker** [comment]
Is there a list of what still needs to be done?

**Comment by MarcusDenker** [comment]
So
- No package with -Help left
- No class with name Help

So this seems to be done

**Comment by astares** [comment]
Also nothing left in help menu:

![image](https://user-images.githubusercontent.com/5980033/207095753-839865ce-e363-4967-b793-33ad2329523d.png)
