### ISSUE TITLE
Pharo UML-Class Hierarchy Help message spelling mistake

### ISSUE THREAD

**Issue by diego-crespo** [guillep/pharo-core#12002]
**Describe the problem**
In the UML-Class hierarchy of the System browser view their is a spelling mistake in the help shortcut menu. It says "Use scrool bars to navigate" instead of "Use scroll bars to navigate"

**Classes involved**
I'm unsure

**Proposal**
Change the description to say  "Use scroll bars to navigate"

**Version information:**
 - Version 10.0
 - Windows 10
 
**Expected development cost**
I'm unsure where exactly this change would need to be made but I think it should be a quick fix

**Additional context**
I've added a [screenshot of the issue](https://imgur.com/a/6Xgk9Ft)

**Comment by Ducasse** [comment]
Thanks for the report!!!
Hi milton :)
I think that this is for you :)

**Comment by astares** [comment]
@akevalion

**Comment by akevalion** [comment]
Working on it

**Comment by akevalion** [comment]
A new version of roassal has been created

**Comment by MarcusDenker** [comment]
merged
