### ISSUE TITLE
Performance Regression in Fuel Serialization of Blocks & CompiledMethods

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#12006]
The CI is breaking with the test FLContextSerializationTest.testDoIt
This test is failing because Fuel has a performance regression.

In Pharo 11:

```
[FLContextSerializationTest run: #testDoIt] timeToRun. "0:00:00:05.642"
```

In Pharo 10:
```
[FLContextSerializationTest run: #testDoIt] timeToRun. "0:00:00:00.016"
```

I have profiled and I see that the issue is in the implementation of: 

FLFullGeneralMapper>>#shouldSerializeCompiledMethodFully:

**Comment by MarcusDenker** [comment]
Nice catch.. I will check

**Comment by MarcusDenker** [comment]
So shouldSerializeCompiledMethodFully: was introduced by the newer Fuel version, it did not exist in Pharo10.

What makes it slow is that it calls FLFullGeneralMapper>>#isBehaviorAnonymous: which does a 

```
(self environment includes: aBehavior instanceSide)
```

The environment is "Smalltalk globals", so this is very very slow.

**Comment by MarcusDenker** [comment]
This is called via #shouldSerializeBehaviorFully: *a lot* and to me it looks like it should make Fuel very very very slow
(and even sower as more classes there are)

**Comment by MarcusDenker** [comment]
I tag @theseion , he should know if this slow code is really needed

**Comment by MarcusDenker** [comment]
Ah, no, this is some part of the runtime, but there are other reasons, investigating...

**Comment by theseion** [comment]
I'll check.

**Comment by theseion** [comment]
I just downloaded the latest development image and see the same short time as in Pharo 10 and previous builds of 11. I'm running on a MacBook Air M2.

**Comment by MarcusDenker** [comment]
If I put a halt in FLLightGlobalMapper>>#mapAndTrace: in the case where it traces globals:

```
(globals includes: anObject) 
		ifTrue: [ self halt. self mapAndTraceByClusterName: anObject to: FLGlobalValueCluster ]
		ifFalse: [ next mapAndTrace: anObject ]
```

I do get a halt, for WordMorph.  Do we serialize all the state of all the Global Variables?

**Comment by MarcusDenker** [comment]
the test is:

```
testDoIt
	"Serialization of DoIt methods should be possible by default.
	Note: we store the context as a global instead of using a local variabl
			to avoid the creation of a closure that will include the test instance.
			If that happened it can pull in most of the image, depending on how the
			test was executed.
	Note: we run the evaluation in a separate process to minimize the number of
			contexts that will be serialized (potentially pulling in a large number
			of additional objects)"

	[ [ Smalltalk compiler evaluate: 'self error' ]
		on: Error
		do: [ :error |
			self environmentOfTest
				at: #FLGlobalVariableForTesting
				put: error signalerContext copyStack ] ] forkAndWait.

	self serialize: (self environmentOfTest at: #FLGlobalVariableForTesting)
```


We compile all closure with outerContext and receiver, the idea described in the comments to not use local variables has no effect: the outerContext of the block is still there.

If I add

<compilerOptions: #(+ optionBlockClosureOptionalOuter)>

It suddenly work fast.

**Comment by MarcusDenker** [comment]
I think why this started to fail: the definition of #isClean was wrong, it was not recursive.. this could have meant that a block was detected as clean that now it not clean, changing how blocks are serialized in this case.

see https://github.com/pharo-project/pharo/pull/11900

**Comment by MarcusDenker** [comment]
I think what happend: according to the non-recursive #isClean that we used to have,  this closure was clean:

```
 [ Smalltalk compiler evaluate: 'self error' ]
		on: Error
		do: [ :error |
			self environmentOfTest
				at: #FLGlobalVariableForTesting
				put: error signalerContext copyStack ] 
```

so fuel treated it as a clean block, calling #cleanCopy. But it is *not* clean, as it contains a non-clean block that accesses "self". So now fuel detects it as not-clean, leading it to serialize the outerContext.

The fix is a bit of a workaround, but then, not using temps is already one, too.

**Comment by theseion** [comment]
Nice catch!
Here's a proposal for a revised test case. Does it solve your issue (it won't solve the issue on the CI, for that we probably need to trim the stack)?

```smalltalk
testDoIt
	self serialize: self compileDoIt
```

```smalltalk
compileDoIt
	| theClass |
	theClass := self classFactory silentlyNewClass.
	self classFactory 
		silentlyCompile: 'm  ^ 42'
		in: theClass
		storingSource: false.
	^ theClass methodDict
		at: #DoIt
		put: (theClass methodNamed: #m)
```

**Comment by MarcusDenker** [comment]
what is a bit problematic is that Doit methods are never installed in a class. So if we add a method, do we really test doit execution?

**Comment by theseion** [comment]
Good point. I wasn't able to quickly figure out a way to create a doit for the test. Is there a simple method? I only saw the complicated setups in the RB tests.

**Comment by MarcusDenker** [comment]
I think the best is if we ask the compiler to compile an expression:

```
theCompiledMethod := Smalltalk compiler
			source: '^41';
			noPattern: true;
			compile.
```

**Comment by MarcusDenker** [comment]
if you inspect that, it looks correct: no method signature, AST is an RBDoItNode, source is encoded in the trailer...

**Comment by theseion** [comment]
Nice. So does this fix the issue?

```smalltalk
testDoIt
	| method |
	method := Smalltalk compiler
		source: '^41';
		noPattern: true;
		compile.
	self assert: method isDoIt.
	
	self serialize: method
```

**Comment by MarcusDenker** [comment]
For FLCompiledMethodSerializationTest>>#testDoIt this is nice, but FLContextSerializationTest>>#testDoIt wants to test that you can serialize the stack of an error raised by a doit.

**Comment by theseion** [comment]
Yes, for that I need a different approach. I can cut away the bottom contexts, but in the end, that will not fix the issue on the CI. I'll have to think about what makes sense there.
