### ISSUE TITLE
print ou of bench are not easily comparable

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#12019]
instead of 
```
"After: 
'18266371.200 per second'"
"Before: 
'10208252.099 per second'"
```
I would like to have 
```
"After: 
'18 266 371.200 per second'"
"Before: 
'10 208 252.099 per second'"
```

**Comment by MarcusDenker** [comment]
It could return an object in instead of a string fro easy comparing

**Comment by NSUSpray** [comment]
Perhaps we should use commas `18,266,371.200` instead of spaces, as in US/GB typography.
https://en.wikipedia.org/wiki/Decimal_separator#Digit_grouping

<blockquote><div><strong><a href="https://en.wikipedia.org/wiki/Decimal_separator#Digit_grouping">Decimal separator - Wikipedia</a></strong></div></blockquote>

**Comment by Ducasse** [comment]
Well in french and spanish there is another convention :)
So guille was suggesting that we use 18_266_371 so that we can manipulate too. 
@MarcusDenker I think that we should build a little class that takes two expressions and returns 
all the stats you compute all the time.

**Comment by svenvc** [comment]
The method #benchFor: already returns a BenchmarkResult object.
The simpler #bench calls #benchFor: for 5 seconds and returns the #shortPrintString.

BTW, there is no way around it, by default a US or GB locale is used.
Floats are printed with a dot as decimal point, not comma.

**Comment by MarcusDenker** [comment]
- why not return the BenchmarkResult result object? This way we can even implement a compare operation there, this way we would never need to do that by hand.
