### ISSUE TITLE
String that freezes Playground in Pharo 10 and 11

### ISSUE THREAD

**Issue by olekscode** [guillep/pharo-core#12064]
If you create a new Pharo 10 image, open a Playground paste the following commit SHA, it will freeze the image:
```
49781e985875315d06c5991f094c30d6f8c9f02d
```
It will also freeze for some time (but shorter) if you paste the first 12 characters:
```
49781e985875
```

**Comment by Ducasse** [comment]
I confirm and it is super surprising.

**Comment by olekscode** [comment]
I think it could be the completion

**Comment by Ducasse** [comment]
I do not know but it is also a problem in P11

**Comment by MarcusDenker** [comment]
It is the Scanner. The Scanner uses NumberParser to parse numbers, and 49781e985875 is read as an integer 49781 to the power of 985875.

Now NumberParser>>#makeIntegerOrScaledIntegerOrFloat creates the number for real, but it is so large that we can not do it

**Comment by MarcusDenker** [comment]
Solution: we could restrict NumberParser>>#readExponent to not try to create exponents that are too large to be practically computable

**Comment by Ducasse** [comment]
I prefer that :)
Indeed may be we should have virtual numbers :)

**Comment by olekscode** [comment]
I like how unlikely it was to find this bug :)
There must have been many numbers, then letter "e" and then many numbers

What a chance :)

**Comment by MarcusDenker** [comment]
fixed by https://github.com/pharo-project/pharo/pull/13840
