### ISSUE TITLE
iceberg browse icon broken

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#12062]
**Bug description**
Iceberg browse icon broken.

**To Reproduce**
In a repository working copy, right-click on a package

![Capture d’écran 2022-12-07 à 09 11 25](https://user-images.githubusercontent.com/2494203/206124195-6d95963d-0111-4345-a7a2-6e88f59729be.png)

**Comment by demarey** [comment]
In fact, there is no icon defined for these actions.
It is strange to get this white line instead of nothing

**Comment by tesonep** [comment]
I have fixed in the icons repository, it will be updated in the next build.
