### ISSUE TITLE
Confusing print of symbol in debugger diff

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#12079]
I'm debugging a little program that manipulate symbols.

![Capture 2022-12-10 at 10 14 17](https://user-images.githubusercontent.com/432549/206842815-ea541b87-9d5c-472f-b76f-a03b05fde295.png)

**Comment by Ducasse** [comment]
I expect a symbol but the right value does not show me the # symbol and for the value returned (while it return the bogus value e.g., #'#east' I see only #east.

**Comment by guillep** [comment]
Yes, it's probably using asString instead of printString

**Comment by Ducasse** [comment]
Indeed. 
For my problem I learned that '#foo' asSymbol is not #foo :)

**Comment by StevenCostiou** [comment]
The problem seemed to be that by default, spec view (or morphic?) just remove the `#` character when printing symbols.
I forced the debugger to display the symbol as a string so that, in the debugger, this problem does not appear.

**Comment by Ducasse** [comment]
Cool merci
