### ISSUE TITLE
FinderUI should be rewritten using Spec2

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#12082]
FinderUI Right now this is a MorphTreeModel (of course) ;)

**Comment by n1toxyz** [comment]
I am in the process of rewriting the UI in Spec2 and made the following mockup. I took the liberty to change the layout a bit as I think that the help text takes just to much space and is pretty much useless.

 I plan to replace it with a dialog that pops up when opening the finder and you can then hit a checkbox to prevent further pop ups in the future. I still added a help button that will open the dialog if needed.

Additionally I added radio button icons to the packages button to show which one is active and a status bar which gives a little info about how many packages are searched and how many results a search produced.

Please tell me what you think about it so far.

![finder](https://user-images.githubusercontent.com/29785597/209434510-fba3c7e4-0485-4248-8c37-e951230128df.png)

**Comment by Ducasse** [comment]
This is really excellent and this will ***REALLY*** help us. Because our goal is to rewrite all the old tools in Spec so that 
we can move on.
This is funny because after all these years I never ever click on any of the buttons :)
Now I pressed them and may be a menu would be better.
Carolina was working a scope browser so that we can have better control on search, refactorings application ....
and we will be able to plug it on the side of packages.... so this is cool.

**Comment by hernanmd** [comment]
This is nice, @n1toxyz do you have something to push so we can check?

**Comment by n1toxyz** [comment]
I am still on it, but need a few more days. I have something nice, however I am still fiddling around with notifying the presenter of changes. I reimplemented the finder model too, as it was really confusing and not really extensible. I created a separate super class for searches and adding searches is as easy as subclassing it and then adding it to the finder. In 2 - 3 days I should have a WIP commit.

**Comment by Ducasse** [comment]
Ok I guess that we will have to do it.
And probably revisit the finder model first

**Comment by hernanmd** [comment]
I had a look and did some minor fixes to load the project.

```smalltalk
Metacello new
 	 baseline: 'NewToolsFinder';
 	 repository: 'github://hernanmd/NewTools-Finder:main/src';
 	 load.
	
StFinderPresenter open.
``` 

I think it is usable althout two major features should be implemented:

- Add tests
- Add the "Examples" search (I use it a lot at least)

**Comment by Ducasse** [comment]
Me too!

**Comment by Ducasse** [comment]
I tried and this looks good. 
Now how can we see the code of some items.

![Capture 2023-12-19 at 13 30 53](https://github.com/pharo-project/pharo/assets/432549/32fea24b-76ba-4939-ae31-31dccdda17ec)

**Comment by Ducasse** [comment]
It was super handy to see the code in the pane.

**Comment by hernanmd** [comment]
I will add the code pane below and send the PR for review.

**Comment by Ducasse** [comment]
Excellent. 
I would be nice to have a menu for the items too.

**Comment by hernanmd** [comment]
BTW I've included a code pane in the results and transferred the ownership to https://github.com/pharo-spec/NewTools-Finder (will continue development there)



<blockquote><img src="https://opengraph.githubassets.com/b66c3aadeac06848214fbd5043f65f09b3d1d48c25ef5973b09c10680e9761a8/pharo-spec/NewTools-Finder" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-spec/NewTools-Finder">GitHub - pharo-spec/NewTools-Finder: New implementation of the Pharo Finder in Spec2</a></strong></div><div>New implementation of the Pharo Finder in Spec2. Contribute to pharo-spec/NewTools-Finder development by creating an account on GitHub.</div></blockquote>

**Comment by astares** [comment]
@hernanmd should we not have it like any other Pharo tool in NewTools repo
https://github.com/pharo-spec/NewTools as an own package

<blockquote><img src="https://opengraph.githubassets.com/8d2663ccbc7be8e1294f4de01561fd1cc807e63ff06d001934f40c6a384c157a/pharo-spec/NewTools" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-spec/NewTools">GitHub - pharo-spec/NewTools: All development tools for Pharo, developed with Spec</a></strong></div><div>All development tools for Pharo, developed with Spec - GitHub - pharo-spec/NewTools: All development tools for Pharo, developed with Spec</div></blockquote>

**Comment by Ducasse** [comment]
Tx!
