### ISSUE TITLE
Fluid class definition is not updated when we click on class side. 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#12088]
![Capture 2022-12-10 at 17 11 52](https://user-images.githubusercontent.com/432549/206864400-d4d4bb39-022d-4527-9db5-4bb5ad3a8d24.png)
![Capture 2022-12-10 at 17 11 44](https://user-images.githubusercontent.com/432549/206864402-877bae0a-701b-4f8b-8bc0-f1d28d391f44.png)

**Comment by Ducasse** [comment]
with old format too.

**Comment by Ducasse** [comment]
Works with Pharo 11.0.0
Build information: Pharo-11.0.0+build.320.sha.3d8cd5d3bbbc42f1e91559d479bb783234342647 (64 Bit)

**Comment by Ducasse** [comment]
I tried to quickly see if I could fix it but I failed.

**Comment by Ducasse** [comment]
In fact I cand see instance methods now only class side 

Pharo 11.0.0
Build information: Pharo-11.0.0+build.320.sha.3d8cd5d3bbbc42f1e91559d479bb783234342647 (64 Bit)

So the bug was introduced before.

**Comment by fmqa** [comment]
I've looked into it, Dr. @Ducasse 

A careful review of the changesets indicates that 453b64f494e10279a143150abba691e27a6d27f6 is the cause of the regression. There is a subtle omission in `ClyClassEditorToolMorph>>isValidInContext:` where it does not check the meta-level (class, instance) within the "dirtyness/validity check" of the Calypso tool.

Incorporating a metalevel check should alleviate the issue. I will see if I can propose a PR for this.

**Comment by Ducasse** [comment]
THANKS A LOT!!!!!
You are helping us!!!
I will try to have a look because this is really blocking me :)
