### ISSUE TITLE
Pharo11: Welcome Window

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#12099]
**Bug description**
The Welcome Window is not there anymore in the latest builds

**Comment by astares** [comment]
I guess by intention - Help classes like **WelcomeHelp** and the in-image help system with packages like

 - HelpSystem-Core
 - HelpSystem-Tests

had been removed. (no replacement, no deprecation round)

I guess to have "static" documentation externally based on Microdown later.

**Comment by Ducasse** [comment]
This is not later. This is for P11.
The documentationBrowser should be loaded and we get all the help in microdown and more. 
You can try if you load NewTools-DocumentationBrowser.
And it works well.
