### ISSUE TITLE
Calypso: Self on a <script:> pragma is the origin trait instead of the user class

### ISSUE THREAD

**Issue by tinchodias** [guillep/pharo-core#12107]
**Bug description**

When a trait method defines a <script:> and you browse a trait user in Calypso and execute this script using the icon button, self refers to the trait instead of the user.

I think nobody would expect that a script defined on a trait is really executed on the trait and not on the user class. But I may be missing a scenario.

**To Reproduce**

1. Open Transcript.
2. Evaluate to read a traced "TraitWithScript": 
```
t := Trait named: #TraitWithScript.
t class compile: 'traceYourself
	<script: ''self traceYourself'' >
	self traceCr'.
t traceYourself.
```
3. Evaluate to read a traced "OneUserOfScripts", as I'd expect:
```
u := Object subclass: #OneUserOfScripts uses: t.
u traceYourself.
```
4. Evaluate `u class browse` and click on the method icon to run script, to read a traced "TraitWithScript" as I wouldn't expect.

**Expected behavior**
I expected that "self" in a <script: 'self' > pragma is bound to the method class instead of the method origin.

**Version information:**
 Pharo 11, probably others too.

**Expected development cost**
The main question is the impact on existing pragmas on traits that assume that self is the trait instead of the user. I didn't query it on the image, but anyway external projects are affected, of course. **What's your opinion?**

The solution would be simple: change `ClyClassScript>>#implementorClass` to answer  `implementorMethod methodClass` instead of `implementorMethod origin`

**Comment by MarcusDenker** [comment]
it should be the class that you look at, not the origin

Change should be not a problem as we do not use the feature a lot, and where we use it, the fixed behavior is what you want

**Comment by tinchodias** [comment]
Thanks for the comment. I will do a PR
