### ISSUE TITLE
ReAbstractCritique asModalWindow

### ISSUE THREAD

**Issue by labordep** [guillep/pharo-core#12110]
The bug appear when clicking on a code modification suggestion : 

![image](https://user-images.githubusercontent.com/49183340/207690668-6b7c2a6f-7375-46ae-91fa-55b73ca3f438.png)

After click on "automatically resolve" : 
![image](https://user-images.githubusercontent.com/49183340/207690991-5b45c36e-d9b4-497f-b680-cc2b5ec91f6f.png)

And the bug appears : 
![image](https://user-images.githubusercontent.com/49183340/207691125-4b9a4945-a94b-4b0c-9702-e3c7707e277e.png)

To fix them I propose that : 
``
changesBrowser := (ChangesBrowser changes: { crit change })
					extent: 500@400;
					asModalWindow;
					yourself.
``

This is working fine :
![image](https://user-images.githubusercontent.com/49183340/207691300-3b882a04-c35f-42d3-8390-fe6a12c7b662.png)

**Comment by Ducasse** [comment]
thanks for the fix. We will integrate it. Now I think that the ChangeBrowser is old and we have a new preview but we should do it in a second time.
