### ISSUE TITLE
[CI] Fail on WIN random: OmSessionStoreTest(OmStoreTest)>>testEntryForAbsentEntry

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#12126]
**Bug description**
OmSessionStoreTest(OmStoreTest)>>testEntryForAbsentEntry fails on the CI on Windows only randomly

```

FileDoesNotExistException
'C:\Users\ci\AppData\Local\Temp\ombu-tests\test-sessions-other\Pharo.38D0549E180.ombu'
```

**Comment by jecisc** [comment]
I don't have time to find the origin, but I can reproduce it locally on one of my machine

**Comment by jecisc** [comment]
I added a logs in OmFileStore>>#flushEntryBuffer, OmFileStore>>#flush and OmFileStore>>#readEntriesWith:

When the test pass I get:

```
Flush
Create D:\Temp\ombu-tests\test-sessions-main\Pharo 12.0 - 64bit (next development version, latest)-01.2F97BA4A5200.ombu
Flush
Flush
Flush
```

When it fails I get 


```
Reading D:\Temp\ombu-tests\test-sessions-other\Pharo 12.0 - 64bit (next development version, latest)-01.2F98127211C0.ombu
```

==========

Going a little further.

When the test pass, we never go in #checkIfMustRefreshBlock: but when the test fails, we go in #checkIfMustRefreshBlock:

===========

A more precise divergeance point is in OmFileStore>>#entryFor:ifPresent:ifAbsent:.

When the test passes, the reference global name and the store global name are the same. But when the test fails, they are different.

============

Trying with more logs:

Passing:

```
Setup
Reference initilized with global name: nil
Store initialized with global name: Pharo 12.0 - 64bit (next development version, latest)-01.31FD2FC61E80
Reference initilized with global name: nil
Store initialized with global name: Pharo 12.0 - 64bit (next development version, latest)-01.31FD2FE4A300
Test
Reference initilized with global name: Pharo 12.0 - 64bit (next development version, latest)-01.31FD2FC61E80
Reference global name: Pharo 12.0 - 64bit (next development version, latest)-01.31FD2FC61E80 store global name: Pharo 12.0 - 64bit (next development version, latest)-01.31FD2FE4A300
Flush D:\Temp\ombu-tests\test-sessions-main\Pharo 12.0 - 64bit (next development version, latest)-01.31FD2FC61E80.ombu
Reference global name: Pharo 12.0 - 64bit (next development version, latest)-01.31FD2FC61E80 store global name: Pharo 12.0 - 64bit (next development version, latest)-01.31FD2FE4A300
```

Failing:

```
Setup
Reference initilized with global name: nil
Store initialized with global name: Pharo 12.0 - 64bit (next development version, latest)-01.32106129E0C0
Reference initilized with global name: nil
Store initialized with global name: Pharo 12.0 - 64bit (next development version, latest)-01.32106129E0C0
Test
Reference initilized with global name: Pharo 12.0 - 64bit (next development version, latest)-01.32106129E0C0
Reference global name: Pharo 12.0 - 64bit (next development version, latest)-01.32106129E0C0 store global name: Pharo 12.0 - 64bit (next development version, latest)-01.32106129E0C0
Flush D:\Temp\ombu-tests\test-sessions-main\Pharo 12.0 - 64bit (next development version, latest)-01.32106129E0C0.ombu
Positions in checkIfMustRefreshBlock: nil
Reading D:\Temp\ombu-tests\test-sessions-other\Pharo 12.0 - 64bit (next development version, latest)-01.32106129E0C0.ombu
```

The problem seems to come from the fact that we have 2 different stores when it works but two time a store with the same global name when it fails.

**Comment by jecisc** [comment]
I think I'm getting closer!

The test initialize 2 stores. Their global name is created by OmSessionStore>>#nextStoreName. 
In the case of the failing test, the two store names are identical. So OmSessionStore>>#nextStoreName return twice the same value.

**Comment by jecisc** [comment]
I created this:

```
testNextStoreName

	| names |
	names := OrderedCollection new.
	100 timesRepeat: [ names add: store nextStoreName ].
	self assertCollection: names hasSameElements: names asSet.
	self assert: names size equals: names asSet size
```

For now it fails because it always return the same name. I am not sure this is normal or not since I'm not an ombu expert. But I would expect different values at each call with a method starting by #next

**Comment by svenvc** [comment]
Good catch !

**Comment by jecisc** [comment]
I proposed a PR to fix the problem that comes from the fact that windows has less precision for time than unix.

My fix is not the best. We should probably not rely on time to create store names, but at least it will fix the CI.

Maybe if someone has time in the future we can use a better strategy as you said in issue #13447

**Comment by MarcusDenker** [comment]
fixed by https://github.com/pharo-project/pharo/pull/13448
