### ISSUE TITLE
Profiler doesn't work in Pharo10 on Windows?

### ISSUE THREAD

**Issue by dmatveev** [guillep/pharo-core#12125]
**Bug description**

Trying to profile my code in a number of ways, but most of the time it doesn't show any results.

**To Reproduce**

1. Trying to profile via menu: `10 factorial` -> `Profile it` -> nothing.
2. Trying to profile via code (as recommended on Discord): `TimeProfiler spyOn: [ 10 factorial ]`. The result is below:

![image](https://user-images.githubusercontent.com/144187/208323579-e0c2e1e0-a500-4344-b0ad-e5c7fa4ed063.png)

3. Trying to profile my package from TestRunner. So far it seems it is the only thing which works:

![image](https://user-images.githubusercontent.com/144187/208323617-bb3ab8eb-29fe-48ea-bec3-4bdcc5aaf9a4.png)

**Expected behavior**

Expected to have profiling working in cases 1 & 2. :)

**Screenshots**

See above.

**Version information:**
 - OS: Windows
 - Version: 11 x86_64
 - Pharo Version: 10 (Pharo-10.0.0+build.535.sha.f72dfb7a95cb072d485373b28b33e8c256b9a3f2 (64 Bit))

**Expected development cost**

Since the package-level profiling seem to work, maybe the overall mechanism is still there and only some integration is broken?

**Additional context**

Also tested with Pharo 9 image on the same machine, same results.

**Comment by dmatveev** [comment]
In case if the reported code looks too fast:

![image](https://user-images.githubusercontent.com/144187/208324063-e0e014e2-1e9c-420c-be96-ea666f6c227c.png)

**Comment by dmatveev** [comment]
But yes, adding more iterations made it work:
![image](https://user-images.githubusercontent.com/144187/208324161-051b684b-7897-4973-a323-bfafc0fb7621.png)

**Comment by MarcusDenker** [comment]
Yes, this is normal behavior of that profiler

**Comment by dmatveev** [comment]
@MarcusDenker thanks! It seems the only problem in this issue is that "Profile it" doesn't work.

**Comment by MarcusDenker** [comment]
Can you open a new issue for that? If we just use this one, then every person first has to read everything to then understand what still needs to be done.

**Comment by dmatveev** [comment]
@MarcusDenker here it is: **https://github.com/pharo-project/pharo/issues/12137**

**Comment by MarcusDenker** [comment]
thanks!
