### ISSUE TITLE
[CI]  With latest VM: Segmentation fault when running all tests

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#12127]
**Bug description**
Every second CI rum (that is, when it uses the -lastest vm) leads to a Segmentation fault on all three platforms. See e.g.

https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-12069/3/pipeline

**Comment by MarcusDenker** [comment]
It works now on Linux, but Win and Mac still show the error, see e.g.

https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-12216/1/pipeline

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-12216/1/pipeline">Jenkins</a></strong></div></blockquote>

**Comment by MarcusDenker** [comment]
Now even Linux fails again: 

https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-12220/3/pipeline/46

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-12220/3/pipeline/46">Jenkins</a></strong></div></blockquote>

**Comment by guillep** [comment]
Hi Marcus,

The crash should be consistent in all platforms. I wonder why it worked in linux earlier :).
I don't think there is a need to follow up all the traces of the CI.
We have investigated the problem, it is in the latest unstable VM, due to a change integrated in december (https://github.com/pharo-project/pharo-vm/pull/518). Yesterday we merged a fix (https://github.com/pharo-project/pharo-vm/pull/524) but the build failed due to a network issue. We are relaunching the build right now, it should be solved during the day.

**Comment by MarcusDenker** [comment]
The cases with Linux working did download the -latest vm, I see in the logs:

Downloading the latest pharoVM:
	http://files.pharo.org/get-files/110/pharo-vm-Linux-x86_64-latest.zip

**Comment by MarcusDenker** [comment]
Now when we use the -latest, the tests seem to *not* crash anymore, see e.g.


https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-12225/1/pipeline/47

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-12225/1/pipeline/47">Jenkins</a></strong></div></blockquote>

**Comment by MarcusDenker** [comment]
This is now working
