### ISSUE TITLE
Poor performance with large WriteStreams

### ISSUE THREAD

**Issue by j-brant** [guillep/pharo-core#12128]
`WriteStream>>pastEndPut:` limits the growth of the `WriteStream` to 1,000,000 slots. This causes bad performance when writing large streams >2 million items if you are using `nextPut:`. If you use `nextPutAll:` to write the same object, the performance is better as it appears to grow the underlying collection by 1/4 current size. For example, compare these two examples: 
```
Time millisecondsToRun: [
	| stream |
	stream := WriteStream on: String new.
	100000000 timesRepeat: [stream nextPut: $0]]
```
and using `nextPutAll:`:
```
Time millisecondsToRun: [
	| stream |
	stream := WriteStream on: String new.
	100000000 timesRepeat: [stream nextPutAll: '0']]
```
The first one using `nextPut:` takes 6.1 seconds on my machine, but the second one takes 2.6 seconds.

**Request**
Please remove `min: 1000000` from the `WriteStream>>pastEndPut:` method (and update the comment).

**Expected behavior**
With the change above, the running time for the first example above is 1 second on my machine. Furthermore, in large images that take longer for the garbage collector to run, it will be much greater. Here's a graph of the time differences between the current code (in red) and the proposed change in blue. Each data point is the time in microseconds to insert 1 million characters:
![image](https://user-images.githubusercontent.com/16563825/208429929-f5ac42e8-9396-44a6-a694-2fac5e3ef067.png)

**Version information:**
 - Pharo Version: All current versions have the same code.

**Comment by MarcusDenker** [comment]
I did a PR with the suggested change, see #12205 and there we got this comment:


"
Hi Marcus, I am not sure if duplicating the size of the underlying collection is good in all the scenarios. Maybe we need to add it as a growth rate factor, because it only affects strange scenarios like this one, adding a single element millions of times, maybe the WriteStream should have a way of setting how to behave.
"
