### ISSUE TITLE
Fuel-Platform-Pharo-10 still in the Pharo 11 image

### ISSUE THREAD

**Issue by theseion** [guillep/pharo-core#12132]
**Describe the problem**
Fuel-Platform-Pharo-10 is not needed in the Pharo 11 image but still exists. I suspect that it's still used as part of bootstrapping, because the package is not part of the FileTree sources.

**Classes involved**
FLPharo10Platform

**Proposal**
🤷 

**Version information:**
Pharo-11.0.0+build.384.sha.39a5f567c5c30deff9aef7bcec5f237fcf6486f6

**Expected development cost**
Should be straight forward, if we know where to look.

**Additional context**
-

**Comment by MarcusDenker** [comment]
it is references only in  BaselineOfFuelPlatform>>#pharoPackagesAndGroups:

So I really wonder why it is loaded

**Comment by theseion** [comment]
Found it. `SmalltalkImage>>#metacelloPlatformAttributes` still includes `pharo10.x` and `pharo10.0.x`.

**Comment by theseion** [comment]
I've opened a PR to remove the Pharo 10 platform attributes.
