### ISSUE TITLE
Epicea does not log events when packages are renamed

### ISSUE THREAD

**Issue by chisandrei** [guillep/pharo-core#12149]
When a package is renamed there is no event in Epicea. For consistency, might be good to have events for all classes in the old package that they were moved to a new package.

Below we renamed as an example the package `TaskIt-Tests` to `TaskIt-Tests2`. After the rename there is no entry in Epicea.

- before the rename
<img width="1792" alt="Screenshot 2022-12-23 at 18 25 46" src="https://user-images.githubusercontent.com/3534711/209367998-ebf9e0f1-f693-457c-95a5-62fddfc2567c.png">

- after the package rename
<img width="1792" alt="Screenshot 2022-12-23 at 18 29 11" src="https://user-images.githubusercontent.com/3534711/209368061-6ea0bbd5-e520-453e-951b-c173e5609a3f.png">

Tested in Pharo 11.0.0 Build information: Pharo-11.0.0+build.391.sha.50b85aa8c91d63e3d12c6a7a97c52ba688a60757 (64 Bit)

**Comment by hernanmd** [comment]
In https://github.com/pharo-project/pharo/pull/12375

**Comment by MarcusDenker** [comment]
merged pr https://github.com/pharo-project/pharo/pull/12375
