### ISSUE TITLE
Remove Array2D from Pharo core 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#12140]
We should remove Array2d from Pharo core and point people to http://github.com/pharo-containers
In addition Array2D is not a matrix so we should remove the math part (that is partially implemented and probably in a bad way). 
For Matrix people should use Polymath implementation.

**Comment by hernanmd** [comment]
I found only one reference to Array2D in Pharo 11, this is Roassal3's method RSDSM>>createShapes
But I see no users of RSDSM or its subclass RSDSMStronglyConnected in the default image.

Maybe the BaselineOfRoassal2 could include Pharo-Containers and adapt the methods?

```smalltalk
createShapes

...
matrix := CTArray2D width: objectsX size height: objectsY size.
...
```

@akevalion ?

**Comment by Ducasse** [comment]
Yes it would be nice in fact :)

**Comment by akevalion** [comment]
Hi, currently Roassal is using Array2D.
CTArray2D is not present in pharo12, 
should I remove then the dependency to Array2D?

**Comment by akevalion** [comment]
I have removed dependency of this class in roassal.

**Comment by jordanmontt** [comment]
Hello, we should benchmark the two implementations of Array2D before removing it. Also, it makes sense to have a 2D array by default in Pharo. Because now with the one of pharo-contributions people need to load it by hand...

**Comment by Ducasse** [comment]
Seb I'm sorry but we should not load all the collections by default. People should load what they need.

**Comment by akevalion** [comment]
This pull request https://github.com/pharo-project/pharo/pull/15148 has changed Array2D as deprecated class.
We can remove it, but people may complain about it

**Comment by lugu** [comment]
Issue referenced at https://github.com/pharo-graphics/Bloc/issues/643

**Comment by jordanmontt** [comment]
Closing this because Array2D is already removed from the default Pharo 13 image
