### ISSUE TITLE
Extract return from ifTrue:ifFalse: in Number>>#abs

### ISSUE THREAD

**Issue by vonbecmann** [guillep/pharo-core#12148]
_simplify the ifTrue:ifFalse: expression._

**Describe the request**
`abs
	"Answer a Number that is the absolute value (positive magnitude) of the 
	receiver."

	self < 0
		ifTrue: [^self negated]
		ifFalse: [^self]`

**Expected behavior**
`abs
	"Answer a Number that is the absolute value (positive magnitude) of the 
	receiver."

	^self < 0
		ifTrue: [self negated]
		ifFalse: [self]`

**Expected development cost**
add a few tests for Float, SmallInteger, etc.

**Version information:**
 - OS: [debian]
 - Version: [bullseye]
 - Pharo Version [ Pharo-11.0.0+build.391.sha.50b85aa8c91d63e3d12c6a7a97c52ba688a60757 (64 Bit) ]

**Comment by Ducasse** [comment]
indeed :) Thanks for the report. We should probably write a rewrite expressions to spot all of them. This is especially nice with the new support for clean and constant blocks.

**Comment by vonbecmann** [comment]
see pull request  #12150

**Comment by Ducasse** [comment]
I saw. Tx. for the simple issues we tagged them first good ... to invite people other than us to be able to commit. 
If you want your issues to close automatically when their associate PR is merged. You can add fix: #number in the commit message. Like that the PR and the issue are automatically linked.

**Comment by vonbecmann** [comment]
i choose something simple that i can solve quickly. otherwise i don't have time to do it. thanks for your comments.

**Comment by Ducasse** [comment]
If you want something really simple and easy but still worth. You can look for example in comments and turn them as executable comments. 
Like that we will be able to spot dead example in comments. 
Example:

"'abc' size 3" into "'abc' size >>> 3"

**Comment by Ducasse** [comment]
Thanks for your time.
