### ISSUE TITLE
SpChooserPresenter swallows items after removing them and then adding others

### ISSUE THREAD

**Issue by n1toxyz** [guillep/pharo-core#12145]
**Bug description**
After opening an instance of SpChooserPresenter and opening it as a window and then removing all or a item(s) from the targetList via a removal button (buttons named '<' or '<<') and then selecting an item in the sourceList and adding it via the button named '>' to the targetList removes/hides all previously removed items from the sourceList and doesn't allow to select or add them anymore.

**To Reproduce**
1. Open an SpChooserPresenter in the playground with e.g. `(SpChooserPresenter sourceItems: #('Apple' 'Pear' 'Melon') chosenItems: #('Peach')) open.`
2. Click on button '<<' or alternatively select 'Peach' and then click on button '<'
3. Now select for example 'Melon' and then click on the button '>'

Now 'Melon' is shown in the targetList but 'Peach' has disappeared from the sourceList is not shown there anymore, thus preventing selecting and adding it again if desired.

**Expected behavior**
After removing an item or multiple items from the targetList via a button and then adding other items to targetList, the previously removed items should stay selectable and addable in the sourceList.

**Screenshots**
Opened SpChooserPresenter:
![chooser_before](https://user-images.githubusercontent.com/29785597/209002923-3c936c21-40d1-4e1e-9436-26a328121570.png)

After moving all or one item to sourceList and selecting a new item for moving to targetList:
![chooser_between](https://user-images.githubusercontent.com/29785597/209002965-6923b38f-d32f-47df-80c9-ec23c07a56d5.png)

After moving previously selected item to targetItems list:
![chooser_after](https://user-images.githubusercontent.com/29785597/209002998-df933a99-14d1-4695-a9d2-bfecb4efade7.png)

Peach has disappeared from sourceList.

**Version information:**
 - OS: Slackware 15.0 64bit
 - Pharo 11 latest

**Expected development cost**
I don't know yet, but I think it must be something in the methods `#removeAll` or `#removeSelected`.  At first glance both look fine to me, but somehow the items disappear. I haven't investigated much yet as I hadn't time.

**Additional context**
None so far

**Comment by n1toxyz** [comment]
My bad. I noticed just now that this is the wrong repository for this report. I am going to repost this in the pharo-spec repository.

**Comment by Ducasse** [comment]
oops this is a real. thanks for reporting it.

**Comment by Ducasse** [comment]
I confirm thatI could reproduce it. I thought that we tested this scenario
