### ISSUE TITLE
Epicea: Problem creating packages

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#12147]
Here is the scenario in latest P11

- coded
- moved classes to a new package
- saved the image (there is a snapshot entry in epicea)
- reopen the image no package there :( WTF?
- then open epicea and the changes are there.
- select all and press apply
- package is not recreated :(

![Capture 2022-12-23 at 12 31 48](https://user-images.githubusercontent.com/432549/209329210-c3b1120e-1efa-40ff-8945-d340de159212.png)
![Capture 2022-12-23 at 12 31 37](https://user-images.githubusercontent.com/432549/209329240-ee15ec59-8afc-4fa6-b6a5-82db3fc9e047.png)

**Comment by MarcusDenker** [comment]
merged PR https://github.com/pharo-project/pharo/pull/12375
