### ISSUE TITLE
Cleanup: do we still need EditorFindReplaceDialogWindow

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#12159]
Do we still need EditorFindReplaceDialogWindow or do we have a Spec2 replacement?

**Comment by Ducasse** [comment]
I do not know but I did not see a replacement. I think that we should do one in Spec.

**Comment by hernanmd** [comment]
I just sent a [PR](https://github.com/pharo-project/pharo/pull/14836) for this.

Notice that there is:

```smalltalk
SpRubFindReplaceService new 
	findText: 'Hola';
	openDialog.
```

**Comment by MarcusDenker** [comment]
EditorFindReplaceDialogWindow has been removed
