### ISSUE TITLE
ReAbstractRule mentions (missing) help in class comment

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#12165]
The class comment of ReAbstractRule mentions (missing) help in class comment:

```Smalltalk
RenrakuHelp readInHelpBrowser
```

but in Pharo 11 the (traditional) help now got removed

**Comment by akevalion** [comment]
These classes were removed because of this issue:
- https://github.com/pharo-project/pharo/issues/11949
I suggest to update the class comment of `ReAbstractRule`
