### ISSUE TITLE
[Feature Request] New rule to remove unnecessary separators and dots

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#12166]
Many methods contain tabs or spaces at the end of each code line. Also some final dot that is not necessary.

We should have a lint rule detecting such methods together with an autofix option

**Comment by astares** [comment]
![image](https://user-images.githubusercontent.com/5980033/210080431-57f07fa5-ae05-493e-bc17-c8761f3824bf.png)

**Comment by astares** [comment]
The autofix allows to keep the source code with the same formatting. It just goes line by line and checks if unnecessary tabs or spaces could be removed from the end. 

It also removes trailing lines without content and a final dot that is not necessary

**Comment by astares** [comment]
**Important**
As this rule can reduce the size of the code the image size could be reduced when applying to more/all methods in classes for all packages

**Comment by astares** [comment]
And before we open up the discussion from people who like their final "premature dots" in the method bodies
please check the full thread here with an answer:

https://twitter.com/TorstenAstares/status/1609666189382254593

<blockquote><img src="//abs.twimg.com/favicons/twitter.2.ico" width="48" align="right"><div>Twitter</div></blockquote>

**Comment by astares** [comment]
![image](https://user-images.githubusercontent.com/5980033/210261778-054b9db1-66e8-40a8-a250-d61572ee9d39.png)

**Comment by Ducasse** [comment]
;) I do not like extras . but we could let people have one at the end if they cannot live without their semi colon :)

**Comment by astares** [comment]
@Ducasse Yes - they can. They just need to ban the rule. But for the standard image we should become clean and consistent. Working on it...
