### ISSUE TITLE
extract return from max: and min: methods

### ISSUE THREAD

**Issue by vonbecmann** [guillep/pharo-core#12176]
_extract return from max: and min: methods._

**Actual**
```
max: aMagnitude 
 self > aMagnitude
   ifTrue: [^self]
   ifFalse: [^aMagnitude]
```

**Expected**
```
max: aMagnitude 
 ^ self > aMagnitude
     ifTrue: [self]
     ifFalse: [aMagnitude]
```

**Version information:**
 - OS: [debian]
 - Version: [bullseye]
 - Pharo Version [Pharo-11.0.0+build.394.sha.25a66bd9b1ac0bf7b1dac4e147bbc0292f426f9e (64 Bit)]

**Comment by Ducasse** [comment]
Tx!

**Comment by Ducasse** [comment]
I saw that in normalizeIftrue in the inline refactoring there are expressions to automatically rewrite ^ up from leaves to top.
