### ISSUE TITLE
Lint rule to detect bad self recursion in a method

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#12183]
Sometimes it is good to use recursion in a method. But often a recursion can lead
to blocking Pharo when a method calls itself using self.

See  https://github.com/pharo-project/pharo/issues/12180 for such an example:

```Smalltalk
open
  self open
```

We should add a lint rule and warning to the system that shows such situations

**Comment by hernanmd** [comment]
In https://github.com/pharo-project/pharo/pull/12389
