### ISSUE TITLE
Pharo Looses method sources and fills code with temporary variables

### ISSUE THREAD

**Issue by diego-crespo** [guillep/pharo-core#12217]
**Bug description**
Sometimes when I'm working on a method in Pharo it replaces all of my variables with variables that say tmp1 or tmp2.

**To Reproduce**
I unfortunately didn't realize this was a bug so I didn't pay attention to it. It's happened a few times and seems to happen when I navigate between the various methods.

**Expected behavior**

**Screenshots**
Here is a [screenshot of the issue](https://imgur.com/a/tVMyXEQ)

**Version information:**
 - OS: Windows 10
 - Version: windows 10 OS build 19045.2364
 - Pharo Version: 10

**Expected development cost**
I'm not sure I didn't realize this was a bug until the Discord told me. I'll be on the look out for steps to reproduce it.

**Comment by hogoww** [comment]
As i said on discord, this happens because the environment looses the sources of your methods, and it uses the decompiler to display them.
@MarcusDenker what do you think ? =]

**Comment by astares** [comment]
Yes - this is the case when no source code is available and the decompiler kicks in (who does not know about the temporary variable names)

@diego-crespo 
Can you try on another Pharo installation (maybe a second machine) if this is a general problem and give us the steps to reproduce.
