### ISSUE TITLE
Not understood 'Syntax Error' when loading a package from an Iceberg project

### ISSUE THREAD

**Issue by labordep** [guillep/pharo-core#12268]
There is a not understood syntax error when I'm loading a package in a project from Iceberg.
The problem is due to the source code syntax of some methods, but this is strange because when I'm regarding the code there is no error (apparently).

How to reproduce : 

Load [toplo](https://github.com/plantec/Toplo) project.

```
EpMonitor disableDuring: [
  Author useAuthor: 'Load' during: [
    [	Metacello new
        baseline: 'Toplo';
        repository: 'github://plantec/Toplo/src';
        onConflictUseIncoming;
        ignoreImage;
        load.
    ]	on: MCMergeOrLoadWarning
      do: [ :warning | warning load ] ] ]
```

When the project and there dependencies are loaded, browse the Toplo project with Icerbeg and load the 'Toplo-tests' package :
![image](https://user-images.githubusercontent.com/49183340/211158252-c6bbeb2c-b3eb-4236-bd82-fb3419bbe26e.png)

And see the error :
![image](https://user-images.githubusercontent.com/49183340/211158208-9997a5cd-8504-49c6-b82d-fe53d7834ede.png)

The project source-code is here : 
![image](https://user-images.githubusercontent.com/49183340/211158292-e0c25b42-4a3b-47b6-bcd4-79b48a2fda38.png)
https://github.com/plantec/Toplo/blob/master/src/Toplo-Tests/ToDresserTest.class.st

Another view of the project source-code with the Monticello browser : 
![image](https://user-images.githubusercontent.com/49183340/211158336-ee94ed48-32d9-44ae-a42c-6a4fafd5ada0.png)

If I'm debugging the error, I cannot understand why there is an error :
 ![image](https://user-images.githubusercontent.com/49183340/211158380-77325d26-05c8-482c-a3ac-729a30971a7f.png)
![image](https://user-images.githubusercontent.com/49183340/211158423-d7b7e865-8a6c-40b0-8a9a-898e4b4bd1ef.png)

And apparently there is no problem :/

My configuration : 
Pharo-11.0.0+build.421 64bits
Windows 11 Pro

**Comment by Ducasse** [comment]
May be there is a hidden character.
I'm loading the code to see if I can reproduce it.

**Comment by Ducasse** [comment]
I checked the source code on github.
I could copy and paste it without problem. 
I did not see a special character.

**Comment by Ducasse** [comment]
I flushed all my repo and reload everything in a fresh image and I could not get an installation with the method testInstallOnlyOnce. So I will retry. Now I do not know if I have the same code.

I have the commit [eaf12a1] eaf12a1290f99a14a08193aa78627ab467619909

**Comment by Ducasse** [comment]
And this is the latests commit as of https://github.com/plantec/Toplo/commit/eaf12a1290f99a14a08193aa78627ab467619909

**Comment by Ducasse** [comment]
Now the tests are not loaded. And when I load the package it breaks.

**Comment by Ducasse** [comment]
So I tried 
- to edit the file on the git repo. 
- to unzip the mcz file in the cache, edit and load the source.st file
- and it still breaks. I removed the space to be sure.
I attached the file here.

**Comment by Ducasse** [comment]
[source2.st.zip](https://github.com/pharo-project/pharo/files/10368080/source2.st.zip)

**Comment by Ducasse** [comment]
```
SystemOrganization addCategory: 'Toplo-Tests'!
SystemOrganization addCategory: #'Toplo-Tests-Dresser'!
SystemOrganization addCategory: #'Toplo-Tests-Widget'!

TestCase subclass: #ToDresserTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Toplo-Tests-Dresser'!

!ToDresserTest commentStamp: '' prior: 0!
A ToDresserTest is a test class for testing the behavior of ToDresser!

!ToDresserTest methodsFor: 'tests' stamp: 'nil'!
testInstallOnlyOnce

	| widget d0 d1 d1cpt |
	widget:=ToWidget new.
	d0 := widget dresser.
	self assert: d0 isInstalled.
	d1cpt := 0.
	d1 := ToActionDresser new installAction: [ :e | d1cpt := d1cpt + 1 ].

	widget addDresser: d1.
	self assert: d1 isInstalled.
	self assert: d1cpt equals: 1.
	
	widget addDresser: d1.
	self assert: d1 isInstalled.
	self assert: d1cpt equals: 1.
! !
```

**Comment by Ducasse** [comment]
I retyped the line widget := ToWidget
and it worked. I think that the problem is that in the original version the : was looking like but it was not :

**Comment by Ducasse** [comment]
What I do not understand is that I cannot reproduce it now by dropping the source.st on pharo and (of course given it a new name to the file).

**Comment by Ducasse** [comment]
So I'm totally confused. I did a PR to toplo to fix the obsolete class.

**Comment by plantec** [comment]
Thanks!!
It works now, I can load the test package.
I'm confused too. 
I will try to reproduce it by playing in windows and Mac alternatively with a test package.

**Comment by labordep** [comment]
Thanks @Ducasse this is working fine for me !
I hope this problem does not appears one more time... we will see

**Comment by Ducasse** [comment]
I would like to have a reproducible case to be able to fix it.
