### ISSUE TITLE
GitHub Rate limiting for CI (yet again)

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#12285]
Looks like GitHub Rate limiting for CI problem again:
see https://github.com/pharo-project/pharo/branches

We already had this in the past: 
- see #11222
- see #10926

**Comment by astares** [comment]
[https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo11/423/display/redirect](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo11/423/display/redirect)

![image](https://user-images.githubusercontent.com/5980033/211222025-69c498fb-ca68-48d8-82e2-2a5725ffb52e.png)

So this is CI machine of INRIA

![image](https://user-images.githubusercontent.com/5980033/211222270-530888b4-bfbf-4c74-ae94-439e008da6ac.png)

**Comment by astares** [comment]
See more details in
[https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting)

**Comment by astares** [comment]
One can verify the rate limit using
```
curl -i https://api.github.com/users/pharo-project
```
which gives: 

![image](https://user-images.githubusercontent.com/5980033/211222524-3baf308b-1c2f-4363-884c-3730ac9f1dca.png)

**Comment by astares** [comment]
So according to [documentation](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting) this is due to doing anonymous requests (=unauthenticated)
```
"For unauthenticated requests, the rate limit allows for up to **60** requests per hour."
```
which would fit what "pharo-project" has at the moment (see curl example with the limit of 60 requests per hour)

If we would use a **dedicated authenticated user** then then we could go up to **5000** request per hour:
```
User-to-server requests are limited to **5,000** requests per hour and per authenticated user.
```

@MarcusDenker This ticket was closed (as you marked this new case as duplicate from an already closed old one) 

But the problem persists when too many requests hit CI. Is there a way we can work with an authenticated user in the CI?

**Comment by privat** [comment]
An additional avenue could be to ask Jenkins to cache artifacts downloaded by icegithub (or whatever is the tool that does the download) between jobs. (search "Jenkins build cache" or something).

Another possibility could be to have some kind of proxy server/service that does the caching.
Git is really great for that! But that need a way of diverting the icegithub requests to github.
Maybe by fooling icegithub by playing on at the network stack level (dns, nat, routes, etc. no nice, and might need a somewhat privileged host access).
Or having icegithub aware of proxy and a way to externally configure them (environment variables for instance).

**Comment by privat** [comment]
What is the status of this issue?

**Comment by jecisc** [comment]
One solution that seem not too hard is to generate a github token, set it as environment variable and during the bootstrap, is this variable is present, we set it as a credential of the github plugin. 
And at the end of the build we reset the credential plugin to remove this credential.

Any though about this?

It seems to me as one of the easiest thing we can do but I'm not sure because I'm not really good in system administration. So maybe I'm missing something easier.

**Comment by privat** [comment]
Note: rate limit is also the reason that a lot of snapshot images are failing to build https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/activity?branch=Pharo12

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/activity?branch=Pharo12">Jenkins</a></strong></div></blockquote>

**Comment by MarcusDenker** [comment]
The fix looks good... lots of PRs are now checked in parallel without the rate limiting happening

**Comment by privat** [comment]
The fix is live? Congratulation! :tada:
