### ISSUE TITLE
Compiler is slow with string literals containing exclamation marks

### ISSUE THREAD

**Issue by fedemennite** [guillep/pharo-core#12300]
**Bug description**
Compiling source code with exclamation marks in string literals is up to 25x times slower than code without exclamation marks.
This has a remarkable speed impact when building a new image with all our code.
It also impacts the speed of some of our testcases covering source generation 

**To Reproduce**
Evaluate and compare the speed of the 2 following code snippets.
Snippet 1:
| stream |
stream := String new writeStream.
stream nextPutAll: 'exclamationSlow';
cr; tab; nextPutAll: '^'''.
100000 timesRepeat:[stream nextPutAll: 'slow!'].
stream  nextPutAll: ''''.
Time millisecondsToRun:[Object compile:stream contents].
Snippet 2:
| stream |
stream := String new writeStream.
stream nextPutAll: 'exclamationFast';
cr; tab; nextPutAll: '^'''.
100000 timesRepeat:[stream nextPutAll: 'fast.'].
stream  nextPutAll: ''''.
Time millisecondsToRun:[Object compile:stream contents].

**Expected behavior**
Speed of compiling should be comparable in both cases.

**Screenshots**
n/a

**Version information:**
 - OS: Windows / Linux
 - Version: any
 - Pharo Version 10

**Expected development cost**
Sounds like something easy to fix unless there are side effects...

**Additional context**
None

**Comment by Ducasse** [comment]
Oh this is a great findings. One of this hidden gem. 
A left over probably of the !! format.

**Comment by MarcusDenker** [comment]
Yes, this is the code in 

SourceChunkWriteStream>>#nextPut:

there is code that checks for ! constancely for every character it writes:

```
	[ 
	(bangIndex := string indexOf: self terminatorMark startingAt: start)
	= 0 ] whileFalse: [ 
```

I really want to replace the current .sources/.changes with a better mechanism.
