### ISSUE TITLE
RewriteRuleChangesBrowser recursive never-ending call to self open

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#12371]
**Bug description**
The implementation of RewriteRuleChangesBrowser>>open leads to a recursive never-ending call to self open.

**To Reproduce**
```smalltalk
RewriteRuleChangesBrowser new open.
```
**Version information:**
 - Pharo Version 11

**Comment by astares** [comment]
@hernanmd 
I fixed that already. see https://github.com/pharo-project/pharo/issues/12180 and
https://github.com/pharo-project/pharo/pull/12182

Try a more recent Pharo 11 image

**Comment by hernanmd** [comment]
Thanks, that was quick :)
