### ISSUE TITLE
move guideToDivision comment to class comment

### ISSUE THREAD

**Issue by vonbecmann** [guillep/pharo-core#12390]
_Move SmallInteger class>>#guideToDivision comment to class comment._

**Describe the request**
the SmallInteger class>>#guideToDivision does nothing, it only holds the documentation comment.

**Expected behavior**
move method's comment to class comment. it will be easy to find and read.

**Version information:**
 Pharo image: Pharo11.0.0#110451
Virtual machine used: CoInterpreter * VMMaker-tonel.1 uuid: aa6234f4-799d-0d00-90d1-c90e092bce84 Jun 10 2022
StackToRegisterMappingCogit * VMMaker-tonel.1 uuid: aa6234f4-799d-0d00-90d1-c90e092bce84 Jun 10 2022
v9.0.15 - Commit: b487900 - Date: 2022-06-02 09:48:57 +0200

Platform Name: unix
Class browser used (if applicable): ClyFullBrowserMorph

**Comment by vonbecmann** [comment]
what's your opinion? thanks

**Comment by guillep** [comment]
+10000
