### ISSUE TITLE
ClassSide initialize is not looked up

### ISSUE THREAD

**Issue by hogoww** [guillep/pharo-core#12407]
**Bug description**
Upon loading a class, the #initialize method is only executed if this specific class defines the #initialize selector.

**To Reproduce**
1. Create class A
2. Create class B ,subclass of A
3. Add an #initialize method in A BUT NOT in B.
4. Commit.
5. Remove A & B.
6. Load A & B.
(I only have tested that with Iceberg and a new image, but that should be enough)

**Expected behavior**
After a class is loaded in the system, this class should look up the initialize selector and execute it.

**Version information:**
Pharo 11, I'd assume it's relevant for other versions, I haven't check.

**Expected development cost**
Currently, the #initialize method is executed in MCMethodDefinition >> #postLoadOver:.
I have never really worked on Monticello, so I don't know.

I consider this a serious bug, because it breaks the expectations of developers.
However, it might impact many application.
So much so, that I don't know whether that's worth fixing.
However, this at the minimum requires a comment in the class sides implementors of initialize.

**Comment by guillep** [comment]
Hi @hogoww this is on purpose.

The reason is that suddenly somebody creating a subclass B of class A may force the re-initialization of A => which may be wrong in many aspects, especially if A has class variables to initialize.

**Comment by hogoww** [comment]
@guillep Would a short comment in the initial definition be acceptable ?
This was very unexpected for me, and there was no highlight that this was expected behavior.

**Comment by guillep** [comment]
Sure! I don't know where that comment could be, but adding a comment would be super useful!
