### ISSUE TITLE
Calypso open two class side tabs when compiling a new method

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#12408]
**To Reproduce**

![class_side](https://user-images.githubusercontent.com/4825959/214008115-47825355-9e66-4c14-9aba-a882f39cac19.gif)

**Expected behavior**
Calypso shouldn't create new tabs when compiling a method.

**Version information:**
 - OS: macOS
 - Pharo Version: 11

**Comment by Inao0** [comment]
This happens both on class side and instance side.

**Comment by ValentinBourcier** [comment]
See PR: https://github.com/pharo-project/pharo/pull/12464
