### ISSUE TITLE
MCMethodDefinition #asSymbol error when catString isNil (loading BaselineOf)

### ISSUE THREAD

**Issue by labordep** [guillep/pharo-core#12418]
Hi,

When loading a baseline of a project (in my example ```BaselineOfTaskIt```), sometimes catString is nil in ```MCMethodDefinition>>initializeWithClassName:classIsMeta:selector:category:timeStamp:source:```.

We propose this fix : 

```
initializeWithClassName: classString classIsMeta: metaBoolean selector: selectorString category: catString timeStamp: timeString source: sourceString 

className := classString asSymbol.
selector := selectorString asSymbol.

category := catString
ifNil: [ #'as yet unclassified']
ifNotNil: [ (catString asSymbol) ifEmpty: [#'as yet unclassified']].

timeStamp := timeString.
classIsMeta := metaBoolean.
source := sourceString withInternalLineEndings.
```

Thanks :)

OS : Windows 10
Pharo 11 build 456

**Comment by Ducasse** [comment]
Thanks. We probably have a bug in the MC support because MC zip the code and use a binary old serialization. The problem is to also fix the causes of the bug but since there is the serialisation we should get a case where we can save and crash on reload. Anyway your fix is the first step.

**Comment by MarcusDenker** [comment]
PR is ready for review: https://github.com/pharo-project/pharo/pull/12589
