### ISSUE TITLE
"Browse this version in Calypso" Error after clicking an unloaded package

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#12412]
**Bug description**

A NotFound exception is raised from the DAMessageSendAnalyzer after clicking a package in the Calypso browser on an unloaded package. This was found when trying to reproduce https://github.com/pharo-project/pharo/issues/9684

**To Reproduce**

![calypso_external_browse](https://user-images.githubusercontent.com/4825959/214012710-9e359498-b0fa-4003-a911-f905acdbdb4c.gif)

**Version information:**
 - OS: macOS
 - Pharo Version 11

**Expected development cost**
We need to check if Calypso should calculate dependencies for unloaded packages.

**Comment by MarcusDenker** [comment]
PR merged
