### ISSUE TITLE
ZeroDivide - update to a more recent Roassal is needed

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#12427]
I tried the new memory profiler from @jordanmontt in Pharo 11 (see https://twitter.com/TorstenAstares/status/1618227007745318912) and found a ZeroDivide issue in Roassal3

![image](https://user-images.githubusercontent.com/5980033/214630437-ebcd77d7-b333-4ce2-89cc-07a82a9ddf5e.png)

When the number of ticks is zero in the config

This is a known Roassal3 issue

**Comment by astares** [comment]
I talked to @akevalion on Discord about it:

![image](https://user-images.githubusercontent.com/5980033/214630768-dc3a33cc-ff5d-45de-88e4-d505979a33f6.png)

**Comment by astares** [comment]
![image](https://user-images.githubusercontent.com/5980033/214631058-69189e1a-bc6f-4a28-85ed-057db15b1337.png)

**Comment by astares** [comment]
So if we could have a new Roassal3 release on the latest code and include this it would be solving the issue

**Comment by jordanmontt** [comment]
Edit:

Sorry I didn't read well. Thanks astares for looking up the tool. We'll update the Roassal version in Pharo 11 :)

**Comment by MarcusDenker** [comment]
This one will be fixed with a new version, too: https://github.com/pharo-project/pharo/issues/7899
