### ISSUE TITLE
Changes browser broken

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#12426]
**Bug description**
When using an auto-fix from a critic in the browser, a changes browser shows up.
It is supposed to show changes before the change and after but it presents the diff as a standard method and syntax highlighting is bad.

**To Reproduce**
1. Open a browser on a method
2. Add a point after the last expression.
3. Click on autofix in the critic

![Capture d’écran 2023-01-25 à 12 35 30](https://user-images.githubusercontent.com/2494203/214554446-40a36c76-f2cc-454e-9e90-5c09361c756f.png)

**Comment by astares** [comment]
A left/right diff similar to the commit diffs in Iceberg would be better than old ChangesBrowser and provide more UI consistency among the tools too.

ChangesBrowser is called in  #doAutoFix
