### ISSUE TITLE
Double-click often selects only part of the word

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#12428]
**Bug description**
When user selects a word by double cliking on it, it often selects only part of the word.

![Pharo_DZveYJC10q](https://user-images.githubusercontent.com/572494/214778807-473680f7-7ef3-4019-be03-85a9bc8578f2.gif)

It is caused by small movement of the mouse during double click. It is highly annoying and it was introduced in Pharo 11.

I discovered that it was introduced in the build 276 fixing https://github.com/pharo-project/pharo/issues/11727
The commit causing it is: https://github.com/pharo-project/pharo/pull/11838/files by @akevalion

**To Reproduce**
1. double click on a word and try to slightly move mouse right during double click

**Comment by akevalion** [comment]
This issue is still present, @MarcusDenker could you please reopen it? it was closed by mistake
