### ISSUE TITLE
Better user experience for final dot critique and cleaning 

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#12431]
By default we would like to remove unnecessary separators from method body to istay clean.

See 
    https://twitter.com/TorstenAstares/status/1609666189382254593
    https://twitter.com/TorstenAstares/status/1609952076804628482
and #12387

This includes unnecessary and unwanted spaces, tabs but also final dots at the end of the method.

Despite the cleaning and the default in the Pharo standard image some users might nonetheless
want to continue with them for their own packages.  They also might not want to be criticized for 
their the final dots.

So we should increase the user experience by providing a setting where they can disable this
default in the settings browser like:

![image](https://user-images.githubusercontent.com/5980033/214922724-260fce85-3139-4f5d-a580-2d50970084c6.png)

**Comment by MarcusDenker** [comment]
one idea could be to split the rule into two: whitespace and dot.

For whitespace, I want to experiment then with an automation: accepting code should do the whitespace remove automatically.

**Comment by jordanmontt** [comment]
I like the idea of splitting the rule into two rules: white spaces and dots :)

**Comment by astares** [comment]
No need to split but just configure - as this is possible with the same code. Already working on it. Please stay patient.

And yes - cleaning on accept would also be nice. But step by step.

**Comment by MarcusDenker** [comment]
What confuses me is that I alway get a message about a dot, but there is no dot. Yes, it says "or", but my brain can not hanle that.

For me a split would really improve the situation.

**Comment by astares** [comment]
It's not finished yet ...

**Comment by astares** [comment]
PR is in #12455
