### ISSUE TITLE
Bug when commentary text zone in the Class Browser is drag'n drop with selection

### ISSUE THREAD

**Issue by labordep** [guillep/pharo-core#12459]
This bug is easy to reproduce with the mouse (not trackpad), you need to do some drag'n drops with selection (by double clic for example), move the mouse inside the selected text and try to have the bug. This bug is very and it's come a lot of time during my programmation sessions :/ 

I think I have a fix, I send a PR soon.

# 1 Go into a commentary zone
![image](https://user-images.githubusercontent.com/49183340/215336595-9aa50392-18d4-429e-8099-06f27fc0e558.png)

# 2 Selection with double click
![image](https://user-images.githubusercontent.com/49183340/215336824-6b0fca8d-7729-471f-ade2-c671dcf0cab1.png)

# 3 Drag and drop inside the selected text with the mouse cursor
![image](https://user-images.githubusercontent.com/49183340/215337104-51bec747-c15f-45f7-a541-14fad105e62e.png)

My configuration : 
- Windows 11 Pro
- Pharo-11.0.0+build.483

**Comment by labordep** [comment]
This bug is coming in every text zone, same problem in the source code editor.

**Comment by guillep** [comment]
I confirm the bug.

To reproduce it, it's important that after the double click the click is retained, and dragged.

**Comment by guillep** [comment]
I chased the cause of the bug to the following commit, P11 build 276.

https://github.com/pharo-project/pharo/commit/cc9a472598f7d6fa0041657b8bd51654d8f573a3 (PR https://github.com/pharo-project/pharo/pull/11838)

Before that, double click did wait until mouse up to make the selection.
