### ISSUE TITLE
Cannot type commands in the emergency debugger "ED"

### ISSUE THREAD

**Issue by labordep** [guillep/pharo-core#12461]
I cannot type any commands when I'm using ED.
To reproduce :

Place a breakpoint here :
```
Morph>>openInWorld
```
![image](https://user-images.githubusercontent.com/49183340/215344472-7ccf0e7d-7704-4b43-9c2e-347147a90fed.png)

And open any SpPresenter (for example the About... window in the main menu view), the emergency debugger appears : 
![image](https://user-images.githubusercontent.com/49183340/215344539-4216ecee-24ab-4dba-aeea-02cab0b97cc3.png)

Here I can : 

- Use arrow key (up and down) to navigate in the stack

I cannot : 

 - Type anything, characters, numbers, esc, entrer, alt, ctrl, etc. have no effects

My config : 
- Windows 11 Pro
- Pharo-11.0.0+build.483

**Comment by astares** [comment]
I guess #openInWorld is called very often - so a general breakpoint will called again and again.

Did you try with a "Break once/Halt once" one-time breakpoint?

**Comment by guillep** [comment]
@astares I think the point is that when the emergency evaluator opens, it should work :) Putting a breakpoint in `openInWorld` is just an easy and effective way of making it appear.

**Comment by adri09070** [comment]
Actually, I don't think so.

I've tried to open the emergency debugger by changing its priority so that it becomes the default debugger.

Then, evaluating `1 / 0` opens ED and I'm able to write commands.

Putting a breakpoint in `openInWorld` specifically prevents from entering commands when ED opens. Weirdly enough, it seems to recognize when I press arrows, enter or delete but not any other key in that case

**Comment by astares** [comment]
@adri09070 again the question: what happens when you insert a one time breakpoint. Does it then also block ED?

**Comment by adri09070** [comment]
@astares yes it does

**Comment by labordep** [comment]
@astares @adri09070 I have tested the two cases : 

For breakpoint in `Morph>>openInWorld` and testing by opening the `About...` view :
![image](https://user-images.githubusercontent.com/49183340/216829829-f827b6e3-ea3a-4e95-91d1-3daa464fe31b.png)

1. With a one time break point
![image](https://user-images.githubusercontent.com/49183340/216829810-67ea6a83-ce1f-48b7-b984-d4cdfa20e655.png)

I have a standard debug view : 
![image](https://user-images.githubusercontent.com/49183340/216829880-65bb6e99-df4e-4348-9fce-ddcc14ee80e6.png)

No problem to use the debugguer and navigate in the stack, restart, etc.

2. With a normal break point
Same problem as @adri09070 and my ticket (cannot type commands).

**Comment by adri09070** [comment]
@astares @labordep I complete:

With a one-time breakpoint in `Morph>>#openInWorld`, and if you change the top priority debugger to ED:

![image](https://user-images.githubusercontent.com/97704417/216916533-2e2d5dc6-c879-4779-ac34-33d37d76385a.png)

Then the same problem appears (cannot type commands in ED)

**Comment by hernanmd** [comment]
Is this bug still alive?

**Comment by labordep** [comment]
hi @hernanmd I have tested on latest Pharo 12 version and this is ok!
Thanks :)
