### ISSUE TITLE
TestRunnner and Regex error - nullable closure

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#12477]
Open a Test runner in Pharo 11 and enter * in the filter for the test classes and system will show an error:

![image](https://user-images.githubusercontent.com/5980033/215550647-be0c13e7-770d-4ce8-a1cc-a8dc8880daba.png)

**Comment by hernanmd** [comment]
@MarcusDenker I think this one can be closed too, since it is fixed in Pharo 13

**Comment by astares** [comment]
Does not happen in latest image for P12 and P13. Lets close it.
