### ISSUE TITLE
Documentation fix for `Dictionary >> keysAndValuesDo:`

### ISSUE THREAD

**Issue by edward** [guillep/pharo-core#12498]
Just a small documentation correction for `Dictionary >> keysAndValuesDo:`:

```diff
-d keysAndValuesDo: [ :k :v | a add: v. a add: k ].
-""an OrderedCollection(75 5 8 3 3 1 5 4 4 2)""
+ d keysAndValuesDo: [ :k :v | a add: v. a add: k ].
+ a.
+ ""an OrderedCollection (76 5 9 3 4 1 6 4 5 2)""
```

(I couldn’t find this in the sources on GitHub 😅)

Do you need a paper copy signed contribution consent form for this?

**Comment by MarcusDenker** [comment]
Thanks, no contribution agreement needed (too small the change)
