### ISSUE TITLE
ImageCleaner shareLiterals shouldn't consider Strings and Symbols the same

### ISSUE THREAD

**Issue by sonibla** [guillep/pharo-core#12518]
**Bug description**
Symbols can be replaced to Strings by ImageCleaner shareLiterals
If in a method you have for example 'something' and #something , then run ImageCleaner shareLiterals, we get a String instead of the #something symbol at runtime

**Additional context**
Related to https://github.com/pharo-project/pharo/issues/12420

**Comment by MarcusDenker** [comment]
I think the problem is in ImageCleaner>>#createLiteralTable, it uses indexOf: instead of identityIndexOf:

The problem therefore should only happen if you have a literal array with both a symbol and a string that are equal, like:

tt
	^ #(#something 'something' ) first

**Comment by MarcusDenker** [comment]
I added a PR that fixes the problem. Ready to be reviewed here: https://github.com/pharo-project/pharo/pull/12529
