### ISSUE TITLE
Duplication of vm parameters description

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#12514]
The vm parameters are described in VirtualMachine>>#parameterLabels but also in StSystemReporter>>#reportVMParameters:

IMO the SystemReporter should use the descriptions given by the VirtualMachine class. The problem now is that both lists are different. It'd be good to unify both.

**Comment by privat** [comment]
PR in the queue: https://github.com/pharo-spec/NewTools/pull/448 add +1 and/or poke maintainers :)

**Comment by MarcusDenker** [comment]
merged
