### ISSUE TITLE
Move `RBMoveInstVarToClassRefactoring >> collectSendersOfInstVar` to metamodel

### ISSUE THREAD

**Issue by balsa-sarenac** [guillep/pharo-core#12535]
Move `RBMoveInstVarToClassRefactoring >> collectSendersOfInstVar`
https://github.com/pharo-project/pharo/blob/df47994ba499c88a2a7d694269d87ae192269796/src/Refactoring-Core/RBMoveInstVarToClassRefactoring.class.st#L29

to metamodel so that it can be reused throughout the system.

**Comment by Ducasse** [comment]
This method and class do not exit anymore so I close the issue
