### ISSUE TITLE
DeprecationPerformedNotification:  The method Float class>>#epsilon has been deprecated. 

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#12572]
**Bug description**
On the CI logs we see

```
DeprecationPerformedNotification: Automatic deprecation code rewrite: The method Float class>>#epsilon called from RSTransformable>>#updateCurrentShape: has been deprecated. Use machineEpsilon instead
```

**Comment by jecisc** [comment]
This seems to be fixed in master branch of roassal but not yet integrated in Pharo

**Comment by MarcusDenker** [comment]
We could un-depricate until that merge is done.

**Comment by MarcusDenker** [comment]
(as this leads to this errror happing very often:

https://github.com/pharo-project/pharo/issues/12575

to the point of making the CI unusable.

**Comment by akevalion** [comment]
Hello roassal uses `Float epsilon` in project numeric scales. Then I will update that project to use the new method `Float machineEpsilon`, and also keep retro compatibility with old pharo versions

**Comment by akevalion** [comment]
At the end the easy way for me to do it was removing dependency to epsilon in roassal, now this error will not be present in the next roassal release

**Comment by svenvc** [comment]
There are software packages (mine) that are maintained for older versions of Pharo.

When I use epsilon, I cannot move to machineEpsilon since that does not exist in older Pharo images.

Automatic rewriting makes this real issue ;-)

**Comment by jecisc** [comment]
Roassal was updated if I’m not wrong. So I guess we could close this issue?

**Comment by jecisc** [comment]
I’ll close it because there is 0 sender the latest Pharo 11
