### ISSUE TITLE
DNU #wantSteps on method remove

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#12595]
**Bug description**
When removing a method from the method browser --> DNU as #wantSteps is send to a non-morph

1 implementors of #acceptVisitorNeverFinishes: 
2 remove that method with cmd-x
3 see DNU

wantSteps should check if the model is a morph or a model?

**Comment by MarcusDenker** [comment]
Sadly this does not work:

```
wantsSteps
	"Return true if the model wants its view to be stepped.  For an open system window, we give the model to offer an opinion"

	^ isCollapsed not and: [ model isNotNil and: [ (model respondsTo: #wantsSteps) and: [model wantsSteps ] ] ]
```

as the deprecated method #wantsSteps in Object means the "model respondsTo: #wantsSteps" is always true

**Comment by hernanmd** [comment]
Since #wantsSteps is only a Morphic thing we could just ask if model is a Morph?

```smalltalk
wantsSteps
	"Return true if the model wants its view to be stepped.  For an open system window, we give the model to offer an opinion"

	^ isCollapsed not and: [ model isNotNil and: [ model isMorph and: [ model wantsSteps ] ] ]
```

**Comment by jecisc** [comment]
This is not only on Morph but also Model
