### ISSUE TITLE
Breakpoint in #getExtractedSource blocks implementors and does not appear in Breakpoint overview

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#12592]
In a fresh up to date Pharo 11 image I have a strange effect that can be reproduced with this scenario:

1.  I open a new playground and enter "getExtractedSource" and select the text
2. I check for the **implementors** of this method using CTRL+M key which opens the implementors browser
=> A single implementing method is found (RBExtractMethodRefactoring>>#getExtractedSource)
3. Now I visit this method in the browser and add a breakpoint
=> when setting the breakpoint the method **disappears** now from the found implementors list - WHY???
4. When I check the world menu "Debug" -> "Browse Breakpoints" the breakpoint browser also shows as empty - the method does not appear there

![image](https://user-images.githubusercontent.com/5980033/217522839-53687c7a-4836-40a9-afec-d1164889c1d3.png)

But I can double check and the system tells me that the breakpoint is active:

```Smalltalk
Breakpoint allInstances size. "1"
Breakpoint allInstances first isEnabled "true"
```

**Comment by MarcusDenker** [comment]
This has something todo with how the "implementors of" browser filters... if you do "implementors of" from the browser, it shows the method, from the playground, it does not.

**Comment by astares** [comment]
@MarcusDenker And why is the breakpoint not showing up in "Debug" -> "Browse Breakpoints" ?

**Comment by MarcusDenker** [comment]
No idea... could be the same reason. It might make it easier to debug, browse breakpoints calls this: 

ClyQueryBrowserMorph class>>#browseBreakpoints

Somehow the method gets removed from the results shown, but it is not clear why

**Comment by MarcusDenker** [comment]
This is now working in correctly in Pharo12
