### ISSUE TITLE
[Feature Request] Community page should mention Mastadon link

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#12590]
https://www.pharo.org/community

should (beside Twitter) also mention Mastadon and include the new Mastadon link

**Comment by MarcusDenker** [comment]
already done, it has:

mastodon: [@pharoproject@mastodon.social](https://mastodon.social/@pharoproject)

**Comment by astares** [comment]
@MarcusDenker Ah yes - but this is a different issue - please reopen this task.

But the link is hard to find as the heading **still says "Twitter", but "Mastadon" is a different thing.**

Maybe we should change to "Twitter / Mastadon" or even better give Mastadon an own section with heading "Mastadon" 

![image](https://user-images.githubusercontent.com/5980033/217511668-a6b54c0a-44a7-4dba-882c-bc8316babe32.png)

**Comment by MarcusDenker** [comment]
The best is to open an issue where pull request can be done:

https://github.com/pharo-project/pharo-site

<blockquote><img src="https://opengraph.githubassets.com/d792ae72f9d9033e640a1e69c6acfaa68c16eafaca3cf1ef7fdb60b88230ceca/pharo-project/pharo-site" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-site">GitHub - pharo-project/pharo-site</a></strong></div><div>Contribute to pharo-project/pharo-site development by creating an account on GitHub.</div></blockquote>

**Comment by astares** [comment]
**Issue**: https://github.com/pharo-project/pharo-site/issues/21
**PR**:     https://github.com/pharo-project/pharo-site/pull/22
