### ISSUE TITLE
Unnecessary characters rule checks spaces inside a String

### ISSUE THREAD

**Issue by jordanmontt** [guillep/pharo-core#12614]
The rule unnecessary characters found in method body checks for characters inside a String. For example see photo below:

<img width="857" alt="Capture d’écran 2023-02-09 à 21 59 02" src="https://user-images.githubusercontent.com/33934979/218098843-c79d6d84-7b12-4bb0-8b31-13cc4b22bbed.png">

It detects one space inside a String. For me this should not be the case since there is no code formatting inside the content of a String

**Comment by svenvc** [comment]
OMG

**Comment by MarcusDenker** [comment]
@astares please check... I have to admit this is for me too much work for whitespace that I in the end should not care about.

If you want the code clean on that level, you have to find a way to do it that does not need the time of people.

I really feel that I am supposed to use my time for something else that white space.

**Comment by astares** [comment]
The lint rule shows as it says
- "UNNECESSARY CHARACTERS" which are otherwise hidden and not visible to the user 
- YES - it is even showing them inside of a string and 
- it will be removed ONLY when the developer decides to remove them by applying the autofix and this is also done with a clear PREVIEW showing you the effect - so the developer is in FULL CONTROL
- it is a hint that you can easily ignore or ban with a single click
- I've already shown that it is also possible to totally disable the rule in the settings if you do not like it (which is a general mechanism and can be done with any rule)

So I do not understand why you consider this a bug.

**Comment by astares** [comment]
If that eases the understanding I reduced the #severity of the rule from #warning to #information 

![image](https://user-images.githubusercontent.com/5980033/218413306-0de18d52-31c3-40de-ac50-3ff0cb2f25bc.png)

**Comment by jordanmontt** [comment]
It is ok that the rule detects the spaces as unnecessary characters and gives a warning. For me this is a bug because it should NOT analyze empty spaces inside Strings. Since the contents of a string it does not have any format and its modification can cause a program to break. So the rule is ok but it should not look inside strings declaration. 

Thinking about it, maybe the bug is in the matching engine that is used?

**Comment by astares** [comment]
@jordanmontt 

Looks like you do not get my point here: this whole thing is not about formatting. It is about unnecessary clutter in the method body AT THE END OF A LINE (which is normally invisible if you do not have that rule/information) that one might want to avoid and a mechanism to easily get rid of it.

So even in Strings this makes sense. It does not change positions in strings or distances between words - it only removes unnecessary characters before the line breaks.

If the method returns or uses a resource string in the method body that spans over multiple lines then in nearly all cases I've found these are also unnecessary characters. It would require a lot of manual editing if one would remove them manually from such resource strings. So this is helpful even for the strings.

Additionally we let the developer decide if he wants to clean the method or not. So we do not destroy the source code automagically - like with many other rules the user can decide.

Do you have a specific case in mind where you see a problem and where a program would really break?
So far your abstract description without a concrete example sounds very theoretical as certain conditions must be met (all at the same time):

 - the method body must have a string inside AND
 - the string must span over multiple lines AND
 - the string must have additional spaces AT THEND OF the lines that have an open end (not terminated) AND  
 - the algorithm must rely on these additional invisible spaces AND
 - then also additionally break if they are not there.

There is an extremely small chance that a method/program is constructed that way, relies on the clutter and breaks.
To me without a concrete example theoretical case

Even if you might be able to construct such a case
 - the developer then has another problem as he RELIES ON **INVISIBLE** SPACES AT THE END OF LINE(S)
   IN A METHOD and in such a case the lint rule could help him to recognize this INVISIBLE stuff
 - still even for such a case the lint rule is non-obtrusive - the developer can still decide if he wants to ignore, ban the rule or clean the method body
  
So please provide a more concrete situation and example where it breaks stuff when applied. 

SIDE NOTE: 
The only case I can imagine - and that I found while now condensing all packages in the standard image
is when we test method bodies itself by comparing them to strings. These were cases comparing test results from the refactoring engine. But with the help of this lint rule I was able to spot and repair these cases easily - in fact the lint rule revealed that they were relying on such invisible characters too which is now not the case anymore.

**Comment by jordanmontt** [comment]
> Do you have a specific case in mind where you see a problem and where a program would really break?

So, there are possible different examples in which removing an space inside a String can cause a bug. I don't think is relevant for this discussion to write an example since we are not discussing about that. As you said, a test for the formatter can be a good example. If you want I can write a test that breaks when you remove a white space inside a String.

The point of this is NOT that if is a good programming practice or not to use spaces inside a String. The point IS that a code quality rule should not check inside the content of a String.

Even if we say that checking inside a String is ok, the behavior of this rule is not consistent.

For example look at these methods, they do not show any warning even that there are white spaces.

![Capture d’écran 2023-02-13 à 16 30 52](https://user-images.githubusercontent.com/33934979/218500673-55951b40-5759-4dec-ab18-e7ef3a2230bb.png)

![Capture d’écran 2023-02-13 à 16 33 00](https://user-images.githubusercontent.com/33934979/218501230-eddfb0bc-6579-4085-b7bd-bbddac2b7a39.png)

So, for me I still think that we should not raise any type of warning for the content that is inside a String. I'm not sure if this bug is because of this rule or because of the "rule engine" or the backend that does the matching between the rule and Pharo code. But there is a problem

**Comment by astares** [comment]
>For example look at these methods, they do not show any warning even that there are white spaces.

Yes - and this is correct. These spaces in the two examples given are NOT UNNECESSARY as developer might concatenate 
this resource strings or do other things with them later.

Also in these cases the developer is easily aware of these spaces as they are between the last word and the closing $' of the string. 

So in your sceenshots the developer would SEE the spaces.

But if you have a multiline string with HIDDEN SPACES at the end of line then it keeps you informed:  

![image](https://user-images.githubusercontent.com/5980033/218507027-3c6bb912-c67e-4a66-b8a0-ce9a7e43f421.png)

and I can only repeat myself: it tells the developer and makes such cases visible. The decision and control is fully in the hand of the developer!

>So, for me I still think that we should not raise any type of warning for the content that is inside a String

It's not marking it as a **warning** anymore. With the PR #12764  it just gives you an **info** = hint now that there are unnecessary characters.  

>The point IS that a code quality rule should not check inside the content of a String.

And my point is what is your problem that it checks? I would not consider this a bug but a helpful and non-obtrusive feature. 
It can reveal unnecessary characters, give you an info and if you want it will fix them for you without big effort. If you see them as necessary to keep (what every the reason might be) you can ban the rule on the method or disable it globally.
Also here developer is in full control and nothing breaks.

And it does what it promises: it gives you an info about unnecessary (hidden) characters within a method body. And it is up to the developer to decide what to do with them.

**Comment by astares** [comment]
Also I would not see it as consistent if the rule would NOT inform the developer about unnecessary characters within the string:

If the rule would not give a hint also within strings that span multiple lines one would not be able to recognize the HIDDEN SPACES at the END OF THE LINES. So I ask you how would a developer be able to distinguish:

```Smalltalk
foo
   ^'This is a method
with a resource string'
```
which has no unnecessary spaces 
from this one 

```Smalltalk
foo
   ^'This is a method                                                                                                                          
with a resource string'
```

which looks exactly the same but has MANY unnecessary spaces that you will not see. You would only see them when you would select specific text areas.

![image](https://user-images.githubusercontent.com/5980033/218515664-c6b0f2c3-fc0d-4ef8-a8f5-68596c553a93.png)


So I stand with my point: it is useful to check also within the strings - and developer is still in full control.
