### ISSUE TITLE
TPrintTest>>#testPrintElementsOn assert nothing

### ISSUE THREAD

**Issue by vonbecmann** [guillep/pharo-core#12645]
TPrintTest>>#testPrintElementsOn assert nothing

the temporary result is always empty so there is nothing to assert

this following code using stream is similar to the testcase
```
|result aStream|
result:=''.
aStream:= ReadWriteStream on: result.
aStream 
 print: 'hello!';
 flush;
 close.
self assert: result isEmpty.
result
```
and it doesn't modify result.

debug LinkedListTest>>#testPrintElementsOn and inspect the temporary result.

Pharo image: Pharo11.0.0#110532
Virtual machine used: CoInterpreter * VMMaker-tonel.1 uuid: aa6234f4-799d-0d00-90d1-c90e092bce84 Jun 10 2022
StackToRegisterMappingCogit * VMMaker-tonel.1 uuid: aa6234f4-799d-0d00-90d1-c90e092bce84 Jun 10 2022
v9.0.15 - Commit: b487900 - Date: 2022-06-02 09:48:57 +0200

Platform Name: unix
Class browser used (if applicable): ClyFullBrowserMorph

**Comment by vonbecmann** [comment]
similar code in
TPrintTest>>#testPrintOn.
TPrintTest>>#testPrintOnDelimiterLast.

**Comment by guillep** [comment]
Yes, that test is bad, it should use `contents` on the stream.

**Comment by vonbecmann** [comment]
another question: how do you know that the test's assert are executed? is there something like code coverage for tests?

**Comment by Ducasse** [comment]
There is a plugin for rotten green tests identification but I do not know the status. 
Ideally it should be used in DrTest
