### ISSUE TITLE
Remove SerialPort?

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#12767]
It was brought in https://github.com/pharo-project/pharo/pull/12692 that SerialPort vm plugin does not exist anymore. If that is really the case, maybe the package should be removed from the system

**Comment by astares** [comment]
@estebanlm / @tesonep 

Do we know why the SerialPort plugin had been removed from VM? Was it broken or due to (high) maintenance effort?

**Comment by robvanlopik** [comment]
SerialPlugin was not part of the new VM back in 2021. @tesonep has an FFI-based implementation (github.com/tesonep/SerialPort ) that I am using now for over a year, but it still didn't make it into the image. Or maybe it should be an external package. Anyway, the code in the present image cannot work

**Comment by astares** [comment]
OK - then lets remove the package

**Comment by jecisc** [comment]
Pablo agrees to remove this old implementation and keep his project loadable
