### ISSUE TITLE
No rule check for non-existing super implementor

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#12766]
**Bug description**
We do not have a code rule check that will inform about non-existing implementor of a message send if the message is sent by `super`.

**To Reproduce**
1. in any class, create this method
```smalltalk
uniqueMessage 

	self asString.
	^ super uniqueMessage
```
2. no warning

(asString message is here just to prevent warning about a method using super send only)

**Comment by pavel-krivanek** [comment]
@astares, please, create a PR

**Comment by astares** [comment]
@pavel-krivanek there is one https://github.com/pharo-project/pharo/pull/12784 but it seem to need more work

**Comment by astares** [comment]
new PR provided in https://github.com/pharo-project/pharo/pull/15705
