### ISSUE TITLE
Unreferenced OldUnicodeInitializer

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#12772]
- Should we deprecate "OldUnicodeInitializer", it is not referenced in Pharo11
- or should we remove the whole "Unicode-Initialization" package?

**Comment by guillep** [comment]
It seems that the code in that class is duplicated in Zinc.
I could not find any usage in the boostrap, so I'd say it's worth trying.

**Comment by astares** [comment]
@guillep remove or deprecate?
