### ISSUE TITLE
categorization tests should print culprints if any

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#12779]
Running `ProperMethodCategorizationTest` tests could lead to failures.
The problem is that the output (you can see it on CI logs) is unusable. Culprint methods are not listed.
It is very annoying because, in some situations, it is hard to reproduce the failure.
Culprints should be printed.

**Comment by jecisc** [comment]
The assertion could be `self assert: violating isEmpty description: 'Instance side #initialize methods should be in "initialization" method category:' , violating asString` in testInstanceSideInitializeMethodNeedsToBeInInitializationProtocol
