### ISSUE TITLE
DrTest: Filter with includes substring instead of begins with

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#12788]
It happens a lot to me that I want to run the tests of a project that is part of a meta-project. For example AI-HierarchicalClustering-Test. To select this package in DrTest I type "Hier" in the package list filter. 

Currently there is not result because my package starts with "AI-", but in the previous test runner, it was filtering by also returning the elements including the pattern given. 

I wonder if this could not be a better behivor also for DrTest. 

Anyone has an opinion on that?

**Comment by privat** [comment]
I had the same issue, so I preorder the PR that fix that :+1: :)

**Comment by Ducasse** [comment]
ah if we can preorder then me too :)

**Comment by jecisc** [comment]
I proposed a change
