### ISSUE TITLE
[CI] Zinc servers tests can conflict on the port to use

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#12783]
Zinc tests can conflict on the port to use. Currently it selects a port among 32 available ports but this is not enough.

The best solution would be to ask the OS for an available port, but this requires more work in Zinc.

I have other propositions:
- Factorize the code used in Zinc to create a test server 
- Do not select a random port for each test, but select a port for the image (we could save it in a class variable that we reset at startup)
- Add a retry mechanism that will change this port once if the server fails to run

@svenvc what do you think about that?

**Comment by svenvc** [comment]
I wrote an initial response here: https://github.com/pharo-project/pharo/pull/12776#issuecomment-1430061582

**Comment by svenvc** [comment]
Check the following code:
```
ZnServer startDefaultOn: 0.

ZnServer default port.

ZnClient new beOneShot get: ZnServer default localUrl / #random.

ZnServer default stop.
```
If this would work reliably on all platforms, it could be used to fix this issue.
I will add a test to Zinc to test this, so we can see what happens.
But I can't test on Windows.

**Comment by svenvc** [comment]
OK, that test already exists ;-)

See ZnServerTest>>#testOSAssignedPort

When I have time I will see what I can do.

**Comment by svenvc** [comment]
This seems to work (on linux and macOS at least): https://github.com/svenvc/zinc/commit/1eac718014f9bb5c0fd27fd16f2af8be11ad2daa

**Comment by jecisc** [comment]
Thank you sven!

That is a great solution and a really quick fix!
Anything that can make Pharo CI more robust is really welcomed! :)

**Comment by svenvc** [comment]
The question now is: how to get this into the main Pharo development image.

This requires another sync of Zinc, but that has again become *very* difficult due to massive amounts of <leaving out lots of adjectives> formatting changes. Like last time, I am not going to do this on my own. Volunteers with git power skills are welcome to help.

**Comment by Ducasse** [comment]
What we decided is that if we have important changes we will favor them over formatting changes because else it is just a pain to resolve the conflicts. And I think that this is a nice solution.

**Comment by jecisc** [comment]
> The question now is: how to get this into the main Pharo development image.
> 
> This requires another sync of Zinc, but that has again become _very_ difficult due to massive amounts of formatting changes. Like last time, I am not going to do this on my own. Volunteers with git power skills are welcome to help.

I can see to help you. My knowledge of git is not perfect but still relatively good. 
What would you like me to help with?

**Comment by svenvc** [comment]
OK, thanks for the offer, accepted ;-)

The idea would be to merge everything that is newer in the Zinc repository into the Pharo 11 repository, but without reverting changes that were done there and were not synced back upstream.

The easiest way to do this is to start updating the Zinc repo with changes in Pharo, so that the difference becomes smaller.

I think the main issue is the last 'condensing' source code formatting changes that were done, maybe more. Maybe @astares can show me how to run his modification script so that we can run that on the Zinc repo code base ourself. Even better would be a PR ;-)

**Comment by jecisc** [comment]
For now the condensation of Zinc is not yet integrated, but a PR is pending so we might aswell do it directly in Zinc. 

The changes can be done with 

```st
cms := CompiledMethod allInstances select: [:each |
each package ifNil: [ false ] ifNotNil: [:p |
	p name beginsWith: 'Zinc' ] ].
 

cms do: [:cm |
    ((RBRefactoryChangeFactory instance)
         addMethodSource: (ReMethodSourceCleaner clean: cm sourceCode) in: cm origin) execute ]
```

But maybe this should be the last change to apply after gathering the other changes first

**Comment by jecisc** [comment]
> OK, thanks for the offer, accepted ;-)
> 
> The idea would be to merge everything that is newer in the Zinc repository into the Pharo 11 repository, but without reverting changes that were done there and were not synced back upstream.
> 
> The easiest way to do this is to start updating the Zinc repo with changes in Pharo, so that the difference becomes smaller.
> 
> I think the main issue is the last 'condensing' source code formatting changes that were done, maybe more. Maybe @astares can show me how to run his modification script so that we can run that on the Zinc repo code base ourself. Even better would be a PR ;-)

I’m checking but it is not easy to follow the changes on both side ^^’

**Comment by svenvc** [comment]
I will try running the script myself

**Comment by jecisc** [comment]
I have the impression that not many changes happened on Pharo side that are not on Zinc since the last sync in May 2022

**Comment by jecisc** [comment]
So the next sync should bring:

- [Condense sources before the next Pharo sync](https://github.com/svenvc/zinc/commit/f57d25030f1c0a3a4f4946a5064745749c76b05d)
- [Fix an edge case in ZnCharacterRead[Write]Stream>>#upToAll: as report](https://github.com/svenvc/zinc/commit/70190ebab5023cfde4af197a1575cacac6e50bcf)
- [Introduce ZnServer classs>>#withOSAssignedPortDo:](https://github.com/svenvc/zinc/commit/1eac718014f9bb5c0fd27fd16f2af8be11ad2daa)
- [Add an extra guard to ZnUTF8Encoder>>#nextCodePointFromStream: for il…](https://github.com/svenvc/zinc/commit/37b7d0f83835520efbde74be65fef35ebc308b95)
- [Refactor system JSON parser code selector into ZnUtils](https://github.com/svenvc/zinc/commit/a588c98880bb5c543fb084aa05b7fdaeae4fb05f)
- [Run ZnServerTest>>#testTooManyConcurrentConnections under #usingClass](https://github.com/svenvc/zinc/commit/c6f2f6174a3b0764987363d76a82165864ed8168)
-

**Comment by svenvc** [comment]
Yes, that sounds about right

**Comment by jecisc** [comment]
https://github.com/pharo-project/pharo/pull/12794

**Comment by svenvc** [comment]
Could the same be done (if necessary) for Zodiac and STON ?

That would be great !

**Comment by jecisc** [comment]
I’ll try to find some time for that, but right now I have other things to work on :)

**Comment by jecisc** [comment]
@svenvc Zodiac is currently up to date. 

I’ll check STON later

**Comment by svenvc** [comment]
Thanks a lot !

**Comment by jecisc** [comment]
PR incoming for STON: https://github.com/pharo-project/pharo/pull/12829
