### ISSUE TITLE
Image freeze when deprecated:transformWith: is used

### ISSUE THREAD

**Issue by labordep** [guillep/pharo-core#12791]
I find a problem when I'm using `Object>>deprecated:transformWith: `.
Download the zip file to have a code to import into a new Pharo image for reproduce it : 

Do the unit test `MyClassTest>>testName`, the image is freezing. I found no possibility to debug or quit, I'm forced to kill the pharo process.

This is a basic code and I'm using the `Object>>deprecated:transformWith: ` as in `ClassDescription>>definition` example.

```
name
	"Example of deprecated rewrite from ClassDescription>>definition"

	self
		deprecated: #name
		transformWith: '`@receiver name:' -> '`@receiver id:'.

	^id
```

And the test : 

```
testName

	| myClass |
	myClass := MyClass new.
	self assert: myClass name.
```

My config : 
- Windows 11 Pro
- Pharo-11.0.0+build.545 (64 Bit)

To reproduce import this code and see `MyClass-Tests` package with the test :
[MyClass-Tests.zip](https://github.com/pharo-project/pharo/files/10758590/MyClass-Tests.zip)

**Comment by labordep** [comment]
@tinchodias find a way to explore : 

When this checkbox is uncheck : ![image](https://user-images.githubusercontent.com/49183340/219439976-17d643ca-c6a1-4656-bac2-a9dd77bc86d5.png) there is a window with an error at the execution of the test : ![image](https://user-images.githubusercontent.com/49183340/219440047-41b9112e-b641-469d-b364-b84ef24927b5.png)

![image](https://user-images.githubusercontent.com/49183340/219439904-79fdf079-ec80-4e0e-8832-16155da1cf21.png)

**Comment by labordep** [comment]
And when the checkbox ![image](https://user-images.githubusercontent.com/49183340/219440829-b5ecc989-7d7c-44c3-91ed-505031c87050.png) is checked, the freeze is here : 

![image](https://user-images.githubusercontent.com/49183340/219440719-8d9ae604-6d31-4115-9a19-fa6ff7f0d705.png)

**Comment by MarcusDenker** [comment]
Just looking at the code: 
the colons are nit correct: "@receiver name:" --> should be "@receiver name", same for id.

**Comment by MarcusDenker** [comment]
it freezes I think due to  #name on classes being used very very deep in the system, if the rename goes wrong it will call that faulty method for sure during error reporting, leading to a loop.

**Comment by labordep** [comment]
Thanks @MarcusDenker, but we have the same problem in Bloc (https://github.com/pharo-graphics/Bloc/issues/207) for another message (not name).

**Comment by labordep** [comment]
It should be better to open a debugger instead of freeze :) I tried to interrupt an eventually loop but this is not working (I have tried MAJ CTRL + . )

**Comment by MarcusDenker** [comment]
But the debugger calls #name again, which leads to the same error, which leads to the same error, which leads to the same error...

**Comment by MarcusDenker** [comment]
If I try this on an example that is not #name of Class (which is very special, as it is called a lot and especially during error handling), it works for me as it should. I get a SytnaxErrorDebugger, I can close it, just as expected.
