### ISSUE TITLE
[CI] testInstanceSideInitializeMethodNeedsToBeInInitializationProtocol started failing

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#12795]
**Bug description**
ProperMethodCategorizationTest>>testInstanceSideInitializeMethodNeedsToBeInInitializationProtocol started failing.

It would be nice to understand why, it means we merged a PR where this test was failing.

Instance side #initialize methods should be in "initialization" method category:

- [ ] EditorFindReplaceDialogWindow>>#initialize
- [ ] StPharoDefaultIconProvider>>#initialize 
- [ ] EqFruit>>#initialize 
- [ ] EqStudent>>#initialize
- [ ] EqTeacher>>#initialize 
- [ ] NSLnScale>>#initialize

**Comment by jecisc** [comment]
This is weird because this test was already there IIRC and the only change was to improve the output of the rule. WE might have missed something.

**Comment by jecisc** [comment]
Where did you see those failing tests?
Because for me it’s green in my image and the Eq classes have the right categorization

**Comment by jecisc** [comment]
I found why it was not failing in my image. I’ll do a PR

**Comment by demarey** [comment]
@MarcusDenker 
It is because Equals packages were not loaded, so not checked. Once in the image, the rule started to find problems.

**Comment by MarcusDenker** [comment]
but should the PR that loaded them not have found the problem?

**Comment by jecisc** [comment]
@MarcusDenker I don’t know how that happened but the CI was green at that time: https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-12616/3/tests

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-12616/3/tests">Jenkins</a></strong></div></blockquote>

**Comment by demarey** [comment]
> but should the PR that loaded them not have found the problem?

Not if the PR was already checked and ok
