### ISSUE TITLE
InitializeSlot causes strange behavior that leads to error

### ISSUE THREAD

**Issue by vitormcruz** [guillep/pharo-core#12811]
Create a class with the following definition:

```
Object << #TestClass
	slots: { #slotA => InitializedSlot default: OrderedCollection new };
	sharedVariables: {};
	package: ''
```

click out and back to the class definition, it changes to:

```
Object << #TestClass
	slots: { #slotA => InitializedSlot default: an OrderedCollection };
	sharedVariables: {};
	package: ''
```

`an OrderedCollection` shows red indicating a syntax error.  If you try to edit the class definition the following error appears:

![image](https://user-images.githubusercontent.com/1001427/219998211-e4a006d8-9740-4e89-8f58-91dea067d550.png)

 - OS: Windows 10
 - Pharo Version 10

**Comment by astares** [comment]
This is because code get evaluated. The only option I found for my slot based private metasystems was to initialize and let the Slot's printString (which is used in the template) reconstruct the object. Far from perfect...

**Comment by vitormcruz** [comment]
I didn't understand. You are saying this behavior is not an error? printString is used to change the definition of the slot?

**Comment by astares** [comment]
The slots message gets evaluated and is printed using #printString and not #storeString  

![image](https://user-images.githubusercontent.com/5980033/220259991-bdf0db3d-6b31-4d30-8566-66f5f61fa792.png)

If we would change AbstractInitializedSlot>>#printOn: from


```Smalltalk
printOn: aStream
	aStream 
		store: self name;
		nextPutAll: ' => ';
		nextPutAll: self class name;
		nextPutAll: ' default: '.
	default printOn: aStream
```

into

```Smalltalk
printOn: aStream
	aStream 
		store: self name;
		nextPutAll: ' => ';
		nextPutAll: self class name;
		nextPutAll: ' default: '.
	aStream store: default 
```
it would work

**Comment by MarcusDenker** [comment]
is this really good to merge?There seems to be now a test failing on the CI related to this
