### ISSUE TITLE
Index out of range using Calypso

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#12821]
Since a while I often get random bugs in Calypso and the error is always the same.

I don’t know how to reproduce exactly but here I got it while saving a method.

This happens on Pharo 11. 

Error message: `Error: index out of range`

Error stack:

```st
PanelMorph(Object)>>error:
PanelMorph(Morph)>>privateAddMorph:atIndex:
PanelMorph(Morph)>>replaceSubmorph:by:
ClyNotebookMorph(SpNotebookMorph)>>updateContentMorph:with:
ClyNotebookMorph(SpNotebookMorph)>>updatePageIndex:
ClyNotebookMorph(TabGroupMorph)>>update:with:
MorphChangedWithArguments>>deliverTo:
ClyNotebookMorph(Morph)>>handleUpdate:
MessageSend>>value:
MessageSend>>cull:
MessageSend>>cull:cull:
[action cull: anAnnouncement cull: announcer] in AnnouncementSubscription>>deliver: in Block: [action cull: anAnnouncement cull: announcer]
FullBlockClosure(BlockClosure)>>on:do:
[ Processor terminateRealActive ] in [ :ex |
			  | onDoCtx handler bottom thisCtx |
			  onDoCtx := thisContext.
			  thisCtx := onDoCtx home.

			  "find the context on stack for which this method's is sender"

			  [ onDoCtx sender == thisCtx ] whileFalse: [
				  onDoCtx := onDoCtx sender.
				  onDoCtx ifNil: [ "Can't find our home context. seems like we're already forked
				and handling another exception in new thread. In this case, just pass it through handler."
					  ^ handlerAction cull: ex ] ].

			  bottom := [ Processor terminateRealActive ] asContext.
			  onDoCtx privSender: bottom.

			  handler := [ handlerAction cull: ex ] asContext.
			  handler privSender: thisContext sender.

			  (Process forContext: handler priority: Processor activePriority) resume.

			  "cut the stack of current process"
			  thisContext privSender: thisCtx.
			  nil ] in FullBlockClosure(BlockClosure)>>on:fork: in Block: [ Processor terminateRealActive ]

```

In PanelMorph>>#replaceSubmorph:by:, we try to get the index of the oldMorph in the list of submorphs. The problem is that my submorphs only contain a calypso method editor morph, and the old morph is a calypso class definition editor morph. Thus the index returned is 0 and there is a morph.

**Comment by Ducasse** [comment]
I often got the same.

**Comment by pavel-krivanek** [comment]
I can reproduce, it is surprisingly simple:
- open fresh Pharo 12 image
- open browser on the class `#AIAstar` (but can be any other), this one is just handy
- go to some method (like `end`)
- go back to the page class definition tab
- change the class name to create a new class (like to `AIAstar2`) and save definition
- DNU
![Pharo_6UVL2DGzwr](https://github.com/pharo-project/pharo/assets/572494/3541d61e-ae5f-4d6a-a321-876eb05ead6a)
