### ISSUE TITLE
[CI] Failing tests: InitializedSlotTest

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#12841]
**Bug description**
Du to merging #12819 without checking that the tests are green, we now have these failing on the CI:

```
testPrintUsingStoreString – MacOSX64.VariablesLibrary.Tests.Tests.InitializedSlotTest
testPrintUsingStoreString – Unix64.VariablesLibrary.Tests.Tests.InitializedSlotTest
```

**Comment by guillep** [comment]
I reverted the PR introducing the issue, it needs more work:
https://github.com/pharo-project/pharo/pull/12842
