### ISSUE TITLE
Numeric keyPad is displaying numbers incorrectly when numLock is disabled

### ISSUE THREAD

**Issue by alesshosry** [guillep/pharo-core#12853]
**Bug description**
Keypad produces a strange behaviour when pressing numbers keys

**To Reproduce**

1. Open textEditor (Like vsCode ...)
2. write numbers using keypad (ex: 123456789) --> numbers displayed correctly
3. Disable NumLock
4. write numbers using keypad (ex: 123456789) --> numbers displayed correctly

***

1. Open playground in Pharo
2. write numbers using keypad (ex: 123456789) --> numbers displayed correctly
3. Disable NumLock
4. write numbers using keypad (ex: 123456789) --> numbers are displayed incorrectly starting number 4

**Expected behavior**
Should be the same behaviour whether numLock is pressed or not (same as any other textEditor)

**Version information:**
 - OS: Mac
 - Version: Ventura
 - Pharo Version 11

**Comment by alesshosry** [comment]
After debugging with @akevalion, we found that the strange behaviour its produced by #convertNumpadKeysOf: If this function is disabled, this will affect badly the behaviour of keypad's functionality in other operating systems.

Probable solution will be: fixing the behaviour in `RubTextEditor>>#keystroke:` instead of `RubTextEditor>>#keyDown:`

**Comment by Ducasse** [comment]
thanks a lot for the investigation.

**Comment by MarcusDenker** [comment]
maybe related to

Weird behavior when typing some numbers with numeric keypad in P11 on Mac #12462

**Comment by alesshosry** [comment]
@MarcusDenker yes same issue.
