### ISSUE TITLE
beRoot was sent to nil

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#12859]
- open Iceberg in Pharo 11
- right click in the projects pane

![image](https://user-images.githubusercontent.com/5980033/221380752-f49593cd-d18b-476f-85c0-e7ccde3c701c.png)

**Comment by Ducasse** [comment]
https://github.com/pharo-vcs/iceberg/issues/1684

**Comment by pavel-krivanek** [comment]
fixed, please close
