### ISSUE TITLE
Delete deprecated methods in Object for the next Pharo version [Pharo12]

### ISSUE THREAD

**Issue by jordanmontt** [guillep/pharo-core#12881]
We have several deprecated methods in `Object`. For the next Pharo version, Pharo 12, we should remove all of those methods since the are deprecated since quite some time. There are even some deprecated methods that refer to non-existing code see. `Object>>#stepIn:`

**Comment by privat** [comment]
Add version information in the depreciation mechanism so that the deprecated method is automatically removed when the next version is reached :)

```st
self deprecated: 'Please use #newMethod instead'
transformWith: '`@receiver oldMethod' -> '`@receiver newMethod'
killFor: 'Pharo12'
```
