### ISSUE TITLE
Enhance Current Fonts with Better One on OSX

### ISSUE THREAD

**Issue by al6x** [guillep/pharo-core#12899]
I just install Pharo 10.0 on OSX to try, and the fonts don't render nicely.
Wonder if it's just problem on my machine or it's expected?

If it's the expected behavior, it may worth to change it to a proper fonts.

<img width="297" alt="Screen Shot 2023-03-06 at 1 00 42 am" src="https://user-images.githubusercontent.com/94196/222965307-1c1e8aab-55c4-4dd6-82e5-441f2c7579dc.png">

<img width="936" alt="Screen Shot 2023-03-06 at 1 00 33 am" src="https://user-images.githubusercontent.com/94196/222965299-f3a54785-e31a-4d8c-b8d5-12c73f1a8d9e.png">

**Comment by sonibla** [comment]
Probably same issue as https://github.com/pharo-project/pharo/issues/10656 if you have a high resolution screen
