### ISSUE TITLE
Rule Engine: what happens if it sees RBParseErrorNode nodes?

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#12918]

**Comment by privat** [comment]
Currently, there is a basic smoke test https://github.com/pharo-project/pharo/blob/Pharo11/src/Renraku-Tests/RBCodeSnippetTest.extension.st that run rules (and count critiques) on the 250+ code snippets (most are faulty).
 
I fixed one or two bug related to rules in previous PR.

<blockquote><img src="https://repository-images.githubusercontent.com/64123480/451beb80-d08b-11e9-9ade-21d166d787d9" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">pharo/RBCodeSnippetTest.extension.st at Pharo11 · pharo-project/pharo</a></strong></div><div>Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk. - pharo/RBCodeSnippetTest.extension.st at Pharo11 · pharo-project/pharo</div></blockquote>
