### ISSUE TITLE
Autofix of Single branch condition lint removed method comment

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#12916]
- Pharo 11
- create a method with a top comment like this:

```Smalltalk
foo: param
	"Hello World"

	param ifTrue: 
		[ Transcript show: 'Pharo rocks'.
		  Transcript show: 'Pharo rocks' ]
```
The system will show a critique like "Replace single branch conditional with guard clause" (last one at the bottom in screenshot)
Click on the button to "Automatically resolve the issue" and the system provides an automatic refactoring that transforms the code into the following code with an early return:

```Smalltalk
foo: param

	param ifFalse: [ ^ self ].
	Transcript show: 'Pharo rocks'.
	Transcript show: 'Pharo rocks'
```

**BUT IT ALSO REMOVED THE METHOD COMMENT WHICH IS A BUG**

![image](https://user-images.githubusercontent.com/5980033/223338439-7a6f031a-93d9-47a1-a6cf-8d3892b73bae.png)

**Comment by MarcusDenker** [comment]
PR ws merged
