### ISSUE TITLE
How can we change the state of an inspected object

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#12911]
I have an object and I want to change the state of a specific instance variable for a specific object using the inspector (Yes I can do it with instVarPut:.... and friends) 
With old inspector we could do it just selecting the field typing a message or value and pressing accept. It would be nice to have this nice feature back.

I tried using an assignment or simply a value but none of the approaches worked.

![Capture 2023-03-06 at 18 59 11](https://user-images.githubusercontent.com/432549/223192698-4b12ccd3-2ad7-44db-a957-ceec2e0e342a.png)

![Capture 2023-03-06 at 19 00 31](https://user-images.githubusercontent.com/432549/223192777-4b5394f3-d571-4523-8338-951e949aa983.png)

**Comment by MarcusDenker** [comment]
the assignment works, the variable is just wrongly colored.

**Comment by MarcusDenker** [comment]
We have now two issues on the Newtools issue tracker:

- Inspector: Syntax highlighting of Variables is not correct in eval pane https://github.com/pharo-spec/NewTools/issues/503 
- [Improvement] Can edit inspect object vars directly in an inspector https://github.com/pharo-spec/NewTools/issues/501
