### ISSUE TITLE
[CI] full image load is broken

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#12926]
**Bug description**
Pharo11 build is broken (and with it the checking of all PRs on the CI)

```
MetacelloNotification: Loading -> Chest-tonel.1 --- github://pharo-spec/Chest:v0.4.2 --- cache
Error: Package Chest depends on the following classes:
  StPlaygroundInteractionModel
  StDebugger
  StDebuggerExtensionVisitor
  StDebuggerExtensionInspectorNodeBuilderVisitor
You must resolve these dependencies before you will be able to load these definitions: 
  ChestCodeScriptingInteractionModel
  ChestCodeScriptingInteractionModel>>#debugger:
  ChestCodeScriptingInteractionModel>>#addBinding:
  ChestCodeScriptingInteractionModel>>#addSelfAndThisContextBindings
  ChestCodeScriptingInteractionModel>>#bindingOf:
  ChestCodeScriptingInteractionModel>>#bindings
  ChestCodeScriptingInteractionModel>>#debugger:
  ChestCodeScriptingInteractionModel>>#hasBindingOf:
  ChestCodeScriptingInteractionModel>>#removeBinding:
  StDebugger>>#bindings
  StDebugger>>#interactionModel
  StDebuggerExtensionInspectorNodeBuilderVisitor>>#visitChest:
  StDebuggerExtensionVisitor>>#visitChest:
```

Maybe caused by https://github.com/pharo-spec/NewTools/pull/473

**Comment by adri09070** [comment]
Ok, Chest has dependencies to the debugger and I've put Chest in the debugger's group in `BaselineOfNewTools` in #473. It was working when I tried to reload NewTools in an image but this doesn't seem to work when the image needs to be built from scratch.

You can revert the PR but now, my question is : How can I load Chest inside `BaselineOfNewTools` ? I've tried so many things that haven't worked

**Comment by jecisc** [comment]
@adri09070 If Chest depends on NewTools I think that the simpler would be to either:
- Add Chest in NewTools
- Make Chest depends on NewTools and add it as a dependency of Pharo?

**Comment by MarcusDenker** [comment]
fixed by merging the revert
