### ISSUE TITLE
Broken ast method on compiled block 

### ISSUE THREAD

**Issue by privat** [guillep/pharo-core#12948]
**Bug description**

Specific combinations of block and global produce problematic CompiledBlock objects where the `ast` method does return a wrong node thus breaking others methods like `ir` and inspection (and possibly more).

It can be shown at least on latest Pharo11

**To Reproduce**

Run in a playground:

```st
| method block |
method := OpalCompiler new compile: 'foo Object. [ self ]. ^ #bar'.
block := method literals detect: #isCompiledBlock.
block ir
```

for some reason, `block ast` gives the return node (RBReturnNode `^#bar`) instead of the block node (RBBlockNode).

@MarcusDenker you might like this one :)

**Comment by MarcusDenker** [comment]
wow... I will check

**Comment by MarcusDenker** [comment]
This is a fun one.

So, the problem is the Variable read that is not used. We do not push and pop,
but instead just add the literal using #addLiteral: to the methodBuilder

OCASTTranslatorForEffect>>#visitVariableNode:

```
visitVariableNode: aVariableNode
	"when visiting a variable for effect, we could push it and then pop it, but we do nothing"
	| variable |
	variable := aVariableNode variable.
	(variable isLiteralVariable or: [ variable isUndeclaredVariable ])
		ifTrue: [ methodBuilder addLiteral: variable ]
```

Normally no problem... until you decompile and recompile. As there is no push/pop for "Object", the decompiler will create a method that has one literal less. 

So how comes the decompiler into the picture? Due to the odd model of CompiledMethod that stores a pointer to the changes/sources file, the compiler can not create methods with source, that is done on installation. (yes, bad).

So your method is source-less, but getting the IR needs the AST which needs the source. And so we do a second compilation, with the literal missing, which messes up the initialPC of the method. So all the bytecode offsets of our mapping is wrong, we find the wrong AST node for the pc of the block.

**Comment by MarcusDenker** [comment]
Personally, I do not like relying on the decompiler for anything... I would prefer a system where a high-level representation code is persistent. 

So what can we do now? We could change the compiler to emit code for the push/pop:

```
visitVariableNode: aVariableNode
	super visitVariableNode: aVariableNode.
	methodBuilder popTop
```

fixes the problem.

Another thing we could do: the compiler could always store the source in a method, and installation would remove it. This could be unified with the fact that we already store the code if we create DoIT methods (the methods compiled for eval). There the code is stored in the compiledMethodTrailer...

Yes, the CompiledMethod format is just one insane insanity...

**Comment by privat** [comment]
Bedside inspection bug, could it affects other components? the debugger for instance?

An alternative fix could be to emit 2 noop but push/pop should be as most as efficient. And I'm not sure it make sense to optimize unlikely code with critiques at the first place.
In fact, these kind of naive optimizations might be the responsibility of the VM that has more latitude to perform combined and aggressive optimizations.

Having to decompile is insane insanity as you say. Keeping the source code (not as cache but as real data) for floating uninstalled CompiledMethod seems a good idea.

I still have questions about the PC of methods and how source code of installed methods are stored in the source file (this seem fragile) but this issue is not the place:)

**Comment by MarcusDenker** [comment]
> Bedside inspection bug, could it affects other components? the debugger for instance?
> 

As long as you have .source/.changes available, there is no problem for normal use.

> An alternative fix could be to emit 2 noop but push/pop should be as most as efficient. And I'm not sure it make sense to optimize unlikely code with critiques at the first place. In fact, these kind of naive optimizations might be the responsibility of the VM that has more latitude to perform combined and aggressive optimizations.
> 

Yes, I will remove the optimization, it is the wrong level.

> Having to decompile is insane insanity as you say. Keeping the source code (not as cache but as real data) for floating uninstalled CompiledMethod seems a good idea.
> 
Yes, and I always wonder: do we really have to support running without .sources?

This is in the end another "Dogma", ... and this kind of clashes fundamentally with the dogma that the AST and the Compiler and Decompiler have to be optional...

> I still have questions about the PC of methods and how source code of installed methods are stored in the source file (this seem fragile) but this issue is not the place:)

Yes, I will write some notes about this for you

**Comment by jecisc** [comment]
I am not sure about what I will say so this needs verifications. But I think that oif you launch multiple time the same Pharo image on windows, only the first one has the rights to manage the source file. 
So, if we make the source file mandatory, maybe we might not be able to run multiple time the same image (which would be bad when we have a Seaside app for example and we want load balancing. Or if we want to parallelize a task and run multiple images on chunks)

**Comment by MarcusDenker** [comment]
On linux and mac, you can just run multiple images and I think it will just happily write to the .changes from both, potentially leading to very very bad effects...

What I mean is that we need to improve all this, it is broken on so many levels.

And the solution should not rely on the Dogma of "but we have to support running without sources" unquestioned.
