### ISSUE TITLE
Auto completion fail to complete if next character is not a blank

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#12972]
I had a method that was just `Float machineEpsilon` and I had my cursor right before the F oh Float. 

I wanted to add an assignation and used the autocomplete to complete my instance variable. The result tried to complete over "Float". 

Actual:

```
machiFloatcision  machineEpsilon
```

Expected:

```
machinePrecision Float machineEpsilon
```

![Mar-10-2023 13-41-53](https://user-images.githubusercontent.com/9519971/224319365-7d114da3-ac28-4a5c-96cd-4068e0dcf421.gif)

**Comment by MarcusDenker** [comment]
maybe related to https://github.com/pharo-project/pharo/pull/12570

**Comment by privat** [comment]
Does #13625 solve it for you?

**Comment by jecisc** [comment]
Yes thank you!
