### ISSUE TITLE
history displays meta class method instead of instance method

### ISSUE THREAD

**Issue by j-brant** [guillep/pharo-core#12999]
Viewing history of an instance method can show the history of the class method if one exists with the same selector.

**To Reproduce**
Find a class that has both instance and class methods with the same selector. Here I picked `SmaCCScanner>>initialize` which has a class side `#initialize` method: 
![image](https://user-images.githubusercontent.com/16563825/224998328-dd897579-c711-4306-a54e-6f7a49495d69.png)

**Version information:**
 - Pharo Version: Both 10 & 11

The `#definitionFor:path:commit:` methods need to compare the `classIsMeta` in addition to the selector: 
```
each selector = aMethod selector
						and: [ each classIsMeta = aMethod methodClass isClassSide ]
```
I tested on the IceLibgitTonelLog method, but IceLibgitFiletreeLog has most of the same logic and likely needs the same fix.

This was originally reported in https://github.com/feenkcom/gtoolkit/issues/3136.

**Comment by hellerve** [comment]
I was able to fix this in gt4git by overriding `IceLibgitFiletreeLog>>#definitionFor:path:commit:` and `IceLibgitTonelLog>>#definitionFor:path:commit:` as a temporary fix in https://github.com/feenkcom/gt4git/commit/dc6e9b23e7085c06ea5e08e7adbbf9d2a1ce7773.

I can add a PR to port this to Pharo if desired.

**Comment by Ducasse** [comment]
Hi please send a PR in the Iceberg repository else it will take more time to get it fixed.

**Comment by hellerve** [comment]
Will do, thanks!
