### ISSUE TITLE
ZnBufferedWriteStream string handling inconsistency

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#12990]
**Bug description**
ZnBufferedWriteStream has inconsistent API when constructed over binary stream but working with text. It allows writing of (byte) strings but fails on own messages like `cr`. 

**To Reproduce**
Steps to reproduce the behavior, evaluate: 
```smalltalk
f := FileSystem memory / 'file.bin'.
ws := f binaryWriteStream.
ws nextPutAll: 'a test string'; cr.
```
-> `Error: Improper store into indexable object ` inside `cr` call

**Expected behavior**
This  is not really correct usage but it may be confusing. If the `ZnBufferedWriteStream` does not allow string related messages like `cr` for all its usage cases, it should probably not implement them at all or handle correctly depending if it is onstructed over binary stream or not.

**Version information:**
Pharo 11.0.0
Build information: Pharo-11.0.0+build.610.sha.0067e2171fd12f7ab27b2f3850475d086f2b6188 (64 Bit)

**Comment by svenvc** [comment]
Hmm, yes and no.

Yes, you are right, this is confusing. But, no, there are many stream classes that implement both character and binary messages that will only work in certain cases, depending on the underlying collection. It has always been like that.

The base problem is illustrated as follows:
```
#[ 0 1 2 3 4 5 6 7 8 9 ] copy replaceFrom: 1 to: 3 with: 'ABC' startingAt: 1.

'ABCDEFGHI' copy replaceFrom: 1 to: 3 with: #[ 0 1 2 ] startingAt: 1.

#[ 0 1 2 ] copy at: 2 put: $A.

'ABC' copy at: 2 put: 0.
```
The first two expression succeed, while the last two fail.

So at the lowest level there already is a problem. If this "bivalent" behaviour between strings and byte arrays (which is technically wrong in most cases, BTW) in #replaceFrom:to:with:startingAt: would not be there, your example (which is wrong usage as you indicate yourself) would fail for both messages.

I don't known if this needs fixing, it could be done, but I don't like artificial type tests and prefer to let things fail.

**Comment by pavel-krivanek** [comment]
I'll close it for now then
