### ISSUE TITLE
[Meta-issue] undeclared variables

### ISSUE THREAD

**Issue by privat** [guillep/pharo-core#13006]
Undeclared variable is the possibility to have a variable "temporarily" bound to nothing at (method-)compile time, then be automatically repaired when the real variable appears (with or without the need of a compiler according to what kind of variable appears). The thing is complex and low-level, have a lot of drawbacks and surprising semantic and some fragile policy to limit the user ability to shoot themself in the foot.

See discussion in #12935 for more explanation and impacts

## Disclaimer

While UX is important, tooling and presentation are out of scope of the issue.
The focuses are on the specification of the language (including good practices), and compiler code (frontend and backend) to enforce and implement.

## Simple summary

Current behavior (rough explanation because I'm not even sure to not miss things) is that undeclared symbols might be bound to one of those

* Compilation error. Only in interactive code editors. There is still the possibility to keep the variable undeclared for those that starts with an uppercase (heuristic) when the "undeclared" menu appears
* Registered undeclared variables that act like globals (system-wide read-write shared variable) that lead to poor bugs, side effects and programmer incomprehension. They live in a global dictionary called `Undeclared`.
* ~~Unregistered undeclared variables (totally unshared) where each variable is bound to a single usage (i.e. a single read or a single store). Basically, they that act like black hole sinks where you can put everything or infinite source of nil where you can only read nil. This leads to more programmer incomprehension, but at last, have limited side effects :)
  It seems that there exists only for situations for front-end only compilation (highlighting for instance) where you do not want to fill `Undeclared` with garbage, but the API that activate/deactivate this is bad. see #12883 for general rants~~ fixed in #13007
* Workspace variables (only in the workspace, and maybe some DoIt related evaluation). Displayed as red (undeclared) until a first execution, but it's a distinct issue.

The choice of one or the other of these behaviors is mostly circumstantial and depend on the tool, its configuration and the system configuration... (but weather humidity seems ruled out)

## Possible solutions

Not mutually exclusives, and include solution that do not work (or very badly) for reference and discussion.

### Stop registering undeclared variables

  * **will not do** tried in initial version #12935
  * pro: clean and simple
  * con: break package loading and bootstrap.
  * con: break variable removal and reparation.

### Policy based on the capitalization of the name

  * **will not do**
  * Explanation: only capitalized undeclared variables are globally shared (working version of #12935)
  * pro: works
  * con: new random rule
  * con: do not solve the problem (just hide it better)

### Do not share registered declared variables

  * **will not do**
  * Explanation: multiple independent undeclared registered variables could exist with the same name, and all are repaired at once (to all become the same global, for instance)
  * Technical explanation `Undeclared` become a dictionary of collections
  * pro: feels somewhat compatible with current approach with far less world-wide side effects
  * pro: undeclared variables might be easily used as unshared temporary variables (in doit or small scripts for instance)
  * con: undeclared variables might be badly used as unshared temporary variables (but could be prevented by interactive compiler)
  * con: reparation on badly used undeclared variables might cause weird bug and programmer incomprehension
  * con: not yet implemented (so just an idea for now)
  * con: complex to implement (I tried)

### Disable writing to undeclared variables at runtime-time

 * [x] Done #13201

### Disable writing to undeclared variables at compile-time

  * [x] done #13280 & #13286
  * Failed attempts cf #12994 & #13244 
  * pro: might alleviate most cases
  * con: feels only partial: what about reading? What about global variables that become undeclared and might already have compiled writes in some RuntimeMethods ?

### Disable reading of undeclared variables at compile-time

 * [x] (done see above)
 * seems to break important things. #13172
 * so, you need the permitFaulty mode
 * or maybe a lesser faultymode?

### Disable reading of undeclared variables at runtime-time

  * [x] Done #13238

### Declare globals somewhere?

  * [ ] ?
  * Explanation: unlike temps, ivars or shared, globals do not have to be declared except by manually putting some key in some dictionary at runtime.
  * Possiblity1 asks to declare globals during class creation (and before compiling its method). Either on class-side initialize, or new setter in the fluid syntax. So methods can have read-write access to these known global
  * Possibility2, asks to declare globals at the baseline-level. It can works: #13236
 
### Register `Undeclared` at backend

* [x] Done! #13007
* So that same code path works for registered/non-registered and do not depend on complex configuration site-effects

## Related Issues&PR

* #9954
* #11903

**Comment by privat** [comment]
@MarcusDenker opened a metabug because I might close the failing PR

**Comment by MarcusDenker** [comment]
Yes, good sumary.

Maybe two properties that are interesting (which is already mentioned, but just to stress:)

1) only globals are a problem
- only globals/classvars/pool vars (the capitalized by convention ones) are updated without recompile
- for temps and ivars, we always recompile the methods to "fix" the vars

So if we would "late bind" globals (access by name from the environment they are from), things would get much simpler.
This would be the "best" solution. E.g. the JIT could do that optimization easily...

Maybe an intermediate step:

2) I always waned to explore if the Variable meta-object can play a role. We could for example late-bind Undeclared (as a message send to the Undeclared variable). This would be fixable even for methods on the stack as the Variable instance would be in the literal frame, thus we could exchange the Undeclated with e.g. a Globa var instance. We only would pay the price of the indirection, which if the compiler is present can be fixed by recompile.


More Random ideas: 

3) We should maybe re-think the dogma that "it has to work without the compiler".

4) We should look into on-stack replacement again? The kind of difference in a recompiled method should be of the kind that we could find the new pc and swap the method

**Comment by privat** [comment]
> 1. only globals are a problem

yes, and the majority of *Undeclared* users are for classes, thus non-writable globals.
So I'm not closing the door to radical specification change if others use cases (non classes) can be converted to something saner with a different behavior (possibly more aggressive and more consistent) on undeclared.

> 3. We should maybe re-think the dogma that "it has to work without the compiler".
> 4. We should look into on-stack replacement again?

Yep, we could simplify everything and just always recompile, i'ts already what is done with ivars, so not a *new* thing.

On-stack replacement is still a non-trivial issue.
However, I'm not sure how (bad) in practice that currenlty (mis-)works with ivars.
Because there could be receivers and methods in the stack, and ivars alterations also affect instances (not just methods).
So this seems to be potentially awful (and fragile and without any "good" solution).
Undeclared variables with globals and literals seem *trivial* in comparison :)

A real issue might be the early bootstrap because there is not enough content to do too much fancy stuff, but there are a lot of undeclared variables.

**Comment by privat** [comment]
I think the job is globally done. Both statically and dynamically.
What is missing might be a way to declare global, but it's an independent adventure
