### ISSUE TITLE
'Find & Replace' broken for some characters

### ISSUE THREAD

**Issue by privat** [guillep/pharo-core#13001]
**Bug description**

The Find & Replace is broken for some characters like `|` or `.`.
It could be related to a bad interpretation of regex, since these characters are meaningful in regex.

Note that escaping the characters `\|` or `\.` or protecting in character classes `[|]` or `[.]` does achieve nothing/
Also note that checking or unchecking the "Regular expression" do not seem to have any effect.

**To Reproduce**

Search for `|` or `.` or any string containing them in a text that have them (or not).

![Capture d’écran du 2023-03-14 08-34-21](https://user-images.githubusercontent.com/135828/225003969-65f30653-1db9-4a7f-b707-880929188f16.png)

**Comment by pavel-krivanek** [comment]
`FindReplaceService>>#findRegex` is not testing `self isRegex` at any place, it always generates a regular expression

**Comment by pavel-krivanek** [comment]
no, I'm wrong, the string is escaped if it is not supposed to be a regex in `FindReplaceService>>#convertedFindString`, these two characters are just missing
