### ISSUE TITLE
Syntax Error while copying code

### ISSUE THREAD

**Issue by maxwills** [guillep/pharo-core#13027]
**Bug description**
When copying from a code editor, if the code is faulty, the system shows a Syntax Error dialog instead of putting the selected text in the clipboard.
is it a bug or a feature? either way, it's annoying.

**To Reproduce**
1. Any method in the system browser.
2. In the  method code area, write any text that don't compile, such as: '1 this should not be accepted'.
3. Select the text, or part of the text and try to copy via hotkeys or context menu.
4. See error: A Syntax Error dialog appears.

**Expected behavior**
The selected code is copied and not judged.

**Version information:**
 - Pharo 11

**Expected development cost**
I'm pushing a PR now for this. However, if that behavior was expected or linked to other smart feature, it will probably be broken, so please check.

**Comment by MarcusDenker** [comment]
fix: https://github.com/pharo-project/pharo/pull/13026
