### ISSUE TITLE
Documentation Browser: crash on fresh installation

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#13032]
The MicDocumentBrowser crashes when opening with a directory does not exist exception.

To reproduce:
- use PharoLauncher as of today and download a fresh Pharo 11 as of today
- start the image - (usually this means there is no "iceberg" folder in "pharo-local" subfolder yet)

<img width="734" alt="image" src="https://user-images.githubusercontent.com/5980033/225752947-706a00f8-11c2-4be4-8c3f-9ccaffda265d.png">

**Comment by astares** [comment]
an #ensureCreateDirectory could solve the problem.

**Comment by demarey** [comment]
fixed in https://github.com/pharo-spec/NewTools-DocumentBrowser/commit/4e815aba17d2cf049e48800661d00aa7eddf909d
