### ISSUE TITLE
Documentation: key not found issue on Announcements tutorial

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#13033]
Open Microdown document browser in Pharo 11 and check for the **Announcements** and then **Tutorial**

<img width="876" alt="image" src="https://user-images.githubusercontent.com/5980033/225753753-aaa05f89-7eb6-4d01-bffa-4736cdffbe42.png">

**Comment by jecisc** [comment]
I have a pending PR for this: https://github.com/pillar-markup/Microdown/pull/648/files

<blockquote><img src="https://avatars.githubusercontent.com/u/9519971?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pillar-markup/Microdown/pull/648">Some styles were updated in Pharo. This updates Microdown by jecisc · Pull Request #648 · pillar-markup/Microdown</a></strong></div><div>Microdown is a cleaned and simpler markdown but with more powerful features such as extensions. - Some styles were updated in Pharo. This updates Microdown by jecisc · Pull Request #648 · pillar-markup/Microdown</div></blockquote>

**Comment by MarcusDenker** [comment]
Pr was merged
