### ISSUE TITLE
RPackageOrganizer>>#basicUnregisterPackage: and #basicUnregisterPackageNamed: have different behaviors

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13039]
When looking at those methods we can see some duplication and that they do not do exactly the same thing with the package to unregister.

I have the impression that basicUnregisterPackage: should just be:

```st
basicUnregisterPackage: aPackage 
    ^ self basicUnregisterPackageNamed: aPackage name
```

**Comment by MarcusDenker** [comment]
pr was merged
