### ISSUE TITLE
Bootstrap: Instance of RGInstanceVariableSlot did not understand #allowsShadowing

### ISSUE THREAD

**Issue by privat** [guillep/pharo-core#13043]
**Bug description**

Bootstrap might show this unhelpful message:

```
    [+] Preparing bootstrap
Instance of RGInstanceVariableSlot did not understand #allowsShadowing
RGInstanceVariableSlot(Object)>>doesNotUnderstand: #allowsShadowing
OCASTSemanticAnalyzer>>declareVariableNode:as:
OCASTSemanticAnalyzer>>declareTemporaryNode:
[...]
```

The bug is caused if a (long time existing) temporary variable is shadowing a newly introduced ivar for instance.
(I had to bisect then remove lines in the offending commit one by one, then think that *allowsShadowing* might be related to a shadowing issue)

example https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-13042/1/pipeline/20/

**To Reproduce**
1. shadow a variable in the compiler
2. run `bootstrap/scripts/3-prepare.sh`

**Expected behavior**
A better error message

**Comment by MarcusDenker** [comment]
#allowsShadowing is implemented on RGInstanceVariableSlot

maybe the bootstrap somehow uses an old version of Ring.

**Comment by MarcusDenker** [comment]
This will be fixed when we use a newer version for the bootrap
