### ISSUE TITLE
AthensCairoSurface not being deallocated

### ISSUE THREAD

**Issue by StewMacLean** [guillep/pharo-core#13053]
Within AthensCairoSurface>>finializeResourceData:

finding the registered surface always fails, consequently the method returns before deallocating resources:

(self findSurface: id) = handle value ifFalse: [ 
		"self error: 'surface is not registered with surface plugin'."
		^ self ].

**To Reproduce**
1. Open Activity Monitor and locate Pharo
2. Observe the current memory size
3. Execute 10000 timesRepeat: [AthensCairoSurface extent: 512 @ 512].
4. Observe that the memory usage increases significantly!

**Expected behavior**
Memory usage should remain relatively constant

**Version information:**
 - OS: macOS
 - Version: 12.0.1
 - Pharo Version 10

**Expected development cost**
Commenting out the return prevents memory bloat, but doesn't fix the underlying problem with registration. As this involves a primitive within the SurfacePlugin, I'm not sure how easy it is to fix.

**Comment by tinchodias** [comment]
Hello @StewMacLean 

I tried this modification to that method and didn't have problems. Did you try any other solution?
```
finalizeResourceData: data
	"Finalize external state"

	| handle id contextHandle |
	handle := data first.
	id := data second.
	contextHandle := data third.
	
	(self findSurface: id) = handle value ifTrue: [
		self unregisterSurfaceWithId: id ].

	self destroyContextHandle: contextHandle value.
	self destroySurfaceHandle: handle value
```

I worked on Alexandrie, a reimplementation of FFI bindings to Cairo which doesn't use the surface plugin, so I have some related experience but not enough to be sure of this modification as a fix.

**Comment by StewMacLean** [comment]
Hi Martin,

Thanks for your reply.

The problem is that the "(self findSurface: id) = handle value" expression
never evaluates to true. Your change will cause the method not to return
and consequently deallocate, but it doesn't unregister the surface. You can
see a trace below showing the values are different.

This causes a memory leak, that I discovered using the MacOS instruments.
Please see the screenshot below.

Unfortunately, this is in primitive land, which is beyond my realm of
expertise!

Hope this helps.

Cheers,

Stewart


>> 14:01:17:919.534 | WeakArray Finalization Process | found: 862005584

>> 14:01:17:919.546 | WeakArray Finalization Process | handle value
5156972880

>> 14:01:17:919.559 | WeakArray Finalization Process | found: 1130506288

>> 14:01:17:919.568 | WeakArray Finalization Process | handle value
5425473584

>> 14:01:17:919.580 | WeakArray Finalization Process | found: 861973040

>> 14:01:17:919.589 | WeakArray Finalization Process | handle value
5156940336

>> 14:01:17:919.623 | WeakArray Finalization Process | found: 861983696

>> 14:01:17:919.633 | WeakArray Finalization Process | handle value
5156950992

>> 14:01:17:919.671 | WeakArray Finalization Process | found: 1130517216

>> 14:01:17:919.680 | WeakArray Finalization Process | handle value
5425484512

>> 14:01:17:919.704 | WeakArray Finalization Process | found: 861968336

>> 14:01:17:919.793 | WeakArray Finalization Process | handle value
5156935632

>> 14:01:17:919.833 | WeakArray Finalization Process | found: 861971696

>> 14:01:17:919.844 | WeakArray Finalization Process | handle value
5156938992

**Comment by tinchodias** [comment]
Thanks.
So, apparently for your observations the plugin's surface needs tu be unregistered by `unregisterSurfaceWithId:` independently from the Cairo API's [destroy](https://www.cairographics.org/manual/cairo-cairo-surface-t.html#cairo-surface-destroy).

**Comment by StewMacLean** [comment]
Hi Martin,

I don't fully understand the surface mechanics, but judging from the
empirical results, the surface needs to be unregistered as well as the
Cairo destroy as you mention.

This seems to be the method's intent, but it is failing to find the surface
using the given id for some reason buried in the VM.

Cheers,

Stewart

**Comment by MarcusDenker** [comment]
PR was merged
