### ISSUE TITLE
Changes Browser doesn't file in by item index order

### ISSUE THREAD

**Issue by StewMacLean** [guillep/pharo-core#13064]
ExternalChangesBrowser>>buildMenu

	"15th January 2022 Stewart MacLean
	Change to file in selected items sorted by their index."

	| aMenu |

	aMenu := self newMenu.

	aMenu 	addItem: [ :item | 
			item
				name: 'File in all selected';
				action: [ self fileIn: changes selectedItemsSorted "selectedItems" ] ].

	aMenu 	addItem: [ :item | 
			item
				name:  'Compare method to current';
				enabled: [ self canCompareToCurrent ];
				action: [ self compareToCurrent: changes selectedItem ] ].

	^ aMenu

**Comment by jecisc** [comment]
The change browser has been removed in favor of Epicea now.
