### ISSUE TITLE
[Pharo 12] Zeroconf: image missing

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#13090]
**Bug description**
The image is missing

```
 curl https://get.pharo.org/120+vm | bash 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3046  100  3046    0     0  23930      0 --:--:-- --:--:-- --:--:-- 24967
Downloading the latest 120 Image:
    http://files.pharo.org/get-files/120/pharoImage-arm64.zip
[image.lvgbN0/image.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of image.lvgbN0/image.zip or
        image.lvgbN0/image.zip.zip, and cannot find image.lvgbN0/image.zip.ZIP, period.
```

**Comment by astares** [comment]
Strange: looks like last week the entries for Pharo 12 had been added:
https://github.com/pharo-project/pharo-zeroconf/tree/master/generated

![image](https://user-images.githubusercontent.com/5980033/227237330-c0bb7f85-3bb7-4064-b171-39b399bd8763.png)

Stilll it is not possible to use them
 
![image](https://user-images.githubusercontent.com/5980033/227238386-e3b26076-5833-4efd-846c-d02b56c68dd4.png)

**Comment by astares** [comment]
File "pharoImage-x86_64.zip" is still missing for Pharo 12 when I compare to Pharo 11:

![image](https://user-images.githubusercontent.com/5980033/227240311-1da5f425-a449-4120-af13-b5bfd72430b3.png)

**Comment by MarcusDenker** [comment]
There was a symlink missing, I added it

stable-64.zip -> latest-64.zip

**Comment by astares** [comment]
Great thanks!
