### ISSUE TITLE
Activate verbosity in 3-prepare.sh

### ISSUE THREAD

**Issue by privat** [guillep/pharo-core#13113]
3-prepare.sh is slow (cf #13014).

It has some log mechanism that are nor enabled for some reason. https://github.com/pharo-project/pharo/blob/Pharo11/bootstrap/src/Pharo30Bootstrap/PBBootstrap30.class.st#L252

Enabling them will feel like it's less slow :)

**Comment by privat** [comment]
@jecisc since you are playing with time and boostrap...

**Comment by jecisc** [comment]
My next step was to look for a bug in the bootstrap that I'm hitting with one of the change I want to do in Pharo (to get faster symbol creation and search!)
But I added that to my todo list :)

**Comment by jecisc** [comment]
I did it 2 weeks ago
