### ISSUE TITLE
selection in Microdown with skew edges

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#13126]
**Bug description**
The highlighting of a selection has skew edges when it starts includes a code block

![image](https://user-images.githubusercontent.com/572494/227245127-3db5e2ca-46c6-4220-b9d9-3d42e33a9a22.png)

**To Reproduce**
1. Open Documentation Browser
2. Go to .../doc/RefactoringEngine/3-ScriptingRefactorings.md
3. do the selection with start and and as shown in the screenshot (beginning of a code bloc)
4. skew selection edges

It is reproducible on similar places as well

**Comment by akevalion** [comment]
This is related in the use of RubPrimarySelectionMorph
