### ISSUE TITLE
RBParser does not manage correctly error nodes leading to a SubscriptOutOfBounds error

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#13122]
**Bug description**
Displaying of Pharo11/doc/RefactoringEngine/4-RefactoringEngineFoundation.md causes RBParser related `SubscriptOutOfBounds` error

**To Reproduce**
1. open Document Browser
2. go to document Pharo11/doc/RefactoringEngine/4-RefactoringEngineFoundation.md
3. error

**Comment by demarey** [comment]
It is a parsing error of a code snippet defined in the document.
It is not directly related to DocumentBrowser but rather on RBParser not managing well error nodes.

**Comment by privat** [comment]
I will look at it. Pharo11 or Pharo12?

**Comment by pavel-krivanek** [comment]
Pharo 11
one part of the problem is that it tries to interpret all fixed sized blocks as a Smalltalk code.

**Comment by privat** [comment]
Nice bug! It's related to some recent change in the parser. I will try to get a fix (btw, Pharo12 is also impacted)
