### ISSUE TITLE
[Feature Request] New warning: Empty temporary declaration

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13139]
In Calypso it would be nice to have a warning "Empty temporary declaration" if we write " |  | " in our code without adding any variable inside.

**Comment by jordanmontt** [comment]
I personally think that Calypso has already too many warning and rules. It feels really intrusive and makes people to ignore all the warnings

**Comment by Ducasse** [comment]
I wanted to have profiles so that we do not have to have a single list of analyses

**Comment by privat** [comment]
I do not sure if it's useful to have too much visual feedback, especially on things that could be repaired with a simple reformatting. Superfluous `.`, `|`, `()`, etc. are removed by formatting (by default): do we also want a visual feedback on each one?
Moreover, formatting is often a highly personal choice. I'm not ready to start such a battle with users.

What should be done, however, is to highlight `|` differently if it's used structurally (to declare temps or separate block parameters) or as a character of a binary operator. For instance, we could color structural `|` with the same color level than the corresponding `[]` so we can see which one belong to which one.

**Comment by jecisc** [comment]
I see. I agree that this is not useful in the end.
