### ISSUE TITLE
`timesRepeat:` does not work on nested loops

### ISSUE THREAD

**Issue by jordanmontt** [guillep/pharo-core#13141]
If you use two nested`timesRepeat:`, one inside the other, the first loop it is only executed once. For example in the following code:

```st
5 timesRepeat: [ 
    IceTipRepositoriesBrowser new open.
    Transcript crShow: 'Opened'.
    10  timesRepeat: [ 
        Transcript crShow: 'Rendering'.
        WorldMorph doOneCycle ] ]
```

The expected behavior is to open 5 times iceberg and render each of them 10 times. What it happens is that Iceberg is opened only 1 time and rendered 10 times. If you change the second `timesRepeat:` for a `1 to: 10 do:` it works as expected. 

```st
5 timesRepeat: [ 
    IceTipRepositoriesBrowser new open.
    Transcript crShow: 'Opened'.
    1 to: 10  do: [ :e | 
        Transcript crShow: 'Rendering'.
        WorldMorph doOneCycle ] ]
```

**Comment by svenvc** [comment]
Wow, that is very bad. I can confirm:
```
3 timesRepeat: [ 
  #outer traceCr.
  4 timesRepeat: [ 
    #inner traceCr ] ].
```
Gives:
```
outer
inner
inner
inner
inner
```
in Pharo 11.

**Comment by privat** [comment]
It seems caused by inline timeRepeat: . Disable it in the general setting if you want a more precise amount of loops

**Comment by jecisc** [comment]
On thing to be careful about is that I think this test will hit the time limit after this is fixed: FLGZippedBasicSerializationTest>>#testWideString

**Comment by jordanmontt** [comment]
Oh yes indeed! the test `FLGZippedBasicSerializationTest>>#testWideString` is actually not testing what it should :)

**Comment by jordanmontt** [comment]
> It seems caused by inline timeRepeat: . Disable it in the general setting if you want a more precise amount of loops

Yes, it looks that the problem is because of the inline. But i don't want to deactivate it because I like to have that optimized version.

**Comment by jecisc** [comment]
But it takes 9 seconds to run already. I'm afraid the time will explode with this fix.
I wonder if we could not just export a wide stream with all possible characters tested here? But I don't know Fuel enough to know what is really tested

**Comment by jordanmontt** [comment]
I don't about Fuel that it can be good also to have this timeout because it can help to detect performance issues. For example: https://github.com/theseion/Fuel/issues/269

**Comment by svenvc** [comment]
Thanks for such a fast turnaround, great work !

**Comment by jordanmontt** [comment]
Yes, thanks @tesonep :)
