### ISSUE TITLE
Coding flow should be degraded in Pharo12

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#13193]
We should be able to define 
- a method or a class in the class pane
- a method or a class in the method pane

This is SUPER IMPORTANT that new version of Pharo do not break to coding flow and 
even if we get a try catch or something like that.

End users are IMPORTANT!

**Comment by MarcusDenker** [comment]
- "a method or a class in the method pane" is not supported in Pharo11, I think it never was as the method pane would need to evaluate the class definition, which is just does not do

- that it does not work in the class side was done in PR https://github.com/pharo-project/pharo/pull/12981

**Comment by MarcusDenker** [comment]
related to https://github.com/pharo-project/pharo/issues/7468

**Comment by MarcusDenker** [comment]
Never issue was reported, I close this one (see #13884)
