### ISSUE TITLE
Can not load pharo project branch pharo11 in pharo 12 image

### ISSUE THREAD

**Issue by akevalion** [guillep/pharo-core#13220]
**Bug description**
Users can not load pharo branch `pharo11` in a pharo 12 image.

**To Reproduce**
1. Fork a pharo, in my case https://github.com/akevalion/pharo
2. Download a pharo12 image 
3. Open iceberg
4. Click on `+ Add` button
5. Select remote repository, enter the url of your repo in my case https://github.com/akevalion/pharo
6. Then click in `ok`. This will load the repository.
7. Wait a minute or take a cup of coffee.
8. After the loading process. Iceberg shows: 
<img width="589" alt="image" src="https://user-images.githubusercontent.com/10532890/229115410-b190ea09-71d6-459b-ae15-21213da78fca.png">

9. Right click on the repo, then click on `Repair repository` -> `Checkout and existing branch ...` -> `ok`.
10. Select in sources window `Local` -> `pharo11` -> `ok`.
11. Preview checkout is presented 
<img width="796" alt="image" src="https://user-images.githubusercontent.com/10532890/229115925-9b9a19e4-43d5-4246-9fae-e175a9390d7a.png">
|
12. After click on `checkout` button we have a list of packages in my case close to 600 or 700 items.
<img width="394" alt="image" src="https://user-images.githubusercontent.com/10532890/229116076-8f6dd2d9-5645-41c8-800b-17d147a14bb7.png">

13. Because its really hard to select them all. press `ok`.
14. Wait for the checkout process
After that you have 
<img width="591" alt="image" src="https://user-images.githubusercontent.com/10532890/229116518-0c6509b6-9947-47aa-8e9f-208ec6e38856.png">

15. Now open a method with some changes. In my case I use class `MouseClickState >> #handleEvent:from:`
16. The method contains the following code in the image
<img width="718" alt="image" src="https://user-images.githubusercontent.com/10532890/229116887-9e04ba28-4b66-4626-981e-33cff9a6af19.png">

17. Compare with the code we have in the fork of pharo11 https://github.com/akevalion/pharo/blob/Pharo11/src/Morphic-Base/MouseClickState.class.st
<img width="714" alt="image" src="https://user-images.githubusercontent.com/10532890/229117063-6446512c-af24-4ea6-afb6-05636ee09ad8.png">

18. Currently you can not load the last version of your code in pharo12.

**Expected behavior**
No matter the loading method users of pharo should be able to load their forks in pharo12.

**Version information:**
 - OS: mac
 - Version: ventura 13.2.1 (22D68)
 - Pharo 12 x64

**Comment by jecisc** [comment]
There has been a lot of changes between the two branches, lot of them in the kernel.
I don’t think it’s something archivable to be able to do that.

**Comment by MarcusDenker** [comment]
And many of our changes are of the kind that are not trivially loadable, but only can be bootstrapped.

**Comment by MarcusDenker** [comment]
Just look at this: we removed the ivar commentSourePointer from ClassOrganisation. For that we carefully change first all the code path to store that data in the ivar of ClassDescription, too. But what you now want to do is an "revert" of that in on step. There is no way that this can work... how would Git know that it should take the content of the ivar of ClassDescription and out it into the new (due to the revert) ivar in ClassOrganisation?

**Comment by akevalion** [comment]
After talk with Marcus we have this ideas
- users can not load branch pharo11 branch to pharo12 for now in nutshell.
- users have load pharo11 branch to pharo11 image.

**Comment by privat** [comment]
In a live system, foundation update is not always a simple thing.
But I think that automatic feedback on such breakages can help us to smooths things (a little) It's why I opened #13072
