### ISSUE TITLE
Class comments can get lost when commiting code

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13246]
I recently noticed that in different commits some of my class comments are vanishing. 

For now I don't know how this happens.

**Comment by privat** [comment]
I noticed the same behavior. I do not recall what I did with the classes that lost their comments.

**Comment by MarcusDenker** [comment]
This could related to moving the commentSourcePointer to ClassDescription, I will have a look

**Comment by privat** [comment]
I found a way to reproduce.

* Choose a class you like with a nice comment
* Go to the class definition panel
* Add an ivar, and accept
* Now the comment is dead in the class and in all its subclasses

**Comment by privat** [comment]
I now have a bunch of changes that are a pain to commit because a lot of class comments are lost :(
Maybe I will commit them as is and try to recover the lost comments with command-line git-fu

**Comment by MarcusDenker** [comment]
I am working on fixing this
