### ISSUE TITLE
Calypso: Comment pane management impact multiple calypso

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13254]
If you have two Calypso open, with both of them on a class comment, and you update the comment of one of them, then the other widow get impacted too. 

To reproduce:
- Open a Calypso on a first class
- Go on comment pane
- Open a second Calypso
- Go on comment pane
- Edit comment
- Save

Expected:

The first window should not be impacted at all

Actual: 

The first window switches from comment pane to class definition pane. WTF. 

![Apr-03-2023 13-31-32](https://user-images.githubusercontent.com/9519971/229497663-3bd31492-2d07-4f44-8c74-4ff97826cb15.gif)

**Comment by guillep** [comment]
Duplicates https://github.com/pharo-project/pharo/issues/16591
