### ISSUE TITLE
Bootstrap: We could probably remove the AST from the core of the bootstrap

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13285]
AST could probably be loaded later than in BaselineOfPharoBootstrap because to seems that nothing in the bootstrap depends on it

**Comment by jecisc** [comment]
In fact this is already in the Compiler group so there is nothing to do here

**Comment by privat** [comment]
If you need a compiler for the bootstrap (it's likely) then you need the AST.
The package does not seem to contain classes that can be moved to some sub-package
