### ISSUE TITLE
[CI] Win testrunner times out after 35min

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#13282]
**Bug description**
The test runner for Windows times out (35min) while running the tests.

Seen on both Pharo11 and Pharo12

**Comment by jecisc** [comment]
This might be the source: https://github.com/pharo-project/pharo/issues/13304

**Comment by jecisc** [comment]
I confirm that all other tests are running smoothly on my windows.

**Comment by MarcusDenker** [comment]
We could add, for now, a skip to testOneGBAllocation and testOneGWordAllocation

**Comment by jecisc** [comment]
I propose to close this issue related to the CI and keep #13304 open for the issue related to the VM problem
