### ISSUE TITLE
Playground not able to evaluate simple #timesRepeat:

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#13309]
**Bug description**
executing of `5 timesRepeat: [ Smalltalk garbageCollect  ]` in the Playground is causing `Instance of WorkspaceVariable did not understand #index:`

Note: everywhere else (Transcript, Calypso) this evaluation works.

**Version information:**
- Pharo 11.0.0
- Build information: Pharo-11.0.0+build.668.sha.660303e6c0a6b7d9709b670d89051d035d80c0b0 (64 Bit)

confirmed on Pharo 12 too

**Comment by pavel-krivanek** [comment]
introduced in build 653
probably by: https://github.com/pharo-project/pharo/pull/13154
@tesonep

**Comment by MarcusDenker** [comment]
Ah, yes, the shitty auto-creation of variables in the workspace...  lead to very odd workarounds. The synthezised var needs to start with "0" (this ensures, too, that this is a name that can never be define as a temp):


```
nextUniqueInlineID

	"The UniqueID has to be shared between the hierarchy of OCASTTranslators.
	The OCASTTranslator has inside one for Effect and one for value. They should share ID values."
	parentTranslator ifNotNil: [ ^ parentTranslator nextUniqueInlineID ].

	nextUniqueInlineID := nextUniqueInlineID + 1.
	^ '0', nextUniqueInlineID asString asSymbol
```

**Comment by pavel-krivanek** [comment]
Thank you, that fixes it

**Comment by privat** [comment]
* why synthetic temps can interfere with the workspace? One is middleend/backend and the other is frontend, theoretically they should not collide.
* 0 prefix feels hackish as hell. If we need temps that are not real temps, can a different class be used (or a subclass, or a flag `isSynthetic` in the instance)?

**Comment by astares** [comment]
@MarcusDenker @jecisc 

Do we need to create another PR against "Pharo12" branch once integrated or will there be another resynch of fixes done for P11 to P12 in one pass?

**Comment by MarcusDenker** [comment]
No, we merge once per week all Pharo 11 changes
