### ISSUE TITLE
AllocationTest opens native windows on Windows, probably because of an OutOfMemory

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13304]
Running tests in AllocationTest cause native windows to open.This might be the cause of Windows testing timeout on CI because the image freeze until we close the window.

![image](https://user-images.githubusercontent.com/9519971/230230045-7326ad05-69c3-4d99-b770-a890fbb756fa.png)

Operating System/Hardware
-------------------------
Win32 Win64 x86_64

Virtual Machine Commandline Options
-----------------------------------
#1	--headless

Virtual Machine
---------------
C:\Users\jecis\Documents\Pharo\vms\120-x64\Pharo.exe
CoInterpreter VMMaker-tonel.1 uuid: b0b89f1b-d3b4-0d00-9960-8ff10c267fe2 Apr  3 2023
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: b0b89f1b-d3b4-0d00-9960-8ff10c267fe2 Apr  3 2023
v10.0.2 - Commit: fdd3df06 - Date: 2023-03-31 17:24:30 +0200

Pharo 10.0.2 built on Apr  3 2023 18:54:17 Compiler: 4.2.1 Compatible Clang 8.0.1 (tags/RELEASE_801/final)
VMMaker versionString v10.0.2 - Commit: fdd3df06 - Date: 2023-03-31 17:24:30 +0200
CoInterpreter VMMaker-tonel.1 uuid: b0b89f1b-d3b4-0d00-9960-8ff10c267fe2 Apr  3 2023
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: b0b89f1b-d3b4-0d00-9960-8ff10c267fe2 Apr  3 2023

Image
-----
C:\Users\jecis\Documents\Pharo\images\Pharo 12.0 - 64bit (next development version, latest)\Pharo 12.0 - 64bit (next development version, latest).image
Pharo12.0.0
Build information: Pharo-12.0.0+build.119.sha.a8aec065bd6f6b2215154c0cf70dc6090815b41a (64 Bit)
Unnamed

Image Commandline Parameters
----------------------------
#0	--interactive

**Comment by jecisc** [comment]
Tests causing this error:
- testOneGBAllocation
- testOneGWordAllocation

I have the impression this is cause by the VM giving an OutOfMemory. Maybe this is cause by the new VM?

**Comment by astares** [comment]
Maybe a (legacy) call to MessageBox() to get some output for debugging purposes.

**Comment by MarcusDenker** [comment]
this was fixed
