### ISSUE TITLE
RBVariableNode with comment goes 1 character too far 

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13318]
I have a piece of code with a variable in parenthesis and a comment. When that happens, the RBVariableNode produced in the AST has a stop going one character too far as you can se here:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9519971/230359513-43ce29c9-4013-4a96-afd0-f1d707205b92.png">

I expect the close parenthesis not to be included in the variable node since the opening parenthesis is not.

Maybe this can interest @privat

**Comment by privat** [comment]
Interesting...

**Comment by privat** [comment]
The location on the node is off. I will look at that. I think there might be related issues for other kind of nodes.
