### ISSUE TITLE
[Feature Request] Switch default branch from Pharo11 to Pharo12

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#13337]
Should we switch the **default branch** for https://github.com/pharo-project/pharo from Pharo11 to Pharo12 already?

![image](https://user-images.githubusercontent.com/5980033/230487306-31b58166-cc6d-4dc1-9263-875f7e133fb5.png)

**Comment by demarey** [comment]
Hi @astares 
yes,  good idea!
I just did it.

**Comment by astares** [comment]
Thanks!
