### ISSUE TITLE
Compiler: Remove OCASTTranslator subclasses for effect/value

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#13330]
OCASTTranslator uses two sub-instances, depending if it visits for effect or for value. 
This in the end just is the difference of adding a pop or not.

We should check if this instead could be be implemented using an instance variable that models this state.

- Much simpler, less magic
- it simplifies subclassing --> the existing subclasses for Reflectivity can be simplified

**Comment by privat** [comment]
It could also be possible to keep `visit` only for value/expression and add `visitEffect` for effect/statement that just call `visit` then pop
