### ISSUE TITLE
Recompiling a method in the debugger raises an error

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#13357]
When I recompile a method I get the following 
<img width="464" alt="Capture 2023-04-08 at 21 10 42" src="https://user-images.githubusercontent.com/432549/230738799-d827affc-f07d-4511-b71e-8898b3ceeefb.png">

I do not know if this is this related to the debugger or not.

**Comment by privat** [comment]
I cannot reproduce. Which version?

**Comment by adri09070** [comment]
I think this is an error that only appears on Windows (and maybe Linux? I'm not sure) but not on Mac. I should debug this on my own machine

**Comment by MarcusDenker** [comment]
maybe same as https://github.com/pharo-project/pharo/issues/13724

**Comment by MarcusDenker** [comment]
I think we fixed this
