### ISSUE TITLE
Feature: deprecated class names

### ISSUE THREAD

**Issue by privat** [guillep/pharo-core#13365]
Deprecated classes have a `isDeprecated` class-side method (that defaults to the package, so moving a class to a deprecated package is enough), but there is no facility to deprecate just a class name. i.e no feature change, instances stay the same, etc.

A trick can be to have a deprecated named class as a subclass of a new named class, but there are still 2 classes that might cause issues:

* new will instantiate the bad one (so class methods must be added to finish the trick).
* `isKindOf: OldName` fails on the new named class (but the message is questionable).
* `on: OldName do:` won't catch new named exceptions.
* both class are not really linked together (it's an information that tools can use)

In the case of pure class renaming, I propose to just have additional entries in the global dictionary.
Such deprecated names can be identified when `assoc key ~= assoc value name` and styled accordingly.
Rules and automatic code rewritings (à la `#deprecated:transformWith:when:`) can also be added.

To install those names, the `initialize` class-side method could be used.
Maybe an additional property of the *fluid* class syntax can also be proposed. eg `deprecatedAliases`.

```st
Object << #MyClass
	slots: {};
	sharedVariables: {};
	deprecatedAliases: { #MyOldClass };
	package: ''
```

I'm not sure if there are other implications

**Comment by jecisc** [comment]
I really like this idea! 
We could also have a command in calypso that is “rename with deprecation” that would generate whatever is used to install the mechanism. 

I guess that if we have an additional entry in the system dictionary, then Browse It would bring to the new class even if we use the old name in our code.

**Comment by jecisc** [comment]
I might give it a shot in the next few weeks because I want te rename all classes of RPackage and I would like to have your idea of deprecations and maybe also give a try to the automatic rewrite.

**Comment by astares** [comment]
This might be really useful also for "renaming with deprecation" of "RBNode" and subclasses into "ASTNode" and subclasses.

Historically these classes are coming from RefactoringBrowser (therefore RB) - but as they represent nodes from the Abstract Syntax tree (AST) this name would be better. It would also better align with the package name "AST-Core" then.

**Comment by jecisc** [comment]
Yes!

I want to rename the AST classes for some months now but I'm restraining myself to not break everything. But if we have better deprecation supports then we can do it :)

**Comment by astares** [comment]
Yes - I made an attempt as well already in the past. See https://github.com/pharo-project/pharo/issues/10815

**Comment by privat** [comment]
In fact, renaming AST classes and the referenced issue was the initial need
