### ISSUE TITLE
extract return from Rectangle quickMerge

### ISSUE THREAD

**Issue by vonbecmann** [guillep/pharo-core#13370]
extract return from Rectangle>>#quickMerge: and use self class instead of Rectangle.

Pharo image: Pharo12.0.0#120141
Virtual machine used: CoInterpreter VMMaker-tonel.1 uuid: d65000bb-d2b4-0d00-9fdf-a6300fd32d39 Apr  3 2023
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: d65000bb-d2b4-0d00-9fdf-a6300fd32d39 Apr  3 2023
v10.0.2 - Commit: fdd3df0 - Date: 2023-03-31 17:24:30 +0200

Platform Name: unix
Class browser used (if applicable): ClyFullBrowserMorph

**Comment by Ducasse** [comment]
Pay attention that Rectangle x and self class x are not totally equivalent because the first one will never call subclass while the second does.

**Comment by Ducasse** [comment]
I'm not saying that changing is not worth but we should pay attention to that. Rectangle xxx could be compiled differently than self class xxx.

**Comment by vonbecmann** [comment]
i revert the  change. check the last commit.
