### ISSUE TITLE
Not possible to create a class with DebugDrivenDevelopment anymore

### ISSUE THREAD

**Issue by jordanmontt** [guillep/pharo-core#13391]
In Pharo 12 is not longer possible to execute code that has a not created class. For example, the class `SimpsonsEpisode` does not exist. If I evaluate

```st
SimpsonsEpisode season: 1 episode: 10
```

I have only a red popup that says me that the class doesn't exist but does NOT let me to create the class. The same happens in Calypso, Inspector, etc

<img width="408" alt="Capture d’écran 2023-04-11 à 15 00 37" src="https://user-images.githubusercontent.com/33934979/231170082-3de6cc59-04db-4431-8209-653226f9d010.png">

I always program like that to create classes, and methods.

**Comment by privat** [comment]
This is fixed in  #13323, but the PR is currently not nice because of workarounds for spec/newtools.
I can try to extract a quick fix for you only for this issue

**Comment by jordanmontt** [comment]
Hello @privat 
Nice! I didn't know about that PR. If the quick fix it is easy yes, please do it :)
If not we can wait until the PR is ready to be integrated, no problem
