### ISSUE TITLE
Automatic method categorization does not repsect superclass category

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#13413]
**Bug description**
When creating a method, the automatic assigning of a protocol ignores the superclass classification.

**To Reproduce**
1. go to class `AIBFS` (first package in the image, second class)
2. create empty method `addNodeFor: aModel`
3. this method has superclass implementation in the protocol `building - graph` but despite that, it is automatically added to the protocol named `adding`. 

The behavior is actually even more crazy for other cases: 
- when you first select a different protocol (like `accessing`) and create the method there, it is anyway automatically added to the protocol `adding`
- if you first create the protocol of the desired name (`building - graph`) and create the new method inside it, it gets anyway recategorized as `adding`. Moreover, the protocol `building - graph` is removed!

It does that for other method names where it guesses the protocol name like `isRunningTasks`.

**Version information:**
 Pharo 11.0.0
Build information: Pharo-11.0.0+build.672.sha.87a0f07f1706902298dd944d7f17a4f9611a0a21 (64 Bit)

**Comment by jecisc** [comment]
The method classifier has different way to find the right protocol for a method. 

Currently the protocol of the superclass is the last rule. IMO it should be the first. 

MethodClassifier>>#listToFindProtocols

What do you think about moving #protocolInSuperclassProtocol: as the first check?

**Comment by jecisc** [comment]
We should really define the behavior we want and add tests on that because the protocol management has always been messy. (Which is also why I am currently trying to clean a lot of things about protocols in the system)

**Comment by privat** [comment]
> What do you think about moving #protocolInSuperclassProtocol: as the first check?

This. Otherwise, we could remove `ReInconsistentMethodClassificationRule`

**Comment by pavel-krivanek** [comment]
originally, it first handled the superclass, see https://github.com/pharo-project/pharo/pull/9095/files#diff-e01112976379bd214d6be77b3973baddd16450e876ed215628a9fa02a9670648L146

<blockquote><img src="https://avatars.githubusercontent.com/u/15729309?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo/pull/9095">RB - Fix move method changing protocols by Lin777 · Pull Request #9095 · pharo-project/pharo</a></strong></div><div>Fixes #8929
Now when we move a method to a class or other package, you can update the protocol, and this open a preview to select a protocol with a suggestion of MethodClassifier.
You can see the n...</div></blockquote>

**Comment by jecisc** [comment]
I think we can revert to prioritise the protocol of the overridden method but with tests
