### ISSUE TITLE
Browser window resizing causes Red Square of Death

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#13414]
**Bug description**
For some methods, resizing of the browser window is causing Red Square of Death

**To Reproduce**
1. open Spotter, type `methodAdded`
2. go to `ChangeSet>>#methodAdded:`
3. increase the browser size
4. you get someting like

![image](https://user-images.githubusercontent.com/572494/231453371-d9dcab74-3cd8-409a-8b08-46b26e6cb7f2.png)

**Version information:**
 Pharo 11.0.0
Build information: Pharo-11.0.0+build.672.sha.87a0f07f1706902298dd944d7f17a4f9611a0a21 (64 Bit)

**Comment by jecisc** [comment]
The fact that the missing method is #isCommentNode might suggest that @privat will be interested in this bug

**Comment by privat** [comment]
Fixed by #13418
