### ISSUE TITLE
CI random failure on HaltTest

### ISSUE THREAD

**Issue by privat** [guillep/pharo-core#13451]
As seen in https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-13423/6/tests

```
Got 6 instead of 8.
HaltTest(TestAsserter)>>assert:description:resumable:
HaltTest(TestAsserter)>>assert:description:
HaltTest(TestAsserter)>>assert:equals:
HaltTest>>testHaltFromCount
HaltTest(TestCase)>>performTest
```

**Comment by jecisc** [comment]
This is related to: https://github.com/pharo-spec/NewTools/issues/505

**Comment by MarcusDenker** [comment]
this was fixed
