### ISSUE TITLE
Calypso: New Trait command does not create the Trait

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13468]
In Calypso:
- Right click on the class pane
- Click on New Trait
- Give the name you want
- Click on "OK"

I expected to get my new trait but nothing is happening

**Comment by jecisc** [comment]
I have Fluid class builder enabled in my image. I don't know if this influence anything

**Comment by jecisc** [comment]
In fact I have the impression that in Pharo 12 I cannot create a trait at all. Maybe it is related to the fluid class builder? I don't know

**Comment by MarcusDenker** [comment]
This was fixed by https://github.com/pharo-project/pharo/pull/14088
