### ISSUE TITLE
Playground does not lets evaluate undeclared variables

### ISSUE THREAD

**Issue by jordanmontt** [guillep/pharo-core#13482]
Now the Playground complains if you try to evaluate non declared variables. Maybe this is related to the refactors of the compiler

**Comment by jordanmontt** [comment]
And I cannot inspect a variable in the debugger!

<img width="957" alt="Capture d’écran 2023-04-19 à 15 12 46" src="https://user-images.githubusercontent.com/33934979/233085594-c8885dd6-0253-44bb-b306-4f1853054768.png">

**Comment by privat** [comment]
My bad, https://github.com/pharo-spec/Spec/pull/1377 was merged too fast, it seems. For some reason, a commit is missing.
New PR that should fix it https://github.com/pharo-spec/Spec/pull/1378
(show stopped people can add the missing method locally in their image)

**Comment by jordanmontt** [comment]
Thanks Jean! With the method of the commit now there is no problem. As that PR was merged I'll close this issue
