### ISSUE TITLE
four senders of non-existing selector #setSelectedIndex:

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13531]
The method is sending #setSelectedIndex: but MessageBrowser does not know this method.

**Comment by MarcusDenker** [comment]
- [ ] MessageBrowser>>#handleMethodModified:
- [ ] MessageBrowser>>#handleMethodRemoved:
- [ ] SpChangeSorterPresenter>>#setSelectedChangeSetIndex:
- [ ] SpChangeSorterPresenter>>#setSelectedClassIndex:
