### ISSUE TITLE
Registered surface not being deallocated

### ISSUE THREAD

**Issue by StewMacLean** [guillep/pharo-core#13543]
This is related to issue AthensCairoSurface not being deallocated #13053

Within AthensCairoSurface>>finializeResourceData:

a primitive is called via:

self unregisterSurfaceWithId: id.

As reported in #13053, the surface is not being found for the provided id. 

Using XCode Instruments to monitor allocated memory it shows that the primitive is failing to deallocate the surface's memory as the following screenshots demonstrate:

![03 createManualSurface](https://user-images.githubusercontent.com/97324099/234130863-f9eaa656-615d-4678-a383-8d1df88dd304.png)

![05 primitiveCreateManualSurface leak](https://user-images.githubusercontent.com/97324099/234130912-c54614ac-53cb-46ba-912f-c83f47967ff4.png)

**To Reproduce**
1. Using XCode > Open Developer Tools > Instruments > Leaks 
attached to the Pharo process
3. Execute 10000 timesRepeat: [AthensCairoSurface extent: 512 @ 512].
4. Observe the memory leak as reported in Instruments

**Expected behavior**
The memory for the surface should be deallocated by the primitive.

**Version information:**

OS: macOS
Version: 12.0.1
Pharo Version 10

**Expected development cost**
This is an issue with the VM. If the associated problem with finding the surface is fixed, this may fix this issue too?

**Comment by MarcusDenker** [comment]
PR was merged

**Comment by tinchodias** [comment]
Excelent!!! thanks
