### ISSUE TITLE
Hide autocompletion when the list is empty

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13571]
It happens often that the autocompletion is empty, for example while typing a new method name that is pretty specific. In that case we have an empty completion window and often it prevents me from seeing some code that interest me.

It would be great to hide the window if we have 0 result.

**Comment by privat** [comment]
If the list is empty, maybe the completion engine do not try hard enough?
The fact that the windows prevent you to see interesting code seems orthogonal to the lack of suggestions

**Comment by jecisc** [comment]
Well, sometimes it can try hard but if it cannot predict things with AI it cannot suggest some things like selectors that do not exist yet :)

I have often an empty completion and in that case I would really expect either for it to vanish, or to be a really really small popup

**Comment by privat** [comment]
Fair enough, a lot a gray, and text is useless.

![Capture d’écran du 2023-05-03 11-46-20](https://user-images.githubusercontent.com/135828/235968765-310e82d5-5069-49bf-b9aa-6a76112741e3.png)

**Comment by jecisc** [comment]
Your screenshot hides the biggest part ;)

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/9519971/236222537-7964000e-2cf4-4afb-8e3b-c6e2d329c867.png">

**Comment by privat** [comment]
Expect that the issue is explicitly about the situation of empty completion lists. Please open a second issue for non empty lists. ;P

**Comment by jecisc** [comment]
Well, the list is empty in my screenshot
