### ISSUE TITLE
Multiple Calypso refresh is painful

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#13598]
- Open two browsers
- Select the same class
- In one select the class comment
- In the other one define a method
The first one now does not show the class comment but another pane 
and this is painful when you want to read a class comment while trying something else.

**Comment by jecisc** [comment]
Duplicated of: https://github.com/pharo-project/pharo/issues/13254

**Comment by guillep** [comment]
Closed in favor of https://github.com/pharo-project/pharo/issues/13254
