### ISSUE TITLE
MessageSend should be subclass of Message

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#13607]
We have two classes nearly doing the same. I suggest that we merge MessageSend into Message.

**Comment by MarcusDenker** [comment]
Message is selector+Args, while MessageSend adds the receiver.

What is not good is that MessageSend  Message have both Object as the superclass and I think the APIs are not the same where they could be (MessageSend should be a subclass of message, just adding the receiver and some additonal API)

**Comment by MarcusDenker** [comment]
One could argue that Pragma should be subclass of Message (ass it is a selector with arguments), while MetaLink should be a subclass of MessageSend (as it defines a message send to a meta object).

MessageSend could be a subclass, or it could use a Message and add a receiver.

**Comment by MarcusDenker** [comment]
TODO:

- [x] Message: rename ivar "args" to "arguments #13654
- [x] Change superclass of MessageSend
- [x] Change superclass of Pragma

**Comment by jecisc** [comment]
Change the super class of MessageSend is done

**Comment by jecisc** [comment]
All items on Marcus's todo are now integrated

**Comment by Ducasse** [comment]
Nice :)
