### ISSUE TITLE
[CI] Win CI fails often. Disk space?

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#13629]
**Bug description**
We see again the win CI fail often, it seems there is a problem with disk space

**Comment by jecisc** [comment]
Maybe it could be cleaned with a cron?

**Comment by tesonep** [comment]
I have cleaned it.
@jecisc It is more complicated, the space is taken by the old closed PR executions. Those are cleaned by Jenkins, but with an smaller frequency that we need. I have a process that we can run to make the clean-up. 
We can add it as another Jenkins job. Before it was not a problem, I think in the build / test process we are generating more and more files.

**Comment by tesonep** [comment]
Also, there was an issue with the network, I have just restarted the slave to fix it 😮

**Comment by MarcusDenker** [comment]
The problem is back. It now even often just is green without running anything

**Comment by MarcusDenker** [comment]
Duplicaet of https://github.com/pharo-project/pharo/issues/14707
