### ISSUE TITLE
Setting a breakpoint after reverting a method to another version gives an error

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#13633]
**Bug description**
Setting a breakpoint after reverting a method to another version gives an error.

**To Reproduce**
* Select the class Gofer in a System Browser, modify the method `#allResolved` by adding `self logExecution` before the assignment
* Select ‘Versions’ from the context menu on the selector `#allResolved`, then revert the method to the first version
* In the method, select `self` in `self repositories`, then open a context menu and select ‘Break on self’ in ‘Breakpoints’

This opens a debugger. The error is a MessageNotUnderstood: `#installLink: was sent to nil` in the context of `RBProgramNode>>#link:`.

**Version information:**
Pharo-12.0.0+build.276.sha.2f03591775c448a6986bc9bf74bf0d1334164a87 (64 Bit)

**Comment by Rinzwind** [comment]
The bug report above is for Pharo 12. I first encountered a problem in Pharo 9 (build 1580) with a similar scenario which results in decompiled code:

* Select the class Gofer in a System Browser, modify the method `#allResolved` by adding `self logExecution` before the assignment
* Select ‘Versions’ from the context menu on the selector `#allResolved`, then revert the method to the first version
* Try to set a breakpoint on `self repositories` by clicking in the sidebar (no breakpoint icon appears)
* Try to set the breakpoint by selecting `self` in `self repositories`, opening a context menu and selecting ‘Add breakpoint’ in ‘Debugging’ (still no breakpoint icon appears)
* Select another method (such as `#allResolvedIn:`), then select `#allResolved` again

The method now appears as decompiled code with temporary variables named `tmp1` and `tmp2`.

**Comment by StevenCostiou** [comment]
![Capture d’écran 2023-05-09 à 14 36 49](https://github.com/pharo-project/pharo/assets/26929529/d801f34c-9793-4620-a5ff-85893cd1c9a5)

The reason is that it seems after reverting the method the `#compiledMethod` property of the AST is reinitialized.
The question is why?

**Comment by StevenCostiou** [comment]
The reason is Calypso: it seems to use a previous version of the AST and not the new one.

**Comment by StevenCostiou** [comment]
It really looks like Calypso does not update its model when we revert a method.
It keeps the old ast node as a selection, and that node is not related to any method.

That problem does not appear (not reproducible) in Pharo 9-10 and some of the Pharo 11 so it was introduced in Pharo 11-12.

**Comment by StevenCostiou** [comment]
Nothing in the latest P11 so it was introduced in Pharo 12.

**Comment by StevenCostiou** [comment]
So right now it is impossible to revert a P12 image to a previous commit, my image just freezes.
It is impossible to pinpoint the commit that introduced the problem.

It also seems that in Pharo 9 to 11, the breakpoint just does not install but it does not opens the debugger, it just does nothing.

**Comment by StevenCostiou** [comment]
Also in Pharo < 12, the ast of the reverted method is correct.

**Comment by StevenCostiou** [comment]
@MarcusDenker any idea?

**Comment by StevenCostiou** [comment]
So, if :
1) I reproduce the bug following the description of Rinzwind 
2) I browse implementors of the method `allResolved` (the message browser opens) and I do nothing more
3) I go back to Calypso, try to put the breakpoint following the description of Rinzwind 

Then it works.
Somehow it sets back the compiled method property correctly, or it updates the method in Calypso.

**Comment by MarcusDenker** [comment]
No idea, I will check.

**Comment by MarcusDenker** [comment]
I think I found a fix: https://github.com/pharo-project/pharo/pull/14991
