### ISSUE TITLE
Promote how to contribute ESUG video to help people joining 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#13662]
Hi 

I would to put a link somewhere to support the "Contribute" to Pharo 
with the ESUG 2022 https://www.youtube.com/watch?v=AtjEgK3lBPE&list=PLJ5nSnWzQXi_7LGwiSa-8VwYXELwFQLBt&index=32

S

**Comment by Ducasse** [comment]
I do not know where to put it and how.

**Comment by jecisc** [comment]
I would put it in https://github.com/pharo-project/pharo/blob/Pharo12/CONTRIBUTING.md via a simple PR

And maybe on the Pharo website in the contribution section

<blockquote><img src="https://repository-images.githubusercontent.com/64123480/451beb80-d08b-11e9-9ade-21d166d787d9" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">pharo/CONTRIBUTING.md at Pharo12 · pharo-project/pharo</a></strong></div><div>Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk. - pharo/CONTRIBUTING.md at Pharo12 · pharo-project/pharo</div></blockquote>
