### ISSUE TITLE
Enabling the setting ‘Show lines numbers for all browsers’ only shows line numbers for the first method selected in a class

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#13663]
**Bug description**
Enabling the setting ‘Show lines numbers for all browsers’ only shows line numbers for the first method selected in a class

**To Reproduce**
* In the Settings, enable ‘Show lines numbers for all browsers’
* In a System Browser, select a class and select a method (note that line numbers are shown)
* Select another method (in the same class)

Line numbers are unexpectedly not shown. When selecting another class and method, the line numbers reappear, then disappear again when another method is selected in the same class.

**Version information:**
Pharo-12.0.0+build.293.sha.f544baec532b913167d1ab83a345514efe6004a2

**Comment by Rinzwind** [comment]
Also: in the case of a test method, running it by clicking the ‘Run tests’ icon toggles the visibility of the line numbers.

**Comment by Rinzwind** [comment]
Changing this:

https://github.com/pharo-project/pharo/blob/bc3caeb48c654a37cdce5675cd7349b9a01609e1/src/Calypso-Browser/ClyTextLineNumbersSwitchMorph.class.st#L60-L61

To:
```smalltalk
	self class showLineNumbers
		ifTrue: [ textMorph withLineNumbers ]
```

At first glance seems to fix the issue, but this is maybe something for the author of pull request #9104 (@akevalion) to take a closer look at.

**Comment by akevalion** [comment]
Approved
