### ISSUE TITLE
The debugger opens with an error when opening a clean Pharo 11 & 12 image with recent VMs

### ISSUE THREAD

**Issue by PierreLouisPAUGAM** [guillep/pharo-core#13672]
**Bug description**
The debugger opens with an error when opening a clean Pharo 11 & 12 image with recent VMs.
It also prevents any initializing script from running.

**To Reproduce**
1. Create a new Pharo 11 or 12 image
2. Open it with a **Pharo VM 10.0.4-bf7aa420 or more recent**
3. See error 

![Capture](https://user-images.githubusercontent.com/58030198/237040449-12ecef8e-f35b-4123-8dc9-20eff13b02bd.PNG)

**Expected behavior**
No debugger opens, initialization scripts run.

**Screenshots**

**Version information:**
 - OS: Windows 11
 - Version: Pharo 11 and 12

**Comment by tesonep** [comment]
I have fixed the dependencies issues. With a P11 image the new VM should work (please update the VM)
