### ISSUE TITLE
[Feature Request] Code completion: react on `self class`

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13681]
When we are doing `self class`, the receiver will be the class side of the object we are currently into. Maybe we could use that in order to refine the completion?

I had a case just today where I typed `self class |` and the propositions were really off what I wanted while the list could have been better by proposing in priority the methods of the class side. 

I don't know how the code completion works so I have no idea of the development cost.

**Comment by privat** [comment]
The old completion (NECompletion, no more activatable but a lot of leftover code remain) did have a very limited type inferer (`TypeVisitor`).

The new one HeuristicCompletion (ie CoCompletionEngine, the default one) use a complex framework to define specific ad hoc cases for specific receiver (eg `self`, literals, globals). One of these case is `CoInitializeInferencedMessageHeuristic` that use some capacity to infer type on variables. But only for message send when variables are receiver (so it tries to guess the type of variables by looking at their assignments). It uses `CoTypeInferencer` that says is able to do some inter-procedural analysis by visiting `initialize` (and `setUp`) methods and collect ivar initialization with constants.

The whole code is very complex, full of fragile heuristics and with almost no test. So the development cost for the feature is [one million dollars](https://en.wikipedia.org/wiki/Dr._Evil).

More seriously, I'm not sure if the correct scalable approach it to add a new random heuristic to explicitly detect `self class` and act on it. Throwing away all the crapy heuristic and using a nice type inference should be a cleaner, scalable and more robust approach. But a fast, scalable and usable type inference is a big job.
