### ISSUE TITLE
Code Completion: completion sometimes has its window in a random place

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13709]
I don't really know how to reproduce it but I have often a case where my completion window is not in the right place.

<img width="1680" alt="image" src="https://github.com/pharo-project/pharo/assets/9519971/c8186b44-f86d-4453-910b-544b2b8b46c6">

I have the impression it happens when the completion is empty.

Might interest @privat 

We can see the code I am typing in the screenshot

**Comment by privat** [comment]
I'm not able to reproduce. :(

**Comment by jecisc** [comment]
I know I still get this problem but I don't know how to reproduce it exactly :( (for now)

**Comment by jecisc** [comment]
I got it!

I created a Toto class. Then a toto method. And then I started to slowly type "tata" as a method name (after doing cmd + a to select the full toto method). And I got it to pop

**Comment by jecisc** [comment]
<img width="1680" alt="image" src="https://github.com/pharo-project/pharo/assets/9519971/a33917fe-efa4-42c0-bbe2-6aa743eba598">

**Comment by Enzo-Demeulenaere** [comment]
This has been fixed last month but the issue is still open due to the lack of # in the commit message
