### ISSUE TITLE
Comment tab in SystemBrowser should be sticky

### ISSUE THREAD

**Issue by aiksiongkoh** [guillep/pharo-core#13713]
In SystemBrowser, when I select a class in top pane, the bottom pane always points to Definition tab.
If I want to explore the comments of each class, I have to select class and also select comment tab to read the comments.
Please make the comment tab stick when I select different classes to explore. Thanks, Aik-Siong Koh

**Comment by Ducasse** [comment]
Yes I think that I already reported this. 
Thanks for your notice.

**Comment by MarcusDenker** [comment]
Related to https://github.com/pharo-project/pharo/issues/13598

**Comment by estebanlm** [comment]
honestly, I would defer this (as it is an enhancement) until we finish the migration, otherwise it will be a pain (and double work).
EDIT: But of course, I agree this needs to be implemented, eventually.

**Comment by Ducasse** [comment]
I understand your points now in how many years do you think that we will have calypso 2 and what are the steps that we should put in place to arrive there.

**Comment by guillep** [comment]
Duplicates https://github.com/pharo-project/pharo/issues/16591
