### ISSUE TITLE
Right click in empty Iceberg pane gives #build was sent to nil

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#13712]
Pharo 12:

- open Iceberg
- right click into the empty repository pane

![image](https://github.com/pharo-project/pharo/assets/5980033/4e5e6725-faa5-4e02-80ae-08f412746774)

**Comment by MarcusDenker** [comment]
Maybe related to 

Half of a fix fix for when right-clicking on an empty Iceberg panel
https://github.com/pharo-vcs/iceberg/pull/1698

**Comment by MarcusDenker** [comment]
Yes, this seems to be fixed in Pharo11 already

**Comment by Gabriel-Darbord** [comment]
Can confirm that this is not reproducible in Pharo12.

**Comment by MarcusDenker** [comment]
Great! I close the issue
