### ISSUE TITLE
Installing a version of a class method adds an instance method

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#13718]
**Bug description**
Installing a version of a class method adds an instance method.

**To Reproduce**
* In Iceberg, clone or otherwise repair the ‘pharo’ repository
* Browse class Object, modify the class method `#whatIsAPrimitive`
* Open the versions of the method (select ‘History’ in the context menu on the selector), then install the last version again

The class method hasn’t been reverted, while an instance method `#whatIsAPrimitive` has unexpectedly been added.

**Version information:**
Pharo-12.0.0+build.327.sha.9fae37764495a6e3ea568f7293cf34edbe825abd (64 Bit)

**Comment by MarcusDenker** [comment]
there was an issue similar to it:
fix: ensure right method side (class vs instance) is chosen when looking through history
https://github.com/pharo-vcs/iceberg/pull/1688
