### ISSUE TITLE
Binding for variable in Playground is nil after assigning a number to it

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#13723]
Scenario:

* Open a Playground, enter `n := 123`, click ‘Do it’, then click ‘Bindings’

There’s a binding for ‘n’, but its value is nil rather than 123 as expected.

**Screenshot:**
<img width="300" alt="Playground Bug" src="https://github.com/pharo-project/pharo/assets/1611248/aa2d6020-8cd5-443e-b141-6bb378965495">

**Build information:**
Pharo-12.0.0+build.328.sha.34ebfbe1a25f4b5a6af46fdab9cf417763422de1 (64 Bit)

**Comment by MarcusDenker** [comment]
it is not changing the value for the first eval, as soon as the binding is there is works. The reason seem to be the check in OCRequestorScope>>#registerVariables

```
registerVariables

	self variables do: [ :each |
		| var |
		"Force the declaraction, if needed"
		var := requestor bindingOf: each name.
		"Because we no non control how requestor handle its variables, just update the one we used locally"
		(var isNotNil and: [ var ~= each ]) ifTrue: [ each becomeForward: var ] ].
	super registerVariables
```

If we do the becomeForward:, it works (as the change of the value then will change the correct WorkspaceVariable)

**Comment by MarcusDenker** [comment]
fixed by merging https://github.com/pharo-project/pharo/pull/13739
