### ISSUE TITLE
[Compiler] bindingOf: and hasBindingOf: in Object

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#13735]
**Describe the problem**
The whole story around lookupVar: and bindingOf: is a mess...

This one is about the fall-back of # bindingOf: and #hasBindingOf: in Object

- #hasBindingOf:  returns false, even if the subclass overrides # bindingOf: (and yes, there are cases)
- I would even remove these methods from Object and force all requestors to implement them.

**Comment by MarcusDenker** [comment]
DONE

**Comment by Ducasse** [comment]
I would even remove these methods from Object and force all requestors to implement them.
> I would :)
