### ISSUE TITLE
[CI] CoverageCollectorTest>>testExample fails randomly

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13746]
This week I saw two random failures of this test.

testExample – Unix64.Coverage.Tests.CoverageCollectorTest

https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-13739/1/tests/

```
Error
Assertion failed
Stacktrace
TestFailure
Assertion failed
CoverageCollectorTest(TestAsserter)>>assert:description:resumable:
CoverageCollectorTest(TestAsserter)>>assert:description:
CoverageCollectorTest(Object)>>assert:
CoverageCollectorTest>>testExample
CoverageCollectorTest(TestCase)>>performTest
```

**Comment by jecisc** [comment]
This failing test seems to always be on Unix. I cannot reproduce it on my OSX and all CI i've seen failing are Linux ones. 

@MarcusDenker Do you have any idea if there is something OS specific on the coverage?

**Comment by MarcusDenker** [comment]
Really strange. If I download that image, I get no problems, but of course I have a mac

**Comment by jecisc** [comment]
I did a PR to get better assertions on this test to try and understand the problem

**Comment by jecisc** [comment]
Now we have better logs:

```
Given Collections do not match!  additions : #()  missing: #('Point>>#y' 'Point>>#x')
Stacktrace
TestFailure
Given Collections do not match!
	additions : #()
	missing: #('Point>>#y' 'Point>>#x')
CoverageCollectorTest(TestAsserter)>>assert:description:resumable:
CoverageCollectorTest(TestAsserter)>>assert:description:
CoverageCollectorTest(TestAsserter)>>assertCollection:hasSameElements:
CoverageCollectorTest>>testExample
CoverageCollectorTest(TestCase)>>performTest
```

But I don't know why sometimes on Linux we have this random failure

**Comment by MarcusDenker** [comment]
for now I skip it: https://github.com/pharo-project/pharo/pull/13853

**Comment by tesonep** [comment]
We have seen that the problem is the interaction between the interpreter and the special sends. 
In linux, they are running in the interpreter so the messages Point >> #x and Point >> #y are never executed. 
In OSX, the method is compiled to machine code and the messages are sent. 
We need to rewrite this test without using special sends to have the same behavior always.
With @guillep we cannot see why in one OS is JIT this method and why not in the other.

**Comment by MarcusDenker** [comment]
The test was rewritten to use an example that does not use special selectors
