### ISSUE TITLE
Print it behavior changed in Calypso

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13741]
The print it feature has a particularity that if you hit enter after printing the value of an expression, the content of the popup is added as a comment. This is good when you want to write examples and want to display the result of a command in a snippet. 

In Pharo 12 this feature seems to be broken. Hitting "enter" will not add the content of the popup in a comment but do a line return and remove the popup.

**Comment by Gabriel-Darbord** [comment]
Cannot reproduce with the latest build. Has this been fixed already?

**Comment by Mathilde411** [comment]
Same, cannot reproduce.

**Comment by MarcusDenker** [comment]
I do not see any popup at all in Calypso, if I print-it, it just adds the result to the code pane.

This is the same in Pharo11.

The Popup is only implemented for Spec based code panes (Playground, debugger, inspector), not Calypso

**Comment by Ducasse** [comment]
The problem is the following, when you type enter after a print 
- in a playground you get the result in ""
- in calypso you get a new line

**Comment by MarcusDenker** [comment]
Yes, this was always like that

**Comment by demarey** [comment]
I propose to close the issue as it is not a bug and Calypso has to be rewritten in Spec
