### ISSUE TITLE
Sources in build 343 differ from the commit

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#13765]
Scenario:

* In Pharo Launcher, add and launch an image using the template ‘Pharo12-SNAPSHOT.build.343.sha.096203f.arch.64bit’ (in the template category ‘Pharo 12.0 (development version)’)
* In Iceberg, repair the repository ‘pharo’ by cloning from the main GitHub repository (when finished, the status changes to ‘Detached Working Copy’)
* Open the repository, select commit 096203f, then select ‘Reset Pharo12 to commit 096203f’ in the context menu
* Close the repository window

In the Iceberg ‘Repositories’ window, the status of the ‘pharo’ repository unexpectedly shows ‘Uncommitted changes’. Using ‘Commit’ shows differences in `ClassDescription>>#removeEmptyProtocols`:

<p align="center">
<img width="400" src="https://github.com/pharo-project/pharo/assets/1611248/51605000-7d4c-4671-9459-8268979ec894">
</p>

**Comment by jecisc** [comment]
I noticed it too but I cannot find the origin. 

The method seems good in the source file

**Comment by jecisc** [comment]
I shipped a fix in https://github.com/pharo-project/pharo/pull/13776

**Comment by Rinzwind** [comment]
It’s not so clear to me how pull request #13776 fixed this issue: it changed `ClassDescription>>#removeEmptyProtocols`, but did it also fix the root cause of this issue? What caused the image of build 343 to not have the implementation of the method from the [file ‘ClassDescription.class.st’ in commit 096203f](https://github.com/pharo-project/pharo/blob/096203f761be37d1de1c0375bfb14816ea97423c/src/Kernel/ClassDescription.class.st#L790-L794) ?

**Comment by jecisc** [comment]
The origin of the problem was that the method called a deprecated method that had an automatic transformation rule. Et the method was executed during the code loading. So it was loaded and transformed during the bootstrap.

This comes from the incoherence that we had ClassDescription>>#protocols returning protocol names and ClassOrganization>>#protocols returning protocol objects. 
the one of ClassDescription has been deprecated in favor of #protocolNames with an automatic transformation rule.

**Comment by Rinzwind** [comment]
Ah OK, I see: the transformation rule is in [`ClassDescription>>#protocols`](https://github.com/pharo-project/pharo/blob/096203f761be37d1de1c0375bfb14816ea97423c/src/Ring-Definitions-Core/ClassDescription.extension.st#L4-L10).

I would suggest to disable the automatic transformation in the builds to avoid a similar issue in the future, it’s rather confusing.
