### ISSUE TITLE
Diagnostics signal crashes Pharo when opened through Finder

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#13773]
From a [comment in issue #13769](https://github.com/pharo-project/pharo/issues/13769#issuecomment-1554034834), I picked up that a Pharo VM process can be sent a signal to write a diagnostics file ‘crash.dmp’. However, on macOS, this seems to not work when the VM has been opened through Finder, scenario:

* In Pharo Launcher, add a new Pharo 12 image
* Open the image folder in Finder (through the button *Show*)
* Launch the image
* In Activity Monitor, look for the Pharo process and send it SIGUSR1 (through the menu item [*View ▸ Send Signal to Process*](https://support.apple.com/en-euro/guide/activity-monitor/actmntr1002/mac))
* In Finder, verify that a file ‘crash.dmp’ has been added to the image folder
* Quit the image
* In Pharo Launcher, open the VM folder in Finder (through the button *Show* in the window opened by the button *VMs*, select the ‘120-…’ VM)
* In Finder, open the ‘Pharo’ application in the VM folder, then select the image in the dialog and open it (to quickly select it, drag it from the image folder in Finder to the file list in the dialog)
* In Activity Monitor, look for the Pharo process again and send it SIGUSR1

Pharo unexpectedly quits. I suspect this is because it tries to write the file ‘crash.dmp’ to its working directory but doesn’t handle that directory not being writable: when opened through Finder, the working directory is ‘/’ which is only writable by the ‘root’ user. This should at least not crash, though it would be better if it tried another directory instead (say the image directory, and the user home directory as a last resort).

**Comment by guillep** [comment]
Fixed in [pharo-project/pharo-vm#](https://github.com/pharo-project/pharo-vm/pull/739)
