### ISSUE TITLE
Cannot fuel-out a stack trace when "Welcome to Pharo 11" window is open

### ISSUE THREAD

**Issue by gcotelli** [guillep/pharo-core#13788]
**Bug description**
When trying to fuel-out a stack trace **and the Welcome to Pharo 11 window is open,** the serialization fails:

![image](https://github.com/pharo-project/pharo/assets/2106744/0fe8ea67-3c45-456b-8e46-17937e699040)

Closing the Welcome to Pharo 11 window makes it work.

As a side effect of this, people running smalltalkCI and trying to fuel out a stack will hit this problem.

**To Reproduce**
1. Download a Pharo 11 image
2. Open a Playground
3. Type `1 zork` or something producing a DNU
4. In the debugger go to the contextual menu over the stack, and choose `Stack -> Fuel-out stack`
5. You will get a debugger like the one shown previosuly

**Expected behavior**
The fuel-out must work even with the Welcome window open.

**Screenshots**
See above

**Version information:**
 - OS: unix linux-gnu x86_64 - Manjaro Linux
- Image: Pharo-11.0.0+build.689.sha.8986777f96ab65cba515d005d13487e0375fa85c (64 Bit)
- Virtual Machine:
  CoInterpreter VMMaker-tonel.1 uuid: dee5446d-beb7-0d00-9fd2-81360cc4fcbd May 10 2023
  StackToRegisterMappingCogit VMMaker-tonel.1 uuid: dee5446d-beb7-0d00-9fd2-81360cc4fcbd May 10 2023
  v10.0.5 - Commit: 2757766f6 - Date: 2023-05-05 13:46:09 +0200

Pharo 10.0.5-2757766f6 built on May 10 2023 17:29:15 Compiler: 12.2.1 20230201
VMMaker versionString v10.0.5 - Commit: 2757766f6 - Date: 2023-05-05 13:46:09 +0200
CoInterpreter VMMaker-tonel.1 uuid: dee5446d-beb7-0d00-9fd2-81360cc4fcbd May 10 2023
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: dee5446d-beb7-0d00-9fd2-81360cc4fcbd May 10 2023

**Expected development cost**

I don't know. It looks totally strange to me that the Welcome window has an impact on stack trace serialization.

**Comment by tesonep** [comment]
I have created the PR in Spec https://github.com/pharo-spec/Spec/pull/1399

**Comment by MarcusDenker** [comment]
For Pharo11 it was merged, for Pharo12 it is still open

**Comment by jecisc** [comment]
I reviewed and merge for P11. Then I saw that esteban commented on the P12 version. So I am not sure on how to proceed. Do we merge also for p12 and maybe do another iteration if estaban's comments are showing a problem?
