### ISSUE TITLE
[Pharo12] StDebugger>>#connectPresenters sends non-existing selector

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#13804]
**Bug description**
When running all tests, the NewTools debugger tests fail. Somehow StDebugger>>#connectPresenters is wrong:

```
connectPresenters

	super connectPresenters.
	self whenDisplayDo: [ 
		self updateToolbar.
		self updateCodeFromContext ]
	for: self
```

#whenDisplayDo:for: does not exist.

**Comment by MarcusDenker** [comment]
Might be due to merging https://github.com/pharo-spec/NewTools/pull/502

**Comment by jecisc** [comment]
I reverted the change
