### ISSUE TITLE
DeprecationPerformedNotification during build

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#13807]
Running tests of NewTools-Inspector-Tests
DeprecationPerformedNotification: Automatic deprecation code rewrite: The method Announcer>>#when:do: called from SpExecutableLayout>>#whenChildrenAddedDo: has been deprecated. Since there are some block closures (Clean and Constant) without a receiver, the API of announcements was changed to send the subscriber explicitly. 
			We are deprecating this method because it was asking for the receiver of the block to use it as the subscriber.
DeprecationPerformedNotification: Automatic deprecation code rewrite: The method Announcer>>#when:do: called from SpExecutableLayout>>#whenChildrenRemovedDo: has been deprecated. Since there are some block closures (Clean and Constant) without a receiver, the API of announcements was changed to send the subscriber explicitly. 
			We are deprecating this method because it was asking for the receiver of the block to use it as the subscriber.
Running tests of BaselineOfReflectivity
Running t

**Comment by DurieuxPol** [comment]
Working on it
