### ISSUE TITLE
Cannot close autocomplete detail

### ISSUE THREAD

**Issue by PalumboN** [guillep/pharo-core#13800]
**Bug description**
If I open the description of autocomplete options using the shortcut `cmd ->` it opens a second menu with the description and I can navigate, and even browse. OK 👍 

But, if I want to close the description with the suggested command `cmd <-` or `<-` (both menus say different things) it's not working 👎 
Instead, it moves the cursor.

**To Reproduce**
1. Write some code to open the autocomplete suggestions menu
2. Open the detail
3. Try to close it without lose the current suggestions

**Expected behavior**
After opening the details autocomplete menu, the shortcut `cmd <-` should close it and come back to the "normal" coding state keeping the current suggestions.

**Screenshots**
![image](https://github.com/pharo-project/pharo/assets/4098184/ff481d2b-5103-4ff7-95a9-c9fab3d11213)

**Version information:**
 - Pharo Version 11

**Comment by jecisc** [comment]
The autocompletion changed a lot in Pharo 12. Maybe it could be good to take a look at it.

Now the detail is open by default. But I'm not sure it is possible to close it.

**Comment by privat** [comment]
Yeah, the completion menu is "improved" in Pharo12 (suspicious quotes).

Ctrl+arrow now just moves the cursor and might close the completion menu is you escape from the current word.
Ctrl+B is now used to browse.
Can you check it and open new issue if you do not like things?
