### ISSUE TITLE
Pharo12 now shows the Pharo11 Welcome Window

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#13805]
Pharo12 now shows the Pharo11 Welcome Window
Maybe this is good, as we know run into 

Cannot fuel-out a stack trace when "Welcome to Pharo 11" window is open #13788

In Pharo12, too. We see lots of 

```
Serialization error. Unexpected reference to Color white in the graph. This usually happens when the graph changes during serialization.
```
and then

```
FileWriteError: File Tests-osx-64-NewTools-Debugger-Tests-Test.xml is closed
```

Which is due to test failing, which happens due to 

[Pharo12] StDebugger>>#connectPresenters sends non-existing selector #13804

**Comment by Mathilde411** [comment]
This was fixed with pharo-spec/NewTools-WelcomeBrowser#6 . The PR now needs to be merged.

**Comment by MarcusDenker** [comment]
and it needs to be done in Both Pharo11 and Pharo12 branches

**Comment by MarcusDenker** [comment]
ups, no, this is for pharro12, the Fuel fix is for both (the Serialization error), but that is another PR

**Comment by MarcusDenker** [comment]
fixed!
