### ISSUE TITLE
Run coverage button is enabled with unselected packages ( Dr Tests )

### ISSUE THREAD

**Issue by CarolinaMelendez** [guillep/pharo-core#13806]
**Bug description**
In the test coverage plugin, when no package is selected and the run coverage button is pressed, it shows an exception "#collect: was sent to nil". Furthermore, it is not possible to go to Tests Runner, it shows the same exception.

**To Reproduce**
1. Go to DrTest
2. Select "Test coverage" plugin
3. Click on 'Run coverage' button
5. See exception 
6. Then select "Tests Runner" plugin
7. See exception

**Expected behavior**
The run coverage button shouldn't be enabled or a message "You have to choose one package" should be displayed.

**Version information:**
 - Pharo Version: 12.0

**Comment by Ducasse** [comment]
Thanks carolina!
Good catch. Are you planning to work on it?

**Comment by CarolinaMelendez** [comment]
Yes, I would like to solve it. 
As a practice too

**Comment by MarcusDenker** [comment]
PR was merged
