### ISSUE TITLE
Signaling an error in a playground does not open a debugger

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#13803]
Scenario:

* Open a playground, enter `Error signal` and press ‘Do it’

I expected a debugger to open, but none is opened.

**Build information:** Pharo-12.0.0+build.359.sha.a30cc6394d8e6140654e153596a3878e14232bb1 (64 Bit)

**Comment by MarcusDenker** [comment]
maybe due to

[Pharo12] StDebugger>>#connectPresenters sends non-existing selector #13804

**Comment by MarcusDenker** [comment]
This is now fixed (I get a debugger)
