### ISSUE TITLE
 Instance of ClassOrganization did not understand #extensionProtocols

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#13813]
**Bug description**
Full image load fails with

```
Instance of ClassOrganization did not understand #extensionProtocols
```
maybe due to merging 

https://github.com/pharo-project/pharo/pull/13783

(but it was green)

**Comment by jecisc** [comment]
Either some code does ‘class organization extensionProtocols’ and the « organization » needs to be removed. Or it’s called directly in ClassOrganization and we need to add a « organizedClass » right before

**Comment by MarcusDenker** [comment]
So how do we fix it? the problem is that the build fails.


We could just revert, it then works again, see: https://github.com/pharo-project/pharo/pull/13814

**Comment by jecisc** [comment]
I'm working with Enzo on other things right now. To not block the CI you can integrate the revert and I will check the problem a do a better PR for this later
