### ISSUE TITLE
New slot is not initialized for an existing instance

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#13839]
Scenario:

* In a System Browser, enable the ‘Fluid’ checkbox
* Select class ThemeIcons and add a slot:
  `#newSlot => InitializedSlot default: 123`
* Inspect `ThemeIcons current`
* Do `ThemeIcons reset` and inspect `ThemeIcons current` again

After the reset, the value of ‘newSlot’ is 123, but before it is still nil. I’m not sure whether that is intentional?

In the `#copyObject:to:` of ShiftClassInstaller, a visible slot gets initialized only if the class of the old object has the slot as well:

https://github.com/pharo-project/pharo/blob/37087caf6f0ca109bef290a601878fcee08aa0ea/src/Shift-ClassInstaller/ShiftClassInstaller.class.st#L95-L99

Shouldn’t the slot also be initialized if the old class doesn’t have the slot?

**Build information:** Pharo-12.0.0+build.374.sha.37087caf6f0ca109bef290a601878fcee08aa0ea

**Comment by MarcusDenker** [comment]
yes, this seems to be wrong

**Comment by macta** [comment]
I hit the same problem tonight after seeing Stef's presentation on Pharo 11. I loaded a new image and tried a cutdown version of https://medium.com/@juliendelplanque/typed-slots-for-pharo-98ba5d5aafbe (I skipped the tests just typed in a simple example) and noticed that when you try using different types, they don't get updated.  e.g.

```
Object << #MyClass
	slots: {
			 #someValue => MaxNumberSlot maxNumber: 15 .
			 #myOtherValue => InitializedSlot default: [ Time now ] };
	package: 'TimTest'
```

In the above, changing 15 to 10 doesn't recognize the 10. Changing [Time now] to [Date today] doesn't change etc.

<blockquote><div><strong><a href="https://medium.com/@juliendelplanque/typed-slots-for-pharo-98ba5d5aafbe">Just a moment...</a></strong></div></blockquote>
