### ISSUE TITLE
Finder - first time [Packages...] selector window does function properly

### ISSUE THREAD

**Issue by sanjayminni** [guillep/pharo-core#13907]
To reproduce behavior
open Browse->Finder
- click [Packages...] on top bar
- move all from selected panel to available panel by using [<<]
- now move some items by selecting in available panel and using [>]
**Error: all iems in Available panel disappear while actually the remaining items should be showing** 
Anyway pres [Ok] close and abail open by clicking the [Packages...] button
this time things work fine  

![PharoScreenshot](https://github.com/pharo-project/pharo/assets/12030766/b05a65e0-f149-4608-a525-a187700026d7)

**Comment by jordanmontt** [comment]
Same issue: https://github.com/pharo-spec/Spec/issues/1340
Could you comment on that issue please?
Actually, this is an issue for Spec. I propose to close the issue in this repo since this is already reported on Spec.

**Comment by sanjayminni** [comment]
I have added my comments in https://github.com/pharo-spec/Spec/issues/1340 if its the same bug

**Comment by jordanmontt** [comment]
Yes, it is the same. Thanks!!

**Comment by jordanmontt** [comment]
Maybe we can leave it open

**Comment by JanBliznicenko** [comment]
Fixed by https://github.com/pharo-spec/Spec/pull/1494
