### ISSUE TITLE
RTFSelfCallInterpreter should be a subclass of RBProgramNodeVisitor

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#13911]
**Describe the problem**
RTFSelfCallInterpreter implements a visitor, but does not inherit from RBProgramNodeVisitor. It seems that lots of methods could be inherited. Or, if there is a reason (e.g because visit order is different), it should be documented that not using RBProgramNodeVisitor is intensional

**Comment by Ducasse** [comment]
What is RTFSelfCall....

**Comment by MarcusDenker** [comment]
This is part of RottenTestsFinder

**Comment by guillep** [comment]
It implements a dynamic analysis that finds all self sends in a given execution.
