### ISSUE TITLE
AIKleinbergGraphGenerator>>#buildLongRangeLinks send unknown selector 

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#13939]
**Bug description**
AIKleinbergGraphGenerator>>#buildLongRangeLinks send unknown selector #cumsum

**Comment by Ducasse** [comment]
@jordanmontt

**Comment by jordanmontt** [comment]
Hello,
This graph generator algos are legacy code from Moose. I think that the best solution is simply to not load that package. I will the graph generators from the graph algos baseline (not from the repo)
