### ISSUE TITLE
GeneralRules packages has a low code coverage

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13935]
A lot of rules in GeneralRules package do not have test. It would be nice to add tests to them.

I am currently doing some refactorings and the rules tests are passing while a lot a exception are raised at the bottom of Calypso or in the critic browser.

**Comment by MarcusDenker** [comment]
The package names and organization are a mess in general for all the Rules related code

**Comment by jecisc** [comment]
It improved
