### ISSUE TITLE
 RBRefactoring>>#onError:do:  should accept both 0 and 1 arg block

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#13957]
<img width="1145" alt="Capture 2023-06-09 at 07 33 07" src="https://github.com/pharo-project/pharo/assets/432549/b8912340-1f90-4b62-acea-4cbef726a163">

**Comment by Ducasse** [comment]
ConstantBlockClosure1Arg(BlockClosure)>>numArgsError:
ConstantBlockClosure1Arg>>value
[:ex |
			errorBlock value.
			ex return: nil] in RBInlineAllSendersRefactoring(RBRefactoring)>>onError:do: in Block: [:ex |...
FullBlockClosure(BlockClosure)>>cull:
Context>>evaluateSignal:
Context>>handleSignal:
RBRefactoringError(Exception)>>signal
RBRefactoringError(Exception)>>signal:
RBRefactoringError class(Exception class)>>signal:
RBInlineMethodRefactoring(RBAbstractTransformation)>>refactoringError:
[self findSelectedMessage.
					self checkOverridden ifTrue: [
						self isOverridden
						ifTrue:
							[self
								refactoringWarning: ('<1p>>><2s> is overriden. Do you want to inline it anyway?', String cr, 'You can break you hooks with this inline.'
										expandMacrosWith: self classOfTheMethodToInline
										with: self inlineSelector)] ].
					self parseInlineMethod.
					self isPrimitive
						ifTrue: [self refactoringError: 'Cannot inline primitives'].
					self checkSuperMessages.
					self rewriteInlinedTree.
					(sourceMessage parent isReturn or: [self hasMultipleReturns not])
						ifFalse:
							[self
								refactoringError: 'Cannot inline method since it contains multiple returns that cannot be rewritten'].
					true] in RBInlineMethodRefactoring>>preconditions in Block: [self findSelectedMessage....
RBCondition>>check
RBConjunctiveCondition>>check
RBInlineMethodRefactoring(RBRefactoring)>>checkPreconditions
RBInlineMethodRefactoring(RBRefactoring)>>primitiveExecute
RBInlineAllSendersRefactoring(RBRefactoring)>>performCompositeRefactoring:
[self performCompositeRefactoring: ((RBInlineMethodRefactoring
									model: self model
									inline: node sourceInterval
									inMethod: aSelector
									forClass: aClass) checkOverridden: false).
						numberReplaced := numberReplaced + 1] in RBInlineAllSendersRefactoring>>inlineMessagesInClass:andSelector: in Block: [self performCompositeRefactoring: ((RBInlineM[..]
FullBlockClosure(BlockClosure)>>on:do:
RBInlineAllSendersRefactoring(RBRefactoring)>>onError:do:
RBInlineAllSendersRefactoring>>inlineMessagesInClass:andSelector:
[:sel | self inlineMessagesInClass: each andSelector: sel] in [:each |
			| selectors |
			self initializePatternFor: each.
			pattern ifNotNil: [
			selectors := each localSelectors.
			class = each ifTrue: [ selectors remove: selector ifAbsent: []].
			selectors do: [:sel | self inlineMessagesInClass: each andSelector: sel]]] in RBInlineAllSendersRefactoring>>inlineSelfSends in Block: [:sel | self inlineMessagesInClass: each andSe[..]
Set>>do:
[:each |
			| selectors |
			self initializePatternFor: each.
			pattern ifNotNil: [
			selectors := each localSelectors.
			class = each ifTrue: [ selectors remove: selector ifAbsent: []].
			selectors do: [:sel | self inlineMessagesInClass: each andSelector: sel]]] in RBInlineAllSendersRefactoring>>inlineSelfSends in Block: [:each |...
OrderedCollection>>do:
RBInlineAllSendersRefactoring>>inlineSelfSends
RBInlineAllSendersRefactoring>>transform
RBInlineAllSendersRefactoring(RBRefactoring)>>primitiveExecute
[ :each |
		each model environment: rbEnvironment.
		each primitiveExecute ] in SycRefactoringPreviewPresenter>>generateChanges in Block: [ :each |...
Array(SequenceableCollection)>>do:
SycRefactoringPreviewPresenter>>generateChanges
SycRefactoringPreviewPresenter>>updateChanges
[ :scope | self updateChanges ] in SycRefactoringPreviewPresenter>>initializePresenter in Block: [ :scope | self updateChanges ]
FullBlockClosure(BlockClosure)>>cull:
[	aBlock cull: self selectedItem ] in SpDropListPresenter>>whenSelectedItemChangedDo: in Block: [	aBlock cull: self selectedItem ]
FullBlockClosure(BlockClosure)>>cull:
[ aBlock cull: self ] in SpSingleSelectionMode>>whenChangedDo: in Block: [ aBlock cull: self ]
FullBlockClosure(BlockClosure)>>cull:
FullBlockClosure(BlockClosure)>>cull:cull:
[ :block | block cull: self value cull: oldValue ] in ObservableValueHolder>>valueChanged: in Block: [ :block | block cull: self value cull: oldValue ]
OrderedCollection>>do:
ObservableValueHolder>>valueChanged:
[ | oldValue |
	oldValue := value.
	value := anObject.
	self valueChanged: oldValue ] in ObservableValueHolder>>value: in Block: [ | oldValue |...
FullBlockClosure(BlockClosure)>>ensure:
ObservableValueHolder>>value:
SpSingleSelectionMode>>basicSelectIndex:
SpSingleSelectionMode(SpAbstractSelectionMode)>>selectIndex:
SpDropListPresenter>>selectIndex:
SpDropListPresenter>>setCollection:
SpDropListPresenter>>items:
SycRefactoringPreviewPresenter>>scopes:
SycRefactoringPreviewPresenter class>>for:scopes:
SycInlineAllSendersMessageCommand(CmdCommand)>>confirmRefactoringInContext:by:
ClyFullBrowserMethodContext(ClySystemBrowserContext)>>executeCommand:by:
[self prepareCommandForExecution.
	context executeCommand: command by: self.
	self applyCommandResult] in CmdCommandActivator>>executeCommand in Block: [self prepareCommandForExecution....
FullBlockClosure(BlockClosure)>>on:do:
CmdCommandActivator>>executeCommand
[ | selArgCount |  "show cursor in case item opens a new MVC window"
		(selArgCount := selector numArgs) = 0
			ifTrue:
				[target perform: selector]
			ifFalse:
				[selArgCount = arguments size
					ifTrue: [target perform: selector withArguments: arguments]
					ifFalse: [target perform: selector withArguments: (arguments copyWith: evt)]].
		self showShortcut.
		self changed] in ToggleMenuItemMorph(MenuItemMorph)>>invokeWithEvent: in Block: [ | selArgCount |  "show cursor in case item o[..]
FullBlockClosure(BlockClosure)>>ensure:
CursorWithMask(Cursor)>>showWhile:
ToggleMenuItemMorph(MenuItemMorph)>>invokeWithEvent:
ToggleMenuItemMorph(MenuItemMorph)>>mouseUp:
ToggleMenuItemMorph(MenuItemMorph)>>handleMouseUp:
MouseButtonEvent>>sentTo:
ToggleMenuItemMorph(Morph)>>handleEvent:
MorphicEventDispatcher>>dispatchDefault:with:
MorphicEventDispatcher>>handleMouseUp:
MouseButtonEvent>>sentTo:
[ ^ anEvent sentTo: self ] in MorphicEventDispatcher>>dispatchEvent:with: in Block: [ ^ anEvent sentTo: self ]
FullBlockClosure(BlockClosure)>>ensure:
MorphicEventDispatcher>>dispatchEvent:with:
ToggleMenuItemMorph(Morph)>>processEvent:using:
MorphicEventDispatcher>>dispatchDefault:with:
MorphicEventDispatcher>>handleMouseUp:
MouseButtonEvent>>sentTo:
[ ^ anEvent sentTo: self ] in MorphicEventDispatcher>>dispatchEvent:with: in Block: [ ^ anEvent sentTo: self ]
FullBlockClosure(BlockClosure)>>ensure:
MorphicEventDispatcher>>dispatchEvent:with:
MenuMorph(Morph)>>processEvent:using:
MenuMorph(Morph)>>processEvent:
MenuMorph>>handleFocusEvent:
[
		result := focusHolder handleFocusEvent: transformedEvent.
	] in HandMorph>>sendFocusEvent:to:clear: in Block: [...
FullBlockClosure(BlockClosure)>>on:do:
WorldMorph>>becomeActiveDuring:
HandMorph>>sendFocusEvent:to:clear:
HandMorph>>sendEvent:focus:clear:
HandMorph>>sendMouseEvent:
HandMorph>>handleEvent:
[
		(morphicWorld activeHand isNotNil and: [ anEvent hand isNotNil ]) ifTrue: [
			morphicWorld activeHand handleEvent: anEvent
		]
	] in OSWindowMorphicEventHandler>>dispatchMorphicEvent: in Block: [...
WorldState>>runStepMethodsIn:
WorldMorph>>runStepMethods
WorldState>>doOneCycleFor:
WorldMorph>>doOneCycleNow
WorldMorph>>doOneCycle
[
		| extraWorldsToDraw |
		extraWorldsToDraw := ExtraWorldListMutex critical: [
			                     self extraWorldList ].
		extraWorldsToDraw do: [ :world | world doOneCycle ].

		(self currentWorld isNotNil and: [
			 (extraWorldsToDraw includes: self currentWorld) not ]) ifTrue: [
			self currentWorld doOneCycle ] ] in WorldMorph class>>doOneCycle in Block: [...
FullBlockClosure(BlockClosure)>>ensure:
WorldState class>>doDrawCycleWith:
WorldMorph class>>doOneCycle
MorphicRenderLoop>>doOneCycle
MorphicRenderLoop>>doOneCycleWhile:
[ MorphicRenderLoop new doOneCycleWhile: [ true ] ] in MorphicUIManager>>spawnNewProcess in Block: [ MorphicRenderLoop new doOneCycleWhile: [ tru[..]
[self value.
			"IMPORTANT: Do not step over next line of code. See method comments for details"
			Processor terminateRealActive] in FullBlockClosure(BlockClosure)>>newProcess in Block: [self value....

**Comment by Ducasse** [comment]
refactoringError: aString
	^ RBRefactoringError signal: aString

**Comment by Ducasse** [comment]
So I cannot work. Business as usual. 
People gets bugs!

**Comment by Ducasse** [comment]
self refactoringError: 'Cannot inline method since it contains multiple returns that cannot be rewritten'

**Comment by Ducasse** [comment]
How do reproduce :(

``` 
RBDummyTestData >> callerCaller1
	self caller1
```

- select callerCaller1
- Then bring the menu and invoke inlineSenders
- -> Boum

**Comment by MarcusDenker** [comment]
If people write wrong code, this is what happens. Look at RBRefactoring>>#onError:do:

```
onError: aBlock do: errorBlock
	^aBlock on: self class preconditionSignal
		do:
			[:ex |
			errorBlock value.
			ex return: nil]
```

the error block is executed with #value.


But then, it is used with an error block with one arg in RBInlineAllSendersRefactoring>>#inlineMessagesInClass:andSelector:

```
self onError:
						[self performCompositeRefactoring: ((RBInlineMethodRefactoring
									model: self model
									inline: node sourceInterval
									inMethod: aSelector
									forClass: aClass) checkOverridden: false).
						numberReplaced := numberReplaced + 1]
					do: [ :e | ]].
```

So when it sends the #value to the [:e |] block, you get a numArgsError: just as you should.  This has nothing to do with the block being constant or not.

The method RBRefactoring>>#onError:do: should be rewritten to use #cull: to hand in the paramenter optionally.

**Comment by Ducasse** [comment]
Well probably this code was there since years so we cannot expect people to know how the system will change, no?

**Comment by Ducasse** [comment]
This raises the questions of 
- what is wrong code?
- can we detect other usage like that.

**Comment by MarcusDenker** [comment]
the #onError:do: is not the Pharo onError:do:, it is  RBRefactoring>>#onError:do: This method is supposed to be called with a zero arg block, but someone calls it with a 1-arg lock in one of the refactorings.

**Comment by Ducasse** [comment]
In P10

```
RBRefactoring >> onError: aBlock do: errorBlock 
	^aBlock on: self class preconditionSignal
		do: 
			[:ex | 
			errorBlock value.
			ex return: nil]
```

**Comment by Ducasse** [comment]
```
RBInlineAllSendersRefactoring >> inlineMessagesInClass: aClass andSelector: aSelector 
	| messagesToInline previousCountOfMessages rbMethod |
	previousCountOfMessages := 4294967295.	"Some really large number > # of initial self sends."
	rbMethod := aClass parseTreeFor: aSelector.
	rbMethod ifNil: [ ^ self ].
	[ messagesToInline := self numberOfSelfSendsIn: (aClass parseTreeFor: aSelector).
	messagesToInline > 0 and: [previousCountOfMessages > messagesToInline]] 
			whileTrue: 
				[| node |
				previousCountOfMessages := messagesToInline.
				node := self selfSendIn: (aClass parseTreeFor: aSelector).
				self onError: 
						[self performCompositeRefactoring: ((RBInlineMethodRefactoring
									model: self model
									inline: node sourceInterval
									inMethod: aSelector
									forClass: aClass) checkOverridden: false).
						numberReplaced := numberReplaced + 1]
					do: [ :e | ]].
	numberNotReplaced := numberNotReplaced + messagesToInline
```

So I'm right. It was working before with this bogus definition and it means that we should find the places because else we will have bugs.

Sorry but when we change something then we cannot expect past users to see that their code will break in the future because we change something.

**Comment by MarcusDenker** [comment]
```
[ :e |  ] value
```

raises and error in Pharo10, too

**Comment by Ducasse** [comment]
Yes this is good that you changed the title I will fix it.
