### ISSUE TITLE
Cleanup: Refactoring package(s) should follow regular package naming order

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#13983]
We should have a package

- "Refactoring-Core-Tests" 
- "Refactoring-Environment-Tests"
- "Refactoring-Changes-Tests"
- "Refactoring-Critics-Tests"

instead of 

- "Refactoring-Tests-Core"
- "Refactoring-Tests-Environment"
- "Refactoring-Tests-Changes"
- "Refactoring-Tests-Critics"

to follow regular package naming order

**Comment by Ducasse** [comment]
Thanks! Good that I checked because I was starting to do it but I got lost looking for the issue :)
