### ISSUE TITLE
Unknown variable handling P11 vs. P12

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#13981]
In Pharo 11 when you select some text and hit CTRL+B (on Windows) you get a dialog to be able to select/correct:

![image](https://github.com/pharo-project/pharo/assets/5980033/c7c11f2f-f46c-4abb-85bb-45f067402520)

In Pharo 12 you get a debugger:

![image](https://github.com/pharo-project/pharo/assets/5980033/11f83b71-dd47-4a27-9e36-606976b91553)

**Comment by JanBliznicenko** [comment]
It seems to have been fixed as I was unable to reproduce it. Can you confirm?

**Comment by astares** [comment]
@JanBliznicenko Yes, I can confirm it is fixed now in a recent image and works again as in Pharo 11. We can close.
