### ISSUE TITLE
Make stdev answer 0 for one-sized collections

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#13993]
stdev is a method implemented in Collection of the package Collections-Arithmetic.

Right now, the result of sending stdev to one-sized collection is a ZeroDivide exception.

The standard deviation mathematically involves taking the square root of the variance, and the variance formula requires at least two values to compute meaningful results.

But in practice, calculating the stdev for a single value will always yield a result of zero since there is no variability or deviation from the single value (because there are no other values to compare it to). So technically we can calculate the standard deviation for a single value, although it may not provide meaningful information in that context.

Answering 0 is consistent with other programming languages implementations such as Python:

```python
import numpy as np
a = np.array([[4]])
print(np.std(a))

"0.0" 
```

R on the other side returns NA (it does not raise an Exception though)

```r
v <- c(1)
s<-sd(v)
print(s)
```

**Expected behavior**
Return a zero integer when sending #stdev to one sized collections.

**Expected development cost**
One-line addition to #stdev method.

**Screenshots**
![Screenshot 2023-06-12 at 12 35 30](https://github.com/pharo-project/pharo/assets/4825959/ddf8471b-9877-4f86-a13c-bfecdcb3c90a)

**Version information:**
 - Pharo Version: 12

**Comment by guillep** [comment]
I think this is a good idea ^^

**Comment by MarcusDenker** [comment]
PR merged
