### ISSUE TITLE
[P12] `RBVariable>>#isDefinition` does not return true when it should

### ISSUE THREAD

**Issue by adri09070** [guillep/pharo-core#14039]
**Bug description**

In P11, `RBVariableNode>>#isDefinition` returns `true` when the variable node represents a temporary variable "between `| |`, which seems logical to me.

In P12, it returns `false` in the same situation, which is wrong.

**To Reproduce**
1. Open a browser on `RBParser>>parseStatementList:into:untilAnyCloserOf:`
2. Inspect the method (Right-click on the method in the browser > Extra > inspect`
3. In the inspector pane, inspect `self ast body children first.`
You see that it represents the node defining the temporary variable named `statements`.
You can close the inspector.
4. In the same inspector pane, print `self ast body children first isDefinition.`
You see that it returns false.

**Expected behavior**
`self ast body children first isDefinition.` should return true

**Screenshots**

![Method inspection](https://github.com/pharo-project/pharo/assets/97704417/dce98208-b31d-4a2e-9f76-7b94729d0546)

![Inspecting the first variable node definition](https://github.com/pharo-project/pharo/assets/97704417/b3286dbc-5821-4568-803e-7eca46bafd3d)

![printing isDefinition expression](https://github.com/pharo-project/pharo/assets/97704417/db8e804d-39a9-4be1-bfd0-677df6afbf1b)

**Version information:**
 - OS: macOS Monterey
 - Version: 12.6
 - Pharo Version: 12

**Comment by MarcusDenker** [comment]
It seems to be the difference is that in Pharo11, the Variable of the defintion stayed a TemporaryVariable, for copied vars just the uses where changed to CopiedLocalVariable

In Pharo12, the defintion now is a CopiedLocalVariable, too. Which kind of makes sense, I think


Can you try to change the #definingNode for CopiedLocalVariable to 


```
definingNode
	^ scope node temporaries
		detect: [ :each | each variable == self ]
		ifNone: [ nil ]
```


I need to check if this change has any bad side effects (but tests are green)

**Comment by jecisc** [comment]
It would be nice to add a test on this also because this is a useful feature when manipulation ASTs.

**Comment by MarcusDenker** [comment]
yes, this definitly needs a test. There is 

RBVariableNodeTest>>#testIsDefinition
TemporaryVariableTest>>#testDeclaringNode
ArgumentVariableTest>>#testDeclaringNode

but it does not test the case where the temp is a copied var. (and the name testDeclaringNode needs to be change to #testDefiningNode).

This might be, too, a case for a regression test that tries to find all the definingNodes for all variables e.g. in Object

**Comment by adri09070** [comment]
> It seems to be the difference is that in Pharo11, the Variable of the defintion stayed a TemporaryVariable, for copied vars just the uses where changed to CopiedLocalVariable
> 
> In Pharo12, the defintion now is a CopiedLocalVariable, too. Which kind of makes sense, I think
> 
> Can you try to change the #definingNode for CopiedLocalVariable to
> 
> ```
> definingNode
> 	^ scope node temporaries
> 		detect: [ :each | each variable == self ]
> 		ifNone: [ nil ]
> ```
> 
> I need to check if this change has any bad side effects (but tests are green)

It looks like it works as I would like
