### ISSUE TITLE
Debugger does not evaluate in the context of the receiver

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#14034]
**Bug description**
In the debugger, do its are evaluated in the context of the current method's class.
This means that if I'm executing a superclass method on a subclass' instance, I cannot access variables defined down in the hierarchy (even if my instance supports it).

Example

- create a hierarchy like
A << B.
A has method foo.
B defines instace variable x.

- debug
`B new foo`

- step into `foo
- write `x`, select it and print it

The syntax highlighter correctly highlights the variable (OK!)
The compiler says that `x` is not defined and does not proceed with the doit (NOT OK!).

**Possible solution=**
I tracked the issue to 

```
OCContextualDoItSemanticScope >> targetClass
	^targetContext compiledCode methodClass
```

That should be changed to

```
OCContextualDoItSemanticScope >> targetClass
	^targetContext receiver class
```

**Comment by MarcusDenker** [comment]
Yes, that makes sense. It seems to be wrong in both Pharo11 and Pharo12

**Comment by privat** [comment]
The method should just be in OCDoItSemanticScope (and valid for both subclasses)

```st
OCDoItSemanticScope >> targetClass
	^self receiver class
```
