### ISSUE TITLE
Do we need a ReadStream for source in OpalCompiler (unnecessary conversion)

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#14080]
When you debug the compilation of the following source code string:

```Smalltalk
Smalltalk compiler compile: 'foo  3+4'
```
you will notice that initially OpalCompiler will set its own instance variable "source" by converting our source string into a **ReadStream** instance. This is done in OpalCompiler>>#source:

Later when the parser is created the compiler asks the ReadStream instance for its #contents - which then converts back the ReadStream into a ByteString instance. 

<img width="810" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/52ab84fe-ca31-41fc-a7b4-b196b4d71fd4">

This conversion is unnecessary - OpalCompiler does not make use of any of the stream facilities of the source.
And there are only three methods accessing the instance variable "source":

- OpalCompiler>>#createParser
- OpalCompiler>>#logDoIt
- OpalCompiler>>#source:

Each of these methods is accessing the source instance variable just returning the #contents - which is the ByteString again.

<img width="643" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/22194e1c-0eab-447a-87e9-d930425481e5">

**Comment by astares** [comment]
I think the conversion into a readStream is historic (when compiler was streaming over the source during parser step) - but now the parsing is done by a parser anyway. 

We should not let OpalCompiler>>#source: create a readStream but just set the instance variable
and change

OpalCompiler>>#createParser
OpalCompiler>>#logDoIt

to use the source instance variable (a string in that case) directly - without the additional #contents send.

This would avoid unnecessary ReadStream instances and might speed up also a little bit

**Comment by jecisc** [comment]
Nice catch :)

**Comment by privat** [comment]
Already fixed months ago in 7cb2ce7083dd2d0cf50d8eafcd9b1231ceaf8925

Note for next time: look at the current devel branch if what you found in stable is still valid.

**Comment by Ducasse** [comment]
Thanks Astares. Jean was a tornado and did a massive cleanup of the compiler. 
I imagine that there is more to improve :)
