### ISSUE TITLE
Enhance fonts details with scale factor

### ISSUE THREAD

**Issue by Mathilde411** [guillep/pharo-core#14107]
As discussed with @Ducasse it would be cool for this block of code (from @Rinzwind in https://github.com/pharo-project/pharo/issues/13767#issuecomment-1555858222_) to be automatically applied when changing display scale factor

```smalltalk
WorldMorph displayScaleFactor: 2.
SourceCodeFonts setSourceCodeFonts: SourceCodeFonts sizeSmall * WorldMorph displayScaleFactor.
ToggleWithSymbolMenuItemShortcut
	classVarNamed: 'SymbolFont'
		put: (LogicalFont familyName: 'Lucida Grande' pointSize: 10 * WorldMorph displayScaleFactor);
	classVarNamed: 'SymbolTable' put: nil.
ThemeIcons current: ((ThemeIcons named: 'svgPack') in: [ :themeIcons |
	(themeIcons respondsTo: #loadIconsFromUrlUsingScale:) ifTrue: [
		themeIcons loadIconsFromUrlUsingScale: WorldMorph displayScaleFactor ] ];
	yourself).
```
Thanks ;)

**Comment by Rinzwind** [comment]
I would suggest to close this. There is now another way to enhance the font details on Macs with a ‘Retina display’ that I think is better: see [pull request #15647](https://github.com/pharo-project/pharo/pull/15647), and my earlier [comment in pull request #14665](https://github.com/pharo-project/pharo/pull/14665#issuecomment-1721624999) about the use of the display scale factor versus the use of ScalingCanvas.

**Comment by Ducasse** [comment]
I will close it because to me you are much more precise in the understanding of the situation.
Thanks for the feedback.
