### ISSUE TITLE
#foo keywords should return #()

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#14140]
Three actions should be done
- add tests for keywords
```
#foo:bar: keywords 
> #(#foo: #bar:)
#name keywords
> #(#name )
#+ keywords
> #(#+)
```
- improve the method comments to tell that keywords return the receiver when this is a unary or binary message
- introduce a method call strictKeywords

```
#foo:bar: strictKeywords 
> #(#foo: #bar:)
#name strictKeywords
> #()
#+ strictKeywords
> #()
```

**Comment by MarcusDenker** [comment]
pr merged
