### ISSUE TITLE
Running test case with trait crashes VM (segmentation fault)

### ISSUE THREAD

**Issue by jvalteren** [guillep/pharo-core#14165]
**Bug description**
Running a test case which has a trait defined that decorates #performTest behavior crashes the VM immediately with a segmentation fault.
See crash dump file for details: [crash.dmp.txt](https://github.com/pharo-project/pharo/files/11916831/crash.dmp.txt)

**To Reproduce**
1. File in the attached MyTestTrait.st and MyTestCase.st (after renaming back from .txt extension).
2. Run the MyTestCase method #testWhatever from the class browser.
3. The VM crashes.

[MyTestCase.st.txt](https://github.com/pharo-project/pharo/files/11916840/MyTestCase.st.txt)
[MyTestTrait.st.txt](https://github.com/pharo-project/pharo/files/11916841/MyTestTrait.st.txt)

**Expected behavior**
The test case should run without problems.

**Version information:**
 - OS: macOS
 - Version: Monterey 12.6.6 (21G646)
 - Pharo Version: Pharo-11.0.0+build.689.sha.8986777f96ab65cba515d005d13487e0375fa85c (64 Bit)

**Comment by MarcusDenker** [comment]
I tried it in Pharo11 and it did not crash

**Comment by jecisc** [comment]
This also passes in Pharo 12. 

Maybe you VM is not up to date?

I'll close this issue for now. If the problem persist do not hesitate to open it again
