### ISSUE TITLE
Erasing the classification tag of an extension method leaves the method is an buggy state

### ISSUE THREAD

**Issue by jthulhu** [guillep/pharo-core#14185]
**Bug description**
When removing the classification tag of a method which is an extension, the "extension" check button is left on, yet clicking on it to disable the extension prompts for a package where the extension comes from.

**To Reproduce**
1. Open a method which is an extension in the browser, such as `Object>>#actionMap`. The extension button should be on, with the package `System-Object Events` being the proprietary of the extension.
 ![image](https://github.com/pharo-project/pharo/assets/23179762/2c126283-1f42-4191-b623-aacebf7379fb)
2. Click on the cross button, to erase the content of that label. 
![image](https://github.com/pharo-project/pharo/assets/23179762/319dd7b1-516f-440a-a7f2-451441bd615b)
The method is now in an inconsistent state, where it is marked as an extension, but has no information about who owns the extension.
![image](https://github.com/pharo-project/pharo/assets/23179762/0b3a5f8f-0676-434d-9fca-bf5f7f65230e)

3. Click on the check mark to try to unflag the method as an extension
![image](https://github.com/pharo-project/pharo/assets/23179762/c17838da-94e9-4be2-a792-af198e6a0b76)
 
4. Instead of unticking the check button, this will prompt a package name, as if the button was already unchecked and we just turned it on.

**Comment by jecisc** [comment]
Hi,
What is the version of Pharo that you are using?
The protocol management is been improved in Pharo 12 and I would like to make sure this is not fixed already in Pharo12

**Comment by jthulhu** [comment]
I am using Pharo 12, dating from june 30th (three days ago).

**Comment by jecisc** [comment]
I've seen that this was already present in previous versions of Pharo. I'll try to check the origin of the problem. This is probably a UI glitch
