### ISSUE TITLE
Failing tests: RBCodeSnippetTest>>testStyler

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#14191]
**Bug description**
Due to something that was merged the weekend July2, RBCodeSnippetTest>>testStyler is now failing 

```
Error
Got 'n"""ssss   uuuuu   uuu   uuuu"""uuuuu"""uuuuuuuuuuu"""' instead of 'n"""uuuu   uuuuu   uuu   uuuu"""uuuuu"""uuuuuuuuuuu"""'.
Stacktrace
TestFailure
Got 'n"""ssss   uuuuu   uuu   uuuu"""uuuuu"""uuuuuuuuuuu"""' instead of 'n"""uuuu   uuuuu   uuu   uuuu"""uuuuu"""uuuuuuuuuuu"""'.
RBCodeSnippetTest(TestAsserter)>>assert:description:resumable:
RBCodeSnippetTest(TestAsserter)>>assert:description:
RBCodeSnippetTest(TestAsserter)>>assert:equals:
RBCodeSnippetTest>>testStyler
RBCodeSnippetTest(TestCase)>>performTest
RBCodeSnippetTest>>performTest
```

```
Error
Got 'n ssss uuuuu uuu uuuu uuuuu uuuuuuuuuuu' instead of 'n uuuu uuuuu uuu uuuu uuuuu uuuuuuuuuuu'.
Stacktrace
TestFailure
Got 'n ssss uuuuu uuu uuuu uuuuu uuuuuuuuuuu' instead of 'n uuuu uuuuu uuu uuuu uuuuu uuuuuuuuuuu'.
RBCodeSnippetTest(TestAsserter)>>assert:description:resumable:
RBCodeSnippetTest(TestAsserter)>>assert:description:
RBCodeSnippetTest(TestAsserter)>>assert:equals:
RBCodeSnippetTest>>testStyler
RBCodeSnippetTest(TestCase)>>performTest
RBCodeSnippetTest>>performTest
```

**Comment by MarcusDenker** [comment]
The reason might be that there is now RBCondition class>>#true, which means that the styler does not color the message "true" in read anymore as we do have a selector.

**Comment by Ducasse** [comment]
But I have no idea what is the RBCodeSnippet.

**Comment by MarcusDenker** [comment]
It's a parametrized AST test.

Snippets are short code examples, there are ~350 of them. Then it runs tests parametrized using them: parsing, compiling, decompiling, syntax highlight... see the test in the class #RBCodeSnippetTest

 It runs 6679 test all in all.


what fails here is the test of syntax highlighting for

```
'1 true false nil self super thisContext'
```

**Comment by Ducasse** [comment]
I have no idea what is this bug. I checked the tests and well this is not a test that is made to be understandable.

And I'm sorry but adding a method true in an unrelated class should not break a test in an unknown part of the system. 
I would remove this test. In any case I will not spend my time fixing totally obscure test for a functionality that is not even documented and I did not touch this part of the system.

**Comment by Ducasse** [comment]
I do not understand how the styler can be related to RBCondition. If this is the case then we should stop Pharo. Because RBCondition are not part of the system but part of the refactoring engine.

**Comment by privat** [comment]
I will look at this one.

**Comment by Ducasse** [comment]
Ok Tx Jean. 
I renamed RBCondition true to true2 (which is a bad idea) and the tests still fail.

**Comment by privat** [comment]
The issue is in `SHRBMockTextStyler` (from Shout) that is used to checks styles of tokens. The thing is that shout asks to the global class Symbol (so the full image) to have information for information if a selector should be styled undefined or incomplete. Therefore, tests that use `SHRBMockTextStyler` are fragile as new methods in the image changes the test.

A solution is to fix SHRBMockTextStyler and stop using `Symbol` to known the color of identifiers but use some and specific mocked knowledge.
