### ISSUE TITLE
Object>>asOrderedCollection automatic deprecation transform causes wrong code

### ISSUE THREAD

**Issue by jbrichau** [guillep/pharo-core#14197]
**Bug description**
The deprecation and automatic rewrite of `Object>>asOrderedCollection` causes an issue when there is code in the image where the receiver can be both a `Collection` (subtype) and any other `Object` subtype.

The automatic rewrite is only correct if the `@receiver` of `asOrderedCollection` is never a `Collection`. However, that cannot be guaranteed statically. Since this rewrite is applied by default, you can run into strange situations when ran on a CI server before you understand what is happening.

**To Reproduce**
Implement the following testcase and run it twice while having the setting "Performs automatic transformations on deprecated methods" set to true. The first testrun will succeed and rewrite the code. The second testrun will fail.

```
testAutomaticRewrite

	| objects resultObjects |
	objects := { Object new . OrderedCollection new }.
	resultObjects := objects collect:[ :o | o asOrderedCollection ].
	self assert: resultObjects second isEmpty.
```

**Expected behavior**
While this obviously is a mistake in the code, the problem with automatic rewrite of this rule is that the resulting code is wrong. I expect it not be rewritten automatically.

**Version information:**
 Pharo Version 11

**Expected development cost**
I recommend removing the `transformWith:` in this deprecation declaration. It is not a safe transformation to do and I do not see a way to express a condition either.

**Additional context**
Because Pharo sets the transformation to true by default, the issue arises automatically in SmalltalkCI builds. We have now turned that off as well, but it was the first time we noticed this.

**Comment by Ducasse** [comment]
indeed!

**Comment by Ducasse** [comment]
So we should remove it because we cannot express not a collection. Or we could do a runtime check.
But what is a collection? Because not all the collection inherits from collection.

**Comment by jbrichau** [comment]
Fixed in https://github.com/pharo-project/pharo/pull/14237
Thx!

**Comment by jbrichau** [comment]
This is still present in Pharo12, reopening to also remove it there.

**Comment by Ducasse** [comment]
Sorry so what should we do. Personally I would remove asOrderedCollection from Object. This is a bad idea to have it there.

**Comment by jbrichau** [comment]
The deprecation is fine. It is the automated transform that is not correct (and impossible to do imho, because the method has different polymorphic implementations). An automated transform should always be correct, otherwise it should simply be deprecated and let a human handle it.

**Comment by Ducasse** [comment]
ok I will change it

**Comment by Ducasse** [comment]
In my P12 version there is no asOrderedCollection with transformation. I just get a deprecated on Object.
So did I get it wrong?
Can we close this issue then.

**Comment by jecisc** [comment]
This was fixed during the sprint

**Comment by Ducasse** [comment]
Tx cyril :)

**Comment by jbrichau** [comment]
@Ducasse I had referenced the PR that Cyril merged on friday. I thought this was clear that was why I reopened the issue. Thanks.
