### ISSUE TITLE
FileBrowser. View as hex not working

### ISSUE THREAD

**Issue by arturozambrano** [guillep/pharo-core#14209]
**Bug description**
(On Mac)
Pharo 12
Doing "View as hex" in the contextual menu of the content of file being shown by File Browser results in 
MNU. (\#binary)  

Pharo 11
Doing "View as hex" in the contextual menu of the content of file being shown by File Browser results in a crash (Pharo window is abruptly closed).

**To Reproduce**
1. Open File Browser
2. Select any file (could be text o binary)
3. Open the contextual menu in the pane that is showing the file content.
4. Select View as hex

**Version information:**
 - OS: Mac Os Monterrey
 - Version: 12.6.7
 - Pharo Version  11 & 12

**Comment by svenvc** [comment]
Here is another fix:
```
AbstractFileReference>>#binaryStreamWritable: writable do: aBlock
	^ writable
		ifTrue: [ self binaryWriteStreamDo: aBlock ]
		ifFalse: [ self binaryReadStreamDo: aBlock ]
```
and use it like this:
```
FileList>>#readContentsHex: brevity

	"retrieve the contents from the external file unless it is too long.
	  Don't create a file here.  Check if exists."

	| size data hexData s |

	self reference
		binaryStreamWritable:  false
		do: [ :f |
			f ifNil: [ ^ 'For some reason, this file cannot be read' translated ].
			( size := f size ) > 5000 & brevity
				ifTrue: [ data := f next: 10000.
					f close.
					brevityState := #briefHex
					]
				ifFalse: [ data := f contentsOfEntireFile.
					brevityState := #fullHex
					].

			s := ( String new: data size * 4 ) writeStream.
			0 to: data size - 1 by: 16 do: [ :loc |
				s
					nextPutAll: loc printStringHex;
					space;
					nextPut: $(;
					print: loc;
					nextPut: $);
					space;
					tab.
				loc + 1 to: ( loc + 16 min: data size ) do: [ :i |
					s
						nextPutAll: ( data at: i ) printStringHex;
						space
					].
				s cr
				].
			hexData := s contents
			].

	^ contents := size > 5000 & brevity
		ifTrue: [ '{1}
------------------------------------------
... end of the first 5000 characters.' translated format: {hexData}
			]
		ifFalse: [ hexData ]
```

**Comment by svenvc** [comment]
Looking at this a bit more, #streamWriteable:do: in only ever called with false as first argument, so it is 100% equivalent to #readStreamDo:

Unless I am missing something, we could simply things a bit and remove a method instead of adding a new one.

Where necessary (as in this issue), #binaryReadStreamDo: needs to be called.

**Comment by MarcusDenker** [comment]
PR was merged
