### ISSUE TITLE
ClassInstaller: Improve installation in non default environment

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#14221]
I tried to use the class installer in order to install a class in a non-default environment in the image but that does not seem to be easy. 

In the end I ended up with this code:

```st
	| newEnvironment |
	newEnvironment := SystemDictionary new.
	newClass := ShiftClassInstaller new
		            installingEnvironment: (ShSmalltalkGlobalsEnvironment new
				             environment: newEnvironment;
				             yourself);
		            make: [ :builder |
			            builder
				            name: #SHClassForTest;
				            superclass: Object;
				            category: self generatedClassesPackageName ].
```

I am wondering, can't we do easier? Do we really need ShSmalltalkGlobalsEnvironment? Can't we just add the methods it has on SystemDictionary and give that as an environment directly? Do we need this intermediate class? If yes, can't we add some syntactic suggar to make this easier?

My goal is to be able to have tests that generates classes and that are not installed in the default system and that seems to be painful to do.

**Comment by jecisc** [comment]
On top of this, the class gets added to the wrong package organizer because it is added through the SystemOrganizer and the system organizer is adding everything to the default package organizer of the image...

This will be a mess really difficult to untangle.

**Comment by privat** [comment]
I tried to look at that when I played with the compiler, and also when I played with undeclared variables. A lot of things assume a default environment, other things offers complex, fragile or untested API and lots of unanswered questions.

Related to #13563 maybe...

**Comment by jecisc** [comment]
The problem is that we currently have 2 "package management" in the image. 

One is the historical "SystemOrganizer" (the class is not there anymore, I merged the content in RPackageOrganizer) and the second is RPackageOrganizer. 

When we install a class in the system, it gets install in the SystemOrganizer and through announcements the organizers are trying to do their thing. But we only have one SystemOrganizer in the image even if we can have multiple RPackageOrganizer. Because of this, we have some hacks in RPackage but I'm trying to remove them because they are making the code incredibly complexe for nothing. 

I'm trying to merge the SystemOrganizer into RPackageOrganizer so that we only have one package manager and not two, but this is not an easy task because RPackageOrganizer is too complex for what it does, it is full of bugs, it is missing features and on top of that, some changes do not pass because Espell assume things that I want to change and Espell is currently in a state that makes it hard to modify it. 

So I'm trying to find my way around all those complications ahah

**Comment by jecisc** [comment]
Done!
