### ISSUE TITLE
In debugger cannot recompile method that accepts

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#14234]
I cannot recompile a method that accesses an instance variable.

**Comment by Ducasse** [comment]
<img width="1182" alt="Capture 2023-07-06 at 17 40 15" src="https://github.com/pharo-project/pharo/assets/432549/c516466b-077e-49c2-a6ac-1ee53825a318">

**Comment by Ducasse** [comment]
I had a method that was shadowing an instance variable, so I removed the temporaries and recompiled the method.

**Comment by MarcusDenker** [comment]
Yes, we do not allow compiling code with Undeclared variables.

I think we should (slowly) explore if it would not be indeed better if we would compile an Undelared in this case and have the tools react nicely (and guide the user to fix it) without blocking the flow with the popup.
