### ISSUE TITLE
Multiplication with Integer and ScaledDecimal operands has different scale depending on argument order

### ISSUE THREAD

**Issue by daniels220** [guillep/pharo-core#14238]
**Bug description**
Multiplying an integer and ScaledDecimal produces a result with a different scale value depending on argument order:

```
1.12s * 2 "=> 2.24s, i.e. scale = 2"
2 * 1.12s "=> 2.2400s, i.e. scale = 4"
```

While the two results still compare as equal, this is definitely pretty weird for a commutative operation, and it seems wrong in general for multiplication by an integer to increase the scale.

**Expected behavior**
Keep the scale from the ScaledDecimal operand.

**Version information:**
 - OS: Any
 - Version: Any
 - Pharo Version: Any AFAIK, definitely true in 11

**Expected development cost**
I think all that is needed is to coerce Integer to ScaledDecimal with scale 0 instead of that of the ScaledDecimal operand. For other operations, the max of the two is used instead of the sum, so this shouldn't change the result. Pull request inbound shortly.

**Comment by daniels220** [comment]
Actually, this applies if the other operand is a Fraction as well, and there's a question: Does a Fraction contribute nothing to the scale, or do we want it to compute the scale needed to represent it (as in the unary `Fraction>>asScaledDecimal`) and use that? I'm inclined towards the former, because having the scale jump by 8 when multiplying by `(1/3)` seems wrong—especially since this does _not_ happen when dividing by 3.

**Comment by daniels220** [comment]
Worth noting that this is a regression introduced by the fix to #8668—previously all four arithmetic operations used the `max:` of the scales of the two operands, so coercing an integer to have equal scale to the ScaledDecimal had no impact.

**Comment by guillep** [comment]
Hi @daniels220 ! good catch! :)

I'm ok with a solution that does not lose precision :) So, please do not hesitate to propose something!

**Comment by daniels220** [comment]
See #14259. Note that in general no arithmetic operation will ever truly lose precision—the scale only affects display, the underlying value is always full-precision. So treating non-ScaledDecimals as having scale 0 does not mean they will be rounded, only that they won't affect the declared scale of the result.
