### ISSUE TITLE
Merge ReDetectIfNoneRule and ReAnySatisfyRule

### ISSUE THREAD

**Issue by balsa-sarenac** [guillep/pharo-core#14239]
There are two warnings in editor both give the same information, but one has auto-fix and the other one doesn't. It would be nice to remove duplication and keep only the one with the auto-fix.
You can check the image below and that method for example.

<img width="646" alt="Screenshot 2023-07-08 at 15 59 57" src="https://github.com/pharo-project/pharo/assets/34557616/5d47d495-c484-442f-a1b7-33e45db4850b">

**Comment by MarcusDenker** [comment]
There seem to be two rules:

1. ReAllAnyNoneSatisfyRule
2. ReAnySatisfyRule

It would be good to merge them. Maybe this is as simple as removing the one without transform (ReAnySatisfyRule)
