### ISSUE TITLE
ensurePackage: and removePackage: as ensurePackageNamed: and removePackageNamed:

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#14286]
As title said.

**Comment by Ducasse** [comment]
this one too self unregisterClassName: aClassNameSymbol
 self unregisterClass: aClassNameSymbol
because  self unregisterClass: aClassNameSymbol is not nice.

**Comment by jecisc** [comment]
In this particular case, I plan to refactor more and the register/unregister methods should vanish altogether

**Comment by Ducasse** [comment]
Cool!

**Comment by jecisc** [comment]
The registering and unregistering of package changed a lot. I think we can close this one
