### ISSUE TITLE
WebBrowser openOn: 'http://pharo.org/' fails on Win10&11, Pharo10,11&12

### ISSUE THREAD

**Issue by ironirc** [guillep/pharo-core#14301]
I noticed there's a problem with opening a webbrowser (tested on Win10&11, Pharo10,11&12, 2 separate machines)
WebBrowser openOn: 'http://pharo.org/'
The string doesn't get properly encoded (or something), resulting in the browser opening on the url, with some random characters added (e.g. "http://pharo.xn--org-kha/").  

Changing following method by adding utf8Encoded fixes the problem:
```Smalltalk
openNativeWebBrowserOn: anURLString
  ^self shellExecute: 'open' file: (anURLString utf8Encoded)  parameters: '' directory: '' show: 5
  ```

**Comment by astares** [comment]
Mmmh ... strange
```Smalltalk
WebBrowser openOn: 'http://pharo.org/'
```
works like a charm for me.

**Comment by astares** [comment]
Sure you have latest VM?

**Comment by ironirc** [comment]
`WebBrowser openOn: 'http://pharo.org/'` also works for me.
BUT
`WebBrowser openOn: 'http://pharo.org'` fails?

Alternatively, click the play button on:  `WebBrowser class>>#example`

Now I'm wondering why I put a trailing slash from in the title.

Now I also need a different patch (which might make more sense):
```Smalltalk
openNativeWebBrowserOn: anURLString
  ^self shellExecute: 'open' file: (anURLString nullTerminatedEncodeWith: #utf8)  parameters: '' directory: '' show: 5
```

**Comment by astares** [comment]
@ironirc Can you check again please in Pharo 12. I think this was fixed and we can close.

**Comment by ironirc** [comment]
Just checked again on Pharo 12 with a doit on:
WebBrowser openOn: 'http://pharo.org/'

<blockquote><img src="/files/favicon.ico" width="48" align="right"><div><strong><a href="http://pharo.org/">Pharo - Welcome to Pharo!</a></strong></div></blockquote>
