### ISSUE TITLE
Iceberg: browse deleted method in commit browser fails

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#14300]
Pharo 11:
Try to browse a removed method in Iceberg commit browser when using "Browse" from menu:

![image](https://github.com/pharo-project/pharo/assets/5980033/f65efe20-c38d-4e89-be7c-3d2ff68cbedd)

Reproduce:
- delete a method
- click on "Commit" in Iceberg repo
- when Iceberg shows difference that method was deleted use the "Browse" menu entry

One gets a KeyNotFound

![image](https://github.com/pharo-project/pharo/assets/5980033/7a8f452a-e225-4674-9292-5ecdc34bf9f1)

Havent checked yet in Pharo 12

**Comment by jecisc** [comment]
We should probably add a condition to the browse action to check that it is not a removal since it is obvious you cannot browse something that got removed.

**Comment by jecisc** [comment]
https://github.com/pharo-vcs/iceberg/pull/1720

**Comment by astares** [comment]
Thanks!
