### ISSUE TITLE
`UndeclaredVariableWrite` and others when loading the pharo repository inside an image

### ISSUE THREAD

**Issue by Mathilde411** [guillep/pharo-core#14305]
**Bug description**
When loading the Pharo12 branch inside an image, I get lots of errors from RPackage:
 - Attempted to write to undeclared `protocol` variable inside `ProtocolRemoved`
 - `#name` was sent to nil inside `EpMonitor>>#methodRemoved:`
 - `CompiledMethod` did not understand `#isExtention`

**To Reproduce**
1. Open a new pharo image (this morning at least)
2. Load the latest pharo commit

**Expected behavior**
Everything loads without error

**Comment by jecisc** [comment]
Seems related to https://github.com/pharo-project/pharo/issues/13273
