### ISSUE TITLE
FileLocator, FileSystems, and copyTo: don’t play nicely

### ISSUE THREAD

**Issue by hellerve** [guillep/pharo-core#14338]
**Bug description**
A code path in `FileReference>>#copyTo:` that is only hit when the file systems of the source and destination paths are not equal fails to resolve the file reference, which works well when we have a regular file reference, but fails when we pass in, say, a `FileLocator` instance. This is due to `path` in `FileLocator` behaving in a special way, returning a relative instead of an absolute path.

**To Reproduce**

Execute the following script:

```pharo
"create an in-memory file"
fromFile := FileSystem memory   root / 'foo.txt'.
fromFile writeStreamDo: [:aStream | aStream nextPutAll: 'hello' ].

"create a file locator"
toFile := FileLocator temp / 'example' / 'bar.txt'.
toFile ensureDelete.
toFile parent ensureCreateDirectory.

"try to copy, this is where we fail"
fromFile copyTo: toFile.

"assertions and cleanup for testing
self assert: toFile contents equals: 'hello'.
toFile parent ensureDeleteAll.
```

**Expected behavior**
Copying should work.

**Screenshots**
Not applicable

**Version information:**
 - OS: macOS 
 - Version: 13.4.1
 - Pharo Version :10.0.4

**Expected development cost**
I have a fix ready and am happy to provide it. It should be simple. I can also provide the above script as a test case for regressions.

**Additional context**
None.

**Comment by jecisc** [comment]
If you have a fix ready and a regression test do not hesitate to open a PR :)

Contributions are really welcomed

**Comment by jecisc** [comment]
Fixed
