### ISSUE TITLE
DoubleLinkedList>>asArray should recursive visit

### ISSUE THREAD

**Issue by liangbing64** [guillep/pharo-core#14361]
My element could be aDoubleLinkedList too, So
```
asArray
	"Return a new Array containing my elements"

	^ Array streamContents: [ :out |
		self do: [ :each | 
			out nextPut: ( 
				(each isKindOf: DoubleLinkedList )
					ifTrue: [ each asArray ]
					ifFalse: [ each ])
				]
		]
		self do: [ :each | out nextPut: each ] ]
```

**Comment by JanBliznicenko** [comment]
Hello, should it really?

I mean, why should using `asArray` on a `DoubleLinkedList` of `DoubleLinkedList`s be interpreted as array of arrays, while using it on a `Set` of `Set`s produces array of sets? Why should `DoubleLinkedList` behave differently to all other collection types?

**Comment by Ducasse** [comment]
I do not really understand the problem. This issue is not really clear.

**Comment by liangbing64** [comment]
DoubleLinkedList using head and tail to implement double visiting its elements (aDoubleLink).  There are two  DubledLiskedList A, B ,   B is an element of A ,   so the answer of A asArray should include arrayB (as anArray of B asArray ) not all element of B.

**Comment by liangbing64** [comment]
for an example, using DoubleLinkedList to analyse syntactic of complex sentences, B is a sub sentence of A (complex sentence)

**Comment by Ducasse** [comment]
Thanks for the information. Could you give a Unit test or two about it. Like that we can understand the problem because it is unclear to me.

**Comment by Ducasse** [comment]
Here is the current implementation as defined in the superclass of DoubleLinkedList

```
Collection >> asArray

	"Answer an Array whose elements are the elements of the receiver.
	Implementation note: Cannot use ''Array withAll: self'' as that only
	works for SequenceableCollections which support the replacement
	primitive."

	"'ab' asArray >>> {$a. $b}"
	"(1 to: 5 by: 3) asArray >>> {1. 4}"

	"#(1 2) asArray == #(1 2) >>> true"

	"'' asArray >>> #()"
	"(10 to: 5) asArray >>> #()"

	| newArray index |
	newArray := Array new: self size.
	index := 0.
	self do: [ :each | newArray at: (index := index + 1) put: each ].
	^ newArray
```

**Comment by liangbing64** [comment]
I found the problem, I used Pharo8 ，DoubleLinkedList's super class is Object， but after Pharo11, DoubleLinkedList is Collection's subclass.     so using Collection>> asArray  works fine.  this issue should be closed.

testMyElementAsDoubleLikedList
	| list list2 |
	list := DoubleLinkedList new.
	list2 := DoubleLinkedList new addAll: #(4 5 6 ).
	list addAll: #(1 2 3 ) ; add: list2.
	self assert: list asArray equals: #(1 2 3 #(4 5 6 ))

"because of Object>>asDoubleLink , any object can be an element of DoubleLikedList  "
