### ISSUE TITLE
The same image started for the second time hangs on Windows

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#14367]
**Bug description**
When you open an image for the second time and the image was saved before, the image immediately hangs. Before, it showed a warning (using `inform:`) about the read-only changes file. When the same is done with the plain vanilla image without any modifications, it does not hang but does not show the warning as well.

This bug was introduced in the build 537 via this PR: https://github.com/pharo-project/pharo/pull/14180 (@Ducasse) 

**To Reproduce**
Variant 1:
1. Open new fresh image from the Pharo Launcher
2. Open the same image for the second time
3. No warning is shown.

Variant 2:
1. Open new fresh image from the Pharo Launcher
2. Save the image
3. Open the same image for the second time
4. Image hangs (User interrupt shoud work).

**Cause**

```smalltalk
StartupUIManager>>#inform: aString
	(ProvideAnswerNotification signal: aString)
		ifNotNil: [:answer | ^true].
	self sessionManager
		addDeferredStartupAction: [ self inform: aString ]
```

Originally, instead of ` self inform: aString`, it called `UIManager default inform: aString`. Now it makes a recursion.

**Screenshots**

**Version information:**
 - OS: Windows
 - Pharo Version: 12 (>=537)

**Comment by Ducasse** [comment]
Still there.

**Comment by Ducasse** [comment]
I do not understand why this class should pop up something so for now I write to the Transcript. 

```
inform: aString
	(ProvideAnswerNotification signal: aString)
		ifNotNil: [:answer | ^ true].
	self sessionManager
		addDeferredStartupAction: [ self traceCr: aString ]
```

**Comment by Ducasse** [comment]
I have no idea what is this but it looks quite bad to me.
![Capture 2023-11-19 at 15 04 23](https://github.com/pharo-project/pharo/assets/432549/497c74fb-0c1d-4b1f-9229-274f82b425ea)

**Comment by Ducasse** [comment]
The logic of the reason why we have a StartupUIManager is obscure. Ok we need a kind of placeholder to launch the Morphic UI manager. :(

**Comment by Ducasse** [comment]
@pavel-krivanek Can you tell me if the change is solving the problem because I cannot reproduce it on my machine.

**Comment by pavel-krivanek** [comment]
Yes, writing to the Transcript solves the problem. Tested in:

Pharo 12.0.0
Build information: Pharo-12.0.0+build.1084.sha.d7c12ac740d3cb1fbd203ebd087cc3ddec555b20 (64 Bit)

Do you wish to close the issue?

**Comment by Ducasse** [comment]
Thanks Pavel. 
I will close since the changes got integrated.
