### ISSUE TITLE
There are now two method rename refactorings

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#14371]
**Bug description**
The method context menu now provides two method rename refactorings with no information about their differences.

![image](https://github.com/pharo-project/pharo/assets/572494/e5669311-bd7b-4c85-a3f4-9620b4868f39)

There is newly added class `#SycRenameMessage2Command` added in this PR: https://github.com/pharo-project/pharo/pull/14161/files (@Ducasse), it has no class comment nor another description so it is not clear what is going on here

**Version information:**
 - Pharo Version: 12

**Comment by Ducasse** [comment]
Yes this is normal we are working on it. So I will close the issue.

**Comment by MarcusDenker** [comment]
as this is work in progress, I close this issue
