### ISSUE TITLE
"Pharo30Bootstrap" file still required?

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#14380]
Is this file still needed:

https://github.com/pharo-project/pharo/blob/Pharo12/bootstrap/src/Pharo30Bootstrap

I think we can remove it. There is no similar file in /src

**Comment by jecisc** [comment]
For now the bootstrap is using this file.

i tried to change the bootstrap to not point this symlink but use the real file (in /src) instead but it was not straightforward.

**Comment by MarcusDenker** [comment]
The file is now a symlink
