### ISSUE TITLE
Class category names are case sensitive and package names case-insensitive

### ISSUE THREAD

**Issue by chisandrei** [guillep/pharo-core#14431]
Seems that class category names are handled as case-sensitive and package names as case-insensitive.

Consider the following two classes. One is created in package `TestPackage one`, and the second in package `TestPackage ONE`

```
Object subclass: #TestClassA
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'TestPackage one'.
	
Object subclass: #TestClassB
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'TestPackage ONE'.
```

If we execute the code and get the package of the second class `TestClassB`, we get `TestPackage one`, as there exists only one package in the system `TestPackage one`. But the category is still `TestPackage ONE`. 

```
TestClassB package  "a RPackage(TestPackage one)".
TestClassB category.  "#'TestPackage ONE'"

RPackage  organizer includesPackageNamed: 'TestPackage one'. "true"

RPackage  organizer includesPackageNamed: 'TestPackage ONE'. "false"
```

This creates a mismatch in tools. For example we get a new tag named `TestPackage one-TestPackage ONE`:

<img width="1792" alt="Screenshot 2023-08-04 at 13 58 42" src="https://github.com/pharo-project/pharo/assets/3534711/c0ed594e-ce39-41b0-a9a5-a472c87e1d93">

Tested in both Pharo 10 and Pharo 11.

This can happen when loading changed that rename a package changing just the capitalization.

**Comment by jecisc** [comment]
Hi Andrei,

I noticed that too. In Pharo 12 I am doing a massive revamp of RPackage and SystemOrganizer and this is on the list of things I wand to check. If everything goes right, this should be fixed before the Pharo 12 release. I'm not fixing it right now because I am doing a lot of simplifications in RPackage and I want the code to be cleaner before hunting the few places that forget to check in an insensitive way

**Comment by jecisc** [comment]
In Pharo 12 everything is case insensitive. The category match the package and tag

**Comment by jecisc** [comment]
```st
Object subclass: #TestClassA
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'TestPackage one'.
	
Object subclass: #TestClassB
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'TestPackage ONE'.
	

TestClassA package.	 "a RPackage(TestPackage one)"
TestClassA category.  "#'TestPackage one'"
TestClassB package. "a RPackage(TestPackage one)"
TestClassB category "#'TestPackage one'"
```
