### ISSUE TITLE
RBEnvironmentVisitor>>#visitClassEnv: has dead code

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#14433]
This might be dead code. Maybe it can interest @balsa-sarenac or @Ducasse

**Comment by Ducasse** [comment]
Thanks. I do not even know if this method is used. In fact the environment should be used for more than the refactoring engine.

**Comment by MarcusDenker** [comment]
Duplicate of https://github.com/pharo-project/pharo/issues/14721
