### ISSUE TITLE
Builld looks broken:  Instance of Time class did not understand #millisecondsSince: 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#14460]
```
Time class >> millisecondsSince: lastTime
 	"Answer the elapsed time since last recorded in milliseconds.
 	Compensate for rollover."

 	^self milliseconds: self millisecondClockValue since: lastTime
```

is originally packaged in Chronology extras

**Comment by MarcusDenker** [comment]
My theory is that a RPackage related change is the reason that we somehow loose the extension method.

It has to be one of the PRs merged yesterday, I think

**Comment by MarcusDenker** [comment]
The build works for the revert of https://github.com/pharo-project/pharo/pull/14449

see https://github.com/pharo-project/pharo/pull/14461

**Comment by MarcusDenker** [comment]
the revert fixed the problem
