### ISSUE TITLE
Browse in the Inspector does not work

### ISSUE THREAD

**Issue by jordanmontt** [guillep/pharo-core#14485]
When you have an inspector opened with an object and you want to browse the class, it is looking for the implementors instead.

For example:
<img width="989" alt="image" src="https://github.com/pharo-project/pharo/assets/33934979/35cb5b8a-652f-4170-b1ca-38e78b9a3dea">

The same happens with the key binding `cmd + B`
<img width="989" alt="image" src="https://github.com/pharo-project/pharo/assets/33934979/f57dfef2-0969-4fca-8c27-ae0135c42aa3">

**Comment by hernanmd** [comment]
Which Pharo version?
It works well for me on integers and empty ordered collection in both Pharo 11 and 12.

**Comment by jordanmontt** [comment]
In Pharo 12 just downloaded image

**Comment by jordanmontt** [comment]
But it has to be from the Inspector. From the Playground it works.

For example look this video that shows that from the inspector does not work when trying to browse.
![Enregistrement-de-lecran-2023-08](https://github.com/pharo-project/pharo/assets/33934979/9fe3022e-c29b-4a4e-a0eb-b2356e0850a4)

**Comment by ValentinBourcier** [comment]
I think this is related to: https://github.com/pharo-spec/Spec/commit/62824ec51e89683313dde4db1e0303a5674f7bb1.
After syncing Spec's version to this commit, I don't face the issue anymore.

**Comment by Ducasse** [comment]
I remove my code and I will work on a private project.

**Comment by Ducasse** [comment]
So normally this should work again. 
Browse was not working in debugger pane too.

**Comment by Ducasse** [comment]
Can you reopen if the latest version does not fix it?

**Comment by jordanmontt** [comment]
Yes, not it is fixed in the latest Pharo 12. I will close the issue
