### ISSUE TITLE
Pharo 11 doesn't seem to work with image paths that include Unicode on Windows 10

### ISSUE THREAD

**Issue by sdasda7777** [guillep/pharo-core#14483]
**Bug description**
I tried running current nightly build of [OpenPonk](https://github.com/OpenPonk/plugins), and I noticed it was broken (`openponk-plugins.bat` (the launcher) didn't appear to do anything). After [much debugging](https://github.com/OpenPonk/plugins/issues/11), I determined it is a bug in Pharo that only appears in paths with Unicode characters (earlier builds on Pharo 10 had no such issue and work to this day), and sure enough, I am able to replicate it with [standalone Pharo](https://pharo.org/download):

```batch
:: Run as a .bat script, %~dp0 (absolute path to batch file folder) isn't set otherwise!

:: This works as expected (but cannot be launched from a different folder)
start "" "pharo-vm-Windows-x86_64-stable\Pharo.exe" "pharo64\Pharo11-SNAPSHOT-64bit-123d0c9.image" 

:: Absolute executable path still works, probably because the path of the executable isn't handled by Pharo
start "" "%~dp0pharo-vm-Windows-x86_64-stable\Pharo.exe" "pharo64\Pharo11-SNAPSHOT-64bit-123d0c9.image" 

:: Absolute image path doesn't work when there's Unicode in the current path
start "" "pharo-vm-Windows-x86_64-stable\Pharo.exe" "%~dp0pharo64\Pharo11-SNAPSHOT-64bit-123d0c9.image" 

:: Doesn't currently work either (but allows launching any folder, due to using absolute paths)
start "" "%~dp0pharo-vm-Windows-x86_64-stable\Pharo.exe" "%~dp0pharo64\Pharo11-SNAPSHOT-64bit-123d0c9.image"
```
The crash can also be replicated when selecting the image manually through the file picker, since the absolute path is likely used there as well.

Since this breaks another project, I hope it's obvious this should be fixed as soon as possible.

**Expected behavior**
Pharo should run, no matter the Unicode characters in the path of anything.

**Observed behavior**
Pharo 11 crashes when the loaded image has Unicode characters in the path (Unicode in executable's path doesn't matter).

**Version information:**
 - OS: Windows
 - Version: 10
 - Pharo Version: 11

**Comment by sdasda7777** [comment]
Still not working as of 2023-10-06, which I find genuinely concerning.

**Comment by JanBliznicenko** [comment]
A simpler example of the issue:

`a.image` opens
`á.image` does not

![obrazek](https://github.com/pharo-project/pharo/assets/9571633/8f6579ea-ea3f-413c-a80e-bbb769f145ea)

Same applies if the non-ASCII char is anywhere in the image path argument provided to the Pharo.exe, whether the path is absolute or relative.

It does not matter if we are in a directory with non-ASCII char or not, all the matters is if the non-ASCII char is in the argument. If we are in the directory with non-ASCII chars and provide relative path with pure ASCII, then it works.

**Comment by JanBliznicenko** [comment]
I created the issue in the VM repository, as this is VM issue: https://github.com/pharo-project/pharo-vm/issues/707

**Comment by sdasda7777** [comment]
Ah, I should have realized that. Thanks!
