### ISSUE TITLE
Refactorings: Removing methods with sender does not work when used via the shortcut

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#14490]
In the latest Pharo 12 I cannot remove a method with senders.

How to reproduce:
- In Calypso launch a remove action on a method with senders using cmd + x with a method selected
- You get prompt a choice between not removing the method, removing it and browse the sender or just removing it
- Select "Remove it"

And nothing happens.

If I use the refactoring via the menu it works.

Also it would be nice to have an option selected by default and to be able to navigate with the keyboard in this UI

**Comment by balsa-sarenac** [comment]
Removing via the shortcut calls the old implementation which should be deprecated soon.

Agreed on default selection, it's a nice UX improvement.

**Comment by jecisc** [comment]
But the windows that opens is the new refactoring window, not the old one

**Comment by balsa-sarenac** [comment]
I was not able to reproduce this. For me it displays a window with changes and after accepting the method gets removed.
Could you check if it works now? Maybe the PR from yesterday fixed this issue, because I think I had it yesterday as well, now that I think of it.

**Comment by jecisc** [comment]
This works now thanks
