### ISSUE TITLE
Browse an argument does not work anymore

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#14519]
Probably due to my changes browsing an argument in the debugger does not work anymore. :(

**Comment by MarcusDenker** [comment]
"Browse it" is fundamentally problematic as if nothing is selected, it selects the whole line and executes this selection, but the user has no idea what that this is even happening.

If (by chance) the line makes sense, it will get executed and could have really bad side effects.

In the case of the method signature, it selects the whole line and then tries to execute that to browse the result.

We really have to re-think it.

Example: Imagine writing a method in AnnouncerTest:

```
myMethod 

	self removeSelector: #testSubscribersForClass
```

now I would like to browse the implementor of #removeSelector:, and I use browse it for that. So I position the cursor somewhere in the "removeSelector" string, press "cmd b", and BOOM, it removed the method #testSubscribersForClass from that class.

Do we know what people destroy every day while using "browse it"? I could explain some of the odd bugs that those see who use it a lot (I never use it, as I just do not want random execution while navigating code).

**Comment by Ducasse** [comment]
Marcus your way of coding is not the way of others. We should find a way that makes everybody productive.
I do not get your example because self is not bound. so at least it can break if this is in a metaclass.

**Comment by Ducasse** [comment]
I will revert my changes and keep them for me and I will load them because I cannot work fast with the default setup.

**Comment by Ducasse** [comment]
And this is since P12 that we lost the coding in the method / class pane. 
And everyday I have around 10 times an error because of it!

**Comment by Ducasse** [comment]
I reverted my changes in Morphic and Spec. 
So this bug will be removed automatically and I will work on my own stuff.

**Comment by MarcusDenker** [comment]
It will I guess not solve the problem: Browse it will still silently select the line and evaluate. If that line has a syntax error, this will result in a syntax error.


In addition,  It is not easy to  understand what "browse it" is supposed to do. It's somehow a mix of "eval and browse class" and "browse this". 

We need to clearly define what we  want. And we need to get rid of the silent selection and instead delegate to the AST.  That alone will clear things up *a lot*.

The thing is that this is not simple and needs some thinking.

**Comment by MarcusDenker** [comment]
I checked and it is exactly the same in Pharo10 and Pharo11: as nothing is selected, Browse-iT silently selects the whole line, tries to evaluate it, this fails.

This is how "Browse it" is implemented: evaluate the selection and browse the class of the result. If nothing is selected, select the line. If the the selection can not be evaluated due to it not being syntactically correct, fail.

**Comment by MarcusDenker** [comment]
So the selection is not the line (that used to be that way in ST80), but instead there is a  method that is a bit more intelligent:

RubSmalltalkEditor>>#widenSelectionIn:selection:ifFound:

this selects e.g. a global variable correctly, this is why if you select nothing but have the cursor on a Class (like "Object"), it will select the string "Object", this then is evaluated by cmd-B. But the mechanism does not work in the first like when the cursor is on the argument. When it is on a selector, it selects the whole message send.

Instead, we should not work with strings: just delegate to the AST, then we can, for every node, implement what we want.
