### ISSUE TITLE
CI build is broken with DNU millisecondsSince:

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#14527]
many PR are blocked with the same error.

millisecondsSince: is packaged in an extension and apparently it is lost.

**Comment by MarcusDenker** [comment]
this was already broken in the past when we merged the first version of

https://github.com/pharo-project/pharo/pull/14462

So maybe this one makes problems, again

**Comment by jecisc** [comment]
The weird thing is that the build for the Pr worked and multiple other worked after its integration. Or maybe it is random?

**Comment by jecisc** [comment]
I have an idea why this is happening. I'll try to do a PR to fix it if my idea is right and I'll explain the problem in this PR

**Comment by Ducasse** [comment]
What I saw is that I cannot merge the revert because of 
```
#StartupPreferencesLoader #FileSystem)
++ date -u
+ echo Fri Aug 25 12:47:41 UTC 2023 '[Compiler] Initializing the packages in the Kernel'
Fri Aug 25 12:47:41 UTC 2023 [Compiler] Initializing the packages in the Kernel
+ /builds/workspace/est_and_branch_Pipeline_PR-14528/64/bootstrap-downloads/vmtarget/pharo --headless Pharo12.0-PR-compiler-64bit-cdc4285.image --no-default-preferences initializePackages --protocols=protocolsKernel.txt --packages=packagesKernel.txt --save
Instance of RPackage did not understand #addClassDefinition:
RPackage(Object)>>doesNotUnderstand: #addClassDefinition:
RPackageOrganizer>>initializeFor:
```
