### ISSUE TITLE
Code Changes filter doesn't work

### ISSUE THREAD

**Issue by balsa-sarenac** [guillep/pharo-core#14529]
**Bug description**
Epicea - Code Changes filter doesn't work.

**To Reproduce**

0. Open an image with some changes, or perform some changes
1. Go to Code Changes 
2. Select one change from the list
3. Start typing

**Expected behavior**
List should filter its content and only show items that match entered string.

**Screenshots**

<img width="950" alt="Screenshot 2023-08-25 at 15 14 59" src="https://github.com/pharo-project/pharo/assets/34557616/7d243c05-3832-444d-9701-4b90732df296">

**Version information:**
 - OS: iOS
 - Pharo Version 12

**Comment by hernanmd** [comment]
This is fixed in P13 with a new search field.
Should we close this issue @MarcusDenker ?
