### ISSUE TITLE
Finding Strings using Expression Finder lacks support from RefactoringBrowser

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#14535]
Currently (in Pharo 12) it is not possible to find strings (and not symbols) using the “Expression Finder”, since some support is missing from RefactoringBrowser.

To test it for example with the Expression Finder the provided input would be:

`#string `{ :node | node isString }`

In order to work, two convenience methods are missing:

```smalltalk
RBLiteralValueNode>>isString
	^ value isString and: [ value isSymbol not ]
```

and

```smalltalk
RBProgramNode>>isString
	^ false
```

**Comment by Ducasse** [comment]
Nice addition.

**Comment by Ducasse** [comment]
Can you send a PR?

**Comment by hernanmd** [comment]
> Can you send a PR?

In https://github.com/pharo-project/pharo/pull/14604

**Comment by jecisc** [comment]
Integrated
