### ISSUE TITLE
Remove method doesn't update the protocols dictionary

### ISSUE THREAD

**Issue by balsa-sarenac** [guillep/pharo-core#14553]
**Bug description**
When you remove a method from a class it is still present in the protocol dictionary as 'as yet unclassified'.

**To Reproduce**
I've added a new method to `MyClassNonEmptyLeafUnused` and add some code to it. After I remove it the `ProperMethodCategorizationTest>>#testNoUncategorizedMethods` starts failing saying it has uncategorized methods. After debugging I've found that the method is still present in `protocols` dictionary, but is not present in the `methodDict`.

**Comment by jecisc** [comment]
This is caused by this change I think: https://github.com/pharo-project/pharo/pull/14531

**Comment by jecisc** [comment]
Hum.. In fact it is not related to that. But the problem is that we remove the protocol and announce that the method changed. Calypso listen to the method change to update the pane. But then it put again the method in a protocol while trying to show the protocol of the method
