### ISSUE TITLE
Fix broken RB tests

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#14554]
## Test 1
 testAllReferencesToClassDoMore – MacOSX64.Refactoring.Tests.Core.RBNamespaceTest
Error
Got #(#testCanRemoveAReferencedClassNotHavingReferenceInTheModel #testCanRemoveUnreferencedClassUsingLimitedEnvironmentButReferencedElsewhere #testRemoveAClassAndTheirSubclass #testRemovingAnEmptyNonLeafClassReparent #testPreconditionNotEmptyClass #testRemoveAClassAndTheirSubclass2UsingAlimitedEnvironment #testRemovingAnEmptyNonLeafClassIsAllowed #testCanRemoveUnreferencedClass #testCanRemoveSuperclass #testCanRemoveReferencedClass) instead of #(#testCanRemoveUnreferencedClass #testCanRemoveReferencedClass #testCanRemoveSuperclass #testRemovingAnEmptyNonLeafClassIsAllowed #testCanRemoveUnreferencedClassUsingLimitedEnvironmentButReferencedElsewhere #testRemoveAClassAndTheirSubclass #testRemovingAnEmptyNonLeafClassReparent #testRemoveAClassAndTheirSubclass2UsingAlimitedEnvironment #testPreconditionNotEmptyClass #testCanRemoveAReferencedClassNotHavingReferenceInTheModel).
Stacktrace
TestFailure
Got #(#testCanRemoveAReferencedClassNotHavingReferenceInTheModel #testCanRemoveUnreferencedClassUsingLimitedEnvironmentButReferencedElsewhere #testRemoveAClassAndTheirSubclass #testRemovingAnEmptyNonLeafClassReparent #testPreconditionNotEmptyClass #testRemoveAClassAndTheirSubclass2UsingAlimitedEnvironment #testRemovingAnEmptyNonLeafClassIsAllowed #testCanRemoveUnreferencedClass #testCanRemoveSuperclass #testCanRemoveReferencedClass) instead of #(#testCanRemoveUnreferencedClass #testCanRemoveReferencedClass #testCanRemoveSuperclass #testRemovingAnEmptyNonLeafClassIsAllowed #testCanRemoveUnreferencedClassUsingLimitedEnvironmentButReferencedElsewhere #testRemoveAClassAndTheirSubclass #testRemovingAnEmptyNonLeafClassReparent #testRemoveAClassAndTheirSubclass2UsingAlimitedEnvironment #testPreconditionNotEmptyClass #testCanRemoveAReferencedClassNotHavingReferenceInTheModel).

## Test2
Attempt to read undeclared variable RBRemoveClassParametrizedTest
Stacktrace
UndeclaredVariableRead
Attempt to read undeclared variable RBRemoveClassParametrizedTest
UndeclaredVariable>>runtimeUndeclaredRead
RBRemoveClassRefactoringTest>>testPreconditionHasNoReferencesWithClassesWithReferencesBetweenThem
RBRemoveClassRefactoringTest(TestCase)>>performTest

## Test 3

osx-64 / Tests-osx-64 / testNoUnusedClassVariablesLeft – MacOSX64.ReleaseTests.CleanCode.NoUnusedVariablesLeftTest
3s
Error
the following classes have unused class variables and should be cleaned: an OrderedCollection(MyClassNonEmptyLeafUnused)

## Test 4
NoUnusedVariablesLeftTest
7s
Error
the following classes have unused instance variables and should be cleaned: an OrderedCollection(MyClassNonEmptyLeafUnused)

## Test 5
Categorization.ProperMethodCategorizationTest
<1s
Error
the following classes have uncategorized methods: an OrderedCollection(MyClassNonEmptyLeafUnused RBNamespace)

**Comment by Ducasse** [comment]
## Test 6 

testNoShadowedVariablesInMethods – MacOSX64.ReleaseTests.Release.ReleaseTest
22s
Error
RBClassDataForRefactoringTest>>#tempVarOverridesInstVar not found in OrderedCollection

**Comment by Ducasse** [comment]
## Test 7

osx-64 / Tests-osx-64 / testUndeclared – MacOSX64.ReleaseTests.Release.ReleaseTest
<1s
Error
Found undeclared Variables:  RBRemoveClassParametrizedTest in: RBRemoveClassRefactoringTest>>#testPreconditionHasNoReferencesWithClassesWithReferencesBetweenThem

**Comment by balsa-sarenac** [comment]
For me, all the tests pass except for `testNoUncategorized` in `ProperMethodCategorizationTest `. And I've looked a bit and it seems to me that it's #14553
