### ISSUE TITLE
[Refactorings] confusing precondition dialog in PullUpMethodRefactoring/Transformation

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#14576]
**Bug description**
The `refactoringError:` used in 
`RBPullUpMethodRefactoring>>#checkInstVarsFor:` and
`RBPullUpMethodTransformation>>#checkInstVarsFor:`
ask in the way the user has the option to cancel or proceed with the action, but only the `OK` button is displayed while it is not clear what is the result of the button pressing.

**Screenshots**
![alert](https://github.com/pharo-project/pharo/assets/572494/91310093-470c-41e0-b218-20c0a473047c)

**Comment by Ducasse** [comment]
thanks pavel we will look at it.

**Comment by balsa-sarenac** [comment]
This is fixed in PR that migrated all preconditions to either applicability or breaking changes.
Fixed in: #16098
