### ISSUE TITLE
`Path>>withExtension:` won't add an extension to filenames that end with those letters

### ISSUE THREAD

**Issue by daniels220** [guillep/pharo-core#14594]
**Bug description**
`Path>>withExtension:` checks if the receiver already has the supplied extension by asking if it `endsWith:` the provided string. But this could be a file whose _name_ ends with those letters, and has no extension at all, e.g. `footxt`. In this case we should produce `footxt.txt`.

**To Reproduce**
1. `'footxt' asFileReference withExtension: 'txt'`
2. Get `footxt`, still no extension

**Expected behavior**
`footxt.txt`

**Version information:**
 - OS: Any
 - Any Pharo Version

**Expected development cost**
Just need to add the extension delimiter to the `endsWith:` check, i.e. check if the name ends with `.txt` not just `txt`. PR incoming.

**Comment by Ducasse** [comment]
Thanks for the report. This is surprising!
