### ISSUE TITLE
TimeProfiler -> migration to Spec

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#14603]
I see that TimeProfiler and #AndreasSystemProfiler have UI reference (more for the TimeProfiler).
We should migrate this to Spec.

**Comment by MarcusDenker** [comment]
See 

https://github.com/pharo-project/pharo/issues/12334

TimeProfiler is used as a model for the new UI, but but the gui part was never removed

**Comment by MarcusDenker** [comment]
So I think we do not need to migrate, we just need to remove the old code, the new UI uses spec already (Package ProfilerUI)

I think we can close this issue and keep https://github.com/pharo-project/pharo/issues/12334 which has a list of steps to do (I will add AndreasSystemProfiler as a cleanup step)
