### ISSUE TITLE
Allow formatting only selected portion of a method or Playground

### ISSUE THREAD

**Issue by daniels220** [guillep/pharo-core#14618]
**Describe the request**
Sometimes I am editing a long method and want to clean up my new code, without introducing diff noise by reformatting the rest of the method. (Ideally there would be a standard code style enforced by the formatter, but this is a big job of its own and third-party code would still not necessarily conform.) It would be nice to be able to select a subset of the method and have formatting performed on that subset (assuming it parses on its own).

**Expected behavior**
Pressing Ctrl+Shift+F with a selection reformats only that part.

**Expected development cost**
I have a mostly-working solution, but it would be nice to handle indentation better when the selection starts not at the beginning of a line. Would also be nice to auto-expand the selection to find a parseable section if the initial selection doesn't parse.

**Version information:** any OS/any Pharo

**Comment by guillep** [comment]
> I have a mostly-working solution,

Oh nice!

**Comment by daniels220** [comment]
I'll try to get a WIP PR up in the next few days. Aside from the two things I mentioned—indentation handling and selection expansion—I'd like to incorporate parse error reporting similar to on method save. And/or, I was playing with it and the error "recovery" (allowing a parse that contains parse-error nodes and just feeding that back to the formatter) works remarkably well for toy examples, but I'm not sure how it'd fare on common classes of error I personally actually make—I know it's things like mismatched block braces in an already-complicated method, messed-up keyword messages, etc. but the nuances are important—I need to pay attention and catch some examples organically when I'm working on other things. In any case, though, I think it's important to make it more visible that an error was encountered. With strict parsing, we need to let the user know, "hey, we tried and failed, and here's where you need to look to correct it". With liberal parsing/parsing with recovery, we still need to point out where we changed something in case it's semantically not what the programmer wanted.

If anyone is familiar with the guts of Rubric as far as line-oriented editing, error display (I know there are red and yellow popup boxes), etc. and would be willing to help that'd be great—I can probably figure it out but I'm starting from scratch as far as familiarity with Rubric.

**Comment by Ducasse** [comment]
@plantec alain knows a bit the internal of Rubric.
