### ISSUE TITLE
Diffs highlight wrong parts of methods

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#14640]
Scenario:

* Open `Object>>#'->'` in a System Browser
* In the second comment, replace “following” by “next”
* Open the versions of the method (1.png)

The diff highlights part of the first comment instead of the second (1.png). The window must be made larger for the diff to correctly highlight the changed word (2.png). This seems to be due to the changes in [Spec commit c9cbc42a2fc98868](https://github.com/pharo-spec/Spec/commit/c9cbc42a2fc98868bd013135a1d9d3bcf838f7c6), previously lines in the diffs were not wrapped (3.png).

Build information: Pharo-12.0.0+build.742

**1.png:**
<img width="499" alt="1" src="https://github.com/pharo-project/pharo/assets/1611248/be77b648-b6c3-45cc-99a4-bf4549014992">

**2.png:**
<img width="698" alt="2" src="https://github.com/pharo-project/pharo/assets/1611248/5371c3f1-695f-4030-8308-c22168845763">

**3.png:**
<img width="497" alt="3" src="https://github.com/pharo-project/pharo/assets/1611248/460d69c9-4961-4809-9768-a2164886da12">

**Comment by jecisc** [comment]
I merged a revert of this change
