### ISSUE TITLE
We need test for thoroughWhichSelectorsReferTo:

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#14644]
Loading the attached file (as an example) and running the following should return the selector of the method referencing MyClassMyClassMyClass4.

```
ReferToMyClassMyClassMyClass thoroughWhichSelectorsReferTo: (RBClass named: #MyClassMyClassMyClass4) classBinding
> return the method reference to MyClassMyClassMyClass4
```

This is important to write test for such behavior because it is the backbone of the cross references
and I'm shocked to see no tests.

**Comment by Ducasse** [comment]
```
ReferToMyClassMyClassMyClass thoroughWhichSelectorsReferTo:
(MyClassMyClassMyClass4 >> #booo) classBinding
> return the referenced method
```

**Comment by Ducasse** [comment]
I added booo

in 
ReferToMyClassMyClassMyClass so that I could try the previous expression

**Comment by MarcusDenker** [comment]
thoroughWhichSelectorsReferTo: is using thoroughWhichMethodsReferTo: 

```
thoroughWhichSelectorsReferTo: literal
	^ (self thoroughWhichMethodsReferTo: literal) collect: [ :method | method selector ]
```

#thoroughWhichMethodsReferTo: is tested by BehaviorTest>>#testthoroughWhichMethodsReferTo

```
testthoroughWhichMethodsReferTo
	| array |
	array := #(thisIsOnlyHereIntestthoroughWhichMethodsReferTo).
	"normal case"
	self assert: (Point thoroughWhichMethodsReferTo: #x) notEmpty.
	"we understand send bytecodes for special selectors"
	self assert: (Point thoroughWhichMethodsReferTo: #+) notEmpty.
	"we dive into literal arrays"
	self assert: (self class thoroughWhichMethodsReferTo: array first) notEmpty.
	"and we are false for non existing symbols"
	self assert: (self class thoroughWhichMethodsReferTo: ('this', 'doesNotExist') asSymbol) isEmpty
```

**Comment by MarcusDenker** [comment]
the test does not test Literal Variables, as it makes not really much sense to use it for that case: as handles special selectors, dives into arrays... where Literal Variables can not be, but maybe we need test for that.

There is Behavior>>#whichMethodsReferTo: for checking Literal Variable use (this is missing a test)
