### ISSUE TITLE
rename RBAbstractClass>>#classBinding to be #binding

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#14656]
**Describe the problem**
We have, I think since ST80, a method #binding on Behavior that returns the Association/Variable in  Smalltalk globals.

RBAbstractClass uses #classBinding, which is not a good name, we should unify and call it #binding. 

There is just one user

**Comment by Ducasse** [comment]
Ok we will do it.

**Comment by Ducasse** [comment]
Marcus this is strange because there are other classBindings users in the image. 
Right now I just fixed the one of RBClass

**Comment by MarcusDenker** [comment]
For CompiledMethod, I think we should keep classBinding 

- there is no "binding of a compiledMethod"
- the method stores the binding of the class that it is installed in (last literal, for super sends and to know the class it is from)
- as such, this is the "binding of the class of the method"
- this, #classBinding is exactly a good name here.
