### ISSUE TITLE
Renaming an abstract class is broken (raises UndeclaredVariableRead: Attempt to read undeclared variable)

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#14658]
Pharo 12:
- create a package "Foo" with a class "Bar"
- make the class abstract via menu entry "Make abstract" from "Refactorings" menu
- now try to rename the abstract class "Bar" into "Bar2" using the "Rename" menu action and you will get the error

<img width="716" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/52f3534c-a4bb-42ac-b4fd-66fb11306b14">

**Comment by balsa-sarenac** [comment]
Fixed with: #14666
