### ISSUE TITLE
DrTest: A menu item to select all classes could be nice to have

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#14663]
Pharo 12: 

Depending on the package selection in the first pane of Dr. Test all contained classes are shown but there is no possiblity
in to "**Select all**" test classes from the context menu of this second pane displaying the test classes.

<img width="433" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/151e13a0-11ac-436a-a561-a3266fed25c2">

The old test runner (which is now removed) included some menu items for selections:

<img width="631" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/f2058e2a-51d9-4104-95ba-5879c335d171">

**Comment by Ducasse** [comment]
By default all the classes are selected and then if needed Cmd+A is selected all the items.

**Comment by astares** [comment]
OK - we can close
