### ISSUE TITLE
Private WriteStream for the compiler

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#14683]
- with just a little subclass of WriteStream we could avoid to have such method in WriteStream.

```
braceArray: anArray
	"This method is used in compilation of brace constructs.
	It MUST NOT be deleted or altered."

	collection := anArray.
	position := 0.
	readLimit := 0.
	writeLimit := anArray size
```

I always thought that OOP was about incremental definition so why put everything in a single class. 
Especially since a method like that is ONLY used by the compiler.

**Comment by Ducasse** [comment]
```
braceArray
	"This method is used in compilation of brace constructs.
	It MUST NOT be deleted or altered."

	^ collection
```

Yes we can hack. But we can also be clean and lean.

**Comment by guillep** [comment]
yes!
