### ISSUE TITLE
Deprecation redirection and modification doesn't work as intended

### ISSUE THREAD

**Issue by Eliott-Guevel** [guillep/pharo-core#14697]
**Bug description**
The deprecation redirection (using the transformWith: argument) doesn't work correctly for Pharo 12.
Using it makes some tests don't work the first time, only the times after. It also doesn't modify the old functions for the new ones.

**To Reproduce**
1. Import this [Molecule fork](https://github.com/Eliott-Guevel/Molecule-various-fixes) by executing the following code in a Playground:
```smalltalk
Metacello new
   baseline: 'Molecule';
   repository: 'github://Eliott-Guevel/Molecule-various-fixes';
   load.
```
2. In the Molecule-Tests package, execute the test which is named "testSeveralComponentsLifecycle"
3. The test fails (see screenshot)
4. Relaunching the test works (and subsequent times too, except when relaunching the VM)

**Expected behavior**
The test should not fail the first time. In addition, the deprecated methods aren't changed for their new versions (instan**c**iateAllComponents should become instan**t**iateAllComponents)

**Screenshot**
<img width="851" alt="node parent bug" src="https://github.com/pharo-project/pharo/assets/76944457/b332a117-57b1-4824-805d-64f113a80054">

**Version information:**
 - OS: Windows 11 Family
 - Version: 22621.2134
 - Pharo Version Pharo-12.0.0+build.768.sha.f2c9067e4cc97f23c4625f99b41be9e46197ef46 (64 Bit

**Additional context**
The test passes on Pharo 11 without any problem whatsoever.

**Comment by MarcusDenker** [comment]
Interesting.. very strange that the node has no parent.  I will check what goes wrong here.

**Comment by Ducasse** [comment]
Can you show the rule?

**Comment by Eliott-Guevel** [comment]
All redirections are done in the same way
<img width="352" alt="instanciate redirect" src="https://github.com/pharo-project/pharo/assets/76944457/4e2b7ede-99cd-4f21-bee8-df4e5a9d3d9e">

**Comment by labordep** [comment]
> Can you show the rule?

```smalltalk
self
		deprecated: 'Use instantiateAllComponents'
		transformWith: '`@receiver instanciateAllComponents'
			-> '`@receiver instantiateAllComponents'.
```

**Comment by Ducasse** [comment]
If you want to get to work you can rewrite by hand all the senders. 
Is it only this rule that is failing?
Now I do not get why the deprecation is failing on this trivial case. We will investigate.

**Comment by MarcusDenker** [comment]
I had a look and there is something strange going on. It seems to use the wrong CompiledMethod and then finds the wrong bc->AST mapping

**Comment by MarcusDenker** [comment]
I found what the cause is. When Monticello load the method, it has Undeclared Variables.

After Monticello then loads the missing class, the bytecode still is:

```
172 <26> pushConstant: ##MolCompleteComponentImpl
173 <84> send: runtimeUndeclaredRead
```

with the pushConstant: pushing the Variable.

This works correctly from an execution point of view (runtimeUndeclaredRead just sends #read to the var), but we end up with problems for the BC->AST mapping.

The BC-AST mapping can only be created by re-compiling, but the re-compiled Bytecode now does not see an undeclared, but a normal Literal Variable. It build the bc-AST mapping bases on that, but this is now not in syn with the real CompiledMethod.

The question is how to fix it... I need to think about it.

**Comment by MarcusDenker** [comment]
A workaround: after loading, execute:

```
  #runtimeUndeclaredRead senders do: [ :method | method recompile ]
```

**Comment by MarcusDenker** [comment]
Note: not a problem in Pharo11 (good!)

**Comment by MarcusDenker** [comment]
So... as a first workaround, we can do the following: on CompiledMethod>>#ast, we can detect this situation and force a recompile. As we need the compiler anyway to create the AST, we know that we can do that.

So we can add:

```
	"It is important that the AST is in sync with the CompiledMethod. With Pharo12, we (for now) might end with a reflective variable access due to repaired Undeclared reads"
	((self hasLiteral: #runtimeUndeclaredRead) or: [self hasLiteral: #runtimeUndeclaredWrite:]) 
			ifTrue: [self recompile].
```

This is not that nice in the big picture (or maybe it is, we need to late-bind Variable access of that kind in some way...), but for sure it is a good fix for now
