### ISSUE TITLE
Boosting the priority of a waiting process does not immediately schedule it to run

### ISSUE THREAD

**Issue by daniels220** [guillep/pharo-core#14701]
**Bug description**
If I have a low-priority process that is waiting in the `quiescentProcessLists`, and I assign it a higher `priority` than the active process, the active process continues to run until preempted by a preexisting higher-priority process.

Additionally, when changing the priority of any non-active process, it is not moved to the correct slot in the `quiescentProcessLists`, which will likely cause it to be scheduled once as if its priority had not been changed, though after that it will end up in the right place.

**To Reproduce**
Evaluate:
```
proc := [ Transcript crShow: 'In boosted process' ] forkAt:
	        Processor userBackgroundPriority.
Transcript crShow: 'In main proc before boosting'.
proc priority: Processor userInterruptPriority.
Transcript crShow: 'In main proc after boosting'.
3 * (10 ** 6) timesRepeat: [ 3 * 5 / 17 * 33 ].
Transcript crShow: 'In main proc after some busywork'.
```

which produces:
```
In main proc before boosting
In main proc after boosting
In main proc after some busywork
In boosted process
```

**Expected behavior**
```
In main proc before boosting
In boosted process
In main proc after boosting
In main proc after some busywork
```

**Version information:** Any OS / any Pharo version

**Expected development cost**
Off the top of my head, the right solution to this seems to be to make `Process>>priority:` a primitive, so it can atomically perform all necessary modifications to `quiescentProcessLists` and manually trigger a scheduling decision. Otherwise there is always the risk of the active process being interrupted by yet a third process while manipulating the processor. If it seems appropriate for a regular `yield` to also check for higher-priority processes this would be a good time to implement that as well. `ProcessorScheduler>>interpriorityYield:` is...concerning...to me, and it would be nice to eliminate it. I don't know enough about the VM to contribute to this, and while I suspect it's not _tremendously_ difficult, I imagine it's not trivial either.

As an alternative, it does seem to work to always suspend/resume the modified process, though it needs a different implementation (no forked process, the active process can handle it just fine) and a guard against resuming a previously-suspended process:

```
interpriorityYield: modifiedProcess
	"The original yield only works within processes of the same priority.
	The primitive does not try to resume a process in a higher priority.
	By suspending and resuming the modified process, we force it to be rescheduled.
	When modifying the active process, we must handle the resume from a forked process.
	We must also be careful not to resume a process that was suspended to begin with.
	(In particular, processes all receive #priority: as part of their creation, before
	it is safe to resume them.)

	This message should not be used directly.
	The only application so far is when changing the priority of a process.
	"

	modifiedProcess isActiveProcess
		ifTrue: [
			[ modifiedProcess resume ] fork.
			modifiedProcess suspend ]
		ifFalse: [
			modifiedProcess isSuspended ifFalse: [
				modifiedProcess
					suspend;
					resume ] ]
```

**Comment by Huixh111** [comment]
o

**Comment by Ducasse** [comment]
Thanks for the report.
