### ISSUE TITLE
[CI] Windows runner

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#14707]
**Bug description**
The test runner on win tries to download

```
	http://files.pharo.org/get-files/120/pharo-vm-UNKNOWN:CYGWIN_NT-10.0-x86_64-latest.zip
```

But that file does not exist

see eg

https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-14703/1/pipeline

**Comment by jecisc** [comment]
Logs from: https://github.com/pharo-project/pharo/pull/14764

```
+ wget --quiet -O - get.pharo.org/64/vmLatest120
+ bash
Downloading the latest pharoVM:
	http://files.pharo.org/get-files/120/pharo-vm-UNKNOWN:CYGWIN_NT-10.0-x86_64-latest.zip
```

**Comment by jecisc** [comment]
We found the source of the error with Hernan and we did a PR to zero conf: https://github.com/pharo-project/pharo-zeroconf/pull/41

Now, we need to regenerate the zero conf scripts and to upload them on files.pharo.org and for this hernan is waiting for the rights to do it. Once this is done, this should be fixed

**Comment by MarcusDenker** [comment]
We can do it together, I have access

**Comment by MarcusDenker** [comment]
We have updated the files on the server

**Comment by MarcusDenker** [comment]
This is now working
