### ISSUE TITLE
`RBNamespace>>#allReferencesTo:` returns incorrect number of senders for methods from `Object` class and its superclasses

### ISSUE THREAD

**Issue by balsa-sarenac** [guillep/pharo-core#14709]
**Bug description**
Incorrect number of senders is displayed when removing a method that is implemented in `Object` class or its superclasses.

Method that returns incorect number of senders is `RBNamespace>>#allReferencesTo:`.

**To Reproduce**
1. Go to `Behavior` class
2. Select `Behavior>>#addSelectorSilently:withMethod:`
3. Press `Ctrl+x` or do Right clik and then Remove2
4. Dialog opens saying method has 342 senders (at the time of writing the issue)
5. Click on "Don't remove, but show me those senders"
6. A Dialog with senders of the method opens and we can see that the method actually has only 12 senders

**Expected behavior**
Dialog that asks you to choose action to perform should say 12 senders instead of 342.

**Screenshots**

<img width="1352" alt="Screenshot 2023-09-20 at 14 30 19" src="https://github.com/pharo-project/pharo/assets/34557616/517455a7-3372-4023-8413-f6166bf7cd83">

**Comment by MarcusDenker** [comment]
Ah, this might be that the RB environment does not filter out the methods that traits add to the MetaClass?

e.g. check

AlignmentMorph class methods

we filter those at the tool level... similar issue, see  #11928

**Comment by balsa-sarenac** [comment]
I guess that's it since RB model doesn't have great support for traits yet...

**Comment by MarcusDenker** [comment]
Yes, that is one aspect. But these traits methods make problems even in the "language" side meta model. We should rethink this problem... is there a better solution possible?

**Comment by balsa-sarenac** [comment]
This is fixed in the newest Pharo12 so I guess it wasn't the trait issue, but RBModel one.
