### ISSUE TITLE
self for number in inspector

### ISSUE THREAD

**Issue by DuklinDonut** [guillep/pharo-core#14719]
when we execute

```
primeFactorsCache := LRUCache new.
50 timesRepeat: [
  | n |
  n := 100 atRandom.
  primeFactorsCache at: n ifAbsentPut: [ n primeFactors ] ].
```

in a playground and we inspect `primeFactorsCache` and we click statistics 
we get the situation shown below:

![image](https://github.com/pharo-project/pharo/assets/86496857/603fa19e-84d3-428a-89a1-3e3315587d78)

The question is why self is used for hits while hits is a number.
This is super confusing.

**Comment by MarcusDenker** [comment]
Yes, this looks wrong. You see it even when inspecting a simple object like a point:
![poinr](https://github.com/pharo-project/pharo/assets/413057/6f00b40a-4379-4f31-b3c0-d02408546a66)

**Comment by MarcusDenker** [comment]
This seems to fix is:

StInspectorNode>>#children should use #inspectorNodes, not #allInspectorNode:

```
children 
	
	^ self value inspectorNodes
```

I think this speeds up the inspector a bit, too (e.g. in the debugger)

**Comment by DuklinDonut** [comment]
Yes, it works, thank you!

**Comment by sdiepend** [comment]
Fix in https://github.com/pharo-spec/NewTools/pull/593

**Comment by MarcusDenker** [comment]
fix was merged
