### ISSUE TITLE
`RBEnvironmentVisitor` seems like a dead code

### ISSUE THREAD

**Issue by balsa-sarenac** [guillep/pharo-core#14721]
**Describe the problem**
`RBEnvironmentVisitor>>#visitClassEnv:` sends messages to selectors that don't exist.
Both `RBEnvironmentVisitor` and `RBEnvironmentPresenter` appear to be unused and can be removed.

**Classes involved**
`RBEnvironmentVisitor` and `RBEnvironmentPresenter`

**Proposal**
Make sure the classes are actually unused and remove them if true.

**Comment by Ducasse** [comment]
This is strange because RefactoringSettings is a singleton for the scopeList. 
Check references and it is a but ugly :)
