### ISSUE TITLE
Question around LRUCache test

### ISSUE THREAD

**Issue by Yamimutu** [guillep/pharo-core#14723]
```
LRUCacheTest >> test5kClasses
	| cache data |
	(cache := self newCache)
		maximumWeight: 1024.
	data := Object allSubclasses first: 5*1024.
	data do: [ :each |
		cache at: each name ifAbsentPut: [ each ] ].
	cache validateInvariantWith: self.
	self assert: cache size equals: 1024.
	data shuffled do: [ :each |
		cache at: each name ifAbsentPut: [ each ] ].
	self assert: cache size equals: 1024.
	cache validateInvariantWith: self.
	data
		select: [ :each | cache includesKey: each name ]
		thenDo: [ :each | cache at: each name ifAbsentPut: [ self fail ] ].
	self assert: cache hits >= 1024.
	cache validateInvariantWith: self

```

Hello, 
We have a small issue about understanding the matter of the last part of the test.
Indeed, line 15 ("select:"), it seems to filter "data" and keep only the elements present in "cache".
However, line 16 ("thenDo"), it sees to test if the elements we already filtered are present in "cache".
It doesn't look like this part of the test could fail in any situation.
If we understood it wrong, could you give us further explanations about this test's behavior ?

**Comment by jecisc** [comment]
I think it is to increase the number of hits for the assertion happening next

**Comment by jecisc** [comment]
Since there is no real problem I think we can close this one. 

The #thenDo: is there to access the cache and increase the hit statistic and is then useful
