### ISSUE TITLE
Extract temp affects neighboring scopes containing same expression

### ISSUE THREAD

**Issue by daniels220** [guillep/pharo-core#14771]
**Bug description**
If I have, for instance, two iteration blocks, both of which contain a particular expression somewhere, and I select it in one of them and use "extract temporary", the expression is replaced in both but the temp is only declared and initialized in one of them, resulting in a method that doesn't compile and wouldn't behave correctly if it did.

**To Reproduce**
I discovered this while inserting logging code in, of all places, `SourceFile>>tryOpenReadOnly:`—long story—so I'll use that as an example.
1. Select `each asFileReference / basename` in either of the iteration blocks in that method.
2. Extract to a temporary (I chose `loc`).
3. Notice that the other iteration block has also been affected:
```
tryOpenReadOnly: readOnly

	| basename |
	basename := path asFileReference basename.

	"Open a read write stream only if read only access was not requested.
	We need to create the encoding and buffering streams manually because we need a read write stream."
	readOnly ifFalse: [
		potentialLocations do: [ :each |
			[
			stream := SourceFileCharacterReadWriteStream
				          on:
				          (SourceFileBufferedReadWriteStream on:
					           loc unbufferedBinaryWriteStream)
				          encoding: 'utf8'.
			^ self ]
				on: Error
				do: [  ] ] ].

	potentialLocations do: [ :each |
		[
		| loc |
		loc := each asFileReference / basename.
		stream := ZnCharacterReadStream
			          on: loc binaryReadStream
			          encoding: 'utf8'.
		^ self ]
			on: Error
			do: [  ] ]
```

**Expected behavior**
Replace the extracted expression only in the scope in which the temp is declared.

**Screenshots**

**Version information:** Any OS, any Pharo

**Expected development cost**
The simple fix is to do what Dolphin Smalltalk does, and only replace the specific statement that was selected to extract with a reference to the temporary. Strictly speaking any more than this may not be a true refactoring, as the expression may have side-effects. In practice, I think much more commonly the programmer does really want all occurrences of that expression replaced with the temp, or they wouldn't be bothering to extract it to a temp in the first place. Fixing this should be a simple matter of only searching for other occurrences within the immediate enclosing scope. I'll make a PR when I have a chance.

**Comment by jecisc** [comment]
This might interest @balsa-sarenac
