### ISSUE TITLE
whichSelectorsAccess: does not work (ok) on unused variables

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#14782]
I have two classes

```
A (a b c)
    SubclassOfA

SubclassOfA>> foo3
	a
```

In SubclassOA I have a method that accesses a
And when I do 

```
SubclassOfA whichSelectorsAccess: #a 

I get an empty array.
```

**Comment by Ducasse** [comment]
So I cannot fix the RBClass logic :(

**Comment by Ducasse** [comment]
allMethodsAccessingSlot: does not work either :(

```
> SubclassOfA allMethodsAccessingSlot: (SubclassOfA slotNamed: #a)
#( )
```

So no idea what I should do.

**Comment by Ducasse** [comment]
And hasMethodAccessingVariable: is not working either :(

```
SubclassOfA hasMethodAccessingVariable: (SubclassOfA slotNamed: #a)
```

So basically in Pharo we cannot know if a class access superclass slot :(

**Comment by Ducasse** [comment]
And 

```
(SubclassOfA slotNamed: #a) isAccessedIn: SubclassOfA >>#foo3
```

is wrong too.

**Comment by MarcusDenker** [comment]
the reason is that if you just write "a", the compiler is clever enough to understand that this is "push a, pop a" wihthout side effect and will optimize it away.

You need to use the variable (e.g. return it, send a message, asssign it...)

**Comment by MarcusDenker** [comment]
I think we really need to push for not using bytecode as a meta model, it just goes against what we think should happen

**Comment by Ducasse** [comment]
I do not get your answer. Right now it means that I cannot make the refactoring working correctly. 
So I will write tests but I'm worry about the state of our reflective layer. 
Giving wrong results does not help.

**Comment by Ducasse** [comment]
And I'm not writing #a I used (Slot named: #a).

**Comment by Ducasse** [comment]
If tools cannot trust the underlying model then what it the use of them.

**Comment by MarcusDenker** [comment]
In this case we can remove the optimization.

But in general, it is just wrong, the ST80 idea to use the low level bytecode as the reflective model of code.

we will always have problems, e.g. there will always be sends on the bytecode level that are not there on the AST level
(for optimzied contructs). Or as soon as we use code generation (e.g. for FFI, Traits or MethodProxies or MetaLinks), it will be wrong and we add more and more workarounds but they will never fix the problem.

**Comment by Ducasse** [comment]
Which optimization? That we break the meta model?
I do not care that you think that everybody is wrong I care that the system is working. 
Or let us drop simply also the refactoring because this is a tool with no value.

**Comment by Ducasse** [comment]
And returning a selector is not good because the analysis is wrong in case of overwriting methods accessing both the same attribute. And I have to deal with that.

**Comment by Ducasse** [comment]
Ah this code is broken because I do not have a real expression.

**Comment by Ducasse** [comment]
I'm writing tests because there no tests of course. And the results are correct for real code. This is why it is working in P11.

**Comment by Ducasse** [comment]
I prefer that.

**Comment by Ducasse** [comment]
I will continue to write tests and add comments. 
Why we cannot have code WITH COMMENTS AND TESTS?

**Comment by Ducasse** [comment]
And we should methods and not selectors!

**Comment by MarcusDenker** [comment]
- The RB model uses selectors, historically the ST80 model just had only selector based APIs, too
- Kernel whichSelectorsAccess:  has a test: testwhichSelectorsAccess
- We started to add APIs to return methods, maybe no all have been implemented yet
- the fact that working on Bytecode as the reflective model has problems is a known issue. I always try to argue that we have to get away from it. But this is not trivial (e.g. memory).


this is not an "active" Project of anyone right now, so there has not been too much work.

**Comment by Ducasse** [comment]
I'm writing tests

```
testWhichSelectorAccessSubclassState

	self assert: (MyClassARoot whichSelectorsAccess: #instVarName1) equals: #(accessing). 
	self assert: (MySubAccessingSuperclassState whichSelectorsAccess: #instVarName1) equals: #(#accessing #accessing2InSub)
```

and I will write tests for all the other functionalities because I cannot spend time like that.

**Comment by Ducasse** [comment]
And I'm adding missing features.

**Comment by Ducasse** [comment]
And also adding more precise comments

```
whichSelectorsAccess: instVarName
	"Answer the selectors whose methods access the argument, instVarName, as a named instance variable. Pay attention the instVarName variable should be used e.g., be part of a return, message send or assignment else the compiler optimize it away and the method will not return it."

	^ self
		slotNamed: instVarName
		ifFound: [ :slot | self selectors select: [ :sel | slot isAccessedIn: self>>sel ] ]
		ifNone: [ #() ]
```

**Comment by Ducasse** [comment]
The user should not be a compiler expert to use a reflective feature.

**Comment by MarcusDenker** [comment]
> The user should not be a compiler expert to use a reflective feature.

Exactly. that is why using as the reflective model the output of the compiler that is meant for execution is a bad idea
