### ISSUE TITLE
FindReplace should be reimplemented in Spec2

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#14832]
EditorFindReplaceDialogWindow should be reimplemented using Spec2.

**Comment by hernanmd** [comment]
This issue (and #12159) could be closed when [PR](https://github.com/pharo-project/pharo/pull/14836) passes.

Notice that there is also `RubFindReplaceDialogWindow`, so we had 3 find/replace dialogs (you can see that if you hit CMD+F **inside** an existing focused search dialog). This Rub implementation could be also removed but I prefer to do it in another issue/PR

**Comment by MarcusDenker** [comment]
This has been done
