### ISSUE TITLE
Calypso: Debugging a test mess up with Calypso

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#14849]
In Pharo 12 it happens often to me that I am debugging a test and then if I click on the name of the test in my calypso, it gets broken saying that #name was sent to nil. 

If this happens all calypso are broken and I can only fix it by closing all Calypsos and launching a GC. Else I get the bug all the time.

I don't know which action exactly during the debugging causes this

**Comment by MarcusDenker** [comment]
This is https://github.com/pharo-project/pharo/pull/14865 I think
