### ISSUE TITLE
Jump to test method is broken from implementors window

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#14844]
**Bug description**

The "jump to test method" in the implementors window does not perform any action, which should be open a new window with the test method or replacing the current view in the implementors window with the test method.

**To Reproduce**

Open an implementors window (StMessageBrowserPresenter) for any method for example `nextVersion`. After right-clicking over the method which has a test, select the option "Jump to test method". A growl notification appears but no window is opened with the test method.

**Comment by hernanmd** [comment]
The Calypso code is quite complex when it comes to selecting a query execution context and configuring its objects appropriately. There are substantial differences between the System Browser functionality implemented in `ClyFullBrowserMorph` (where this jump to test functionality works correctly) and the Query Browser (where this functionality seems not to have been implemented at least since Pharo 8). Ideally the QueryBrowser should implement a command execution callback like :


```smalltalk
selectMethod: aMethod

	self selectObject: aMethod.
	self selectClass: aMethod origin.
	self methodSelection selectItemsWith: { aMethod } .
```

But this would make it necessary to implement (and adapt) the `selectObject:` and `selectClass:` methods in `ClyQueryBrowserMorph`. The differences with `ClyFullBrowserMorph` involve either replacing `packageView` with `resultView` or refactoring the two classes so that they re-use code in methods such as `selectPackage:atClassTag:` and `switchToPackages` (these methods are derivatives of `selectClass:` which allows you to select the class found in a query). Probably the `switchToPackages` functionality is not relevant, because the `ClyQueryBrowserMorph` does not display packages, so it should be replaced by `switchToFlatClasses`.

During my attempt, some methods assumed that a `methodItem` had a property named `ClyItemDefinitionProperty`, so I had to add verification code:

```smalltalk
ClyQueryBrowserMorph>>isClassSelected: aClass
	^ self selection items anySatisfy: [ [ :methodItem |
		(methodItem hasProperty: ClyItemDefinitionProperty) and: [ methodItem systemDefinition definingClass == aClass ] ].
```

and

```smalltalk
ClyQueryBrowserMorph>>classScopeOfSelectedItems
	| classes |
	classes := self-select items 
		select: [ : methodItem | methodItem hasProperty: ClyItemDefinitionProperty ]
		thenPick: [ :methodItem | methodItem systemDefinition definingClass ].
	ClyBothMetaLevelClassScope ofAll: classes in: navigationEnvironment
```

In view of the complexities of adapting Calypso, I propose that this issue can be temporarily solved with "Open test method" menu item that opens a new browser in the test method.

**Comment by Ducasse** [comment]
For me I hate when jump to creates a method.
I would prefer that the menu item is available only when jump to is actually working (ie that there is a test method).
Creating a method is a bad design because as a user I have no idea if it will or not create a new test method.

**Comment by dionisiydk** [comment]
> **Bug description**
> 
> The "jump to test method" in the implementors window does not perform any action, which should be open a new window with the test method or replacing the current view in the implementors window with the test method.

Problem that full browser is able to show any method while query browser can only select what is shown in the result list. So that the semantics of Jump meaning to stay inside the same window is not applicable to the query browser case. 
We can probably change the logic and just open new window instead of navigating the current one. Then it will work for both browsers.
From the other side we can say that QueryBrowser>>#selectMethod: should open the full browser if there is no method in its own list.

**Comment by hernanmd** [comment]
This issue can be closed as the PR has been integrated
