### ISSUE TITLE
ModificationForbidden error for array manipulation / primitive 163

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#14854]
In Pharo 8 one was able to manipulate Arrays quickly and directly:

```Smalltalk
a := #(0 0).
a at: 1 put: 2.
a inspect
```
<img width="421" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/1ad7295a-5e7f-4cbf-95bc-64285a59a09f">

In Pharo 11 one gets a **ModificationForbidden error:**

<img width="797" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/c363bf7e-bcbd-4c5d-907b-1d59cd316a38">

it only works by instantiating using constructor methods:
```Smalltalk
a := Array with: 0 with: 0.
a at: 1 put: 2.
a inspect
```

What is confusing is that the #at:put: method of object is used which checks if the object is a read only object by
using #isReadOnlyObject

<img width="606" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/6dcf838f-81c1-4722-bf9f-0ae6c7385163">

this is dependent on a primitive 163 in the VM. 

The fallback code in this method (which would be used if the primitive would not be there) uses #isImmediateObject 
which returns true for Character, SmallFloat64, SmallInteger. 

<img width="439" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/de3fd5b0-90ee-4214-81e1-c4365f8218d4">

For any other class it uses ProtoObject>>#isImmediateObject which would use #isImmediateClass on the class.

If one tries 

```Smalltalk
Array isImmediateClass  "false"
```
so an array should not be immediate or be read only IMHO.

Its working for these examples:

<img width="354" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/93aa82a7-bb1d-437f-8bfe-9a7970bfd899">

which I think are correct - but it returns true for 

```Smalltalk 
#(0 0) isReadOnlyObject.
```
<img width="262" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/eca51e4b-baf0-42b4-b4bd-d6232c871766">

in Pharo 11 which I think should return false as in Pharo 8:

<img width="274" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/c0f426f9-9b29-4fba-9000-6880d533d3ef">

**Comment by astares** [comment]
I think this is a bug in Pharo-VM, specifically in the primitive 163:

When I manipulate #isReadOnlyObject in Pharo 11 like this:

<img width="506" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/6e4c2685-1fd1-44a7-a3a5-355bf2f63f64">

one can see that the fallback code is not called and that the primitive returns true instead of the expected false.

**Comment by astares** [comment]
Pharo 12 has the same issue.

So I think like in Pharo 8 the following test needs to become green in P11 / P12 again:

```Smalltalk
testArrayCanBeManipulated
	|a|
	a := #(0 0).
	a at: 1 put: 42.
	a first
	self assert: a first equals: 42
```

@guillep, @tesonep, @estebanlm - any comments?

**Comment by jecisc** [comment]
The fact that it is forbidden to write in literal arrays is intended. This was causing *a lot* of bugs that were really hard to debug. And almost all modifications to such arrays were not intended. Thus, it is now forbidden to update such arrays. Note that dynamic arrays are still writable.

**Comment by astares** [comment]
But it has some side effects: code examples from books like "Agile AI with Pharo" from @bergel will not work anymore where neurons are setup with weights in #(...) array notation and weights are manipulated during training phase.

If it is by intention we can close

**Comment by MarcusDenker** [comment]
Yes, it is by intention: if you change a literal array, you change the array *yet the code is not changed*.

That is, you execute the method that says #(0 0 ), but the compiledMethod now hat #(42 0).

You can see that in your tests:

```
testArrayCanBeManipulated
	|a|
	a := #(0 0).
	a beWritableObject.
	self assert: a first equals: 0.
	a at: 1 put: 42.
	self assert: a first equals: 42
```

Green the first run, but fails the second. And you have no idea how that is possible...

**Comment by bergel** [comment]
Thanks @astares and @MarcusDenker I will take care of this.
