### ISSUE TITLE
Cleaned image has trouble moving between OS platforms

### ISSUE THREAD

**Issue by daniels220** [guillep/pharo-core#14850]
**Bug description**
I noticed that, when saving an image to run as a production application using the ImageCleaner, that image gets a bit "sticky" with respect to what platform it thinks it's running on. Saving on Windows and opening on Linux, or vice-versa, it fails to find the sources and changes files because it is looking for them using the other platform's path delimiter. Looking at the code, it seems like `SourceFileArray` tries to run its startup code before `DiskStore`, which is responsible for the path handling, so this makes sense. What I don't understand is why a normal, non-cleaned image _doesn't_ have this problem.

**To Reproduce**
1. Start an image with a script that runs the `ImageCleaner` and saves.
2. Start the resulting image on a different platform—Linux if you saved it on Windows, Windows if you saved it on Linux.
3. Observe "Pharo cannot locate the sources file" error, displaying a path that uses the wrong delimiters for the current platform. When opening on Windows, the image may fail to start altogether due to SDL failing to initialize.

**Expected behavior**
All filesystem code is initialized in time to search for source files and everything works.

**Version information:**
 - OS: Should be version-independent, in my case Windows 10 and a somewhat old Debian.
 - Pharo Version 11 for sure

**Expected development cost**
It seems reasonable enough to explicitly initialize DiskStore and File ahead of, y'know, trying to access the file system. PR inbound.

**Comment by MarcusDenker** [comment]
Yes, this is a bug, it should work to move an image between platforms.

ImageCleaner calls all the class side #cleanup methods... maybe this destroys something
