### ISSUE TITLE
Debugger inspector does not show the class of my object

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#14863]
I’m confused I’m inspecting an arg instance of RBLIteralCollectionNode 
and when I click on meta I get RBArrayNode. 

![Capture 2023-10-01 at 16 32 31](https://github.com/pharo-project/pharo/assets/432549/28bb7569-d7e2-4537-9b86-d1e4b8144df6)

while raw shows me the right version

![Capture 2023-10-01 at 16 34 05](https://github.com/pharo-project/pharo/assets/432549/b7dfe4ef-df2c-4fc3-9984-c4813b912cf1)

**Comment by MarcusDenker** [comment]
as there is a triangle to the left, I guess the subclass is below but not selected (the window s too small)

**Comment by adri09070** [comment]
Indeed, if you make the inspector pane smaller, you'll see the class `RBLIteralCollectionNode` in the hierarchy.

The inspector is too small and making it bigger would just make the problem appear less often so this is not a solution.

I guess the main problem is that the scrollbar doesn't appear. I'll see what we can do

**Comment by adri09070** [comment]
But when you resize it, and make it smaller again, the scrollbar reappear. There must be a bug in Spec

**Comment by adri09070** [comment]
Fix suggested here: https://github.com/pharo-spec/NewTools/pull/597
