### ISSUE TITLE
Add argument refactoring does not work for class side methods

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#14891]
**Bug description**
Add argument refactoring does not work for class side methods. When you add an argument to a class side method, it complains that the instance side does not contain the given method.

**To Reproduce**
1. on class side of a class (like `AIGraphAlgorith`) create methods
```smalltalk
msgArg1: arg1 arg2: arg2
```
and 
```smalltalk
msg 

	^ self msgArg1: nil arg2: nil
```
2. on `AIGraphAlgorithm class>>#msgArg1:arg2:`, open context menu and select refactoring **Add argument**
4. in the Method name editor, add an argument named `arg3` and click __Rename__
5. `Alert: AIGraphAlgorithm does not define #msgArg1:arg2:`

If the method of such name exists on the instance side, the refactoring is performed well.

**Comment by hernanmd** [comment]
Fixed in #15879
