### ISSUE TITLE
there are 4 selectors with messages sent but not implemented in Monticello

### ISSUE THREAD

**Issue by vonbecmann** [guillep/pharo-core#14930]
```
| selectors |
selectors := SystemNavigation new allSentNotImplementedSelectors.
selectors select: [ :each | each package name beginsWith: 'Monticello' ].
```

**Comment by MarcusDenker** [comment]
There is already

https://github.com/pharo-project/pharo/issues/10834


Does it make sense to have more open issues for this?

**Comment by Ducasse** [comment]
People do not know and this is difficult to find information so this is normal.

**Comment by vonbecmann** [comment]
sorry, i didn't know.

**Comment by Ducasse** [comment]
Do not worry we really appreciate what you are doing!

**Comment by MarcusDenker** [comment]
Yes, it is hard to find issues... there are just too many.

This is why I will close these and we keep https://github.com/pharo-project/pharo/issues/10834 as the main issue for all these selectors.
