### ISSUE TITLE
Pharo 11 Crashing on Windows 11

### ISSUE THREAD

**Issue by vitormcruz** [guillep/pharo-core#14956]
I am not sure what exactly is causing the image to crash, sometimes just browsing classes crashes it. The first time this happened to me was when I as trying to perform git operations. The log show the following message at every image start:

[ERROR] 2023-10-10 14:27:36.000 sqMakeMemoryNotExecutableFromTo (extracted/vm/src/win sqWin32SpurAlloc.c:226):VirtualProtect(x,y,PAGE_EXECUTE_READWRITE): No error

I found that #13726 may be related. I atached logs with debug mode set.
[pharo-25984.log](https://github.com/pharo-project/pharo/files/12860294/pharo-25984.log)

This error happened when I was browsing classes loaded by Iceberg.

**Comment by jecisc** [comment]
Hi,
What is your VM version? Pharo 11 should use Pharo VM 10.0.7 currently

**Comment by vitormcruz** [comment]
The log says "PharoVM version:5.0-Pharo 10.0.5", I am using Pharo Launcher.

I will try to update and post results here.

**Comment by vitormcruz** [comment]
Update to version 10.0.7 did solve some issues, but the message:

`qMakeMemoryNotExecutableFromTo (extracted/vm/src/win/sqWin32SpurAlloc.c:226):VirtualProtect(x,y,PAGE_EXECUTE_READWRITE): No error`

is still showing upon image opening.

The crash, however, did happend after I tried to load a larger project using Iceberg, but it seems less frequent now since I can navigate throught another smaller project loaded withou crashing it.


[pharo-16692.log](https://github.com/pharo-project/pharo/files/12897444/pharo-16692.log)

Still, in the current version, Pharo is unusable by me on Windows.

**Comment by vitormcruz** [comment]
Perhaps this is a problem with the VM, should I post an issue there?

**Comment by jecisc** [comment]
Pharo VM issues are usually reported here: https://github.com/pharo-project/pharo-vm

<blockquote><img src="https://opengraph.githubassets.com/1532591adb2298932e62571719b1246f96def743552d767a4091a5763a5a57fe/pharo-project/pharo-vm" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-vm">GitHub - pharo-project/pharo-vm: This is the VM used by Pharo</a></strong></div><div>This is the VM used by Pharo. Contribute to pharo-project/pharo-vm development by creating an account on GitHub.</div></blockquote>

**Comment by guillep** [comment]
This seems to be solved https://github.com/pharo-project/pharo-vm/issues/704

Let me close this issue. Let's reopen it if we see the issue again.
