### ISSUE TITLE
buildClassFromAST: and all the users should be migrated to FluidClassDefinition

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#14979]
ASTClassBuilderTest, undefinedClassTests are using the old class format

**Comment by jecisc** [comment]
ASTClassBuilderTest is used to parse the old class definition explicitly. 

It is to be able to have specific menus in the class definition pane of calypso. We will be able to remove the old class definition parser and AST once we remove the little checkbox to make Calypso go back to the old class definition. 

The question is: do we do that in Pharo 12 or 13? => https://github.com/pharo-project/pharo/issues/14950

**Comment by jecisc** [comment]
![image](https://github.com/pharo-project/pharo/assets/9519971/255f6282-1f86-423b-8837-1060ac3d05ed)


I'm talking about the "Fluid" checkbox at the bottom right corner of this screenshot

**Comment by Ducasse** [comment]
Yes I know. Now 
- undefinedClass test do not tests to be based on the old class format
- ASTClassBuilderTests do not need to be expressed using the old format.
These tests have nothing to do with the menu there are about the builder!

So instead of testing that the builder is able to filling information from the old format 
we should have tests that show that we can also fill up from the fluid format.

**Comment by Ducasse** [comment]
```
testCreateEphemeronClassWithAll

	| ast class |
	ast := self parserClass parse:
		       'Class ephemeronSubclass: #TestSubClass
		uses:   TAddForUniquenessTest + TIncludesWithIdentityCheckTest															instanceVariableNames: ''cat env''															classVariableNames: ''var classVar pouet''
poolDictionaries: ''TestSharedPool ShTestSharedPool''	
package: ''Kernel-Classes'''.

	class := ShiftClassBuilder new
		         buildEnvironment: self environment;
		         buildFromAST: ast;
		         build.

	self assert: class isEphemeronClass.
	self assert: class name equals: #TestSubClass.
	self assert: class instanceVariablesString equals: 'cat env'.
	self assert: class classVarNames equals: #( #classVar #pouet #var )
```

**Comment by Ducasse** [comment]
So these tests are about the class builder and not the AST to have menus.

**Comment by jecisc** [comment]
Proposed fix: https://github.com/pharo-project/pharo/pull/14984

**Comment by Ducasse** [comment]
Cool!

**Comment by Ducasse** [comment]
Are you sure that we should keep the ASTBuilderTest because there are ClassParserTest that are the tests for the AST and the menu and others are based on the AST and not the builder.

**Comment by jecisc** [comment]
I see what you mean. I agree, I'll remove them! :)
