### ISSUE TITLE
Cannot inspect SubscriptionRegistry of SystemAnnouncer

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#15005]
In Pharo 12 if I inspect the unique instance of the system announcer and click in the raw view on the registry then my image freeze and I cannot do anything

**Comment by hernanmd** [comment]
You mean inspecting `SystemAnnouncer uniqueInstance` ?
I cannot reproduce it in Pharo 12.0.0 Build information: Pharo-12.0.0+build.925.sha.2d4a6ff07292d65ad288c497926c7fbdf95743ed (64 Bit)

<img width="944" alt="Screenshot 2023-10-19 at 17 25 44" src="https://github.com/pharo-project/pharo/assets/4825959/4c35ad94-45d6-412f-b0bb-daa9c6047e32">

**Comment by MarcusDenker** [comment]
if you scroll down odd things happen, I think it tries to render some morphs in the list which fails
