### ISSUE TITLE
`String>>asClassIfAbsent:` inconsistent with `SystemDictionary>>#hasClassNamed:`

### ISSUE THREAD

**Issue by chisandrei** [guillep/pharo-core#15020]
**Describe the problem**

`String>>asClassIfAbsent:` triggers an error if the given class name is a global that is not a class.
For example `(#Processor asClassIfAbsent: [ nil ]) notNil` results in an error, instead of returning `false`. 

Doing this check in a different way like `nil class environment hasClassNamed: #Processor` triggers no error.

Even if `asClassIfAbsent:` should not be used that much, the fact that it triggers an error for globals that are not classes feels strange.

**Classes involved**
This involves just the methods `String>>asClassIfAbsent:` and `String>>#asClassInEnvironment:ifAbsent:`

**Proposal**

The fix would involve changing `String>>#asClassInEnvironment:ifAbsent:` to

```
asClassInEnvironment: anEnvironment ifAbsent: absentBlock
	^  anEnvironment 
			at: self asSymbol 
			ifPresent: [ :aClass| 
				"Use the absentBlock in case the global is not a class."
				aClass isBehavior ifFalse: [ ^ absentBlock value ].
				aClass ]
			ifAbsent: absentBlock
```

**Version information:**
Pharo 10, 11, 12

**Expected development cost**
The fix is easy. Just not sure if there was a specific reason for the current implementation.

**Comment by jecisc** [comment]
i agree with the proposed fix. We should also add a regression test. 

Even if #asClassIfAbsent: should not be used much, the bug reside in #asClassInEnvironment:ifAbsent: that is aware of the environment so we should fix it. 

Do you want to propose a PR or do you prefer that we do it with your fix?

**Comment by chisandrei** [comment]
If you can do a PR it would be awesome ( you'll be a lot faster :) )

**Comment by Ducasse** [comment]
Sorry guys but I will veto this change and I want to remove all the asClass* from Pharo. People who want to script class access should load a package. It can be in Pharo-contribution if needed but I will not do it. 
I opened an issue about removing asClass and I will do it so do not invest in it.

**Comment by Ducasse** [comment]
https://github.com/pharo-project/pharo/issues/14970

**Comment by jecisc** [comment]
This includes #asClassInEnvironment:? I know that you want to remove #asClass because it goes in a global, but #asClassInEnvironment: do not go in a global and is affected by this issue

**Comment by MarcusDenker** [comment]
I would prefer we do this cleanup step by step and in a way that it is possible to load old code.

It is easy to have methods on the environment for all these, and there is no reason why  not transform...

```
#name #asClassInEnvironment: someEnvironment
```

can be easily transformed to 

```
someEnvironment classNamed: #name
```

and so on. #asClass would be transformed to take the standard environment always (e.g. "self environment").

**Comment by Ducasse** [comment]
But I mentioned it long time ago. asClass is a bad pattern. 
So for Pharo 12 we should just package these functionalities out. 
Why should we always maintain shitty ideas for other people. 
My time is far from infinite.

**Comment by Ducasse** [comment]
And after people ask us to work on namespaces.
How a module system could possibly work with asClass.

**Comment by Ducasse** [comment]
We should reduce the extensions on Symbol and strings because there are disguided singletons. We cannot dispatch.

**Comment by fedemennite** [comment]
That isn't a problem. We can easily maintain our own version.
FYI, we use this, outside the scope of package management for at least to reasons:
1. basically because we have our own way to sync code to a custom code repository
2. we need to support code that runs in multiple Smalltalk dialects
The second can possibly solved in other ways but it is less of problem.
