### ISSUE TITLE
Stepping failure on optimized method Dictionary>>#at:

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#15059]
**Bug description**
When you step into the method `Dictionary>>#at:`, the stepping fails with `Dictionary(Object)>>doesNotUnderstand: #between:and:`. This dictionary method has the compiler optimization `<compilerOptions: #(+ optionBlockClosureOptionalOuter)>`.

**To Reproduce**

```smalltalk
dict := Dictionary newFrom: { #key1 -> 1. #key2 -> 2 }.
dict at: #key1.
```
1. Debug the code above, on the second line, go inside `at:` (4 times Over, Into)
2. Go inside `at:ifAbsent:` (Over, Into)
3: It goes inside `ByteSymbol`, it changes the receiver to the key `#key1`

![image](https://github.com/pharo-project/pharo/assets/572494/b0e3d566-78b4-4d7b-9812-01908d43bfd7)

...and then it starts to debug nonsenses.

When this optimization is removed from the method, it debugs it normally.

**Comment by MarcusDenker** [comment]
Yes, I saw that, too... I will revert the change.
