### ISSUE TITLE
Remove 2222

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#15061]
```smalltalk
ClyRemoveMethodGroupCommand>>defaultMenuItemName
	^'Remove 2222'
```

- Click on a method category.
- The option to remove a method category is named "Remove 2222" (?)

**Comment by Ducasse** [comment]
I should do a pass. and remove some other menu. 
Basically the version 2 is new version and the one that we should keep.

**Comment by pavel-krivanek** [comment]
Already cleaned, can be closed.
