### ISSUE TITLE
Pragmas lost when updating methods

### ISSUE THREAD

**Issue by fcr--** [guillep/pharo-core#15074]
**Bug description**
Pragma pragmaCache has an inconsistent view of the methods containing which pragmas.

**To Reproduce**
1. Create a method (either class or instance method) with eg: the `<foo: 'yes'>` pragma.
2. Inspect `Pragma allNamed: #foo:.`

**Expected behavior**
an Array with the Pragma instance.

**Steps**
Then when I run:
1. `(MyClass methodNamed: #myMethod) cachePragmas.`
2. `Pragma allNamed: #foo:` I get the pragma
3. but if I update the method code changing the pragma to `<foo: 'no'>`,
4. then when I run Pragma allNamed: #foo:` the Pragma is no longer there.

**Screenshots**
<img width="1902" alt="image" src="https://github.com/pharo-project/pharo/assets/1237586/9257fdaf-61e2-483c-89a7-de25b984b15b">

**Version information:**
 - OS: [e.g. iOS]: macOS
 - Version: [e.g. 1.6.1]: Sonoma 14.0 running on Apple M1 Pro
 - Pharo Version [e.g 9]: 12

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 
* No idea, I'm not familiar with Pharo internals, and I'm starting in my path towards learning Smalltalk.

In addition, are you willing to help because after all Pharo is yours too?
* Sure, I'll try to help.

**Additional context**

* Could it be that I'm using pragmas wrong and they are not supposed to be used that way?

**Comment by MarcusDenker** [comment]
Thanks! I think I have an idea what is going wrong...  when removing compiled method properties, it copies the AdditionalMethodState object (it is an array, kind of) to shrink. That copy does a shallow copy of both the pragmas and the associations of the properties.


I think we should add version of copy just for the case and not do the shallow copy

I will do somet experiments...


(and we really need to simplify.. this AdditionalMethodState stuff is just too complex for nothing)
