### ISSUE TITLE
calypso: drag a class to a new package tag raises DNU

### ISSUE THREAD

**Issue by estebanlm** [guillep/pharo-core#15076]
**Bug description**
while using calypso, dragging a class to a new package tag (a common task while organizing a package) raises a DNU

**To Reproduce**
1. Open calypso in a package
2. attempt to drag a class to a specific package tag
3. watch the DNU :)

**Expected behavior**
I want to be able to move my classes :)

**Comment by estebanlm** [comment]
@jecisc I think this one has to do with the category clean up you are working on :)

**Comment by jecisc** [comment]
I proposed a fix. Thanks for the report!
