### ISSUE TITLE
Rename Regex-Core into Regex

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#15070]
We have only one package for Regex (and another for the tests). It does not really make sense to call it "Regex-Core" when there is no other declination of the Regex project. It would be simpler to have Regex and Regex-Tests instead

**Comment by astares** [comment]
You might argue this is personal taste. But to me this makes sense from the architectural "layer" perspective.

To explain: typically you might have packages like:

- Something-Core   (with the core functionality)
- Something-Core-Tests   (with the tests for the core functionality)

Often this "core functionality" is **always** needed - be it in a headless or in a desktop/UI image. In a runtime/deployment image you might even not load the tests.

Then often you have packages for other "layers building on top" of the "Core" like UI, or Spec, Tools or other. For instance:

- Something-UI            (with a UI on top of the core functionality)
- Something-UI-Tests   (with the tests for the UI functionality)

**Now if you just want to see the core you can filter in the browser for  "Regex-Co" and the browser will only display the first two core packages. **

If you would just name them with "Regex" like
- Regex
- Regex-Tests
- Regex-UI
- Regex-UI-Tests

you could only filter for "Regex" and would see the core and ui / spec / always together. 
**So with this scheme it would not be possible to have a filter to only see the core packages and their tests.**

Also "Core" makes it more explicit what the package is about.

**Comment by astares** [comment]
So when someone provides a 

- "Regex-UI" or 
- "Regex-Tools" 
- ...

packages later in the image or as an external package it is still possible to just filter for the core by filtering for "Regex-Core". Therefore I would leave the naming of this package as it is as it makes sense

**Comment by guillep** [comment]
I personally like name conventions like @astares says, they provide structure somehow, and help build tools without too much configuration. For example, I'd like Pharo projects to have a standard structure so we can automatically analyze dependencies, run mutation testing on them easily without too much manual configuration, or even validate that the structure is as expected.

Now, the reality is that there is no agreement in such a structure, and in that case, we will do refactorings from A to B and then from B to A. Is there somebody interested in discussing and setting up such an agreement? People from **ba-st** have a superb "project initializer" that kind of enforces a structure (see https://github.com/ba-st/GitHub-setup/blob/master/setup.sh).

If somebody is interested I propose we could meet and lay out a phep (https://github.com/pharo-project/pheps/) to describe the structure to follow inside Pharo's code, and recommend to third-party projects.

**Comment by astares** [comment]
As written in #15070 I would not integrate this and keep the name. 

It makes sense to clearly distinguish "Core" functionality from other layers like "UI". While at runtime/deployment one often only requires core part the users often struggle with stuff like regex and some additional "UI" and "Tools" packages make sense too.

For instance I could update utilities like https://github.com/astares/Pharo-Regex-Tools
for better integration

<blockquote><img src="https://opengraph.githubassets.com/65bb48d8ba85437b0135f24ff561e196c1348fdfa9ca3a7592dc4b1c037c866b/astares/Pharo-Regex-Tools" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/astares/Pharo-Regex-Tools">GitHub - astares/Pharo-Regex-Tools: Simple tool to verify regular expressions in Pharo</a></strong></div><div>Simple tool to verify regular expressions in Pharo - astares/Pharo-Regex-Tools</div></blockquote>
