### ISSUE TITLE
[CI] Windows CI run sometimes is green but did not run

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#15105]
**Bug description**
If the WIN test run is green (instead of timing out, see #15104), it finishes in 5 seconds without actually running any tests.

**Comment by Rinzwind** [comment]
Looking at the pages opened by the following, it would seem the problem occurs whenever the Windows tests run on ‘pharo-ci-jenkins2-win10’ (as opposed to ‘pharo-ci-jenkins2-win10-2’):

```smalltalk
{ { 16342. 1 to: 1 }. { 16341. 1 to: 4 }. { 16337. 1 to: 5 }. { 16336. 1 to: 1 }. { 16302. 1 to: 1 }. { 16277. 1 to: 3 } }
	do: [ :arguments |
		arguments bind: [ :pullRequestNumber :buildNumbers |
			buildNumbers do: [ :buildNumber |
				#(51 81) do: [ :executionNodeNumber |
					WebBrowser openOn: ('https://ci.inria.fr/pharo-ci-jenkins2/job' ,
						'/Test%20pending%20pull%20request%20and%20branch%20Pipeline' ,
						'/view/change-requests/job/PR-{1}/{2}/execution/node/{3}/log/?consoleFull'
							format: { pullRequestNumber. buildNumber. executionNodeNumber }) ] ] ] ]
```

For example, for pull request 16277, for build 2, the [‘Allocate node’ page](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/view/change-requests/job/PR-16277/2/execution/node/51/log/?consoleFull) shows:

```
Running on pharo-ci-jenkins2-win10-2 in C:\builds\workspace\est_and_branch_Pipeline_PR-16277
```

And the [‘Windows Batch Script’ page](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/view/change-requests/job/PR-16277/2/execution/node/81/log/?consoleFull) shows:

```
ci@WIN10-CI C:\builds\workspace\est_and_branch_Pipeline_PR-16277\Tests-windows-64>bash -c 'bootstrap/scripts/runTests.sh 64 Tests-windows-64' 
+++ dirname bootstrap/scripts/runTests.sh
++ cd bootstrap/scripts
[…]
Running tests in 766 Packages
Beginning to run tests of NewTools-SpTextPresenterDecorators with random seed 871543922
[…]
```

While for build 3, the [‘Allocate node’ page](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/view/change-requests/job/PR-16277/3/execution/node/51/log/?consoleFull) shows:

```
Running on pharo-ci-jenkins2-win10 in C:\builds\workspace\est_and_branch_Pipeline_PR-16277
```

And the [‘Windows Batch Script’ page](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/view/change-requests/job/PR-16277/3/execution/node/81/log/?consoleFull) shows just:

```
ci@WIN10-CI C:\builds\workspace\est_and_branch_Pipeline_PR-16277\Tests-windows-64>bash -c 'bootstrap/scripts/runTests.sh 64 Tests-windows-64' 
```

**Comment by Ducasse** [comment]
Thanks for the analysis. We will discuss it during our weekly sync.

**Comment by Rinzwind** [comment]
Could [‘pharo-ci-jenkins2-win10’](https://ci.inria.fr/pharo-ci-jenkins2/computer/pharo%2Dci%2Djenkins2%2Dwin10/) be temporarily disabled in Jenkins so that it always uses [‘pharo-ci-jenkins2-win10-2’](https://ci.inria.fr/pharo-ci-jenkins2/computer/pharo%2Dci%2Djenkins2%2Dwin10%2D2/) for now?

**Comment by jecisc** [comment]
@Rinzwind Done

**Comment by Rinzwind** [comment]
As already remarked [in pull request #16172](https://github.com/pharo-project/pharo/pull/16172#issuecomment-2077966426), this issue is occurring again, including in the latest ‘Pharo13’ build ([build 37](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo13/37/)), which has no results for Windows in its [test results](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo13/37/testReport/). The [Jenkins nodes](https://ci.inria.fr/pharo-ci-jenkins2/computer/) table seems to no longer include ‘pharo-ci-jenkins2-win10-2’, only the nonworking ‘pharo-ci-jenkins2-win10’ is there. Is ‘pharo-ci-jenkins2-win10-2’ no longer available? Is the problem with ‘pharo-ci-jenkins2-win10’ being investigated?

**Comment by jecisc** [comment]
Maybe @demarey knows about the missing slave?

**Comment by Rinzwind** [comment]
Is this being investigated? The latest ‘Pharo13’ build ([build 106](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo13/106/)) still (or again) doesn’t have any results for Windows in its [test results](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo13/106/testReport/): the table in the ‘All Tests’ section only has ‘MacOSX64’ and ‘Unix64’. The [stage ‘Tests-windows-64’](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo13/106/pipeline-console/?selected-node=74) took just 13 seconds.

**Comment by guillep** [comment]
Some information that may be useful:

1. the slave `win-2` is deprecated. I tried to connect it to jenkins but it has an outdated java version. When I tried to connect to it to update it, I saw it was marked as deprecated. Probably @demarey has more info on it, as he updated the CI before the P12 release.

2. The VM build is running the Pharo tests on windows, and using the correct slave.

<img width="1008" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/3cfa54a1-69a2-434a-aedf-110225e0a672">

So there is something in Pharo's JenkinsFile

**Comment by guillep** [comment]
The code running the tests on windows is effectively different in both repositories.

In the VM (working) we have special code for windows (see https://github.com/pharo-project/pharo-vm/blob/73808bc528cb3383e35153dda210f8bf2fb7765b/Jenkinsfile#L245):
```
	if(isWindows()){
					runInCygwin "cd runTests && unzip ../build/build/packages/PharoVM-*-${platform}-bin.zip -d ."
					// Disable testAfterSequence that creates incorrect bytecode sequences
                    runInCygwin "PHARO_CI_TESTING_ENVIRONMENT=true cd runTests && ./PharoConsole.exe  --logLevel=4 ${hasWorker} Pharo.image ${additionalParameters} ../repository/scripts/patchPharoPreTests.st"
                    runInCygwin "PHARO_CI_TESTING_ENVIRONMENT=true cd runTests && ./PharoConsole.exe  --logLevel=4 ${hasWorker} Pharo.image ${additionalParameters} test --junit-xml-output --stage-name=${stageName} '${packages}'"
	} ...				
```

However, in Pharo it uses the same shell script for all platforms, run through cygwin and a bat file on windows (see https://github.com/pharo-project/pharo/blob/52f80ab25bf8cd54706c6401cc02c3db756f52b3/Jenkinsfile#L35,  https://github.com/pharo-project/pharo/blob/52f80ab25bf8cd54706c6401cc02c3db756f52b3/Jenkinsfile#L25-L27).

One other thing is that we are "ignoring empty results" (see https://github.com/pharo-project/pharo/blob/52f80ab25bf8cd54706c6401cc02c3db756f52b3/Jenkinsfile#L36) probably explaining why we get a green CI when nothing is run :)

<img width="454" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/46bd8029-fdd5-41b7-bb91-7dcaea7cb3cb">


In any case, there is probably a difference in setup/installation between the two slaves (the one that worked and this one), making the tests fail silently in this case.

**Comment by guillep** [comment]
Fixed, see solution in https://github.com/pharo-project/pharo/pull/16845
