### ISSUE TITLE
[CI] Windows times out running the tests

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#15104]
**Bug description**
The test run stage is reaching the 35 minute limit.

```
Running tests of Refactoring-UI
Running tests of ProfStef-Tests
Running tests of MonticelloFileServices
Running tests of MonticelloTonel-Core
Running tests of Compression-Tests
script returned exit code 127
```

**Comment by jecisc** [comment]
There seems to be a problem during Epicea's tests. I found this in a log that timed out:

```
Beginning to run tests of Epicea-Tests

























































Finished to run tests of Epicea-Tests in 9 minutes 34 seconds 731 milliseconds
```

More than 9min for Epicea's test is way too long. We have this on the OSX slave:

```
Beginning to run tests of Epicea-Tests

Finished to run tests of Epicea-Tests in 440 milliseconds 849 microseconds
```

**Comment by Rinzwind** [comment]
In [build 4 for pull request #16201](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16201/4/), the [Windows test run](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16201/4/execution/node/81/log/) timed out while running the package ‘Epicea-Tests’ (the ellipsis omits 91 empty lines):

```
Beginning to run tests of UnifiedFFI-Tests with random seed 319495693
Finished to run tests of UnifiedFFI-Tests in 1 second 410 milliseconds
Beginning to run tests of Epicea-Tests with random seed 161277837
[…]
Sending interrupt signal to process

script returned exit code -1
```

The [‘progress-Tests-windows-64.log’](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16201/4/execution/node/156/log/) shows that that was more specifically while running `#testFromDetectIfNotFound ` on EpLogTest:

```
starting testcase: EpLogTest>>testFromDetect ... finished
starting testcase: EpLogTest>>testFromDetectIfNotFound ... 
```

It might be useful for the progress log to show the run times for the individual test methods.

**Comment by Rinzwind** [comment]
I opened a pull request to make HDTestReport print the test run times on the progress log (pull request #16266). In [build 1 for that pull request](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16266/1/), the [Windows test run](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16266/1/execution/node/81/log/) timed out again while running the package ‘Epicea-Tests’. The [‘progress-Tests-windows-64.log’](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16266/1/execution/node/156/log/) shows each test method takes between 10 to 20 seconds:

```
ci@WIN10-CI C:\builds\workspace\est_and_branch_Pipeline_PR-16266\Tests-windows-64>cat progress-Tests-windows-64.log 
running suite: Epicea-Tests
starting testcase: EpAnnouncementsTest>>testMonitorAnnouncesUpdateWhenDisabled ... finished in 20 seconds 24 milliseconds
starting testcase: EpAnnouncementsTest>>testMonitorAnnouncesUpdateWhenEnabled ... finished in 10 seconds 8 milliseconds
[…]
starting testcase: EpCodeChangeIntegrationTest>>testRemoveTraitFromComposition ... finished in 20 seconds 60 milliseconds
starting testcase: EpCodeChangeIntegrationTest>>testTraitAddition ... finished in 10 seconds 32 milliseconds
starting testcase: EpCodeChangeIntegrationTest>>testTraitModificationOfTraitComposition ... finished in 10 seconds 13 milliseconds
starting testcase: EpCodeChangeIntegrationTest>>testTraitRemoval ... finished in 20 seconds 47 milliseconds
[…]
starting testcase: EpLogTest>>testPriorEntriesFromNullReferenceIsEmpty ... finished in 20 seconds 50 milliseconds
starting testcase: EpLogTest>>testShouldKeepHeadReferenceAfterReOpen ... 
```

The following snippet can be used to parse the run times from the progress log:

```smalltalk
logURL := 'https://ci.inria.fr/pharo-ci-jenkins2/job' ,
	'/Test%20pending%20pull%20request%20and%20branch%20Pipeline' ,
	'/job/PR-16266/1/artifact/progress-Tests-windows-64.log'.
lines := (ZnEasy get: logURL) contents lines.
matcher := RxMatcher forString: '.* ([^ ]+) ... finished in ([0-9]*) seconds ([0-9]*) milliseconds'.
runTimes :=
	(lines collect: [ :line |
		(matcher matches: line) ifTrue: [ {
			matcher subexpression: 2.
			((3 to: 4) with: #(seconds: milliSeconds:) collect: [ :index :selector |
				Duration perform: selector with: (matcher subexpression: index) asInteger ]) sum } ] ])
		select: #notNil.
```

**Comment by Rinzwind** [comment]
As shown in [my first comment in pull request #13777](https://github.com/pharo-project/pharo/pull/13777#issuecomment-2016488515), there’s an error in the `#setUp` of various tests in ‘Tests-windows-64-Epicea-Tests-Test.xml’. Pull request #16342 fixes that.

I’m not sure why the error is causing the Windows test runs to time out though. I did notice that in the test report I quoted in pull request #13777, the ‘time’ of the ‘testsuite’ is just 24.537 seconds:

```
<testsuite name="Epicea-Tests" tests="55" timestamp="12:39:40.92 pm" seed="1053542408"  failures="0" errors="110" time="24.537">                                                            
	<testcase classname="Windows64.Epicea.Tests.EpAnnouncementsTest" name="testMonitorAnnouncesUpdateWhenDisabled" time="0.631">
		<error type="SymbolNotFoundError" message="Could not find symbol named: #GetTempPath2W searching in module: 'Kernel32'">
```

While in the [same test report of ‘Pharo12’ build 1455](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo12/1455/artifact/Tests-windows-64-Epicea-Tests-Test.xml/*view*/) it is 561.668 seconds:

```
<testsuite name="Epicea-Tests" tests="55" timestamp="8:27:32.849 pm" seed="609081109"  failures="0" errors="110" time="561.668">                                                           
	<testcase classname="Windows64.Epicea.Tests.EpAnnouncementsTest" name="testMonitorAnnouncesUpdateWhenDisabled" time="19.204">
		<error type="SymbolNotFoundError" message="Could not find symbol named: #GetTempPath2W searching in module: 'Kernel32'">
```

I got the first test report by temporarily modifying ‘runTests.sh’ to run ‘Epicea-Tests’ first (through commits 748bfc323279021d and 00b8614c71ebc19b in pull request #16337). The second test report is from running ‘Epicea-Tests’ after several other test packages. I’m guessing the ‘time’ difference may be due to the other tests somehow causing the Fuel error serialization for each test in ‘Epicea-Tests’ to take much longer, resulting in the timeout of the entire Windows test run.

**Comment by Rinzwind** [comment]
One of those other test packages in ‘Pharo12’ build 1455, which specifically seems to cause ‘Epicea-Tests’ to take longer, is ‘PharoDocComment-Tests’. Using the Dockerfile given below, I get just 9 seconds for ‘Epicea-Tests’ when running it by itself:

```
$ image=$(docker build -q .) && docker run "$image" Epicea-Tests
Running tests in 1 Packages
Beginning to run tests of Epicea-Tests with random seed 786879616
Finished to run tests of Epicea-Tests in 9 seconds 416 milliseconds 682 microseconds
55 run, -55 passes, 0 failures, 110 errors.
```

And 7 minutes for ‘Epicea-Tests’ when running it after ‘PharoDocComment-Tests’:

```
$ image=$(docker build -q .) && docker run "$image" PharoDocComment-Tests Epicea-Tests
Running tests in 2 Packages
Beginning to run tests of PharoDocComment-Tests with random seed 786879810
Finished to run tests of PharoDocComment-Tests in 683 milliseconds 591 microseconds
Beginning to run tests of Epicea-Tests with random seed 109071536
Finished to run tests of Epicea-Tests in 7 minutes 10 seconds 806 milliseconds 197 microseconds
1368 run, 1258 passes, 0 failures, 110 errors.
```

**Dockerfile:**

```dockerfile
FROM almalinux:9
# The following file is from: https://github.com/pharo-project/pharo-launcher/actions/runs/7669561590
COPY PharoLauncher-linux-37d81461-x64.zip .
RUN yum install -y unzip && yum clean all && rm -rf /var/cache/yum
RUN unzip -p PharoLauncher-linux-37d81461-x64.zip | tar -x
RUN mkdir /root/Pharo
RUN ./pharo-launcher/pharo-launcher image create fromBuild --newImageName test-image 1455
RUN /root/Pharo/vms/120-x64/pharo --headless /root/Pharo/images/test-image/test-image.image eval " \
	UnixResolver compile: 'temp \
		Error signal'. \
	TestCommandLineHandler compile: ((TestCommandLineHandler sourceCodeAt: #packages) \
		copyReplaceAll: 'Set' with: 'OrderedCollection'). \
	Smalltalk snapshot: true andQuit: true"
ENTRYPOINT ["/root/Pharo/vms/120-x64/pharo", "--headless", \
	"/root/Pharo/images/test-image/test-image.image", "test", "--junit-xml-output"]
```

**Comment by MarcusDenker** [comment]
This seems to be fixed
