### ISSUE TITLE
update after asDate deprecation

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15164]
The log says: 

The method Date class>>#fromString: called from String>>#asDate has been deprecated.

**Comment by Ducasse** [comment]
The method Date class>>#readFrom: called from Date class>>#fromString: has been deprecated. Use Date>>#readFrom:pattern: specifying a concrete pattern instead.

**Comment by Ducasse** [comment]
I'm wondering if we should not rollback the deprecation for now.

**Comment by Ducasse** [comment]
But may be this is simple to fix. May be the deprecation could set the default pattern.

**Comment by guillep** [comment]
PR Reverted in https://github.com/pharo-project/pharo/pull/15227 and reopened in https://github.com/pharo-project/pharo/pull/15228.

It's not clear from the comments if the bootstrap warnings are actually blocking or not.
There was also a report of broken tests.

This comment will link the PR with this issue. I'll close this one and rework it during the week when I come back from vacation.
