### ISSUE TITLE
explicitRequirement causes significant slowdown

### ISSUE THREAD

**Issue by JanBliznicenko** [guillep/pharo-core#15169]
Using `self explicitRequirement` can be quite slow compared to, for example, calling super.

It might not be noticable and barely measurable if it is called sporadically or if the actual implementation of the method is quite slow anyway, but if such method with `explicitRequirement` is called many times in a loop and the actual implementation of the method is quite fast, it can make incredible difference.

I found this out because Roassal started using `explicitRequirement` in many traits, and it caused mouse event handling to take 3 times longer in some cases (https://github.com/pharo-graphics/Roassal/issues/10).

Example:
```Smalltalk
actualExampleCode := 'example ^ ''hello'''.
[
  traitExplicit := Trait named: #TExplicit.
  traitExplicit compile: 'example ^ self explicitRequirement'.
  superclassExplicit := Object subclass: #SuperclassExplicit.
  superclassExplicit compile: actualExampleCode.
  subclassExplicit := superclassExplicit subclass: #SubclassExplicit uses: traitExplicit.
  instanceExplicit := subclassExplicit new.
  
  traitSuper := Trait named: #TSuper.
  traitSuper compile: 'example ^ super example'.
  superclassSuper := Object subclass: #SuperclassSuper.
  superclassSuper compile: actualExampleCode.
  subclassSuper := superclassSuper subclass: #SubclassSuper uses: traitSuper.
  instanceSuper := subclassSuper new.
] on: Deprecation do: #resume.

Smalltalk garbageCollect.
explicitRequirementsTime := [ 1000000 timesRepeat: [ instanceExplicit example ] ] timeToRunWithoutGC.

Smalltalk garbageCollect.
superTime := [ 1000000 timesRepeat: [ instanceSuper example ] ] timeToRunWithoutGC.

{	 
  'explicitRequirements' -> explicitRequirementsTime.
  'super' -> superTime
} inspect.
```

In this example, using explicitRequirements takes, on my machine, over 100x longer. If the code of the `example` method takes more time, like `example ^ DateAndTime now - DateAndTime tomorrow`, the difference is less extreme, but it is still there (2 sec vs 3 sec on my PC).

![obrazek](https://github.com/pharo-project/pharo/assets/9571633/4cfff257-3135-44d9-beb1-d153ae190e0c)

Pharo 11 and 12 (build.973.sha.c0bd11f), measured in 12,
Windows 11,
VM v10.0.0.8

**Comment by MarcusDenker** [comment]
#explicitRequirement is quite complex. it uses thisContext to find the receiver/selector/args of the send... and does the lookup for a method, then executes it reflectively:

```
explicitRequirement
	"If one of the superclasses can perform the selector, we execute the method of that class, otherwise, the explicit requirement error is thrown"
	<debuggerCompleteToSender>
	| originalMethod originalArguments errorBlock originalReceiver callingContext originalSelector |
	errorBlock := [ ^ self error: 'Explicitly required method' ].
	callingContext := thisContext sender.
	originalMethod := callingContext homeMethod.
	originalMethod isFromTrait
		ifFalse: [ errorBlock value].
	originalReceiver := callingContext receiver.
	originalSelector := originalMethod selector.
	originalArguments := callingContext arguments.
	originalReceiver class superclass
		withAllSuperclassesDo: [ :superClass |
			superClass
				compiledMethodAt: originalSelector
				ifPresent: [ :method |
					(method isProvided or: [ method isFromTrait not ])
						ifTrue: [ callingContext
								return:
									(method
										valueWithReceiver: originalReceiver
										arguments: originalArguments) ] ] ].
	errorBlock value
```

inlining the errorBlock would remove one block creation, but that will not be a huge speedup.

I think the only way to speed it up for real would be to generate this method statically at compile time. We know all the needed infos, instead of looking up the method and executing it reflectively, we could check if we could  (ab)-use the super send bytecode (the variation that gets the class from the stack) to do the send.

**Comment by MarcusDenker** [comment]
I think "self explicitRequirement" is very similar to what "super" is "send this method to self, but use another lookUp to find the method to execute"
. 
Which means one can understand it as a PseudoVariable.

It would be an interesting experiment to implement a PseudoVariable sublass... with a generate method that implements this by emitting bytecode directly, using the static info that is available.

(this does not mean that I think it *should* be PseudoVariable, just as an experiment...)

**Comment by jecisc** [comment]
We discussed with Pablo and thought about two possible solutions that I'll write here to keep trace.

The first solution would be at the installation of the trait in the class, to copy the explicit requirement methods only if they have no equivalent in the super class. We will need to be careful also about some cases were we later install a method.

The second solution would be to update the code executed by the #explicitRequirement to first do a super of the method been executed to not lose time, and catch a potential DNU to then raise the explicit requirement exception

**Comment by jecisc** [comment]
Just a note for myself: I want to try to implement the second solution and here is a method that can be useful to do that: `Object>>#perform:withArguments:inSuperclass:`

**Comment by Ducasse** [comment]
To me all these introduce just more complexity.  
explicitRequirement is static so I hate all the implementations that require a runtime check. 
And I would just remove them. We do not even know if a method raises an exception or if a class defines all its subclass responsibility methods so why do we do something special for trait requirement. 
This is something that I not get.
