### ISSUE TITLE
Should we keep #acceptsLoggingOfCompilation?

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#15171]
Maybe @MarcusDenker knows why this is here?

This methods only returns true in the image and the only class implementing it has an implementation returning true (except for its subclasses but it has none). 

Maybe we could just remove that and always log except if we configure to not log things?

**Comment by MarcusDenker** [comment]
yes, this looks like like a workaround introduced just for the fonts that used to be stored in huge methods in one class

we still abuse methods to store data, but we never turned off logging in the .changes. The granularity "per class" seems to be wrong, too.

So I vote for removing this hook

**Comment by MarcusDenker** [comment]
take care: Fuel uses this in tests to compile methods without sources to test that it can serialize/deserialize those.

Else there seem to be no users at all
