### ISSUE TITLE
The OK-Cancel and Accept-Cancel buttons positions

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#15218]
**Bug description**
In refactorings, the dialogs use button pairs OK-Cancel and Cancel-Accept button possitions in the mentioned order. Which means, the Cancel option is each time in the different position, which is really horrible UX

![Pharo_3PXx1PQR3D](https://github.com/pharo-project/pharo/assets/572494/aca112ca-7f6e-4058-9946-1c34c1e0f837)

**Comment by Ducasse** [comment]
I agree and this is the same problem in Iceberg. Thanks for reporting. I would like that the tools use a predefined order because this is annoying and also all the dialogs MUST have a default so that we can type enter.

**Comment by balsa-sarenac** [comment]
This seems fixed now.
