### ISSUE TITLE
Pharo Association website git repo missing

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#15224]
1. The website for the **Pharo website** (https://www.pharo.org) has its source and repo in git (https://github.com/pharo-project/pharo-website)

2. The website for the **Pharo consortium** (https://consortium.pharo.org) has its source and repo in git commited by @estebanlm (https://github.com/pharo-project/pharo-consortium-site)

What might be missing is 

3. a git repo for the **Pharo association** website (https://association.pharo.org)

This website also lacks the nice logo:

<img width="115" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/926cd177-e8fd-4001-a58f-f32b48dbc80b">

that @Ducasse had in its ESUG 2023 Welcome talk (see https://www.youtube.com/watch?v=EskqBFtYpfs at 5:45)

**Comment by MarcusDenker** [comment]
This website is not created from any source but with another platform (using some CMS)

**Comment by astares** [comment]
OK - then this is not missing. We can close this one then
