### ISSUE TITLE
Rename TraitsV2 into Traits ?

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#15298]
We often integrate some projects with some "New" or "V2" in the name but over the years it's not new or nobody uses the V1 anymore.

I propose to rename TraitsV2 into Traits because I don't think anybody uses a V1 anymore

**Comment by astares** [comment]
Spec2 into Spec?

**Comment by tesonep** [comment]
👍

**Comment by MarcusDenker** [comment]
We can even think of removing the compatibility package at some point

**Comment by jecisc** [comment]
Spec but also NewTools into Tools :p 

For the compatibility package, I saw it recently and I was thinking the same but I don't really know what this is. I was planning to look at the code or discuss with pablo before doing anything because I have no idea if we can just remove it or if some code still rely on it.
