### ISSUE TITLE
Browser: Accepting a class definition with no change does not refresh

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15334]
so if do expand to get all the fluid API and I fill up the template then...
accept (compiling) does not call the printer and we get the same and not the compact form :(

We get
```
Object << #Grb
	layout: FixedLayout;
	traits: {};
	slots: { #point . #point2 };
	sharedVariables: { #C1 . #C2 . #C3};
	sharedPools: {};
	tag: '';
	package: 'Refactoring-Junk'
```

while we should get

```
Object << #Grb
	slots: { #point . #point2 };
	sharedVariables: { #C3 . #C1 . #C2 };
	tag: '';
	package: 'Refactoring-Junk'
```

**Comment by Ducasse** [comment]
And I do not see why we need a tag with an empty string. Argh again we should put all the options in the face
of the developer in case.... I hate such design that polutes my mind when I'm coding.

**Comment by MarcusDenker** [comment]
For me it works, I accept and the pane is refreshed. As we never save the code of the definition, any re-render has to pretty-print the definition according the class printers default

**Comment by MarcusDenker** [comment]
Ah, I found the case where this happens:

-> you have a class already
-> you accept a define which actually *does not change the class*  (e.g add a second class var with an existing name, the system knows that there can be only one)
-> as no class is changed, I think we do not raise an announcement, which in turn means the browser does not refresh (as nothing changed)

So we should refresh always somehow and not rely on the class builder's announcements

**Comment by MarcusDenker** [comment]
This happens in Pharo11, too

**Comment by Ducasse** [comment]
This is strange because that class was new. 
I will retry.
Because I was really using the expand functionality.

**Comment by Ducasse** [comment]
Here are the step by step issues:
- define a class for example `#MyClass4566`
```
Object << #MyClass4566
	slots: {};
	tag: '';
	package: 'Refactoring-Environment-Tests'
```
- use expand
```
Object << #MyClass4566
	layout: FixedLayout;
	traits: {};
	slots: {};
	sharedVariables: {#C1};
	sharedPools: {};
	tag: '';
	package: 'Refactoring-Environment-Tests'
``` 
- Compile the class and it is not refreshed.
- We do not get 
```
Object << #MyClass4566
	sharedVariables: {#C1};
	package: 'Refactoring-Environment-Tests'
```

**Comment by jecisc** [comment]
Maybe we see it more often because I fixed bugs in the change detector that was considering that changes happened sometimes when there was no change in reality?

**Comment by Ducasse** [comment]
I do not know but I see it systematically following the steps I mentioned and the class is changed.
