### ISSUE TITLE
Classes with shared pools cannot be created

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#15345]
**Bug description**
Saving a class definition with a shared pool in Calypso causes an error

**To Reproduce**
1. Go to `Time` class in Calypso, the tab with the class definition
2. Modify the class definition to create a new class named Time2 with otherwise the very same definition (just add postfix "2" to the class name), so 
```smalltalk
Magnitude << #Time2
	slots: { #seconds . #nanos };
	sharedPools: { ChronologyConstants };
	tag: 'Chronology';
	package: 'Kernel'
```
3. Save the new definition
4. See error `Instance of ChronologyConstants class did not understand #asSymbol`

**Version**
Pharo 12.0.0
Build information: Pharo-12.0.0+build.1039.sha.3082affa8788ebb312a021e847546242c1408e51 (64 Bit)

**Comment by pavel-krivanek** [comment]
It is not even needed to try to create a new class, just add space on some safe place to make the `Time` class definition dirty and save it.

**Comment by Ducasse** [comment]
It can be related to https://github.com/pharo-project/pharo/issues/15335.

**Comment by MarcusDenker** [comment]
Not related to https://github.com/pharo-project/pharo/issues/15335.

This was introduced by the unification and cleanup of the class builders, combined with the base reflective model still using names of variables often while the builder uses Variable instances.

Here Class>>#sharing: is called (via the classBuilder), but it passes the Variable, not the name of the Variable.

**Comment by tinchodias** [comment]
Hello, I got the same error. As a workaround, I discovered that it works when you prefix shared pool names with a `#`. In the example:
```
Magnitude << #Time2
	slots: { #seconds . #nanos };
	sharedPools: { #ChronologyConstants };
	tag: 'Chronology';
	package: 'Kernel'
```
And then accept with cmd+s works in Calypso.

**Comment by MarcusDenker** [comment]
The fix is to change ShiftClassBuilder>>#createSharedVariables to use #sharedPoolNames

```
createSharedVariables

	self builderEnhancer on: newClass declareClassVariables: self layoutDefinition sharedVariables sharing: self layoutDefinition sharedPoolNames
```

and ShLayoutDefinition>>#sharedPoolNames


```
sharedPoolNames
	^ self sharedPools collect: [ :each | each name]
```

**Comment by MarcusDenker** [comment]
This is sadly more complicated: the class builder uses a string based API everywhere for the tests... lots of refactoring needed to fix it for real, as a workaround the described change breaks all the tests that use strings.
