### ISSUE TITLE
Renaming a method protocol has no effect

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#15387]
- latest image as of today - Pharo-12.0.0+build.1058.sha.d7fe9c39709fd9c1855730743d80c4c7d49a116d (64 Bit)
- create a package "Foo" with a class "Bar"
- create a method category "test"
- then use "Rename" from context menu and give it a new name "testing"

=> Renaming has no effect

I think this is related to the package / tag work that @jecisc is doing which is either WIP or broke the renaming.
Just want to mention it as an issue so it is not forgotten

<img width="341" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/d1072cc5-74e0-40f6-ba4e-571f3a23ab48">

**Comment by jecisc** [comment]
I just followed your steps and it worked for me on the latest Pharo 12 on OSX

**Comment by astares** [comment]
@jecisc tried (again with fresh image) also on Linux. Same effect.

[Screencast from 2023-11-17 14-52-54.webm](https://github.com/pharo-project/pharo/assets/5980033/2be70c8a-204c-4a60-8d76-9f078886e497)

**Comment by astares** [comment]
@jecisc spotted a difference:

- renaming an existing method protocol in the image does work
- renaming a method protocol of a new created class in a newly created package does not work
