### ISSUE TITLE
Not possible to move methods via drag and drop

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#15388]
- latest image as of today - Pharo-12.0.0+build.1058.sha.d7fe9c39709fd9c1855730743d80c4c7d49a116d (64 Bit)
- create a package "Foo" with a class "Bar"
- create another class "Sub" as subclass of "Bar"
- create a simple instance side method "foo" in Bar and save it

Now drag the method from "Sub" subclass and drop it to the superclass "Foo" to move it.

=> System shows a message "Sub does not define #bar" but does not move the method.

In Pharo 11 this was moving the method to the superclass.

<img width="444" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/35e0dec2-a9eb-4165-8387-5cffbc329d63">

This might be a known issue or WIP related to new refactorings. Just wanted to mention it as an issue so it is not missed.

**Comment by jecisc** [comment]
Duplicated of https://github.com/pharo-project/pharo/issues/15193
