### ISSUE TITLE
The taskbar labels stop to be useful

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#15391]
**Bug description**
The window titles in the taskbar are
- not using the available area when they can and shrinking instead
- start to show only type prefix (like Method:, Implementors:) if there is like 12 windows opened which makes them significantly less useful
 
![image](https://github.com/pharo-project/pharo/assets/572494/1e439409-5d0b-4189-aedf-b9e25d2cc1f1)

**Comment by jecisc** [comment]
This should be fixed since a few weeks and remove the prefix. What is your Pharo version?

**Comment by pavel-krivanek** [comment]
ahh, right, it was build 911. Closing
