### ISSUE TITLE
Caro will remove RBRemoveClassVariableRefactoring

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15396]
RBRemoveClassVariableRefactoring is a left over and now the driver is calling RBRemoveSharedVariableRefactoring.
Carolina will read it to see a bit the changes from the old to the new implementation and just remove it.

**Comment by carolahp** [comment]
I tried today, but it's already done and was replaced by RBRemoveSharedVariable. 
Sorry for the delay!
