### ISSUE TITLE
cannot drag an drop a method from a class to its super/subclass anymore

### ISSUE THREAD

**Issue by estebanlm** [guillep/pharo-core#15407]
**Bug description**
When I try to drop a method to a different class, I got a message `AClass does not defines #method` .  
(where AClass is anyclass and #method is any method).  

**To Reproduce**
1. in calypso, go to any class. e.g. `AIDijkstra`
2. drag any method, e.g. `newPriorityQueue`  to `AIDijkstra` parent, `AIGraphAlgorithm`.
3. See the error :)

**Expected behavior**
I should be able to drag&drop my methods as before.  

I suspect this is related to the ongoing refactoring work :)

**Comment by Ducasse** [comment]
Ok we will check this.

**Comment by Ducasse** [comment]
Now dropping a method is not a refactoring so I do not see why this would be related to refactorings.

**Comment by jecisc** [comment]
It invokes refactorings to transform and move the method from class A to class B

**Comment by Ducasse** [comment]
Do you know where?

**Comment by jecisc** [comment]
SycMoveMethodsToClassCommand>>#execute

**Comment by Ducasse** [comment]
Thanks because I was look for does not define and I could only see the moveTemporaries which as nothing to do with that.

**Comment by Ducasse** [comment]
I see the target class is uses instead of the source.

**Comment by Ducasse** [comment]
@balsa-sarenac 

The code calling the transformation is correct

```

privateTransform
...
self generateChangesFor:
		(RBAddMethodTransformation
			sourceCode: rbMethod source
			in: newClass
			withProtocol: originalProtocol)
...
```

The target class is correctly set.

**Comment by Ducasse** [comment]
Apparently the RBRemoveMethodTransformation is checking that the method to be removed indeed exists.

```
applicabilityPreconditions
		^ RBCondition definesSelector: selector in: self definingClass
```

Now I checked and self definingClass is correct in the source so I'm investigating more to see why the condition is failing.

**Comment by Ducasse** [comment]
But definesSelector: is checking the wrong class because the one breaking is the one of the RBMoveMethodToClassRefactoring...

```
RBMoveMethodToClassRefactoring >> preconditions
	self halt.
	^(RBCondition definesSelector: method selector in: class) not
```

**Comment by Ducasse** [comment]
As a refactoring it checks (but this is only done for directlydefine methods) that the target class does not define the method and this is correct.

**Comment by Ducasse** [comment]
So I was wrong this is the check in the RemoveMethodTransformation that is checking that the method to be removed actually exist is wrong while it should be true. We check in that the method is actually in the source class. So this is correct.

```
definesSelector: aSelector in: aClass
	^self new
		block: [ self halt.aClass directlyDefinesMethod: aSelector]
		errorString: aClass printString , ' <1?:does not >define<1?s:> ' , aSelector printString
```

**Comment by Ducasse** [comment]
I do not get why realClass is nil and 

```
RBClass >> directlyDefinesMethod: aSelector
	self isDefined
		ifTrue:
			[(self hasRemoved: aSelector) ifTrue: [^false].
			(self realClass includesSelector: aSelector) ifTrue: [^true]].
	^newMethods notNil and: [newMethods includesKey: aSelector]
```

**Comment by Ducasse** [comment]
This is the part of the refactoring engine I did not dive in yet - I was supposing it worked :(

**Comment by Ducasse** [comment]
I'm totally puzzled. Now reading the comment of RBClass it looks like the class is defined/created when a query is done. 
So may be a query is missing like realClassFor:...

**Comment by Ducasse** [comment]
So I have a nice example of need for contextFlow conditional breakpoint.
I would like to be able to say I put a Tag Top in the precondition of RBMoveRefactoring and one in AddRemoveTransformation
and then in the other methods in the flow I would like to be able to have a haltIfFrom: Top or haltIf:...

**Comment by Ducasse** [comment]
I do not understand what the Source class is not defined in the model :( so may be we have two models.

**Comment by Ducasse** [comment]
I tried to force the model used by the transformation


```
privateTransform
	| oldClass newClass rbMethod originalProtocol |
	oldClass := self classModelOf: method methodClass.
	newClass := self classModelOf: class.
	rbMethod := RBClassModelFactory rbMethod for: newClass source: method sourceCode selector: method selector.
	originalProtocol := method protocolName.
	
	self generateChangesFor: 
		((RBRemoveMethodTransformation 
			selector: method selector
			from: oldClass) model: self model ; yourself).
	self generateChangesFor:
		((RBAddMethodTransformation
			sourceCode: rbMethod source
			in: newClass
			withProtocol: originalProtocol) model: self model ; yourself).
```

but it did not change anything

**Comment by Ducasse** [comment]
I do not understand why RBMoveMethodToClassRefactoring is using this code

```
classModelOf: aClass

	| classModel |
	classModel := aClass isMeta
		ifTrue: [ RBClassModelFactory rbMetaclass named: aClass name ]
		ifFalse: [ RBClassModelFactory rbClass named: aClass name ].
	classModel model: self model.
	^classModel
```

**Comment by Ducasse** [comment]
And this is the reason of the bug......................
I hate it so much!!!!

The correct definition is 
```
classModelOf: aClass
	^ self model classObjectFor: aClass
```

else the model ignores that the query was done and so the class is not really well reified. What a fucking bug

**Comment by Ducasse** [comment]
I will do a PR later.

**Comment by Ducasse** [comment]
This is strange because we did not touch this code at all. It is the same as in P11.
