### ISSUE TITLE
Wrong text selection: selection selects an extra character

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15408]
if you look for a piece of text in a method the marked found text is too large.
For example select `does not define`
look for all the methods with it
you will see that `does not define ` is selected and not `does not define`

**Comment by hernanmd** [comment]
I couldn't reproduce the issue:

<img width="1486" alt="Screenshot 2024-01-22 at 13 55 50" src="https://github.com/pharo-project/pharo/assets/4825959/d4693592-bc79-485f-af34-3fa07689558a">

I am missing something?

**Comment by Ducasse** [comment]
When I do it it selects an extra character
Steps to reproduce
- does not define in the method or class pane not quote
- select it and not more than the visible characters
- Source with it in the Search. 
- You get the following

**Comment by Ducasse** [comment]
![Capture 2024-01-22 at 14 04 35](https://github.com/pharo-project/pharo/assets/432549/a4f99524-b70e-4608-ace6-c1bb6d5fbaab)

**Comment by jecisc** [comment]
In a playground menu it is the option "Code search" -> "method source with it..."

**Comment by hernanmd** [comment]
> In a playground menu it is the option "Code search" -> "method source with it..."

Yes, I've got it but the result is what I uploaded above in the screenshot.
I don't see the problem

**Comment by Ducasse** [comment]
I'm trying on Pharo 12.0.0
Build information: Pharo-12.0.0+SNAPSHOT.build.1311.sha.179be510706e561f0f195fe34f76f5f1aedcdf4c (64 Bit)

**Comment by Ducasse** [comment]
And I redid it with the same image without running any preferences.

**Comment by Ducasse** [comment]
@jecisc can you reproduce it because I can systematically

**Comment by jecisc** [comment]
From the playground I cannot but I can from Calypso

**Comment by hernanmd** [comment]
This is because there are three implementations for it

- The one in `methodSourceContainingIt` from Rubric in RubSmalltalkEditor
- The one in `ClyTextEditor`
- The one in `SpBrowseMethodsContainingStringCommand`
 
So I will start removing the Rubric method and add the command to the Source code menu.

**Comment by Ducasse** [comment]
No we should do the inverse. 
This is the responsibility of the text editor to call the correct methods and not the command.

**Comment by hernanmd** [comment]
Found it, seems like a bug in text selection.

![Screenshot 2024-01-24 at 14 37 31](https://github.com/pharo-project/pharo/assets/4825959/63dccf22-abc1-421f-9c52-f7aeb758a658)

I propose to change it to make the method more accurate and handle cases where the searched string is a substring of a larger string in the text:

```smalltalk
findAnyString: strings in: text

	| index |
	strings do: [ :each |
		index := text indexOfSubCollection: each startingAt: 1.
		index > 0 ifTrue: [ ^ index to: index + each size - 1 ] ].

	^0 to: -1
```

The changes are:
- Replace `findString:startingAt:` with `indexOfSubCollection:startingAt:` to handle substrings properly. The `indexOfSubCollection:startingAt:` method is more appropriate when dealing with substrings.
- Adjust the interval calculation to `^index to: index + each size - 1` to correctly represent the interval of the found substring.

**Comment by hernanmd** [comment]
In #16010
