### ISSUE TITLE
error when creating a class from class template

### ISSUE THREAD

**Issue by estebanlm** [guillep/pharo-core#15406]
**Bug description**
fluid class template when you are seeing a package and a tag leads to wrong class categorization when creating one.

**To Reproduce**
1. with calypso opened go to `AST-Core` tag `Formatter`
2. you will see the class template:
```smalltalk
Object << #MyClass
    slots: {};
    sharedVariables: {};
    package: 'AST-Core-Formatter'
```
(which is already wrong)

3. just change a name e.g. `MyClass1` and save, you will have this as a result: 

![Screenshot from 2023-11-17 10-13-13](https://github.com/pharo-project/pharo/assets/513630/878e39e9-a833-45b9-8662-3d36a359f204)

class is created, but in a wrong package :)

**Expected behavior**
I expect the class to be created in the package `AST-Core` with tag `Formatter`.

**Comment by Ducasse** [comment]
I think that cyril decided that you should use a tag so that there is no magic and I agree with him.
Too much magic leads to shit.

**Comment by estebanlm** [comment]
I do agree, what is wrong is the template :P 
when you click on AST-Core tag Formatter you should get a template: 
```smalltalk
Object << #MyClass
    slots: {};
    sharedVariables: {};
    tag: 'Formatter';
    package: 'AST-Core'
```
not what you get now.

**Comment by Ducasse** [comment]
Ctrl -E expand the template

**Comment by jecisc** [comment]
The class template while seelcting a tag in Calypso is wrong. I'll see to fix it.

It currently uses #package: but is giving the category as variable. It should show the tag: and package: parameters with the right arguments

**Comment by Ducasse** [comment]
Cyril it would be good to see why the class definition is not printed on compilation
because for me when I expand it I cannot get it back in the compact form. Probably a problem with calypso.

**Comment by estebanlm** [comment]
> Ctrl -E expand the template

Is not about that, I want that the template to be correct, not a wrong input.

**Comment by estebanlm** [comment]
> The class template while seelcting a tag in Calypso is wrong. I'll see to fix it.
> 
> It currently uses #package: but is giving the category as variable. It should show the tag: and package: parameters with the right arguments

yeah, that :)
