### ISSUE TITLE
Bug in Context >> cannotReturn causing VM crash and illegal return

### ISSUE THREAD

**Issue by isCzech** [guillep/pharo-core#15433]
Consider the following examples:

`[[^ 1] on: BlockCannotReturn do: #resume ] fork.  "VM crash"`

`[[true ifTrue: [^ 1]] on: BlockCannotReturn do: #resume ] fork.  "Illegal return from ^1"`

A fix will follow in a PR.

Explanation: In the first example the VM places a #cannotReturn context on top of the [^1] context which at this time has pc past the last bytecode instruction and thus the VM crashes when attempting to return here.
In the second example the pc is past the return, but more bytecodes follow so the return from #cannotReturn context can happily continue, however, this continuing is "illegal" in the sense it should not have happened.
The two examples should consistently cause a walk-back indicating an illegal return attempt.

**Comment by Ducasse** [comment]
THANKS a lot. 
This is nice to have such bombs :)
The VM should not crash in fact

**Comment by isCzech** [comment]
Hi Stephane @Ducasse ,
> The VM should not crash in fact

Indeed! It's been bothering me for a long time.
The fix seems surprisingly simple after all: just nil the pc before returning:
```
cannotReturn: result

	closureOrNil ifNotNil: [ 
		BlockCannotReturn result: result from: self home.
		^self push: pc; pc: nil ].  "backup the pc for the sake of debugging"
	UIManager default
		requestDebuggerOpeningNamed: 'computation has been terminated'
		inContext: thisContext
```
I'll add some comments and send a PR.

**Comment by Ducasse** [comment]
Thanks. This is cool. Any action to crash the vm in a reproducible way is welcomed :)
I got a crash but impossible to reproduce it, sadly.
