### ISSUE TITLE
Clipboard class should be packaged outside of Morphic-Core

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15446]
And in addition it should not refer to UIManager

```
chooseRecentClipping

	"Choose by menu from among the recent clippings"

	"Clipboard chooseRecentClipping"

	recent ifNil: [ ^ nil ].
	^ UIManager default
		  chooseFrom: (recent collect: [ :txt |
				   ((txt asString contractTo: 50)
					    copyReplaceAll: String cr
					    with: '\') copyReplaceAll: String tab with: '|' ])
		  values: recent
```

```
clipboardText: aText informing: aString
	UIManager inform: aString.
	^ self clipboardText: aText
```

**Comment by astares** [comment]
This "chooseRecentClipping" is used in menus as "Paste..." to paste recent clippings (which is not working anyway)
So we should remove #chooseRecentClipping in the same pass

![image](https://github.com/pharo-project/pharo/assets/5980033/b1b5801f-f699-452c-b40a-953e58d077e3)

**Comment by Ducasse** [comment]
thanks for the investigation.

**Comment by astares** [comment]
@Ducasse The #clipboardText:informing: (second part) is something we need to fix in Iceberg repo, not here in Pharo repo. 
                   It is an extension method on Clipboard from Iceberg. 

The PR #15511 
- packages Clipboard in own package
- fixes the first part #chooseRecentClipping
- repairs the "Paste..." menu
- and adds tests
