### ISSUE TITLE
Clean FindReplaceService Hierachy: Only SpRubFindReplaceService is used

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15442]
It looks like the FindReplaceService is unused. 
Everything is setup but nobody use it. 
I suggest to drop it.

**Comment by MarcusDenker** [comment]
SpRubFindReplaceService is used instead, the class can be removed

**Comment by Ducasse** [comment]
My point is that the other PR removes FindReplaceService but the general question is that there is nobody using the FindReplaceService so we could remove also SpRubFindReplaceService

**Comment by MarcusDenker** [comment]
We can I think collapse the hierarchy. SpRubFindReplaceService is the one used, it is setup in the  BaselineOfIDE>>#postload:package:

```
	RubTextFieldArea defaultFindReplaceServiceClass: SpRubFindReplaceService.
``

**Comment by Ducasse** [comment]
Alain said:

RubFindReplaceService est un modele pour RubFindReplaceServiceWindow.
Toutes les instance de RubFindReplaceServiceWindow utilisent ce modele pour partager les options de recherche.
Quand j’avais fait RubFindReplaceService il y avait aussi un mecanisme pour qu'il n’y ait qu’une seule instance de FindReplace partagée par les éditeurs.
Ce mécanisme n’a pas été maintenu.
Actuellement ça ne semble pas fonctionner car find replace est local à chaque éditeur. C’est plus simple mais c’est parfois gênant…

**Comment by Ducasse** [comment]
I will close this issue. In any case the Spec version is not good and not working.
