### ISSUE TITLE
Finder should be ported to Spec

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15456]
Right now it is in morphic

**Comment by JanBliznicenko** [comment]
I believe there is a issue for that: https://github.com/pharo-project/pharo/issues/12082

@n1toxyz started working on it, but it seems the work was not finished

**Comment by Ducasse** [comment]
hernan did one port.

**Comment by Ducasse** [comment]
```
Metacello new
 	 baseline: 'NewToolsFinder';
 	 repository: 'github://hernanmd/NewTools-Finder:main/src';
 	 load.
```

**Comment by Ducasse** [comment]
https://github.com/pharo-project/pharo/issues/12082
