### ISSUE TITLE
FileList should be ported to Spec

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15455]
Right now it is tighly coupled to Morphic

**Comment by astares** [comment]
Could we have https://github.com/astares/Pharo-Harbour switched from Spec to Spec2 and use
it as a possibly better looking replacement? Ideally in NewTools then,

Screenshots are on the page

**Comment by astares** [comment]
There is also already a new implementation of "NewTools-FileBrowser" by @estebanlm 
which could/should be used as a replacement for FileList in Pharo 12.

For this to work on all platforms we have to get in the PR https://github.com/pharo-project/pharo/pull/15501
to provide a #isHidden method for file references. 

This then could be used for fixing an issue with StFBVisibleFilter to get  "NewTools-FileBrowser-Tests" green for all platforms.
(will provide another PR in NewTools repo for that)

**Comment by hernanmd** [comment]
@astares I am reviewing your implementation, and I think some parts (specially the Wrappers) are really nice and could be merged into the implementation of Esteban. 

It is ok with you if I use the implementation of Harbour for the directory tree?

**Comment by astares** [comment]
@hernanmd yes, license allows it already. Ideally the new File Browser in NewTools will be the future common target/file tool. Would not make sense that anybody builds its own when we can have a single one with all features.

(Harbour is not usable in any recent Pharo anyway as it is based on old Spec)

**Comment by hernanmd** [comment]
Thank you @astares

**Comment by hernanmd** [comment]
I close this issue as the core functionality of the old morphic-based FileList is now ported to Spec 2.
It is accessible by evaluating:

```smalltalk
StFileSystemPresenter open.
```

Feel free to further discuss and open new issues.
