### ISSUE TITLE
Cleanup: AIGraphReducerTest>>#mergedNodesIn: should use isNotNil 

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#15483]
- AIGraphReducerTest>>#mergedNodesIn: should use isNotNil instead of notNil

<img width="582" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/1a724381-9f83-496c-b64d-b642af27098d">

we need to fix this in https://github.com/pharo-ai/graph-algorithms

**Comment by jordanmontt** [comment]
Fixed in
- https://github.com/pharo-ai/graph-algorithms/pull/38
- https://github.com/pharo-ai/graph-algorithms/pull/36
