### ISSUE TITLE
Cleanup: categorize AIPrim

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#15482]
missing class tag for AIPrim

![image](https://github.com/pharo-project/pharo/assets/5980033/1b39e81b-c017-4548-9096-fc0a4f5c0558)

**Comment by astares** [comment]
I think this needs to be fixed in github://pharo-ai/graph-algorithms

**Comment by jecisc** [comment]
Same organization but graph-algorithm repo

**Comment by MarcusDenker** [comment]
was merged and is fixed in latest build
