### ISSUE TITLE
Tests ignore the <timeout: NN> pragma

### ISSUE THREAD

**Issue by lopezca** [guillep/pharo-core#15487]
**Bug description**
The pharo testing booklet indicates that when tests take longer than 10 seconds, the timeout pragma can be added to the test to change this behavior.

**To Reproduce**
a simple test as follows:

```
testWithTimeout
<timeout: 17>
	(Delay forMilliseconds: 15000) wait.
	
	self assert: true.
```

**Expected behavior**
the test completes without errors

**Screenshots**
N/A

**Version information:**
 - OS: Windows 
 - Version: 11
 - Pharo Version : Build information: Pharo-11.0.0+build.713.sha.05938f25d075a29b83ebdd585ba64899b6a0c13e (64 Bit)

Here is a proposed fix, I can do a PR or feel free just to copy from here.
This code looks to see if the tested method as a pragma matching #'timeout:' and if so, extracts the seconds from it.
otherwise it falls back to returning the class default.

```
TestCase>>defaultTimeLimit
	"I define the limit that any testcase should not exceed."
	" I look for the <timeout: 20> pragma that changes the timeout for this specific test in seconds. If not found I use the default value from the class."
	
	(self class compiledMethodAt: testSelector) pragmas 
		detect: [ :p | p selector = #'timeout:' ] 
		ifFound: [ :p | ^ (p argumentNamed: #'timeout:') seconds ] 
		ifNone: [ ^ self class defaultTimeLimit ].
```

**Comment by dionisiydk** [comment]
> testWithTimeout
> <timeout: 17>
> 	(Delay forMilliseconds: 15000) wait.
> 	
> 	self assert: true.

You don't really need a pragma for this. Simply set the #timeLimit using a message:

```Smalltalk
testWithTimeout
         self timeLimit: 17 seconds.
	(Delay forMilliseconds: 15000) wait.
	
	self assert: true.
```

It is more powerful than a static pragma. You have a freedom to change the time limit at any time inside the test. Also you don't need to guess about the unit of the time as we pass full duration instead of a raw number.
I don't know where the booklet got the pragma idea. Possibly it is from other smalltalks. Then probably it makes sense to support it for compatibility reason.

**Comment by jecisc** [comment]
I agree with Denis. I would prefer that we do not have multiple ways to do this if the first one (the #timeLimit: message) has no drawback compared to the first one.

**Comment by lopezca** [comment]
What I like about the pragma is that it stands out a the top of the method and lets you know its a long running test. As for having multiple ways, I was changing the TestCase class default during setup so multiple ways already exist; that said maybe adding one more is not required. 

If it's decided not to revive the pragma, then I propose 2 changes elsewhere:
1) there is 1 test in the image that has it so that should be removed and 
2) changing the pharo testing booklet to remove that reference and instead add the `self timeout:` solution which is also excellent. This would help new users find the best approach right away. 

Thanks for taking the time to look at this.

**Comment by Ducasse** [comment]
Hi carlos 
Could you do a PR on the booklet?
We should remove/transform all the <timeout:> in the image.

**Comment by Ducasse** [comment]
See #15527
