### ISSUE TITLE
The Debugger handles explicit requirement methods wrongly

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#15507]
**Bug description**
When a class uses a trait that defines a method as `self explicitRequirement` and the method is implemented in the superclass, the stepping in the Debugger is different than the actual execution. Actual execution performs the method in superclass while the Debugger steps into the trait method (with `self explicitRequirement`)

**To Reproduce**
1. create these classes and methods:
```smalltalk
Object << #MyClass1
	slots: {};
	tag: '';
	package: 'TraitIssue'.

Trait << #IssueTrait
	package: 'TraitIssue'.

MyClass1 << #MyClass2
	traits: {IssueTrait};
	slots: {};
	tag: '';
	package: 'TraitIssue'.

MyClass2>>#msg
	^ self explicitRequirement

IssueTrait>>#msg
	^ 42
```
2. print-it `MyClass2 new msg`, it returns `42`
3. debug-it `MyClass2 new msg`, step into `msg`
4. The debugger shows the `self explicitRequirement` implementation coming from the trait.

While the `explicitRequirement` mechanism is quite magical, it would be reasonable if the debugger would return a correct value when stepping through or over it, but it does not happen.

**Version information:**
Pharo 12.0.0
Build information: Pharo-12.0.0+build.1084.sha.d7c12ac740d3cb1fbd203ebd087cc3ddec555b20 (64 Bit)

**Comment by Ducasse** [comment]
I really suggest that we remove explicitRequirement. It is a static concept and we simulate it with a lookup. 
It was a nice ideas but there is a mismatch with the dynamic aspects of Pharo.

**Comment by hernanmd** [comment]
About removing explicitRequirement, there is also #15169 discussing it. 
I checked in Pharo 12:

```smalltalk
#explicitRequirement senders size. "301"
```

And mostly belong to Roassal and Traits (to simulate interfaces?).
Are these safely removable? 
Maybe @akevalion could tell us how they help a lot? :)

**Comment by Ducasse** [comment]
We should remove explicitRequirement. 
We do not test that abstract methods are implemented in the subclass. 
We do not know if a method raises an exception. So why do we need a special implementation trick for explicitRequirement?
To me it makes the system more complex for super little added value.

**Comment by Ducasse** [comment]
Of course we can remove all the explicitRequirement. This is the same as if we remove subclassResponsibility.

**Comment by hernanmd** [comment]
> Of course we can remove all the explicitRequirement. This is the same as if we remove subclassResponsibility.

Yes, I have the same impression, it does not provide too much value really.
I will make a pass on this.
