### ISSUE TITLE
[RB] DNU on New subclass, Insert subclass and Insert superclass refactorings

### ISSUE THREAD

**Issue by tinchodias** [guillep/pharo-core#15536]
**Bug description**
In Pharo 12, you get a DNU on New subclass, Insert subclass and Insert superclass refactorings.

**To Reproduce**
1. Create A subclass of Object.
2. Create B subclass of A.
3. In Calypso, select A and click on Refactoring -> Insert Subclass
4. See the error:
<img width="674" alt="Screenshot 2023-11-23 at 22 51 12" src="https://github.com/pharo-project/pharo/assets/3044265/a23cea48-a690-4467-a961-ce2a8c687e14">

Same for the other refactorings.

**Comment by MarcusDenker** [comment]
duplicated https://github.com/pharo-project/pharo/issues/15602
