### ISSUE TITLE
No menubar in Mac OS Sonoma

### ISSUE THREAD

**Issue by koendehondt** [guillep/pharo-core#15564]
**Bug description**
I upgraded to MacOS Sonoma. When opening a Pharo 12 image, I do not see a MacOS menubar anymore. The same happens in Pharo 11.

**To Reproduce**
1. Upgrade to MacOS Sonoma
2. Open an image
3. No menubar is shown

**Expected behavior**
I expect a menu bar.

**Screenshots**
<img width="723" alt="Screenshot 2023-11-26 at 10 43 21" src="https://github.com/pharo-project/pharo/assets/753271/6c43d727-a5c8-4bc1-8938-46b65329e0ac">

**Version information:**
 - OS: MacOS
 - Version: Sonoma 14.1.1
 - Pharo Version: 11, 12 (I did not check older versions)

**Expected development cost**
No idea

**Additional context**
None

**Comment by Ducasse** [comment]
Indeed I'm on Sonoma since a month and I did not notice it but I can confirm it.

**Comment by guillep** [comment]
I tried unsuccessfully:
- updating SDL2 using brew and making Pharo using it (`sdl2--2.30.0.arm64_sonoma.bottle.tar.gz`)
- commenting the code inside `SDLOSXPlatform>>afterSetWindowTitle: aString onWindow: aOSSDLWindow`
