### ISSUE TITLE
calypso: class panel is wrong for shared pools

### ISSUE THREAD

**Issue by estebanlm** [guillep/pharo-core#15578]
When you see a class that has a sharedPool you see something like this: 

```smalltalk
GObject << #GtkWidget
	traits: {GtkTLibrary};
	slots: { #data . #deferActions . #eventControllers . #actionGroups };
	sharedPools: { GtkAccelFlags . GtkAlign . GtkOrientation . GtkStateFlags };
	tag: 'Widget';
	package: 'Gtk'
```

and this is wrong, since the builder does not accepts anymore classes. So you should see something like this: 

```smalltalk
GObject << #GtkWidget
	traits: {GtkTLibrary};
	slots: { #data . #deferActions . #eventControllers . #actionGroups };
	sharedPools: { #GtkAccelFlags . #GtkAlign . #GtkOrientation . #GtkStateFlags };
	tag: 'Widget';
	package: 'Gtk'
```

**To Reproduce**
Just open calypso in any class with a shared pool.

**To discuss**
Why you can't list classes directly anymore? I do not see a clear reason.

**Comment by MarcusDenker** [comment]
related to #15345

**Comment by estebanlm** [comment]
oops, I did not see the original, yes this is duplicated :(
