### ISSUE TITLE
MNU when looking for the writers of a shared pool variable

### ISSUE THREAD

**Issue by tinchodias** [guillep/pharo-core#15592]
**Bug description**
There is MNU when looking for the writers of a shared pool variable: "Instance of ConstantBlockClosure did not understand writesRef:"

**To Reproduce**
1. Browse `ExternalStructure class>>#byteSize`
2. Click on the variable `FFIStructSizeMask`
3. Right click and select Source code --> Writers

**Screenshots**
<img width="737" alt="Screenshot 2023-11-27 at 18 27 38" src="https://github.com/pharo-project/pharo/assets/3044265/33684e85-d456-44ce-b44e-4920a1b5bee8">

**Version information:**
 - Pharo Version 12

Pharo 12.0.0
Build information: Pharo-12.0.0+build.1112.sha.aaff089d5cf557cac72306b5a4d809e3fe689b84 (64 Bit)

**Comment by MarcusDenker** [comment]
#writesRef: needs to be implemented to forward to the compiledBlock in CleanBlockClosure.
(all the other #innerCompiledBlockAnySatisfy: senders are ok, I checked).

As we can access these kinds of variables in clean blocks, it needs to forward, no return false (as e.g. the self scan can do).

And we need a test of course (simplest example for the true case would be a method with a Global that has a constant block, too).
