### ISSUE TITLE
In IceTipGitHubRepositoryPanel>>#newRepository DNU #addRemote:

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#15599]
**Bug description**
I am trying to get an image to do a PR.

- download latest Pharo12
- repair and clone again Pharo12 git repositiry

I get a DNU that IceTipGitHubRepositoryPanel does not understand #addRemote:

**Comment by MarcusDenker** [comment]
I had to remove the #informUser:during: from IceTipGitRepositoryPanel>>#newRepository to make it work

Just removing the return in the block does not solve it, it seems that #informUser:during: does not return the value of the block.

**Comment by tesonep** [comment]
Great, I will fix both

**Comment by tesonep** [comment]
It is fixed in build >= 1158
