### ISSUE TITLE
Instance of IceTipCheckoutModel did not understand application

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#15593]
- Latest Pharo 12
- when trying to checkout the local (up to date) Pharo12 branch using Iceberg:

![image](https://github.com/pharo-project/pharo/assets/5980033/dc84f099-387e-4100-b38d-91a4e79841cd)

**Comment by Ducasse** [comment]
Yes I introduced it but this is a bad idea (this is why I created this issue to fix it later - it is bad because the model should now know the UI but I used the application singleton to be able to work around)
and pablo during the sprint proposed another solution. He should probably push his code. @tesonep

**Comment by Ducasse** [comment]
This is strange that it is breaking because I did not push the code (or I did it). Oops. 
you can define application as StPharoApplication current/default locally.

**Comment by astares** [comment]
If you want to reproduce use the attached Makefile

[Makefile.txt](https://github.com/pharo-project/pharo/files/13481194/Makefile.txt)

- just rename it from Makefile.txt into **Makefile** (GitHub otherwise does not accept upload here)'
- Adopt the first line of the Makefile with your github user (GITHUB_USERNAME) and the fourth line with your author name (AUTHOR_NAME)
- run

```ksh
make clone
```
which is cloing your github fork locally and updates it (also pushes) to make sure your fork is on latest "Pharo12" branch

- then run

```ksh
make fresh
```
this retrieves the latest vm+image freshly from zeroconf. It then attaches the Pharo repo and opens Iceberg. 

When you select "Pharo12" branch you will get the above mentioned error

**Comment by Ducasse** [comment]
Oh I sure it is breaking if you show it to me (I'm sick right now so my brain is not working fast).

**Comment by astares** [comment]
Yes: a presenter (UI) should know about UI stuff (including the #inform: variations).
But not the model. I think this should be rolled back somehow

**Comment by MarcusDenker** [comment]
Same as https://github.com/pharo-project/pharo/issues/15584

**Comment by MarcusDenker** [comment]
Do we revert? I now have no image anymore that I could use to do PRs... as I get this error when I try to put a new image into a state to do a PR.

**Comment by Ducasse** [comment]
We can just define application as 

application
   ^ StPharoApplication current

and we do another pass.

**Comment by tesonep** [comment]
Fixed in latest Pharo (it will be there in build 1148 and so on)
