### ISSUE TITLE
Iceberg cannot import the existing repository

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#15600]
**Bug description**
In the latest P12 build (1142), Iceberg cannot import the existing repository. It raises two debugger errors at once:
- BlockCanntoReturn from `IceTipLocalRepositoryPanel>>#newRepository`
- `Instance of IceTipLocalRepositoryPanel did not understand #register` in `IceTipRegisterRepositoryDialogPresenter>>#doAccept`.

Looks like somewhere the presenter is returned instead of the actual repository object.

It worked correctly in the build 1039

**Comment by tesonep** [comment]
Fixed, will be available in build >= 1542
