### ISSUE TITLE
[RB] There is something strange with the preconditions of removeclassDriver

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15604]
Hi balsa

Once https://github.com/pharo-project/pharo/pull/15598 is integrated I need your look. 

I tried to write a test

```
testBadPathRemovingNonEmptySubWithSubclasses
	
	| pack driver |
	pack := RBPackageEnvironment packageName: 'Refactoring-UI-Tests'.
	driver := RBRemoveClassDriver new 
		scopes: { pack }
		classes: { RBRemoveClassDriver }.
	self setUpDriver: driver.
	driver runRefactoring.
		
	self assert: driver breakingChoices size equals: 2
```

Doing this I got problem with 

```
preconditionAreNotMeta

	^ RBClassesAreNotMetaClassCondition new classes: classesDictionary
```
Because RBCLassesAreNotMetaClassCondition is expecting a collection. 
The select: could iterate over the values, but they were nil

I tried to revisit that way but it did not work. 

```
preconditionAreNotMeta

	^ RBClassesAreNotMetaClassCondition new classes: (classesDictionary keys collect: [:each | self model classObjectFor: each ])
```

but I failed and I need your help.
I will continue to work on the migration of RBCondition and RBMoveInstanceToClass to get a green bar.

**Comment by balsa-sarenac** [comment]
@Ducasse I just took a look, and I think the issue is that model doesn't include class `RBRemoveClassDriver`.

I was able to make the test green with:

```smalltalk
testBadPathRemovingNonEmptySubWithSubclasses
	
	| pack driver |
	pack := RBPackageEnvironment packageNames: { 'Refactoring-UI-Tests' . 'Refactoring-UI' }.
	driver := RBRemoveClassDriver new 
		scopes: { pack }
		classes: { RBRemoveClassDriver }.
	self setUpDriver: driver.
	driver runRefactoring.
		
	self assert: driver breakingChoices size equals: 2
```

**Comment by Ducasse** [comment]
oh stupid me. Thanks for your time!
