### ISSUE TITLE
By default, errors are logged twice to the PharoDebug.log

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#15620]
**Bug description**
By default, errors are logged twice to the `PharoDebug.log` file because `DebugSession logDebuggerStackToFile` is true by default.

Here are the call stacks for both writes:
![image](https://github.com/pharo-project/pharo/assets/572494/bdf0d322-5c9f-4fcc-afa7-010ac9feee43)

**To Reproduce**
1. In a fresh image, do `self halt`in Playground
2. look at `PharoDebug.log`, it contains twice the same content

**Comment by hernanmd** [comment]
From a quick pass on the code, it seems from the code that we could be mixing two concepts: One is dumping stack traces during error exceptions, and another one is dumping stack traces during request opening of a debugger. So I thought about adding a setting to specifically enable stack dump of debugger open requests.

So requesting to open a debugger should log the stack trace?

The entry point to these changes could be `logError:inContext:`

**Comment by hernanmd** [comment]
Closing since it is fixed now.
