### ISSUE TITLE
SpWindowPresenter>>okToChange returns true incorrectly

### ISSUE THREAD

**Issue by ericwinger** [guillep/pharo-core#15646]
**Bug description**
I believe this code is incorrect
```
SpWindowPresenter>>okToChange

	self flag: #TODO. "Maybe wrong?"
	self presenter canDiscardEdits ifTrue: [ ^ true ].
	"Solicit cancel from view"
	self changed: #wantToChange.  
	^ self canDiscardEdits
```

**To Reproduce**
Implement a spec2 presenter where `canDiscardEdits` returns false and none of the window presenter's dependents returns false. The edits will be discarded anyway. 

**Expected behavior**
If the presenter returns false from `canDiscardEdits`, return false from the method because, if I understand the methodology, either the presenter or one of the window presenter's dependents can veto the change. 
I think `
...
self presenter canDiscardEdits ifFalse:[^false]. 
...` is correct. 

**Screenshots**
None applicable

**Version information:**
Ubuntu 20.04

Pharo 11.0.0
Build information: Pharo-11.0.0+build.714.sha.0ead11d0b8573ff685db8a39fceeca2a8d528d3e (64 Bit)

**Expected development cost**
2 cents ... After all, it's just my opinion. :)

**Additional context**
None to add. It seems pretty straightforward.

**Comment by Ducasse** [comment]
Thanks for your report. I will link it to the issue in the Spec project.

**Comment by Ducasse** [comment]
https://github.com/pharo-spec/Spec/issues/1492

**Comment by Ducasse** [comment]
Hi eric

esteban replied on the spec issue. Please have a look. I will close this one to avoid duplication.
