### ISSUE TITLE
Check and add test for  CompiledCode>>#newFrom:

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#15652]
**Bug description**
CompiledCode>>#newFrom: calls basicNew: on super, but it should instead use basicNew:header: to make sure that the header is setup correctly

There seem to be no test.

It is used in the code that is handling an out of memory situation when instantiating compiled code objects, maybe there is some way to test that mechanism, too.

**Comment by hernanmd** [comment]
Marcus are you sure it is `CompiledCode`? Because I only see the method `CompiledMethod>>newFrom:`. There is no newFrom: in CompiledCode.

**Comment by MarcusDenker** [comment]
the PR moves newFrom:  up to CompiledCode, too.

**Comment by MarcusDenker** [comment]
This PR: https://github.com/pharo-project/pharo/pull/15651
