### ISSUE TITLE
[Compiler/Parser] Need to be able to do parse+name analysis forScripting, against a class, without a receiver

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#15708]
**Bug description**
When inspecting (e.g. just inspect 4@5), the inspector has an eval pane were I can put "x" and evaluate it (and it is 4).

But the syntax highlighter shows that variable as unknown (red)

![Untitled](https://github.com/pharo-project/pharo/assets/413057/96dfb9b1-696b-4fc8-9b2a-a4dbfbdaf694)

The reason for this is that in SHRBTextStyler>>#privateStyle: we create the compiler to parse for syntax hightlight like this:

```
compiler := classOrMetaClass compiler
		source: aText asString;
		isScripting: self isScripting;
		requestor: workspace.
```
#isScripting: forces a OCReceiverDoItSemanticScope with a nil scope, as the receiver is not yet known:

```
isScripting: aBoolean

	(aBoolean and: [ self isScripting not ]) ifTrue: [
		self semanticScope: OCReceiverDoItSemanticScope targetingNilReceiver ]
```

We need to add another kind of sope for this case OCClassDoItSemanticScope, which models a DoIt where we have no receiver yet but know the class that the receiver will have. Then we use this instead of targetingNilReceiver.

**Comment by dionisiydk** [comment]
> #isScripting: forces a OCReceiverDoItSemanticScope with a nil scope, as the receiver is not yet known:

But why the receiver is not yet known? It seems this is the bug

**Comment by MarcusDenker** [comment]
Ah... we do have the workspace in hand, so we can just ask for #doitReceiver. I will do a PR
