### ISSUE TITLE
Leak in the Finalization Registry - Ephemerons

### ISSUE THREAD

**Issue by PalumboN** [guillep/pharo-core#15718]
Yesterday, we were debugging some bugs and, at some point, the image grew too much (~20G).

So, I **closed all windows** and started to search where is the leak from a new empty (without variables) workspace.

**StDebuggers zombies**
I found that many debuggers are still alive, even after closing all windows and passing the GC (many many times).

<img width="714" alt="image" src="https://github.com/pharo-project/pharo/assets/4098184/3eaedb9e-c0fc-44fe-a3d6-93da95aaa275">

So, I used the ReferenceFinder to look for some path to one of them and I found this loooong list of **ephemerons**:

<img width="1134" alt="image" src="https://github.com/pharo-project/pharo/assets/4098184/165c9613-42fc-4aa3-9fac-1f1a82a63ca2">

This is because when a StDebugger is instantiated, it is subscribed to some (weak) announcements, you can check this method:
```st
StDebugger >> susbcribeToExtensionToggleAnnouncement

	SystemAnnouncer uniqueInstance weak
		when: StDebuggerExtensionActivationToggle
		send: #updateExtensionsFromAnnouncement:
		to: self
```

From here I had 2 questions:
1. If the ephemeron still is there, is the StDebugger being pointed for another object?
2. Why does the double-linked list in the FinalizationRegistry say that only has one element when the chain has more than 9k items?!
<img width="1123" alt="image" src="https://github.com/pharo-project/pharo/assets/4098184/7b786b90-8bf9-4f07-b2c6-5a94b9830766">

-----

#### 1. Is the StDebugger being pointed from a non-ephemeron object?

I looked for another path to the StDebugger, ignoring the FinalizationRegistry:

<img width="1329" alt="image" src="https://github.com/pharo-project/pharo/assets/4098184/3724b527-0fdd-4db8-9dbd-513aafc55468">

The answer is **no**. All the reference paths to this object come from the ephemerons. 

_That means that the problem is in the ephemeron list_ ??

#### 2. The FinalizationRegistry is buggy?

Checking the double-linked list in the `FinalizationRegistry default` I saw that the head element is disconnected from the tail:
<img width="1137" alt="image" src="https://github.com/pharo-project/pharo/assets/4098184/147b65ee-6d3c-4c34-a247-d13f2c796720">

So, yes, **this list is broken**. The head seems to be an ephemeron that was already finalized but it is still there (zombie ephemeron?).

Now I have other 2 questions:

1. Why the ephemeron (and the StDebugger) is still there anyway?
2. How is possible that the registry list is broken?

---------

Well, trying to answer my last questions, my image arrived at more than 40GB (and growing) and my machine could not continue executing it anymore 😄 
<img width="421" alt="image" src="https://github.com/pharo-project/pharo/assets/4098184/4c7d4bb4-8840-4864-b3dd-bf160c90aa85">

So I had to kill it 😢

I put here some thoughts and things that I want to do, for the next time:

#### 1. Do we have zombie Ephemerons?

- This is difficult to check in the image because we cannot access the format of the object (I think, I'm not sure)
- Check if there is one Ephemeron referenced from more than one DoubleLink (it shouldn't!)
  - A "zombie Ephemeron" (I refer to an Ephemeron that was fired and should not exist anymore but is still alive because of a not-expected reference) can be the cause of avoiding the finalization of other ephemerons.

#### 2. How is possible that the registry list is broken?

- Maybe a race condition between adding new ephemerons and the process to remove them?
- A bug in the DoubleLinkedList code? I don't think that...

------

**Version information:**
 - Pharo 11

**Comment by Ducasse** [comment]
Thanks for this gorgeous gorgeous explanation!!!!!! Now we should check this in P12 no?

**Comment by noha** [comment]
And please backport the fix then, please!

**Comment by Ducasse** [comment]
Close it if necessary

**Comment by noha** [comment]
I did not experience leaks anymore. Neither in p11 nor in p12. So I'm closing this
