### ISSUE TITLE
testNoSentButNotImplementedSelectors

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15719]
testNoSentButNotImplementedSelectors is really not self explanatory. I never get what is the No.
We should rename it and provide a better explanation.

**Comment by astares** [comment]
Yes, we could improve the name:

testNoSentButNotImplementedSelectors is basically "test that we have no selectors remaining that are sent but not implemented"


Maybe we should use:

#testThatThereAreNoSelectorsRemainingThatAreSentButNotImplemented
