### ISSUE TITLE
[Debugger] `Run to` corrupts the variables view

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#15721]
**Bug description**
When "Run to" operation is used, the variables view is filled with a lot of mess.

**To Reproduce**
1. Debug this expression `#(1 2 3) collect: [:each | each  + 10]`
2. Step into `collect:`, the current debugger position will be at the message `species`
3. Select `newCollectionn next-to-last line, RMB and from the context menu, select `Run to`
4. The variables view will have many duplicities of `aBlock` and `newCollection` variables:

![image](https://github.com/pharo-project/pharo/assets/572494/d5457cb0-c882-4014-9d22-348738efa95e)

**Comment by adri09070** [comment]
duplicate with https://github.com/pharo-spec/NewTools/issues/607

**Comment by StevenCostiou** [comment]
I think it was fixed by https://github.com/pharo-spec/NewTools/pull/642
