### ISSUE TITLE
Calypso discard code with error and prevent to fix it

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#15730]
Recently in Pharo if you type a method or a class definition in calypso which will cause an error during the compilation or the installation, Calypso will just remove all your code and show either the class creation template and the previous method that was edited. 

Because of this we cannot just fix our error and we have to type everything once again. 

I think I saw some changes of @tesonep recently on calypso refresh. Maybe this is related? (I am not sure)

**Comment by MarcusDenker** [comment]
The PR was this: https://github.com/pharo-project/pharo/pull/15538

There was another PR related to refresh, but that just changed the code when accepting Classes: https://github.com/pharo-project/pharo/pull/15619

**Comment by MarcusDenker** [comment]
Yes, it that.

- go to ClyTextEditorToolMorph>>#changesAccepted
- comment out the second "setText: self editingText."  
- after it keeps the code with the syntax error
