### ISSUE TITLE
OldClassDefinitionBuilder needs to support #uses:instanceVariableNames:

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#15733]
**Bug description**
In the log on the CI we see some

```
Deprecation: Automatic deprecation code rewrite: The method Metaclass>>#uses:instanceVariableNames: called from UndefinedObject>>#DoIt has been deprecated. Use #trait:slots: instead.
```

What happens is that the tests for traits test fileout/reading of .cs files. (TraitFileOutTest>>#testFileOutTrait)

As OldClassDefinitionBuilder class>>#allowedSelectors does not list  #uses:instanceVariableNames: (as the OldClassDefinitionBuilder does not support it yet), we fall through to eval and call the deprecated method.

(see DoItChunk>>#importFor:logSource:)

**What needs to be done**

- add  #uses:instanceVariableNames: to #allowedSelectors
- Fix OldClassDefinitionBuilder to parse it correctly

**Comment by Ducasse** [comment]
For fileout why do we output the old format?

**Comment by MarcusDenker** [comment]
yes

- we have to support reading old format anyway
- the new format does not fit well with the ! as class defs evaluate to a builder, not a class, so they I think never worked for .cs and .st fileout

**Comment by Ducasse** [comment]
Why the reader can read a class def and send install. 
We have a code importer for legacy so why not using it.
