### ISSUE TITLE
Should git commit really auto-save the image by default?

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#15737]
**Bug description**
When the possibiity for auto-save on commit was added, we made it the default.

But is that really good? To me it would be better to turn this off.

Or, if we really want it, remove the dialog.

**Comment by astares** [comment]
I disklike it too as a default - but other might want it for comfort and safety

As a compromise maybe we should have a setting (if not already) and ask the first time if not yet set

**Comment by hernanmd** [comment]
I don't like this auto-setting neither and I've always [disabled](https://github.com/hernanmd/pharo-startup-settings/blob/aceff6c8e0d038b220f0adc2528cffb3d2d1586c/startup.st#L13) this setting in a startup script.

```smalltalk
IceTipCommitSettings saveImageOnCommit: false. 
```

**Comment by jecisc** [comment]
I like the setting but I don't like the popup I have to click on. 
I prefered the inform that was in a corner and that vanished with time

**Comment by Ducasse** [comment]
We should migrate the inform: now that there is the "notificationCenter" in the system.
And this auto save can save you lot of pain.

**Comment by Ducasse** [comment]
If someone has cycles: https://github.com/pharo-spec/Spec/issues/1487

**Comment by guillep** [comment]
I think there are several things to take into account here:

*About the save on commit*
- newcomers in general tend to forget to save the image. This feature helps them to (a) not forget and (b) keep their images in sync with their git repositories, which is not a minor issue.
- experienced people (@MarcusDenker , @hernanmd , @jecisc etc) know how to change a setting and do it manually, as @hernanmd correctly explains.

I think we should take newcomers into account and make them have a better initial experience.
In this sense, I think the *feature is good*, and the fact that it has an associated setting is also good.
The open question, unrelated to this issue, is how to make them transition from newcomer to expert.

Second, is the *intrusive popup* :)
- Before, this was directly using `UIManager`, which means a dependency to Growl notifications and indirectly to Morphic.
- Recently this was changed to use Spec interaction system, but as @Ducasse says, there is still missing support for notifications in Spec

**Comment by estebanlm** [comment]
the save image can be also disabled by pressing thge toggle button that is shown there, and it will remind it... why this would be a problem?

**Comment by Ducasse** [comment]
Indeed so for me I would close this issue because this is not the design nor the setting that it the problem.
