### ISSUE TITLE
[RB] PushDownClassVariableRefactoring logic is strange

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15750]
The refactoring tries to push the class variable down the subclass that actually uses it.
This is nice idea but what will happen 
- if the user wants to push down the class variables in all the direct subclasses?

The following code looks strange 

```
findDestinationClass
	| classes |
	classes := class withAllSubclasses reject: [ :each |
		(each whichSelectorsReferToClassVariable: variableName) isEmpty
			and: [ (each classSide whichSelectorsReferToClassVariable: variableName) isEmpty ] ].
	destinationClass := classes ifEmpty: [ nil ]
		ifNotEmpty: [ classes asOrderedCollection first ].
	classes do: [ :each |
		(destinationClass includesClass: each)
			ifTrue: [ destinationClass := each ]
				ifFalse: [
					(each includesClass: destinationClass)
						ifFalse: [ self signalMultipleReferenceError ] ] ].
	destinationClass = class
		ifTrue: [ self signalStillReferencedError ].
	^ destinationClass
```

**Comment by Ducasse** [comment]
I got one test breaking only on refactoring and not on the transformation. 
Now the transformation logic looks much better than the refactoring one: it creates an addVariable for the same variable for each of the subclasses. So much nicer. 
I skipped the test for now and we will have to have a look when we revisit this refactoring.

**Comment by balsa-sarenac** [comment]
This was cleaned in: #16113!
