### ISSUE TITLE
[RB] Getting failedApplicabilityPreconditions fails

### ISSUE THREAD

**Issue by carolahp** [guillep/pharo-core#15790]
### To reproduce
Try to move an instance side method to a class side method.

### The cause
The following method assumes that `applicabilityPreconditions` returns a collection, but in most of refactorings this method returns an instance of RBCondition.
```
failedApplicabilityPreconditions

	^ self applicabilityPreconditions reject: [ :cond | cond check ]
```

### The problem
The method `applicabilityPreconditions` is sometimes returning a collection and this is useful to handle errors at the level of the driver. 
For example in `RBRenameClassAndDeprecateClassTransformation`, `RBRemoveClassRefactoring` and `RBRenameInstanceVariableRefactoring`

@Ducasse @balsa-sarenac I think we need to find an alternative way to get failed preconditions, but I'm not sure how

**Comment by Ducasse** [comment]
Ok we should think.
