### ISSUE TITLE
Integrate Teachable into SUnitMock

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15806]
I misunderstood the difference between Mock and Teachable and I would really like to have Teachable because one some scenarios it is more adapted than Mock.
I asked Torsten about his ok about it.

https://github.com/astares/Pharo-Teachable

**Comment by astares** [comment]
Feel free to use following the included MIT license. Maybe you also ask @emicklei what he thinks about it as my Pharo port was based on his original idea. 
(see https://astares.blogspot.com/2005/04/teaching-behavior.html about early history of Teachable and the README in https://github.com/astares/Pharo-Teachable)


But be aware that Teachables (while being easy to use and understand on one end) can be more hard to debug in certain situations compared to writing a real mock object. It depends on the use case as usual when to apply them best,.

<blockquote><img src="https://lh3-testonly.googleusercontent.com/blogger_img_proxy/AJ0KDdUVcHco7e1mwftzC7jPaMBDVyS_ji0SQhO9_AIdWcBMZ28JKBTBSSFvdNTB7wYL1b6OPi3c3fA0no2rFTvKgtDnJ4doFEjwItPApOgXwjdqwp0q4dYXnwC1tEY_Nx9l6g=w1200-h630-p-k-no-nu" width="48" align="right"><div><strong><a href="https://astares.blogspot.com/2005/04/teaching-behavior.html">Teaching Behavior</a></strong></div><div>I cleaned up some old VisualWorks  code I had from Ernest Micklei  and published it to the Cincom Public Repository . Watch out for a "Teach...</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/643381dc046eda4dfde699ff06f9aadaf6ecdd20e893e10134300ef49a684126/astares/Pharo-Teachable" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/astares/Pharo-Teachable">GitHub - astares/Pharo-Teachable: A teachable object for Pharo</a></strong></div><div>A teachable object for Pharo. Contribute to astares/Pharo-Teachable development by creating an account on GitHub.</div></blockquote>

**Comment by hernanmd** [comment]
Closing this as #15913 was closed.
