### ISSUE TITLE
Improve doIt in Playground

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#15817]
At ESUG there was a demo project shown to improve the doIt in the Playground to perform doIt activity as
non-blocking action. 

Also it will be possible to cancel the action when (longer) running. 

See https://www.youtube.com/watch?v=FeFrt-kdvms&t=1930s for details

Maybe it makes sense to look into this and bring functionality back into standard Pharo image

**Comment by Ducasse** [comment]
It does! Now they should do a PR. :)

**Comment by Ducasse** [comment]
Eric send the code please.

**Comment by ELePors** [comment]
An override of the playground is made in OpenSmock :
                         https://github.com/OpenSmock/OpenSmock/tree/master/OpenSmock-IDE

It works only on the Do It button, not on actions on the contextual menu.

Eric.

De : StéphaneDucasse ***@***.***>
Envoyé : mercredi 20 décembre 2023 12:26
À : pharo-project/pharo ***@***.***>
Cc : LE PORS Eric ***@***.***>; Assign ***@***.***>
Objet : Re: [pharo-project/pharo] Improve doIt in Playground (Issue #15817)


Eric send the code please.

**Comment by MarcusDenker** [comment]
this was merged
