### ISSUE TITLE
Add unique icons for all major development tools

### ISSUE THREAD

**Issue by daniels220** [guillep/pharo-core#15826]
**Describe the request**
The taskbar is much more useful if it's easy to tell what kind of window each slot represents at a glance, but not all tools have a specific icon for it to use. Notable examples:
* Debugger (the old Glamorous Toolkit debugger had one, a bug, which would work fine)
* Iceberg tools—could all share a single one to start, though it would be cool if certain ones at least had specific icons—distinguishing commit windows from repo-list/working-copy/history windows would be a high priority for me
* Playground has one some places but not others, specifically not the taskbar. The one it does use some places isn't that different from the generic Morph icon either, but I guess it's good enough especially if other tools are more unique.
* Inspector—maybe a magnifying glass?

This is a follow-up to #15825—serving the same goal but seems like a distinct unit of work.

**Expected development cost**
I'm less confident in coming up with the icons themselves here, but otherwise the scope of work is similar to #15825.

**Version information:** Any OS, any Pharo

**Comment by hernanmd** [comment]
If you find (or create) an icon pack or even a set of icons, I would be happy to integrate them.

Check https://github.com/pharo-project/pharo-icon-packs for the directory format and expected SVG scale sizes to provide.


<blockquote><img src="https://opengraph.githubassets.com/3f980df69a8a36114afe35c88eaa37da20736ed1c6ce0eedbfa7ea182661d52e/pharo-project/pharo-icon-packs" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-icon-packs">GitHub - pharo-project/pharo-icon-packs: A repository to keep icon packs for Pharo</a></strong></div><div>A repository to keep icon packs for Pharo. Contribute to pharo-project/pharo-icon-packs development by creating an account on GitHub.</div></blockquote>

**Comment by daniels220** [comment]
Is this actually completed? I don't see anything different in the latest Pharo13 image. Is it a matter of selecting a different icon pack?

**Comment by astares** [comment]
@daniels220 I think it was closed as it was too old (one year) and nobody picked it up.
