### ISSUE TITLE
Add icons for more special/system classes (especially nil)

### ISSUE THREAD

**Issue by daniels220** [guillep/pharo-core#15825]
**Describe the request**
Some special/system classes like Magnitude, Collection, String, Exception have a custom icon that they use in inspectors, the class browser, etc. It would be very useful to have a few more—specifically I would say:
* `nil`/`UndefinedObject`—maybe a grey circle with a "U" or "N" in it, or no letter at all—based on the blue circled-C of classes) This is a big one as right now nil properties just look blank, and while that is _technically_ unique (e.g. an empty string would have the string icon, and display empty quotes), it would be much more intuitive to have an icon solely for nil.
* `Symbol` as distinct from `String`. Just a hash-mark instead of the paragraph symbol would be great.
* `Date` (a calendar), `Time` (a clock), `DateAndTime` (both superimposed, or just pick one if that doesn't work/fit), `Duration` (a stopwatch)
* `Array` as distinct from other collections—a `#()` rather than `{}`.
* `Error`, `Warning` and `Notification` as distinct from `Exception`. Just recoloring the orange bubble to red, yellow, blue respectively would be a good start. Abort, UnhandledException etc. would keep the orange icon, which would usefully serve to point out that they're _weird_ and outside what you normally see in application code.
* Lots of the development tools—that seems worth a separate issue.

I also think it would be useful to have a new generic "Object" icon, so that the icon for classes is _only_ for classes, not their instances. The icon of a class in the class browser would be its _instance_ icon, so it would usually be this new icon, however Behavior, ClassDescription, Class, Metaclass themselves would use the class icon, and when e.g. a temp holds a reference to a class, or inspecting an array containing (a) class(es) they would use the class icon. Perhaps a more attention-getting icon for classes would be appropriate as well as it would now be much more rare.

**Expected development cost**
I don't know how hard it is to add icons to the icon pack. I'd be willing to create the icons themselves and add the necessary methods to refer to them.

**Version information:** Any OS, any Pharo

**Additional context**
There are other classes that I'd like to see icons for, but it gets harder to come up with good ones in such limited space. Most modern UIs leave a little more space for icons—might be something to think about for the future UI work that's being done.

**Comment by hernanmd** [comment]
I agree, additional icons would be really nice to have. Do you have any icon pack with FOSS license to suggest?
They're not so easy to find.

To maintain consistency, if new ones are added, they must have the same color palette as the existing ones. Otherwise, new icons must also be found for all the existing ones and the additional ones you suggest.

**Comment by daniels220** [comment]
I was—perhaps erroneously—assuming that the existing icons were designed in-house, and the new ones would be as well. Of course if we're using an existing FOSS icon pack, we can still design new icons and contribute them back—bonus for everyone else. Certainly for the most important one, `nil`, that's trivial and I'm happy to do it. Some of the others are pretty straightforward as well.

What exactly do you mean by color palette? Just maintaining a consistent appearance—like, if there's green, use this particular green, these shades when you need dark and light, etc? Sure, I can do that.

For the idea of making more space for icons and using larger ones, yeah, that's a whole other job, but that was just a nod to future possibilities, not a serious suggestion right now.

**Comment by astares** [comment]
Side note:
In the past we had several icon themes / "icon packs" like Eclipse, IDEA ... hosted in

https://github.com/pharo-project/pharo-icon-packs

and changable via Settings


<img width="597" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/42527b52-5e61-4ed2-aac5-532c31904717">

There has been a switch to an svg pack too


<blockquote><img src="https://opengraph.githubassets.com/3f980df69a8a36114afe35c88eaa37da20736ed1c6ce0eedbfa7ea182661d52e/pharo-project/pharo-icon-packs" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-icon-packs">GitHub - pharo-project/pharo-icon-packs: A repository to keep icon packs for Pharo</a></strong></div><div>A repository to keep icon packs for Pharo. Contribute to pharo-project/pharo-icon-packs development by creating an account on GitHub.</div></blockquote>

**Comment by daniels220** [comment]
Ah, right—I vaguely remember seeing that in the settings, now that you mention it. I'll have to look at how the system would handle a missing icon—whether it can be told to fall back to a particular alternative rather than a single generic or "error" icon. Would be nice to be able to do a sort of progressive enhancement—add things to the default icon pack, set them up in the image, for other icon packs have it fall back to whatever it does now, and if someone prefers a different icon pack that doesn't have that icon, maybe they could contribute it.

**Comment by daniels220** [comment]
Is this actually completed? I don't see anything different in the latest Pharo13 image. Is it a matter of selecting a different icon pack?
