### ISSUE TITLE
Metacello broken

### ISSUE THREAD

**Issue by theseion** [guillep/pharo-core#15837]
**Bug description**
This PR #15504 (@guillep) has broken SmalltalkCI for Pharo12. In the following method, the `#get` send to a `Metacello` fails:

```smalltalk
basicLoadProjectOn: aSmalltalkCI
	| metacello metacelloPassword metacelloUser |
        "..."
	metacello := (Smalltalk at: #Metacello) new.
        "..."	
	metacello copy get. "----> fails"
```

The failing code is in `MetacelloScriptEngine>>#get`:

```smalltalk
get
  " load a fresh copy from repo"

  | spec projectPackage |
  MetacelloProjectRegistration
    copyRegistryRestoreOnErrorWhile: [ 
      self setDefaultsAndValidateProjectSpec.
      spec := self projectSpec.
      projectPackage := spec projectPackage.
      projectPackage repositorySpecs
        do: [ :repoSpec | repoSpec createRepository flushForScriptGet ].
      projectPackage load. "---> fails"
      "..."
```

**To Reproduce**
This is easily reproducible by cloning SmalltalkCi from https://github.com/hpi-swa/smalltalkCI and running:
```bash
./run.sh -s Pharo64-alpha --headful .smalltalk.ston
```
**Version information:**
 - Pharo Version: 12

**Comment by jbrichau** [comment]
Breaks all builds using Smalltalk-CI.. e.g. https://github.com/SeasideSt/Grease/actions/runs/7308255921/job/19914737832



<blockquote><img src="https://opengraph.githubassets.com/e649d8a5dafdb24b5ff1e544ea5a0133f9f1ee629a351f215054ae43e44b3af0/SeasideSt/Grease" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/SeasideSt/Grease">Add GRPlatform>>sizeOfFile: for older Pharo versions · SeasideSt/Grease@e99e20d</a></strong></div><div>The Grease Portability Library . Contribute to SeasideSt/Grease development by creating an account on GitHub.</div></blockquote>

**Comment by Ducasse** [comment]
Thanks for the feedback.
