### ISSUE TITLE
SpBoxLayout does not use all the space

### ISSUE THREAD

**Issue by koendehondt** [guillep/pharo-core#15830]
**Bug description**

Maybe there is a good explanation why this happens. But it smells like a bug 😀.

**To Reproduce**

Suppose we have a presenter with:
```smalltalk
defaultLayout
	
	^ SpBoxLayout newLeftToRight 
		vAlignCenter;
		add: self newList;
		add: self newList;
		yourself
```

`vAlignCenter` is not relevant for the problem. I applied it to see the window background clearly.

Suppose we open the presenter in a window.

Here is an example. To make the problem visible, I opened a window without decorations (no title etc), and I applied a blue window background and red edge grips (`EdgeGripMorph`). I expect that all the space between the edge grips is used. But it is not. There is an unexpected gap of 2 pixels.

Look at the right side of the right list. There is a 2 pixel gap between the right side of the right list and the left side of the right edge grip.

<img width="410" alt="SpBoxLayout horizontal" src="https://github.com/pharo-project/pharo/assets/753271/53dca0f1-c0cd-4f8f-8e18-e775ceac11ba">

I inspected the morphs. The morph for the left list has width `184`. The morph for the right list has width `185`. The parent morph  (with a `SpMorphicBoxChildLayout`) of the lists has width `369`. Its parent morph (with a `SpMorphicBoxlayout`) has width `371`. There is the 2 pixel difference.

The same happens when using a vertical layout:
```smalltalk
defaultLayout
	
	^ SpBoxLayout newTopToBottom
		hAlignCenter;
		add: self newList;
		add: self newList;
		yourself
```

Look at the bottom side of the bottom list. There is a 2 pixel gap between the bottom side of the bottom list and the top side of the bottom edge grip.

<img width="280" alt="SpBoxLayout vertical" src="https://github.com/pharo-project/pharo/assets/753271/038eec5b-c98d-4af3-a3cf-1cb4ae0246f1">

**Expected behavior**
I expect that all the space between the edge grips is used. Or in other words: I expect that a SpBoxLayout uses all the available space to layout its children. This is important to properly align UI components.

**Version information:**
 - OS: Mac OS
 - Version: Sonoma 14.1.2
 - Pharo Version: 11

**Expected development cost**
No idea.

**Additional context**
None.

**Comment by estebanlm** [comment]
have you tried setting borderWidth: 0 to the layouts?

**Comment by koendehondt** [comment]
I tried it. Now I have:

```smalltalk
defaultLayout

	^ SpBoxLayout newLeftToRight 
		vAlignCenter;
		add: self newList;
		add: self newList;
		borderWidth: 0;
		yourself
```

But the issue remains:
<img width="479" alt="Screenshot 2023-12-22 at 15 25 03" src="https://github.com/pharo-project/pharo/assets/753271/ccee6c52-3ad3-4fea-93e0-1310350c8788">

**Comment by estebanlm** [comment]
can you provide a full example code?

**Comment by koendehondt** [comment]
This is the most simple example I can give that shows the issue:

```smalltalk
| box |
box := SpBoxLayout newLeftToRight 
	add: SpListPresenter new;
	add: SpListPresenter new;
	yourself.
SpPresenter new layout: box; open
```
Here is the result:

<img width="438" alt="Screenshot 2023-12-22 at 16 48 13" src="https://github.com/pharo-project/pharo/assets/753271/023fd1d3-e43d-4443-87fc-84128a538820">

And vertically:

```smaltalk
| box |
box := SpBoxLayout newTopToBottom
	add: SpListPresenter new;
	add: SpListPresenter new;
	yourself.
SpPresenter new layout: box; open
```
<img width="427" alt="Screenshot 2023-12-22 at 16 55 38" src="https://github.com/pharo-project/pharo/assets/753271/22c934db-c70a-4b87-b03f-863ef83df1fc">

**Comment by koendehondt** [comment]
@estebanlm and @Ducasse

I re-analysed the issue and I can confirm that it is a bug. I will state the problem again with a screenshot, I will explain what the bug is, and I will show a screenshot after fixing the bug.

### 1. The problem

Let's use this piece of code to open a window with a box layout with two lists.

```smalltalk
| box |
box := SpBoxLayout newLeftToRight
	spacing: 10;
	add: SpListPresenter new;
	add: SpListPresenter new;
	yourself.
SpPresenter new layout: box; open
```

This is the result. There are 2 extra pixels at the right side of the window.

<img width="437" alt="Screenshot 2024-01-19 at 18 06 35" src="https://github.com/pharo-project/pharo/assets/753271/96ee7637-5989-48dc-97dd-e0721b0c0681">

### 2. The root cause

Morphic uses `SpMorphicBoxAdapter` for a `SpBoxLayout`.

`SpMorphicBoxAdapter>>#newHorizontal` creates a panel with two subpanels, called `startPanel` and `endPanel`. `startPanel` holds all morphs for presenters that are added with `SpBoxLayout>>#add:*` messages. `endPanel` holds all morphs for presenters that are added with `SpBoxLayout>>#addLast:*` messages.

In the example, only `SpBoxLayout>>#add:` is sent, which means that morphs for the two lists are added to the `startPanel`. `endPanel` is empty when the window opens.

`SpMorphicBaseBoxLayout>>#layoutLeftToRight:in:` uses a `SpMorphicBoxLayoutCalculatorLeftToRight` to layout the morphs. `SpMorphicBoxLayoutCalculatorLeftToRight>>#calculateCellFor:` (line 20) sends `minExtent` to the morphs. `Morph>>#minExtent` sends `Morph>>#minWidth`, which is implemented as:

```smalltalk
minWidth
	"answer the receiver's minWidth"
	^ self
		valueOfProperty: #minWidth
		ifAbsent: [2]
```

For the empty `endPanel`, this method answers `2`. So the empty `endPanel` is rendered with a width of 2 pixels at the right side of the second list in the window. That is where the extra 2 pixels come from. That is incorrect. The `minWidth` should be `0`, because `endPanel` is empty.

### 3. Fix

When we change `Morph>>#minWidth` to:

```smalltalk
minWidth
	"answer the receiver's minWidth"
	^ self
		valueOfProperty: #minWidth
		ifAbsent: [0]
```

then we get this result, which is the expected result. There is no extra space at the right side between the second list and the border of the window.

<img width="431" alt="Screenshot 2024-01-19 at 18 24 28" src="https://github.com/pharo-project/pharo/assets/753271/afd7fd99-2d35-45b1-b0c1-b93cef023d11">

### 4. Vertical case

Note that this also applies for vertical box layouts, as we have `Morph>>#minHeight`:

```smalltalk
minHeight
	"answer the receiver's minHeight"
	^ self
		valueOfProperty: #minHeight
		ifAbsent: [2]
```

### 5. Impact on existing applications

I cannot assess what the impact of the bug fix will be on existing applications. Maybe they rely on the 2 pixel extra space? They shouldn't, but you never know.

Maybe there was a good reason to have a `minWidth` and a `minHeight` of 2 pixels for all morphs? If that is the case, this issue should be fixed at the level of the Morphic box layout. That can be done by setting the `#minWidth` and the `#minHeight` properties to zero, so that `Morph>>#minWidth` and `Morph>>#minHeight` answer zero instead of 2 for `startPanel` and `endPanel`.

How do you think this bug has to be fixed? Based on your input, I will be happy to submit a PR.

**Comment by estebanlm** [comment]
nice catch :)

**Comment by Ducasse** [comment]
Hi Koen 

Morphic is too arcane for me. Now since minHeight is defined on Morph may be we could redefine it on the panel subclasses like that we can minimize the impact. 
Else we should try and see
S

**Comment by koendehondt** [comment]
Additional note: this issue is not present for an empty `startPanel`. For instance:

```smalltalk
| box |
box := SpBoxLayout newLeftToRight
	addLast: SpListPresenter new;
	yourself.
SpPresenter new layout: box; open
```

I gave the `startPanel` a red color in `SpMorphicBoxAdapter>>#newHorizontal` to see this:

<img width="438" alt="Screenshot 2024-01-21 at 11 50 38" src="https://github.com/pharo-project/pharo/assets/753271/93a3413f-7af5-4f52-9981-e219fcdf9fdf">

And for completeness, here is the result when the box layout is empty. I gave the `endPanel` a green color in `SpMorphicBoxAdapter>>#newHorizontal` . Then we see the issue: 2 green pixels on the right side.

<img width="431" alt="Screenshot 2024-01-21 at 12 05 10" src="https://github.com/pharo-project/pharo/assets/753271/acf30564-04d9-4ca0-a485-4a15a8753020">

**Comment by koendehondt** [comment]
When developing a fix, I noticed that the code belongs to https://github.com/pharo-spec/Spec. I created a PR there: https://github.com/pharo-spec/Spec/pull/1507.

<blockquote><img src="https://opengraph.githubassets.com/f4207d9b7a75f9eb5235e328ffeebb6bf9e36182b1ee520156322145f81df61f/pharo-spec/Spec" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-spec/Spec">GitHub - pharo-spec/Spec: Spec is a framework in Pharo for describing user interfaces.</a></strong></div><div>Spec is a framework in Pharo for describing user interfaces. - GitHub - pharo-spec/Spec: Spec is a framework in Pharo for describing user interfaces.</div></blockquote>

**Comment by koendehondt** [comment]
I checked in a recent Pharo 12 image. All good.
