### ISSUE TITLE
ZeroDivide when selecting idea11 icons

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#15841]
in Pharo 12 download and select idea11 icon set

![image](https://github.com/pharo-project/pharo/assets/5980033/1543f5fc-faa1-4564-8a92-03fb17e76ac8)

![image](https://github.com/pharo-project/pharo/assets/5980033/416edf68-1cec-4256-a1f1-11dc5b93bc44)

**Comment by hernanmd** [comment]
This is because the svgPack uses a directory structure different from the ones in other icon sets (eclipse, idea11, famfam) to match different icon scales.

If you know from where to obtain the SVG files from these sets I would be happy to fix this issue.

**Comment by hernanmd** [comment]
BTW Carolina told me that icons were generated by hand, so the best chance for the already present icons is to generate the SVGs from the PNGs using an existing tool. Feel free to suggest a FOSS one :)

**Comment by astares** [comment]
@hernanmd Inkscape (which is free and open source) can generate an SVG from PNG and is als able to vectorize. But depending on quality you get different results.

https://www.youtube.com/watch?v=4bZ-emmFb4E

<blockquote><img src="https://i.ytimg.com/vi/4bZ-emmFb4E/maxresdefault.jpg" width="48" align="right"><div><img src="https://www.youtube.com/s/desktop/691ad9c2/img/favicon_144x144.png" height="14"> YouTube</div><div><strong><a href="https://www.youtube.com/watch?v=4bZ-emmFb4E">Inkscape How To Convert PNG To SVG</a></strong></div><div>With Inkscape's user-friendly interface, converting PNG to SVG has never been easier. Simply import your PNG file into the software and let Inkscape work its...</div></blockquote>

**Comment by guillep** [comment]
Maybe the thing could be more robust when the Icons are "broken"? In this case probably we are trying to interpret an svg as a bitmap/png and boom! Now, this could also happen is there was a network error and the downloaded files are broken, or even if people make mistakes.

Maybe we need to show a "broken icon" icon? Like when the browser shows broken images.

![imagen](https://github.com/pharo-project/pharo/assets/708322/cd024254-0d4e-454c-b36d-f655b8c2548b)
