### ISSUE TITLE
Reduce references to Transcript

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15843]
We should avoid to make direct references to Transcript but use self traceCr or friends. 

Example

```
....
     Transcript show: 'ljklkjlkj' cr

```

into 

```
...
   'ljklkjlkj' traceCr
```

**Comment by MarcusDenker** [comment]
I am sure there is an issue already for this

**Comment by MarcusDenker** [comment]
Ah, this was  https://github.com/pharo-project/pharo/issues/4161, it was closed (having fresh issues is nice sometimes)

What we should do:

- make a list of the (not. many) cases left
- add a release test
