### ISSUE TITLE
Build may be broken

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15848]
I cannot find in the latest image the changes integrated one day ago. 
For example commit 4322b28 merging 15822 is not in the image 

Pharo 12.0.0
Build information: Pharo-12.0.0+build.1246.sha.d645f40b7eaae2f9d4e409a026241c8067d569c5 (64 Bit)

**Comment by guillep** [comment]
Hi Stef, the build broke but it seems it was just a network error 

```
IceGenericError: error reading from the zlib stream
IceLibgitErrorVisitor>>visitGenericError:
IceLibgitErrorVisitor>>visitERROR:
LGit_GIT_ERROR>>acceptError:
[ :error |
		location exists ifTrue: [ location ensureDeleteAll ].
		error acceptError: (IceLibgitErrorVisitor onContext: self) ] in IceGitClone>>execute in Block: [ :error |...
FullBlockClosure(BlockClosure)>>cull:
Context>>evaluateSignal:
Context>>handleSignal:
LGit_GIT_ERROR(Exception)>>signal
LGit_GIT_ERROR class(LGitCallReturnHandler class)>>signalWith:
LGitReturnCodeEnum>>handleLGitReturnCode
LGitRepository(LGitExternalObject)>>withReturnHandlerDo:
LGitRepository>>clone:options:to:
LGitRepository>>clone:options:
[location ensureCreateDirectory.
```

I don't think there is any action to take.
It it persists, let's deal with it :)

**Comment by jecisc** [comment]
This error happens from time to time. Around 1 build every 30 build I’d say? (Just my impression here).
Maybe an easy thing could be to add a retry. (Or look for the exact error but I’d not know where to start looking)

**Comment by Ducasse** [comment]
Thanks guys!
Merry christmas :)
