### ISSUE TITLE
Installing a breakpoint into an unsaved method hangs the image

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#15851]
**Bug description**
Installing a breakpoint into an unsaved method hangs the image without user interrupt working.

**To Reproduce**
1. Go to any method, modify it (e.g. by adding space)
2. Add a breakpoint on any place in the method (from context menu or by clicking on the left bar, makes no difference)
3. Image hangs

**Version information:**

Pharo 12.0.0
Build information: Pharo-12.0.0+build.1249.sha.1da0f13d6bce006cb0c38802b2e7092f3abf2e14 (64 Bit)

**Comment by hernanmd** [comment]
Problem seems to be in 

```smalltalk
affectsMethod: aMethod

	^ self link methods anySatisfy: [:each | each compiledMethod == aMethod compiledMethod ]
```

See the following screenshot:

<img width="991" alt="Screenshot 2023-12-29 at 15 51 18" src="https://github.com/pharo-project/pharo/assets/4825959/02bde22b-ad71-4137-908a-2f00f6f14af3">

`methods` is answering nil elements. While checking why this happen stepping into my image also hung:

<img width="978" alt="Screenshot 2023-12-29 at 15 41 42" src="https://github.com/pharo-project/pharo/assets/4825959/fa6e400e-85ea-4238-8ea6-f9659aa9d793">

Maybe @MarcusDenker has a suggestion here for a fix?

**Comment by MarcusDenker** [comment]
This problem (of a crash) does not happen anymore,

But we found another issue, we will open a new issue
