### ISSUE TITLE
String displayAt: aPoint is a bad idea.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15858]
why because it suppose that String (you know the class holding character) must know about the size of the display.

```
displayAt: aPoint
	"Display the receiver as a DisplayText at aPoint on the display screen."

	self displayOn: Display at: aPoint
```

And this is a bad design idea!

```
Object >> printDirectlyToDisplay
	"For debugging: write the receiver's printString directly to the display at (0, 100); senders of this are detected by the check-for-slips mechanism."

	self asString displayAt: 0@100

"StringMorph someInstance printDirectlyToDisplay"
```

**Comment by hernanmd** [comment]
I think this issue could be closed since `displayAt:` and `printDirectlyToDisplay` aren't present anymore in latest Pharo 12.

**Comment by Ducasse** [comment]
Good!

**Comment by guillep** [comment]
> I think this issue could be closed since `displayAt:` and `printDirectlyToDisplay` aren't present anymore in latest Pharo 12.

Mwahahaha

**Comment by Ducasse** [comment]
You really made me laugh. That was a good one.
