### ISSUE TITLE
In the message browser cmd B should open a class browser 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15860]
In the attached screenshot, 
when on the right and selecting displayInstance or any selector we should be able to press cmd+b and get to the class browser.
Right now we get a terrible UndefinedObject.
This is a hug break of flow. 
![Capture 2023-12-27 at 17 07 22](https://github.com/pharo-project/pharo/assets/432549/80481a95-3af8-4462-8205-a14d89a3e03b)

**Comment by hernanmd** [comment]
It seems focus is not set once the message browser is opened: 

https://github.com/pharo-project/pharo/assets/4825959/66266193-9ec6-40c9-8a20-3e9547f4e1bc

**Comment by hernanmd** [comment]
Took me a while to discover but problem here. If the selectedIndexes of a FTTableMorph matches with the requested ones, the ifTrue: exits the method and the selection is not refreshed/announced, and then focus is not set.

<img width="977" alt="Screenshot 2023-12-28 at 16 48 25" src="https://github.com/pharo-project/pharo/assets/4825959/33c9c0ab-67a3-4acb-87eb-1f05a962280f">

**Comment by Ducasse** [comment]
Thanks hernan!
