### ISSUE TITLE
Use MessageNotUnderstood in TechableTest

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#15891]
We should backport https://github.com/astares/Pharo-Teachable/commit/472cbd17dcac09cc09dccea36760298506d4245a to Pharo
following a discussion in https://github.com/pharo-project/pharo/pull/15873

**Comment by guillep** [comment]
Hi @astares I followed from far the discussion. I think it would be good if we integrate it as an external package as you say.
Do you mind giving it a try? In that case I think it's easy to revert the other PR at this stage (just pressing a button in gh :))
