### ISSUE TITLE
Iceberg cannot find the current image version commitish in pharo git repository

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#15893]
**Bug description**
Iceberg cannot locate the commit set in `SystemVersion commitHash`.
The commitHash is prefixed by a `g`character. It was introduced in https://github.com/pharo-project/pharo/commit/6b8b2ab3e7aab922d7537d160609fd9d281bd2d0 to support git-describe format but it looks like it does not work in our case.
Example:
```bash
% git show -s --format=%h
870aa6052a6
% git show --format=%H       
870aa6052a64408ea6c0230e188a9e52987f4a24
% git rev-parse --verify HEAD
870aa6052a64408ea6c0230e188a9e52987f4a24
% git describe
v8.0.0-dev-21699-g870aa6052a6
```
In the examplea above, sytem version commitish is set to `g870aa6052a64408ea6c0230e188a9e52987f4a24` that is not valid.

**To Reproduce**
Trying to update some Pharo code in latest P12,
then open iceberg, locate my up-to-date pharo git folder, Iceberg cannot locate the commitish
set in `SystemVersion`.

<img width="973" alt="Capture d’écran 2024-01-02 à 10 05 25" src="https://github.com/pharo-project/pharo/assets/2494203/98893fa1-d2b9-497e-bd74-831032903e08">

**Comment by guillep** [comment]
> The commitHash is prefixed by a `g`character. It was introduced in [6b8b2ab](https://github.com/pharo-project/pharo/commit/6b8b2ab3e7aab922d7537d160609fd9d281bd2d0) to support git-describe format but it looks like it does not work in our case.

I think the code evolved in a way that we do not need that anymore :)

**Comment by demarey** [comment]
PR: https://github.com/pharo-project/pharo/pull/15894
