### ISSUE TITLE
[RB] RBRenameClassChange is not executing the refactor correctly

### ISSUE THREAD

**Issue by estebanlm** [guillep/pharo-core#15903]
**Bug description**
The refactor class RBRenameClassChange is not executing the refactor correctly (or I am using it bad, or the API is misleading).
Class is renamed, but rename is not applied to references.

**To Reproduce**
Execute this: 

```smalltalk
(RBRenameClassChange rename: 'AIAstar' to: 'AiAstar') execute.
```

and verify AIStarTest>>setUp did not change.

**Expected behavior**
rename should be applied to references

**Comment by Ducasse** [comment]
You should not call the change directly.
Change are internal to the refactoring. You should call the refactoring (also and not the transformation).

**Comment by estebanlm** [comment]
oops. Ok :)
