### ISSUE TITLE
Instance of MetacelloVersionSpec did not understand #repositoryDescriptions

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15904]
Hi guille 

I see this problem in the PR https://github.com/pharo-project/pharo/pull/15901
```
MetacelloNotification: Loaded -> NewTools-WelcomeBrowser --- github://pharo-spec/NewTools-WelcomeBrowser:Pharo12/src
Instance of MetacelloVersionSpec did not understand #repositoryDescriptions
MetacelloVersionSpec(Object)>>doesNotUnderstand: #repositoryDescriptions
```

**Comment by Ducasse** [comment]
and I suspect that it is related to the metacello cleaning effort

**Comment by guillep** [comment]
As I said in another issue somewhere, this is actually caused by this PR https://github.com/pharo-spec/NewTools-WelcomeBrowser/pull/16

I'll see if I can fix it quickly or revert that PR otherwise

**Comment by Ducasse** [comment]
Oki :) Did not know.
