### ISSUE TITLE
Package does not understand buildMicroDownUsing: builder withComment: aString 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15916]
So we lost this method from P11.

**Comment by Ducasse** [comment]
I do not really get this 


```
ClyPackageRichTextCommentEditorToolMorph >> renderComment: aString of: aClassOrPackage 
	"The actual implementation is moved to BeautifulComments - basically to allow Testing"
	
	^ BeautifulComments renderComment: aString of: aClassOrPackage
```

**Comment by Ducasse** [comment]
![Capture 2024-01-04 at 20 11 08](https://github.com/pharo-project/pharo/assets/432549/6e1eae10-3e70-43f4-8504-75f00362ba44)

**Comment by hernanmd** [comment]
I fixed it here https://github.com/pillar-markup/Microdown/pull/675
But tests are failing and then 99.9% of changes are formatting.

Should I open another issue in Microdown to fix the failing tests?

**Comment by Ducasse** [comment]
Thanks hernan. I'm flooded by work. So I do not know. 
I will check for the tests before integrating this change.

**Comment by hernanmd** [comment]
No problem Stef. I just opened an issue here: https://github.com/pillar-markup/Microdown/issues/681
So it would be necessary to fix Microdown issues.

**Comment by Ducasse** [comment]
Ok I released a version of microdown for P12 and it should fix this problem. It is V2.5.0. Now we should merge it into pharo12. 
But I want to do it with people around and not when many are on vacation.

**Comment by Ducasse** [comment]
I merge V2.5.0 of microdown in the microdown branch Pharo12 so this bug should be fixed.

**Comment by estebanlm** [comment]
I confirm this is done

**Comment by Ducasse** [comment]
nice to know.
