### ISSUE TITLE
new class template (in dialog) is wrong

### ISSUE THREAD

**Issue by estebanlm** [guillep/pharo-core#15914]
**Bug description**
The class template that appears in the class creation dialog is wrong, it shows package+tag in the package section and hence it produces a new package when executing (instead a class in a package and a tag).

**To Reproduce**
- open browser in AST-Core, tag Exception
- select CodeError and with right click select "new class"
- add a name (e.g. MyWrongClass)
- see how a new package "AST-Core-Exception" is created, with the new class inside.

this is because the template is presented like this: 

```smalltalk
Object << #MyClass
	layout: FixedLayout;
	traits: {};
	slots: {};
	sharedVariables: {};
	sharedPools: {};
	tag: '' ;
	package: 'AST-Core-Exception'
```
and now there is no ambiguity between packages and categories... which means a package is a package always. But then... **is the template** the one that's wrong. It should be presented as this: 

```smalltalk
Object << #MyClass
	layout: FixedLayout;
	traits: {};
	slots: {};
	sharedVariables: {};
	sharedPools: {};
	tag: 'Exception' ;
	package: 'AST-Core'
```
("Exception" being a tag).

**Expected behavior**
new class should be created in the same package+tag than the selected place.

ADDITIONALLY: I would consider the whole template... is too complex and probably misleading. I would at least eliminate the layout section to make things easy (changing the layout of a class requires an extensive knowledge of the system and it has a very limited quantity of use cases).

**Comment by estebanlm** [comment]
@jecisc I assigned you because you worked on the system categories removal and this is clearly a side effect of that (and the changes in Package)

**Comment by Ducasse** [comment]
This bug was already reported. Now I cannot find the issue number.

**Comment by jecisc** [comment]
Working on it

**Comment by jecisc** [comment]
I fixed it and I think it got integrated
