### ISSUE TITLE
Integrate Teachable into "SUnit-Mock" via LOADING

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#15912]
Try to integrate Teachable by LOADING not COPYING to satisfy the requirements of
all participants, still allow Teachable to be used independent from SUnit-Mock, not having
any dirty packages when loading a new (external) new versions but also allow to 
properly compose the image by loading (instead of copying code around)

For details see discussion in
- https://github.com/pharo-project/pharo/pull/15873
- https://github.com/pharo-project/pharo/issues/15907

**Comment by jordanmontt** [comment]
I suggest closing this as the related PR was closed too
