### ISSUE TITLE
Instance of MetacelloProjectReferenceSpec did not understand #projectPackage

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15929]
in https://github.com/pharo-spec/NewTools/pull/652
the build is showing this `MetacelloProjectReferenceSpec did not understand #projectPackage`
This is probably related to the Metacello cleaning pass. 

I do not know if this is something special of newtools configuration

**Comment by theseion** [comment]
A change in `ad8fb7c98e0b1879771627446c5c1c5b8c9f22f9` (probably, @guillep) broke Metacello. SmalltalkCI is affected as well. Can be debugged easily by cloning https://github.com/hpi-swa/smalltalkCI and running (make sure that the current image is downloaded, there's currently a bug that will use the cached image for alpha):

```bash
./run.sh -s Pharo64-alpha --headful .smalltalk.ston
```

<blockquote><img src="https://opengraph.githubassets.com/6929f554bac374b7fe63fe06d1981aff47e59f890a04ef188bd1a332b4781521/hpi-swa/smalltalkCI" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/hpi-swa/smalltalkCI">GitHub - hpi-swa/smalltalkCI: Framework for testing Smalltalk projects with GitHub Actions, GitLab CI, Travis CI, AppVeyor, and others.</a></strong></div><div>Framework for testing Smalltalk projects with GitHub Actions, GitLab CI, Travis CI, AppVeyor, and others. - GitHub - hpi-swa/smalltalkCI: Framework for testing Smalltalk projects with GitHub Action...</div></blockquote>

**Comment by Ducasse** [comment]
Thanks. I think that we will another pass. It would have been so nice to have more tests. But we will get there.

**Comment by Ducasse** [comment]
I'm rechecking because in P11 I'm still sharing my repo so the latest changes were not loaded

**Comment by Ducasse** [comment]
So I got the same- P11 with a green bar.

**Comment by guillep** [comment]
Not quite yet, Smalltalk CI depends on `MetacelloIgnorePackageLoaded` that looked like an internal-use only class.
I'll add it back deprecated for now

**Comment by guillep** [comment]
The newtools build works now ^^ https://github.com/pharo-spec/NewTools/pull/652
