### ISSUE TITLE
Loading project... Instance of MetacelloProjectReferenceSpec did not understand #projectPackage

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15928]
**Bug description**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version information:**
 - Version: [e.g. 1.6.1]
 - Pharo Version [e.g 9]

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 
In addition, are you willing to help because after all Pharo is yours too?

**Additional context**

**Comment by tinchodias** [comment]
I have several github actions suffer this issue. Example: https://github.com/pharo-graphics/Alexandrie/actions/runs/7444753585/job/20251736826

<blockquote><img src="https://opengraph.githubassets.com/831a5dd63689eb1bb96ed015409bb5d0df79beb6ffdc5d690ea94f2661016cdb/pharo-graphics/Alexandrie" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-graphics/Alexandrie">Tests · pharo-graphics/Alexandrie@e6f1b1b</a></strong></div><div>FFI bindings and a 2D canvas for Pharo based on Cairo, Freetype and Harfbuzz - Tests · pharo-graphics/Alexandrie@e6f1b1b</div></blockquote>

**Comment by MarcusDenker** [comment]
This is fixed, see https://github.com/pharo-project/pharo/issues/15929
