### ISSUE TITLE
Spurious copy

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15926]
I may be wrong but asOrderedCollection should return a new collection (except if it is already an orderedCollection). 
But either there is something smelly. 
Either we do not need to copy or we do not need the conversion, isn't?

```
RBMethodNode >> allStatements
	^ statements asOrderedCollection copy
			addAll: super allStatements;
			yourself
```

```
RBArrayNode >> allStatements
	^ statements asOrderedCollection copy
			addAll: super allStatements;
			yourself
```

```
RBBlockNode >> allStatements
	"including temp variable definition."
	^ self temporaries asOrderedCollection copy
			addAll: super allStatements;
			yourself
```

```
RBSequenceNode >> allStatements
	"including temp variable definition."
	^ self temporaries asOrderedCollection copy
			addAll: super allStatements;
			yourself
```

So since most of the classes are delegating to RBSequenceNode and the initialize of SequenceNode indicates an orderedcollection, it looks like we are just generating extra collection for nothing.

**Comment by Ducasse** [comment]
This piece of code has been duplicated. We can find it in at least 3 classes.

**Comment by Ducasse** [comment]
So my analysis is that there asOrderedCollection have been blinded added may be in the past for one case and they propagated. 

```
RBSequence >> initialize

	super initialize.
	periods := OrderedCollection new.
	statements := OrderedCollection new.
	temporaries := OrderedCollection new
```


It would be interesting to know the number of time asOrderedCollection is sent to an OrderedCollection!

**Comment by Ducasse** [comment]
I would like to put a methodProxy on OrderedCollection >> asOrderedCollection and see.

**Comment by Ducasse** [comment]
@jordanmontt seb this is fun. It looks like another forms of spurious objects

**Comment by Ducasse** [comment]
I would like to have an analysis of 
- How many times do we send asOrderedCollection to an orderedCollection
- How many times an instance variable is changing types it in life time.
- Is an expression doing yoyo with types: e.g. self temporaries asOrderedCollection
may be it was an array converted to anOrderedCollection
may be it was already an orderedCollection

**Comment by jordanmontt** [comment]
I run the tests of the AST and the receiver of `asOrderedCollection copy` in those 4 methods is *always* an OrderedCollection. I don't know if the tests represent all the possibilities. If that is the case, we could safetely remove `asOrderedCollection`...

**Comment by jordanmontt** [comment]
Actually, running the kernel tests, refactoring, collection, the receiver is always an `OrderedCollection`
