### ISSUE TITLE
gtAllKeyCategoryPairs does not exist but it still called

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15925]
```
spotterForKeysFor: aStep
	<stSpotterOrder: 15>
		
	aStep listProcessor
			title: 'Keys';
			allCandidates: [ (self gtAllKeyCategoryPairs collect: [:each | each key]) asOrderedCollection ];
			itemName: [ :aKeymap | 
				aKeymap shortcut displayString, 
				(aKeymap name ifNil: [ '' ] ifNotNil: [ ' [', aKeymap name,']' ]) ];
			candidatesLimit: 5;
			filter: StFilterSubstring
````

**Comment by jecisc** [comment]
I have the impression that a lot of extensions of the Spotter are never called. I removed multiple things related to Packages and Monticello calling code that just could not work a few weeks ago and if we never had a DNU this means that either we have a #on:do: or that the code is dead code.

**Comment by MarcusDenker** [comment]
I think they are part of feature of spotter that we never use: if you inspect an object, you can use spotter on that *object* and the subgraph of it (depending of these implemented exptensions).

**Comment by Ducasse** [comment]
let us remove it.

**Comment by hernanmd** [comment]
I found a way to reproduce this:

```smalltalk
StSpotter openOnOrigin: KMDispatcher allInstances anyOne.
```

However as I don't use Spotter, I don't know if this is a valid use case.
Do you want me to reinstate the missing method or just kill it?

<img width="845" alt="Screenshot 2024-01-29 at 15 53 28" src="https://github.com/pharo-project/pharo/assets/4825959/b1b96186-96e3-4c77-b04e-99a41ba0c96a">

**Comment by Ducasse** [comment]
Let us remove the methods.

**Comment by Ducasse** [comment]
When we do not use something for more than 4 years then it does exist and the rest is dead code.

**Comment by hernanmd** [comment]
> When we do not use something for more than 4 years then it does exist and the rest is dead code.

Rog that. In https://github.com/pharo-spec/NewTools/pull/676

**Comment by hernanmd** [comment]
Merged in NewTools
