### ISSUE TITLE
MetacelloMCBaselineOfProjectSpect did not understand #loadVersion:

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#15936]
**Bug description**
Loading previously working Metacello baselines now fail in Pharo 12. This does not happen always, so it is not clear to me yet if it's related with loading Bloc in a specific way. (Loading [Bloc](https://github.com/pharo-graphics/Bloc) as documented in the [Installation](https://github.com/pharo-graphics/Bloc#installation) section loads without problems).

**To Reproduce**
```smalltalk
Metacello new
	repository: 'github://Ducasse/Myg';
	baseline: 'Myg';
	onConflictUseLoaded;
	load.
```

**Screenshots**
<img width="1434" alt="Screenshot 2024-01-08 at 12 37 56" src="https://github.com/pharo-project/pharo/assets/4825959/59d3325d-568d-4f2c-9dbb-ae3b7a92d084">

**Comment by guillep** [comment]
Thanks, @estebanlm was tellingme about an issue like this, I was looking for a reproducible case :)

I'll check on it quickly.

**Comment by guillep** [comment]
Reproduced!
