### ISSUE TITLE
Problem Ci: Instance of MetacelloProjectRegistration did not understand #currentlyLoadedClassesInProject

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#15939]
**Bug description**
I can not run the CI on git for Soil on Pharo12:

```
Testing project...
Instance of MetacelloProjectRegistration did not understand #currentlyLoadedClassesInProject
MetacelloProjectRegistration(Object)>>doesNotUnderstand: #currentlyLoadedClassesInProject
```

see https://github.com/ApptiveGrid/Soil/actions/runs/7421847544/job/20278279808?pr=559

**Comment by guillep** [comment]
We should discuss if that is a good API.

Nevertheless, I'll add it back and deprecate it probably.

**Comment by MarcusDenker** [comment]
The problem is that I can not fix is as this is not Soil that uses it...

**Comment by labordep** [comment]
Hi, I have the same problem in my GitLab server.
On Pharo 12 only:

![image](https://github.com/pharo-project/pharo/assets/49183340/907718d5-e8e8-43d1-8a45-9c484fd544bb)

**Comment by guillep** [comment]
I'm working on it, a fix will arrive during the morning
