### ISSUE TITLE
Need to clean the Gofer deprecated dependency

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15940]
We have many tests failing due to the Gofer deprecation. 
I would simply remove Gofer BTW :)

**Comment by jecisc** [comment]
@guillep What's your opinion on deprecating vs removing gofer?

**Comment by guillep** [comment]
> @guillep What's your opinion on deprecating vs removing gofer?

No strong opinion.
We should just give people a migration path.

**Comment by Ducasse** [comment]
Oh the migration path is simple. Save the package in P11 and load it in P12.
For me Gofer is not a public API.

**Comment by jecisc** [comment]
Done
