### ISSUE TITLE
Report class definitions errors when loading code

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#15958]
When loading class definitions that contain errors, the `loadClassDefinitions` method currently saves the erroneous definitions, but omits any logging of the errors. 

**Expected behavior**
This enhancement proposes that at least the errors can be sent to the Transcript, so that the user can quickly see what loading errors existed and take action.

**Screenshots**
<img width="1237" alt="Screenshot 2024-01-16 at 13 56 53" src="https://github.com/pharo-project/pharo/assets/4825959/6faeecaa-e3be-4dc0-8d54-9d21812be226">

**Comment by jecisc** [comment]
The goal of this variable is to do a retry of those definition because it might be a class using a trait from the same package that gets loaded before the trait. So we retry once the trait is loaded. 

But it's true that if in the end we still have errors they should be reported.

**Comment by jordanmontt** [comment]
Can we close this @hernanmd ? as there is a related PR that has been merged
