### ISSUE TITLE
Code critique improvement: ReMultiplePeriodsTerminatingStatementRule does not detect multiple periods with source code comments in between

### ISSUE THREAD

**Issue by jbrichau** [guillep/pharo-core#15955]
**Bug description**
The code critique rule` ReMultiplePeriodsTerminatingStatementRule` does not detect multiple periods when a source code comment is put in between the dots. Such a case is still considered an empty statement and was detected using the Grease Slime rule `GREmptyStatementsRule`. This rule is important for portable code to dialects where the compiler does not accept empty statements.

I am moving out all duplicate rules from Grease Slime in Pharo in an improvement effort (see https://github.com/SeasideSt/Grease/pull/167). To remove the `GREmptyStatementsRule`, it is important that this case is detected by `ReMultiplePeriodsTerminatingStatementRule`

**To Reproduce**
Enter the following code in an editor:
```Smalltalk
emptyStatement
  self and."foo".self and
```

**Expected behavior**
The code critique for multiple periods should be shown.

**Version information:**
 - Pharo Version 11+

**Comment by Ducasse** [comment]
Nice catch. 
BTW we should push the Slime rules that make sense in Pharo.

**Comment by jbrichau** [comment]
I made a PR to fix this issue: #15956.

@Ducasse Indeed. This is part of that effort ;-). I am moving all general rules to https://github.com/SeasideSt/PharoWithStyle/ and trying to add more.
But for that, I needed to move current Slime implementation to the Renraku critiques otherwise it became a mess.
Now I can finally move forward there


<blockquote><img src="https://opengraph.githubassets.com/9c57bcb34c54a36448ce98efddd294e4e660249b7f4058de157a91160a1b3f44/SeasideSt/PharoWithStyle" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/SeasideSt/PharoWithStyle">GitHub - SeasideSt/PharoWithStyle: Code style rules from the Pharo With Style book</a></strong></div><div>Code style rules from the Pharo With Style book. Contribute to SeasideSt/PharoWithStyle development by creating an account on GitHub.</div></blockquote>

**Comment by Ducasse** [comment]
Excellent!!!!!

**Comment by Ducasse** [comment]
I will use the Pharo With Style for all the students :)
