### ISSUE TITLE
[CI] Failing tests on the CI: Sindarin

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#15964]
**Bug description**
These tests are failing: 

```
osx-64 / Tests-osx-64 / testIsExecutionFinished – MacOSX64.Sindarin.Tests.SindarinDebuggerTest
osx-64 / Tests-osx-64 / testStepOverFinishedExecution – MacOSX64.Sindarin.Tests.SindarinDebuggerTest
```

**Comment by hernanmd** [comment]
A PR in https://github.com/pharo-spec/ScriptableDebugger/pull/89

**Comment by MarcusDenker** [comment]
The PR was merged, but sindarin tests are still failing on the CI:

- testIsExecutionFinished – MacOSX64.Sindarin.Tests.SindarinDebuggerTest
-  testStepOverFinishedExecution – MacOSX64.Sindarin.Tests.SindarinDebuggerTest

The PR was merged in master, maybe we load another branch in Pharo12?

**Comment by guillep** [comment]
Yes, we load Pharo12 branch.
No merges should be done in master.

**Comment by hernanmd** [comment]
I've seen https://github.com/pharo-spec/ScriptableDebugger/tree/Pharo12 is 3 commits behind master.
Do you want me to re-send the PR to Pharo12 branch in ScriptableDebugger?


<blockquote><img src="https://opengraph.githubassets.com/a80bce2bfa44306f87660de29da375426afd2f5a97569316e965c25aa3cd6ce3/pharo-spec/ScriptableDebugger" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-spec/ScriptableDebugger">GitHub - pharo-spec/ScriptableDebugger at Pharo12</a></strong></div><div>Contribute to pharo-spec/ScriptableDebugger development by creating an account on GitHub.</div></blockquote>

**Comment by jecisc** [comment]
I fast forwarded P12 to master.

I don't know if the change to master should be reverted or not tho

**Comment by MarcusDenker** [comment]
Fixed!
