### ISSUE TITLE
Opening "Rewrite Rule Editor" hangs the image

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#15961]
**Bug description**

In latest Pharo 12 go to Library - Rewrite Rule Editor, and then if you don't CMD+. quickly, image hangs.

**Expected development cost**
This could be an error related with opening the Debugger, or related with something aside from the Rewrite Rule Editor.
Under investigation,

**Comment by Ducasse** [comment]
Oops may be I introduce a regression because I used it recently and fixed some deprecations.

**Comment by hernanmd** [comment]
Ok, I checked all menu accessible tools and it also happens with:

- About window
- Expression Finder

**Comment by jordanmontt** [comment]
I cannot reproduce this issue (latest Pharo 12). I tried opening the described tools and they open normally. Maybe it was already fixed?

![Capture d’écran 2024-01-19 à 15 06 01](https://github.com/pharo-project/pharo/assets/33934979/2483f0f7-35fc-4a8e-8423-bba0e9f02e33)

**Comment by hernanmd** [comment]
Same here, cannot reproduce it anymore. Must have been corrected in the last PRs.
I will close the issue.
