### ISSUE TITLE
UFFI/TFFI call for WebBrowser with specific URL length adds strange characters to the URL

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#15980]
**Bug description**
Given a URL with a specific length to open in WebBrowser on Windows adds strange characters to the URL

**To Reproduce**
- use Pharo 11 or 12 on Windows
- Open Playground and run

```Smalltalk
WebBrowser openOn: 'https://pharo.org?abcdefghijklmnopqrstuvwxyz1234567890ok'.
```
you will see that strange characters added to the URL location in the webbrowser like

```
[https://pharo.org?abcdefghijklmnopqrstuvwxyz1234567890ok](https://pharo.org/?aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa%C5%92()
```

**Expected behavior**
Expect the URL to stay the same as given and to correctly open on the web browser

**Screenshots**
<img width="366" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/e164799b-5b86-48bd-af11-7f5749107749">

**Version information:**
 - OS: Windows 10
 - Pharo Version 11 and 12, probably others too

**Additional context**
- seems to be less a problem of URL content but more a problem of  **specific URL length**. if you use other lenth it works

<img width="446" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/cf425c2c-fd2f-4d3c-af1c-78cb892d5917">

Using that URL in DOS just opens the correct location

<img width="636" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/086d15b9-56c8-4cc5-aec5-c0ab0f857a79">

Might possibly be an issue of UFFI/TFFI

**Comment by VincentBlondeau** [comment]
The issue is in the FFI call. The WBWindowsWebBrowser is doing a call with String* which doesn't make sense in this context since it is not made to be written on.
A simple fix would be:
![image](https://github.com/pharo-project/pharo/assets/4706329/7b2cb75d-6b34-499b-a653-e59cbd6e2f20)
PR incoming.

See doc on FFI for reference:
https://files.pharo.org/books-pdfs/booklet-uFFI/UFFIDRAFT.pdf
![image](https://github.com/pharo-project/pharo/assets/4706329/ebae69bb-3c1b-4134-b46a-01e53bbb3629)

**Comment by astares** [comment]
But in Pharo 8 this was working using the String* definition. 

<img width="663" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/b898d306-17d3-4c77-aab8-0ab664cf91c2">

Maybe there was a change between the newer TFFI in P12 and (back then) the UFFI in P8.

**Comment by astares** [comment]
@demarey 
A full fix is provided as a PR in https://github.com/pharo-project/pharo/pull/16262

Because as now UFFI seems to be more strict it is required to also have a type definiton for the first parameter (constant 0)

```Smalltalk
shellExecute: lpOperation file: lpFile parameters: lpParameters directory: lpDirectory show: nShowCmd

	^ self ffiCall: #(
			FFIConstantHandle ShellExecuteA(
     				int 0, "Operation is not associated with a window"
     				String lpOperation,
         			String lpFile,
     				String lpParameters,
     				String lpDirectory,
        			int nShowCmd)) module: #shell32
```
