### ISSUE TITLE
Rename instance variable and shared variable drivers are broken .

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15982]
Hi balsa

if you have a couple of minutes could you check the removeInstance/SharedVariable driver?

S

**Comment by balsa-sarenac** [comment]
Hey, I just tried them both on latest Pharo, and they work for simple path. Did you have issues with some specific use-case?

**Comment by Ducasse** [comment]
Ah good I thought that they break when we select multiple items.

**Comment by balsa-sarenac** [comment]
I found some bugs with showing violators and removing SharedVars with references, I'm preparing a PR with it.
I haven't tested removing multiple items, it's possible that it breaks. Will check that tomorrow.

**Comment by Ducasse** [comment]
Tx (correcting exams and getting depressed by my lack of vigilance).

**Comment by balsa-sarenac** [comment]
Hang in there! Hope it'll be over soon :)

I've quickly tested removing multiple vars and it works, I think the fixes are in the PR, I'll update it to close this issue when merged.
