### ISSUE TITLE
Instance-side initialize is criticized as if it's a class-side initialize

### ISSUE THREAD

**Issue by tinchodias** [guillep/pharo-core#15989]
**Bug description**
Instance-side initialize is criticized as if it's a class-side initialize, as shown in Calypso:
<img width="649" alt="Screenshot 2024-01-19 at 17 37 58" src="https://github.com/pharo-project/pharo/assets/3044265/ab42aa4a-091a-487c-955b-6518426524aa">

**To Reproduce**
1. Open Calypso
2. Create a class
3. Compile a initialize that sends "super initialize" in instance-side
4. See the warning at bottom, which is incorrect because we are at instance-side.

**Version information:**
Pharo 12.0.0
Build information: Pharo-12.0.0+SNAPSHOT.build.1301.sha.4c28e69a56c2be348a87daf4b67a220dd60b4ec0 (64 Bit)
BUT: I pulled changes from Pharo12 branch

**Comment by tinchodias** [comment]
Additionally, I wonder what is the "Rewrite super messages to self messages"... it creates a loop:
  
<img width="484" alt="Screenshot 2024-01-19 at 17 41 15" src="https://github.com/pharo-project/pharo/assets/3044265/7b5a097a-398b-45f7-98fe-a155367edf8c">

**Comment by jecisc** [comment]
Hi,

I'll close because Steph reported it also and I proposed a fix in https://github.com/pharo-project/pharo/pull/16007
