### ISSUE TITLE
Super initialize rule is now checking instance side and this is wrong

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16002]
Hi cyril

I have the impression that we got a regression with the rule.
I see the following in latest pharo12.

![Capture 2024-01-21 at 18 45 33](https://github.com/pharo-project/pharo/assets/432549/47b42cd4-1122-42c2-b235-93b9dc0ff299)

**Comment by jecisc** [comment]
The issue is that Calypso implements its own way of iterating over the AST nodes and does not use the way of Renraku.

Maybe in a future iteration we could have only one entry point for this instead of duplicating
