### ISSUE TITLE
Bytes panel is broken on CompiledMethods

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16018]
![Capture 2024-01-25 at 09 33 56](https://github.com/pharo-project/pharo/assets/432549/910b31ea-0348-45d5-b8ff-a20f0065a746)

**Comment by MarcusDenker** [comment]
The reason is that CompiledMethod inherits ByteArray>>#inspectBytes:, but that makes no sense for any of the CompiledCode subclasses.

**Comment by Ducasse** [comment]
I do not really understand but we should fix it or remove it.

**Comment by MarcusDenker** [comment]
We could override it. I have not found a way to do nothing, so mayeb we could show the bytes of the Bytecode:

```
inspectBytes: specBuilder
	<inspectorPresentationOrder: 30 title: 'Bytes'>

	^ self size > 1000 
		ifTrue: [
			(StSimpleInspectorBuilder on: specBuilder)
				key: 'error' value: 'too many bytes, size is ' , self size asString;
				table ]
		ifFalse: [
			(StSimpleInspectorBuilder on: specBuilder)
				key: 'hex string bytecode' value: (String streamContents: [ :out | 
					self bytecodes do: [ :each | each printOn: out base: 16 nDigits: 2 ] ]);
				key: 'hex lines bytecode' value: (String streamContents: [ :out |
					self bytecodes withIndexDo: [ :each :index |
						index = 1 ifFalse: [ 
							index - 1 \\ 8 = 0 ifTrue: [ out cr ] ifFalse: [ out space ] ].
						each printOn: out base: 16 nDigits: 2 ] ]);
				table]
```

Code here instead of PR as I can not commit, I added another issue for that: #16019

**Comment by hernanmd** [comment]
Merged in https://github.com/pharo-spec/NewTools/pull/670
