### ISSUE TITLE
BlockClosure>>#valueWithin:onTimeout: lost return

### ISSUE THREAD

**Issue by theseion** [guillep/pharo-core#16011]
**Bug description**
The method `BlockClosure>>#valueWithin:onTimeout:` was refactored and now no longer returns the value of the evaluated block.

**To Reproduce**
```smalltalk
([ 2 ] valueWithin: 1 second onTimeout: [ self error ]) = 2.
```

**Expected behavior**
The method must return the value of the evaluated block.

**Version information:**
 - Pharo-12.0.0+SNAPSHOT.build.1311.sha.179be510706e561f0f195fe34f76f5f1aedcdf4c (64 Bit)

**Expected development cost**
Trivial

**Comment by Ducasse** [comment]
Thanks. We will fix it. It deserves also a test in that case.
