### ISSUE TITLE
Context menu item ‘Revert to selected version’ in recent versions of a method does not revert

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#16045]
In Pharo 12 build 1323, the context menu item ‘Revert to selected version’ in the recent versions of a method does not seem to work. The balloon text also seems wrong:

<img width="707" src="https://github.com/pharo-project/pharo/assets/1611248/1828537d-b324-4540-b8e4-2e99f18390eb">

The ‘Revert’ toolbar button does work.

**Comment by Rinzwind** [comment]
Also: all of the other toolbar buttons (‘Browse’, ‘References’, ‘Senders’ and ‘Implementors’) cause a MessageNotUnderstood to be signaled.

**Comment by Ducasse** [comment]
This is the price to pay when we do not write tests. :(

**Comment by bouraqadi** [comment]
Experienced the same bug here. I think this should be fixed before releasing P12.

**Comment by bouraqadi** [comment]
No suprize revert does not work. Method `StVersionBrowserPresenter >> #doRevert` is empty!

**Comment by bouraqadi** [comment]
This issue actually belongs to [NewTools](https://github.com/pharo-spec/NewTools).  
[Bug fixed + PR opened](https://github.com/pharo-spec/NewTools/pull/710).

**Comment by MarcusDenker** [comment]
fix merged

**Comment by Rinzwind** [comment]
Thanks! I quickly tried it out using Pharo 12 build 1402. The menu item ‘Revert to selected version’ works again. But the balloon text still seems wrong. The toolbar buttons ‘Browse’, ‘References’, ‘Senders’ and ‘Implementors’ also still cause a MessageNotUnderstood to be signaled.

Perhaps this should be reopened, or should a new issue be opened?
