### ISSUE TITLE
Display methods should be in "displaying" protocol

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16049]
For an object traditionally in Smalltalk there is a clear distinction between 

1. "printing" (like #printString, #printOn:, #fullPrintString, ....) methods 
     printing the object in the debugger or playground 

2. "displaying" methods (like #displayString, #displayStringLimitedTo:, printStringLimitedTo:, ...)
    displaying the object on a user interface

3. "storing" methods (like #storeString, ...)
    To give a representation of the object that is stored on a stream but can be used to recreate the 
    object

which you can find in any decent Smalltalk implementation.
    
Pharo ignores these protocols at the moment and the way we categorize them in the standard image (ist often wrong and) is not consistent.

We should improve on that level.

**Comment by astares** [comment]
Especially as we have all the tools (like automatic lint fixing) to fix such parts. We just need to be more disciplined.

![image](https://github.com/pharo-project/pharo/assets/5980033/b6a2c267-204c-45af-8778-a081cebe2708)

**Comment by jecisc** [comment]
Personally I find that printing and displaying are kind of the same. I'm not sure I'd like two protocols for a usage that is so close. When browsing code I'd prefer to have both grouped and not have a thousand protocols with really few methods in each.

Printing is for UI as much as displaying.
