### ISSUE TITLE
#displayStringOn: of three spotter classes should be in category "displaying"

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16054]
- StSpotterCandidateLink>>#displayStringOn:
- StSpotterProcessorLink>>#displayStringOn:
- StSpotterPragmaBasedProcessor>>#displayStringOn:

should also be in "displaying" category instead of "printing". See #16049 for more details.

This needs to be done in NewTools project:

![image](https://github.com/pharo-project/pharo/assets/5980033/9300ac9e-ecda-4e17-aef1-6da11d22e733)

**Comment by PosledniAmir** [comment]
Hello, isn't this issue for another repository; [NewTools](https://github.com/pharo-spec/NewTools)?

Nevertheless, I have created a pull request [there](https://github.com/pharo-spec/NewTools/pull/737).
