### ISSUE TITLE
Array>>#displayString should be part of Kernel and not an override from NewTools

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16050]
We should put that directly into the kernel as Array is a Kernel class and therefore should have its #displayString method there:

![image](https://github.com/pharo-project/pharo/assets/5980033/80b734be-3490-4131-bc22-2d2ffd635914)

**Comment by Ducasse** [comment]
Agreed

**Comment by astares** [comment]
both PRs need to be merged in one pass as NewTools is in another repo
