### ISSUE TITLE
Job related bugs prevent commit or push anymore 

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#16077]
**Bug description**
Using a clean Pharo 12 image there are multiple issues related with changes in Job (for instance `SpJobListPresenter`).
The error message is "Instance of Job did not understand `installOn:`"

**To Reproduce**

1. Open Iceberg -> System -> pharo -> Select a local repository -> Ok
2. Make some changes
3. Commit [1] or Push [2]
4. See errors below

**Screenshots for Commit errors**

<img width="1310" alt="Screenshot 2024-01-29 at 17 56 07" src="https://github.com/pharo-project/pharo/assets/4825959/a727c78e-7454-474b-8d82-00140647ceb2">

<img width="917" alt="Screenshot 2024-01-30 at 21 40 12" src="https://github.com/pharo-project/pharo/assets/4825959/5afa02c4-d359-4528-b751-e5e54c98844a">

**Screenshots for Push errors**

<img width="993" alt="Screenshot 2024-01-30 at 21 40 43" src="https://github.com/pharo-project/pharo/assets/4825959/3eb9a756-2ed2-4d15-90f4-6692996201df">

<img width="994" alt="Screenshot 2024-01-30 at 21 41 17" src="https://github.com/pharo-project/pharo/assets/4825959/7826c92e-730d-4b86-9ac4-0198a5ce9007">

**Comment by MarcusDenker** [comment]
This is fixed, I could push
