### ISSUE TITLE
StInspectorCommand is calling a method that does not exist

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16091]
There is no super buildMicroDownUsing: aBuilder withComment: aString in the hierarchy of StInspectorCommand
```
StInspectorCommand >> buildMicroDownUsing: aBuilder withComment: aString
	
	super buildMicroDownUsing: aBuilder withComment: aString.
	self addDocumentContextRequiredSelectors: aBuilder
```

**Comment by jordanmontt** [comment]
In Pharo 12 there is a super `Class>>#buildMicroDownUsing:withComment:`
Maybe it was added after you created this issue?
