### ISSUE TITLE
Build Broken: Error: Package Monticello-Tests depends on the following classes:   StPharoApplication

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#16099]
**Bug description**
The CI can not build (not the image for download, not any PR check):

```
NewUndeclaredWarning: StMethodNameEditorPresenter>>renameArgument: (CmdCommandAborted is Undeclared)
MetacelloNotification: Loaded -> Refactoring-UI --- tonel:///builds/workspace/est_and_branch_Pipeline_PR-16097/64/src
MetacelloNotification: Loaded -> Spec2-Transformations --- github://pharo-spec/Spec:Pharo12/src
Error: Package Monticello-Tests depends on the following classes:
  StPharoApplication
You must resolve these dependencies before you will be able to load these definitions: 
  StPharoApplication>>#openDirectoryDialog
```

**Comment by MarcusDenker** [comment]
Build 1342 is the first failing one:

https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo12/1342/


The changes there seem to be not related:

- Release all waiting processes when destroying a socket (details / githubweb)
- Cleanly report attempts to retrieve the last socket error code when the socket is already destroyed (details / githubweb)

But then, for all the external packages we just load the latest. 

But I can not find a PR for NewTools or Spec that could cause this.

**Comment by MarcusDenker** [comment]
Ah, so there where more problems that made the build fail. So it has to be a later build.

**Comment by hernanmd** [comment]
Marcus there should be in a new package I introduced named "System-Spec", which is WiP.
I wasn't aware that Monticello-Tests used the directory dialog (seems strange too). But I'll have a look.

**Comment by MarcusDenker** [comment]
Changes that break the build have to be reverted if they can not be fixed fast.

Until this problem is fixed, *everything* is blocked.

**Comment by Ducasse** [comment]
@hernanmd in which PR did you introduce System-Spec because we should revert it. 
All the other changes are blocked. I could not find it in Spec and Newtools.

**Comment by Ducasse** [comment]
Do you think that this is this one? https://github.com/pharo-project/pharo/pull/16068/
Should I revert it?

**Comment by hernanmd** [comment]
> Do you think that this is this one? #16068 Should I revert it?

I added the required dependency,

However I don't get why most of the baselines in BaselineOfBasicTools does not define "required" and they don't raise any error?

**Comment by MarcusDenker** [comment]
this is now fixed
