### ISSUE TITLE
Hierarchical implementors look to have a bug

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16117]
I tried to look for hierarchical implementors of printOn: and I do not het the Object one.

**Comment by Ducasse** [comment]
I retried today and I got the same with displayString

**Comment by hernanmd** [comment]
I think what is wrong is the usability. In the sense you have to click the arrow to open the hierarchical implementors.
Is this what you mean?

<img width="868" alt="Screenshot 2024-02-08 at 18 33 21" src="https://github.com/pharo-project/pharo/assets/4825959/48deb898-08f6-426f-8bc1-e581aa348cb7">

**Comment by Ducasse** [comment]
When I click on 
![Capture 2024-02-08 at 20 00 04](https://github.com/pharo-project/pharo/assets/432549/791d6604-c9ff-4bb5-8f79-18bad9ef9fff)
![Capture 2024-02-08 at 20 00 13](https://github.com/pharo-project/pharo/assets/432549/16d595dc-1537-4ca4-bd66-a3a90aa480cc)

**Comment by Ducasse** [comment]
When I select a method with an override I should see the overriden method and right I do not see it.

**Comment by hernanmd** [comment]
Fixed in #16150.
