### ISSUE TITLE
asFileName in Tool-FileList used by Fuel

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#16123]
The method `String>>asFileName` is packaged in Tool-List but used by NewTools-Fuel and CodeExporter.

As FileList is a Morph-based package and it will be removed, we should move this method to another package where it guarantees to survive.

**Comment by Ducasse** [comment]
I would rewrite all the senders of the system to avoid to use it and I would deprecate it but keeping it around. Strings are too much overloaded
