### ISSUE TITLE
Cleanup and look into `uses:` and `isUsed`

### ISSUE THREAD

**Issue by balsa-sarenac** [guillep/pharo-core#16126]
**Describe the problem**
Seems like these are only used by ExtractMethodTransformation and Refactoring.
They don't use them the same, so there are differences in behavior of the two.

**Classes involved**
`RBProgramNode >> uses:` (and overrides), `RBProgramNode >> isUsed`.

**Proposal**
Look into them, verify if their implementation is correct.

**Version information:**
 - Pharo 12.0

**Comment by MarcusDenker** [comment]
I do not remember the details, we tried to use those in the past (e.g to find dead code), but it turned out to have very odd semantics and seemed to be tailored to one specific (undefined) use-case.

**Comment by balsa-sarenac** [comment]
Look at #16125, now named `#isEssential` and `#isUsedAsReturnValue`
