### ISSUE TITLE
[WEB] Link on Download page points to Pharo 10 image.

### ISSUE THREAD

**Issue by macatari** [guillep/pharo-core#16134]
The link in the sentence "Pharo images need to be downloaded separately [here](https://files.pharo.org/get-files/100/pharo64.zip)." on https://pharo.org/download points to the Pharo 10 image. I guess it should be pointing to Pharo 11 as the link in the section "Pharo standalone" does?

**Comment by Ducasse** [comment]
Thanks for the feedback. Indeed it should put to Pharo11.
