### ISSUE TITLE
Caret (return char) broken in Pharo 11 macOS Keyboard as U.S. International - PC

### ISSUE THREAD

**Issue by sebastianconcept** [guillep/pharo-core#16132]
**Bug description**
The caret is not working in Pharo 11 with US-International as it used to be in previous Pharo versions.

**To Reproduce**
1. Open a Playground
2. Ensure Keyboard is in `U.S. International - PC`  mode
3. Type ` Shift-6` for the caret
4. It prints something different than the return caret

**Expected behavior**
The return caret should be printed on key up.

**Screenshots**
![caret](https://github.com/pharo-project/pharo/assets/475508/83982934-d7c9-40b2-91fa-4dba2a28f77c)

**Version information:**
 - OS: macOS
 - Version: 12.7.2
 - Pharo Version 11

**Expected development cost**
Any investigation clues? What class controls this behavior?

**Comment by Ducasse** [comment]
Thanks we will check this.
