### ISSUE TITLE
VM crashes when running `RBCodeSnippetScriptingTest >> testTestEvaluateFailBlock`

### ISSUE THREAD

**Issue by balsa-sarenac** [guillep/pharo-core#16149]
**Bug description**
While working on #16146 `RBCodeSnippetScriptingTest >> testTestEvaluateFailBlock` crashes the VM. We've narrowed down the change that causes the crash and it is:
```
RBBlockNode >> lastIsReturn 
	^body lastIsReturn
```
We changed this method on block node, whereas previously it returned `false` by default.

**Comment by MarcusDenker** [comment]
The #lastIsReturn story is more complex and needs some more analysis.

```
(RBParser parseExpression: '[[^1]]' )body lastIsReturn
```

is clearly false. But with you change it becomes true... as lastIsReturn now recurses into, which we do not want.

**Comment by balsa-sarenac** [comment]
Thanks for clarifying Marcus!
I'll close the issue now since it's not a bug.
