### ISSUE TITLE
Package copy does not respect class-side hierarchy

### ISSUE THREAD

**Issue by Inao0** [guillep/pharo-core#16140]
**Bug description**
When duplicating a package, class-side superclasses are not properly set. They are all as "Class" instead of the expected one

**To Reproduce**
Right-click a package, copy all packages, put a new package name, and a pattern for generating new classes
<img width="643" alt="Screenshot 2024-02-12 at 20 01 41" src="https://github.com/pharo-project/pharo/assets/37711386/a1afc559-b263-4eac-ac4d-fbaf919c5a81">
<img width="346" alt="Screenshot 2024-02-12 at 20 07 08" src="https://github.com/pharo-project/pharo/assets/37711386/6d56f20b-94a2-4483-a88d-4bf4bbedb88a">

**Actual Behavior**
<img width="643" alt="Screenshot 2024-02-12 at 20 05 52" src="https://github.com/pharo-project/pharo/assets/37711386/4be03665-4fa4-4251-8316-ed0b08adc891">

**Expected behavior**
The previous example should show :
``` Smalltalk
Object class << MyClass2 class
	slots: {}
```
**Version information:**
 - OS: MacOS
 - Pharo Version 12  (Pharo-12.0.0+SNAPSHOT.build.1363.sha.a84b1048f904d97b64a03cc1fc6c43d0e3aeb9ce)

**Comment by Ducasse** [comment]
I wonder if this is a refactoring or coding directly in a command. I tagged it as refactoring so that we do not forget it.

**Comment by Ducasse** [comment]
@Inao0 I think that this was fixed when we fixed the class builder. If you have a moment could you check. 
Else I will try to follow your instructions.

**Comment by balsa-sarenac** [comment]
This is now fixed
