### ISSUE TITLE
[CI] Failing test: MetacelloLockTest>>testLoadLockedWillNotIncludeLockedPackages

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#16163]
**Bug description**
 MetacelloLockTest>>testLoadLockedWillNotIncludeLockedPackages is now failing non the CI

**Comment by guillep** [comment]
I'll make a quick PR today or tomorrow fixing most of the tests.

**Comment by MarcusDenker** [comment]
Fixed!
