### ISSUE TITLE
BeautifulComment should be managed inside Pharo

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16171]
Having a separate repository is just overkill for a package with 3 classes. 
I would like to merge it in Pharo.

**Comment by hernanmd** [comment]
Absolutely agree!

**Comment by guillep** [comment]
Just to think, wouldn't NewTools be a better place? Just asking without entirely understanding how Beautiful comments is integrated with Calypso.

**Comment by Ducasse** [comment]
New tools is more around spec. BC is calypso driven and Morph.
