### ISSUE TITLE
Cleanup: Remove <- from collection

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16185]
There is a method called #<- implemented in Collection
- it just has a single sender in AdditionalMethodState class>>#propertiesToPersist (the other two are tests for it) 
- and AdditionalMethodState class>>#propertiesToPersist could be more easily written using #asSet

We should deprecate and remove it.

**Comment by guillep** [comment]
Please, follow the discussion in here https://github.com/pharo-project/pheps/pull/22
