### ISSUE TITLE
[RB] Insert superclass refactoring breaks class side hierarchy

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#16209]
- Create a hiearchy

```smalltalk
Object << #A
	slots: {};
	package: 'A'
A << #B
	slots: {};
	package: 'A'
```

- Then select `B`, refactoring `Insert supeclass` and name it `Inserted`

<img width="171" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/549dd16c-76f9-43aa-bdf4-9a28162f00a1">

The following assertions in a playground are broken now:

```smalltalk
"Instance side"
self assert: B superclass == Inserted.
self assert: Inserted superclass == A.

"Class side"
self assert: B class superclass == Inserted class.
self assert: Inserted class superclass == A class.
```

**Comment by guillep** [comment]
Same happens with insert subclass refactoring

**Comment by Ducasse** [comment]
Yes I lost one hour yesterday because of this bug.
I created an issue: https://github.com/pharo-project/pharo/issues/16202

**Comment by Ducasse** [comment]
I think that it got broken as a side effect of the category removal.

**Comment by Ducasse** [comment]
https://github.com/pharo-project/pharo/issues/15805

**Comment by Ducasse** [comment]
We checked and the RB changes are correctly created.

Apparently the shClassBuilder use class when the metaSuperclass returns nil.


```
createMetaclass

	newMetaclass := self builderEnhancer newMetaclass: self.

	self builderEnhancer
		configureMetaclass: newMetaclass
		superclass: self metaSuperclass
		withLayoutType: FixedLayout
		slots: (self withAdditionalSlots: self classSlots).

	self builderEnhancer metaclassCreated: self

metaSuperclass

	^ metaSuperclass ifNil:[ (superclass ifNil: [ Class ] ifNotNil: [ superclass class ]) ]
```

So it means that the bug is probably in the interpretation of the changes where either the metaclass or the superclass is queried and returned nil.
