### ISSUE TITLE
[RB] Rename shortcut does not work in method pane

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#16211]
In
Pharo 12.0.0
Build information: Pharo-12.0.0+SNAPSHOT.build.1390.sha.6cefa1c3d575720237036249a266e167366ab7d9 (64 Bit)

- Go to a method pane
- put the cursor on top of a selector
- Cmd+R
=> nothing happens

**Comment by Ducasse** [comment]
Another calypso thing that we have no idea how to fix and need help for.
