### ISSUE TITLE
[RB] Method name editor dialog up/down buttons should be disabled with < 2 arguments

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#16213]
In the example below I have one argument, so it does not make sense to do Up/Down.
When I do them, they are correctly trapped and I have a pop, up, but they could be avoided.

<img width="632" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/0e74f597-8197-42dd-9e1a-6ccf60888a5c">

Also, the buttons on the right of this list do not clearly show that we are going to change the order of this list...
It would be nicer to have something like this, where the buttons are inside the elements to move!

![imagen](https://github.com/pharo-project/pharo/assets/708322/4d4d44ce-fd18-4445-aae8-6c605ff39689)

**Comment by guillep** [comment]
also, the inform pop up does not have it's button selected by default, which means I have to manually go and click on it.

**Comment by guillep** [comment]
Notice that default inform dialogs in spec handle this well by default, so there should be some difference

```smalltalk
SpInformDialog new
	openModal
```
<img width="448" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/27f0a798-89e6-43ad-a5dc-471903e7d561">

**Comment by Ducasse** [comment]
We focused on the driver and not on the UI. I mentioned that because we could lose too much time with Spec so we just use the presenter as they are.
