### ISSUE TITLE
Miller columns do not work for more than two columns when selecting an element

### ISSUE THREAD

**Issue by noha** [guillep/pharo-core#16221]
**Bug description**
If the miller columns are expanded to more than two then selecting an element in the middle shifts the view to the left and leaves an empty pane on the right. The video should explain it well

**To Reproduce**
1. Open playground
2. Create an array and inspect it and then inspect an element
3. expand the miller columns to three in the lower bar
4. then select another element of the collection
5. see that all columns shifted left and on the right is an undefined pane and it is broken

**Expected behavior**
When having three miller columns and selecting an element in the middle pane only the right pane should change. Only if you select an element on the right most pane should shift left and open a new inspector view

**Screenshots**
[video](https://github.com/pharo-project/pharo/assets/136711/18acf119-4a69-4ead-abf7-0fb3c7dfc95f)

**Version information:**
 - OS: MacOS but unrelated
  - Pharo Version 11 + 12

**Expected development cost**
I'm missing the expertise but the cost should be rather low as the context of the miller columns should be available making the logic apply.

**Comment by jordanmontt** [comment]
Related issue: https://github.com/pharo-spec/Spec/issues/1441

**Comment by estebanlm** [comment]
reopen because we need to verify if fix works for real

**Comment by estebanlm** [comment]
@noha I verified it works. Can you do it too, so this can be closed?

**Comment by noha** [comment]
I can confirm that the problem described works in a fresh pharo12 gotten from zeroconf . 

If you have 4 columns and change something on column 2 the layout reduces to 3 columns which is a bit weird. Having 4 columns with an empty fourth would be better IMHO. But yes this is not related exactly to this ticket. 

Thanks for doing it. It really saves me a lot of time
