### ISSUE TITLE
Conflicting implementations exist for #extractAllIn: for ZipArchive

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#16238]
There are conflicting implementations for `#extractAllIn:` for ZipArchive in the [‘pharo’](https://github.com/pharo-project/pharo/blob/125db9148117d14c17bd1d36eeda678b836b23fc/src/Compression/ZipArchive.class.st#L45-L52) and [‘NewTools’](https://github.com/pharo-spec/NewTools/blob/ceae3ea3b879f5babbfa0e01d5d93792a9955d6b/src/NewTools-Compression-Utils/ZipArchive.extension.st#L4-L18) repositories. This leads to confusion when committing as only of the two implementations can be loaded in the image and the one in the other repository is unexpectedly shown in the commit window as being removed.

**Comment by Rinzwind** [comment]
Other conflicting implementations: `#settingsOn:` for NECPreferences in [‘pharo’](https://github.com/pharo-project/pharo/blob/125db9148117d14c17bd1d36eeda678b836b23fc/src/NECompletion-Preferences/NECPreferences.class.st#L178-L254) and [‘NewTools’](https://github.com/pharo-spec/NewTools/blob/ceae3ea3b879f5babbfa0e01d5d93792a9955d6b/src/NewTools-SettingsBrowser/NECPreferences.extension.st#L4-L81), `#possibleSolutionsForInput:` on MethodFinder in [‘pharo’](https://github.com/pharo-project/pharo/blob/125db9148117d14c17bd1d36eeda678b836b23fc/src/Tool-Finder/MethodFinder.class.st#L32-L51) and [‘NewTools’](https://github.com/pharo-spec/NewTools/blob/ceae3ea3b879f5babbfa0e01d5d93792a9955d6b/src/NewTools-Finder/MethodFinder.extension.st#L10-L27).

**Comment by hernanmd** [comment]
I don't know why `extractAllIn:` is still in Pharo repo, it should be in NewTools-Compression-Utils (https://github.com/pharo-spec/NewTools/commit/ef9aad0d531575a6462511f74ccbf7d22bda813e)
I will make a PR to remove it from Pharo.

**Comment by astares** [comment]
@hernanmd Shouldnt it be the other way around: have it by default already in standard Pharo and remove the extension in NewTools. 

Because it is usuable in a wider scope to deal with ZIPs (also in smaller images that just have ZIP but not NewTools)

**Comment by hernanmd** [comment]
> @hernanmd Shouldnt it be the other way around: have it by default already in standard Pharo and remove the extension in NewTools.
> 
> Because it is usuable in a wider scope to deal with ZIPs (also in smaller images that just have ZIP but not NewTools)

This was already discussed in the context of removing UIManager references, because this method was using UI.

**Comment by astares** [comment]
Answering to myself:  ok - it opens a dialog (StOpenDirectoryPresenter) to ask for the target folder. So yes - it should be part of NewTools only
