### ISSUE TITLE
[RB] Extract method is broken

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#16248]
In the latest Pharo 12 I had this method:

```st
applyOn: aModel

	(self queryBlock cull: aModel cull: self) ifNotEmpty: [ :entities |
		| tag |
		tag := aModel allTags
			       detect: [ :t | t name = self tagName ]
			       ifNone: [ aModel createTagNamed: self tagName ].
		entities do: [ :e | e tagWith: tag ] ]
```

And I wanted to extract this part:

```st
	aModel allTags
	       detect: [ :t | t name = self tagName ]
	       ifNone: [ aModel createTagNamed: self tagName ]
```

But I got multiple problems:
- The text field was already filled with "fooForNow" that seems to be leftover code
- My piece of code needs `aModel` as argument but I had no argument in the window and I cannot add one
- Accepting ends up in an error message saying the content cannot be parsed

**Comment by balsa-sarenac** [comment]
I've created #16301 that will remove this transformation for the UI.
I've tried to extract it using the refactoring and it works ok, you can check as well.
