### ISSUE TITLE
Strict mode for FFI impacting build?

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16241]
on the CI of microdown I get an error that is 

https://github.com/pillar-markup/Microdown/issues/692

```
FFIUnsupportedUntypedLiteral
FFICallout>>unsupportedUntypedLiteral:
FFIStrictResolutionMode>>resolveUndeclaredTypeForArgument:withResolver:
FFICallout>>resolveUntypedArgument:
FFIUndefinedTypeDeclaration>>resolveUsing:forArgument:
FFIConstantArgument>>resolveUsing:
[ :e | e resolveUs
```

**Comment by guillep** [comment]
Hi Stef, this means that there is an FFI signature missing a type.
However, with this log I cannot tell what is the function, whether this is inside Pharo or in a third party library.
Do you have the full log somewhere?

**Comment by Ducasse** [comment]
I will check again the build.
