### ISSUE TITLE
RB - Push up refactoring the method select window opens up twice

### ISSUE THREAD

**Issue by carolahp** [guillep/pharo-core#16259]
**Bug description**
When applying a push up refactoring the window to select methods opens up two times during the execution of the refactoring

**To Reproduce**
1. Create a ClassX with a method #exampleMethod
2. Create the super class of ClassX
3. Now left click on exampleMethod and select `Refactorings>Push up`
4. In the window to select the methods to be push up, select #exampleMethod and click `Refactor`
5. The same window from step 4 will open. This is a mistake

**Expected behavior**
The Window to select the method should be displayed only once

<img width="606" alt="image" src="https://github.com/pharo-project/pharo/assets/4822303/434b214b-e878-4904-be09-eb2bbfea0bbe">

**Comment by jecisc** [comment]
Fixed in https://github.com/pharo-project/pharo/pull/16281
