### ISSUE TITLE
Latest P12 Release contains release test issues / failing tests (Impact on CI)

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16252]
Downloading a most recent Pharo 12 

Pharo12.0.0SNAPSHOT
Build information: Pharo-12.0.0+SNAPSHOT.build.1404.sha.c25b2fe6df3d2f9f27833c88ae9b36e416a769ce (64 Bit)

the release tests are failing.

For instances tests like
 - testThatThereAreNoSelectorsRemainingThatAreSentButNotImplemented
 - testNoLeadingOrTrailingSpacesInCategoryNames
 - and other

<img width="432" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/9c12a7ca-176d-40f8-8d54-11b86e84b858">

**Comment by MarcusDenker** [comment]
Fixed!
