### ISSUE TITLE
Keybinding for Open Monticello Browser signals an error

### ISSUE THREAD

**Issue by tinchodias** [guillep/pharo-core#16275]
Message: `Error: No tool named: "monticelloBrowser" present in the registry`

**Steps**
Open Pharo 12 and do the "o+p" shortcut sequence. In Mac it's CMD "o" then "p".

**Expected behavior**
Not an error. Should the key binding be removed?

**Screenshot**
<img width="648" alt="Screenshot 2024-03-04 at 19 35 35" src="https://github.com/pharo-project/pharo/assets/3044265/e3120dc8-763d-4ec6-bb7b-238056cc7eca">

**Version information:**
 - OS: Mac
 - Pharo Version 12
 - Build information: Pharo-12.0.0+SNAPSHOT.build.1407.sha.0404d4e9e74f4ea4d918a65c6a328840a548adbe (64 Bit)

**Comment by hernanmd** [comment]
This keybinding (O+P) was re-mapped to Open Playground in P13.
We can close this issue.
