### ISSUE TITLE
Adding option to load Bloc / Toplo as there is for Roassal

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#16289]
We need to add the menu entry to load the stable version of Bloc and Toplo

**Comment by tinchodias** [comment]
master branch is the stable in both

**Comment by tinchodias** [comment]
I think if we use Pharo12 branch, then we have to create such branch in these 4 repos: Toplo, Album, Bloc and Alexandrie
and update the baselines so that Toplo:Pharo12 loads Album:Pharo12, etc.

**Comment by hernanmd** [comment]
Is this for Pharo 12 or Pharo 13?

**Comment by jecisc** [comment]
For Pharo 12!

**Comment by jecisc** [comment]
Don't we want to also load Toplo via a menu entry?
