### ISSUE TITLE
[CI] failing test: ReleaseTest>>testThatThereAreNoSelectorsRemainingThatAreSentButNotImplemented

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#16280]
**Bug description**
This tests is failing: ReleaseTest>>testThatThereAreNoSelectorsRemainingThatAreSentButNotImplemented

```
Error

an OrderedCollection('FFILibrary>>#unixLibraryName') should have been empty
Stacktrace

TestFailure
an OrderedCollection('FFILibrary>>#unixLibraryName') should have been empty
ReleaseTest(TestAsserter)>>assert:description:resumable:
ReleaseTest(TestAsserter)>>assert:description:
ReleaseTest(TestAsserter)>>assertEmpty:
ReleaseTest>>testThatThereAreNoSelectorsRemainingThatAreSentButNotImplemented
ReleaseTest(TestCase)>>performTest
```

**Comment by hernanmd** [comment]
I think `unixModuleName` was removed without rewriting senders? 
https://github.com/pharo-project/pharo/pull/16257/files


<blockquote><img src="https://avatars.githubusercontent.com/u/3044265?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo/pull/16257">Minor improvement in TF test class by tinchodias · Pull Request #16257 · pharo-project/pharo</a></strong></div><div>Rename unixModuleName as unix64LibraryName
Superclass definition is:
FFILibrary&gt;&gt;
unixLibraryName
&quot;Kept for backward compatibility.
The system complains that this method is not implement...</div></blockquote>
