### ISSUE TITLE
Pharo doesn't run on latest Mac OS

### ISSUE THREAD

**Issue by j-brant** [guillep/pharo-core#16286]
**Bug description**
On my M1 and M3 Macs, I've updated to macOS Sonoma 14.4, and can no longer run Pharo. I get 

```
[ERROR] 2024-03-08 08:16:04.000 allocateStackPages (Replacement/generated/64/vm/src/gcc3x-cointerp.c:84689):Could not allocate stack in the expected place (0x280000000), got 0x300140000
[ERROR] 2024-03-08 08:16:04.000 error (src/debug.c:45):Error allocating

VM Error Fri Mar  8 08:16:04 2024


/Users/brant/Documents/Pharo/vms/120-x64/Pharo.app/Contents/MacOS/Pharo
PharoVM version:5.0-Pharo 10.1.0 built on Feb 14 2024 09:35:15 Compiler: Apple LLVM 12.0.5 (clang-1205.0.22.9) Apple LLVM 12.0.5 (clang-1205.0.22.9) [Production Spur 64-bit VM]
Built from: CoInterpreter VMMaker-tonel.1 uuid: c73ebc1b-b5cd-0d00-86fe-81420df24b96 Feb 14 2024
 With:StackToRegisterMappingCogit VMMaker-tonel.1 uuid: c73ebc1b-b5cd-0d00-86fe-81420df24b96 Feb 14 2024
 Revision: v10.1.0 - Commit: a290a408 - Date: 2024-02-14 09:15:58 +0100


Segmentation fault: 11 Fri Mar  8 08:16:04 2024


/Users/brant/Documents/Pharo/vms/120-x64/Pharo.app/Contents/MacOS/Pharo
PharoVM version:5.0-Pharo 10.1.0 built on Feb 14 2024 09:35:15 Compiler: Apple LLVM 12.0.5 (clang-1205.0.22.9) Apple LLVM 12.0.5 (clang-1205.0.22.9) [Production Spur 64-bit VM]
Built from: CoInterpreter VMMaker-tonel.1 uuid: c73ebc1b-b5cd-0d00-86fe-81420df24b96 Feb 14 2024
 With:StackToRegisterMappingCogit VMMaker-tonel.1 uuid: c73ebc1b-b5cd-0d00-86fe-81420df24b96 Feb 14 2024
 Revision: v10.1.0 - Commit: a290a408 - Date: 2024-02-14 09:15:58 +0100
```

**Version information:**
 - OS: macOS Sonoma 14.4
 - Version: latest Pharo 12 image downloaded by the Pharo Launcher (or older P11 and P10 images with newer VMs)

**Additional context**
It appears that the bug was introduced between https://files.pharo.org/vm/pharo-spur64-headless/Darwin-arm64/PharoVM-10.0.2-fdd3df06-Darwin-arm64-bin.zip and https://files.pharo.org/vm/pharo-spur64-headless/Darwin-arm64/PharoVM-10.0.4-bf7aa420-Darwin-arm64-bin.zip as the former was able to `eval` `"3+4"` and the later crashed.

**Comment by sweagraff** [comment]
I can verify that I have the same problem on Pharo 11 as well as Pharo 12. This can be reproduced by downloading either release via curl -L https://get.pharo.org | bash. 

<blockquote><div><strong><a href="https://get.pharo.org/">Pharo Zeroconf Script</a></strong></div></blockquote>

**Comment by Ducasse** [comment]
Thanks we will check that as soon as possible.

**Comment by tesonep** [comment]
I am pushing a release this week (maybe today) to fix it

**Comment by tesonep** [comment]
It has been solved with the latest release of the VM.
Please update your VMs.

**Comment by Ducasse** [comment]
Thanks Pablo. 
I like that to thank the consortium because nothing is free in this world and thanks is cheap :)
