### ISSUE TITLE
Toolbar buttons in window showing recent versions of a method signal a MessageNotUnderstood

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#16299]
In the window showing the recent versions of a method, the toolbar buttons other than ‘Revert’ (so ‘Browse’, ‘References’, ‘Senders’ and ‘Implementors’) all cause a MessageNotUnderstood to be signaled.

This was previously reported in issue #16045 but is still the case in Pharo 12 build 1425. Another problem mentioned in issue #16045 is still present as well: the balloon text for the context menu item ‘Revert to selected version’ seems wrong.

**Comment by Ducasse** [comment]
Oops!

**Comment by tesonep** [comment]
Fix by https://github.com/pharo-spec/NewTools/pull/721
