### ISSUE TITLE
CodeCritics displays rationale with method syntax hightlight

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16290]
and it should be plain text.

**Comment by Ducasse** [comment]
<img width="771" alt="Capture 2024-03-12 at 11 37 09" src="https://github.com/pharo-project/pharo/assets/432549/a572a1a1-e915-48da-8bde-a100b18e7926">

**Comment by demarey** [comment]
It should only be plain text when no critic is selected in the right pane but should be hightlighted otherwise
