### ISSUE TITLE
Wrong focus in Calypso Find Class Dialog causes exception

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#16313]
**Bug description**
 - Open Calypso
 - Right-click in package panel
 - Select "Find class"
 - Type Cmd+W
 => This wrongly closes calypso instead of the find class dialog

Moreover,
 => closing the dialog throws exception sometimes

**Comment by demarey** [comment]
fixed in #16386

**Comment by guillep** [comment]
The attempted fix in https://github.com/pharo-project/pharo/pull/16492 was actually causing other issues such as https://github.com/pharo-project/pharo/issues/16436.

We should properly fix the focus

**Comment by guillep** [comment]
Ok, we chased this issue up to the `#ClyCloseBrowserCommand` that is bound to Cmd+W.
The modal pop up to find classes calls that command that in turn does:

```
browser close
```

That is made to close a tab in a group window, or the (browser)window itself, but it has no knowledge about pop ups that are open by it.

```smalltalk
ClyFullBrowserMorph >> close
	| currentWindow |
	currentWindow := self window.

	(currentWindow ownerThatIsA: GroupWindowMorph) ifNotNil: [:group |
		^self okToChange ifTrue: [
			[group removeWindow: currentWindow]
				on: ProvideAnswerNotification do: [:notification |
					"We already got answer from okToChange check above"
					notification resume: true]]].

	currentWindow close
```
