### ISSUE TITLE
Instance of ScopesManager class did not understand #defaultScope (when right clicking generated getter method)

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16329]
Open latest Pharo 12 image

- Create a package "Foo"
- Create a class "Bar" with an ivar "x"
- use the "Generate accessors" menu to generate a getter and setter
- now select the getter method and right click in the code pane

<img width="587" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/d32cb08b-fcfd-4952-b6ce-e87cf1b44baa">

<img width="583" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/ed21b680-3c49-43e5-a85f-3c37e2bf823e">

**Comment by tesonep** [comment]
Will be fixed with https://github.com/pharo-spec/NewTools/pull/718

**Comment by tesonep** [comment]
Fixed with new version of newtools
