### ISSUE TITLE
ScopesPresenter class did not understand #openSelecting:

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16327]
Open Pharo 12 (here we use Pharo-12.0.0+SNAPSHOT.build.1436.sha.8b34d13d68ada0f38346af4d6e07dd0fcfe1c034 (64 Bit))
and select a simple class like "ASTCache" and now try to create a new scope from the provided class:

<img width="659" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/95c8209c-52a7-4b14-9703-d996eabe8f29">

this gives an error:

<img width="664" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/537f6edc-4471-470f-b64e-6badb45c8dc3">

**Comment by tesonep** [comment]
Fixed with new version of Newtools
