### ISSUE TITLE
Instance of ScopesManager class did not understand #activeScope (when removing a class)

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16328]
Open latest Pharo image (Pharo-12.0.0+SNAPSHOT.build.1436.sha.8b34d13d68ada0f38346af4d6e07dd0fcfe1c034 (64 Bit)
and create a simple class.

Now *try to remove it* using the "(R) Remove" menu item from context menu and you will end up with a DNU:

<img width="409" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/523aa668-0f30-485f-a481-bfbc792c99cc">

<img width="646" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/a1dddca3-c48c-4f38-a865-c9257c9e5c19">

**Comment by Rinzwind** [comment]
Merging [NewTools pull request #718](https://github.com/pharo-spec/NewTools/pull/718/files) should fix this, see [pull request #15918](https://github.com/pharo-project/pharo/pull/15918).

**Comment by tesonep** [comment]
Fixed with new version of newtools
