### ISSUE TITLE
Bug in Transcript

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16332]
I just typed `Smalltalk all`

<img width="859" alt="Capture 2024-03-21 at 14 06 27" src="https://github.com/pharo-project/pharo/assets/432549/f4e8553f-546f-4113-af7d-c577d8cd8705">

**Comment by MarcusDenker** [comment]
Yes, this is related to the cleanup that we did to avoid checking everytime if the selector is implemented in the model instead of just implementing it.

I will add the method to the transcript class

**Comment by Ducasse** [comment]
I fixed it by defineing 

hasBindingOf: aString
   ^ false.
