### ISSUE TITLE
Tonel export of class trait can be wrong

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#16345]
Since a few weeks/months in Pharo 12 it happens that the Tonel export of some code generates wrong class trait. It will be `#classTraits : '{} + TraitedClass'`. 

This prevents the code from loading afterward and is not easy to catch. 

This should be fixed before the release of P12.

**Comment by jecisc** [comment]
Here is an example: https://github.com/pharo-project/pharo/pull/16343/commits/c23a2fea536d9c473c06aeed4a4629082997765b

**Comment by PalumboN** [comment]
Probably related to this merged PR: https://github.com/pharo-project/pharo/pull/15833/files

As it says this other issue: https://github.com/pharo-project/pharo/issues/16014

In your example, the `DADependencyTreePresenter` has no traits but there are up in the hierarchy.

I understand that `#classTraits : '{} + TraitedClass'` should not appear in the subclasses.

<blockquote><img src="https://avatars.githubusercontent.com/u/708322?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo/pull/15833">Make TraitedClass part of the trait composition of TraitedMetaclasses by guillep · Pull Request #15833 · pharo-project/pharo</a></strong></div><div>When changing the superclass of spec tests in pharo-spec/Spec#1496, a release test broke.
Completely unrelated to the original PR.
ProperPackagesTest debug: #testPackageExtensionsStartsWithProperPa...</div></blockquote>

**Comment by estebanlm** [comment]
is this still happening ?
(I did not have this problem recently)

**Comment by jecisc** [comment]
I've not seen any fix for this integrated so I think it's probably still happening
