### ISSUE TITLE
(T) Realize class fails with DNU

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#16358]
- Create a class
- right click -> Realize class

<img width="1094" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/27f53bcc-db38-48ab-a3a2-a5a99e079ec5">

**Comment by hernanmd** [comment]
I couldn't reproduce the issue here in a new Pharo 12 image.

https://github.com/pharo-project/pharo/assets/4825959/f2fc706c-1bf7-4033-9dbc-e592b02b4e13

https://github.com/pharo-project/pharo/assets/4825959/ff7182f8-6538-4149-ae87-9e23293ca883

**Comment by balsa-sarenac** [comment]
I'm not able to reproduce this either, is there some additional code you've used to create this?

**Comment by guillep** [comment]
Nope, but maybe it was a slightier old image? (two weeks older than my test?)
We can close it if you think it's not a bug anymore
