### ISSUE TITLE
Rename class refactoring popup does not have default button

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#16356]
When renaming a class, the pop up does not react to the <enter> key. It would be nice if it did.

<img width="456" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/89e59bb2-eadf-4423-81ad-33f0de0ac227">

I wanted to mark it as "First impression counts" but the tag is not there anymore :(

**Comment by guillep** [comment]
Also the popup says "the name should be valid" but there is no way a newbie knows what is a valid class name.

**Comment by jecisc** [comment]
@guillep I added the tag First impression count. This was something we had with Fogbugz
