### ISSUE TITLE
Improve "Expand" menu for class definition

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#16363]
Today we have the following menu

<img width="191" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/02a917c0-3bb2-4028-84a9-c3648cfd523a">

<img width="220" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/9db7f904-7e61-4844-9544-ab50222c68cf">

I propose that:
 - it should be the first menu item
 - we should rename it to something more explicit like "Expand class definition"
 - it could also use some good tooltip

**Comment by Ducasse** [comment]
Agreed
