### ISSUE TITLE
[RB] Generate equals and hash, generate printon are destructive

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#16361]
- Take a class in calypso
- right click, extras
- either generate hash or generate printon, and generate something

=> they will overwrite existing hash/=/printOn: methods without a warning

I would expect a change list like in refactorings

**Comment by Ducasse** [comment]
I would disable them because they always got this behavior.

**Comment by demarey** [comment]
would need a preview window

**Comment by guillep** [comment]
I propose to not make this block the release.
