### ISSUE TITLE
[RB] Generate Equals and Hash DNU

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#16360]
- On a class with no instance variables
- Right click -> extras -> generate equals and hash
- this opens a popup to select variables (there are none)
- click ok

<img width="849" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/fbb73614-a88d-4502-bb19-d0dae536f617">

**Comment by guillep** [comment]
Same happens if there are slots but none is selected.

**Comment by demarey** [comment]
fixed by #16384
