### ISSUE TITLE
Add subclass can create trait subclasses

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#16365]
Both Add subclass and Insert subclass refactorings on traits can create Trait subclasses and break lots of invariants!

<img width="434" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/de477b3b-f7d5-4619-9441-5fe1a7cb5a5b">

<img width="187" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/bbf73337-dc79-4bbb-a448-79ba1ca48bb1">

**Comment by demarey** [comment]
would need a preview window
