### ISSUE TITLE
Make new tools easily accessible

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#16377]
New tools in Pharo 12 such as File System Browser, Settings Browser and Finder are not accessible from the world menu. 

**Expected behavior**
Add a new menu entry under System menu so we can launch these new tools making more easily accessible for users.

**Expected development cost**
This is no more than a method to group menu entries. New tools should specify this menu entry as parent:

**Comment by demarey** [comment]
I'm not sure we should expose these tools.
We decided to do not make them the default version for P12 because they are not fully ready.
I think it is better to make them the default tools early in P13.

**Comment by hernanmd** [comment]
Two different things.

I understand that the new tools are not configured by default in P12, but simply hiding them from all menus is a lousy way to show progress. In fact, I think it might even be taken the wrong way as it would be deliberately hiding the fact that there are improved versions of the old Squeak-era tools.

I think Pharo users are able to understand when a toolset is in an experimental state.

**Comment by Ducasse** [comment]
We could add (preview) in the menu entry.

**Comment by jecisc** [comment]
PRs got merged.
