### ISSUE TITLE
Buttons in quit confirmation dialog move when moving the hand over them

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#16389]
As demonstrated in the following video, in the dialog asking whether to ‘Save changes before quitting?’, the buttons move when moving the hand over them. The Playground snippet used in the video shows the position of the ‘Discard’ button on the transcript. The position is 299.5@244.0 initially, it first changes to 300.0@244.0 and then to 301.0@244.0.

https://github.com/pharo-project/pharo/assets/1611248/2d52d11a-8fa9-45ee-9134-0d62337c5685

Tested using: Pharo 12 build 1455.

**Comment by Rinzwind** [comment]
This is related to the dialog’s position (173.5@160.0) having a nonintegral x-coordinate, which is changed in pull request #16390.

**Comment by jecisc** [comment]
The PR was merged
