### ISSUE TITLE
Having good styles for Microdown rendered comments in light theme

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16394]
In light theme class comment are barely readable.
It gives the feeling that we did not care. Here we cannot read the classes in the hiearchy

![Capture 2024-04-02 at 15 29 22](https://github.com/pharo-project/pharo/assets/432549/d4bf0ec4-56e4-40d7-ba29-907a81c1b892)

**Comment by Ducasse** [comment]
Or we can simply remove the light theme.

**Comment by hernanmd** [comment]
Could you update the following method with the code here and send me a screenshot or tell me if it does look right for you?

```smalltalk
MicTextStyler >> #monospaceBackgroundColor
	^ Smalltalk ui theme settings windowColor muchLighter
```

This is what it looks like on my screen.

<img width="845" alt="Screenshot 2024-04-03 at 17 10 23" src="https://github.com/pharo-project/pharo/assets/4825959/cb2d4e21-608b-4c1d-9245-0fbfadf52b79">

**Comment by jecisc** [comment]
Did you also check with the dark theme?

**Comment by hernanmd** [comment]
> Did you also check with the dark theme?

I never use dark theme but I tried and if dark theme is used, then my "update" should be `muchDarker` instead of `muchLighter`

**Comment by estebanlm** [comment]
we can't remove light theme :)
now the problem is that the "code" block (this is how the hierarchy and links are made) is rendered with a background that is not  very appealing. Honestly I would put it just transparent (no need to have it differentiate)

**Comment by Ducasse** [comment]
Agreed it sucks. So we do a lot to improve and the last 2 % may kill us.

**Comment by hernanmd** [comment]
Surprisingly, if you change the color to transparent and hover the mouse over a microdown text with monospace, you get this error...

![Screenshot 2024-04-05 at 15 59 34](https://github.com/pharo-project/pharo/assets/4825959/1bfc6aa6-fce5-4437-b26f-0440568f2825)

I think it would be better to have a minimum variation of transparent because I don't know what the code is actually checking

**Comment by hernanmd** [comment]
Ok, PR in https://github.com/pillar-markup/Microdown/pull/701

**Comment by jecisc** [comment]
Fixed in https://github.com/pillar-markup/Microdown/pull/702
