### ISSUE TITLE
"Open terminal here" in new File browser does not work correctly on Windows

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16393]
Open the new file browser and select "Open terminal here" when you are on a Windows machine:

![image](https://github.com/pharo-project/pharo/assets/5980033/0e4c21b5-63ab-40a0-b58b-85bee5a088b4)

This fails with an error:

![image](https://github.com/pharo-project/pharo/assets/5980033/7a3a74a9-7d04-440c-9ec3-808a0ea2c14e)

One has to change the method StFileBrowserOpenTerminalCommand>>#openWindowsTerminalOn:
from

```Smalltalk
openWindowsTerminalOn: aPath

	^ String streamContents: [ : stream |
		stream
			<< 'start cmd.exe /K "cd /d ';
			<< aPath;
			<< '"' ]
```

to

```Smalltalk
openWindowsTerminalOn: aPath

	^ String streamContents: [ : stream |
		stream
			<< 'start cmd.exe /K "cd /d ';
			<< aPath fullName;
			<< '"' ]
```

to make it work. Should be fixed before P12 release.

**Comment by astares** [comment]
Need to be fixed in https://github.com/pharo-spec/NewTools

<blockquote><img src="https://opengraph.githubassets.com/8d2663ccbc7be8e1294f4de01561fd1cc807e63ff06d001934f40c6a384c157a/pharo-spec/NewTools" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-spec/NewTools">GitHub - pharo-spec/NewTools: All development tools for Pharo, developed with Spec</a></strong></div><div>All development tools for Pharo, developed with Spec - pharo-spec/NewTools</div></blockquote>

**Comment by hernanmd** [comment]
Thanks for reporting, and the quick fix.
PR in https://github.com/pharo-spec/NewTools/pull/732

**Comment by jecisc** [comment]
Merged

**Comment by astares** [comment]
@hernanmd thanks for the PR
