### ISSUE TITLE
Preview Settings Browser: does not open when a custom setting is used

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16399]
In a fresh Pharo 12 image:
1. Create or load any tool with a *custom setting* ( a tool that uses the "&lt;systemsettings&gt;" pragma) like https://github.com/astares/Pharo-Pomodoro

```Smalltalk
Metacello new 
	repository: 'github://astares/Pharo-Pomodoro:main/src';
	baseline: 'Pomodoro';
	load
```

2. Open the Preview of the new Settings Browser from the world menu

![image](https://github.com/pharo-project/pharo/assets/5980033/308e94f2-2e49-4385-94f6-94ef0428009a)

Looks like it tries to search for an icon in the icon map

![image](https://github.com/pharo-project/pharo/assets/5980033/d8e6fc3e-978a-4196-a40e-ff16e8d4cb59)

Maybe a "fallback" icon should be used so at least it is possible to open this tool when no icon is provided.

**Comment by hernanmd** [comment]
Fix proposed in https://github.com/pharo-spec/NewTools/pull/734

**Comment by jecisc** [comment]
Merged

**Comment by astares** [comment]
@hernanmd Thanks!
