### ISSUE TITLE
Preview Settings Browser: gives FileLocator DNU #asText

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16398]
- open the **New Settings Browser** from the world menu in P12
- click on "System" icon in the left pane

I understand that we include the new tools as a **Preview** in P12 - but if they throw already
issues then it would be better to hide them as this could give a bad impression of Pharo
(or fix the most obvious bugs if timeline still allows to take care of them before releasing P12)

![image](https://github.com/pharo-project/pharo/assets/5980033/0c320ec9-92f0-4a8e-94cb-3387e4c607c0)

**Comment by hernanmd** [comment]
Fixed in https://github.com/pharo-spec/NewTools/pull/736
