### ISSUE TITLE
Rename menu item position

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16396]
Pharo 11:

![image](https://github.com/pharo-project/pharo/assets/5980033/a47cd03a-f50e-4ed2-a731-8705231322ff)

Pharo 12:

![image](https://github.com/pharo-project/pharo/assets/5980033/edf965ae-7a00-489d-8105-d7d7bcdaeacc)

why is "Rename" now on the top of the menu now? 

Is this a bug or by intention?

**Comment by hernanmd** [comment]
The menu item orders are a complete mess. Even some items were removed. 
And the items are conceptually all mixed and have no consistency in their order. 
They should be ordered with some kind of logical sense. Something like this:

```
- (Direct class operations)
Browse
Deprecate
Duplicate
Migrate
New class
Realize
References
Remove
Rename
- (Instance variable operatiosn)
Generate accessors
Abstract instance variables
- (Test class operations)
New test class
Jump to test class
- (Groups)
Scopes >
Refactorings >
```

**Comment by Ducasse** [comment]
Ok now rename and browse and references are the most frequently used.

**Comment by jecisc** [comment]
Fixed by hernan
