### ISSUE TITLE
Confusing Button order

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16395]
In **Pharo up to version 11** one was able to 
 - **confirm** dialogs with a button on the **left side** (which follows european reading order to have first primary action on left)
 - **cancel** dialogs with a button on the **right side**
and which is the usual way for platforms like **LINUX and WINDOWS**.

![image](https://github.com/pharo-project/pharo/assets/5980033/c3459ebb-074b-4b2a-859d-0a8304e49c70)

Now in *Pharo 12* it looks like the confirmation has been changed to do it exactly the other way around. 
 - **cancel** dialogs with a button on the **left side**
 - **confirm** dialogs with a button on the **right side**
which seems to align with Apples macOS style.

![image](https://github.com/pharo-project/pharo/assets/5980033/58ed910e-ff3c-4a58-9ed1-594ff7c44b9d)

**This is breaks the flow, is now really strange and painful for every developer used to the other platforms and the previous "clicking" style of Pharo. **

Unfortunately there is no setting to get back to the original situation for those who are used to it while allowing the current order for people who are used to Apple.

For the label area of windows Pharo offers already a setting to distinguish between macOS and Linux/Windows style.

![image](https://github.com/pharo-project/pharo/assets/5980033/7a95d5f8-c25c-45ef-97da-0459d1df8eb5)

Havent checked how the new dialog is done - but I expect it to be done with Spec2. So maybe it is a reusable part so such a setting and button order switch could be provided centrally and in a reusable way.

**Comment by jecisc** [comment]
Hi,

The order of button was not always the same in all Pharo applications and this is something we want to improve.
For Pharo 12 a first step that Estaban did was to make sure the order was the same for all the Pharo tools.

The long term goal would be to add a configuration indeed once we will have only one way used to declare an action button and a cancel button

**Comment by astares** [comment]
We still have a mixture in P12 - some of the dialogs use the previous order:
![image](https://github.com/pharo-project/pharo/assets/5980033/78e85118-da19-48a6-8754-970826039940)

I understand and appreciate the progress to convert the dialogs - so it is a WIP.

**Comment by Ducasse** [comment]
I will close this issue and we can reopen it in spec.

**Comment by astares** [comment]
I opened a Spec issue for it: https://github.com/pharo-spec/Spec/issues/1684
