### ISSUE TITLE
Refactoring options popup does not have enough space for the message

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#16403]
Remove a class with users:

<img width="425" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/487b208f-118c-4f91-b4d9-5cc7c5048bef">

the message is cut:

<img width="705" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/f73a02de-754d-41e0-ac57-c9b75be15f34">

**Comment by jecisc** [comment]
Ideally spec should wrap the message instead of forcing us to extend the popup no?
