### ISSUE TITLE
[RB] expose accessor to instance variable access refactoring

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16415]
The concretize refactoring is not exposed to the user. 
It would be nice to expose it.

**Comment by hernanmd** [comment]
I couldn't find this one. What is the class implementing this refactoring?

**Comment by Ducasse** [comment]
This is the protect menu item.
So this is already available. 
We should find a way to use class comment as menu tooltip. so that people can understand the refactoring
