### ISSUE TITLE
Messy menu in code pane

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16431]
![Capture 2024-04-09 at 16 09 04](https://github.com/pharo-project/pharo/assets/432549/99675463-6bf5-494b-896e-2e83c8a5043c)

**Comment by Ducasse** [comment]
We should group the debugging into debugging. And do we need the add counter and add watchPoint entry

**Comment by adri09070** [comment]
#16397 PR is already open for that. If it is merged, only the "Debug Points" menu would be left

**Comment by estebanlm** [comment]
this is fixed upstream
