### ISSUE TITLE
String>>asSymbol no protected against concurrent access

### ISSUE THREAD

**Issue by fedemennite** [guillep/pharo-core#16430]
**Bug description**
Sending String>>asSymbol may fail on inconsistency errors of the symbol table's access, if at least all the following is true:
- the symbols being looked up aren't yet in the symbol table
- such an operation is performed from multiple smalltalk processes

**To Reproduce**
No easy to reproduce.
Sending #asSymbol on sequentially random or enumerated strings from forked smalltalk processes with different priorities

**Expected behavior**
No error should be signaled 

**Version information:**
Pharo 10/11

**Expected development cost**
A simple implementation protecting String>>asSymbol with a mutually exclusive semaphore should be enough and quick to have.
A more refined implementation could try to lookup the symbol without semaphore protection and subsequently go through the semaphore only if the symbol doesn't exist yet.

**Comment by pavel-krivanek** [comment]
Maybe Mutex would be safer to use here but this is such a low-lever speed critical operation that we probably need to accept Semaphore.

**Comment by pavel-krivanek** [comment]
related to https://github.com/pharo-project/pharo/issues/6524

**Comment by MarcusDenker** [comment]
PR was merged: https://github.com/pharo-project/pharo/pull/16565
