### ISSUE TITLE
No button to fileIn code from FileBrowser

### ISSUE THREAD

**Issue by yannij** [guillep/pharo-core#16453]
**Bug description**
FileIn code using the FIleBrowser can no longer be done, because there is no button the initiate a fileIn

**To Reproduce**
1. Go to System/FileBrowser menu to open a FIleBrowser
2. Navigate to a .st file you have previously filed-out, and select it
3. Notice there is no way to fileIn the file. In version 11, there was an Install button

**Expected behavior**
There should be a button labelled Install or FileIn

**Screenshots**
![filebrowser-v11](https://github.com/pharo-project/pharo/assets/12106900/55019fe3-f9dc-4327-8ac1-e243914c89d9)
![filebrowser-v12](https://github.com/pharo-project/pharo/assets/12106900/f8a71eea-f7b6-421f-b21f-b1e37785ea41)

**Version information:**
 - OS: MacOSX
 - Version: 13.6.6 (22G630)
 - Pharo Version 12

**Comment by Ducasse** [comment]
thanks a lot

**Comment by estebanlm** [comment]
@hernanmd this is for you :)

**Comment by jecisc** [comment]
I think this got lost when we removed the change set browser. IIRC there was a file service in that package to manage the file in of code.

**Comment by jecisc** [comment]
Related issue: https://github.com/pharo-project/pharo/issues/15933

**Comment by hernanmd** [comment]
> @hernanmd this is for you :)

In #16470 
(please note since I'm on vacation, it may take me longer to respond)

**Comment by jecisc** [comment]
Fixed

**Comment by MarcusDenker** [comment]
I do not see the fileIn button when I select a .st file

**Comment by MarcusDenker** [comment]
Ah, we have a new issue:

https://github.com/pharo-project/pharo/issues/16453

I close this
