### ISSUE TITLE
[CI] Windows test run fails due to ‘No space left on device’

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#16450]
In [build 1 for pull request #16449](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16449/1/), the [Windows test run](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/view/change-requests/job/PR-16449/1/execution/node/81/log/) failed due to an error ‘No space left on device’:

```
ci@WIN10-CI C:\builds\workspace\est_and_branch_Pipeline_PR-16449\Tests-windows-64>bash -c 'bootstrap/scripts/runTests.sh 64 Tests-windows-64' 
[…]
cp: error writing './Pharo10.0-64bit-9a68076.sources': No space left on device
```

**Comment by Rinzwind** [comment]
The error did not occur in [build 2 for the pull request](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-16449/2/) so I guess this issue can be closed though I don’t know why it no longer occurred.

**Comment by Rinzwind** [comment]
I’m reopening this as ‘Pharo12’ builds [1478](https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/Pharo12/1478/pipeline) and [1479](https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/Pharo12/1479/pipeline) had the Windows test run fail with a similar error: “write error (disk full?)”. Some investigation seems to be needed of why the Windows Jenkins node sometimes doesn’t have enough disk space.

**Comment by MarcusDenker** [comment]
This is now fixed
