### ISSUE TITLE
What is the difference between hierarchical implementors and hierarchy?

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#16463]
<img width="200" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/775bffc0-0a01-4042-b29e-9bb7ef784d61">

They seem to do the same but one uses the scope and the other does not.

**Comment by estebanlm** [comment]
uhm, no idea.

**Comment by Ducasse** [comment]
The implementors/senders are only look within the classes and its superclasses and this is superhandy.

**Comment by Ducasse** [comment]
So imagine that we can close this issue.

**Comment by guillep** [comment]
> The implementors/senders are only look within the classes and its superclasses and this is superhandy.

I know, but my point is that both menu entries do the same!

**Comment by Ducasse** [comment]
Ah this is strange then we should remove the items that is not 'Hierarchical' because this is unclear that the sender and hierarchical in this menu
