### ISSUE TITLE
Tonel code saving leads to strange classTraits definition

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16480]
Using Pharo 12 for development now sometimes leads to the issue that classes that are saved in Tonel like;

```
...
Class {
	#name : 'MKAOpenBrowserCommand',
	#superclass : 'MKALauncherCommand',
	#classTraits : '{} + TraitedClass',
	#category : 'MyKillerApp-Spec-UI-Commands',
	#package : 'MyKillerApp-Spec-UI',
	#tag : 'Commands'
}
...
```

where the line with the classTraits definition leads to an issue when loading the project back in a fresh image.
**Removing such a line in the class definition manually makes the project work again.**

Unfortunately I can not reproduce what leads exactly to the issue but it is happening from time to time, several times.
I think mostly when I define new classes in packages and afterwards save / commit them. 

The issue then will only be noticed when I load the project code back in a fresh image.

**Comment by estebanlm** [comment]
duplicated of #16345
