### ISSUE TITLE
Debugging context menu is lost with new debug point integration

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#16488]
Before the debug point integration, we had menu items in Calypso's about debugging and watchpoints

<img width="364" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/63513680-8d4d-44e6-b813-3096135a8415">

Now those menus are gone in build 1487

**Comment by adri09070** [comment]
Ok, but what should there be exactly? The debugging group only contained commands to set breakpoints/watchpoints/execution counters which are all replaced by debug points.

Do you just want me to put all debug points commands in the "Debugging" command group?

**Comment by guillep** [comment]
Well, no idea, but this should be discussed :)
I was just noting that before we had menu entries in the method list to set/remove breakpoints and watchpoints.

And now we have nothing

<img width="210" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/fb4a90df-6a48-4ddd-96fd-101671ec3744">

Maybe @estebanlm can give us some guideline.
Should we have a menu option in the method list?
Or not? => and then we should close this issue

**Comment by adri09070** [comment]
Ah, I understand now! The "Debug Points" menu group appears at the source code level in Calypso but not in the method list! 

Indeed, this deletion was not intended. I'll work on it

**Comment by guillep** [comment]
Thanks @adri09070 !!!
