### ISSUE TITLE
New rule for empty period

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16514]
I saw some code like this: with the period after the first comment
and it would be nice to have a rule spotting them. 

```
phaserRate: anInteger
	"change phaserRate for the sound ".
	self dirtMessage add: 'phaserrate'; add: anInteger
```

**Comment by astares** [comment]
The "unnecessary characters found in method body" setting is unfortunately still off by default.

![Screenshot from 2024-05-15 10 26 27](https://github.com/pharo-project/pharo/assets/5980033/6ba36ee8-9c56-4431-9577-9af3a6ea0e2f)


But we could extend the ReMethodSourceCleaner (which is already caring on a final dot and unnecessary whitespaces) to also care about an unnecessary dot behind a comment. The ReMethodSourceCleaner utility class is already used in   ReCompactSourceCodeCritic / ReCompactSourceCodeRule

**Comment by astares** [comment]
Closed but not fixed
