### ISSUE TITLE
Broken download link on website

### ISSUE THREAD

**Issue by igouy** [guillep/pharo-core#16536]
https://pharo.org/download page

Pharo image: [64bit (default)](https://files.pharo.org/get-files/120/pharo64.zip)

Not Found

The requested URL was not found on this server.

**Comment by pavel-krivanek** [comment]
Thank you! I created the issue in the pharo-website repository:

https://github.com/pharo-project/pharo-website/issues/70

**Comment by MarcusDenker** [comment]
merged pr https://github.com/pharo-project/pharo-website/pull/71
