### ISSUE TITLE
Pharo 12 - 'file in'

### ISSUE THREAD

**Issue by arihd2024** [guillep/pharo-core#16545]
To save what I had done in Pharo 11, I did a ‘file out’ to a ‘*.st’ file. I had been under the impression there would be a ‘file in’ (or equivalent) in Pharo 12 but cannot locate such a command/mechanism. Is there one ? If so, where is it ?

**Comment by pavel-krivanek** [comment]
Related to: https://github.com/pharo-project/pharo/issues/15933

You may drag&drop your file on the Pharo window, select Changes browser from the menu that appears, do `select all` and then `file in selected`. But that is only a workaround, not intended usage.

**Comment by arihd2024** [comment]
Thank you very much Pavel. This worked just fine.

Is there a plan to re-implement ‘file in’ ?

 

Kind regards,

Aril Dyrseth

**Comment by Ducasse** [comment]
Normally with the file browser you can. At least I saw that we reintroduced it.

**Comment by MarcusDenker** [comment]
The PR was 

https://github.com/pharo-project/pharo/pull/16470

Very strange that it is gone again

**Comment by tinchodias** [comment]
After dropping a .st file and selecting "Code-file browser", I get "Instance of RGClassDefinition did not understand #protocolNames" (Pharo 12):
![CodeFileBrowserError](https://github.com/pharo-project/pharo/assets/3044265/e985690e-6859-4ae4-a025-4fa4fa8b6a6f)
I created the .st file in the same image in the context menu of the class in Calypso.
