### ISSUE TITLE
MockMessageSend is difficult to read in a test

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#16554]
**Describe the request**
The new'ish MockObjects implementation is a useful addition to the image however test failures are difficult to read - MockMessageSend should implement a better printOn: and a failed message should keep what what was sent so you can figure things out.
**Expected behavior**
Print the paramters of a message send

**Expected development cost**
small

**Screenshots**

**Version information:**
 - Version: [e.g. 1.6.1]
 - Pharo Version [e.g 9] 13

**Additional context**
Have a proposed fix and will submit a pr

**Comment by MarcusDenker** [comment]
Can this be closed after merging https://github.com/pharo-project/pharo/pull/16555 ?

**Comment by macta** [comment]
yes
