### ISSUE TITLE
Enhance inspection of negative numbers

### ISSUE THREAD

**Issue by tinchodias** [guillep/pharo-core#16564]
The inspector on `-5` is:
<img width="401" alt="Inspector for -5" src="https://github.com/pharo-project/pharo/assets/3044265/d2d4870b-1b15-470a-b0ec-8195b8ef9868">
While `-5 bitString` answers `'1111111111111111111111111111111111111111111111111111111111011'`, that is the two's complement representation. This String is built by sending `bitAt:` to the number, and I consider this would be a more informative string to see in the inspector.

With positive numbers, it's okay:
<img width="401" alt="Inspector for 5" src="https://github.com/pharo-project/pharo/assets/3044265/214f4aa1-c66c-4db4-86fc-fad5997e634e">
While `5 bitString` is `'0000000000000000000000000000000000000000000000000000000000101'` (okay).

**Expected behavior**
For the inspector, it could be better to show a string based on `bitAt:`, as in `bitString`, but probably without all left zeroes.

The same applies for the hex representation.

**Version information:**
- Pharo-12.0.0+SNAPSHOT.build.1474.sha.723e992378842828924aea037a6d2da975cd8da4 (64 Bit)
- MacOS 14.4.1

**Comment by pavel-krivanek** [comment]
![image](https://github.com/pharo-project/pharo/assets/572494/1d5cb95d-4fd5-4e31-a8e5-89859555ef7b)

**Comment by tinchodias** [comment]
Nice... It'd be enough to close the issue, but however I think we could remove the binary row... the minus at the beginning of "-101" is weird, isn't it?
I may be wrong!

**Comment by pavel-krivanek** [comment]
Why should it be weird? Two's complement is only an implementation hack, not a mathematical expression of the number in binary form. If -16rF is not weird, why should -2r1111 be? To show both is IMHO approriate.

**Comment by guillep** [comment]
That's a two's complement on 64bits :)
