### ISSUE TITLE
ProfStef 17/29 LessonView did not understand #hasBindingOf 

### ISSUE THREAD

**Issue by acheng-hm** [guillep/pharo-core#16577]
**Bug description**
`ProfStef next` works until 17/29

**To Reproduce**
1. Go through ProfStef until you're on 17/29
2. Put cursor after `ProfStef`
3. Start typing `next; next`
4. See error before you finish typing. `"Instance of LessonView did not understand #hasBindingOf:"`

![image](https://github.com/pharo-project/pharo/assets/76965663/a2536334-706e-4395-becf-21715c72acf0)

You can dismiss the error and type one more character, which triggers the error again. Do this enough times and you can get to 19/29. But the error continues to pop up at other times like when typing `ProfStef prev`

**Expected behavior**
no error, 19/29

**Screenshots**

**Version information:**
 - OS: MacOs M1
 - Version: Ventura 13.5.2 (22G91)
 - Pharo Version 12.0.0
 - Build information: Pharo-12.0.0+SNAPSHOT.build.1508.sha.c19563fd0cc2c2a33ae373aca3898f027eb357da (64 Bit)

**Expected development cost**
Would like to help but am new to Pharo.

**Additional context**

**Comment by Ducasse** [comment]
Super thanks for reporting the issue.
Thanks pavel for fixing it. 
I'm super proud of our community.
