### ISSUE TITLE
Problem with completion in the tutorial

### ISSUE THREAD

**Issue by jacereda** [guillep/pharo-core#16576]
**Bug description**
Text completion is broken in the tutorial.

**To Reproduce**
1. Open tutorial.
2. Type `ProfStef n`

**Expected behavior**
Text completion should work.

**Screenshots**
![image](https://github.com/pharo-project/pharo/assets/4195919/667720d2-62c1-4bce-b1a4-ec4d687d4f6e)
**Version information:**
 - OS: GNU Guix
 - Version: guix a1d711c
- Pharo Version 12

**Comment by jacereda** [comment]
Could well be a PEBKAC, should I be able to use the latest image with the latest pharo-vm release? (10.2.1, not yet released AFAICS)

**Comment by Ducasse** [comment]
Thanks for the report! We are sorry about it.
This is not a problem of the VM but just a regression in Pharo

**Comment by pavel-krivanek** [comment]
fix in  PR https://github.com/pharo-project/pharo/pull/16578

**Comment by MarcusDenker** [comment]
Pharo 13 is fix is megerd, we keep this issue open for the Pharo12 backpot

**Comment by MarcusDenker** [comment]
I merged the backport
