### ISSUE TITLE
`RBCompositeRefactoryChange>>#defineClass:` arguments seems incorrectly named

### ISSUE THREAD

**Issue by badetitou** [guillep/pharo-core#16592]
**Describe the problem**
When looking at `RBCompositeRefactoryChange>>#defineClass:`, the definition says it expects a String
https://github.com/pharo-project/pharo/blob/Pharo13/src/Refactoring-Changes/RBCompositeRefactoryChange.class.st#L143

However, when looking at associated tests, it always take a builder block.
https://github.com/pharo-project/pharo/blob/Pharo13/src/Refactoring-Changes-Tests/RBRefactoringChangeTest.class.st#L94
and
https://github.com/pharo-project/pharo/blob/Pharo13/src/Refactoring-Changes-Tests/RBRefactoringChangeTest.class.st#L94

**Classes involved**
- `RBCompositeRefactoryChange`

**Proposal**
Change the name of the variable in `RBCompositeRefactoryChange>>#defineClass:` for `aBuilder`

**Version information:**
 - Version Pharo 12.0 and Pharo 13.0

**Expected development cost**
Can be done super easily, even by new comers

In addition, are you willing to help because after all Pharo is yours too?
I will propose the fix if you agree with the issue (I'm not expert of this package, but assign me if you agree)

**Comment by jecisc** [comment]
Your proposition is good.

I updated RB to create class using a class builder instead of a string representing a definition during P12 but I might have miss some variable names to update

**Comment by Ducasse** [comment]
Tx for the report.
