### ISSUE TITLE
Create Milestone for P13 in GitHub issue tracker

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16609]
In the Pharo issue tracker on GitHub one can select a Milestone for 11.0.0. and 12.0.0 
but not yet one for 13.0.0

I tried to create it but it looks this is from permission side only able to owners.

Anyone able to create it?

@jecisc / @MarcusDenker / @estebanlm / @guillep / @Ducasse

**Comment by jecisc** [comment]
Usually we have a label and a milestone. But I have the impression that the milestone never was really used. 

Is there an upside to have it on top of the "Version: Pharo 13" label?

**Comment by astares** [comment]
There is no downside - but using labels is a little bit strange.

I would vote to **use the Milestone** now properly as this is a clear concept in software, also in Github as a structural element to manage a project and we now work on this next milestone P13.

https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones

<blockquote><img src="https://github.githubassets.com/images/modules/open_graph/github-logo.png" width="48" align="right"><div><img src="/assets/cb-345/images/site/favicon.png" height="14"> GitHub Docs</div><div><strong><a href="https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones">About milestones - GitHub Docs</a></strong></div><div>You can use milestones to track progress on groups of issues or pull requests in a repository.</div></blockquote>

**Comment by estebanlm** [comment]
there you have.
but as @jecisc said, it was never really useful :P
