### ISSUE TITLE
Cmd-v to see method version

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16694]
Hi,
If you too miss some shortcuts like... cmd-v to show the versions of a method, here is the solution, you have to add methodShortcutActivation to SycShowMethodVersionCommand class:

```
SycShowMethodVersionCommand class >> methodShortcutActivation
    <classAnnotation>
    ^ CmdShortcutActivation by: $v meta for: ClyMethod asCalypsoItemContext
```

**Comment by hernanmd** [comment]
Merged
