### ISSUE TITLE
Debugger window does not remember size and position

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16693]
When we have a halt, the debugger window reopened with the same size and position ignoring the changes the user may have done. 
Imagine a method with several halts.

And imagine that the user after the first halt and befopre proceeding to reach the second, move the debugger window to a better place and resize the window to be more confortable. 
Pressing proceeding will show debugger window to the old place with the old size. :(

**Comment by hernanmd** [comment]
In https://github.com/pharo-spec/NewTools/pull/795

**Comment by adri09070** [comment]
Should be closed via https://github.com/pharo-spec/NewTools/pull/795 (I can't close the issue)

**Comment by MarcusDenker** [comment]
I added you with triage rights to the project, this should allow you to close issues, add tags and to on
