### ISSUE TITLE
Cannot find expand class definition menu

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#16719]
I am working in Pharo 13 and I see no "expand" menu item when I right click on the class definition pane. And also if I press the shortcut cmd + e nothing happens.

Did we lose the expand command?

**Comment by Ducasse** [comment]
:(    again.

**Comment by guillep** [comment]
Hi @jecisc would you mind trying a couple of P13 versions? That could help identify the problematic build.

**Comment by Ducasse** [comment]
I get 

<img width="460" alt="Capture 2024-12-17 at 21 06 40" src="https://github.com/user-attachments/assets/cf9d1ab4-bf25-4b98-97bc-ed652b9d141c" />
