### ISSUE TITLE
Backport Pharo12: Wrong source for CompiledBlocks due to incorrect bytecode to AST nodes mapping #16495

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#16725]
We should backport this:

Wrong source for CompiledBlocks due to incorrect bytecode to AST nodes mapping #16495

**Comment by fedemennite** [comment]
If it isn't too challenging it would be nice to also have a backport fix on Pharo11.
We will eventually transition to Pharo12 but will take a little time.

**Comment by carolahp** [comment]
Backport to Pharo 12 was implemented in https://github.com/pharo-project/pharo/pull/16756
This issue does not exist in Pharo 11
