### ISSUE TITLE
The StRewriterRuleEditor helpfully shows sample rules, there is no way for projects to easily add their example rules

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#16753]
**Describe the request**
The StRewriterDemoRules class (which is badly named - and should be called StRewriterSampleRules or StRewriterTemplateRules) has a list of useful rules which are accessible from the Rewriter Rule Editor tool. However if you want to add your own rules to the list for people to use, there is no easy way to extend this without editing the class.

**Expected behavior**
Ypou should be able to add a rule extension method - and its a quick fix to make this tool use a pragma to fine such sample rules - I suggest <rewriterRule>

**Expected development cost**
trivial

**Screenshots**
<img width="1114" alt="image" src="https://github.com/pharo-project/pharo/assets/5553623/62716944-d162-4e67-9cc3-96c830c6517c">

**Version information:**
 - Version: [e.g. 1.6.1]
 - Pharo Version P13

**Additional context**
I have a proposed fix

**Comment by macta** [comment]
@jecisc where is the NewTools repo - as I've realised that this browser is in NewTools and don't know what repo to clone to propose a fix?

**Comment by jecisc** [comment]
Hi Tim, 
The NewTools repository is in the pharo-spec association. 

https://github.com/pharo-spec/NewTools

<blockquote><img src="https://opengraph.githubassets.com/8ab6a37c2d61b06cec2e92178867bd40ab7f2ddfb3e0f9e07ff3e2f09138eff6/pharo-spec/NewTools" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-spec/NewTools">GitHub - pharo-spec/NewTools: All development tools for Pharo, developed with Spec</a></strong></div><div>All development tools for Pharo, developed with Spec - pharo-spec/NewTools</div></blockquote>

**Comment by macta** [comment]
How would you feel about renaming StRewriterDemoRules to StRewriterTemplateRules, as they are more than demo rules, there are some great ones in there and potentially other libraries could add to them ? Could do it in the PR I plan to submit or propose a new one.

**Comment by macta** [comment]
Not quite sure how PR's for that other repo are handled - but the PR has been submitted over there in https://github.com/pharo-spec/NewTools/pull/770

**Comment by macta** [comment]
Do I need to create a seperate issue in that Repo?

**Comment by jordanmontt** [comment]
Solved in https://github.com/pharo-spec/NewTools/pull/770
