### ISSUE TITLE
New finder example mode time out too easily

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#16759]
I tried to use a few time the new finder example mode but in the end I always got a time out and no result. 

This was not happening with the old finder. Because of this, it is unusable for me.

I don't know why this is different. I even tried to put the time out from 5sec to 50sec and I still have time outs.

**Comment by jecisc** [comment]
Here is an example of text I tried:

```
#(1 2 3 4) . #(2 4) . #(1 3) 
```

In the old finder I have results in less than a second. With the new one I timeout even after a minute with 0 result

**Comment by hernanmd** [comment]
I will have a look tomorrow. The key method here is:

```smalltalk
evaluateWithTimeOut: anInteger 

	| runner result |

	runner := TKTLocalProcessTaskRunner new.
	runner 
		schedule: [ result := [ self evaluate ] onErrorDo: [ : e | self handleError: e ] ] asTask
		timeout: anInteger milliSeconds.
	^ result
```
