### ISSUE TITLE
Cannot set breakpoint in class side methods

### ISSUE THREAD

**Issue by aiksiongkoh** [guillep/pharo-core#16757]
Pharo12. Does breakpoint work in class methods? For example: Object class>>newFrom: will not take a breakpoint.

**Comment by MarcusDenker** [comment]
This PR should have fixed it:

https://github.com/pharo-project/pharo/pull/16734

**Comment by aiksiongkoh** [comment]
When will it show up in stable form? Will Pharo 12 get a maintenance release?

**Comment by Ducasse** [comment]
Our stable release have always maintenance release. Now it takes us time to do so.

**Comment by aiksiongkoh** [comment]
In Pharo Launcher, I see "Pharo 12.0 - 64bit (stable)". Do you mean that selection will use the latest Pharo 12 maintenance release and not the first release?

**Comment by MarcusDenker** [comment]
All fixes we backport are directly in the 12.0 release branch as long as these are just fixes
