### ISSUE TITLE
Finder with strange example output

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16762]
I enter the example 

```Smalltalk
'true' . true
```

and run examples:

![image](https://github.com/pharo-project/pharo/assets/5980033/9d1c4fe6-81ad-4f6a-bfc4-a680bca06ca2)

the output shows something about **ture** and not **true**

**Comment by astares** [comment]
Same for 

![image](https://github.com/pharo-project/pharo/assets/5980033/8709bd75-3da1-4695-96e6-eb776ac992e8)

**Comment by AlexisCnockaert** [comment]
the receiver (true or false here) changes when the selector is "sort" in the ```MethodFinder``` class in ```findMethodsByExampleInput: andExpectedResult:``` method but idk how the receiver is changed

**Comment by Ducasse** [comment]
We have a new implementation so I close this one.
