### ISSUE TITLE
StPlaygroundPresenter does not open playground/workspace

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#16778]
- use latest Pharo 13 image and open a playground from world menu. This fails with a DNU

Reason is the implementation of StPlaygroundPresenter class>>#menuCommandOn: which need to be implemented like:

 
![Screenshot from 2024-06-16 21 33 28](https://github.com/pharo-project/pharo/assets/5980033/8a848004-9589-4c78-b5a3-314d52391f5d)

**Comment by hernanmd** [comment]
In my case, it also hangs the image.
A PR is pending in https://github.com/pharo-spec/NewTools/pull/787

**Comment by MarcusDenker** [comment]
fix merged

**Comment by astares** [comment]
Works. 

@hernanmd thanks for creating the PR
