### ISSUE TITLE
Randomgenerator broken 

### ISSUE THREAD

**Issue by jbrichau** [guillep/pharo-core#16775]
**Bug description**
On Pharo 12, since a couple of days, the random generator is broken.
`Random new next` always produces the **same value**.

This breaks Seaside, who is using the random generator to produce session keys and now all session and continuation keys are `aaaaaaaaaaaaa`.

Edit: this is a VM issue
It works well with VM Pharo 10.2.1-aeba90c8 built on May 16 2024 15:53:24
But it fails starting with VM Pharo 10.2.1-49e95fa7 built on Jun  4 2024 15:16:03 

**To Reproduce**
Execute the following snippet in Pharo 11 and Pharo 12. 
In Pharo 12, the entire collection will have only the value `1` (WRONG).
In Pharo 11, you will get a collection with `1`,`2` and`3` (CORRECT).

```Smalltalk
| random collection |
random := Random new.
collection := (1 to: 200) collect: [ :e | random nextInteger: 3 ].
collection asSet 
```

**Expected behavior**
See above.

**Version information:**
 - OS: [Mac] (but also Linux on the Seaside CI)
 - Pharo Version 12
 - Build information: Pharo-12.0.0+SNAPSHOT.build.1514.sha.3eb8aad6ce720672fe608e9f64aec10e20d577bb

**Comment by jbrichau** [comment]
Unfortunately, I cannot pinpoint the change that lead to this bug. I just know that the CI for Seaside was running fine on June 12th at 10:52 CET: https://github.com/SeasideSt/Seaside/actions/runs/9479579484/job/26118415881 
First CI build that started breaking with this failure was on June 14th 21:54 CET: https://github.com/SeasideSt/Seaside/actions/runs/9519973481/job/26248806073

<blockquote><img src="https://opengraph.githubassets.com/ae139b95a3782de558e00716e9126c0b52b6466b35df4471f54bb5ae36d200eb/SeasideSt/Seaside" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/SeasideSt/Seaside">Merge pull request #1415 from SeasideSt/devwork · SeasideSt/Seaside@3074c69</a></strong></div><div>The framework for developing sophisticated web applications in Smalltalk. - Merge pull request #1415 from SeasideSt/devwork · SeasideSt/Seaside@3074c69</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/ae139b95a3782de558e00716e9126c0b52b6466b35df4471f54bb5ae36d200eb/SeasideSt/Seaside" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/SeasideSt/Seaside">add a JSON API example · SeasideSt/Seaside@8a3f08c</a></strong></div><div>The framework for developing sophisticated web applications in Smalltalk. - add a JSON API example · SeasideSt/Seaside@8a3f08c</div></blockquote>

**Comment by jbrichau** [comment]
It seems this is a VM issue. 

It works well with VM `Pharo 10.2.1-aeba90c8 built on May 16 2024 15:53:24`
But it fails starting with VM `Pharo 10.2.1-49e95fa7 built on Jun  4 2024 15:16:03 `

**Comment by guillep** [comment]
I tracked the issue to primitive 231.
Primitive 231 was never implemented on the VM, or at least not since a Loooong time.
[See https://github.com/pharo-project/pharo-vm/compare/v10.0.5...v10.2.1](https://github.com/pharo-project/pharo-vm/compare/v10.0.5...v10.2.1#diff-715172f5f9bc44477ac2dc857665367d6e38210cc77747ad5ea4da441814ca4aL1259)

```smalltalk
(231 239 primitiveFail)
```

And recently it got defined to provide an object's format:

```smalltalk
(231 primitiveFormat)
```

However, it is used in the `Random` class, probably a leftover of some prototype.

```smalltalk
"On Pharo"
Random class >> primitiveRandomNumber: stateArray
	"Answer a random Float in the interval [0 to 1)."

	<primitive: 231>
```

I'll propose a PR, just removing the primitive tag in `primitiveRandomNumber:` should be enough to get back the old behavior. We should also back port it to P12.
