### ISSUE TITLE
DarkBlueTheme: Improve contrast of combo box

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16813]
<img width="543" alt="Capture 2024-06-28 at 10 03 16" src="https://github.com/pharo-project/pharo/assets/432549/3053bc24-ddae-40e0-8bd7-6ef718ca4d7c">

**Comment by AlexisCnockaert** [comment]
I can change theme personally

**Comment by jecisc** [comment]
The theme can be changed but the display of the combo box is hard to distinguish with the current colors of the theme

**Comment by Ducasse** [comment]
Tx I was checking to close it and indeed I could not see it the combobox:)
