### ISSUE TITLE
debugger nicer setter and getter add method

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16836]
Right now when I define a setter I have to press + 
then the debugger shows me 

```
id: aString
   self shouldBeImplemented
```

and I have to type

```
id: aString
   id := aString
```

When we know that we want to define a setter, I would love to press + setter
and get directly

```
id: aString
   id := aString
```

**Comment by StevenCostiou** [comment]
This works for me... do you still have this problem?
And the code for that seems to not have changed in 5 years.

![Capture d’écran 2024-09-20 à 09 50 01](https://github.com/user-attachments/assets/e01e61bc-cd5d-46f5-b1fb-8542badb96a3)

Perhaps you found a bug?

What I did:
- create a class with a variable test
- executes `theclass new test: 'blabla'`
- debugger opens on DNU, I click the `+` button and it generates the setter automatically

**Comment by Ducasse** [comment]
I do not remember why it did not work for me so I will close the issue.
