### ISSUE TITLE
REMOVE THE WINDOWS SLAVE FROM THE CI

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16842]
We must disable the window slave. 
It is useless to have something that does nothing and say that everything is working. 
We should grow up. 

Then why do we change all the time the labels of the issue. 
To me this is a showstopper.
I cannot work when I have to remember bullshit.

**Comment by astares** [comment]
Yes, lets ignore the most prominent OS used in business setups and keep pharo an experiment for apple only

**Comment by Rinzwind** [comment]
Related: issue #15105 (“[CI] Windows CI run sometimes is green but did not run”).

**Comment by astares** [comment]
Anything one can do from the outside to support on this issue? Is there any description of the CI setup so that it is possible to try to verify issues caused?

**Comment by Ducasse** [comment]
No.

Now keeping a CI that does not do anything and mention in permanence that everything is ok and that all the tests are ok is not a good practice. 

- The first step is remove the CI job 
- The second step is fix the CI and reenable it.

**Comment by guillep** [comment]
Fixed, solution is in https://github.com/pharo-project/pharo/pull/16845
