### ISSUE TITLE
Pharo13: DNU when opening Browser "Metaclass does not understand #over"

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#16847]
**Bug description**
In Pharo13, we can not open a code browser anymore: 
"Metaclass does not understand #over"

**Comment by guillep** [comment]
I think we should identify the broken PR and revert it

**Comment by guillep** [comment]
A quick binary search: the build introducing the issue is build 111

**Comment by guillep** [comment]
Broken Commit is 09c1dc0d860c38406b86449cf1c06b054c7c8071

The related PR is https://github.com/search?q=repo%3Apharo-project%2Fpharo+09c1dc0d860c38406b86449cf1c06b054c7c8071&type=pullrequests

**Comment by Ducasse** [comment]
Yesterday I found the same problem but I could not find the PR. 
You should show me your process. 
My problem was that I could not rerun the tests after the Zip fix.
