### ISSUE TITLE
[CI] RBCopy broken tests

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16850]
Hi hernan can you have a look at the following tests:

```
Unix64.Refactoring.Transformations.Tests.RBCopyPackageParametrizedTest.testCopyPackageAndChangesCopyReferences(#rbClass->RBCopyPackageRefactoring)
 Unix64.Refactoring.Transformations.Tests.RBCopyPackageParametrizedTest.testCopyPackageWithParameters(#rbClass->RBCopyPackageRefactoring)

 Unix64.Refactoring.UI.Tests.ReDuplicateClassDriverTest.testDuplicateClass
```

**Comment by MarcusDenker** [comment]
The revert would fix them: https://github.com/pharo-project/pharo/pull/16849

**Comment by MarcusDenker** [comment]
I merged the revert, we need to get the tests green and there are more failing tests due to PRs that we can not even revert anymore as they are from 2 weeks ago. Reverting this means we can focus on those.

**Comment by hernanmd** [comment]
> I merged the revert, we need to get the tests green and there are more failing tests due to PRs that we can not even revert anymore as they are from 2 weeks ago. Reverting this means we can focus on those.

I was working on this issue but didn't know it was so urgent. I just pushed a PR with the fix in #16853

**Comment by MarcusDenker** [comment]
So now we have a conflict.

**Comment by hernanmd** [comment]
> So now we have a conflict.

Yes, now it seems I had to manually resolve the conflict :(
