### ISSUE TITLE
.NoUnusedVariablesLeftTest.testNoUnusedInstanceVariablesLeft OupsDummyDebuggerSystem

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16869]
TestFailure
the following classes have unused instance variables and should be cleaned: an OrderedCollection(OupsDummyDebuggerSystem)
NoUnusedVariablesLeftTest(TestAsserter)>>assert:description:resumable:
NoUnusedVariablesLeftTest(TestAsserter)>>assert:description:
NoUnusedVariablesLeftTest>>testNoUnusedInstanceVariablesLeft
NoUnusedVariablesLeftTest(TestCase)>>performTest

**Comment by MarcusDenker** [comment]
fixed
