### ISSUE TITLE
Code in Documentation Browser is unreadable after switching to ‘Pharo Light’ theme

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#16876]
I created a new Pharo 13 image, changed the theme from ‘DarkBlue’ to ‘Pharo Light’, then opened the Documentation Browser and selected the page ‘WorldMenuItems.md’ in the section ‘BoltsAndNuts’, part of the code for ‘Adding a menu item’ is unreadable:

<p align="center">
<img width="750" src="https://github.com/pharo-project/pharo/assets/1611248/08d010f9-d9f3-4d8d-8936-acbfcd3b4def">
</p>

Version used: Pharo 13 build 122.

**Comment by Rinzwind** [comment]
As a side note, the title of the section is a bit odd as it inverts the idiomatic order [‘nuts and bolts’](https://en.wiktionary.org/wiki/nuts_and_bolts).

**Comment by Ducasse** [comment]
I imagine that we should have a specific color theme for the text
