### ISSUE TITLE
Compiler error on Pharo 13 startup with fresh image

### ISSUE THREAD

**Issue by asampal** [guillep/pharo-core#16881]
**Bug description**
On starting a fresh (unmodified/not previously saved) Pharo 13, debugger opens with the following error:

```
CodeError:OCUndeclaredVariableNotice UndefinedObject>>DoIt118:Undeclared variable->RPackage
```

**To Reproduce**
1. From Pharo Launcher, start Pharo 13 - 64 bit (development version, latest) 
2. See debugger

**Expected behavior**
No debugger should open on startup

**Screenshots**
![image](https://github.com/pharo-project/pharo/assets/281639/8c5a7c6d-c542-4fea-b568-8e25e1e2fb22)

**Version information:**
 - OS: Windows 11 Pro
 - Version: 10.0.22631 Build 22631
 - Pharo-13.0.0+SNAPSHOT.build.123.sha.42ef1f8cdb76618dc19d5e734ea86f2419cda575 (64 Bit)

**Comment by Ducasse** [comment]
Thanks for reporting this problem!

**Comment by MarcusDenker** [comment]
This seems to be related to loaded existing stored Startup scripts from disk that reference a class that has been renamed (RPackage to Package)

**Comment by asampal** [comment]
> This seems to be related to loaded existing stored Startup scripts from disk that reference a class that has been renamed (RPackage to Package)

Thanks for the heads up, @MarcusDenker - closing.
