### ISSUE TITLE
Deprecation >> #messageText results in MNU 

### ISSUE THREAD

**Issue by marschall** [guillep/pharo-core#16897]
**Bug description**

`Deprecation >> #messageText` sometimes results in a MNU because `contextOfSender` answers `nil` so `Deprecation >> #sendingMethodName` ends up sending `#homeMethod` to `nil`.

**To Reproduce**

```st
testPharoBug
	| notification |
	notification := [ self deprecated: 'test']
			on: Deprecation
			do: [ :d | d ].
	self assert: notification messageText notNil
```

**Expected behavior**

`Deprecation >> #messageText` answers a string.

**Stacktrace**

```
UndefinedObject(Object)>>doesNotUnderstand: #homeMethod
Deprecation>>sendingMethodName
[ :str |
		self shouldTransform ifTrue: [
			str nextPutAll:  'Automatic deprecation code rewrite: '].
		str
			nextPutAll: 'The method ';
			nextPutAll: self deprecatedMethodName;
			nextPutAll: ' called from ';
			nextPutAll: self sendingMethodName;
			nextPutAll: ' has been deprecated. ';
		 	nextPutAll: explanationString] in Deprecation>>messageText in Block: [ :str |...
String class(SequenceableCollection class)>>new:streamContents:
String class(SequenceableCollection class)>>streamContents:
Deprecation>>messageText
GRPharoPlatformTest>>testPharoBug
```

**Version information:**
 - OS: macOS
 - Version: 14.5
 - Pharo Version 12

**Expected development cost**

???

**Additional context**

Seaside collects all the deprecation notifications during request processing so they can later be displayed on demand. Right now Seaside does this only for the Seaside deprecation mechanism. This was discovered when also supporting the Pharo deprecation mechanism.

**Comment by Ducasse** [comment]
Thanks Philip.
