### ISSUE TITLE
Test about unimplemented selectors does not take #super into account

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#16905]
In Pharo we have a test checking that we do not call selectors in Pharo that have no implementors. 

But this one seems to miss cases where those selectors are sent to #super instead of #self.

Check: DiskDirectoryEntry class>>#store:path:node:

**Comment by astares** [comment]
![image](https://github.com/user-attachments/assets/20b58af8-ee16-45b6-b8fb-842589a65fc7)

**Comment by Inao0** [comment]
DiskDirectoryEntry class>>#store:path:node: is in the knownFailures of the testThatThereAreNoSelectorsRemainingThatAreSentButNotImplemented test. This is why it is not detected by release tests.
