### ISSUE TITLE
[CI] testUndeclared is failing

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#16910]
**Bug description**
Some PR was merged that leads to testUndeclared failing

```
```
Found undeclared Variables:  StClassCritiqueRuleSelectorPresenter in: StClassCritiqueBrowserPresenter class>>#openOnCurrentWorkingConfiguration
```

**Comment by MarcusDenker** [comment]
I did this PR: https://github.com/pharo-spec/NewTools/pull/799

**Comment by jecisc** [comment]
Merged
