### ISSUE TITLE
ReferenceFinder should not look at ephemeron references

### ISSUE THREAD

**Issue by j-brant** [guillep/pharo-core#16923]
**Bug description**
The ReferenceFinder searches for strong references to an object. It doesn't go through weak references and shouldn't go through ephemeron references either.

**To Reproduce**
This code shouldn't return any reference path: 

```
| obj dict |
obj := Object new.
dict := WeakKeyDictionary new.
dict at: obj put: 1.
ReferenceFinder findPathTo: obj from: dict
```

**Version information:**
 - Pharo Version: all with ephemeron support

**Expected development cost**

Here's a change that skips the initial ephemeron slot:

```
ReferenceFinder>>searchVariablesIn: anObject
	| class |
	class := self _objectClass: anObject.
	(class isEphemeronClass ifTrue: [ 2 ] ifFalse: [ 1 ])
		to: class instSize
		do: [ :i | 
			| path |
			path := self
					processLinkTo: (self _object: anObject instVarAt: i)
					from: anObject.
			path notNil ifTrue: [ ^ path ] ].
	^ nil
```

**Comment by Ducasse** [comment]
Tx john. 
We should turn this example in a test.
