### ISSUE TITLE
Enhance Bug Report template with links to specific repositories

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#16922]
I've seen many of the issues reported in this repository belong to other repositories. I would like to propose a new default template for the bug report template:

```
Thanks for taking the time to fill out this bug report 🤗
Please make sure there aren't any open/closed issues for this topic 😃

**Is this the right place to report this issue?**

Please note that projects have their own repositories and issue trackers:

Pharo Launcher -> https://github.com/pharo-project/pharo-launcher
Virtual Machine -> https://github.com/pharo-project/pharo-vm
Spec -> https://github.com/pharo-spec/Spec
GTK -> https://github.com/pharo-spec/Spec-Gtk and https://github.com/pharo-spec/gtk-bindings
NewTools (Debugger, Playground, CodeCritiques, Spotter, New File Browser, New Finder, New Settings Browser) -> https://github.com/pharo-spec/NewTools
Roassal -> https://github.com/ObjectProfile/Roassal3

**Bug description**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version information:**
 - OS: [e.g. iOS]
 - Version: [e.g. 1.6.1]
 - Pharo Version [e.g 9]

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 
In addition, are you willing to help because after all Pharo is yours too?

**Additional context**
Add any other context about the problem here.
```

**Comment by Ducasse** [comment]
Yes good idea.

**Comment by hernanmd** [comment]
I don't have permission to edit but maybe @jecisc or @MarcusDenker ?

**Comment by MarcusDenker** [comment]
You can just do a PR for https://github.com/pharo-project/pharo/tree/Pharo13/.github/ISSUE_TEMPLATE or not?

<blockquote><img src="https://repository-images.githubusercontent.com/64123480/451beb80-d08b-11e9-9ade-21d166d787d9" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo/tree/Pharo13/.github/ISSUE_TEMPLATE">pharo/.github/ISSUE_TEMPLATE at Pharo13 · pharo-project/pharo</a></strong></div><div>Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk. - pharo-project/pharo</div></blockquote>

**Comment by hernanmd** [comment]
> You can just do a PR for https://github.com/pharo-project/pharo/tree/Pharo13/.github/ISSUE_TEMPLATE or not?
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/64123480/451beb80-d08b-11e9-9ade-21d166d787d9"><img alt="" height="14" src="https://camo.githubusercontent.com/95e35b1ddbd18e9680ef4876f3544fdf46e2116b5fefc3f6a48e1e427ea75b59/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[pharo/.github/ISSUE_TEMPLATE at Pharo13 · pharo-project/pharo](https://github.com/pharo-project/pharo/tree/Pharo13/.github/ISSUE_TEMPLATE)**Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk. - pharo-project/pharo

Thanks, I thought a GitHub setting was available for it.
Now in #16959.



<blockquote><img src="https://repository-images.githubusercontent.com/64123480/451beb80-d08b-11e9-9ade-21d166d787d9" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo/tree/Pharo13/.github/ISSUE_TEMPLATE">pharo/.github/ISSUE_TEMPLATE at Pharo13 · pharo-project/pharo</a></strong></div><div>Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk. - pharo-project/pharo</div></blockquote>
