### ISSUE TITLE
[RB] Refactorings add argument: fails on unary messages

### ISSUE THREAD

**Issue by skycluster** [guillep/pharo-core#16945]
**Bug description**
When applying "add argument" to a unary message there is no way to finish the process due to scopes not properly working. The process itself is not straightforward nor is it self-explaining.

**To Reproduce**
1. Create scope from a package.
2. Apply the scope on the system browser or select scoped view.
3. Select the unary message to be refactored.
4. Select from a menu: refactorings -> Add argument.
5. In the opened window press "+".
6. Enter the new name for the message.
7. Enter the argument name to pass.
8. Remove the excessive old string from selector name.
9. Press rename.
10. (in case the hierarchy has the message already - the process fails at this point).
11. The refactoring changes selection window opens - full scope applied.
12. When trying to change the scope by selection the drop-down list in the window - the process fails with an error.

**Expected behavior**
The refactoring finishes successfully and it is possible to apply the scopes to choose classes to apply the refactoring to.

**Screenshots**
<img width="400" alt="Screenshot 2024-07-23 at 22 05 27" src="https://github.com/user-attachments/assets/1045f765-cfec-4870-b290-12bc0dcd8263">
<img width="647" alt="Screenshot 2024-07-23 at 00 05 19" src="https://github.com/user-attachments/assets/4f329b30-172e-45b2-ae0d-14af3bb5a143">
<img width="601" alt="Screenshot 2024-07-23 at 00 31 38" src="https://github.com/user-attachments/assets/fbcad16c-cb1d-40f7-b4c7-7f83b7300001">
<img width="599" alt="Screenshot 2024-07-23 at 13 31 46" src="https://github.com/user-attachments/assets/6f122c4a-1bb5-4079-b09f-d008c13fdf23">
<img width="599" alt="Screenshot 2024-07-23 at 13 31 55" src="https://github.com/user-attachments/assets/dc7548a0-5331-45e2-85d6-d19739896ab3">
<img width="484" alt="Screenshot 2024-07-23 at 13 32 03" src="https://github.com/user-attachments/assets/b5554a9a-7d20-48a1-9c35-8d7440abfec7">
<img width="502" alt="Screenshot 2024-07-23 at 13 39 01" src="https://github.com/user-attachments/assets/24ff35ab-28f6-43fb-a0f8-91814798cdf6">
<img width="501" alt="Screenshot 2024-07-23 at 13 39 35" src="https://github.com/user-attachments/assets/9ef061d6-8cde-4b00-a338-2813364fb6f1">
<img width="756" alt="Screenshot 2024-07-23 at 13 40 04" src="https://github.com/user-attachments/assets/b0157589-4027-47a8-9a85-c9ff1a8b8049">

**Version information:**
 - OS: macOS Sonoma 14.5
 - Pharo 12.0 (stable), also reproducible in Pharo 13.0 (dev version)

**Expected development cost**
No idea. 
- Seems like some intermediate logic fails to copy the initial state of the refactored part of the system but expects it and fails to find it later on. 
- Also possible that once the scope browser is properly integrated in the refactoring process - the result could be obtained quicker to solve this issue.

**Additional context**
This feature is addressed in the "Advanced object oriented design and development with Pharo" course.
This refactoring works in Pharo 11.0 (stable).

**Comment by Ducasse** [comment]
THANK  YOU for this great bug issue.

**Comment by Ducasse** [comment]
@carolahp Hi caro I do not know if you have cycles right now but this is a nice bug to fix.

**Comment by carolahp** [comment]
Hi @Ducasse , I will give it a look now
