### ISSUE TITLE
deprecated:transform transformed users are not logged in epicea

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16963]
- define a unary method 
- add a user
- deprecate it

```
fooghf
self 
		deprecated: 'use fromFileFullName' 
		transformWith: '`@rec fooghf' ->  '`@rec bar'.
```

- Execute the user code
- open Epicea 
- the changed user code is not listed there.

**Comment by Ducasse** [comment]
Annoying when we want to revert a deprecation.

**Comment by hernanmd** [comment]
Hi Stef. I wonder if I've got this issue right.
This is what I have after your steps:

![Screenshot 2024-07-30 at 13 53 39](https://github.com/user-attachments/assets/142cfcbc-3f24-43c1-9748-0aaae5fc64db)

**Comment by Ducasse** [comment]
Thanks a lot for checking. So this is good that this is working for you. If this happens to me again I will check if I can reproduce it.
