### ISSUE TITLE
V12 , V13 , iceberg ,  in accept,  (model getConfigurationGlobal: self isGlobal) sent to nil (the current value of model)

### ISSUE THREAD

**Issue by Orfraie** [guillep/pharo-core#16979]
**Bug description**
Debian 11,  pharo V12 and V13, impossible to fill up User.name / User.email in iceberg menu named  "Please provide  Git missing properties"

**To Reproduce**
1. Install a fully new image V12 or V13 (note that V11 and below is working fine), i done it with zeroConf.
2. Goto Iceberg / Repositories / Settings / Credentials / Edit / +Token and create a new one with a valid token got from GitHub, do a Store Settings and close the Settings browser.
3. Do a +Add, choose "clone from github.com" , choose a valid Owner, a valid ProjectName as one of your repositories, leave the local directory as is, select HTTPS as your protocol and let iceberg getting back your repository.
4. Choose any package , +load, change any method you want ( modify  a comment is adequat ) , your status  becomes "uncommitted changes",  select and commit the package => you get usual menus until the menu named  "Please provide  Git missing properties"
5. Fill up the 2 fields (with anything you want) and you are into the debugger !
6. Just to see better what's happening, i put a breakpoint in accept and take the screen shot below.
7. That's seems to be an init PB in setModelBeforeInitialization: coming for an incorrect setup of model content. I also saw that the code has been modified between V11 (working) and V12 or V13 (Not working)
![image](https://github.com/user-attachments/assets/7bd30e0e-3a85-412b-9177-e91a33c9d44e)

 I done my best on this first issue commit , i hope to be enought completed and to do not make a stupid error.

**Comment by Ducasse** [comment]
Thanks for your report. 
The current fix is to initialize the author via the command line

**Comment by Ducasse** [comment]
Here is the issue in iceberg https://github.com/pharo-vcs/iceberg/issues/1828

**Comment by Orfraie** [comment]
The workaround perfectly works , thanks, i suggest to close this issue keeping
 #1828 opened, BR.

**Comment by Ducasse** [comment]
Ok good idea. I let it so that you get the info.
