### ISSUE TITLE
Enhancement request - Process Browser Full Stack option should be default

### ISSUE THREAD

**Issue by ericwinger** [guillep/pharo-core#16974]
**Bug description**
The process browser should, in my opinion, show the entire stack when a process is selected. I can't see any reason why it's necessary to not show the Full Stack automatically when selecting a process, nor can I determine what criteria is used to determining where to truncate a stack. I don't think, with modern hardware, there is any savings to not showing a big stack. 

To make matters worse, if you click away from a process and back, you have to hit Full Stack again. 

**To Reproduce**
1. Open a Process Browser
2. Select a stack
3. See partial stack only. (better to see full stack)

**Expected behavior**
Full Stack menu option shouldn't be needed if it's shown every time. 

**Screenshots**
![image](https://github.com/user-attachments/assets/0c5846c4-5366-4314-9064-64b4a12599b6)

**Version information:**
Pharo 12.0.0
Build information: Pharo-12.0.0+SNAPSHOT.build.1523.sha.3fd20c14be4ec63710f40bb8eb486e1eaf262af2 (64 Bit)

**Expected development cost**
minimal

**Additional context**

**Comment by Ducasse** [comment]
Thanks for your issue. 
The process browser is a super old tool that we should rewrite. Just did not have the time to proceed.
