### ISSUE TITLE
Allow to browse a method when selection is selector

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#16992]
**Describe the request**
When doing a browse (CMD+B or CTRL+B) on a class, it will open a browser on a class.
Browsing an expression will evaluate it and browse the class of the result of the evaluation.
Browsing a selector (e.g. selectAll) will browse `UndefinedObject`...

@Ducasse proposes to browse implementors of this selector instead of browsing `UndefinedObject`

**Comment by demarey** [comment]
depends on https://github.com/pharo-spec/Spec/issues/1583

**Comment by hernanmd** [comment]
Can we close this issue now?
