### ISSUE TITLE
[RB] Duplicate class opens a debugger while the new class is browsed

### ISSUE THREAD

**Issue by anneetien** [guillep/pharo-core#17021]
**Bug description**
Duplicate class opens a debugger while the new class is browsed

**To Reproduce**
1. Open a new P13 image
2. Open a System Browser
3. Duplicate a class (using the right click option)
4. Let all the methods selected
5. Accept to browse the new class (in fact accept everything that is proposed)

**Expected behavior**

**Screenshots**
<img width="849" alt="image" src="https://github.com/user-attachments/assets/dc859f2e-6e9e-43ab-9a9b-9eb4f9d903b5">

**Version information:**
 - OS: MacOS
 - Version: 14.6.1
 - Pharo Version 13

**Expected development cost**

**Additional context**

**Comment by hernanmd** [comment]
Beware that for some reason the newly created class is not present in the newClasses instance variable.

<img width="824" alt="Screenshot 2024-08-22 at 12 26 13" src="https://github.com/user-attachments/assets/82d6ee2e-ba2b-41d4-aa45-647e8e232e70">

**Comment by hernanmd** [comment]
In #17085
