### ISSUE TITLE
[Web] Github account report P11 as latest while we are at P12

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#17020]
![Capture 2024-08-20 at 21 53 38](https://github.com/user-attachments/assets/fbc5fc18-1d75-4f79-81a0-ed7598d050ad)

**Comment by astares** [comment]
I see **tags** https://github.com/pharo-project/pharo/tags
and also **releases** with Pharo 12 on https://github.com/pharo-project/pharo/releases

![image](https://github.com/user-attachments/assets/1179397a-6cd7-4afc-bffa-f6c9a5c1c84c)

![image](https://github.com/user-attachments/assets/3911b5e2-0cf0-470a-ab6d-85027bab0705)

**Comment by astares** [comment]
@Ducasse So to me this looks correct. Can we close?

**Comment by jecisc** [comment]
P12 was only made as a "tag" and not a "release" but this should be enough I think

**Comment by jecisc** [comment]
In fact there was a release but not tagged as "Latest" and I just did it. 

![image](https://github.com/user-attachments/assets/072606a2-0932-4eb2-8028-54d880808283)
