### ISSUE TITLE
Microdown presenter show parts of the URL for some images when having an _ in URL

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#17023]
If you use Microdown in comments it is possible also to reference images:

```
This should display a docker image from wikipedia:

![Docker](https://upload.wikimedia.org/wikipedia/commons/7/79/Docker_%28container_engine%29_logo.png)
``` 

but for this particular URL Pharo shows unfortunately also a part of the URL additionally to the picture:

![Screenshot from 2024-08-22 17-33-25](https://github.com/user-attachments/assets/fff326dd-3e62-4258-9abf-492632e013d3)

**Comment by astares** [comment]
I think the reason is that the URL contains an "underline" which is for Pharo also a separator similar to a space. As you see the URL is sliced/splitted directly after the "underline".

Maybe the Microdown parser has a bug and there is a check for separators (instead of a space) to find the end of the URL.
As according to the syntax description one could also write use:

```
![Pharologo](https://files.pharo.org/media/logo/logo.png size=80&anchor=figLogo.)
```

**Comment by Ducasse** [comment]
In recent Microdown we can now write

```
![Pharologo. % size=80&anchor=figLogo](https://files.pharo.org/media/logo/logo.png)
```

**Comment by Ducasse** [comment]
This way it does not break the file rendering on VScode or Github.

**Comment by Ducasse** [comment]
The problem with the underline in file filename is fixed in recent version.

**Comment by astares** [comment]
@Ducasse Great - thanks! We close the issue once it is part of standard image.

**Comment by Ducasse** [comment]
Normally this is fixed.

**Comment by astares** [comment]
@Ducasse Thanks - can confirm that it is working in latest Pharo 13.

BTW: Found another (new) problem with URLs in Microdown: https://github.com/pharo-project/pharo/issues/17534
