### ISSUE TITLE
[Papercut] Rename method dialog should focus the first field by default

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#17030]
When doing a rename method refactoring, nothing has the focus initially. 

When we do it we want to rename the method so we should select the first input field by default.

**Comment by hernanmd** [comment]
Hi Cyril,
I tried to reproduce it, but here the focus is on the method name presenter. Is this what you mean?

https://github.com/user-attachments/assets/b24b7b6d-badd-45f9-9da0-d3ea051cbd8f

**Comment by Ducasse** [comment]
Thanks hernan. I think that we were on pharo 12. So this is good to see pharo 13 being better there.

**Comment by jecisc** [comment]
Thanks Hernan, it was indeed in P12
