### ISSUE TITLE
Enhance Iceberg by sorting the project list by alphabetical order by default

### ISSUE THREAD

**Issue by anneetien** [guillep/pharo-core#17043]
**Describe the request**
In the Iceberg Browser, the list of projects is not ordered by default

**Expected behavior**
It would be great that the projects are listed by alphabetical order by default.

**Expected development cost**
It should not be too long while we know when the list is generated

**Screenshots**
<img width="600" alt="image" src="https://github.com/user-attachments/assets/830fb8e3-2dcb-4e70-a59f-d57a3c30e9dd">
Please see in Moose how it appears. Obviously it can't appear in a new Pharo image since there is no project already loaded. In Moose, by default there are a lot and looking for the one we need to clone.

**Version information:**
 - OS: iOS
 - Version: 1.6.1
 - Pharo Version Pharo 13

**Comment by jecisc** [comment]
I prefer to have the list by the order where I add the projects personally :(

But I would definitely love to be able to sort the columns in Iceberg! I opened an issue about it not long ago in the Iceberg repository. I'm just not sure about the default value of the sorting

**Comment by jecisc** [comment]
Maybe in Moose we could execute this in the post load to order repositories by name:

```st
IceRepository registry sort: #name ascending
```

@ClotildeToullec
