### ISSUE TITLE
ASTLiteralValueNode>>sourceText leads to infinite recursion when value is a BreakDebugPoint

### ISSUE THREAD

**Issue by chisandrei** [guillep/pharo-core#17058]
**Bug description**

Creating a breakpoint and the calling `ASTLiteralValueNode>>sourceText` on the ast node `ASTLiteralValueNode` containing the `BreakDebugPoint` instance leads to an infinite recursion

**To Reproduce**
From a `BreakDebugPoint`  instance we can get to a `RFMessageSend`. Then calling `sourceText` on the receiver leads to an infinite recursion as `BreakDebugPoint>>storeOn:` is called.

<img width="1792" alt="Screenshot 2024-09-02 at 14 39 48" src="https://github.com/user-attachments/assets/33cd2c4d-49fd-4aff-87fe-77a3d05d0d35">

<img width="1792" alt="Screenshot 2024-09-02 at 14 40 16" src="https://github.com/user-attachments/assets/8233b81a-a34b-4f86-ad39-d9994a3de7ad">

**Expected behavior**

Ideally no infinite recursion. Other parts of the system like `RBSimpleFormatter>>#visitLiteralNode:` explicitly do a check like `aLiteralNode value isLiteral` before calling `ASTLiteralValueNode>>sourceText` to avoid the recursion.  But then every other sender should do that check.

**Version information:**
Tested in Pharo 13

**Expected development cost**
Maybe `ASTLiteralValueNode>>sourceText`  can return an explicit value like  `'<an unprintable nonliteral value>'`
 instead of doing into an infinite recursion.

**Comment by StevenCostiou** [comment]
Thanks!
@MarcusDenker I had a look, and I am confused about the reason of calling `storeOn:`here.
In `Object>>storeOn:` the comment says:
```Smalltalk
	"Append to the argument aStream a sequence of characters that is an
	expression whose evaluation creates an object similar to the receiver."
```
But this is called in the message `sourceText`... a should a source text not be just a text? 
Why is it needed that we use `storeOn:` which explicitly could be evaluated to create an object similar to the receiver (that is, not even necessarily the original receiver)?

**Comment by MarcusDenker** [comment]
Yes, I think we should not use storeOn: here
