### ISSUE TITLE
SycSourceCodeCommand>>#asRefactoring should be moved

### ISSUE THREAD

**Issue by JanBliznicenko** [guillep/pharo-core#17053]
`SycSourceCodeCommand` defines `asRefactorings` subclass responsibility. However, general source code command should probably not **require** being a refactoring-type command. 

Indeed, 7 out of 16 base image subclasses, including `SysInspectNodeCommand` from its own package, do not implement this method without any adverse effect.

The method should probably be moved from `SycSourceCodeCommand` to `SycSourceCodeRefactoringCommand`.

Applies to Pharo 10 - 13

**Comment by jecisc** [comment]
PR fixing this has been integrated
