### ISSUE TITLE
RxMatcher does not recognize LF as line ending

### ISSUE THREAD

**Issue by riuttner** [guillep/pharo-core#17062]
When applying a regex pattern to a file stream with #lf line ending, I noticed that even a simple pattern does not match:
```
(ClyRegexPattern with: '^b') matches: (String streamContents: [ :s | #( 'aa' 'bb' 'cc') do: [ :e | s << e; lf] ]).
```
The  same expression matches if I send #cr instead of #lf inside the #do:. 

Having a look at `RxMatcher`, I notice that there are 2 shared Variables, `Cr` and `Lf`, where `Lf` is not referenced at all. Thus I consider the problem being a simple mistake that was not detected until now because Regex is mostly used for Smalltalk source code which always uses #cr line ending.

The following fixes work for me (even with dropping the #atEnd checks on outer level, because they are anyway performed inside of #peek and #lastChar):

```
atEndOfLine
	^ stream peek 
		ifNotNil: [ :c | c = Cr or: [ c = Lf] ]
		ifNil: [ true ]
```

```
atBeginningOfLine
	^self lastChar
		ifNotNil: [ :lc | lc = Cr or: [ lc = Lf ] ]
		ifNil: [ true ]
```
To be "totally correct", it might be nice to internally skip a #lf character in case we detected a #cr as first character of a sequence #crlf. But: First of all, I did not encounter issues with my solution, and second, doing searches across lines anyway does not work for regular expressions with direct sequences of `^` and `$` tokens, neither in Pharo nor is it intended to work, as I noticed (I also checked on [regex101](https://regex101.com).

In such cases, you should rather use backslash escaped values like in the following which yields true in Pharo (and works equivalently on regex101):

```
((ClyRegexPattern with: '^bb\ncc') matches: (String streamContents: [ :s | #( 'aa' 'bb' 'cc') do: [ :e | s << e; lf] ]))
&
((ClyRegexPattern with: '^bb\rcc') matches: (String streamContents: [ :s | #( 'aa' 'bb' 'cc') do: [ :e | s << e; cr] ]))
&
((ClyRegexPattern with: '^bb\r\ncc') matches: (String streamContents: [ :s | #( 'aa' 'bb' 'cc') do: [ :e | s << e; cr; lf] ]))
```

Thus I will prepare a fix as shown above, along with new testing methods.

**Comment by noha** [comment]
Ah sorry I was busy but seems to have improved
