### ISSUE TITLE
Class Critique Browser menu Item should not be in refactoring 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#17079]
<img width="596" alt="Capture 2024-09-05 at 21 36 29" src="https://github.com/user-attachments/assets/ba4a1cb6-ab94-4dfa-8b01-d955a0fba7bc">

**Comment by hernanmd** [comment]
Create Extras sub-menu and migrate Commands to Commander 2 :  #17099 
Move Class Critique Browser to the new Extras sub-menu : https://github.com/pharo-spec/NewTools/pull/846
