### ISSUE TITLE
classesAndTraitsDo takes much longer than classesDo: in RBBrowserEnvironment

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#17072]
When setting up a browsing environment to search for classes for example, the time it takes to iterate classes using `classesDo:` is much less than the time it takes to iterate classes and traits with `classesAndTraitsDo:`.

One would expect the time for both iterations to be at least similar, since iterating Traits should not place a special burden during iteration.

Consider the following expressions:

```smalltalk
| globalEnv |
	
globalEnv := RBBrowserEnvironment new.
[ (globalEnv forPackages: globalEnv packages) classesDo: [ : c | c printString ] ] bench.
```
 "93 iterations in 5 seconds 5 milliseconds. 18.581 per second"

versus

```smalltalk
| globalEnv |
	
globalEnv := RBBrowserEnvironment new.
[ (globalEnv forPackages: globalEnv packages) classesAndTraitsDo: [ : c | c printString ] ] bench.
```
"1 iteration in 5 seconds 96 milliseconds. 0.196 per second"

**Comment by jecisc** [comment]
I did some digging here and I found that #classesDo: is already iterating over the traits. So we do not need #classesAndTraitsDo: 

So the question is:
- Do we remove #classesAndTraitsDo: and use the #classesDo: that is faster?
- Do we change the behavior of #classesDo: to exclude traits?

<img width="710" alt="image" src="https://github.com/user-attachments/assets/77780d19-1fc8-4ed3-a4d2-04b3b18bf792">


@Ducasse @MarcusDenker

**Comment by jecisc** [comment]
I did a PR with the first solution https://github.com/pharo-project/pharo/pull/17201

The problem seems to also be in SystemEnrionment. We should probably clean that

**Comment by Ducasse** [comment]
I think that this is nice to be able to have iteration on classes and iterations on trait separated because there are not the same. I do not like that classesDo: is going over traits because else for certain scenarios I would have to check and remove the traits.
