### ISSUE TITLE
Wrong compilation to ConstantBlockClosure: [ 0 . 1 ] value returns 0 instead of 1

### ISSUE THREAD

**Issue by tomooda** [guillep/pharo-core#17090]
**Bug description**
A block closure that starts with a literal is compiled to ConstantBlockClosure that returns the first literal.
As a result, expressions after the literal are not evaluated and the sender gets a wrong return value.

**To Reproduce**
[ 0 . 1 ] value >>> 0
([:t | 0 . 1 ] value: 2) >>> 0

**Expected behavior**
[ 0 . 1 ] value >>> 1
([:t | 0 . 1 ] value: 2) >>> 1

**Version information:**
 - OS: macOS
 - Version: 14.6.1
 - Pharo Version Pharo 11, 12 and 13
 - Pharo 10 does not have this bug.

**Expected development cost**
Need to fix Opal compiler.

**Comment by MarcusDenker** [comment]
thanks for the report, I will fix it
