### ISSUE TITLE
P13: SpApplication comment still includes #openWithSpec

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#17119]
Pharo 13, class comment of SpApplication says one should use #openWithSpec
but #openWithSpec is not valid anymore and removed

![image](https://github.com/user-attachments/assets/39a0a76e-f73b-4b5a-8f59-8f3e819b9d94)

**Comment by koendehondt** [comment]
This is a Spec issue, so it was fixed there: https://github.com/pharo-spec/Spec/pull/1634

**Comment by MarcusDenker** [comment]
merged !
