### ISSUE TITLE
Using Eclipse icons gives wrong sized icon for Critique Browser

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#17146]
- open Pharo 13
- go to Settings - Appearance and switch to Eclipse icons

the icon for Critgique Browser in world menu is then wrongly sized:

![image](https://github.com/user-attachments/assets/930d8d77-6618-4bae-a57b-499ff745dd2f)

**Comment by hernanmd** [comment]
In https://github.com/pharo-spec/NewTools/pull/846
