### ISSUE TITLE
Browser's "Choose class" dialog does not work with exact searches

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#17140]
**Bug description**
The new "Choose class" dialog implemented in `ClyFindClassCommand` does not do exact matches, and there is no way to tell that I want to search using exact matches.

For instance, If I write "Object" I want "Object" and not "CmObject" :)

**To Reproduce**
 See the following video:

https://github.com/user-attachments/assets/0752bbc5-e151-475c-b465-360697b1313f

**Expected development cost**
There is already an implementation of multiple types of matching in the NewFinder. It could be refactored in a new package to be used in the Choose class window. That would need a PR in NewTools so it can include the refactored package.

**Comment by hernanmd** [comment]
In https://github.com/pharo-spec/NewTools/pull/845

**Comment by Rinzwind** [comment]
I agree with wanting to get the class Object and not the class CmObject when looking for “Object”. But in the demo in [NewTools pull request #845](https://github.com/pharo-spec/NewTools/pull/845) it seems you would still need to select the ‘exact’ option for that. Whereas in Pharo 12 there’s no need for an extra click: you get Object when you type “Object” and just press the return key. A problem in Pharo 12 though is that it’s not always clear whether there’s an exact match or not: issue #13720. That could be solved by scrolling the list to the exact match when there is one, or by putting it first in the list. The ‘ok’ button should probably also be disabled when no class is selected.

**Comment by hernanmd** [comment]
> I agree with wanting to get the class Object and not the class CmObject when looking for “Object”. But in the demo in [NewTools pull request #845](https://github.com/pharo-spec/NewTools/pull/845) it seems you would still need to select the ‘exact’ option for that. Whereas in Pharo 12 there’s no need for an extra click: you get Object when you type “Object” and just press the return key. A problem in Pharo 12 though is that it’s not always clear whether there’s an exact match or not: issue #13720. That could be solved by scrolling the list to the exact match when there is one, or by putting it first in the list. The ‘ok’ button should probably also be disabled when no class is selected.

Thanks for the feedback. I will try to implement your suggestions in another PR

**Comment by hernanmd** [comment]
> > I agree with wanting to get the class Object and not the class CmObject when looking for “Object”. But in the demo in [NewTools pull request #845](https://github.com/pharo-spec/NewTools/pull/845) it seems you would still need to select the ‘exact’ option for that. Whereas in Pharo 12 there’s no need for an extra click: you get Object when you type “Object” and just press the return key. A problem in Pharo 12 though is that it’s not always clear whether there’s an exact match or not: issue #13720. That could be solved by scrolling the list to the exact match when there is one, or by putting it first in the list. The ‘ok’ button should probably also be disabled when no class is selected.
> 
> Thanks for the feedback. I will try to implement your suggestions in another PR

I updated the PR in https://github.com/pharo-spec/NewTools/pull/845 to handle auto-selection when the typed class exists.

**Comment by Ducasse** [comment]
So do we close this issue?

**Comment by hernanmd** [comment]
Already integrated, so I closed it

**Comment by Rinzwind** [comment]
Thanks! A few comments I still have though:

* The result list only gets updated when the text field is edited, not when any of the options are changed
* The ‘Ok’ button remains enabled when there are no results
* The label ‘Case’ should probably be ‘Case sensitive’
* I’m not sure the ‘Exact’ option is useful anymore now that ‘Substring’ will select an exact match if there is one (removing it would also avoid the next point)
* The spacing between the radio buttons makes it seem as if the grouping is ‘Substring’ and ‘Regexp / Exact’ rather than ‘Substring / Regexp / Exact’
* The result list should preferably be updated through a background process to avoid delay in the handling of keystrokes while typing in the text field (which is especially noticeable now when using ‘Regexp’)
* When using ‘Regexp’, a debugger is opened when trying to enter ‘test[a-c]’ in the text field due to a RegexSyntaxError (“no terminating "]"”)

**Comment by Ducasse** [comment]
@hernanmd may be better to open another issue.

**Comment by Rinzwind** [comment]
@hernanmd: I was wondering whether you’ve opened another issue as suggested above? The last point, about the RegexSyntaxError, should probably be handled at least.

**Comment by hernanmd** [comment]
@Rinzwind the error belongs to Spec, so I opened an issue there (working on a PR now)
https://github.com/pharo-spec/Spec/issues/1633

**Comment by hernanmd** [comment]
@Rinzwind Please open issues in the Spec repository, so people can discuss it there. For the Regex bug I sent a PR https://github.com/pharo-spec/Spec/pull/1635
