### ISSUE TITLE
[Refactoring] Cleanup user interactions from Pull Up Method Refactoring and Transformation

### ISSUE THREAD

**Issue by carolahp** [guillep/pharo-core#17158]
**Problem Description**
'RBPullUpMethodDriver, introduced in [PR#17018](https://github.com/pharo-project/pharo/pull/17018), handles all user interactions. However in this PR remaining user interactions in pull up refactoring and transformations were not cleaned up.

**Classes involved**
`RBPullUpMethodTransformation` and `RBPullUpMethodRefactoring`, besides from related tests

**Proposal**
Not sure yet, since I still don't understand very well how far I should go with the cleanup, because many tests would need to be modified. 

Here's a related comment from @balsa-sarenac 
         We want to remove all these warnings to driver from both transformation and refactoring. We can introduce flags for scripting purpose so user can configure it and we will set sane defaults.

_Originally posted by @balsa-sarenac in https://github.com/pharo-project/pharo/pull/17018#discussion_r1768355823_

https://github.com/pharo-project/pharo/pull/17018#discussion_r1768355823

**Version information:**
 - Version [e.g. Pharo 13.0]

**Additional context**
We can start to solve this after merging [PR#17018](https://github.com/pharo-project/pharo/pull/17018)

**Comment by Ducasse** [comment]
We did a pass with Balsa
