### ISSUE TITLE
[Refactorings] Add driver and make sure the same functionality is called from three places

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#17155]
In a clean P13 image I did this:
- Take a class and add a class variable
- Go class side
- Select the variables view
- Right click on the class variable
- Click on "Generate accessors"

Actual result: A message saying that nothing applied
Expected result: An UI to generate the accessors

**Comment by Ducasse** [comment]
It looks like we did not migrate this one to the driver architecture too. I thought we did it.

**Comment by Ducasse** [comment]
At least it works from the class list

![Capture 2024-09-23 at 18 17 20](https://github.com/user-attachments/assets/549151c2-a921-4456-923c-e513a0471e93)

**Comment by Ducasse** [comment]
The problem is probably that they are different ways to call the refactoring since the logic is coded in the command....

**Comment by Ducasse** [comment]
Now this is strange because this one we migrate it as we can see the (T).

**Comment by Ducasse** [comment]
![Capture 2024-09-23 at 18 19 51](https://github.com/user-attachments/assets/c0d0a10f-3bd0-4703-ab81-8387a6b3aafa)

**Comment by Ducasse** [comment]
I put an halt in the commands and none of the way reached the breakpoints :(

**Comment by Ducasse** [comment]
```
SycGenerateAllInstVarAccessorsCommand >> execute
	self halt.
	self executeRefactorings
```

**Comment by Ducasse** [comment]
same with a halt in asRefactorings

In addition the generate does not work from the class definition either.

![Capture 2024-09-23 at 18 30 44](https://github.com/user-attachments/assets/62d1f0f6-422f-43d6-8544-bbfcf5a2038a)

**Comment by Ducasse** [comment]
Apparently this is SycGenerateVariableAccessor that is responsible for the class definition and the variable list.

**Comment by Ducasse** [comment]
Then 

```
SycGenerateAllInstVarAccessorsCommandasRefactorings

	| refactorings |
	self halt.
	refactorings := classes flatCollect: [ :eachClass |
		                eachClass slots collect: [ :var |
			                | accesorRefactoring |
			                accesorRefactoring := RBAddVariableAccessorTransformation
				                                      instanceVariable: var name
				                                      class: eachClass.
			                accesorRefactoring ] ].
	^ refactorings
```

is invoked from the main class menu (there is (T) in front).

**Comment by Ducasse** [comment]
Strangely enough I cannot get now the source menu item when I select the same instance variable in the same class definition. 
How hateful is this part of the system.

**Comment by Ducasse** [comment]
So conclusion:
- we should only have one command
- the interaction should be delegated to a driver 
- We should not use the SycRefactoringPreviewPresenter but the StRefactoringPreviewPresenter

**Comment by Ducasse** [comment]
Apparently the SycRefactoringPreviewPresenter has a bug and does not show changes anymore.

**Comment by Ducasse** [comment]
Hi @carolahp 

Could you have a look. I think that this refactoring should be simpler than the one you fight with :).

S

**Comment by carolahp** [comment]
Hi @Ducasse , of course, I will take a look tomorrow, while we merge the more complicated PR I am fighting now!

**Comment by carolahp** [comment]
I realized that the transformation had a bug. 
For this reason I first created a PR to fix this bug because I will need this transformation later. 

In a following PR I will 
* Refactor to have one command
* Create a driver to handle interactions
* Replace the usage of SycRefactoringPreviewPresenter by StRefactoringPreviewPresenter

**Comment by Ducasse** [comment]
OK ;)
