### ISSUE TITLE
[Refactoring] Duplicate class does not honor the package tag

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#17166]
I used the duplicate class refactoring today and I found that the package tag is not honored. It should have been in "Visitor" but was created in "Unclassified". 

@hernanmd This can interest you?

**Comment by hernanmd** [comment]
> I used the duplicate class refactoring today and I found that the package tag is not honored. It should have been in "Visitor" but was created in "Unclassified".
> 
> @hernanmd This can interest you?

Sure, let me check it
