### ISSUE TITLE
[CI] Refactoring related tests failing on the CI

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#17164]
These tests started failing on the CI:

- RBAddVariableAccessorsParametrizedTest.testNewClassVariableAccessors
- RBAddVariableAccessorsWithLazyInitializationParametrizedTest.testNewClassVariableAccessors
- RBMoveMethodParametrizedTest.testMoveMethodIntoArgument
- RBMoveMethodParametrizedTest.testMoveMethodIntoInstanceVariable
- ReMethodsHaveNoDuplicatesTest.testMethodDuplicatedInSibling

**Comment by Ducasse** [comment]
Hi caro can you have a look at them?

**Comment by MarcusDenker** [comment]
It seems that https://github.com/pharo-project/pharo/pull/17160 was merged that introduces many of them ( all but ReMethodsHaveNoDuplicatesTest.testMethodDuplicatedInSibling ?)

**Comment by carolahp** [comment]
I'm looking at them now

**Comment by carolahp** [comment]
In PR #17165 I reverted changes introduced in #17160, but tests are still failing. 
I am investigating the cause

**Comment by guillep** [comment]
We are investigating this with @omarabedelkader, if we apply the PR #17165 locally, the following tests are fixed:

RBAddVariableAccessorsParametrizedTest.testNewClassVariableAccessors
RBAddVariableAccessorsWithLazyInitializationParametrizedTest.testNewClassVariableAccessors
RBMoveMethodParametrizedTest.testMoveMethodIntoArgument
RBMoveMethodParametrizedTest.testMoveMethodIntoInstanceVariable

But not the fifth one.

**Comment by MarcusDenker** [comment]
Now only .ReMethodsHaveNoDuplicatesTest.testMethodDuplicatedInSibling us failing I clore this and open a new one for that
