### ISSUE TITLE
[CI] Failing test: ReMethodsHaveNoDuplicatesTest.testMethodDuplicatedInSibling

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#17175]
One Refactoring related test is failing:

ReMethodsHaveNoDuplicatesTest.testMethodDuplicatedInSibling

**Comment by Rinzwind** [comment]
The test was added in pull request #17018 by @carolahp and failed in the [last build (#7) for that pull request](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/PR-17018/7/).

**Comment by MarcusDenker** [comment]
So what do we do?  Do we revert  https://github.com/pharo-project/pharo/pull/17018 ?

**Comment by Ducasse** [comment]
I thought that caro would fix it but this is not the case right now. 
@carolahp 
I will have a look now this is not urgent!

**Comment by MarcusDenker** [comment]
This is fixed!
