### ISSUE TITLE
Pharo 13 with strange screen on Windows

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#17189]
ON WINDOWS: Open latest Pharo image (P13) with latest updated VM gives a strange screen 

![image](https://github.com/user-attachments/assets/50a99795-0859-496a-89dd-7c230e575881)

**Comment by astares** [comment]
Trying again gives same results:

![image](https://github.com/user-attachments/assets/e677a123-ece1-44e6-8c48-d7fd12713b0d)

**Comment by riuttner** [comment]
Thanks for the report and thanks for being not the only one seeing that! For me it looks like that the scaling is wrong for about a factor of 100(!). On MacOS it's similar, it there even tries to create a cursor shape of about 2000x2000 px, and you can even move that cursor ...
For me it occurred when just trying to create an image via Pharo Launcher for latest P13 release, without any initializtion script. Creation works, but trying to launch the new image starts with an overscaled view and does not come to an end of max cpu usage in a reasonable time.
This is really a show stopper!

**Comment by Rinzwind** [comment]
Pull request #17192 will fix this. Until it’s merged and a new build is available, you can use the image of build 262, either by downloading it from the [directory ‘image/130’ on ‘files.pharo.org’](https://files.pharo.org/image/130/), or through the template category ‘Pharo 13.0 (development version)’ in Pharo Launcher.

**Comment by Ducasse** [comment]
It is merged :)

**Comment by Ducasse** [comment]
tx kris. We love all these enhancements.

**Comment by riuttner** [comment]
Many thanks to everybody involved to fix that issue so soon! Works for me too on both platforms now.

**Comment by astares** [comment]
Fixed with https://github.com/pharo-project/pharo/pull/17192

Works now - we close the issue
