### ISSUE TITLE
An explanation of the usefulness of the system dependencies test?

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#17211]
**Describe the request**

There is a set of tests that for months have been causing the Pharo CI to fail for minor changes to internal and external packages. These tests may be good for minor changes, but for major re-architecting tasks (e.g. removing Morphic from the image) these tests impose an additional load on the work. These failures are difficult to foresee, take time to fix, and take an almost archeological effort to find the reasons and possible solutions. These tests generally compare a set of dependencies (packages) collected through different Baselines against a set of “known dependencies”.

I have seen that the tests were introduced in [this commit](https://github.com/pharo-project/pharo/commit/b8a559711cca073f6bfb249ee046b57fe2f44caf) by @pavel-krivanek.

But there are no comments that have helped me to understand well the usefulness of these tests. The class comment seems to me insufficient given the importance of these tests: “This test checks dependencies in the image and proves that there are no new unknown dependencies between packages.”.

- These “unknown” dependencies are unknown in what sense? How do you define whether a dependency is known or not? Known by whom or between whom? I understand that you are trying to ensure a kind of stability and verifiability, but it is not clear how the system can evolve if these tests do not allow new dependencies.
- If we take for example the `testExternalUIDependencies` method. There is a dispatch to the `externalDependenciesOf:` message that receives a collection as an argument, when should a parameter be added to that message?
- Why do some messages use `deepPackagesOfGroupNamed:` and others use `allPackageNames` ?
- Why do some use the Baseline group #default even when there is another group named #ui? e.g. `BaselineOfCommander2 deepPackagesOfGroupNamed: #default` uses #default, but there is a group #ui. 

On the other hand, why does `knownUIDependencies` have the comment `“ideally this list should be empty”`?

**Comment by jecisc** [comment]
One of the goal of the work done to introduce the bootstrap process was to have "layers" in Pharo. Like Kernel, network, UI, tools... and to be sure that a "bottom" layer was not dependent on a "top" layer. 

Those tests are there to define those layer and ensure we do not have a bad dependency.

They can break easily but they helped a lot! They allowed us to avoid a lot of unwanted dependencies to appear. Like for example to have parts of the core of Pharo dependent on the UI classes. 

All "knownXXXDependencies" methods should ideally be empty because they are unwanted dependencies that we where not yet able to remove

**Comment by hernanmd** [comment]
> One of the goal of the work done to introduce the bootstrap process was to have "layers" in Pharo. Like Kernel, network, UI, tools... and to be sure that a "bottom" layer was not dependent on a "top" layer.
> 
> Those tests are there to define those layer and ensure we do not have a bad dependency.
> 
> They can break easily but they helped a lot! They allowed us to avoid a lot of unwanted dependencies to appear. Like for example to have parts of the core of Pharo dependent on the UI classes.
> 
> All "knownXXXDependencies" methods should ideally be empty because they are unwanted dependencies that we where not yet able to remove

Thanks, Cyril, I understand the overall goal.

What is not clear is the criteria for including o removing parts of the "dependencies" collection. So far nothing prevents me from just editing those methods so this accommodates my needs. Please read carefully again for the specific questions because it seems to me there is no real criteria :)

**Comment by jecisc** [comment]
Ideally, those methods should return an empty collection, and even better, not exist :)

They are there just because we did not succeed yet to cut those dependencies and we are working on them little by little (we removed like 5-6 of those exceptions during the development of P12)

**Comment by hernanmd** [comment]
> Ideally, those methods should return an empty collection, and even better, not exist :)
> 
> They are there just because we did not succeed yet to cut those dependencies and we are working on them little by little (we removed like 5-6 of those exceptions during the development of P12)

I will try to re-phrase as a simple question: Why shouldn't I remove/change this line from `testExternalUIDependencies` ?

```smalltalk
(BaselineOfNewTools deepPackagesOfGroupNamed: 'Methods')
```

**Comment by hernanmd** [comment]
I will close this issue since I've developed my tool to help in the explainability of dependencies :)
