### ISSUE TITLE
Browser: Lost "copy method name" Button

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#17251]
There was a button in the browser to copy the name to the clipboard:

![Untitled](https://github.com/user-attachments/assets/2b76894b-05e9-4cd9-bcd3-9c84b7d3b058)

I use that *very* often. Now it is gone:

![LostCop](https://github.com/user-attachments/assets/ad0b019c-c48d-48cb-9d7a-5690f1a8c096)

**Comment by MarcusDenker** [comment]
It is still in the "extra' menu of methods. Maybe that is enough?

**Comment by jecisc** [comment]
Personally I loved this little button

@hernanmd maybe this is linked to your recent change?

**Comment by hernanmd** [comment]
> Personally I loved this little button
> 
> @hernanmd maybe this is linked to your recent change?

Probably it is related. I will check later today
