### ISSUE TITLE
[Refactorings] Cannot use "Generate accessors" 

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#17280]
In the latest P13 I cannot use "generate accessors". 

- Create a class Toto with a variable named var
- Use the variables view of Calypso
- Right click on the variable var
- Click on "(T) Generate accessors"

Expected result: A window with the proposed generated methods

Actual: A popup saying no change will be generated

**Comment by Ducasse** [comment]
related too https://github.com/pharo-project/pharo/issues/17155

**Comment by Ducasse** [comment]
We should modify SycGenerateVariableAccessor because it is the one invoked.

**Comment by Ducasse** [comment]
Apparently this one is not used and we should remove it: SycGenerateAllInstVarAccessorsCommand
