### ISSUE TITLE
Debugger method context menu no longer has items ‘Do it’, ‘Debug it’, ‘Inspect it’ and so on

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#17320]
As observed [in issue #17038](https://github.com/pharo-project/pharo/issues/17038#issuecomment-2438656875), in Pharo 13 build 313, the method context menu in a debugger no longer has items ‘Do it’, ‘Debug it’, ‘Inspect it’ and so on (1.png). The items were still present in build 299 (2.png), they disappeared in build 300.

**1.png:**
<img width="417" src="https://github.com/user-attachments/assets/98b9369e-56c4-4a98-9e29-08b24e88d791">

**2.png:**
<img width="417" src="https://github.com/user-attachments/assets/cb6980d7-d52c-4e2c-ae9a-c9fa3987ff8a">

**Comment by StevenCostiou** [comment]
This is a command migration issue, it was fixed by esteban in https://github.com/pharo-spec/Spec/pull/1642
