### ISSUE TITLE
Clicking on inspector icons just break

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#17323]
![Capture 2024-10-28 at 11 28 04](https://github.com/user-attachments/assets/1eb6eacb-1bf5-4498-9b30-3c1b922b64c1)

**Comment by StevenCostiou** [comment]
I have started that one last week. 
It seems spec has changed somehow in its internal and now the correct context is lost.

**Comment by StevenCostiou** [comment]
@estebanlm this one
