### ISSUE TITLE
Pressing "Add method" instead of "Create method" when creating a new method in the debugger

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#17356]
- with the new pane on the left we can enter all the information such as protocol, class....
- then we are invited to press Add Method. 
- To me it should be renamed create method because I was hesitating to press it. 
- I got confused.

**Comment by jecisc** [comment]
@StevenCostiou This might interest you

**Comment by StevenCostiou** [comment]
It will be changed friday ;)

**Comment by StevenCostiou** [comment]
PR done in New Tools

**Comment by StevenCostiou** [comment]
fixed by https://github.com/pharo-spec/NewTools/pull/892
