### ISSUE TITLE
P11 does not build because of microdown

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#17391]
About the failing ‘Pharo11’ builds: build 730 had a ‘Segmentation fault’ at [line 854 in the ‘Full Image-64‘ stage output](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo11/730/pipeline-console/?start-byte=0&selected-node=26#log-854), while the error in build 729 at [line 883 in the ‘Full Image-64’ stage output](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo11/729/pipeline-console/?start-byte=89976&selected-node=26#log-883) seems to be due to BaselineOfNewToolsDocumentBrowser referring to an nonexistent branch ‘integration’ in the [‘Microdown’ repository](https://github.com/pillar-markup/Microdown), builds 728 and 727 had a similar error. Because of these failures, the most recent available Pharo 11 image does not include the changes of pull requests https://github.com/pharo-project/pharo/pull/16485 and https://github.com/pharo-project/pharo/pull/17131.

@Rinzwind

**Comment by Ducasse** [comment]
I checked in an old P11 image I got and I get the following. 


![Capture 2024-11-17 at 16 36 27](https://github.com/user-attachments/assets/2c8eac62-ed59-41b2-87a5-4ed87d86bec1)

So may be pointing to v2.4.1 instead of integration can fix the problem.

**Comment by Rinzwind** [comment]
I opened pull requests to make BaselineOfNewToolsDocumentBrowser and BaselineOfWelcomeBrowser use the tag ‘v2.4.1’ instead of the branch ‘integration’ as suggested above: [NewTools-DocumentBrowser pull request #17](https://github.com/pharo-spec/NewTools-DocumentBrowser/pull/17) and [NewTools-WelcomeBrowser pull request #28](https://github.com/pharo-spec/NewTools-WelcomeBrowser/pull/28).

**Comment by Rinzwind** [comment]
I’ll close this as a new Pharo 11 image was built, see pull requests #17427 and #17462.
