### ISSUE TITLE
TestCase >> failureLog should not refer to a globla

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#17403]
```
TestCase >> failureLog
	^ Smalltalk tools transcript
```
Should be turned into 

```
TestCase >> failureLog
	^ application tools transcript
```

http://rmod-pharo-mooc.lille.inria.fr/AdvancedDesignMooc/Slides/M9-4-CaseStudy-06-LayeredSettingsArchitecture.pdf

Practice what you preach!

https://www.youtube.com/watch?v=FQfgET6TxDY

**Comment by hernanmd** [comment]
StPharoApplication is in 'NewTools-Core'.
So implementing `application` would introduce a new dependency from SUnit to NewTools.

Do you know how can I get the application without introducing this dependency?

**Comment by Ducasse** [comment]
Indeed this is a problem.
My impression is that my suggestion was wrong. In fact the failureLog should refer to a stream and provide a setter so that clients may decide to inject a different streamable object.
Like that we can if we want ask the log to be redirected to transcript and this is the responsibility of the tools in the upper layer to provide correct objects.

**Comment by Ducasse** [comment]
My fix was merged (and useful to find a nice bug in the VM)
