### ISSUE TITLE
Removing an unused instance variable made pharo quits

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#17433]
- I added a variable stream logStream and a setter to TestAsserter.
- It worked ok
- Then later I realized that I did not need it so I removed the setter and 
when I removed the instance variable from the class by editing the class definition

The image quit.
[PharoDebug.log](https://github.com/user-attachments/files/17893653/PharoDebug.log)

**Comment by Ducasse** [comment]
I could reproduce it!

**Comment by Ducasse** [comment]
https://filesender.renater.fr/?s=download&token=d1431577-2db9-43e6-82cc-314103cc80cf

**Comment by hernanmd** [comment]
I couldn't reproduce it but when I added the instance variable in TestAsserter it went unresponsive 2 minutes (I inspected and it was migrating instances).

**Comment by jecisc** [comment]
Is it what Pablo fixed in the VM?

**Comment by Ducasse** [comment]
Got fixed!

**Comment by Ducasse** [comment]
Cyril it was a problem in the assembly when the class was changed (because a new one was created) and that the assembly extracted the class tag of the old class - or something like that. 
To generate the bug it required to change a large hierarchy such as the Asserter one with all the test subclasses.
