### ISSUE TITLE
[Refactorings] #reservedNames should not be duplicated

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#17440]
We have a method with some reserved names for variables in the refactorings but this method is present two times. 

I think we should have it only in one place because the list might evolve and we might miss a place. For example, I think that now we should add `thisProcess`.

RBCondition class>>#reservedNames and ReVariableNameCondition class>>#reservedNames

**Comment by Ducasse** [comment]
In fact we want to remove RBCondition.

**Comment by jecisc** [comment]
I discussed with Marcus.

We think it might be nice if those names could be collected instead of hard coded but for that we need to think more on how to do it. 

In the meantime, for a better state than what we have now, we think we should have this method out of RB.
We propose to add a method named `reservedLiterals` on the class side of Symbol and to use this method in RB. Like this, we can use it in other places than RB too. 

Also, instead of hardcoding everything, we can ask the pseudo variables with PseudoVariable lookupDictionary keys and add the missing literals by hand.
