### ISSUE TITLE
Remove "Declare new Global" feature from the undeclared variable dialogue

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#17459]
In a code editor (for example in Calypso) it is possible to write the name of a class that is not present in the system. When we compile the method or execute it, we get a dialog proposing some options such as leaving the variable undeclared or creating a new class of this name.

In the options we have "Declare new global". 

I propose to remove this option because it should be really rare to have the need of declaring a new global and this should not be something easy to do. People who know how to handle globals in a good way will know how to declare it without this option in the dialog. And new developers should probably not play with globals.

@Ducasse What do you think?

**Comment by Ducasse** [comment]
`+ 10000`

**Comment by jecisc** [comment]
Done
