### ISSUE TITLE
[CI] Build broken "StInspectorPresenter class(Object)>>doesNotUnderstand: #register"

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#17464]
This PR shows a build problem: https://github.com/pharo-project/pharo/pull/17463

```
StInspectorPresenter class(Object)>>doesNotUnderstand: #register
```

**Comment by guillep** [comment]
Yesterday the build was ok

<img width="314" alt="imagen" src="https://github.com/user-attachments/assets/3ac40372-50df-4ffc-859c-636f32bd7caa">

This means that something changed on NewTools in the middle.

**Comment by jecisc** [comment]
https://github.com/pharo-spec/NewTools/pull/911/files#diff-510bc4720ed0d7aaf400208b69e9938544588127a0c532aa3ae802901113a9fb

This is the faulty PR I guess

<blockquote><img src="https://avatars.githubusercontent.com/u/432549?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-spec/NewTools/pull/911">use registerToolsOn: logic to respect architecture: class initialize  by Ducasse · Pull Request #911 · pharo-spec/NewTools</a></strong></div><div>use registerToolsOn: logic to respect architecture: class initialize</div></blockquote>

**Comment by jecisc** [comment]
I proposed a fix: https://github.com/pharo-spec/NewTools/pull/913

**Comment by jecisc** [comment]
That was not enough. 

New one: https://github.com/pharo-spec/NewTools/pull/914

**Comment by jecisc** [comment]
Fixed!
