### ISSUE TITLE
Pharo12 Build fails with "KeyNotFound: key #unzipped not found in MethodDictionary"

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#17472]
The last PRs fail full image reload with

```
KeyNotFound: key #unzipped not found in MethodDictionary"
```

**Comment by MarcusDenker** [comment]
The last build of Pharo12 worked: https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo12/

This was Nov 15

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo12/">Pharo12 [Pharo] [Jenkins]</a></strong></div></blockquote>

**Comment by Ducasse** [comment]
I'm confused. When I check the last build I get a working build.

![Capture 2024-12-01 at 17 33 16](https://github.com/user-attachments/assets/3317ef53-9c68-4f37-baab-dfcd8bd4fa69)

**Comment by MarcusDenker** [comment]
This only happen for the PR https://github.com/pharo-project/pharo/pull/17469

This means the build is ok and we can close this issue
