### ISSUE TITLE
File-in by drag and drop runs into DNU #itemsForFile:

### ISSUE THREAD

**Issue by riuttner** [guillep/pharo-core#17480]
When dropping an arbitrary ST file for file-in on an arbitrary package (P13 latest under W10, but should fail on all platforms), I always get the following DNU:

*Message not understood: StFileSystemPresenter class >> #itemsForFile:*

This happens in the the first executed method line of `ExternalDropHandler class>>#lookupServiceBasedHandler:` before the #reject: is called:
```
lookupServiceBasedHandler: aFileReference
	"the file was just droped, let's do our job"
	| services theOne |

	services := (Smalltalk tools fileList itemsForFile: aFileReference)
		reject: [:svc | self unwantedSelectors includes: svc selector].
```

Looking at earlier pharo releases (my image created on Nov 14th yet worked), I found that there was a thorough change on dealing with `Smalltalk tools fileList` such that formerly there was a class `FileList` returned implementing the following:
```
itemsForFile: file
	"Answer a list of services appropriate for a file of the given full name"

	^ FileServices itemsForFile: file fullName
```

As opposed to that, the latest pharo release returns a Presenter instead, which will not work in principle for the application case of handling a dropped ST file. Thus I propose the following hotfix  for `ExternalDropHandler class>>#lookupServiceBasedHandler:`  (first lines shown only): 
```
lookupServiceBasedHandler: aFileReference
	"the file was just droped, let's do our job"
	| services theOne |

	services := (FileServices itemsForFile: aFileReference fullName)
		reject: ...
```
For a final fix it will maybe better to rely on a `DefaultExternalDropHandler` instead which already implements a method doing something equivalent, see  `DefaultExternalDropHandler>>#servicesForFileNamed:`

**Comment by guillep** [comment]
Thanks Richard, I'm going to tag it. This is due to the introduction of the new FileList rewritten in Spec
