### ISSUE TITLE
Finder is not in the browse menu anymore

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#17483]
In the latest P13 the Finder is not in the browse menu anymore.

![image](https://github.com/user-attachments/assets/3ddd919c-5212-49b2-bb33-3eb961d33e71)

**Comment by jecisc** [comment]
@AlexisCnockaert Apparently Hernan finished his contract so can you take a look?

Currently the entry is there:

<img width="396" alt="image" src="https://github.com/user-attachments/assets/51e4ef7c-6b50-4969-9388-b9cb8be95f9f">

**Comment by AlexisCnockaert** [comment]
ok no problem

**Comment by AlexisCnockaert** [comment]
@jecisc opened this PR in new tools : https://github.com/pharo-spec/NewTools/pull/918
