### ISSUE TITLE
Extending an existing method in other package does nothing in Calypso browser

### ISSUE THREAD

**Issue by riuttner** [guillep/pharo-core#17481]
Checking `extension` box in calypso allows to select package, but when extension is confirmed, nothing happens (P13, W10).
Expected behavior is however:
- The checkbox stays checked when returning from package selection
- The name of the extending package is shown left of the checkbox

The expected behavior is broken not longer than since 3 weeks.

How to reproduce it:
- Browse class `Boolean`
- Select method #asBit (which is just implemented as subclassResponsibility in Kernel package)
- Click checkbox `extension`, choose an arbitrary package (e.g. `Deprecated13`)
- Close package selection dialog with `Ok` 

 Nothing happens. Existing extension methods of the same class, however, are displayed correctly.

IMHO this is very urgent: Currently, you cannot extend a class in a package where the class has not yet been extended in. Even my personal "emergency fallback" for cases like that, using file-in, currently does not work without another patch (see https://github.com/pharo-project/pharo/issues/17480)

**Comment by jecisc** [comment]
I got the same problem today. This was working recently so the break is pretty recent
