### ISSUE TITLE
[CI] Builds have segmentation faults

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#17500]
Several recent builds failed due to segmentation faults, presumably related to the new [VM v10.3.2 release](https://github.com/pharo-project/pharo-vm/releases/tag/v10.3.2): [‘PR-17496’ build #1](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/view/change-requests/job/PR-17496/1/), [‘PR-17496’ build #2](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/view/change-requests/job/PR-17496/2/), [‘PR-17497’ build #1](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/view/change-requests/job/PR-17497/1/), [‘PR-17498’ build #1](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/view/change-requests/job/PR-17498/1/).

**Comment by Rinzwind** [comment]
We had segmentation faults in the builds of our own projects yesterday as well, which were resolved by reverting to the previous VM version.

**Comment by jbrichau** [comment]
Reported as well here: https://github.com/pharo-project/pharo-vm/issues/883

**Comment by guillep** [comment]
I've rolled the stable version back to 10.3.1, please test

**Comment by guillep** [comment]
Can you confirm that the rollback worked for you?

**Comment by jecisc** [comment]
Builds are passing in the Pharo CI at least. I'll close and we can reopen if someone still has problems

**Comment by Rinzwind** [comment]
I've reverted our Jenkins setup back to using the ‘stable’ VM rather than specifically v10.3.1, that seems to work again.

**Comment by guillep** [comment]
Thanks for the confirmation @Rinzwind and @jbrichau !
