### ISSUE TITLE
Iceberg fails silently when user email is private

### ISSUE THREAD

**Issue by icjohnson** [guillep/pharo-core#17565]
**Bug description**

When pushing to a github repo the interface does not react to the following error.

```
emote: error: GH007: Your push would publish a private email address.
remote: You can make your email public or disable this protection by visiting:
remote: https://github.com/settings/emails
```

Confirm by toggling the email address used to perform the commit to private in the users Github settings.

**Comment by Ducasse** [comment]
Thanks for your report.

**Comment by Ducasse** [comment]
Migrated to the iceberg bug tracker
https://github.com/pharo-vcs/iceberg/issues/1872
