### ISSUE TITLE
Synchronise Spec

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2127]
## Migration guide

https://github.com/pharo-spec/Spec/blob/master/resources/migration/specPharo7ToSpecPharo8.md

## Highlitghs

There was a lot of cleaning.
- We removed a lot of dead code and unused features (Such as the
TableLayout since the SpecLayout that was the only one documented and
they did the same thing).
- We progressed on the renaming of Models into Presenters
- We cleaned the dependencies between packages
- We begun to make Spec more "Morphic independant" to be able to have
connectors to other backends later
- ...

There is also new features:
- Windows can now have a toolbar, statusbar or menu. Those can be
initialized via the #initializeWindow: method. See
PrepareWindowExample. Later, the goal is to move everything related to
window to this method instead of having all presenters that can access
their window.
- It is now possible to customize dialog action bar via the
#initializeDialogWindow: method. See SpecDemoModalPresenter
- We introduced ModalPresenter that might replace DialogPresenter. A
ModalPresenter compared to dialogs will act as a real modal and stop
the user to take control on other windows while the modal is opened.
See SpecDemoModalPresenter
- Introduction of a InputNumber (See Spec Demo in the help menubar)
- Introduction of a LinkPresenter (See Spec Demo in the help menubar)
- ...

I try to add demos to the SpecDemos each time I add a new feature so
that users can find new features even if they are not yet well
documented.

### Features

* **Add #addSpacer to SpecLayout** ([298eb26](https://github.com/pharo-spec/Spec/commit/298eb266541e5d25cc02a3f06293a0a22f8d9a82))
* **Add labelled presenter** ([bf76234](https://github.com/pharo-spec/Spec/commit/bf76234cb83df108dcfaa6c6a9dc75b8ece97610))
* **Do not force users to have getters for their presenters** ([f24bd7f](https://github.com/pharo-spec/Spec/commit/f24bd7f4de7cc6c9765cb0d18bfa8ca0a7257881))
* **Now presenters have a special icon in Calypso** ([5c47a63](https://github.com/pharo-spec/Spec/commit/5c47a63d599f681bebc117612ac5252a59a9141e))
* **Add ComposablePresenter>>#iconNamed:** ([d8ce2e2](https://github.com/pharo-spec/Spec/commit/d8ce2e2cc07729d67ed214ce1cf0a950a3f1f88d))
* **Layouts now understand `presenter` instead of `model`** ([7a78375](https://github.com/pharo-spec/Spec/commit/7a783758881fbbb6d536e2b0e2db97f91b3150a1))
* **It is now possible to add menus, status bar and menu bars to window presenters** ([ee0acf6](https://github.com/pharo-spec/Spec/commit/ee0acf6ce49245ae441e0e3475d52795e3426f2e))
* **Add NumberPresenter with its Morphic adapter** ([88792da](https://github.com/pharo-spec/Spec/commit/88792daa4b8c230946fda633ecbab43143c4124d))
* **Refactor dialog presenter to be more flexible** ([e835558](https://github.com/pharo-spec/Spec/commit/e8355589c1f56eedd37f68887f711cddfe04fa74))
* **New presenter: URL prensenter** ([49f941f](https://github.com/pharo-spec/Spec/commit/49f941fd6587052688b76e546dd824db22a8b615))
* **Introduction of real modals**: Those modals will stop the workflow of the user to force the interaction. Like everymodal everywhere else. ([27289a8](https://github.com/pharo-spec/Spec/commit/27289a8c73a711d18142b8e79d8d1d1d06d82c76))

### Bug fixes

* **#additianalKeybindings is not a value holder** ([547d5f0](https://github.com/pharo-spec/Spec/commit/547d5f09762ae30c965307f2129e4b1db0537241))

### Cleaning

* **Rename composable presenter** ([f29cf68](https://github.com/pharo-spec/Spec/commit/f29cf687d051ce3b75193331225df995cc18b9c5))
* **Remove WindowPresenter title variable** ([6a311e1](https://github.com/pharo-spec/Spec/commit/6a311e1d6d3c46eaab61270365ca5ab9927ed532))
* **Cut cyclic dependencies between Layouts and Core** ([4953967](https://github.com/pharo-spec/Spec/commit/495396701daf71e296db16c605163f23649a7236))
* **Remove deadcode** ([50b2a8c](https://github.com/pharo-spec/Spec/commit/50b2a8ce9693df84a81a0658f192d20b7f476a51))
* **Move all tests to tests packages** ([bae8f4c](https://github.com/pharo-spec/Spec/commit/bae8f4cbc4e9516b43a6634ec46630fb85d8f927))
* **Better about title managment** ([9d91152](https://github.com/pharo-spec/Spec/commit/9d91152c64d0e0b32166d65cb51ab486b945dac1))
* **Clean the interpreter** ([a509654](https://github.com/pharo-spec/Spec/commit/a50965405e37998e2bf321140ba4fab2f351202d) and [6587836](https://github.com/pharo-spec/Spec/commit/6587836cc38e0e3d753729e7d1085b883d924dab))
* **Clean tests** ([073ed26](https://github.com/pharo-spec/Spec/commit/073ed26c4115078bb237789596167666cf173ffa))
* **Remove SpecLayout>>selector** ([7e1d283](https://github.com/pharo-spec/Spec/commit/7e1d28359c53d43918a4aea5ef2167124ce14883))
* **Ensure presenter are not directly linked to MorphcAdapters** ([bc63f1c](https://github.com/pharo-spec/Spec/commit/bc63f1ca06a5fd652b7762bcfb46c1f862fc09cf))
* **Deprecate instantiateModels: for instantiatePresenters:** ([8bd78cc](https://github.com/pharo-spec/Spec/commit/8bd78ccfb79f04e7f0d618cfea3b5c7e2246811e))
* **Layouts now stores objects instead of arrays** ([2b35bc4](https://github.com/pharo-spec/Spec/commit/2b35bc454a722c549c7a531e03f785abf064cfa9))
* **Remove Spec table layout since Spec layout has the same behavior** ([103a827](https://github.com/pharo-spec/Spec/commit/103a827a88fc533a234d3f7a74fcdda60bf53de1))
* **Remove references to `Smalltalk ui theme`** ([b37dd2a](https://github.com/pharo-spec/Spec/commit/b37dd2afffb12adf1daa2d6b4ea6a0091e5b1239))
* **Remove Object>>isSpecAdaptor** ([1664920](https://github.com/pharo-spec/Spec/commit/1664920c4a16dbe7489e17f95ac0d5e115b9b90d))
* **Rename #ghostText into #placeholder** ([639e7e5](https://github.com/pharo-spec/Spec/commit/639e7e5f97f25126f219e780c385e0bdc7a72f09))
* **Clean windows/dialogs opening mechanism** ([39ce96a](https://github.com/pharo-spec/Spec/commit/39ce96accf02835aea2d607fa4eac25217e41572))

### Infrastructure

* **Enable TravisCI** ([8208767](https://github.com/pharo-spec/Spec/commit/8208767590371c5ce4e6938f0f79d6cea601fca8))
* **Add dependencies between packages** ([b655505](https://github.com/pharo-spec/Spec/commit/b655505c32533a18860a1e26819d7f93ef2e212a))
* **Make Spec loadable in non interactive mode** ([0411400](https://github.com/pharo-spec/Spec/commit/0411400b7aa6507d857ee7114964c5ff1c287d92))
* **Register Spec demo in the Help menu** ([d36d2ed](https://github.com/pharo-spec/Spec/commit/d36d2ed6b0804ac1171014d7a1b519bb6febcc74))
* **Add source code in Tonel format to demos** ([648a681](https://github.com/pharo-spec/Spec/commit/648a6813a09c23a64ff8b3bf98b15ff14a182e15))

**Comment by MarcusDenker** [comment]
I think we can close this issue?
