### ISSUE TITLE
VM version is hardcoded in the bootstrap

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2130]
Currently, the VM to download during the bootstrap is hardcoded to be the stable VM for Pharo 7. 

I think it should not hardcode the `70` because for Pharo 8 we will need the one for `80`.

Here is where it is hardcoded: https://github.com/pharo-project/pharo/blob/Pharo7.0/bootstrap/scripts/2-download.sh#L33

**Comment by jecisc** [comment]
In the same idea, the pharo.version file generated is also hardcoded:

https://github.com/pharo-project/pharo/blob/Pharo7.0/bootstrap/scripts/4-build.sh#L225

**Comment by estebanlm** [comment]
not hardcoded anymore, but for now forced to answer "70" anyway (because there is no "80" yet)
