### ISSUE TITLE
Rubric cleaning

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2138]
In rubric a paragraph can be decorated by decorators. 
The trick is that a paragraph is the last one of the chain. 

Current implementation use tricks such as 

doesNotUnderstand: aMessage
	^ [ aMessage sendTo: next ]
		on: MessageNotUnderstood
		do: [ super doesNotUnderstand: aMessage ]

or this 

paragraph
	"this method is here to find the paragraph in the chain, instead of relying on implementing #doesNotUnderstand: !!!"

	| p |
	p := next.
	[ p  isNotNil and: [ p isKindOf: RubParagraph ] ] whileFalse: [ p := p next ].
	^p
	
Terribly ugly!

A nicer solution is to define all the used methods as 
RubParagraphDecorator >> selectionStop
     next selectionStop

This way no magic. The tools and the reader can understand and this is more important. 
The price to add a stupid method per paragraph method that is adapted is smaller than 
mystifying the reader and maintainer.

**Comment by jecisc** [comment]
Maybe we could change `doesNotUnderstand:` to compile methods instead of forwarding the messages, use the image, launch all rubric tests and commit all the compiled methods after a review of which ones make sense as a first step.

**Comment by Ducasse** [comment]
I would do it simply by hand because there are 10 methods and I can see what I'm doing. 
May be I should even do it for Pharo 70 because this code sucks too much.

**Comment by jecisc** [comment]
I'm not sure it's a good idea because this is more interesting for future developments, and developments will soon be in Pharo 8. So there is not much gain to do it in P7 instead of early P8. Also, we already introduced a lot of regressions (failing tests, rubric problems, windows shortcut are broken...) those past weeks. If we want to release in January, it might be better to stick to bug fixes :)

**Comment by Ducasse** [comment]
Yes you are right. I'm just feed up buy the "technical debt" we carry. And it makes a lot of code more difficult to understand. I should not have integrated the changes of Alain :( 
Let's us see if he reacts. Else we will have to remove it. I'm doing my best to fix the glitches but this is super boring.

**Comment by Ducasse** [comment]
This is also why we should have a P8alpha because else we cannot say to people "oh come back in february to improve Pharo" or just work on your own project. The release of P7 is definitively far too long.

**Comment by hilaire** [comment]
Is it still of interest?

**Comment by hilaire** [comment]
Do we have a rational, even very basic, about Rubric?

**Comment by Ducasse** [comment]
yes the idea was to replace Texeditor waiting for a better one

**Comment by ackerleytng** [comment]
Was poking around Rubric to fix comments and I was having trouble understanding Rubric.

Also @kasperosterbye I saw your [comment](https://www.mail-archive.com/pharo-users@lists.pharo.org/msg36731.html). If anyone is able to provide some understanding of the direction of where Rubric is going it would be great!
