### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2139]
For the infrastructure, we can use GitHub to define some issue templates. For example, we can have a template for bug report where we can ask for the OS, Pharo version, VM version, etc and explain how to get the informations.

**Comment by estebanlm** [comment]
I do not want something too bureaucratic, honestly. 
how do you think this template could be?

**Comment by MarcusDenker** [comment]
With the old issue tracker people ignored the template always.
