### ISSUE TITLE
RB classes should not hardcode class rewriter and searcher....

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2146]
We should reduce the number of references to `RBParseTreeRewriter` and `RBParseTreeSearcher`

**Comment by Ducasse** [comment]
I will have a look but I think that I did several passes already.

**Comment by guillep** [comment]
Pharo 90 commit 177a16763fb410ad36cc119cb499b004a3622536.

`RBParseTreeRewriter` has 62 references
`RBParseTreeSearcher` has 58 references

**Comment by LaurineDargaud** [comment]
Working on it
