### ISSUE TITLE
acceptTextMorphs is super ugly

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2148]
acceptTextMorphs
    "Accept any text morphs except for those that have no edits."
self allMorphs do: [:p |
        ((p respondsTo: #accept) and: [
            (p respondsTo: #hasUnacceptedEdits) and: [
                p hasUnacceptedEdits]]) ifTrue: [p accept]]

This marvellous code states that the text editor of a dialog must have an #accept method.
adding it to RubPluggableTextMorph fixes the issue

The solution is to have an explicit instance variable pointing to the right object.
allMorphs is domeed 

Stef

**Comment by jecisc** [comment]
I wonder if we should take the time to work on RubPluggableTextMorph for now since we want to remove it (It's a transition class)
