### ISSUE TITLE
Revise extensions made to RBProgramNode

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2150]
Some extensions made to the ProgramNode hierarchy would benefit to be put back in the node class package. 
For example:
- methodProperty* 
- allSequenceNodes
- addPragma:
- reverseNodesDo: aBlock 
- traversalIndexOf: aNode
- nodeAtTraversalIndex:
- statements
- asSequenceNode
- asPragma
- removeNode: aNode
- leftmostChainReceiver
This will also allow to write tests in isolation, because I'm quite sure such extensions methods are
not the subject of tests.

**Comment by Ducasse** [comment]
PR https://github.com/pharo-project/pharo/pull/2391

**Comment by MarcusDenker** [comment]
PR was merged
