### ISSUE TITLE
Enable the stack coloring 

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#2155]
The stack coloring in the debugger should be enabled by default

**Comment by pavel-krivanek** [comment]
the setting should contain the description of the colors too.

Blue = same class
Purple = same package

**Comment by jecisc** [comment]
+1

**Comment by estebanlm** [comment]
we are removing glamour. 
which means we need to reimplement the debugger UI using spec.
But we should be able to have similar behaviour with the revamped spec debugger :)
