### ISSUE TITLE
PrettyPrinter eats space on large selectors

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2159]
asRingDefinitionWithMethods: methodsBoolean withSuperclasses: supersBoolean withSubclasses: subsBoolean withPackageKeys: packageKeys in: aRGSlice

When method signatures on multiple lines is on
=>

we obtain
asRingDefinitionWithMethods: methodsBooleanwithSuperclasses: supersBooleanwithSubclasses: subsBooleanwithPackageKeys: packageKeysin: aRGSlice

the parameters are glued with the next selector part.

**Comment by Ducasse** [comment]
This is related to the fact that characterSeparatorMethodSignatureFor: returns a block
and that with the issue 2158 it is sometimes or not executed. 

characterSeparatorMethodSignatureFor: aMethodNode
	^ [ 
	(self needsMethodSignatureOnMultipleLinesFor: aMethodNode)
		ifTrue: [ self newLine ]
		ifFalse: [ self space ] ]

**Comment by Ducasse** [comment]
So 

characterSeparatorMethodSignatureFor: aMethodNode
^  (self needsMethodSignatureOnMultipleLinesFor: aMethodNode)
ifTrue: [ self newLine ]
ifFalse: [ self space ]


in conjunction with issue #2158 solves the problem.

**Comment by Ducasse** [comment]
In fact it was not the case. It was change I did to correct the use of characterSeparator or something like that but still returning a block when it is a character that is expected is a bad idea.

**Comment by astares** [comment]
https://github.com/pharo-project/pharo/pull/2160
