### ISSUE TITLE
Implement indeterminate progress bar

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2171]
For Spec I am implementing an indeterminate progress bar. I think we should have it directly in Pharo for Pharo 8 and use it when we do not manage the steps instead of having an empty progress bar that does not move.

![2019-01-04_11-54-21](https://user-images.githubusercontent.com/9519971/50685427-71252f80-1019-11e9-8770-700bf4ed8e2b.gif)

**Comment by astares** [comment]
Still valid I guess
