### ISSUE TITLE
Color class>>fromHexString: should remove possible #

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2172]
It is common to define a hex color by beginning with a $# character. 

For example: '#4CAF50'.

If you execute `Color fromHexString: '#4CAF50'` you will currently get an error.

I think we should also be able to manage the case the string begins with a $#

**Comment by estebanlm** [comment]
not sure about this. 
this is not "common", is just HTML notation.

**Comment by jecisc** [comment]
From what I read the hexadecimal notation was introduced for the web. So, if we have a method to create a color from its hexadecimal notation I guess we should be able to parse '#4CAF50' no?

The oldest documentation I find on this notation is the CSS spec.
