### ISSUE TITLE
Add #withoutDuplicates in Collections?

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2174]
Sometimes I need to remove the duplicated entries of a collection, but I want to keep the same kind of collection, so #asSet is not what I need. Currently, I have things like `anArray asSet asArray` in my code. 

Maybe we could have a method #removeDuplicates in Collections? Or do we already have something like that?

**Comment by simonfranz** [comment]
But it should be a little bit cleverer. If you create a Set from an OrderedCollection you will loose your sequence of the objects.

**Comment by MarcusDenker** [comment]
I propose to do it step by step: first add something as simple as "asSet asArray", then improve it

**Comment by dionisiydk** [comment]
It would be better to name it copyWithoutDuplicates to be consistent to other copy methods
