### ISSUE TITLE
Character>>#isSpecial is not complete

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#2175]
the method Character>>#isSpecial defines following possible characters allowed in binary symbols: 

+-/\*~<>=@,%|&?!

This list is not complete because the RBScanner class>>#initializeClassificationTable adds several other possible binary characters:

± · × ÷

It needs to be synchronized.

**Comment by MarcusDenker** [comment]
maybe Character could have a method that returns a string with all special characters... but this one fixes the problem for now
