### ISSUE TITLE
contrastingColor and contrastingForegroundColor should be merged and renamed

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2184]
contrastingColor
    "Answer black or white depending on the luminance."

    self isTransparent ifTrue: [ ^ self class black].
    ^self luminance > 0.5
        ifTrue: [self class black]
        ifFalse: [self class white]
                
should be named contrastingBlackAndWhiteColor because there is no notion of contrast.
    
    
contrastingForegroundColor and contrastingColor looks the same

contrastingForegroundColor
        "Make a foreground color contrasting with me"
        ^self luminance >= 0.5
                ifTrue: [self class black]
                ifFalse: [self class white]

contrastingForegroundColor should be removed and contrastingColor should be renamed contrastingBlackAndWhiteColor

**Comment by psteeve** [comment]
@Ducasse Hi, this issue should be closed i think.
