### ISSUE TITLE
Color >> storeOn: loses precision

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2185]
Color >> storeOn: aStream [
 self isTransparent ifTrue: [^ aStream nextPutAll: '(Color transparent)'].

 aStream
  nextPutAll: '(' , self class name;
  nextPutAll: ' r: '; print: (self red roundTo: 0.001);
  nextPutAll: ' g: '; print: (self green roundTo: 0.001);
  nextPutAll: ' b: '; print: (self blue roundTo: 0.001);
  nextPutAll: ' alpha: '; print: (self alpha roundTo: 0.001);
  nextPutAll: ')'.

]

I don't think this is the best implementation for storeOn:, since it
does lose some precision, and so when evaluated could produce a Color
that is not quite equal to the original Color.

Since all values, r, g, b, and alpha are internally stored as integers,
it would be cleanest to have storeOn: emit those values. However, there
are currently no instance creation methods to create a Color from those
integer values. We could have an instance creation method

rgb: anInteger alpha: anInteger

and that would make it easy.

Alternatively, just not rounding would result in correct behavior, if
less pretty output for human readers. But since the output of storeOn:
is primarily for machines to read, this is less of a concern. So this
would work:

storeOn: aStream
    self isTransparent
        ifTrue: [ ^ aStream nextPutAll: '(Color transparent)' ].
    aStream
        nextPutAll: '(';
        nextPutAll: self class name;
        nextPutAll: ' r: ';
        print: self red;
        nextPutAll: ' g: ';
        print: self green;
        nextPutAll: ' b: ';
        print: self blue;
        nextPutAll: ' alpha: ';
        print: self alpha;
        nextPutAll: ')'

Martin McClure.

**Comment by Ducasse** [comment]
I like the idea to store integers and offers adequate API.

**Comment by svenvc** [comment]
In STON added recently added a similar implementation:

```
stonOn: stonWriter
	| name |
	(self isTranslucent or: [ (name := self name) = #unnamed ])
		ifTrue: [ 
			stonWriter writeObject: self streamMap: [ :map |
				#(red green blue alpha) do: [ :each | 
					map at: each put: ((self perform: each) roundTo: 0.001) ] ] ]
		ifFalse: [ 
			stonWriter writeObject: self listSingleton: name ]
```

At first, I also found it strange to use floats, but it is a way to uncouple the implementation from its abstract/external idea. Storing 4 floats in an integer using limited precision is an optimalization, it is not fundamental to the RGBA idea.

I think that the loss of precision is acceptable, as 0.01 is approximately 1/1023 the maximum internal resolution.
