### ISSUE TITLE
ActiveWorld should be removed

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2192]
This is not used and just bring complexity for nothing. 
And one global less

**Comment by Ducasse** [comment]
SystemNavigation default allGlobalRefsOn: #1410 
26 users so it should be possible to handle it.

**Comment by Ducasse** [comment]
The global world is World.

**Comment by jecisc** [comment]
@estebanlm Since you worked on that part of the system not so long ago, do you agree with the removal of ActiveWorld? Or will it be use with SDL/GTK?

**Comment by estebanlm** [comment]
`ActiveWorld` cannot be removed at the moment. 
What I did is to remove the direct accesses to it (and to `World`).
I think we need to think on remove one or the other and keep just one, but this is so complex that cannot be made without deep consideration.

I would keep this alive because is true, it should not exist. But I do not think this is actionable in the short term (maybe for Pharo 9?)

**Comment by estebanlm** [comment]
is there a way to mark an issue as "do not stale" @MarcusDenker ?
Because I think there will be issues like this, that needs to remain there just to keep them in sight, even if we cannot act immediately.

**Comment by MarcusDenker** [comment]
It can be configured in the config file.

https://github.com/pharo-project/pharo/blob/Pharo8.0/.github/stale.yml

for now it is:

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - pinned
  - security
  - "[Status] Maybe Later"

<blockquote><img src="https://avatars3.githubusercontent.com/u/1838382?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">pharo-project/pharo</a></strong></div><div>The Sources for Pharo. Contribute to pharo-project/pharo development by creating an account on GitHub.</div></blockquote>

**Comment by guillep** [comment]
In Pharo9.0 commit 177a16763fb410ad36cc119cb499b004a3622536.

`ActiveWorld` references are down to 14.

Looking at my latest refactorings, I'm thinking having some mechanism for having an "active world" during render will still be useful in the future.
So I'm for not completely removing it.
I think this issue can be closed with the cleanups I already did.
