### ISSUE TITLE
Build broken for 64 bits

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#22]
Since the introduction of the Unicode tables, the build for 64 bits got broken

https://travis-ci.org/guillep/pharo-core/builds/203456269

**Comment by pavel-krivanek** [comment]
This is strange because till now I only added the tables to the repository but the initialization itself is still not executed.

**Comment by guillep** [comment]
This is apparently happenning not because of the Unicode tables but because a change in the VM.
We were using latest vm because there was no stable version for 64 bits.

If we see the dates of the working and failing jobs, we see that the problem was introduced between the 17 and the 20 of february.

We should pick a fixed VM from here:

http://files.pharo.org/vm/pharo-spur64/linux/

**Comment by guillep** [comment]
I'm doing a bisect. It looks like the broken VM is the one of the 19 of february. The one from 18/02 works fine.

We should probably
 1 - release the one of 18/02 stable
 2 -  report the issue we have to the VM list

I invoke @estebanlm

**Comment by guillep** [comment]
Sorry, I was mistaken the one of 18/02 is already broken. The one that works is definitively the one from 12/02.

http://files.pharo.org/vm/pharo-spur64/linux/pharo-linux-x86_64itimer-201702121843-530863a.zip

**Comment by guillep** [comment]
This is fixed since some time ago
