### ISSUE TITLE
Metalinks are leaving methods with unbound globals

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2201]
To spot the problem just execute the tests of MethodConstantTests, the tests will use method constants that are based on Metalinks. 

Then run the test ReleaseTest>>testMethodsWithUnboundGlobals

You will see some methods with unbound globals. The problem is that they have a literal like `#RFMetaBinding -> [ "aBlock" ]`.

**Comment by estebanlm** [comment]
what happens with this? Still alive?

**Comment by MarcusDenker** [comment]
with https://github.com/pharo-project/pharo/pull/3510 now all these use a special binding (subclass of Association). When the PR is merged I will change the test to skip all special bindings

**Comment by sbragagnolo** [comment]
Still failing. 
@MarcusDenker , What can be done for having this tests working properly?
