### ISSUE TITLE
OCASTTranslator class initialize should not invoke super

### ISSUE THREAD

**Issue by nicolas-cellier-aka-nice** [guillep/pharo-core#2205]
It's a smell!
Only instance side initialize should invoke super.
In this case, this will invoke Object class >> initialize and reset all `DependentsFields`

**Comment by Ducasse** [comment]
Indeed! Tx nicolas!

**Comment by MarcusDenker** [comment]
fixed by 2520

**Comment by MarcusDenker** [comment]
fixed by #2520 2520

**Comment by MarcusDenker** [comment]
merged
