### ISSUE TITLE
Opal: Max number of method arguments

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#2213]
Nicolas writes:

After the existing legacy Compiler implementation in Squeak/Pharo,
I draw the contour of an Opal Compiler variant for compiling methods/messages with more than 15 arguments.
I'am using the single array scheme, but this could be changed easily IMO to 14+excess...

Contrarily to what I wrote in the comment, the VM does NOT crash and I can implement methods and send messages like this

a1: a1 a2: a2 a3: a3 a4: a4 a5: a5 a6: a6 a7: a7 a8: a8 a9: a9 a10: a10
a11: a11 a12: a12 a13: a13 a14: a14 a15: a15 a16: a16 a17: a17 a18: a18 a19: a19 a20: a20
    ^(a1+a2+a3+a4+a5+a6+a7+a8+a9+a10) + (a11+a12+a13+a14+a15+a16+a17+a18+a19+a20)

testSend
    ^(self 
        a1: 1 a2: 2 a3: 3 a4: 4 a5: 5 a6: 6 a7: 7 a8: 8 a9: 9 a10: 10
        a11: 11 a12: 12 a13: 13 a14: 14 a15: 15 a16: 16 a17: 17 a18: 18 a19: 19 a20: 20) = (20*21/2)

Playground: TestManyArgs new testSend. -> true

Find it here:
http://www.squeaksource.com/Smallapack/Smallapack-OpalCompiler-nice.1.diff

It would be nice to re-integrate these tricks in Pharo8 once stable.

**Comment by nicolas-cellier-aka-nice** [comment]
Side note:  I based those developments on Pharo6 because I want to support Smallapack on both Pharo6 and Pharo7.
Pharo7 has too many changes at once for Smallapack which depends on legacy Compiler + legacy FFI.
So a review will be necessary to make sure to not introduce regression from Pharo6, especially for the Reflective implementation.

**Comment by nicolas-cellier-aka-nice** [comment]
For making a FFI call from within a method with more than 15 arguments, another patch is necessary.

http://www.squeaksource.com/Smallapack/Smallapack-UnifiedFFI-nice.1.diff

**Comment by astares** [comment]
still valid

**Comment by MarcusDenker** [comment]
I close this issue: the solution to hack the compiler is not good. The idea is that the bytecode that we emit should be as close as possible to the model of the VM.

That is, to support more parameters, we should extend the bytecode. (the new bytecode set might already support it)

But: We had no people reporting problem with number of arguments since
