### ISSUE TITLE
Fuel Version number is incorrect for the code present in Pharo 6+

### ISSUE THREAD

**Issue by theseion** [guillep/pharo-core#2224]
Migrated from https://pharo.fogbugz.com/f/cases/20405/Fuel-Version-number-is-incorrect-for-the-code-present-in-Pharo-6
//-----

Apparently the integration of Fuel fixes into Pharo never used the configuration. As a consequence the Fuel version number is incorrect.
//-----

PR: https://github.com/pharo-project/pharo/pull/2055
//-----

The pull request for this issue is stuck on GT specific test failures: https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-2055/6/tests/.
The concerned test class is GTSpotterEventCollectorBackwardCompatibilityTest. The tests in that class try to materialize Fuel data created with version 1.9.4 (e.g. #version1). This fails now as I've updated the version number to 3.0.0.

I don't see a direct way to update those methods but what I could do is to reserialize the affected methods and only change the Fuel version number. I think that shouldn't affect GT but I'm unsure what exactly you're testing there. Can I get your feedback on this please?
//-----

The test ensures that events recorded with previous versions are still analyzable in newer versions.

@JurajKubelka : could you take a look at this?

**Comment by estebanlm** [comment]
@theseion What's the status of this?

**Comment by theseion** [comment]
The PR was integrated but neither Juraj nor Doru ever got back to me. I assume everyone's happy :)
Let's close the issue. I'm sure someone will open another one if they think something's wrong.
