### ISSUE TITLE
Fix bugs in ZipFileSystem

### ISSUE THREAD

**Issue by theseion** [guillep/pharo-core#2227]
Migrated from https://pharo.fogbugz.com/f/cases/14106/Fix-bugs-in-ZipFileSystem
//-----

> - add `ZipFileSystem` specific tests
> - resolve issues with lazily accessing members and writing members (e.g. existing member should probably not be writable)
> - fix MNU when trying to write to a new member:
> ```smalltalk
> | zipFile zip |
> zipFile := FileSystem memory workingDirectory / 'test.zip'.
> zip := (FileSystem zip: zipFile) open.
> zip / 'sample.txt'
> writeStreamDo: [ :stream |
> stream nextPutAll: 'test' ];
> yourself.
> zip workingDirectory files first readStreamDo: [ :s | s contents ]
>```

**Comment by theseion** [comment]
(Vincent Blondeau)
//-----

Maybe we should change *Archive classes in the Compression package to support the memory file system?

**Comment by theseion** [comment]
That's not a bad idea. The Zip implementation is pretty fixed on MultiByteFileStream (I think) and doesn't allow to change the stream easily. That also makes it impossible to use them with a memory file system.

If you want to work on that I suggest you open another issue to track that effort separately.

**Comment by theseion** [comment]
Still relevant.

**Comment by demarey** [comment]
Does #4401 solve the issue?
With this one, all zip tests are now done in a memory file system

**Comment by theseion** [comment]
IDK. I'll check.

**Comment by theseion** [comment]
Writing to a new member without explicitly adding a member still fails with an MNU. I'll open a separate issue.
