### ISSUE TITLE
FileException on FLSerializer serialize: toFileNamed:

### ISSUE THREAD

**Issue by theseion** [guillep/pharo-core#2228]
Migrated from: https://pharo.fogbugz.com/f/cases/18832/FileException-on-FLSerializer-serialize-toFileNamed
//-----

(Davide Varvello)
//-----

There is an issue with Fuel evaluating:
```smalltalk
FLSerializer serialize: 'whatever' toFileNamed: 'demo.fuel'.
```

The stacktrace is:
```smalltalk
File>>openForWrite:
File>>openForWrite
File>>writeStream
File>>writeStreamDo:
FLPharo5Platform>>fileNamed:writeStreamDo:
FLSerializer>>serialize:toFileNamed:
FLSerializer class>>serialize:toFileNamed:
```

You can reproduce downloading the Pharo5 oneclick image http://files.pharo.org/platform/Pharo5.0-mac.zip and evaluating 
```smalltalk
FLSerializer serialize: 'whatever' toFileNamed: 'demo.fuel'
```
in playground

**Comment by theseion** [comment]
(Martín Dias)
//-----

Couldn't reproduce here. However, two differences: I have ubuntu instead of mac, and I download pharo this way:

`curl get.pharo.org/50+vm | bash`

could you try this in command line? maybe your vm was wrong?

**Comment by theseion** [comment]
Not reproducible.

**Comment by theseion** [comment]
The bug is always there.
To reproduce you have:
1) to download  the Pharo5 oneclick image http://files.pharo.org/platform/Pharo5.0-mac.zip
2) to evaluate  `FLSerializer serialize: 'whatever' toFileNamed: 'demo.fuel'` in a playground

as already shown. I'm not aware of other versions nor platforms

**Comment by theseion** [comment]
Thanks for the update. Unfortunately, I have Sierra installed on my machine so I can't open the Pharo 5 all in one. I'll try to find another way to reproduce the problem.

Can you give me a bit more information?
- to what location do you download / unpack?
- do you launch by double clicking or via terminal?
- which version of OS X are you using?

**Comment by theseion** [comment]
(Sven Van Caekenberghe)
//-----

This is a bug in File (the class), not Fuel. Looks like case https://pharo.fogbugz.com/f/cases/19227/

This does work on Pharo 5: 
```smalltalk
  FLSerializer serialize: 'whatever' toFileNamed: '/tmp/demo.fuel'.
```
But indeed not the example given (no absolute path).

**Comment by theseion** [comment]
If it is, then this is probably a manifestation of case https://pharo.fogbugz.com/f/cases/18143/

**Comment by theseion** [comment]
There are actually to separate issues at play here. The first one is App Translocation on macOS: a resource that has been downloaded and unzipped automatically will reside on a read-only file system until *actively* moved by the user. Hence, no files can be created within the app structure (e.g. within the image directory). See for example https://eclecticlight.co/2016/06/16/macos-sierra-will-break-many-installers-and-updaters/.

The second issue might be the linked issue with `File` and relative paths.

Incidentally, the second failure also happens for Pharo 7.
1. Download the latest VM from https://bintray.com/opensmalltalk/vm/cog
2. Move the VM manually to escape the App Translocation jail
3. Drag an image onto the VM to open
4. Evaluate `FLSerializer serialize: 'whatever' toFileNamed: 'demo.fuel'.`

**Comment by estebanlm** [comment]
@theseion what's the issue here? I fail to understand.

**Comment by theseion** [comment]
I'd have to check whether this still happens with current builds but am pretty sure that it will still be an issue for Pharo 6 (there's not much we can do for Pharo 6 anyway I think).

**Comment by theseion** [comment]
This issue remains. It appears that the trouble lies with the working directory that is set when the image is opened through drag and drop (I've talked about this with Guille on the mailing list once IIRC).

**Comment by theseion** [comment]
As this doesn't happen with launcher or when opened via command line I'll close this. If it's important enough, someone will complain ;)
