### ISSUE TITLE
SizeInMemoryTest has some failures on 64-bit

### ISSUE THREAD

**Issue by theseion** [guillep/pharo-core#2232]
Migrated from https://pharo.fogbugz.com/f/cases/20106/SizeInMemoryTest-has-some-failures-on-64-bit
//-----

(Sven Van Caekenberghe)
//-----

SizeInMemoryTest has some failures on 64-bit

**Comment by theseion** [comment]
See https://github.com/pharo-project/pharo/issues/2231

**Comment by theseion** [comment]
(Alexandre Bergel)
//-----

This issue is related to an incorrect test. However, it is not clear if `Object>>#sizeInMemory` is  properly defined. 
On 32 bits, the expression `(Array new: 10) sizeInMemory` returns 48. However, it returns 56 on 64 bits. What is the size of an array slot on 64 bits? Is it 4 or 8 bytes?

**Comment by theseion** [comment]
(Sven Van Caekenberghe)
//-----

Since `#sizeInMemory` gives different results depending on 32/64 bits, I guess at least some effort was done there.

Yes it is probably a test problem.

I think an Array slot is a pointer is 64 bits, 8 bytes, 1 wordSize.

**Comment by theseion** [comment]
(Pavel Krivanek)
//-----

What is the current status?

**Comment by theseion** [comment]
Still open (`#testSizeInMemoryCompactClasses` fails for both 32 and 64-bits).

**Comment by theseion** [comment]
Still relevant.

**Comment by MarcusDenker** [comment]
I have run the tests and they are green (one is skipped).

**Comment by theseion** [comment]
Okay, thanks.
