### ISSUE TITLE
#name was sent to nil

### ISSUE THREAD

**Issue by hilaire** [guillep/pharo-core#2239]
THERE_BE_DRAGONS_HERE
#name was sent to nil
14 January 2019 8:33:02.782205 pm

VM: unix - x86_64 - linux-gnu - CoInterpreter VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan 10 2019
StackToRegisterMappingCogit VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan 10 2019
VM: 201901100922 https://github.com/OpenSmalltalk/opensmalltalk-vm.git Date: Thu Jan 10 10:22:25 2019 CommitHash: 58ffe032 Plugins: 201901100922 https://github.com/OpenSmalltalk/opensmalltalk-vm.git

Image: Pharo7.0.0rc1 [Build information: Pharo-7.0.0+rc1.build.117.sha.65868b2ab36e77ebb1db5f750725205e92999116 (64 Bit)]

UndefinedObject(Object)>>doesNotUnderstand: #name
	Receiver: nil
	Arguments and temporary variables: 
		aMessage: 	name
		exception: 	MessageNotUnderstood: receiver of "name" is nil
		resumeValue: 	nil
	Receiver's instance variables: 
nil

[ :each | each includesPackageNamed: aPackage name ] in IceRepository class>>registeredRepositoryIncludingPackage:
	Receiver: IceRepository
	Arguments and temporary variables: 
		aPackage: 	nil
		each: 	IceLibgitRepository(iceberg)
	Receiver's instance variables: 
		superclass: 	Object
		methodDict: 	a MethodDictionary(size 115)
		format: 	65540
		layout: 	a FixedLayout
		organization: 	a ClassOrganization
		subclasses: 	{IceLibgitRepository}
		name: 	#IceRepository
		classPool: 	a Dictionary(#Registry->an OrderedCollection(IceLibgitRepository(ice...etc...
		sharedPools: 	an OrderedCollection()
		environment: 	a SystemDictionary(lots of globals)
		category: 	#'Iceberg-Core'

[ :each | 
(aBlock value: each)
	ifTrue: [ ^ foundBlock cull: each ] ] in OrderedCollection(Collection)>>detect:ifFound:ifNone:
	Receiver: an OrderedCollection(IceLibgitRepository(iceberg) IceLibgitRepository(pharo) IceLibgitRepo...etc...
	Arguments and temporary variables: 
		aBlock: 	[ :each | each includesPackageNamed: aPackage name ]
		foundBlock: 	[ :element | element ]
		exceptionBlock: 	[ nil ]
		each: 	IceLibgitRepository(iceberg)
	Receiver's instance variables: 
		array: 	an Array(IceLibgitRepository(iceberg) IceLibgitRepository(pharo) IceLibg...etc...
		firstIndex: 	1
		lastIndex: 	31

OrderedCollection>>do:
	Receiver: an OrderedCollection(IceLibgitRepository(iceberg) IceLibgitRepository(pharo) IceLibgitRepo...etc...
	Arguments and temporary variables: 
		aBlock: 	[ :each | 
(aBlock value: each)
	ifTrue: [ ^ foundBlock cull: each ] ]
		index: 	1
	Receiver's instance variables: 
		array: 	an Array(IceLibgitRepository(iceberg) IceLibgitRepository(pharo) IceLibg...etc...
		firstIndex: 	1
		lastIndex: 	31

OrderedCollection(Collection)>>detect:ifFound:ifNone:
	Receiver: an OrderedCollection(IceLibgitRepository(iceberg) IceLibgitRepository(pharo) IceLibgitRepo...etc...
	Arguments and temporary variables: 
		aBlock: 	[ :each | each includesPackageNamed: aPackage name ]
		foundBlock: 	[ :element | element ]
		exceptionBlock: 	[ nil ]
	Receiver's instance variables: 
		array: 	an Array(IceLibgitRepository(iceberg) IceLibgitRepository(pharo) IceLibg...etc...
		firstIndex: 	1
		lastIndex: 	31

OrderedCollection(Collection)>>detect:ifNone:
	Receiver: an OrderedCollection(IceLibgitRepository(iceberg) IceLibgitRepository(pharo) IceLibgitRepo...etc...

**Comment by estebanlm** [comment]
a little bit of context to reproduce it would be good :)

**Comment by dionisiydk** [comment]
Hi Esteban. It is on the fogbugs page

ср, 16 янв. 2019 г., 7:53 Esteban Lorenzano notifications@github.com:

**Comment by dionisiydk** [comment]
I thought it is the thread "select is sent to nil". But I think it can be
related

ср, 16 янв. 2019 г., 9:07 Denis Kudriashov dionisiydk@gmail.com:

**Comment by estebanlm** [comment]
Fogzbugz page link?

**Comment by estebanlm** [comment]
link to the thread?

**Comment by StephanEggermont** [comment]
https://pharo.manuscript.com/f/cases/22896/Creating-methods-in-a-subclass-with-a-class-using-a-trait

**Comment by hilaire** [comment]
I post on the user list some more info

Le 16/01/2019 à 08:53, Esteban Lorenzano a écrit :
> a little bit of context to reproduce it would be good :)

-- 
GNU Dr. Geo
http://drgeo.eu

**Comment by bencoman** [comment]
> I post on the user list some more info 

That won't mean much in a couple of months.  I got the link...
http://forum.world.st/select-was-sent-to-nil-td5093510.html

**Comment by guillep** [comment]
Latest Pharo7 should have a fix for it. Can someone confirm if the problem is gone or not?

**Comment by hilaire** [comment]
Is this build the candidat to test: build: 131, commit: 84b2e38 ?

Le 21/01/2019 à 17:49, Guille Polito a écrit :
> Latest Pharo7 should have a fix for it. Can someone confirm if the
> problem is gone or not?

-- 
GNU Dr. Geo
http://drgeo.eu

**Comment by hilaire** [comment]
I confirm the issue is gone.

Le 21/01/2019 à 17:49, Guille Polito a écrit :
> Latest Pharo7 should have a fix for it. Can someone confirm if the
> problem is gone or not?

-- 
GNU Dr. Geo
http://drgeo.eu
