### ISSUE TITLE
Model step related methods should be extensions from Morph

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2240]
The Model class currently implements methods for the Morph stepping mechanism. I'm not sure this is right. They should at least be morphic extensions and not directly in Model. (#step, #stepIn:, #stepTime, #wantsSteps, #stepTimeIn:, #wantsStepsIn:)

**Comment by jecisc** [comment]
Still valid.

**Comment by bencoman** [comment]
Does Bloc provide any "step"ing mechanism?  Its a useful convention that maybe shouldn't be thrown away when Morphic is deprecated.  Model seems a good place to hang a UI-independent stepping mechanism for simulations or games - to make it easier to migrate to another UI

**Comment by hilaire** [comment]
So step methods are implemented in three places: Object, Model and Morph.
I am testing on its removal in Object class. Likely will break on some places.

**Comment by guillep** [comment]
No, the fact that `Model` implements methods to interact with `Morphic` stepping mechanism does not mean that those methods should be moved from package. This is a bad move.
