### ISSUE TITLE
Remove step related methods from Object

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2241]
Object implements some methods related to the step mechanism of Morph. Those methods should be removed/push down to Morph. 

Methods:
- stepAt:in:
- stepIn:
- stepTime
- stepTimeIn:
- wantsSteps
- wantsStepsIn:

**Comment by jecisc** [comment]
We could implement a Trait to use by Morph and Model since they have the same API.

**Comment by jecisc** [comment]
Hum... In fact we cannot use Trait because of this issue: https://github.com/pharo-project/pharo/issues/2240

The idea was to put stepping methods as Morph extensions.

**Comment by jecisc** [comment]
Still valid.

**Comment by hilaire** [comment]
Indeed, it is odd it is part of Object class.
Moving it may break third party software compatibility though.
Once the protocol is moved to Morph, how do you inform developer about the compatibility change?

**Comment by astares** [comment]
@hilaire  Over time we can not stay compatible. Otherwise we would not move or change anything.

But we can use the usual way we inform about changes: not removing them first time but keeping the old with an additional deprecating warning. In the next version then really removing them,

**Comment by hilaire** [comment]
I removed the methods from Object. GTPlayground is used as a model but in the Object hierarchy not the Model one... GTPLayground hierarchy is in the Announcer hierarchy too..

**Comment by Ducasse** [comment]
Can you give a more precise report of the results or problems you got?

**Comment by hilaire** [comment]
When removing the step protocol in Object, GTPlayground does not work correctly because it relies on it.
There are likely other classes affected.
It is not clear how it can be refactored. Trait?

**Comment by Ducasse** [comment]
We are rewriting Playground. So the replacement should not expect that any object can understand step.

**Comment by Ducasse** [comment]
I passed the info to esteban because I do not know how to add it to the conversation.

**Comment by estebanlm** [comment]
yup. 
Since the new playground will rely on Spec2 and it will have a different alarm mechanism. 
Still, it will probably still rely on step for the morphic backend, but this will happen just for the morphs, never outside them!

No idea if we should extract the stepping mechanism to a trait and then remove it from Object, or is better just to wait until we have the replacement (that may mean wait until P9).

**Comment by Ducasse** [comment]
Ok I would remove it from Object :) And we can check what break :). I would like to remove the GTPlayground in P8 :)

**Comment by hilaire** [comment]
I have a P8 image with step removed from Object. It breaks GTPlayground and may be other place, not sure. Do you want the commit? May be better to wait the new Playground, no?

**Comment by Ducasse** [comment]
I'm not sure. First we should check the new playground. What we can do is to put the step and related method in a deprecated category. And also put a self deprecated. so that we can get a trace from where the methods are invoked.

**Comment by hilaire** [comment]
I made the change. It gonna hurt a bit!

**Comment by guillep** [comment]
> Object implements some methods related to the step mechanism of Morph. Those methods should be removed/push down to Morph.

Yes, they should be pushed down to Morph.
