### ISSUE TITLE
Propose a UI for the ParseTreeSearcher and Rewriter

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2249]
ParseTreeRewriter is a superb tool. Now it is lacking a tool to help defining and applying the transformations. 
The tool developed by Yuriy should be integrated to such tool.
https://github.com/Uko/MatchTool

**Comment by Ducasse** [comment]
First we should have something super simple:

Package List Selection
or class list selection

one expression

=> a list of method found or a list of method rewrote like in the 
original RB tools

https://refactory.com/tools/refactoring-browser/rewrite-tool

Second we can integrate the tool of Yuriy to help us write some 
patterns.

Third we could add the one mark.

**Comment by StephanEggermont** [comment]
Indeed. Just like the original one is good enough for now, just make sure it is clear on which scope it is applying. I need it when fixing Issue #2974 to see which messages are sent to streams.

**Comment by StephanEggermont** [comment]
still open

**Comment by Ducasse** [comment]
Yes I should try to find some times to migrate yuriy's tool first.

**Comment by Ducasse** [comment]
This is what Sebastian is doing and this is really nice. 
In spec2 and we should review his code and integrate it to NewTools.

**Comment by Ducasse** [comment]
This is done we should integrate in new tools the version done by Sebastian Jordamont.

**Comment by MarcusDenker** [comment]
There is some tool in the system... which needs improvement, but that is another issue.
