### ISSUE TITLE
Enhance RBParseTreeRewriter class comment to show 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2250]
we should add an example showing how to install a transformed method.

| rewriter node method |
rewriter := RBParseTreeRewriter new.
rewriter replace: 'self shouldnt: [re compile] raise: Error' with: 'self compileIsOK'.
method := (ReTest>>#testNewSuite3test10).
node := method parseTree.
(rewriter executeTree: node)
	ifFalse: [ ^ self ].
method origin 
	compile: node formattedCode 
	classified: method protocol

**Comment by Ducasse** [comment]
https://github.com/pharo-project/pharo/pull/2288

**Comment by MarcusDenker** [comment]
this was merged
