### ISSUE TITLE
Leftover Halts

### ISSUE THREAD

**Issue by dupriezt** [guillep/pharo-core#2254]
There are leftover halts in pharo, sometimes for good reasons like checking the behaviour of halts, sometimes because they were forgotten or used for other purposes than debugging.

Halts used on purpose should be marked with a pragma so as to not be flagged by the breakpoint browser tool. Other halts should be removed or replaced by other constructs.

**Comment by guillep** [comment]
This issue should have been open in fogbugz.
I've created one https://pharo.manuscript.com/f/cases/22898/Removing-leftover-halts

This is fixed in https://github.com/pharo-project/pharo/pull/2255
