### ISSUE TITLE
Character>>#printOn: has decompiled source

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#2256]
the method `Character>>#printOn:` has only the decompiled code so the real argument name and temporaries are lost. 

arg1 = aStream
tmp1 = name

**Comment by guillep** [comment]
Moved issue to https://pharo.manuscript.com/f/cases/22899/Recover-parameter-names-remove-unneeded-temps-in-Character

Will integrate it in Pharo7
