### ISSUE TITLE
Running Iceberg causes an invalid memory access.

### ISSUE THREAD

**Issue by mrakgr** [guillep/pharo-core#2258]
While holding down Ctrl and then pressing P then O then I causes a white box to show at the bottom with `LoadLibrary(SurfacePlugin.dll) (998: Invalid access to memory location.`. Also a window titled `Iceberg Repositories` opens. I am new to Pharo so my keypressing is erratic. I have no idea what the combination I just did should be doing, but it is probably not a memory error.

---

Pharo 6.1, Windows 10 using the `Pharo image(stable)` template. I got it today.

**Comment by mrakgr** [comment]
Just opening it from World is enough to trigger it.

**Comment by estebanlm** [comment]
can you verify in Pharo 7?
Iceberg changed far to much between Pharo 6.1 and Pharo 7 to actually have something useful to fix there :)

**Comment by mrakgr** [comment]
In Pharo 7(64-bit) the error is not occurring.

**Comment by bencoman** [comment]
@mrakgr My understanding was that Iceberg was only a technology-preview in Pharo 6.
Not sure about the value/effort of fixing this in Pharo 6 now that Pharo 7 is released. 
Would you be happy for this issue to be closed?

**Comment by mrakgr** [comment]
Sure.
