### ISSUE TITLE
DarkTheme depends on Shout!

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2261]
shStyleTable

	^SHRBTextStyler darkStyleTable

and 
UITheme class>> 
...

self class environment at: #SHPreferences ifPresent: [ :shPreferences |
		shPreferences setStyleTable: aUITheme shStyleTable ].
...

There is something wrong in terms of cyclic references.

**Comment by estebanlm** [comment]
well, technically... all UITheme has it :)
