### ISSUE TITLE
Should fix users of RGCommentDefinition

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2264]
There are still users of RGCommentDefinition. We should rewrite them.

**Comment by Ducasse** [comment]
There is also RGMethodDefinition

**Comment by MarcusDenker** [comment]
rewrite to what?

**Comment by Ducasse** [comment]
Here is what I would do
- introduce a simple class to represent dead method with a polymorphic API. 
- Then rewrite the users of RGMethoddefinition

And later we should check how to use RG2 instead of Ring.

**Comment by MarcusDenker** [comment]
still needs to be done

**Comment by guillep** [comment]
This is a small project in itself. It requires defining a comment model, replace all usages, think about dependencies.
We should move it to a wiki page with ideas.
