### ISSUE TITLE
Set the new blockclosure

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2268]
We should enable the new blockclosure. 
No idea how to do it but it should be somewhere.

**Comment by jecisc** [comment]
This is in `CompilationContext class>>optionsDescription`. 
I guess the - should be a +

**Comment by Ducasse** [comment]
I wanted to see if the new blockclosure encoding is working in P8. 
Related to https://clementbera.wordpress.com/2016/06/27/fullblockclosure-design/

Now I was wondering if this is the EncoderForV3PlusClosures. At least it does not look compatible with SistaV1.

And I was wondering what is the status of the EncoderForSistaV1

I saw

bytecodeBackend: bytecodeSet
	((self defaultOptions includes: #optionFullBlockClosure)
		and: [ bytecodeSet ~= EncoderForSistaV1 ]) ifTrue: [ 
			^ self notify: 'Operation aborted. Bytecode set incompatible with FullBlockClosure option.' ].
	BytecodeBackend := bytecodeSet

So it looks like indeed this is the Sista encoder.


And I read in the comments of EncoderForV3PlusClosures

An encoder for the V3 bytecode set augmented with the following bytecodes that are part of the full closure implementation.
	138   10001010 jkkkkkkk		Push (Array new: kkkkkkk) (j = 0)
								or	Pop kkkkkkk elements into: (Array new: kkkkkkk) (j = 1)

	140   10001100 kkkkkkkk jjjjjjjj 	Push Temp At kkkkkkkk In Temp Vector At: jjjjjjjj
	141   10001101 kkkkkkkk jjjjjjjj 	Store Temp At kkkkkkkk In Temp Vector At: jjjjjjjj
	142   10001110 kkkkkkkk jjjjjjjj 	Pop and Store Temp At kkkkkkkk In Temp Vector At: jjjjjjjj
	143   10001111 llllkkkk jjjjjjjj iiiiiiii	Push Closure Num Copied llll Num Args kkkk BlockSize jjjjjjjjiiiiiiii
This is an exact duplicate of EncoderForLongFormV3PlusClosures.
Could be a trait (or in Newspeak, a Mixin).
For now we impose upon you to synchronise any and all changes between these two classes.

**Comment by jecisc** [comment]
This is important stale bot.

**Comment by MarcusDenker** [comment]
DONE
