### ISSUE TITLE
WorldState refers to missing class DelayScheduler

### ISSUE THREAD

**Issue by StephanEggermont** [guillep/pharo-core#2283]
WorldState>>innerCyclePause:

**Comment by dupriezt** [comment]
`WorldState>>innerCyclePause:` doesn't exist, but `WorldState>>interCyclePause:`does.
Typo?

**Comment by dupriezt** [comment]
I couldn't find a reference to DelayScheduler in WorldState>>interCyclerPause: ...

**Comment by MarcusDenker** [comment]
there is this:

self flag: 'Issue 14754 - wait2>millisecs is only True for clock rollover. Remove it once DelayScheduler based on microsecondClock - Ben Coman 19.01.2015'.
