### ISSUE TITLE
#highestPriority versus #timingPriority

### ISSUE THREAD

**Issue by bencoman** [guillep/pharo-core#2287]
``Processor>>highestPriority`` and ``Processor>>timingPriority`` both return 80.  There is a mix of use in the system and the former currently doesn't get the benefit of any comment related to performance.  I believe most senders of the former should be changed to latter per the former's own comment. 

An exception might be ``BlockClosure>>valueUnpremptively`` and that could instead call ``priorityLevels``  as a closer semantic to the existing comment of ``highestPriority``.   

The existing ``highestPriority`` could be deprecated with a rewrite rule.

**Comment by jecisc** [comment]
@bencoman Should this stay close or should we reopen it?
