### ISSUE TITLE
Failing tests on Pharo 8

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2293]
We have two failing tests on Pharo 8 related to host window icons. 

Apparently, it might be because VM for Pharo 8 is too old.

Tests:

```
windows-32 / Tests-windows-32 / testHostWindowIcon – Windows32.Graphics.Tests.Primitives.DisplayScreenTest
windows-32 / Tests-windows-32 / testHostWindowIconWrongTypeOfArgument – Windows32.Graphics.Tests.Primitives.DisplayScreenTest
```

**Comment by estebanlm** [comment]
we *think* that's not anymore there. 
Can you verify?

**Comment by estebanlm** [comment]
ah, yes, but you need to update VM :)

**Comment by jecisc** [comment]
I merge the P8 branch in this PR: https://github.com/pharo-project/pharo/pull/2245

Let's see :)

**Comment by jecisc** [comment]
Then I'll need to test at home on my windows.

**Comment by MarcusDenker** [comment]
still failing

**Comment by astares** [comment]
I have them failing too when I use ZeroConf loading latest P8 with latest vm as of today

If CI uses ZeroConf to get the VM then it is reproducible.
