### ISSUE TITLE
Catalog Browser reports projects marked Pharo7.0 "has not been tested for Pharo 7.0.0!"

### ISSUE THREAD

**Issue by PierceNg** [guillep/pharo-core#2296]
Download the 7.0 image. Open Catalog Browser. Choose a project marked "Pharo7.0". (I chose Bootstrap, Community and GlorpSQLite.) Click the tick mark for "Install stable version". A warning pops up - "`project' has not been marked as tested for Pharo 7.0.0! Do you want to continue (installation could fail)?"

The warning comes from `CatalogBrowser>>installStableVersion:onSuccess:` which is raised when `CatalogProject>>isAvailableForCurrentPharo` answers false.

```
CatalogProject>>isAvailableForCurrentPharo
	^ self repositoryName = Smalltalk version
 ```

`self repositoryName` is 'Pharo7.0'. `Smalltalk version` gives 'Pharo7.0.0'.

`self repositoryName`'s 'Pharo7.0' comes from `CatalogProject`'s class-side  `#repositoryURLToNameMappings` and `#createRepositoryURLtoNameMappings`.

A cheap fix is as follows:

```
CatalogProject>>isAvailableForCurrentPharo
	^ self repositoryName = (Smalltalk version allButLast: 2)
 ```

**Comment by MarcusDenker** [comment]
Still relevant
