### ISSUE TITLE
Homebrew Cask

### ISSUE THREAD

**Issue by chrisfinazzo** [guillep/pharo-core#2297]
The URL that Homebrew Cask uses to download the latest version 404's. What is the correct format that should be used? The current state of the Cask is below:

    cask 'pharo' do
    version '7.0'
    sha256 :no_check # required as upstream package is updated in-place
    
    url "https://files.pharo.org/platform/Pharo#{version}-64-mac.zip"
    name 'Pharo'
    homepage 'https://pharo.org/'
    
    app "Pharo#{version}-64.app"
    end

**Comment by SergeStinckwich** [comment]
I think now you need to use PharoLauncher instead: https://files.pharo.org/pharo-launcher/mac 
So I guess you need to update the cask with this URL and remove the PharoLauncher cask.

**Comment by chrisfinazzo** [comment]
@SergeStinckwich OK, will update. I looked at the URL again and it redirects to the same place so I think this should work.

_Small nit_: If there's a less tedious way to figure out redirects, I've yet to find it. URLs are not always readable because people can be dumb sometimes.

**Comment by SergeStinckwich** [comment]
There is a pharo-launcher cask.
Can we close this issue @MarcusDenker ?
