### ISSUE TITLE
Integrate ClassParser

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2299]
We should integrate ClassParser from https://github.com/Ducasse/ClassInfrastructure
Because I'm doing tons of overrides to be able to use Sugs. Now it is not modular anymore. :(

**Comment by dionisiydk** [comment]
Why you want Sugs stuff?
Calypso integration needs to be based on Commander. And I believe it will
be simper to do than sugs way. I will check it

вт, 22 янв. 2019 г. в 20:38, StéphaneDucasse <notifications@github.com>:

**Comment by MarcusDenker** [comment]
this has been done
