### ISSUE TITLE
MCMethodDefinition has inconsistent equal and hash methods

### ISSUE THREAD

**Issue by dionisiydk** [guillep/pharo-core#2305]
MCMethodDefinition>>#= method uses only category and sources for comparison while #hash method checks other properties like #classIsMeta and #className. So you can have two equal methods which will have different hash.

It leads to the possibility to lose source code when saving it with TonelWriter. TonelWriter groups extensions by class using Set to store methods. If you have two equal extensions on instance and class side you will lose one of these methods during commit.
And it is possible that there are other related issues.

**Comment by tesonep** [comment]
You are wrong. 
The equals of MCDefinition is using #description to compare the equality of the objects. 
This #description message is implemented using className, selector and classIsMeta. 
So, the equals is taking care of the state that is used in the hash calculation. 

It is not possible to have a breaking hash in this class.

**Comment by dionisiydk** [comment]
Thank's for looking. I did not expect extra logic behind super #=. Looks quite complicated.
I wonder how it impacts performance because every comparison generates array instance.

**Comment by Ducasse** [comment]
Can you benchmark it denis?
