### ISSUE TITLE
calypso and the inspector have wrong icons

### ISSUE THREAD

**Issue by estebanlm** [guillep/pharo-core#2310]
they are showing the generic window icon while both have icons associated with them

**Comment by pavel-krivanek** [comment]
playground too

**Comment by estebanlm** [comment]
I know :)
I already fixed it. 
Just digging where the hell in Calypso can I modify the message browser to add the correct icon too :P

**Comment by dionisiydk** [comment]
There is special logic to consider Nautilus in image: ClyFullBrowser
class>>#worldMenuOn:. Now it can be simplified.
I thought message browser has correct icon

чт, 24 янв. 2019 г. в 21:04, Esteban Lorenzano <notifications@github.com>:
