### ISSUE TITLE
Strange behaviour in DebugSession>>#pcRangeForContext: (?)

### ISSUE THREAD

**Issue by chisandrei** [guillep/pharo-core#2311]
The current implementation of `DebugSession>>#pcRangeForContext:` is:

```
pcRangeForContext: aContext
	"Answer the indices in the source code for the method corresponding to 
	aContext's program counter value."
	(aContext isNil) ifTrue: [ 
		self terminate.
		 ] ifFalse: [  
	(aContext isDead) ifTrue:
		[^1 to: 0].
	^aContext debuggerMap
		rangeForPC: aContext pc
		contextIsActiveContext: (self isLatestContext: aContext) ]
```

So if the parameter `aContext` is nil the current session is terminated. Calling `terminate` will kill the current interrupted process making the debugger not really usable any more.

Normally `pcRangeForContext:` should just be an accessor method computing the pc range.

Looking at the senders of `pcRangeForContext:` it should be possible to remove the call to `terminate`

**Comment by chisandrei** [comment]
I see it was added as a solution to issue #18391 (https://github.com/pharo-project/pharo/pull/409/files). Still looks strange.

**Comment by MarcusDenker** [comment]
related to https://github.com/pharo-project/pharo/issues/3979
