### ISSUE TITLE
#on:do: contexts added on step through not removed

### ISSUE THREAD

**Issue by chisandrei** [guillep/pharo-core#2312]
When using step through the debugger adds an ` #on:do:` context to catch possible unhandled exceptions. Those contexts are however not removed from the stack when the debugger is opened.

For example, in the debugger below I used `Restart` and one `Step through` action five times. This adds five ` #on:do:`  contexts on the stack.

<img width="958" alt="screen shot 2019-01-23 at 16 49 12" src="https://user-images.githubusercontent.com/3534711/51618833-4569db00-1f2f-11e9-9761-a7e90ab389ad.png">

Using `Step through` in longer debugging sessions can lead to some confusion due to all the added contexts.

**Comment by CafeKrem** [comment]
fix in progress

**Comment by MarcusDenker** [comment]
The on:do: context is added in Context>>#stepToHome: 

We could remove it before the method returns, I guess

**Comment by dupriezt** [comment]
I can still reproduce the issue even after this pull request has been merged into pharo.
