### ISSUE TITLE
Integrates FastTable improvements in Pharo

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2316]
From: https://github.com/SamTheDev/Morphic-Widgets-FastTable

**Comment by jecisc** [comment]
They will probably be needed for Spec improvement.

**Comment by MarcusDenker** [comment]
was this done?

**Comment by jecisc** [comment]
Most of them were. Not all. But the rest is really lower priority so I’ll close the case since we have what is needed for Spec.
