### ISSUE TITLE
The dark age is coming

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#2321]
As a result of switching of themes with every release, we should change the default theme to the dark one again

**Comment by svenvc** [comment]
Finally ;-)

**Comment by estebanlm** [comment]
I said last time we did it and I repeat it now: I do not think a dark theme should be the default for Pharo.
*shrugs* But then you guys go and decide other so...

**Comment by pavel-krivanek** [comment]
I know only about the decision to change themes every new release :-) 
At least it helps to fix issues related to themes. E.g. last time the secondary text selection color was wrong etc.

**Comment by astares** [comment]
Can we switch at the end of P8 release cycle please?

**Comment by pavel-krivanek** [comment]
Personally, I do not care about the theme, but why? Every build should be as close to the final release version as possible.

**Comment by astares** [comment]
Because I have dont have to switch to light theme when getting a new image daily for doing contributings ;)

I know I can use startup scripts - but I often change directories, images, computers and even platforms (Mac, Windows, Ubuntu cloned often in VirtualBox) to find trouble on fresh installs/setups.

At least it would help if we would keep the welcome window open - because then I can click on the theme switching there. 

BTW: Who decided to change themes every new release? I cant remember a discussion on Pharo mailinglist.

**Comment by svenvc** [comment]
We should consider an initial dialog that asks a couple of simple setup questions (theme color, font size, ..). Or maybe the top menu bar could offer a widget to do that quickly.

But then again, there should be no dialogs in a headless image either.

**Comment by astares** [comment]
Doing it the Squeak way with many initial questions to answer? We already integrated quick intro and quick setup points into the initially shown welcome window in a way that it does not get into your way.

Adding a special dialog with questions to answer would be annoying for "start always with fresh image" users and contributors to close or click away. 

Let's focus on the basic question to be answered here: what should be the default theme and when to change it.

**Comment by pavel-krivanek** [comment]
I think that the right place for such settings is the PharoLauncher ;-) 
We will probably keep the welcome window opened so the switching of the theme is single click operation. I think that if we want to switch the theme, we should do it ASAP. 
Anyway, it's bikeshedding...

**Comment by jecisc** [comment]
I also think we should do it ASAP, especially if one of the goals is to fix issues in the theme :)

**Comment by estebanlm** [comment]
I don't like the squeak way :)
It assumes a process that can be good for squeak, but not for us: it assumes you do not creates a new image each time.
Now, of course I can set my open preferences (in fact, I use my own super-dark theme :P @astares you can do the same, no need to do it manually)... but the real question is "does a startup wizard fits with our way of using Pharo?" For me the answer is no :)

**Comment by noha** [comment]
Definitely no. It would be a microsoft kind of way annoying the user the most possible. Is there no way having settings on disk which you change once and in the same directory all images would load them?

**Comment by astares** [comment]
@noha

You can already use the disk, put a startup.sh file into either

System -> Startup -> Version Preference Folder
System -> Startup -> General Preference Folder

then this is used for all images/ or image version (like 6.0 or 7.0 only) 

On a fresh computer it is usually easy to open  these folders from the menu,
use the GT extension button to create a new file startup.sh and note down

```Smalltalk
PharoDarkTheme beCurrent 
```
or 

```Smalltalk
PharoLightTheme beCurrent 
```

This is described in https://marianopeck.wordpress.com/2012/05/12/startuploader-running-startup-scripts-in-pharo/

Side note: currently there is a problem on fresh installations with empty directories as the GT extensions on File references is not displayed. This is discussed in https://github.com/pharo-project/pharo/issues/2338 with a fix (not yet integrated as of today)
