### ISSUE TITLE
The Meta Tab in the debugger shows the class hierarchy too small

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2324]
In the debugger when you flip to the Meta tab to see the class of a variable the displayed list above the filter box is too small even though there is tons of space in the pane (I think a constraint might be missing).

If you resize the window it seems to cause it to resize properly - but its a nuisance.

Platform: P7 (release), OSX

**Comment by macta** [comment]
![image](https://user-images.githubusercontent.com/5553623/51702412-a6ff7780-200b-11e9-888e-6690be69fce2.png)

**Comment by estebanlm** [comment]
Mmm... most probably this will not has sense if we (as expected) replace glamour with spec2.
In any case, this will need to be revisited later.
