### ISSUE TITLE
TonelWriterTest>>#testWriteSnapshotWithoutOrganization failing in Pharo 7.0.1

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#2328]
TonelWriterTest>>#testWriteSnapshotWithoutOrganization is failing in the production Pharo 7.0.1. On Pharo 8 this test was removed

**Comment by estebanlm** [comment]
so maybe we should remove it in P7 too

**Comment by MarcusDenker** [comment]
I think this is now fixed: testWriteSnapshotWithoutOrganization was already removed from Pharo7 but that change was only yesterday put in pharo8
