### ISSUE TITLE
groupedBy does not work for SortedCollection

### ISSUE THREAD

**Issue by dionisiydk** [guillep/pharo-core#2332]
Try following example:
```Smalltalk
(Object methods asSortedCollection: #selector ascending) groupedBy: #methodClass
```

**Comment by MarcusDenker** [comment]
- implement #groupedBy: to retain sortBlock for SortedCollectiob
- simplify sortBlock (new creates size 10 by default)
- turned the example in the issue into a simple test

https://github.com/pharo-project/pharo/pull/3454
