### ISSUE TITLE
doIt in debugger does not variables of receiver when it is not a method class

### ISSUE THREAD

**Issue by dionisiydk** [guillep/pharo-core#2340]
Try open debugger with:
```Smalltalk
(2@3) someMessage
```
Then select DNU context. You will be not able execute doits with x and y of point. Debugger will ask you what these names mean.

**Comment by dionisiydk** [comment]
It looks like right behaviour because otherwise you will be able save the method with variables which it does not see.
But it means that compiling method and doIt scripts should be executed in different "scope". So I think it can be improved.

**Comment by MarcusDenker** [comment]
yes, the doitIn: is compiled somehow for Object, not Point... very strange.

Definitely something wrong.

**Comment by MarcusDenker** [comment]
Hmm... I looked at it and I do not see how to improve it.

=> DoIts are always executed with a nil receiver (for the doit)
=> the reason we can not access "x" is that the method doesNotUnderstand: is in Object
