### ISSUE TITLE
memory leak through "NECController uniqueInstance"

### ISSUE THREAD

**Issue by j-brant** [guillep/pharo-core#2341]
The NECController class uniqueInstance variable can cause temporary memory leaks. If you close a window, the NECController uniqueInstance variable still holds on to objects in the closed window. As an example:

1. Inspect ``Array new: 1234567``. 
2. In the inspector, switch to the Raw tab, and enter ``self yourself. self yourse``. While entering the second "yourself" message send, the completion popup should display. 
3. Close the window after the completion appears. 
4. Execute ``Smalltalk garbageCollect``.
5. Inspect ``ReferenceFinder findPathTo: (Array allInstances detect: [ :each | each size = 1234567 ] ifNone: [^'Array not found']) from: NECController uniqueInstance``.

If there is a memory leak, you'll get the reference path. If there isn't a memory leak, then it shouldn't find the array created in step 1, and should return 'Array not found'. While executing steps 4 & 5, make sure that the completer does not display.

**Comment by maenu** [comment]
Just ran into this. The controller does not properly clean up. Why is a unique instance required? Why not keep a controller per editor/morph/textmodel? That would remove the link to the root and cleaning up would be trivial as it will be garbage-collected when the owning morph/editor/whatever dies?

**Comment by MarcusDenker** [comment]
PR to fix it: https://github.com/pharo-project/pharo/pull/4079
