### ISSUE TITLE
memory leak through GTSnippets instance cache

### ISSUE THREAD

**Issue by j-brant** [guillep/pharo-core#2342]
The GTSnippets class has a class instance variable named "instance" that holds a cache of code that was executed in the inspector for a particular class. This instance has an IdentityDictionary in the snippets variable whose key is a class. If you execute some code in an inspector for a class and later remove the class, you will still have a reference to your removed class. 

As an example:

1. Create a new class named "Foo"
2. Inspect a new instance of Foo -- ``Foo new``
3. Evaluate `self printString` in the Foo inspector
4. Close the inspector
5. Remove the "Foo" class
6. Evaluate ``Smalltalk garbageCollect``
7. Inspect ``GTSnippets instance snippets`` and notice the AnObsoleteFoo class in the dictionary

**Comment by Ducasse** [comment]
Tx john!

**Comment by j-brant** [comment]
The fix for this has been integrated.
