### ISSUE TITLE
Pharo 7 freezes full screen on macOS

### ISSUE THREAD

**Issue by toshiblue** [guillep/pharo-core#2343]
Hello

Experiencing Pharo VM freezing completely when Windows->Toggle Full Screen Mode is selected on macOS 10.14.1 (16 GB, i7)

Using:
Pharo 7.0.1
Build information: Pharo-7.0.1+build.142.sha.b8825954d0dcff883bf4f47ea5c516c9cfc2fe4b (64 Bit)

I'm starting the VM from terminal with:
> ./pharo-ui Pharo.mbs.image
The image is 7 image with some code I'm playing with (newbie).  I've added NeoJson and Mustache so far.

However, when using the native window full screen button (green dot, upper left hand corner)  it does enter into full screen mode with no problem and works fine.  But you lose the ability to come back out of full screen mode, other than Quit the VM.  The native OSX window controls don't respond, and again Toggle Full Screen locks the Pharo VM.

Thank you

**Comment by Ducasse** [comment]
Thanks for the report. 
And of course I cannot reproduce it on my machine I'm on 10.13.6.
We will try on mojave.

**Comment by macta** [comment]
I can reproduce this on OSX 10.13.5 (High Sierra) with Pharo 7.0 stable 32bit. As described, I can go into full screen and start coding. If I mouse up to the top - the OSX menu drops down and I can click the green un-maximise button but pharo doesn't contract down. It does keep running and I can continue coding - however mousing up to the top doesn't bring down the osx menu bar anymore. So you are stuck in that mode.

I also notice that if you go into the world menu | Windows | Toggle full screen mode - it then hangs the image.

**Comment by StephanEggermont** [comment]
Can reproduce with Pharo 8 on 10.14.3
Well known long term issue: https://pharo.fogbugz.com/f/cases/18126/MacOS-Display-toggleFullscreen-cmd-H-makes-screen-black-cmd-opt-esc-kills-vm

The cmd h problem was solved somewhere

**Comment by StephanEggermont** [comment]
When I start the image with a Squeak vm from the 64 bit 5.2, dated 2018-12-14 (download today from squeak.org), I can correctly toggle fullscreen mode, by repeatedly doing: Display toggleFullscreen.

Nobody ever responded to my question if http://forum.world.st/commit-3686-Tobias-Bert-Change-fullscreen-behavior-of-Cocoa-VMs-td4892397.html is relevant for this

**Comment by StephanEggermont** [comment]
It is a VM problem. If I open the Squeak image with the Pharo VM, the bug is reproducable

**Comment by StephanEggermont** [comment]
And it is a regression. With the PharoLauncher VM I have here for Pharo6.1 from 2018-6-28 5.0.201806281256  I can not reproduce

**Comment by StephanEggermont** [comment]
201810222239 works, 201810230536 is broken

**Comment by macta** [comment]
@StephanEggermont loving your detective work on this one - thanks
