### ISSUE TITLE
envversion.sh causes out-of-repository bootstrap to fail

### ISSUE THREAD

**Issue by akgrant43** [guillep/pharo-core#2345]
Recent changes to envversion.sh assume that the bootstrap is being run from within the repository, which is not required (BOOTSTRAP_REPOSITORY can be set to point to the repository).

The solution is to change directory to BOOTSTRAP_REPOSITORY before issuing the git commands, and then change back.

PR to be submitted soon.

**Comment by Ducasse** [comment]
Tx!!

**Comment by akgrant43** [comment]
PR: https://github.com/pharo-project/pharo/pull/2346

**Comment by akgrant43** [comment]
Merged.
