### ISSUE TITLE
Usability: Clicking a tab in Calypso should put keyboard focus in corresponding tab's text editor

### ISSUE THREAD

**Issue by fuhrmanator** [guillep/pharo-core#2349]
I did some TDD this weekend and found it irritating (at least on my Windows version of Pharo 7) that when I create a new method (e.g., test method), the cursor for typing wasn't automatically shifted into the text box of that new method. It seems the focus is still in another place (e.g., the protocol list, the class list, etc.). To start typing the method it requires another click in the text box. Perhaps this is how it's supposed to work, but I find it slows me down (I'm perhaps used to how clicking tabs works in other IDEs such as VS Code or Notepad++).

**Comment by Ducasse** [comment]
Agreed. There are many glitches in calypso. Can you report the issue in Calypso bug entry? I could not find denis in the people that I can assign.

**Comment by fuhrmanator** [comment]
Ok, I will paste it in https://github.com/pharo-ide/Calypso.

**Comment by fuhrmanator** [comment]
Also, others transitioning from Fogbugs may do the same thing I did (that is, report Calypso bugs in pharo-project/pharo not realizing it's under a different GitHub user pharo-ide).
