### ISSUE TITLE
Usability: Find/Replace dialog tab from Find text box should take me to Replace text box.

### ISSUE THREAD

**Issue by fuhrmanator** [guillep/pharo-core#2350]
It's great that selected text shows up in the Find box when I do CTRL-F, but it's disappointing when I type tab and my keyboard focus is on the Regular Expressions check box (at least on Windows 10 with Pharo 7) and I have to hit tab 5 more times to get to Replace. 

![image](https://user-images.githubusercontent.com/7606540/51793847-76643d00-21c7-11e9-8dcc-868d3444e94c.png)

I think most IDEs tab you to the Replace text box, as that's the most likely place you want to go?

**Comment by jecisc** [comment]
I would put the replace input under the find input and the options to the right like in most IDE. 

And for the tab, it would go from find to replace then the options

**Comment by jecisc** [comment]
Still valid

**Comment by marcor** [comment]
Works as expected in Pharo 11 GNU/linux.

Possibly only Windows related, or fixed?

**Comment by fuhrmanator** [comment]
Working as expected in P10 on windows
