### ISSUE TITLE
TAB and SHIFT Tab should be used for Indentation in Pharo editors

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#2351]
See http://forum.world.st/Text-Indentation-in-Pharo-editor-td5059993.html

Currently Pharo still feels like an Alien as we use "Ctrl + Shift + L or Ctrl + Shift + R" for 
Text Indentation in any Pharo editor.

But most of the world (VisualStudio, Eclipse, Notepad/Notepad++, Atom, Brackets, ...) is 
using TAB and SHIFT+TAB for Indentation and Pharo should do that too.

**Comment by astares** [comment]
Original issue was https://pharo.fogbugz.com/f/cases/21826/TAB-and-SHIFT-Tab-should-be-used-for-Indentation-in-Pharo-editors

**Comment by Ducasse** [comment]
Yes now someone has to do it.

**Comment by jecisc** [comment]
Keep
