### ISSUE TITLE
Pharo (VM) not able to run as a (headless) Windows service anymore

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#2352]
The VM for Squeak (and initial Pharo) was able to run headless as a Windows Service.
This is not only useful but often necessary for deploying Pharo (web) services on Windows
platforms. Running as a service allows for easy maintenance (start, stop, backup services,
remote administration, ...).

Usually one would see the Services running on a machine in the Windows Service manager: 
 - click on Windows Start and enter "services.msc"
  (http://www.thewindowsclub.com/open-windows-services)

Unfortunately with current Pharo this deployment option. The "-service" option on the command
line of the Pharo VM as described in

http://wiki.squeak.org/squeak/105

seems lost. Maybe also the others like "-log", "-memory" and "-browserWindow"

Scenario to reproduce:
======================

1. Download latest Pharo Windows VM version
===========================================
1.1. Download http://files.pharo.org/get-files/70/pharo-win-latest.zip
1.2. Extract contents to c:\myservice

2. Download latest Pharo image version 
======================================
2.1. Download http://files.pharo.org/get-files/70/pharo.zip
2.2. Extract contents to c:\myservice
    at the time of this writing this was 
        - Pharo7.0-32bit-52a28a8.image
        - Pharo7.0-32bit-52a28a8.sources
        - Pharo7.0-32bit-52a28a8.changes

3. Start Pharo image the first time
===================================
3.1. Drag the "Pharo7.0-32bit-52a28a8.image" to the VM executable "Pharo.exe" to start Pharo
3.2. Open a Playground and enter

    (ZnServer startDefaultOn: 9091)
        onRequestRespond: [:request | ZnResponse ok: (ZnEntity text: Time now asString )]

3.3. Point your browser to http://localhost:9091/ to verify that the server is running. 
    Hit refresh in the brower to see the time change.

3.4. Click on "Save and Quit" in the world menu to save and close the image
 
4. Start Pharo image a second time
===================================
4.1. Drag the "Pharo7.0-32bit-52a28a8.image" to the VM executable "Pharo.exe" to start Pharo
4.2. Point your browser to http://localhost:9091/ to verify that the server is running. 
    Hit refresh in the brower to see the time change.
4.3. Close the image using "Quit" from the world menu

This step is just to verify that the image starts/runs the webserver when it is started.
    
5. Try to install as a Windows service
======================================
5.1. On Windows click "Start" and enter cmd.exe to open the Windows DOS Console 
5.2. Change the directory using "cd c:\myservice"
5.3. Run

          Pharo.exe -service "PharoService" c:\myservice\Pharo7.0-32bit-52a28a8.image

    on the command line. This brings you into an: "Command line handler failed 1"
    error.

I guess this is due to the restructuring of Pharo command line handling that this 
parameter is not passed to the VM.

 But also the command line with -headless

        Pharo.exe -headless -service "PharoService" c:\myservice\Pharo7.0-32bit-52a28a8.image

does not work and install Pharo in the Windows Service manager (services.msc).
--------------------------------------------------------------------------------------------------------

Just to confirm that it was once working in Squeak:

One can download and take the old Squeak Swiki Server and run it with the "-service" option
easily: http://wiki.squeak.org/swiki/uploads/10/Winterlong.zip without any problem as Windows service.

**Comment by astares** [comment]
Issue moved from https://pharo.fogbugz.com/f/cases/20908/Pharo-VM-not-able-to-run-as-a-headless-Windows-service-anymore to github

**Comment by astares** [comment]
Still necessary and unsolved

**Comment by guillep** [comment]
I've moved this issue to https://github.com/pharo-project/opensmalltalk-vm

Thanks!

<blockquote><img src="https://avatars3.githubusercontent.com/u/1838382?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/opensmalltalk-vm">pharo-project/opensmalltalk-vm</a></strong></div><div>This is the VM used by Pharo. Contribute to pharo-project/opensmalltalk-vm development by creating an account on GitHub.</div></blockquote>
