### ISSUE TITLE
Cleanup DelaySpinScheduler and DelayExperimentalSpinScheduler

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#2354]
- DelaySpinScheduler needs a comment
- DelayExperimentalSpinScheduler is not used, can we remove it?

Issue was migrated from https://pharo.fogbugz.com/f/cases/20510/Cleanup-DelaySpinScheduler-and-DelayExperimentalSpinScheduler to github

**Comment by bencoman** [comment]
These were both removed prior to release of Pharo 7. Should be closed.

**Comment by MarcusDenker** [comment]
Good! I close the issue.
