### ISSUE TITLE
parseKeywordPattern is invoked 10 times when we open a browser (not showing methods)

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2378]
Step to reproduce.

1 add 	Transcript show: '.'; cr.

parseKeywordPattern
	| selector positions args node |
	selector := ''.
	positions := OrderedCollection new: 2.
	args := OrderedCollection new: 2.
	[currentToken isKeyword]
		whileTrue:
			[selector := selector, currentToken value.
			 positions add: currentToken start.
			self step.
			args add: self parseVariableNode].
	node := self methodNodeClass
		selector: selector asSymbol
		keywordsPositions: positions asIntegerArray
		arguments: args.
	Transcript show: '.'; cr.
	node comments: (node comments, args last comments).
	args last comments ifNotEmpty: [ args last comments: #() ].
	^node

2: Spotter SystemNavigation for example.

**Comment by dionisiydk** [comment]
It could highlighting of class template

пн, 28 янв. 2019 г., 15:11 StéphaneDucasse notifications@github.com:

**Comment by Ducasse** [comment]
Hi denis we checked and it does not look related to Calypso but to Spotter.

**Comment by Ducasse** [comment]
What is strange is that the AST cache may be activated because if I open several times the same class I still get the 15 times the parser invoked.
