### ISSUE TITLE
Cleanup DoubleLinkedList packages

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#2383]
Pharo 8.0.0
Build information: Pharo-8.0.0+build.33.sha.a896d6da6b2617aa96aed6d3614402d518d8da4 (64 Bit)

in package Collections-DoubleLinkedList and Collections-DoubleLinkedList-Tests

- lint laments that the test package does violate a rule about using the result of an #add method
  but this is fine - so we should ban that rule for the test class
- so we also need a proper manifest
- class comments are missing
- tag the classes on test and core package equally as well as the manifest

**Comment by astares** [comment]
Fix is in https://github.com/pharo-project/pharo/pull/2384

**Comment by astares** [comment]
still on todo list

**Comment by juliendelplanque** [comment]
Bump, I just used the DoubleLinkedList and this issue is super important.

**Comment by juliendelplanque** [comment]
Can some admin reopen it? @MarcusDenker ?

**Comment by juliendelplanque** [comment]
I see that PR #6022 addressed this issue, maybe it can be closed?

@astares can you confirm?

**Comment by astares** [comment]
For the records: #6022 fixed the issue
