### ISSUE TITLE
Deprecate #allUnreferencedInstanceVariables

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#2387]
- it is broken as it sends #classThatDefinesInstanceVariable: which is not in the image
- it has no senders

We should deprecate it or remove it (as it is broken anyway)

Also: 
Looks like we do not have a Deprecated80 package yet ...

Pharo 8.0.0
Build information: Pharo-8.0.0+build.33.sha.a896d6da6b2617aa96aed6d3614402d518d8da4 (64 Bit)

**Comment by jecisc** [comment]
Usually, we create the package DeprecatedXX at the same time as the first deprecation.

**Comment by Ducasse** [comment]
I created an issue to create Deprecated80

**Comment by astares** [comment]
classThatDefinesInstanceVariable: is available in latest Pharo 8.0.0
Build information: Pharo-8.0.0+build.77.sha.288ddc33392d8dde76d9db8cb4b2994776cc042a (64 Bit)

So the #allUnreferencedInstanceVariables is working again. No need to deprecate
