### ISSUE TITLE
Should the RBMethodNode extensions: methodProperty* moved to AST-Core

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2389]
Hi marcus 

I'm checking extensions made by several packages to RB*Node and I wonder if 
the method properties*, property* should be move to AST-Core. I would do it but I want 
your point of view.

**Comment by MarcusDenker** [comment]
I will check but  most likely next week after the 7th.

**Comment by Ducasse** [comment]
Can you have a look?

**Comment by MarcusDenker** [comment]
Yes, I checked the users and it makes sense to move it to the AST. I will do  a PR

**Comment by MarcusDenker** [comment]
I checked it again.. I think they are better in the compiler package.

properties --> properties on the AST. Part of the AST package.

methodProperties: the properties that will be on the compiledMethod, as the result of the compilation. As such methodProperties is something that no other client but the compiler will ever use. It is maybe even somthing that might be possible to do nicer later, so making this an API for the AST would not be good.
