### ISSUE TITLE
Do we push transformLastToReturn to AST-Core?

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2390]
Hi marcus 

Do we push transformLastToReturn to AST-Core?

Stef

**Comment by MarcusDenker** [comment]
I would not... it is a very special method only useful for the compiler

**Comment by Ducasse** [comment]
Thanks then one issue less

**Comment by MarcusDenker** [comment]
Actually even better: with the short demo of the stepping AST Interpreter, we learned that #addReturn does exactly the same :-) 

I will make PR to remove transformLastToReturn

**Comment by MarcusDenker** [comment]
see #2743
