### ISSUE TITLE
#isSymlink broken and additional file attributes

### ISSUE THREAD

**Issue by akgrant43** [guillep/pharo-core#2393]
- #isSymlink returns false for valid symlinks on Linux (and the code doesn't look right for MacOS).
- stat() on linux & MacOS returns additional attributes that aren't currently accessible from within the image.
- Provide access to symlink attributes (lstat())

PR: https://github.com/pharo-project/pharo/pull/2431

Related fogbugz issues:

- https://pharo.fogbugz.com/f/cases/18279/isSymlink-seems-to-be-broken-on-Linux
- https://pharo.fogbugz.com/f/cases/21368/Integrate-FileAttributesPlugin
- https://pharo.fogbugz.com/f/cases/22368/File-permissions-and-ownership

Mailing list discussions:

- http://forum.world.st/FileSystem-file-attributes-and-isSymlink-patch-td4956517.html
- http://lists.squeakfoundation.org/pipermail/vm-dev/2017-July/025605.html

The fix uses a new plugin in the VM, FileAttributesPlugin:

```smalltalk
MCHttpRepository
    location: 'http://smalltalkhub.com/mc/Alistair/FileAttributesPlugin/main'
    user: ''
    password: ''
```

More details of the changes:

1. #isSymlink now works properly on Linux (and it should also work on 
  MacOS and BSD).
2. The list of file attributes available from DiskDirectoryEntry now is:
    #accessTime (new)
    #changeTime (new)
    #deviceId (new)
    #gid (new)
    #inode (new)
    #isBlock (new)
    #isCharacter (new)
    #isExecutable (new)
    #isFIFO (new)
    #isRegular (new)
    #isSocket (new)
    #isSymlink (works)
    #numberOfHardLinks (new)
    #targetFile (new)
    #uid (new)

    #creationTime
    #exists
    #isDirectory
    #isFile
    #isReadable
    #isWritable
    #modificationTime
    #permissions
    #size
3. FileReference>>exists is faster than before (well, at least on my 
  linux laptop).  This is useful as it is called quite often.
4. It is possible to retrieve symbolic link attributes, e.g. all the 
  attributes listed above plus the target path.

As implied above, the changes are all backward compatible (except 
the broken #isSymlink), although a couple deserve mention:

1. Obviously #isSymlink now answers correctly (previously it would only 
  answer correctly for a broken link).
2. Requesting any of the attributes listed above (except #isSymlink) 
  will return the value of the target path.
3. The attributes of a symbolic link can be retrieved using 
  FileReference>>symlinkEntry.

Overall, performance is slightly better than before.  Code that accesses a
single attribute through FileReference will be faster than before (it used 
to retrieve all supported elements and throw the unused ones away).  Code
that needs to access multiple attributes and uses FileSystemDirectoryEntry
will access the new attributes without any additional performance cost.

I've been using this code continuously since May 2017 - initially on 32 bit linux and more recently on 64 bit linux.  It's had some testing on Windows and MacOS.

**Comment by cdlm** [comment]
…why do I see myself assigning @akgrant43 and adding a label to that issue? I don't recall doing that…

**Comment by jecisc** [comment]
@cdlm It's automatic and I think it uses one of the users with the rights randomly and currently it uses your account to add labels and assignations.

**Comment by cdlm** [comment]
Ok, I was starting to suspect @Ducasse usurped my identity while he was doing the lecture on my machine last friday 🤔

**Comment by akgrant43** [comment]
@jecisc Could the script use pharo-project?  Having a random user makes auditing difficult later on.

**Comment by jecisc** [comment]
I don't know personally how it works and what exactly is doing that. It's just what I observed.

**Comment by Ducasse** [comment]
This is strange because I just displayed powerpoint.

**Comment by Ducasse** [comment]
And yes I do not understand why damien's account is always adding the review tag.
