### ISSUE TITLE
Decorator in Rubric have a problem

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2402]
here is the trace that we have in some build. 
testFileTreeRepository: /builds/workspace/uest_and_branch_Pipeline_PR-2327/Tests-unix-32/temp/repoSubscriptOutOfBounds: 0
OrderedCollection(Object)>>errorSubscriptBounds:
OrderedCollection>>at:
OrderedCollection(SequenceableCollection)>>last
RubParagraph>>extent
Message>>sendTo:
[ aMessage sendTo: next ] in RubOpeningClosingDelimiterDecorator(RubParagraphDecorator)>>doesNotUnderstand: #extent in Block: [ aMessage sendTo: next ]
BlockClosure>>on:do:
RubOpeningClosingDelimiterDecorator(RubParagraphDecorator)>>doesNotUnderstand: #extent
Message>>sendTo:
[ aMessage sendTo: next ] in RubExtraSelectionDecorator(RubParagraphDecorator)>>doesNotUnderstand: #extent in Block: [ aMessage sendTo: next ]
BlockClosure>>on:do:
RubExtraSelectionDecorator(RubParagraphDecorator)>>doesNotUnderstand: #extent
Message>>sendTo:
[ aMessage sendTo: next ] in RubCurrentLineBarDecorator(RubParagraphDecorator)>>doesNotUnderstand: #extent in Block: [ aMessage sendTo: next ]
BlockClosure>>on:do:
RubCurrentLineBarDecorator(RubParagraphDecorator)>>doesNotUnderstand: #extent
RubEditingArea(RubAbstractTextArea)>>updateBottomFromParagraph
[ self wrapped
	ifTrue: [ self updateBottomFromParagraph ]
	ifFalse: [ self updateExtentFromParagraph ] ] in RubEditingArea(RubAbstractTextArea)>>paragraphWasComposedFrom:to: in Block: [ self wrapped...
RubEditingArea(RubAbstractTextArea)>>handleBoundsChange:
RubEditingArea(RubAbstractTextArea)>>paragraphWasComposedFrom:to:
[ self uptodateComposer
	composeLinesFrom: 1
	to: self text size
	delta: 0
	into: OrderedCollection new
	priorLines: Array new
	atY: self compositionRectangle top.
textArea
	ifNotNil: [ textArea paragraphWasComposedFrom: 1 to: self text size ] ] in RubParagraph>>compose in Block: [ self uptodateComposer...
RubParagraph>>disableDrawingWhile:
RubParagraph>>compose
RubParagraph>>extentFromClientBottomRight:
[ self wrapped
	ifTrue: [ (bounds notNil and: [ bounds width = aPoint x ])
			ifTrue: [ ^ self ].
		super
			extent:
				((self paragraph withoutDecorator extentFromClientBottomRight: aPoint)
					max: self minimumExtent).
		self recomputeSelection ] ] in RubEditingArea(RubAbstractTextArea)>>extent: in Block: [ self wrapped...
RubEditingArea(RubAbstractTextArea)>>handleBoundsChange:
RubEditingArea(RubAbstractTextArea)>>extent:
RubEditingArea(Morph)>>width:
RubTextScrollPane>>fitScrollTargetWidth
RubTextScrollPane>>updateScrollbars

**Comment by Ducasse** [comment]
still valid

**Comment by guillep** [comment]
Hi @Ducasse is (was?) this an issue seen in the CI?
Or you had it in some other way?

I've logged recently this other one as a fleaky test:
https://github.com/pharo-project/pharo/issues/5966

**Comment by guillep** [comment]
I mark it as duplicate and close it.
Please reopen if you think this is still valid outside the CI.
