### ISSUE TITLE
Crashing tests

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2403]
the build is often dead because of this 

testFileTreeRepository: /builds/workspace/uest_and_branch_Pipeline_PR-2367/Tests-osx-32/temp/repoMessageNotUnderstood: receiver of "previousLink" is nil
UndefinedObject(Object)>>doesNotUnderstand: #previousLink
GLMLabelBrick(GLMBrick)>>privateRemoveBrick:
GLMLabelBrick>>onLayouted
GLMBrickWrapper>>onLayouted
[ :origin :each | 
| result |
result := origin
	+
		((self isFloating: each)
			ifFalse: [ aBlock cull: origin cull: each ]
			ifTrue: [ self layoutFloating: each in: aRectangle ]).
"applying aligning: #none, #left, #center, #right"
self
	align: each
	in: aBrick
	anchorPoint: origin
	inContext: nil.
each onLayouted.
result ] in GLMHorizontalLinearLayout(GLMLinearLayout)>>layout:in:inject:into: in Block: [ :origin :each | ...
[ :each | nextValue := binaryBlock value: nextValue value: each ] in OrderedCollection(Collection)>>inject:into: in Block: [ :each | nextValue := binaryBlock value: nextValu...etc...
OrderedCollection>>do:
OrderedCollection(Collection)>>inject:into:
GLMHorizontalLinearLayout(GLMLinearLayout)>>layout:in:inject:into:
GLMHorizontalLinearLayout>>layout:in:
GLMBrick>>invalidateLayout
GLMBrickWrapper>>invalidateLayout
GLMBrickHeightTraverser(GLMBrickLayoutTraverser)>>layoutSubbricks:
GLMBrickHeightTraverser(GLMBrickLayoutTraverser)>>layoutAround:inContext:
[ :each | self layoutAround: each inContext: aBrick ] in GLMBrickHeightTraverser(GLMBrickLayoutTraverser)>>layoutChildrenOf: in Block: [ :each | self layoutAround: each inContext: aBric...etc...
OrderedCollection>>do:
GLMBrickHeightTraverser(GLMBrickLayoutTraverser)>>layoutChildrenOf:
GLMBrickLayoutParentState>>layout:on:
GLMBrickHeightTraverser(GLMBrickLayoutTraverser)>>layoutAround:inContext:
[ :each | self layoutAround: each inContext: aBrick ] in GLMBrickHeightTraverser(GLMBrickLayoutTraverser)>>layoutChildrenOf: in Block: [ :each | self layoutAround: each inContext: aBric...etc...
OrderedCollection>>do:
GLMBrickHeightTraverser(GLMBrickLayoutTraverser)>>layoutChildrenOf:
GLMBrickLayoutParentState>>layout:on:
GLMBrickHeightTraverser(GLMBrickLayoutTraverser)>>layoutAround:inContext:
[ :each | self layoutAround: each inContext: aBrick ] in GLMBrickHeightTraverser(GLMBrickLayoutTraverser)>>layoutChildrenOf: in Block: [ :each | self layoutAround: each inContext: aBric...etc...
OrderedCollection>>do:
GLMBrickHeightTraverser(GLMBrickLayoutTraverser)>>layoutChildrenOf:
GLMBrickLayoutMyselfState>>layout:on:
GLMBrickHeightTraverser(GLMBrickLayoutTraverser)>>layoutAround:inContext:
GLMBrickLayouter>>layout:

**Comment by MarcusDenker** [comment]
this seems to not happen anymore
