### ISSUE TITLE
Add rule and release test to not use `Smalltalk ui theme` in subclasses of Morph

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2404]
Morph implements in the instance and the class side a method #theme. Thus, its subclasses should never call `Smalltalk ui theme`. 

We should correct current usage, add a rule and a release test about that.

**Comment by jecisc** [comment]
Still valid

**Comment by hilaire** [comment]
Any pointer on how to write a rule?

**Comment by hilaire** [comment]
Rule based on Renraku ?

**Comment by hilaire** [comment]
Or Refactoring? Or Refactoring2?

**Comment by Ducasse** [comment]
We should migrate the rules to Renraku but never got the time. 
So favor renraku

**Comment by hilaire** [comment]
Under the Fist Impression Count perspective, does it not hurt Pharo to have multiple packages doing the same things?

**Comment by Ducasse** [comment]
Yes it does now this is a question of resources and we would love help. 
For example I'm working on a better formatter and the goal is to remove the existing one before we introduce the new one. But not everybody is doing the same.
