### ISSUE TITLE
NewValueHolder should use hook to get its value

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#2405]
When announcing a value change

```
valueChanged
	
	self announcer announce: (ValueChanged newValue: value)
```

Using the value in the variable directly does not let subclasses override that behaviour.
This creates issues in the SelectionValueHolder and breaks all Selection events in Spec

**Comment by Ducasse** [comment]
ahhhh nice

**Comment by guillep** [comment]
PR: https://github.com/pharo-project/pharo/pull/2408

**Comment by guillep** [comment]
Integrated
