### ISSUE TITLE
Kill flaky test (GLMTabulatorMorphicTest)

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2407]
windows-32 / Tests-windows-32 / testSizeAndSpan – Windows32.Glamour.Tests.Morphic.GLMTabulatorMorphicTest

**Comment by Ducasse** [comment]
I have the impression that this was done.

**Comment by MarcusDenker** [comment]
no, it is still there

**Comment by MarcusDenker** [comment]
fixed with pr #2737

**Comment by MarcusDenker** [comment]
merged
