### ISSUE TITLE
Debugger step through mustBeBoolean case hangs

### ISSUE THREAD

**Issue by dionisiydk** [guillep/pharo-core#2410]
(from fogbugs)

Debugger hangs on step through block which internally analysed for bool result.
Try step through:
```Smalltalk
#(2) select: [:i| i]
```
Problem somehow related to mustBeBoolean error. It works normally with different internal errors:
```Smalltalk
#(2) select: [:i| i / 0]
```
Debugger fallback into #/ method at ZeroDivide statement. But with mustBeBoolean trick it not works.

**Comment by dionisiydk** [comment]
You can see reason of issue if you perform step over instead of through.
Debugger will show #mustBeBooleanInMagic: where you will see that produced #ExecuteUnOptimizedIn: method is incorrect for this case.

**Comment by dionisiydk** [comment]
After investigating a bit I think it is another problem with context temps mapping.
In debugger (from step over action) look at "context tempNames" in method #mustBeBooleanInMagic:. You will not see variable "index".

**Comment by dionisiydk** [comment]
Unfortunately I could not produce script with "thisContext tempNames" to localize problem

**Comment by dionisiydk** [comment]
(from @nicolaihess )

Is this error really only related to #stepThrough?

If you just execute the code
#(2) select: [:i| 3].

I would expect an error like:
MessageNotUnderstood: SmallInteger>>ifTrue:
but instead, I get:
Array(Object)>>errorSubscriptBounds:

**Comment by dionisiydk** [comment]
(from @dupriezt )

What Nicolai brought up looks similar to  https://pharo.fogbugz.com/f/cases/20614/ which we just fixed with Marcus.
The debugger still hangs on stepping through #(2) select: [:i| i] though, so there may be another problem.

**Comment by dionisiydk** [comment]
(from @dupriezt )

- Setting a halt in Context>>#stepToHome:
- Executing `#(2) select: [:i| i]` in the debugger.
- Step Through 3 times, clicking proceed on the exception
- Open the debugger on the fourth exception
Then the problem comes from the following loop of Context>>#stepToHome:, that never finishes.
`    [ctxt := ctxt step.
    error ifNotNil: [
        "Error was raised, remove inserted above contexts then return signaler context"
            "aContext terminateTo: context sender."  "remove above ensure and handler contexts"
            ^ {ctxt. error}].
    
    home == ctxt home] whileFalse: [
        home isDead ifTrue: [^ {ctxt. nil}]
    ].`

You can also see the unending loop by using only step over: the execution keeps sending ifTrue: to the SmallInteger, which raises a DoesNotUnderstand, then the ifTrue: is sent again to the SmallInteger...

This may be an intended behaviour in some way. For example, when coding from the debugger in general, you could implement the missing method and then step over, which will avoid the DoesNotUnderstand and the execution will go on.
The Step Through, however, keeps stepping until the context home comes back to what it was at the beginning without raising the exception (for some reason), so it loops indefinitely.

**Comment by guillep** [comment]
This is still valid and super important.
