### ISSUE TITLE
Small facelift of the Dark Theme

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#2412]
Make it a little blueish as Stef asked.

![pharoscreenshot](https://user-images.githubusercontent.com/572494/51941762-abfe6580-2415-11e9-943c-e77a8df6b58c.png)

the original for comparison:

![pharoscreenshot 1](https://user-images.githubusercontent.com/572494/51941989-3777f680-2416-11e9-8cc9-5ed16276ea49.png)

**Comment by estebanlm** [comment]
I'm sorry but I do not like it like that.
Is a mix of brown and blue and it does not looks very good. 

If we want a "blueish" dark theme, I suggest start with my DarkMetal and make It less strong.

**Comment by estebanlm** [comment]
btw, in case of tweaking themes, I always prefer to "take inspiration" on what others did. 
In this case, I think VS did a good work with dark theme : http://d2.alternativeto.net/dist/s/0ea597f3-03b0-4d48-991f-9a2147f52049_5_full.png?format=jpg&width=1600&height=1600&mode=min&upscale=false
(which is more or less the same as Xcode: https://9to5mac.com/wp-content/uploads/sites/6/2018/06/macos-10-14.jpg?quality=82&strip=all&w=1354)
or IntelliJ Dracula: https://raw.githubusercontent.com/Revivius/nb-darcula/screenshots/screenshots/v1.4.png

All very similar, and for a reason (there are UX studies behind that :P )

**Comment by pavel-krivanek** [comment]
I took the colors from Blender :-) 
ok, closing
