### ISSUE TITLE
Add warning if we add a new instance variable creating shadow variables

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2418]
Currently, if I add an instance variable whose name is the same as a temporary variable, then nothing happens and we get a shadow variable. 

It would be great to have a prompt when that happens with the list of temporary variables of the same name.

**Comment by jecisc** [comment]
This is still valid but apparently I cannot re-open my issues? :(

**Comment by MarcusDenker** [comment]
This is not that easy: adding ivars is done by the class builder, not the compiler.

So to do this we would need to, every time the class builder creates a class, check all method of the class and all subclasses if they define a temp of that name. 

Now the reflective model of methods does not include the name of temps. This means that one would need to create the AST for each method and search it for all temps of all blocks.

This would slow down adding an instance variable *a lot*

**Comment by MarcusDenker** [comment]
Is it really worth it? We have so many problems with class creation / change being slow. This would make it *very* slow.

**Comment by jecisc** [comment]
I agree it's not worth degrading performances.
