### ISSUE TITLE
Convert Bootstrap to Tonel

### ISSUE THREAD

**Issue by bencoman** [guillep/pharo-core#2430]
I wanted to contribute to #1887 & #1957 for Pharo 8.0 and got blocked cloning pharo repo.
I created and opened a new Pharo 7.0.1 image from PharoLauncher,
then Tools > Iceberg > "pharo" repo > Repair repository > Clone again this repository > Clone from github.com - tried two repos...
-  Owner=bencoman    Project=pharo
- Owner=pharo-project    Project=pharo

and both times got the same...
```
ERROR, Failed to stat file 'C:/Users/Ben/Documents/Pharo/images/Pharo 7.0 - 32bit (development version)-02/
pharo-local/iceberg/pharo-project/pharo/bootstrap/src/Pharo30Bootstrap.package/
PBBootstrap.class/instance/
exportPackages.withBlacklistedClasses.withBlacklistedMethods.usingInitializeScript.intoFile..st': 
The filename or extension is too long.
```

It looks like the Bootstrap code is not yet in Tonel format.

I realize my image path is quite long itself and I can shorten it as a work around,
but having Bootstrap in Tonel format would reduce the hurdles to contributing.

**Comment by astares** [comment]
You will hit the windows path problems on several places. 

Use a virtual box installation with an Ubuntu inside. Easy to setup and even as a windows user this is very comfortable and pleasant to use in addition to the Windows Pharo version.

**Comment by bencoman** [comment]
I appreciate your intention to help me (and actually I'm fine to just rename my image shorter) , but if we just work around things then it leaves those potholes and hurdles for newcomers to trip over and leave a bad impression.

**Comment by astares** [comment]
Agree - but as you know the resources are limited. 

Currently also Seaside could not be converted due to a **bug in Tonel conversion** (https://github.com/pharo-vcs/tonel/issues/74) - so unfortunately for the time being it will not yet be loadable on Windows . So if it is urgent on your side I would suggest the virtual box way.

**Comment by bencoman** [comment]
I'm not clear, are you saying a Bootstrap conversion hits that Tonel bug?

**Comment by jecisc** [comment]
Can this be re-open? This is important to ease the work on the bootstrap.

**Comment by jecisc** [comment]
We might take a look with Carolina this week
