### ISSUE TITLE
Crashes Pharo 7 when defining instance variable in ProfStef

### ISSUE THREAD

**Issue by wyattbiker** [guillep/pharo-core#2437]
if you try the following in ProfStef tutorial pane. 

`x := Character space.`   and then on the prompt add instance variable it crashes Pharo.

Issue both on VM 7 / OS X and Linuxmint 19.1

**Comment by MarcusDenker** [comment]
Yes, this is still a problem. We got another issue: https://github.com/pharo-project/pharo/issues/4017 reported.

I will close this here as it is referenced from the newer.
