### ISSUE TITLE
Doubleclick on a word text in Playground, does not highlight the word.

### ISSUE THREAD

**Issue by wyattbiker** [guillep/pharo-core#2438]
OS X, High Sierra / VM 7

If you have a line of ST command and you double click on a single word, it will not highlight when caret is moved over the word.

open Playground and try it on the following statement:  `(1 class maxVal + 1) class.`
First place your caret on the word `class` and then double click on `maxVal`

It seems you have to first click the word and then doubleclick to highlight. Very annoying and not a standard in any application I have seen.

PS. I tested this on Linuxmint 19.1 and works as expected.

**Comment by macta** [comment]
I tried this on OSX HighSierra 10.13.5 with build 1436 and 64bit VM and it works fine?

This said, I have had other strange things where cursor keys suddenly don't work in lists - which then start working again (#2507) - so I wouldn't immediately dismiss this.

**Comment by SergeStinckwich** [comment]
Work correctly on MacOS 10.13.6 on Pharo 7.0.3, 64 bits VM.
I suggest to close this issue @MarcusDenker
