### ISSUE TITLE
Less Smalltalk ui theme - Cleaning Glamour and GT (Part 1)

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2441]
AntiSingleton Campaign!
Choose your camp designer. Be pro or lame.

**Comment by Ducasse** [comment]
May be we should introduce 
DisplayableObject which as a theme variable and object using a theme should really subclass from it because avoiding this Smalltalk ui theme plague.

**Comment by cdlm** [comment]
Is there a critic rule for this? Other instances that could be flagged by such a rule?

**Comment by Ducasse** [comment]
This is strange because I thought that I did a PR.

**Comment by Ducasse** [comment]
I issued a new PR.

**Comment by juliendelplanque** [comment]
@MarcusDenker @Ducasse this issue has been fixed by #2473  but was not closed.
