### ISSUE TITLE
Trait users should be accessible from Calypso and also a query in SystemNavigation should be offered

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2443]
Trait users should be accessible from Nautilus and also a query in SystemNavigation should be offered

**Comment by Ducasse** [comment]
There is browseAllUsersOfTrait: in SystemNavigation.

**Comment by Ducasse** [comment]
But the code does not work anymore

browseAllUsersOfTrait: aTrait
	"Create and openenvironment  a browser on each class or trait that imports aTrait"

	^Smalltalk tools browser openInEnvironment: (RBBrowserEnvironment new forClasses: aTrait traitUsers)
	
openInEnvironment: is not defined anymore :(

**Comment by dionisiydk** [comment]
Environment issue is here #3112 .
About trait users: it is already available in browser. When trait is selected there are three radio buttons in toolbar: Flat, Traits, Users.

**Comment by MarcusDenker** [comment]
this PR makes the SystemNavigation method work again: https://github.com/pharo-project/pharo/pull/3801

(this way we can close this issue(

**Comment by MarcusDenker** [comment]
merged
