### ISSUE TITLE
Catalog Browser not showing any items

### ISSUE THREAD

**Issue by ghoetker** [guillep/pharo-core#2446]
Downloaded Pharo7.0.1build: 147, commit: 19ab109. Opened Catalog Browser. The browser window opens as expected, but there are no items listed. Pressing the Refresh button doesn't fix.  Running MacOS 10.14.3 (Mojave). Please let me know if I can provide other useful debugging information.

**Comment by astares** [comment]
Are you behind a proxy? If so set it in Settings browser under Network.

Also you can try to reset the catalog provider

```Smalltalk
   CatalogProvider reset
```

and then reopen catalog / refresh it.

**Comment by astares** [comment]
@ghoetker Any feedback?

**Comment by ghoetker** [comment]
Sorry.  Traveling. Will provide more info next week.

Sent from my iPhone

On 14 Feb 2019, at 12:15 am, Astares <notifications@github.com<mailto:notifications@github.com>> wrote:


@ghoetker<https://github.com/ghoetker> Any feedback?

**Comment by ghoetker** [comment]
Sorry for the delay.  Not behind a proxy. Issuing 

```
CatalogProvider rest
```

generated an "Instance of CatalogBrowser class did not understand #reset" error.

**Comment by astares** [comment]
Oh - sorry 

```Smalltalk
CatalogProvider default reset
```

**Comment by ghoetker** [comment]
Good news. "CatalogProvider default reset" works fine. 

Bad news. The problem of "browser window opens as expected, but there are no items listed" seems to be random. The only constant seems to be that one it works on a given image, it works forever. Beyond that, I haven't been able to see any consistency. I have confirmed that I'm not behind a proxy.

I'll keep exploring and report if I find any consistent pattern. But for now, that's all I have to offer.

**Comment by astares** [comment]
For me it is working fine. Have this effect sometimes when traveling due to network hickups. To me it looks like local network trouble as no other members of the community reporting the same problem and this part of the code has'nt changed during Pharo 7 release cycle.

**Comment by estebanlm** [comment]
mmm. As @astares says, this is for sure a connectivity problem. 
What you see as random is because Catalog updates each day and then caches the information. 
We will need to change the catalog in the near future but for now I consider this not an addressable issue.
