### ISSUE TITLE
Rubric race-conditions

### ISSUE THREAD

**Issue by StephanEggermont** [guillep/pharo-core#2447]
Pharo 7 build 143

When using the STCommandLineHandler>>installSourceFile:
ThreadSafeTranscript open seems to have a race-condition
I get a subscriptOutOfBounds in the beForSmalltalkScripting
In RubSmalltalkScriptingMode>>updateTextAreaWhenPlugged

self textArea updateTextWith: '' manages to get confused about selection boundaries and tries to use those of the original text

'
Fetched -> BaselineOfTaskIt-CompatibleUserName.1543957602 --- https://github.com/sbragagnolo/taskit.git[v1.0.1] --- https://github.com/sbragagnolo/taskit.git[v1.0.1]'
is the text that was in there.

**Comment by StephanEggermont** [comment]
Reopen

**Comment by Ducasse** [comment]
Stephan do you have a way to reproduce it?

**Comment by StephanEggermont** [comment]
@VincentBlondeau is that still reliably happening?

**Comment by VincentBlondeau** [comment]
I do not use Pharo 7 anymore so I do not know

**Comment by guillep** [comment]
Hi @StephanEggermont could you check if this is the same case as in https://github.com/pharo-project/pharo/issues/5966?

Thanks!

**Comment by StephanEggermont** [comment]
That could be the same case indeed. Reliably reproducing it is difficult, this one used your proprietary code, @VincentBlondeau

**Comment by VincentBlondeau** [comment]
I cannot tell anymore. I do not know how to reproduce it.

**Comment by MarcusDenker** [comment]
i close this as a duplicate of  #5966
