### ISSUE TITLE
Automatic rewriting of deprecated code needs feedback to developers whose code is changed

### ISSUE THREAD

**Issue by fuhrmanator** [guillep/pharo-core#2449]
Yesterday, I discovered the very cool feature that deprecated code is automatically rewritten as soon as it is executed (http://forum.world.st/Deprecation-guide-for-methods-classes-and-packages-td5085081.html -- I'm not sure it's the right link to the feature?). 

However, being a relative newbie to Pharo (but not to coding), it caused me to panic a bit because it happened when I was adapting lots of code from one OS to another (Windows, MacOS) and I didn't recognize my code anymore (after branching, pushing, merging, etc.). 

Specifically it was a call like
```Smalltalk
envVar := OSEnvironment current getenv: 'MYOSVAR'.
```
that was rewritten to:
```Smalltalk
envVar := OSEnvironment current at: 'MYOSVAR' ifAbsent: [ nil ].
```
My issue here is to make this more "newbie" friendly (or even to make it just transparent so people know when it has happened).

I can think of a couple of ways: 

1) in the translation rules, is it possible to add comments to delimit the code that was modified automatically clearly saying it was rewritten automatically? Had I seen those comments, I would have know that the feature existed and was performed.
2) perhaps use `self flag: 'code rewritten using deprecation rules - (you can safely remove this line) '` so the programmer can remove it later.

Maybe there are other ways that can be discussed?

**Comment by jecisc** [comment]
As a first step, what I would do is to add an inform. Like that when a method is rewritten it would show a popup.

**Comment by MarcusDenker** [comment]
the idea to add a comment is good.

**Comment by astares** [comment]
I dislike adding a comment - because then one has to remove these comments before 
committing.

An inform: or output on Transcript should be enough.

**Comment by MarcusDenker** [comment]
I did an experiment to use #flag: but nobody likes it (me neither :-)

https://github.com/pharo-project/pharo/pull/4511

So I think the idea to to a Transcript output is good, I will implement that

**Comment by Ducasse** [comment]
I think that we should integrate the mini beacon I cleaned and we could use it instead of transcript.

**Comment by MarcusDenker** [comment]
Yes, better logging would be great. I did a trivial change for now:

https://github.com/pharo-project/pharo/pull/4539

it just exapends the message with an addition at the front:

Automatic deprecation code rewrite: The method Object>>#test called from Object>>#test2 has been deprecated. use test2

**Comment by MarcusDenker** [comment]
I close this. Everyone was very much against putting anything in the code.

In addition to the note, there is now the possibility to turn the transformation off, too (in the Settings)
