### ISSUE TITLE
Week>>year:week: doesn't do what its documentation says

### ISSUE THREAD

**Issue by khinsen** [guillep/pharo-core#2455]
The comment in the method says:

    Return the ISO week for the given week number and the given year.
    Week 1 contains the year's first Thursday (weekday = 5)

However, ISO8601 specifies that weeks start on a Monday, whereas Pharo generally adopts the convention that weeks start on Sunday.

I can see two correction strategies:

 1) Change the documentation of `Week>>year:week:`. Add a new method `Week>>year:isoWeek:` that returns a Week starting on Monday.
 2) Change the behavior of `Week>>year:week:` to reflect the documentation.

This comes down to deciding how important backwards compatibility is. Nowadays week numbers always refer to the ISO6801 definition (not sure that was always the case), so the current behavior of `Year>>year:week:` is not very useful, but nevertheless existing code may rely on it.

I'd be happy to provide a patch for either approach.

**Comment by svenvc** [comment]
I would go for the ISO Week definition (starting on Monday) as it is the only formally defined system with proper defined numbering.

https://en.wikipedia.org/wiki/Week
https://en.wikipedia.org/wiki/ISO_week_date

> On 7 Feb 2019, at 13:03, Konrad Hinsen <notifications@github.com> wrote:
> 
> The comment in the method says:
> 
> Return the ISO week for the given week number and the given year.
> Week 1 contains the year's first Thursday (weekday = 5)
> 
> However, ISO8601 specifies that weeks start on a Monday, whereas Pharo generally adopts the convention that weeks start on Sunday.
> 
> I can see two correction strategies:
> 
> 	• Change the documentation of Year>>year:week:. Add a new method Year>>year:isoWeek: that returns a Week starting on Monday.
> 	• Change the behavior of Year>>year:week: to reflect the documentation.
> This comes down to deciding how important backwards compatibility is. Nowadays week numbers always refer to the ISO6801 definition (not sure that was always the case), so the current behavior of Year>>year:week: is not very useful, but nevertheless existing code may rely on it.
> 
> I'd be happy to provide a patch for either approach.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Sven Van Caekenberghe - mailto:sven@beta9.be
Beta Nine - software engineering - http://www.beta9.be

**Comment by khinsen** [comment]
For illustration, this is the method `Week>>year:isoWeek:` that I have written as an extension for my immediate needs.

```
year: aYear isoWeek: weekNumber
	"Return the ISO week for the given week number and the given year. Note that year:week: does not
	fully respect the ISO definition because it returns a week starting on a Sunday. ISO 8601
	specifies that weeks start on a Monday."
	"Note: we have to call starting:duration: from the superclass Timespan to make this work.
	 The Week class tries hard to enforce weeks starting on Sunday."
	^ super starting: aYear asYear firstThursday + (weekNumber * 7 - 10) days duration: 1 week
```

**Comment by khinsen** [comment]
A more radical change would be to make `Week>>startDay` default to Monday, making weeks ISO-compatible by default. But I have no idea what the impact on existing code would be.

The idea behind `Week>>startDay:`, which changes a system-wide setting, isn't quite clear to me.  It looks like an invitation for date-processing code to set its own convenient defaults, but that looks extremely dangerous, in particular in a multi-threaded context.
