### ISSUE TITLE
Timespan subclasses induce unexpected behavior

### ISSUE THREAD

**Issue by khinsen** [guillep/pharo-core#2458]
Before reading on, consider the expression `(Year year: 2019) intersection: (Week year: 2019 week: 1)`. What would you expect its value to be?

My expectation was: the part of the first week of 2019 that's actually in 2019 (given that the first day is in 2018, a consequence of the ISO definition of a week). But its actual value is... `Year year: 2019`!

This is a consequence of `Timespan>>intersection:` returning an object of `self class`, and `Year` forcing all its instances to be one year from January to December. A meaningful result of my expression would have to be of class `Timespan`, not `Year`.

Unfortunately, `Timespan` has two kinds of subclasses: `Year`, `Month` etc. are special *values* of timespans, whereas `Schedule` is a timespan with additional semantics. This doesn't look like a particularly clean object model to me. You'd probably want the intersection of a schedule with a timespan to be a schedule, but you don't want the intersection of a year with anything else to be a year.

There are other operations that suffer from similar problems. For example. `(Year year: 2019) + 1 day` is again `Year year: 2019`, whereas any other timespan would be shifted by one day. But perhaps the clearest indicator of the problem is the class method `starting:duration:` that all these classes override in order to explicitly ignore its second argument and modify the first one.

**Comment by svenvc** [comment]
Konrad,

The current model of chronology in the image is what it is, it is far from perfect, but it works more or less.

Chronology with comprehensive international support is very hard (non-gregorian calendars, China, India, etc).

If you want to model much more of this, you should consider having a look at the Chronos library. I don't know where you can find the most recent code, but some links are

http://www.chronos-st.org [ dead ]
http://chronos-st.blogspot.com/search/label/Chronos
http://www.cincomsmalltalk.com/main/community/product-portal/contributed/chronos/
http://map.squeak.org/package/46b5731f-5112-4157-94d3-d40c4ed8304d

Many people have tried different approaches, alternatives and add-ons. I have a small one myself, called ZTimestamp

https://github.com/svenvc/ztimestamp

There is a reason most people don't try to change the existing classes ;-)

HTH,

Sven

**Comment by PharoProject** [comment]
http://www.smalltalkhub.com/#!/~Chronos/Chronos

**Comment by khinsen** [comment]
Handling all possible aspects of date and time conventions around the globe is indeed a major task, but it's also much more than most applications need. Chronos looks impressive, but also abandoned. Not sure that's the right way to go.

My context is scientific data analysis, where the data contains date and time information. In this universe, [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) has been almost universally adopted today, and most programming environments I know support it either as a feature in the standard library (e.g. Python) or with universally agreed-on add-ons (e.g. R). I consider it highly desirable to get to the same point with Pharo, either by improving the built-in date/time classes or by writing an add-on that supports ISO 8601 fully but without added luxury that's hard to maintain.

My impression so far is that the built-in classes have all the functionality required for ISO 8601, but don't always behave quite right. But I haven't studied this enough to be able to say if all the existing problems can be fixed.
