### ISSUE TITLE
Many VM crashes during Pharo checks

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2459]
I have a PR I already relaunched 5 times and each time a different OS-specific check fail because there is a VM crash.

This make it really hard to validate PRs.

**Comment by Ducasse** [comment]
Let me know if I close it or not.

**Comment by akgrant43** [comment]
> Let me know if I close it or not.

The changes I've made won't solve the problem - if we're lucky they'll help narrow down what introduced it.

So... this will probably be open for a while yet.
