### ISSUE TITLE
Metacello Loading a github project like 'github://exercism/pharo:master/dev/src' fails with: '#pathString: was sent to nil' as  #guessRegisteredRepository is too simplistic

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2485]
I’m trying to pick up the Exercism project (Which loads properly in Pharo 6) - but when trying to load:

Metacello new 
 baseline: 'Exercism'; 
 repository: 'github://exercism/pharo:master/dev/src';
 load.

I get an error: #pathString: was sent to nil 

Looking at the walkback, it seems that when its trying to create a missing repository - the IceMetacelloPharoPlatform delegates to Iceberg>>mcRepositoryFor: and ultimately calls the method #guessRegisteredRepository - which doesn't guess very well!

As the repo //exercism/pharo was given to us by the Exercism team to match repo’s of other languages like //exercism/ruby etc., it's not easy to change - and really there shouldn't be a collision with the straight Pharo repository.

I think discriminating solely on project name is not a great idea, and it should be based on a fuller path?

**Comment by macta** [comment]
I don't know if the following is a real fix - but possibly something like this might work (it did for the error above - but its rather hacky. Currently repos don't seem to store their path, but you do have the directory where they got resolved to, and the path segment before the projectName looks like the path?



```
guessRegisteredRepository
	"I get the project name and try to find it into the already registered projects. 
	 If I find it, I will use this instead cloning a new one."

	| projectPath projectName |
	projectPath := (self location substrings: '/') second.
	projectName := (self location substrings: '/') third copyUpTo: $:.
	
	^ IceRepository registry 
		detect: [ : each | |repoPath|
			repoPath := each location ifNil: [ '' ] ifNotNil: [ :v | v path segments nextToLast].
			each name = projectName and: [repoPath = projectPath]] 
		ifNone: [ nil ]
```

**Comment by macta** [comment]
Related to this, you can't use Iceberg to load the github project with owner: exercism, project: pharo

I suspect its similar to this problem - it thinks this different project is actually the pharo project - even though it comes from a different owner.

It also looks like the code snipped above for #guessRegisteredRepository worked in an image from Feb 8th but newer ones don't like it

**Comment by macta** [comment]
This looks to still be the case in P8, and its not very cool that we have this limitation (we worked around it on exercism by getting our repo renamed - but it was a hassle)

**Comment by guillep** [comment]
I think this issue should be updated for new versions
