### ISSUE TITLE
Improving refactoring: how to merge on method usage into another

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2493]
For example imagine that I have 
- method inBibSet: which is called several time and is equivalent to another method bibSet:. 
I would like to the able to say use bibSet: instead of inBibSet:

S.

**Comment by macta** [comment]
I think the title should be "merge one method usage" (not on)

**Comment by macta** [comment]
I think this is still a valid request, our refactoring tools need more love

**Comment by sbragagnolo** [comment]
Cheking on the issue

**Comment by Lin777** [comment]
Is this not equivalent to RBReplaceMethodRefactoring?

**Comment by Ducasse** [comment]
Probably
