### ISSUE TITLE
Pharo7 - Walkback "new was sent to nil" when saving a method and correcting referenced class name

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2498]
When I was saving a method and I referenced a class "RPakcage" - the autoprompt offered to correct the reference to RPackage, which I selected and then I got this walkback.

This is on OSX, with a recent Pharo 7 image obtained via zeroconf.

UndefinedObject(Object)>>doesNotUnderstand: #new
[ self substituteVariable: each atInterval: interval.
(OCSourceCodeChanged new newSourceCode: self requestor text) signal ] in [ :each | 
labels add: each.
actions
	add: [ self substituteVariable: each atInterval: interval.
		(OCSourceCodeChanged new newSourceCode: self requestor text) signal ] ] in OCUndeclaredVariableWarning>>openMenuIn: in Block: [ self substituteVariable: each atInterval: interv...etc...
OCUndeclaredVariableWarning>>openMenuIn:
OCUndeclaredVariableWarning(OCSemanticWarning)>>defaultAction
OCUndeclaredVariableWarning>>defaultAction
UndefinedObject>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
OCUndeclaredVariableWarning(Exception)>>signal
OCASTSemanticAnalyzer>>undeclaredVariable:
OCASTSemanticAnalyzer>>visitVariableNode:
RBVariableNode>>acceptVisitor:
OCASTSemanticAnalyzer(RBProgramNodeVisitor)>>visitNode:
OCASTSemanticAnalyzer(RBProgramNodeVisitor)>>visitMessageNode:
RBMessageNode>>acceptVisitor:
OCASTSemanticAnalyzer(RBProgramNodeVisitor)>>visitNode:
[ :each | self visitNode: each ] in OCASTSemanticAnalyzer(RBProgramNodeVisitor)>>visitMessageNode: in Block: [ :each | self visitNode: each ]
OrderedCollection>>do:
OCASTSemanticAnalyzer(RBProgramNodeVisitor)>>visitMessageNode:
RBMessageNode>>acceptVisitor:
OCASTSemanticAnalyzer(RBProgramNodeVisitor)>>visitNode:
OCASTSemanticAnalyzer>>visitAssignmentNode:
RBAssignmentNode>>acceptVisitor:
OCASTSemanticAnalyzer(RBProgramNodeVisitor)>>visitNode:
[ :each | self visitNode: each ] in OCASTSemanticAnalyzer>>visitSequenceNode: in Block: [ :each | self visitNode: each ]

**Comment by macta** [comment]
It's kind of a weird one - as it looks like it compiled the correct source with the correct RPackage name, however when the compiler does a #semanticAnalysis it seems like it gets old ast nodes? Seems like one for @MarcusDenker to have a look at?

**Comment by MarcusDenker** [comment]
yes, I will look at it

**Comment by macta** [comment]
I tried this in a fresh image (just creating a method and using the auto-correct on save) and it didn't do it. In my other image (which was downloaded on the 8th) - it reliably does this. I'll keep that image and see if I can repro something. So don't waste any time on it until I find out a bit more.

**Comment by MarcusDenker** [comment]
I tried to re-create it and could not...

**Comment by macta** [comment]
I've not been able to recreate it in any of my recent images. I will close it and keep an eye open
