### ISSUE TITLE
Pharo7 - senders window doesn't let you keyboard cursor down methods

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2507]
When you do a senders query and you get a new calypso browser, the list of methods is not keyboard navigable. In Nautilus is was - and you could down arrow through the list and browse code - now you have to move your mouse and click, which isn't a great way to read code.

I've noticed that keyboard navigation like this is often hit and miss in the Calypso browsers - sometimes it works and other times it doesn't?

**Comment by dionisiydk** [comment]
I can't reproduce it. What platform do you use?

вт, 12 февр. 2019 г. в 18:57, Tim Mackinnon <notifications@github.com>:

**Comment by macta** [comment]
Hi - this is Pharo 7, on OSX (10.13.5) - on a zero conf image downloaded Feb 8th. Here's a photo - and it looks like the selected method has focus but the arrow keys don't work?

Not sure if it makes a difference, but the image is full screen?

![image](https://user-images.githubusercontent.com/5553623/52666002-efbc9900-2f04-11e9-980e-e2ea5795c9ac.png)

**Comment by macta** [comment]
I've just loaded a new image and you're right the same query at first go, seems fine.
I wonder if its something about zeroConf or the vm it downloads - I'll try working in this fresh image for a while and see if I spot something odd. So lets wait and see, parituclarly if its not something you've noticed (it did seem weird)

**Comment by macta** [comment]
I will save the image that demonstrates this problem, and try working in a fresh image and see if its something that gets loaded in that causes this.

**Comment by macta** [comment]
I hit this again in build 1436 (OSX, 64bit) - the iceberg window wouldn't let me use the cursor keys, nor would the senders window or they system browser.

I wonder if it has something to do with running in full screen mode? I tried minimising and at first I couldn't use cursor keys in lists but then it started working again. Going back to full screen has kept it working. It seems that it gets into some strange mode where it stops working? It almost seems that when you click on a list item it shows the selection colour but bounces away somehow.?

**Comment by macta** [comment]
@dionisiydk I'm going to close this, as subsequent images haven't exhibited it. If I get something more concrete (e.g. it happens in the latest 7.01 image) then I will find and reopen it.
