### ISSUE TITLE
Refactorings: Why dragging and dropping a class within the same class is calling a move refactoring

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2527]
Especially when the refactoring fails for nothing. 

Scenario. 
I wanted to move a class methods into another protocols on the same class and class side. 
I do not get why this is invoking a refactoring that is failing :(

**Comment by Ducasse** [comment]
This behavior seems to only happen when dragging class side initialize methods!

**Comment by dionisiydk** [comment]
Can you give concrete steps to reproduce?

ср, 13 февр. 2019 г. в 20:22, StéphaneDucasse <notifications@github.com>:
