### ISSUE TITLE
[Removing global action] Introduce DisplayableObject 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2531]
To remove many of the Smalltalk ui icons .... and we should introduce
- DisplayableObject for objects that are not Model (this bug entry)
- Model should be a subclass of DisplayableObject

**Comment by Ducasse** [comment]
For example Paragraph is using theme but it is not a model and does not need an icon. 
So it could be a DisplayableObject, same for Borderedxxx

**Comment by Ducasse** [comment]
BorderStyle should be a subclass of DisplayableObject

**Comment by astares** [comment]
DisplayableObject is an unusual name.

I would suggest to name it "DisplayObject" as you will find in most other frameworks. (VisualSmalltalk, Adobe, ...)

**Comment by pavel-krivanek** [comment]
We already have the DisplayObject with a different meaning. DisplayableObject looks a little bit confusing to me. I would propose UIObject, UIAwareObject or something like that.

**Comment by Ducasse** [comment]
OK we will discuss it and we will see. UIObject or UIAwareObject is not nice.
