### ISSUE TITLE
Spec MenuPresenter

### ISSUE THREAD

**Issue by mahugnon** [guillep/pharo-core#2534]
#MenuPresenter
1. I want to access a specific menuItem 
    - I didn't find a suitable API to do it
    -Here is an example
            `| navigationMenuGroup buttonMorph |
	navigationMenuGroup := menuPresenter menuGroups second.
	buttonMorph := navigationMenuGroup menuItems at: anIndex.
	buttonMorph enabled: aBoolean.`
2. The Spec widget does not update automatically.
      . For example, the above example works if the widget has not been created yet. 
       .If the widget is created, here is what one have to do to update the widget automatically   
`| dockingBarMorph |
		dockingBarMorph := self widget widget submorphs first submorphs first submorphs first findA: ToolDockingBarMorph.
		((dockingBarMorph submorphs last: 2) at: anIndex) enabled: aBoolean ]`

**Comment by guillep** [comment]
Hi @mahugnon, this issue belongs to spec, maybe we can put it in the spec issue tracker?
https://github.com/pharo-spec/Spec

**Comment by mahugnon** [comment]
ok
