### ISSUE TITLE
ListPresenter Spec

### ISSUE THREAD

**Issue by mahugnon** [guillep/pharo-core#2535]
There is no easy way to get a ListPresenter context menuItem programmatically. 
`ListPresenter>>menu` return `aBlock`  instead of the actual context menu.

**Comment by Ducasse** [comment]
Hello honore 
did you check with cyril because we are entering the issue on the pharo-spec github repo. 

Stef

**Comment by mahugnon** [comment]
ok I will check with him

Le jeu. 14 févr. 2019 à 16:55, StéphaneDucasse <notifications@github.com> a
écrit :
