### ISSUE TITLE
settings message senders are dead code because there is no implementors of settings

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2538]
Example

selectionColor: aColor
	"Set the colour for selected items."

	|w|
	aColor
		ifNil: [self removeProperty: #selectionColor]
		ifNotNil: [self setProperty: #selectionColor toValue: aColor].
	w := self ownerThatIsA: SystemWindow.
	self selectionColorToUse: (
		(self theme settings fadedBackgroundWindows not or: [w isNil or: [w isActive]])
			ifTrue: [aColor]
			ifFalse: [self theme unfocusedSelectionColor])

**Comment by Ducasse** [comment]
The senders and implementors were scoped. So they could not be found.

**Comment by dionisiydk** [comment]
Should we switch to global scope automatically when current scope gives an
empty result?

There is opened PR in Calypso
<https://github.com/pharo-ide/Calypso/pull/438>with some notes on this
idea. Please add some comments there.

чт, 14 февр. 2019 г., 17:47 StéphaneDucasse notifications@github.com:
