### ISSUE TITLE
looks like settings in UITheme cannot be recreated...

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2539]
defaultSettings
	"Answer the default settings for the theme."
	
	^defaultSettings ifNil: [
		self defaultSettings: self newDefaultSettings.
		defaultSettings]

The method newDefaultSettings is full of message to undefined methods!
newDefaultSettings
	self setPreferredPreferences.
	
	^ThemeSettings new
		buttonColor: Color gray;
		scrollbarColor: Color gray;
		menuColor: self baseColor;
		menuTitleColor: self baseColor;
		windowColor: self baseColor;
		selectionColor: self lightSelectionColor;
		menuSelectionColor: self baseSelectionColor;
		progressBarColor: self baseColor;
		standardColorsOnly: true;
		autoSelectionColor: false;
		preferRoundCorner: false;
		fadedBackgroundWindows: false;
		flatMenu: true

**Comment by jecisc** [comment]
Keep

**Comment by hilaire** [comment]
May be it was removed at some point. Some archeology may be needed in past Pharo image.

**Comment by hilaire** [comment]
These messages appear to be abstract at the UITheme class level. I propose to implement them with subclassResponsability message sent

**Comment by Ducasse** [comment]
Yes it can be a first step. 
Tx hilaire

**Comment by hilaire** [comment]
Btw, there is this methods PharoLightTheme>>setPreferredShoutColors never used..
