### ISSUE TITLE
Lint problem in #allUnreferencedInstanceVariables

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#2552]
The method Behavior>>#allUnreferencedInstanceVariables calls the method #classThatDefinesInstanceVariable: which is provided in subclass ClassDescription

This leads to a lint error "Super and Self Messages sent but not implemented"

The options to fix:

 1. We push the method #allUnreferencedInstanceVariables down to ClassDescription
 2. We pull the method #classThatDefinesInstanceVariable up into Behavior

I would vote for the first. Any comments or opinions?

**Comment by pavel-krivanek** [comment]
I would push it down (1). Now when traits are classes it has no real practical impact and it is not core Behavior functionality

**Comment by astares** [comment]
Fixed in https://github.com/pharo-project/pharo/pull/2553
