### ISSUE TITLE
Epicea: EpApplyPreviewer sourceEntries and logBrowserModel ivars not used

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#2554]

**Comment by astares** [comment]
to be fixed in Epicea (https://github.com/tinchodias/epicea/issues/1)

**Comment by Ducasse** [comment]
Tx! Epicea is not managed outside of Pharo.

**Comment by Ducasse** [comment]
So we should fix it in this repo.

**Comment by astares** [comment]
Fixed in https://github.com/pharo-project/pharo/pull/2555
