### ISSUE TITLE
Model / DisplayableObject relation should be thought carefully

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2561]
- Naively I was thinking that DisplayableObject should be a superclass of Model so that we can 
also directly inherit from it (some objects are not model but still want to have theme, and other)
- DisplayableObject should probably also offer UIManager default access. 
- I'm thinking that DisplayableObject could be a subclass of Model. But may be it should not. 
In any case it should packaged in a UI package because right now Model is not depending on UI concerns. So it would be good not to introduce it.

**Comment by Ducasse** [comment]
This is still active. I'm waiting for Spec 20 to have have an icon manager and a theme method so that I can check all the non Model/presenter users of smalltalk ui theme smalltalk ui icons....

**Comment by guillep** [comment]
This is a big non punctual thing, difficult to action.
I propose to close it, maybe this should be moved to a place/wiki that stores "project ideas".
