### ISSUE TITLE
HandMorph cleanups required

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#2564]
HandMorph allUnreferencedInstanceVariables 

returns "#(#keyboardListeners #eventSource #lastSystemEvent)"

Do we still need them?

**Comment by astares** [comment]
fix in https://github.com/pharo-project/pharo/pull/2565

**Comment by jecisc** [comment]
They cannot be removed or your image will crash. 

I am already working on removing unused instance variable (https://github.com/pharo-project/pharo/pull/2468, https://github.com/pharo-project/pharo/pull/2503, https://github.com/pharo-project/pharo/issues/2494) and I already know most of the ivar we should not remove. If you can way a little I'll finish my cleanup, add a way to mark which unused var should be kept and add a release test.

**Comment by astares** [comment]
Already fixed a few today.

No - my image is working fine after removing them. Did I miss something?

**Comment by jecisc** [comment]
![screenshot 2019-02-15 at 11 17 56](https://user-images.githubusercontent.com/9519971/52850289-6333f580-3113-11e9-9167-c738b8a482cd.png)

Yes, it does make the image crash in some cases. I don't know this part of the system well enough to know how we get those events making the image crash, but it happens.

**Comment by astares** [comment]
Maybe this is on Mac due to the migrations of ivar order and event processing when loading the code or applying the change.

I can work with the image without problems on Linux and Windows. If the image is freshly built it should work anyhow. Can you try a CI built fresh image of the PR on Mac?

**Comment by astares** [comment]
@jecisc Can you try again on Mac?

**Comment by hilaire** [comment]
I just tested on Ubuntu/P8 64 bits, no crash. 
Just an error once right after the changes.

```
Point(Object)>>doesNotUnderstand: #hand
	Receiver: (284@108)
	Arguments and temporary variables: 
		aMessage: 	hand
		exception: 	MessageNotUnderstood: Point>>hand
		resumeValue: 	nil
	Receiver's instance variables: 
		x: 	284
		y: 	108


MouseOverHandler>>handleAsMouseOver:
	Receiver: a MouseOverHandler
	Arguments and temporary variables: 
		anEvent: 	(284@108)
	Receiver's instance variables: 
		mouseOverMorphs: 	an Array(a RubEditingArea(773896448) a TransformWithLayoutMorp...etc...
		enteredMorphs: 	a WriteStream
		overMorphs: 	a WriteStream
		leftMorphs: 	an IdentitySet(a SystemWindow(908144384) named: HandMorph a Morph(9...etc...


MouseOverHandler>>processMouseOver:
	Receiver: a MouseOverHandler
	Arguments and temporary variables: 
		anEvent: 	(284@108)
	Receiver's instance variables: 
		mouseOverMorphs: 	an Array(a RubEditingArea(773896448) a TransformWithLayoutMorp...etc...
		enteredMorphs: 	a WriteStream
		overMorphs: 	a WriteStream
		leftMorphs: 	an IdentitySet(a SystemWindow(908144384) named: HandMorph a Morph(9...etc...


HandMorph>>handleEvent:
	Receiver: a HandMorph(1064782080)
	Arguments and temporary variables: 
		anEvent: 	[keystroke '<Ctrl-s>']
		evt: 	[keystroke '<Ctrl-s>']
	Receiver's instance variables: 
		bounds: 	(830@671) corner: (846@687)
		owner: 	a WorldMorph(406596096) [world]
		submorphs: 	#()
		fullBounds: 	(830@671) corner: (846@687)
		color: 	Color blue
		extension: 	a MorphExtension (848790528)
		mouseFocus: 	nil
		keyboardFocus: 	a RubEditingArea(773896448)
		eventListeners: 	nil
		mouseListeners: 	nil
		mouseClickState: 	nil
		mouseOverHandler: 	a MouseOverHandler
		lastMouseEvent: 	[(838@680) mouseOver 56350 nil]
		targetOffset: 	(284@108)
		damageRecorder: 	a DamageRecorder
		cacheCanvas: 	nil
		cachedCanvasHasHoles: 	false
		temporaryCursor: 	Form(16x16x8)
		temporaryCursorOffset: 	(-8@ -9)
		hardwareCursor: 	((CursorWithMask
	extent: (16@16)
	depth: 1
	fromArray: #(
		2r...etc...
		hasChanged: 	true
		savedPatch: 	nil
		lastEventBuffer: 	#(1 56350 838 680 0 0 0 1)
		lastKeyScanCode: 	115
		combinedChar: 	nil
		captureBlock: 	nil
		recentModifiers: 	2


HandMorph>>processEventsFromQueue:
	Receiver: a HandMorph(1064782080)
	Arguments and temporary variables: 

```

**Comment by MarcusDenker** [comment]
I did a PR from source (right from github). This way the image will be bootraped with the three vars removed
