### ISSUE TITLE
Pressing proceed on a failed test incorrectly gives a green bar

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2566]
In a fresh image if you create a simple HelloWorld class with method:

hello
 ^'goodbye'

And then have a TestCase - HelloWorldTest with a test

testHello
  self assert: HelloWorld hello equals: 'Hello World'

When you runt he test you will get the correct assertion failed walkback - but if you press continue SUnit finishes running and shows a Green bar? This is wrong!

**Comment by macta** [comment]
Unfortunately In Pharo 8, this is still the case and I still believe its the wrong behavior

**Comment by gcorriga** [comment]
@macta can you please check in a Pharo 9 image? I am unable to press proceed now.

**Comment by macta** [comment]
@gcorriga - it does seem like the new debugger now disables the "proceed" button - however if you use the new  "advanced step" button , then "to return", and then press "proceed" - the test will then complete, show a green success notificaion and mark the method orb with a green circle.

So I think that disabling the button is a kind of workaround so you don't have to mark failed methods properly - but I think in the context of when I reported this, the solution is probably fine.
