### ISSUE TITLE
Can't format code in the debugger

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2569]
We talk a lot about coding in the debugger (which is fab) - but why can't we reformat the code in the debugger? The menu item is mising.

**Comment by macta** [comment]
This is still relevant in Pharo 8, however, I notice there is a workaround - it appears that in the debugger, CMD-T (suggest) doesn't always give the full menu like in the regular editor (which has Format Code as the list item) - instead it gives much more context sensitive info. However, if you select all the code  and CMD-T - format is available (and it is also available if you happen to go to the top of the code as well). The trouble is - not many would know this, and often you have fixed a bug in the middle of of your code and then the format menu item, or suggest menu item - just don't appear.

**Comment by guillep** [comment]
Hi @macta 

The CMD+T is the suggestions menu.
It does not show the entire set of options (like copy/paste too).
It only shows options related to the place where the caret is (like, the variable or call-site).

It also seems the main menu is not showing the formatting entry.

Does the shortcut CMD+SHIFT+F do the reformat for you?

I'd like to summarize:
 - the "format method" option is not in the (debugger) menu entry
 - but it is available in the suggestions for the entire method
 - we can format using the shortcut

So we should add the "format method" menu entry in the main menu, is that it?
Maybe I misunderstood

**Comment by macta** [comment]
Hi Guile - there are 2 things wrong in current P8, CMD-T doesn’t work in the debugger (the shortcut isn’t enabled).

If you right click and get the context menu - there is no “source code” sub menu (which cmd-t should trigger) and then in that menu is format .

See photo - where I have added some code in the debugger and wanted to format it (in fact - as we always claim that we code in the debugger, the debugger code pane should operate the same way as the code pain in the system browser).
![image](https://user-images.githubusercontent.com/5553623/77753997-6988e680-7022-11ea-9d0e-bcd9a3d67cdd.png)

**Comment by StevenCostiou** [comment]
This is now possible in Pharo 9 with the new debugger. I propose to close this issue.
