### ISSUE TITLE
Command line --list get an error

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2575]
/Applications/Pharo/Pharo70-64.app/Contents/MacOS/Pharo P7-Citezen.image --list

Currently installed Command Line Handlers:
    loadHermes                Loads the hermes files passed as parameter
    printVersion              Print image version
    save                      Rename the image and changes file
    initializePackages        Initialize packages and protocols from a given lists
    st                        Loads and executes .st source files
    config                    Install and inspect Metacello Configurations from the command line
    metacello                 Install and inspect Metacello Baselines/Configurations from the command line
    test                      A command line test runner
    Fuel                      Loads fuel files
    clean                     Run image cleanup
    get                       Install catalog projects from the command line (consult catalog at http://catalog.pharo.org)
    perform                   Perform given message on a specified class or global
    SmaCCCompareParseTrees    --
    eval                      Directly evaluates passed in one line scripts
BlockCannotReturn
Context>>cannotReturn:
[ :exit | 
"If the command line is protected by password, we just exit the image because in non-headless mode the handleExit will let the image open. If the password protection is enabled, it is to avoid to let the access to the image."
self class commandLinePasswordManager hasPasswordSet
	ifTrue: [ Smalltalk snapshot: false andQuit: true ].
^ self handleExit: exit ] in [ [ self
	handleArgument:
		(self arguments
			ifEmpty: [ '' ]
			ifNotEmpty: [ :arguments | arguments first ]) ]
	on: Exit
	do: [ :exit | 
		"If the command line is protected by pas

**Comment by Ducasse** [comment]
/Applications/Pharo/Pharo70-64.app/Contents/MacOS/Pharo P7-Citezen.image --eval "CZFileSorter new sortFile: 'rmod.bib'"

Invalid argument also produces a stack trace

**Comment by Ducasse** [comment]
@svenvc Sven can you reproduce the problem? or it is only me?
I took the default pharo 70 + vm 64

**Comment by svenvc** [comment]
I can't run your Citezen code, but with a stock image downloaded using zeroconf I get
```
prometheus:2019-02-14 sven$ ls
Pharo.changes			Pharo7.0-32bit-b882595.sources	pharo-local			pharo-vm
Pharo.image			pharo				pharo-ui

prometheus:2019-02-14 sven$ ./pharo Pharo.image printVersion
[version] 'Pharo7.0.1' 'Pharo-7.0.1+build.142.sha.b8825954d0dcff883bf4f47ea5c516c9cfc2fe4b (64 Bit)'

prometheus:2019-02-14 sven$ ./pharo Pharo.image --list
Currently installed Command Line Handlers:
    loadHermes            Loads the hermes files passed as parameter
    printVersion          Print image version
    save                  Rename the image and changes file
    initializePackages    Initialize packages and protocols from a given lists
    st                    Loads and executes .st source files
    config                Install and inspect Metacello Configurations from the command line
    metacello             Install and inspect Metacello Baselines/Configurations from the command line
    test                  A command line test runner
    Fuel                  Loads fuel files
    clean                 Run image cleanup
    get                   Install catalog projects from the command line (consult catalog at http://catalog.pharo.org)
    perform               Perform given message on a specified class or global
    eval                  Directly evaluates passed in one line scripts
```

**Comment by Ducasse** [comment]
Sven I did the following and I get the same

/Applications/Pharo/Pharo70-64.app/Contents/MacOS/Pharo P7-Citezen.image --eval 1 + 2
Invalid arguments: "--eval 1 + 2"
sage: [<subcommand>] [--help] [--copyright] [--version] [--list] [ --no-quit ]
	--help       print this help message
	--copyright  print the copyrights
	--version    print the version for the image and the vm
	--list       list a description of all active command line handlers
	--no-quit    keep the image running without activating any other command line handler
	--deploymentPassword if a password needs to be used by the user to launch the command
	<subcommand> a valid subcommand in --list
	
	Preference File Modification:
	--preferences-file   load the preferences from the given <FILE>
	--no-default-preferences    do not load any preferences from the default locations
	
Documentation:
A PharoCommandLineHandler handles default command line arguments and options.
The PharoCommandLineHandler is activated before all other handlers. 
It first checks if another handler is available. If so it will activate the found handler.
Error: Command line handler failed
PharoCommandLineHandler(BasicCommandLineHandler)>>handleExit:for:
PharoCommandLineHandler(BasicCommandLineHandler)>>handleExit:
[ :exit | 
"If the command line is protected by password, we just exit the image because in non-headless mode the handleExit will let the image open. If the password protection is enabled, it is to avoid to let the access to the image."
self class commandLinePasswordManager hasPasswordSet

**Comment by svenvc** [comment]
it is not --eval but just eval

**Comment by Ducasse** [comment]
ahhh but still it should not break. 

I checked

/Applications/Pharo/Pharo70-64.app/Contents/MacOS/Pharo --headless P7-Citezen.image --eval "CZFileSorter new sortFile: 'rmod.bib'"
and reports  that the command line is invalid and there is not stack printed.
