### ISSUE TITLE
Scroll bar in Welcome window is not reset when changing the page

### ISSUE THREAD

**Issue by rillig** [guillep/pharo-core#2577]
I downloaded and launched Pharo-7.0.0-alpha.build.1384.sha.c34d6a6.arch.64bit.

In the Welcome screen I selected the Changelog and scrolled to the very bottom:

![image](https://user-images.githubusercontent.com/3233724/52912608-df653f00-32b3-11e9-9bc8-8fd78551af93.png)

Then I changed the page to Learn Pharo:

![image](https://user-images.githubusercontent.com/3233724/52912616-ec822e00-32b3-11e9-8b87-0323c326702d.png)

I expected the scrollbar at the right to start at position 0. Instead, it starts at some other value, which hides the top of the page.

Either:
- the Welcome window should remember the scroll bar position for each of the pages individually, or
- the Welcome window should reset the scrollbar position to 0 when the page is changed

**Comment by Ducasse** [comment]
Thanks this tool will be rewritten with the new version of Spec so we close this bug entry.
