### ISSUE TITLE
Test result notification uses wrong plural forms

### ISSUE THREAD

**Issue by rillig** [guillep/pharo-core#2578]
I have added a second test case to `PDFColorTest` and made it fail intentionally, just to get my hands wet with testing.

![image](https://user-images.githubusercontent.com/3233724/52912821-2c96e000-32b7-11e9-9fa4-326466062114.png)

The yellow notification says "1 failures", which is grammatically wrong. It should be "1 failure" instead.

**Comment by rillig** [comment]
Here is my suggestion for `TestResult.printOn`:

```smalltalk
printOn: aStream
	| putN sep |
	sep := ''.
	putN := [ :n :singular :plural |
		n = 0 ifFalse: [
			aStream
				nextPutAll: sep;
				nextPutAll: n printString;
				nextPutAll: ' ';
				nextPutAll: (n = 1 ifTrue: singular ifFalse: plural).
			sep := ', '
		]
	].

	putN value: self runCount value: 'run' value: 'run'.
	putN value: self expectedPassCount value: 'pass' value: 'passes'.
	putN value: self skippedCount value: 'skipped' value: 'skipped'.
	putN value: self expectedDefectCount value: 'expected failure' value: 'expected failures'.
	putN value: self unexpectedFailureCount value: 'failure' value: 'failures'.
	putN value: self unexpectedErrorCount value: 'error' value: 'errors'.
	putN value: self unexpectedPassCount value: 'unexpected pass' value: 'unexpected passes'.
	sep = '' ifTrue: [ aStream nextPutAll: 'no tests run' ].
```

I tested it interactively, but as a Pharo beginner, I cannot estimate what influence the changed formatting of this message has on the whole system.

**Comment by svenvc** [comment]
Did you see String>>#asPluralBasedOn: ?
Check its senders as well.
That will simplify your code.

**Comment by rillig** [comment]
> Did you see String>>#asPluralBasedOn: ?

I think the above code has too many exceptional cases to make `asPluralBasedOn` useful in this case. For example, there is `run` and `run` (which presumably is an abbreviation of `test has been run` and `tests have been run`), and there is `pass` and `passes`. Therefore I prefer to leave the code as it is right now.

Thanks for the hint anyway, I would not have thought that such a function existed at all since most other programming languages also don't have it. Furthermore it is useless in an internationalized context where [the rules are much more complicated](https://www.unicode.org/cldr/charts/34/supplemental/language_plural_rules.html).

**Comment by bencoman** [comment]
Side topic - what are you doing with PDFs?  Have you Christian Haider's library [PDFTalk library](https://wiki.pdftalk.de/doku.php) which a few people would love ported to Pharo.

**Comment by rillig** [comment]
I'm just browsing through some code to get my hands wet on Pharo. Nothing in particular. I was just lucky to find some unit tests that were easy to adjust and extend, just to learn the Smalltalk syntax. I'm more doodling around.

**Comment by svenvc** [comment]
By putting everything in the passed tense and some rewording, my version would be
```
printOn: aStream
  aStream
    print: self runCount; nextPutAll: ' ran, ';
    print: self expectedPassCount; nextPutAll: ' passed, ';
    print: self skippedCount; nextPutAll: ' skipped, ';
    print: self expectedDefectCount; nextPutAll: (' expected failure' asPluralBasedOn: self expectedDefectCount); nextPutAll: ', ';
    print: self unexpectedFailureCount ; nextPutAll: (' failure' asPluralBasedOn: self unexpectedFailureCount); nextPutAll: ', ';
    print: self unexpectedErrorCount; nextPutAll: (' error' asPluralBasedOn: self unexpectedErrorCount); nextPutAll: ', ';
    print: self unexpectedPassCount; nextPutAll:' passed unexpected'.
```
I would not make a special case for 0, since this is not a common case. If need be, a
```
  self runCount isZero ifTrue: [ ^ aStream nextPutAll: 'No tests ran' ].
```
could be added.
This intentional formatting results in some relatively long lines, just about acceptable, the alternative, with each cascaded message send on a line, would work too.

**Comment by svenvc** [comment]
https://github.com/pharo-project/pharo/pull/2695
