### ISSUE TITLE
Archive>>addTree:match: does not preserve folder structure resulting in a flat list

### ISSUE THREAD

**Issue by a2b-alb** [guillep/pharo-core#2584]
(Zip)Archive>>addTree:match: does not preserve folder structure of the original source folder resulting in a flat list.

It can be reproduced like:
|zip|
zip := ZipArchive new.
zip addTree: 'folderToZip' match: [ :e | true ].
zip writeToFileNamed: 'new.zip'.

Images is running on a centos 7

Info from system reporter:

Image: Pharo7.0.1
Build information: Pharo-7.0.1+build.142.sha.b8825954d0dcff883bf4f47ea5c516c9cfc2fe4b (64 Bit)

Virtual Machine:
CoInterpreter VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan  5 2019
StackToRegisterMappingCogit VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan  5 2019
VM: 201901051900 https://github.com/OpenSmalltalk/opensmalltalk-vm.git Date: Sat Jan 5 20:00:11 2019 CommitHash: 7a3c6b64 Plugins: 201901051900 https://github.com/OpenSmalltalk/opensmalltalk-vm.git

Unix built on Jan  5 2019 19:12:23 Compiler: 4.8.4
VMMaker versionString VM: 201901051900 https://github.com/OpenSmalltalk/opensmalltalk-vm.git Date: Sat Jan 5 20:00:11 2019 CommitHash: 7a3c6b64 Plugins: 201901051900 https://github.com/OpenSmalltalk/opensmalltalk-vm.git
CoInterpreter VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan  5 2019
StackToRegisterMappingCogit VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan  5 2019

**Comment by astares** [comment]
@a2b-alb  Still valid?
