### ISSUE TITLE
Pharo7 - IceGenericError: SecureTransport error: connection closed via error

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2585]
Quite frequently when loading my baseline from an image I will get the erorr: "IceGenericError: SecureTransport error: connection closed via error", and it looks like its some sort of timing/retry issue. As if I immediately try again everything will load fine. I would say 1 time in 8, I will get this kind of error.

Can't we handle it better? I suspect it might be dodgy http response times or network slowdowns - but I don't see much indication of a retry (might be wrong).

In this case the dependent project was: "origin (https://github.com/dionisiydk/StateSpecs.git)"

For the record - this is the stack trace. 

I'm on OSX HighSierra, using Phaor 7.0.1 32bit (this time).

IceLibgitErrorVisitor>>visitGenericError:
IceLibgitErrorVisitor>>visitERROR:
LGit_GIT_ERROR>>acceptError:
[ :e | e acceptError: (IceLibgitErrorVisitor onContext: self) ] in [ [ (LGitRemote of: self repositoryHandle named: self name)
	lookup;
	fetchWithCredentials: (IceCredentialsProvider defaultForRemote: self)
		andProgressCallback: IceGitTransferProgress new ]
	on: LGitAbstractError
	do: [ :e | e acceptError: (IceLibgitErrorVisitor onContext: self) ].

"Call post fetch to fix unknown commits"
localRepository postFetch ] in IceGitHttpsRemote(IceGitRemote)>>fetch in Block: [ :e | e acceptError: (IceLibgitErrorVisitor onCon...etc...
BlockClosure>>cull:
Context>>evaluateSignal:
Context>>handleSignal:
LGit_GIT_ERROR(Exception)>>signal
LGit_GIT_ERROR class(LGitCallReturnHandler class)>>signalWith:
LGitReturnCodeEnum>>handleLGitReturnCode
LGitRemote(LGitExternalObject)>>withReturnHandlerDo:
LGitRemote>>fetchWithCredentials:andProgressCallback:refSpec:
LGitRemote>>fetchWithCredentials:andProgressCallback:
[ (LGitRemote of: self repositoryHandle named: self name)
	lookup;
	fetchWithCredentials: (IceCredentialsProvider defaultForRemote: self)
		andProgressCallback: IceGitTransferProgress new ] in [ [ (LGitRemote of: self repositoryHandle named: self name)
	lookup;
	fetchWithCredentials: (IceCredentialsProvider defaultForRemote: self)
		andProgressCallback: IceGitTransferProgress new ]
	on: LGitAbstractError
	do: [ :e | e acceptError: (IceLibgitErrorVisitor onContext: self) ].

"Call post fetch to fix unknown commits"
localRepository postFetch ] in IceGitHttpsRemote(IceGitRemote)>>fetch in Block: [ (LGitRemote of: self repositoryHandle named: sel...etc...
BlockClosure>>on:do:
[ [ (LGitRemote of: self repositoryHandle named: self name)
	lookup;
	fetchWithCredentials: (IceCredentialsProvider defaultForRemote: self)
		andProgressCallback: IceGitTransferProgress new ]
	on: LGitAbstractError
	do: [ :e | e acceptError: (IceLibgitErrorVisitor onContext: self) ].

"Call post fetch to fix unknown commits"
localRepository postFetch ] in IceGitHttpsRemote(IceGitRemote)>>fetch in Block: [ [ (LGitRemote of: self repositoryHandle named: s...etc...
BlockClosure>>on:do:
IceLibgitRepository>>handleLibgitError:
IceGitHttpsRemote(IceGitRemote)>>fetch
IceLibgitRepository(IceRepository)>>fetchFrom:
[ :found | localRepository fetchFrom: found ] in IceRepositoryCreator>>addLocalRepositoryAndCheckout in Block: [ :found | localRepository fetchFrom: found ]
BlockClosure>>cull:
[ :each | 
(aBlock value: each)
	ifTrue: [ ^ foundBlock cull: each ] ] in Array(Collection)>>detect:ifFound:ifNone: in Block: [ :each | ...
Array(SequenceableCollection)>>do:
Array(Collection)>>detect:ifFound:ifNone:
Array(Collection)>>detect:ifFound:
IceRepositoryCreator>>addLocalRepositoryAndCheckout
IceMetacelloDuplicatedNotification>>useIncoming
IceMetacelloDuplicatedNotification>>defaultAction
UndefinedObject>>handleSignal:

**Comment by macta** [comment]
As a side point - simply trying again from the command line kept giving the same error - I had to clear the iceberg directory to get it to load without this error.

**Comment by macta** [comment]
I will reopen this one if it starts recurring in P8 - its not an obvious one to test, as you have to be loading lots of things

**Comment by olekscode** [comment]
@macta I think you'll have to reopen it
https://github.com/pharo-vcs/iceberg/issues/1326

**Comment by MarcusDenker** [comment]
The problem is that there are two icebergs: the old one (which is in Pharo 8) and a new one that no-one uses. You first need to make sure to see if you did not fix it in the wrong code base. 

Fixing it in the Iceberg repo will not help any users of Pharo8.
