### ISSUE TITLE
Deleting a class with references gives extra "Do you want to delete anyway" msg

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2586]
When you delete a class that has references to it - Pharo helpfully asks you if you want to view the references (which is cool) - if you answer No - you get a superfluous extra question "Do you want to remove anyway?".  This is annoying as if you say yes - you then get the refactoring window that shows you the removal which you can also accept and cancel. Thus you don't need that extra question as you can still cancel.

**Comment by dionisiydk** [comment]
Yes. It needs to be improved.
I just followed the way how it was in Nautilus because it was a simplest
solution

пн, 18 февр. 2019 г. в 16:39, Tim Mackinnon <notifications@github.com>:

**Comment by macta** [comment]
This is still valid in P8 - the extra question should be eliminated.
