### ISSUE TITLE
Backport Pharo7: Cannot remove a Trait

### ISSUE THREAD

**Issue by cdlm** [guillep/pharo-core#2587]
Trying to remove a trait (stateful) from Calypso
- "there are subclasses, show them?" → don't ask, directly show them (usability)
- the list is actually empty (since my trait is unused) → skip the previous dialog in that case
- the changes window doesn't show me the trait's code that's going to be removed, just a "Remove TMyTrait"
- confirming removal brings a debugger about `Error invalid definition string from RBAddClassChange class` → bug in the actual removal code ?

**Comment by dionisiydk** [comment]
I found a bug in traits:
```Smalltalk
ATrait subclasses "==> #()"
ATrait hasSubclasses "==> true"
```

**Comment by dionisiydk** [comment]
Because the implementation: 
```Smalltalk
Class>>hasSubclasses
	^subclasses notNil
```
And for traits it is an empty array

**Comment by MarcusDenker** [comment]
This has been fixed in Pharo 8 but needs to be back ported to Pharo7

**Comment by MarcusDenker** [comment]
https://github.com/pharo-project/pharo/pull/2721

**Comment by MarcusDenker** [comment]
the Pharo 8 PR is here: https://github.com/pharo-project/pharo/pull/2721

**Comment by estebanlm** [comment]
what's the status of this?

**Comment by MarcusDenker** [comment]
Both Pharo 8 and Pharo7 have been merged --> we can close the issue
