### ISSUE TITLE
New Rubric widget has placeholder centered instead of left aligned

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2588]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/22846
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 28 December 2018 11:14:58 am
	
Description:
	
In the new rubric widget that got integrated the placeholder have a regression because they are centered instead of left aligned.

**Comment by jecisc** [comment]
Reply:
Author: Alain Plantec
Date: 31 December 2018 2:11:06 pm
	
Message:
	
If I understand well, it is just a question of look.
I guess that by default, a ghost text is centered.
easy to fix anyway

**Comment by jecisc** [comment]
Reply:
Author: CyrilFerlicot
Date: 2 January 2019 2:28:26 pm
	
Message:
	
Yes, usually placeholders are on the left and not in the center.

**Comment by Ducasse** [comment]
this is important to fix it. 
Could we get rid of this adevertisment for this guy.

**Comment by guillep** [comment]
This was fixed in ad260af
