### ISSUE TITLE
Cannot add a tab when cursor is at the end of a word

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2591]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/22715
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 30 November 2018 10:16:57 am
	
Description:
	
When you are at the end of a word and hit "tab", nothing will happen. You need to do a space before been able to do a tab.

**Comment by jecisc** [comment]
Still valid

**Comment by marcor** [comment]
Not able to reproduce this, tab seems to work fine on Pharo 11.
