### ISSUE TITLE
Subclasses of Morph and Model should use self theme 

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2592]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/22631
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 5 November 2018 3:43:59 pm
	
Description:
	
Instead of hardcoding `Smalltalk ui theme`. 

We should also add a rule and release test.

**Comment by jecisc** [comment]
Still valid.

**Comment by hilaire** [comment]
Duplicate of #2404

**Comment by MarcusDenker** [comment]
#2404 has been merged, so this one is done, too?
