### ISSUE TITLE
UITheme class is missing methods

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2593]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/22645
Status: Work Needed
Project: UI
Original Author: CyrilFerlicot
Date: 8 November 2018 10:18:38 am
	
Description:
	
In the instance side of UITheme, methods from the class side are called but not implemented. (For example #baseColor or #darkBaseColor).

They should be implemented even if they are subclass responsibility.

**Comment by jecisc** [comment]
Still valid

**Comment by hilaire** [comment]
Duplicate of #2539

**Comment by MarcusDenker** [comment]
Closed as Duplicate
