### ISSUE TITLE
Package manifest does not takes numbers into account for names

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2595]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/22647
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 8 November 2018 1:46:34 pm
	
Description:
	
When we create a Package manifest apparently numbers in the name are not taken into account. For example, the manifest of Spec-Deprecated80 will be ManifestSpecDeprecated. 

This cause a problem because we have a package Spec-Deprecated and Spec-Deprecated80 and creating a manifest for the second delete the manifest of the first one.

**Comment by jecisc** [comment]
Still valid

**Comment by MarcusDenker** [comment]
this is fixed as part of https://github.com/pharo-project/pharo/pull/5732 (review needed)
