### ISSUE TITLE
Add a command to open files natively

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2596]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/22514
Status: Work Needed
Project: Tools
Original Author: CyrilFerlicot
Date: 3 October 2018 8:41:10 am
	
Description:
	
I want to add a new feature for Iceberg and for that I need to be able to open a folder natively in the OS. 

It is possible to do it with LibC and I think it would be a cool feature to have directly in Pharo. 

I'll try to do  a PR when I'll have the time.

**Comment by tesonep** [comment]
Moved to Iceberg
