### ISSUE TITLE
Cursor should change to a pointer over links

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2597]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/22562
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 9 October 2018 1:07:36 pm
	
Description:
	
I see that we now have links in the welcome window. It is not explicit they are links. The cursor should change to a pointer when it's over those links.

**Comment by jecisc** [comment]
Still valid

**Comment by guillep** [comment]
Could we have a reproducible case?

**Comment by guillep** [comment]
Ok, I misread the initial comment (too many fogbugz stuff).
So in the help window, cursor does not react to links.

![image](https://user-images.githubusercontent.com/708322/77750076-75c17380-7023-11ea-9bd6-ec220130dbf3.png)

**Comment by pavel-krivanek** [comment]
it looks like an issue that should be simple to fix but I tried to look at it some time ago and it is almost impossible with the current Rubric architecture...

**Comment by estebanlm** [comment]
morphic does not allow us to do that.
