### ISSUE TITLE
#isSpecial is not an explicit name for a method

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2598]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/22586
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 16 October 2018 7:51:58 am
	
Description:
	
While browsing the implementation of Association I found a method #isSpecial. 

The name is not revealing. Maybe this method (and its other implementations) can have a better name? Because what does it mean that it is special or not?

**Comment by MarcusDenker** [comment]
needsFullDefinition is a better name.

TODO: add transforming deprecation, then check senders of #isSpeecial
