### ISSUE TITLE
Debugger menus do not show tooltips of the debug actions.

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2604]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/21614
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 17 March 2018 11:56:05 pm
	
Description:
	
Debuger actions can add an help for the user, but the context menus in the debugger do not display any tooltip. They should display a tooltip if we stay hover an item of the menu to explain it.

I am adding the helps missing in 21613

**Comment by Ducasse** [comment]
Merged!
