### ISSUE TITLE
#reset methods should be in 'initialization' protocol and a test should ensure we do not have regression

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2607]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/20683
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 13 November 2017 1:33:33 pm
	
Description:
	
First we should correct and integrate the subcases. 

We should add a test/rule to ensure #reset methods are in 'initialization' by convention. 

See : http://forum.world.st/Convention-for-quot-reset-quot-methods-td5019493.html

**Comment by jecisc** [comment]
Still relevant.

**Comment by hilaire** [comment]
I will look at this one, so I can learn more on automatic categorization and test/rule

**Comment by hilaire** [comment]
commit #987c767 should not be there. Can be discarded.

**Comment by hilaire** [comment]
Any pointer to the place to look for the automatic categoriser and rule/test?
Thanks

**Comment by Ducasse** [comment]
Hilaire
In https://github.com/Ducasse/MethodCategorizer there are two little helper classes that I use to analyse the distribution and to fix categorisation. 
After inside Pharo I do not remember but I fixed the system so that he beter categorizes the methods but I do not remember where it is. 
S.

<blockquote><img src="https://avatars2.githubusercontent.com/u/432549?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/Ducasse/MethodCategorizer">Ducasse/MethodCategorizer</a></strong></div><div>Harvesting the old method categorizer and little tools from Smalltalkhub. - Ducasse/MethodCategorizer</div></blockquote>

**Comment by jecisc** [comment]
@hilaire Hi,

I already have an image with the rule but my problem is that some reset methods are part of Iceberg. 

Until Iceberg is fixed and integrated we cannot add it. :(

**Comment by hilaire** [comment]
ok.

**Comment by guillep** [comment]
What is the status of this? Was there an issue open in iceberg?

**Comment by gypsydave5** [comment]
Well, I'm having a crack at this. Running this 'orrible bit of code:

```smalltalk
(Smalltalk 
	globals 
	allBehaviors 
	flatCollect: [ :class | class methods ])
	select: 
	[ :method | 
		method selector == #reset 
			and: [ method protocol ~= #initialization ]].
```

comes up with *44* `#reset` methods in the wrong protocol. Poking that shows that they're in *29* packages. 

trying the following, with `methods` bound to the above:

```smalltalk
methods groupedBy: [ :m | [ m package iceRepository ] on: Error do: [ nil ] ]
```

would indicate that there are 26 methods in the base image, and in external repos:

- 5 in iceberg
- 3 in Roassal3
- 1 in libgit2-pharo-bindings
- 4 in Spec
- 5 in NewTools

would the best way to handle these be PRs or issues in the external repos, as well as making the 26 changes to this repo in a PR?

**Comment by MarcusDenker** [comment]
Yes, cleanup changes are like that... the best is to do a TODO list here and open issues for the other repos and then do it slowly step-by-step.

For #reset, we should discuss if this is really good for all classes or if this is just really needed on the class side.

To me, this is more the class side where we know that the domain is initialization, on the instance side I don't think this is always the case that it has to do with inialization.

**Comment by gypsydave5** [comment]
> For #reset, we should discuss if this is really good for all classes or if this is just really needed on the class side.

If we can agree that a minimum is to do this recatagorization for all `#reset` methods on the class side, then I'd suggest doing that straight off and picking up the rest as and when there's agreement.

**Comment by gypsydave5** [comment]
## Class Side

- [x] `pharo` 
  - [x] [Pull Request opened](https://github.com/pharo-project/pharo/pull/9999)
  - [x] merged
- [x] `iceberg`
  - [x] [Pull Request opened](https://github.com/pharo-vcs/iceberg/pull/1535)
  - [x] merged
- [x] `Roassal3`
  - [x] [Pull Request opened](https://github.com/ObjectProfile/Roassal3/pull/419)
  - [x] merged
- [x] `Spec`
  - [x] [Pull Request opened](https://github.com/pharo-spec/Spec/pull/1148)
  - [x] merged
- [x] `NewTools`
  - [x] [Pull Request opened](https://github.com/pharo-spec/NewTools/pull/292)
  - [x] merged
- [x] `FuelPlatform`
  - [x] [Pull Request opened](https://github.com/theseion/FuelPlatform/pull/2)
  - [x] merged

## Instance Side

Do we even do this?

## Test

- [ ] Add test to prevent regression

**Comment by gypsydave5** [comment]
Question - on the class side, should it still be under the `initialization` protocol, or should it be `class initialization`?

**Comment by gypsydave5** [comment]
Just noting this down here so I don't forget it:


```smalltalk
methods := (Smalltalk globals allBehaviors 
	flatCollect: [ :class | class methods ])
	select: [ :method | 
		(method methodClass isMeta)
		& (method selector == #reset)
		& (method protocol ~= #initialization)].
	
groups := methods groupedBy: 
[ :method |  [ method package iceRepository name ] on: Error do: [ 'pharo' ] ].

(groups at: 'iceberg') do: [ :method | method protocol: 'initialization' ].
```

**Comment by akevalion** [comment]
I have merged the code for roassal3, I will create a new release for that

**Comment by akevalion** [comment]
My pull request has been merged to pharo10

**Comment by Ducasse** [comment]
Thanks Milton

**Comment by gypsydave5** [comment]
The `FuelPlatform` [PR was merged](https://github.com/theseion/FuelPlatform/pull/2); just `pharo`, `iceberg` and `spec` to go!

**Comment by gypsydave5** [comment]
@MarcusDenker - not sure we should close this one yet!

**Comment by gypsydave5** [comment]
OK! I think all of the necessary changes have been made - I'll check if they've been merged into the P10 image.

@jecisc, you mentioned that you had a test with the rule (https://github.com/pharo-project/pharo/issues/2607#issuecomment-533055737) ready to merge in. Is this still the case?

**Comment by astares** [comment]
@gypsydave5 

Be aware of the restructuring for the rules/release tests that is in the pipe already to fix cases but also bring them into alignment.
Specifically https://github.com/pharo-project/pharo/issues/10170 but also #10174, #10168, #10166 
but also the already merged #10140, #10139, #10126

**Comment by gypsydave5** [comment]
I'm not very familiar with this bit of Pharo. I not very familiar with _most_ of Pharo to be honest. So there's a set of rules that run as a part of the Pharo code review, and we can both apply them as fixes as well as test that they've been adhered to?

It does sound like this would be the right thing to with this rule. I'll try and write it.

---

So, now I've thought about this; it would be a good idea to get this rule in sooner rather than later so that we don't end up with even more methods in the wrong protocol?

**Comment by gypsydave5** [comment]
I've started to write a Renraku rule (thanks for the pointers above @astares), see #10182. I'd really like some feedback and advice!

**Comment by MarcusDenker** [comment]
merged
