### ISSUE TITLE
Path>>printOn: is overriden by all its subclasses and none call "super printOn:"

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2608]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/20718
Status: Work Needed (Conclusion)
Project: File System
Original Author: CyrilFerlicot
Date: 17 November 2017 8:47:03 pm
	
Description:
	
Since this method seems like dead code we can maybe remove it.

**Comment by jecisc** [comment]
Reply:
Author: CyrilFerlicot
Date: 17 November 2017 8:47:55 pm
	
Message:
	
Or maybe we can keep the behaviour but rename it "pathString"?

**Comment by jecisc** [comment]
Still relevant.

**Comment by guillep** [comment]
If the method is not used probably it can be removed.
