### ISSUE TITLE
Metacello attributes should be based on SystemVersion instead of hardcoding

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2616]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/22679
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 16 November 2018 9:35:50 am
	
Description:
	
This will reduce the number of tasks to do for each release.

**Comment by jecisc** [comment]
Reply:
Author: CyrilFerlicot
Date: 16 November 2018 9:43:57 am
	
Message:
	
https://github.com/pharo-project/pharo/pull/1999

**Comment by jecisc** [comment]
Reply:
Author: Esteban Lorenzano
Date: 3 December 2018 8:26:52 am
	
Message:
	
in fact, this breaks next builds so it needs to be reverted.

**Comment by jecisc** [comment]
Reply:
Author: CyrilFerlicot
Date: 7 January 2019 3:36:06 pm
	
Message:
	
For P8

**Comment by jecisc** [comment]
Still relevant.

**Comment by guillep** [comment]
Would be nice to know why this was reverted, and exactly what is expected from this issue, for those people that do not know the details...

**Comment by jecisc** [comment]
It was reverted because after integration a test failed saying that an Undeclared variable was added. 
The weird thing is that the test was not failing during the PR check. We have no idea what caused it.
