### ISSUE TITLE
Instance of RubSmalltalkCodeMode did not understand #textMorph

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2622]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/19953
Status: Work Needed
Project: Rubric
Original Author: CyrilFerlicot
Date: 19 April 2017 12:17:52 pm
	
Description:
	
How to reproduce:

- Type `1+1` and debug it
- Before the return of `1+1` add a line `test := 1.`
- Try to "Do it" with the new line selected
- A popup say that `test` is an unknown variable
- Select `Declare new temporary variable`
- Get a MNU

**Comment by jecisc** [comment]
Reply:
Author: CyrilFerlicot
Date: 19 April 2017 12:18:23 pm
	
Message:
	
Here we get it in a playground with a DoIt method, but it happen also in a normal method.

**Comment by jecisc** [comment]
Still relevant.

**Comment by MarcusDenker** [comment]
This now works and defines a binding in the requesting playground for test.
