### ISSUE TITLE
Auto complete should take into account what is after the cursor

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2625]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/19726
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 19 February 2017 8:52:51 pm
	
Description:
	
Let's say I wrote "MyClassName", but I remember I wanted "MyAbstractClassName". I will use the arrow to move after "My" the type "Abst". The auto complete will propose the class but if I hit enter I will end up with "MyAbstractClassName ClassName".

I think that auto complete should check if it needs to complete everything.

**Comment by jecisc** [comment]
Still relevant.

**Comment by MarcusDenker** [comment]
This now works
