### ISSUE TITLE
Concistency question: pull up/push up

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2628]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/19607
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 26 January 2017 9:42:16 am
	
Description:
	
My English is not perfect so I would like the advice of an experimented English speaker. 

When I do a refactoring the menus propose me to "Pull up" an instance var but to "Push up" a method. For me it seems that it would be more consistent to have the "push up" term for both cases because we use "push up" everywhere except for attributes. Someone good in English to give his advice?

**Comment by jecisc** [comment]
Reply:
Author: Marcus Denker
Date: 9 November 2017 4:41:46 pm
	
Message:
	
Discussion is here:

http://forum.world.st/about-push-up-and-pull-up-td4939950.html

**Comment by akgrant43** [comment]
Hi Cyril,

John's description is the way I view 'push' and 'pull':

>Essentially, the push vs. pull naming was based on where you were in the browser. If the thing to move wasn’t where you were in the browser, then pull was used — you would reach over to the other place and pull it to you. However, if the thing was currently where you were in the browser, then you would push it to the new location. 

But it adds cognitive load to be sure what is going on - I have to think about where I am and if it matches that perspective.

Stef's suggestion of "Move Up" & "Move Down" is better as it isn't relative to "my" position.

HTH,
Alistair
