### ISSUE TITLE
If we select some code then push Tab we could add a tab at the beginning of all selected lines

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2629]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/19652
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 4 February 2017 10:12:38 am
	
Description:
	
Most IDE have the function.

Sometimes we want to format the code as we like and we select some lines of code to add a tab at the beginning of each lines.

Would be great of Pharo could have this kind of feature. It annoyed a friend that have the habits of Java's IDE.

**Comment by jecisc** [comment]
Reply:
Author: Pavel Krivanek
Date: 4 February 2017 6:50:33 pm
	
Message:
	
We have Ctrl+Shift+r. Are you missing the function or the fact that it is not assigned with Tab?

**Comment by jecisc** [comment]
Reply:
Author: CyrilFerlicot
Date: 4 February 2017 7:22:51 pm
	
Message:
	
I did not knew we could do it with this shortcut. Most IDE use TAB, I think we should do the same.

Just for the context:
I was "teaching" Pharo to friends for an university project with free techno and this is something that annoyed them as Pharo beginners. This is the reason I think we should add this feature when we select multiple lines then tab. People using Pharo tend to live with hardly discoverable features but it repel some new peoples.

**Comment by MarcusDenker** [comment]
From the duplicate issue #2896 

One should be able to select a block of code /testand use Tab to shift all of it to the right (or to the left - Shift+Tab). That's how most editors do it.

See https://twitter.com/i/status/1106179169472471040

Also look at discussion here: http://forum.world.st/Text-Indentation-in-Pharo-editor-td5059993.html
