### ISSUE TITLE
Newcommers Cheats Sheet in welcome window

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2631]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/19522
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 6 January 2017 3:22:59 pm
	
Description:
	
Phillipe Back has a cool package serving as a Cheat Sheet. You can load it this way:

Gofer new 
    url: 'http://smalltalkhub.com/mc/philippeback/HOExtras/main';
    package: 'HOCheatSheet';
    load.

#HOCheatSheet asClass browse

It would be really cool to have this kind of cheat sheet in a Pharo repository and to get the instructions to load it in the help window.

**Comment by jecisc** [comment]
Reply:
Author: Pavel Krivanek
Date: 27 January 2017 10:06:15 am
	
Message:
	
Increasing priority. Needs resolution.

**Comment by jecisc** [comment]
Reply:
Author: Pavel Krivanek
Date: 3 March 2017 10:13:31 am
	
Message:
	
We will not add it into the base image, at least not in Pharo 6. The package need to be updated.

**Comment by jecisc** [comment]
Reply:
Author: CyrilFerlicot
Date: 3 March 2017 10:27:35 am
	
Message:
	
If we do not integrate this package into the image we can at least add a button in the welcome window to load it.

I reopen since this is important to help newcommers. More in Pharo since this is so much different than other languages. 

Of course, this Cheat Sheet need revisions.

**Comment by Ducasse** [comment]
I will check to integrate this package with ProfStef
