### ISSUE TITLE
File>>readStream should raise FileDoesNotExistException if the file does not exist.

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2633]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/19025
Status: Work Needed
Project: File System
Original Author: CyrilFerlicot
Date: 2 September 2016 10:31:53 am
	
Description:
	
If you try to read a File that does not exist you get a FileException, but there is a subclass of this exception named "FileDoesNotExistException", it should be used instead.

**Comment by jecisc** [comment]
Reply:
Author: Pavel Krivanek
Date: 21 September 2016 11:13:07 am
	
Message:
	
If the fileHandle is nil, we do not know if the file does not exists or if it has read-only permissions. That is probably the reason why general FileException is signaled here.

**Comment by jecisc** [comment]
Reply:
Author: Pavel Krivanek
Date: 27 January 2017 11:46:24 am
	
Message:
	
Low priority issue. Not for Pharo 6. The milestone "Later" was set automatically.

**Comment by akgrant43** [comment]
Hi Cyril,

Can you confirm that this is already resolved in Pharo 8.0 (by the FileAttributes changes)?

Thanks,
Alistair

**Comment by jecisc** [comment]
Yes! Thank you ;)
