### ISSUE TITLE
Code's drag n drop

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2634]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/19229
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 20 October 2016 6:29:28 pm
	
Description:
	
In most editors it is possible to select some text then drag and drop it at another location by holing the click and moving. It could be cool to be able to do it in Pharo too.

**Comment by jecisc** [comment]
Reply:
Author: Pavel Krivanek
Date: 27 January 2017 1:15:07 pm
	
Message:
	
Low priority issue. Not for Pharo 6. The milestone "Later" was set automatically.

**Comment by liangbing64** [comment]
Hi, please have a look  this https://github.com/liangbing64/Text-DragansDrop

**Comment by jecisc** [comment]
Valid

**Comment by guillep** [comment]
This is a pretty big "issue", not easily actionable, more like a big feature project.
But if nobody actively works on it, it would be nicer to move it maybe to a wiki page with project ideas.
