### ISSUE TITLE
LazyListMorph does not update well on #themeChanged

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2638]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/18353
Status: Work Needed
Project: Morphic
Original Author: CyrilFerlicot
Date: 28 May 2016 11:34:35 pm
	
Description:
	
To see it just open the setting browser on the "appearance", change the theme and open the list of themes.

**Comment by jecisc** [comment]
Reply:
Author: CyrilFerlicot
Date: 28 May 2016 11:37:53 pm
	
Message:
	
It seems to work well if the list is opened but not if we open it after the change of theme.

**Comment by jecisc** [comment]
Reply:
Author: Pavel Krivanek
Date: 27 January 2017 12:16:37 pm
	
Message:
	
Low priority issue. Not for Pharo 6. The milestone "Later" was set automatically.

**Comment by jecisc** [comment]
Still relevant.

**Comment by guillep** [comment]
Shouldn't be better to replace `LazyListMorph` usages by `FTTableMorph`? `LazyListMorph` should be deprecated...

I'll close this, please reopen if really really necessary.
