### ISSUE TITLE
Add a "Pharo script" and a "Pharo X script" setting

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2644]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/18236
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 15 May 2016 6:18:58 pm
	
Description:
	
We can create a file .st into the preferences's directory. This file will be executed at startup. We can do the same with a specific version of Pharo with a folder named `X.0` where X is the version of pharo.

A new user will not know that. In order to make Pharo more User Friendly we should have a text field into the setting browser where the user will be able to create a script to launch at startup for every versions of Pharo or for a specific version of Pharo.

**Comment by jecisc** [comment]
Reply:
Author: Pavel Krivanek
Date: 27 January 2017 1:19:24 pm
	
Message:
	
Low priority issue. Not for Pharo 6. The milestone "Later" was set automatically.

**Comment by akgrant43** [comment]
+1

If a script is already present it should automatically populate the fields so that the user can see what is affecting the image on startup.

**Comment by jecisc** [comment]
Still valid

**Comment by guillep** [comment]
This already exists. These are called startup actions.

![image](https://user-images.githubusercontent.com/708322/77923167-57b57680-72a2-11ea-8745-69c629a5ab7a.png)

There are general scripts (for all versions).
And specific per version.
You can create a new one or edit old ones from the image itself.
They are stored in the user's preferences directory.

Maybe this just deserves better documentation?
