### ISSUE TITLE
Saving a trait method into the debugger doesn't propose to compil as a trait

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2648]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/17414
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 18 January 2016 10:36:47 am
	
Description:
	
When we save a method of a trait in a class that use this trait, we get a window which ask if we want to save the method in the class or in the trait. We don't get this proposition in the debugger. We only have the possibility to save the method in the class.

**Comment by jecisc** [comment]
Reply:
Author: CyrilFerlicot
Date: 21 March 2016 4:31:09 pm
	
Message:
	
Not urgent

**Comment by jecisc** [comment]
Reply:
Author: Pavel Krivanek
Date: 27 January 2017 10:15:07 am
	
Message:
	
Low priority issue. Not for Pharo 6. The milestone "Later" was set automatically.

**Comment by jecisc** [comment]
Still relevent.

**Comment by StevenCostiou** [comment]
This now works in Pharo 9
