### ISSUE TITLE
Refactor rename gives superfluous/misleading "Warning this will rename X other implementors Y/N" dialog

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2664]
When you rename a method and it has other implementors, the UI gives a dialog prompt "Warning/Want to Proceed: This will modify all X implementors Y/N"

While the warning is correct, it looks like its going to immediately do this which isn't true as you then get another refactoring window that shows you all the implementors and lets you pick or cancel.

Ideally this warning would be simply included in that second window with a yellow ! mark.

At the very least, this shouldn't be a Y/N - it should be just an OK and then you can cancel on the next screen (admittedly not ideal - but the way it is now is confusing).

**Comment by dupriezt** [comment]
Since there is another window in which you can visualise the changes and decide which methods are actually renamed, is the warning window actually useful?
Couldn't we just remove this warning window and display the detailed change window as usual?

**Comment by macta** [comment]
I thought about that - but did think that something that warns you was handy - if you are in automatic, and maybe there were 2 implemenations vs 1, its easy to miss the refactor dialog having 2 vs. 4 lines in it.

I think it would be good if the refactor dialog has a status line that could be yellow to show these messages.

This said - maybe just removing it is fine - It annoys me having all the extra questions.
