### ISSUE TITLE
Moving a class up in the hierarchy doesn't diff properly

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2665]
If you have a class hierarchy like A->B->C
and you move C up to be a subclass of A, the iceberg commit diff shows C as if its a brand new class and shows all its instance and class methods as being new additions - when really the only change is the superclass.

this makes it confusing to understand the diff - it should just show the single change on the class (which it does) and not all of the methods as well (unless they have actually changed)

**Comment by tesonep** [comment]
Moved to Iceberg https://github.com/pharo-vcs/iceberg/issues/1198
Thanks for reporting!
