### ISSUE TITLE
SystemNavigation>>confirmRemovalOfSelectors:on: duplicates ClyBrowserMorph>>requestRemoveMethodStrategyFor: is it Used?

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2672]
There is a strong similarity between SystemNavigation>>confirmRemovalOfSelectors: aCollection on: aClass and ClyBrowserMorph>>requestRemoveMethodStrategyFor: 

So not sure if the former needs to go away as Calypso replaces it (no senders?).  There are possibly many others like this too.

**Comment by MarcusDenker** [comment]
#confirmRemovalOfSelectors: was dead code, I removed it already

**Comment by macta** [comment]
You are awesome - I am hoping to find a some free space in the day job to try and follow your lead on some fixes too... but thanks!
