### ISSUE TITLE
Fix RxmBranch to do greedy matching instead of first match passes

### ISSUE THREAD

**Issue by marianopeck** [guillep/pharo-core#2679]
The background of the discussion is here: http://forum.world.st/Bug-in-Regex-td5095783.html

I went into the VW public store and I found this commit on Regex:

> Regex11  (1.3.1-soops1)  Development
> --- Blessed: Development
> --- By: reinz
> --- On May 11, 2011 10:37:43 AM
> Fixed RxmBranch to do greedy matching instead of first match passes.
> This entailed adding a collection copy to #currentState, so I expect this to slow down Regex11 a bit (not measured yet).
> This fixes a bug found a Soops:
>     '.*(ABCD|BC)' asRegex matches: 'fooABCD'
> and Mantis bug 5391:
>     '15' matchesRegex: '[1-9]|1[0-9]'
> 

As you can see, that was patched in VW Regex 1.3.1. Pharo's Regex I think it's a port of VW 1.1.

I then did a diff of that 1.3.1 version with it's parent and I spotted the 2 changes made. I applied those changes into our latest Regex and they seem to work:

	RxMatcher >> currentState
		"Answer an opaque object that can later be used to restore the
		matcher's state (for backtracking)."

		| origPosition origMarkerPositions |

		origPosition := stream position.
		origMarkerPositions := markerPositions collect: [:collection | collection copy].
		^[
			stream position: origPosition.
			markerPositions := origMarkerPositions]
			
			
	RxmBranch >> matchAgainst: aMatcher
		"Match the longest match of `next' or `alternative'. Fail the alternative if the alternative is nil."

		| original firstMatch firstMatchPos |

		original := aMatcher currentState.
		(next matchAgainst: aMatcher)
			ifFalse: [^alternative notNil and: [alternative matchAgainst: aMatcher]].
		alternative ifNil: [^true].
		firstMatch := aMatcher currentState.
		firstMatchPos := aMatcher position.
		aMatcher restoreState: original.
		(alternative matchAgainst: aMatcher)
			ifFalse: [
				aMatcher restoreState: firstMatch.
				^true].
		firstMatchPos >= aMatcher position
			ifTrue: [
				aMatcher restoreState: firstMatch.
				^true].
		^true			
		
		
After that, I wrote a new test:

	RxMatcherTest >> testStringGreedyMatchesRegex

		self assert: ('199' matchesRegex: '([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])').
		self assert: ('25' matchesRegex: '([0-9]|[1-9][0-9])').
		self assert: ('25' matchesRegex: '([1-9][0-9]|[0-9])').
		self assert: ('25' matchesRegex: '(\d\d|\d)').
		self assert: ('25' matchesRegex: '(\d|\d\d)').
		self assert: ('bb' matchesRegex: '([a-z]|[b-z][a-z])').
		self assert: ('b' matchesRegex: '([b-z][a-z]|[a-z])').
		self assert: ('15' matchesRegex: '[1-9]|1[0-9]').
		self assert: ('b' matchesRegex: '(b|bb)').
		self assert: ('b' matchesRegex: '(bb|b)').
		self assert: ('fooABCD' matchesRegex: '.*(ABCD|BC)').
		self assert: ('fooBC' matchesRegex: '.*(ABCD|BC)').
		self assert: ('fooB' matchesRegex: '.*(ABC|B)').
		self assert: ('fooABC' matchesRegex: '.*(ABC|B)').	

What do you think? Any other assert we can add into the test?

**Comment by theseion** [comment]
Looks good to me. I went back and looked for other work arounds I may have used but didn't find any. 

Side note: It would be great to have non-capturing groups (`(:?match)`) for boosting performance and making capture group enumeration simpler.
Side note2: Bindings to PCRE would be super cool! :)

**Comment by theseion** [comment]
Still relevant. Should open a PR with the fixes.
