### ISSUE TITLE
Debugger StepInto does not go into accessors or methods with primitives 

### ISSUE THREAD

**Issue by StevenCostiou** [guillep/pharo-core#2681]
When stepping into an accessor or a method with a primitive, the debugger just step over with no explanation. If not stepping into a primitive or a simple accessor is understandable, it should at least warn the user somehow that a value was returned or a primitive was executed.

**Comment by StephanEggermont** [comment]
It should still go into there. Otherwise debugger driven development is made impossible. 
https://vimeo.com/329317634 (at 6 min 55)

<blockquote><img src="https://i.vimeocdn.com/filter/overlay?src0=https%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F774106527_1280x800.jpg&src1=https%3A%2F%2Ff.vimeocdn.com%2Fimages_v6%2Fshare%2Fplay_icon_overlay.png" width="48" align="right"><div>Vimeo</div><div><strong><a href="https://vimeo.com/329317634">Debugger Driven Development in Pharo (Part 1)</a></strong></div><div>Debugger Driven Development is a form of Test Driven Development that can be done in Smalltalk systems like Pharo. It offers a superior feedback cycle</div></blockquote>

**Comment by MarcusDenker** [comment]
Very important, I removed the stale tag

**Comment by StevenCostiou** [comment]
I finally have the opportunity to look at that.

After analyzing a bit, it requires to touch sensible code and also it would disrupt a bit how users are accustomed to work with the debugger.

I propose:
- a setting that steps accessors and primitives, activated by default
- if you want the old way without stepping these parts of the code, just deactivate the settings
What do you think?

**Comment by StephanEggermont** [comment]
In what situation would I be interested in the behavior where I can not step into primitives and accessors?

**Comment by StevenCostiou** [comment]
I do not see any. I myself am bothered by that.
I could skip the settings part and make this the default behavior (less work!).

If someone asks it back, the settings would be the way to go with, by default, the stepping into those statements.

**Comment by maxwills** [comment]
Don't know if I understood that correctly. I don't think the setting would be helpful. If it does what I think, that setting would make a "step into" behave like a "step over", but only in those particular cases. That seems a little odd to me.

**Comment by StephanEggermont** [comment]
Indeed. If you feel you need it because of the sensitivity (dangerous?) that would be different, but otherwise I like the illusion of objects all the way.

**Comment by StevenCostiou** [comment]
No it is not the sensitivity, the change with or without the settings may have an impact.
I was thinking about the way users were used to see, but I agree with you.

I will just make this default and people will have to adapt, afterall, nobody is participating to this thread to argue against so...

Just to summarize, affected behavior are:
- when stepping in a method that contains a simple return of a value or instance variable
- when stepping in a method containing a primitive

Stepping in an accessor works for me in latest P9.

Any other cases you can think of?

**Comment by StevenCostiou** [comment]
@StephanEggermont looking again at your video, could you confirm that your use case is that you would like to step into the method accessor to change its code?

After investigation, this is actually something coded in the VM and not in the image. There are implications and we would need a larger discussion to change that point.

From the image I can:
- notify you in the debugger that you stepped into an accessor and show you the code, but I understand that is not what you want
- provide you with a step that does some instrumentation to transform the compiled method (but not its source code) in a way that you can step into it

In that latter case, I would have not much choice than either provide you with a specific step button, or with a setting that does that special stepping instead of the normal one. In that case the settings will be necessary because you need to know that accessors will be stepped in in a very special hidden way.

**Comment by StephanEggermont** [comment]
Yes, I definitely need to change accessors

**Comment by StevenCostiou** [comment]
Ok I have a clean fix (I think)

**Comment by StephanEggermont** [comment]
Something I should test?

**Comment by StevenCostiou** [comment]
Yes please you can take the artefact of https://github.com/pharo-project/pharo/pull/8456 once the build is complete.
And review it if you find time ;)

**Comment by StephanEggermont** [comment]
Ok. Where do I find the artefact?

**Comment by StevenCostiou** [comment]
Here https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-8456/1/pipeline when the build is over, you have an *Artefact* item on the top menu bar.

Be cautious, my solution is actually incomplete it does not handle the `^self` quick methods. I have to complete that.

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-8456/1/pipeline">Jenkins</a></strong></div></blockquote>

**Comment by StephanEggermont** [comment]
Hmm, the last step seems to break?
