### ISSUE TITLE
Some tests for FileReferences use a <publicTest> pragma

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#2685]
It seems it is not used anywhere else in the system. Maybe it can be removed.

**Comment by MarcusDenker** [comment]
What needs to be done: delete all the lines <publicTest>. 

You can find them by browsing "senders of" publicTest

**Comment by akevalion** [comment]
I have removed the publicTest check PR https://github.com/pharo-project/pharo/pull/3094

**Comment by MarcusDenker** [comment]
merged PR
