### ISSUE TITLE
Remove GLMExamplesBrowser and GLMExamples

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#2688]
Because Glamour will be removed from the system so it is not needed anymore.

**Comment by Ducasse** [comment]
I guess that you mean GLMExamplesBrowser

**Comment by juliendelplanque** [comment]
Yes, I edited the title.

**Comment by Ducasse** [comment]
I thought that it was already removed. I wonder why we still have GLMExamplesBrowser in the latest image.

**Comment by Ducasse** [comment]
Indeed it was done here https://github.com/pharo-project/pharo/pull/2702

**Comment by Ducasse** [comment]
But it is still in the system. Super strange.

**Comment by Ducasse** [comment]
Ok I was browsing a pharo 70 image :(
so the issue can be closed
