### ISSUE TITLE
Median is not calculated correctly for even sizes (22595)

### ISSUE THREAD

**Issue by ghost** [guillep/pharo-core#2691]
Original case: https://pharo.fogbugz.com/f/cases/22595

SortedCollection median does not work correctly for even amount of elements.
Median, by definition (see links below for possible definitions and explanations of median), returns middle element of sorted numbers in case of odd-sized collections.
In even-sized collections, there is no precisely middle element (in 4-sized collection the 2nd and 3rd are kinda both in the middle), therefore median is defined as average of these two "middle" elements (in case of 4-sized collection, it is average of 2nd and 3rd element).
However, current implementation of SortedCollection>>#median just returns element before the "middle", so (in case of 4-sized collection), it returns 2nd element, although it should return average of 2nd and 3rd.

I understand that median can be sent even to collections of strings, classes or whatever that cannot be averaged, but this way it does not comply to definition of median and therefore should not be called that.

https://www.dictionary.com/browse/median
https://searchdatacenter.techtarget.com/definition/statistical-mean-median-mode-and-range
https://en.wikipedia.org/wiki/Median

Jan

**Comment by ghost** [comment]
I have created pull request for this issue https://github.com/pharo-project/pharo/pull/2690

**Comment by Ducasse** [comment]
I will published a PR with the changes I suggested.

**Comment by MarcusDenker** [comment]
Ups, I merged the PR already. I will close the issue...

If there is still something to be done => please reopen and comment
