### ISSUE TITLE
Can't clear breakpoint in the debugger

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2694]
If you set a soft breakpoint in some code, and then later get the debugger - there is no way to easily clear that breakpoint in the debugger. This is particularly annoying if the breakpoint is in some system code like the compiler.

(Pharo 7.0 stable, OSX)

**Comment by dupriezt** [comment]
By "soft breakpoint", you mean for example clicking in the margin?

**Comment by macta** [comment]
yes - or meta-t, add breakpoint 
(so not saving self halt in the code)

**Comment by MarcusDenker** [comment]
still a problem

**Comment by guillep** [comment]
There is a duplicate entry in #5211. I'll close this one as the other one has a richer discussion.
Please let's continue the discussion there.
