### ISSUE TITLE
Clean Editor method 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2716]
Editor is FULL of message sends but not implemented. We can add at least 10 subclassResponsibility. 
Now I have the impression that merging Editor into TextEditor is a smarter move. At least it will minic Rubric editor hierarchy and we should remove TextEditor.

**Comment by Ducasse** [comment]
Now if Editor should be removed. let us remove it.

**Comment by hilaire** [comment]
What are the differences between the packages Rubric and Text-Edition?

**Comment by hilaire** [comment]
There is indeed no instance nor instantiation of Editor. Therefore Editor can be merged into TextEditor. Are there any deprecation mechanism to integrate when removing a class?

**Comment by Ducasse** [comment]
Hi hilaire for class removal we package the class in a deprecated package and make it a subclass of the renamed class.

**Comment by hilaire** [comment]
Done

**Comment by Ducasse** [comment]
This is cool that you did it. I will have a look when I can read a screen. I have the impression that it gets me violent headhaches.
