### ISSUE TITLE
Should deprecate Editor, TextEditor and SmalltalkTextEditor

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2717]
Editor is referenced in 
- Editor >> editingSettingsOn:  do we add this to RubTextEditor?
- Paragraph >> caretWidth (refer to editor) and Paragraph should be replaced by RubParagraph
- TextMorph >> manageCursor refer to Editor blinkingCursor (but there is nobody else).
- WorldMorph >> dispatchKeyStroke: refer to Editor sending message cmdKeysInText 

We should check the settings and see how they are covered in RubTextEditor

**Comment by Ducasse** [comment]
- We should handle the references to TextEditor (11). 
- In particular the installation of mapping

**Comment by StephanEggermont** [comment]
Blocked by Issue #2904

**Comment by Ducasse** [comment]
Running after this robot is killing my fun.

**Comment by guillep** [comment]
There are still users of Paragraph and TextEditor. Editor and SmalltalkEditor have been removed in P11.

**Comment by guillep** [comment]
Paragraph is already in https://github.com/pharo-project/pharo/issues/2851

**Comment by MarcusDenker** [comment]
Editor, TextEditor and SmalltalkTextEditor are removed
