### ISSUE TITLE
PrimitiveFailed: primitive #fileDescriptorType: in File class failed, when opening stdout for writing

### ISSUE THREAD

**Issue by rydnr** [guillep/pharo-core#2720]
When I open a stock Pharo7+ image, I get this error. It didn't happen in Pharo6.1.

In particular, using Pharo7.0.1 build 142, commit b882595, I get

```PrimitiveFailed: primitive #fileDescriptorType: in File class failed```.

The stack trace is:

- ```File class> fileDescriptorType: 1```
- ```File class> fileDescriptorIsAvailable: 1```
- ```Stdio class > standardIOStreamNamed: #stdout forWrite: true```

I checked my OS user can write to the `stdout` file of the `pharo` process:

```
> ps -ef | grep pharo | grep -v grep | awk '{print $2}'
3920
> ls -lrtlhia /proc/3920/fd
total 0
242460 dr-xr-xr-x 9 myuser users  0 Feb 25 07:53 ..
264939 dr-x------ 2 myuser users  0 Feb 25 07:59 .
263030 lr-x------ 1 myuser users 64 Feb 25 07:59 9 -> /home/myuser/pharo-test/Pharo7.0.1-0-64bit-b882595.changes
263029 lr-x------ 1 myuser users 64 Feb 25 07:59 8 -> /home/myuser/pharo-test/Pharo7.0-32bit-b882595.sources
263028 lrwx------ 1 myuser users 64 Feb 25 07:59 6 -> /home/myuser/pharo-test/Pharo7.0.1-0-64bit-b882595.changes
263027 lr-x------ 1 myuser users 64 Feb 25 07:59 5 -> /home/myuser/pharo-test/Pharo7.0-32bit-b882595.sources
263026 lr-x------ 1 myuser users 64 Feb 25 07:59 4 -> /home/myuser/pharo-test/Pharo7.0.1-0-64bit-b882595.image
263025 lrwx------ 1 myuser users 64 Feb 25 07:59 3 -> 'socket:[242462]'
263024 lrwx------ 1 myuser users 64 Feb 25 07:59 2 -> /dev/pts/1
263023 lrwx------ 1 myuser users 64 Feb 25 07:59 1 -> /dev/pts/1
263022 lrwx------ 1 myuser users 64 Feb 25 07:59 0 -> /dev/pts/1
> ls -lrhlia /dev/pts/1
4 crw--w---- 1 myuser tty 136, 1 Feb 25 07:53 /dev/pts/1
> echo 'testing' >> /dev/pts/1
> # testing appears in the terminal of the pharo process
```

Even if I change the permissions of `/dev/pts/1` (`chmod a+w /dev/pts/1`), I get the same `primitive failed` issue.

I'm compiling the VM myself. I've checked the primitive is bound to `FilePlugin`, which is declared in `plugins.int`. If I move it to `plugins.ext`, the build fails.

**Comment by akgrant43** [comment]
Hi Jose,


On Mon, 25 Feb 2019 at 08:02, Jose San Leandro <notifications@github.com>
wrote:

> When I open a stock Pharo7+ image, I get this error. It didn't happen in
> Pharo6.1.
>
> In particular, using Pharo7.0.1 build 142, commit b882595
> <https://github.com/pharo-project/pharo/commit/b8825954d0dcff883bf4f47ea5c516c9cfc2fe4b>,
> I get
>
> PrimitiveFailed: primitive #fileDescriptorType: in File class failed.
>

This looks like you're trying to use the Pharo 6 VM with a Pharo 7 image.

Can you check the date on your VM, it should be:

$ ./pharo --version | grep CommitHash
Date: Sat Jan 5 20:00:11 2019 CommitHash: 7a3c6b64

(a later date would be OK).

HTH,
Alistair

**Comment by rydnr** [comment]
Hi @akgrant43,

This is the output I get from `pharo --version`:

```
5.0-git.6a63f68a3dd4deb7c17dd2c7ac6e4dd4b0b6d937  Sun Feb 24 20:22:08 UTC 2019 gcc 5.5.0 [Production Spur 64-bit VM]
CoInterpreter VMMaker.oscog-eem.2231 uuid: de62947a-7f40-4977-a232-e06a3a80c939 Jan  1 1970
StackToRegisterMappingCogit VMMaker.oscog-eem.2227 uuid: 7ea146b4-39ce-4de7-afa3-a76ed1d1da35 Jan  1 1970
VM: git.6a63f68a3dd4deb7c17dd2c7ac6e4dd4b0b6d937 https://github.com/opensmalltalk/opensmalltalk-vm $ Date: Mon Jan 21 11:39:00 2019 +0100 $
Plugins:  $Rev$
Linux localhost 4.14.102 #1-NixOS SMP Wed Feb 20 09:20:56 UTC 2019 x86_64 GNU/Linux
plugin path: /nix/store/r625prvsc5jn9i4x398ilmh03ln5qlwl-pharo-spur64/ [default: /nix/store/r625prvsc5jn9i4x398ilmh03ln5qlwl-pharo-spur64/]
```

I build my own VM, and it's been very tricky to make it work (I get a blank desktop depending on the version of gcc and certain dependencies). Any particular VM commit I should try out?

**Comment by Ducasse** [comment]
Did you try 
http://files.pharo.org/get-files/70/
or curl get.pharo.org/vm70 | bash?

Why do you need to recompile the vm yourself?
And yes it can be painful.

**Comment by rydnr** [comment]
I'm using NixOS. It means I don't have `/usr` folder, so the VM won't be able to find any dependency.
Also, NixOS encourages to build everything from source, with non-moving versions, so the artifacts are reproducible.

**Comment by akgrant43** [comment]
Hi Jose,

It looks like you're not running

```
scripts/updateSCCSVersions
```

before building the VM (which is probably why some of the version dates are 1970 and you still have a reference to the $Rev$ macro).  I'd suggest running the current stable version, which is commit hash 7a3c6b64, but it shouldn't really make any difference.

For the blank desktop, Luke Gorrie reported similar symptoms on NixOS late last year.  It might be worthwhile trying to contact him in Discord or the mailing lists (he seems to be more active on discord recently).

For the primitive failure, can you use the debugger to look at the value of 'error' in File class>>fileDescriptorType: ?  Your VM seems new enough.

**Comment by rydnr** [comment]
Hi @akgrant43,

Thanks, I'll call `scripts/updateSCCSVersions` script as you suggest, when building the VM.

Regarding @lukego, I've contacted him already and he's saved me lots of time.

Sorry for not providing the `error` information before. It's `#'not found'`.

**Comment by akgrant43** [comment]
> Hi @akgrant43,
> 
> Thanks, I'll call `scripts/updateSCCSVersions` script as you suggest, when building the VM.

I should have said that this only needs to be called once after git clone.  It sets up some git hooks which then take care of updating the version information.

Around 5 Jan 2019 the existing mvm scripts were updated to call scripts/checkSCCSversion which prints out a message if the version information hasn't been updated (not sure if NixOS will pick this up).


> Regarding @lukego, I've contacted him already and he's saved me lots of time.

After I sent the last message I had a vague recollection of seeing something similar (getting the blank desktop) on linux.  From (my dubious) memory, there was an error during the build but the build didn't exit.  Going back through the build log and fixing the error resolved the issue.

> Sorry for not providing the `error` information before. It's `#'not found'`.

That's saying that it can't find the primitive.  It calls primitiveFileDescriptorType(), which is defined in src/plugins/FilePlugin/FilePlugin.c.  This was introduced in May 2018, so it should be there.
