### ISSUE TITLE
Bug in recompiling slots

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2729]
Hi pablo 

if you take the latest version :
/Users/ducasse/Documents/Pharo/images/P8ToTest2728/P8ToTest2728.image
Pharo8.0.0
Build information: Pharo-8.0.0+build.107.sha.f902bfda763ab51b7a3e730fe53ba46dfa116e3b (64 Bit)
Unnamed

and load the fixes in MY pharo repo ([85ab7fe] 85ab7fec36f56d865d8a5c534ad0f1c2e8ec4b38)

Once you load you cannot open anymore a Playground. 

Now recompiling manually the definition of the class 

RubTextFieldMorph subclass: #GLMRubTextFieldMorph
	instanceVariableNames: 'customHeight '
	classVariableNames: ''
	package: 'Glamour-Morphic-Brick-Morphic'

recompute correctly the offset and Playground can be open without problem
So we have a producible case of miss recomputation of slots/instance variables. 

Stef

**Comment by MarcusDenker** [comment]
Need to check if this is still an issue

**Comment by estebanlm** [comment]
not valid anymore
