### ISSUE TITLE
Symbol equality method #= - weird condition in the Pharo sourcecode

### ISSUE THREAD

**Issue by petr-fischer** [guillep/pharo-core#2744]
Hello, this is Symbol equality method in Pharo:

```
1: = aSymbol
2:      "Compare the receiver and aSymbol."
3:      self == aSymbol ifTrue: [^ true].
4:      self class == aSymbol class ifTrue: [^ false].
5:      "Use String comparison otherwise"
6:      ^ super = aSymbol
```

Look at line 4 - what does it mean? That's wrong, isn't it?

Typically, every symbol comparisons end up in line 3, but if you do some work with forward proxies for example, condition on line 3 is "false" and then weird things on line 4 happens.

If line 4 and further are correct, can someone explain a little?

http://lists.pharo.org/pipermail/pharo-users_lists.pharo.org/2019-March/042704.html

**Comment by ofi** [comment]
Just citing the updated "Pharo By Example" book, section "Identity and Equality" (p. 183 as of 2018-09-29):

> Note that Pharo has some strange equality behaviour compared to other Smalltalks. For example a symbol and a string can be equal. (We consider this to be a bug, not a feature.)

So it seems like a long-term Pharo-pro with holistic oversight has to attend to this, because getting rid of the "strange equality behaviour" might break things depending on it.

**Comment by petr-fischer** [comment]
There is a little discussion on the pharo mailling list - I still "feel" that this implementation of equality is not entirely appropriate and could be more universal (or "open"). My specific point is problem with equality of forward proxy pointing to the symbol with symbol itself - from this point of view, actual implementation of Symbol>>= looks like a hack :), but someone can document/comment this method (point from mailing list discussion) and close this issue. Fortunately, I can hack implementation of Symbol>>= as an extension of my package.

**Comment by akgrant43** [comment]
> Look at line 4 - what does it mean? That's wrong, isn't it?

It's an optimisation.  If aSymbol (maybe a poor choice of name) is actually a symbol and line 3 determined that they are different, then there is no need to execute line 6, which may be computationally (relatively) expensive.

**Comment by svenvc** [comment]
I don't consider the equality of Strings and Symbols to be a bug, for me this is a feature.

Also, (1) what is your exact problem with the proxy ? I would say that there is little point in proxying a symbol, as it is a small, readonly value object, a bit like a number - you would not proxy that either, would you (2) what is your 'more open' alternative ?

**Comment by Ducasse** [comment]
Can one of you write a super nice method comment?

**Comment by petr-fischer** [comment]
@svenvc You are right - I just switched off proxying for Booleans, Symbols, SmallIntegers and Characters in my system right now and yes, it's better :)

**Comment by MarcusDenker** [comment]
I personally would like to see Pharo to be be able to proxy any object. We should fix all places that make proxies harder to do.

**Comment by MarcusDenker** [comment]
We should check how common that case is... A quick check saw quite a lot if executions of that branch... so maybe the optimisation really is needed...
