### ISSUE TITLE
Stdout error creation at startup

### ISSUE THREAD

**Issue by hilaire** [guillep/pharo-core#2745]
With DrGeo 19.03a[1] bundle built with 32bits stable P7 image and VM for OS X, I have the following error at the image start up sequence:

> error with stdout does not exist, force recursive file creation, filename "stdout"

The debugger stack:
[Mac-stdout.txt](https://github.com/pharo-project/pharo/files/2922906/Mac-stdout.txt)

The error occurs identically with drgeo started from CLI or GUI. It is a REPEATABLE error.

[1] https://launchpad.net/drgeo/trunk/19.03/+download/DrGeo-mac-19.03a.zip

**Comment by akgrant43** [comment]
Hi Hilaire,

Can you provide the text from System -> System Reporter -> VM General

Thanks,
Alistair

**Comment by hilaire** [comment]
Here it is:

Virtual Machine
---------------
/Applications/DrGeo.app/Contents/MacOS/Pharo
CoInterpreter VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan  5 2019
StackToRegisterMappingCogit VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan  5 2019
VM: 201901051900 https://github.com/OpenSmalltalk/opensmalltalk-vm.git Date: Sat Jan 5 20:00:11 2019 CommitHash: 7a3c6b6 Plugins: 201901051900 https://github.com/OpenSmalltalk/opensmalltalk-vm.git

Mac OS X built on Jan  5 2019 19:10:57 UTC Compiler: 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)
VMMaker versionString VM: 201901051900 https://github.com/OpenSmalltalk/opensmalltalk-vm.git Date: Sat Jan 5 20:00:11 2019 CommitHash: 7a3c6b6 Plugins: 201901051900 https://github.com/OpenSmalltalk/opensmalltalk-vm.git
CoInterpreter VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan  5 2019
StackToRegisterMappingCogit VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan  5 2019

Dr. Geo -- http://drgeo.eu

----- akgrant43 <notifications@github.com> a écrit :

**Comment by akgrant43** [comment]
Hi Hilaire,

You're using an alpha image from 6 months before Pharo 7 was released and the stdio handling changed during that time - so your VM and image aren't compatible.

The VM is the Pharo 7 stable VM.  You really need to update to the released image.

Cheers,
Alistair

**Comment by hilaire** [comment]
Oh, WTF, I am indeed accidently using the wrong image. I remember I
installed the stable one to build the bundles, but I mix up in the files.

I will make a new bundle and see how it goes.

Thanks

Le 04/03/2019 à 08:04, akgrant43 a écrit :
>
> Hi Hilaire,
>
> You're using an alpha image from 6 months before Pharo 7 was released
> and the stdio handling changed during that time - so your VM and image
> aren't compatible.
>
> The VM is the Pharo 7 stable VM. You really need to update to the
> released image.
>
> Cheers,
> Alistair
>
-- 
GNU Dr. Geo
http://drgeo.eu

**Comment by hilaire** [comment]
Ah, I just rediscover why I was still using this alpha P7 image. The
stable P7 image miserably failed when I build the drgeo image.... And
frankly it is very obscure, related to File>>nextVersion fail!

But it is again another problem.

Le 04/03/2019 à 08:04, akgrant43 a écrit :
>
> You're using an alpha image from 6 months before Pharo 7 was released
> and the stdio handling changed during that time - so your VM and image
> aren't compatible.
>
> The VM is the Pharo 7 stable VM. You really need to update to the
> released image.
>
-- 
GNU Dr. Geo
http://drgeo.eu


ByteString class(Object)>>doesNotUnderstand: #replaceFrom:to:with:startingAt:
ByteString(SequenceableCollection)>>copyFrom:to:
ByteString(SequenceableCollection)>>last:
[ :f | 
Number
	squeezeNumberOutOfString: (f basename last: f basename size - nameWithoutExtension size - 1)
	ifFail: [ 0 ] ] in FileReference>>nextVersion in Block: [ :f | ...
[ :stream | 
1 to: self size do: [ :index | 
	(selectBlock value: (each := self at: index))
		ifTrue: [ stream nextPut: (collectBlock value: each) ] ] ] in Array(SequenceableCollection)>>select:thenCollect: in Block: [ :stream | ...
Array class(SequenceableCollection class)>>new:streamContents:
Array(SequenceableCollection)>>select:thenCollect:
FileReference>>nextVersion
PharoChangesCondenser>>temporaryFile
PharoChangesCondenser>>reset
PharoChangesCondenser>>initialize
PharoChangesCondenser class(Behavior)>>new
PharoChangesCondenser class>>condense
AnObsoleteDrGeoInstallerWorkstation>>install
AnObsoleteDrGeoInstaller class>>forWorkstation
UndefinedObject>>DoIt
OpalCompiler>>evaluate
DoItChunk>>importFor:logSource:
[ :declaration | 
requestor ifNotNil: [ requestor contents: declaration contents ].
value := declaration importFor: requestor logSource: logSource ] in CodeImporter>>evaluate in Block: [ :declaration | ...
OrderedCollection>>do:
CodeImporter>>evaluate
[ codeImporter evaluate ] in STCommandLineHandler>>installSourceFile: in Block: [ codeImporter evaluate ]
BlockClosure>>on:do:
STCommandLineHandler>>handleErrorsDuring:reference:
STCommandLineHandler>>installSourceFile:
[ :reference | self installSourceFile: reference ] in [ sourceFiles do: [ :reference | self installSourceFile: reference ] ] in STCommandLineHandler>>installSourceFiles in Block: [ :reference | self installSourceFile: reference ]...etc...
OrderedCollection>>do:
[ sourceFiles do: [ :reference | self installSourceFile: reference ] ] in STCommandLineHandler>>installSourceFiles in Block: [ sourceFiles do: [ :reference | self installSourc...etc...
BlockClosure>>ensure:
STCommandLineHandler>>installSourceFiles

**Comment by akgrant43** [comment]
Hi Hilaire,

I think this issue can be closed.

Cheers,
Alistair

**Comment by Ducasse** [comment]
Tx!
