### ISSUE TITLE
When will we get a new release of P7 with the bugs fixed ?

### ISSUE THREAD

**Issue by badetitou** [guillep/pharo-core#2746]
Hello,

How can we ask for a minor release of P7 (because, some tests are failling in the current P7 image and a new release should solve at least some of them) ?

Benoit

**Comment by jecisc** [comment]
IIUC we need a new release (tag) from Esteban.

**Comment by badetitou** [comment]
ping @estebanlm

**Comment by badetitou** [comment]
done
