### ISSUE TITLE
merge capabilities of GLMHighlighterTextParserStyler into SHTextStyler

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#2752]
GLMHighlighterTextParserStyler is just adding a pluggable parser --> we can add that to SHTextStyler

**Comment by MarcusDenker** [comment]
I checked it: not really needed anymore. SHTextStyler is now the abstract class with a minimal API, GLMHighlighterTextParserStyler is just a subclass.

I close those

**Comment by Ducasse** [comment]
Marcus do you think that we should rescue and keep GLMhighlitgherTestParserStyler when we remove GLM or not?

**Comment by MarcusDenker** [comment]
not really. it just makes the parser pluggable which can be done easily as soon as it is needed.
