### ISSUE TITLE
Bring in improvements for ImageSegment saving and loading

### ISSUE THREAD

**Issue by theseion** [guillep/pharo-core#2755]
The ImageSegment code has received a couple of improvements, including:
- loading legacy V3 image segments into Spur
- loading 64-bit Spur segments into 32-bit Spur
- loading 32-bit Spur segments into 64-bit Spur
- natively loading N-bit Spur into N-bit Spur

These changes should be ported from Squeak.

**Comment by MarcusDenker** [comment]
We removed all support for image segments from Pharo a looong time ago, or not?

**Comment by theseion** [comment]
I see :) Well then, nothing to port (I loaded the image segment code into Pharo myself and forgot).
