### ISSUE TITLE
DNU  when try to file out category (WriteStream(Object)>>doesNotUnderstand: #trailer)

### ISSUE THREAD

**Issue by SabineMa** [guillep/pharo-core#2757]
I wanted to file out several methods of one **category**
File out of single method or class works.

![bildschirmfoto 2019-03-06 um 11 54 12](https://user-images.githubusercontent.com/13763544/53876359-e5268880-4006-11e9-9b49-7c4250743074.png)
![bildschirmfoto 2019-03-06 um 11 52 02](https://user-images.githubusercontent.com/13763544/53876387-f2dc0e00-4006-11e9-9df7-2ce3561b3497.png)

reproducable on win, mac and unix

"MessageNotUnderstood: WriteStream>>trailer"

**'From Pharo7.0.1 of 25 February 2019 [Build information: Pharo-7.0.1+build.149.sha.890f474a81f116ead0e68c8de77790aef4e9a752 (64 Bit)] on 6 March 2019 at 11:50:13.043605 am'!**

**WriteStream(Object)>>doesNotUnderstand: #trailer**
ClyTaggedMethodGroup(ClyMethodGroup)>>fileOut
[ :each | each fileOut ] in ClyFileOutCommand>>execute in Block: [ :each | each fileOut ]
Array(SequenceableCollection)>>do:
ClyFileOutCommand>>execute
ClyMethodGroupContextOfFullBrowser(ClySystemBrowserContext)>>executeCommand:by:
[ self prepareCommandForExecution.
context executeCommand: command by: self.
self applyCommandResult ] in CmdCommandActivator>>executeCommand in Block: [ self prepareCommandForExecution....
BlockClosure>>on:do:
CmdCommandActivator>>executeCommand
[ | selArgCount |
"show cursor in case item opens a new MVC window"
(selArgCount := selector numArgs) = 0
	ifTrue: [ target perform: selector ]
	ifFalse: [ selArgCount = arguments size
			ifTrue: [ target perform: selector withArguments: arguments ]
			ifFalse: [ target perform: selector withArguments: (arguments copyWith: evt) ] ].
self showShortcut.
self changed ] in ToggleMenuItemMorph(MenuItemMorph)>>invokeWithEvent: in Block: [ | selArgCount |...

**Comment by MarcusDenker** [comment]
The fix seems simple: remove the line with the message send #trailer and it works

**Comment by MarcusDenker** [comment]
I added: https://github.com/pharo-ide/Calypso/issues/481

**Comment by dionisiydk** [comment]
Calypso method is a copy of ClassDescription>>#fileOutCategory: (I did the copy to support file out on any method group). 
This method is still in image and it also asks stream for trailer.

In Pharo 6 this method does nothing. So yes, simple removal is enough

**Comment by SabineMa** [comment]
i close this because of the new issue https://github.com/pharo-ide/Calypso/issues/481
