### ISSUE TITLE
Bag doesn't support #asDictionary, Walkback DNU #key

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2763]
I was surprised to find that a Bag can’t convert to a dictionary (even though it has a mapping between values and occurences) - e.g.

Bag new 
	addAll: 'aabbbbcddd’; 
	asDictionary 

Gives an error - Dnu #key

It looks to me like Bag is inheriting a bad version of #associationsDo: 

I think it should support this, or throw an exception and perhaps guide the user to #valuesAndCounts.

**Comment by MarcusDenker** [comment]
merged PR
