### ISSUE TITLE
Introduce new debuggers

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2771]
It would be great to have more options for debuggers. 

I am thinking to have at least:
- A NoDebugger that will never do anything 
- A LogDebugger that will log all exceptions to the transcript

This is useful to deploy an application in some cases.

**Comment by VincentBlondeau** [comment]
maybe a ToastDebugger too? (with informs when exceptions are triggered)
See https://github.com/VincentBlondeau/Cruiser/tree/121a2aa38f1d8e59b66ef192c80451efbc4ca896/src/Cruiser.package/NoDebugger.class
