### ISSUE TITLE
Bag improvements

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2773]
From the mailing-list discussions. 
Tim published a related issue. https://github.com/pharo-project/pharo/issues/2763
 So we should sync and add also more tests.

======================================================
Handling   <some bag> as: Dictionary 
is really quite straightforward.
Add a one-line method to Bag:

Bag>>
associationsDo: aBlock
    contents associationsDo: aBlock.

This is a good idea anyway, because currently there is a bug where
aBag associationsDo: aBlock
fails to pass Associations to aBlock.  Once you have done that,
'abracadabra' asBag as: Dictionary
just works.  This one simple addition
 - makes aBag associationsDo: aBlock work when it didn't before
 - makes aBag asDictionary work
 - makes aBag as: Dictionary work
 - makes Dictionary newFrom: aBag work

#valuesAndCounts is a method that violates good OO practice,
because it exposes (what you'd expect to be) private state.
For example,
  b := 'abracadabra' asBag.
  b valuesAndCounts at: $a put: 'BOOM!'.
  b
select, Print It, BOOM!.  It should *copy* the dictionary.

**Comment by MarcusDenker** [comment]
This has been done
