### ISSUE TITLE
Accessor creation throws error (SubscriptOutOfBounds) in Epicea

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#2775]
- create a class Foo
- go to the class side and select "generate accessors"
- the list is empty - but still click on OK

Array(Object)>>errorSubscriptBounds:
Array(Object)>>at:
Array(SequenceableCollection)>>first
Array(SequenceableCollection)>>anyOne
SycRefactoringPreview>>asEpiceaEvent
EpMonitor>>jobStarted:
MessageSend>>value:
MessageSend>>cull:
MessageSend>>cull:cull:
[ action cull: anAnnouncement cull: announcer ] in AnnouncementSubscription>>deliver: in Block: [ action cull: anAnnouncement cull: announcer ]
BlockClosure>>on:do:
BlockClosure>>on:fork:
AnnouncementSubscription>>deliver:
[ "Ensure delivery to remaining announcements" subscription deliver: anAnnouncement ] in SubscriptionRegistry>>deliver:to:startingAt: in Block: [ "Ensure delivery to remaining announcements" sub...etc...
BlockClosure>>ifCurtailed:
SubscriptionRegistry>>deliver:to:startingAt:
SubscriptionRegistry>>deliver:to:
SubscriptionRegistry>>deliver:
Announcer>>announce:
Job>>announce:
Job>>prepareForRunning
[ self prepareForRunning.
CurrentJob value: self during: [ ^ block cull: self ] ] in Job>>run in Block: [ self prepareForRunning....
BlockClosure>>ensure:
Job>>run
SycRefactoringPreview>>accept
[ submitDialog accept.
aCommandActivator applyCommandResult ] in SycGenerateAllInstVarAccessorsCommand(CmdCommand)>>confirmRefactoringInContext:by: in Block: [ submitDialog accept....
BlockClosure>>cull:
DialogWindowPresenter>>triggerOkAction
[ :presenter | 
presenter triggerOkAction.
presenter close ] in SycRefactoringPreview(ComposablePresenter)>>initializeDialogWindow: in Block: [ :presenter | ...
BlockClosure>>cull:

**Comment by tinchodias** [comment]
Thanks for reporting

**Comment by tinchodias** [comment]
Couldn't reproduce it in latest P8, because there is a validation in the refactoring, when you choose the action in the menu. But probably the #asEpiceaEvent shouldn't assume that collection is not empty...
Not sure if still it can be merged into P7 if I fix it.

**Comment by sbragagnolo** [comment]
I do agree with martin. This seems to not be a problem in pharo8 anymore :)

**Comment by astares** [comment]
OK - checked. It does not happen in P8 anymore.
No need to hotfix it for P7. We close the issue
