### ISSUE TITLE
Hitting an undefined class gives a debugger with misleading message "#new was sent to nil"

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2776]
When you save a method that references an as yet undefined class - there is now an option to save is as undeclared (the same applies when using the Opal compiler - it can be configured to do this automatically as well).

This is a great enhancement, that lets you code "in the now" without being forced down another path you aren't ready for.

However - when you execute the code and hit that undefined class (perhaps due to something like: MyUndefinedClass new" the debugger shows the messsage "#new was sent to nil".

While this might be technically correct - its not very helpful and I'm sure we can do better. In my mind, this is an undefined class (not the same as nil), and I wonder if it is stored in the bytecode as such (or could be) so that we could present the more informative message "#MyNewClass is Undefined".

Everything else is then perfect, as we have already fixed the debugger so that create will let you create a new class an continue.

So its just the message - and then it really makes TDD awesome! (its still pretty awesome now - in Exercism, when you run a test, you can click Create, to get a new class, continue, then get a debugger and click Create again to define a new method - its very fluid).

Tim

**Comment by bencoman** [comment]
On Fri, 8 Mar 2019 at 17:41, Tim Mackinnon <notifications@github.com> wrote:

> When you save a method that references an as yet undefined class - there
> is now an option to save is as undeclared (the same applies when using the
> Opal compiler - it can be configured to do this automatically as well).
>
> This is a great enhancement, that lets you code "in the now" without being
> forced down another path you aren't ready for.
>
> However - when you execute the code and hit that undefined class (perhaps
> due to something like: MyUndefinedClass new" the debugger shows the
> messsage "#new was sent to nil".
>
> While this might be technically correct - its not very helpful and I'm
> sure we can do better. In my mind, this is an undefined class (not the same
> as nil), and I wonder if it is stored in the bytecode as such (or could be)
>
I don't have the answer, but for some insight, in the Browser for the
containing method, right-click > Extra > Inspect, then review the tabs...
[AST] tab expanded to the leaf node shows...
"RBVariableNode(MyUndefinedClass )"
[Ir] tab shows... "pushLiteralVariable: MyUndefinedClass"
[Bytecode] tab shows... "17 <40> pushLit: MyUndefinedClass"
[Raw] Tab shows... literal1 "#MyUndefinedClass->nil"

So its considered a variable with a value of nil, which makes sense since
"Leave variable undeclared" was selected when the method was saved

cheers -ben

so that we could present the more informative message "#MyNewClass is
> Undefined".
>
Everything else is then perfect, as we have already fixed the debugger so
> that create will let you create a new class an continue.
>
> So its just the message - and then it really makes TDD awesome! (its still
> pretty awesome now - in Exercism, when you run a test, you can click
> Create, to get a new class, continue, then get a debugger and click Create
> again to define a new method - its very fluid)
>

**Comment by macta** [comment]
If the byte code can’t handle it - then I guess we can marry it up with the source to identify the variable name and show the right message. At the moment it’s just misleading - I didn’t mean to save null, I saved an undeclared variable that has a name. Anyway, it sounds doable somehow

**Comment by bencoman** [comment]
> [Raw] Tab shows... literal1 "#MyUndefinedClass->nil"

I wonder if that comes from...
    RBVariableNode>>binding
        ^self propertyAt: #binding ifAbsent: [nil].

Potentially useful methods...
RBVariableNode>>hasIncompleteIdentifier 
RBVariableNode>>isUndeclared

I notice that RBVariableNode has 7 subclasses.
Perhaps it would help to have a subclass RBUndefinedGlobalOrVariableNode.

**Comment by macta** [comment]
Actually Ben you are right - in the exception, in the context (thisContext) there is the sender of the message , which has a method (CompiledMethod) and you could then traverse the AST to find the method name (#new) who is sent as a message to a node where #isUndeclared is true.

Its a bit of a mouthful, but I wonder if there is a more immediate way - as you mention the raw view it seems to show it - so sending #literals to the method in question does give an array of them - and you can select: [ :i | i isKindOf: UndeclaredVariable  ].  But if there was more than one - not sure you can marry that up to the error...

And then the penny drops - thisContext sourceNodeExecuted give the node you were executing.
so: thisContext sourceNodeExecuted nodesDo: [:n |
	(n isVariable and: [ n isUndeclared]) ifTrue: [ ^n name ] gives you the name of the undeclared variable you hit.

But not quite sure how to plug that together yet.

**Comment by macta** [comment]
Ok - I know how to do it, and I think it simplifies my previous class creation submission (doing it properly often simplifies things)

**Comment by macta** [comment]
@Ducasse - I thought putting the word fix in the pr would close the issue automatically? Given this is merged, should this have closed automatically?

**Comment by bencoman** [comment]
use the phrase "Fixes #123" or "Fixes: #123" in your pull request "description" or "commit message"
not just in a comment
https://help.github.com/en/articles/closing-issues-using-keywords
