### ISSUE TITLE
Calypso: excessive active tab text should be clipped

### ISSUE THREAD

**Issue by ofi** [guillep/pharo-core#2780]
Whenever the tab title text area of an active source tab in calypso of P7.0.1 exceeds the tab width it overlaps into the next neighbor like here:
<img width="538" alt="screenshot_calypso-active-tab-glitch" src="https://user-images.githubusercontent.com/408223/54070792-0389bf80-4265-11e9-9d21-76f3a7e933ca.png">

It's not only itching the eye but sometimes makes it hard to hit the remaining tab area screen estate of the neighboring tab to active it by click, because the overlapping text area catches the event.
[Edit]Clarification.

**Comment by dionisiydk** [comment]
Do you use large fonts?

Anyway it is an issue with TabMorph

сб, 9 мар. 2019 г. в 14:20, Olaf Fiedler <notifications@github.com>:

**Comment by ofi** [comment]
Yep, it's the "medium" font set of the predefined styles, offered under the System Browser's "Appearance">"Standard fonts" settings.

**Comment by ofi** [comment]
In terms of UX this seems to me to be too important to be forgotten. Hence this comment to prevent the issue from being closed automatically.

**Comment by estebanlm** [comment]
this is fixed upstream
