### ISSUE TITLE
Pulling Polymath failed in type 6

### ISSUE THREAD

**Issue by chang111** [guillep/pharo-core#2785]
After I executor the script:
`Metacello new
        repository: 'github://PolyMathOrg/PolyMath:master/src';
        baseline: 'PolyMath';
        load`
It crashed.

**Comment by Ducasse** [comment]
Can you tell us 
- os
- pharo version
- vm version
Else this is not clear. Then you should report this to the polymath bug tracker. 
Stef

**Comment by chang111** [comment]
I have run it on os and pharo version is 7. The error is "IceGenericError:HTTP parser error:stream ended at an unexpected  time"

**Comment by chang111** [comment]
It seems the network error. I tried twice in the same image.It finally suceeds.

**Comment by MarcusDenker** [comment]
so I guess we can close the issue?
