### ISSUE TITLE
ci.pharo.org broken

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#2791]
http://ci.pharo.org does not point to CI server anymore.

Anyone able to repair the link?

@estebanlm 
@MarcusDenker

**Comment by MarcusDenker** [comment]
ah, yes, I can do that

**Comment by MarcusDenker** [comment]
I have fixed it to point to https://ci.inria.fr/pharo-ci-jenkins2, but the surface of that is not that nice...

**Comment by astares** [comment]
Thanks!
