### ISSUE TITLE
do not run RBBadMessageRule for tests

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#2808]
Tests do often "meta" level checks. #isKindOf: is not a bad message to send in a test. The same is true for many of the messages in RBBadMessageRule

(RBBadMessageRule should be split in the future, one rule for each message, with a good explanation each)

**Comment by MarcusDenker** [comment]
still relevant (will do that soon)

**Comment by Ducasse** [comment]
Good idea! Indeed reflective calls in tests make sense.

**Comment by jecisc** [comment]
+1
