### ISSUE TITLE
Failing tests in MorphicTextInputFieldAdapterTest

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#2813]
Failing for Pharo8 on all 3 architectures:

MorphicTextInputFieldAdapterTest testChangeWidgetTextUpdatesPresenter 
MorphicTextInputFieldAdapterTest testMaxLengthIsSetInWidget

**Comment by Ducasse** [comment]
Yes we know. Now PluggableTextInputFieldMorph implemented this is in a hackish way 
that Alain did not added to Rubric. We will have to fix this.

**Comment by MarcusDenker** [comment]
The problem is that now the test were not green for 2 weeks on the CI and we integrated other Pull Requests that made even more tests fail due to that.

**Comment by MarcusDenker** [comment]
I will add a #skipOnPharoCITestingEnvironment to the tests

**Comment by MarcusDenker** [comment]
this issue will be closed with integrating the PR. I will add a note to #2980 to remove the skip
