### ISSUE TITLE
distinguish between instance-side and class-side in method template

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#2817]
This is https://pharo.fogbugz.com/f/cases/22748/distinguish-between-instance-side-and-class-side-in-method-template

A new method #sourceCodeTemplateFor: was introduced, it is not used in Pharo8.

better solution: implement #sourceCodeTemplate on Metaclass instead.

==> works, no API change needed.

The PR should remove sourceCodeTemplateFor: and rewrite the test to test #sourceCodeTemplate

**Comment by bencoman** [comment]
> better solution: implement #sourceCodeTemplate on Metaclass instead.

That is the obvious solution and I vaguely remember trying it first but there was "some" problem with it, but sorry I can't remember what - maybe my memory is mistaken.
