### ISSUE TITLE
Welcome screen is corrupted in 7.0.2 release

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2828]
When you launch the new 7.0.2 release, the welcome screen is corrupted (has something changed in the build process or has something glitched?)
![image](https://user-images.githubusercontent.com/5553623/54392835-7bf6e300-46a0-11e9-96d3-8c6e371476e1.png)

**Comment by macta** [comment]
This seems to affect Pharo launcher images and not zero conf?

**Comment by astares** [comment]
Is this a permenant thing? What when you close the Welcome screen and reopen it using Help -> Welcome

**Comment by macta** [comment]
Its just a temporary thing - but doesn't look great for new users. Interestingly, zero conf doesn't have this issue, its just PharoLauncher images from what I can tell.
