### ISSUE TITLE
Epicea: Revert class deletion does not reveret method deletion

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2853]
Today I did a wrong shortcut and ended up deleting a package. I wanted to use Epicea to revert that, but it only reverted the classes deletion. The classes then contained no method :(

**Comment by tinchodias** [comment]
I have it partially fixed. It's a solution that works on my image but should write some tests. It required several workarounds due to the fact the ClassRemoved system announcement arrives when the class is already obsolete and it's not direct to get the real package names and class names.

**Comment by tinchodias** [comment]
hi @jecisc ! please review #2853 when you have some time :)
