### ISSUE TITLE
CompiledMethod>>#commentsIn: should be enhanced

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#2864]
The source code is quite hard to understand and I think it should be possible to do it directly using a regular expression. Or maybe even directly using system's parser.

**Comment by MarcusDenker** [comment]
one good aspect is that it does not depend on regular expressions or the parser...

**Comment by MarcusDenker** [comment]
using the parser might be nice: it is something that has  to do with making meaning from the source, something that we have the parser and AST for.

**Comment by juliendelplanque** [comment]
Ok, maybe good comments then. :-)

But I'm sure that even without calling another framework it can be rewritten better.
I will try to do it during a sprint.

**Comment by MarcusDenker** [comment]
a question, too, is if we should not move that API to the method.

why have

Behavior commentsAt: #commentsAt:

if you can just do

(Behavior>>#commentsAt:) comments at: 

?

To me that is much more object oriented

**Comment by MarcusDenker** [comment]
e.g. instead of firstCommentAt: with that it would be

(Behavior>>#commentsAt:) comments first

no special method needed

**Comment by MarcusDenker** [comment]
TODO use "ast comments" instead of #commentsIn:
