### ISSUE TITLE
Debugger should step silently over #halt

### ISSUE THREAD

**Issue by bencoman** [guillep/pharo-core#2868]
Moved from https://pharo.fogbugz.com/f/cases/22474/Debugger-should-step-silently-over-halt.

I'll often put several breakpoints in code like this...
```
debug := true.
"Somewhere else in application code..."
debug ifTrue: [ self halt ].
1 + 1. "Representing some longer bit of application code"
debug ifTrue: [ self halt ].
2 + 2. "Representing some longer bit of application code"
debug ifTrue: [ self halt ].
3 + 3. "Representing some longer bit of application code"
```
While stepping through code after hitting the first halt,  
I am used to subsequent halts being silently stepped over.  
I just confirmed this with http://files.pharo.org/platform/Pharo6.0-win.zip
and also build 60541 started from PharoLauncher.

However build 71231 and build 60542 do not silently step over a #halt.
Each produces slightly different results (pics attached).

**Comment by jecisc** [comment]
Still relevent.

**Comment by StevenCostiou** [comment]
This is now fixed in Pharo 9
