### ISSUE TITLE
Minor cleanup of Delay

### ISSUE THREAD

**Issue by bencoman** [guillep/pharo-core#2870]
Moved from https://pharo.fogbugz.com/f/cases/22637/Minor-cleanup-of-Delay

While doing the DelayScheduler refactoring some guards were added in Delay so that it could work with both new and old DelaySchedulerXXX hierarchies.
After letting thing settle a bit after removing the old hierarchy, those guards can be removed from Delay and a few redundant instance variables deleted.
Incoming PR shortly.

**Comment by bencoman** [comment]
Pavel requested this move to Pharo 8.

btw, the PR is https://github.com/pharo-project/pharo/pull/1957

**Comment by SergeStinckwich** [comment]
Should be closed @MarcusDenker
