### ISSUE TITLE
Debugger variable "error obtaining field value" inside some blocks

### ISSUE THREAD

**Issue by bencoman** [guillep/pharo-core#2872]
Moved from https://pharo.fogbugz.com/f/cases/19836/Debugger-variable-error-obtaining-field-value-inside-some-blocks

Add this method and DEBUG the comment...
    Mytest class >> test
        "self test"
        |aaa bbb| 
        aaa := 0.
        [  ['a'='b'] whileFalse: [ 
            aaa := 1.
            Transcript crShow: aaa.
            ].
        ] value. 

1. Step once INTO, and "aaa" variable shows "error obtaining field value"
2. Step once THROUGH, and the error clears.
3. Step three times THROUGH so inside ['a'='b'], and "aaa" variable shows "error obtaining field value"
4. Step THROUGH, and the error clears.

Remove the definition of "bbb" variable, and the error at [3.] does not occur.
Change ['a'='b'] to [aaa=1], and the error at [3.] does not occur.
Remove the [...]value wrapper, and all errors go away.

This might be a corner case okay to leave for Pharo 7, 
but I've put it Must Fix at least until its triaged.

**Comment by bencoman** [comment]
Dennis says... "So problem that debugger step into method at instruction when temp vectors are not initialized yet. So thisContext contains nil as value of temp vector instead of #(nil).
Right fix would be to always start method in debugger at point where all temp vectors are created.
I also try bad fix to return #(nil) for OCCopyingTempVariable when given context has nil value for variable:
```
OCTempVariable>>readFromContext: aContext scope: contextScope
    "Usually the loop is useless, the first case with i = offset returns the correct result. 
    However, the loop is required for specific case as Debugger restart feature."

    | value |
    value := aContext tempAt: (contextScope outerNotOptimizedScope node irInstruction indexForVarNamed: name).
    ^value ifNil: [ #(nil) ]
```

**Comment by MarcusDenker** [comment]
This is the case in #readVectorFromContext:scope: at the end when it reads the vector and it is nil

But in addition, there is no outer context to read from.

We can add a nil check for "aContext outerContext" and return an empty array of the correct size:

^ theVector ifNil: [ 
		aContext outerContext ifNil: [ ^Array new: tempVectorVar tempVectorForTempStoringIt size ].
		self readVectorFromContext: aContext outerContext scope: contextScope outerScope ]
