### ISSUE TITLE
Critiques - "Temporaries read before written" versus nil-checking messages

### ISSUE THREAD

**Issue by bencoman** [guillep/pharo-core#2873]
Copied from... https://pharo.fogbugz.com/f/cases/21704/Critiques-Temporaries-read-before-written-versus-nil-checking-messages

On 15 April 2018 at 22:42, Ben Coman <btc@openinworld.com> wrote:
>
> The greater prominence of Critiques in Calypso 
> encourages me to try to clean them out.
>
> I bumped into a false positive "Temporaries read before written."
> that I've condensed to the following example.
>
>    test
>        |x|
>        [ x := nil ] whileNil: [ x ifNil: [ x := 1] ]
>
> Now before I log an Issue, is it feasible to be able to recognise this?
> Perhaps only for common looping idioms?
>
> Anyway, the workaround is simple enough...
>    test
>        |x|
>        x := nil. "silence critiques"
>        [ x := nil ] whileNil: [ x ifNil: [ x := 1] ]
>
> cheers -ben

On 16 April 2018 at 03:07, Denis Kudriashov <dionisiydk@gmail.com> wrote:
>
> Maybe critique can be a bit smarter and check that sent message is known by nil.

That sounds like a practical approach.  Browsing the messages of Undefined, maybe its worthwhile to restrict this to messages containing the the string "nil", because this shows explicit intent and cover most common cases.

**Comment by MarcusDenker** [comment]
I would like to change it so that *every* assignment in a block counts as "this is written to".

Else there will always be false positives

**Comment by bencoman** [comment]
Still relevant.
