### ISSUE TITLE
Small cursor on high-DPI displays in Windows 10 Creators Update

### ISSUE THREAD

**Issue by webwarrior-ws** [guillep/pharo-core#2883]
Moved from https://pharo.fogbugz.com/f/cases/20281/Small-cursor-on-high-DPI-displays-in-Windows-10-Creators-Update

After Windows 10 on my notebook installed Creators update, cursors in Pharo no longer scale and are now twice smaller than they should be.

Tried launching Pharo with different compatibility settings regadring high DPI, nothing works.

Latest stable VM.

**Comment by astares** [comment]
You can load VistaCursor from catalog. It has even a setting to scale the cursors.

**Comment by webwarrior-ws** [comment]
@astares 
As I've already written on the forum,
> This only partly fixes the problem. 
> Not all cursors are replaced - e.g. cursor for text selection is sitll tiny. 
> Also seting has to be changed every time someone switches to another computer or even to another display with different DPI.

**Comment by webwarrior-ws** [comment]
Seems to be fixed by Windows in one of the updates. Don't know which one and when it happened.
Perhaps wait for confirmation by other users before closing?

**Comment by guillep** [comment]
Anybody else can confirm?

**Comment by MarcusDenker** [comment]
No answer for a year is a "yes". I close it as fixed
