### ISSUE TITLE
Spotter should ignore the current top-level window

### ISSUE THREAD

**Issue by StephanEggermont** [guillep/pharo-core#2886]
The current window having the focus is unlikely to be an interesting one to spot towards. It should not be shown in the suggested list, and definitely not twice in the top positions

**Comment by VincentBlondeau** [comment]
For example:

![HsxxhQNOhu](https://user-images.githubusercontent.com/4706329/54609255-def6ca00-4a52-11e9-8ba7-4582dea3d995.gif)

**Comment by StephanEggermont** [comment]
still needed

**Comment by estebanlm** [comment]
I think this is done ?
