### ISSUE TITLE
Keymap Browser tools - filtering gives walkback (dnu: #resetFilteringBlock)

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2887]
If you launch the System | Keymap Browser - if you try and type in a filter you get an error.

It looks like : ListPresenter>>#resetFilteringBlock is implemented one class too low (however moving it up doesn't seem to let filtering work)?

Is this tool even used? But then how do you find keyboard shortcuts?

RubExtraSelectionDecorator(Object)>>doesNotUnderstand: #replaceFrom:to:with:
[ super doesNotUnderstand: aMessage ] in RubExtraSelectionDecorator(RubParagraphDecorator)>>doesNotUnderstand: #replaceFrom:to:with: in Block: [ super doesNotUnderstand: aMessage ]
BlockClosure>>cull:
Context>>evaluateSignal:
Context>>handleSignal:
MessageNotUnderstood(Exception)>>signal
RubOpeningClosingDelimiterDecorator(Object)>>doesNotUnderstand: #replaceFrom:to:with:
[ super doesNotUnderstand: aMessage ] in RubOpeningClosingDelimiterDecorator(RubParagraphDecorator)>>doesNotUnderstand: #replaceFrom:to:with: in Block: [ super doesNotUnderstand: aMessage ]
BlockClosure>>cull:
Context>>evaluateSignal:
Context>>handleSignal:
Context>>handleSignal:
MessageNotUnderstood(Exception)>>signal
MultiColumnListPresenter(Object)>>doesNotUnderstand: #resetFilteringBlock
KeymapBrowser>>setFilter:
[ :text | 
clearFilterButton enabled: text isNotEmpty.
self setFilter: text ] in KeymapBrowser>>initializePresenter in Block: [ :text | ...
BlockClosure>>cull:
BlockClosure>>cull:cull:
BlockClosure>>cull:cull:cull:
BlockClosure>>cull:cull:cull:cull:
[ :announcement :ann | 
aBlock
	cull: announcement newValue
	cull: announcement oldValue
	cull: announcement
	cull: ann ] in CollectionValueHolder(Model)>>whenChangedDo: in Block: [ :announcement :ann | ...
BlockClosure>>cull:cull:
[ action cull: anAnnouncement cull: announcer ] in AnnouncementSubscription>>deliver: in Block: [ action cull: anAnnouncement cull: announcer ]
BlockClosure>>on:do:
BlockClosure>>on:fork:
AnnouncementSubscription>>deliver:
[ "Ensure delivery to remaining announcements" subscription deliver: anAnnouncement ] in SubscriptionRegistry>>deliver:to:startingAt: in Block: [ "Ensure delivery to remaining announcements" sub...etc...
BlockClosure>>ifCurtailed:
SubscriptionRegistry>>deliver:to:startingAt:
SubscriptionRegistry>>deliver:to:

**Comment by jecisc** [comment]
Hi, 
I think I already opened an issue in Spec issue tracker about that some time ago.
