### ISSUE TITLE
add a baseline for TelePharo support in the minimal image

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#2889]
Add a baseline for TelePharo support in the minimal image that will not be used during the Pharo image but available for the building of custom images.

**Comment by noha** [comment]
What would be only for telepharo support?

**Comment by pavel-krivanek** [comment]
I was playing with something more general but that would require to add the other things like FFI
and for example, the sort functions are required especially because of TelePharo

The other option is to create something more general with groups
