### ISSUE TITLE
remove SmalltalkEditor

### ISSUE THREAD

**Issue by plantec** [guillep/pharo-core#2895]
Now that Rubric is sync back with text/smalltalkEditor, the old editors should be removed.
Let us start with SmalltalkEditor.

**Comment by plantec** [comment]
Now that Rubric is the only text/smalltalkEditor, the old editor should be removed

**Comment by StephanEggermont** [comment]
Blocked by Issue #2904

**Comment by Ducasse** [comment]
Sorry this is independent and we will integrate the PR Alain did do to remove SmalltalkEditor. 
I'm waiting for too long on this one. 
And after we will remove editor, texteditor and pluggableTextMorph and pluggableTextInputFieldMorph.
There are too much cruft in this system. We will massively clean it.
