### ISSUE TITLE
Pharo should learn on correct indentation

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#2896]
One should be able to select a block of code /testand use Tab to shift all of it to the right (or to the left - Shift+Tab). That's how most editors do it.

See https://twitter.com/i/status/1106179169472471040

Also look at discussion here: http://forum.world.st/Text-Indentation-in-Pharo-editor-td5059993.html

**Comment by jecisc** [comment]
Seems a duplication of https://github.com/pharo-project/pharo/issues/2629

**Comment by MarcusDenker** [comment]
I copied the comment over and will close this issue
