### ISSUE TITLE
TextPresenter does not support keystroke based focus on next (17789)

### ISSUE THREAD

**Issue by StephanEggermont** [guillep/pharo-core#2903]
TextPresenter>>eventKeyStrokesForNextFocus
    "String describing the keystroke to perform to jump to the next widget"
    ^ { Character arrowRight command ctrl asKeyCombination }

That key combination is not available on Ubuntu (it switches the window to use the right half of the screen)

https://pharo.fogbugz.com/f/cases/17789/TextModel-does-not-support-keystroke-based-focus-on-next

**Comment by StephanEggermont** [comment]
Still broken in Spec2 too

**Comment by guillep** [comment]
This method does not exist anymore in my Pharo 11 image.
