### ISSUE TITLE
Rubric duplication of Morphs is broken (16612)

### ISSUE THREAD

**Issue by StephanEggermont** [guillep/pharo-core#2904]
Henrik wrote in a thread on RubAbstractTextArea copying in pharo-dev:

"It does not seem that RubScrolledTextMorph supports duplication/copy (tried to duplicate one from nautilus code area and the same clear all code happened. Trying to duplicate a Playground just freezes the image (might be some circular references that is not handled when copying ))."

In my image, it freezes for several seconds and then clears all rubric based editors. 

Morphs are copied using #veryDeepCopy (as you'd normally expect all submorphs to be copied too). 
The #veryDeepInner: and #veryDeepFixupWith: should help indicate which instance variables of the morph should not be deep copied, and allows for clean up afterwards. The implementation in 
RubAbstractTextArea might be out of sync, and calls a method with a strange implementation:

text: t textStyle: s color: c textColor: tc
    "Private -- for use only in morphic duplication"    
    self releaseParagraph.
    super text: t textStyle: s color: c textColor: tc.

It is the only implementation of #text:textStyle:color:textColor

http://forum.world.st/RubAbstractTextArea-copying-td4850987.html
http://forum.world.st/Rubric-Event-handling-issue-td4850374.html

https://pharo.fogbugz.com/f/cases/16612/Rubric-duplication-of-Morphs-is-broken

**Comment by StephanEggermont** [comment]
Here is a fun example:

| m main dup |
 
m := RubScrolledTextModel new newScrolledText beWrapped.
 
m
beWrapped;  
withLineNumbers; 
withoutAdornment;
beForSmalltalkScripting.
 
main := m openInWindow.
main extent: 400@400.
main setLabel: 'Main'.
 
main position: 20@20.
 
dup := main duplicate.
 
dup openInWorld.
dup position: 440@20.
dup setLabel: 'Duplicate'.

Write something in the main window. then select the text area in the duplicate window.
 
 
One strange thing is that the duplication works at al,l because what should happen is that an error should be thrown from RubParagraph, but it looks like the copying reaches this point.

**Comment by StephanEggermont** [comment]
Ownership is not handled correctly, leading to all kinds of problems

**Comment by StephanEggermont** [comment]
Might also be related to Issue #2904

**Comment by plantec** [comment]
Morph duplication is a mess and should be deprecated

**Comment by StephanEggermont** [comment]
Morphs can be duplicated. That is essential behavior. Where it fails, ownership is incorrect.

**Comment by plantec** [comment]
maybe at the level of simple graphic objets such as Morph, CircleMorph, or a little bit more complex morph. But at the level of a widget, why it is essential ?
In my opinion it does not make sense as a general and as a systematic expectation.  deep copy, very deep copy and co are not maintainable. A widget should be allowed to forbid duplication  for itself. This is already the case, at least for the world.

**Comment by StephanEggermont** [comment]
That's fine for certain specific (or abstract) morphs. It is certainly wrong for widgets. I might have to choose to break linking to a model, but the copying needs to work. That is the whole purpose of morphs

**Comment by plantec** [comment]
yes, there is the model and the observers that can be listening to the announcements.

**Comment by StephanEggermont** [comment]
And the current situation leads to data loss

**Comment by Ducasse** [comment]
Hi Stephan 

Do not expect that it will be magically be fixed. And I agree with Alain: why a widget should be duplicated. veryFixInner, deepcopy all this logic should be revisited and right now this is a huge mess.

Now we can also say to Alain go and work on his real time scheduler instead of losing his time helping us. 
So we should understand how much we want to put in the system. Frankly what we are doing around Rub is to remove shit in Morphic and to avoid code bloat. But Rub is not the panacea and I hope that we will be able to remove Morphic. 
Now it looks like we are always the only one to really clean the system and sometimes
this is not difficult just boring tedious and annoying. And I do not that instead of watching TV. 
So you can fill up bug reports but if nobody outside of the time is really helping them
do not dream too much. 

Stef

**Comment by StephanEggermont** [comment]
I don't expect magic. I have enough patience. And this is something that not too many people can fix, as it has a lot of moving parts. It took long enough to understand where the actual problem is. And that  is indeed that morphs need to support duplication, and that deciding how to deal with that is difficult.

**Comment by StephanEggermont** [comment]
This remains important basic broken functionality of the system, at least until the Bloc based editor is introduced

**Comment by Ducasse** [comment]
I do not think that this will be ever fixed so I suggest that we close it.
