### ISSUE TITLE
Switching in the method stack of the debugger make one loose code (22484)

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#2907]
![2018-09-24_15-36-51](https://user-images.githubusercontent.com/4706329/54609661-b7543180-4a53-11e9-8319-741545bc2a9c.gif)

Suggested by @jecisc : I imagine we should pop a window "You will lose your current changes. Continue? Yes/No"

**Comment by VincentBlondeau** [comment]
https://github.com/pharo-project/pharo/issues/2912

**Comment by VincentBlondeau** [comment]
UP

**Comment by VincentBlondeau** [comment]
Still happening even in the new debbugger

**Comment by StevenCostiou** [comment]
This is now fixed in the new debugger.
