### ISSUE TITLE
deprecate on:send:to: and use when:send:to: (4399, 5087, 16740)

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#2908]
![image](https://user-images.githubusercontent.com/4706329/54609970-49f4d080-4a54-11e9-932d-43af3f4267c0.png)

http://www.mail-archive.com/pharo-project@lists.gforge.inria.fr/msg49343.html

**Comment by Ducasse** [comment]
Hello vincent
on:send:to: is for Morph. when:send:to: for announcer. 
So this is ok?

**Comment by VincentBlondeau** [comment]
yup
