### ISSUE TITLE
Under Windows the key to remove a word is not SHIFT+Backspace but CTRL + Backspace

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#2914]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/13882
Status: Work Needed
Project: Keymapping
Original Author: Vincent Blondeau
Date: 21 August 2014 4:30:15 pm
	
Description:
	
When you want to remove a word from an editor, the current Pharo keybinding is Shift+BackSpace and Shift+Suppr. But the default Windows binding is Ctrl+BackSpace and CtrlShift+Suppr.

**Comment by VincentBlondeau** [comment]
Reply:
Author: Nicolai Hess
Date: 15 October 2014 8:53:33 pm
	
Message:
	
I am afraid, this part of keymapping does not distinguish between
different platforms. If we change the code here, it would be like that
for all platforms.

**Comment by VincentBlondeau** [comment]
Reply:
Author: Ben Coman
Date: 11 August 2015 4:16:14 pm
	
Message:
	
Which part of code defines these?  
 
 Is this related to the work done to align Cmd/Ctrl as OSX/Win platform meta keys for the majority of Pharo shortcuts?  There will be exceptions and where possible we should conform with existing platform conventions per...
 
 https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts

**Comment by VincentBlondeau** [comment]
Reply:
Author: Nicolai Hess
Date: 18 June 2016 6:53:32 pm
	
Message:
	
with case 18430, it will be easier to define this behavior more platform dependent

**Comment by VincentBlondeau** [comment]
Reply:
Author: Vincent Blondeau
Date: 19 June 2017 8:40:44 am
	
Message:
	
Problem still existing...

**Comment by VincentBlondeau** [comment]
Still there

**Comment by NSUSpray** [comment]
Still relevant.

**Comment by fmqa** [comment]
Well, can we fix it then? PR #12096 updates all bindings accordingly.

Note that ctrl+right and ctrl+left already navigate to the next/previous words so this just makes everything symmetric and logical.
