### ISSUE TITLE
Execute Commented code is not possible anymore

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#2915]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/19095
Status: Work Needed
Project: Rubric
Original Author: Vincent Blondeau
Date: 15 September 2016 12:31:25 pm
	
Description:
	
Under Pharo 5.0, it is possible to execute code inside comments by pressing CTRL+P with the carret at the end of the line.
 
 Eg: 
 
 Now, we have to select the code inside the comments... The code is not executed and the line of code flashes once in black.

**Comment by VincentBlondeau** [comment]
Reply:
Author: Pavel Krivanek
Date: 21 September 2016 8:40:26 am
	
Message:
	
It is now processed the same way as an empty line.

in RubSmalltalkEditor>>#computeSelectionIntervalForCurrentLine the skipping of the comments is done explicitly

**Comment by VincentBlondeau** [comment]
Reply:
Author: Pavel Krivanek
Date: 21 September 2016 8:50:46 am
	
Message:
	
If you will remove the comments skipping in the form it is done now, you will be able to evaluate single line with only one " as valid expression. Now it is skipped.

**Comment by VincentBlondeau** [comment]
Reply:
Author: Tudor Girba
Date: 30 September 2016 4:45:49 pm
	
Message:
	
As Pavel mentioned, this is not an issue specific to the Playground. It is the same everywhere Rubric is used.

**Comment by VincentBlondeau** [comment]
Reply:
Author: Nicolai Hess
Date: 30 September 2016 10:18:10 pm
	
Message:
	
Yes, this feature is gone.
We tried to fix case 15345, where this feature made it impossible to evaluate code that has
an $" inside. I tried to fix that but the fix was not good (see case 17491), finally AliakseiSyrel fixed the
implementation to correctly parse code with $", but this only works if the cursor is within the comment too.

**Comment by VincentBlondeau** [comment]
Reply:
Author: Pavel Krivanek
Date: 27 January 2017 10:28:35 am
	
Message:
	
Low priority issue. Not for Pharo 6. The milestone "Later" was set automatically.

**Comment by VincentBlondeau** [comment]
Reply:
Author: Vincent Blondeau
Date: 28 September 2018 5:25:20 pm
	
Message:
	
Issue not solved in Pharo7 - build 1276

**Comment by VincentBlondeau** [comment]
Not fixed

**Comment by guillep** [comment]
Maybe I'm misunderstanding the issue, but this is working:

<img width="162" alt="imagen" src="https://user-images.githubusercontent.com/708322/215172703-267811d4-49b5-4d23-8b45-0db5caad0475.png">
