### ISSUE TITLE
Not mapped shortcut combinaison should do nothing instead of writing the character

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#2916]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/19099
Status: Work Needed
Project: Keymapping
Original Author: Vincent Blondeau
Date: 16 September 2016 1:02:05 pm
	
Description:
	
When typing a shortcut that is not binded (like ALT+I), we expect that no action is thrown. However, the key in the combinaison is still executed (for the example, the shortcut writes i).
 
 In the previous version of Pharo, inspect used to be ALT + I, it is now CTRL + I. As the shortcut learning is not instantaneous, some code is remplaced by i ;)

**Comment by VincentBlondeau** [comment]
Reply:
Author: Pavel Krivanek
Date: 27 January 2017 10:29:09 am
	
Message:
	
Low priority issue. Not for Pharo 6. The milestone "Later" was set automatically.

**Comment by VincentBlondeau** [comment]
Reply:
Author: Vincent Blondeau
Date: 28 September 2018 5:09:17 pm
	
Message:
	
Still in Pharo 7 build 1276 (sha 6c09bd4)

**Comment by VincentBlondeau** [comment]
Still there

**Comment by guillep** [comment]
How does it work on other windows apps? I've seen this previously, but I cannot get a grasp of what really needs to be done.

For example, here on my OSX, in non-pharo app 
 - I type Alt+i and I get ` ` (a space)
 - I type Alt+a and I get `å`.
 - Ctrl combinations are ignored if no shortcut is assigned
 - Cmd combinations are ignored if no shortcut is assigned

For example, here on my OSX, in non-pharo app 
 - I type Alt+i and I get ` ` (a space) => same behavior
 - I type Alt+a and I get `å`. => same behavior
 - Ctrl combinations create strange characters
 - Cmd combinations type the character without the Cmd

it would be good if somebody replicates the same in Windows and Unix

**Comment by guillep** [comment]
From my understanding, it would be enough to ignore Keypress events in OSX if they have a Ctrl or a Cmd. Windows should be the same for Alts (and Ctrls?).

**Comment by VincentBlondeau** [comment]
In Windows:
- ALT + <key> : open the entry in the main app menu
![pR5v9SFtpQ](https://user-images.githubusercontent.com/4706329/79009082-07220100-7b5f-11ea-8f9f-df9a5749ce46.png)
- Ctrl combinations are ignored if no shortcut is assigned
- Win + <key> : windows global shortcuts

Alts events should trigger the main menu bar and Ctrls should not do anything if they are unassigned.
If there is a combination with Ctrl, the behavior is the same than Ctrl. 
If there is a combination with Alt, the behavior is the same than Ctrl.

**Comment by VincentBlondeau** [comment]
Fixed
