### ISSUE TITLE
FileSelectionDialog: remember the last explored directory to start with it for the next selection

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#2917]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/19225
Status: Work Needed
Project: Morphic
Original Author: Vincent Blondeau
Date: 19 October 2016 1:18:25 pm
	
Description:
	
In FileSelectionDialog, the first selected folder is alway the working directory. It will be nice to remember the last explored directory to start with it for the next folder selection.

**Comment by VincentBlondeau** [comment]
Reply:
Author: Nicolai Hess
Date: 20 October 2016 7:00:07 am
	
Message:
	
Looks good, did you test what happens if the lastLocation is not available anymore (because you moved the image to another platform or a network share has been removed)?
On windows it seems to fall back to an empty directory and so the directory selection shows the top level (a list of drives), it would be good if  the directory chooser would start again at the working directory again.

**Comment by VincentBlondeau** [comment]
Reply:
Author: Vincent Blondeau
Date: 21 October 2016 11:06:58 pm
	
Message:
	
You're right, I did not take this into account. A check have to be done if the system is the same or not.

**Comment by VincentBlondeau** [comment]
Reply:
Author: Pavel Krivanek
Date: 27 January 2017 12:06:37 pm
	
Message:
	
Low priority issue. Not for Pharo 6. The milestone "Later" was set automatically.

**Comment by VincentBlondeau** [comment]
Reply:
Author: Vincent Blondeau
Date: 28 September 2018 5:13:12 pm
	
Message:
	
Not fixed in Pharo 7 build 1276 (sha 6c09bd4)

**Comment by VincentBlondeau** [comment]
Not fixed yet

**Comment by guillep** [comment]
I don't think this is the responsibility of the file selection dialog... It looks to me it should depend on the tool. Maybe two tools (in the same image) would want to remember two different locations (thinking for example iceberg and epicea).

Thoughts?

**Comment by VincentBlondeau** [comment]
I think it should be a default in the dialog itself and in the tool for override if necessary.
Anyway, I think that as a first step in the dialog is fine.

**Comment by VincentBlondeau** [comment]
PS: the bot should put a reminder first and then close it

**Comment by VincentBlondeau** [comment]
@PharoProject Can you please reopen this issue?

**Comment by Ducasse** [comment]
We should do a pass on the new file dialog in new tools because it is in spec20 and we can specify special places and it remembers previous ones. So may be we should focus on the spec20 version and let the morphic one. I added esteban so that we talk about it.

**Comment by guillep** [comment]
This should be handled by the new file list.
I'll close the issue.
