### ISSUE TITLE
Simplify DebugSession>>isContextPostMortem:

### ISSUE THREAD

**Issue by dupriezt** [guillep/pharo-core#2927]
```
isContextPostMortem: selectedContext
	"return whether we're inspecting a frozen exception without a process attached"
	| suspendedContext |
	suspendedContext := interruptedProcess suspendedContext.
	suspendedContext ifNil: [ ^ false ].
	(suspendedContext == selectedContext)
		ifTrue: [ ^ false ].
	^ (suspendedContext findContextSuchThat: [:c | c sender == selectedContext]) isNil
```
This method is a tough one to understand.
After looking at it, it looks like all that the 3 last lines are doing is checking that "selectedContext" is not on the context chain of the interruptedProcess.
This can be rewritten in a much simpler fashion:
`^ (suspendedContext hasContext: selectedContext) not`

**Comment by Ducasse** [comment]
Can you ask in the mailing-list to know if someone knows about it?

**Comment by dupriezt** [comment]
@Ducasse Eliot and Max Leske have answered my mail and said they think this improvement would work.
