### ISSUE TITLE
RBScanner isSelector: is wrong

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2936]
RBScanner isSelector: #foo::
>>> true

and foo:: is not a valid selector

**Comment by Ducasse** [comment]
same for 'agr:goo:aa' this is not a valid selector.

**Comment by kasperosterbye** [comment]
Was fixed in #4469. Close this issue :-)

**Comment by Ducasse** [comment]
Thanks Kasper. If you add Fixes: #XXXX in your commit log then when we integrate a PR it will close automatically the issue.

**Comment by kasperosterbye** [comment]
On 5 September 2019 at 19.21.17, StéphaneDucasse (notifications@github.com)
wrote:

Thanks Kasper. If you add Fixes: #XXXX in your commit log then when we
integrate a PR it will close automatically the issue.

Great - will do.
