### ISSUE TITLE
FFIConstantHandleType externalType wrong in 64 bit

### ISSUE THREAD

**Issue by StephanEggermont** [guillep/pharo-core#2938]
externalType
	^ ExternalType unsignedLongLong

works much better in x64

**Comment by StephanEggermont** [comment]
"protocol: #'*UnifiedFFI'"

Integer>>pointer 
	^ (ByteArray new: FFIExternalType pointerSize)
		unsignedLongLongAt: 1 put: self;
		yourself

**Comment by VincentBlondeau** [comment]
@estebanlm @tesonep @guillep : What is missing in the second PR to be integrated?

**Comment by estebanlm** [comment]
this was long time ago integrated
