### ISSUE TITLE
 Cannot extract method using Suggestions menu

### ISSUE THREAD

**Issue by ghost** [guillep/pharo-core#2939]
Hello, 

Im following the seaside tutorial where I have to refractor a long function into some smaller. 

here is a part of the long function: 

```
renderContentOn: html
	| group |
	html
		form: [ html text: 'Name:'.
			html textInput on: #name of: self contact.
			html break.
			html text: 'Email address:'.
			html textInput on: #emailAddress of: self contact.
			html break.
```

So I highlight this part

```
html text: 'Name:'.
			html textInput on: #name of: self contact.
			html break.
```

highligght it , choose suggestions -> extract method and I see this error message which makes no sense

Information
Invalid source to extract - End of statement list encountered

or this one : 

first was send to nill

in the code I do not use any list so I think there is a bug somewhere

**Comment by ghost** [comment]
when I do ctrl-t extract I see the same error 

![afbeelding](https://user-images.githubusercontent.com/47429430/54708537-e2b64980-4b43-11e9-9279-79dc8853a350.png)

**Comment by macta** [comment]
I can reproduce this in a 7.0.2 image, its not a seaside issue. The same operation does work if you use the "Source Code" - extract method  menu item.

Looking quickly . - the variable "selectionPreviousHighligth" (sic) - is not being set, and there are 3 places using this. (but many subclasses, of which some use this var too - nasty).  Not even sure why this variable is used as its simply "self selectedInterval" ? 

Making the change to SugsAbstractContext>>#selectedStatements to use "self selectedInterval" fixes this error, but will need some careful reasoning to understand what that "selectionPreviousHighligth" variable is for.

**Comment by Ducasse** [comment]
Thanks! 
We will manage it https://github.com/juliendelplanque/Enjoliveur/issues/20

**Comment by ghost** [comment]
Any news when this is solved. Im eager to learn seaside ?

**Comment by guillep** [comment]
I've tested it in Pharo90 and it seems fixed. If somebody can still reproduce it, please update the instructions and reopen.
