### ISSUE TITLE
OmDeferrerTest>>testExecuteOnceAfterSchedulingMultipleTimes fails

### ISSUE THREAD

**Issue by StephanEggermont** [guillep/pharo-core#2951]
There is no reason to assume that test can work, it strongly depends on the load on the machine.

**Comment by VincentBlondeau** [comment]
https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-2940/4/pipeline/

**Comment by MarcusDenker** [comment]
merged
