### ISSUE TITLE
[ICEBERG]Diff titles should be consistently specified

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#2953]
i.e. : Title of the diff windows named "3c65f47 to cceac76" implies that the left pane is 3c65f47  version and right is cceac76 version. But is is not the case....

![image](https://user-images.githubusercontent.com/4706329/54749157-045f1180-4bd4-11e9-8c33-11216671e5ef.png)

**Comment by VincentBlondeau** [comment]
Not fixed

**Comment by guillep** [comment]
I moved the issue to https://github.com/pharo-vcs/iceberg/issues/1362
