### ISSUE TITLE
[ICEBERG]Revert changes menu item name should indicate what it does

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#2954]
Does it revert from the first commit of the diff? to the second? Could we merge it ? Are the changes are integrated directly? Or whatever?
(it seems to apply the old commit to the current image version...)

![image](https://user-images.githubusercontent.com/4706329/54749314-720b3d80-4bd4-11e9-8194-c234097d9978.png)

**Comment by VincentBlondeau** [comment]
PS: this may need multiple PRs for the separates issues ;)

**Comment by VincentBlondeau** [comment]
@StephanEggermont

**Comment by StephanEggermont** [comment]
There seems to be a branch missing to merge to

**Comment by VincentBlondeau** [comment]
Not fixed

**Comment by guillep** [comment]
Migrated to https://github.com/pharo-vcs/iceberg/issues/1363
