### ISSUE TITLE
[Refactoring] CTRL+T Menu should appears in the contextual menu in Calypso

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#2961]
see gif: 

![raUXWSFuCb](https://user-images.githubusercontent.com/4706329/54775068-7738ae80-4c0d-11e9-934a-7fe1ff41bcae.gif)

**Comment by VincentBlondeau** [comment]
and in:
```
ClySugsMethodContext>>#selectedTemporaryVariables
	selectedNode isSequence ifFalse: [ ^#() ].
	selectedNode temporaries ifEmpty: [^OrderedCollection new].
	^ ((selectedNode temporaries at: 1) containedBy: selectionPreviousHighligth )
		ifTrue: [ selectedNode temporaries ]
		ifFalse: [#()].
```
selectionPreviousHighligth  should be replaced by selectionPreviousHighlight

**Comment by dionisiydk** [comment]
Suggestions are deprecated in calypso.
Sadly I did not found how remove this menu.
Can you check extract method from Source code menu?

чт, 21 мар. 2019 г., 18:16 Vincent Blondeau <notifications@github.com>:

**Comment by VincentBlondeau** [comment]
Alright.... Then the menu item "suggestion" should display the menu that appears in CTRL+T
![image](https://user-images.githubusercontent.com/4706329/54820381-4608be80-4c9f-11e9-92c0-8c1f7c94e4fe.png)

**Comment by dionisiydk** [comment]
No, suggestion menu should be removed from calypso. The Source code menu is
replacement for it. It performs same role but it's done with Commander like
any other commands in browser

пт, 22 мар. 2019 г., 11:37 Vincent Blondeau <notifications@github.com>:

**Comment by VincentBlondeau** [comment]
Sorry but I do not understand. What do you call the source code menu?
And ok the actual suggestion menu should be removed, but the CTRL+T menu should be also accesssible by mouse click or a button in the GUI

**Comment by dionisiydk** [comment]
In context menu there are two submenus: "Source code" on the top of list and next item Suggestions.
What I am trying to explain is that Source code menu is replacement for Suggestions. Source code menu is already activated by cmd+t instead of old suggestions. So we only need to remove suggestions submenu. I did not find the way how to do it only for Calypso browser. It is defined globally by text editor.

**Comment by dionisiydk** [comment]
These two items are shown in your gif
