### ISSUE TITLE
[Debugger]text of the popup debugger can be selected

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#2962]
And it is quite annoying because you cannot open a bigger debugger when you click on it ...
![EKbjLHQSne](https://user-images.githubusercontent.com/4706329/54775364-165da600-4c0e-11e9-85a3-1799e8dd6465.gif)

**Comment by pavel-krivanek** [comment]
This is already fixed in the latest Spec development versions.

**Comment by estebanlm** [comment]
yup :)

**Comment by VincentBlondeau** [comment]
But I guess that is not already integrated?

**Comment by estebanlm** [comment]
no, but keeping the issue open is just noise :)
We will integrate a new version of Spec after PharoDays.
