### ISSUE TITLE
[Debugger]Fuel out stack happens silently

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#2963]
The file is just empty...
![DO23bQwV9V](https://user-images.githubusercontent.com/4706329/54776195-e1eae980-4c0f-11e9-901d-7ccc76d9f641.gif)

**Comment by StephanEggermont** [comment]
Caused by #2789

**Comment by fortizpenaloza** [comment]
Which version of Pharo are you using @VincentBlondeau ? I'm found the same issue on 7.0.3

**Comment by VincentBlondeau** [comment]
It is actually working under Pharo 8 and 7, but it happens silently... Can a toast be added?

**Comment by fortizpenaloza** [comment]
Good idea, but I would be great to have the stack serialization working first and then add the toast

**Comment by VincentBlondeau** [comment]
It is working and saved into the image folder. Could you check on your side?

**Comment by guillep** [comment]
So an action to fix this would be to add a toast/Growl (see GrowlMorph).

**Comment by MarcusDenker** [comment]
The new debugger has this not yet, I close this issue and will open an issue for that in the newtools repo

**Comment by MarcusDenker** [comment]
I added: https://github.com/pharo-spec/NewTools/issues/148
