### ISSUE TITLE
[ICEBERG]Message when openning an branch for an issue should be improved

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#2965]
The pic talks by itself
![image](https://user-images.githubusercontent.com/4706329/54777226-25465780-4c12-11e9-9aae-afe99157dd03.png)

**Comment by jecisc** [comment]
Are you on the right remote?

**Comment by MarcusDenker** [comment]
the "remote" field is a drop down (not visible). You need to select the pharo repository there.

Yes, that needs to be simplified and improved.

**Comment by estebanlm** [comment]
yes, I don't know why you do not see the dropdown, but this is not an error :)
and @MarcusDenker, I don't know how this could be simplified more (pick remote, type issue number) other than querying for the open issues, which would take time.

**Comment by VincentBlondeau** [comment]
Maybe adding a message that says: "you may want to check the other remotes?"

**Comment by astares** [comment]
What about using "INVALID-ISSUE-FOR-REMOTE" instead of "INVALID_ISSUE" so one could at least have an idea it might be due to the selected remote...

**Comment by VincentBlondeau** [comment]
Good idea! 
Can the issue be reopenned? please?

**Comment by MarcusDenker** [comment]
Just got a mail from another new commuter (in german) who did not know what to do at this step. It is not clear that this is a drop=down menu.

**Comment by guillep** [comment]
Moved to https://github.com/pharo-vcs/iceberg/issues/1364
