### ISSUE TITLE
[Iceberg]Is there an option for rebasing?

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#2966]
When the Pharo8.0 branch is ahead of you and you want to catch the train. Nice feature to have to keep up with the fast progresses that Pharo is making

**Comment by VincentBlondeau** [comment]
Not fixed nor integrated in the image

**Comment by guillep** [comment]
I think this is an issue for the iceberg issue tracker, and more than an issue is a feature request :).
Let's keep the discussion in Iceberg's issue tracker

**Comment by VincentBlondeau** [comment]
Then it is reopen in https://github.com/pharo-vcs/iceberg/issues/1361
