### ISSUE TITLE
MNU when dropping a fileout file on the image

### ISSUE THREAD

**Issue by StephanEggermont** [guillep/pharo-core#2974]
When trying to fix #2969 I tried fling in by dragging a fileout on the image (Windows, Pharo 8/64 build 164), MessageNotUnderstood: ZnBufferedWriteStream>>name pops up
[TaskbarMorph.st.txt](https://github.com/pharo-project/pharo/files/2995563/TaskbarMorph.st.txt)
[PharoDebug.log](https://github.com/pharo-project/pharo/files/2995565/PharoDebug.log)
[Debugger-Stack-ZnBufferedWriteStream-2019-03-22-990.zip](https://github.com/pharo-project/pharo/files/2995567/Debugger-Stack-ZnBufferedWriteStream-2019-03-22-990.zip)

**Comment by StephanEggermont** [comment]
And the stream also DNU edit

**Comment by StephanEggermont** [comment]
ExternalDropHandler and DefaultExternalDropHandler need to be rewritten to use fileReferences in addition to the streams

**Comment by VincentBlondeau** [comment]
And tests should be added too :)

**Comment by StephanEggermont** [comment]
Caused by #2789

**Comment by VincentBlondeau** [comment]
Issue indeed solved.
