### ISSUE TITLE
Problem when you read an old non utf8 mcz

### ISSUE THREAD

**Issue by Alisu** [guillep/pharo-core#2975]
When you try to read an mcz in iso-latina the #contentsForMember: member method is bugged.
It works with a String but got a Stream instead.

**Comment by VincentBlondeau** [comment]
Could you give an example that can be easily reproduced?

**Comment by Alisu** [comment]
When i try to load this for example.
repository := MCHttpRepository
    location: 'http://www.squeaksource.com/MutationTesting'
    user: ''
    password: ''.

versionInfo := repository versionInfoFromVersionNamed: 'MutationTesting'.
version := repository versionWithInfo: versionInfo.

version snapshot

**Comment by guillep** [comment]
Yes, this problem is there in Pharo 7 and Pharo8. We are working on a solution.
