### ISSUE TITLE
New class dialog shows comment tab for package (and not new class)

### ISSUE THREAD

**Issue by fuhrmanator** [guillep/pharo-core#2979]
Steps to get to this issue:
1. select a package and an existing class.
2. select the class again (effectively selecting NO classes in the package).
3. Two tabs appear in the browser: `Comment` and `New class`

Clicking on the comment tab, I see the comments for the package (and not a template for comments of a new class). This is confusing, especially for new Pharo users.

Saving the class changes the contents of the `Comment` tab to have the standard template for a class, e.g. "Please comment me using the following template...".

**Comment by dionisiydk** [comment]
In that case the comment tab is a package comment. It is shown only when no
class is selected.
When class is selected the tab shows the class comment

пт, 22 мар. 2019 г., 10:08 C. Fuhrman <notifications@github.com>:

**Comment by fuhrmanator** [comment]
> In that case the comment tab is a package comment. It is shown only when no class is selected. When class is selected the tab shows the class comment 

OK, I realize now I can remove the comment tab by clicking (again) on the package to deselect it. However, that takes the scope out of the package and gives me a `New class` tab with a template for no package (not even sure that makes sense). 

As I say, it's confusing to new people in Pharo (of which I am still one, although at some point I won't be able to argue this...):

- You see a tab for a comment for a package when you're creating a class. 
- Once the class is created, the contents of the comment tab are changed into a comment-for-class tab (in the same space) without giving the user many clues that that tab is now for the class.  

For new people there's a "create class" user story, but there's no (more?) a create class command (except for entering text into the tab which appears with a comment tab that is for the package). I remember it being an explicit command before (right-clicking in the list of classes?). Clicking in Pharo 7.0.2 I can only find a "create subclass" command if I right-click in the class list. In Pharo 6 there was an "Add class..." right click commands.

As a professor who wants to get students using Pharo (when they are used to IDEs like Eclipse, JetBrains, etc.) it is a big struggle because of these changes.
