### ISSUE TITLE
[Rubric] setTextAndAccept: is missing to RubPluggable

### ISSUE THREAD

**Issue by StephanEggermont** [guillep/pharo-core#2980]
MorphicTextInputFieldAdapterTest is red
Be more precise.

#testChangeWidgetTextUpdatesPresenter is failing

**Comment by MarcusDenker** [comment]
We should put them as expected failures... the CI needs to be green

**Comment by StephanEggermont** [comment]
No. This was merged 8 days ago and shouldn't have been if there was no time to fix the code the next day.
This is simply unstable code, and we can't have text editing not working for a week

**Comment by StephanEggermont** [comment]
And, yes, CI needs to be green

**Comment by StephanEggermont** [comment]
This is one
RubPluggableTextFieldMorph
"protocol: #'*Spec-MorphicAdapters'"

setTextAndAccept: aText
	self
		setText: aText;
		hasUnacceptedEdits: true;
		accept

**Comment by StephanEggermont** [comment]
There is no support for maxlength in Rubric yet

**Comment by MarcusDenker** [comment]
see #2813

**Comment by MarcusDenker** [comment]
I have added a #skipOnPharoCITestingEnvironment to these two tests in the other issue:

MorphicTextInputFieldAdapterTest testChangeWidgetTextUpdatesPresenter
MorphicTextInputFieldAdapterTest testMaxLengthIsSetInWidget

they need to be removed when the tests are green.

**Comment by StephanEggermont** [comment]
Caused by #2789
