### ISSUE TITLE
Add a website with all the infos about installed bots

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#2984]
We need a page on Pharo.org with all the infos about the installed bots.

Work In Progress
Prevent merging of Pull Requests with "WIP" in the title
https://github.com/marketplace/wip
No Response
Closes Issues where the author hasn't responded to a request for more information
If the tag more-information-needed is set and no answer provided, issue is closed in 14 days.
https://probot.github.io/apps/no-response/
Request Info
Requests more info on issues and pull requests with the default title or an empty body.
it sets the more-information-needed flag to trigger the No Response Bot.
https://probot.github.io/apps/request-info/
Stale
Close stale Issues and Pull Requests
https://github.com/probot/stale
Issues: daysUntilStale: 240, daysUntilClose: 60
Pulls: daysUntilStale: 20, daysUntilClose: 10

and:
https://probot.github.io/apps/reminders/
	Use the /remind slash command to set a reminder on any comment box on GitHub and you'll get a ping about it again when the reminder is due.
	Use any form of /remind me [what] [when], such as:

	/remind me to deploy on Oct 10
	/remind me next Monday to review the requirements
	/remind me that the specs on the rotary girder need checked in 6 months

**Comment by jecisc** [comment]
Or maybe a section in the README?

**Comment by MarcusDenker** [comment]
Polls
	Automatically create polls in GitHub issues.
	/polls Option1 'Option 2' "Option 3"
       https://github.com/apps/polls

**Comment by bencoman** [comment]
Maybe here https://github.com/pharo-project/pharo/blob/Pharo8.0/CONTRIBUTING.md

<blockquote><img src="https://avatars3.githubusercontent.com/u/1838382?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">pharo-project/pharo</a></strong></div><div>The Sources for Pharo. Contribute to pharo-project/pharo development by creating an account on GitHub.</div></blockquote>

**Comment by MarcusDenker** [comment]
I for now added it to the wiki https://github.com/pharo-project/pharo/wiki/Issue-Tracker-Bots
and put a link to that in the CONTRIBUTING.

<blockquote><img src="https://avatars3.githubusercontent.com/u/1838382?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">pharo-project/pharo</a></strong></div><div>The Sources for Pharo. Contribute to pharo-project/pharo development by creating an account on GitHub.</div></blockquote>
