### ISSUE TITLE
update CONTRIBUTING.md for Pharo8

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#2986]
The CONTRIBUTING file needs to be updated for Pharo8:

https://github.com/pharo-project/pharo/blob/Pharo8.0/CONTRIBUTING.md

We should make sure that it is in sync with http://pharo.org/contribute

**Comment by MarcusDenker** [comment]
First pass done.

Next: it should be the same content as 

http://pharo.org/contribute-report-bug
http://pharo.org/contribute-propose-fix



<blockquote><img src="/files/favicon.ico" width="48" align="right"><div><strong><a href="http://pharo.org/contribute-report-bug">Pharo - Contribute - Report a bug</a></strong></div></blockquote>
<blockquote><img src="/files/favicon.ico" width="48" align="right"><div><strong><a href="http://pharo.org/contribute-propose-fix">Pharo - Contribute - Propose a fix</a></strong></div></blockquote>

**Comment by MarcusDenker** [comment]
This has been done

**Comment by hilaire** [comment]
The information about contributing fix in P8 does not align with the reality (at least with my experience on contributing fix, I am not exactly sure what I am doing, but it involves different steps than the ones described in the page referenced bellow).

Please update the information at https://github.com/pharo-project/pharo/wiki/Contribute-a-fix-to-Pharo

It is crucial to make comfortable newbie contributors.

<blockquote><img src="https://repository-images.githubusercontent.com/64123480/451beb80-d08b-11e9-9ade-21d166d787d9" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">pharo-project/pharo</a></strong></div><div>Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk. - pharo-project/pharo</div></blockquote>

**Comment by Ducasse** [comment]
Hi hilaire

I read it again and this is really close to reality. So could you spot what did not work for you.
May be one paragraph is missing on the fact that we do not need to manually sync our fork. 
I will read it carefully in the train and see what I can improve. 

Stef

**Comment by hilaire** [comment]
step 3 and 4 are different for me.
I have several steps to conduct not documented: commit, push, not sure where, I guess in my forked repo.

**Comment by hilaire** [comment]
Here the steps I must follow:
1. commit
2. new branch for issue
3. push
4. create a pull request

my steps 1 and 3 are not explained in the doc.

**Comment by SergeStinckwich** [comment]
Contributing.md has been updated. Can we close this ?

**Comment by Ducasse** [comment]
Oki thanks!
