### ISSUE TITLE
provide standard class comment for tests

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#2987]
Tests without comments are now shown with a ! in the Browser

We now add lots of comments of the kind 

"this is a test class".

==> add this comment as the default comment in TestCase class

**Comment by MarcusDenker** [comment]
/polls Option1 'I like it' "Bad Idea"

**Comment by dionisiydk** [comment]
That's good

**Comment by MarcusDenker** [comment]
lets try the voting bot:

/polls "I like it" 'bad Idea'
