### ISSUE TITLE
Pharo Code of Conduct

### ISSUE THREAD

**Issue by SergeStinckwich** [guillep/pharo-core#2989]
A lot of open-source project got a code of conduct document. At the moment, there is nothing for Pharo. Why do we need a code of conduct: https://opensource.guide/code-of-conduct/

We can create one here from this template: https://github.com/pharo-project/pharo/community/code-of-conduct/new?template=contributor-covenant

**Comment by Ducasse** [comment]
Ok propose something. We had a zen description but not a code of conduct

**Comment by SergeStinckwich** [comment]
There is a template here : https://github.com/pharo-project/pharo/community/code-of-conduct/new?template=contributor-covenant 

<blockquote><img src="https://github.githubassets.com/images/modules/open_graph/github-logo.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 31 million people use GitHub to discover, fork, and contribute to over 100 million projects.</div></blockquote>
