### ISSUE TITLE
When commenting a trait, the change does not appear in Iceberg diff

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#2998]
To reproduce:
1. Ensure your package is not dirty in Iceberg.
2. Change the comment of a trait.
3. Try to commit your change in Iceberg.

When reaching 3. you will not be able to commit your change nor to see the related diff.

**Comment by Alisu** [comment]
Is there still a bug or can someone close it ?

**Comment by juliendelplanque** [comment]
It has been fixed in https://github.com/pharo-vcs/iceberg/pull/1223, I close.
