### ISSUE TITLE
Question: who does the "cdlm added the review  label"

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#3004]
There is something adding review labels automatically.... where is that configured?

**Comment by cdlm** [comment]
Not me directly, that's for sure… Most probably some CI script is using either my credentials or a token, butI was trying to check if we have a build script on jenkins but can't seem to find where any of the jobs or pipelines are defined in there 😞

**Comment by estebanlm** [comment]
no, is waffle.
@cdlm you entered first so it takes your name.

**Comment by MarcusDenker** [comment]
waffle?

**Comment by MarcusDenker** [comment]
This? https://waffle.io
With a heavy heart, we are announcing today that we will be closing our doors at Waffle on May 16, 2019. 

<blockquote><img src="https://www.waffle.io/marketing-assets/images/waffle-yellow-on-blue.png" width="48" align="right"><div>Waffle.io</div><div><strong><a href="https://waffle.io">Developer-first Project Management for Teams on GitHub | Waffle.io</a></strong></div><div>Waffle.io tracks your GitHub issues and pull requests with an automated workflow.</div></blockquote>

**Comment by estebanlm** [comment]
yes, that

**Comment by estebanlm** [comment]
is (was) a tool to manage the issue tracker (something like projects, but better in a way/worst in another)

**Comment by MarcusDenker** [comment]
I added it to https://github.com/pharo-project/pharo/wiki/Issue-Tracker-Bots

<blockquote><img src="https://avatars3.githubusercontent.com/u/1838382?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">pharo-project/pharo</a></strong></div><div>The Sources for Pharo. Contribute to pharo-project/pharo development by creating an account on GitHub.</div></blockquote>
