### ISSUE TITLE
Morphic / Checkbox enable / disable 

### ISSUE THREAD

**Issue by 570gina** [guillep/pharo-core#3021]
checkboxButtonSelectedDisabledFillStyleFor: aCheckboxButton
	"Return the selected disabled checkbox button fillStyle for the given button."	
	^self checkboxButtonDisabledFillStyleFor: aCheckboxButton

A disable checked checkbox is rendering an unchecked checkbox instead.

**Comment by pavel-krivanek** [comment]
https://github.com/pharo-spec/Spec/issues/233
