### ISSUE TITLE
Adding Debugger Tests

### ISSUE THREAD

**Issue by dupriezt** [guillep/pharo-core#3025]
I wrote some additional tests for the debugger and will make a pull request with them to add them to pharo.

**Comment by dupriezt** [comment]
Edited top comment to add information

**Comment by MarcusDenker** [comment]
I will change the text of the bot to include: "Note: I am not a very intelligent bot, I can only react to new comments. Please add a comment for me after you editi the body or title"

**Comment by dupriezt** [comment]
@MarcusDenker there's a typo in the text you wrote (an "i" after "edit")

**Comment by MarcusDenker** [comment]
the committed version is now:

 Note: I am not a very intelligent bot, I can only react to new comments. Please add a comment for 
 me if you update the body or title.

**Comment by Ducasse** [comment]
Thanks thomas. if you have Fixes: #3026 in your PR, when the PR is integrated it closes automatically the issue and we do not have to do it manually.
