### ISSUE TITLE
We should improve the emergency evaluator

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3035]
The last modified method is not logged correctly. 
and we should improve this logic because when working on texteditor and related the emergency evaluator can save us.

**Comment by Ducasse** [comment]
I fixed the recentMessageList but it got again broken and yes we should really improve the emergency evaluator because it can save our day!

**Comment by Ducasse** [comment]
Steven can you help on this one.

**Comment by StevenCostiou** [comment]
Ok. This tool should be completely redone, but for now we can make it better bit by bit until we provide a real tool. 
What are the most urgent improvements? 
The recent message list?

**Comment by StevenCostiou** [comment]
The bug is not reproducible, at least I can't.
Doing revert correctly reverts the last modified method.
The tool should be improved, but that issue should be closed unless someone can reproduce and tell me how.

**Comment by Ducasse** [comment]
We can close the issue but it would be really nice to improve the emergency evaluator.

**Comment by Ducasse** [comment]
I was thinking that what we need is a kind of minimal textual way to interact.
