### ISSUE TITLE
On Mac selecting "About" option form the menu - About window will not close

### ISSUE THREAD

**Issue by SergeStinckwich** [guillep/pharo-core#3036]
See details here: https://github.com/pharo-project/pharo-launcher/issues/318

**Comment by demarey** [comment]
yes, this issue is related to the VM App for OS X. thanks

**Comment by demarey** [comment]
With Pablo, we determined that this problem comes from the deactivation of the events for windows that are not the main window.
See commit https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/b6cb1927f39786de37d829a8677fe9cac2693a94

**Comment by SergeStinckwich** [comment]
We can close I think because this has been fixed in last VM version of Pharo.

**Comment by SergeStinckwich** [comment]
No this is not fixed ? Any news if the fix will be used in Pharo VM also ?

**Comment by guillep** [comment]
This should be fixed by the idle VM. Let's check it later

**Comment by SergeStinckwich** [comment]
This is fixed for Pharo images, because there is no more about menu in last Pharo version, but the problem is still there for PharoLauncher, if you click ``about PharoLauncher``.

**Comment by MarcusDenker** [comment]
For the launcher, there is an issue here: https://github.com/pharo-project/pharo-launcher/issues/318

I close this one
