### ISSUE TITLE
String>>withUnixLineEndings shouldn't modify the the original string

### ISSUE THREAD

**Issue by tinchodias** [guillep/pharo-core#3048]
Ronie Salgado reported this issue in pharo-dev mailing list 10 days ago:

> Hi,
> 
> I just noticed that String >> withUnixLineEndings modifies the the original string, at least when the string only has cr, and not crlf. For example, try the following (in Pharo 7) in a Playground:
> 
> original :='asa' , String cr , 'asa'.
> newString := original withUnixLineEndings.
> original at: 4.
> 
> Best regards,
> Ronie

**Comment by aranega** [comment]
@tinchodias we checked very quickly, and we are not sure of what should be the behavior of the `#withUnixLineEnding` method. Indeed, currently, the modification is made in-place, but there's nothing in the documentation of the method that states it should not. 
What would be the right behavior for this method?

**Comment by tinchodias** [comment]
Hi @aranega, thanks for answering.

I checked briefly if there was something in [Pharo with Style](https://github.com/SquareBracketAssociates/Booklet-PharoWithStyle) to reference but didn't find it quickly.

One concrete argument is that other selectors that begin with with don't mutate self. At least, when I briefly inspected in Pharo 8 didn't find any (I used`SystemNavigation default allMethods select: [ :each | each selector beginsWith: 'with' ]`).

Trying to be less concrete (more abstract), I guess the rule is that methods that begin with prepositions don't mutate. Often mutators without arguments begin with 'be', for example `ZnClient>>beBinary`, and actually don't remember other beginnings for this case.

So... I'd propose to either rename to `beUnixLineEndings` or to make `withUnixLineEnding` answer a new string. I vote for 2nd one.

**Comment by tinchodias** [comment]
@ronsaldo

**Comment by ronsaldo** [comment]
I also vote for the copying behavior. For me it makes more sense.

**Comment by svenvc** [comment]
I vote for the second option

#withXYZ: should copy
