### ISSUE TITLE
Opening 32bits Pharo 8 image raises primitive failed error

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#3053]
Need someone to be able to reproduce to be sure this problem is not local to my machine...

## Overview
<img width="980" alt="Capture d’écran 2019-03-29 à 10 00 12" src="https://user-images.githubusercontent.com/8260456/55221375-9afd8500-5209-11e9-879e-43446b0bd319.png">

## OS details
```bash
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.6 (16G1917)
      Kernel Version: Darwin 16.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Julien’s MacBook Pro
      User Name: Julien (julien)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 12:47

```

## Pharo version
Image: Pharo8.0-SNAPSHOT.build.190.sha.485a5eb.arch.64bit

From Pharo launcher, I can not find a Pharo 8 VM for 32 bits images (see screenshot below)
<img width="714" alt="Capture d’écran 2019-03-29 à 10 05 51" src="https://user-images.githubusercontent.com/8260456/55221676-4f97a680-520a-11e9-92d2-0ea45563e421.png">

**Comment by GDayne** [comment]
I am able to reproduce this problem as well. I also have a 64bits system.

**Comment by akgrant43** [comment]
Can you copy the text from the System Reporter Image and VM General pages and PharoDebug.log (delete it first and reproduce the problem so it is a clean log).

Thanks,
Alistair

**Comment by bencoman** [comment]
> I also have a 64bits system.

By "system" do you mean the OS?  I don't believe any 32-bit MS Windows systems exist anymore.

The starting question (@estebanlm) is whether Windows 32-bit VM will be supported for Pharo 8?

**Comment by guillep** [comment]
Hi @bencoman I think both of them are on MacOS by reading the comments

**Comment by bencoman** [comment]
ahh yes, you are right.  My perception was biased by getting the same error myself with Windows Pharo 8 32-bit Image.

**Comment by guillep** [comment]
This seems related to the file attributes plugin. @juliendelplanque, @GDayne, @bencoman could you test with the latest VM or with the VM build a838346 from http://files.pharo.org/vm/pharo-spur32/?

I've tested it on my machine and it works.

Thanks!

<blockquote><img src="/_h5ai/client/images/app-16x16.ico" width="48" align="right"><div><strong><a href="http://files.pharo.org/vm/pharo-spur32/">index · styled with h5ai 0.22.1 (http://larsjung.de/h5ai/)</a></strong></div><div>index styled with h5ai 0.22.1 (http://larsjung.de/h5ai/)</div></blockquote>

**Comment by akgrant43** [comment]
Also, open up the debugger and let us know exactly what is being passed to File class>>exists:
