### ISSUE TITLE
Applying automatic code transformation for "guard clause critic" removes method comment

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#3055]
When I apply the automatic code transformation for "guard clause critic", it removes method comment.

Here is how to reproduce the issue:

1. Create `DummyObject` class
2. Add `#methodToRefactorWithGuardClause` method with source code:
```smalltalk
methodToRefactorWithGuardClause
	"This comment will be removed by refactoring engine."
	1 + 1 = 2
		ifTrue: [ 
			'Hello' inspect.
			'world' inspect ].
```

This method will show the quality assistant critic "Replace single branch conditional with guard clause".

<img width="860" alt="Capture d’écran 2019-03-29 à 10 19 53" src="https://user-images.githubusercontent.com/8260456/55222448-3859b880-520c-11e9-89dc-b5b55b5f54f4.png">

If you click the automatic repair button of the critic, it correctly transform the code but removes the class comment leading to the following method:

```smalltalk
methodToRefactorWithGuardClause
	1 + 1 = 2
		ifFalse: [ ^ self ].
	'Hello' inspect.
	'world' inspect
```

**Comment by juliendelplanque** [comment]
Bump.

**Comment by MarcusDenker** [comment]
This is caused by https://github.com/pharo-project/pharo/issues/5818
