### ISSUE TITLE
Each assert like method in TestRunner should have the dual deny method

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#3064]
Some assert methods do not have their dual deny method.
It should be the case.
With @GDayne we looked and summarise what should be done:

| Assert method  |  Dual deny method |
|---|---|
| `#assert:`  | `#deny:`  |
| `#assert:closeTo:`  | /  |
| `#assert:description:`  | `#denyDescription:`  |
| `#assert:description:resumable` | `#deny:description:resumable` |
| `#assert:equals:` | `#deny:equals:` |
| `#assert:identicalTo:` | `#deny:identicalTo:` |
| `#assertCollection:equals:` | `#denyCollection:equals:` |
| `#assertCollection:hasSameElements:` |  / |
| `#assertCollection:includesAll:` | / |
| `#assertEmpty:` | `#denyEmpty:` |

"/" means the dual does not exist.

Our proposal is to add these missing methods:

- `#deny:closeTo:`
- ~`#denyCollection:hasSameElements:`~ In fact this one is useless, seem comment below.
- `#denyCollection:includesAll:`

Additionally, we propose to add these two methods which can be useful:

- `#assert:closeTo:precision:`
- `#deny:closeTo:precision:`

**Comment by juliendelplanque** [comment]
While implementing this, we realised that in fact adding `#denyCollection:hasSameElements:` makes no sense because it is juste checking that the two collections are different. So we will not add this one.

**Comment by juliendelplanque** [comment]
Bump.

**Comment by MarcusDenker** [comment]
all done
