### ISSUE TITLE
Cleanup unused publicTest pragma in FileReferenceTest

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#3065]
Check senders of publicTest and you will find a few tests tagged with
a pragma: 

      <publicTest>

Why is this? Seems only used in FileReferenceTest and still unused.

Should we remove it?

**Comment by MarcusDenker** [comment]
yes, there is already an issue for that...

**Comment by MarcusDenker** [comment]
is is https://github.com/pharo-project/pharo/issues/2685

**Comment by astares** [comment]
@MarcusDenker 

Ah OK - how will this be handled?

Should I close this one then, is it tagged as duplicated or can we merge them?

**Comment by MarcusDenker** [comment]
sadly there is no duplicate handling in GitHub... there are plugins (e.g. https://reporanger.com).
For now we just add a comment and close it (duplicate of #2685)

<blockquote><div><strong><a href="https://reporanger.com/">Ranger — A GitHub bot that eases the burden of repository maintainers</a></strong></div><div>A GitHub bot that eases the burden of repository maintainers</div></blockquote>

**Comment by astares** [comment]
Duplicate of  #2685
