### ISSUE TITLE
Float>>#closeTo: does not use Float>>epsilon as default precision.

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#3067]
This is odd, it uses a magic constant `0.0001` instead.

```smalltalk
Float>>#closeTo: num
 	"Tell whether the receiver and arguments are close from each."
	
	^ self closeTo: num precision: 0.0001
```

But the comment of Epsilon class variable in Float is  "Defines precision of mathematical functions" and is set to `Epsilon := 0.000000000001.` in `Float>>#initialize`.

So, I think Float>>#closeTo: should use Epsilon but it will be a non-retrocompatible change.

**Comment by Ducasse** [comment]
We should fix it

**Comment by SergeStinckwich** [comment]
In fact there is two epsilon defined by Float:
- Epsilon, define as a class variable in ``Float class>> initialize`` with a value of 0.000000000001
- epsilon as a class method that returns : 2^−52 ≈ 2.22e-16

There is in fact many definition of epsilon: 
https://en.wikipedia.org/wiki/Machine_epsilon 

Apparently ``Epsilon`` is used only in the implementation of ln, sin, arcTan, exp and sqrt when the primitive fails.

**Comment by SergeStinckwich** [comment]
0.001 is used in different places:
- ``NumberParserTest>>testSqueezingOutNumbers``
- ``TestAsserter class>>defaultPrecisionsForCloseToComparison``
- ``Float>>closeNum: num``

0.000000000001 is used only in ``Float>>initialize``
