### ISSUE TITLE
ComputedSlots break accessor generation

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#3072]
When using the ComputedSlots in a class

```Smalltalk
Object subclass: #Person
	slots: { #name. #firstName. #fullName => ComputedSlot with: [ :obj | obj firstName asString , ' ' , obj name asString ] }
	classVariables: {  }
	package: 'Simple-Example'
```

and then use the "generate accessor" functionality

@MarcusDenker
Implementing a  "createRefactoring: variableRefactoringClass for: declarationClass" seems necessary - to at least allow to generate the getter.

**Comment by MarcusDenker** [comment]
#createRefactoring:for: could just be moved up to Slot

**Comment by MarcusDenker** [comment]
I added: https://github.com/pharo-ide/Calypso/issues/482

**Comment by dionisiydk** [comment]
It is better to improve refactorings to avoid this kind of methods at all. And we need to do this anyway to support more complex changes than simple accessors. Now rename, push up/down refactorings will break slot type: target class will include new slot as a simple instance variable. And maybe push up/down needs more advanced logic to move hidden base variable for complex slots.

So currently we have parallel hierarchy of refactorings for each kind of variable: instance variable and class variable. It was good solution at the time when there were no first class variables. But now we can easily unify refactorings by delegating logic to those variables. At the end It should be single hierarchy and methods from this issue will not be needed.

**Comment by MarcusDenker** [comment]
Pushing up the method fixes it. I added the note of Dennis to the backlog.
