### ISSUE TITLE
Review testIndexOfSubCollectionStartingAtIfAbsent

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#3080]
testIndexOfSubCollectionStartingAtIfAbsent for SortedCollectionTest seems already equally coded in Trait
(but with different formatting)

**Comment by astares** [comment]
Same for 

 testKeyAtIdentityValueIfAbsent
 testIncludesKeyLocalyDefined

**Comment by MarcusDenker** [comment]
fix for Pharo 8 has been merged
