### ISSUE TITLE
Code Completion tool registration is commented

### ISSUE THREAD

**Issue by dupriezt** [guillep/pharo-core#3081]
In NECController class
![image](https://user-images.githubusercontent.com/32486709/55233864-0fe0b700-522a-11e9-87fd-024ac100310f.png)
The line responsible for the registration of the code completion tools was commented, which prevents a code-completion-related setting from getting a proper default value. This seems responsible for issue #3040

**Comment by dupriezt** [comment]
Probably linked to why the registration line was commented: #2943

**Comment by Ducasse** [comment]
There is not such registration to a global place. Such global place should be queried anymore!
Now each text editor can be configured and a default can be set for all the future text editors.
