### ISSUE TITLE
TAssertable should be sync with TestAsserter?

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#3083]
It seems out of sync.

**Comment by juliendelplanque** [comment]
I'll do it.

**Comment by SergeStinckwich** [comment]
This issue is tag a simple issue for beginners, but I don't understand what is problem ... Should we use the TAssertable to define TestAsserter ? Can you elaborate a bit more.

**Comment by pavel-krivanek** [comment]
We should not use TAssertable in the TestAsserter to do not have SUnit dependent on Traits

**Comment by MarcusDenker** [comment]
newer issue, same topic: https://github.com/pharo-project/pharo/issues/13913
