### ISSUE TITLE
RunArray should implement add: method

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#3084]
Could possibly be solved by using

```Smalltalk
add: newObject 
  ^self addFirst: newObject
```

**Comment by Ducasse** [comment]
Do not close!

**Comment by kasperosterbye** [comment]
This issue is solved with the implementation suggested originally by @astares. It was done as part of the merge #8076.
Should be closed now.

**Comment by MarcusDenker** [comment]
Thanks for the analysis!
