### ISSUE TITLE
we should rename NEC and NOC Controller into CompletionEngine

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3113]
Name name names....

**Comment by Ducasse** [comment]
Tx marcus. I'm doing it now because I'm fedup to read these names.

**Comment by Ducasse** [comment]
I'm trying to come up with a better name because they are a kind of controller since they are talking to morph. Now may be Completer would be better. Then we will have to move the Preferences into the class because this is super strange to have code like that....

newSmartCharacterInsertionStringForLeft: left right: right
	((NECPreferences smartCharactersWithDoubleSpace includes: left) or: [
	(NECPreferences smartCharactersWithDoubleSpace includes: right)])
	ifTrue: [ 
		^ String with: left with: Character space with: Character space  with: right ].
	
	((NECPreferences smartCharactersWithSingleSpace includes: left) or: [
	(NECPreferences smartCharactersWithSingleSpace includes: right)])
	ifTrue: [ 
		^ String with: left with: Character space  with: right ].
	
	^ String with: left with: right

**Comment by Ducasse** [comment]
Argh lost my changes.... will redo it later

**Comment by MarcusDenker** [comment]
I will check... first we should remove the old unused code... this will already solve parts of the problem
