### ISSUE TITLE
Write test for: Losing class side instance variables on class redefinition

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3114]
Hi 

I was introducing a new superclass to NECController and I lost its class instance variables.
Here is what I did.
- Define a class that inherit from Object
Object subclass: #NullCompletionEngine
- changed
Object subclass: #NECController
	instanceVariableNames: 'model menuMorph editor context inverseMapping completionDelay'
	classVariableNames: 'ContextClass'
	package: 'NECompletion-View'

to 

NullCompletionEngine subclass: #NECController
	instanceVariableNames: 'model menuMorph editor context inverseMapping completionDelay'
	classVariableNames: 'ContextClass'
	package: 'NECompletion-View'

The NECController lost its class instance variable uniqueInstance.

**Comment by MarcusDenker** [comment]
bug was likely introduced by #2777

**Comment by MarcusDenker** [comment]
another thing that might be related:  #fillFor: does not set the class instance variables (I saw that when doing  #2901 )

**Comment by MarcusDenker** [comment]
this might be fixed by PR #3230

We need to write a test for the class builder for this case

**Comment by MarcusDenker** [comment]
This has been fixed
