### ISSUE TITLE
ZnBufferedReadStream>>upToEnd performance

### ISSUE THREAD

**Issue by akgrant43** [guillep/pharo-core#3135]
ZnBufferedReadStream>>upToEnd currently retrieves buffers from the underlying stream and then writes them to a WriteStream, which grows its buffer in steps. For a 4M file approximately 15 buffers (ByteArray | String) of increasing size will be created, copied and discarded. 

Since many streams know their size, #upToEnd can create and load a single buffer by using next: size - position.  This automatically handles cases where size is an over-estimate, and a check can be made afterwards in case size is an under-estimate.

A 4Mbyte file on my Dell XPS13 loads approx. 6 times faster with this optimisation.

PR on the way.

**Comment by akgrant43** [comment]
PR: https://github.com/svenvc/zinc/pull/32

**Comment by akgrant43** [comment]
Merged.  Thanks, Sven!

**Comment by StephanEggermont** [comment]
[Backport to 7 Performance]?

**Comment by estebanlm** [comment]
@StephanEggermont no :)

**Comment by StephanEggermont** [comment]
How does this impact the performance of the changes file?

**Comment by svenvc** [comment]
What do you mean by 'the performance of the changes file' ?

Do you have a use case of a performance issue ?

As far as I know, this thread/improvement has nothing to do with that.

And just for the record, the fastest way to read a whole file (in terms of IO operations) is, IMO,
````
'/tmp/foo.txt' asFileReference binaryReadStreamDo: [ :in | in next: in size ].
````
Then you could do the binary>text conversion yourself, if needed
````
('/tmp/foo.txt' asFileReference binaryReadStreamDo: [ :in | in next: in size ]) utf8Decoded.
````

**Comment by StephanEggermont** [comment]
In the other direction, writing to the changes file with as much as possible notifications off took 30% of time in #setToEnd. Before the fixes @tesonep did.
