### ISSUE TITLE
GTSpecPreDebugWindow>>initializeCodePane is dead

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3150]

**Comment by jecisc** [comment]
In fact it is used via reflectivity.

**Comment by MarcusDenker** [comment]
in this case it helps to add a comment!

**Comment by MarcusDenker** [comment]
To describe "this method looks empty but it is called using #perform: from ... " or something

**Comment by guillep** [comment]
@jecisc why the spec pre debugger needs to use reflectivity?

**Comment by MarcusDenker** [comment]
Not that I know. (I took it to mean "reflection" in general, e.g. some perform: or something like that). But I can not find any reference to the selector anywhere.

**Comment by jecisc** [comment]
@guillep I think it is not really needed but it's how it is currently done.

There are two unnecessary things IMO. 
- Use of performs in #createNotifierPaneWidgets
- Use of DNU to access the widgets of the pre debugger (which mark access to presenters as unimplemented methods)

**Comment by estebanlm** [comment]
tbh, the PreDebug window deserves a full rewrite (that I think we will do during the development of Spec2, at a point).
