### ISSUE TITLE
Trait: Overriden class side methods not added to classes using traits

### ISSUE THREAD

**Issue by chisandrei** [guillep/pharo-core#3158]
The code below creates a trait and adds two class side methods and two instance side methods:

```
Trait named: #TraitForTest
	 uses: {}
	 category: 'AAA'.
	
TraitForTest compile: 'ffiLibraryName
	^ 1+1. ' classified: 'test' .
	
TraitForTest compile: 'anotherMethod
	^ 1+1. ' classified: 'test' .
	
TraitForTest classTrait compile: 'ffiLibraryName
	^ 2+3. ' classified: 'test' .
	
TraitForTest classTrait compile: 'anotherMethod
	^ 2+3. ' classified: 'test' .
```

The class side method `#ffiLibraryName` is also defined in Object.

When creating then a class using that trait, the class side method  `#ffiLibraryName`  is not added to the class.

```
Object subclass: #ClassWithTrait
	uses: TraitForTest
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'AAA'.

ClassWithTrait ffiLibraryName.
```
	
The call to `#ffiLibraryName` raises an exception as the method defined in `Object` ends up being called: "'SubclassResponsibility: ClassWithTrait class had the subclass responsibility to implement #ffiLibraryName'".

Running `ClassWithTrait anotherMethod.` works ok and returns 5.

Checking selectors shows that the method `#ffiLibraryName` is not added to the class.

```
ClassWithTrait includesSelector: #ffiLibraryName.  "true"
ClassWithTrait class includesSelector: #ffiLibraryName.  "false"
ClassWithTrait class includesSelector: #anotherMethod.  "true"

TraitForTest includesSelector: #ffiLibraryName. "true"
TraitForTest classTrait includesSelector: #ffiLibraryName.  "true"
```

Same behaviour in Pharo 7 and 8.

**Comment by khinsen** [comment]
I came here to exactly this bug, only to find it reported a day earlier.

There is a potentially useful observation I can add to this. If you remove `ffiLibraryName` from `TraitForTest` *after* defining `ClassWithTrait`, and then define it again, then `ClassWithTrait ffiLibraryName` will work as expected. I have been using that as a workaround to continue working on my code.

**Comment by chisandrei** [comment]
Still important to fix

**Comment by MarcusDenker** [comment]
This seems to be the same problem as https://github.com/pharo-project/pharo/issues/4454

**Comment by MarcusDenker** [comment]
I added a PR that I think fixes it:

https://github.com/pharo-project/pharo/pull/5283

**Comment by MarcusDenker** [comment]
I merged the PR
