### ISSUE TITLE
MemoryLeak: Charge sorter

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3165]
In an image, I worked on Change Sorter and after I finished I ran some GC but I still had instances in my image. 

It's possible we have a memory leak.

**Comment by Ducasse** [comment]
There should be one instance to hold the changes. Now not multiple ones.

**Comment by akgrant43** [comment]
Not sure if this is related, but the window title suggests a similar issue:

"a SpecWindow(784367360) named: Dual Change Sorter on: Unnamed on: Unnamed on: Unnamed"

(I'd expect only one "on: Unnamed")

**Comment by Ducasse** [comment]
Yes :)

**Comment by jecisc** [comment]
It will be fixed with spec 2 synch

**Comment by astares** [comment]
Still valid

**Comment by guillep** [comment]
I don't think this is a memory leak, `ChangeSet` has always stored a default instance in a singleton.
Avoiding this could mean storing change sets in disk for example. That would require an entire redesign.
I propose to write that down in a wiki as a potential project and close this issue.

Of course, please reopen if there is a concrete issue we can deal with.
