### ISSUE TITLE
Logic of changeFactory references is suspicious

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3173]
RefactoryChangeFactory class >> instance
	^ RBRefactoryChangeManager instance changeFactory

RefactoringChangeManager class >> instance
	^ Instance ifNil: [ Instance := self basicNew initialize ]

RefactoringChangeManager >> changeFactory
	^ RBRefactoryChangeFactory new

I do not see the point to pass via the singleton if this is just to return a fresh instance each time.

**Comment by Ducasse** [comment]
I do not like the stale robot can we remove it.!

**Comment by noha** [comment]
Why? Do you want to keep all issues that nobody cares about? Sure these mails are annoying but they help clean stuff and concentrate on things somebody cares, no?

**Comment by Ducasse** [comment]
Because I have to write on the issues that I want to work on!!!

**Comment by noha** [comment]
You mean issues you want to work on but didn‘t in the last months?

**Comment by Ducasse** [comment]
Exactly and seriously I'm not the only one to be annoyed by this stale robot. Marcus changed the delay.

**Comment by noha** [comment]
I‘m not a fan of the stale robit and won‘t defend it. I‘m just asking myself if in a couple of month from now there is moaning about the very growing issue list where too many issues are okd and nobody cares. What is the alternative for this ?

**Comment by Ducasse** [comment]
Tagging and encouraging people to contribute.

**Comment by guillep** [comment]
This issue looks more like a small project than an actionable issue.
I propose we move it to a wiki with potential projects for people to contribute.
Could be a great basis for GSOC.
