### ISSUE TITLE
RB*Change should work on environment and not Smalltalk globals

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3175]
and their new environment variable could be initialized to Smalltalk globals for now.

**Comment by Ducasse** [comment]
changeClass
	| class |
	class := Smalltalk globals at: self changeClassName ifAbsent: [ ^ nil ].
	^ isMeta ifTrue: [ class class ] ifFalse: [ class ]

**Comment by Lin777** [comment]
This issue was already solved.

The RB*Change classes only refers to Smalltalk globals in these methods:

```
RBRefactoryChange >> initialize 
	super initialize.
	onSystemDictionary := Smalltalk globals.
	changeFactory := RBRefactoryChangeManager changeFactory

RBRemoveClassChange >> initialize 
	super initialize.
	onSystemDictionary ifNil: [ onSystemDictionary := Smalltalk globals ].
	changeFactory := RBRefactoryChangeManager changeFactory
```
