### ISSUE TITLE
NEC should provide a hook to suggest the class of a variable with certain names

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3177]
This PR (https://github.com/pharo-project/pharo/pull/3155) remove a hack used by Seaside. 

The goal of the hack is that, when seaside is loaded, the auto-completion will propose the brushes of Seaside when the variable is named `html` because naming a variable `html` is a big convention in Seaside. 

This is pretty important for the usability of some framework like seaside to do that because brushes do not have a common prefix and it improves a lot the productivity to auto-complete with the brushes. 

Since the hack was removed, we should provide a clean way to reproduce the behavior.

**Comment by guillep** [comment]
This issue looks more like a small project than an actionable issue.
I propose we move it to a wiki with potential projects for people to contribute.
Could be a great basis for GSOC.
