### ISSUE TITLE
ObjectLayout: remove var compactClassIndex

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#3196]
the var compactClassIndex is only set in #initialize but never read.

==> remove. 

But this needs to be done manually in the text files of the git repo, as we can not change that class in the system (it is used by too many classes).

How to do it: do a PR with a manual edit of https://github.com/pharo-project/pharo/blob/Pharo8.0/src/Slot-Core/ObjectLayout.class.st

**Comment by bencoman** [comment]
I'm not really familiar with it but wonder if the VM depends on it?

**Comment by MarcusDenker** [comment]
No, the VM does not know about the Layout... the layout is encoded in the format ivar of Behaviors for the VM.

**Comment by MarcusDenker** [comment]
the PR: https://github.com/pharo-project/pharo/pull/3208

**Comment by MarcusDenker** [comment]
has been merged
