### ISSUE TITLE
Creating a missing class in debugger still shows it missing in browser/critique

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#3211]
If you have a test method (but could be any method) referencing a missing class (either load it from a filein, or save it using the new leave undeclared menu option) and the create the class via the debugger by running the test, the class is correctly created however Calypso (possibly the code critic) still shows the class as undeclared.  Opening a new browser doesn't work - however running the test again, its happy the class is there. Re-saving the method does correct it (so something is out of sync).

An easy way to prove this is to run through the [pharo-exercism](https://exercism.io/my/tracks/pharo-smalltalk) first exercise (hello-world or two-fer).

![image](https://user-images.githubusercontent.com/5553623/56443454-0b716080-62f5-11e9-9c8c-ecc9666c0fcb.png)

**Comment by macta** [comment]
Something similar happens when deleting a class - it gets stuck with a DeletedClass reference even if the class is recreated.

**Comment by dionisiydk** [comment]
I investigated the issue. And it seems it is old bug (not related to Calypso). It is same in Pharo 6. 
Thee is some problem with updating cached ast of the method. 
Following expression shows the issue: 
```Smalltalk
(TwoFerTest>>#setUp) critiques "==> a Set(a ReTrivialCritique ([TwoFerTest] References an undeclared variable))"
```
It returns same critique when class is undefined and when you finally created it.
And the ast:
```Smalltalk
((TwoFerTest>>#setUp) ast allVariables detect: [ :e | e name = #TwoFer ]) binding  "==> an OCUndeclaredVariable"
```

**Comment by jecisc** [comment]
With Theo we did a first step with this PR: https://github.com/pharo-project/pharo/pull/3247

After this one, the critiques will be fine. The only problem remaining is that Calypso will not update the rules itself.

**Comment by StevenCostiou** [comment]
@MarcusDenker I am cleaning debugger issues to see clearer what's remaining.
Does this have to do with the debugger (in the large)? 
I looks like it is more a general reflective issue of the system (see #3247).

**Comment by MarcusDenker** [comment]
Yes, it is not about the debugger
