### ISSUE TITLE
[Iceberg] How can I do to resync the current image with the current branch?

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#3212]
I made some changes in the pharo repo folder in a way that my image is unsync with my repo.

I would like to resync with the current checkout branch and remerge it but the options is not suggested...
See:

![2019-04-22_13-58-07](https://user-images.githubusercontent.com/4706329/56499601-56fb5880-6507-11e9-9cc3-f8ef51a499dc.gif)

How to I do to not create another branch nor loose my changes nor check them out like I did for #2969

**Comment by kasperosterbye** [comment]
I am sure this long forgotten, but let me put an answer so it can be closed:
The short answer is that you
1. in your own fork on github does a "Sync fork".
2. In your image iceberg you do "Fetch"
3. In your image iceberg you do "Pull"

If it can merge into the image it will do, if not, iceberg will ask you to pick image or repository on a method to method basis.
