### ISSUE TITLE
copy class do not copy class side instanceVariableNames

### ISSUE THREAD

**Issue by CafeKrem** [guillep/pharo-core#3217]
copy a class where there are instanceVariableNames in class side
and you wil see that the new class do not have any instanceVariableNames in class side.

**Comment by CafeKrem** [comment]
Image
-----
/Users/clement/Documents/Pharo/images/NewTools-7/NewTools-7.image
Pharo8.0.0
Build information: Pharo-8.0.0+build.232.sha.32aa55cdd13de9c8d7e755d772583c29fc1cacf8 (64 Bit)
Unnamed

**Comment by MarcusDenker** [comment]
I think this is because #fillFor: does not set the variables on the class side. It misses a line

		classSlots: aClass class localSlots;
