### ISSUE TITLE
RGPackage should be RGPackageDefinition

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#3225]
There is a big mess in Ring naming. Most of the classes have the suffix -Definition however some of them like RGPackage not. In the Ring2 I named all the classes naturally (like RGClass) but in case of the package, I needed to use RGPackageDefinition to have the Ring2 loadable next to the original Ring. 

We should fix it simultaneously in both versions. This will break some compatibility with external users of the old Ring. Unfortunately, we cannot load Ring2 and put into its package class a constructor that will simply redirect the instantiation to the old Ring because both use the same method (`named:`)

**Comment by Ducasse** [comment]
Tx pavel. Yes we should clean this. And I would like to package RGMethod Definition alone in a small package for version browsers and remove Ring.
