### ISSUE TITLE
CDNode got polluted with extension methods that are on reflectivity for nodes

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3234]
Hi Denis

Why you did not package the extensions made by reflectivity on RBNode on the reflectivity package and not CDNode. Because now I will have to repackage them.

Stef

**Comment by dionisiydk** [comment]
Hi Stef.

No intention here. It needs to be fixed.

чт, 25 апр. 2019 г., 20:51 StéphaneDucasse <notifications@github.com>:
