### ISSUE TITLE
Why CDClassDefinition now depends on Compiler?

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3235]
binding
	| classBinding |
	classBinding := self existingBindingIfAbsent: [className -> nil].
	^OCLiteralVariable new 
		scope: originalNode scope;
		assoc: classBinding

**Comment by dionisiydk** [comment]
Intention was to behave like RBVariableNode.

чт, 25 апр. 2019 г., 20:55 StéphaneDucasse <notifications@github.com>:
