### ISSUE TITLE
isInstance is not consistent with isClassVariable

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3236]
isInstance should be deprecated into isInstanceVariable. 
And of course this bad API propagate to ClassDefinitionNode. 

I would love that we pay a bit attention to consistency in Pharo.

**Comment by dionisiydk** [comment]
Notice it is the state of ast-nodes API.
We should improve it all together and maybe first we need unify hierarchies

чт, 25 апр. 2019 г., 20:59 StéphaneDucasse <notifications@github.com>:

**Comment by MarcusDenker** [comment]
Yes, I used #isInstance it to be consistent with RBVariableNode.
