### ISSUE TITLE
What is RBProgramNode >> dumpOn: 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3237]
Why there is not a single comment!
Why this is not a visitor because it strives for it.

**Comment by aranega** [comment]
@Ducasse 

I'm the one who wrote this 

Actually nothing related to lisp or anything. The dump method generates the pharo code you need to write to have the equivalent of your ast. You can copy paste the code from the inspector in a playground and execute it directly.  This code gene is very handy when you need to write complex AST fragments and add them in your code (e.g, in reflectivity for reification code). I choose this name to match the one from other languages (Ruby, Python...) which often own such a method on their AST. 

The code could have been embedded in a visitor instead, but as the generated code was Pharo code and so closely bound to the AST (and to avoid a new class that would not have so much sense), I decided to add it on the node. If that's a problem, I can propose a new PR with the code located in another Class

**Comment by MarcusDenker** [comment]
merged the visitor refactoring
