### ISSUE TITLE
Better usability in Create after DNU

### ISSUE THREAD

**Issue by fuhrmanator** [guillep/pharo-core#3242]
One of my favorite features of Pharo is the ability to create new things after a Does Not Understand. However, I think the process needs some improving in the user experience. 

![image](https://user-images.githubusercontent.com/7606540/56791505-819b2900-6807-11e9-860a-0cceb6ac8e1f.png)

It's too easy (when we're coding quickly) to choose `Object` in the list above. I have done it, and it's a huge pain you can't "undo." Perhaps the solution is to pop up a dialog to warn the user they're about to add something to Object, and to confirm before actually doing it. Canceling returns the user to the dialog above.

Later, there's a step to choose protocol, which I often just take the default "as yet unclassified" value. I'm not sure this is a useful dialog during TDD or DDD. 

Finally, perhaps the two decisions could be put into a wizard-like engine (does it exist in Pharo?) so that the user can go back before finalizing the Create action.

**Comment by bencoman** [comment]
I also previously have thought this could be streamlined by skipping "step to choose protocol" 
but I'm thinking it could be really useful to auto-categorize extension methods.  
e.g... help ```2 myMethod``` end up in my application package.

**Comment by fuhrmanator** [comment]
This remains important to me.

**Comment by guillep** [comment]
In the past year, we have experimented with removing the protocol pop-up, and the experience was that later, we had to chase the unclassified methods...

This issue looks more like a small project than an actionable issue.
I propose we move it to a wiki with potential projects for people to contribute.
Could be a great basis for GSOC.

**Comment by fuhrmanator** [comment]
> This issue looks more like a small project than an actionable issue.

I agree about the whole issue as written. The usability part (it's too easy to mis-assign a method to the wrong class, no confirmation, no undo) seems actionable -- just add an OK button to the workflow instead of the click in the list being the action. 

It's clear that for people who like to go fast and live dangerously (or who've learned to pay attention at this dialog after suffering :-) ), it's another click. Frankly, with my experience trying to get students intereste in Pharo, I think it's one of the things that turns them off, because they are used to guard rails.
