### ISSUE TITLE
We should have a check on protocol names

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3245]
It is possible outside Pharo to edit some tonel code and to have "empty" protocols (protocols that are just empty strings).

Currently, Pharo will load the code but Calypso cannot display it. 

We discussed with Steph and we think that the solution is to check while loading the code if a protocol is valid. If not, the protocol should be set to as yet classified.

**Comment by Ducasse** [comment]
We should check the category setter or protocol: setter and make sure that it does not set empty string.
