### ISSUE TITLE
Remove Halt from Kernel

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3256]
I propose as a first step to move Halt from Kernel and put it in Debugging-Core.

**Comment by bencoman** [comment]
Halt seems deeply intertwined with the kernel.
Its removal from ```Context >> runUntilErrorOrReturnFrom:``` introduced a regression with a problem stepping-over "self halt" in the debugger, fixed here... https://github.com/pharo-project/pharo/pull/5289

Perhaps the class itself can remain but be slimmed down to move the majority of code to Debugging extensions that live outside the Kernel ?

**Comment by StevenCostiou** [comment]
@MarcusDenker what do you think about this issue? 
@jecisc could you explain why removing halt from the kernel?

Should we close this issue?

**Comment by jecisc** [comment]
One of Pharo's goal is to be more modular and to have the smallest core possible for the bootstrap. 

Halt is a debugging utility. Kernel does not need it and it can be loaded during a later step of the bootstrap probably.

**Comment by StevenCostiou** [comment]
Thanks Cyril, I understand. 
I remove debugger tags from this issue, as it is more related to modularity and not to the debugger and debugging system themselves.

**Comment by guillep** [comment]
This is a larger task than a bug in itself, I propose we write the idea down on a wiki page with potential projects.
