### ISSUE TITLE
Color API is totally confusing

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3264]
Many messages suggest that the receiver is changed and a new color is returned. 
For example beOpaque, adjustBrightness:, alpha: ...

I would love to have a naming convention showing that a color is modified or that a new color is created and returned.

Suggestions are welcome.

**Comment by kasperosterbye** [comment]
I understand your sentiment. 
The same issue is true with String: `#padLeftTo` and `#trim`

As I see it, the comments in Color can be improved to reflect new instances are created. Also, the protocol name 'transformations' is misleading as they are operators.

Should be an easy fix if this is what should be done.

`beOpaque` should be in the `transformations` protocol btw.

**Comment by guillep** [comment]
This issue looks more like a small project than an actionable issue.
I propose we move it to a wiki with potential projects for people to contribute.
Could be a great basis for GSOC.
