### ISSUE TITLE
ZeroConf does not bring version file

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3274]
To help with the PharoLauncher, Pharo comes with a version file. The problem is that this file is not present when we get the image via zero conf. Thus we cannot ship it with our project when we build a custom image on Jenkins.

**Comment by astares** [comment]
Still valid

**Comment by guillep** [comment]
@jecisc could you give some more details?

You want to have access to the version file, so that you can propose your images in the launcher?
What if Pharo images came with a facility to regenerate the version file, or the version info?

**Comment by astares** [comment]
@jecisc Is this one still relevant? Or should we close as it is too old.

**Comment by jecisc** [comment]
An option to regenerate it could be fine too.

The next version of the Pharo launcher should make it easier to launch images without the version file so maybe this is not so urgent anymore and we can close to focus on more important stuff
