### ISSUE TITLE
Rename method Refactoring leads to infinite warning in latest image

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3275]
/Users/ducasse/Documents/Pharo/images/P8Evaluator/P8Evaluator.image
Pharo8.0.0
Build information: Pharo-8.0.0+build.247.sha.57e3eb84cac4564882b47b87e2a977199fbe2470 (64 Bit)
Unnamed

May be Spec2 side effect.
Good news
	- reproducible
	- can stop with cmd .

Stef

**Comment by StephanEggermont** [comment]
- wrong deprecation message: ‘The forCode functionality has moved to TextCodePresenter, please use it instead TextPresenter’ -> class does not exist, only CodePresenter. Also, should not be deprecated, but used to instantiate the CodePresenter subclass on the AbstractTextPresenter, which should be renamed (Use as a factory hiding which subclass is created)

**Comment by sbragagnolo** [comment]
This seems to not be a problem anymore (probably related to Stephan Eggermont's commit). I tested it in pharo 8 without any problem. 
I would like to close it. I cannot manually close it.

**Comment by MarcusDenker** [comment]
this is fixed
