### ISSUE TITLE
adding initializeSlots: may break instance initialization

### ISSUE THREAD

**Issue by estebanlm** [guillep/pharo-core#3276]
`initializeSlots:` is being added to class initialize when we define slots who `wantsInitalization`.

The problem is that it is being added as last action of the initialize method and it should be the first (because the initialisation chain could be giving value to the variables that will be reseted when calling initializeSlots).

Additionally, `initializeSlots:` is being added without taking into account that it may have been added before in the initialisation chain (making the slots to be initialised multiple times).

**Comment by MarcusDenker** [comment]
I wonder if we could just do the initializeSlots: by default... it would slow down #new a little, though.
