### ISSUE TITLE
FTTableMorph refers to rows instead of cells

### ISSUE THREAD

**Issue by StephanEggermont** [guillep/pharo-core#3286]
A table consists of cells, not rows. There are a lot of references to rows, that should be systematically replaced by cells. The DataSource default interface needs to be cells. Next to a row-centric, also a column-centric view is needed.

**Comment by bencoman** [comment]
What is the status of this GSoC work...?
https://github.com/SamTheDev/Morphic-Widgets-FastTable

<blockquote><img src="https://avatars0.githubusercontent.com/u/2827220?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/SamTheDev/Morphic-Widgets-FastTable">SamTheDev/Morphic-Widgets-FastTable</a></strong></div><div>Contribute to SamTheDev/Morphic-Widgets-FastTable development by creating an account on GitHub.</div></blockquote>

**Comment by jecisc** [comment]
In Pharo 8 I cleaned some of the work and integrated it. (Some part of the design were not good).
It includes cell selection and column sorting. 

I still need to find some time to clean and integrated cells template like editable text cells, calendar cells, ...

**Comment by jecisc** [comment]
The repository in which I did my cleanings before integrating in Pharo is https://github.com/jecisc/Morphic-Widgets-FastTable

<blockquote><img src="https://avatars1.githubusercontent.com/u/9519971?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/jecisc/Morphic-Widgets-FastTable">jecisc/Morphic-Widgets-FastTable</a></strong></div><div>Contribute to jecisc/Morphic-Widgets-FastTable development by creating an account on GitHub.</div></blockquote>
