### ISSUE TITLE
aTrait isClass should be false

### ISSUE THREAD

**Issue by Alisu** [guillep/pharo-core#3287]
aTrait isClass anwser true.

**Comment by myroslavarm** [comment]
aTrait isClass should (and does) give false, whereas Trait isClass should (and does) give true. I think this issue should be closed.

**Comment by dionisiydk** [comment]
Ok. Better confusion example:
```Smalltalk
ClyTraitRoot1 isKindOf: Class. "==> true"
ClyTraitRoot1 isClass "==> will be false"
``` 
What explanation will be for this logic? It would be nice to put it in the comment for #isClass method if you will decide to perform this change.

**Comment by jecisc** [comment]
This seems to have changed

```
TEmpty isClass "false"
```
