### ISSUE TITLE
Deprecation: The method AbstractListPresenter>>#menu: called from EpLogBrowserPresenter>>#initializeItemsPresenter has been deprecated.

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#3291]
Lots of messages in the build log:

*** Warning: Deprecation: The method AbstractListPresenter>>#menu: called from EpLogBrowserPresenter>>#initializeItemsPresenter has been deprecated.
Use #contextMenu: instead. The old way to create a MenuPresenter was this method taking a MenuMorph as parameter. This will not work with other backend and will be totally removed in Pharo7. Now you should use #contextMenu takin a MeruPresenter (or a block returning a menu presenter) as parameter.

**Comment by jecisc** [comment]
We can correct it but not with the full current features. To port it well we need Lieutenant. @juliendelplanque Do you know when we will be able to try it?

**Comment by MarcusDenker** [comment]
initializeItemsPresenter does not exist anymore, so I close this
