### ISSUE TITLE
File Browser > Changes - FileList DNU #readStream

### ISSUE THREAD

**Issue by bencoman** [guillep/pharo-core#3302]
1. Tools > File Browser
2. Select an ST file
3. Click *Changes*

==> Instance of FileList did not understand #readStream

Fix is to change that to #readOnlyStream as hinted at... https://pharo.fogbugz.com/f/cases/19859

```
ExternalChangesBrowser>>serviceBrowseCSOrSTFile
	"Answer a service for opening a changelist browser on a file"
	^ (SimpleServiceEntry 
		provider: self 
		label: 'Changelist browser'
		selector: #openOnStream:
		description: 'Open a changelist tool on this file'
		buttonLabel: 'Changes')
-		argumentGetter: [ :stream | stream readStream ]
+		argumentGetter: [ :stream | stream readStreamOnly ]
```
And same for ```ExternalBrowser>>serviceBrowseCode```

(P.S. Its strange that case indicates it was integrated but it seems to be missing.)

Can this also be backported for the next Pharo 7 minor release.  It would be pretty jarring for a newcomer browsing around features.

**Comment by bencoman** [comment]
I was doing up a PR but find the FileList>>readOnlyStream is using deprecated FileStream
```
FileList >> readOnlyStream
	"Answer a read-only stream on the selected file. For the various stream-reading services."
	^ FileStream readOnlyFileNamed: self reference fullName
```
so another solution is required for Pharo 8. I'm not familiar with what the planned replacement should be so I'll have to leave it to others.

**Comment by svenvc** [comment]
But the reference inside FileList is already a FileReference, so the fix is to just ask the reference for its readStream

**Comment by estebanlm** [comment]
@bencoman can I close this issue now?

**Comment by bencoman** [comment]
Thx @estebanlm.   I've confirmed its fixed in build...
Pharo7.0.0-rc1.build.1436.sha.e281eb4.arch.32bit

Side thought... only if its simple to do... it could be good for the "development versions" shown in Launcher to follow the releases, so this build might have been named... 
Pharo7.0.4-alpha.build.1436.sha.e281eb4.arch.32bit

**Comment by bencoman** [comment]
@estebanlm So I was slow to notice that its been fixed in Pharo7.0.3.
Thats cool, although the idealist in me would have liked the patch version bumped.
