### ISSUE TITLE
Instance of SpecMultipleSelectionMode did not understand #selectedItem

### ISSUE THREAD

**Issue by bencoman** [guillep/pharo-core#3304]
I understand that Spec is in transition, just documenting a case to be handled.
After fixing issue #3302, for an ST file in File Browser clicking <Changes> button 
the clicking on a row in Changes Browser produces error "Instance of SpecMultipleSelectionMode did not understand #selectedItem"

```
ListPresenter(AbstractListPresenter)>>whenSelectedItemChanged: aBlock
	self
		deprecated: 'Use #whenSelectedItemChangedDo: instead'
		transformWith:
			'`@receiver whenSelectedItemChanged: `@argument'
				-> '`@receiver whenSelectedItemChangedDo: `@argument'.
	^ self
		whenSelectionChangedDo: [ :selection | aBlock cull: selection selectedItem ] "<<<<"
```

**Comment by bencoman** [comment]
I was doing up a PR but find the FileList>>readOnlyStream is using deprecated FileStream
```
readOnlyStream
	"Answer a read-only stream on the selected file. For the various stream-reading services."
	^ FileStream readOnlyFileNamed: self reference fullName
```
so another solution is required for Pharo 8. I'm not familiar with what the planned replacement should be so I'll have to leave it to others.

**Comment by jecisc** [comment]
Hello Ben,

For future issues on Spec2 could please open them at: https://github.com/pharo-spec/Spec/issues ?

This is the repository I look at the most when working on Spec. Thank you! 

<blockquote><img src="https://avatars1.githubusercontent.com/u/43748223?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-spec/Spec">pharo-spec/Spec</a></strong></div><div>Spec is a framework in Pharo for describing user interfaces. - pharo-spec/Spec</div></blockquote>

**Comment by bencoman** [comment]
cool, yes.

**Comment by svenvc** [comment]
But the reference inside FileList is already a FileReference, so the fix is to just ask the reference for its readStream

**Comment by MarcusDenker** [comment]
This is now working
