### ISSUE TITLE
Tabs in Calypso seems to not work anymore

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#3307]
In my image I can not switch to the class comment view... need to double check latest image

**Comment by dionisiydk** [comment]
Sorry guys. It's my fault.
Please revert latest Calypso integration.

Problem  that #doubleClick handler for tab label disables clicks on the tab.
I will try to find how to fix it

**Comment by dionisiydk** [comment]
I did a fix https://github.com/pharo-project/pharo/pull/3308
