### ISSUE TITLE
[Calypso] click on tab do nothing

### ISSUE THREAD

**Issue by CafeKrem** [guillep/pharo-core#3311]
when i want to click on tab (Comment , Class information or creat a Method ) nothing append.

my image come from 
pharo contribute jenkins >> newTools >> lastBuild >> pharo 8
this problem do not exist in 
Official distributions >> pharo 8 64 bit  

Image
-----
/Users/clement/Documents/Pharo/images/NewTools-23/NewTools-23.image
Pharo8.0.0
Build information: Pharo-8.0.0+build.256.sha.a614a9be3d84d729048978af1069bc10544042bc (64 Bit)
Unnamed

**Comment by MarcusDenker** [comment]
This should be fixed in the very very latest version

**Comment by MarcusDenker** [comment]
double checked: it is fixed in the latest download. see #3307

**Comment by CafeKrem** [comment]
sorry i will be carefull.
