### ISSUE TITLE
BlockClosure>>#storeOn: does infinite recursion

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#3319]
To reproduce this bug:
```st
[ :x | x + 1 ] storeString
```

Additionally, when it was working the `#storeString` of a BlockClosure was not printing as nicely as #printString (i.e. printing the code source).

Maybe we should discuss to:
1. Move `#printOn:` implementation to `#storeOn:` method.
2. Make `#printOn:` call `#storeOn:`

But we have to pay attention that normally `#storeOn:` should recreate a similar object but when a block closure does a reference to a variable defined in a outer context, it will not be possible to recreate this block.

**Comment by Ducasse** [comment]
Still the case

**Comment by guillep** [comment]
Same happens for compiled methods, where `storeOn:` does not handle cycles:
 - the method has an additional method state
 - the additional method state has the method
 - ...

I wonder if we need the storeOn: or it has been superseeded by STON in the past few years.

I see:
 - 25 senders of `storeString`, half of them tests
 - 176 seners of `storeOn:` but mostly recursive calls and tests. The only ones I see that could be legal users are
     -  use it to store timestamps in `writeClassComment:` and two comment related methods in `ClassDescription` and  `ClassOrganization`. And this could probably use another kind of serialisation...
     - the settings browser... But this could use STON

This issue looks more like a small project than an actionable issue.
I propose we move it to a wiki with potential projects for people to contribute.
I'm collecting all these.
Could be a great basis for GSOC.
