### ISSUE TITLE
traits definition message should use package: instead of category:

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3323]

**Comment by Ducasse** [comment]
why 

named: aSymbol
	^ self named: aSymbol uses: {} category: 'Unclassified'

is not 

named: aSymbol
	^ self named: aSymbol uses: {} category: '_UnpackagedPackage'

**Comment by jecisc** [comment]
Isn't "Unclassified" the default *tag*?

**Comment by Ducasse** [comment]
I started to clean some tests to avoid using category when it meant tag

**Comment by Ducasse** [comment]
I do not know in fact. 
This is why I raised the question.
