### ISSUE TITLE
Calypso senders should not DNU :(!!!

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3324]
when you type some text and your cursor is at the end for example 

traits:uses:| 

pressing Cmd N -> DNU

First the previous text should be selected: and second it should not raise a DNU

Stef

**Comment by dionisiydk** [comment]
I can't reproduce it

чт, 9 мая 2019 г. в 19:37, StéphaneDucasse <notifications@github.com>:

**Comment by Ducasse** [comment]
Thanks for checking it. I downloading and checking it.

**Comment by Ducasse** [comment]
I took the latest version I could not reproduce it. I tried all the panes. 
I saw that now we do not have select the line to do Browse and this is really cool. 
Tx!

So I close the issue. I have no idea how I broke the system
