### ISSUE TITLE
ClyClassDefinitionEditorToolMorph contains dead code

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3325]
selectVariableNamed: aString 
	| classDefinition varNode |
	classDefinition := self parseClassDefinition.
	varNode := classDefinition children 
		detect: [ :each | each isVariable and: [each name = aString]]
		ifNone: [ ^self ].
	self selectSourceNode: varNode

parseClassDefinition is undefined!

**Comment by dionisiydk** [comment]
It is for class parser integration

чт, 9 мая 2019 г., 20:04 StéphaneDucasse <notifications@github.com>:
