### ISSUE TITLE
New package committed by Iceberg is always dirty

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#3332]
If you create a new package, add it into a repository and commit it, it is still marked as "dirty" in Calypso. The package responds on #isDirty with true. That's probably because the committing in Iceberg does not create a version known to Monticello (the package has no version in MC Browser) so it is supposed to be not saved.

**Comment by kasperosterbye** [comment]
This is often my experience as well, but not always. And now it is 3 years later.
There are several issues on iceberg which seems related:
https://github.com/pharo-vcs/iceberg/issues?q=is%3Aissue+is%3Aopen+%22empty+commit%22

<blockquote><img src="https://opengraph.githubassets.com/21f10944537c62a3a2e2beed0cff5e7e87dbfe98d81426c28fd5a668df1ace86/pharo-vcs/iceberg" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-vcs/iceberg">Issues · pharo-vcs/iceberg</a></strong></div><div>Iceberg is the main toolset for handling VCS in Pharo. - Issues · pharo-vcs/iceberg</div></blockquote>
