### ISSUE TITLE
Test Runner history menu is broken

### ISSUE THREAD

**Issue by cdlm** [guillep/pharo-core#3333]
1. Open test Runner,
2. run some tests,
3. right click in the test result bar, pick any of the history/progress options of that menu

💥 `instance of RubTextEditor DNU #showHistoryMenu / #storeResultIntoTestCases / #showProgress`

**Comment by Ducasse** [comment]
Yes we will throw it away.

**Comment by MarcusDenker** [comment]
PR was merged
