### ISSUE TITLE
Character cr isLineSeparator ==> false

### ISSUE THREAD

**Issue by dionisiydk** [guillep/pharo-core#3334]
I am not sure if it should true according to Unicode. But it looks strange:
```Smalltalk
Character cr isLineSeparator "== false"
```

**Comment by kasperosterbye** [comment]
[According to Unicode, LineSeparator](https://www.fileformat.info/info/unicode/char/2028/index.htm) is actually code 8232 (2028 hex).
`Character cr isSeparator` returns true though.

**Comment by kasperosterbye** [comment]
I suggest to close this issue. `LineSeperator` is a technical Unicode term, and implemented correctly in the image.
