### ISSUE TITLE
Begin to split tests linked to Halt in Kernel

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3341]
I did a PR to remove Halt from the kernel but it makes the bootstrap fail. I'll do a smaller PR to begin the changes. It will include separation of Kernel tests and Halt tests. It should help me to localise the root of the problem.

**Comment by bencoman** [comment]
A had considered Halt to be quite intrinsic to the system.  I'm curious what the driver is for removing Halt.

**Comment by jecisc** [comment]
Hi Ben! 
The goal is not to remove halt from the system but from the Kernel package to move it in debugging packages. 

Currently, the Halt implementation have dependencies on other packages that Kernel should not have. For example, Halt depend on the compiler, but at the beginning of the Bootstrap the compiler is not loaded with the Kernel and the Kernel package should work. 

The long terme idea for the Bootstrap would be to have layers such has Kernel layer, graphical, network, development tools... IMO, Halt should not be part of the Kernel one.

**Comment by bencoman** [comment]
got it. thx.
