### ISSUE TITLE
`(ProtoObject >> #==) senders` yields many false positives

### ISSUE THREAD

**Issue by khinsen** [guillep/pharo-core#3347]
On a freshly downloaded Pharo 8.0 image, `(ProtoObject >> #==) senders` yields more than 10.000 methods. Most of them do not use `==`. Searching for senders in Calypso only shows 9.000 methods (for reasons that I don't understand), but most are also false positives.

Many of the falsely found methods use `ifNil:` and/or `ifNotNil:`, so I suspect that the compiler somehow optimizes these methods into tests involving `== nil`. But that's not what I expect to see when looking for uses of `==`.

**Comment by MarcusDenker** [comment]
yes, smalltalk uses a low level model as the language meta model... I think we should think about using a higher level model...

Workaround: we could filter all these cases in addition using the AST model. Or add meta-data at compile time...

**Comment by MarcusDenker** [comment]
The real reason why they show is that we optimise #== specially for space: as it is not a send, we do not put it into the literal array. Instead we detect all these cases and then scan the bytecode.

if we would just add a literal entry for it, and have "senders of" just check those, the problem would not happen for #==.

I added a new issue tracker entry: https://github.com/pharo-project/pharo/issues/3347
