### ISSUE TITLE
refactor to remove #not in method #hasSubclasses

### ISSUE THREAD

**Issue by myroslavarm** [guillep/pharo-core#3349]
currently the method #hasSubclasses is implemented as follows:

hasSubclasses
	^ self subclasses isEmpty not

this way of defining it is not ideal

**Comment by myroslavarm** [comment]
#3350 created a pull request

**Comment by Ducasse** [comment]
I do not get why this definition would be bad. 
Your solution is worse 

Class >> hasSubclasses [
 	^ (self subclasses isEmpty)
 			ifTrue: [ false]
 			ifFalse: [ true ]

This is not good. Especially because not should be used instead!
