### ISSUE TITLE
Running crititz on equality and hash function gives a message

### ISSUE THREAD

**Issue by ghost** [guillep/pharo-core#3354]
Hello, 

When I use the extra -> generate equal and hash this code is made 

```
= anObject
	"Answer whether the receiver and anObject represent the same object."

	self == anObject
		ifTrue: [ ^ true ].
	self class = anObject class
		ifFalse: [ ^ false ].
	^ minute = anObject minute and: [ hour = anObject hour ]
```

but when running critiz gives this message: 

![afbeelding](https://user-images.githubusercontent.com/47429430/57766238-4e153580-7707-11e9-9e9d-7a2d831a50ee.png)

this one is also tracked here : https://github.com/exercism/pharo-smalltalk/issues/341

where we concluded it is a pharo problem not a exercism problem

**Comment by MarcusDenker** [comment]
I really do not like this rule. For me methods with early returns are *much* faster to read then if it would be one huge nested boolean expression.

I would like to propose to delete the rule

**Comment by bencoman** [comment]
I agree.  Early returns mean you don't have to hold the logic structure in
your mind to track where the block drops out. Less coupling between
conditions and less cognitive load.

**Comment by Ducasse** [comment]
Dont delete it just cancel it. One day we should support profile because we remove rules that us experts to not like but newbies make incredible mistakes you would not believe it.

**Comment by MarcusDenker** [comment]
But it is even bad for newbies. Especially for new people: "turn this easy to read method into mess of a nested boolean expression that takes 10 minutes to read" is not a good advice for anyone.

**Comment by Ducasse** [comment]
What I said is that we need rule examples so we can just disable it.
