### ISSUE TITLE
Hiedra: Migrate example to current Spec

### ISSUE THREAD

**Issue by tinchodias** [guillep/pharo-core#3379]
It raises errors since Spec2 was integrated.

**Comment by guillep** [comment]
It seems to work now after latest Spec update. I've tried
- example2870IcebergCommits
- example493PharoCommits
- example60RandomCommits

Also, wouldn't it be good to run them as tests?

**Comment by tinchodias** [comment]
I created the issue, good idea and simple to implement ;).
