### ISSUE TITLE
Dependentbrowser is broken by Spec2.0

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3383]

**Comment by Ducasse** [comment]
opening the dependency analyser from the menu raises an error.

**Comment by guillep** [comment]
I've tried this. The tree in the dependency analyzer uses trees with multiple selection that are not yet working in the Spec version integrated in Pharo so far. For example I've found:

```smalltalk
TreeTablePresenter >> #whenSelectedItemChangedDo: aBlockClosure 
	
	self whenSelectionChangedDo: [ :selection | aBlockClosure cull: selection second ]
```

```smalltalk
TreeMultipleSelectionMode >> #selectedItem
	self shouldBeImplemented
```

Maybe we need a new spec update?

**Comment by MarcusDenker** [comment]
I can open the browser now in Pharo9
