### ISSUE TITLE
pharo.org: we should enforce https:

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#3390]
Right now, the pharo.org website supports both https: and http:, we should configure it to force https:

**Comment by noha** [comment]
What is meant by forcing? Usually you redirect automatically from http to https. The next question is why https is needed as there is no sensitive data. Finally if it should be https the use of certbot could easiest. The certbot even writes the webserver config

**Comment by MarcusDenker** [comment]
I meant having an automatic redirect... yes, it might be not needed... but people seem to now look at projects like pharo, end up on the http: page (even though https: exists) and immediately judge it as "this is not secure". Even though the download links are https: to files.pharo.org...

from twitter:

@pharoproject I want to start playing with Pharo, but I'm unsure about downloading the launcher: pharo.org/download My concerns are: 1. no ssl on page 2. no hash to check against 3. MacOS flags it as not from an identified developer. #2 (hash)would go a long way to improving

(I added issue tracker entries for all)

**Comment by noha** [comment]
Ok, for downloads this is true. Maybe does not harm to have all https. Which webserver is this?

**Comment by astares** [comment]
@MarcusDenker Can you answer the question of @noha so we can move forward here?

**Comment by MarcusDenker** [comment]
this is apache

**Comment by MarcusDenker** [comment]
done
