### ISSUE TITLE
files.pharo.org: checksum for all downloads

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#3391]
We should add back .sha256 checksums for all downloads

For real security, the checksum needs to be downloadable from a second source, the best would be to online the data at the pharo.org download page.

after: add gpg based checksum

**Comment by Ducasse** [comment]
Yes this is a really good idea.
We need to grow on the tracability.

**Comment by MarcusDenker** [comment]
I close this for the newer  https://github.com/pharo-project/pharo/issues/15071
