### ISSUE TITLE
Update to Iceberg 1.7.1

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#3404]
Iceberg needs to be updated to version 1.7.1, it includes important fixes

**Comment by guillep** [comment]
https://github.com/pharo-vcs/iceberg/releases/tag/v1.7.1

<blockquote><img src="https://avatars0.githubusercontent.com/u/28102403?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-vcs/iceberg">pharo-vcs/iceberg</a></strong></div><div>Iceberg is a set of tools that allow one to handle git repositories directly from a Pharo image. Right now we support only git, but Iceberg is designed to allow other code versioning systems in the...</div></blockquote>
