### ISSUE TITLE
SystemCommands: document #isComplexeRefactoring

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3414]
I am trying to add some commands to a project that should act on classes so I checked existing commands. I found a method #isComplexeRefactoring but since there is no method comment I don't know if my commands should return true or false for it.

We should have a comment.

**Comment by jecisc** [comment]
probably still valid

**Comment by MarcusDenker** [comment]
There is no senders or implementors of isComplexeRefactoring anymore
