### ISSUE TITLE
classTrait introduces a lot of noise

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3419]
SHRBTextStyler class
	uses: TRBProgramNodeVisitor classTrait
	instanceVariableNames: 'styleTable textAttributesByPixelHeight'

Browse the class side of SHRBTextStyler and you will see many methods that are not redefined and it looks strange to see them.

**Comment by jecisc** [comment]
+1

**Comment by VincentBlondeau** [comment]
Could you check if it is related to https://github.com/pharo-project/pharo/issues/3389?

**Comment by MarcusDenker** [comment]
we integrated  https://github.com/pharo-project/pharo/pull/3426,  this solves the problem described here but not yet #3389 completely.

I will close this issue.
