### ISSUE TITLE
spec glitch?

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3421]
when we do ChangeSorterPresenter new openWithSpec
we get 
<img width="512" alt="Screen Shot 2019-05-26 at 20 32 25" src="https://user-images.githubusercontent.com/432549/58389134-72b9b900-7ff5-11e9-85f5-84461673fb8d.png">

**Comment by Ducasse** [comment]
It looks to me that the layout is not good 

<img width="497" alt="Screen Shot 2019-05-26 at 20 47 08" src="https://user-images.githubusercontent.com/432549/58389321-9251e100-7ff7-11e9-87b6-95afddbb3b42.png">

**Comment by jecisc** [comment]
It's a bug we already encountered with the new layouts :( 

It's possible that the origin is in FastTable because we only encountered it with lists and tables and I did not find anything weird in the layouts.

**Comment by MarcusDenker** [comment]
This is now working
