### ISSUE TITLE
ifError should accept error instance instead of its properties

### ISSUE THREAD

**Issue by dionisiydk** [guillep/pharo-core#3430]
I found super surprizing logic of ifError: method. It passes error description to the block:
```Smalltalk
[self error: 'test error'] ifError: [:errString  | errString]. 
"==> 'Error: test error' - string instance"
```
I really wonder why it is better then full error instance. And I think it is not.
My proposal is to change #ifError: method to have only zero block or one argument block which accept error instance.  

There are few users in system of string block argument. But they all in tests. 
Compatibility should not be a big issue because it's unlikely that anybody relies on "error as string" analysis except in tests.

**Comment by MarcusDenker** [comment]
one could even add a test and if a string is passed, transform the caller...
