### ISSUE TITLE
ComposablePresenter>>#newTree is deprecated before an alternative is there 

### ISSUE THREAD

**Issue by StephanEggermont** [guillep/pharo-core#3435]
The API is different, and TreeTable does not yet implement needed functionality. This makes the build log hard to read.

https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo8.0/301/consoleText

**Comment by estebanlm** [comment]
this is not going to be fixed but replaced by Spec2
