### ISSUE TITLE
Mis-spelled protocol name 'acccessing'

### ISSUE THREAD

**Issue by niepiekm** [guillep/pharo-core#3444]
Accessing protocol name misspelled as 'acccessing' in several classes.

**Comment by bencoman** [comment]
Hi @niepiekm, Thanks for taking the time to report this.  But we are left having to do additional work trying to guess which 'several classes' this occurs in.  If you have that information in front of you, it would help us if you could add it here.

**Comment by jecisc** [comment]
```Smalltalk
classes := Set new.
Smalltalk allClasses do: [ :class | (class protocols includes: 'acccessing') ifTrue: [ classes add: class ] ].
classes 
"a Set(FFICharacterType IceTipRefreshCommitCommand NullPharoIssue GIFReadWriterTests ExternalChangesBrowser RFReification)"
```

**Comment by niepiekm** [comment]
@bencoman Apologies for incomplete report. I was going to prepare a PR with fixes for the issue I reported.  For latest Pharo 8, I get following list of classes from snippet from @jecisc:

> 'a Set(GIFReadWriterTests IceTipRefreshCommitCommand FFICharacterType NullPharoIssue ExternalChangesBrowser RFReification)'

**Comment by bencoman** [comment]
On Fri, 31 May 2019 at 16:59, Marek Niepiekło <notifications@github.com>
wrote:

> @bencoman <https://github.com/bencoman> Apologies for incomplete report.
> I was going to prepare a PR with fixes for the issue I reported. For latest
> Pharo 8, I get following list of classes from snippet from @jecisc
> <https://github.com/jecisc>:
>

Great !!  I just couldn't tell that from what you'd written.  Please
continue.

**Comment by Ducasse** [comment]
Thanks a lot 
Can you do one PR for the NullPharoIssue GIFReadWriterTests ExternalChangesBrowser RFReification?
Because Iceberg is managed separately. 
I do not know for UFFI it is probably managed inside Pharo

**Comment by astares** [comment]
Yes - UFFI is managed inside of Pharo - so for FFICharacterType it can be changed too

**Comment by niepiekm** [comment]
Resolved. Closing.
