### ISSUE TITLE
Pharo 8 crashes hard on cloning project

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#3461]
On UBUNTU and on Windows I have a crash when (using a recent Pharo 8 image, 64 bit) and running the following scenario:

 - Open Iceberg
 - click on "Add"
 - select "Clone from GitHub"
 - use "astares" as Owner name and "pharo" as Project name, select "HTTPS" as Protocol, click on "Accept"

Pharo tries to clone the repo - but then the Pharo process just dies.

On Ubuntu the consol tells:

  free(): invalid pointer
  ./pharo-ui: line 11:  3604 Aborted                 (core dumped) "$DIR"/"pharo-vm/pharo" "$@"

I guess it is related to the changes done in PR 3136

http://lists.pharo.org/pipermail/pharo-dev_lists.pharo.org/2019-June/275488.html

**Comment by MarcusDenker** [comment]
PR #3136

**Comment by MarcusDenker** [comment]
I merged the revert

**Comment by astares** [comment]
Yes - works again. 

I guess the PR 3136 from @zecke now needs another adoption or review to get in
