### ISSUE TITLE
Push up has unexplicit warning

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3467]
I have this hierarchy:

`B` inherits from `A` that inherits from `Object`. 

In `Object` I have a method `foo`. This method is overridden in `B`.

I wanted to push up `foo` from `B` to `A`. Doing so I got a warning: `Non-abstract class A already defines #foo` and it asked me if I wanted to proceed. 

I have a problem with that because my method was not in `A` but in `Object`. The warning should have been something like `Method #foo is defined in Object, a superclass of A. Are you sure you want to proceed since it will change the behavior of #foo?`

Or maybe no warning. I don't know.

**Comment by Ducasse** [comment]
Agreed we should improve it.
