### ISSUE TITLE
Improve fiability of DependencyAnalyzer

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3470]
In some cases, the DependencyAnalyzer cannot be sure of some dependencies because there are multiple methods of the same name in the image and it fails to infer which is the right one.

But when showing dependencies at the level of the package, it does not mean that it cannot know from which package the dependency is from. 

Example:

![Screenshot 2019-06-06 at 18 04 30](https://user-images.githubusercontent.com/9519971/59048293-d067c400-8885-11e9-9a7e-c5451561f3a5.png)

On this screen, we see that a method is implemented on 5 objects but the 5 are in the same package. Thus we are sure of the dependency in that case. It would be great of the tool could manage this case.

**Comment by jecisc** [comment]
keep it

**Comment by guillep** [comment]
This issue looks more like a small project than an actionable issue.
I propose we move it to a wiki with potential projects for people to contribute.
I'm collecting all these.
Could be a great basis for GSOC.
