### ISSUE TITLE
Fuel + statefull traits

### ISSUE THREAD

**Issue by sbragagnolo** [guillep/pharo-core#3481]
Fuel uses inst-var-name based methods, which are retro-compatible, but not fully compatible with the new traits implementation. As result is failing pretty bad.

Just try to create a trait with slots
Trait named: #TExample
	 uses: {}
	 slots: { #value }
	 category: 'Example'

Object subclass: #ExampleUsage
	uses: TExample
	slots: {  }
	classVariables: {  }
	package: 'Example'

FLSerializer serializeToByteArray: ExampleUsage new.

**Comment by theseion** [comment]
Fixed by #4367. Added tests to Fuel in https://github.com/theseion/FuelPlatform/commit/7441c40eaf5f93f32f62c2c7a71ee066a70eae4e
