### ISSUE TITLE
Rename method refactoring copies trait methods into user class

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#3482]
Here is how to reproduce the bug:

Create a class that defines some behaviour to be called by the trait.
```st
Object subclass: #FakeClass
	slots: {  }
	classVariables: {  }
	package: 'TestPackage'
```

```st
FakeClass class>>#justForTest
	^ 42
```

Create a trait:

```st
Trait named: #TDummy
	 uses: {}
	 category: 'TestPackage'
```

This trait calls the method we will rename:

```st
TDummy >>#methodCopiedInClassAfterRefactoring
	FakeClass justForTest
```

Create a class that use the trait:

```st
Object subclass: #ClassUsingTrait
	uses: TDummy
	slots: {  }
	classVariables: {  }
	package: 'TestPackage'
```

Now, rename `FakeClass class>>#justForTest` to `FakeClass class>>#justForTestRenamed` from the UI.

The renaming goes fine (no error is raised) but the method `methodCopiedInClassAfterRefactoring` is now duplicated in both in `TDummy` and `ClassUsingTrait`.

This was tested under Pharo 7. Will see if I have time to test it under Pharo 8 later.

**Comment by jecisc** [comment]
This also happen with the RenameClass refactoring if a method of a Trait use the class.

**Comment by sbragagnolo** [comment]
We really need to give some love to update the model of the Refactoring browser
