### ISSUE TITLE
UITheme>>#desktopImageFor: is wrong

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#3485]
```st
desktopImageFor: aWorld
	"Answer the desktop image for the given world.
	Look for an image file with the name of the theme.
	Answer nil for none available."

	|file|
	file := FileSystem disk workingDirectory / self class themeName , 'jpg'.
	^ file exists ifTrue: [
		ImageReadWriter formFromFileNamed: file fullName]
```

file can never be a valid file name because the dot is missing between themeName and 'jpg'.

One can look at #themeName implementation, there is no dot at the end of String returned.

**Comment by svenvc** [comment]
Yes it works, #, is not String concatenation here.

Try:

    (FileLocator desktop / 'data' , 'csv') pathString.
    "'/Users/sven/Desktop/data.csv'"

**Comment by juliendelplanque** [comment]
Wow I didn't know thanks I close the issue
