### ISSUE TITLE
UUID>>#printHexAt:to: should use standard API to print bytes in base 16

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#3487]
```st
printHexAt: index to: aStream
	"Print the hex value of my byte at index to aStream"
	
	| map v |
	map := '0123456789abcdef'.
	v := self at: index.
	aStream nextPut: (map at: (v bitShift: -4) + 1). 
	aStream nextPut: (map at: (v bitAnd: 15) + 1).
```

One can get the same with:

```st
printHexAt: index to: aStream
	"Print the hex value of my byte at index to aStream"
	(self at: index) printOn: aStream base: 16
```

**Comment by svenvc** [comment]
No because it does not fill, try:

    String streamContents: [ :out | 1 printOn: out base: 16 ].

01 is needed, not just 1

**Comment by juliendelplanque** [comment]
I was a bit quick again :-)

I will work with `#printOn:base:length:padded:`
```st
String streamContents: [ :aStream | 255 printOn: aStream base: 16 length: 4 padded: true ]
```

**Comment by svenvc** [comment]
Hmm, I understand your point to some degree, but this implementation is more efficient (faster, less garbage).

I have (seen/written) similar code in many places, maybe a better shared implementation is needed. I will think a bit about this.

**Comment by Ducasse** [comment]
And I added nice comments to printOn: aStream base: 16 length: 4 padded: true. 
So the minimum is to improve the comment of printHexAt: index to: aStream

**Comment by svenvc** [comment]
See https://github.com/pharo-project/pharo/issues/3642

**Comment by svenvc** [comment]
I guess this can be closed too
