### ISSUE TITLE
UUID>>#readHexByteFrom: do not use standard API for parsing base 16 string

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#3488]
```st
readHexByteFrom: aStream
	"Read and return a single lowercase hex encoded byte from aStream"
	
	| map v |
	map := '0123456789abcdef'.
	v := (map indexOf: aStream next asLowercase ifAbsent: [ self error: 'hex digit expected' ]) - 1.
	v := v bitShift: 4.
	v := v + (map indexOf: aStream next asLowercase ifAbsent: [ self error: 'hex digit expected' ]) - 1.
	^ v
```

Could be fixed using `Integer readFrom: base16String base: 16`

**Comment by svenvc** [comment]
Sorry, no, it does not, it reads to much (is keeps on reading)

    Integer readFrom: 'FFFF' base: 16

**Comment by juliendelplanque** [comment]
Yeah I wrote it a bit quick, more something like:

```st
Integer readFrom: (base16String next: 2) base: 16
```

or something.

But I think it should use the standard api.

**Comment by svenvc** [comment]
Hmm, I understand your point to some degree, but this implementation is more efficient (faster, less garbage).

I have (seen/written) similar code in many places, maybe a better shared implementation is needed. I will think a bit about this.

**Comment by juliendelplanque** [comment]
Yes it would be nice to reuse as much as possible and also to expose such API to parse string encoding integer in some base to Pharo developers.

**Comment by Ducasse** [comment]
Sven can you at least issue a new comment for this method with all the information. 
Because we were really thinking that it was just a duplication.

**Comment by svenvc** [comment]
See https://github.com/pharo-project/pharo/issues/3642

**Comment by Ducasse** [comment]
So can we close this issue?

**Comment by svenvc** [comment]
I guess this can be closed
