### ISSUE TITLE
Save item in the toolbar

### ISSUE THREAD

**Issue by bergel** [guillep/pharo-core#3522]
The "Save" menu item is now the last one, this is odd.

![Screen Shot 2019-06-14 at 10 45 42 AM](https://user-images.githubusercontent.com/393742/59517604-ebdc5b80-8e91-11e9-8a53-86ba31f3a35b.png)

**Comment by astares** [comment]
![image](https://user-images.githubusercontent.com/5980033/59521232-0c290c00-8ecc-11e9-958f-7a0ff521e2ee.png)
