### ISSUE TITLE
Refactoring idea: Make instance variable

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3543]
I have a test class where all classes use a `log` temporary variable. I would like to make it an instance variable.

Maybe we could have a "Make instance variable" refactoring?

**Comment by Ducasse** [comment]
Ok you mean that it is no just turning the local temp into a variable but checking all the methods. 
From a refactoring point of view, it should work since the tmpe should be assigned a value.

**Comment by sbragagnolo** [comment]
Still it is kind of complex. How would we deal with multiple hierarchies ?
