### ISSUE TITLE
Behavior>>instSize includes slots from Traits, but ClassDescription>>instVarNames doesn't

### ISSUE THREAD

**Issue by akgrant43** [guillep/pharo-core#3546]
`ClassDescription>>instanceVariableNamesDo:` will generate a SubscriptOutOfBounds error when the receiver includes a Trait with slots, e.g.:

```
Trait named: #TestTrait2
	uses: { }
	slots: { #slot1 }
	category: 'AKG-instSize'.

Object subclass: #HasTrait1
	uses: TestTrait2
	instanceVariableNames: 'iVar'
	classVariableNames: ''
	package: 'AKG-instSize'.

{ HasTrait1 instSize. HasTrait1 instVarNames. }.
" #(2 #(#iVar))"

HasTrait1 instanceVariableNamesDo: [ :x | ].
"==> SubscriptOutOfBounds: 2"
```

As can be seen from the above, `#instSize` includes the slot (`#slot1`), while `#instVarNames` does not.

This was triggered by trying to Fuel out a class with this type of definition, so I assume that `#instVarNames` should be modified to include the defined slots.

**Comment by MarcusDenker** [comment]
We need to be careful: Slots is  can be "virtual", that is: there can be a slot, but it does not increase the size of the object.

**Comment by MarcusDenker** [comment]
I think the solution is to provide an explicit "indexedInstVarsDo:" method (and #indexedInstVarNames) for low level users that just care about indexed ivars (and includes hidden ones).

Then indeed have #instVarNames return all visible slot names. 

In general, I think this is were we start to see a case for some "view" concept: Do I want to look at the instance at the low level (memory layout) or see the high level view?

**Comment by MarcusDenker** [comment]
this seems to be related: instVarNames explicitly just answers the local ones:

instVarNames
	"Answer an Array of the receiver's instance variable names."

	^self localSlots collect: [ :each | each name ]

**Comment by MarcusDenker** [comment]
PR merged
