### ISSUE TITLE
SystemNavigation: move all methods related to "all objects" to SmalltalkImage

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#3574]
allObjects, allObjectsDo:, allObjectsOrNil

These are about iterating all objects of the image. --> the right place is SmalltalkImage.

**Comment by astares** [comment]
@MarcusDenker Autoclosed. Is it still required?

**Comment by MarcusDenker** [comment]
I still think so... "all objects" is a image level abstraction... and the primitives are per image, not per SystemNavigation

**Comment by guillep** [comment]
This issue looks more like a small project than an actionable issue.
I propose we move it to a wiki with potential projects for people to contribute.
I'm collecting all these.
Could be a great basis for GSOC.
