### ISSUE TITLE
GLMRubricExample presentation has unnecessary tempvar seg

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#3577]
- GLMRubricExample presentation method has unnecessary tempvar seg
- easy to fix

**Comment by astares** [comment]
Hey you! Yes you - my dear GitHub user. You are a reader of this issue comment now. What if YOU would be the one fixing it beside just reading.... 

It's trivial and it does not cost much time. Nonetheless it would be YOUR important contribution to Pharo. Because Pharo is YOURS as well as mine.

-------------------------------------------------------------------------------------------------------------
Why should you help:

In 2017 I already asked people to help cleaning and raise the quality level:
http://forum.world.st/Pharo-Quality-raising-the-quality-level-in-Pharo-7-and-onwards-tp5027111.html

And I took action with around 658 sometimes very trivial changes to get Pharo 7 
and 8 into a cleaner state (https://github.com/astares/pharo/branches)

One step at a time ... evening per evening, week per week. 
What if more and more people would stepped in and done the same?  

Now @MarcusDenker brings this to attention again with a small game: 
do one trivial improvement every day
http://lists.pharo.org/pipermail/pharo-dev_lists.pharo.org/2019-June/275586.html

And it looks like this little issue got famous now on Twitter therefore: https://twitter.com/marcusdenker/status/1148287564937400321

So it's up to you to help fixing this and other issues

<blockquote><div><strong><a href="http://forum.world.st/Pharo-Quality-raising-the-quality-level-in-Pharo-7-and-onwards-tp5027111.html">Pharo Smalltalk Developers - Pharo Quality: raising the quality level in Pharo 7 and onwards</a></strong></div><div>Pharo Quality: raising the quality level in Pharo 7 and onwards. Hi, when we forked Pharo back in the days (2008) one of the primary goals of Pharo was and still is to provide a CLEAN SYSTEM. Now...</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/5980033?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/astares/pharo">astares/pharo</a></strong></div><div>Contribute to astares/pharo development by creating an account on GitHub.</div></blockquote>
<blockquote><div><strong><a href="http://lists.pharo.org/pipermail/pharo-dev_lists.pharo.org/2019-June/275586.html">[Pharo-dev] A small game: do one trivial improvement every day</a></strong></div></blockquote>
<blockquote><img src="https://pbs.twimg.com/profile_images/754577594914308096/YaTIlRf6_400x400.jpg" width="48" align="right"><div>Twitter</div><div><strong><a href="https://twitter.com/marcusdenker/status/1148287564937400321">Marcus Denker on Twitter</a></strong></div><div>“@pharoproject @KentBeck It is harder to state then to convince others about the importance of small change… e.g. “remove needed temp declaration”, trivial, but nobody wants to do it in 19 days: https://t.co/GEuAeXqX6d”</div></blockquote>

**Comment by majella67** [comment]
Hi, new to github. I found the change to make. How do I get it in the Pharo Repository?
