### ISSUE TITLE
Forked processes from a TestResource are prematurely terminated

### ISSUE THREAD

**Issue by ErikOnBike** [guillep/pharo-core#3582]
Any `Process` forked from within a `TestResource>>#setUp` method will be terminated after the first `TestCase` (referring to the test resource) has run. This is because the test resource will create this process within the `TestExecutionEnvironment` belonging to the test case. This particular `ExecutionEnvironment` has the added behaviour of terminating forked processes (to prevent tests from running loose). A relative simple fix would be to execute the resource's `#setUp` method in the `DefaultExecutionEnvironment`. As a consequence of this fix, any forked processes within a test resource need to be terminated explicitly in the accompanying `#tearDown` method of that same test resource. This later would be common practice and does not seem to be a heavy penalty. It can even be argued that a `TestCase` is responsible for its own process cleanup and does not need the magic of the `TestExecutionEnvironment`.

**Comment by ErikOnBike** [comment]
PR contains a TestCase which (when fix is removed) shows the unwanted behaviour of forked processes being terminated.

**Comment by MarcusDenker** [comment]
Pharo 8 has been merged, back port PR is here: https://github.com/pharo-project/pharo/pull/3605

**Comment by MarcusDenker** [comment]
merged in Pharo7, too
