### ISSUE TITLE
Decompilation may signal error

### ISSUE THREAD

**Issue by theseion** [guillep/pharo-core#3608]
Evaluating the below snippet will signal an error in Pharo 8 because the compiled method does not contain any source code (neither in the source files nor in the method trailer). Sending `#ast` or `#sourceCode` will send `#formattedCode` after decompilation, which initiates BlueInk. But BlueInk can't handle AST's without source annotations.
```
(Object class compiler
	source: 'foo self param1: self context';
	compile) ast
```

**Comment by MarcusDenker** [comment]
yes, it looks like that the pretty printer uses information from the existing text... this is not a good idea as the whole point of a pretty printer is to print the AST (e.g. when has been created programmatically).

We should enhance the tests to strip this kind of data from the AST used for testing
