### ISSUE TITLE
Tools->Dependency analyser won't start

### ISSUE THREAD

**Issue by Alisu** [guillep/pharo-core#3617]
In Pharo 8 image, going to tools then clicking on dependency analyser show a popup "instance of ListPresenter did not understand #multiSelection".

**Comment by jecisc** [comment]
@Alisu This will be fixed when we will revert Spec to Spec 1.

In the meantime, you can use it from Calypso.

Right click on a package and select `Browse dependencies`.

**Comment by MarcusDenker** [comment]
see case #3383, too

**Comment by MarcusDenker** [comment]
I close this as a duplicate

**Comment by Alisu** [comment]
Oh my bad didn't see the other.
