### ISSUE TITLE
SequenceableCollection>>#integerAt:put: and SequenceableCollection>>#integerAt: should be removed.

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#3624]
They just wrap `#at:` and `#at:put:`.

**Comment by MarcusDenker** [comment]
maybe this is there to be polymorphic with Bitmap?

**Comment by MarcusDenker** [comment]
but the user seems to only call it on Bitmap, so no

**Comment by svenvc** [comment]
IMO, this can be removed just fine.

Collections are generic, they can contain anything, there is no need for such API

**Comment by MarcusDenker** [comment]
merged PR
