### ISSUE TITLE
SequenceableCollection should implement #add:after: and #add:before:

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#3625]
It is implemented by LinkedList but I think it should be present directly in SequenceableCollection since it is not specific to linked list data structure.

However, the implementation in LinkedList can stay because it seems good.

We just need to have a generic version in SequenceableCollection.

**Comment by juliendelplanque** [comment]
It is also implemented in OrderedCollection by the way.

**Comment by tesonep** [comment]
It is not possible to implement it clean as many sequenceable collections does not grow dynamically (eg: Array). We should split the acces to sequenceable collections and the modification of them. Maybe we require a GrowableCollection concept.

**Comment by juliendelplanque** [comment]
@tesonep I agree.

**Comment by demarey** [comment]
With @Alisu we checked this issue and we think it is not worth it to add  #add:after: and #add:before: to SequenceableCollection.
```Smalltalk
SequenceableCollection subclasses 
 "{ArrayedCollection. Interval. LinkedList. OrderedCollection. ProcessList. RunArray}"
```

#add:after: and #add:before:  are already implemented in `OrderedCollection` and `LinkedList`.
We do not think it has a value to add these methods to other collections: `ArrayedCollection Interval ProcessList`.
What do you think?

**Comment by olekscode** [comment]
I think this issue can be closed

**Comment by MarcusDenker** [comment]
yes, I think so
