### ISSUE TITLE
Improve hex byte printing/parsing

### ISSUE THREAD

**Issue by svenvc** [guillep/pharo-core#3642]
There are multiple places in the image where printing/parsing of byte and byte arrays to/from a standard hex representation are implemented.

Cleanup the base implementation to improve code sharing.

**Comment by svenvc** [comment]
https://github.com/pharo-project/pharo/pull/3645

**Comment by Ducasse** [comment]
Better add Fixes: #3645 in your commit it will close automatically the issues on PR integration.
