### ISSUE TITLE
Iceberg: can not commit a class removal where the class has instance variables

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#3644]
committing class removal seems to be broken:

How to see the problem:
-NOCCompletionTable
-try to commit

--> error "improper store into indexable object"

A string is handed over as the parameter where a collection of string is expected.

We could fix it by doing a change in asMCDefinitionWithoutMetaSide

	instVarNames: mcDefinition instVarNames

it has to be #instVarNames, not instanceVariableString

**Comment by MarcusDenker** [comment]
with this change we were able to commit this PR: https://github.com/pharo-project/pharo/pull/3643

**Comment by jecisc** [comment]
Last week I did this PR to Iceberg: https://github.com/pharo-vcs/iceberg/pull/1258/files

<blockquote><img src="https://avatars1.githubusercontent.com/u/9519971?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-vcs/iceberg/pull/1258">1257-Cannot-change-class-that-have-an-inst-var-of-the-same-name-as-a-class-inst-var- by jecisc · Pull Request #1258 · pharo-vcs/iceberg</a></strong></div><div>Do not give strings but array to MCClassDefinition.
Fixes #1257</div></blockquote>

**Comment by myroslavarm** [comment]
@jecisc oh yes, we were looking in the main pharo repo and didn't find anything. just reviewed your code. hopefully now it can be implemented

**Comment by MarcusDenker** [comment]
I need to commit a removal of a class instance variable again: https://github.com/pharo-project/pharo/issues/4080

We did not manage to get this trivial fix into Pharo8 in 28 days. What can we do?

**Comment by MarcusDenker** [comment]
I tried it again with the new version: works!
