### ISSUE TITLE
Serialization of ExternalAddress is not handled correctly in Fuel

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#3680]
It generates from exceptions to segmentation faults.
Fuel is trying to deserialize its content in invalid addresses.

**Comment by astares** [comment]
@tesonep / @theseion 

Possibly solved in new Fuel already https://github.com/pharo-project/pharo/issues/5870 ?

**Comment by theseion** [comment]
Possible. There are tests for ExternalAddress in 3.0.2. Please provide a failing test case if there's a case I missed. Then open an issue on the Fuel repo (https://github.com/theseion/Fuel/issues).

<blockquote><img src="https://avatars3.githubusercontent.com/u/250711?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/theseion/Fuel">theseion/Fuel</a></strong></div><div>Fuel, the Smalltalk object serializer. Contribute to theseion/Fuel development by creating an account on GitHub.</div></blockquote>
