### ISSUE TITLE
Behavior class misses #compiledMethodAt:ifPresent: method

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#3683]
It implements:
- `Behavior>>#compiledMethodAt:ifPresent:ifAbsent:`
- `Behavior>>#compiledMethodAt:ifAbsent:`

I think `Behavior>>#compiledMethodAt:ifPresent:` should be added it is handy.

**Comment by juliendelplanque** [comment]
I'm doing it.

**Comment by MarcusDenker** [comment]
merged PR
