### ISSUE TITLE
simplify allUnreferencedInstanceVariables

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#3700]
It can now we implemented this way:

allUnreferencedInstanceVariables
	"Return a list of the instance variables known to the receiver which are not referenced"

	^ self allSlots reject: #isReferenced

**Comment by Ducasse** [comment]
I would prefer not to use #isReferenced in core code because it is slower and it will make type inferencer more complex to do.

**Comment by MarcusDenker** [comment]
we can make a block out of if

 ^ self allSlots reject: [:slot | slot isReferenced]

I will do another PR to fix the two cases like that

**Comment by MarcusDenker** [comment]
updated PR is committed
