### ISSUE TITLE
GIFReadWriter>>readExtensionBlock:withFrame: does not recognize Comment Extension.

### ISSUE THREAD

**Issue by EiichiroIto** [guillep/pharo-core#3706]
GIFReadWriter failed when reading GIF file like below.

[clearTurtlesButtonBlack.gif](https://raw.githubusercontent.com/EiichiroIto/Stelo/master/win/Themes/common/clearTurtlesButtonBlack.gif)

For example,

`Form fromFileNamed: 'clearTurtlesButtonBlack.gif'`

Print it above, then occurs 'Unknown GIF Extension: 254'.

"GIF Extension: 254" means Comment Extension, but no codes are in GIFReadWriter>>readExtensionBlock:withFrame: for the extension.

**Comment by Ducasse** [comment]
if you write

Fixes: #number of the issue 
The issue will automatically close when your PR is integrated.

**Comment by Ducasse** [comment]
You probably got an invalid issue because you did not select the pharo remote but yours when you created the branch.

**Comment by EiichiroIto** [comment]
Thank you very much. I will try to add the pharo remote next time.
