### ISSUE TITLE
Calypso menus should have a "Refactoring" sub menu

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3737]
Currently, refactorings are inlined in the menus. It would be better for ergonomy to have a submenu "Refactorings" instead.

**Comment by Lin777** [comment]
I already worked on these changes, I expect revisions to do my PR. You can see how these changes were at: https://medium.com/@cusi.evelyn/adding-shortcuts-and-new-submenu-for-refactorings-ab3e71ac8fa2

<blockquote><img src="https://miro.medium.com/max/1200/1*sOkiC6gJPrMfQfbRE8cU1Q.png" width="48" align="right"><div><img src="https://cdn-static-1.medium.com/_/fp/icons/favicon-rebrand-medium.3Y6xpZ-0FSdWDnPM3hSBIA.ico" height="14"> Medium</div><div><strong><a href="https://medium.com/@cusi.evelyn/adding-shortcuts-and-new-submenu-for-refactorings-ab3e71ac8fa2">Adding shortcuts and new submenu for refactorings</a></strong></div><div>In this post I will show some small improvements that I made on the refactoring access commands.</div></blockquote>
