### ISSUE TITLE
ShiftClassInstaller: Unwind error when migrating instance to variable

### ISSUE THREAD

**Issue by tinchodias** [guillep/pharo-core#3742]
Reproduce with:

~~~
Object subclass: #Hola
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Saludos'.
instance := Hola new.
Object variableSubclass: #Hola
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Saludos'.
~~~

Found in Pharo 8 downloaded yesterday:

> 
> Pharo 8.0.0
> Build information: Pharo-8.0.0+build.417.sha.4ce137f752361d09e53b053fdf0589810922170f (64 Bit)
>

**Comment by MarcusDenker** [comment]
The problem is is #copyObject:to:  

at the beginning:

	newObject := newClass isVariable
		ifTrue: [ newClass basicNew: oldObject size ]
		ifFalse: [ newClass basicNew ].

should check oldClass, too:

	newObject := (newClass isVariable) and: [oldClass isVariable])
		ifTrue: [ newClass basicNew: oldObject size ]
		ifFalse: [ newClass basicNew ].


In this case it will end in the ifFalse: branch, which is ok as "basicNew" works for variable classes of size 0, too.

**Comment by MarcusDenker** [comment]
The change seems to have lots of bad side effects (see failing tests PR)
