### ISSUE TITLE
Feature Request: Debugging vs. optimized runtime code

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#3744]
In 2015 we discussed if it would be possible to have a generally available
mechanism in the standard image:

 To write "debug or log code" in methods which is 
  - by default optimized away and not compiled down to bytecode
  - only activated/compiled when needed to hunt down problems
either depending on global pool constants, flags or other

Unfortunately beside the discussion 
http://lists.pharo.org/pipermail/pharo-dev_lists.pharo.org/2015-June/111037.html
there was no real final solution

Now - a few years later the problem is still not solved. It would be really helpful 
to have debug, tracing or logging code for instance in UFFI calls, finalization calls or 
other. But for the final runtime such code should not eat up any processing time...

Maybe we now have some more possibilities with MetaLinks, included OpalCompiler, ...
and other to find an easy mechanism to support such a feature.

@MarcusDenker  @guillep @estebanlm

**Comment by bencoman** [comment]
This seems reasonable to leave open.  I wonder if a label like "Long term planning" could be used to avoid being staled in the future.

**Comment by guillep** [comment]
I think often about this too. But the "everything is a message" kinda gets in the way of it.
This kind of compile time optimisation require that either we have more static constructs (think of a macro or a static method), or more static analysis during compilation to discern when this can be safely done + looot of metadata to invalidate this when the assumption does not hold anymore.

Imagine you want to optimise away the `log:` sends.
- The system should distinguish the logging logs vs the send to compute logarithms :)
- We should tell the user somehow that this has been optimised away (maybe syntax highlighting)
- If suddenly I define `log:` in my hierarchy, I all the sends to `log:` should be deoptimised

This is a nice topic for a PHEP and looks more like a small project than an actionable issue.
I propose we move it to a wiki with potential projects for people to contribute.
I'm collecting all these.
Could be a great basis for GSOC.
