### ISSUE TITLE
Compiler: add the concept of a productionEnvironment, enable for CompiledMethod

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#3748]
When compiling, there might be the case that the result of the compiler (the compiledMethod) should not be an instance of the class CompiledMethod from the environment 
in which we compile, but from some other environment.

(e.g. imagine you have multiple environments and want to cross cross compile)

This PR adds the concept of a productionEnvironment and enables it for CompiledMethod.
(other use cases might make sense, too, for example all the literals in the CompiledMethod, this is future work but can be done similarly by handing the context into the Scanner)

This is our test for CompiledMethod:

testCompileWithProductionEnvironment
	| environment method return | 
	environment := {#CompiledMethod -> MyCompiledMethodForTesting} asDictionary.
	method := Smalltalk compiler 
					productionEnvironment: environment;
					compile: 'tt ^1+2'.
	
	self assert: method class equals: MyCompiledMethodForTesting.			
	return := method valueWithReceiver: nil arguments: #().
	self assert: return equals: 3.

As one can see, the produces compiled method of the Compiler is an instance of our class.

**Comment by eMaringolo** [comment]
Why "production" environment and not just "compiler" environment?

It could be the case that you compile in a development image on a remote staging enviroment, and "production" could be misleading there.

**Comment by MarcusDenker** [comment]
we have already an environment: the environment that is used to look up all the globals when compiling
(the productionEnvironment falls back to that).

**Comment by dionisiydk** [comment]
> When compiling, there might be the case that the result of the compiler (the compiledMethod) should not be an instance of the class CompiledMethod from the environment
> in which we compile, but from some other environment.

Interesting to see real example where productionEnvironment is not the environment.

**Comment by eMaringolo** [comment]
Why not `targetEnvironment` instead?

**Comment by Ducasse** [comment]
Yes I would prefer too.

**Comment by MarcusDenker** [comment]
We should continue to discuss the naming, but target does not capture it... it's really "the environment with classes for the object the compiler will create"

**Comment by MarcusDenker** [comment]
e.g. what Denis said as a comment of the PR:

"
I think I see.
For example in TelePharo the remote playground doIt's are compiled locally using remote environment for globals. But method is created as local object using local CompiledMethod class.
At the end method is sent to remote side for execution.

In other scenario we would want to use different method class. For example we could copy CompiledMethod and modify its logic for experiment. Then we will need to use it to test compilation
"

**Comment by MarcusDenker** [comment]
(I merge it, we can improve names in a second step.. not happy with productionEnvironment either)
