### ISSUE TITLE
[Calypso] Cannot add methods to class in _UnpackagedPackage

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3750]
```
UndefinedObject(Object)>>doesNotUnderstand: #name
UndefinedObject>>doesNotUnderstand: #name
SycMoveMethodsToClassPackageCommand(SycMethodRepackagingCommand)>>moveMethod:toPackage:
[ :each | 
classPackage := each origin package.
self moveMethod: each toPackage: classPackage.
each tagWith: targetTagName ] in SycMoveMethodsToClassPackageCommand>>execute in Block: [ :each | ...
Array(SequenceableCollection)>>do:
SycMoveMethodsToClassPackageCommand>>execute
[ (extendingPackage notNil and: [ aMethod package ~~ extendingPackage ]) ifTrue: [ ^ (SycMoveMethodsToPackageCommand for: {aMethod} to: extendingPackage) execute ].

(extendingPackage isNil and: [ aMethod isExtension ]) ifTrue: [ (SycMoveMethodsToClassPackageCommand for: {aMethod}) execute ] ] in ClyMethodCreationToolMorph(ClyMethodEditorToolMorph)>>packageEditingMethod: in Block: [ (extendingPackage notNil and: [ aMethod package ...etc...
BlockClosure>>ensure:
ClyMethodCreationToolMorph(ClyTextEditorToolMorph)>>applyChangesBy:
ClyMethodCreationToolMorph(ClyMethodEditorToolMorph)>>packageEditingMethod:
ClyMethodCreationToolMorph(ClyMethodEditorToolMorph)>>tagAndPackageEditingMethod:
ClyMethodCreationToolMorph>>applyChanges
[ self changesAreAboutApply.
applied := self applyChanges ] in [ textMorph hasUnacceptedEdits: true.
[ self changesAreAboutApply.
applied := self applyChanges ]
	on: Error
	do: [ :err | 
		textModel text: self editingText.
		textMorph hasUnacceptedEdits: true.
		err pass ].
applied
	ifTrue: [ textMorph hasUnacceptedEdits: false.
		self textUpdated.
		browser focusActiveTab ]
	ifFalse: [ textModel text: self editingText.
		textMorph hasUnacceptedEdits: true ] ] in 

```

**Comment by dionisiydk** [comment]
Known issue. Description is here https://github.com/pharo-ide/Calypso/issues/395.

**Comment by dionisiydk** [comment]
And here was declined workaround https://github.com/pharo-project/pharo/pull/2195

**Comment by dionisiydk** [comment]
My proposal is to not handle _UnpackagedPackage as a special case. It should be completely normal package

**Comment by MarcusDenker** [comment]
I think #2195 was just declined for Pharo7 late in the release cycle. might be an idea to do it now

**Comment by jecisc** [comment]
Keep

**Comment by guillep** [comment]
This is a real issue, I've been hit by this sooo many times, and once you hit this, your image is completely destroyed and there is no way to put the pieces back. We need to fix it.

> And here was declined workaround #2195

@dionisiydk  the declined change was Pablo's one, the one you did not agree with :).
Your "workaround" was just a comment, there was no PR.

I agree with you in that the unpackaged package should just be a normal package.
But we need a PR...

**Comment by guillep** [comment]
One potential problem happens here. When a new method is created in calypso, calypso tries to categorise it using the `SycMoveMethodsToPackageDefiningClassCommand`. That is trying to "recategorize it". But the method just got created, why recategorising it instead of categorising it well from the first time?

```smalltalk
moveMethod: aMethod toPackage: aPackage
	| existingPackage wasExtension willBeExtension |
	existingPackage := aMethod package.
	existingPackage == aPackage ifTrue: [ ^ self ].
	wasExtension := aMethod isExtension.
	willBeExtension := aPackage ~~ aMethod origin package.
	aPackage addMethod: aMethod.
	willBeExtension ifTrue: [ 
		aMethod tagWith: ('*' , aPackage name) asSymbol ].
	wasExtension ifFalse: [ ^ self ].
	aMethod untagFrom: ('*' , existingPackage name) asSymbol.
	self tagMethod: aMethod
```

Then here, adding a method in an class that is unpackaged yields `nil` for `aMethod package`, and that is the error of the original issue. That brings us back to Pablo's solution #2195.
 - a method's package is not properly defined: `packageFromOrganizer:` is not the nicest thing
 - somehow the method did not get into the unpackaged package since the beginning either
