### ISSUE TITLE
make code completion experiment the default (for feedback)

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#3802]
We have a first version of code completion using the RB AST, we should make it the default to get feedback

**Comment by MarcusDenker** [comment]
the simplest way to do it: we can have NECController just register the subclass for now
(with a comment as this is a hack)


register
	"just for testing: we register the subclass here to test it"
	RubSmalltalkEditor completionEngine: TestCompletionController

**Comment by astares** [comment]
@MarcusDenker 

Why not do it in BaselineOfIDE>>additionalInitialization where already other initializations are done?

**Comment by MarcusDenker** [comment]
Yes, I will add new issue tracker entry to do that.
