### ISSUE TITLE
Add release test to ensure we do not have shadow variable in the image

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3838]
To ensure what James removed is not introduced again.

**Comment by jecisc** [comment]
Here is the test. I cannot submit it until one of James PR is integrated. 
```Smalltalk
testNoShadowVariablePresentInTheImage
	| variables |
	self
		assertEmpty:
			(SystemNavigation default allClasses
				select: [ :class | 
					variables := Set new.
					class methods do: [ :method | variables addAll: method tempNames ].
					class blockNodes
						do: [ :block | 
							variables
								addAll: block temporaryNames;
								addAll: block argumentNames ].
					(variables intersection: class allInstVarNames) isNotEmpty ])
```

**Comment by astares** [comment]
@jecisc 

I often write such release tests with a local variable like:
```Smalltalk
|violations|
violations := (Expression to query bad artifacts).
self assertEmpty: violations
```
This eases debugging when there are actually violations and makes it clear which are the bad introductions. Maybe we can change to a similar pattern for consistency and easier finding in case the test is failing

**Comment by jecisc** [comment]
In a PR I changed the method to ensure there is not violation to a lint to have a better output. 

It should print the violated rule and the list of violations.
