### ISSUE TITLE
CI Failure: lines in Rubric are empty

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#3879]
OrderedCollection(Object)>>errorSubscriptBounds:
OrderedCollection>>at:
OrderedCollection(SequenceableCollection)>>last
RubParagraph>>extent
Message>>sendTo:
[ aMessage sendTo: next ] in RubOpeningClosingDelimiterDecorator(RubParagraphDecorator)>>doesNotUnderstand: #extent in Block: [ aMessage sendTo: next ]
BlockClosure>>on:do:
RubOpeningClosingDelimiterDecorator(RubParagraphDecorator)>>doesNotUnderstand: #extent
Message>>sendTo:
[ aMessage sendTo: next ] in RubExtraSelectionDecorator(RubParagraphDecorator)>>doesNotUnderstand: #extent in Block: [ aMessage sendTo: next ]
BlockClosure>>on:do:
RubExtraSelectionDecorator(RubParagraphDecorator)>>doesNotUnderstand: #extent
Message>>sendTo:
[ aMessage sendTo: next ] in RubCurrentLineBarDecorator(RubParagraphDecorator)>>doesNotUnderstand: #extent in Block: [ aMessage sendTo: next ]
BlockClosure>>on:do:
RubCurrentLineBarDecorator(RubParagraphDecorator)>>doesNotUnderstand: #extent
RubEditingArea(RubAbstractTextArea)>>updateBottomFromParagraph

**Comment by MarcusDenker** [comment]
we could try to check for empty lines:

extent
	self actualWidth ifNil: [ ^self minimumExtent ].
	self lines ifEmpty:  [ ^self minimumExtent ]. "workaround: lots of crashes on the CI"
	^ (self actualWidth + self margins left + self margins right)
				@ (self lines last bottom - self lines first top + self margins top + self margins bottom)

**Comment by jecisc** [comment]
Something weird is that it always happens in tests and never when we use Rubric. 

This might be caused by a race condition or something like that and maybe it's the root of more problems.

**Comment by MarcusDenker** [comment]
yes, but now the CI fails every time with something. We need to add workarounds or else we can just stop using the CI
