### ISSUE TITLE
Remove the stack pre debuger

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3880]
See: http://forum.world.st/Changes-proposal-on-Pre-debugger-td5101059.html

**Comment by jecisc** [comment]
I clicked enter too soon. It's now fixed bot ;)

**Comment by MarcusDenker** [comment]
In the past people said that they use the feature a lot that you click in the stack and the debugger opens in the right method

**Comment by jecisc** [comment]
I really fail to understand this.

You can do the same thing without the pre debugger in the same amount of click. 

With pre debugger:

![2019-07-11 11 21 04](https://user-images.githubusercontent.com/9519971/61038863-0bea3680-a3ce-11e9-8f0d-2ea6cefa94ac.gif)

With full debugger:

![2019-07-11 11 22 22](https://user-images.githubusercontent.com/9519971/61038953-33d99a00-a3ce-11e9-9c53-2a370984f648.gif)

Exactly the same amount of click. 

Am I missing something?

**Comment by bencoman** [comment]
you are right. its worth a try.
