### ISSUE TITLE
[Pharo 8 Release] Review Gemstone port modifications

### ISSUE THREAD

**Issue by bencoman** [guillep/pharo-core#3894]
@jgfoster is experimenting with a port of Pharo-minimal to run on Gemstone.  I think this has the potential to be of great value to Pharo and we should do what we can to support this.  James could just work in a fork (and that remains a feasible backup plan), but there is value in keeping his work as close to Pharo trunk as possible (and some good general improvements have already been merged).  

However some changes may be more contentious than others, but what really matters is what we take forward from Pharo 8 Release.  To facilitate James' progress while diffusing tension for issues that can not be "quickly" resolved, an option is to provisionally approve PRs and track here to review again prior to Pharo 8 Release.  Best effort should be made to resolve individual issues and minimize this list so it serves as list of potential "blockers" for a Gemstone port.

**Comment by bencoman** [comment]
Some background from James compiled from comments elsewhere...
>  My situation is this is a private project [suggested by Pharo leaders not Gemstone management] and I'm trying to move as quickly as possible to discover what issues exist.

> I could, each time I find a roadblock, take the weeks necessary to modify GemStone and seek internal approval for that change and wait for it to be built into the product. Or I could take a couple hours to modify a few Pharo methods to further my exploration and discover the next issue. Perhaps I should do this on a fork of Pharo, but I have a strong aversion to long-running branches. In my experience is it a bad engineering practice to work on out-of-date code (I'm a strong believer in continuous integration). So, I'm trying to stay as close to the current Pharo8.0 as possible.

> I invite the Pharo team to view my proposed changes as limited to the places where I made them. With these changes I'm able to compile 1530 classes and ~25,000 methods into GemStone. There are many (thousands?) of other places in Pharo code that I'm not changing. Would they need to change eventually? Probably not. Think of what I'm doing as an exploration with various possible outcomes, including the following:

> - I abandon the project and nothing more is asked of Pharo;
> - I eventually demonstrate the ability to run a "minimal" image and those who want to use GemStone can "downgrade" their code to conform to GemStone's syntax; or
> - The project is such an overwhelming success that GemStone's management is convinced to completely adopt every new Pharo feature so that everything is 100% portable.

> Naturally, we hope for the last outcome, but without knowing what issues will arise it is difficult to get there. My approach has been to "work around" the issues in the simplest way possible (without major compromise). As we learn more we can refine the process and modifications to GemStone are a likely part of that refinement.

**Comment by bencoman** [comment]
One difference between Pharo and Gemstone is handling of array literals.  James has worked around this by modifying his export code so that it rewrites array literals.  Just recording originals issues for posterity:
* #3843 Make a few binary selectors in literal Array into explicit Symbols 
* #3845 Use string literal to define a few FFI calls

**Comment by jgfoster** [comment]
The GemStone issue is being tracked as issue 48212. (This refers to an internal database, so I'm mostly recording it here just to allow me to track back without having to do a more complex search.)
