### ISSUE TITLE
Cancel buttons are missing on some iceberg windows

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#3900]
So, I cannot close them properly..
![image](https://user-images.githubusercontent.com/4706329/61115324-82506c80-a492-11e9-8b94-698c9221dcd0.png)

**Comment by VincentBlondeau** [comment]
ESC key works randomly. Maybe an issue on the focus too?

**Comment by jecisc** [comment]
I did a PR already with an issue on the Iceberg repository: https://github.com/pharo-vcs/iceberg/pull/1255

**Comment by MarcusDenker** [comment]
This seems to be fixed, I have a button in pharo8 to cancel
