### ISSUE TITLE
[ICEBERG]The arrow that indicate there are more choices is not displaying

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#3901]
And it overloaded by the text of the field.
![image](https://user-images.githubusercontent.com/4706329/61115465-ce9bac80-a492-11e9-894a-630d34caaeb7.png)

I know this issue could exist in other repos but I do not know where to look

**Comment by MarcusDenker** [comment]
This is now fixed
![Untitled](https://user-images.githubusercontent.com/413057/111289131-21a10c00-8645-11eb-9b01-6201a74f334e.jpg)
