### ISSUE TITLE
Undo works incorectly in the debugger

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#3903]
And the code is completely unusable and you have to write it again...

**Comment by StevenCostiou** [comment]
This seems to be a problem in the code presenter @estebanlm doing cmd+z in the playground as well as in the debugger produce strange effects and loss of code.

**Comment by guillep** [comment]
It works for me on `Pharo-9.0.0+build.1042.sha.28c635372657d5916fb4221603a51151de85de90 (64 Bit)`.
Could you give some more details?

**Comment by StevenCostiou** [comment]
Starting from there, where I put to new lines in a code I was debugging:
![Screenshot 2021-01-13 at 10 09 32](https://user-images.githubusercontent.com/26929529/104430789-6fd35980-5587-11eb-8951-17e6ed90d44d.png)

CMD+Z once:
![Screenshot 2021-01-13 at 10 09 44](https://user-images.githubusercontent.com/26929529/104430815-7792fe00-5587-11eb-816f-6a4a40b88237.png)

CMD+Z twice:
![Screenshot 2021-01-13 at 10 09 54](https://user-images.githubusercontent.com/26929529/104430829-7cf04880-5587-11eb-9be1-49ef35b76ab8.png)

CMD+Z third time:
![Screenshot 2021-01-13 at 10 10 06](https://user-images.githubusercontent.com/26929529/104430850-84175680-5587-11eb-97bb-4474efe22708.png)

CMD+Z fourth time:
![Screenshot 2021-01-13 at 10 10 15](https://user-images.githubusercontent.com/26929529/104430865-8974a100-5587-11eb-8f9e-0b6404cd4ce7.png)

CMD+Z 3-4 more times:
![Screenshot 2021-01-13 at 10 10 29](https://user-images.githubusercontent.com/26929529/104430893-91ccdc00-5587-11eb-90c5-966726f992f9.png)

1) It is not obvious what happens, and at least the third time is buggy (inserts an additional `Object` string)
2) It looks like it also remembers all the previous states of the code presenter, that was changed becaused the context changed (maybe here it should be the responsibility of the debugger to reset that state at each new context change in the stack)

There is a similar problem in the playground, I can check.

**Comment by VincentBlondeau** [comment]
![NTrxboN7wQ](https://user-images.githubusercontent.com/4706329/104431694-77473280-5588-11eb-868a-5e6d565548c9.gif)

**Comment by VincentBlondeau** [comment]
Same can be reproduced in the Playground

**Comment by Ducasse** [comment]
I think that there is conceptual bug in the Undo in general. We discussed about it with julien and cyril. But we never got the time to fix it.

**Comment by rolandbernard** [comment]
The main problem with the Undo currently is that inserting new lines and tabs is not inserted into the history. If that happens, using the Undo and Redo functionality is pretty much impossible. Writing any two lines and then adding a new line in between them will break the history. Similarly, inserting a tab anywhere will result in the same problem.

https://user-images.githubusercontent.com/18496639/124363840-1e567e00-dc3e-11eb-8cbc-fa191e1b912c.mp4


https://user-images.githubusercontent.com/18496639/124363849-257d8c00-dc3e-11eb-9e72-3bcbd86787ab.mp4

**Comment by MarcusDenker** [comment]
merged the PR
