### ISSUE TITLE
Unable to start Pharo 8 64 bits with latest VM (Linux)

### ISSUE THREAD

**Issue by gcotelli** [guillep/pharo-core#3912]
I've just downloaded the latest version using:
```bash
curl https://get.pharo.org/64/80+vmLatest | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3084  100  3084    0     0   1994      0  0:00:01  0:00:01 --:--:--  1994
Downloading the latest 80 Image:
    http://files.pharo.org/get-files/80/pharo64.zip
Pharo.image
Downloading the latest pharoVM:
	http://files.pharo.org/get-files/80/pharo64-linux-latest.zip
pharo-vm/pharo
Creating starter scripts pharo and pharo-ui
On a 64-bit system? You must enable and install the 32-bit libraries
   Please see http://pharo.org/gnu-linux-installation for detailed instructions
```
And now when I run the usual start script (`./pharo-ui` or `./pharo-ui Pharo.image`) nothing happens:

![Pharo-8](https://user-images.githubusercontent.com/2106744/61144920-9a34ea00-a4ac-11e9-9269-0f4938bb0dc6.gif)

There's no error, log or any clue of what's happening.

OS Info: 
```
uname -a
Linux jarvis 4.15.0-52-generic #56~16.04.1-Ubuntu SMP Thu Jun 6 12:03:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by gcotelli** [comment]
If I use the stable VM instead of the latest one it's working (`curl https://get.pharo.org/64/80+vm | bash`), so it's seems to be a problem with the latest VM.

**Comment by gcotelli** [comment]
Pharo 7 - 64 bits on Linux shows the same behavior using the latest VM.

**Comment by bencoman** [comment]
Do you have a VM commit-hash that might be reported to vm-dev mail list for the Squeak guys to try?

**Comment by gcotelli** [comment]
No. I don't get any kind of output, so unless there's some kind of way to get this info without running an image I don't know how to gather this info

**Comment by MarcusDenker** [comment]
Hello,

I tested with both Pharo8 and Pharo9 and it seems to work now
