### ISSUE TITLE
Renaming a class raises a DNU

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3993]
handleClassRenamed: anAnnouncement
	| items selectedIndex |
	items := self messages
		collect: [ :rgMethod | 
			| interestedClassName interestedClass |
			interestedClassName := anAnnouncement oldName.
			interestedClass := anAnnouncement classRenamed.
			rgMethod isMetaSide
                               ^^^^^^^^^^^^^^^^^^^^^^^^ 

				ifTrue: [ interestedClassName := interestedClassName , ' class'.
					interestedClass := interestedClass classSide ].
			rgMethod parentName = interestedClassName
				ifTrue: [ (interestedClass >> rgMethod selector) asFullRingDefinition ]
				ifFalse: [ rgMethod ] ].
	selectedIndex := messageList selectedIndex.
	self messages: items.
	self setSelectedIndex: selectedIndex

**Comment by Ducasse** [comment]
Apparently isMetaSide is not polymorphic between compiled method and RGElementDefinition.
Only RGElementDefinition defines isMetaSide. 
I suggest to deprecate isMetaSide and use isClassSide.

Now I do not understand why this bug shows up now.

**Comment by gcotelli** [comment]
There are other senders of #isMetaSide , so probably them are broken too.

**Comment by MarcusDenker** [comment]
duplicate of https://github.com/pharo-project/pharo/issues/4268
