### ISSUE TITLE
Temporaries read before written Rule => potentially. Add explanation

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#4002]
The Temporaries read before written Rule gives the impression that it knows that temp is not written in a case where the assignement is a block

| temp |
self doSomething: [ temp := 1].

We should as a first step make clear in the description that this rule has lots of false positives.

I am even thinking that we should have a more stricter rule and only complain if there is no assignment at all.

**Comment by myroslavarm** [comment]
There are two different rules: temps read before written is one, and temps not read or not written is another. The code you wrote invokes a critique with the second one, not the first one, i.e. it just indicates you've not used your temp var in any meaningful way. Maybe the message of the critique should be renamed to make it more clear, but the critique itself makes sense.
For implementations, check out RBTempsReadBeforeWrittenRule and GRTemporaryNeitherReadNorWrittenRule.
