### ISSUE TITLE
$x nextObject crashes Pharo too

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#4011]
A VM related problem was discussed for Squeak:

http://lists.squeakfoundation.org/pipermail/vm-dev/2019-July/031175.html

but it crashes Pharo too.

**Comment by astares** [comment]
still valid

**Comment by kasperosterbye** [comment]
From what I gather from the system -`nextObject` works for all but`Character`,`SmallInteger` and`Float` (I only tried for `SmallFloat64`). `SmallInteger` implements the`nextObject` method using:

```smalltalk
nextObject
	"SmallIntegers are immediate objects, and, as such, do not have successors in object memory."

	self shouldNotImplement 
``` 
Removing the implementation of`nextObject` in`SmallInteger`, to use the same as in`Object` makes the crash also happen for SmallIntegers.

I suggest to implement the`nextObject` method in Float and Character the same way as in SmallInteger to prevent this crash.
