### ISSUE TITLE
Measure the use and usefulness of literal string sharing in literal frame

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4019]
I would like to know how many methods and which ones are having two similar string literals and perform an == or =. 
(besides test methods). 
Because I would like to know how we can disable it in Doit.

**Comment by Ducasse** [comment]
And I would like to know the impact on the JIT and friends.

**Comment by MarcusDenker** [comment]
If you implement in ByteString:

literalEqual: aLiteral
	^self == aLiteral

**Comment by MarcusDenker** [comment]
I will do a PR to see if there will be any problems.
