### ISSUE TITLE
PluggableSet class>#integerSet should be in instance creation category

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#4021]
PluggableSet class>#integerSet  is categorised as "accessing", this is not nice as is is constructor. It should be in something like "instance creation" category.

(This is a very trivial issue perfectly do be done by a beginner)

**Comment by jecisc** [comment]
It can even be done by editing the file in github directly!

**Comment by MarcusDenker** [comment]
fixed as part of another PR
