### ISSUE TITLE
some callers of compiledMethodAt:ifPresent:ifAbsent: do not need ifAbsent: part

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#4025]
some senders of compiledMethodAt:ifPresent:ifAbsent: use a empty block or nil as the ifAbsent: argument.

Now that we have  #compiledMethodAt:ifPresent:, these callers can just use that method (that is, one can delete the "ifAbsent: nil" or "ifAbsent: []".

(This is a very simple issue, nice to do for a beginner)

**Comment by bencoman** [comment]
It might be good to list a few beginner issues in the weekly report.

**Comment by MarcusDenker** [comment]
the weekly report is a unchanged plugin. this would require to a) fork the javascript code and b) somehow publish it in a way that it can be installed as a github service. I fear this is too much to ask.

If someone wants to implement GitHub bots, a more important one would be one that checks if a committer has signed the license agreement.
