### ISSUE TITLE
Support Unix domain sockets.

### ISSUE THREAD

**Issue by PierceNg** [guillep/pharo-core#4046]
The socket plugin already supports Unix domain sockets. I have code for Pharo 2.0 that I will adapt to current Pharo.

**Comment by astares** [comment]
@PierceNg Still relevant?

**Comment by PierceNg** [comment]
On Mon, Apr 06, 2020 at 05:20:35AM -0700, Astares wrote:
> @PierceNg Still relevant?

Yes, still relevant. I'll get the code ready this month or close it if I
cannot.

**Comment by Ducasse** [comment]
Hi pierceNG

You can also ask the consortium guys for help. 
Do not show for something perfect. 
You can publish the code in a PR of headless and ask feedback for example. 

S.

**Comment by guillep** [comment]
It's not clear to me if the code finally arrived or not.
If not, this issue looks more like a small project than an actionable issue.
I propose we move it to a wiki with potential projects for people to contribute.
I'm collecting all these.
Could be a great basis for GSOC.

**Comment by svenvc** [comment]
I was not aware of this issue (sorry), but we (@JurajKubelka and me) recently added some support for Unix Domain Sockets to the Zinc HTTP Components project and got the client side working, but got stuck on the server side part which we wanted to be able to write unit tests.

There is a new package https://github.com/svenvc/zinc/tree/master/repository/Zinc-HTTP-UnixSocket.package

You can check some of our commits from Aug 30 https://github.com/svenvc/zinc/commits/master or some of the closed PRs https://github.com/svenvc/zinc/pulls?q=is%3Apr+is%3Aclosed which contain conversations about this subject.
