### ISSUE TITLE
Transcript should be able to clear the contents of the transcript

### ISSUE THREAD

**Issue by pdebruic** [guillep/pharo-core#4074]
```
Transcript clear 
```

just resets the stream position & clears the display without actually clearing the contents of the stream. 

So one could end up with a 1.25GB transcript without realizing it if they were abusing it while debugging something or in some other way.

**Comment by bencoman** [comment]
@pdebruic, Since you have your head in the issue, could you propose a solution in a PR?
At a guess Transcript>>clear rather than #reset the existing stream, create a new one.

**Comment by svenvc** [comment]
The default Transcript in a normal interactive image is an instance of ThreadSafeTranscript, which is indeed a bit weird (in its implementation).

What you report is correct: the internal stream can only grow and does not shrink. It does get reset at each step. When there is an open Transcript window at least. If there is none, it keeps on collecting. You also need to call endEntry enough.

An in-image Transcript is by definition a place where you dump output to, so it collects.

It is possible to replace the Transcript, for example by NonInteractiveTranscript or its subclass, DailyNonInteractiveTranscript. There could be others (there is a TTranscript trait).

I am not defending the current situation, just explaining it a bit as far as I understand it.

Other than that, I would say that clear should only reset when the stream is reasonably small, else the large stream should be shrunk.

**Comment by pdebruic** [comment]
Hi - I ran into this again this week. 4GB this time.  The UI does some weird stuff at that size.  

@svenvc - when you say "clear should only reset when the stream is reasonably small, else the large stream should be shrunk" I'm not sure what you mean.  

How small is reasonably small? 

What is the benefit of shrinking vs just replacing the stream with a new empty one? 

The '#reset' method in the WriteStream (as sent in ThreadSafeTranscript>>#clear) doesn't empty the collection and doesn't move the write limit back to 0.  Because of that the stream in the transcript stays large once it gets large for the life of the image. 

I'd be happy to submit a PR that does change the #clear method to send something that does wipe the contents of the stream, whether by replacing it entirely or emptying the one thats there.

**Comment by svenvc** [comment]
OK, try that, replacing the whole stream. But mind the weird implementation and mixing with UI behaviour.

**Comment by pdebruic** [comment]
Sorry - what do you mean by "mind the weird implementation and mixing with UI behaviour."


Is there something I should expect to go wrong or are you referring to the weird UI behavior I mentioned in my note an hour ago? 

So far so good on the stream replacement, but then the Transcript doesn't get continual use in my image that I can see.

**Comment by svenvc** [comment]
If you think you understand all implications of changing how that class works, fine for you, I don't.

I said before that I think that you are not using it correctly (without a UI nothing happens and you just collect forever, that is by definition/design).

But fixing clear a bit could be a good idea, let's see.

**Comment by guillep** [comment]
Hi @pdebruic has there been movement on this?

**Comment by pdebruic** [comment]
Hi - Sorry for the delay.  I added this method to my image, and it seems to work fine.

```
ThreadSafeTranscript>>clearEverything
"	identical to #clear but installs a new stream instead of starting it at the beginning"	
	self 
		critical: [ 
			deferredClear := true.
			deferredEndEntry := false.
			stream := String new writeStream. ]
```
