### ISSUE TITLE
remove the class instance var in NECController

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#4080]
Sadly I can not commit due to us not being able to get a fix into Pharo that was fixed a long time ago.

see #3644

**Comment by MarcusDenker** [comment]
the issue referenced described a *trivial* fix, 28 days (!!!!) ago.

**Comment by jecisc** [comment]
I did a PR the 21 June https://github.com/pharo-vcs/iceberg/pull/1258
But it was not yet integrated.
