### ISSUE TITLE
Epicea mix packages and tags

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4082]
In an image, I created a package `Tool-CriticBrowser-TestResources` and worked on it. At some point, my image crashed. 

I used Epicea to get back my changes but Epicea did not create a package `Tool-CriticBrowser-TestResources`. Instead, it added a tag `TestResources` to the package `Tool-CriticBrowser.

Maybe this is related to https://github.com/pharo-project/pharo/issues/4014

**Comment by tinchodias** [comment]
Related to #6519

**Comment by jecisc** [comment]
Fixed!
