### ISSUE TITLE
Commit should have been implemented in IceUnknownCommit

### ISSUE THREAD

**Issue by jgfoster** [guillep/pharo-core#4088]
In Pharo build 453.sha.43f21722, select any package and attempt to commit:

![image](https://user-images.githubusercontent.com/1577872/61814994-207ef380-adfe-11e9-9889-1309311b1e45.png)

**Comment by bencoman** [comment]
Hi James,

Rather than "any package", can you specify the steps to reproduce one
concrete example in a fresh image.
This will help co-ordinate multiple people working on the same issue.

Also can you test that sequence in latest build 561?

cheers -ben

**Comment by jgfoster** [comment]
The problem still exists in build 561 with AST-Core (and every other package that I tried). I'm not sure what other steps I can provide: in a brand new image, open a System Browser, right click on any package, select Commit, and see walkback. If Commit works for others then what is wrong with my setup? What is IceUnknownCommit?

My workaround is to manually edit files in Git, so it isn't a significant burden.

**Comment by jgfoster** [comment]
It appears that this happens if the image is launched from bootstrap-cache.
