### ISSUE TITLE
add allUnsentMessages to RPackage

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#4118]
we have #allUnsentMessages for classes, but it would be nice to get a list of all unsent methods on RPackage.

allUnsentMessages
	^SystemNavigation new allUnsentMessagesIn: (self methods collect: [ :cm | cm selector ])

(even though I do not like the name of the method, as a first step i would just add it as we use the bad name already for classes)

**Comment by myroslavarm** [comment]
PR : https://github.com/pharo-project/pharo/pull/4125

**Comment by MarcusDenker** [comment]
merged
