### ISSUE TITLE
Use WeakSlot in the system

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4127]
Currently, weak arrays are used in the system sometimes when you only need one entity. 

We should use WeakSlot and create a package System-Slots. 

Example: BufferCache in BalloonEngine

**Comment by astares** [comment]
@jecisc still valid?

**Comment by MarcusDenker** [comment]
This is still valid, but not really a good issue tracker entry... and we do use it now at least in one case :-)

I close this
