### ISSUE TITLE
Many font TextStyle comments are DNU

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4135]

**Comment by Ducasse** [comment]
Mainly because fontReference lost the method #name.
We should add tests for this part of the system.

**Comment by hilaire** [comment]
I don't see any FontStyle class in P8. What am I missing?

**Comment by Ducasse** [comment]
Argh I'm stupid I should have been much more precise. I'm looking for them. 
I think that this is also because some code relied on name in Object and not test. 
I will check.

**Comment by Ducasse** [comment]
I think that writing some tests would help.

FontSet class >> fontName
	^ self name asSymbol

**Comment by Ducasse** [comment]
I found it 

TextStyle default fontNames
and friends
TextStyle default fontNamesAndSizes

TextStyle default fontNamed: 'TimesRoman10'

**Comment by hilaire** [comment]
@Ducasse 
Questions:
1. Should we use famillyName instead of name message?
2. Tests on name message misuses or TextStyle?

**Comment by Ducasse** [comment]
I do not know. 
May be fontName. 
In fact we should add tests to cover such part of the system.

**Comment by hilaire** [comment]
What about opening another issue to address lack of documentation and tests in the Text-Core package?

**Comment by Ducasse** [comment]
Sure :)
