### ISSUE TITLE
instVarNames is not including instance variables coming from Stateful traits

### ISSUE THREAD

**Issue by gcotelli** [guillep/pharo-core#4149]
For example, `TextPresenter` is using `TSpecHaveWrappingScrollBars` that includes a `wrapScrollBars` slot, but 
`TextPresenter superclass instSize` >>	40
`TextPresenter instSize` >> 42 "Seems to be considered here, but:"
`TextPresenter instVarNames` -> #(#scrollValue)

This is breaking Fuel serialization because `ClassDescritpion>>instanceVariableNamesDo:` uses `instSize` to iterate over the variables returned by `instVarName`, so you get a `SubscriptOutOfBounds` error.

**Comment by jecisc** [comment]
Seems linked to https://github.com/pharo-project/pharo/issues/3546 and https://github.com/pharo-project/pharo/issues/3520

**Comment by MarcusDenker** [comment]
I adde a PR that we might consider: https://github.com/pharo-project/pharo/pull/4367

The idea is that #instVarnames should return #slots, not #localSlots.

**Comment by MarcusDenker** [comment]
This is now fixed
