### ISSUE TITLE
Connection closed while waiting for data -- error from Zinc still in Pharo 8

### ISSUE THREAD

**Issue by fuhrmanator** [guillep/pharo-core#4150]
Some weeks ago I posted http://forum.world.st/Re-Strange-Connection-closed-while-waiting-for-data-Zinc-error-td5100085.html with no replies.

When I use a web server running on localhost, I get the crash as mentioned. 

Here is a simple(ish) way to recreate:
- clone the repo at  https://github.com/plantuml/plantuml-server
- install Java
- install maven
- In the clone directory, run: 
`mvn jetty:run`

In Pharo, it's just: 
```Smalltalk
ZnEasy getPng: 'http://localhost:8080/plantuml/img/IzIrIm80'.
```

**Comment by kasperosterbye** [comment]
I reposted this issue in Zinc:
https://github.com/svenvc/zinc/issues/102
I suggest to close it here.
