### ISSUE TITLE
Defaults on 4K Linux display result in user interface that is too small

### ISSUE THREAD

**Issue by nrnrnr** [guillep/pharo-core#4156]
The default sizes of the fonts and the user-interface elements are chosen such that on a 4K (UHD) display, the launcher and the working image are so small as to be very hard to use (at least for those of us with eyes over 50).  As it is, I have to use `xrandr` to adjust my display to make Pharo usable.  It would be ideal if the launcher were to consult the X server about pixels and physical dimensions and to make choices accordingly.

I'm using Pharo 7.0 (stable) on 64-bit Debian Linux 10 (buster).  The key information from `xdpyinfo` is as follows:

````
screen #0:
  dimensions:    3840x2160 pixels (604x340 millimeters)
  resolution:    161x161 dots per inch
````

**Comment by StephanEggermont** [comment]
These issues are only going to increase, as the size of monitors/tv's continues to grow, and the resolution of mobile devices also. 

screen #0:
  dimensions:    3840x2160 pixels (1016x571 millimeters)
  resolution:    96x96 dots per inch

**Comment by MarcusDenker** [comment]
This is now fixed in Pharo9
