### ISSUE TITLE
glmSubscriptions is deprecated and its three users can be rewritten as subscriptions

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4157]
glmSubscriptions is deprecated and its three users can be rewritten as subscriptions
No stupid robot you will not bark!!!

**Comment by Ducasse** [comment]
In fact, there are no senders in the image since the other senders are on GLMAnnouncer and not Announcement.

**Comment by MarcusDenker** [comment]
yes, this is internal to GLMAnnouncer, I think we can let it like this.

**Comment by Ducasse** [comment]
Yes I fixed the other users and integrated the extensions
