### ISSUE TITLE
Less Transcript hardcoded references

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4161]
(SystemNavigation default allGlobalRefsOn: #Transcript) 
	reject: [ :each | each package name = #Kernel ]

>>> 118 cases and many are not good.

**Comment by Ducasse** [comment]
methodWithTranscript
	Transcript show: 'something'

testTranscriptPrinting
	self runSimulated: [ self methodWithTranscript ]

To me, this is not a real test. No explicit assertion

**Comment by astares** [comment]
@VincentBlondeau @Ducasse Still relevant?

**Comment by VincentBlondeau** [comment]
@astares I think they should still be some of them

**Comment by Ducasse** [comment]
Yes it would be good to reduce their number. I will tag it as easy so that people are not afraid 
to start contributing.

**Comment by GeraldineGalindo** [comment]
Good night, on branch #9302 I made some refactorings based on previous code reviewing PR https://github.com/pharo-project/pharo/pull/4445, in the beginning, the Transcript cases were 32, in this change are 23, I will be attentive to any observation, or suggestion, thanks!!

**Comment by guillep** [comment]
Still 36 of them, some should be super easy to fix.
