### ISSUE TITLE
(Pharo 7.0.3) StdioStream(Object)>>doesNotUnderstand: #tab

### ISSUE THREAD

**Issue by dalehenrich** [guillep/pharo-core#4169]
The following workspace illustrates the issue:
```
STON 
	put: { 7 } 
	onStreamPretty: Stdio stdout
```

**Comment by dalehenrich** [comment]
Once you get past the missing tab message you aren't completly out of the woods. If you want the STON output to be correctly display on stdout (on Ubuntu 16.04) you have to arrange for STONWriter to use `String lf`, instead of the default `String cr` --- if you don't, the output is pretty much scrambled ...

**Comment by dalehenrich** [comment]
FWIW, this implementation satisfies my needs:
```smalltalk
tab
	^ self nextPutAll: String tab
```

**Comment by akgrant43** [comment]
As with #4173 , take a look at wrapping stdout with a `ZnCharacterWriteStream` and `ZnNewLineWriterStream`.

**Comment by dalehenrich** [comment]
@akgrant43 thanks a lot ... 

Is there a reason that Stdio>>stdout and friends don't return character streams, themselves? Needing direct access to the binary seems to be the minority use case ... and given the fact that the stream mostly works as a character stream, misleads one into thinking that one shouldn't have to wrap it with another stream ...

Ah well, I will go ahead and use your suggestion ... I appreciate your help.

**Comment by akgrant43** [comment]
Hi Dale,

The general approach adopted by Pharo (partly in Pharo 7 and more completely in Pharo 8) is to wrap streams to add the required functionality.  At the bottom, all file and stdio streams are binary.

When you do something like:

```
'my.file' asFileReference readStreamDo: [ :stream |  stream doStuff ]
```

You're actually getting a ZnCharacterReadStream on a ZnBufferedReadStream on a BinaryFileStream.

The old `FileStream` hierarchy has been deprecated.

Cheers,
Alistair

**Comment by akgrant43** [comment]
P.S. the default stdio streams are binary because we don't want to preclude reading and writing binary streams.
