### ISSUE TITLE
Double-click on a String containing quote does not work correctly

### ISSUE THREAD

**Issue by SergeStinckwich** [guillep/pharo-core#4188]
Type in a Playground : ``"'123'"``
then double-click beetwen ``'``and ``"``, then the selection is not correctly done.

![Screenshot 2019-08-04 at 19 23 18](https://user-images.githubusercontent.com/327334/62427609-5a4cd580-b6ed-11e9-86d3-614642489302.png)

**Comment by myroslavarm** [comment]
seems it works well now. i think this should be closed @SergeStinckwich

**Comment by SergeStinckwich** [comment]
Still does not work. Click on the second `'` and `"`. For the first one, it works.

**Comment by myroslavarm** [comment]
i was trying it on P9... your report is P8, right?

**Comment by SergeStinckwich** [comment]
No I try on P9. Did you try correctly ? Double click betwen the second '" not the first one.

**Comment by myroslavarm** [comment]
Yes, i did it between the second one. For me the selection looks like this:
![image](https://user-images.githubusercontent.com/24677542/78014733-a74e7d80-7348-11ea-985a-b23a3430c1c2.png)
However, i do have your case AFTER i put a newline, but that seems reasonable to me in that case? Because it selects everything you have after...

**Comment by SergeStinckwich** [comment]
Normally, if you double click either one first or second, you should have '123' selected.

**Comment by SergeStinckwich** [comment]
If you try on "123", 123 will be selected.

**Comment by myroslavarm** [comment]
you might be right but to me it makes total sense intuitively that
1. if you click on `123` you get `123`
2. if you click between the first `"'` you get `'123'`
3. if you click between the second `'"` you get just what's after, which is either `"` or `"`+newline

was this indeed different in previous pharo versions?

**Comment by SergeStinckwich** [comment]
Does not work for: ``'"123"'`` also in last version of Pharo9.

**Comment by astares** [comment]
<img width="497" alt="image" src="https://user-images.githubusercontent.com/5980033/231145579-f5de600f-aeb6-4657-a745-e226b2607b34.png">

works in latest Pharo 12 and this clicking makes sense

**Comment by astares** [comment]
@SergeStinckwich can we close it?

**Comment by astares** [comment]
Maybe the issue @SergeStinckwich wants to address here is that when you have a line break (hitting ENTER) then not the final ' (or ") is selected but the remaining part of the fist line or content from line 2 is selected as well:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/5980033/231148027-41004bbc-077c-4e80-a3bc-47649f7a0ba3.png">

**Comment by astares** [comment]
No feedback from @SergeStinckwich since a year. Lets close it.
