### ISSUE TITLE
Missing refactoring: Abstract instance variable

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4194]
We have RBAbstractInstanceVariableRefactoring but it has no command in Calypso to launch it.

**Comment by Ducasse** [comment]
Hi all 
I started to work on it. Check https://github.com/Ducasse/pharo/tree/4194-Missing-refactoring-Abstract-instance-variable
But I do not get why the refactoring does not perform the direct iv access to accessor calls transformations. 

<blockquote><img src="https://avatars2.githubusercontent.com/u/432549?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/Ducasse/pharo">Ducasse/pharo</a></strong></div><div>The Sources for Pharo. Contribute to Ducasse/pharo development by creating an account on GitHub.</div></blockquote>

**Comment by Ducasse** [comment]
In fact it is working. I just tested with 

foooo
   ^ x +2 
and the 
code is transformed in 
   ^ self x + 2
