### ISSUE TITLE
Should SystemDictionary sort classes by name?

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4204]
I was doing some profiling today and I found that when you call #allBehaviors it access to a cache, but during the build of the cache it sorts the class names. 

I am wondering if it should be the responsibility of the SystemDictionary to sort the cache. 

I would expect the model to return unsorted collection and the UI should sort it *if* needed.

**Comment by MarcusDenker** [comment]
No, I think it should not: sorting is a client (and mostly even UI) issue.

**Comment by MarcusDenker** [comment]
PR: https://github.com/pharo-project/pharo/pull/4274

**Comment by MarcusDenker** [comment]
merged after review
