### ISSUE TITLE
Review ReflectivityExamples class packaging

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#4232]
ReflectivityExamples class is currently packaged in "Reflectivity-Tests". 
But it is not a test - it is an example class used in tests and other places

So would ReflectivityExamples class not be better packaged into existing package "Reflectivity-Examples" ?

Comments?

**Comment by MarcusDenker** [comment]
Yes, this is a good idea.

**Comment by MarcusDenker** [comment]
I had a look: these are code examples of pharo code to be used by tests.. I think the best would be to 
- rename it and document it
- change the one user outside of tests to not use it
- and let it in the test package.

I want to later remove it and use some shared "code example" class with the compiler.
