### ISSUE TITLE
Activate Catalog JSON generation for MetaRepoForPharo80

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#4241]
I doubt that we are able to replace catalog in Pharo 8.

So I created a new project "MetaRepoForPharo80" for the configs for catalog to be known to work with Pharo8 to prepare for later release already.

   http://www.smalltalkhub.com/#!/~Pharo/MetaRepoForPharo80

There is a single ConfigurationOfDesktopManager copied into it already including a definition
of a stable loading spec for #'pharo8.x'.

@estebanlm needs to activate it for the generation of http://catalog.pharo.org/catalog/json

**Comment by estebanlm** [comment]
this is done

**Comment by estebanlm** [comment]
and I want to replace it, but as @astares sais... I don't know if we will have the time to do it for P8.

**Comment by astares** [comment]
We still can do when time permits ... for now this already helps.
