### ISSUE TITLE
ZnMimeType hash have problems in Pharo 7.0.3/8.0.0

### ISSUE THREAD

**Issue by gcotelli** [guillep/pharo-core#4255]
Code to reproduce the problem:
```smalltalk
| mime1 mime2 |
mime1 := (ZnMimeType fromString: 'application/json;q=1').
mime2 := (ZnMimeType applicationJson parameterAt: 'q' put: '1').
{ mime1 = mime2 . mime1 hash = mime2 hash }

--> #(true false)
```

This problem is fixed (or never introduced I don't know) in the main Zinc Repository. The problem is that `ZnMimeType>>fromString:` uses a plain `Dictionary` for the parameters instead of `SmallDictionary` like the parameters method that lazy initializes the variable.

In Sven's Zinc repository `SmallDictionary` is always used and the hash computation is consistent. https://github.com/svenvc/zinc/blob/master/repository/Zinc-Resource-Meta-Core.package/ZnMimeType.class/class/fromString..st

**System info:**
```
Pharo 7.0.3
Build information: Pharo-7.0.3+build.158.sha.0903ade8a6c96633f07e0a7f1baa9a5d48cfdf55 (64 Bit)
```

I don't know how external projects included in Pharo are supposed to be updated. We must modify code in Pharo directly? Or there's some way to bring the updates sven makes in his repo?

**Comment by gcotelli** [comment]
The same problem exists in Pharo 8

**Comment by Ducasse** [comment]
Thanks. To me this is strange that Dictionary and SmallDictionary are producing different results. 
It looks like a bug to me.

**Comment by gcotelli** [comment]
@Ducasse It happens because `ZnMimeType>>#hash` is using the `parameters` hash and the hash for both `Dictionary` and `SmallDictionary` combines the class hash with the hash of the elements.. So if the hash of both classes is different (it certainly can happen) the resulting hash of the mime type will be different.
How I should proceed in order to fix it? Just issue a PR against Pharo7 and Pharo8 branches? Or we have some procedure to merge back Sven changes ?

**Comment by gcotelli** [comment]
Just in case, there's now pull requests available for Pharo 7, Pharo 8 and Sven's repo.

**Comment by Ducasse** [comment]
Tx ;) we will have a look.
This is cool to have great guys around Pharo. We are really moving in the right direction.
