### ISSUE TITLE
[AbsolutePath] withParents on root  , on linux ,  return 2 root path

### ISSUE THREAD

**Issue by CafeKrem** [guillep/pharo-core#4258]
Linux
FileLocator root fullPath withParents 
return:
{ Path root . Path root }
it's strange

**Comment by Ducasse** [comment]
This is the same on mac. but what should it returns. When you are on the root the parent is what?
BTW we should add a comment on the method.

**Comment by CafeKrem** [comment]
I think he should return { Path root  }
by definition, the root has no parent.
