### ISSUE TITLE
Improving comment of Color methods... nobrainer.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4260]
blah blah idiot robot.

**Comment by MarcusDenker** [comment]
merged

**Comment by MarcusDenker** [comment]
I actually think the robot reminding people to describe issues is good. I often look at older issues and they are completely unclear and there is just not enough information for anyone but the submitter to do anything (and I feel that event he submitter will forget after some months).

For non-bugs, it might be good to just do a PR directly without an issue tracker entry.
