### ISSUE TITLE
Renaming a class when the message browser is open breaks

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4268]
handleClassRenamed: anAnnouncement
	| items selectedIndex |
	items := self messages
		collect: [ :rgMethod | 
			| interestedClassName interestedClass |
			interestedClassName := anAnnouncement oldName.
			interestedClass := anAnnouncement classRenamed.
			rgMethod isMetaSide
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
				ifTrue: [ interestedClassName := interestedClassName , ' class'.
					interestedClass := interestedClass classSide ].
			rgMethod parentName = interestedClassName
				ifTrue: [ (interestedClass >> rgMethod selector) asFullRingDefinition ]
				ifFalse: [ rgMethod ] ].
	selectedIndex := messageList selectedIndex.
	self messages: items.
	self setSelectedIndex: selectedIndex

**Comment by Ducasse** [comment]
This is because a ring method does not have the same api than a compile method and that isMetaSide is only defined on RG.

Solution should probably be
- check compiledMethod and Ring Method 
- check what is the status of Ring
- make sure that both are compatible

**Comment by hilaire** [comment]
Confirmed in release Pharo8.0-SNAPSHOT-64bit-278304f.
No idea in which state it lets the code.

**Comment by MarcusDenker** [comment]
Fixed in the spec repository. Will be be merged in the image withe the next merge
