### ISSUE TITLE
Spelling in default comment

### ISSUE THREAD

**Issue by grpistoia** [guillep/pharo-core#4272]
Hi

There is a spelling mistake in the default comment of a class, on the word "Responsability" should be spelled "Responsibility".

Is there any spell checker in Smalltalk? if so, maybe suggest it there.

Maybe suggest an example of a class well documented.

Great improvements in the last versions, good work people!

Thanks lots.

**Comment by MarcusDenker** [comment]
the class comment spelling error has already been fixed in Pharo8. But there where other cases, I add a PR for that (and might do a backport for just the comment fix)

**Comment by MarcusDenker** [comment]
PR for Pharo8: https://github.com/pharo-project/pharo/pull/4376

**Comment by MarcusDenker** [comment]
I checked Pharo7: it is fixed there, to. So now I wonder: where did you see it?

**Comment by MarcusDenker** [comment]
merged the PR

**Comment by grpistoia** [comment]
Yes.. so sorry.. i must mixed up when i use Pharo 6. I had lost changes in Pharo 7.. When to rescue my project in 6... I must got confused probably. So sorry.
