### ISSUE TITLE
Select Image dialog missing

### ISSUE THREAD

**Issue by grpistoia** [guillep/pharo-core#4273]
Hi

For the ones that worked in Squeak or Pharo before v7.. when you saved the image with a new name, next time you run Pharo it will ask you which image you wanted to open when found more than one in the directory.

That was a fantastic way to make backups, and save a progress allowing to open previous versions of a change was not successful, and also allowing to compare an image with another. Sometimes the FileOut not sufficient because you relied on Playground notes or temporary code.

Since version 7, that's no longer working. Version 7 will always open the default, and any newbie will assume changes got lost. Allows you to save code but will not open the dialog. And asking a parameter in the console, when that was working before makes no sense. Version 8 is same or worse.

Pharo ability to freeze all the image and load later is beautiful, shouldn't get lost because they introduce the Loader.

Remember many people experiment with Pharo or code where there is no internet, so we can't force them to commit to a global repository when there was an alternative already.

Personally I remained in Pharo six just for this reason

Thanks lots.

**Comment by astares** [comment]
@grpistoia 
This issue is rather old and managing multiple images is now since a few years done with Pharo Launcher more properly and professionally than Squeak or Pharo image handling in the past. Lets close the issue.
