### ISSUE TITLE
Code completion DNU inside literal array

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#4280]
When editing a method like

	^#(
		"Object will break immediately"
		#ProtoObject #Object
		"Contexts and their superclasses"
		#InstructionStream #Context #BlockClosure #CompiledMethod #CompiledCode #CompiledBlock
		"UndefinedObject crashes the VM"
		#UndefinedObject
	)

I get a DNU for visitLiteralArrayNode: when editing the comment inside the array

**Comment by myroslavarm** [comment]
PR : https://github.com/pharo-project/pharo/pull/4301

**Comment by myroslavarm** [comment]
merged so should be closed
