### ISSUE TITLE
RBNullFormatter should declare that it is a PrettyPrinter

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4304]
doing

RBNullFormatter class >> isPrettyPrinter
	^ true

We should probably define 

RBProgramNodeVisitor class >> isPrettyPrinter
       ^ false

**Comment by Ducasse** [comment]
Or we can remove all the isPrettyPrinter methods

**Comment by MarcusDenker** [comment]
This can be closed as RBNullFormatter was removed (we use the simple formatter as the fallback as hand-build ASTs need a way to be printed)
