### ISSUE TITLE
Add comment why name cache in SystemDictionary is sorted

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#4306]
with removing the sorting of the cached class names (see https://github.com/pharo-project/pharo/pull/4274)

#hasBindingThatBeginsWith: does not work anymore, as it was using a search strategy based on the fact that it was ordered.

This was indeed faster, but I wonder of we need all that complexity?

**Comment by Ducasse** [comment]
imagine the images of certain companies with 30000 classes

**Comment by MarcusDenker** [comment]
indeed... I will revert #4274 and add a good comment explaining why we sort the cached class names.

**Comment by MarcusDenker** [comment]
merged
