### ISSUE TITLE
Pushing to github seems to be broken

### ISSUE THREAD

**Issue by myroslavarm** [guillep/pharo-core#4311]
perhaps spec/iceberg related. at the step of saving the credentials before you can push in the latest Pharo8 image, there's only 'ok' button but no 'accept' which lets you store the credentials to your github account but doesn't push. has been spotted for both pharo for win 64, and pharo for macOS 64.

**Comment by MarcusDenker** [comment]
I can not do any Pull Requests until this is fixed.

**Comment by tesonep** [comment]
@jecisc this is a problem with the revert of Spec1, because the same version is running in Pharo7 with the old spec. Can you check if the dialogs are working in the same way?

**Comment by myroslavarm** [comment]
this seems to be fixed now, so i guess i can close this?
