### ISSUE TITLE
Cannot use slot as class variable: Raise explicit error

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4314]
I tried to make BalloonEngine class variables `BufferCache` a WeakSlot but I got an error:

```
WeakSlot(Object)>>doesNotUnderstand: #asClassVariable
[ :e | e asClassVariable ] in ShiftClassBuilder>>sharedVariables: in Block: [ :e | e asClassVariable ]
Array(SequenceableCollection)>>collect:
ShiftClassBuilder>>sharedVariables:
[ :builder | 
builder
	name: aSubclassSymbol;
	superclass: self;
	slots: slotDefinition;
	sharedVariables: classVarDefinition;
	sharedPools: someSharedPoolNames;
	category: aCategorySymbol ] in Object class(Class)>>subclass:slots:classVariables:poolDictionaries:package: in Block: [ :builder | ...
ShiftClassInstaller>>make:
ShiftClassInstaller class>>make:
Object class(Class)>>subclass:slots:classVariables:poolDictionaries:package:
UndefinedObject>>DoIt
OpalCompiler>>evaluate
ClySystemEnvironment>>compileANewClassFrom:notifying:startingFrom:
ClyFullBrowser>>compileANewClassFrom:notifying:startingFrom:
ClyClassDefinitionEditorToolMorph>>applyChanges
```

This might interest you @MarcusDenker

**Comment by MarcusDenker** [comment]
Class Variables and Slots are two different entities: You can not use a Slot as a class variable.

(this might be possible to unify later, but even then this unified variable would need to implement different code for both the slot or the class var case and might be done via some additional layer,
the *objects* representing a variable inside an object vs. one in the class will have to be different as their API is different *and* the data they need is different....)

This means, if you want to have a "Weak Class Variable" you have to implement this, see ExampleClassVariable as an example.

I will add code to detect when people try to use slots as class vars and raise a nice error message.

**Comment by MarcusDenker** [comment]
Sadly I can not commit as my image does not allow me to make PRs (I press on "Ok" and nothing happens)

What needs to be done: add this method to Slot:

asClassVariable
	self error: 'Slots can not be used to define Class Variables, you need to create a LiteralVariable subclass instead'
