### ISSUE TITLE
Compiling a method without changing the source code mark package as dirty

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4317]
When you compile a method with a source code that is exactly the same than the current code, the package is marked as dirty. 

Example, execute:

Object compile: (Object>>#as:) sourceCode

Then Kernel will be dirty in Iceberg.

IMO, when the body and protocol do not change, we should not recompile the method.

**Comment by kasperosterbye** [comment]
This seems no longer to be the case. I suggest to close this.
