### ISSUE TITLE
activateCursor: method is missing on WorldMorph

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#4324]
The #activateCursor: method was removed (during refactoring of cursor ownership) 
but is sent within #activateInCursorOwner: which is looking like that in P8 now:
```Smalltalk
   activateInCursorOwner: aCursorOwner
	^ aCursorOwner activateCursor: self
```
There is no #activateCursor: implementation in the image.

When one sets a new Cursor using Cursor (class)>>#currentCursor: then the cursor is 
not set - instead the system crashes into the emergency debugger.

![image](https://user-images.githubusercontent.com/5980033/63056038-7f102c80-bee7-11e9-8b0e-a05ef4786adc.png)

One can reproduce this by loading the "VistaCursor" project for Windows which worked in P7 
but not in P8. Note that it has to be a Windows machine as the cursor switch does not happen on Mac and Linux as "VistaCursor" only works on Windows.

**Comment by astares** [comment]
We can easily fix this by implementing the missing method on WorldMorph>>activateCursor:
again but this time dispatching back to the cursor.

```Smalltalk
activateCursor: aCursor
     aCursor beCursor
```

**Comment by astares** [comment]
To verify the PR:
 - load "VistaCursor" goodie which is for Windows in a regular Pharo 8 image -> emergency
   evaluator
 - then try the same with the code change in the PR and the "VistaCursor" goodie works again

**Comment by estebanlm** [comment]
why not just to rewrite: 

```Smalltalk
activateInCursorOwner: aCursorOwner
	^ self beCursor
```

?

**Comment by astares** [comment]
@estebanlm 

Yes - it is shorter. But if you look into Pharo 7 the handling was **explicitly dispatched to the cursor owner** in case he has to do something additional.

```Smalltalk
activateInCursorOwner: aCursorOwner
	^ aCursorOwner activateCursor: self 
```
```
activateCursor: aCursor
	osWindow ifNil: [
		aCursor beCursor
	] ifNotNil: [
		osWindow setMouseCursor: aCursor
	]
```

It's not really necessary in P8 as the osWindow is not anymore in WorldMorph - but I just thought we keep that flexibility. But I have no specific preference what we should use. 

Do we
 A) keep the PR (with the dispatching) 
 B) or should I change the PR to what you proposed (without dispatching)?

If you decide for A then merge the PR, if you decide for B just tell me and I change it

**Comment by tesonep** [comment]
To fix the problem now, I will choose to use directly #beCursor. 
However, this solution is only good when the world is rendered with the VM world render. We need to have a double dispatch between the cursor and the active world renderer to correctly use the code needed to make a cursor the cursor. 
This will require a bigger refactoring, and maybe thinking if the cursor is a cursor for the whole image or only for a given world or even more for a rendering of a world, for example, what it should happen if I close the image and reopen it?

**Comment by astares** [comment]
@tesonep changed
