### ISSUE TITLE
Missing refactoring - Duplicate class

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#4329]
Sometimes it would be helpful to be able to duplicate a class "A". The duplication into a class "D" should include all the variable definitions, comment and instance as well as class  side methods using the same baseclass "B".

Such a duplicate class "D" can then be modified and used to experiment before changing "A" in full and all users. Also if the duplicate fits the new requirements one can remove "A" and rename the duplicate "D" into "A" to profit from the new behavior.

@Lin777

**Comment by dionisiydk** [comment]
Hi @astares .

There is command copy from context menu of class. Is it not what you are looking for?

**Comment by astares** [comment]
Looks like I'm getting old or blind. That was too obvious ... really never noticed it before.

**Comment by Lin777** [comment]
Hi @astares and @dionisiydk 

Personally I saw that there are many tools that Pharo has that are not very well known or very intuitive to understand, so I decided to do a [mini tutorial](https://github.com/Lin777/pharo-wiki/blob/AddRefactoringWiki/General/Refactorings.md) of the existing refactorings in Pharo.

I already did a [PR](https://github.com/pharo-open-documentation/pharo-wiki/pull/214) on pharo-wiki, I hope it helps and of course any suggestion is welcome :)

**Comment by guillep** [comment]
> so I decided to do a mini tutorial <https://github.com/Lin777/pharo-wiki/blob/AddRefactoringWiki/General/Refactorings.md> of the existing refactorings in Pharo.
> 
> I already did a PR on pharo-wiki, I hope it helps and of course any suggestion is welcome :)
> 
Thanks Evelyn, it is super nice, I love it :)
