### ISSUE TITLE
Fuel should not depend on Deprecated file streams

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4346]
The tests of Fuel are depending on deprecated file streams. 
One reference can just be removed since there are no senders, but the other is used in tests.

Maybe @theseion knows what to do about it.

**Comment by theseion** [comment]
Yeah, I need to clean up for Pharo 8 anyway. I'll address all of the deprecation issues then.

**Comment by theseion** [comment]
You can either move this issue to the Fuel issue tracker or just close it.

**Comment by MarcusDenker** [comment]
I think this has been fixed
