### ISSUE TITLE
notExistingClassStoredSettingSTONString 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4350]
'Cannot read stored value of #notExistingClassStoredSettingSTONString. Exception: KeyNotFound: key #MockNotExistingClass not found in SystemDictionary'

**Comment by Ducasse** [comment]
From the ci log breaking on linux and unix. May be related to recent changes on Settings using streams.

**Comment by MarcusDenker** [comment]
No, it is a test that tests exactly that error:

testLoadNotExistingClassNameForRealValue
	reader stream: MockSettings notExistingClassStoredSettingSTONString readStream.
	reader load.
	self assert: reader storedSettings notNil.
	self assert: reader storedSettings size equals: 1.
	self should: [  reader storedSettings first realValue ] raise: NotFound.
	reader storedSettings first updateSettingNode: nil.
