### ISSUE TITLE
Moving a method should another package does not refresh the browser

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4352]
So we do not see that we move the method.

**Comment by Ducasse** [comment]
To check on P8 because I was on P7 :(

**Comment by myroslavarm** [comment]
is this still relevant?

**Comment by hernanmd** [comment]
This issue can be safely closed now in Pharo 12. Moving a method to another package refresh the list of methods.
The selector in the method list appears in grey, so it is making the method an extension installed in the same class but in a different package.
