### ISSUE TITLE
[Calypso] Dropping a list of class from one tag to another one 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4353]
opens tabs for nothing during the transfer making everything super slow.

**Comment by jecisc** [comment]
Opening tabs is not a bad behavior, but it should wait 200ms before opening.

https://github.com/pharo-ide/Calypso/issues/288

**Comment by Ducasse** [comment]
But I drop 30 classes so I do not see the point to create tabs for 30 classes I just move.

**Comment by jecisc** [comment]
Oh, I miss read “tabs” as “tags”.
So this is a different issue. I was talking about the fact that when you drag over a tag, it opens it. This is something else. Sorry for the noise.

**Comment by MarcusDenker** [comment]
This now works, there are to tabs opened when dragging classes from one tag to the other
