### ISSUE TITLE
Add Package and Remove Package of dependency analyser are confusing

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4363]
they refer to the selected packages and they should be renamed
+ Add packages or + Add

**Comment by myroslavarm** [comment]
this now seems to be fixed?
or if you think it is not please specify what you mean by "confusing" here?

**Comment by hernanmd** [comment]
This issue can be closed as now (Pharo 12) the Dependency Analyser has two icon buttons with "+ Add Packages" and "- Remove packages".
