### ISSUE TITLE
SortedCollection>>, loses custom sortBlock

### ISSUE THREAD

**Issue by daniels220** [guillep/pharo-core#4364]
Concatenating to a SortedCollection with a custom `sortBlock` results in a SortedCollection with the standard `sortBlock`, resulting in at minimum unexpected behavior, and possibly errors if the custom `sortBlock` is there because the contents don't implement `#<=`. For example:

```
collOne := (1 to: 5) asSortedCollection: [ :a :b | a > b ]. "=> a SortedCollection(5 4 3 2 1)"
collTwo := (6 to: 10) asSortedCollection: [ :a :b | a > b ]. "-> a SortedCollection(10 9 8 7 6)"
combined := collOne , collTwo. "=> a SortedCollection(1 2 3 4 5 6 7 8 9 10)"
combined sortBlock. "=> nil"
```

In other Smalltalk dialects, the sortBlock of the receiver is retained, which has its own issues but seems strictly better than the current behavior. The simplest way to implement this is to override `#,` back to the implementation on `Collection`:

```
SortedCollection>>, aCollection
	^self copy addAll: aCollection; yourself
```

If that seems like a good solution I can make a PR when I get a chance.

**Comment by Ducasse** [comment]
do not forget to add tests
