### ISSUE TITLE
Debugger "Run to here" command bring emergency evaluator in blocks

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4387]
I tried to use the debugger action "Run to here" inside a block and I got a debugger.

Code:

```Smalltalk
testDenyCollectionHasSameElements
	| c1 c2 |
	c1 := { 1. 2. 3 }.
	c2 := Set with: 2 with: 3 with: 1.
	self should: [ self denyCollection: c1 hasSameElements: c2 ] raise: TestFailure.

	c2 := Set with: 2 with: 3 with: 1 with: 4.
	self shouldnt: [ self denyCollection: c1 hasSameElements: c2 ] raise: TestFailure.
```

My cursor was in the block line 8 just after a restart.

**Comment by MarcusDenker** [comment]
can you try again? I do not get a emergency evaluator anymore in the latest Pharp8

**Comment by jecisc** [comment]
It does not bring an emergency evaluator anymore but it skips the block. I am not sure it's the wanted behavior.

**Comment by MarcusDenker** [comment]
Can you submit a new issue? because the original issue is fixed... keeping the same issue for another problem will be very confusing, as then everyone who wants to work on it first needs to read what is not a problem anymore.
