### ISSUE TITLE
Should write a test for the class definition and slot parser error

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4410]
https://github.com/pharo-project/pharo/issues/4406

**Comment by Ducasse** [comment]
I do not understand what happened because we already have tests for Slots.

classDefinitionString

	^ '{superclassname} subclass: #{classname}
		slots: \{
		''{instvar1}'' => InstanceVariableSlot. 
		''{instvar2}'' => InstanceVariableSlot.
		\}
		classVariableNames: ''{classvar1} {classvar2}''
		package: #MyPackage'
			format: { 
				'classname' -> self className.
				'superclassname' -> self superclassName.
				'instvar1' -> self firstInstanceVariableName.
				'instvar2' -> self secondInstanceVariableName.
				'classvar1' -> self firstClassVariableName.
				'classvar2' -> self secondClassVariableName. } asDictionary

I really think that we should add tests when doing fix. Because else the poor guy that has to write tests will lose a lot more time.

**Comment by guillep** [comment]
What was missing was a test for definitions like:

```smalltalk
AthensAbstractPaint subclass: #GradientPaint
	slots: { #colorRamp }
	classVariables: {  }
	package: 'Athens-Core-Paints'
```



> I really think that we should add tests when doing fix. Because else the poor guy that has to write tests will lose a lot more time.

++ 200

**Comment by Ducasse** [comment]
I started to define a new class of test 

and I'm checking with 

classDefinitionString

	^ '{superclassname} subclass: #{classname}
		slots: \{
		''{instvar1}'' =>  LazyClassVariable default: 5. 
		''{instvar2}'' => InstanceVariableSlot.
		\}
		classVariableNames: ''{classvar1} {classvar2}''
		package: #MyPackage'
			format: { 
				'classname' -> self className.
				'superclassname' -> self superclassName.
				'instvar1' -> self firstInstanceVariableName.
				'instvar2' -> self secondInstanceVariableName.
				'classvar1' -> self firstClassVariableName.
				'classvar2' -> self secondClassVariableName. } asDictionary

and I'm trying to see what is not working. 
But I got "distracted" by my garden.

**Comment by guillep** [comment]
The thing is that there are two different *syntaxes* for slot definitions:

```smalltalk
{ #iv1 =>  InstanceVariableSlot. #iv2 => LazyClassVariable default: 5. }
```

But alternatively `InstanceVariableSlots` do not need that we specify the type so the expression above is equivalent to this:

```smalltalk
{ #iv1. #iv2 => LazyClassVariable default: 5. }
```
My guess is that this last one was the one not working.

**Comment by MarcusDenker** [comment]
Slots definitions are expression that are executed to create an instance of the slot class. 

The selector is user defined, so it can be e.g. 

 #iv2 => TypedSlots type: #Integer   

Thus for me there are two syntaxes:

1) Expression that is evaluated, this is always the one with #name => 
2) to not have to write "InstanceVariableSlot" 8000 times, we have the short-hand notation of just using the symbol.

**Comment by Ducasse** [comment]
Yes we do not have problems with changes. We have problems to look for a fixed bug and to write a test for it because we have to get back in the spirit of the bug. 
Now there is another bug and please do not fix it without writing a test.

**Comment by Ducasse** [comment]
So I'm thinking that we will have get more than a type name in the slot definition.
Because when we have 
iv2 => TypedSlots type: #Integer
we should return TypedSlots type: #Integer. and right now we only have a typename.

**Comment by Ducasse** [comment]
Now I have a problem because 
'first' => LazyClassVariable default: 5
is not correct from a syntax point of view

it should be 
'first' => (LazyClassVariable default: 5)

I can do a hack in the parser but to me it does not look good. 
If I accept 
'first' => LazyClassVariable default: 5
it means that I should also support
 'first' => (LazyClassVariable default: 5)
because it would be bad that people understanding the syntax are punished when they write well their code. 


What do you think?

**Comment by Ducasse** [comment]
Ok I understand now that the correct way is 'first' => LazyClassVariable default: 5
so I will support it in the class parser. 
Now I really think that we should only accept literal in the 'default: 5 part'
