### ISSUE TITLE
Extract method does not check for duplicated instances of the refactored code

### ISSUE THREAD

**Issue by Lin777** [guillep/pharo-core#4429]
This change to improve extract method refactoring

**Comment by Ducasse** [comment]
C00L :)
May be we should add an option at the end of any refactporing menu sequence

**Comment by Lin777** [comment]
I was thinking the same thing but I didn't know exactly in which menu I would put it, because it could be in the class, method, variable or source code browser. And as I saw it very repetitive I decided to put the undo last refactoring command where it is now.

**Comment by Ducasse** [comment]
Hi evelyn 
I think that we talked about a different issue than the title. 
Could you check? Because I was talking about the undo and you too. 
Do you know if extract method is looking for duplicated instances?
