### ISSUE TITLE
Crashing on Iceberg push

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#4446]
I tried to follow the instructions in the video Marcus has made for how to make a pull request for an issue - in my case a solution to issue 2936.
However, when I get to push the vm crash. I have attached the dump.

[phasro8crash.txt](https://github.com/pharo-project/pharo/files/3561053/phasro8crash.txt)

**Comment by Ducasse** [comment]
Hello :)

Can you tell us on which VM, Pharo version and OS?
Are you able to reproduce this bug?
Can you describe the steps?

TX

**Comment by kasperosterbye** [comment]
I’ll try to make a more precise description tomorrow. Been traveling all
day.

I skipped the os info as it is in the dump file anyways.

I have some loose ideas as to what might be the problem, but need to try
out some variations to verify this.

Best,

Kasper


On 31 August 2019 at 13.17.43, StéphaneDucasse (notifications@github.com)
wrote:

Hello :)

Can you tell us on which VM, Pharo version and OS?
Are you able to reproduce this bug?
Can you describe the steps?

TX

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pharo-project/pharo/issues/4446?email_source=notifications&email_token=AEHHCYKVWDOFUDZ3TOQVHMTQHJHNPA5CNFSM4ISP7GK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5TKXUI#issuecomment-526822353>,
or mute the thread

**Comment by kasperosterbye** [comment]
Who knows what went wrong for me - I cleaned all images, reinstalled pharo launcer and started over. It now works.
