### ISSUE TITLE
[CI] Wget log is too verbose

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#4447]
I'd like to avoid that this is displaying:

> [32]      0K .......... .......... .......... .......... ..........  0%  397K 60s
> [32]     50K .......... .......... .......... .......... ..........  0%  570K 50s
> [32]    100K .......... .......... .......... .......... ..........  0%  969K 42s
> [32]    150K .......... .......... .......... .......... ..........  0% 22.6M 31s
> [32]    200K .......... .......... .......... .......... ..........  1% 1.46M 28s
> [32]    250K .......... .......... .......... .......... ..........  1%  985K 27s
> [32]    300K .......... .......... .......... .......... ..........  1% 22.3M 24s
> [32]    350K .......... .......... .......... .......... ..........  1% 25.0M 21s
> [32]    400K .......... .......... .......... .......... ..........  1% 1.65M 20s
> [32]    450K .......... .......... .......... .......... ..........  2% 27.0M 18s
> [32]    500K .......... .......... .......... .......... ..........  2% 20.5M 16s
> [32]    550K .......... .......... .......... .......... ..........  2% 1.03M 17s

So we can spot the real issue faster.

I think that the -nv option will do it.

**Comment by bencoman** [comment]
Being sometimes on a slow link, I find it disconcerting when the build appears to HANG when downloading large files.  Can you first try `--progress=dot:mega` to see if it sufficiently reduces verbosity? 
Ref https://www.computerhope.com/unix/wget.htm

**Comment by VincentBlondeau** [comment]
--progress=dot:mega seems to be a good compromise. Let's try it

**Comment by MarcusDenker** [comment]
I think this was done?

**Comment by VincentBlondeau** [comment]
It is done for me
