### ISSUE TITLE
UnifiedFFI: function signatures with char * aren't correctly resolved

### ISSUE THREAD

**Issue by theseion** [guillep/pharo-core#4455]
I have to use `void *` in place of `char *` in my function signatures to get them to be resolved directly. Neither modifying the pointer arity by adding / removing `*` nor changing the type to String helps.

See for example `LGitId>>oid_fmt:id:` which should have a signature of `#(char git_oid_fmt(char * out, LGitId * self))`.

**Comment by theseion** [comment]
Note that you'll have to load my fixes branch `fix-tests-and-double-frees` (see https://github.com/pharo-vcs/libgit2-pharo-bindings/pull/30) for the tests to fail when you change the signature to use `char *`.

**Comment by theseion** [comment]
I'm not sure if this bug has been fixed (it appears to now work whatever I put in the signature) or if there's some cache that I've missed. @estebanlm any idea?

**Comment by estebanlm** [comment]
mmm... don't know what you mean as "resolved correctly"  (there was a debate about that) 
In any case, `char *` is resolved as a String.

**Comment by theseion** [comment]
Ok. I consider this fixed then.
