### ISSUE TITLE
printOn: of LayoutFrame should be friendly to possible migration 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4456]
Right now 

(LayoutFrame identity
			topOffset: 12;
			bottomFraction: 0;
			bottomOffset: 15;
			leftOffset: -1;
			rightOffset: 1)	
printOn:
       a LayoutFrame ( (0@0) + (-1@12)px corner: (1@0) + (1@15)px ) 

And it would be better to print as 

(LayoutFrame identity
			topOffset: 12;
			bottomFraction: 0;
			bottomOffset: 15;
			leftOffset: -1;
			rightOffset: 1)	

So that people migrating from LayoutFrame fractions:offsets: can just inspect the object and know how to convert.

**Comment by Ducasse** [comment]
A first step can be to add an alternative printOnForHelpingMigration: method and refer to it in the methods fractions... and the class comment.

**Comment by jordanmontt** [comment]
Does only the instance variables named in the description (topOffset, bottomFraction, bottomOffset, leftOffset, rightOffset) have to be shown on the method?

Or all the instance variables (leftFraction, leftOffset, topFraction, topOffset, rightFraction, rightOffset, bottomFraction, bottomOffset)?

For example, this is what i'm thinking that has to be shown:
(leftFraction: 0
leftOffset: 0
topFraction: 0
topOffset: 0
rightFraction: 0
rightOffset: 0
bottomFraction: 1
bottomOffset: 0)

**Comment by Ducasse** [comment]
Hi
Tx! 
What would be nice is that the result of output can be reexecuted to produce a layout (check the self-evaluation in class like point and array to see what I mean. 
It then means that the printOnFor migration could be something in the vein of 

LayoutFrame identity + messages that only are the delta from the identity. 
Am'I clear?
S.
