### ISSUE TITLE
String could understand removeLast

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4466]
As a collection I would expect that 

'abcdef' removeLast 
>>> 'abcde'

Now the point is that I would like to avoid to create a new string but this goes 
against immutable string. So I would create a new one.

**Comment by svenvc** [comment]
We already have

    'abcdef' allButLast. ">> 'abcde'"

**Comment by Ducasse** [comment]
At least as 
removeLast
     ^ self allButLast

**Comment by noha** [comment]
Usually removeLast modifies the receiver, no?

**Comment by juliendelplanque** [comment]
`#removeLast` as implemented on `OrderedCollection` modifies the receiver.

```Smalltalk
OrderedCollection>>removeLast
	"Remove the last element of the receiver and answer it. If the receiver is 
	empty, create an error notification."
	| lastObject |
	self emptyCheck.
	lastObject := array at: lastIndex.
	array at: lastIndex put: nil.
	lastIndex := lastIndex - 1.
	^ lastObject
```

**Comment by estebanlm** [comment]
please do not modify the receiver. 
I could agree with something as proposed by Stef (but still, I can see in the future a moment when we say "why do we have two methods that do the same?")

**Comment by juliendelplanque** [comment]
I did not specify it but I am against modifying a String of course.

For me, one should just use `#allButLast` as @svenvc said.

**Comment by Ducasse** [comment]
May be I was stupid and we can close this issue. It was just not immediate that I should do allButLast because I was probably in collection mode and not string mode. 
Because collection do not have allButLast. 
Now strings are not polymorphic. 
May be one day I will resurrect first class interface to be able to understand the API of classes in terms of polymorphism. 
S.

**Comment by juliendelplanque** [comment]
It is in `SequenceableCollection` and `String` inherits from it via inheritance to `ArrayedCollection`.

**Comment by MarcusDenker** [comment]
From reading the discussion, I guess this can be closed (please re-open if that is wrong)
