### ISSUE TITLE
Copying class does not copy class comment

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4481]
If you copy a class it does not copy the class comment.

**Comment by MarcusDenker** [comment]
Yes, the reason was that the copy should have a different class comment... 
What I always wanted to add is on the UI a check box [] copy class comment

**Comment by jecisc** [comment]
Most of the time when I copy a class it's because they are similar and I want to keep part of the comment and update the rest with specificities. But most of the time I would like to start from the previous class comment :(

Or sometimes it's because I do not want to break the actual class that is used in the system so I copy it, update it then replace the previous one with the new one. 

The option to choose would be good.

**Comment by kasperosterbye** [comment]
How about just adding a line to the top of the class comment stating:
"I am a copy of class XXX. This comment is copied from there, and might not be entirely accurate"

**Comment by MarcusDenker** [comment]
I like the idea to add a comment on top.

**Comment by jecisc** [comment]
Great! Thanks
