### ISSUE TITLE
Undo/Redo bug after saving a method

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4486]
Steps to reproduce:
- Open Calypso on BitBltDisplayScanner>>#setFont
- Double click on "transparent" and write "red" instead
- Save the method with cmd/ctrl + s
- Do cmd/ctrl + z

Expected:
- A revert of red into transparent

Actual:
- The method end up like this:

```Smalltalk
setFont 
	super setFont.  "Sets font and emphasis bits, and maybe foregroundColor"
	font installOn: bitBlt foregroundColor: foregroundColorred
```

![2019-09-03 17 22 51](https://user-images.githubusercontent.com/9519971/64186672-8768e100-ce6f-11e9-99e2-b83eb948b8b1.gif)

**Comment by hogoww** [comment]
related issue : #2814 , although it describes a different reproducable case.

**Comment by MarcusDenker** [comment]
I think this issue tracker entry really was describing an undo problem, not the problem of using wrong code.

The indo problem is now fixed (I can not reproduce it after merging https://github.com/pharo-project/pharo/pull/9544 )
