### ISSUE TITLE
Add social preview in github settings

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4488]
Apparently, now we can set an image as "social preview" of a project.

It will appear on social media or pages such as the tags pages on GitHub. 

Maybe we could add the image from the readme as a social preview to catch attention.

**Comment by MarcusDenker** [comment]
There is a template:
![repository-open-graph-template](https://user-images.githubusercontent.com/413057/64235917-a1e79c80-cef9-11e9-8897-65377b943374.png)

**Comment by astares** [comment]
Note that I created a "pharo-brand" organization on GitHub with media stuff in different formats (icons, ...)

https://github.com/pharo-brand

If you have a preview picture we should put it there as well.



<blockquote><img src="https://avatars1.githubusercontent.com/u/46996382?s=280&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-brand">pharo-brand</a></strong></div><div>Pharo Brand items. pharo-brand has 3 repositories available. Follow their code on GitHub.</div></blockquote>

**Comment by astares** [comment]
Two examples sized according to the template:

![pharo-social-media01](https://user-images.githubusercontent.com/5980033/64407916-cff9e780-d085-11e9-8b93-b962cf4e2e65.png)
![pharo-social-media02](https://user-images.githubusercontent.com/5980033/64407917-cff9e780-d085-11e9-9393-61726a6d6e87.png)

**Comment by MarcusDenker** [comment]
Thanks! I have set the first one

**Comment by astares** [comment]
Yes - I like the first one too - as it corresponds to the homepage

**Comment by astares** [comment]
Added into the brand library:

https://github.com/pharo-brand/pharo-brand-material/commit/8f8084f2a4230c5a91b096f4f79fa5267a638a11

**Comment by jecisc** [comment]
I like it!
