### ISSUE TITLE
Community page should link to Official Pharoproject blog and Blog Aggregator only

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#4490]
The http://www.pharo.org/community page currently only includes links to 
 - pharoweekly blog
 - my astares.blogspot.com blog, 
 - the blog of clementbera

![image](https://user-images.githubusercontent.com/5980033/64249637-6e663b80-cf14-11e9-988b-6411cbbaea2e.png)

It does not make sense that my blog or the blog of Clement is mentioned directly and in favour of others. Because other respected members of the community also blog about Pharo Pierce Ng with his blog at:  https://www.samadhiweb.com/blog
 
So we should not mention single members blogs as Pharo is a **community project**.

Therefore I would suggest to change the page to only link to the official communit blog and the aggregator blog:

  -  Weekly Pharo https://pharoweekly.wordpress.com/
  - Aggregator "Planet Smalltalk": which is at http://prog.vub.ac.be/~cderoove/planet
     (the http://planet.smalltalk.com  is currently not working but will be reactivated)

If we like we can later also setup an own aggregator on "planet.pharo.org"

**Comment by astares** [comment]
I just noticed that we have already a list of blogs:

  https://pharo.org/web/blogs

which seems to also be indexed by Google as it was #1 hit when googling for "Pharo" and "Blogs".

Maybe the community page should just link to that one.

<blockquote><img src="/files/favicon.ico" width="48" align="right"><div><strong><a href="https://pharo.org/web/blogs">Pharo - Blogs</a></strong></div></blockquote>

**Comment by noha** [comment]
I just wondered what is the difference about active blog and just blog

**Comment by MarcusDenker** [comment]
This is fixed:

https://www.pharo.org/community


There is another issue about https://pharo.org/web/blogs here, so I close this one

<blockquote><img src="/files/favicon.ico" width="48" align="right"><div><strong><a href="https://www.pharo.org/community">Pharo - Community</a></strong></div></blockquote>
<blockquote><img src="/files/favicon.ico" width="48" align="right"><div><strong><a href="https://pharo.org/web/blogs">Pharo - Blogs</a></strong></div></blockquote>

**Comment by MarcusDenker** [comment]
Issue on the Pharo website repo: https://github.com/pharo-project/pharo-site/issues/12
