### ISSUE TITLE
Epicea: Better In-Image Documentation

### ISSUE THREAD

**Issue by seandenigris** [guillep/pharo-core#4495]
- What is the heuristic to find API access points? Epicea package has no 
comment, 'Browser' tag doesn't seem to have an XyzBrowser class, no 
particular class in the 'Model' tag jumps out at me as an access point; as 
above Browser about text not set. I finally bring up Morphic halos on the 
browser and after flopping around, find subclasses of EpLogNode; I browse it 
and find EpLogNodeGraphModel, which sounds interesting and turns out to be a 
spec. I figure out how to list the log files, but not how to get the entries 
- I was expecting a term like that and the relevant method (#log it turns 
out) has no comment to indicate it's what I'm looking for. Now that I'm 
starting to understand the project organization, back to the browser to 
explore EpUnifiedBrowserModel. After a bit of poking around, I suspect 
(correctly) that #log is what I'm after.

**Comment by tinchodias** [comment]
This is important. It's not only incomplete but also outdated. I wrote it for the first integration into Pharo (6.0 IIRC), and (especially GUI) changed.
