### ISSUE TITLE
Epicea: Browser Seems Awkward to Use

### ISSUE THREAD

**Issue by seandenigris** [guillep/pharo-core#4496]
- Filters disappear whenever left selection changed
- can't multi-select sessions
- can't select multiple packages in filter

**Comment by tinchodias** [comment]
I fixed the first item in a separate issue/PR. The remaining items could be fixed independently, too.

**Comment by tinchodias** [comment]
@seandenigris the browser seems awkward to me too. Sadly, even when I created it I was not satisfied but had no more time to invest and considered it was anyway an improvement over the previous version, so just pushed it.

It is now migrated to Spec2 (thanks to @juliendelplanque and @jecisc, I think), and may be a good opportunity to create a new one.

**Comment by tinchodias** [comment]
Another think I really don't like is the "Dashboard" button that opens this small window with status and controls on the monitor (enable/disable)...

**Comment by tinchodias** [comment]
So... more than a year passed and don't know the value of having this issue open.

This month, I have worked in a simplification of the model of Epicea (only locally, in my machine), but this change doesn't have any impact in the UI for now.

I think we should close this issue unless somebody (for example, @seandenigris) want to refresh it with some discussion or some code.

**Comment by seandenigris** [comment]
Given that all the tools are in flux with the move to Spec2, let’s close for now
