### ISSUE TITLE
line end conversion does not work for old ByteTextConverters

### ISSUE THREAD

**Issue by Rydier** [guillep/pharo-core#4506]
While these have been replaced by the new ZnCharacterEncoders, it might be nice to fix (some of?) the bugs that exist in the old TextConverters, for educational reasons and/or potential backport to Pharo 6.1 (... and maybe as a cautionary tale of the dangers of mixing too many responsibilities)

The issues are:
- In installLineEndConvention:, the latin1Map is replaced by nonAsciiMap, meaning all non-ascii characters should be translated. This only works for utf8 - in the byte converters there are usually many entries with byte encoding equivalent to unicode code points. 
When the optimized nextPutByteString: searches for next index to convert, for most non-ascii, it will then encounter false hits, for which the latin1Encodings does not contain a set of bytes to translate to, because they shouldn't.
- In the "slow" fallback for WideStrings, unicodeToByte: is used. This method precedes the latin1Encoding optimalization / lineEndConvension being added to Converter responsibilities, and thus assumes each code point corresponds to at most one byte. This is not true when cr can be converted to crlf.

How line end convention is supposed to work when decoding is anyone's guess, the above applies to the encoding process.

Another minor bug:
-  installLineEndConvention uses convertFromSystemString: when the correct call would be convertToSystemString:. Luckily, cr and lf are the same in all encodings, but it highlights the importance of method comments that state what one means by "system" string ;)

**Comment by MarcusDenker** [comment]
as ByteTextConverter is deprecated in Pharo9, I think this can be closed
