### ISSUE TITLE
Github: setup sponsoring infos

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#4508]
Github can now display sponsoring infos

![sponsors](https://user-images.githubusercontent.com/413057/64410657-c8d5d800-d08b-11e9-8dc2-d96335058f67.png)

We should check how to set this up.

**Comment by MarcusDenker** [comment]
DONE

**Comment by astares** [comment]
Spread the news: https://twitter.com/TorstenAstares/status/1169902354725888000

<blockquote><img src="https://pbs.twimg.com/media/EDxT_S3UwAIYxrH.png:large" width="48" align="right"><div>Twitter</div><div><strong><a href="https://twitter.com/TorstenAstares/status/1169902354725888000">Torsten Bergmann on Twitter</a></strong></div><div>“The @pharoproject github page 

     https://t.co/oNVfBQYyxQ

now includes a sponsor button:”</div></blockquote>
