### ISSUE TITLE
Move stable slots out of Example package

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#4514]
Because people fear to use them as they are tagged as example.

Slots *ARE* working, we should promote them.

**Comment by astares** [comment]
Dont know if it is not too early and we should keep them still as examples. Upcoming Composable slots might still change a little part of the game...

If one requires slots he can implement custom ones based on the examples

**Comment by noha** [comment]
I don‘t think it is too early. We are usually too cautious about that. And these things take a long time before they get adopted.

**Comment by Ducasse** [comment]
I agree with Julien.
