### ISSUE TITLE
Integrate ObservableSlot in base image

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#4515]
ObservableSlot is part of the Spec project for now, it should be moved to the image as it is not Spec-specific.

The plan is to:
1. Copy SpObservableSlot as ObservableSlot from Spec project into Pharo
2. Refactor Spec code to use ObservableSlot
3. Remove SpObservableSlot from Spec.

An issue for the Spec side is opened on Spec project: https://github.com/pharo-spec/Spec/issues/757

**Comment by astares** [comment]
According to @MarcusDenker there will be one - but with better name and better implementation

**Comment by juliendelplanque** [comment]
Yep, I talked with him yesterday about it (at the office).

But we can start with the current implementation. Refactoring it will not impact users.

**Comment by MarcusDenker** [comment]
Yes, but later... we can for now add the current version as the user visible API will stay the same

**Comment by sbragagnolo** [comment]
What is then the strategy to follow up this issue? I agree with Julien, It would be better to have a non performant solution and iterate over the existing implementation. 
In some time people may start to use SpObservableSlot becoming in to a headache for the future. Is really cheap now :)

**Comment by jecisc** [comment]
I already did it. We can close the issue.
