### ISSUE TITLE
Ensure git repository LICENCE file and inside image licence text are in sync

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#4516]
This should be done during the bootstrap.

One of the two sides needs to be considered as the reference and update the other one accordingly.

**Comment by kasperosterbye** [comment]
It is a bit unsure which git repository is being meant, but assume it is the main pharo github.
In that case I am not sure there is an issue, as pharo is MIT, but the about gives details about other aspects which are not stored in github (in particular fonts).
