### ISSUE TITLE
Pharo 8 crashes hard on cloning project from Github (Windows - ssh)

### ISSUE THREAD

**Issue by maxbareis** [guillep/pharo-core#4519]
I am not able to reopen [#3461](https://github.com/pharo-project/pharo/issues/3461) so I created a new issue.
I still get those hard crashes without any stack or dump when trying to clone in a fresh image with ssh (but without credentials), trying to repair the pharo repository with git@github.com:pharo-project/pharo.git. During debug I stumbled over ExternalAddress>>unpackFromArity sending 1 to ExternalAddress(ByteArray)>>pointerAt: . This is then send to unsignedByteAt: and integerAt:size:signed which is not overrode in ExternalAddress and therefore always returns self primitiveFailed :
```
integerAt: byteOffset size: nBytes signed: aBoolean
	"Primitive. Return an integer of nBytes size from the receiver.
	Note: This primitive will access memory in the outer space if
	invoked from ExternalAddress."
	<primitive: 'primitiveFFIIntegerAt' module:'SqueakFFIPrims'>
	^self primitiveFailed
```
in Alien this is overwritten but is also sending a message where the return never could be as expected (and probably promised):
```
integerAt: byteOffset size: size signed: signed

	^ (ExternalAddress fromAddress: self address) integerAt: byteOffset size: size signed: signed
```
Unfortunately I am too far away from this code to judge the impact of change and which information should be returned by ExternalAddress, so please maybe someone else could have a look at it.

Cheers 
Max
Attached StackFuel as zip
[Debugger-Stack-ExternalAddress-2019-09-08-133116.zip](https://github.com/pharo-project/pharo/files/3587546/Debugger-Stack-ExternalAddress-2019-09-08-133116.zip)

**Comment by Ducasse** [comment]
Thanks a lot for the report

**Comment by maxbareis** [comment]
I was also wondering how unpackFromArity: works, as the method doesn't use the index of the for loop:
```
unpackFromArity: arity
	"This will 'unpack' a pointer from a certain arity. See #unpackToArity: for a better explanation."
	| rolledPointer |
		
	rolledPointer := self.
	"Start in 2 because first pointer is self"
	2 to: arity do: [ :index | rolledPointer := rolledPointer pointerAt: 1 ].
	^ rolledPointer	
```
Instead it is alway asking pointerAt for self.

**Comment by MarcusDenker** [comment]
Can you check if this is still a problem in Pharo9?

**Comment by MarcusDenker** [comment]
question from  19 Jul 2021 was un=answered, so we can assume it is not a problem anymore
