### ISSUE TITLE
Provide a trimAll/trimAll: to complete the trim messages

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#4533]
We have
 - trimLeft
 - trimRight
 - trimBoth

but no way to replace overall separators or character provided in a block expression.

But this is something one often needs in parsing or data reading.

We should therefore provide additionally
 - trimAll
 - trimAll: aBlock

**Comment by juliendelplanque** [comment]
I super-agree with that!

**Comment by Ducasse** [comment]
Now I would prefer to have all these methods into a separated class because the API of string is just gigantic and parsing is not a good idea with strings.

**Comment by juliendelplanque** [comment]
In fact, those are already implemented by `#trimBoth` and `#trimBoth:`

**Comment by astares** [comment]
@juliendelplanque No trimBoth is only a combination of left and right. trimAll removes all (even the ones in the middle)

@Ducasse Having a rich String manipulation interface is a plus - not a downside.
Sure  can easily have separate "utility classes" - but we do not want to play Java here ;)

**Comment by juliendelplanque** [comment]
I continue discussion on the related PR #4534

**Comment by astares** [comment]
https://twitter.com/awbjs/status/1172273315727101952?s=20

So we close

<blockquote><img src="https://pbs.twimg.com/media/EETAWTIWsAISEHK.jpg:large" width="48" align="right"><div>Twitter</div><div><strong><a href="https://twitter.com/awbjs/status/1172273315727101952">Allen Wirfs-Brock on Twitter</a></strong></div><div>“Reminded today that trimStart and trimEnd are in ES2019—a little later doing some organizing of my long term storage I found this. I guess somethings just keep recurring forever. (Looks like a bug in the comment on example line 4, something else that never changes)”</div></blockquote>
