### ISSUE TITLE
MessageS sent but not implemented

### ISSUE THREAD

**Issue by Alisu** [guillep/pharo-core#4541]
I found some of them in the current image, i will start a list here (this is a list of the method trying to send non implemented messages):
*~~striketrough~~ = fixed

FFI-Kernel (package)
-ExternalObject class>>initialize
-ExternalFunction class>>externalCallFailedWith:

Alien-Core
-Alien class>>ensureNotifiedAtStartUp:
-FFICallbackThunk class>>ensureNotifiedAtStartup
-Callback class>>ensureNotifiedAtStartup

~~OpalCompiler-Core~~
~~-CompiledCode>>compiler~~
~~-CompiledCode>>compilerClass~~

BaselineOfLibGit
-BaselineOfLibGit>>changeRepositoryType

Metacello-Core
-MetacelloPlatform>>registerPackageNamed: 
-MetacelloPlatform>>suspendSystemUpdateEventsDuring:

SIUnit-UI
TestRunner>>excludeClassesNotUnderTestFrom: 

Tool-ProcessBrowser
ProcessBrowser class>>registerWellKnownProcesses

Context>>doPrimitive: primitiveIndex method: meth receiver: aReceiver args: arguments 
(Expected by VM?)

**Comment by MarcusDenker** [comment]
For 

OpalCompiler-Core
-CompiledCode>>compiler
-CompiledCode>>compilerClass

CompiledCode misses a subclassResponsibilty for #methodClass 

I will do a PR for that

**Comment by MarcusDenker** [comment]
I added: [Longterm Cleanup] fix or tag all "selectors send but not implemented" #10834
