### ISSUE TITLE
Remove class refactoring should not warn user if the class reference itself

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4550]
Currently, if a class reference itself and you try to remove it, you get a warning saying the class is referenced. 

In case the class reference itself, it should not warn the user.

**Comment by MarcusDenker** [comment]
Hmm.. I can not reproduce that.

The check seems to remove the name as intended and I get not warning:

preconditionHasNoReferences: aClass

	| env |
	env := self environmentWithReferencesTo: aClass.
	^ (RBCondition withBlock: [ (env classNames copyWithoutAll: classNames) isEmpty ])
			errorMacro: aClass , ' is referenced.<n>Browse references?';
			errorBlock: [ self openBrowserOn: (env) ];
			yourself

**Comment by MarcusDenker** [comment]
RBRemoveClassRefactoring

**Comment by jecisc** [comment]
![2019-09-11 13 16 36](https://user-images.githubusercontent.com/9519971/64692970-8f8bd680-d496-11e9-974e-98718be3545e.gif)

**Comment by jecisc** [comment]
So it happens with class side because it check names and in the class side there is " class" at the end of the name.

**Comment by MarcusDenker** [comment]
fix: in ClyBrowserMorph>>#confirmUnusedClasses:

noUsers needs to exclude both class and instance side:

	noUsers := self confirmEmptySystemQuery: refQuery excluding: (classes flatCollect: [ :each | { each . each classSide } ]).
