### ISSUE TITLE
Ring metaclass definition

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#4557]
taken from: https://github.com/pavel-krivanek/Ring2/pull/12

RGMetaclassStrategy >> #definition returned a String with an incorrect definition. This commit contains a fix and a unit test for this problem.

Jan.

**Comment by kasperosterbye** [comment]
I am confused. You have some solution? You have some work on your own copy and mention a PR, but it is not a PR to pharo-project?

**Comment by pavel-krivanek** [comment]
I opened the issue here because now the main development repository of Ring is the one in pharo-project. There is a PR but the proposed solution is not correct.

**Comment by kasperosterbye** [comment]
Is this one still a problem?

The implementation of `RGMetaclassStrategy >> #definition` seems to refer to `self traitComposition`, which is not defined.

**Comment by MarcusDenker** [comment]
I checked and it seems to work

```
env := RGEnvironment new.
c := env ensureClassNamed: 'Class1'.
c classSide definition
```

prints

```
 "'a RGMetaclassStrategy
	instanceVariableNames: '''''"
```

But in the meantime, #definiton on the real model has been deprecated... I will open a new issue for that.

(In general, it feels that we can not maintain two models... and especially keep them in sync... but that is yet another problem)
