### ISSUE TITLE
digitLength should be renamed

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#4583]
Guess, what is the result of `333 digitLength`? It is `2`, of course ;-) You are supposed to use decimalDigitLength
We should rename this method to something less confusing, e.g. bytesCount.
While it is so confusing, it would be better to remove it without deprecation but it is used quite a lot so we shall use auto-deprecation

**Comment by Ducasse** [comment]
Thanks for cleaning this. 
All this cruft accumulated over the years.!!!!
TXTXTXTXTXTXTX

**Comment by dionisiydk** [comment]
+1
