### ISSUE TITLE
Update Beacon packages

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4587]

**Comment by Ducasse** [comment]
Clean a bit more - remove bloc last reference

**Comment by estebanlm** [comment]
what's the status of this ?
I see Beacon is integrated now.

**Comment by Ducasse** [comment]
Old and fixed.

**Comment by Ducasse** [comment]
I will check Beacon.

**Comment by Ducasse** [comment]
I'm sorry but I will not check it.
