### ISSUE TITLE
Why do we have BaselineOfTelePharo support in P8 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4593]
baseline: spec 
    
	<baseline>

	| repository | 
	
	repository := self packageRepositoryURL.

	spec for: #common do: [
		spec baseline: 'SUnit' with: [spec repository: repository].
		spec baseline: 'Display' with: [spec repository: repository].

		spec package: 'SortFunctions-Core'.
		spec package: 'Tool-Registry'.
	].

**Comment by MarcusDenker** [comment]
duplicate of https://github.com/pharo-project/pharo/issues/5084
