### ISSUE TITLE
Did not get why BaselineOfBaseLibraries is not loaded

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4595]

**Comment by Ducasse** [comment]
This PR added baselineOfBaseLibraries and Beacon 
https://github.com/pharo-project/pharo/pull/4588

**Comment by Ducasse** [comment]
In the committed source I see

Class {
	#name : #BaselineOfPharo,
	#superclass : #BaselineOf,
	#category : #BaselineOfPharo
}

{ #category : #baseline }
BaselineOfPharo >> baseline: spec [
	<baseline>
	| repository |
	repository := self packageRepositoryURL.

	spec for: #common do: [
		spec postLoadDoIt: #'postload:package:'.
		spec baseline: 'BaseLibraries' with: [spec repository: repository].
		
But not in the image I downloaded.

**Comment by Ducasse** [comment]
Now in the image build: 734, commit: 10d18f2 so may be at the end it was not built.

**Comment by Ducasse** [comment]
![Screenshot 2019-09-14 at 09 39 02](https://user-images.githubusercontent.com/432549/64905122-a3704c00-d6d3-11e9-9068-994da3fb95db.png)

**Comment by Ducasse** [comment]
I revert the changes to be able to rerun the merge. Because on jenkins I get
![Screenshot 2019-09-14 at 09 40 50](https://user-images.githubusercontent.com/432549/64905132-d4e91780-d6d3-11e9-85a3-d24f7fdb5fae.png)

**Comment by Ducasse** [comment]
I reverted it but I need help because I do not understand how to try again.

**Comment by MarcusDenker** [comment]
This is fixed: there is BaselineOfBaseLibraries
