### ISSUE TITLE
SettingBrowser allSettingsState throws DNU in Author

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#4613]
inspect

```Smalltalk
SettingBrowser  allSettingsState
```

gives a DNU due to the settings declarion in Author #authorSettingOn:

**Comment by astares** [comment]
The allSettingsState assumes the target to be a class - that's why it seems to send #name
(which gives a DNU on the Author instance)

If one would comment out the <systemsettings> in #authorSettingOn we would have
the same problem with SmalltalkImage and other.

**Comment by MarcusDenker** [comment]
do we need #allSettingsState? It is just called from viewAllSettings and that has no senders

**Comment by MarcusDenker** [comment]
the method was removed
