### ISSUE TITLE
ClassDefinitionParser should allow global message node receivers for slots

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#4629]
When a slot is given not using the current syntax:

```Smalltalk
  { #slotName => MySlot parameter: 2  }
```
but just using a class side instance creation method like:

```Smalltalk
   { MySlot named: #'slotName' parameter: 2 }
```

as described in https://lists.pharo.org/pipermail/pharo-dev_lists.pharo.org/2019-September/276248.html

then the class definition sends an invalid message and the context menu in Calypso
is not shown anymore.

![image](https://user-images.githubusercontent.com/5980033/64982729-2e616a00-d8bf-11e9-839c-6e892ac29493.png)

**Comment by Ducasse** [comment]
I think that we can close this bug. I spent some time fixing the parser in another issue.

**Comment by MarcusDenker** [comment]
I will make sure that we have all the hooks later for custom slot defintions
