### ISSUE TITLE
RPackageSet Out of Sync

### ISSUE THREAD

**Issue by seandenigris** [guillep/pharo-core#4648]
Pharo 7.0.3

## Situation 1
After removing a method via Calypso, I got:
```
UndefinedObject(Object)>>doesNotUnderstand: #methodClass 
RGMethodDefinition>>asMCMethodDefinitionFromActiveDefinition 
RGMethodDefinition>>basicAsMCMethodDefinition 
RGMethodDefinition>>asMCMethodDefinition 
[ :ea | definitions add: ea asMCMethodDefinition ] in 
MCPackage>>basicSnapshot in Block: [ :ea | definitions add: ea 
asMCMethodDefinition ]
```

## Situation 2
After adding a method via Calypso's "generate accessors" in variable view mode, the new method did not show up in Iceberg as being added. It never appears as a change in the commit window, despite many creative attempts e.g. moving the method to a different package and back, and even deleting and reimplementing it from scratch.

## Problem
In both cases, the `RPackageSet` cache  did not update correctly.

## Workaround (not a solution!)
```smalltalk
IceTipCommitCommand >> #execute

	self repositoryModel realObject packages do: [ :p |
		| rp |
		rp := RPackageSet named: p packageName.
		rp instVarNamed: #definedClasses put: nil.
		rp instVarNamed: #methods put: nil. ].
	(IceTipCommitBrowser on: self repositoryModel) openWithSpec
```

**Comment by MarcusDenker** [comment]
Does this still happen?

**Comment by MarcusDenker** [comment]
As this is from Pharo7, I close it (if the problem still exists, please open a new one or re-open this one)
