### ISSUE TITLE
formattedCode of 2 is not a string

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4658]
It is strange and to be verified by formattedCode of a LiteralNode (for example 2) does not return a string.

**Comment by kasperosterbye** [comment]
In my image from this morning (23-Sep-2019), this is what I get:
`(RBLiteralNode value: 42) formattedCode` "'42'"

In context of a CompiledBlock:
`[ 2 ] sourceNode body statements first formattedCode` also gives me a ByteString

Could you expand where you see the error/problem?

The formattedCode is set up to use a class  BIConfigurableFormatter, which in my image is rather lacking any tests :-(, but I am not sure if that is what you were thinking of.

**Comment by Ducasse** [comment]
Ihave the check but I have view problems in this moment. No screen for me :(

**Comment by MarcusDenker** [comment]
I checked and it seems to be ok
