### ISSUE TITLE
Remove #digitAt:put: in integer classes

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#4672]
After merging of #digitAt:put: deprecation, two implementations are still in the image:
LargeInteger>>#digitAt:put:
SmallInteger>>#digitAt:put:

These methods need to be removed

**Comment by Ducasse** [comment]
Hi pavel

what do you mean, we should deprecate them? 

Stef

**Comment by svenvc** [comment]
A superclass deprecation is sufficient, no need for overrides

**Comment by pavel-krivanek** [comment]
Right, Sven :-)
