### ISSUE TITLE
BMPReadWriterTest references old API FileStream

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#4697]
BMPReadWriterTest has methods with input data having a comment referencing old FileStream API. Instructions should be updated to use the new stream API.
example:
```Smalltalk 
bmpData16bit
	"Created via:
		(Base64MimeConverter mimeEncode: 
			(FileStream readOnlyFileNamed: 'bmptest16b.bmp') binary)
				contents
	"
	^ 'Qk24AAAAAAAAADYAAAAoAAAACAAAAAgAAAABABAAAAAAAIIAAADDDgAAww4AAAAAAAAAAAAA
4APgA+AD4AMfAB8AHwAfAOAD4APgA+ADHwAfAB8AHwDgA+AD/3//f/9//38fAB8A4APgA/9/
/3//f/9/HwAfAAAAAAD/f/9//3//fwB8AHwAAAAA/3//f/9//38AfAB8AAAAAAAAAAAAfAB8
AHwAfAAAAAAAAAAAAHwAfAB8AHwAAA==' base64Decoded
```

**Comment by sbragagnolo** [comment]
'bmptest16b.bmp' asFileReference binaryReadStream upToEnd base64Encoded. proposed as first change. Still i would like to know better if we have a proper documentation on how to encode files into base64. After all this may be used by seaside and other frameworks that have to send / receive information
