### ISSUE TITLE
Class definition parser does not work with TypedSlots

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#4702]
I get error when it tries to parse slots defined as:

```smalltalk
PCGProgramNode subclass: #PCGCompositeTemplateParameter
	slots: { #templateParameters type: (SequenceableCollection withItemsType: PCGTemplateParameter) }
	classVariables: {  }
	package: 'PharoCodeGenerator-AST'
```

The project to reproduce bug: https://github.com/juliendelplanque/TypedSlot

**Comment by Ducasse** [comment]
#templateParameters with: .... is not supported. 

It should be 
#templateParameters => TypeSlot type: zz foo: 22
So may be 
#templateParameters => TypeSlot forCollection:  SequenceableCollection of: PCGTemplateParameter

**Comment by juliendelplanque** [comment]
Why it can not be supported?

**Comment by Ducasse** [comment]
because we want to have a clear delimiter => and because we can express the way I mentioned. 
So we should probably fix the template or class definition output. 
You can ask pablo, marcus or guille.

**Comment by juliendelplanque** [comment]
I understand this point for Pharo core but,  I had a look at the code that analyse the class definition AST and I wonder: if one do not follow the `#=>` pattern, why not just allow it but drop tool support for this specific slot declaration ?

I mean, I understand we want to uniformise what happens in Pharo core but outside projects should be able to do whatever they want no?

**Comment by astares** [comment]
@juliendelplanque Yes - I want that too. See discussion here https://github.com/pharo-project/pharo/issues/4636

**Comment by juliendelplanque** [comment]
@Ducasse Maybe we can look together during this Friday sprint to see how it can be done without impacting specific usages of slots.
