### ISSUE TITLE
Text-Core package documentation and test

### ISSUE THREAD

**Issue by hilaire** [guillep/pharo-core#4712]
The Text-Core package need to be more documented and tested: method and class comments, more examples and a better test coverage will be welcome.

**Comment by kasperosterbye** [comment]
This is an interesting question. What should be in the wiki, and what in the image. Ideally the two should live together and supplement each other.

For now, take a look and see if this is helpful:
https://github.com/pharo-open-documentation/pharo-wiki/blob/master/PharoProjects/RichText.md


<blockquote><img src="https://avatars1.githubusercontent.com/u/45095154?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-open-documentation/pharo-wiki">pharo-open-documentation/pharo-wiki</a></strong></div><div>Wiki related to the Pharo programming language and environment. - pharo-open-documentation/pharo-wiki</div></blockquote>

**Comment by Ducasse** [comment]
The answer is simple. 
- more tests in the image
- more executable comments in the image.
- we should adapt the help browser to display pillar external documentation on demand
(if you want to help on this, it would be super nice).

**Comment by MarcusDenker** [comment]
this has been merged
