### ISSUE TITLE
Cannot load Pharo with a metacello script

### ISSUE THREAD

**Issue by dupriezt** [guillep/pharo-core#4719]
Running the following in a pharo 8 image throws a SubscriptOutOfBound exception.
```Smalltalk
Metacello new
	baseline: 'Pharo';
	repository: 'github://pharo-project/pharo:Pharo8.0/src';
	load.
```
The exception happens in MetacelloPlatform>>extractTypeFromDescription:
```Smalltalk
extractTypeFromDescription: description
  description == nil
    ifTrue: [ ^ nil ].
  ((description beginsWith: '/') or: [ description second = $: ])
  ...
```
*description* is an empty string (not nil), so `description second` throws the aforementioned exception.

**Comment by dupriezt** [comment]
The issue comes from BaselineOfPharo defining sub-baseline using `self repositoryPackageURL` (BaseLibraries and IDE). Loading pharo with the metacello script works when these sub-baselines are commented. It also works when these sub-baselines explicitly define the address of the repository: for example `spec baseline: 'BaseLibraries' with: [spec repository: 'github://pharo-project/pharo:Pharo8.0/]`.
```Smalltalk
BaselineOfPharo>>#baseline: spec
	<baseline>
	| repository |
	repository := self packageRepositoryURL.

	spec for: #common do: [
		spec postLoadDoIt: #'postload:package:'.
		spec baseline: 'BaseLibraries' with: [spec repository: repository].
		
		spec baseline: 'IDE' with: [spec repository: repository].
                ...
```

**Comment by dupriezt** [comment]
I set up a simpler repository with a sub-baseline to reproduce the issue quicker: https://github.com/dupriezt/testBsl (instead of having to wait for every package of Pharo to be checked out everytime)
Loading script:
```Smalltalk
Metacello new
    baseline: 'TestBsl';
    repository: 'github://dupriezt/TestBsl';
    load.
```

<blockquote><img src="https://avatars0.githubusercontent.com/u/32486709?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/dupriezt/testBsl">dupriezt/testBsl</a></strong></div><div>Contribute to dupriezt/testBsl development by creating an account on GitHub.</div></blockquote>

**Comment by dupriezt** [comment]
The issue is that BaselineOf>>#packageRepositoryURL does not find the url of the repo when it is loaded as a sub-baseline.
@jecisc suggested adding to it a fallback in case this happens, that would look into iceberg repos for the one that contains the sub-baseline, and take the url from there.
With this change (see below), loading my test repo TestBsl works fine.

**BEFORE**
```Smalltalk
BaselineOf>>#packageRepositoryURL

	" Tries to determine a repository URL from which the baseline is being loaded. Useful for 
	refering other baselines in the same repository. "

	^ self packageRepository
		ifNotNil: [ :aRepository | aRepository description ]
		ifNil: [ '' ]
```
**AFTER**
```Smalltalk
BaselineOf>>#packageRepositoryURL
	" Tries to determine a repository URL from which the baseline is being loaded. Useful for 
	refering other baselines in the same repository. "

	| url packageName |
	url := self packageRepository
		ifNotNil: [ :aRepository | aRepository description ]
		ifNil: [ '' ].
	url ifNotEmpty: [ ^ url ].
	"The following is in case the url of the repository could not be determined. It looks at iceberg repositories in the image to see if any contains the baseline we are trying to load. If there is one, we use its repository url"
	packageName := self class package name.
	^ 'tonel://' , (IceRepository registry detect: [ :repo | repo workingCopy packageNames includes: packageName ] ifFound: [ :repo | repo location pathString , '/' , repo subdirectory ] ifNone: [ '' ])
```

**Comment by dupriezt** [comment]
However, these is a complication when trying to load the pharo repo with this method. Because of the dummy pharo repo iceberg starts with by default (see picture), there is a "#pathString was sent to nil" exception in `#packageRepositoryURL`.

![image](https://user-images.githubusercontent.com/32486709/65602428-25018d00-dfa4-11e9-9247-a5a3bd8b41df.png)

The metacello script successfully loads pharo after this dummy repo is removed by executing:
```Smalltalk
IceRepository registry remove: (IceRepository registry detect: [ :repo | repo name = 'pharo' ]).
```

**Comment by jecisc** [comment]
This is not the case anymore so I'll close this issue
