### ISSUE TITLE
Collection>>#notEmpty should be deprecated

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#4720]
Using an automatic transformation because it just calls `#isNotEmpty` and one of its comment says `#isNotEmpty` should be used instead.

```Smalltalk
notEmpty
	"Answer whether the receiver contains any elements."
	"use isNotEmpty for consistency with isEmpty"

	^ self isEmpty not
```

**Comment by MarcusDenker** [comment]
For these extremely often used methods I would like to add a kind of deprecation which is not a depcation: methods that we keep for backward compatibility, but which transform the caller...

**Comment by juliendelplanque** [comment]
Yeah, I understand what you mean.
I agree.

**Comment by hogoww** [comment]
Doesn't work with rewriting tool, because it's using it.

**Comment by MarcusDenker** [comment]
a newer version has been submitted, I close this one as a duplicate https://github.com/pharo-project/pharo/issues/11309
