### ISSUE TITLE
Pharo 8 freeze on launch on OS X

### ISSUE THREAD

**Issue by sparagi** [guillep/pharo-core#4727]
![Screen Shot 2019-09-25 at 1 28 29 PM](https://user-images.githubusercontent.com/33610997/65629106-655b0e00-df98-11e9-8fce-d9a1ffaa31bb.png)

## Versions

Pharo VM: 5.0.201902062351
Pharo image: 8.0.0 build: 782, commit: 7532efe
macOS Mojave 10.14.6

This was working fine through as least build: 765, commit: 90cc5bd.

## Repro Steps

- Clone a new image (Pharo 8.0 - 64 bit (development version, latest)) using Pharo Launcher.
- Select the image & press play.

Everything inside the Pharo window is completely unresponsive to user input, including Cmd-. (I'm coming from Squeak & just assuming this is still the interrupt key). The OS X menus come up, and some items work, but the window close button and "Quit SqueakOSXApp" do nothing.  The window maximize button maximizes the window, which then looks like TV static.

## Search Terms

The error shown in the image is probably more useful, but for the next person who searches for this, here are a couple of entries from the stack trace:

FFICallout>>resolveType:
FreeTypeFace(Object)>>ffiCall:

**Comment by Ducasse** [comment]
Thanks for your bug report. We have a race condition around glyphs. We will have to fix it again.

**Comment by Ducasse** [comment]
Are you sure that it freezes. Because usually you can just close the window.

**Comment by sparagi** [comment]
For me, it definitely freezes.  I can't quit *Pharo* with the usual OS X window close buttons, and I can't close the window with the error inside Pharo (or do anything else).

**Comment by sparagi** [comment]
Here is a link to the [comparison of the working revision and the broken one](https://github.com/pharo-project/pharo/compare/90cc5bd...7532efe).  The commit messages don't identify any changes likely to cause this, so I am going to look at the changed files next.

**Comment by sparagi** [comment]
Aha!  Pharo Launcher has multiple sections with development versions.  This problem is present in "development version, latest" from the "Official distributions" section.  It is NOT present in build: 784, commit: 1aba218, which is the top entry in the "Pharo 8.0 (development version)" section.

So, this bug is fixed, but it's going to continue to affect Mac users using the "Official distributions" in Pharo Launcher.  Maybe update the version of Pharo 8 that gets launched from this section?  Or, remove the development version of Pharo 8 from this section entirely?

Thank you for your help, and I'm sorry to waste your time looking through code for a bug that was already fixed.  :(  I tried to follow the CONTRIBUTING guidelines but didn't notice the separate section for Pharo 8 in Pharo Launcher.

**Comment by MarcusDenker** [comment]
yes, this happens sometimes, this is a side effect of https://github.com/pharo-project/pharo/pull/3157 and shows a problem with Freetype.

you can press "Cmd-." (command dot) to break the wait on the semaphore and then the image is usable.

**Comment by sparagi** [comment]
I just tried Cmd-. a few more times, swapping in a different keyboard.  Contrary to my repro steps, this worked to make the image responsive again.  I'm going to go clean my usual keyboard now.
