### ISSUE TITLE
asClass should be deprecated

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4732]
If one day we want to have a system with namespace we should not start to use one message that presumes that there is only one namespace.

**Comment by kasperosterbye** [comment]
It seems to me that this depends very much on an implicit assumption on how name spaces are implemented. It would seem like the method `asClass`in string could be written both handle global namespace, current namespace (which I presume is a reified run-time concept anyways), and explicit name spaces (e.g. 'Pillar::Paragraph').

Are you thinking on any specific namespace mechanism where asClass could not be made to work in a useful manner?

**Comment by MarcusDenker** [comment]
Duplicated: https://github.com/pharo-project/pharo/issues/14970
