### ISSUE TITLE
Deprecated DebuggerMethodMapOpal

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#4741]
DebuggerMethodMapOpal is just a tiny facade over the AST... it was there to be compatible to the old compiler, but now that we unloaded the old compiler we do not need it anymore.

after merging https://github.com/pharo-project/pharo/pull/4740 (wich removes one API already) we can just inline the methods into the caller.

This will simplify things *and* speed up the code as we will not have to create a DebuggerMethodMapOpal instance for every call.

**Comment by Ducasse** [comment]
Cool!
This is cool music to my hear. I love this idea that we are improving, cleaning and improving. 
This is super cool.

**Comment by MarcusDenker** [comment]
I Have now changed it to not be used anywhere in the system, that is, all the changes that this PR did with the exception of the deprecations are done.

 I will for now close this (we can deprecate it at some point, but that is not that important)
