### ISSUE TITLE
FileBrowser has troubles with hidden system files on Windows

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#4792]
The FileBrowser cannot work correctly with the hidden system files on the Windows platform.
When you try to navigate to the root of the C: drive, you get:
`FileDoesNotExistException: '/C:/hiberfil.sys'`

**Comment by akgrant43** [comment]
I think this might be a duplicate of: https://github.com/pharo-project/pharo/issues/3571
