### ISSUE TITLE
Add zipped/unzipped to ByteArray

### ISSUE THREAD

**Issue by svenvc** [guillep/pharo-core#4806]
It would be very useful to add #zipped / #unzipped unary methods to ByteArray, as was the conclusion of the following ML thread

https://lists.pharo.org/pipermail/pharo-users_lists.pharo.org/2019-October/044435.html

**Comment by svenvc** [comment]
A real PR will follow, here is the gist of the implementation

````
ByteArray>>#zipped
 "Return a GZIP compressed version of the receiver as a ByteArray"

 ^ ByteArray streamContents: [ :out |
     (GZipWriteStream on: out) nextPutAll: self; close ]

ByteArray>>#unzipped
 "Assuming the receiver contains GZIP encoded data, 
  return the decompressed data as a ByteArray"

 ^ (GZipReadStream on: self) upToEnd
````

**Comment by Ducasse** [comment]
A question are these methods extensions attached to the package of GZipReadStream?
I do not have latest image at hand.

**Comment by svenvc** [comment]
Yes they are extensions in the Compression package

**Comment by Ducasse** [comment]
excellent then!
