### ISSUE TITLE
Epicea: "Monticello save" event only adds noise to log

### ISSUE THREAD

**Issue by tinchodias** [guillep/pharo-core#4817]
At least when Metacello loads a baseline, for example see "MC load"s here:

![Screen Shot 2019-10-03 at 19 43 08](https://user-images.githubusercontent.com/3044265/66169212-0a6b8b80-e616-11e9-85a1-21faa1f4566c.png)

**Comment by tinchodias** [comment]
Also, test fails (skipped in CI): `EpEventIntegrationTest>>#testMCVersionSaved`

**Comment by tinchodias** [comment]
I think we can stop logging this event.

**Comment by Ducasse** [comment]
Yes!
