### ISSUE TITLE
src/SystemCommands-VariableCommands/SycAbstractAllInstVarAccessorsCommand.class.st was removed unintentionaly

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4820]
The class src/SystemCommands-VariableCommands/SycAbstractAllInstVarAccessorsCommand.class.st was removed unintentionaly in #4715

**Comment by MarcusDenker** [comment]
it is still there:

ycClassCommand subclass: #SycAbstractAllInstVarAccessorsCommand
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'SystemCommands-ClassCommands'

**Comment by Ducasse** [comment]
Sorry I do not get what should be done?
Because I can do a PR to add it back.

**Comment by MarcusDenker** [comment]
The thing is that it was not removed... maybe it was moved between packages?

**Comment by MarcusDenker** [comment]
It is still there, so I close this
