### ISSUE TITLE
Pharo 7 ZnBufferedReadWriteStream vs SourceFileBufferedReadWriteStream

### ISSUE THREAD

**Issue by akgrant43** [guillep/pharo-core#4828]
Pharo 8 no longer includes ZnBufferedReadWriteStream in the base image, it's been renamed to SourceFileBufferedReadWriteStream.

Pharo 7 has received the re-written version of ZnBufferedReadWriteStream, which conflicts with the version in Sven's repository.

Leaving this as is means that loading other Zinc components leaves the image in an unusable state (see http://forum.world.st/ZincHTTPComponents-SSO-breaks-ZnBufferedReadWriteStream-td5104621.html)

In Pharo 7 (ccd2a239), can we either:
- make the same changes, i.e. rename ZnBufferedReadWriteStream to SourceFileBufferedReadWriteStream, or
- revert ZnBufferedReadWriteStream to its earlier version?

**Comment by svenvc** [comment]
option 1 please

**Comment by Ducasse** [comment]
+ one :)

**Comment by MarcusDenker** [comment]
This was done, so we can close the issue
