### ISSUE TITLE
Sugs* are commands?

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4830]
I would like to know if I'm correct when I think that Sugs classes (besides the Sugs Context subclasses) are in fact commands.

I need a second pair of eyes to confirm my analysis.

**Comment by Ducasse** [comment]
Julien if you have a moment. I'm interested in your point of view.

**Comment by juliendelplanque** [comment]
I just had a look at it and it seems it is the implementation of a command design pattern. :-)

**Comment by Ducasse** [comment]
:) Ok I thought the same. It looks like this is just the 26th one that we have :).
I will check to see if as a Kata I can replace them by CM2 commands. 
:)

**Comment by MarcusDenker** [comment]
all the Sugs* are already implemented with Commander in Calypso. They are just there as the Debugger uses them. If we change the dubugger to use the same menu building code, we can just remove them.

**Comment by MarcusDenker** [comment]
Closed due to: https://github.com/pharo-project/pharo/issues/5093
