### ISSUE TITLE
Collection>>#piecesCutWhere:do: and Collection>>#piecesCutWhere: should not be implemented in Collection

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#4836]
The implementation of `Collection>>#piecesCutWhere:` relies on `Collection>>#piecesCutWhere:do:` which itself relies on `#copyFrom:to:` which is only implemented in `SequenceableCollection`.

I propose to move this method to `SequenceableCollection` it makes no sense to have a collection implementing it if it is not sequenceable.

**Comment by Ducasse** [comment]
I agree.

**Comment by myroslavarm** [comment]
i see the PR has been merged so this issue should be closed?
