### ISSUE TITLE
Debugger context menu should display Smart suggestions

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4838]
We can get the smart suggestion doing command-T but we cannot see them in the menu.
Esteban I can show you what I'm learning on SmartSuggestions (in essence I have the impression that a large part can be expressed with Commander2) and many context got lost in the process (they are not used anymore). 

![Screenshot 2019-10-05 at 16 43 47](https://user-images.githubusercontent.com/432549/66256563-54c44800-e78f-11e9-8f23-0e116a18f9d9.png)

**Comment by VincentBlondeau** [comment]
Related to #2961

**Comment by Ducasse** [comment]
Thanks Vincent I did not know. 
Now I'm trying to create commands (CM2) out of Suggestions and so that after esteban can use them.

**Comment by StevenCostiou** [comment]
I am closing this one because of the following reasons:
- cmd + T opens the context menu, same as the right click
- SmartSuggestions have been removed if I correctly remember
Please reopen the issue if I am mistaken.
