### ISSUE TITLE
We need to have a Browse menu item 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4839]
that given any object open the class of the object. 
I'm often doing inspect + self class.

**Comment by kasperosterbye** [comment]
`'Ducasse' browse` ?

**Comment by kasperosterbye** [comment]
Or you want it as a menu and keyboard shortcut in the `Playground`?

**Comment by Ducasse** [comment]
in fact I would like that close to inspect it in all the code editors. 
And the implementation is super simple: self class browse.
The idea is to be able to do browse class the same way we do inspect.

**Comment by estebanlm** [comment]
but we have the browse menu item. 
it is in "code search" submenu.

**Comment by Ducasse** [comment]
I never saw it. And it does not work

**Comment by Ducasse** [comment]
![Screenshot 2019-10-09 at 13 44 55](https://user-images.githubusercontent.com/432549/66478576-01a60a00-ea9b-11e9-9936-de90f9d44b4f.png)

**Comment by Ducasse** [comment]
When I select 1 browse it I want to browse the class of 1 = SmallInteger

**Comment by estebanlm** [comment]
> in fact I would like that close to inspect it in all the code editors.
> And the implementation is super simple: self class browse.
> The idea is to be able to do browse class the same way we do inspect.

no, is not as simple. What are you going to browse? If you do `self class browse` inside the inspector you will be browsing `RubSmalltalkEditor`.

**Comment by Ducasse** [comment]
When I select 'aaa' browse it I get nothing. 
Totally bogus this.

**Comment by estebanlm** [comment]
> When I select 1 browse it I want to browse the class of 1 = SmallInteger

no idea why it does not works (maybe someone changed its implementation). But it is there since always.

**Comment by Ducasse** [comment]
If you type Point you get the class Point but this is not the point :).

**Comment by estebanlm** [comment]
you want something that does a "do it" and then browses the result of it, I get it. 
but we do not need a new command, just to fix the one we always had.

**Comment by Ducasse** [comment]
Yes this is like inspect except that it opens class on the inspected object class.
And a new binding would be cool because I do that often. 
In fact cmd+b should be smart enough to do the right job but dev are often modal. 
S.

**Comment by estebanlm** [comment]
problem is when you have more complex situations. Imagine you have this 
```Smalltalk
StInspector inspect: Object.
```
and you ask "browse it". It will execute it, it will open an inspector, and *then* it will browse `SpWindowPresenter`. I'm quite sure you do not want this :)

**Comment by Ducasse** [comment]
Yes this is what I want. The result of expression but browsing its class.

**Comment by MarcusDenker** [comment]
We have this now (there are other issue tracker entries to improve it, but "browse it" is there)
