### ISSUE TITLE
printOn: methods should avoid calling blindly printString on their elements...

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4856]
since it just creates intermediary streams for nothing.

This is ugly! and slow and consuming memory for nothing. 

printOn: aStream

	aStream nextPut: $(;
		nextPutAll: g0Size printString; space;
		nextPutAll: g1Size printString; space;
		nextPutAll: g0Leading printString; space;
		nextPutAll: g1Leading printString; space;
		nextPutAll: charSize printString; space;
		nextPutAll: streamPosition printString.
	aStream nextPut: $).

**Comment by kasperosterbye** [comment]
This is the set of classes to be fixed:
```Smalltalk
((Object allSubclasses 
	select: [ :c| c methodDict keys includes: #printOn: ]) 
		collect: [ :c| c->(c>>#printOn:)  ]) 
			select: [ :a | a value sourceCode includesSubstring: 'printString'  ]
```
(There might be a few false positives as I am doing string matching).

**Comment by Ducasse** [comment]
Thanks!
I thought that we already fixed the ones that should be fixed. I will check.

**Comment by kasperosterbye** [comment]
Actually, it is even more of a mess in some places. Some classes overwrite printString to do the same as the one in `Object`. For example `UUID`. Also there is something fishy about the implementation of `printString` and `printOn:`with `Numbers` and `Integer`.

**Comment by Ducasse** [comment]
Yes I saw this too.

**Comment by svenvc** [comment]
Hmm, UUID>>#printString is an optimization (since the size is fixed).

**Comment by Ducasse** [comment]
Yes. Now we have to check others and also senders.

**Comment by kasperosterbye** [comment]
@svenvc UUID>>printString: is indeed an optimisation. But it limits a buffer to 36, where as the 'non-limited' from ´SequenceableCollection class>>streamContents:limitedTo:´ is 100, so most likely not a big win.

However, I think there are really two issues here:
- Stef's original issue regarding mixing printString and printOn:. 
- And an other issue of classes more or less redundantly implementing both printString and printOn:

**Comment by svenvc** [comment]
At one point, but apparently no longer (I wonder when we lost this), we had something like:

````
new: newSize streamContents: blockWithArg
	| stream originalContents |
	stream := WriteStream on: (self streamSpecies new: newSize).
	blockWithArg value: stream.
	originalContents := stream originalContents.
	originalContents size =  stream position
		ifTrue: [ ^ originalContents ]
		ifFalse: [ ^ stream contents ]
````

Then it is actually a win: the general case creates a buffer of size 100 to answer a sub copy of size 36.

The optimized case directly then creates a string of size 36, and no extra buffer.

**Comment by kasperosterbye** [comment]
Was trying to go through this again, but got stuck at the api being clumsy for solving the issue. `Locale>>printOn:` is an example:

```smalltalk
printOn: aStream 
	super printOn: aStream.
	aStream nextPutAll: '(' , id printString , ')'
```

It would be nice if one could rewrite it to:

```smalltalk
printOn: aStream
  aStream << '(' << id << ')'.
```

But `<<` is defined in `WriteStream` as:
```smalltalk
<< anObject
 	anObject class == collection class
		ifTrue: [ self nextPutAll: anObject ]
		ifFalse: [ anObject putOn: self ]
```
But the `id`of a `Locale` cannot be put on a stream.

So I end up with an implementation looking like this:
```smalltalk
printOn: aStream 
	super printOn: aStream.
	aStream << '('.
	id printOn: aStream.
	aStream << ')'
```

Which is in my opinion  ugly to behold.

Perhaps there are an other way to do this. Perhaps a subclass of Stream which is based on String that implements `<<` to use `printOn:` instead of `putOn:`?

**Comment by svenvc** [comment]
You can do

````
aStream nextPutAll: '('; print: id; nextPutAll: ')'
````

or

````
aStream << '('; print: id; << ')'
````

but I would say:

````
aStream nextPut: $(; print: id; nextPut: $)
````

which are all pretty clean.

Don't mess with trying to make #<< more general, it is not a good idea.

**Comment by astares** [comment]
@Ducasse I guess a rule would make sense to point people to this being ugly... (just opened https://github.com/pharo-project/pharo/issues/8469)

**Comment by kasperosterbye** [comment]
Thanks @svenvc. I had overlooked the `print:` message - learned a bit more of Pharo. 

My solution to my case will then be:

```smalltalk
printOn: aStream 
	super printOn: aStream.
	aStream  print: '(';  print: id; print:  ')'
```

Which I like for its symmetrical handling of constants and variables and keeping the cascade - which will allow `cr` and `tab:`.

**Comment by MarcusDenker** [comment]
We have already ReNoPrintStringInPrintOnRule

**Comment by astares** [comment]
Thanks - so we just need to fix the violators :)

**Comment by kasperosterbye** [comment]
I am on it.

@Ducasse - looking through the "violators", it seems like some of them use `asString` instead of `printString` (some even use both - "suspenders and belt" as we say in Danish). 

I presume that is as bad?

**Comment by svenvc** [comment]
> Thanks @svenvc. I had overlooked the `print:` message - learned a bit more of Pharo.
> 
> My solution to my case will then be:
> 
> ```smalltalk
> printOn: aStream 
> 	super printOn: aStream.
> 	aStream  print: '(';  print: id; print:  ')'
> ```
> 
> Which I like for its symmetrical handling of constants and variables and keeping the cascade - which will allow `cr` and `tab:`.

Hmm, nextPutAll: aString and print: aString (which invokes printOn:) are NOT the same ! The string gets surrounded by single quotes and embedded single quotes get doubled.

**Comment by Ducasse** [comment]
Thanks Kasper. Cleaning this is really nice. It felt off my radar but this is really nice to see more traction.
