### ISSUE TITLE
DrTest - Browse on Test class generates DNU

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#4860]
![image](https://user-images.githubusercontent.com/355455/66381462-ac45fc00-e9b9-11e9-8f97-2c2a464f7b35.png)
![image](https://user-images.githubusercontent.com/355455/66381474-b36d0a00-e9b9-11e9-94c0-167611cab62b.png)

**Comment by myroslavarm** [comment]
is this still relevant?

**Comment by MarcusDenker** [comment]
This seems to be fixed as tests are now shown in a flat list.
