### ISSUE TITLE
CTRL + M does not work anymore under windows

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#4862]
And was working before... but CTRL + N and CTRL +B does work.

PS: I have a Swiss keyboard layout

**Comment by tesonep** [comment]
Hi Vincent,

    It is with the headless vm?

**Comment by Alisu** [comment]
Works on french keyboard.

**Comment by VincentBlondeau** [comment]
@tesonep Nope, it is the last standard stable VM.

**Comment by VincentBlondeau** [comment]
Fixed in Pharo-9.0.0+build.1203.sha.35f9e3d0024bccf46c3928d9f195e26bbe97f563 (64 Bit) with the stable VM
