### ISSUE TITLE
Completion in class comment leads to DNU

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4863]
I made a typo 
:nl and I got a dnu in the class comment pane.

**Comment by MarcusDenker** [comment]
same happened at the start of a method in the method pane.

reason: #parseFaultyMethod: does not return a method in this case but just a RBParseErrorNode.

two fixes needed:

1) fix  #parseFaultyMethod: (should be done as part of this PR)

2) class comment pane should not be a code editor a it is not code (we should add another issue for that)

**Comment by MarcusDenker** [comment]
something like:

parseFaultyMethod: aString
	"parse aString even if syntactically incorrect. Instead of raising an error, we create an AST with RB RBParseErrorNode"
	| ast |
	ast := self parseMethod: aString onError: self errorNodeBlock.
	^(ast class == RBMethodNode)
		ifFalse: [ RBMethodNode selector: #faulty body: ast asSequenceNode ]
		ifTrue: [ ast ]
