### ISSUE TITLE
Epicea does not log super class changes

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#4869]
After an image crash, I noticed that some events are not logged / lost by Epicea.
For example, I had A subclass: #Foo that I changed to B subclass: #Foo

This change does not appear in the session log.

**Comment by demarey** [comment]
@tinchodias

**Comment by tinchodias** [comment]
Hi @demarey this is in Pharo 7, right? did you try in 8?

**Comment by tinchodias** [comment]
Ah, now I see you tagged as 8 milestone. But I don't delete my answer because I still suspect it happens in 7 and that it would be fixed by backporting #2959

**Comment by demarey** [comment]
Hi @tinchodias 

Yes, it happens in Pharo 7. Did not try on Pharo 8

**Comment by tinchodias** [comment]
Then it should be fixed via #4908

**Comment by demarey** [comment]
Yes, I can confirm it is fixed.
Thanks!
