### ISSUE TITLE
[RBRefactoring]RBBrowserEnvironment implementorsOf: doesn't handle well when anding envs

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#4874]
env := RBBrowserEnvironment new.
col1 := ((env implementorsOf: #do:)
				& (env implementorsOf: #size) 
					forClasses: Object allSubclasses) classes.

					
env := RBBrowserEnvironment new.
do :=((env implementorsOf: #do:) forClasses: Object allSubclasses) classes.
size := ((env implementorsOf: #size) forClasses: Object allSubclasses) classes.
col2 := size intersection: do.

self assert: col1 = col2.

**Comment by VincentBlondeau** [comment]
More explanation:
This code get in the Smalltalk environment the subclasses of Object and filter the ones that implement #do: and #size. 

If you do the same request separately, i.e. 1 filter for the #do: and another one for the #size and then take the intersection, you expect to have the same results. Which is not the case.

**Comment by VincentBlondeau** [comment]
Ref #3010

**Comment by VincentBlondeau** [comment]
Test to be integrated to check the fix:

```
RBBrowserEnvironmentTest >> #testAndEnvironmentWithImplementors
	| originalEnvironment objectPrintStringEnvironment andEnvironment |
	originalEnvironment := universalEnvironment implementorsOf: #printOn:.
	objectPrintStringEnvironment := universalEnvironment forClass: Object
				selectors: #(#fullPrintString).
	andEnvironment := objectPrintStringEnvironment & originalEnvironment.
	self universalTestFor: andEnvironment.
	self assert: andEnvironment numberSelectors = 1.
	self assert: andEnvironment classNames asArray = #(#Object).
	self assert: (andEnvironment protocolsFor: Object) size = 1.
	self assert: (objectPrintStringEnvironment & objectPrintStringEnvironment) packages = objectPrintStringEnvironment packages.
	andEnvironment := originalEnvironment 
				& (universalEnvironment referencesTo: #printString).
	self assert: andEnvironment numberSelectors 
				= (originalEnvironment referencesTo: #printString) numberSelectors.
	self assert: andEnvironment classNames asSortedCollection 
				= (originalEnvironment referencesTo: #printString) classNames 
						asSortedCollection

```

**Comment by MarcusDenker** [comment]
The comment to RBAndEnvironment:

"I am the combination of two RBEnvironments, a logical AND. That is:
entity A is in this environment if it is in BOTH environment I am constructed from."

In the test, we have now two environments where the selectors *do not overlap*:

```
originalEnvironment := universalEnvironment implementorsOf: #printOn:.
	objectPrintStringEnvironment := universalEnvironment forClass: Object
				selectors: #(#fullPrintString).
	andEnvironment := objectPrintStringEnvironment & originalEnvironment.
```
That is, "andEnvironment numberSelectors" is 0. And according to the Comment in RBAndEnvironment, it should be, as there is no entity that is in both environments.

If you change the test to build two environments for #printOn:, the and-environment does include it

**Comment by Ducasse** [comment]
Ok thanks marcus. 
So we can close this issue?

**Comment by MarcusDenker** [comment]
I think so... I find it odd how "and" is working, I would have thought that it would combine environments. Maybe boolean operations on things that are sets is not good... we should use the terminology of sets. (intersection...)

**Comment by Ducasse** [comment]
Ah it does not combine the scope but the intersection of the sets?
Indeed we should rename that as intersection, union 
because I would like to have And: as a real and.

**Comment by MarcusDenker** [comment]
I would like to close this issue: The environments are just strange, but they are for now what they are and in this strange model, this behavior we see is what is implemented.

**Comment by Ducasse** [comment]
agreed.

**Comment by VincentBlondeau** [comment]
Thanks for the justification Marcus, I think it makes sense.
