### ISSUE TITLE
Recover lost changes does not apply changes in right order

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#4875]
After an image crash, if you **click yes on "recover lost changes" dialog**, then you select changes and click accept => changes are not applied in the right order.
Epicea tries to declare methods before their class.

Simple case to reproduce:
Create a class Foo, then create #a, #b, #c, #d, #e methods. Make the image crash (on OS X full window -> sleep -> wake up).
=> errors saying that class Foo is not found while trying to declare methods.

What is strange is that if you say no to the recover lost changes window and you use 'code changes' tool from the menu, changes are applied in the right order from the tool.

@tinchodias an idea of what happens?

**Comment by demarey** [comment]
happens in Pharo 7.0
Cannot check in Pharo 8 because of #4876

**Comment by tinchodias** [comment]
I fixed it in 8.0, @demarey Could we still backport the fix to 7.0? it would be great.

**Comment by jecisc** [comment]
@tinchodias Yes please!

**Comment by demarey** [comment]
@tinchodias Very nice if already fixed. If possible, it would be nice to have it for pharo 7.0 too

**Comment by tinchodias** [comment]
I have the fix ready to commit and push. Could you change the milestone of the issue? Not sure how to do it.

**Comment by tinchodias** [comment]
Done, please review #4908. I've written my steps to test it.

**Comment by demarey** [comment]
@tinchodias A bit late, but now works as expected.
Thanks a lot
