### ISSUE TITLE
FileSystemResolver should let the user add its own origins

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4883]
FileLocator uses FileSystemResolver in order to resolve some locations. 

The FileSystemResolver can answer a list of location it can resolve. If the location is in the list, it will ask the resolver, else it will go to the next resolver of the chain of responsibility.

I would like to add my own locations depending on the OS I am on, but currently, the locations are hardcoded. 

It would be great to improve it. I see two possibilities:
- Add a pragma `<origin>` to the methods defining an origin and collect them.
- Store #supportedOrigins into a collection so that we can add our own in we need to.

**Comment by seandenigris** [comment]
Seems like this was fixed by #4885. Any reason not to close?
