### ISSUE TITLE
= instead of ==? in RBMethodRefactoring>>buildSelectorString:withPermuteMap:

### ISSUE THREAD

**Issue by hayatou** [guillep/pharo-core#4906]
RBMethodRefactoring>>buildSelectorString: aSelector withPermuteMap: anIntegerCollection 
	| stream keywords |
	aSelector numArgs **_== 0_** ifTrue: [^aSelector asString].
	stream := WriteStream on: String new.
	keywords := aSelector keywords.
	keywords with: anIntegerCollection
		do: 
			[:each :i | 
			stream
				nextPutAll: each;
				nextPutAll: ' ``@arg';
				nextPutAll: i printString;
				nextPut: $ ].
	^stream contents

**Comment by MarcusDenker** [comment]
this seems to be already fixed, it now uses #=
