### ISSUE TITLE
CrLfExchangeTable is not used anymore after #4912

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4913]
BTW, now this method has no senders in the image:

String class >>
Once https://github.com/pharo-project/pharo/pull/4912 is merged

```
crLfExchangeTable

	^CrLfExchangeTable
```
which might be removed together with:

```
String class >>
newCrLfExchangeTable
	"a table for exchanging cr with lf and vica versa"
	^ Character allByteCharacters collect: [ :each |
		each = Character cr 
			ifTrue: [ Character lf ]
			ifFalse: [ 
				each = Character lf
					ifTrue: [ Character cr ]
					ifFalse:[ each ]]]
```

which is only used by #initialize and a test.

**Comment by MarcusDenker** [comment]
I made a PR that removes all the methods: https://github.com/pharo-project/pharo/pull/5050

we need to remove the variable with a PR generated from the source (as it does not work from the image)
