### ISSUE TITLE
Add a new test for withUnixLineEndings

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4950]
withUnixLineEndings deserves a nicer test and it can be inspired from #4912 PR

Tests already cover it, but this is another way to review its behavior:

original :='asa' , String cr , 'asa'.
self assert: (original at: 4) = Character cr.
newString := original withUnixLineEndings.
self assert: (original at: 4) = Character cr.

**Comment by olekscode** [comment]
I will try to improve that test

**Comment by olekscode** [comment]
I replaced that test with a single assertion which compares two strings and should cover all cases:
```Smalltalk
testWithUnixLineEndings
	| stringWithVariousEndings stringWithUnixEndings |
	
	stringWithVariousEndings := String streamContents: [ :stream |
		stream
			lf;
			nextPutAll: 'lorem';
			cr; cr;
			nextPutAll: 'ipsum';
			cr; lf;
			nextPutAll: 'dolor sit amet';
			crlf ].
	
	stringWithUnixEndings := String streamContents: [ :stream |
		stream
			lf;
			nextPutAll: 'lorem';
			lf; lf;
			nextPutAll: 'ipsum';
			lf;
			nextPutAll: 'dolor sit amet';
			lf ].
	
	self assert: stringWithVariousEndings withUnixLineEndings equals: stringWithUnixEndings.
```

**Comment by MarcusDenker** [comment]
PR https://github.com/pharo-project/pharo/pull/5811 has been merged that fixes this
