### ISSUE TITLE
crLfExchangeTable has no senders

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4951]
BTW, now this method has no senders in the image:

String class >>
crLfExchangeTable

	^CrLfExchangeTable
which might be removed together with:

String class >>
newCrLfExchangeTable
	"a table for exchanging cr with lf and vica versa"
	^ Character allByteCharacters collect: [ :each |
		each = Character cr 
			ifTrue: [ Character lf ]
			ifFalse: [ 
				each = Character lf
					ifTrue: [ Character cr ]
					ifFalse:[ each ]]]
which is only used by #initialize and a test.

**Comment by MarcusDenker** [comment]
yes, there is issue #4913 for this already (I close this)
