### ISSUE TITLE
SequenceableCollection>>#concatenation is not used and should maybe be removed

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#4966]
It just flatten on one level the collection.

```Smalltalk
#((1 (2)) (3) (4 5)) concatenation. "#(1 #(2) 3 4 5)"
```

It is totally equivalent to `#flatCollect:` with `#yourself` as argument.

```Smalltalk
#((1 (2)) (3) (4 5)) flatCollect: #yourself. "#(1 #(2) 3 4 5)"
```

Either it should be removed or renamed as `#flatten` to ease discovery.

**Comment by Ducasse** [comment]
I would remove it because it is more confusing that anything else. 
flatten is the way to go. So we can rename concatentation (I do not even understand why concatenation behavior is flatten) into flatten!
Good catch!

**Comment by kasperosterbye** [comment]
There is actually a `#flattened` (not `flatten`), in `Collection` which flattens. Also there is no senders of `concatenation`. And for most usages I can come up with, instead of `concatenation` you are equally well of using `joinUsing:`. 

I say throw it out.

**Comment by Ducasse** [comment]
Oki
