### ISSUE TITLE
Epicea: Reverting a class remove looses class comment

### ISSUE THREAD

**Issue by tinchodias** [guillep/pharo-core#4969]
Checked in P7 and 8.
Steps:
1. EvaluatE:
~~~
c := Object subclass: #Loremipsum1.
c comment: String loremIpsum.
c removeFromSystem.
~~~
2. Browse the class: the class comment is there
3. Open class changes browser and revert the class removal.
4. Browse the class: ccomment is not there.

**Comment by macie** [comment]
Also exist in Pharo 9
