### ISSUE TITLE
Extract method is not working ok with string/symbol literals

### ISSUE THREAD

**Issue by gcotelli** [guillep/pharo-core#4972]
If you have a method including a symbol literal and already exists in the same class another method returning an string equivalent to it, the extract method will use the existing method which is incorrect because it can broke existing code.

For example:
 ```smalltalk
TestClass>>method1

  self doSomething: #symbol

TestClass>>symbolString

  ^ 'symbol'
```
if you select `#symbol` and use the extract method option the resulting code will be:
 ```smalltalk
TestClass>>method1

  self doSomething: self symbolString
```

**Comment by Ducasse** [comment]
Argh good catch.
probably a problem with symbol and string being equals.
