### ISSUE TITLE
RB extract method fails to replace other calls that could be extracted inside the same method

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4973]
I thought that I made  a mistake but there are some cases where indeed  extract method fails to replace other calls that could be extracted inside the same method.
It happened to me with two class refs. 
I extracted the first one 
and the second one was not changed when the system asked me if I want to extract them all.

**Comment by maenu** [comment]
Cannot reproduce. If I have the method:
```
do
	String new.
	^ String
```
then select `String` and use `Extract method`, it asks me to replace both references and does it accordingly to something like:
```
do
	self objectClass new.
	^ self objectClass
```
Do you have a method where the behavior you describe happens?
