### ISSUE TITLE
deprecate withSqueakLineEndings

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4992]
Once tonel is updated to use withInternalLineEndings we
can deprecate 

withSqueakLineEndings
	"Answer a new instance where all occurrences of CRLF and LF are substituted with CR."
	
	self deprecated: 'Use #withInternalLineEndings instead.' transformWith: '`@receiver withSqueakLineEndings' -> '`@receiver withInternalLineEndings'.
	^ self withInternalLineEndings

And not do it before :)

**Comment by MarcusDenker** [comment]
this was done
