### ISSUE TITLE
Possible memory leak in SpApplication>>defaultApplication

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#4999]
I am not 100% sure about this one, but it looks fishy.

When I do `openWithSpec` on something which inherits from `SpPresenter` and debug it, I end up here:
<img width="435" alt="image" src="https://user-images.githubusercontent.com/17723745/67615043-606fc100-f7c7-11e9-88ab-8aec5d3f8b31.png">

`defaultApplication` makes use of a classVariable to cache the null application.
```Smalltalk
defaultApplication
	^ DefaultApplication ifNil: [ DefaultApplication := SpNullApplication new ]
```
That means that later in the code where

```Smalltalk
SpNullApplication>>open: aPresenter withSpecLayout: aSpecLayout using: aWindowClass
	| window |
	self validateApplicationOfPresenter: aPresenter.
	window := aWindowClass presenter: aPresenter.
	self windows add: window. "<--------- leak"
	window openWithSpecLayout: aSpecLayout.	
	^ window
```

As I was experimenting I ended up with 40+ instances of windows in the window collection of the cached `SpNullApplication`.

It would seem to me that either it is a bad idea to cache the defaultApplication, or something should be done when the window closes.

**Comment by Ducasse** [comment]
tx kasper!

**Comment by estebanlm** [comment]
It needs to be a singleton, because otherwise is impossible to track the window flow.
but yes, they need to be collected on close. I know there was a bug that is already fixed (maybe not integrated into Pharo yet), but they may be other places of leak.

**Comment by kasperosterbye** [comment]
Got bitten by that one again today.
I believe it is somehow related to when my window crash and I exit less than elegant from the debugger. I will keep an eye for how to replicate it.

**Comment by estebanlm** [comment]
but this is most probably because something else is preventing the window to actually execute the `windowClosed:` method and consequently triggering the unregistering of windows... without I reproducible case, it is hard to know  what is happening.

**Comment by kasperosterbye** [comment]
I'll keep an eye out for this one and try to see if I can replicate it
