### ISSUE TITLE
Debugger better create method

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5005]
In TDD we may want to define a method size that does not exist yet and running the test should lead to an error and the possibility to create the method. Right now this is not possible because size raised an error when it was executed. 

testSorted 

	| c |
	c := CBookCollector smallCollection.
	self assert: c size equals: 4.

**Comment by MarcusDenker** [comment]
size  is implemented in Object, thus the method does exist already.

**Comment by StevenCostiou** [comment]
Is this still valid? 
I think now method creation from the debugger works?

**Comment by dupriezt** [comment]
Calling #size on an object whose class does not define it uses the default implementation of Object>>#size, which signals an error that the object is not indexable.
It looks like the system is working as it should...

@Ducasse 
Do you mean you would like a special case in the debugger that if the error is "errorNotIndexable", then the debugger offers to create a #size method on the class of the object to which #size was initially sent?

**Comment by MarcusDenker** [comment]
Yes. I always found it very ugly that #size, #at: and #at:put: are in Object... sadly it is not easy to change: People are expecting that they can do a variable subclass of Object and that then #size works.

I think the only real solution... would be a radical one: Now that the object layout is modelled not just as an object, we could imagine a system where being of a certain *layout* would influence which methods are provided. That is, the layout could add a kind of Trait by default to a class.

If we would do that, we could remove #size from Object, but any class that uses VariableLayout would get the methods from there.

**Comment by StevenCostiou** [comment]
What can we do for the moment and regarding this issue?

**Comment by MarcusDenker** [comment]
I do not think that we can do anything, I will close it

**Comment by guillep** [comment]
I don't understand why this issue is being closed. This issue is very important for newcomers.
I think for TDD we should have the possibility to have something like "redefine it".

It's not we cannot think a smart way to do that.

**Comment by StevenCostiou** [comment]
I wonder: is this really a debugger issue?

**Comment by StevenCostiou** [comment]
> I don't understand why this issue is being closed. This issue is very important for newcomers.
> I think for TDD we should have the possibility to have something like "redefine it".

You mean in the debugger?
This is tricky, as by definition if the method exists, it's working and in that case redefining it is usually done by doing so in the class browser.

What you say is that, for each method producing an error, adding the possibility to redefine it?

**Comment by guillep** [comment]
Maybe, I'm doing TDD all the time, and personally I code 80% of my time in the debugger. I almost write no code in the browser. So constraining me to the browser seems artificial. Ideally, the debugger should do everything the browser does and more, because it has dynamic context :)

**Comment by StevenCostiou** [comment]
Hmm it's one vision.
But I do not get how it would work in practice: what would be your flow?

Method call -> DNU -> create (ok)
Method call -> method execution -> failure -> redefine (in the receiver) ?

If so, that is a new feature, and not an actual issue right?

**Comment by guillep** [comment]
> Hmm it's one vision.

Always, I speak for myself :)

> If so, that is a new feature, and not an actual issue right?

I'd say "I don't care". If we go into those technicalities: an issue is not necessarily a bug. A feature request could be seen as an issue.

> Method call -> DNU -> create (ok)
> Method call -> method execution -> failure -> redefine (in the receiver) ?

Maybe, don't know. This is a just a recurrent problem, the solution needs thought.
We were discussing with @Ducasse some minutes ago and one possibility is that we could do a right click on the frame in the stack and say "Redefine it in my class". That could be redefined with a `shouldBeImplemented` as the other. Or even with a `super xxx`. But I do not reject other solutions :)

**Comment by Ducasse** [comment]
Hello guys,
If you do not want to do it, don't do it. but keep it open so that we can add it during a sprint. 
It would be a cool addition. 

I'm in positive energy. I add such kind of issue to improve our situation. 
So take it as it.

**Comment by Ducasse** [comment]
May be just the time that we discuss we could have done :). 
Let us be positive and build a great system.

**Comment by StevenCostiou** [comment]
Don't get me wrong I'm totally for that kind of improvement.
I just need to understand, and after I organize issues into categories and urgency/priority to ease the sprints (bugs, improvements, etc.) and manage some kind of roadmap.

**Comment by Ducasse** [comment]
Ok to me this would be good addition.

**Comment by adri09070** [comment]
I f I understand well what is said here, then if, when the user tries to recompile a method, the debugger asks the user where  the method tshould be recompiled, it should solve this issue, right?: https://github.com/pharo-spec/NewTools/issues/453

**Comment by MarcusDenker** [comment]
No, I think that the idea is that if a method is implemented in object like #size *but * raises and error, that the debugger in that case should ask if you want to create a method in one if the subclasses instead.

I wonder how many cases there are besides #size...

**Comment by adri09070** [comment]
Yeah, well, ok.

But what I mean is that my proposal in https://github.com/pharo-spec/NewTools/issues/453 is more generic than that and could solve the problem.

If the method is implemented in a superclass (e.g. object) and raises an error, a debugger opens and it is then possible to change the method with normal DDD style, except that when the method is recompiled, the debugger asks the user in which class the method should be recompiled. So if the user chooses another class than the one the method is defined in , the latter stays the same while the new method is compiled in the class the user has chosen.

The only difference with the solution discussed above is that the debugger does not ask systematically to redefine the method. I would hate that and listing specific cases is ugly and does not make sense to me. Letting the user choose to redefine it or not after they have expressed the will to modify the method seems more logical to me

**Comment by MarcusDenker** [comment]
Nice, yes, to me this sounds like a good solution!

**Comment by MarcusDenker** [comment]
(I close this issue)
