### ISSUE TITLE
Do we need NECEntry>>#browseWith: and NECSelectorEntry>>#browseWith:?

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#5007]
In Pharo 8 I see two methods:
- NECEntry>>#browseWith:
- NECSelectorEntry>>#browseWith:

Both are invoking a method that seems to not exist in their class.

Do we need them? @MarcusDenker

**Comment by MarcusDenker** [comment]
Yes, This is work in progress. I will work in it this week

**Comment by MarcusDenker** [comment]
I added in issue #5033 a method to explain this
