### ISSUE TITLE
Undoing a refactoring is not working anymore

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5010]
and this is important to be able to do it.

**Comment by dupriezt** [comment]
Is there already a way to undo refactorings, but it's not linked to a button in the menu entry yet?
I've looked quickly but did not find an #undo method on the refactorings classes.

**Comment by VincentBlondeau** [comment]
I do not think there is already a way. It should be added (and the button too).

**Comment by Ducasse** [comment]
There is an undo refactoring. You can ask the RefactoringManager for it. 
I thought that evelyn did it may be this is in her repo. 


Hi evelyn

I’m trying to understand how to reintroduce the undo in the refactoring. 
Here is my analysis but I may be wrong

A RBRenameInstanceVariableRefactoring produces changes.
A change returns an undo changes as defined by the asUndoOperation
For example,
```
AddInstanceVariableChange >> asUndoOperation
	^ changeFactory removeInstanceVariable: self variable from: self changeClass
```
	invoked by 
```
executeNotifying: aBlock
		| undo |
		undo := self asUndoOperation.
		undo name: self name.
		self primitiveExecute.
		aBlock value.
		^ undo
```
The RBFactoryChangeManager is a singleton and it collects all the changes and has the logic to propose undo and redo.
So may be we can try to get a menu proposing an undo showing a list of (undo) changes that can applied. 

Stef

**Comment by Lin777** [comment]
Undo refactoring is available in World Menu, I don't understand well how it works but I'll review. So... by the moment you can use this Feature selecting WorldMenu >> Tools >> Undo Last Refactoring 
<img width="363" alt="imagen" src="https://user-images.githubusercontent.com/15729309/100622040-c4cc5080-32f6-11eb-919b-f12b36d5eb49.png">
