### ISSUE TITLE
evaluate: aString andDo: aBlock should better handle buggy expressions. 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5013]
For example if I type menuOn: do it 
it would be good to have something else that a crappy feedback variable or expression expected -> ....

We should get an error that we can then decide what to do.

**Comment by MarcusDenker** [comment]
I do not understand how todo it better: 
"do it" means : execute this selected code. The parser might not be able to parse it, so it shows that parse error. There is no better error that can be shown, as this is what the error is.

**Comment by Ducasse** [comment]
We should remove the -> logic modifying the original code is a cheap and dated way to report error. 
We should raise an error and let the client decide what to do.
