### ISSUE TITLE
Author => towards User reification

### ISSUE THREAD

**Issue by cdrick65** [guillep/pharo-core#5040]
(again not a bug - more a feature request)
User is a central entity of the system. Especially in images systems where a user is also a programmer, an Author of code (and eventually data ?). 

Right now the Author class exists but is limited to a full name string. Its responsibilities is indeed only to mange author stamps on the produced code.

**What do you think of the current implementation of Author. It should be more than a fullname string to me. An identifier like the GitHub account, some others (1..*) ?** 
This could enhance the licence register of all code and also the integration of GitHub accounts.

Related is the **possibility to think a minimal reification of the User space**. I think that'd be a great addition to offer the possibility to register (as a user) a bit more precisely and provide maybe a minimal extensible interface for applications.

I have some ideas but nothing concrete, hence the **bug entry so that people may discuss it** (tell me if inappropriate as bug entry). Maybe people have pointers on that subject.

So KISS. I'm the main user of my system when I open an image and as a side effet the Author like today. I imagine an Author being a User. 
> Is it a subclass or is it better a Role based approach ?

I don't mean to make an image multi-user at the same time (there is only one user behind the keyboard at a time...). We could at first offer the possibility to switch user fro settings.

Later maybe we could extend to multiple user (through different interfaces - physical/distant).
...

What do other people think ?

**Comment by jecisc** [comment]
The Author class got removed totally from Pharo in P12. Should we keep this issue?

**Comment by Ducasse** [comment]
Close
