### ISSUE TITLE
DrTest doesn't report expected failure.

### ISSUE THREAD

**Issue by hogoww** [guillep/pharo-core#5069]
On the mini version, it doesn't show that there was expected failures (which one may forget in time)
On the full version, it doesn't allow you to browse them as failures. Semantically, this wouldn't make sense, but I think that sometimes that would allow you to come back to your expected failure, and verify that  they are still valid in the current state of your project.

**Comment by MarcusDenker** [comment]
I merge this into the newer issue https://github.com/pharo-project/pharo/issues/9545
