### ISSUE TITLE
Add byteAt: as alias to digitAt: to Integer in Pharo 7 to support forward compatibility with Pharo 8

### ISSUE THREAD

**Issue by svenvc** [guillep/pharo-core#5077]
Add byteAt: as alias to digitAt: to Integer in Pharo 7 to support forward compatibility with Pharo 8

**Comment by svenvc** [comment]
Correct PR is https://github.com/pharo-project/pharo/pull/5079 (against Pharo 7)

Wrong PR is https://github.com/pharo-project/pharo/pull/5078 (against Pharo 8)

**Comment by MarcusDenker** [comment]
merged
