### ISSUE TITLE
Creating a method from debugger goes into infinite loop when typing something in the class list

### ISSUE THREAD

**Issue by hogoww** [guillep/pharo-core#5097]
Not sure this belong here, might be for spec2, didn't find a similar issue.

When creating a method from the 'create' button of the debugger, if you enter a string in the 'research' bar under the class names, it goes into an infinite loop. Sometimes breakable ( seems to be with a small number of character)

(tested on the last p8 version of the launcher)

**Comment by pavel-krivanek** [comment]
easier way how to reproduce:
```
UIManager default 
	chooseFrom: #(1 2 3)
	title: 'chose one'.
```
I think is similar error we had with the find&replace dialog. It is a side-effect of replacing of all simple text inputs with Rubric ones.
