### ISSUE TITLE
Broken step Through a message with error handler that raises an exception

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#5103]
Let's have a code that has an error handler that raises another error (translation of the exception or simply a bug)
```smalltalk
[ self methodWithError ] ifError: [ self error: #transformedError ]
```
And let's have a method that has a bug (raises DNU) and has a breakpoint or halt inside
```smalltalk
methodWithError

	self halt.
	self nonExistingMethod.
```
When stepping Through this method, the debugger hangs.

**Comment by pavel-krivanek** [comment]
Testing code:
[issue5103.zip](https://github.com/pharo-project/pharo/files/3824786/issue5103.zip)

**Comment by Ducasse** [comment]
Steven is working on the debugger. But I cannot assign him.

**Comment by bencoman** [comment]
I guess the same error is produced by evaluating the following in Playground...
```
Author fullName: 'ErrorDemo'.

class := Object subclass: #My
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'AAA-My'.
	
class compile: '
methodWithError
	self halt.
	self nonExistingMethod.
'.

[ class new methodWithError ] ifError: [ self error: #transformedError ]
```
and then clicking \<Through\>\<Through\>.

Seems to have been around since Pharo 5.

**Comment by StevenCostiou** [comment]
Fixed by https://github.com/pharo-project/pharo/pull/8426
