### ISSUE TITLE
The Through button in the debugger should be named Step

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#5104]
The Through button in the debugger should be named simply Step. In most cases, it is the kind of stepping the users want and this name is more friendly and understandable to newcomers.

**Comment by Ducasse** [comment]
I agree. 
Now I do not understand the different between through and step over and step into. 
I hate all these names.

**Comment by svenvc** [comment]
I think that is Pavel's point: doing Trough is the most common, hence could be named Step, to help steering people in the right direction.

But this is not so simple: there are the expectation that people might have from other environments, and the other options that need clear names too.
