### ISSUE TITLE
Division by zero for Float should be infinity

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#5117]
`2.0 / 0.0` should be `Float infinity` according to the IEEE754. But it raises division by zero.

Should `2 / 0` also yield `Float infinity`? (as there is no other infinity)

Same goes for `0.0 raisedTo: -1.0`, which should also be Float infinity.

On the other hand `0 log` do properly yield `Float negativeInfinity`.

**Comment by astares** [comment]
Maybe we review my old Infinity goodie from Sthub

**Comment by kasperosterbye** [comment]
Do you have a link @astares ?

**Comment by astares** [comment]
Visit Smalltalkhub.com and search for Infinity

**Comment by kasperosterbye** [comment]
I checked out your old library @astares. I like the idea of factoring out Infinity as a special class in itself. 

I finally got done what I should have done from the beginning, reading the scripture (the ansi standard), which states that `2.0 / 0.0` *can be* `Float infinity, whereas `2 / 0` *must* raise an exception. (paragraph 5.6.2.4 Message: / operand).

It hurts my eyes to have that difference. That was what caused me to raise the issue. I am not going to bother entering into a discussion of making Pharo numbers divert from the standard and will close this issue.

**Comment by kasperosterbye** [comment]
I checked out how Java relates to this same issue. Integer division by zero raises a runtime exception, Floating division by zero returns infinity. While I believe it might be a surprise to some, at least it is consistent with both IEEE754 and the smalltalk standard (paragraph 5.6.2.4).

I therefor reopen this issue, and suggest that we adopt this principle. 2.0 / 0.0 should return Float infinity. 
@astares - lets have a chat about your idea of infinity at some point. But right now, I suggest that we merely change behaviour of Float.

**Comment by kasperosterbye** [comment]
Too many tests fail, it is too build into the type conversions to get a clean implementation. I will not touch numbers again until someone ask me to do so...
