### ISSUE TITLE
To check: PharoLauncher and Catalina

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#5121]
We got one question on twitter:

"are you guys aware of this issue on #macOS Catalina? Any known workarounds"

It shows a warning "PharoLauncher can not be opened because Apple can not check it for malicious software"

https://twitter.com/frr149/status/1192919428696068100

(I personally use the command line and not PharoLauncher, so I have never seen it)

**Comment by Ducasse** [comment]
The pharo vm has not been signed for catalina and this is probably the cause?
Christophe? 
This is also why it would be good to signed with our PGP key our distribution

**Comment by janniklaval** [comment]
Hi guys,

It works fine here.

**Comment by frr149** [comment]
This happens when you install Pharo on macOS Catalina and then try to run the PharoLauncher. Maybe you need to [notarize](https://developer.apple.com/news/?id=09032019a) the file.

**Comment by frr149** [comment]
[Pharo is not alone in this situation](http://www.nathalielawhead.com/candybox/the-future-of-my-games-on-apple-post-catalina-and-what-this-means-for-art-games-in-general). Sounds like Apple running a scam... :-(

**Comment by SergeStinckwich** [comment]
PharoLauncher works fine for me on MacOS Catalina.

**Comment by MarcusDenker** [comment]
ok, so it can be closed
