### ISSUE TITLE
Why while RBNullFormatter PR has been merged, the class is still there?

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5142]
the class is still in the latest image?
https://github.com/pharo-project/pharo/pull/5137

I need help to understand because in my image Pharo 8.0.0
Build information: Pharo-8.0.0+build.972.sha.bbb812d1387fd27ef4096e35224cb4425a60ab6c (64 Bit)

I still have the old RBNullFormatter and the wrong name for SimpleFormatter. 

I need help.

**Comment by MarcusDenker** [comment]
Because the mac slave was down, there where no build done.

The current image now has no class RBNullFormatter.

(For me the rule is: if the CI is down, I stop all work)

**Comment by MarcusDenker** [comment]
We merged PRs that added failing tests, too. We should really not merge anything when the CI is down.
