### ISSUE TITLE
Improve CompiledCode>>hasLiteralThorough: literal

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5154]
CompiledCode>>hasLiteralThorough: literal
        .....	
        2 to: self numLiterals - 1 "exclude header and methodClass or outerCode"
	   do:[:index | | lit |
		(((lit := self objectAt: index) literalEqual: literal)
		 or: [lit isArray and: [lit hasLiteral: literal]]) ifTrue:
			[^ true].
		(lit isMemberOf: CompiledBlock) ifTrue: [ (lit hasLiteralThorough: literal) ifTrue: [ ^true ] ] ].
	^ false 

It looks quite bad. It should simply delegate to literal instead of all these type checks.
In that case VariableBinding as a literal could implement such message and we will avoid class name analysis by users of senders query. Actually it is not a senders query but a literal references query.

I would also simplify names of those methods. I do not get this "Thorough" word. Simple #refersToLiteral: is much better. In fact it is existing method with deprecation comment inside. I think we should rethink it

**Comment by MarcusDenker** [comment]
merged!

**Comment by dionisiydk** [comment]
Hm. It is not done really. The PR referenced here just mentioned this issue as discovered one .
How to reopen issue? I do not see any button for this

**Comment by MarcusDenker** [comment]
Sadly you need commit rights to re-open (the rights model of GitHub for the issue tracker is not good), I reopened

**Comment by demarey** [comment]
@dionisiydk Did you check https://github.com/pharo-project/pharo/pull/5613?

**Comment by dionisiydk** [comment]
Sorry guys. It seems my image is too old but I really downloaded it yesterday. I will check again

**Comment by Alisu** [comment]
Did you download a pharo80 image ? Cause the change is only in pharo 90 and it needs to be backported.

**Comment by MarcusDenker** [comment]
I will *not* be back ported!!! The whole idea of doing a release is to stop doing things like that in the released version.

**Comment by dionisiydk** [comment]
I tested on pharo 9 but probably not fresh enough. Sorry for noise.

чт, 6 февр. 2020 г., 09:05 Alisu <notifications@github.com>:

**Comment by dionisiydk** [comment]
Just confirm that it's all in the image.

But I found another ugly method AdditionalMethodState>>refersToLiteral: 
```Smalltalk
(propertyOrPragma isVariableBinding
			ifTrue: [propertyOrPragma key == literal
					or: [propertyOrPragma value == literal
					or: [propertyOrPragma value isArray
						and: [propertyOrPragma value hasLiteral: literal]]]]
			ifFalse: [propertyOrPragma hasLiteral: literal]) ifTrue:
```
We can define refersToLiteral: in Pragma and VariableBinding (or what is the property here?). And the code will be very simple:
```Smalltalk
1 to: self basicSize do: [:i |
		| propertyOrPragma "<Association|Pragma>" |
		propertyOrPragma := self basicAt: i.
                (propertyOrPragma refersToLiteral: literal) ifTrue: [^true]
```

**Comment by demarey** [comment]
Yes, you're right Denis! We did not touch this one : end of the sprint and also were not sure on which class to add `#refersToLiteral:` for VariableBinding. On LookupKey and WeakKeyAssociation?
On Magnitude with a check on isVariableBinding?

**Comment by MarcusDenker** [comment]
The hierarchy is a little bit of a mess for VariableBindings (and I still have on my TODO to explore to make it's own hierarchy independent of Association). 

For now I would add it to the two classes where we have #isVariableBinding and then clean that up as part of the VariableBinding cleanup.

**Comment by MarcusDenker** [comment]
I added https://github.com/pharo-project/pharo/issues/5724 for the next step and will close this issue
