### ISSUE TITLE
Inspector should not open blindly any file without asking the user

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#5187]
We should be a limit on the size of the file like 500 ko or 1Mo before showing a popup.

**Comment by bencoman** [comment]
Thats only saying what should be done, not what the problem is.
What are the steps to reproduce and what behaviour is observed?

**Comment by Ducasse** [comment]
Try to open a file of multiple mb in the inspector. 
FOr example a dot.st file of 124Mb

**Comment by VincentBlondeau** [comment]
Problem is now handled for most of the file (only the first bytes are shown in the inspector).
Except the .zip files: opening a large one still have issues.
Coming from: AbstractFileReference >> inspectionCompressedItems

**Comment by estebanlm** [comment]
> Try to open a file of multiple mb in the inspector.
> FOr example a dot.st file of 124Mb

this is in fact working (or should) : contents are cut at 10k always.

**Comment by estebanlm** [comment]
> Problem is now handled for most of the file (only the first bytes are shown in the inspector).
> Except the .zip files: opening a large one still have issues.
> Coming from: AbstractFileReference >> inspectionCompressedItems

this is a problem that happens when you have a lot of files, then... since this is a table to show contents.  
You have : 
```Smalltalk
children := root directories, root files.
```

and it seems that's the problem (collecting the entries).

can you confirm this is the case?

**Comment by fedemennite** [comment]
This doesn't seem an issue for us anymore.
Can be closed at your convenience.
