### ISSUE TITLE
Popup when scoping packages should have the already selected packages

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#5192]
![56NQ3eq18Z](https://user-images.githubusercontent.com/4706329/69257777-e4954880-0bbb-11ea-882a-8b806d688b1a.gif)

**Comment by jecisc** [comment]
+1

**Comment by dionisiydk** [comment]
Agree. 
But notice that there is a Scope radio button below the package list. It enables the scope using selected packages.

**Comment by VincentBlondeau** [comment]
Fixed
