### ISSUE TITLE
WeakValueDictionary includesKey: returns true after value is collected.

### ISSUE THREAD

**Issue by tblanchard** [guillep/pharo-core#5202]
Pharo 7 64 Bit (stable) MacOS launched from Pharo Launcher.

I found this while running Garage driver registry tests and one of those failed - I tracked it to this underlying cause.

I have created the following test in WeakValueDictionaryTest

```
testIncludesKeyIsFalseAfterGarbageCollection

	self assert: (self dictionaryWithGarbageCollectedValue includesKey: self keyWithGarbageCollectedValue ) == false description: 'Key for garbage collected value still present in WeakValueDictionary'
```

and sure enough it fails.

This method is inherited from Dictionary. It can be fixed with this override in WeakValueDictionary

```
includesKey: key
    (self at: key ifAbsent:[nil]) ~~ nil
```

**Comment by jecisc** [comment]
Hi,

Can you check in Pharo 8, please? I fixed multiple bugs in WeakValueDictionary during the Pharo 8 development and I think this is one of them.

**Comment by jecisc** [comment]
https://github.com/pharo-project/pharo/commit/e37f126a898a2d90375ab94bf58cbf2f5fee46ef

**Comment by tblanchard** [comment]
Yes, it is fixed in 8.

**Comment by MarcusDenker** [comment]
it might be a candidate for back porting

**Comment by tblanchard** [comment]
I will leave it to you guys to decide on closing this.

**Comment by MarcusDenker** [comment]
With Pharo8 released, I propose to close it
