### ISSUE TITLE
DrTest has strange UI overlapping in grouping selection widget

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#5205]
DrTest is integrated into Pharo 8 now - but there seems to be a strange bug
in overlapping widgets when one uses the grouping selection box.

![drtest](https://user-images.githubusercontent.com/5980033/69408134-73ae7780-0d06-11ea-859c-a20334a07c7e.png)

**Comment by oliveiraallex** [comment]
This looks like a Morphic issue.

When you open a Window with a button and list, the mouse down works when your last click is in the button but not in the list.

E.g.: 
SpDropListPresenter new 
	items: #(1 2 3); openWithSpec.

In Morphic PluggableButtonMorph class there is a implementation of #triggerOnMouseDown: 
I think we need something like that in PluggableIconListMorph class.

**Comment by MarcusDenker** [comment]
This seems to be fixed
