### ISSUE TITLE
Executable comment checker problem

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5212]
I do not get why Bag >> includes: executable is reported as an error.
Same for 
![Screenshot 2019-11-24 at 09 46 26](https://user-images.githubusercontent.com/432549/69492189-4f39d300-0e9f-11ea-99f7-a1a50a3bcc7d.png)

**Comment by Ducasse** [comment]
https://github.com/juliendelplanque/DrTests/issues/99

**Comment by svenvc** [comment]
Because it is not valid syntax ?

It should be

    (#(1 2 3) includes: 5) >>> false

no ?

>>> is a unary message

**Comment by juliendelplanque** [comment]
Yes, syntax is invalid.
