### ISSUE TITLE
Executable comments should support a kind of skipping of the execution.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5225]
May be we should have a simple marker to cancel the execution. This way we can avoid to have errors

"Return a collection of pharo comment nodes: expressions following the pattern expr1 >>> expr2. no-test"

so that 

parseDocComments: aRBCommentNode
	| ranges |
	ranges := self docCommentRangesIn: aRBCommentNode contents.
	^ ranges
		collect: [ :range | 
			| expression result exps |
			exps := '>>>' split: (aRBCommentNode contents copyFrom: range first to: range last).
			expression := PharoDocCommentExpression new
				expressionInterval: (range first to: range first + exps first size - 1);
				source: aRBCommentNode contents.
			result := PharoDocCommentExpression new
				expressionInterval: (1 + range last - exps last size to: range last);
				source: aRBCommentNode contents.
			self expression: expression result: result inComment: aRBCommentNode ]

**Comment by hogoww** [comment]
Is this still a problem, or did your PR correct this?

**Comment by MarcusDenker** [comment]
after https://github.com/pharo-project/pharo/pull/11784 this is not needed anymore, as a doc comment needs to have a >>> as the last message send
