### ISSUE TITLE
SystemDependencies tests are failling

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#5230]
testExternalUIDependencies
testExternalBasicToolsDependencies
testUndeclared

are failing in the CI

**Comment by MarcusDenker** [comment]
this seems to be after integrating https://github.com/pharo-project/pharo/pull/5218

**Comment by Ducasse** [comment]
Yes I mentioned that I will fixed them once I removed BlueInk and after I integrate enlumineur. 
And remove GTEVentRecorder. I do not want to do 3 times the same and generate 3 PRs with potential conflicts.

**Comment by Ducasse** [comment]
Now I really understand how useful are such tests.

**Comment by MarcusDenker** [comment]
Somehow we lost AST-Core-Tests (all tests for the AST). Did you remove it?

**Comment by MarcusDenker** [comment]
The SystemDependency test are now fixed. But there are others that still fail. I open new entries
