### ISSUE TITLE
Metacello loading github project crashes image on windows 10 x64

### ISSUE THREAD

**Issue by riverdusty** [guillep/pharo-core#5231]
Reproduce: Load any github based project (Like Roassal3) into a 64bit phoro image running on windows 10 x64. Example:

```
Metacello new
    baseline: 'Roassal3';
    repository: 'github://ObjectProfile/Roassal3/src';
    load.
```

Expected Behaviour: Project Loads
Actual Behaviour: Image closes without error, writing debug log, or anything to stderr.

Further Information
Pharo 7.0.4
Build information: Pharo-7.0.4+build.168.sha.ccd1f6489120f58ddeacb2cac77cd3a0f0dcfbe6 (64 Bit)

Windows 10 Pro (x64) Version 1903 Build 18362.388

**Comment by myroslavarm** [comment]
was able to reproduce the issue and reported it in the Roassal3 github repo

**Comment by MarcusDenker** [comment]
This seems to be fixed: https://github.com/ObjectProfile/Roassal3/issues/144
