### ISSUE TITLE
Remove GTEventRecorder. 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5232]
The full project has been migrated to 
https://github.com/pharo-contributions/EventRecorder

**Comment by jecisc** [comment]
Removing this project without deprecation broke some projects around Pharo such as Roassal 2. This broke the builds of Moose.

**Comment by Ducasse** [comment]
Then it means that Roassal 2 is not working on Pharo 80 alpha. So roassal2 should be ported to Pharo 80 alpha. 
I do not really understand what is your point.But you can continue bashing me.
If you want feel free.

**Comment by astares** [comment]
@Ducasse Please stop this - he is not bashing. He just wrotes what is the situation now!
