### ISSUE TITLE
RBSimpleFormatter should not lose method comment!!!

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5241]
This is super bad.

**Comment by MarcusDenker** [comment]
This might be related to #5587

**Comment by MarcusDenker** [comment]
(if there is no original source, there is no way to print the comment)

**Comment by Ducasse** [comment]
Now I could not reproduce it. I asked cyril for a case but he never told me.

**Comment by MarcusDenker** [comment]
I cose it
