### ISSUE TITLE
 AST-Core-Tests package disappeared

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#5246]
We lost all tests for the AST.

**Comment by jecisc** [comment]
The package was declared in BlueInk baseline. When BlueInk was removed, the tests were also removed.

**Comment by pavel-krivanek** [comment]
It was like that because it was a dependency of it. I will try to prepare a PR. Some SystemDependenciesTests will need to be changed back.

**Comment by Ducasse** [comment]
Yes I never saw that dependency else I would have cleaned it. 
I will try to allocate time to look at the dependencies in our system :(
