### ISSUE TITLE
testUndeclared is failing in the released image

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#5247]
Found undeclared references: #(#ASTEvaluationTest #BIConfigurableFormatter)

ASTEvaluationTest was part of the test package for the AST. The completion package
disappeared!!

**Comment by Ducasse** [comment]
Apparently Pavel removed it by accident when fixing the dependency tests. 
So #5254 should address this bug. I close it. Reopen it if this is not the case.

**Comment by pavel-krivanek** [comment]
The test package for AST was part of the BlueInk baseline because this project needed that as a dependency. So it stopped to be loaded because of removing BlueInk.

**Comment by pavel-krivanek** [comment]
this issue is still open

**Comment by Ducasse** [comment]
Ah ok. 
I hate such bad dependency. 
I will have a look this evening. Because I have 6 hours lectures + meetings with Thales and more today.

**Comment by MarcusDenker** [comment]
It is now ok in the image I downloaded
