### ISSUE TITLE
BlockClosureTest>>testSourceNodeOptimized is failing

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#5248]
fails with:

Got 'RBBlockNode([:ctx | [ ctx atEnd ] whileTrue: [ 1 + 2 ] ])' instead of 'RBBlockNode([ :ctx | [ ctx atEnd ] whileTrue: [ 1 + 2 ] ])'.

**Comment by jecisc** [comment]
This is because the new formatter is not used in the image. So the format is wrong

**Comment by MarcusDenker** [comment]
fixed
