### ISSUE TITLE
Spotter is broken 

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#5249]
Open Spotter in recent image gives a DNU since the brick iVar is nil

![image](https://user-images.githubusercontent.com/5980033/69704113-23af2680-10f3-11ea-84b6-867ba3f934e6.png)

**Comment by MarcusDenker** [comment]
fixed by merging https://github.com/pharo-project/pharo/pull/5251

**Comment by astares** [comment]
@MarcusDenker and @VincentBlondeau: Thanks!
