### ISSUE TITLE
someClass basicNew printString fails for around 10.000 classes

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#5250]
Is that a problem?

```Smalltalk
Object allSubclasses select: [ :c |  
    [(c basicNew) printString. false ] 
        on: Exception 
        do: [ true ] ].
```
The problem has an easy fix, changing the `#printStringLimitedTo:using:` method in 'Object' to have an exception handling part , perhaps returning 'an uninitialized nameOfClass` (or something better please).

Perhaps also some of the other implementations of `printString` need to be fixed, but not sure.

**Comment by kasperosterbye** [comment]
I encountered the problem when debugging initialization code

**Comment by VincentBlondeau** [comment]
That's a good idea! You could even set up a test that check there is no error risen.

**Comment by kasperosterbye** [comment]
I close it as the PR I did was not approved because the behaviour seems to be the wanted one.
