### ISSUE TITLE
[CI]Why the tests are not run on Pharo x64?

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#5260]
Is there any reason the tests are not run on the x64 version of Pharo?
Since both the x64 and x32 are released why they should be skipped?

**Comment by MarcusDenker** [comment]
because nobody did it.

**Comment by MarcusDenker** [comment]
it's really that simple: everything obvious that should be done is not done because nobody did it

**Comment by VincentBlondeau** [comment]
I was expecting a more complex answer... I'll do a PR then!

**Comment by MarcusDenker** [comment]
was done
