### ISSUE TITLE
[featureRequest]custom filter when browsing senders/implementor

### ISSUE THREAD

**Issue by hogoww** [guillep/pharo-core#5263]
Currently we're stuck with the offered hierarchy for this, and quite often I would like to scope in another way.
Am I missing something?
Is it something planned for newTools?

(Ideally, i'd like to be able to write my own predicate, even if the API is very very simple)

**Comment by dionisiydk** [comment]
Can you tell more?
I do not understand your request. Example would be nice

пт, 29 нояб. 2019 г., 8:13 hogoww <notifications@github.com>:

**Comment by hogoww** [comment]
Hi,
Of course ! 
![Screenshot 2019-11-29 at 10 04 47](https://user-images.githubusercontent.com/21278554/69857223-bedd0300-128f-11ea-9ce4-94d67d61d558.png)

In that random example, I searched for implementor of printString inside a playground.
I can therefore search scope it by:
- CurrentImage
- Hier:something
- Package:SomethingElse
and scope those by name

What I'd like to have is to have something like 2.
The first being a scroll menu containing the potential filters (from what we already have: None/packages/hierarchy)
in the second one a complementing filter we can write.

So for example, if we have filter = package name = DrTest* we'd see everything implementors in drTest. (to have that behavior currently, i think i have to be in a drTestPackage, and I cannot have severals)

Is that clearer? =]

**Comment by dionisiydk** [comment]
Yes. This is good idea.
I also thought to implement real tool to define query scope (instead of
trivial combobox). But no time for this

пт, 29 нояб. 2019 г., 9:11 hogoww <notifications@github.com>:

**Comment by hogoww** [comment]
This is still relevant, but it makes no sense to keep it as an issue.
I have a prototype of a custom query implementations that I'll share when I have the mental space to do so
