### ISSUE TITLE
Calypso does not announce a WindowOpened event when opened

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#5266]
If you execute: 

```Smalltalk
 World announcer when: WindowOpened do: [ :a | a printString logCr ].
``` 

You'll not see any log when Calypso is opened.

**Comment by jecisc** [comment]
Ok so the problem is that Calypso does not use SystemWindow so it does not have all the hooks from it.

**Comment by dionisiydk** [comment]
It does not sound true. Look at method ClyBrowserMorph>>open


пт, 29 нояб. 2019 г., 11:04 CyrilFerlicot <notifications@github.com>:

**Comment by jecisc** [comment]
Ok, I'll take a look. I though it did not use ite because when I browse the halo I do not get a level with a SystemWindow when I have it for most other tools and the class does not inherits from it.

**Comment by jecisc** [comment]
Too low priority, I'll close
