### ISSUE TITLE
could we introduce isDoubleQuote in Character

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5279]
because this is useful to have.

**Comment by Ducasse** [comment]
And some tests too :)

**Comment by ackerleytng** [comment]
Should `isDoubleQuote` return true only for `"`, or should it also return true for all of these? https://www.compart.com/en/unicode/search?q=quotation#characters

<blockquote><img src="/en/unicode/images/icon/icon-compart.svg" width="48" align="right"><div>https://www.compart.com/en/unicode/search</div><div><strong><a href="https://www.compart.com/en/unicode/search">Unicode</a></strong></div><div>All Unicode Symbols with Names and Descriptions on One Page</div></blockquote>
