### ISSUE TITLE
stepping on halt is breaking debugging experience

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5280]
In P7 stepping on halt was just going over it and now it blocks completely and open another debugger and break everything. 
This is a serious regression in terms of debugging experience.

**Comment by StevenCostiou** [comment]
Well, on latest Pharo7 it does not work either (64bits).
Both on Pharo7 and Pharo8 it opens a debugger on the "Halt" interruption.
This even amazing: before submitting this comment I wanted to check the behavior on Pharo6 and it does not work! 
I do not remember that bug, were we even able to step over a halt??

**Comment by StevenCostiou** [comment]
Everything's fine on Pharo 5. Interesting.

**Comment by Ducasse** [comment]
This is strange because I always do a step over and it worked. Now it does not
Did you try with a step over?

**Comment by Ducasse** [comment]
This is strange because in Pharo 8.0.0
Build information: Pharo-8.0.0+build.1026.sha.8863f3bae4f82b45938385c0f45cf2df7ea6de12 (64 Bit)

I can setp over halt without problem.
I'm totally confused.
