### ISSUE TITLE
MessageNotUnderstood: Text>>findLastOccurrenceOfString:startingAt: 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5282]
How to reproduce

- Open Transcript
- In a method type
--  ()
-- then remove the last )
-- adding space or removing space produces 

MessageNotUnderstood: Text>>findLastOccurrenceOfString:startingAt:
MessageNotUnderstood: Text>>findLastOccurrenceOfString:startingAt:

**Comment by Ducasse** [comment]
Steven I would like to pair program with you with your debugger to see how we can fix this. 
I have the impression that a Text is passed instead of a String.

**Comment by kasperosterbye** [comment]
Should be simple, but I am not going to ruin your learning experience :-)

**Comment by MarcusDenker** [comment]
this has to do with RBParser>>#parseErrorNode:, it is called on a Text object but the method is only in string... it seems that it can be fixed by making sure to hand a string to the parser for syntax highlight:

privateStyle: aText
	| ast |
	ast := classOrMetaClass compiler
		source: aText asString;
		noPattern: self isForWorkspace ;
		options:  #(+ optionParseErrors + optionSkipSemanticWarnings);
		requestor: workspace;
		parse.				
	ast doSemanticAnalysis.
	^ self style: aText ast: ast
