### ISSUE TITLE
SourceFileBufferedReadWriteStream does not handle well #refreshBufferFrom:

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#5291]
When writing in a deferFlushDuring mode (to compile methods), when the buffer is full #refreshBufferFrom: will write the contents of it even if the chunk is not complete. After a #refreshBufferFrom: the source file can be in an instable state and then cannot be read by epicea.

I suggest to flush only complete strings (the argument of the nextPutAll: for instance) and not flushing in the middle of it.

**Comment by VincentBlondeau** [comment]
But it will not work if the string to write is larger than the buffer... I then suggest to disable the gathering of the timestamp from Epicea in the change log when in deferFlushDuring: block.

**Comment by VincentBlondeau** [comment]
Weak linked with #5292

**Comment by tesonep** [comment]
@VincentBlondeau can you check if the fix I have proposed for #5292 keeps the same problem? It should be fixed by the same code.

**Comment by MarcusDenker** [comment]
merged
