### ISSUE TITLE
Rules display wrong or not all codelines

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#5309]
- Create a class Foo
- provide a #foo method with a message send to a **non-existing** #bar method
- by default the line with the bar message send is marked in red (which is intended and OK for a simple method)

But 
 - it does not work if the message name appears in the comment, because then the 
   name in the comment is marked
 - it does not work if the message send appears several times in the same method, because then only the first one is marked

![image](https://user-images.githubusercontent.com/5980033/70193599-f587a300-16ff-11ea-9c41-59527a25c6b7.png)

**Comment by kasperosterbye** [comment]
I am able to reproduce this. It has it origins in the feedback which is build on stringSearch. It plainly highlights the first `bar` it finds.

The error is spotted in `RBSelfSentNotImplementedRule>>check:forCritiquesDo:`.
However, that method communicates to the browser using `ReSearchStringSourceAnchor`, which - well - searches the source for the first occurrence.

At present it is not quite clear to me what should be done, but I will try look into it.
