### ISSUE TITLE
Package Renaming does not rename Manifest class 

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#5310]
A manifest class name is (when created) formed from the name of the package,

- assume you have a package with a manifest
- now rename the package - only the package is renamed

The package's manifest class is not renamed according to the rules which can have side effects
(like banned rules are not applied anymore or other)

**Comment by MarcusDenker** [comment]
I am sure there is a duplicate for this entry

**Comment by MarcusDenker** [comment]
This: https://github.com/pharo-project/pharo/issues/3604
