### ISSUE TITLE
DrTest preview overwrites TestRunner menu

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#5311]
DrTest was integrated into P8 as a preview.

We now have two menu items "Test Runner" and "DrTest (preview)"
 - both open DrTest while the user might expect to get and should get the existing SUnit test runner
 - both menu items have the key combination CTRL+O+U

![image](https://user-images.githubusercontent.com/5980033/70194074-8f9c1b00-1701-11ea-8b24-dd6a9727a001.png)

**Comment by MarcusDenker** [comment]
there is this issue:  https://github.com/pharo-project/pharo/issues/5216

**Comment by juliendelplanque** [comment]
Hum, I saw this, I will investigate.
