### ISSUE TITLE
system non-responsive after "storeString" message passed to object

### ISSUE THREAD

**Issue by cencool** [guillep/pharo-core#5316]
after executing following in Playground:
a := [ 5 + 7]  ---> DoIt
i := a storeString ---> DoIt

system is non-responsive, gradually consuming memory and CPU 100%. Had to kill it.

OS: OpenSuse Leap 15.1 64bit
Pharo 7.0 64bit. Reproduced also on 6.0 64bit.

**Comment by bencoman** [comment]
If you DebugIt rather than DoIt, are you able to narrow it down any further?

>

**Comment by MarcusDenker** [comment]
It seems #storeOn: called on BlockClosure does not work... I guess as it tries to store the context that the closure points to.

**Comment by cencool** [comment]
Based on Marcus suggestion it looks like Duplicate of #3319. 
Happens  with BlockClosure.
