### ISSUE TITLE
Cleaning DrTests

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#5329]
I have a bunch of issues on [DrTests repository](https://github.com/juliendelplanque/DrTests) related to cleaning.

I will fix them in the PR related to this issue.

See:

- https://github.com/juliendelplanque/DrTests/issues/102
- https://github.com/juliendelplanque/DrTests/issues/104
- https://github.com/juliendelplanque/DrTests/issues/105
- https://github.com/juliendelplanque/DrTests/issues/106
- https://github.com/juliendelplanque/DrTests/issues/107
- https://github.com/juliendelplanque/DrTests/issues/108
- https://github.com/juliendelplanque/DrTests/issues/109
- https://github.com/juliendelplanque/DrTests/issues/110
- https://github.com/juliendelplanque/DrTests/issues/111

**Comment by MarcusDenker** [comment]
merged https://github.com/pharo-project/pharo/pull/5331
