### ISSUE TITLE
enlumineur default should put a space after ^

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5332]
allTokens
  "Return all the tokens"
  | tokens |
  tokens := OrderedCollection new.
  [ self isNotAtEnd ] whileTrue: [ tokens add: self nextToken ].
  ^ tokens

and not

allTokens
  "Return all the tokens"
  | tokens |
  tokens := OrderedCollection new.
  [ self isNotAtEnd ] whileTrue: [ tokens add: self nextToken ].
  ^tokens

**Comment by santids** [comment]
May I ask where is this method implemented? I couldn't find it in Pharo 8.0 branch. I offer myself to fix it.

Also, there isn't a tool like a linter to detect when something breaks white space convention?

**Comment by Ducasse** [comment]
In fact for enlumineur I think that this is a just a setting to put on.
Our idea was to be able to configure enlumineur to be able to reformat all pharo and to have this check.

**Comment by Ducasse** [comment]
Spaces following caret symbol in return
Number of spaces expressed that is put just after the caret (^) of a return expression. 
For example: ^   self is the result for 3 spaces

And on my image it is on by default.

**Comment by MarcusDenker** [comment]
this is fixed. pretty print adds the space now
