### ISSUE TITLE
Enlumineur???

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#5335]
The main comment says "I'm a new pretty printer for Pharo." - as Pharo is getting older, and modules come and go, this comment says nothing. Please instead write something like:
"I'm a pretty printer for Pharo developed in 2010"

**Comment by Ducasse** [comment]
Here is a comment. 
Now I do not participate anymore so I made an exception.

Enlumineur is a replacement of BlueInk pretty printer.
It was developed by Hugo Lasnier during 6 months internship within RMOD and supervised by S. Ducasse and G. Polito during 2019.. 

Enlumineur enhancements are:
- systematic test coverage with more than 270 tests
- full revisiting of settings with description and example
- no way to break the code by entering a non space character to indent code
- support for {.....} long list
- cleaning coupled settings
- support for to:do: block like statement (multiline arguments)
- removal of "traditional parentheses" what ever it meant.
- new line and more indentation after the opening bracket
A dedicated UI was in preparation but should be validated before introduced in Pharo. 
See package Enlumineur-UI

Now Enlumineur should be improved to be able to reformat the full code of Pharo. 
The tests are a first step to make sure that we understand what is impacted by a change.

**Comment by kasperosterbye** [comment]
Thanks - It is most helpful.
