### ISSUE TITLE
Inconsistency in compilation

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#5348]
If I have a class with an instance variable `aaa`, I cannot make a method with an argument named `aaa` in the Calypso browser.

However, I am able to install the method using `compile:classified:

**Comment by MarcusDenker** [comment]
yes, this is because there are two modes: interactive and non-interactive. In non=interactive mode we try to load the code even if it is wrong. This is important, as else e.g. it would make loading broken (or old) code very complex.

**Comment by MarcusDenker** [comment]
they are not shown on the transcript... no idea why:


showWarningOnTranscript
	true
		ifTrue: [ ^ self ].	"turned off by default"
	SystemNotification signal: self warningMessage

**Comment by MarcusDenker** [comment]
I think we should turn that on.

**Comment by kasperosterbye** [comment]
I will close this issue as it seems like it was the intended behaviour
