### ISSUE TITLE
Fraction arithmetic does not work as expected

### ISSUE THREAD

**Issue by alexzandros** [guillep/pharo-core#5355]
Pharo version: Pharo 7.0.4
Build information: Pharo-7.0.4+build.168.sha.ccd1f6489120f58ddeacb2cac77cd3a0f0dcfbe6 (64 Bit)
OS: Windows 10
When adding Fractions the result is wrong.
Why I did: (1/5 + 8/12)
Expected result 13/15
What I got 41/60
When I swap the terms the result should be the same, so I did:
Why I did: (8/12 + 1/5)
Expected result 13/15
What I got 1/3

![PharoScreenshot](https://user-images.githubusercontent.com/10458935/70585080-0ec1a100-1b91-11ea-8181-b9c365271095.png)

**Comment by akgrant43** [comment]
Hi @alexzandros 

Arithmetic operations are just standard message sends, so it's simple left to right, there's no priority.

What you've evaluated is:

```
(((8 / 12) + 1) / 5)
```

The consistency of the message send is considered more important than the mathematical interpretation, so this is by design.


HTH,
Alistair
