### ISSUE TITLE
Enlumineur is too slow.

### ISSUE THREAD

**Issue by andreina-covi** [guillep/pharo-core#5362]
Hi, when I want to parse a string of a complex method the image in Pharo stays in infinite loop.

Example: 
```|str|
str := 'searchMin: dmin max: dmax desired: desiredNumberOfTicks
	| best sm dm cm delta bestScore k |
	best := RTGrapherLabel new.
	bestScore := -2.
	desiredNumberOfTicks <= 0 ifTrue: [ self error: ''The minimun value of desiredNumberOfTicks is 1'' ].
	
	"In case of a particular situation"
	(dmin = 0 and: [ dmax = 0 ]) ifTrue: [ 
		best
			min: 0;
			max: 1;
			step: 1;
			score: bestScore.
		^ best ].
	
	[ :break |
		[ true ] whileTrue: [ 
			n := nice next.
			sm := self simplicityMax.
			((self w: sm c: 1 d: 1 l: 1) < bestScore)
				ifTrue: [ break value ].
			k := 2.
			[ :break2 |
				[ true ] whileTrue: [ | z |
					dm := [ self densityMax: k m: desiredNumberOfTicks ] on: ZeroDivide do: [ :ex | self error: ''Please increase the value of desiredNumberOfTicks/labels'' ].
					((self w: sm c: 1 d: dm l: 1) < bestScore) 
						ifTrue: [ break2 value ].
					delta := (dmax - dmin)/(k+1)/ n j/ (nice qat: n i).
					z := (nice logB: delta) ceiling.
					[ :break3|
						[ true ] whileTrue: [ 
							[ :continue | | minStart maxStart step |
								step := n j * (nice qat: n i) * (nice base raisedTo: z).
								cm := self coverageMin: dmin max: dmax span: step * (k-1).
								((self w: sm c: cm d: dm l: 1) < bestScore) 
									ifTrue: [ break3 value ].
								minStart := ((dmax / step) floor - (k-1)) * n j.
								maxStart := (dmin / step) ceiling * n j.
								(minStart > maxStart) ifTrue: [ 
									z := z +1.
									continue value. ].
						
								(minStart to: maxStart) do: [ :start |
									| lmin lmax lstep c s d l score |
									lmin := start * step / n j. 
									lmax := lmin + (step * (k -1)).
									lstep := step.
									c := self coverageMin: dmin max: dmax lmin: lmin lmax: lmax.
									s := self simplicity: lmin max: lmax step: lstep.
									d := self density: k m: desiredNumberOfTicks dmin: dmin dmax: dmax lmin: lmin lmax: lmax.
									l := self legibility: lmin max: lmax step: lstep.
									score := self w: s c: c d: d l: l.
							
									((score > bestScore) and: 
									[ loose not or: [ (lmin <= dmin) and: 
														  [ lmax >= dmax ] ] ]) ifTrue: [
										best
											min: lmin;
											max: lmax;
											step: lstep;
											score: score.
											bestScore := score.
									 ].
								].
								z := z +1.
							] valueWithExit.
						].
					] valueWithExit. 
					k := k +1.
				].
			] valueWithExit.
		 ]
	] valueWithExit.
	
	nice reset.
	
	^ best.'.
RBParser parseMethod: str.```

**Comment by MarcusDenker** [comment]
It seems to be related to printing the AST, just parsing is OK (if you evaluate it, it works, but if you print or inspect it there is a problem)

**Comment by andreina-covi** [comment]
Oh yes, I was reviewing and I think that there's a bug in EFFormatter class, because I changed with another formatter and I didn't have problem.
I'll review to fix the bug

**Comment by Ducasse** [comment]
Please let us know because the new formatter is the way to go but we know that it is far from perfect.

**Comment by Ducasse** [comment]
Hi I loaded the code and change the formatter to EFFormatter and I indeed got a system that freezes and I do not know why. I will check when I have time to see why.

**Comment by Ducasse** [comment]
Problem may be around here:

bracketWith: bracketString around: aBlock indentExtraSpaces: anInteger
	bracketString isEmpty
		ifTrue: [ ^ aBlock value ].
	codeStream nextPut: bracketString first.
	^ [self indentExtraSpaces: anInteger  around:  aBlock]
		ensure: [ codeStream nextPut: bracketString last ]

**Comment by Ducasse** [comment]
Now if Enlumineur is not ready we will remove it and push back blueInk to Pharo80. 
Now I cannot debug because the debugger is using the formatter and this is a super bad idea.

**Comment by Ducasse** [comment]
Pay attention the debugger is using the formatter so we will have to do something because I cannot debug simply right now. Probably create the debug and switch formatter.

**Comment by Ducasse** [comment]
We looked at it and this is just that the code of the pretty printer is too slow. 
We are investigating it. 

The culprit looks to be in willBeMultiLine:saveIn:

**Comment by j-brant** [comment]
I haven't looked at the code, but I'm guessing that you have the same problem that Don had with the original RB formatter. If your multi-line test "formats" the block, and then later you format the block after computing the multi-line, you are formatting a block twice. Nesting the blocks gives you exponential times. In the example above, there are ~11 nested blocks, so likely you are formatting some blocks over a 1000 times.

**Comment by Ducasse** [comment]
Hi john,
Yes hugo did exactly that. We were not aware of it :(. I should have review better the code. 
It reminded me mistakes I did when I learned CS and where on a tree a simple naive variation got exponential. 
We spotted some other problems like a non working cache. I will reload blueink because Enlumineur is not ready for production and I do a code review of the code and see. 
But yes. we found the same that you mentioned. 
Now I do not have much time. We should recheck our investigation because even shortcutting the double formatting we got a problem so we have to revisit our hypotheses. 
S.

**Comment by j-brant** [comment]
I tested the RB formatter by formatting every method in the image and then parsing the formatted code. The formatted AST should equal the original AST. Furthermore, if you format the formatted AST, the string should equal the original formatted string. If this test passes in a reasonable amount of time, I doubt that many additional bugs will be found, and instead people will just complain on what the formatted code looks like. :)

**Comment by Ducasse** [comment]
Yes. I have to fix it to not lose comments. I think that your test did not take into account comments.

**Comment by Ducasse** [comment]
I investigated further and the code is creating and caching a separate formatter for any arg. 
I will check if I get some time to work on it. 
The idea of the new formatter was: have more tests, clean the settings and introduce more hooks. So we will arrive there but I will probably remove it from P8 if I do not have the time to have a good speed.

**Comment by Ducasse** [comment]
This is strange because both BIConfigurableFormatter and RBSimple also 

```
formattedSourceFor: aNode
	^ lookaheadCode
		at: aNode
		ifAbsentPut: [ 
			self class new
				indent: self indent;
				installNewContext: context;
				format: aNode ]
```

**Comment by Ducasse** [comment]
I checked and formatted this method with the latest version of Enlumineur and it worked well.
