### ISSUE TITLE
Completion failure when using super in a trait

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#5372]
When in method, that belongs to a trait, you start to use message call in form `super message` then during the writing of the `message` selector, the completion fails with error `#allSelectors was sent to nil`

![Pharo_sNUQO0WguH](https://user-images.githubusercontent.com/572494/70781256-2b72fa00-1d86-11ea-869a-8f7515afb680.png)

**Comment by MarcusDenker** [comment]
Has been merged in Pharo8, I checked and the fix is in Pharo9, too
