### ISSUE TITLE
Archive of "workflow-engine_lists" should be open like for other Pharo mailinglists

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#5391]
From the four mailinglist on https://lists.pharo.org only three are open from the archive to be readable using the web:

 1. https://lists.pharo.org/pipermail/pharo-dev_lists.pharo.org/
 2. https://lists.pharo.org/pipermail/pharo-users_lists.pharo.org/
 3. https://lists.pharo.org/pipermail/pharo-iot_lists.pharo.org/

The archive of "workflow-engine_lists" requires a registration and login:

 4. https://lists.pharo.org/mailman/private/workflow-engine_lists.pharo.org/

@MarcusDenker Would it make sense to open the archive for "workflow-engine_lists" ML too?

**Comment by MarcusDenker** [comment]
yes, it is just the default and I always forget to set it correctly...

**Comment by MarcusDenker** [comment]
Fixed

**Comment by astares** [comment]
Thanks!
