### ISSUE TITLE
Unused temps 

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#5398]
Error
the following methods have unused temporary variables and should be cleaned: an OrderedCollection(Class>>#duplicateClassWithNewName:)
Stacktrace
NoUnusedTemporaryVariablesLeftTest(TestAsserter)>>assert:description:resumable:
NoUnusedTemporaryVariablesLeftTest(TestAsserter)>>assert:description:

**Comment by CafeKrem** [comment]
I'm working on it

**Comment by MarcusDenker** [comment]
should be very simple: just remove the "newComment" temp

**Comment by CafeKrem** [comment]
Sorry I had some problem with public transport  at Paris.
