### ISSUE TITLE
About Processor yield => Object >> yield

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5408]
Could we introduce yield in Object to avoid to have to write 
Processor yield?

This looks so dated to have a global variable and refer to it everywhere looks like a bad idea 
and promotes bad design (Smalltalk tools, Smalltalk ui theme....).

**Comment by bencoman** [comment]
#yield on Processor is specific enough, but #yield on Object may be too generic and potentially clash with application domain logic.  To make it more specific should it be Object>>yieldProcessor ?

**Comment by Ducasse** [comment]
Closed sadly. Because the API of processor is much larger and I'm not happy with just a single move.
