### ISSUE TITLE
Alien class sends unimplemented messages in #libcName

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#5418]
![image](https://user-images.githubusercontent.com/5980033/71414524-a6c28e80-2657-11ea-8a06-efab3ca16bd2.png)

**Comment by astares** [comment]
- could be fixed by replacing it with "os version" - but we will be incompatible to regular Alien ...

**Comment by tesonep** [comment]
The examples are not working in 64 bits. Everything should be rewrotten. Also, we have to think if having the examples there are not just confusing as UFFI should be used.

**Comment by astares** [comment]
Yes

**Comment by Ducasse** [comment]
We should probably put a big comment to state it too.

**Comment by MarcusDenker** [comment]
This has been fixed, it now uses "os version"
