### ISSUE TITLE
P7 BACKPORT - fix debugger to step over #halt

### ISSUE THREAD

**Issue by bencoman** [guillep/pharo-core#5425]
In Pharo 7, evaluate the following...
```
Smalltalk tools debugger alwaysOpenFullDebugger: true.
Author fullName: 'ErrorDemo'.

class := Object subclass: #My
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'AAA-My'.

class compile: '
errorDemo
	self inform: 1 printString.
   self halt.
	self inform: 2 printString.
'.

class new errorDemo
```
then click \<Restart\>\<Over\>\<Over\>\<Over\> and observe it does not cleanly step over the #halt. 

The above script worked fine in original Pharo 6.1 Release (60540), and also 60541, but 60542 was broken by "Backport of the fix of Infinite Debugger" (https://pharo.fogbugz.com/f/cases/22298).  Its recently been fixed in Pharo 8 by https://github.com/pharo-project/pharo/pull/5289.

Applying that same #5289 fix onto current Pharo 7 Release fixes the problem there.

**Comment by MarcusDenker** [comment]
Pharo 7 fixes will not be done anymore...
