### ISSUE TITLE
confirm:trueChoice:falseChoice:cancelChoice:default: is not working correctly

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5426]
UIManager default 
	confirm: 'Credential file exist at: ' 
	trueChoice: 'Leave it like that' 
	falseChoice: 'Erase it' 
	cancelChoice: 'Cancel' 
	default: #cancel

bring a DNU
But the comments

	"Put up a yes/no/cancel menu with caption queryString. The actual wording for the choices will be as provided in the trueChoice, falseChoice and cancelChoice parameters.
	Default should be one of #yes, #no or #cancel to set the default button.
	Answer true if the response is the true-choice, false if it's the false-choice, nil if the cancelChoice.
	This is a modal question -- the user must respond."

While the implementation of default makes me feel that that default can be nil, true, false.

S.

**Comment by jecisc** [comment]
I propose to close this one since we are removing the usage of the UIManager in favor of Spec equivalents.

We can reopen if it's really important
