### ISSUE TITLE
Can debugger be scripted to provide a test for "step over #halt message"

### ISSUE THREAD

**Issue by bencoman** [guillep/pharo-core#5432]
@dupriezt  Can the debugger be scripted to add a Kernel unit test to ensure the regression related to https://github.com/pharo-project/pharo/pull/5289 and https://github.com/pharo-project/pharo/issues/5425 doesn't reoccur?

**Comment by StevenCostiou** [comment]
This is not going to be addressed anytime soon, and Sindarin is not in a state where that could be possible.
In addition, Sindarin is not in the kernel, so I am not sure it is possible to provide a kernel test.
I propose to close the issue.
