### ISSUE TITLE
Add Package queries

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5437]
We should add two query methods to `RPackageOrganizer`:

```smalltalk
organiser selectPackages: [ :each | ... ]
```

```smalltalk
organiser selectPackageWithName: [ :name | ...  ]
```

On top of those, users could easily build more complex queries (beginsWith, endsWith, substrings, regex-based...)

**Comment by Ducasse** [comment]
May be proposing a matching: method 

```
RPackageOrganizer >> matching: aPatternString
       "Return the list of packages whose names match the argument."

	^ self default packages select: [ :p | aPatternString match: p name  ]
```

**Comment by guillep** [comment]
I've made a review on the PR #5786. Now that I read the original issue, I'm understanding that you were proposing a single `matching:` method? Because with `matching:` we could cover the other cases.

**Comment by guillep** [comment]
I allowed myself to change the original description based on the discussion

**Comment by jecisc** [comment]
We can do `organizer packages select:` currently. Do we want more?

**Comment by jecisc** [comment]
I think it is now easy enough to query the packages with the new implementation. I propose to close this issue
