### ISSUE TITLE
Finder glitches

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5438]
![Screenshot 2020-01-05 at 18 05 13](https://user-images.githubusercontent.com/432549/71783360-f99c2e80-2fe5-11ea-9057-2e94e15910e0.png)

This is strange since the rendered result replace the argument by a space.

**Comment by bencoman** [comment]
Co-incidentally, a week ago I bumped into similar for the first time in Pharo 7.

**Comment by LaurineDargaud** [comment]
Working on it.

**Comment by Ducasse** [comment]
computeWithMethodFinder: aString
	"Compute the selectors for the single example of receiver and args, in the very top pane"

	| data result resultArray dataObjects |
	(aString includes: $.)
		ifFalse: [ ^ #() ].	"delete trailing period. This should be fixed in the Parser!"
	data := aString trimRight: [ :char | char isSeparator or: [ char = $. ] ].

	[ dataObjects := Smalltalk compiler evaluate: '{' , data , '}' ]
		on: SyntaxErrorNotification
		do: [ :e | 
			self inform: 'Syntax Error: ' , e errorMessage.
			^ #() ].	"#( data1 data2 result )"
	
	dataObjects size < 2
		ifTrue: [ 
			self
				inform:
					'If you are giving an example of receiver, \args, and result, please put periods between the parts.\Otherwise just type one selector fragment'
						withCRs.
			^ #() ].
	self halt.
	result := MethodFinder new findMethodsByExampleInput: dataObjects allButLast andExpectedResult: dataObjects last.

The problem is in the expression above. 




	result isEmpty ifTrue: [ self inform: 'no single method'. ^ #()].
	
	resultArray := result collect: [ :send | send asString , ' --> ', dataObjects last asString. ].
	^ resultArray.

**Comment by Ducasse** [comment]
The expression showing the problem 

MethodFinder new possibleSolutionsForInput: #(#(a b) a) andExpectedResult: 1

**Comment by Ducasse** [comment]
The problem is multiple

- a symbol is modified (so the copy and deepCopy used by the Finder is not efficient to protect it from modification).
- we suspect that the readOnlyObject primitive does not raise an error.
- we suspect that the problem is print:

**Comment by Ducasse** [comment]
Steven this bug is really.

**Comment by Ducasse** [comment]
We discovered that `primitiveStringAtPut` modifies the receiver on primitive failure.

```
#aaa string:  {'abc'. Object new.  true}
```
or 
```
#aaa privateAt: 1 put: Object new 
```
And this is different than 
inspecting #aaa and executing line by line or not showing that 
```
#aaa beReadonlyObject.
#aaa string: '123'
```


A simple immediate solution is to cancel string: from the finder white list.

Then the primitive stringAtPut

**Comment by Ducasse** [comment]
Symbol >> forbiddenSelectorsForMethodFinder
   ^ #(string:)
