### ISSUE TITLE
Reading out of range Float exponents is inconsistent

### ISSUE THREAD

**Issue by svenvc** [guillep/pharo-core#5443]
It was noted that the following two have different results:

    Float readFrom: '7.5e333'. => Float infinity
    Float readFrom: '7.5e3333'. => Error

Turns out NumberParser>>#readExponent has a bogus and unnecessary test at the end.

More specifically: Float emin and emax define the allowed exponent interval in binary, not decimal. Even so, trying to use a too large exponent gets automatically resolved to infinity when the float instance is created. Hence the test can be removed.

**Comment by nicolas-cellier-aka-nice** [comment]
It might be related to this little game:
https://codegolf.stackexchange.com/questions/7197/crash-your-favorite-compiler/11429#11429

<blockquote><img src="https://cdn.sstatic.net/Sites/codegolf/img/apple-touch-icon@2.png?v=ed60a1645c65" width="48" align="right"><div>Code Golf Stack Exchange</div><div><strong><a href="https://codegolf.stackexchange.com/questions/7197/crash-your-favorite-compiler/11429">Crash your favorite compiler</a></strong></div><div>Write a perfectly legal code in a decent language of your choice whose compiling will either crash the compiler or send it into an infinite loop (infinite compile time).

Restrictions:
Use a stand...</div></blockquote>

**Comment by svenvc** [comment]
Yes, we probably need lots of resource safeguards while parsing, this is not so easy to do well, especially in a language that allows very large structures easily.

> On 6 Jan 2020, at 15:53, Nicolas Cellier <notifications@github.com> wrote:
> 
> It might be related to this little game:
> https://codegolf.stackexchange.com/questions/7197/crash-your-favorite-compiler/11429#11429
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
Sven Van Caekenberghe - mailto:sven@beta9.be
Beta Nine - software engineering - http://www.beta9.be
