### ISSUE TITLE
does addSelfReturn needs to return a VariableNode

### ISSUE THREAD

**Issue by hogoww** [guillep/pharo-core#5459]
@MarcusDenker 
Currently we have: 
```
addSelfReturn
	| node |
	self lastIsReturn
		ifTrue: [ ^ self statements last ].
	node := RBReturnNode value: (RBVariableNode named: 'self').
	^ self addNode: node
```
Could we replace the VariableNode by a SelfNode directly, or may it mess up with the Semantic Analysis?

**Comment by MarcusDenker** [comment]
Should be save to change that, yes. Should not have an impact on Semantic Analysis (it would be done again there but that is no problem)
