### ISSUE TITLE
Bug Slot template: add variable without #hash: Crash on accept

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#5464]
when accepting 

Object subclass: #NameOfSubclass
	slots: {hello}
	classVariables: {}
	package: 'Athens-Cairo-Tests'

the system asks if it is ok to add the unknown variable hello. But that is the wrong question to ask
(and  then is done in class UndefinedObject -> not good).

Solution: The new class definition parser can check this for real.

Intermediate solution:

in compileANewClassFrom:notifying:startingFrom: wrap the compilation in a execution handler like that:

evaluate] on: OCUndeclaredVariableWarning do: [ self inform: 'Undeclared Variable in Class Definition' . ^nil ].

**Comment by astares** [comment]
@MarcusDenker Rember that that there are also people following a different approach (like me) without the default class definition parser.
