### ISSUE TITLE
Inspector on a ByteSymbol should get the senders of this symbol on a lazy way

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#5478]
One doesn't want to look for all the senders of it in a huge image...

![image](https://user-images.githubusercontent.com/4706329/72272561-21644580-3629-11ea-8261-7e0bc54fbf26.png)

The main issue is that the tab contents is searched before the opening of the window.

And even if the tab is loaded lazily, a confirmation message for the loading will be welcomed.

**Comment by Ducasse** [comment]
Indeed. We will revisit many of the extensions because some of them are not making sense.

**Comment by Ducasse** [comment]
Esteban has a pane that is really lazy. So we could remove the senders and implementors (I think that this is not needed in Pharo since we can just press CMd-N and Cmd-M) but what do you think? We wait for the lazy tab? or just remove them? (last one is my favorite).

**Comment by Ducasse** [comment]
there is also 

gtInspectorInstancesOn: composite
	<gtInspectorPresentationOrder: 40>
	^ composite table
		title: [ 'Instances' translated ];
		display: [ self allInstances ];
		column: 'Hash' evaluated: [ :each | each hash asString ];
		column: 'Object' evaluated: [ :each | each printString ]

I do not see the value of this.
