### ISSUE TITLE
Surprising file writeStream behaviour - it does byte by byte overwrite

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#5480]
It might be me who expected something else, but in other languages it seems the normal thing a write stream does is that it overwrites any existing contents of a file. Sometimes you can make it an append stream, which - well - appends contents to the end.

But Pharo does something which surprises me:

```smalltalk
'foobar.txt' asFileReference  writeStreamDo: [ :s | s << 'Hello World!';flush;close ].
'foobar.txt' asFileReference readStream contents.  "'Hello World!'"
'foobar.txt' asFileReference  writeStreamDo: [ :s | s << 'Waves';flush;close ].
'foobar.txt' asFileReference readStream contents. "'Waves World!'"
```
It writes from the beginning of the file, but leaves existing stuff in the file intact. 

While I am sure it might be useful in some situations, I find it surprising as the default action.

**Comment by kasperosterbye** [comment]
Ultimately the `flush` ends up using `File class>>write:from:startingAt:count:`, which is a primitive that overwrite existing bytes, but leaves the rest in place.

**Comment by kasperosterbye** [comment]
The problem as I see it is that `FileReference>>binaryWriteStream" do not rewind the file. It would seem that it need to be rewritten to do an "ensureDelete", and end up as:

```smalltalk
binaryWriteStream
	"Answer a buffered binary write stream on the receiver"
	self ensureDelete. " <--- added statement"
	^ ZnBufferedWriteStream on: (filesystem binaryWriteStreamOn: self path)
```

But as I said, I am not sure it is unintended in the first place.

**Comment by svenvc** [comment]
Hi Kasper,

Yes, it is like that: if you open a file for writing but it already exists, you will be overwriting it from the beginning. When closing, the file will not be truncated, so some old content might survive.

To append, you can call #setToEnd on a write stream.

Like you suggest yourself, it is the user's task to decide what to do if the file already exists, you could check and/or ensureDelete it.

Always doing ensureDelete would cost more.

Sven

BTW, there is also truncate[:] but I never tried that, it might be useful in this context as well.

> On 14 Jan 2020, at 10:23, Kasper Østerbye <notifications@github.com> wrote:
> 
> The problem as I see it is that `FileReference>>binaryWriteStream" do not rewind the file. It would seem that it need to be rewritten to do an "ensureDelete", and end up as:
> 
> binaryWriteStream
> 	
> "Answer a buffered binary write stream on the receiver"
> 
> 	
> self ensureDelete. " <--- added statement"
> 
> 	
> ^ ZnBufferedWriteStream on: (filesystem binaryWriteStreamOn: self path)
> But as I said, I am not sure it is unintended in the first place.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
Sven Van Caekenberghe - mailto:sven@beta9.be
Beta Nine - software engineering - http://www.beta9.be

**Comment by PharoProject** [comment]
> Am 14.01.2020 um 10:18 schrieb Kasper Østerbye <notifications@github.com>:
> 
> It might be me who expected something else, but in other languages it seems the normal thing a write stream does is that it overwrites any existing contents of a file. Sometimes you can make it an append stream, which - well - appends contents to the end.
> 
> But Pharo does something which surprises me:
> 
> 'foobar.txt' asFileReference  writeStreamDo: [ :s | s << 'Hello World!';flush;close ].
> 'foobar.txt' asFileReference readStream contents.  "'Hello World!'"
> 'foobar.txt' asFileReference  writeStreamDo: [ :s | s << 'Waves';flush;close ].
> 'foobar.txt' asFileReference readStream contents. "'Waves World!'"
> It writes from the beginning of the file, but leaves existing stuff in the file intact.
> 
> While I am sure it might be useful in some situations, I find it surprising as the default action.
> 
> 
Indeed it is surprising as it starts from the start but does not truncate the file. If you want to append you can use #setToEnd on the stream before writing to it.

Norbert

**Comment by kasperosterbye** [comment]
Rather than deleting it - truncate seems better - I had not noticed that method.

**Comment by kasperosterbye** [comment]
So - @svenvc - this is a feature and specialty of Pharo (perhaps smalltalk) and as such this is not an issue? 

Python and Java has implicit truncate when you make a writeStream, which is what caused me to get confused.

```smalltalk
'foobar.txt' asFileReference  writeStreamDo: [ :s | s truncate. s << 'Waves' ].
```
Does what I want, and I can live with that.
