### ISSUE TITLE
Updating values in a dictionary is cumbersome and inefficient

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#5486]
As an example, the following code from `Bag`.

```smalltalk
add: newObject withOccurrences: anInteger 
	"Add newObject anInteger times to the receiver. Answer newObject."

	contents at: newObject put: (contents at: newObject ifAbsent: [0]) + anInteger.
	^ newObject
```

It should not be necessary to lookup the key twice, and while it is a one liner it is an idiom rather than an abstraction. I will propose we include a method in` Dictionary`: 

```smalltalk
aDict at: key update: [:val | val + 7] initial: [0].
```

**Comment by juliendelplanque** [comment]
I definitely agree with this proposal.
I always find annoying to have to write this pattern to update a value.

Now, why the initial argument needs to be a block?

**Comment by kasperosterbye** [comment]
I suggest the first to be a block to enable the update to cover more than `+`. I have from time to time had dictionaries of `OrderedCollection?, in which case it becomes:
```smalltalk
aDict at: key update: [:col | coll addLast: 99 ] initial: [OrderedCollection new].
```

**Comment by kasperosterbye** [comment]
I think PR is reopened now.
@juliendelplanque - should I interpret your comment that the *increment* pattern is so common it should exist as well:
```smalltalk
aDict at: key incrementBy: 2 initial: [0]
```

**Comment by juliendelplanque** [comment]
No, I mean why

`aDict at: key update: [:col | coll addLast: 99 ] initial: [OrderedCollection new].`

and not just

`aDict at: key update: [:col | coll addLast: 99 ] initial: OrderedCollection new.`

Why the third parameter can be a block?

**Comment by kasperosterbye** [comment]
@juliendelplanque - because I do not want to compute the initial value on each increment. Perhaps that is a stupid optimisation.

Actually, I believe both is possible as you can send `value` to any object, so you should be able to call it both ways (as per my PR)

**Comment by MarcusDenker** [comment]
PR has been merged
