### ISSUE TITLE
SpChooseMethodUI>>#protocolListAction has been deprecated. Use #methodSelectors instead.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5499]
\\DeprecationPerformedNotification: Automatic deprecation code rewrite: The method Protocol>>#methods called from SpChooseMethodUI>>#protocolListAction has been deprecated. Use #methodSelectors instead.

**Comment by MarcusDenker** [comment]
class SpChooseMethodUI does not exist anymore
