### ISSUE TITLE
Allow concatenation of CompositeAnnotationContext subclasses too

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#5501]
The #, concatenation is implemented with a hard reference on CompositeAnnotationContext

```Smalltalk
, anAnnotationContext
	^ CompositeAnnotationContext with: (parts copyWith: anAnnotationContext asAnnotationContext)
```
which is also shown as a lint problem.

So concatenation is not possible when one (for whatever reason) needs to subclasses this class. We should better use "self class" here.

```Smalltalk
, anAnnotationContext
	^ self class with: (parts copyWith: anAnnotationContext asAnnotationContext)
```

**Comment by MarcusDenker** [comment]
merged
