### ISSUE TITLE
Source of slugginess

### ISSUE THREAD

**Issue by egvillalobos** [guillep/pharo-core#5512]
```
RBImplementedNotSentRule class >> allMessages
	"return all 'message sends' in the system and cache them"

	^allMessages ifNil: [
		allMessages := IdentitySet new.
	
		Smalltalk globals allBehaviors do: [ :behavior | 
				behavior methodsDo: [ :method |
					self forApproxMessagesOf: method do: [ :mes |
						allMessages add: mes ] ] ].
		allMessages	]

```

This method rescans the complete system.
This method is called when the analysis is performed. 
And the cache is invalidated each time a method is added, removed, or modified!

We are not saying that this method is executed at each method added, removed, modified but the cache is flushed.

**Comment by StephanEggermont** [comment]
So allMessages needs to become an IdentityBag and instead of nilling the exact change needs to be calculated from the event?

**Comment by Ducasse** [comment]
Probably

**Comment by MarcusDenker** [comment]
or we could do the recalculation in a low-priority thread and update the reference the new collection when that is finished?

**Comment by tesonep** [comment]
Low priority processes are complicated, as they may not finish before the forking of a new one. For example if the user add new letters to the search. 
@MarcusDenker we should not add new users of fork directly, we have been talking about scheduling this task and using taskit, this is a good example of something should not be done by hand, as it has to be able to be interrupted and also it is important to give feedback to the user. 
This should be handled globally in the system, as this use case is not different than the one of Calypso or Spotter.

**Comment by StephanEggermont** [comment]
I don't think this global knowledge should be stored there. To me it sounds more like something for the SystemNavigation or so.

**Comment by MarcusDenker** [comment]
We have turned off the rule for now
