### ISSUE TITLE
Update class comments of Regex

### ISSUE THREAD

**Issue by egvillalobos** [guillep/pharo-core#5514]
Indeed the script proposed is working well when the class references and the renamed classes are packaged in the package with the mentioned prefix. 
But it breaks to update (apply the refactorings) to classes that are packaged in packages not covered by the package prefix.

For the record the script is 
```| pkgPrefix newClassPrefix env model |
pkgPrefix := 'General'.
newClassPrefix := 'Re'.
env := RBBrowserEnvironment new 
			forPackageNames: (RPackage organizer packageNames select: [ : pkgName | (pkgName beginsWith: pkgPrefix) ]).
model := (RBClassModelFactory rbNamespace onEnvironment: env) name: 'MyModel'; yourself.
RBClassRegexRefactoring new
	model: model;
	renameClasses; 					"Here I just want a rename no copy"
	replace: '^GR(.*)$' with: newClassPrefix,'$1';
  execute.
```

**Comment by pavel-krivanek** [comment]
The classes are already named as the script proposes.
The issue can be closed.
