### ISSUE TITLE
Another quantic jump in pakage quality requires class unload hook!

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5529]
We should introduce a hook at the level of the class 
- preUnload
- unload

The idea is that a package should be
- clean loading 
- green tests
- clean unloading 
- green tests

For example check #5521 you cannot rename such classes without breaking everything. 
You cannot load a file that rename or changes such classes.
Why because the class should at during unload, unregister from systemAnnouncer and the hook is missing.

**Comment by kasperosterbye** [comment]
I am still confused about what is a package, a project, a category, package manifest, baseline, iceberg projects, ....
It seem to me like there is a need to get some basic structure settled upon before settling on this (implicit) proposal. 

This comment is meant as an upvote for the importance of the problem (but perhaps not this github issue).

**Comment by Ducasse** [comment]
A package is a group of classes. 
A project not reified is a group of packages or projects.
A baseline is a map to load a project
A category does not exist anymore (except in the implementation). 
Now all these concepts are orthogonal with the fact that right now I can tell you to rename a class and commit the code and you will not be able to reload! Because you break the system because this class did unload itself nicely. 
So adding one extra message does not hurt and will bring a lot of stability on places 
that can really put the system on its knees.

**Comment by Ducasse** [comment]
A packageManifest is a stupid class representing package object meta data and we should probably promote this class as Package associated with a package object (because a package should represent the list of classes it contains also the extensions.... and this is done by instance of RPackage.

**Comment by Ducasse** [comment]
Also system like VisualWorks or Envy have this hook since ages. When I was taught smalltalk Joesph Perline told me that I will be a good developer not when my code loads but when it unloads cleanly and he was super right.

**Comment by kasperosterbye** [comment]
👍

**Comment by kasperosterbye** [comment]
My comment to all above is two things:
a) by all means, lets have it if it has proven its worth elsewhere!
b) to me it sounds more like you need an "undo" on your baseline (which then might use what you are asking for). 

But as always, I still feel like a newbie in a lot of this.

**Comment by Ducasse** [comment]
No this is not an undo. 
Each class should be able to specify a postLoad action, a preUnload
VW has three and I do not remember.
Then may be you want to have the same at the package level. 
Especially the postLoad because normally we have initialize for that and 
by design I would prefer that programmer solves the problem via their design. 
For the unload this is a different story because we do not have a hook to unload. 
We have a startup and shutdown but no unload
so we cannot express it so we don't and we get a system more brittle than he could be. 
With the unload with one expression of one line some problems related to registration to announcers can be fixed.
SystemAnnouncer default unregister: self. 
but we have to way to express it.

**Comment by kasperosterbye** [comment]
👍

**Comment by David5i6** [comment]
I recently had some issues after an error installing Roassal.
The UML View was registered but the depending classes were not.

Perhaps classes in a package can refer which other classes are needed to be installed so the loader can load them in order. Also package load must offer the option to load atomically, ie: if a class gives an error, no class is loaded (or currently loaded classes are loaded).

**Comment by akevalion** [comment]
@David5i6 In last version of Roassal, UML class panel is not included in calypso system browser.

**Comment by astares** [comment]
> Also system like VisualWorks or Envy have this hook since ages. When I was taught smalltalk Joesph Perline told me that I will be a good developer not when my code loads but when it unloads cleanly and he was super right.

Yes - and he was and is right. His "Mastering ENVY" book is still here in my bookshelf.
 
I remember the module system that was built for the "Squeak world tour" (SWT) from Joseph Pelrine and John Sarkela after we all met at the first CampSmalltalk 2000 in San Diego to build a better Smalltalk alignment by porting to all dialects tools like TestRunner, XML library, Socket implementations, ..... 

This module of SWT allowed to load and unload packages. I guess I still have the "Squeak world tour" image available on an old CD and maybe we can revive or reuse some of its ideas.  

But in Pharo typically the package manifest class represents the package (package description is taken from the Mainfest class comment already).

Maybe it would already help to have the hooks on the package manifest class

**Comment by Ducasse** [comment]
We have postLoad: so we should have preUnload:

**Comment by MarcusDenker** [comment]
I added a reference to a newer issue https://github.com/pharo-project/pharo/issues/14073, I close this one
