### ISSUE TITLE
FFI is seriously broken

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#5534]
While trying to prepare an image with Mars, I got this issue:
FFIVariableArgument did not understand #emitArgument:context:
see:
https://github.com/pharo-project/threadedFFI-Plugin/issues/20

It is caused by commit https://github.com/pharo-project/pharo/commit/b839d66fae6cd779f58726ddc4d5576853959aec

Recovering the old method content leads to:
`Instance of FFIExternalValueHolderType did not understand #emitArgument:context:`
Recovering of the implementation in `FFIExternalType` causes:
`Instance of FFITypeDeclaration did not understand #emitReturn:resultTempVar:context:`
...then I stopped to try

**Comment by guillep** [comment]
We have to put threadedFFI up to date. I'll check it after lunch

**Comment by pavel-krivanek** [comment]
ok, as I see, the problem really in old API usage in ThreaddedFFI (like not using inCallout: argument, stringEncodingStrategy etc.) 
I will close the issue here
