### ISSUE TITLE
Debugger crashes for any Warning - emergency evaluator opens instead

### ISSUE THREAD

**Issue by JanBliznicenko** [guillep/pharo-core#5545]
In latest images of Pharo 8 and 9 (including the "main" ones in Pharo Launcher), whenever debugger should open for Warning, it does not and emergency evaluator opens instead.

![2020-01-22](https://user-images.githubusercontent.com/9571633/72893634-ceba1600-3d19-11ea-8e20-8cf70b4477d3.png)

In Pharo 8, it happens since build `1121.sha.bbcdf97` (commit bbcdf97 ). 
Build `1120.sha.c115bf4` (commit c115bf4 ) is ok.
On Windows, Linux and Mac.

Steps to reproduce:
1. Get clean latest Pharo 8 image.
2. Run `self notify: 'hi'` or anything else that should signal any warning.

**Comment by MarcusDenker** [comment]
GTSpecPredebugActionPresenter>>#initializeWidgets calls non existing method #presenterAt:put:

**Comment by MarcusDenker** [comment]
It seems the pull request that did that was https://github.com/pharo-project/pharo/pull/5513

**Comment by MarcusDenker** [comment]
It seems there is a trait missing in the GTSpecPreDebugActionsPresenter class, if I do this, it works:

SpPresenter subclass: #GTSpecPreDebugActionsPresenter
	uses: SpTDynamicPresenter
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'GT-Debugger-UI'

**Comment by JanBliznicenko** [comment]
I tried new image and it is fixed, thank you

**Comment by JanBliznicenko** [comment]
I decided to reopen the issue until this fixed build is put as stable here: 
https://files.pharo.org/image/80/stable-64.zip
and here:
https://files.pharo.org/image/80/stable-32.zip
because these are the links Pharo Launcher takes "official" images (that everybody downloads) from, as you can see here:
https://github.com/pharo-project/pharo-launcher/blob/master/sources.list

**Comment by seandenigris** [comment]
A new 8.0.1 release has been tagged, but the URL still downloads 8.0.0 (bbcdf97). Is there another step?

**Comment by estebanlm** [comment]
There is an error in the CI and it did not uploaded the stable*.zip archives (while it did the latest). 
I uploaded them by hand but we need to review the process (problem is now I cannot test it in my machine anymore, I need to prepare an environment)
