### ISSUE TITLE
String assumes specific class hierarchy

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#5549]
I want to make an other subclass of String (slices). In that process I have found a number of methods in String which use `self class` instead of `self species` preventing me from making a seamless implementation of string slices.

Also, the method alike make assumptions on class hierarchy through assumptions on which superclass to hit on `super at:`. 

Finally, the `asByteArray` is implemented for `WideString` in String, and overwritten in `ByteString`, instead of being declared abstract in `String`.

As soon as I get my git stuff set up for Pharo 9, I expect to make a PR which fixes this (which I did already in a local image).

**Comment by Ducasse** [comment]
From the latest Pharo 90 image, you should checkout the 9 branch in your repo and push. 
It will sync your fork and after you get ready to work.

**Comment by kasperosterbye** [comment]
I believe I got it to work!
