### ISSUE TITLE
Inspecting a CompiledMethod should allow update?

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#5551]
It is possible to see the source code of a CompiledMethod in the inspector. One use scenario I have found is 
```smalltalk
("complicated collect/select of compiled methods") inspect
```
which gives me in the inspector a list of methods which have a specific problem I queried for.
Now, to fix these problems, I need to go and find the method in the browser, rather than editing it directly in the inspector where it is showing.

One example I looked at was to find all the methods in String which sends `class` to self:
```smalltalk
String methods select: [ :m | m ast selfMessages includes: #class ]
```
some of these should be changed to `self species`, other should not. But it would be convenient to do it in the inspector where I got the list of methods, and looked at the source code.

**Comment by MarcusDenker** [comment]
Yes, we can add this method to CompiledMethod:


gtInspectorSourceIn: composite
	<gtInspectorPresentationOrder: 00>
	^ composite pharoMethod 
		title: 'Source';
		smalltalkClass: [ self methodClass ];
		display: [ self sourceCode ];
		act: [ :text | self methodClass compile: text text notifying: nil ]
			icon: GLMUIThemeExtraIcons glamorousAccept
			on: $s
			entitled: 'Accept';
		act: [ self browse ] 
			icon: GLMUIThemeExtraIcons glamorousBrowse 
			entitled: 'Browse'

**Comment by MarcusDenker** [comment]
This makes a editable source view the default view, with editing enabled

**Comment by MarcusDenker** [comment]
(this then allows us to remove a lot of #asRingDefinition calls, too)

**Comment by MarcusDenker** [comment]
In https://github.com/pharo-spec/NewTools/pull/184 I have enabled accepting code *if* that method is currently installed.

This means that if the method gets updated from somewhere else while you have an inspector open, it will not allow editing.

**Comment by kasperosterbye** [comment]
Awesome Marcus!!!
