### ISSUE TITLE
Recent Messages menu item results in warning

### ISSUE THREAD

**Issue by webwarrior-ws** [guillep/pharo-core#5555]
Pharo 8, both 32-bit and 64-bit. Windows 10.

Also this menu item uses Ctr+Z key combination that expectedly doesn't work.

![Capture](https://user-images.githubusercontent.com/6537039/72920946-fd081780-3d52-11ea-9d31-ca61871cd33d.PNG)

**Comment by JanBliznicenko** [comment]
For the emergency evaluator part of the problem, fix is already being prepared - see issue #5545 

The original problem (why debugger tried to open) is still there though, so I recommend checking again and updating your issue once #5545 is fixed.

**Comment by JanBliznicenko** [comment]
The emergency evaluator issue is fixed, so, please, download latest (current) Pharo 8 image (build 1124 or later), try it again and update the issue

**Comment by webwarrior-ws** [comment]
OK, but still I get warning and the tool doesn't work.
Either fix it or remove from the image.

```
The method SpPresenter>>#title: called from RecentMessageList>>#open has been deprecated. With Spec 2, SpPresenter was refactored to move all window management to WindowPresenter.
	From now on, if you want to interact with a window you need to:
	- Implement #initializeWindow: method (#initializeDialog: for dialogs) to manage window elements before the presenter is opened
	- Use the method #window or #withWindowDo: to interact with windows after it has been opened.

Select Proceed to continue, or close this window to cancel the operation.
```
