### ISSUE TITLE
do not shout big literal methods

### ISSUE THREAD

**Issue by estebanlm** [guillep/pharo-core#5560]
a "literal methods" are those that contains just a single string or bytearray with resources embedded in the image (typical for images, fonts, etc.)

Shout process takes too much time, and slows the full system. We want a setting to enable/disable this shout. 

Alternatively we can try improve shout for this cases (maybe using a non-AST based parser).

**Comment by MarcusDenker** [comment]
I do not think that the parser is the problem... if we recompile a method with a 700K string, it still can be done 13 times per second:

[(HiExampleCommit class>>#iceberg_v1_5_6) recompile] bench. "'13.859 per second'"

Of course a simple method is faster:

[(Object>>#halt) recompile] bench.  "'5973.821 per second'"


So I would suggest to first tag methods with large literals and not shout them and see if that fixes the problem.

**Comment by MarcusDenker** [comment]
Ups, better bench:

[(HiExampleCommit class>>#iceberg_v1_5_6) parseTree] bench. 
 "'14.700 per second'"
[(Object>>#halt) parseTree] bench.   "'24617.953 per second'"

(as we need to create the AST). 

According to the TimeProfiler, 57% of the runtime is spend reading the sources from the (cached) .sources

**Comment by estebanlm** [comment]
in fact, the problem is more complex. 
shout takes some time, indeed... but most of the time is done verifying for decorators (like halts and that).

**Comment by dionisiydk** [comment]
I did little optimization for string literal scanning #5773.
