### ISSUE TITLE
Pharo 8 DropListMorph ghostText: causes DNU in RubTextFieldArea

### ISSUE THREAD

**Issue by riverdusty** [guillep/pharo-core#5566]
simple example to cause issue.
Pharo 8 64bit on Windows 10 64bit.
```
| aList |
aList := DropListMorph 
	on: nil list: (OrderedCollection new) 
	selected: nil
	changeSelected: nil.
aList ghostText: 'Select'
```

**Comment by astares** [comment]
- ghostText: is deprecated anyway if you check all implementors
- can confirm the error - we should deprecate the ghostText: from DropListMorph too
   (Pharo UI building is moving towards Spec2 anyway and there the method is called #placeholder:)

**Comment by riverdusty** [comment]
Would also help to write a test for this (substituting ghostText for placeholder) so this doesn't reoccur in the future

**Comment by Ducasse** [comment]
Thanks please send a test.

**Comment by riverdusty** [comment]
> Thanks please send a test.

Is this the new way of saying,"Submit a diff" ? xD

I will do a PR with a test when i get a chance

**Comment by MarcusDenker** [comment]
Can you check if this is still needed?
