### ISSUE TITLE
ZnUrl does not support protocol-relative URLs

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#5567]
ZnUrl does not support protocol-relative URLs.

Protocol-relative links (PRL), also known as protocol-relative URLs (PRURL), are URLs that have no protocol specified. For example, //example.com will use the protocol of the current page, either HTTP or HTTPS. (https://en.wikipedia.org/wiki/URL#prurl)

We could use it to replace TCPAddress from the Seamless packages.

**Comment by svenvc** [comment]
(1) is there an RFC that describes this ? ZnUrl is mostly based on https://tools.ietf.org/html/rfc3986

(2) I don't know about TCPAddress from Seamless

(3) there is a concept of relative URLs that is part of the RFC mentioned above implemented in the method ZnUrl>>#withRelativeReference:

```
'http://pahro.org/page.html' asZnUrl withRelativeReference: '//example.com'.

 "http://example.com/"

'https://pahro.org/page.html' asZnUrl withRelativeReference: '//example.com'.   

"https://example.com/"
```

Here the receiver is the context (the page) and the argument is the relative url on that page.

Would that help ?



<blockquote><img src="/images/rfc.png" width="48" align="right"><div><strong><a href="https://tools.ietf.org/html/rfc3986">RFC 3986 - Uniform Resource Identifier (URI): Generic Syntax</a></strong></div></blockquote>

**Comment by pavel-krivanek** [comment]
hmm, as I see, it is really meant to be the concept of relative references and the usage I had in mind is not in line with the way how URLs are defined. Thank you. I'm closing the issue.
