### ISSUE TITLE
Check the impact of Inspector extensions on large images

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#5568]
Different extensions should be analyzed:

- Senders
- Implementors
- All instances

**Comment by jecisc** [comment]
One problem seems to come from the fact that extensions are not lazily computed?

I inspected the same huge model in an image with and without custome extensions, the one without extension is much faster. And this, when I never clicked on the custom tab.

Maybe the Spec inspector with lazy tabs will improve the situation?

**Comment by MarcusDenker** [comment]
So the Senders and implementors (before I changed it) where doing a "give me all senders / implementors" just to know if it should show a tab or not. 

So yes, it was slow even without going to the tab itself. The new version does not do that (instead shows in empty tab) and only costs time if you click in the tab.

**Comment by MarcusDenker** [comment]
Status: 
- All instances has been removed
- Senders and Implementors on Symbol has been speed up *a lot*

**Comment by MarcusDenker** [comment]
changes have been merged

**Comment by Ducasse** [comment]
So do we close it?
