### ISSUE TITLE
testDefaultImageDoesNotStoreAnySetting failing in Pharo9 on CI (all plattforms)

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#5571]
Error
Given Collections do not match! additions : an Array(a StoredSetting('#useSecondarySelection#secondarySelectionTextColor') a StoredSetting('#Rubric#backgroundColor') a StoredSetting('#''Code Completion''#backgroundColor') a ClassStoredSetting('#appearance#uiThemeClass') a StoredSetting('#LineNumbers#lineNumbersTextColor') a StoredSetting('#menu#menuColor') a StoredSetting('#LineNumbers#lineNumbersBackgroundColor') a StoredSetting('#Rubric#textColor')) missing: #()
Stacktrace
SystemSettingsPersistenceTest(TestAsserter)>>assert:description:resumable:
SystemSettingsPersistenceTest(TestAsserter)>>assert:description:
SystemSettingsPersistenceTest(TestAsserter)>>assertCollection:hasSameElements:
SystemSettingsPersistenceTest>>testDefaultImageDoesNotStoreAnySetting

**Comment by MarcusDenker** [comment]
Interestingly it is green when I run it locally with the latest Pharo9

**Comment by tesonep** [comment]
To reproduce it should be run without preferences, I am uploading a PR for it
