### ISSUE TITLE
There is a whichSelectorsRead: but not whichSelectorsWrite:

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5574]
"queries"
Class >> whichSelectorsWrite: instVarName
	"Answer a Set of selectors whose methods write to the argument, 
	instVarName, as a named instance variable."

	^ self
		slotNamed: instVarName
		ifFound:
			[ :slot | self selectors select: [ :sel | slot isWrittenIn: self >> sel ] ]
		ifNone: [ #() ]

We should add tests too.

**Comment by MarcusDenker** [comment]
There is one called "whichSelectorsStoreInto:" there used to be whichSelectorsAssign:, which was deprecated for whichSelectorsStoreInto:, but I think this was because we had both.

**Comment by Ducasse** [comment]
Ok storeinto looks clunky. 
Read is not readFrom: I could not find whichSelectorsStoreInto: which is super strange too.
