### ISSUE TITLE
Rename protocol refactoring should select the current name

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#5580]
Most of the time, when we want to rename a protocol, we want to change it entirely. 

I wonder if it would not be better to select the text when we open the rename protocol window instead of having the selection before the current value?

**Comment by Ducasse** [comment]
I would like to just double click on the list and edit in place (we are in 2020) so this popu plague is boring and we had the in place edit in the past.

**Comment by Ducasse** [comment]
To me the interaction in Nautilus is often alien and I do not understand how to use it.

**Comment by Lin777** [comment]
Already fixed in https://github.com/pharo-project/pharo/pull/8394
