### ISSUE TITLE
Should we deprecate our lovely catalog :(

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5586]
I loved it. Now the hosted data is obsolete and christophe should really release PakBot.

**Comment by astares** [comment]
For the time being I created a http://www.smalltalkhub.com/#!/~Pharo/MetaRepoForPharo90
so at least catalog is working for now in Pharo 9 too until we have a replacement.


Any more info on **PakBot** so contributors can step in and help? 

https://github.com/pharo-pkg does not seem to have much activity and contains only tests - not real code.



<blockquote><img src="/files/ShFiles/favicon.ico" width="48" align="right"><div><strong><a href="http://www.smalltalkhub.com/#!/~Pharo/MetaRepoForPharo90">SmalltalkHub</a></strong></div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/41051729?s=280&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-pkg">pharo-pkg</a></strong></div><div>pharo-pkg has 4 repositories available. Follow their code on GitHub.</div></blockquote>

**Comment by estebanlm** [comment]
we need a different catalog. 
now, PakBot is big beast... I have an idea to replace it with ston files and a GitHub repository. 
Now, problem is to have time to do it :/

**Comment by PharoProject** [comment]
What is PakBot? You know in the long run I want to provide a new catalog like I presented on ESUG. But it won't happen soon. But I want to avoid to waste effort on something that is being implemented already.

Norbert

**Comment by Ducasse** [comment]
Same here. I will let christophe answer. We requested money to pay his salary to finish the package dependency system and repo that he developed. We are not doing something else. 
Now to me metacello should be revisited and we need to be able to build tools on top of a new dependency management. I also want to have distributions **Validated** (smallIint + tests run).

**Comment by astares** [comment]
If I understood him correctly  PakBot is essentially what is in https://github.com/demarey/cargo

Side note: 
- we branded the  https://github.com/pharo-pkg now with an icon as the other official repos
  (all branding material including these icons is on https://github.com/pharo-brand)


<blockquote><img src="https://avatars3.githubusercontent.com/u/2494203?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/demarey/cargo">demarey/cargo</a></strong></div><div>Cargo package manager. Contribute to demarey/cargo development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/41051729?s=280&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-pkg">pharo-pkg</a></strong></div><div>pharo-pkg has 4 repositories available. Follow their code on GitHub.</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/46996382?s=280&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-brand">pharo-brand</a></strong></div><div>Pharo Brand items. pharo-brand has 3 repositories available. Follow their code on GitHub.</div></blockquote>

**Comment by noha** [comment]
> Am 29.01.2020 um 12:29 schrieb StéphaneDucasse <notifications@github.com>:
> 
> Same here. I will let christophe answer. We requested money to pay his salary to finish the package dependency system and repo that he developed. We are not doing something else.
> Now to me metacello should be revisited and we need to be able to build tools on top of a new dependency management. I also want to have distributions Validated (smallIint + tests run).
> 
> 
That is what I want to do. I'm building a scanner that collects projects and derives the dependency graph from them. These projects and dependants are added to the repository and are checked for a lot of things like tests + lint + documentation + activeness + etc…

From all these projects we define a barrier that makes a project worth to be part of the pharo ecosystem. And the ecosystem will be recommended. And much more I don't have time to do :)

Norbert

**Comment by demarey** [comment]
@noha Pakbot is the new name of Cargo, the package manager I developed. I had to rewrite it after discussions with people and then to stop working on it to focus on other projects (e.g. Pharo Launcher). The current state is that the dependency manager is ok for experimentations with project dependencies granularity (I want to introduce back package dependencies ASAP). Integration with Pharo tools (e.g. Calypso) was not so bad but Pharo moved: I will need to resync. Then, I just started to work on the repository to host project metadata (ston file that includes project dependencies) on a github repository (I had a mongo-db implementation but it requires more work to maintain). Also, I got an early version of Metacello baseline support and automatic conversion. We should discuss what you already have. If I understand, you have a project scanner (baseline parsing?) to determine dependencies (including transitive ones) and a set of "trusted/validated" project that you use to compare. Do you already have the validation part? I did not look on this topic for now.

**Comment by noha** [comment]
I'm starting to pick that up again. I started to convert baselines to my model and am working on dependency resolution. This I need for the scanner but it will be as benefical for package loading as well. So if you have time we might discuss in order to join forces where possible

**Comment by demarey** [comment]
@noha I'm back to work next monday. We can sync monday 17th if you want. I started to work again on Pabot before my holidays and it is now ported to Pharo 9. It would be great if we can join forces.

**Comment by PharoProject** [comment]
Ok, let’s try to meet then

**Comment by jecisc** [comment]
I have the impression catalog is not here anymore?
I’m closing for now
