### ISSUE TITLE
RBSimpleFormatter should not use start and stop to print comments

### ISSUE THREAD

**Issue by hogoww** [guillep/pharo-core#5587]
basicFormatCommentFor: aComment
	codeStream nextPutAll: (originalSource copyFrom: aComment start to: aComment stop)

Nor does it make sense to use the original source, since the comment is already a parameter.

**Comment by hogoww** [comment]
basicFormatCommentFor: aComment
	codeStream nextPutAll: aComment contents

seems to work.
Will do it later if nobody takes care of it first, cannot do it now :p

**Comment by MarcusDenker** [comment]
The same is true for all the other AST pretty printers: they can *not* rely on the old formatted code, as their job is explicitly to go from AST -> text without having text.

**Comment by hogoww** [comment]
Problem with that one is that it's also unneeded. (or I really don't understand it)
Because the comment already contains the character stream necessary, so why copy it from the originalSource? 
Looks like a residue of another time to me.

But yeah, others should not do it either, definitely
