### ISSUE TITLE
Improve log when sending a message to an unknown global

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#5600]
Currently, when you send a message to an unknow global, you get this kind of error:

```Smalltalk
VariableNotDeclared: receiver of "new" is nil
UndefinedObject>>doesNotUnderstand: #new
FQNameQueryTest(FQAbstractQueryTest)>>setUp
```

It would be much better to find the problem if we could also log the name of the variable in the error message. For example `VariableNotDeclared: receiver named "MooseSmalltalkImporter" of "new" is nil

**Comment by MarcusDenker** [comment]
This is now better: you get an UndeclaredVariableRead exception which prints the variable name
