### ISSUE TITLE
DateTest >> #testPrintFormat fail

### ISSUE THREAD

**Issue by CafeKrem** [guillep/pharo-core#5618]
```Smalltalk
printFormat := #(1 2 3 $/ 1 1).
self assert: (january23rd2004 printFormat: printFormat) equals: '23/1/2004'.
...
next test
```
this first assertion fail got '23--04' instead of  '23/1/2004'

**Comment by Ducasse** [comment]
Thanks for reporting it. 
I will close this issue since I checked and the test is passing on the latest Pharo90 image.
