### ISSUE TITLE
Why cmd+d is now bound to the breakpoint menu?

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5623]
When I select in a method Dictionary new and press command+D why do I get the following menu?

![Screenshot 2020-02-01 at 15 16 17](https://user-images.githubusercontent.com/432549/73593564-d5a90b80-4505-11ea-9e66-3cd44086b1ef.png)

**Comment by estebanlm** [comment]
I can confirm. I though it was my mistake :)

**Comment by dionisiydk** [comment]
Ah, I just remembered. It was done through my bad review :)
Is it in Pharo 8 as well?

сб, 1 февр. 2020 г., 15:21 Esteban Lorenzano <notifications@github.com>:

**Comment by Ducasse** [comment]
It is working correctly in P8.

**Comment by StevenCostiou** [comment]
I guess it's a bug I introduced. Looking at it.

**Comment by StevenCostiou** [comment]
I put meta + shift + g which seems available. I'm doing a PR.
However it's a bit complicated to get to that menu, which is kinda important.

**Comment by Ducasse** [comment]
Thanks!
