### ISSUE TITLE
Bootstrap broken: MessageNotUnderstood: RGBehavior>>announceEnvironmentChanged

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#5642]
The bootstrap is broken somehow... all CI runs fail with:

MessageNotUnderstood: RGBehavior>>announceEnvironmentChanged

see: https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-5640/1/pipeline/10

The last build of Pharo9 itself was successful, though

**Comment by MarcusDenker** [comment]
It seems that #methodRemoved: tries to call #announceEnvironmentChanged, but that method does not exist. The method RGEnvironmentAnnouncer>>methodRemoved: in the image seems to *not* call that method.

MessageNotUnderstood: RGBehavior>>announceEnvironmentChanged
RGBehavior(Object)>>doesNotUnderstand: #announceEnvironmentChanged
RGEnvironmentAnnouncer>>methodRemoved:

**Comment by MarcusDenker** [comment]
This is due to a change here: https://github.com/carolahp/Ring2

https://github.com/carolahp/Ring2/commit/50d30ae9c1a21b9d58e0350dbb19c984065e8637

<blockquote><img src="https://avatars2.githubusercontent.com/u/4822303?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/carolahp/Ring2">carolahp/Ring2</a></strong></div><div>Ring metamodel reimplementation. Contribute to carolahp/Ring2 development by creating an account on GitHub.</div></blockquote>

**Comment by tesonep** [comment]
Hi Marcus, yes it is that change. Caro has proposed a PR to fix the ring
version used in the bootstrap to the correct one.

**Comment by MarcusDenker** [comment]
Thanks! I merged both for Pharo8 and Pharo9
