### ISSUE TITLE
Meta + j (Jump to next keyword) inserting "j" on linux

### ISSUE THREAD

**Issue by edcrypt** [guillep/pharo-core#5648]
The keymapping for jumping to the next keyword (ifTrue: [jump from here] ifFalse: [to here]) is not showing on the keymap browser, despite being defined on RubSmalltalkEditor class>>#buildShortcutsOn:. If I try to use it, the "j" character is inserted.

Pharo 8.0.0
Build information: Pharo-8.0.0+build.1124.sha.0932da82f08175e906b0e2a8052120c823374e9f (64 Bit)
Linux 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by estebanlm** [comment]
this is not a bug, that functionality has been removed (despite being defined, that method is never called).

**Comment by edcrypt** [comment]
@estebanlm Shouldn't the "reverse" command be disabled too? (Shift + Meta + j)
