### ISSUE TITLE
XML-Parser broken in 9.0

### ISSUE THREAD

**Issue by sukoi26** [guillep/pharo-core#5651]
on 8.0 it i Ok,  but test on 9.0 give error on XML-parser package 

:
![image](https://user-images.githubusercontent.com/23014567/74088133-2a62fe00-4a93-11ea-9f0d-dfddaaf7f9ee.png)

**Comment by Ducasse** [comment]
Can you give us the file and the exact expression breaking because I do not think that this is pharo the problem.

**Comment by sukoi26** [comment]
Sorry to clarify.
The files on github pharo-contributions XML-XLMParser

So i will retest the sequence in few days on clean image:
Donwload Latest pharo9.0 x64
Iceberg pharo pull latest
Iceberg pharo contributions xmlParser
Xml parser tests

**Comment by Ducasse** [comment]
Can you paste the expression you use to load the package?
Can paste upload the xlsx file if possible?
Can you paste the expression you use to produce the bug?

To fix something we always try to reproduce it.

**Comment by astares** [comment]
- loaded a fresh clean Pharo 9 from today using PharoLauncher (on Windows)
- click on "regular network connection" in the welcome window 
- opened Spotter and keyed in "XMLParser", hit ENTER to load via catalog
- run all tests: green

![image](https://user-images.githubusercontent.com/5980033/74445635-ff075700-4e76-11ea-8d54-12a270e94c59.png)

**Comment by svenvc** [comment]
Wow, does Spotter>Catalog loading stil work ? That is great.

**Comment by astares** [comment]
@svenvc 

Yes, it works. It is dependent on a setting 
```Smalltalk
CatalogSettings displayCatalogProjectsInSpotter: true
```
so one could enable/disable. Currently it is unfortunately off by default in fresh Pharo 8/9 images, 
but you could click on "regular network connection" in the welcome window (or put above expression into a "startup.st" script). 

Then one could simply open Spotter and key in "XMLParser", "Roassal3", ... or other to load.

In the past there was a discussion with @Ducasse (lamenting that catalog entries in Spotter slow down Spotter) as he teached Pharo in regions without stable internet. Which I understand but most users are connected on a fast web line and the catalog entries already appear asynchronous.

There is a simple solution:  we have an easily clickable "regular network connection" vs "slow network" text in the welcome window which internally is also affecting the above setting. 
Still I would wish the default would be to enable Spotter search:

While in Ubuntu, Yarn, npm and other you have to remember stupid commands in Pharo you just "**search and load**". :)

Catalog is still a nice tool and with the Catalog UI and with Catalog's Spotter integration 
things are accessible very easily (especially to newbees). Accessibility is key to first time users - if they struggle already in getting easy things done they might turn away.

**Side note:**
There is a discussion about finding a replacement for Catalog. But the problem of Catalog (or any other future package manager) is not the tool itself - it is more that entries get outdated and have to
be maintained over time. I'm steadily updating the configs so more projects work in recent Pharo version and we can profit from old packages in new Pharo still. Pharo alone would not make sense - it is the ecosystem that counts.

**Comment by sukoi26** [comment]
yes, it is  ok also for me via catalog. Probably a package manipulation error from me .
To close.
th+  @svenvc
