### ISSUE TITLE
Keyboard shortcuts help topic references inexistent class

### ISSUE THREAD

**Issue by ericbrandwein** [guillep/pharo-core#5653]
The subtopic 'Browser Shortcuts' has a DoIt that uses `KMDescription`, which doesn't exist. Changing it for `KMDescriptionPresenter` seems to work.

**Comment by kasperosterbye** [comment]
Thanks Eric. 

Unfortunately that help system need more than a little repair as it is seriously outdated. The page you refer to states (if I am not mistaken): 
> There are many keyboard shortcuts available in Pharo:
>
>- A full list is available in the System Browser by clicking the window menu button (the triangle) at the top right of the browser title, and selecting the 'Shortcuts Description' menu item.  >Alternatively you can evaluate (cmd-d) the following code now:
>
>KMDescription new categories: #(NautilusGlobalShortcuts); openWithSpec.
>
>- Shortcuts are typically multi-key combinations, where you hold a modifier key and press the listed secondary key. For example if something is listed as CMD-F, CMD-C you would press and hold the CMD key while typing  F and then C
>
>- The modifier key varies between platforms:
> - Windows = CTRL
> - Mac/OSX = CMD
> - Linux = CTRL

1. The triangle in the browser do not give the list
2. It is KMDescriptionPresenter as you say
3. There is no longer as subsystem called Nautilus

**Comment by kasperosterbye** [comment]
Should this specific issue be fixed, should we remove (or deprecate) topics which are no longer up to date, or should the whole help browser be removed because so many topics are outdated?
