### ISSUE TITLE
UFFI: Troubles with struct of doubles

### ISSUE THREAD

**Issue by tinchodias** [guillep/pharo-core#5701]
I implemented this tiny library:

```C
typedef struct cpVectD{double x,y;} cpVectD;
cpVectD newVectD(double x, double y);
double getVectDX(cpVectD point);
double getVectDY(cpVectD point);

typedef struct cpVectI{int x,y;} cpVectI;
cpVectI newVectI(int x, int y);
int getVectIX(cpVectI point);
int getVectIY(cpVectI point);
```

I followed the UFFI booklet (wonderful, many thanks) and it works with ints, but not with doubles.

Steps to reproduce:

- download P8 with: `curl https://get.pharo.org/64/80+vm | bash`.
- unzip attached file in same directory
- ensure lib in `issue` directory is compiled. For MacOs, the zip already.provides the dylib (created with `gcc -dynamiclib issuelib.c -o issuelib.dylib`).
- Open pharo, filein the provided .st
- Run tests CpLibraryTest. For CpVectI (struct of ints) it works, for CpVectD (struct of doubles) it fails. (The assert shouldn't have equals: but closeTo: but it shows the error.)

[UFFIDoublesStructIssue.zip](https://github.com/pharo-project/pharo/files/4214087/UFFIDoublesStructIssue.zip)

**Comment by tinchodias** [comment]
Following a suggestion via chat, I tried "TFFI" with the same results (but not sure I did it well). What I did:
- Cloned https://github.com/pharo-project/threadedFFI-Plugin
- Executed the steps of gitlab-ci:
    - cmake .
    - make install
    - make test
(it didn't work in Mac but it did in Debian 10).
- Started the image created by the test, loaded my code and ran the tests... same.

<blockquote><img src="https://avatars3.githubusercontent.com/u/1838382?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/threadedFFI-Plugin">pharo-project/threadedFFI-Plugin</a></strong></div><div>A Threaded FFI plugin for Pharo. It extends the Cog VM with non blocking queue based FFI. - pharo-project/threadedFFI-Plugin</div></blockquote>

**Comment by tinchodias** [comment]
In fact, it's partially fixed with TFFI: the returned struct of doubles has the right x y values in the test, but the functions don't. More exactly: the accessor #y answers the right Float, but #getY answers zero. Such method is defined as follows:
~~~Smalltalk
getY
	^ self ffiCall: #(double getVectDY(cpVectD self))
~~~

**Comment by tinchodias** [comment]
Oh! it seems you fixed and close it but I didn't receive notification. Will check it.

**Comment by tinchodias** [comment]
BTW, Weekly Digest closes issues without mention to the commit that fixed it? hmm

**Comment by tinchodias** [comment]
Uf, now I understand: I read the red "Closed" tag and thought that THIS issue was closed... will delete my comments...

**Comment by ronsaldo** [comment]
That looks like a problem with not following properly the System-V for x86_64 which dictates that small structures are passed splitted and passed through the vectorial SSE registers. Look for details here on documentation on how this works: https://github.com/hjl-tools/x86-psABI/wiki/X86-psABI

I guess that the TFFI solves this problem by leaving the task of dealing with ABI specific nuances like this to libffi.

<blockquote><img src="https://avatars0.githubusercontent.com/u/1072356?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/hjl-tools/x86-psABI">hjl-tools/x86-psABI</a></strong></div><div>x86 psABI download. Contribute to hjl-tools/x86-psABI development by creating an account on GitHub.</div></blockquote>

**Comment by tinchodias** [comment]
Thanks @ronsaldo. One day I should try again with TFFI, maybe it's fixed there. 

(Reported it as https://github.com/pharo-project/threadedFFI-Plugin/issues/24)

**Comment by tinchodias** [comment]
Hi! it is fixed in Pharo 10 (`curl https://get.pharo.org/64/100+vm | bash`)

**Comment by tinchodias** [comment]
It's closed now in the source project / upstream so I close it here too.
(https://github.com/pharo-project/threadedFFI-Plugin/issues/24)

**Comment by tesonep** [comment]
@tinchodias to include those tests we need to push the test code to the test library that is shipped with the VM
