### ISSUE TITLE
Large images: Setting to not check if we should show inspectors tabs

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#5717]
This is just an idea of how to improve the speed of large images. 

In Moose, there are a lot of inspector extensions and the inspector might be really long to show sometimes. Most of the time is spent to check which tabs we should show in the inspector. 

Maybe with Spec 2 inspector, we could have a setting to not compute this by default. 

In that case, all tabs would be available and if you click on a tab that should not be displayed, we display a message "Not available".

**Comment by MarcusDenker** [comment]
I think we have now removed (or fixed) all the slow inspector tabs, or not?

**Comment by VincentBlondeau** [comment]
It is ok for the Lifeware image. I let @jecisc check on Moose.

**Comment by jecisc** [comment]
Maybe Clotilde knows more about moose now

**Comment by MarcusDenker** [comment]
I think she will re-open if it is still a problem.
