### ISSUE TITLE
Athens caches are not used

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#5721]
AthensCanvas class has two caches that are unused. 

StrokePaintCache and PaintCache. 

They can be removed.

**Comment by astares** [comment]
You mean deprecated first ...

**Comment by jecisc** [comment]
They have non accessors, only variables

**Comment by MarcusDenker** [comment]
this is something similar: https://github.com/pharo-project/pharo/issues/2560

**Comment by MarcusDenker** [comment]
PaintCache seems to be used:

setPaint: aPaint
	"set the current paint of receiver"
	paint = aPaint ifTrue:[ ^ paint ].
	paint := PaintCache at: aPaint ifAbsentPut: [ aPaint asAthensPaintOn: self ].
	^ paint.

**Comment by MoussaSak** [comment]
i deleted the StrokePaintCache class variable and i kept PaintCache.

**Comment by MarcusDenker** [comment]
merged
