### ISSUE TITLE
Renaming packages leads to out of synch manifest names

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#5725]
The name of Manifest classes are created based on the package name. See #createManifestNamed: 
method implemented in TheManifestBuilder which is implemented like

```Smalltalk
createManifestNamed: packageName
	|tag|
	tag := self class manifestTag.
	manifestClass := PackageManifest subclass: (tag, packageName onlyLetters) asSymbol
			instanceVariableNames: ''
			classVariableNames: ''
			poolDictionaries: ''
			package: packageName.
	manifestClass 
		tagWith: tag;
		comment: self class manifestClassComment.
	^ manifestClass
```

now when you rename a package the class name of the manifest class is not renamed.
Also the above method only uses the letters of the package names - but we have package
names like "Spec" and "Spec2" which then might collide with the manifest class name

This can lead to 
 - the package name not being in synch with the manifest name anymore
 - collissions in manifest names as "Spec" and "Spec2" would both lead to a ManifestOfSpec
and other side effects

**Comment by astares** [comment]
Example to reproduce:

1. Create a package "Foo" with a class "Bar"

```Smalltalk
Object subclass: #Bar
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Foo'
```

2. Create a package "Foo2" with a class "Bar2"

```Smalltalk
Object subclass: #Bar2
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Foo2'
```

Now create a manifest for "Foo" package:

```Smalltalk
(TheManifestBuilder new) createManifestOf: Bar
```

which will create a **ManifestFoo** class in "Bar" package. 

If you now create a manifest for "Foo2" package
```Smalltalk
(TheManifestBuilder new) createManifestOf: Bar2
```
it will not be called **ManifestFoo2** but also **ManifestFoo**. 

So **ManifestFoo** class is now wrongly moved to Foo2 package.

**Comment by MarcusDenker** [comment]
There is https://github.com/pharo-project/pharo/issues/3604

**Comment by astares** [comment]
Yes, there is #3604 - but it is not enough. The manifest class name should not be created 
using #onlyLetters but by allowing all alphanumeric characters 

We can find out which package / manifest combinations are already out of synch using the following test method (which we could have in ReleaseTest)

```Smalltalk
"tests"
testManifestNamesAccordingToPackageNames
	"Sometimes (when renaming packages) the manifest does not get renamed accordingly. Find these cases"
	
	|manifestClasses actualManifestNames expectedManifestNames |
	manifestClasses := Smalltalk allClasses select: [:each |
							(each name beginsWith: 'Manifest') ].
	actualManifestNames := (manifestClasses collect: [:each | each name ]) sorted.
	expectedManifestNames := manifestClasses 
										collect: [:each | ('Manifest',each package name onlyLetters) 	asSymbol ].
	self assert: actualManifestNames equals: expectedManifestNames 
```

**Comment by astares** [comment]
Will care on the two remaining out of synch cases and fix this one here as well.

**Comment by astares** [comment]
But:
https://github.com/pharo-project/pharo/issues/5727 and
https://github.com/pharo-project/pharo/issues/5728 
**need to be integrated first** to fix the two remaining cases where package name and manifest name is out of synch.
