### ISSUE TITLE
Iceberg and UTF-8

### ISSUE THREAD

**Issue by David5i6** [guillep/pharo-core#5739]
When doing a commit Iceberg asked for name and email.After writing my name "David Sánchez Gregori" I get an error reading UTF-8, in the debug I saw that a Stream contain the name but in latin1 instead than in UTF-8.

I changed IceLibgitRepository#commitFromGitRepository to:

```smalltalk
"protocol: #'private-commits'"

commitFromGitCommit: aLGitCommit 
	
	^ self commitCache at: aLGitCommit id hexString ifAbsentPut: [ 
		IceGitCommit new
			id: aLGitCommit id hexString;
			author: aLGitCommit author name asByteArray asString  ;
			datetime: aLGitCommit time asDateAndTime;
			ancestorIds: (aLGitCommit parents collect: [ :parent | parent id hexString ]);
			comment: aLGitCommit message;
			repository: self;
			yourself ]
```

The change is in "author: aLGitCommit author name asByteArray asString  ;".

After this change it worked for me but I'm not sure if it will work for UTF-8 saved streams.

Perhaps decoding UTF-8 and in case of error defaultin to "asString" ?
Perhaps it should ensure when the user name and email are stored that they're stored as UTF-8 streams and not in other encodings ?

**Comment by Ducasse** [comment]
We should open an issue in the iceberg project http://github.com/pharo-vcs/iceberg

**Comment by David5i6** [comment]
Put the issue in Iceberg project.
 #1346

**Comment by Ducasse** [comment]
super tx!!!
