### ISSUE TITLE
Weird black highlighting after executing commands in Playground

### ISSUE THREAD

**Issue by myroslavarm** [guillep/pharo-core#5771]
[Pharo 9 Win 10]
after executing commands in Playground that line of code (or a whole block) become highlighted in black and it either disappears after a second or you have to click somewhere in the Playground for it to become normal again (often it also doesn't appear at all). i looked through the issues a bit, doesn't seem like it's been reported, but it's fairly annoying. I'm trying to remember, i think it's been there for the last month at least. In any case, here's a picture to better illustrate the bug:
![image](https://user-images.githubusercontent.com/24677542/75386585-3ef02480-58e2-11ea-95a4-335ee8cbb3c5.png)

**Comment by astares** [comment]
Yes - have seen this effect too. Looks like freshly introduced - I guess it is there since the last one or two weeks

**Comment by pavel-krivanek** [comment]
It seems to be introduced by the BalloonCanvas refactoring, I will try to look at it since I did it

**Comment by Ducasse** [comment]
Thanks pavel. It looks strange.

**Comment by pavel-krivanek** [comment]
Does someone know how to reproduce this issue?

**Comment by pavel-krivanek** [comment]
![Pharo_S24HtdaqrW](https://user-images.githubusercontent.com/572494/75479014-298d0000-599f-11ea-98a7-18893eda426d.png)

Halos transparency is corrupted, maybe it is related

**Comment by pavel-krivanek** [comment]
I have a way how to reproduce. The expresion needs to cause opening of a new window. So it is enough to take a fresch image, write `self` to the playground, inspect it and then close the inspector

**Comment by pavel-krivanek** [comment]
The proposed fix does not touch the halos
