### ISSUE TITLE
Settings -> Display Scale Factor changing

### ISSUE THREAD

**Issue by David5i6** [guillep/pharo-core#5779]
In the Menu "Settings" in Appearance the "Display scale Factor" is alive. It changes automatically.
This issue also happens with the "Fullscreen Margin" value.

Sometimes that happens magically when entering in the Settings, other times it happens after draggin the value selector and changing the value.

It happens on MacOSX with Pharo 8 and Pharo 9 images downloaded from the launcher and in Windows 10 an pharo 9 from git.

**Comment by David5i6** [comment]
The problem is in the Slider, The examples of Spec and Spec2 has the same problem.

I don't know too much about Spec, Spec2 or morphic, but as far I can go debugging, the problem is in the Morphic adapter.
There is a method in the parant class that updates on mouse move but I'm not sure if it's safe to verride it or the side effects of made changes on those methods (or if the problem really relies on them).

**Comment by David5i6** [comment]
Found the problen in Slider>>ScrollAbsolute, sending a pullrequest.

**Comment by Ducasse** [comment]
Thanks we will have a look.

**Comment by guillep** [comment]
I confirm the issue. Just passing the cursor over the slider causes it to move :/
