### ISSUE TITLE
Two tests of RB are broken when we switch to slot class definition

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5790]
RBRefactoringChangeTest>>testAddMetaclassPattern
And 
RBRefactoringChangeTest>>testPerformChangeMetaclass

createMockClass
	self class compiler 
		evaluate: 'Object subclass: #RBRefactoringChangeMock
	instanceVariableNames: ''instVar''
	classVariableNames: ''ClassVar''
	poolDictionaries: ''''
	category: ''Refactoring-Tests-Changes'''.
	
	self class compiler 
		evaluate:  'RBRefactoringChangeMock class
	instanceVariableNames: ''classInstVar'''.
	
	self changeMock compile: 'one ^ 1' classified: 'accessing'.

**Comment by MarcusDenker** [comment]
- RBRefactoringChangeTest>>testAddMetaclassPattern is now green with Fluid
- RBRefactoringChangeTest>>testPerformChangeMetaclass has "self skip" and fails for both Fluid and non-fluid when run

So this PR can be closed (not a fluid problem)
