### ISSUE TITLE
Executable comments checker (in drTest) does not run executable comments on an abstract class

### ISSUE THREAD

**Issue by bergel** [guillep/pharo-core#5804]
We tried to add some executable comments in `SequentiableCollection`, but we were surprised that comments are not executed. A plausible reason is that `SequentiableCollection` is abstract, so, DrTest does not execute them. 
Although not executing tests in an abstract class does make sense, for executable comments, it does make sense.

**Comment by MarcusDenker** [comment]
This is fixed

**Comment by bergel** [comment]
Thanks!
