### ISSUE TITLE
parser's AST missing comments

### ISSUE THREAD

**Issue by j-brant** [guillep/pharo-core#5817]
If you parse an expression that is just a comment, the returned AST does not have any comments. For example, this should return 1, but returns 0 instead:
```
| commentCount |
commentCount := 0.
(RBParser parseExpression: '"comment"') nodesDo: [ :each | commentCount := commentCount + each comments size ].
commentCount
```
Adding any expression to the parsed string will result in the commentCount > 0.

**Comment by lesueur-philippe** [comment]
Hi the problem is that during the scan of the string, since there are no concrete token, the only one created is the EOFToken. Therefor the comment is stored inside it. The problem was that there was no extraction of the comments on this token.
The fix will be up along with my work on the parser.

**Comment by MarcusDenker** [comment]
I have checked it in Pharo9: it is now working correctly!
