### ISSUE TITLE
SystemBrowser UML doesn't work

### ISSUE THREAD

**Issue by David5i6** [guillep/pharo-core#5836]
On Pharo 9, System Browser has an UML View that doesn't work until I install Roassal.

Some methots must be dependent of Roassal or some extension provided by that package.

**Comment by astares** [comment]
The uml view is provided by Roassal 3. So it mußt be loaded to be available in the calypso System Browser. This is not a Bug.

**Comment by David5i6** [comment]
Sorry, I didn't explained well.
The problem is that the UML view is shown but with an error content (red screen) because Roassal is not installed.

After testing again with clean images I saw that the tab doesn't show, I tryied a couple of times to reproduce that and it seems that is a problem with package management/installation.

Under some circunstances the installation of roassal gives an error and seeem that the UML view is registered but some needed clases not.

Currently there're other issues about package load and unload so I will close this and coment on those.

Thank for your help !
