### ISSUE TITLE
PharoLauncher showing Pharo 9 - but not each detailed built image

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#5841]
in the PharoLauncher tree one can download the latest Pharo 9 (32 or 64 bit) from the "Official distributions" node.

But not at the bottom nodes where the tree can be opened and where one can download each built image separately. 

So it is currently not possible to lets say download the Pharo 9 image from today and the Pharo 9 image from last week to compare.

This one often helped in the past when one wants to try out in which image an error was introduced.

![image](https://user-images.githubusercontent.com/5980033/75915154-4b322f80-5e56-11ea-96ab-1dc40248482d.png)

I guess it is a problem of the Pharo Launcher templates (downloaded when clicking on refresh) and need to be fixed there.

**Comment by Ducasse** [comment]
Hi torsten can you open an issue in the the launcher? Because I will close this one.
