### ISSUE TITLE
Cannot extract method with arguments

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#5855]
Extracting a method, I specify a keyword selector.
1. it is not clear if we should add the argument in the selector or in the list
2. it is not clear if the argument list should contain 
   1. argument names for the extracted method,
   2. or expressions for the replaced expression 

Trying to add the argument name for the extracted method (case 2.i) fails telling it is an invalid selector but it is not clear why
![image](https://user-images.githubusercontent.com/708322/75973761-0352ed00-5ed6-11ea-8f18-7a52102cfea9.png)

Trying to add an expression (case 2.ii) fails but it is not clear why
![image](https://user-images.githubusercontent.com/708322/75973068-de11af00-5ed4-11ea-9b27-a06784fc2dd7.png)

**Comment by StevenCostiou** [comment]
1 - The `(invalid)` name is generated by RBMethod when the selector and the arguments do not match. The "checking" is done by asking the name of the method and then testing if it is equal to `(invalid)`
- Testing on the string to tell the status of the renaming is not nice => open another issue
- The `(invalid)` status tells nothing => open another issue

2 - I believe that `Edit` refers to editing the name of the selected parameter, and not adding parameter. 
- It's not immediate to say because it's untested :)
- Why not having a field to add a parameter?

For this issue I'll work on point 2.

**Comment by StevenCostiou** [comment]
Ok so, in fact not that simple to add a parameter while refactoring if it does not exist as a temp in the original selection. Maybe it could be replaced with nil by default in that case?

**Comment by StevenCostiou** [comment]
Ok it's working, but maybe adding parameters means we should be able to remove them?
Also, does not solve the problem of the unclear selector text input: with or without the args?

**Comment by guillep** [comment]
After seeing the comments and the code, I'm pretty convinced that this is a UI issue.
The `SycMethodNameEditor` does not allow one to add new selector parts or arguments, just edit the ones that are there. So it is misleading
 - to let the user use the text input to edit an argument that cannot be inserted/modified (that is already fixed in https://github.com/pharo-project/pharo/pull/6219 by disabling the button and the input field).
 - to let the user change the selector as if it was a string

=> I agree that changing the selector is the better and simpler UI, but this means that it should be managed well :)

I'll think about it while coffee prepares

**Comment by StevenCostiou** [comment]
In what I started, I added a field with an explicit "add argument" field, but it becomes a bit tedious to handle that with the adding directly in the selector

**Comment by StevenCostiou** [comment]
I'm trying to find it just to show you the ui but I can't seem to find the image :/

**Comment by guillep** [comment]
I'm working on a simpler widget like this:

![method-signature-editorv2](https://user-images.githubusercontent.com/708322/80219496-d8b62280-8642-11ea-885f-bc3178edc3e1.gif)

Where you'll be able to write the entire method signature and the widget will extract the correct things for you. This could be combined with the list of arguments, but I think this thing makes it much more understandable. (Still I have to see how to make the columns aling well in spec :)

**Comment by StevenCostiou** [comment]
Ok I found it back:
![Screenshot 2020-04-24 at 15 54 23](https://user-images.githubusercontent.com/26929529/80220345-f46df880-8643-11ea-8294-399106321878.png)

But yours seems better if it works.

**Comment by guillep** [comment]
I'm finding bugs in the parser, so it's not so evident to make it work :)

**Comment by Lin777** [comment]
Hi @guillep, I'm not sure if this is the behavior you expect. 

The method extraction works like this, it calculates the necessary parameters to extract the method, it calls the image rename view where you must enter a selector with the amount of parameters that are shown in the view.

For example in the following view you must enter the name of a method with only one parameter, this parameter can be renamed, but you can not add or remove parameters.

<img width="598" alt="imagen" src="https://user-images.githubusercontent.com/15729309/116855755-eabc9080-abc7-11eb-90a2-1e8060e7fa4c.png">
