### ISSUE TITLE
Printing an exception should not rely on the AST

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#5879]
These methods are added later in Pharo, they should not be used to just print an exception

**Comment by Ducasse** [comment]
Yes for a layered architecture

**Comment by guillep** [comment]
Thanks Pablo :)

Le jeu. 12 mars 2020 à 08:07, StéphaneDucasse <notifications@github.com> a
écrit :

**Comment by MarcusDenker** [comment]
I can help too... in general I should do an analysis of the use of the AST... it is far too ad-hoc and very easy to break layers.

**Comment by Ducasse** [comment]
What is the status of this issue?

**Comment by MarcusDenker** [comment]
I am on it. It is not that simple to solve...
