### ISSUE TITLE
[P8/P9] Iceberg duplicates project entry when using Metacello -> Install baseline of 

### ISSUE THREAD

**Issue by gcotelli** [guillep/pharo-core#5881]
Pharo 8.0.0
Build information: Pharo-8.0.0+build.1131.sha.33cef37d88e65f958dfe097747c87c906a87f302 (64 Bit)

When you try to install a project using the contextual menu option Metacello --> Install baseline of... over an already cloned project, the repository ends up being duplicated in Iceberg: 

![Iceberg Project Duplication](https://user-images.githubusercontent.com/2106744/76426995-8965ac80-638a-11ea-8e86-8e5070a65d3c.gif)

**Comment by bouraqadi** [comment]
I get the same annoying duplication for other projects also when I attempt to load from the playground
```
Metacello new
  baseline: '...';
  repository: 'github...';
  load.
```

**Comment by agiaccone** [comment]
I've had the same problem. It happens repeatedly when loading the OpenAPI project.

**Comment by Ducasse** [comment]
Hi thanks for the report. Did you check if this is fixed in P9?

**Comment by bouraqadi** [comment]
I did not check P9. 
But, for sure there's a regression here compared to P7.

Noury

**Comment by gcotelli** [comment]
It is not fixed in P9. I've just checked:
Pharo 9.0.0
Build information: Pharo-9.0.0+build.583.sha.ebc40dc3dc449ba669a5efb65d1ff426f0f1dc8a (64 Bit)
also produces the problem

**Comment by gcotelli** [comment]
Looks fixed in Pharo 11
