### ISSUE TITLE
Changing superclass rises nonsense exception

### ISSUE THREAD

**Issue by sbragagnolo** [guillep/pharo-core#5885]
So, some days ago we seem to have added a check for not getting out a variable.
These seems like a good idea, but the implementation is quite unfortunate. 
1- If i take out a used variable and try to compile the class definition, it informs "Undeclared variable in class definition" In this context, this error is kind of understandable, but is not really helpfull. I think that we could do way better than this (By example, as when we delete a used method). I rather prefer to have the former behaviour than this new behaviour. 

2- When we change the super class of our class, and this class is using a superclass variable, we have exactly the same inform "Undeclared variable in class definition"  In this context, this message is not only useless but confusing. It does not give anyhint on how to solve the problem (and we are in pharo, we have all the needed information in this point for doing way better than this).

I have no clue what is the issue/ feature that pushed this change, but I think that it should be rollback if it is not a blocking issue, and re designed.

**Comment by sbragagnolo** [comment]
@Ducasse @MarcusDenker @estebanlm @tesonep @guillep clues?

**Comment by MarcusDenker** [comment]
I will look... I know which change it is, I will revert it.

**Comment by MarcusDenker** [comment]
I tried to fix this using this PR: https://github.com/pharo-project/pharo/pull/5825

Can you check if your image has that already?

**Comment by Ducasse** [comment]
sbragagnolo can you answer to marcus?

**Comment by MarcusDenker** [comment]
This seems to be fixed, I could not reproduce it in Pharo9
