### ISSUE TITLE
Running -headless does not work on Ubuntu 14.04 (Pharo 8)

### ISSUE THREAD

**Issue by MaximusWhite** [guillep/pharo-core#5888]
I am trying to automate running some .st script in multiple images and save the outputs to corresponding files. 
For some reason, when I run Pharo using -headless flag, it still creates a new window. It's just an empty window with a white background, which cannot be closed using (X) button, I have to manually CTRL+C in the terminal to close it.

**Comment by svenvc** [comment]
Hmm:
````
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
$ mkdir tmp/pharo
$ cd !$
cd tmp/pharo
$ curl get.pharo.org/64/80+vm | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3054  100  3054    0     0  41835      0 --:--:-- --:--:-- --:--:-- 41835
Downloading the latest 80 Image:
    http://files.pharo.org/get-files/80/pharo64.zip
Pharo.image
Downloading the latest pharoVM:
	http://files.pharo.org/get-files/80/pharo64-linux-stable.zip
pharo-vm/pharo
Creating starter scripts pharo and pharo-ui
$ ./pharo Pharo.image printVersion
[version] 'Pharo8.0.0' 'Pharo-8.0.0+build.1131.sha.33cef37d88e65f958dfe097747c87c906a87f302 (64 Bit)'
$ ./pharo Pharo.image eval 42 factorial
1405006117752879898543142606244511569936384000000000
````
Works fine (as it has allows worked) for me.

**Comment by MaximusWhite** [comment]
@svenvc Hi there, thank you very much for quick reply. 
I reproduced your steps and that seems to be working. However, in my case I am not trying to use "eval", I am using "st" option to run my script. 
My command is the following: 
`./pharo Pharo.image -headless st MyScript.st`
Once executed, it displays expected output in stdout, BUT if I am doing it one the physical machine it opens up and empty window. 
And if I run the command over ssh, it also produces expected output, but then just hangs until I terminate using CTRL+C. 
Not sure why exactly that's happening. Is there some other/better way to do headless execution? 

UPD: Huh... I think I solved it by using `-quit` flag instead of `-headless`.
Not sure why that option is not listed in `pharo -info`.

**Comment by svenvc** [comment]
There are two scripts: pharo and pharo-ui. The first one never starts a UI. The last one does not need the -headless option.
```
$ cat test.st 
NonInteractiveTranscript stdout install.

Transcript logCr: ('42 factorial = {1}' format: { 42 factorial }).

$ ./pharo Pharo.image st --quit test.st 
42 factorial = 1405006117752879898543142606244511569936384000000000
```
Of course, it might also depend on what you do in your script.

**Comment by MaximusWhite** [comment]
Somehow for me the plain `pharo` script does start a UI, unless I run it with `-quit` flag.

**Comment by svenvc** [comment]
Can't you share what is in your script ? Or a minimal version of it that has the same effect ?

**Comment by MaximusWhite** [comment]
Sure. This is essentially it (I removed items from the arrays, since this is a tester used to mark students and I don't want to expose actual test cases.)
```
| youSaid shouldBe perms ans sum poker ex desc p1 a1 h1 h2 nShuf|

perms := #( #(1 1 1 1 1 1 1 1 1 1)  ). 
               
ans := #( #('1C' '1C' '1C' '1C' '1C') ).

Transcript clear.
sum := 0.
nShuf := 2.

1 to: (perms size) do: [ :p | 
    
    a1 := (ans at: p).
    
    1 to: nShuf do: [ :r |
    
        ex := false.
        poker := Poker new.
        p1 := (perms at: p).  
        h1 := {(p1 at: 1).(p1 at: 3).(p1 at: 5).(p1 at: 7).(p1 at: 9)} shuffled.
        h2 := {(p1 at: 2).(p1 at: 4).(p1 at: 6).(p1 at: 8).(p1 at: 10)} shuffled.
        p1 := {(h1 at: 1).(h2 at: 1).(h1 at: 2).(h2 at: 2).(h1 at: 3)
               .(h2 at: 3).(h1 at: 4).(h2 at: 4).(h1 at: 5).(h2 at: 5)}. 
        
        [ youSaid := poker deal: p1 ] on: Exception do: [ :e | ex := true. desc := e description].
        ex 
        ifFalse: [
            [ youSaid := youSaid asSortedCollection asArray ] on: Exception do: [ :e | ex := true. desc := e description].
            ex 
            ifFalse: [
                shouldBe := a1 asSortedCollection asArray.
                
                (youSaid = shouldBe) 
                ifTrue: [ 
                    Transcript show: 'Test '; show: p; show: '.'; show: r; show: ' PASSED'; cr.
                    sum := sum + 1.	
                ] 
                ifFalse: [ 
                    Transcript show: 'Test '; show: p; show: ' FAILED: '; show: p1; cr.	
                ].
            ]
        ]
        ifTrue: [
            Transcript show: 'Test '; show: p; show: ' FAILED'; cr.	
            Transcript show: 'Exception: '; show: desc; cr.	
        ]
    ]
].
Transcript show: 'Passed '; show: sum; show: '/'; show: (perms size * nShuf); show: ' tests.'; cr.
```

**Comment by svenvc** [comment]
I can't run this since I don't have the Poker class.

**Comment by bencoman** [comment]
@MaximusWhite You might edit your example to add a sample definition of Poker & methods, like this...
```
| youSaid shouldBe perms ans sum poker ex desc p1 a1 h1 h2 nShuf|

Object subclass: #Poker
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Example'

Poker compile: '
deal: anObject
    "Fill in enough of what I do"
`

perms := #( #(1 1 1 1 1 1 1 1 1 1)  ). 
```

**Comment by LucFabresse** [comment]
Executing the following command: 
```
pharo --headless Pharo.image st --quit script.st 
```
the PharoVM (version 100-x64) correctly executes `script.st` in headless mode and then quits.

we can close this old bug.

**Comment by Ducasse** [comment]
Thanks luc.
