### ISSUE TITLE
ZnHTTPSTest >> testGetPharoVersion is failing because is using a Jenkins that is Down

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#5899]
This test is using a Jenkins server that is down, it is the Pharo6 server. 
Maybe we can update it to use the new CI

**Comment by svenvc** [comment]
yes this is annoying.
this is actually an old regression test for a problem that once existed.
but the target URL has to move regularly.
maybe we should just drop the test ?

**Comment by tesonep** [comment]
I will rather keep the test, I am creating a PR to move the URL.
The issue was not to forget.
