### ISSUE TITLE
Convert  Processor yield into self yieldProcess

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5903]
Now that yieldProcess is defined in Object we can convert all the hard Processor yield by self yieldProcess

**Comment by Ducasse** [comment]
Guille I'm thinking that we should revert the introduction of yieldProcess. 
I looked at all the Processor references and many of them are to be able to access a priority or the active process so my suggestion just makes the systeme is bit more awkwark.
Tell me what you think.

**Comment by guillep** [comment]
Ok, let's close this one then.
