### ISSUE TITLE
Issue with Monticello in clean Pharo 8 image

### ISSUE THREAD

**Issue by aebutcher** [guillep/pharo-core#5906]
Hello, beginner here. I could not find this problem reported anywhere else, please forgive me if has already been reported.
I'm running MacOS Catalina 64bit.  Working from a clean Pharo 8 image.
When trying to save a package to a local repository, an error occurs while typing in Monticello's Log Message dialog.  It happens while typing.  If I close the error, and try to save, it does not save.
What I have been doing is typing my log message into a Playground window, copying that and pasting into the Log Message dialog, then saving, which is successful.
I have attached a screenshot of the error.
I raised this issue in the Pharo Discord MOOC server, and was advised to report it here. I don't know if this is a bug or just an issue on my computer?
![Screenshot 2020-03-16 at 11 39 28](https://user-images.githubusercontent.com/57952051/76745010-ce6c5300-677d-11ea-8c3f-83f3d4789f6f.png)

**Comment by Ducasse** [comment]
Thanks for the report. This is strange we will have a look. 
Can you tell us what you did exactly? You save using the Monticello browser?

**Comment by aebutcher** [comment]
Yes, I save to a local repository using Monticello, and the error seems to arise only while I am trying to type a log message.

**Comment by bpieber** [comment]
I just ran into the same issue with a new image created by Pharo Launcher from template Pharo 8.0 - 64bit (stable).

**Comment by crunsk** [comment]
I also got the same error message "MCSaveVersionDialog did not understand #selectedClassOrMetaClass" when I typed letters 't' and 'e'.
![example](https://user-images.githubusercontent.com/5631441/82759162-3da49a00-9df4-11ea-89f9-696c7360146d.png)
 to the save dialog.

I am running:
Windows 10 64-bit.
Pharo Launcher version: 2.0
Pharo image was created from 'Official distributions' template category Pharo 8.0 - 64bit (stable) 
After the image was created the 'Origin template' is 
Pharo 8.0 - 64bit (stable) 
(https://files.pharo.org/image/80/stable-64.zip)
![pharo_monticello_image](https://user-images.githubusercontent.com/5631441/82759088-8b6cd280-9df3-11ea-95d2-3b565f813f78.png)

<blockquote></blockquote>

**Comment by PeterDNewton** [comment]
I have also encountered this problem and advised to report it here. As far as I can tell the issue doesn't exists in Pharo 7, was introduced in Pharo 8 and still exists in Pharo 9 (all tested on Mac OS 10.12.6). It's related to how autocomplete now works.

**Comment by MarcusDenker** [comment]
I do not get this in Pharo9 as downloaded from http://files.pharo.org/image/90/latest-64.zip

<blockquote></blockquote>

**Comment by MarcusDenker** [comment]
as there is no other comment, I guess this is fixed.
