### ISSUE TITLE
What about moving Tests-Traits and Traits-MOP into TraitsV2-Tests

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5909]
What about moving Tests-Traits and Traits-MOP into TraitsV2-Tests?

**Comment by MarcusDenker** [comment]
take care: Tests-Traits has traits that iceberg (git) has problems with. If you move them, they are not correctly added to the new package (or something like that)

**Comment by MarcusDenker** [comment]
this is done
