### ISSUE TITLE
About category in subclass:uses:....

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5910]
Hi Pablo

A while ago I started to clean and remove all the category references, in messages. 
I think that I kept hidden deep inside. 
And now I see that the interface of TraitsV2 reintroduce them. 
Could we rename them?

subclass: aTraitName uses: aTraitCompositionOrArray instanceVariableNames: instVarNameList classVariableNames: classVarNames category: cat 

	^ self
		subclass: aTraitName
		uses: aTraitCompositionOrArray
		instanceVariableNames: instVarNameList
		classVariableNames: classVarNames
		poolDictionaries: ''
		category: cat

**Comment by jecisc** [comment]
This method is not in the image anymore
