### ISSUE TITLE
Refactor `Rectangle>>fromUser`

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#5919]
`Rectangle >> fromUser` freezes the display to let the user select a rectangle from the screen (drawing the selection in between). Then it returns a rectangle instance with the size selected.

This functionality does not belong to the Rectangle class, It generates a rectangle, but that does not mean it should be in the rectangle class. It should be extracted.

**Comment by guillep** [comment]
- `Rectangle>>newRectFrom:`
- `Rectangle>>newRectButtonPressedDo:`

should be included in the refactoring too. Those are the methods that access the world and override event handling. They do not belong in `Rectangle`

**Comment by Ducasse** [comment]
I hate so much methods named newRectFrom: may be it was newRectumFrom: :(
I do not get why a couple of characters more would cost so much
We should renamed them

**Comment by Ducasse** [comment]
back to bed freezing - hoping tomorrow will get better.
