### ISSUE TITLE
ScrollBars don't drag with mouse

### ISSUE THREAD

**Issue by David5i6** [guillep/pharo-core#5924]
Scrollbars don't drag when using mouse.
This bug is related with my fix for the slider.

I'm going to make a pullrequest with this fix.

Also the useShadow option is checked in code but UITheme alwas return false.
I made a little change in UITheme to let users customize this behaivor.

**Comment by guillep** [comment]
Thanks for catching it fast. I was experiencing it today and was not sure of the reason.
