### ISSUE TITLE
Remove Text-Edition package

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5936]
Because now it is duplicated of Rubric and we are nearly there to remove it with the pluggable text morph and friends.

**Comment by Ducasse** [comment]
But PluggableListMorph is still used.

**Comment by guillep** [comment]
This is related to https://github.com/pharo-project/pharo/pull/5020
But I don't get @jecisc to answer me :)

**Comment by MarcusDenker** [comment]
This is a duplicate of https://github.com/pharo-project/pharo/issues/2717
(cleaning up text editor)
