### ISSUE TITLE
Opening of Iceberg settings causes DNU: #preferredCornerStyle

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#5939]
open Iceberg, click on Settings button (or find Iceberg settings in the Settings browser)

Instance of PickOneSettingDeclaration did not understand #preferredCornerStyle

**Comment by myroslavarm** [comment]
I get this error if i try to click or find anything in the Settings browser, not just Iceberg.

**Comment by pavel-krivanek** [comment]
seems to be fixed now

**Comment by guillep** [comment]
This is a duplicate of #5947.
I'll check why this was fixed because there was no related PR to my knowledge.
Maybe somebody's (mine?) workaround slipped in
