### ISSUE TITLE
Spotter: cannot browse effectively implementors

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#5944]
I often know part of a method name but not the full name. To find the method I open Spotter and type what I know.

I think it was possible before to have a minimal list of results, then click on the arrow next to "Implementors" category and then have a full list. 

In Pharo 8 the list is only 5 results long, which is really not helpful.

**Comment by Ducasse** [comment]
did you check the preferences?

**Comment by jecisc** [comment]
I only have two unchecked settings for spotter: world menu and renraku rules.

**Comment by MarcusDenker** [comment]
this should now work
