### ISSUE TITLE
Endless creation of UI windows

### ISSUE THREAD

**Issue by myroslavarm** [guillep/pharo-core#5945]
In the latest Pharo 9 since at least yesterday afternoon if you try to change a method protocol and you get a window to select the name you want, you start getting the same window for every click you do, whereas it's for 'ok', 'cancel', or any click anywhere in the image. And no way to get rid of them!

![image](https://user-images.githubusercontent.com/24677542/77168253-cf6fee00-6ab7-11ea-8f54-329abd634a01.png)

I assume this is Spec related @guillep

**Comment by guillep** [comment]
> I assume this is Spec related @guillep

Wrong assumption, this has nothing to do with Spec :)

I cannot reproduce it. Can you give more details?

What I did:
 - took latest image
 - I created a new package
 - I created a class in it
 - I created a method in it (as yet unclassified)
 - I clicked on the protocol => cmd + R 

Then clicking on OK, cancel or Browse works correctly.

I then repeated the same but from the button in the bottom of the window.

![image](https://user-images.githubusercontent.com/708322/77170217-01368400-6abb-11ea-971d-ff2deb551e96.png)

It worked again.

I then tried to change the method protocol by doing "Classify methods" from the method.
It worked again.

I then tried to rename the protocol by doing. Right click -> rename. On the protocol (note, without shortcut).
Worked again.

I need more details...

**Comment by myroslavarm** [comment]
I always change the protocol by clicking on:
![image](https://user-images.githubusercontent.com/24677542/77171152-51faac80-6abc-11ea-99f6-4174036a7d29.png)
and when the selection pops up, i choose a name from the list, and the UI window starts multiplying after every click after. It is the same even as i created a new package, class, method and tried to classify a newly created method.

P.S. i don't know if it might influence something, but i'm using windows :)

**Comment by myroslavarm** [comment]
I don't think this was happening yesterday in the early afternoon,
but in the evening it was for sure there.

**Comment by guillep** [comment]
What commit is your image built ?

Please, issue reports should at least contain:
 - pharo version (+ commit)
 - platform
 - how to reproduce
 - extra information that could be useful

:(

**Comment by myroslavarm** [comment]
pharo 9 64 bit, build: 171, commit: 1b24cb3
windows 10

everything about reproducing is already in there

**Comment by guillep** [comment]
I'm on the same commit

Pharo 9.0.0
Build information: Pharo-9.0.0+build.171.sha.1b24cb39f45f8659fa6c435d7ffc52144c8e7ad2 (64 Bit)

Still not able to reproduce it.
If someone has more info, It'll be appretiated :)

**Comment by guillep** [comment]
Ok I was finally able to reproduce it.
It turns out that when "renaming" I was typing things in the entry field for the name.
If you enter something, it does not loop.

However, as soon as you don't type something and leave the entry field with the default value, it opens again.
I'll check it later.

For the moment: workaround => type something in the input box.

**Comment by guillep** [comment]
I'm working on it now

**Comment by myroslavarm** [comment]
woohoo !!

**Comment by guillep** [comment]
I was logging my info in a wrong issue. I'll put it here.

1. Some more input. From the message browser (senders/implementors) this seems to work correctly. So the it is something related to Calypso browser itself.

2. I checked the stacks from the two cases above and they seem similar.

3. Also, I've noticed that changing protocol and changing package seem to work differently => although both seem to do the same, one has the bug the other does not.

![image](https://user-images.githubusercontent.com/708322/77306749-64f9c080-6cf8-11ea-9c9b-c52cdc2d9215.png)

4. Seems both do different things :(. Package selection is implemented from scratch repeating all the logic from the other one...

5. It seems also that clicking on the Edit button (the little pencil) works well. While clicking on the label, creates the problem.

This seems to boil down to a problem managing the events.

@myroslavarm could you help me confirming my assumptions?

clicking on the "Extension" checkbox works well
clicking on the pencil to edit the protocol works well
clicking on the label to edit the protocol generates the issue

6. Input from @myroslavarm 

>@guillep yes, i confirm it's exactly the same, it only breaks when clicking the label itself.

**Comment by guillep** [comment]
Ok I've found the different stacks.

- Clicking on the label:
```
ClyQueryBrowserContext(ClySystemBrowserContext)>>requestSingleMethodTag:suggesting: ClyMethodTagsAndPackageEditorMorph>>requestTag [
		self isExtensionActive 
			ifTrue: [ self requestPackage]
			ifFalse: [ self requestTag ]
	] in ClyMethodTagsAndPackageEditorMorph>>openEditor
BlockClosure>>on:do:
ClyMethodTagsAndPackageEditorMorph>>requestChangeBy:
ClyMethodTagsAndPackageEditorMorph>>openEditor
MorphEventSubscription>>notify:from: [ :s | result := result | ((s notify: anEvent from: sourceMorph) == true) ] in MorphicEventHandler>>notifyMorphsOfEvent:ofType:from: Set>>do: MorphicEventHandler>>notifyMorphsOfEvent:ofType:from:
MorphicEventHandler>>click:fromMorph:
LabelMorph(Morph)>>click:
MouseClickState>>click
MouseClickState>>handleEvent:from:
HandMorph>>handleEvent:
```

- Clicking on the button

```
ClyQueryBrowserContext(ClySystemBrowserContext)>>requestSingleMethodTag:suggesting: ClyMethodTagsAndPackageEditorMorph>>requestTag [
		self isExtensionActive 
			ifTrue: [ self requestPackage]
			ifFalse: [ self requestTag ]
	] in ClyMethodTagsAndPackageEditorMorph>>openEditor
BlockClosure>>on:do:
ClyMethodTagsAndPackageEditorMorph>>requestChangeBy:
ClyMethodTagsAndPackageEditorMorph>>openEditor
[target perform: actionSelector withArguments: arguments] in IconicButton(SimpleButtonMorph)>>doButtonAction
BlockClosure>>ensure:
CursorWithMask(Cursor)>>showWhile:
IconicButton(SimpleButtonMorph)>>doButtonAction
IconicButton(SimpleButtonMorph)>>mouseUp:
IconicButton(Morph)>>handleMouseUp:
MouseButtonEvent>>sentTo:
IconicButton(Morph)>>handleEvent:
IconicButton(Morph)>>handleFocusEvent: [
		result := focusHolder handleFocusEvent: 
			(anEvent transformedBy: (focusHolder transformedFrom: self)).
	] in HandMorph>>sendFocusEvent:to:clear:
BlockClosure>>on:do:
WorldMorph>>becomeActiveDuring:
HandMorph>>sendFocusEvent:to:clear:
HandMorph>>sendEvent:focus:clear:
HandMorph>>sendMouseEvent:
HandMorph>>handleEvent:
MouseClickState>>handleEvent:from:
HandMorph>>handleEvent:
```

The first one is messing with focus and event handling in general. When using modals.
The hand is actually stateful! It keeps state of the "clicking" to identify things like double clicks.
The thing is *seemingly* that in the problematic case, invoking the modal window does not cleanup the state of the hand (and the other one yes? I have to check that) and the same event gets sent again and again and again (Thus opening the same modal again and again and again).

@StevenCostiou @dupriezt maybe you're interested on my analysis and reproducing it with some cool tool :).

**Comment by guillep** [comment]
My final analysis, with associated fix in PR.

The hand (which is the event dispatcher) handles some internal state to capture clicks and double clicks.
That state should be coherent every time an event is dispatched. Otherwise, an error in the dispatched could provoke a malfunction of the hand.

#handleEvent: should be done before #click.
#handleEvent: does not only handle the event but also makes sure that the state of the hand is correct before handling the event.
Like this, both events handled in #handleMouseDown/Up: and #click do not break the event dispatcher if they, for example, block in a modal window.
