### ISSUE TITLE
PharoEnvironmentHelp outdated

### ISSUE THREAD

**Issue by dvtomas** [guillep/pharo-core#5952]
There's a lot of outdated information in the PharoEnvironmentHelp class comment (propagated to #wikiStyleHelp). A review would be nice to avoid confusing users.

**Comment by oliveiraallex** [comment]
https://github.com/pharo-project/pharo/pull/6225

**Comment by CafeKrem** [comment]
why this issue is still open when there is a PR merged ?  
is there some work to do? it's a bit confusing

**Comment by MarcusDenker** [comment]
if there is a "fixes #number" in the PR, the issue gets closed automatically. If not, it has to be closed manually. 

I will close this.
