### ISSUE TITLE
Wrong format of DoubleWordArray

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#5956]
Report from discord

> I investigated a bit more, and found that it is not a VM bug but the
> lack of support for variable double word classes in Pharo images.
> So, primitive 61 will fail not because of a VM bug but because the
> receiver, a DoubleWordArray is not a variable double word subclass but a
> variable word subclass in Pharo. So, it has 32-bit fields instead of
> 64-bit fields. Shame...

**To Reproduce**

Evaluate
```smalltalk
{ 1 << 32 } as: DoubleWordArray
```

**Expected behavior**
A double word array with a single element of value (1<<32)

**Version information (please complete the following information, you can get it from Help->about):**

I think this applies to all 64 bit images we have up to today.

**Comment by guillep** [comment]
We should check class layouts correspond in the `DoubleWordArray` class

**Comment by svenvc** [comment]
Here is a changeset by leves@caesar.elte.hu that is relevant, though it also contains other changes (I believe we renamed digitAt and friends).

So, this needs to be checked.

He writes:

> I've attached a changeset. If you load it before the Cryptography packages, CryptographyHashing will work in Pharo 8 and in the current Pharo 9 alpha. Some tests will fail, because random strings are generated with the Random class, which is different in Squeak and Pharo but still,
everything will work.

[Pharo-DoubleWordArray-patch.cs.txt](https://github.com/pharo-project/pharo/files/4397695/Pharo-DoubleWordArray-patch.cs.txt)

The last 3 changes are the relevant ones, I think.

**Comment by MarcusDenker** [comment]
I merged the image level changes, but it is not completely solved yet: I could not change the layout of the classes as they could not be loaded from git with the changed layout. I reopen this issue for this next step.

(I need to check what exactly fails)

**Comment by MarcusDenker** [comment]
(The changes in the image are only those related to create variableDoubleWordSubclass and variableDoubleByteSubclass)

**Comment by MarcusDenker** [comment]
This has been fixed!
