### ISSUE TITLE
Drag and drop a method leads to DNU shiftPressed sent to nil

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5958]
**Describe the bug**
Drag and drop a method leads to DNU shiftPressed sent to nil
Dragging a method to a different protocol. 

![Screenshot 2020-03-22 at 10 59 37](https://user-images.githubusercontent.com/432549/77246929-33b3be80-6c2c-11ea-8426-6733da7d43d0.png)

**Version information**
 - Pharo 90
 - Commit info Pharo 9.0.0
Build information: Pharo-9.0.0+build.173.sha.c97646c61233fdcf1c691bfef84b97133865fedb (64 Bit)

**Additional context**
```
withPassenger: anObject from: source hand: dragHand
	| hand |
	
	hand := dragHand.
	
	^ self new
		passenger: anObject;
		source: source;
		"If the client hasn't provided a hand use the currently active hand"
		dragHand: hand;
		shouldCopy: hand shiftPressed;
                                     ^^^^^^^^^^^^^^^^^^^^^^
		position: source positionInWorld;
		yourself

Guille this may be related to some hand cleaning?

**Comment by Ducasse** [comment]
I'm not sure that my fix is correct
```
withPassenger: anObject from: source hand: dragHand
	| hand |
	
	hand := dragHand.
	
	^ self new
		passenger: anObject;
		source: source;
		"If the client hasn't provided a hand use the currently active hand"
		dragHand: source window activeHand;
		shouldCopy: source window activeHand shiftPressed;
		position: source positionInWorld;
		yourself

**Comment by guillep** [comment]
> ![Screenshot 2020-03-22 at 10 59 37](https://user-images.githubusercontent.com/432549/77246929-33b3be80-6c2c-11ea-8426-6733da7d43d0.png)

Is it me or the "Class" and "Context" columns are shifted by one?
Look at this line: it is super misleading:

![image](https://user-images.githubusercontent.com/708322/77298723-a3d54980-6ceb-11ea-866b-e81bd369cdbd.png)

It would seem we are executing `TransferMorph>>withPassenger:from:` but the context is not in that class. To get the real context we get to look to the context above:

![image](https://user-images.githubusercontent.com/708322/77298825-cbc4ad00-6ceb-11ea-81af-0773b63edb24.png)

I just wasted 3 minutes trying to descipher how to read a stack trace...

**Comment by guillep** [comment]
Ok I found the cause.

Before we had:

```smalltalk
TransformMorph class >> withPassenger: anObject from: source [
	^self withPassenger: anObject from: source hand: nil
]

TransformMorph class >> withPassenger: anObject from: source  hand: dragHand [
        hand := (dragHand ifNil:[ ActiveHand ]).
	
	^ self new
		passenger: anObject;
		source: source;
		"If the client hasn't provided a hand use the currently active hand"
		dragHand: hand;
		shouldCopy: hand shiftPressed;
		position: source positionInWorld;
		yourself
]
```

Notice the  `hand := (dragHand ifNil:[ ActiveHand ])` which I happened to change to:

```smalltalk
TransferMorph class >> withPassenger: anObject from: source hand: dragHand [
	| hand |
	
	hand := dragHand.
	
	^ self new
		passenger: anObject;
		source: source;
		"If the client hasn't provided a hand use the currently active hand"
		dragHand: hand;
		shouldCopy: hand shiftPressed;
		position: source positionInWorld;
		yourself
]
```

I think a better solution is to do
```smalltalk
TransformMorph class >> withPassenger: anObject from: source [
	^self withPassenger: anObject from: source hand: source currentHand
]
```

I'm working on it
