### ISSUE TITLE
Adjust CallbackForWin64X64 class >> isForCurrentPlatform

### ISSUE THREAD

**Issue by bencoman** [guillep/pharo-core#5968]
Per #2246, it seems `SmalltalkImage current getSystemAttribute: 1001` only returns 'Win32', even on 64-bit images, because that is the historical name or the API regardless of word size.   So the existing code...
```
CallbackForWin64X64 class >> isForCurrentPlatform
	| processor |
	(#('Win32' 'Win64') includes: (SmalltalkImage current getSystemAttribute: 1001)) ifFalse:
		[^false].
	processor := (SmalltalkImage current getSystemAttribute: 1003) asLowercase.
	^processor first = $x and: [processor = 'x64' or: [('x86#64*' match: processor)]]
```
...works because it matches 'Win32', but then the redundant 'Win64' confounds proper understanding.  Propose to remove the 'Win64' and add a similar comment as proposed in #2246 for **OSPlatform class >> currentPlatformName**.

**Comment by MarcusDenker** [comment]
fix was merged
