### ISSUE TITLE
ReSentNotImplementedRule should return a smell if the only sender is the same method

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#5970]
While removing dead code I found multiple times methods that were not detected as smells by RBImplementedNotSentRule. The reason is that they had a sender that is themself. 

I think that in that case, the smell should still be raised.

**Comment by myroslavarm** [comment]
I cannot find this rule btw. Has it been removed?

**Comment by MarcusDenker** [comment]
it is now called ReSentNotImplementedRule
