### ISSUE TITLE
Factorial enhancement

### ISSUE THREAD

**Issue by David5i6** [guillep/pharo-core#5972]
While factorial implementation is very simple and surprisingly fast, there are some problems.

First is not the fastest implementation by far. (perhaps thats not the most important).

It's high recursive, so while trying to benchmark with **TimeProfiler** some scenarios in wich I have Taylor polinomies the resulting tree is hard to navigate, and need too much time to generate.

For a very extreme case:

```smalltalk

[100000 factorial] timeToRun

```

I was mading some tests and using a non-recursive aproximation the **TimeProfiles** works great.

Original factorial last for more than a minute, while non recursive version finishes in few seconds.

Also if doing some small improvements grouping elements together in pairs time for large number is almost the half of original version. ( also less GC and memory usage).

I'm going to make a pull request with my chage because I think it can improve performance and made code more easy to profile, but feel free to discard it if that does not fit into pharo philosofy.

**Comment by Ducasse** [comment]
may be we can keep factorial as slowFactorial as an example because we use it in books and mooc.

**Comment by svenvc** [comment]
Yes the classic definition has to stay, as it is one of the most common examples of recursion.

Maybe both could be combined: if n > 20 use fast algorithm ?

**Comment by svenvc** [comment]
BTW, years ago I wrote the following article:

https://medium.com/concerning-pharo/speeding-up-factorial-computation-by-changing-the-order-of-multiplications-f4da3a5576da

<blockquote><img src="https://miro.medium.com/max/1200/1*RuxaPPPrL6K09eF4pFhISw.jpeg" width="48" align="right"><div><img src="https://cdn-static-1.medium.com/_/fp/icons/favicon-rebrand-medium.3Y6xpZ-0FSdWDnPM3hSBIA.ico" height="14"> Medium</div><div><strong><a href="https://medium.com/concerning-pharo/speeding-up-factorial-computation-by-changing-the-order-of-multiplications-f4da3a5576da">Speeding up factorial computation by changing the order of multiplications</a></strong></div><div>This is a story about a small, seemingly innocent code change that speeds up a very simple computation. It is pretty magical and serves as…</div></blockquote>

**Comment by kasperosterbye** [comment]
rather keeping the existing as `slowFactorial`, I would suggest:
1. Keeping the implementation as it is.
2. Implementing a `fastFactorial`
3. making a comment in `factorial` to point to that fast one

**Comment by olekscode** [comment]
@kasperosterbye in practice, most people use simple functions like factorial without reading the method comment. Which means that very few developers will be aware of the existence of fastFactorial.

I suggest that we have `factorial` (fast implementation) and `slowFactorial` or `recursiveFactorial`. This way, many applications that use factorials (including the existing ones) will become faster, and people who read the book (and actually read the code) will be able to find the textbook implementation because it will be referenced in a method comment.
