### ISSUE TITLE
progress bars show only red box of death

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#5977]
to reproduce:
```smalltalk
(1 to: 100) do: [ :i | 2 milliSeconds wait  ] displayingProgress: 'Title'
```

It is strange that it does not try to display any error text inside...

![Pharo_Pr9GU2vQm7](https://user-images.githubusercontent.com/572494/77403233-3c350200-6db0-11ea-809f-4c289d54933e.png)

**Comment by guillep** [comment]
I cannot reproduce it.
Is there something else to it?

I was just doing `(1 to: 100) do: [ :i | 2 milliSeconds wait  ] displayingProgress: 'Title'` in a playground? No other package installed, no other "broken thing before" that may have caused a side effect?

**Comment by pavel-krivanek** [comment]
I tried a latest image and I cannot reproduce it too... maybe it was caused by some side-effect of the state of the image dealing with the previous issue. I'm closing it. Thanks

**Comment by guillep** [comment]
No problem. Let's just reopen it if you find it again :).
Thanks again.
