### ISSUE TITLE
Error on theme change

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#5983]
**Describe the bug**
Today, while my theme changed I got a debugger because a morph crashed during the change.

Error title: `#image: was sent to nil`

Stack:

```
UndefinedObject(Object)>>doesNotUnderstand: #image:
UndefinedObject>>doesNotUnderstand: #image:
ListDialogWindow(MessageDialogWindow)>>themeChanged
ByteSymbol(Symbol)>>value:
OrderedCollection>>do:
PharoLightTheme class(UITheme class)>>current:
PharoLightTheme class(UITheme class)>>beCurrent
```

The exact window with a problem is the `New name of protocol` one while renaming a protocol. 

**To Reproduce**
1) Rename a protocol
2) Do not validate
3) Change theme 

**Version information (please complete the following information, you can get it from Help->about):**

Pharo 8

**Comment by Ducasse** [comment]
How do I do step 3
```PharoLightTheme beCurrent```

So I can reproduce it

**Comment by Ducasse** [comment]
```
themeChanged
	"Update the icon."

	super themeChanged.
	self iconMorph image: self icon
        ^^^^^^^^^^^^^^^^^^^^^ iconMorph is nil
```

**Comment by Ducasse** [comment]
here is a possible fix

```
MessageDialogWindow >> iconMorph
	"Answer the value of iconMorph"

	^ iconMorph ifNil: [ iconMorph := self newIconMorph ]
```

**Comment by Ducasse** [comment]
should do a PR.

**Comment by Ducasse** [comment]
What I do not understand is that 

```
initialize
	super initialize.
	textFont := self defaultTextFont.
	iconMorph := self newIconMorph.
```
does not work

**Comment by Ducasse** [comment]
I did a PR.... looking for it. :(

**Comment by Ducasse** [comment]
https://github.com/pharo-project/pharo/pull/6027

**Comment by jecisc** [comment]
Fixed by @Ducasse
