### ISSUE TITLE
Error on UITheme newDropListIn:

### ISSUE THREAD

**Issue by David5i6** [guillep/pharo-core#5989]
**Describe the bug**
When click on a tree menu on the Settings there is an error messagen instead of showing options.
Previous issue #5947 closed but the bug is still here on a fresh pharo 9 image-

**To Reproduce**
Go to Setting and try to expand "appearance" options.

**Expected behavior**
Do not show error

**Screenshots**

![imagen](https://user-images.githubusercontent.com/7849541/77505202-cccc1a80-6e62-11ea-9f87-753cef264575.png)

**Version information (please complete the following information, you can get it from Help->about):**
 - OS: Windows 10, MacOS X Catalina
 - Version: Pharo 9.0
 - Commit info: Pharo-9.0.0+build.184.sha.3fe36492f3f87b3d8258c9f4353a1fb68b26749f (64 Bit)

**Additional context**

**Comment by guillep** [comment]
You're right, there were two different places where the bug was produced.

Could you try changing:

```smalltalk
createIconPackList
	^ (Smalltalk ui theme 
		newDropListIn: self
		for: self
		list: #availablePacks
		getSelected: #current
		setSelected: #current:
		getEnabled: nil
		useIndex: false
		help: nil)
		wrapSelector: #name;
		hResizing: #rigid;
		width: 120;
		yourself
```

by

```
createIconPackList
	^ (Smalltalk ui theme 
		newDropListIn: self currentWorld
		for: self
		list: #availablePacks
		getSelected: #current
		setSelected: #current:
		getEnabled: nil
		useIndex: false
		help: nil)
		wrapSelector: #name;
		hResizing: #rigid;
		width: 120;
		yourself
```

and tell me if that fixes the issue for you?
If so I'll make a PR.

**Comment by David5i6** [comment]
No, the problem seems still here:

![imagen](https://user-images.githubusercontent.com/7849541/77615661-2ea68600-6f30-11ea-958c-2d12aee9ffba.png)

**Comment by Ducasse** [comment]
I think that https://github.com/pharo-project/pharo/issues/6004 fixed the problem can you verify.

**Comment by Ducasse** [comment]
OK I verified and #6004 fixed it. So if I wrong please reopen it.
