### ISSUE TITLE
Cannot set breakpoint in method by mouse

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#5999]
Now, it is not possible to set a breakpoint by clicking on the left bar next to the method text (RubTextSegmentIconDisplayer). If the breakpoint is set from the context menus, it is possible to remove it.

**Comment by StevenCostiou** [comment]
Could you provide more information?
I just tried in Pharo 9 in a class browser and it works by clicking in the gutter.
It seems a bit buggy sometimes though (I click in the line and the breakpoint is put on the method).

**Comment by pavel-krivanek** [comment]
it was broken in the build 185, not it seems to be ok. Closing
