### ISSUE TITLE
Font problems

### ISSUE THREAD

**Issue by ndearns** [guillep/pharo-core#6000]
**Describe the bug**
Hello, new user of pharo here.

I'm running pharo-ui on my Chromebook.  When I started it up the fonts were miniscule, so I increased their size in the settings.  The results were mixed:

- Font sizes changed as expected in the Smalltalk windows
- Font sizes in the main workspace menu did not change
- The mouse cursor size remains miniscule
- The layout of some 'widgets' in the Smalltalk windows is broken, e.g. in the SystemBrowser the code panes obscure the filter buttons. 

**Expected behavior**
I thought the whole environment - including the mouse cursor - would scale to suit the selected font size.

**Screenshots**

This shot shows the two font sizes, and the obscuring of the filter buttons.  The mouse cursor is lost during screen capture, but it was scaled as per the workspace menu font size.

![Screenshot 2020-03-26 at 08 02 11](https://user-images.githubusercontent.com/61657800/77624760-310ddd80-6f3a-11ea-99a1-d1bc6a9cc642.png)

**Version information (please complete the following information, you can get it from Help->about):**
 - OS: Chromium
 - Version: Pharo 8.0

**Comment by MarcusDenker** [comment]
This is now better to be done by setting a scale factor in general, not increase the font size.
