### ISSUE TITLE
Broken modal dialogs in Spec

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#6010]
When trying to create a Pull Request from Iceberg (context menu - Github - Create pull request...), I got:

`Instance of WorldMorph did not understand #modalLockTo:`

I expect it may be more general problem

**Comment by Ducasse** [comment]
I have no idea if the bug I found a while ago was fixed.
I added 
https://github.com/pharo-spec/Spec/issues/853

We could not do openDialogWithSpec
but I have no visibility.

**Comment by pavel-krivanek** [comment]
I is in the old Spec, in build 164 it still worked, in 166 not

**Comment by pavel-krivanek** [comment]
introduced in build 166: https://github.com/pharo-project/pharo/pull/5934
