### ISSUE TITLE
Merge Fuel 3.0.2 in P9

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6016]
Fuel 3.0.2 has been integrated in P8 and we should integrate it in P9
https://github.com/pharo-project/pharo/pull/5871

**Comment by MarcusDenker** [comment]
I think this was done?

**Comment by astares** [comment]
There is already a 3.0.3 from @theseion 

https://github.com/theseion/Fuel/branches

but the versions in Fuel seem to be managed via branches, not stable "release" tags

**Comment by theseion** [comment]
Yes, 3.0.3 (latest version) is already in P9.

**Comment by MarcusDenker** [comment]
thanks, I close the issue!
