### ISSUE TITLE
TaskBar is not appearing by default

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#6021]
**Describe the bug**
The TaskBar is not appearing

**To Reproduce**
1. Open a new Pharo9 Image
2. The bar is not there

**Expected behavior**
To have the taskBar at the bottom of the world.

**Screenshots**
Expected:

![image](https://user-images.githubusercontent.com/355455/77751563-3e07fb00-7026-11ea-88ea-89a6f7ca2469.png)

Actual:

![image](https://user-images.githubusercontent.com/355455/77751613-51b36180-7026-11ea-9932-c6d58d461ea6.png)

**Version information (please complete the following information, you can get it from Help->about):**
 - OS: any
 - Version: Pharo 9.0

**Additional context**
If you do ```TaskbarMorph reset``` it appears back.
Looks like an initialization problem. Maybe the initialization of the task bar during the bootstrap is not in the right place

**Comment by pavel-krivanek** [comment]
There was nothing changed in the Taskbar initialization. In build 166 it was still working.

**Comment by VincentBlondeau** [comment]
I confirm that this bug is still here in Pharo9.0.0 build: 209, commit: 515c422

**Comment by guillep** [comment]
I've checked, taskbar vanished in build 182. Which related to commit

Pharo9.0.0
build: 182, commit: dfac81c

Build 182 was the integration of https://github.com/pharo-project/pharo/pull/5978

Funny enough, the commit does not modify anything seemingly related. I'm investigating it.

**Comment by guillep** [comment]
After some more testing, I'm mostly sure its somehow related. But I don't understand why yet.

I've tried just removing the next line from `BaselineOfIDE`:

```smalltalk
LogicalFontManager current addFontProvider: FreeTypeFontProvider current.
```
And then bootstrapping it. Then of course, fonts were not the FT2 ones, but we get the task bar back:

![image](https://user-images.githubusercontent.com/708322/79360026-a2421e80-7f43-11ea-8896-17c17e5d983e.png)

**Comment by VincentBlondeau** [comment]
Where is the fix integrated? The commit was made in the Guille repo...

**Comment by guillep** [comment]
That would be PR #6185
