### ISSUE TITLE
TonelWriter>>writeSnapshot: includes tag name in package name when there's no OrganizationDefinition

### ISSUE THREAD

**Issue by carolahp** [guillep/pharo-core#6040]
When writing a snapshot of a package that includes tags and the snapshot does not contain an OrganizationDefinition, the name of the folder for the package includes the name of the tag.
 
```  
| aSnapshot memoryFileReference writer |
" Taking a snapshot of the package MonticelloMocks "
aSnapshot := (MCPackage new name: #MonticelloMocks) snapshot.
" Removing all elements from the snapshot except one class 
which is classified in the Package's tag 'Tag' "
(aSnapshot definitions
	select: [ :def | def className ~= #MCMockClassJ ])
	do: [ :each | aSnapshot definitions remove: each ].
memoryFileReference := FileSystem memory root.
writer := TonelWriter on: memoryFileReference.
writer writeSnapshot: aSnapshot.
	
(memoryFileReference / 'MonticelloMocks-Tag') exists. "Should not exist"
(memoryFileReference / 'MonticelloMocks') exists. "Should exist"
```

**Comment by carolahp** [comment]
The solution to this problem involves a few modifications in Monticello, which I send by PR. 
I'm creating an issue in the Tonel repository https://github.com/pharo-vcs/tonel

<blockquote><img src="https://avatars0.githubusercontent.com/u/28102403?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-vcs/tonel">pharo-vcs/tonel</a></strong></div><div>Contribute to pharo-vcs/tonel development by creating an account on GitHub.</div></blockquote>

**Comment by jecisc** [comment]
This is now fixed :)
