### ISSUE TITLE
Cannot multiple select in calypso

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#6041]
**Describe the bug**
In Pharo 8 it is possible to multiple select in calypso.

Now I can use cmd and shift to multiple select, but when I use my trackpad to right-click an entry in the list, the multiple selections is lost and only a simple selection remain.

**Comment by guillep** [comment]
This is a duplicate of https://github.com/pharo-project/pharo/issues/6003.
Again, the issue was in the first page of the issues.

Could you please do a quick check for duplicates before opening an issue?
