### ISSUE TITLE
Taskbar vanish in Pharo 9

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#6043]
I used Pharo 9 today and it happened multiple time that the taskbar vanished. I needed to use `TaskbarMorph reset` to get it back.

**Comment by guillep** [comment]
This is a duplicate of #6021 .
It would be good to do a quick check for duplicates, specially when they appear in the first page of open bugs...

![image](https://user-images.githubusercontent.com/708322/77780795-d7e69c80-7054-11ea-8e0d-f404592587fd.png)
