### ISSUE TITLE
It should not be possible to use super as something else than the receiver of a message

### ISSUE THREAD

**Issue by juliendelplanque** [guillep/pharo-core#6049]
**Describe the bug**
Right now, it is possible to use `super` as `self` in method source code.
For example, `^ super` is accepted by the compiler.
`super` seems to be bound to `self` right now.
It makes no sense. `super` should not be bound to anything, it just provides information to the method lookup algorithm.

There should be a static analysis of the AST during compilation to ensure that the only places where `super` occur is as receiver of a message.

**To Reproduce**
1. Create the following method on any class:

```Smalltalk
returnSuper
	^ super
```
2. The compiler did not complain.

**Expected behavior**
The compiler should refuse to compile source code making such usage of `super`.

**Version information (please complete the following information, you can get it from Help->about):**
 - OS: MacOSX (but will apply to any OS)
 - Version: Pharo 9.0
 - Commit info: Pharo-9.0.0+build.198.sha.882810f4efdfdf717c51248aefa9d67b24026358 (64 Bit)

**Comment by pavel-krivanek** [comment]
I think that a code quality rule should be enough.

**Comment by juliendelplanque** [comment]
Well, it should not even be allowed by the grammar to make such use of `super` in fact.

But yeah, I'm not for creating incompatibility for no good reason, so maybe a code quality rule would be nice. :-)

**Comment by MarcusDenker** [comment]
Yes, a rule would be nice.
