### ISSUE TITLE
Text in Playground tabs not fully visible

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#6064]
Not a big issue but I noticed while in other tabs (like Calypso) the text is fully visible it is not in the 
tabs the playground is using. 

So the "g" of "Page" is covered at the bottom.

![image](https://user-images.githubusercontent.com/5980033/78046352-586c0c80-7377-11ea-93af-73d9707b3a4b.png)

**Comment by MarcusDenker** [comment]
I think this is not a problem anyore? I do not see tabs
