### ISSUE TITLE
ZnHTTPSTest should be in a test package

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#6065]
The class ZnHTTPSTest is currently in package Zinc-Zodiac, but as it is a unit test class
it should be moved to a "Test" package.

@svenvc: should we move it either to 

- "Zinc-Tests" or 
- "Zodiac-Tests" or 
- create a new package "Zinc-Zodiac-Tests" ?

**Comment by svenvc** [comment]
https://github.com/svenvc/zinc/tree/master/repository/Zinc-Zodiac-Tests.package

<blockquote><img src="https://avatars2.githubusercontent.com/u/870089?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/svenvc/zinc">svenvc/zinc</a></strong></div><div>Zinc HTTP Components is an open-source Smalltalk framework to deal with the HTTP networking protocol. - svenvc/zinc</div></blockquote>

**Comment by astares** [comment]
@svenvc OK - this is solved in zinc repo.

Do we reintegrate a full Zinc release into the base image (now or later?) or should we do just a similar change in the Pharo base?

**Comment by svenvc** [comment]
the big, full integration is not possible today (mainly also because Zinc supports olders Pharo versions).

if this is important to you, you can cherry pick that change, it will make the difference between the 2 smaller.

**Comment by jecisc** [comment]
This is fixed
