### ISSUE TITLE
Some variables seem shadowed and reported as such in the build report. 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6082]
**Describe the bug**

SystemNotification: DTPluginConfiguration>>asTestSuite(testSuite is shadowed)
SystemNotification: DrTestsTestRunnerTest>>testAllSelectedClassesAreTestCases(package is shadowed)
SystemNotification: MCFileTreeStCypressWriter class>>fileNameForSelector:(specials is shadowed)
SystemNotification: OCASTTranslatorTest>>testExamplePrimitiveErrorCode(method is shadowed)
SystemNotification: OCASTTranslatorTest>>testExamplePrimitiveErrorModule(method is shadowed)
SystemNotification: OCASTTranslatorTest>>testExamplePrimitiveErrorCodeModule(method is shadowed)
SystemNotification: OCASTTranslatorTest>>testExamplePrimitiveModuleError(method is shadowed)
SystemNotification: OCASTVariableTranslatorTest>>testPushThisContext(method is shadowed)
SystemNotification: PNGReadWriter>>writeChunk:(stream is shadowed)
SystemNotification: RBDummyRefactoryTestDataApp>>tempVarOverridesInstVar(temporaryVariable is shadowed)
SystemNotification: RBRefactoryTestDataApp>>tempVarOverridesInstVar(temporaryVariable is shadowed)
SystemNotification: RBSmalllintTestObject>>tempVarOverridesInstVar(temporaryVariable is shadowed)

**Comment by guillep** [comment]
Oh yes, I like this entry :)
