### ISSUE TITLE
Review "GT-SUnitDebugger" package

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#6087]
There are abstract test classes in package "GT-SUnitDebugger" like
- GTSUnitExampleWithProblematicSetUpTest
- GTSUnitExampleWithSetUpAndNoTearDownTest
- GTSUnitExampleWithSetUpAndTearDownTest

including some test methods and implementing #isAbstract to return true.

They have no subclasses - so I guess this is an unfinished legacy leftover.

Possibly we can remove them

**Comment by MarcusDenker** [comment]
This can be closed as the package got removed
