### ISSUE TITLE
Suggestions not working on arguments

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#6088]
**Describe the bug**
The suggestions in the browser are not working anymore for arguments.
Instead, they give suggestions for the method.

![image](https://user-images.githubusercontent.com/708322/78117979-9b28f580-7406-11ea-95e0-bf9be1b9391b.png)

For example, selecting a temp works well:

![image](https://user-images.githubusercontent.com/708322/78118031-ab40d500-7406-11ea-9d0b-c254954fe24b.png)

**To Reproduce**
Steps to reproduce the behavior with shortcut:
1. Go to a method with arguments
2. Click on the argument or an usage
3. Cmd+T or Ctrl+T

Steps to reproduce the behavior with context menu:
1. Go to a method with arguments
2. Right-click on the argument or an usage
3. look at submenu suggestions

**Expected behavior**

We should have argument suggestions (like renaming it)

**Version information (please complete the following information, you can get it from Help->about):**
 - Version: Pharo 9.0
 - Commit info: 2c38e9fbc05c63fbe5db1b23db83fa442500d7f3

**Additional context**

This is maybe related to AST changes in https://github.com/pharo-project/pharo/pull/6013/ ?
Maybe the suggestions were depending on `isTemp`?

**Comment by dionisiydk** [comment]
I confirm, it was working ~month ago

**Comment by Ducasse** [comment]
Guille was it fixed with the new update of compleshion?

**Comment by guillep** [comment]
I don't think this is related with completion but not sure. It could also be related with AST changes probably from @hogoww or @MarcusDenker ? 

We should check what build broke it (a simple binary search would suffice) to find the real PR that causes the regression and see how to fix it from there.

**Comment by hogoww** [comment]
Indeed it is, PR incoming.
Thanks for the ping @guillep I didn't see this issue!

**Comment by guillep** [comment]
No problem! Just let's add a test to find these problems faster in the future :)

**Comment by MarcusDenker** [comment]
This in the meantime has been fixed by calling on the context #isArgOrTempVariableSelected
