### ISSUE TITLE
Fleaky Reflectivity test

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#6092]
**Describe the bug**

There is a fleaky reflectivity test failing in the CI.
See

![image](https://user-images.githubusercontent.com/708322/78128912-011d7900-7417-11ea-84d3-535c33c71055.png)

**Version information (please complete the following information, you can get it from Help->about):**
 - Version: Pharo 9.0

**Comment by StevenCostiou** [comment]
I will handle that as soon as I can.
The mechanics of object-centric metalinks was changed and stabilized, but is not yet integrated.

**Comment by StevenCostiou** [comment]
@guillep Can you point out a failing CI with this problem so that I can see the failure?

**Comment by MarcusDenker** [comment]
It happened just now again:

Error
key #methodWithTempVarAccess not found in MethodDictionary
Stacktrace
KeyNotFound
key #methodWithTempVarAccess not found in MethodDictionary
MethodDictionary(Dictionary)>>errorKeyNotFound:
[self errorKeyNotFound: key] in MethodDictionary(Dictionary)>>at:
MethodDictionary>>at:ifAbsent:
MethodDictionary(Dictionary)>>at:
a subclass of ReflectivityExamples2 class(Behavior)>>compiledMethodAt:
a subclass of ReflectivityExamples2 class(Behavior)>>>>
RBMethodNode>>method
RBTemporaryNode(RBProgramNode)>>link:
MetaLinkInstaller>>install:onNode:forObject:
MetaLink>>linkToNode:forObject:
RBTemporaryNode(RBProgramNode)>>link:forObject:
a subclass of ReflectivityExamples2(Object)>>link:toAST:
[ :node | self link: aMetaLink toAST: node ] in a subclass of ReflectivityExamples2(Object)>>link:toNodes:
IdentitySet(Set)>>do:
a subclass of ReflectivityExamples2(Object)>>link:toNodes:
MetaLinkInstaller>>registerAndInstallPermaLink:forTarget:
MetaLinkInstaller>>installPermaLink:onTempVarNamed:inMethod:
MetaLink>>installOnTempVarNamed:inMethod:for:option:instanceSpecific:
LinkInstallerTest>>testLinkOnTempVarForObject
LinkInstallerTest(TestCase)>>performTest


I will download the image from the CI, maybe it can be helpful, too


https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-6582/2/tests

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-6582/2/tests">Jenkins</a></strong></div></blockquote>

**Comment by StevenCostiou** [comment]
Thanks! Ok with the CI image the bug does not occur, I'll investigate it.
