### ISSUE TITLE
Fleaky Fuel test

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#6094]
**Describe the bug**

`FLContextSerializationTest>>testDoIt` produces failures in the CI from time to time:

```
0x7fff53422210 I Context>copyStack 0x1141b2e38: a(n) Context
0x7fff53422248 M [] in FLContextSerializationTest>testDoIt 0x113500990: a(n) FLContextSerializationTest
```
**Version information (please complete the following information, you can get it from Help->about):**
 - Version: Pharo 9.0

**Additional context**
This is probably a VM bug, we should check it carefully

**Comment by theseion** [comment]
Not sure if it's the same bug but I did have segfault issues in February 2018 with `#copyStack`. I sent an e-mail about it to vm-dev but couldn't get any help:
> I'm seeing many segfaults (around 20 to 30% of the time) when running Fuel builds on Linux. Everytime I see it it's caused by #copyStack (e.g. https://travis-ci.org/theseion/Fuel/jobs/345741310). AFAICT it happens more often (exclusively?) on 32 bit with Pharo 7 (latest VM + latest image).

...

> I've tried for the last two hours to come up with a reliable way of
triggering the segfault but haven't had any luck. I can only reproduce it
on Linux, not macOS and I've only been able to force the segfault with
using smalltalkCI:
>
> git clone https://github.com/hpi-swa/smalltalkCI.git && git clone
https://github.com/theseion/Fuel.git && smalltalkCI/run.sh -s Pharo-alpha
Fuel/.default.ston
>
> I used Ubuntu 17.04 (32-bit), TravisCI uses 14.04.5 (64-bit).

<blockquote><div><strong><a href="https://travis-ci.org/theseion/Fuel/jobs/345741310">Travis CI - Test and Deploy Your Code with Confidence</a></strong></div><div>Travis CI enables your team to test and ship your apps with confidence. Easily sync your projects with Travis CI and you'll be testing your code in minutes.</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/8598281?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/hpi-swa/smalltalkCI">hpi-swa/smalltalkCI</a></strong></div><div>Framework for testing Smalltalk projects with GitHub Actions, Travis CI, AppVeyor, GitLab CI, and others. - hpi-swa/smalltalkCI</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/250711?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/theseion/Fuel">theseion/Fuel</a></strong></div><div>Fuel, the Smalltalk object serializer. Contribute to theseion/Fuel development by creating an account on GitHub.</div></blockquote>

**Comment by guillep** [comment]
Very probably, and probably also related to https://github.com/pharo-project/pharo/issues/6052.

I'll pay more attention to the OSs where it fails and I'll log it.

**Comment by MarcusDenker** [comment]
This is now fixed...
