### ISSUE TITLE
Error on CocompletionEngine >> RubScrolledTextModel did not understand #variableBindings

### ISSUE THREAD

**Issue by David5i6** [guillep/pharo-core#6101]
**Describe the bug**
When using CoCompletionEngine sometimes an error " RubScrolledTextModel did not understand #variableBindings" is raised.

**To Reproduce**
1. In preferences select the CoCompletionEngine
2. Open Workspace
3. Type "Transcript" (without doule quotes) on Workspace
4. Error happens before you can write a message

**Expected behavior**
Don reaise an error

**Screenshots**
![imagen](https://user-images.githubusercontent.com/7849541/78181828-48325b00-7465-11ea-87b7-d145545bd137.png)

**Version information (please complete the following information, you can get it from Help->about):**
 - OS: Windows 10
 - Version: Pharo 9.0
 - Commit info: Pharo-9.0.0+build.202.sha.2799b9114f70ce3931612334575cd42509315882 (64 Bit)

**Additional context**

**Comment by guillep** [comment]
Ah, you're using Workspace, not Playground. I never tested it before with it, so that may be the cause of the bug :)

Why are you using "Workspace"? Curiosity on my side only

**Comment by guillep** [comment]
I've fixed it in https://github.com/guillep/complishon/releases/tag/v3.0.0.

I'll propose the change to Pharo

<blockquote><img src="https://avatars3.githubusercontent.com/u/708322?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/guillep/complishon">guillep/complishon</a></strong></div><div>Contribute to guillep/complishon development by creating an account on GitHub.</div></blockquote>

**Comment by David5i6** [comment]
Hi @guillep, I usually use Playground, but I was diving into Pharo for uses of Rubric and I found Workspace then I use it simply because I have the window open ...
