### ISSUE TITLE
Rework init logic in DamageRecorder

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#6113]
The class DamageRecorder overwrites the new methods

```Smalltalk
new

	^ super new reset
```
and provides a reset like

```Smalltalk
reset
	"Clear the damage list."

	invalidRects := OrderedCollection new: 15.
	totalRepaint := false
```

This looks like a strange pattern. It would be better to have an instance side #initialize method.
Such an #initialize method is usually expected to see what and which initialization happens - this makes overwriting the "new" unnecessary.

**Comment by Ducasse** [comment]
Indeed also the initialize can call reset if reset is used somewhere else.
