### ISSUE TITLE
Transcript enhancement and doubts...

### ISSUE THREAD

**Issue by David5i6** [guillep/pharo-core#6126]
Not a bug, but a possible improvement.

Transcript is used for loggin texts from classes and doing some thigs from the user.
It's a great tool... but today in my opinion is a little outdated in functionality.

I'ven playing with it and made a little experiments so apart from the traditional show I've added some methods "logInfo, logWarning,logError..." and get soething like this:

![imagen](https://user-images.githubusercontent.com/7849541/78258010-e58b9e80-74fa-11ea-9ec4-975bd267bca4.png)

Apart from adding colors, the log funcions, acces the context and adds the class and methods that calls the log (so it's easy to identify where we need to go to.

I'm not sure about direction of pharo, so I've a question.

¿ Would you be interested in this kind of funtionality ? If response is yes I will try to finish it and made a merge request. (of course suggestions will be accepted).

Apart from this, I'm searchig for info about Rubric, because I want two funcionalities that I don't know if they already exists or if not how could them be impleented.

Those are:

1.- Possibility to define an attribute to made some paart of the text nont editable. (That can be useful for editing template parts of a document.

2.- Possibility to add a part of text that when edited can be handled so th content of that text can be monitorized.

The main focus on those functionalities is to get an option to create some kind of terminal apps like this:

![imagen](https://user-images.githubusercontent.com/7849541/78258886-2cc65f00-74fc-11ea-9d7e-e55322ebae9f.png)

In wich everithig is read only except the yellow background part and wherever text in editable part changes we can get the change via a handler, or announcement.... And of course for example when enter key is pressed change the editable part to readonly again (changing also it's backgroud color).

**Comment by guillep** [comment]
Hi @David5i6 ,  I think this is the kind of thing that should be discussed elsewhere :).

Are you in [Pharo's discord channel?](https://discord.gg/QewZMZa).

@estebanlm is reworking all tools, so maybe it could be good you discuss with him directly?

**Comment by David5i6** [comment]
Thanks !
I've discord, but usually I only use the computer outside of job for 15 min/day or less, I'm going to contant with @estebanlm, but I'm sorry in advance if dialogue is stalled time to time.

**Comment by David5i6** [comment]
after asking in discord I'm goint to cles this.

Surely I'm going to learn about ropes and try to make a terminal like app.

thanks !
