### ISSUE TITLE
Backport Halo fixes to Pharo8

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#6137]
**Describe the bug**
Some halos are broken/glitchy in Pharo 8.
- #4458
- #5638
- #4709

There was a partial fix introduced in P9, that could be backported: #5446
The rest of the fix should come as part of fixing #5638

As soon as those issues are closed, we should backport them to Pharo8

**Comment by MarcusDenker** [comment]
I think we will not backport this to Pharo8
