### ISSUE TITLE
Object >> #-> comment does not follow implementation

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#6147]
**Describe the bug**
Following the intergration of this PR, the comment is in mismatch with the implementation

https://github.com/pharo-project/pharo/pull/5244#issuecomment-610284686

**Expected behavior**

The comment should be removed

**Version information (please complete the following information, you can get it from Help->about):**
 - Version: Pharo 9.0

**Comment by MarcusDenker** [comment]
this has been fixed
