### ISSUE TITLE
CoTypeInferencer does not take traits into account

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#6163]
**Describe the bug**
`CoTypeInferencer>>#inferFrom:typeGetters:` uses expression `self inferMethod: (aClass lookupSelector: #initialize)` which expects that the `initialize` method will always be found. This is not the case for methods in traits. The code completion causes `#methodClass was sent to nil` for every attempt to for code completion in methods inside traits.

**Comment by guillep** [comment]
I don't know why Github closed the issue when my push was in another repo....
Anyways. Fix is here https://github.com/guillep/complishon/releases/tag/v3.0.1.
Incoming

<blockquote><img src="https://avatars3.githubusercontent.com/u/708322?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/guillep/complishon">guillep/complishon</a></strong></div><div>Contribute to guillep/complishon development by creating an account on GitHub.</div></blockquote>
