### ISSUE TITLE
CoClassImplementedMessagesFetcher does not take traits into account

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#6164]
**Describe the bug**
`CoClassImplementedMessagesFetcher`  expects that `completionClass` is always known. It is not true for traits.

**To Reproduce**
1. open TBehavior in Calypso
2. start to enter new method typing `mes`
3. See error

**Build information**
Pharo-9.0.0+build.229.sha.944aa4648070f46b8a10b6f23ad0f8ef854b65d5 (64 Bit)

**Comment by guillep** [comment]
Duplicate of #6181 and fixed in #6187
