### ISSUE TITLE
Syntax highlighter doesn't work with capitalised symbols 

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#6172]
**Describe the bug**
When your write # followed by a capitalized letter A-Z in the code editor (like #World), the syntax highlighter doesn't update the syntax coloring of the method anymore.

**To Reproduce**
Go see an example here:
`(BaselineOfMorphicCore >> #postload:package:) browse`

Live example:
![LjRUXxUa04](https://user-images.githubusercontent.com/4706329/79122026-fd82de00-7d96-11ea-832e-76f184ab143f.gif)

**Expected behavior**
You know

**Screenshots**
![LjRUXxUa04](https://user-images.githubusercontent.com/4706329/79122026-fd82de00-7d96-11ea-832e-76f184ab143f.gif)

**Version information:**
 - OS: WIN10
 - Version: Pharo9.0.0 build: 233, commit: 989264b

**Expected development cost**
Base number:
- Someone that know the framework: x= 30 mins.
- Me: x= 180 mins
*Estimated Total Development cost* : x * 2 + 10

**Additional context**

**Comment by MarcusDenker** [comment]
this has been merged
