### ISSUE TITLE
New completion should consider pragmas

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#6180]
This is what I get in recent Pharo when I add the <script> pragma to an existing method:

"MessageNotUnderstood: CoASTHeuristicsResultSetBuilder>> #visitPragmaNode:"

![image](https://user-images.githubusercontent.com/5980033/79278837-e0d8ca00-7eac-11ea-8f6f-2604eb8efda3.png)

@guillep 
So the #visitPragmaNode: method seems not to be available for the Visitor pattern.

**Comment by guillep** [comment]
Fix is here https://github.com/guillep/complishon/releases/tag/v3.0.1.
Incoming

<blockquote><img src="https://avatars3.githubusercontent.com/u/708322?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/guillep/complishon">guillep/complishon</a></strong></div><div>Contribute to guillep/complishon development by creating an account on GitHub.</div></blockquote>
