### ISSUE TITLE
New completion gives DNU on traits

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#6181]
implement a simple trait

```Smalltalk
Trait named: #TFoo
	 uses: {}
	 package: 'MyKillerApp-Core'
```
now try to type an instance side method called #isLoadable 

=> one gets a DNU

![image](https://user-images.githubusercontent.com/5980033/79285110-d6263100-7ebc-11ea-9875-4f337811b866.png)

**Comment by guillep** [comment]
Fix is here https://github.com/guillep/complishon/releases/tag/v3.0.1.
Incoming

<blockquote><img src="https://avatars3.githubusercontent.com/u/708322?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/guillep/complishon">guillep/complishon</a></strong></div><div>Contribute to guillep/complishon development by creating an account on GitHub.</div></blockquote>
