### ISSUE TITLE
Rectangle class >> center:extent: method bug

### ISSUE THREAD

**Issue by chicoary** [guillep/pharo-core#6200]
Bug below:

![Rectangle class center_extent bug](https://user-images.githubusercontent.com/7659991/79914809-3efd3400-83fc-11ea-80e6-76bd82dd60c1.png)

Fixed:

![Rectangle class center_extent fixed](https://user-images.githubusercontent.com/7659991/79914888-605e2000-83fc-11ea-9937-522a1f2a1a97.png)

**Comment by chicoary** [comment]
I'm sorry. I see now that there is the `Rectangle>>floatCenter:extent:` method that does what I expected. I'll close the issue myself.

**Comment by astares** [comment]
@chicoary see https://github.com/pharo-project/pharo/issues/6192

**Comment by chicoary** [comment]
Thanx astares.
