### ISSUE TITLE
super sends mess up parent chain in AST

### ISSUE THREAD

**Issue by theseion** [guillep/pharo-core#6201]
**Describe the bug**
I've found source code that produces an AST in which a node has the wrong parent.

**To Reproduce**
Evaluate the code below. For some reason the problem does not always occur. It should show up on the block node (where I've placed the halt). If you can't find the problem when evaluating, browse the method and you should see an error in the critics: "MessageNotUnderstood: receiver of 'methodNode' is nil".

Comparing the parents in this situation shows that the parent of the block node has `self` instead of `super` in the generated source.

```smalltalk
| block |
Object subclass: #Foo
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Hacks'.
(Smalltalk at: #Foo) compile: 'addKeyToSequence: aString
	super at: aString ifAbsent: [Smalltalk addLast: aString]'.
block := [ :node |
	node children do: [ :child |
		self assert: child parent == node.
		self assert: child methodNode notNil.
		self haltIf: [ child class = RBBlockNode ].
		child nodesDo: block ] ].
((Smalltalk at: #Foo) >> #addKeyToSequence:) ast nodesDo: block
```

**Expected behavior**
Asking the block node from the above AST for `#methodNode` should return the top node of the AST. It answers nil.

**Screenshots**
![Screenshot 2020-04-22 at 13 49 34](https://user-images.githubusercontent.com/250711/79978470-4544ec00-84a0-11ea-88c9-9e7ef3d639e0.png)

**Version information:**
 - OS: macOS
 - Version: Pharo 9 build: 245, commit: 7879085 (also happens in Pharo 8)

**Comment by MarcusDenker** [comment]
It seems that the ReSuperSendsRule destroys the AST.

There are multiple problems:

1) the transformation does not correctly update the parent pointer
2) It is very had that the rules modify the AST in the first place... this is not a good idea as
even if we hand in a copy, it will destry the copied AST and thus lead to problems with the rules that are executed after

An idea could be to copy the node in general in the ReNodeRewriteRule check: aNode forCritiquesDo:

**Comment by theseion** [comment]
I see. That's why I couldn't reproduce the problem with a script. Thanks Marcus.

**Comment by guillep** [comment]
Well that’s also because maybe the rules predate the AST caching?
If so, the rules were written assuming the AST was not cached...

**Comment by MarcusDenker** [comment]
even that does not fix it: then the rule destroys the copy and the next rule runs into problems
