### ISSUE TITLE
Select the old protocol when renaming a protocol

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6208]
When you rename a protocol, the old one is not selected so we cannot immediately type. 

![Screenshot 2020-04-23 at 15 17 36](https://user-images.githubusercontent.com/432549/80106797-9a553080-857a-11ea-8ece-a7d29e235e11.png)

**Comment by AleCossioCh** [comment]
Hi @Ducasse I tried to replicate this error, I didn't succeed. I suggest closing this issue because it's apparently solved.
![solved](https://user-images.githubusercontent.com/23039347/118867455-19698500-b8b1-11eb-88f6-8c9d2d179d09.gif)

**Comment by Ducasse** [comment]
Thanks. Yes indeed!
