### ISSUE TITLE
spanNewSessionFrom -> spawnNewSessionFrom

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6248]
span does not mean spawn
We should rename all the method spanNewSession* -> spawnNewSession*

**Comment by MarcusDenker** [comment]
as the change breaks the debugger for debugging tests, I committed a revert: https://github.com/pharo-project/pharo/pull/6253

I close this issue (as a new solution do both steps in one)

**Comment by Ducasse** [comment]
I do not get why simply renaming a method and all its sender can break the debugger?

**Comment by MarcusDenker** [comment]
there was one change: 

self sessionClass  -> self class

which then lead to the sunit debugger being started with a normal session, leading to problems
