### ISSUE TITLE
MacRoman/Unicode char converter methods are backwards.

### ISSUE THREAD

**Issue by jdougan** [guillep/pharo-core#6256]
**Describe the bug**
The methods Character>>macRomanToUnicode and unicodeToMacRoman are backwards from each other.

**To Reproduce**
1. Go to a playground
2. Print  (Character value: 16r80) macRomanToUnicode
3. It should evaluate to a capital A with an umlaut. $Ä (Unicode U+00C4) instead I get null.
4. Print  (Character value: 16r80) unicodeToMacRoman
5. It should evaluate to Character null, instead I get $Ä

**Version information:**
Pharo 9.0.0 build: 270, commit: 93fc647

**Expected development cost**
2 minutes to swap the methods and and unknown amount of time for paperwork and testing.

**Additional context**
An additional note is it seems kinda wasteful to create a text converter instance for every character.

**Comment by svenvc** [comment]
Hi,

Several things:
- yes you probably found a bug
- but it is in old code that we should remove

Consider (using newer API, there is more)
```
(ZnCharacterEncoder newForEncoding: #macRoman) decodeBytes: #[ 16r80 ].
 "'Ä'"

(ZnCharacterEncoder newForEncoding: #macRoman) encodeString: 16rC4 asCharacter asString. 
"#[128]"
```

Encoding works from characters to bytes, decoding from bytes to characters. We nowadays try to avoid viewing characters as bytes.

What exactly are you trying to do ? MacRoman is not in active use anymore, AFAIK.

Sven

**Comment by svenvc** [comment]
Shorter API:
```
#[ 16r80 ] decodeWith: #macRoman. "'Ä'"

16rC4 asCharacter asString encodeWith: #macRoman. "#[128]"
```

**Comment by jdougan** [comment]
I have a project in mind that needs fairly low level keyboard input and I've been investigating just what I can get from a custom event handler registered with the InputEventFetcher.  It mentioned in the class comment that the current key coding is in Mac Roman, so I used the character methods as a quick conversion for making my event dump output more readable. It didn't seem obvious to look in the web library for the conversion.

**Comment by Ducasse** [comment]
Hi jdougan 
may be you should check with the crew to use SDL20 because 
some years ago based on SDL and OSWindow we build gesture recognition 
and now it will be the architecture for Pharo 90. 

S.

**Comment by svenvc** [comment]
https://ci.inria.fr/pharo-contribution/job/EnterprisePharoBook/lastSuccessfulBuild/artifact/book-result/Zinc-Encoding-Meta/Zinc-Encoding-Meta.html

these classes are Zn prefixed, but this is the standard way of doing character encoding/decoding in Pharo (as well as related streams), this is way more general.

<blockquote><div><strong><a href="https://ci.inria.fr/pharo-contribution/job/EnterprisePharoBook/lastSuccessfulBuild/artifact/book-result/Zinc-Encoding-Meta/Zinc-Encoding-Meta.html">Character Encoding and Resource Meta Description</a></strong></div></blockquote>

**Comment by Rydier** [comment]
The comment is outdated :(
If you look at HandMorph >> #generateKeyboardEvent: , you can see the 6th slot is now allocated to the Unicode code point, which is what should be used if it's been set.
You can also see in that method no processing occurs of the character code fetched, which means modern VM's no longer pass macroman, but latin1. (or there would be quite some complains due to nonfunctional keyboard input already)
At least on Windows, this *only* applies to keystroke-events, keydown/up contains virtual key codes in slot 3, and virtual key or nonsense in slot 6.

**Comment by Rydier** [comment]
Hmmm, I thought it would be linked automatically, but I needed to refamiliarize myself with the commit process anyways, so added a small pull request: 
https://github.com/pharo-project/pharo/pull/6365

**Comment by Ducasse** [comment]
Hi rydier 
welcome back :)

S.

**Comment by MarcusDenker** [comment]
PR was merged a long time ago
