### ISSUE TITLE
ZnBivalentWriteStream has some missing methods

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#6258]
![image](https://user-images.githubusercontent.com/5980033/80678638-9ca81500-8abb-11ea-91a9-2421303f92bf.png)

**Comment by svenvc** [comment]
Why would a write stream need reading methods ?

**Comment by astares** [comment]
We can dispatch (like in PR) to the underlying stream or implement the #next  this way:

```Smalltalk
next
	self shouldNotImplement
```
as in WriteStream.

see https://github.com/pharo-project/pharo/pull/6259/commits/6afd2ec7e98872febdece726989c710c944cc91d


I also wonder if ZnBivalentWriteStream  could be made a subclass of regular WriteStream

**Comment by svenvc** [comment]
I explained already many many times that the Stream hierarchy sucks.

This why I often don't subclass and often go for standalone ones (object subclasses).

I don't want to add reading methods to a write stream, it makes no sense.

This was not an oversight, this was by design, or at least author's privilege.

**Comment by astares** [comment]
Perfection is a dream and then you would need to inherit from ProtoObject.
Then lets get at least the others in. 

see https://github.com/pharo-project/pharo/pull/6259/commits/33aa5dfccdf084cbbf25840473909911feaf2689

**Comment by StephanEggermont** [comment]
I'm not sure how to solve that as long as File opens for reading if asked to open for writing but it is not allowed to.

**Comment by svenvc** [comment]
Well, I did the following:

https://github.com/svenvc/zinc/commit/965cab85d852bf2828f8b5a618730b45d5ae5e70

**Comment by astares** [comment]
@svenvc OK - thank you. This will solve it as well.

Then lets synch with next Zinc integration and close this one
