### ISSUE TITLE
RBTemporaryNode does not return the right info when in a sequence node

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#6277]
In Pharo 8 I have this method:

```Smalltalk
method
  | test |
  test := 2.
  test.
  ^test
```

First, I was surprised that we only have a RBTemporaryNode and not a distinction between temporary declaration and usage. But I can live with it. 

The problem arises when we ask the temporaries if the are definitions or read. 

I was expecting the third RBTemporaryNode of this method to be considered as read. But in reality #isRead return false and #isDefinition return true.

The problem arises from the fact that the temporary is in the sequence node defining it. In theory, only declarations should be in this sequence node, but in reality, it's possible to have useless temporaries  like the one I presented above.

**Comment by jecisc** [comment]
I found a really ugly way to know if a temporary is a declaration or not. 

```Smalltalk
aTemp parent statements includes: aTemp
```

Since the statements do not include the declaration it returns false if my temporary was a declaration. But it's really an ugly hack.

**Comment by Ducasse** [comment]
For me what I do not like is the fact that the visitor does not clearly make a difference between a declaration of definition and use, same for parameter so I'm also confused.

Now declaration are not in statements so I do not understand the bug

**Comment by jecisc** [comment]
The bug can be show with this snippet of code:

```Smalltalk 
Object compile: 'myMethod
  | test |
  test := 2.
  test.
  ^test'.

ast := (Object>>#myMethod) ast.

temps := ast allChildren select: #isTemp.

temps first isRead.
temps first isWrite.
temps first isDefinition.

temps second isRead.
temps second isWrite.
temps second isDefinition.

temps third isRead.
temps third isWrite.
temps third isDefinition.

temps fourth isRead.
temps fourth isWrite.
temps fourth isDefinition 
```

I expected this:

```Smalltalk
temps first isRead. "false"
temps first isWrite. "false"
temps first isDefinition. "true"

temps second isRead. "false"
temps second isWrite. "true"
temps second isDefinition. "false"

temps third isRead. "true"
temps third isWrite. "false"
temps third isDefinition. "false"

temps fourth isRead. "true"
temps fourth isWrite. "false"
temps fourth isDefinition "false"
```

And currently I get this:

```Smalltalk
temps first isRead. "false"
temps first isWrite. "false"
temps first isDefinition. "true"

temps second isRead. "false"
temps second isWrite. "true"
temps second isDefinition. "false"

temps third isRead. "false"
temps third isWrite. "false"
temps third isDefinition. "true"

temps fourth isRead. "true"
temps fourth isWrite. "false"
temps fourth isDefinition "false"
```

**Comment by guillep** [comment]
> El 4 may 2020, a las 12:36, CyrilFerlicot <notifications@github.com> escribió:
> 
> 
> The bug can be show with this snippet of code:
> 
> Object compile: 'myMethod
>   | test |
>   test := 2.
>   test.
>   ^test'.
> 
> ast := (Object>>#myMethod) ast.
> 
> temps := ast allChildren select: #isTemp.
> 
> temps first isRead.
> temps first isWrite.
> temps first isDefinition.
> 
> temps second isRead.
> temps second isWrite.
> temps second isDefinition.
> 
> temps third isRead.
> temps third isWrite.
> temps third isDefinition.
> 
> temps fourth isRead.
> temps fourth isWrite.
> temps fourth isDefinition 
> I expected this:
> 
> temps first isRead. "false"
> temps first isWrite. "false"
> temps first isDefinition. "true"
> 
> temps second isRead. "false"
> temps second isWrite. "true"
> temps second isDefinition. "false"
> 
> temps third isRead. "true"
> temps third isWrite. "false"
> temps third isDefinition. "false"
> 
> temps fourth isRead. "true"
> temps fourth isWrite. "false"
> temps fourth isDefinition "false"
> And currently I get this:
> 
> temps first isRead. "false"
> temps first isWrite. "false"
> temps first isDefinition. "true"
> 
> temps second isRead. "false"
> temps second isWrite. "true"
> temps second isDefinition. "false"
> 
> temps third isRead. "false"
> temps third isWrite. "false"
> temps third isDefinition. “true"
Probably related to the fact that that temp is dead code…

**Comment by MarcusDenker** [comment]
#isDefinition is not implemented nicely: it checks that the parent is a sequence, which is not enough. (normally it is, as every non-dead code use of a var embeds it into something else)

**Comment by MarcusDenker** [comment]
the current definition is:

isDefinition
	^self parent isSequence and: [ self parent defines: name ]

**Comment by jecisc** [comment]
It's exactly what I wanted to detect. Dead temporaries. But it is hard with the current implementation of the AST.
