### ISSUE TITLE
RBProgramNode>>parents is messy

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#6278]
In the Pharo AST, it is possible to get all the children of a node with the method #allChildren. 

The equivalent for the parents is a method called #parents. The name is not coherent. 

Another problem is that parents return the receiver in the list. IMO this is really wrong because a node is to its own parent. 

I propose those changes:
- Introduce #allParents returning all the parents *without* the receiver
- Introduce #withAllParents that is an equivalent of the current #parents 
- Deprecate #parents in favour of #withAllParents
- Replace the senders of #parents in the system either with #withAllParents or #allParents

**Comment by Ducasse** [comment]
agreed!

**Comment by kasperosterbye** [comment]
Just a comment.
I was wondering to do this one. I was rather confused about the `withAllParents`, what with them?. But it seems like the `withAll..` has precedence (used in `#withAllSuperclasses #withAllSubbricks #withAllOwners #withAllSuccessors #withAllSubclasses #withAllPresentations #withAllPanes #withAllSuperAndSubclasses`), so I guess it is OK

**Comment by jecisc** [comment]
Hi Kasper. 

By convention in Pharo we have:
- X : returns X at one level
- allX: return X recursively
- withAllX: return the receiver and X recursively

For example:
- subclasses: return the direct subclasses
- allsubclasses: returns all the subclasses
- withAllSubclasses: return all the subclasses and the class receiving the message
