### ISSUE TITLE
Morphics #closestPointTo: has no senders - should be deprecated

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#6282]
There are three methods called #closestPointTo: in 

- BorderedMorph
- EllipseMorph
- PolygonMorph

that have NO SENDERS. 

I think we should remove them by deprecating them first.

**Comment by Ducasse** [comment]
To me this is an API method. 
Of course Morphic is missing tests.

**Comment by pavel-krivanek** [comment]
I think we can close this issue.
