### ISSUE TITLE
Cleanup Glamour browser tabulator classes

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#6286]
Classes like

  - GLMCustomCell
     - GLMCustomColumn
     - GLMCustomRow

should have a class comment. 

Also the superclass GLMCustomCell should provide #isAbstract implementation as 
it is an abstract superclass. Only the two subclasses are used.

**Comment by Ducasse** [comment]
Pay attention that we want to remove all GT.

**Comment by astares** [comment]
@Ducasse we once wanted to remove Morphic ;) 
So for now I think it is valid
