### ISSUE TITLE
RBRuleIfNotEmptyDo seems now useless

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#6297]
**Describe the problem**
Pharo contains a rule called RBRuleIfNotEmptyDo but the methods indicated as bad by this class are no longer in Pharo. Thus, this rule is now useless. 

**Classes involved**
RBRuleIfNotEmptyDo

**Proposal**
Remove the rule.

**Version information:**
Pharo 8

**Comment by Ducasse** [comment]
Thanks for the catch
