### ISSUE TITLE
Enhance The Bug request template with Pharo version

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#6308]
**Describe the request**
Add a pharo version field in **Version information:**

**Expected behavior**
N/A

**Expected development cost**
 5 min * hourly rate of an admin of the Pharo Github

**Version information:**
Like that:
 - OS Version: [e.g. 1.6.1]
 - Pharo Version: Pharo9.0.0 build: 288, commit: bc25507

**Additional context**
N/A

**Comment by MarcusDenker** [comment]
DONE!
