### ISSUE TITLE
Enhance Completion to be more fluid in large images

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#6311]
**Describe the request**
When writing a piece of code containing a message that is not existing yet, each addition of a letter to the non existing message will take a second. It seems that each completion request triggers the creation of a new "generator" in the CoFetcher. It doesn't seems to reuse the previously generated one and should since it is the same word we are writing.

**Expected behavior**
A more fluid one

**Expected development cost**
Ask @guillep and @tesonep ;)

**Screenshots**
![LF9SxRQdVt](https://user-images.githubusercontent.com/4706329/81094471-d639af80-8f03-11ea-8ca7-38db02275072.gif)

**Version information:**
 - OS: W10
 - Version: Pharo-9.0.0+build.288.sha.bc25507fbe677d4df5f4abddb533931599c76bba (64 Bit)

**Additional context**
Only visible in large images

**Comment by VincentBlondeau** [comment]
Profiling report:
```
 - 24973 tallies, 24998 msec.

**Tree**
--------------------------------
Process: (60) Input Event Fetcher Process: InputEventFetcher>>waitForInput
--------------------------------
7.4% {1859ms} InputEventFetcher>>installEventLoop
  7.4% {1859ms} InputEventFetcher>>eventLoop
    7.4% {1859ms} InputEventFetcher>>waitForInput
--------------------------------
Process: (40) Morphic UI Process: nil
--------------------------------
88.9% {22225ms} MorphicRenderLoop>>doOneCycle
  88.9% {22225ms} WorldMorph class>>doOneCycle
    88.9% {22225ms} WorldMorph>>doOneCycle
      88.9% {22225ms} WorldState>>doOneCycleFor:
        61.6% {15390ms} WorldState>>doOneCycleNowFor:
          |59.1% {14777ms} WorldMorph>>runStepMethods
          |  |59.1% {14777ms} WorldState>>runStepMethodsIn:
          |  |  59.1% {14775ms} CoCompletionEngine(CompletionEngine)>>resetCompletionDelay
          |  |    59.1% {14775ms} CoCompletionEngine(CompletionEngine)>>openMenu
          |  |      59.0% {14751ms} NECMenuMorph class>>engine:position:
          |  |        59.0% {14747ms} NECMenuMorph>>engine:position:
          |  |          59.0% {14741ms} NECMenuMorph>>narrowCompletion
          |  |            59.0% {14740ms} NECMenuMorph>>selected:
          |  |              59.0% {14740ms} CoCompletionContext>>hasEntries
          |  |                59.0% {14740ms} CoResultSet>>notEmpty
          |  |                  59.0% {14740ms} CoFilterFetcher(CoFetcher)>>atEnd
          |  |                    59.0% {14740ms} CoFilterFetcher(CoFetcher)>>generator
          |  |                      59.0% {14740ms} Generator class>>on:
          |  |                        59.0% {14740ms} Generator>>initializeOn:
          |  |                          59.0% {14740ms} Generator>>reset
          |  |                            59.0% {14740ms} Generator>>fork
          |  |                              59.0% {14740ms} CoFilterFetcher(CoFetcher)>>generator
          |  |                                59.0% {14740ms} CoFilterFetcher>>entriesDo:
          |  |                                  59.0% {14740ms} CoAvoidRepeatedFetcher>>entriesDo:
          |  |                                    59.0% {14740ms} CoFetcherSequence>>entriesDo:
          |  |                                      59.0% {14740ms} OrderedCollection>>do:
          |  |                                        59.0% {14740ms} CoFetcherSequence>>entriesDo:
          |  |                                          59.0% {14740ms} CoFetcherSequence>>entriesDo:
          |  |                                            59.0% {14740ms} OrderedCollection>>do:
          |  |                                              59.0% {14740ms} CoFetcherSequence>>entriesDo:
          |  |                                                58.9% {14733ms} CoMappingFetcher>>entriesDo:
          |  |                                                  58.9% {14733ms} CoCollectionFetcher>>entriesDo:
          |  |                                                    58.9% {14733ms} WeakSet>>do:
          |  |                                                      56.1% {14019ms} CoMappingFetcher>>entriesDo:
          |  |                                                        |49.3% {12314ms} CoAvoidRepeatedFetcher>>entriesDo:
          |  |                                                        |  |30.2% {7553ms} IdentitySet(Set)>>add:
          |  |                                                        |  |  |22.7% {5682ms} IdentitySet(HashedCollection)>>atNewIndex:put:
          |  |                                                        |  |  |  |21.2% {5302ms} IdentitySet(HashedCollection)>>fullCheck
          |  |                                                        |  |  |  |  |19.2% {4811ms} IdentitySet(Set)>>grow
          |  |                                                        |  |  |  |  |  |19.2% {4810ms} Array(SequenceableCollection)>>do:
          |  |                                                        |  |  |  |  |  |  13.1% {3276ms} IdentitySet(Set)>>grow
          |  |                                                        |  |  |  |  |  |    |11.4% {2842ms} IdentitySet(Set)>>noCheckAdd:
          |  |                                                        |  |  |  |  |  |    |  |8.3% {2086ms} primitives
          |  |                                                        |  |  |  |  |  |    |  |3.0% {756ms} IdentitySet(HashedCollection)>>findElementOrNil:
          |  |                                                        |  |  |  |  |  |    |  |  2.8% {711ms} IdentitySet>>scanFor:
          |  |                                                        |  |  |  |  |  |    |  |    2.6% {643ms} primitives
          |  |                                                        |  |  |  |  |  |    |1.7% {434ms} primitives
          |  |                                                        |  |  |  |  |  |  6.1% {1534ms} primitives
          |  |                                                        |  |  |  |  |1.5% {368ms} SmallInteger(Magnitude)>>max:
          |  |                                                        |  |  |  |1.5% {379ms} primitives
          |  |                                                        |  |  |4.0% {1007ms} IdentitySet>>scanFor:
          |  |                                                        |  |  |  |3.7% {937ms} primitives
          |  |                                                        |  |  |3.5% {864ms} primitives
          |  |                                                        |  |15.7% {3937ms} CoAvoidRepeatedFetcher>>hasAlreadyReturned:
          |  |                                                        |  |  |15.7% {3914ms} IdentitySet(Set)>>includes:
          |  |                                                        |  |  |  15.5% {3870ms} IdentitySet(HashedCollection)>>findElementOrNil:
          |  |                                                        |  |  |    15.3% {3816ms} IdentitySet>>scanFor:
          |  |                                                        |  |  |      15.0% {3760ms} primitives
          |  |                                                        |  |2.4% {594ms} CoFilterFetcher>>entriesDo:
          |  |                                                        |  |  1.7% {431ms} CoResultSet>>filterWithString:
          |  |                                                        |  |    1.1% {272ms} ByteSymbol>>beginsWith:
          |  |                                                        |6.3% {1577ms} primitives
          |  |                                                      2.9% {714ms} primitives
          |1.3% {333ms} WorldState>>handsDo:
          |  |1.3% {333ms} Array(SequenceableCollection)>>do:
          |  |  1.3% {333ms} WorldState>>doOneCycleNowFor:
          |  |    1.3% {333ms} HandMorph>>processEvents
          |  |      1.3% {333ms} HandMorph>>processEventsFromQueue:
          |  |        1.2% {310ms} HandMorph>>handleEvent:
          |1.1% {280ms} WorldState>>displayWorldSafely:
          |  1.1% {280ms} BlockClosure>>onErrorDo:
          |    1.1% {280ms} BlockClosure>>on:do:
          |      1.1% {280ms} WorldState>>displayWorldSafely:
          |        1.1% {280ms} WorldMorph>>displayWorld
          |          1.1% {280ms} WorldState>>displayWorld:
          |            1.1% {280ms} VMWorldRenderer(AbstractWorldRenderer)>>displayWorldState:ofWorld:
          |              1.0% {257ms} VMWorldRenderer>>deferUpdatesDuring:
          |                1.0% {257ms} BlockClosure>>ensure:
          |                  1.0% {257ms} VMWorldRenderer>>deferUpdatesDuring:
          |                    1.0% {255ms} VMWorldRenderer(AbstractWorldRenderer)>>displayWorldState:ofWorld:
          |                      1.0% {255ms} VMWorldRenderer>>drawDuring:
          |                        1.0% {255ms} VMWorldRenderer(AbstractWorldRenderer)>>displayWorldState:ofWorld:
        27.3% {6835ms} WorldState>>interCyclePause:
          27.3% {6835ms} Delay>>wait
            27.3% {6833ms} BlockClosure>>ifCurtailed:
              27.3% {6833ms} Delay>>wait

**Leaves**
30.2% {7543ms} Delay>>wait
21.4% {5342ms} IdentitySet>>scanFor:
8.3% {2086ms} IdentitySet(Set)>>noCheckAdd:
7.4% {1859ms} InputEventFetcher>>waitForInput
6.3% {1577ms} CoMappingFetcher>>entriesDo:
6.2% {1545ms} Array(SequenceableCollection)>>do:
3.5% {864ms} IdentitySet(Set)>>add:
2.9% {714ms} WeakSet>>do:
1.7% {434ms} IdentitySet(Set)>>grow
1.5% {381ms} Set(HashedCollection)>>atNewIndex:put:
1.5% {374ms} SmallInteger(Magnitude)>>max:

**Memory**
	old			+268,435,456 bytes
	young		-254,953,872 bytes
	used		+13,481,584 bytes
	free		+254,953,872 bytes

**GCs**
	full			0 totalling 0ms (0.0% uptime)
	incr		12 totalling 116ms (0.0% uptime), avg 10.0ms
	tenures		0
	root table	0 overflows

```

**Comment by guillep** [comment]
A naive solution to try would be to invert the order of the filter and the avoid-repetition fetchers.
If that yields good results for your case, we could try to keep that. Otherwise we will need to timebound the search or make it async.

I'll give it a try for the first solution and come back here.

**Comment by Ducasse** [comment]
guillep
I have a question: as soon as a symbol does not exist is the completion stopped ?

I was wondering why it get slow all the time. 
Because 
p
pr -> completion
prz -> no completion
przk -> no completion

Then if you already do it I do not get why this is slow.

**Comment by guillep** [comment]
You're right!

```
59.1% {14775ms} CoCompletionEngine(CompletionEngine)>>resetCompletionDelay
          |  |    59.1% {14775ms} CoCompletionEngine(CompletionEngine)>>openMenu
          |  |      59.0% {14751ms} NECMenuMorph class>>engine:position:
          |  |        59.0% {14747ms} NECMenuMorph>>engine:position:
          |  |          59.0% {14741ms} NECMenuMorph>>narrowCompletion
          |  |            59.0% {14740ms} NECMenuMorph>>selected:
          |  |             59.0% {14740ms} CoCompletionContext>>hasEntries
          |  |                59.0% {14740ms} CoResultSet>>notEmpty
          |  |                  59.0% {14740ms} CoFilterFetcher(CoFetcher)>>atEnd
```

It looks also like the UI is calling the completion again and again using a new context!

**Comment by VincentBlondeau** [comment]
Better but still slow in our large image:

>  - 44707 tallies, 44797 msec.
> 
> **Tree**
> --------------------------------
> Process: (40) Morphic UI Process: nil
> --------------------------------
> 27.2% {12166ms} MorphicRenderLoop>>doOneCycle
>   27.2% {12166ms} WorldMorph class>>doOneCycle
>     27.2% {12166ms} WorldState class>>doDrawCycleWith:
>       27.2% {12166ms} FullBlockClosure(BlockClosure)>>ensure:
>         17.4% {7801ms} WorldMorph class>>doOneCycle
>           |17.4% {7801ms} WorldMorph>>doOneCycle
>           |  17.4% {7801ms} WorldMorph>>doOneCycleNow
>           |    17.4% {7801ms} WorldState>>doOneCycleFor:
>           |      9.1% {4076ms} WorldState>>displayWorldSafely:
>           |        |9.1% {4076ms} FullBlockClosure(BlockClosure)>>onErrorDo:
>           |        |  9.1% {4076ms} FullBlockClosure(BlockClosure)>>on:do:
>           |        |    9.1% {4073ms} WorldState>>displayWorldSafely:
>           |        |      9.1% {4073ms} WorldMorph>>displayWorld
>           |        |        9.1% {4073ms} WorldState>>displayWorld:
>           |        |          9.1% {4073ms} OSWorldRenderer(AbstractWorldRenderer)>>displayWorldState:ofWorld:
>           |        |            8.9% {4001ms} OSWorldRenderer>>deferUpdatesDuring:
>           |        |              8.9% {4001ms} OSSDL2FormRenderer>>deferUpdatesWhile:
>           |        |                8.7% {3890ms} FullBlockClosure(BlockClosure)>>ensure:
>           |        |                  8.7% {3890ms} OSWorldRenderer(AbstractWorldRenderer)>>displayWorldState:ofWorld:
>           |        |                    8.7% {3890ms} OSWorldRenderer>>drawDuring:
>           |        |                      8.7% {3890ms} OSSDL2FormRenderer>>deferUpdatesWhile:
>           |        |                        6.0% {2694ms} FullBlockClosure(BlockClosure)>>ensure:
>           |        |                          |6.0% {2694ms} OSWorldRenderer>>drawDuring:
>           |        |                          |  6.0% {2694ms} OSSDL2FormRenderer(OSWindowFormRenderer)>>drawDuring:
>           |        |                          |    6.0% {2694ms} OSWorldRenderer(AbstractWorldRenderer)>>displayWorldState:ofWorld:
>           |        |                          |      4.8% {2155ms} OSWorldRenderer>>updateDamage:
>           |        |                          |        |4.8% {2155ms} OSSDL2FormRenderer>>updateAreas:immediate:
>           |        |                          |        |  4.8% {2155ms} Mutex>>critical:
>           |        |                          |        |    4.8% {2155ms} Semaphore>>critical:
>           |        |                          |        |      4.8% {2155ms} FullBlockClosure(BlockClosure)>>ensure:
>           |        |                          |        |        4.8% {2155ms} Semaphore>>critical:
>           |        |                          |        |          4.8% {2155ms} Mutex>>critical:
>           |        |                          |        |            4.8% {2155ms} FullBlockClosure(BlockClosure)>>ensure:
>           |        |                          |        |              4.8% {2155ms} OSSDL2FormRenderer>>updateAreas:immediate:
>           |        |                          |        |                4.8% {2149ms} FullBlockClosure(BlockClosure)>>ensure:
>           |        |                          |        |                  4.8% {2132ms} OSSDL2FormRenderer>>updateAreas:immediate:
>           |        |                          |        |                    4.8% {2132ms} OSSDL2ExternalForm>>destroySurface
>           |        |                          |      1.2% {539ms} WorldState>>drawWorld:submorphs:invalidAreasOn:
>           |        |                          |        1.2% {536ms} Array(SequenceableCollection)>>do:
>           |        |                          |          1.2% {536ms} WorldState>>drawWorld:submorphs:invalidAreasOn:
>           |        |                          |            1.2% {536ms} Rectangle>>allAreasOutsideList:do:
>           |        |                          |              1.2% {536ms} Rectangle>>allAreasOutsideList:startingAt:do:
>           |        |                          |                1.2% {536ms} WorldState>>drawWorld:submorphs:invalidAreasOn:
>           |        |                          |                  1.1% {504ms} FormCanvas(Canvas)>>fullDrawMorph:
>           |        |                          |                    1.1% {504ms} FormCanvas(Canvas)>>fullDraw:
>           |        |                          |                      1.1% {504ms} TaskbarMorph(Morph)>>fullDrawOn:
>           |        |                          |                        1.1% {504ms} FullBlockClosure(BlockClosure)>>on:do:
>           |        |                          |                          1.1% {504ms} TaskbarMorph(Morph)>>fullDrawOn:
>           |        |                          |                            1.1% {504ms} FormCanvas(Canvas)>>roundCornersOf:during:
>           |        |                          |                              1.1% {504ms} FormCanvas>>roundCornersOf:in:during:
>           |        |                          |                                1.1% {504ms} TaskbarMorph(Morph)>>fullDrawOn:
>           |        |                        2.7% {1195ms} OSSDL2FormRenderer>>useDeferredUpdates
>           |        |                          2.7% {1195ms} Mutex>>critical:
>           |        |                            2.7% {1195ms} Semaphore>>critical:
>           |        |                              2.7% {1195ms} FullBlockClosure(BlockClosure)>>ensure:
>           |        |                                2.7% {1192ms} Semaphore>>critical:
>           |        |                                  2.7% {1192ms} Mutex>>critical:
>           |        |                                    2.7% {1192ms} FullBlockClosure(BlockClosure)>>ensure:
>           |        |                                      2.6% {1174ms} Mutex>>critical:
>           |      7.8% {3499ms} WorldMorph>>runStepMethods
>           |        7.8% {3499ms} WorldState>>runStepMethodsIn:
>           |          5.6% {2492ms} OSWindowMorphicEventHandler>>dispatchMorphicEvent:
>           |            |5.6% {2492ms} HandMorph>>handleEvent:
>           |            |  5.4% {2423ms} HandMorph>>sendKeyboardEvent:
>           |            |    5.4% {2423ms} HandMorph>>sendEvent:focus:clear:
>           |            |      5.4% {2423ms} HandMorph>>sendFocusEvent:to:clear:
>           |            |        5.4% {2423ms} WorldMorph>>becomeActiveDuring:
>           |            |          5.4% {2423ms} FullBlockClosure(BlockClosure)>>on:do:
>           |            |            5.4% {2423ms} HandMorph>>sendFocusEvent:to:clear:
>           |            |              5.4% {2423ms} RubEditingArea(Morph)>>handleFocusEvent:
>           |            |                5.4% {2423ms} RubEditingArea(Morph)>>handleEvent:
>           |            |                  5.4% {2423ms} KeyboardEvent>>sentTo:
>           |            |                    4.7% {2119ms} RubEditingArea(RubAbstractTextArea)>>handleKeystroke:
>           |            |                      4.7% {2119ms} RubEditingArea(RubAbstractTextArea)>>keyStroke:
>           |            |                        4.7% {2116ms} RubEditingArea(RubAbstractTextArea)>>handleEdit:
>           |            |                          4.7% {2113ms} RubEditingArea(RubAbstractTextArea)>>keyStroke:
>           |            |                            4.7% {2113ms} ClyTextEditor(RubSmalltalkEditor)>>keystroke:
>           |            |                              4.7% {2113ms} ClyTextEditor(RubSmalltalkEditor)>>completionAround:keyStroke:
>           |            |                                4.3% {1920ms} CoCompletionEngine(CompletionEngine)>>handleKeystrokeAfter:editor:
>           |            |                                  4.3% {1917ms} NECMenuMorph>>refreshSelection
>           |            |                                    4.3% {1917ms} NECMenuMorph>>selected:
>           |            |                                      3.4% {1540ms} NECMenuMorph>>itemsCount
>           |            |                                        3.4% {1540ms} CoCompletionContext>>entryCount
>           |            |                                          3.4% {1540ms} CoCompletionContext>>entries
>           |            |                                            3.4% {1540ms} CoResultSet>>first:
>           |            |                                              3.4% {1540ms} CoResultSet>>ensureResults:
>           |            |                                                3.4% {1540ms} CoResultSet>>fetch:
>           |            |                                                  3.4% {1540ms} CoFilterFetcher(CoFetcher)>>next:
>           |            |                                                    3.4% {1540ms} Array class(SequenceableCollection class)>>new:streamContents:
>           |            |                                                      3.4% {1540ms} CoFilterFetcher(CoFetcher)>>next:
>           |            |                                                        3.4% {1540ms} FullBlockClosure(BlockClosure)>>doWhileTrue:
>           |            |                                                          3.4% {1537ms} CoFilterFetcher(CoFetcher)>>next:
>           |            |                                                            3.4% {1537ms} CoFilterFetcher(CoFetcher)>>next
>           |            |                                                              3.4% {1537ms} Generator>>fork
>           |            |                                                                3.4% {1537ms} CoFilterFetcher(CoFetcher)>>generator
>           |            |                                                                  3.4% {1537ms} CoFilterFetcher>>entriesDo:
>           |            |                                                                    3.4% {1537ms} CoAvoidRepeatedFetcher>>entriesDo:
>           |            |                                                                      3.4% {1537ms} CoFetcherSequence>>entriesDo:
>           |            |                                                                        3.4% {1537ms} OrderedCollection>>do:
>           |            |                                                                          3.4% {1537ms} CoFetcherSequence>>entriesDo:
>           |            |                                                                            3.4% {1537ms} CoFetcherSequence>>entriesDo:
>           |            |                                                                              3.4% {1537ms} OrderedCollection>>do:
>           |            |                                                                                3.4% {1537ms} CoFetcherSequence>>entriesDo:
>           |            |                                                                                  2.6% {1164ms} CoFetcherSequence>>entriesDo:
>           |            |                                                                                    2.6% {1164ms} OrderedCollection>>do:
>           |            |                                                                                      2.6% {1164ms} CoFetcherSequence>>entriesDo:
>           |            |                                                                                        2.5% {1119ms} CoFetcherSequence>>entriesDo:
>           |            |                                                                                          2.5% {1119ms} OrderedCollection>>do:
>           |            |                                                                                            2.5% {1119ms} CoFetcherSequence>>entriesDo:
>           |            |                                                                                              2.5% {1119ms} CoFetcherSequence>>entriesDo:
>           |            |                                                                                                2.5% {1119ms} OrderedCollection>>do:
>           |            |                                                                                                  2.5% {1119ms} CoFetcherSequence>>entriesDo:
>           |            |                                                                                                    2.5% {1119ms} CoFetcherSequence>>entriesDo:
>           |            |                                                                                                      2.5% {1119ms} OrderedCollection>>do:
>           |            |                                                                                                        2.5% {1119ms} CoFetcherSequence>>entriesDo:
>           |            |                                                                                                          2.5% {1113ms} CoMappingFetcher>>entriesDo:
>           |            |                                                                                                            2.5% {1113ms} CoCollectionFetcher>>entriesDo:
>           |            |                                                                                                              2.5% {1113ms} WeakSet>>do:
>           |            |                                                                                                                2.2% {997ms} CoMappingFetcher>>entriesDo:
>           |            |                                                                                                                  2.0% {897ms} CoAvoidRepeatedFetcher>>entriesDo:
>           |            |                                                                                                                    1.4% {615ms} Set>>add:
>           |          2.2% {1005ms} CoCompletionEngine(CompletionEngine)>>resetCompletionDelay
>           |            2.2% {1005ms} CoCompletionEngine(CompletionEngine)>>openMenu
>           |              2.2% {1002ms} NECMenuMorph class>>engine:position:
>           |                2.2% {1002ms} NECMenuMorph>>engine:position:
>           |                  2.2% {999ms} NECMenuMorph>>refreshSelection
>           |                    2.2% {999ms} NECMenuMorph>>selected:
>           |                      2.2% {993ms} CoCompletionContext>>hasEntries
>           |                        2.2% {984ms} CoResultSet>>notEmpty
>           |                          2.2% {984ms} CoFilterFetcher(CoFetcher)>>atEnd
>           |                            2.2% {984ms} CoFilterFetcher(CoFetcher)>>generator
>           |                              2.2% {984ms} Generator class>>on:
>           |                                2.2% {984ms} Generator>>initializeOn:
>           |                                  2.2% {984ms} Generator>>reset
>           |                                    2.2% {984ms} Generator>>fork
>           |                                      2.2% {984ms} CoFilterFetcher(CoFetcher)>>generator
>           |                                        2.2% {984ms} CoFilterFetcher>>entriesDo:
>           |                                          2.2% {984ms} CoAvoidRepeatedFetcher>>entriesDo:
>           |                                            2.2% {984ms} CoFetcherSequence>>entriesDo:
>           |                                              2.2% {984ms} OrderedCollection>>do:
>           |                                                2.2% {984ms} CoFetcherSequence>>entriesDo:
>           |                                                  2.2% {984ms} CoFetcherSequence>>entriesDo:
>           |                                                    2.2% {984ms} OrderedCollection>>do:
>           |                                                      2.2% {984ms} CoFetcherSequence>>entriesDo:
>           |                                                        2.2% {984ms} CoFetcherSequence>>entriesDo:
>           |                                                          2.2% {984ms} OrderedCollection>>do:
>           |                                                            2.2% {984ms} CoFetcherSequence>>entriesDo:
>           |                                                              1.6% {738ms} CoFetcherSequence>>entriesDo:
>           |                                                                1.6% {738ms} OrderedCollection>>do:
>           |                                                                  1.6% {738ms} CoFetcherSequence>>entriesDo:
>           |                                                                    1.6% {738ms} CoFetcherSequence>>entriesDo:
>           |                                                                      1.6% {738ms} OrderedCollection>>do:
>           |                                                                        1.6% {738ms} CoFetcherSequence>>entriesDo:
>           |                                                                          1.6% {738ms} CoFetcherSequence>>entriesDo:
>           |                                                                            1.6% {738ms} OrderedCollection>>do:
>           |                                                                              1.6% {738ms} CoFetcherSequence>>entriesDo:
>           |                                                                                1.6% {738ms} CoMappingFetcher>>entriesDo:
>           |                                                                                  1.6% {738ms} CoCollectionFetcher>>entriesDo:
>           |                                                                                    1.6% {738ms} WeakSet>>do:
>           |                                                                                      1.5% {657ms} CoMappingFetcher>>entriesDo:
>           |                                                                                        1.3% {586ms} CoAvoidRepeatedFetcher>>entriesDo:
>         9.7% {4366ms} WorldState class>>doDrawCycleWith:
>           9.7% {4366ms} WorldState class>>doInterCycleWait
>             9.7% {4366ms} Delay>>wait
>               9.7% {4325ms} FullBlockClosure(BlockClosure)>>ifCurtailed:
>                 9.7% {4325ms} Delay>>wait
> --------------------------------
> Process: (60) SDL2 Event loop: [delaySemaphore wait] in Delay>>wait
> --------------------------------
> 46.8% {20978ms} OSSDL2Driver>>setupEventLoop
>   46.8% {20978ms} OSSDL2Driver>>eventLoopProcessWithoutPlugin
>     46.8% {20976ms} Delay>>wait
>       46.8% {20970ms} FullBlockClosure(BlockClosure)>>ifCurtailed:
>         46.8% {20970ms} Delay>>wait
> --------------------------------
> Process: (10) Idle Process: ProcessorScheduler class>>idleProcess
> --------------------------------
> 26.0% {11643ms} ProcessorScheduler class>>startUp
>   26.0% {11643ms} ProcessorScheduler class>>idleProcess
> 
> **Leaves**
> 56.5% {25301ms} Delay>>wait
> 26.0% {11643ms} ProcessorScheduler class>>idleProcess
> 4.8% {2132ms} OSSDL2ExternalForm>>destroySurface
> 2.9% {1286ms} Mutex>>critical:
> 1.3% {586ms} ByteSymbol(Symbol)>>=
> 
> **Memory**
> 	old			+0 bytes
> 	young		-16,039,936 bytes
> 	used		-16,039,936 bytes
> 	free		+16,039,936 bytes
> 
> **GCs**
> 	full			0 totalling 0ms (0.0% uptime)
> 	incr		24 totalling 409ms (1.0% uptime), avg 17.0ms
> 	tenures		0
> 	root table	0 overflows
>

**Comment by Ducasse** [comment]
(I'm working on fluid class and I found this one by accident) but Vincent is this issue still valid for you?

**Comment by VincentBlondeau** [comment]
(Just to make sure we are talking about the same thing, fluid here is more about fluidity :))
And yes it is still an issue expected if you worked on some improvements recently?

**Comment by Ducasse** [comment]
We did not work on completion recently. Too many glitches in recent iceberg due to migration to commander2 and spec2. So I let it open.

**Comment by Ducasse** [comment]
I tagged it for P9 so that we do not forget. We should enter a beta phase soon and it will be in the radar.

**Comment by VincentBlondeau** [comment]
Better but still slow when using backspace to remove characters from a non existing symbol.

**Comment by tesonep** [comment]
Continued in #10253
