### ISSUE TITLE
RBExtraBlockRule does not check for #cull: & co

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#6320]
RBExtraBlockRule checks evaluation messages but does not check for #cull:(cull:(cull:(cull:)))) messages.

**Comment by jecisc** [comment]
We could also add #valueWithPossibleArgs: and #valueWithPossibleArgument:

**Comment by Ducasse** [comment]
What is this rule?

**Comment by MarcusDenker** [comment]
Check for blocks that are immediately evaluated. Since the block is immediately evaluated, there is no need for the statements to be in a block.

For example, [:x | 1 + x] value: 4 is equivalent to 1 + 4
