### ISSUE TITLE
FileDialog raises an error when we want to delete a non empty folder. 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6331]
**Describe the bug**
FileDialog raises an error when we want to delete a non empty folder. 
**To Reproduce**
You can try to remove a GitHub repo when Iceberg shows you where to clone a new one. 
It is nearly impossible to remove it.

**Comment by JamesStallings** [comment]
At present, on Pharo 8 stable 64 bit, latest launcher, AMD fx4000, 32GB Arch Linux, no error is raised, but path and contents remain intact.

Identical reproduction recipe

**Comment by ackerleytng** [comment]
On the latest launcher as well, Pharo Mooc image, Arch Linux too. Even if the directory is empty, nothing appears to happen when I click the delete button.

**Comment by ackerleytng** [comment]
Oh! The delete button only works if something is selected on the right menu (File), it doesn't apply to anything selected on the left menu (Directory)
