### ISSUE TITLE
Iceberg? pasting a GitHub raises an RubExtraSelectionDecorator DNU

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6332]
**Describe the bug**
I do not know if this is a rub or an iceberg bug.

Paste 
https://github.com/pharo-mooc/PharoMoocUtils.git
into Remote URL 
![Screenshot 2020-05-10 at 22 23 19](https://user-images.githubusercontent.com/432549/81509718-08d11700-930d-11ea-9aad-d7401b464013.png)

**Comment by MarcusDenker** [comment]
I tried it with in the latest version: it now works!
