### ISSUE TITLE
Introduce displayString 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6333]
printOn: is often use to display items in list but this is not made for that. 
asString is not really made for that too. 

We should introduce displayString because it is a nice protocol. It worked well in VisualWorks 
with a clear responsibility.

**Comment by dionisiydk** [comment]
Hi Stef.

I introduced it in Pharo 7. See Object>>#displayString. Classes should
implement #displayStringOn:
Now we have many implementors of #gtDisplayOn: with same goal. We can
rename them and have most of classes covered

пн, 11 мая 2020 г. в 14:31, StéphaneDucasse <notifications@github.com>:

**Comment by astares** [comment]
+100

**Comment by noha** [comment]
This is a really good idea. +1

**Comment by Ducasse** [comment]
Thanks Denis. I would like to understand what asString is for versus printString.
May be printString is for debugger? asString is a conversion.
I also think that explicit printers like what Sven did for time/date is quite nice.

**Comment by dionisiydk** [comment]
> May be printString is for debugger?

I would say it is for development in general, not just debugging.

**Comment by Ducasse** [comment]
My point is how to make it clear to people. 
When I see the discussion around asString in the mailing-list, I'm puzzled. 

S

**Comment by pavel-krivanek** [comment]
Because `displayString` is in the system for a long time, we can close this issue.
