### ISSUE TITLE
Epicea handles badly classifications in traits

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#6335]
I wanted to recover some changes after my image crashed. I tried to use Epicea for that but I found out that Epicea does not handle nicely classifications in Traits. 

In the list, I have one change recorded for each users of the trait.

![Screenshot 2020-05-11 at 15 54 01](https://user-images.githubusercontent.com/9519971/81569536-ad039e00-939f-11ea-8089-ed50dac0c570.png)

```
Image
-----
/Users/cyrilferlicot/Documents/Pharo/images/Moose Suite 8.0 (development version)-117/Moose Suite 8.0 (development version)-117.image
Pharo8.0.0
Build information: Pharo-8.0.0+build.1136.sha.a153e04ae4e325509ed78bfe25c9ce560afb24b0 (64 Bit)
Unnamed

Virtual Machine
---------------
/Users/cyrilferlicot/Documents/Pharo/vms/80-x64/Pharo.app/Contents/MacOS/Pharo
CoInterpreter * VMMaker-CompatibleUserName.1580983506 uuid: 7aff73cb-5a2e-5002-a356-37de4e762a49 Feb 12 2020
StackToRegisterMappingCogit * VMMaker-CompatibleUserName.1580983506 uuid: 7aff73cb-5a2e-5002-a356-37de4e762a49 Feb 12 2020
VM: 202002121007 https://github.com/pharo-project/opensmalltalk-vm.git Date: Wed Feb 12 11:07:12 2020 CommitHash: 2bd9e39 Plugins: 202002121007 https://github.com/pharo-project/opensmalltalk-vm.git

Mac OS X built on Feb 12 2020 10:23:42 UTC Compiler: 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)
VMMaker versionString VM: 202002121007 https://github.com/pharo-project/opensmalltalk-vm.git Date: Wed Feb 12 11:07:12 2020 CommitHash: 2bd9e39 Plugins: 202002121007 https://github.com/pharo-project/opensmalltalk-vm.git
CoInterpreter * VMMaker-CompatibleUserName.1580983506 uuid: 7aff73cb-5a2e-5002-a356-37de4e762a49 Feb 12 2020
StackToRegisterMappingCogit * VMMaker-CompatibleUserName.1580983506 uuid: 7aff73cb-5a2e-5002-a356-37de4e762a49 Feb 12 2020

Operating System/Hardware
-------------------------
Mac OS 1014.6 x64


```

**Comment by tinchodias** [comment]
Hello Cyril. I'm sorry but I'm not sure if I understood the description. Could you please clarify a bit? Concrete steps to reproduce would help, but it may be enough if you tell me what was the expected result for that screenshot: Those `lines` methods... 
- they shouldn't be compiled  at all as methods of the `Famix*Comment` classes? 
- they are correctly compiled there but they should have other protocol/classification?

**Comment by jecisc** [comment]
Hi,

I have a trait used by a lot of classes. If I update a method of the trait, I get 1 entry in epicea by user of the trait. I would expect only one entry for the trait only.

**Comment by pavel-krivanek** [comment]
This seems to be fixed, can you confirm?

**Comment by jecisc** [comment]
I fixed some bugs on announcements with traits in P12 that probably fixed this
