### ISSUE TITLE
Ensure test classes are named in singular

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#6337]
The name of TestCase sublasses should end with "Test" and not "Tests".

We cleaned and renamed a few classes to be in correct singular form. See https://github.com/svenvc/zinc/issues/30 for an example.

Now in Pharo 9 the image is clean and consistent.

We should add a **release test** that makes sure we can keep that level of quality and do not introduce again plural names.

So I guess we should provide something like:

```Smalltalk
testTestClassesShouldBeSingular
	|violations|
	violations := Object allSubclasses select: [:each | (each inheritsFrom: TestCase)
	and: [ each name endsWith: 'Tests']].
	self assert: violations isEmpty
```

**Comment by astares** [comment]
Such a test could be in either "SUnit-Tests" package or in "ReleaseTests". I would prefer the first as it belongs to unit tests.

**Comment by olekscode** [comment]
Shouldn't it be a code critique?
e.g. whenever someone creates a class `SomethingTests`,  he or she will see a warning: "Please use `SomethingTest` instead"

**Comment by dionisiydk** [comment]
ср, 13 мая 2020 г. в 15:13, Oleksandr Zaitsev <notifications@github.com>:

> Shouldn't it be a code critique?
>
I think we have one

**Comment by astares** [comment]
@olekscode we have one - but as with all rules people can ignore them. The release tests force and ensure it is ok for the releases image
