### ISSUE TITLE
Code completion opens debugger when editing a Trait

### ISSUE THREAD

**Issue by dupriezt** [guillep/pharo-core#6341]
**Describe the bug**
When creating a Trait, the code completion heuristic raises an error which opens the debugger. It is really annoying.

**To Reproduce**
1. Create an empty package
![image](https://user-images.githubusercontent.com/32486709/81705815-bc521c80-946f-11ea-9226-afd246b2f066.png)
2. In the class creation text box, replace "Object" with "Trait" (no need to save the code)
![image](https://user-images.githubusercontent.com/32486709/81705300-303ff500-946f-11ea-849f-7c0daeb3aac4.png)
3. a `#superclass was sent to nil` error is raised, and a debugger opens.
![image](https://user-images.githubusercontent.com/32486709/81705439-536aa480-946f-11ea-8871-f3312c03b128.png)

**Expected behavior**
Being able to edit the class creation code to create a trait without a debugger opening.

**Version information:**
 - OS: Ubuntu 19.10
- Pharo 9

**Comment by hogoww** [comment]
This is also true while editing a class
