### ISSUE TITLE
SubscriptoutOfBounds while unzipping with ZipArchive

### ISSUE THREAD

**Issue by bocasti** [guillep/pharo-core#6342]
**Describe the bug**
I have a zip file looking pretty "normal"
file myzip.zip => myzip.zip: Zip archive data, at least v4.5 to extract
xxd myzip.zip => 00000000: 504b 0304 2d00 0008 0800 0468 aa50 63f1  PK..-......h.Pc....

When I do:

```
ZipArchive new 
			readFrom:'myzip.zip' asFileReference;
			extractAllTo: mydirectory
```

I get a SubscriptOutOfBounds signaled from the method ZipFileMember >> uncompressDataTo:

**To Reproduce**

It concerns a private file which I cannot "re-build" myself  

**Expected behavior**

I would expect that the file get unzipped without error

**Version information:**

Pharo 8.0.0
Build information: Pharo-8.0.0+build.1122.sha.bbcdf9770748d12e2c1b84f168f0232e4f918d20 (64 Bit)

**Expected development cost**

In order to workaround, I hacked the incriminated method and  succeeded to make my file get unzipped.
However, these are pure intuitive changes without knowing much about the ZipArchive utility :)
I will open a PR with this change

https://github.com/pharo-project/pharo/pull/6343

**Comment by MarcusDenker** [comment]
PR was merged
