### ISSUE TITLE
A different generated path for Unix and Windows

### ISSUE THREAD

**Issue by LaurineDargaud** [guillep/pharo-core#6350]
A path that begins with 'aLocation://' is recognized as a disk for Windows, but considered as a directory for Unix. It leads to errors when File References are created through `aPathString asFileReference`

**Reproduce bug**
This can be used for example, in Pillar to insert figures. 

```smalltalk
UnixStore new pathFromString: 'file://test/picture.png'.
WindowsStore new pathFromString: 'file://test/picture.png'
```
Inspect each reference: path is different
- For Unix, path is `file:/test/picture.png`
- For Windows, path is `test/picture.png`

Since Windows override the `pathFromString:` method, your code could find or not a reference according to your system...

**Comment by pavel-krivanek** [comment]
Looking at these two methods, none of them really expects the `aLocation://` prefix, and it is a misusage to expect it. The current behavior is just a coincidence. You should process it using ZnUrl.
