### ISSUE TITLE
Deprecated openModal: UIManager

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6362]
Merging raises an DNU

```
defaultAction

	| window mergeMorph |
	mergeMorph := (IceTipMergeMorph forMerger: merge).

	mergeMorph
		fromDescription: merge sourceDescription;
		toDescription: merge targetDescription.

	window := mergeMorph newWindow
		title: 'Merge';
		yourself.

	UIManager default openModal: window.
	^ mergeMorph merged
```

UIManager >> openModal: aSystemWindow is missing

```
UIManager >> openModal: aSystemWindow 
	"Open the given window at an available position with modality.
	Answer the system window."
	
	^self modalMorph openModal: aSystemWindow
```

Now I will publish the fix but I’m worried that we lost other methods. 
I do not know how to perform a blame but this is important that we check.

**Comment by Ducasse** [comment]
Guille said that the solution should be 


```
window openModal.
```

**Comment by Ducasse** [comment]
Ah ok this is in iceberg so I cannot change it. 
But may be we should have a deprecated openModal: window?

**Comment by guillep** [comment]
In general the API is

```smalltalk
window openModal.
window openModal: windowThatShouldBeBlockedByTheModal.
```

**Comment by guillep** [comment]
> Ah ok this is in iceberg so I cannot change it.
> But may be we should have a deprecated openModal: window?

Yes we could do that.

**Comment by Ducasse** [comment]
Yes I was thinking that strange to have w openModel: w :)

**Comment by Ducasse** [comment]
So I can add a deprecated method in UIManager

```
UIManager >> openModal: w
     self deprecated. 
      w openModal

```

**Comment by Ducasse** [comment]
My image is ready for that so if this is ok for you I can do it.

**Comment by Ducasse** [comment]
| foo | bar |
| --- | --- |
| baz | bim |

**Comment by MarcusDenker** [comment]
This was fixed

```
window openModal.
```

is used
