### ISSUE TITLE
Pharo rename refactoring should update references only in local methods

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#6366]
**Describe the bug**
While using the rename classes refactoring, methods comming from traits referencing the classes get recompiled in the class. 

**To Reproduce**
- create a Trait X
- create a class Y using X
- create a class Z
- Add a method to X referencing Z
- Rename Z to anything

**Expected behavior**
I expect the reference in Y to be renamed but the method is recompiled in Y also. 

I suppose the refactoring is updating the references in all methods of the class instead of doing it only in local methods.

Present in Pharo 8.

**Comment by Ducasse** [comment]
I do not really get why a rename would not impact all its users.
Did I miss something?

**Comment by jecisc** [comment]
If you rename #Toto to #Toto2, you need to update all references so that they reference Toto2 instead of Toto.

**Comment by Ducasse** [comment]
Yes that I understand and agree :) but I could not understand the sentence: "I suppose the refactoring is updating the references in all methods of the class instead of doing it only in local methods."

**Comment by jecisc** [comment]
I guess that when it collects the methods with references to the renamed class of a class, it gets all its methods, even those coming from traits. Thus when it updates the references, it recompiles the method in that class on top of recompiling it in the trait. 

But it's just a guess. I know that before I got this kind of problem in my scripts when I was using #methods instead of #localMethods

**Comment by jecisc** [comment]
I fixed the bug in my scripts.

Since I don't know Refactoring that well I don't know if it's clean enought and I don't have time to add tests.

If someone wants to fix the issue you can check https://github.com/jecisc/pharo-scripts/commit/eaa0512a0fbc69952b3fbfa3c949db08c83508ed

**Comment by jecisc** [comment]
My fix change the method RBRefactoring>>#convertAllReferencesTo:using: to reject methods from traits.

**Comment by jecisc** [comment]
Exactly the same problem happens when we rename a Class and here is my quickfix: 

https://github.com/jecisc/pharo-scripts/commit/05f89a52c31aa53156b136e682893bbad234ec81

I have the impression that RB has a lot of duplicated code
