### ISSUE TITLE
UFFI DNU:  FFIConst not understanding #emitArgument:context:

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#6368]
In the past (Pharo 7) Pharo was able to put constants into the calling spec:

```Smalltalk
self ffiCall: #(int MessageBoxA(
              HWND hWnd,
            LPCTSTR  lpText,
            LPCTSTR  lpCaption,
              MB_YESNO
        )) module: #user32
```
where MB_YESNO is from a SharedPool subclass and defined as 4

In Pharo 8 and 9 one now gets a DNU:

![image](https://user-images.githubusercontent.com/5980033/82252253-fbd8a700-994e-11ea-9b55-c85edae04377.png)

so the function spec has a FFIConstantArgument which leads to a FFIConst not understanding #emitArgument:context:

**Comment by astares** [comment]
According to a Discord discussion with @estebanlm this is due to a refactoring of @guillep to allow explicit declaration.

We should at least ensure that things do not break ... possibly give a warning like "warning: you are using a constant value without declaring type, blabla"

**Comment by astares** [comment]
To compare
```Smalltalk
self ffiCall: #(int MessageBoxA(
              HWND hWnd,
            LPCTSTR  lpText,
            LPCTSTR  lpCaption,
              4
        )) module: #user32
```
is working when the constant definition is not used

**Comment by MarcusDenker** [comment]
Can you check: there is now a method FFIConst>>#emitArgument:context: (extension method from ThreadedFFI-UFFI)

**Comment by astares** [comment]
OK - I used latest Pharo 10:

1. Create a shared pool for constants

```Smalltalk	
SharedPool subclass: #MKWAWinConstants
	instanceVariableNames: '' 
	classVariableNames: 'MB_YESNO'
	package: 'MyKiller-WindowsApp'.
```

2. Provide class side initialize method to initialize the constant

```Smalltalk	
initialize 	

	MB_YESNO := 4
```
one has to evaluate 

```Smalltalk	
MKWAWinConstants initialize 	
```
at least a single time so class var/pool gets initialized

3. Provide the class with the actual UFFI call which is using the constant:

```Smalltalk	
Object subclass: #MKWAWinMessageBox
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: 'MKWAWinConstants'
	package: 'MyKiller-WindowsApp'
```
with a class side method:
```Smalltalk	
openMessageBox: hWnd text: lpText caption: lpCaption

	self ffiCall: #(int MessageBoxA(
              long hWnd,
            char*  lpText,
            char*  lpCaption,
              MB_YESNO
        )) module: #user32
```

I can run it with

```Smalltalk
MKWAWinMessageBox openMessageBox: 0 text: 'Hello' caption: 'World'
```

**Comment by astares** [comment]
Works. So we can close this one.
