### ISSUE TITLE
Add bindings for Cairo writing PDF and SVG files

### ISSUE THREAD

**Issue by tinchodias** [guillep/pharo-core#6374]
I read in [cairo documents](https://cairographics.org/manual/cairo-PDF-Surfaces.html) that creation of PDF and SVG files is quite easy: you just need to create another type of surface that is polymorphic to the one currently used to render on screen.

I also found [an example](http://zetcode.com/gfx/cairo/cairobackends/) and [another example](http://www.ie.u-ryukyu.ac.jp/~e085739/c.cairo.3.html) showing how to do it, and confirm it shouldn't be a big effort at all to create the missing bindings in Pharo.

**Is your feature request related to a problem? Please describe.**
AFAIK, the possibility to export files could be very useful for Roassal3 visualizations.

**Describe the solution you'd like**
I already did a test and it worked. I can create a PR and let community review it.

**Describe alternatives you've considered**
Not many alternatives... the `AthensCairoPDFSurface` already exists in the image but has no references to take as an example or test.
I only had to do 2 changes:
- a cairo function (cairo_surface_finish) to `AthensCairoSurface` make it write the PDF correctly.
- fix the release (finalizeResourceData:) of this class.

**Expected development cost**
A code review may be enough.

**Comment by tinchodias** [comment]
I have it but in Pharo 8 instead of 9... bad idea because the PR has conflicts to merge in Pharo9.0 branch. I will try to create a patch and reapply in Pharo9.0.

**Comment by bencoman** [comment]
This will be really cool.  Even more cool if a follow up PR could add a SystemWindow menu entry to generate a PDF for printing.  
![image](https://user-images.githubusercontent.com/1713447/82402681-a2c45c80-9a8f-11ea-947c-a49987d5252d.png)

**Comment by tinchodias** [comment]
@bencoman: For morphs, we are much closer to have a "Export to PNG". The ideal PDF would have vector elements and this is not how morphs drawOn: generate what we see in the windows now. I may be wrong, please correct me in that case.

Of course, the PDF could have the PNG embedded inside, but I think you are not talking of that.

**Comment by tinchodias** [comment]
BTW: In the PR (#6376) I commented how to manually test this change.

**Comment by Ducasse** [comment]
Martin with athensDrawOn: I think that we can have a vector based output.

**Comment by tinchodias** [comment]
Impressive!!! I didn't know that. It worked with a small fix in the surface that I will have to push!

**Comment by tinchodias** [comment]
[3767893483184731.pdf](https://github.com/pharo-project/pharo/files/4678837/3767893483184731.pdf)

**Comment by tinchodias** [comment]
PR: #6399.

@bencoman @Ducasse
