### ISSUE TITLE
SmallInteger methods are calling for test and executable comment

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6378]
- lowBit
-highBitOfPositiveReceiver
- odd and many more deserves 
some tests in SmallIntegerTest and also executable comments.

**Comment by olekscode** [comment]
This issue was fixed in:
1. https://github.com/pharo-project/pharo/pull/6456
2. https://github.com/pharo-project/pharo/pull/6465

**Comment by olekscode** [comment]
I think it can be closed now
