### ISSUE TITLE
Athens-Examples seems hard to understand

### ISSUE THREAD

**Issue by tinchodias** [guillep/pharo-core#6383]
**Describe the problem**
Examples are quite diverse, with inconsistent class names. 
For example: `VGTigerDemo`, `AthensFlakeDemo`, `AthensSurfaceExamples`, or `AthensTextRenderManualTests`. Most of them have class-side example methods to show a rendering in either a Morphic or Spec window, but now there are also the PDF and SVG export. My point is that the prefix and suffix of these classes are inconsistent, but also the categorization in package tags.

BTW, this package has examples for Balloon, Cairo, Morphic and Spec2... this smells to circular dependencies, but in this issue I don't talk of this. 

**Classes involved**
Classes in the package Athens-Examples

**Proposal**
I will propose a rename and recategorization.

**Version information:**
Pharo 9 but this is not recent at all

**Comment by Ducasse** [comment]
100% with you!

**Comment by MarcusDenker** [comment]
fix was merged, we can close this
