### ISSUE TITLE
fileout a protocol with Calypso produces a DNU

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6390]
- select a protocol 
- extra> fileout 
- > WriteStream for not understand trailer.

```fileOut
	| internalStream class |
	internalStream := (String new: 1000) writeStream.
	internalStream
		header;
		timeStamp;
		cr.
	self methods do: [ :each | each origin printMethodChunk: each selector on: internalStream ].
	internalStream trailer.
	class := methodQuery scope basisObjects anyOne.
	^ CodeExporter writeSourceCodeFrom: internalStream baseName: class name , '-' , self name isSt: true
```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Version information:**
 - Version: [e.g. 1.6.1]

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 
In addition, are you willing to help because after all Pharo is yours too?

**Additional context**

**Comment by MarcusDenker** [comment]
new issue is here: https://github.com/pharo-project/pharo/issues/7416

I close this one
