### ISSUE TITLE
fileouting a setter save the same file than a getter in calypso

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6391]
The two methods are stored in a file with the same name so .... this is quite annoying. 
Because when you need to file out a method, it means that you need it.

**Comment by olekscode** [comment]
I'm working on this one

**Comment by olekscode** [comment]
The problem comes from here:
```Smalltalk
ClassDescription >> fileOutMethod: selector
	"Write source code of a single method on a file.  Make up a name for the file."
	
	| internalStream |
	internalStream := (String new: 1000) writeStream.
	self fileOutMethod: selector on: internalStream.
	CodeExporter writeSourceCodeFrom: internalStream baseName: (self name , '-' , (selector copyReplaceAll: ':' with: '')) isSt: true.
```
Specifically,
```Smalltalk
selector copyReplaceAll: ':' with: ''
```
I remove that statement because I think that colon is allowed in file names in all modern OS (I might be wrong about this, so let me know)

**Comment by Ducasse** [comment]
oleksandr : is not accepted on windows. 
So could you replace it with DoubleDot?
