### ISSUE TITLE
Spotter throws DNU

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#6403]
**Describe the bug**
Spotter throws DNU `Instance of ByteString did not understand #cull:` when filtering

**To Reproduce**
1. Open Spotter
2. type any letter
3. hit cmd+B (browse classes)
4. click on the 'show all' blue arrow
4. type any letter
5. See error

**Comment by Alisu** [comment]
We check with Pierre.
It appears that we set the tittle of the window as an itemFilterName which make no sense.
We don't know what should be an itemFilterName and it works without it, meaning you can have all your result and look for a particular pattern in the result list.
Thus we will remove the itemFilterName related and make a PR unless someone know what should be the itemFilterName.

Edit: the method SptSpotterProcessor>>itemFilterName does not exist on Pharo7.

**Comment by demarey** [comment]
maybe looking in pharo 7 you could see what is expected

**Comment by hogoww** [comment]
When removing it, semantically it seem right.
From my understanding, using the arrow is supposed to create a new scope.
So the first scope is the everything (?)
Second one is everything scoped with the first entry.
Which is the behavior pretty much whatever is inside the variable that I removed.

**Comment by MarcusDenker** [comment]
Seems to be fixed
