### ISSUE TITLE
Spotter show all shorcut broken

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#6404]
**Describe the bug**
In Spotter, you can see all results by clicking on the blue arrow or using the shortcut (cmd+shift+right) to start a new search.
The shortcut (cmd+shift+right) is broken

**Comment by Alisu** [comment]
The shortcut is working unless your mouse is over the blue arrow.

**Comment by MarcusDenker** [comment]
this now works with just "arrow right"
