### ISSUE TITLE
OSWindowWorldMorph no longer working in Pharo8/9 (SDL2 issue - Linux)

### ISSUE THREAD

**Issue by voxkmp** [guillep/pharo-core#6406]
An SDL error is signalled when trying to use OSWindowWorldMorph.

Clean install of Pharo 8 or 9 on a clean Linux Xubuntu 19.10 (then later 20.04)

Try evaluating OSWindowWorldMorph new open. 

Error dialog comes up - see screenshot 
![Screenshot_SDL_Error](https://user-images.githubusercontent.com/61465933/83023420-cb66cc00-a024-11ea-8d37-62b07009b3dc.png)

**Comment by Ducasse** [comment]
Thanks for reporting now you did not follow the template. So we are missing information. 
- Which version of the vm?
- How did you install it?
- Is it the plain default installation or using the headless vm?

**Comment by Ducasse** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version information:**
 - OS: [e.g. iOS]
 - Version: [e.g. 1.6.1]

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 
In addition, are you willing to help because after all Pharo is yours too?

**Additional context**
Add any other context about the problem here.

**Comment by voxkmp** [comment]
Sorry to have missed out some details.
This is a clean install from Pharo Launcher of the default Pharo 8 stable with normal VM

VM: unix - x86_64 - linux-gnu - CoInterpreter VMMaker.oscog-eem.2509 uuid: 91e81f64-95de-4914-a960-8f842be3a194 Feb  6 2019
StackToRegisterMappingCogit VMMaker.oscog-eem.2509 uuid: 91e81f64-95de-4914-a960-8f842be3a194 Feb  6 2019
VM: 201902062351 https://github.com/OpenSmalltalk/opensmalltalk-vm.git Date: Wed Feb 6 15:51:18 2019 CommitHash: a838346b Plugins: 201902062351 https://github.com/OpenSmalltalk/opensmalltalk-vm.git

Image: Pharo8.0.0 [Build information: Pharo-8.0.0+build.1124.sha.0932da82f08175e906b0e2a8052120c823374e9f (64 Bit)]


<blockquote><img src="https://avatars2.githubusercontent.com/u/19434631?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/OpenSmalltalk/opensmalltalk-vm">OpenSmalltalk/opensmalltalk-vm</a></strong></div><div>Cross-platform virtual machine for Squeak, Pharo, Cuis, and Newspeak. - OpenSmalltalk/opensmalltalk-vm</div></blockquote>

**Comment by Ducasse** [comment]
Thanks. I think that we should have a test for OSWindowWorldMorph because we did not pay attention to OSWindow in P8

**Comment by voxkmp** [comment]
Does not occur with latest headless and pharo 9
Image
-----
/home/kmp/Documents/Technical/Pharo/mars6000/Pharo.image
Pharo9.0.0
Build information: Pharo-9.0.0+build.1379.sha.41c784432d862fe44618f04ac8a6ab502e737df3 (64 Bit)
Unnamed

Virtual Machine
---------------
/home/kmp/Documents/Technical/Pharo/mars6000/pharo-vm/lib/pharo
CoInterpreter VMMaker-tonel.1 uuid: 286e9806-8e7d-0d00-ab06-4e280faf8631 Apr 30 2021
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 286e9806-8e7d-0d00-ab06-4e280faf8631 Apr 30 2021
5125110 - Commit: 5125110 - Date: 2021-04-30 10:05:04 +0200

Pharo 9.0.0 built on Apr 30 2021 10:22:47 Compiler: 5.4.0 20160609
VMMaker versionString 5125110 - Commit: 5125110 - Date: 2021-04-30 10:05:04 +0200
CoInterpreter VMMaker-tonel.1 uuid: 286e9806-8e7d-0d00-ab06-4e280faf8631 Apr 30 2021
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 286e9806-8e7d-0d00-ab06-4e280faf8631 Apr 30 2021
