### ISSUE TITLE
Two Zinc tests have timeOut on the CI

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#6409]
These two tests now time out on all 3 platforms. They work fine when I run them locally.

ZnEasyTest>>#testGetPng
ZnImageExampleDelegateTest>>#testDefaultImage

**Comment by svenvc** [comment]
In both cases the same URL is requested: http://pharo.org/files/pharo.png

Strange.

<blockquote></blockquote>

**Comment by MarcusDenker** [comment]
Maybe it is related to pharo.org now enforcing https? but then the test would fail locally, too

**Comment by MarcusDenker** [comment]
So I  tried two things:

1) use https:
2) higher timeout (10 seconds)

Still timing out.

I have no idea what this can be.

**Comment by svenvc** [comment]
There are many more external URLs called from the Zn unit tests.
Only 2 tests fail, going to the same URL.
Are we sure it is not being blocked somewhere ?

Is it possible to execute

$ curl http://pharo.org/files/pharo.png

on that CI machine to see if that works ?

<blockquote></blockquote>

**Comment by tesonep** [comment]
Hi Sven, you are right. I tried to do use curl from the CI machine and it fails. I will check what can be the problem.

**Comment by MarcusDenker** [comment]
The tests are now disabled until we get the network setup fixed. 

PR to re-enable: https://github.com/pharo-project/pharo/pull/6498

**Comment by dionisiydk** [comment]
It's now fixed
