### ISSUE TITLE
Code completion: 'thisContext': DNU #visitThisContextNode:

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#6411]
**Describe the bug**
Code completion for 'thisContext' results in DNY

**To Reproduce**
1. Go to Playground
2. type "thisContext"
3. See error

**Version information:**
 - Version: [e.g. Pharo9]

**Comment by olekscode** [comment]
This issue was moved to "Working On", then to "Done", and then back to "Ideas"
But I don't see any PR attached to it.

@guillep did you make some progress on it?

**Comment by MarcusDenker** [comment]
I moved it back because I did not see that this is done

**Comment by MarcusDenker** [comment]
(Done means that it can be closed, but it is no closed)
