### ISSUE TITLE
Refactorings: Expose ProtectInstanceVariable

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6414]
We have this refactoring but it is not exposed!

I am a refactoring for protecting instance variable access.
If a class defines methods for reading and writing instance variables, they are removed and all calls on this methods.
Omit method that are redefined in subclasses.

**Comment by Ducasse** [comment]
We should add a menu and logic to access it.

**Comment by tesonep** [comment]
This is already done
