### ISSUE TITLE
protectInstance refactoring does not seem to work. 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6469]
- create a class with an instance variable + accessors. 
- create two methods calling the accessor in the same class.
- invoke the refactoring on the instance variable. 

- we should get the calling methods should now refer to the instance variable.

**Comment by Ducasse** [comment]
The calling method got empty and the accessor removed!

**Comment by Lin777** [comment]
@Ducasse I'm not sure what problem you had with this refactoring or what is the result you want to obtain.

If I'm not mistaken, this refactoring is used to protect instance variable access. First, it searches the accessors, and then puts them in line (only in owner class), if exist senders of these methods out of owner class, the accessors won't be deleted, in other case these will be deleted of class.

**Comment by Ducasse** [comment]
Apparently this is working now.
