### ISSUE TITLE
Calypso showing method when clicking on selector

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6474]
Hi denis

Often calypso refuses to show the method pane of the method selector we click on. 
Could you fix this? because this forces the user to click again and again on the tab.

S.

**Comment by dionisiydk** [comment]
Hi Stef.

Do you have a reproducible scenario?
And what do you mean by "refuses to show the method pane"? Different tab is
selected instead?


ср, 3 июн. 2020 г. в 10:14, StéphaneDucasse <notifications@github.com>:

**Comment by pavel-krivanek** [comment]
This does not seem to be a problem anymore. I think we can close this issue.
