### ISSUE TITLE
dictionary flattened return the same result of values message

### ISSUE THREAD

**Issue by CafeKrem** [guillep/pharo-core#6479]
**Describe the bug**
flattened message send to a dictionary should not return the same thing as values message. 

**To Reproduce**
```smalltalk
|dict|
dict := { 'keyA' -> 15 .'keyB' -> 'something' } asDictionary
dict  flattened 
dict keys 
```
**Expected behavior**
I think flattened should return 
```smalltalk 
#('keyA' . 15 . 'keyB' . 'something' ) 
```
**Version information:**
 - OS: unix linux-gnu x86_64
 - Version: test on Pharo 7 and 8

**Expected development cost**
I don't know I think it can fastly

**Comment by CafeKrem** [comment]
I working on it

**Comment by CafeKrem** [comment]
I succeed to implement a simple case.
but a complex case like this one
```smalltalk
| aDictionary |
	aDictionary := Dictionary
		with: 'keyA' -> 'valueA'
		with: 'dictionary' -> (Dictionary with: 'keyB' -> 'valueB' with: 'keyC' -> 'valueC')
		with: 'keyD' -> 'valueD'.

aDictionary flattened "what should it return ?"
```
what's is behavior ?

**Comment by Ducasse** [comment]
flattened
	"Flattens a collection of collections (no matter how many levels of collections exist). Strings are considered atoms and, as such, won't be flattened"
	"( #(1 #(2 3) #(4 #(5))) flattened ) >>> #(1 2 3 4 5)" 
	"( #('string1' #('string2' 'string3')) flattened ) >>> #('string1' 'string2' 'string3')"
	
	^ Array streamContents: [ :stream | self flattenOn: stream].

so for dictionary it should be the same

**Comment by CafeKrem** [comment]
ok my bad , sorry for this useless commit but I learn something.
