### ISSUE TITLE
Serializing Objects using stateful traits fails

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#6489]
**Describe the bug**
When serializing an object using stateful traits it fails.

**To Reproduce**
1. Create a trait with an instance variable.
2. Create a class without instance variables using the trait.
3. Try to serialize it with fuel.

**Expected behavior**
It serializes the object correctly.

**Version information:**
 - OS: Any
 - Version: Pharo9

Thanks @Marmat21

**Comment by pavel-krivanek** [comment]
![image](https://github.com/pharo-project/pharo/assets/572494/2cf103df-c720-499c-8ce3-3abe80017dae)

In Pharo 13, it seems to work. Can be closed.
