### ISSUE TITLE
It is difficult to access the tag of a class

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6496]
for the moment I have to use:

```
tag := (self package classTagForClass: self) name.
tag = self package name
```
This is due to the fact that the RPackageTag logic is not nice. 
So at least we should be able to ask the class of its tag and avoid exposing such 
ugly logic. 

S.

**Comment by Ducasse** [comment]
I really do not like the logic of PackageTag
Why a packageTag is not just empty when the class does not have a tag. 
I do not get it. 
Now the package tag of a class without tag is its package. 
So ugly.
It forces clients to stupid and useless check. If you have the same name as your package that you are empty. So beautiful.

**Comment by Ducasse** [comment]
I do not really understand why RPackageTag use category :( I worked on removing category and they are reused everywhere :( so sad!

**Comment by dionisiydk** [comment]
> for the moment I have to use:
> 
> ```
> tag := (self package classTagForClass: self) name.
> tag = self package name
> ```

There is simple "aClass tags". It returns an array of tag names

**Comment by Ducasse** [comment]
And it does not help me. Sorry but I'm sick about bad design.
Why this is plural? Who decided that a class can have multiple tags?
I'm fed up of cleaning.

**Comment by dionisiydk** [comment]
вс, 7 июн. 2020 г. в 17:33, StéphaneDucasse <notifications@github.com>:

> And it does not help me. Sorry but I'm sick about bad design.
> Why this is plural? Who decided that a class can have multiple tags?
>
I proposed this plural API here (ML) and in fogbugs long time ago. The
ticket was kept opened for few months for review and nobody objected to.
I wanted to have same API for classes and methods to mark them with
multiple tags.
Currently it is always one or zero tags. But the idea was to not change API
when we will support multiple tags.
Unfortunately I also stuck with category cleanup and did not progress with
implementation.

**Comment by hernanmd** [comment]
At the moment in Pharo 12 this could be done as:

```smalltalk
('Kernel' asPackage tagOf: True) name. "#Objects"
``` 

Should we have tagNameOf: ?
Otherwise feel free to close it or comment :)

**Comment by jecisc** [comment]
This can be done with `True packageTag` also now or for the name `True packageTag name`

**Comment by jecisc** [comment]
I'll close this one since all y changes around packages are integrated and `Class packageTag` is not possible.
