### ISSUE TITLE
adding one space after #slotname and classvarname

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6499]
```
Link subclass: #Process
	slots: { #suspendedContext. #priority. #myList. #name. #env. #effectiveProcess. #terminating. #level }
	classVariables: { #PSKeys. #InheritablePSKeys. #PSKeysSema }
	package: 'Kernel-Processes'
```
=> 
```
Link subclass: #Process
	slots: { #suspendedContext . #priority . #myList . #name . #env . #effectiveProcess . #terminating . #level }
	classVariables: { #PSKeys . #InheritablePSKeys . #PSKeysSema }
	package: 'Kernel-Processes'
```

**Comment by estebanlm** [comment]
Mmm... May I ask why? I do not think the second is clearer/better than the first one.

**Comment by Ducasse** [comment]
Because like that we see the period. 
I really hate that important information is hidden and this separator is hidden not adding it BREAKS the class definition.

**Comment by Ducasse** [comment]
And also the dot is not part of the variable name. but if we want to have a Java like crappy syntax we can also add ().

**Comment by Ducasse** [comment]
I'm working on the fluid class syntax and seriously we have the possibility to improve both the code and the API.

**Comment by Ducasse** [comment]
But I can also do something else and I'm not in the mood to spend three months and that at the end we do not use it, but the class API is full of shit and brings a lot of shit in the system. 
One day we will not be able to move inside this shit anymore.

**Comment by Ducasse** [comment]
It may look nicer to glue it in the following case.
``` 
slots: { #instvar1 =>  (LazyClassVariable default: 5). instvar2 =>  (ObservableSlot default: true extras: 7). }
```

But then I will not use it in any of the future support I will write because
teachers will face the problem that students will believe that this is terminator.


They will write 
``` 
slots: { #var1 =>  (LazyClassVariable default: 5). 
#6500 var2 =>  (ObservableSlot default: true extras: 7).
}
```
thinking that this is a dot like at the end of message. But this is not 
and bam a bug in your face stupid idiot.

So I prefer that we are really explicit and write

slots: { #var1 =>  (LazyClassVariable default: 5) . var =>  (ObservableSlot default: true extras: (7))
}

Now if dynamic arrays would use something else than period I would not care.
but slots exactly use dynamic arrays and dynamic array require periods INSIDE and not at the end. I would have prefer that they use , for dynamic arrays because you do not put comma at the end of sentences. and now we get everything mixed.

**Comment by Ducasse** [comment]
And I cannot customise the space from the outside so I have to copy paste if this is not changed.

**Comment by estebanlm** [comment]
thing is, dynamic arrays receive sentences, hence the dot. 
now, this syntax is made to look like something existing? (like a dynamic array?) then it needs to have the same behaviour (or almost). 
Otherwise, let's do it radically different... because space or not space people will think this is just another dynamic array. 
And... IMHO invisible syntax alla python (forcing a space) is bad.

**Comment by astares** [comment]
Second one let the dot look like a placeholder ... which does not seem to be a good idea.

**Comment by Ducasse** [comment]
this is like a dynamic array. In a dynamic array you should not glue . to element because the parser can get confused with floats.
