### ISSUE TITLE
slotNames is defined in ClassDescription but invoked from Behavior

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6504]
Behavior >> definesSlotNamed: aString
	"Return true whether the receiver defines an instance variable named aString."
	
	^ self slotNames includes: aString

**Comment by Ducasse** [comment]
I do not understand why allSlots is not defined on behavior because classLayout is defined on Behavior. 
So I wanted to clean but I cannot so I stopped.

**Comment by MarcusDenker** [comment]
Yes, we have a lot of problems of methods in the wrong class. (even for methods that are there for a long time)

I did some cleanups from time to time there, should continue
