### ISSUE TITLE
AbstractFileReference >> directories invokes subclass method 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6505]
```
AbstractFileReference >> directories
	"Return all the directories (by opposition to files) contained in the receiver"

	| reference |
	reference := self resolve.
	^ (reference fileSystem directoryNamesAt: reference path) 
		collect: [ :aName | self withPath: self path / aName ]
```

path is not defined in AbstractFileReference

**Comment by Ducasse** [comment]
same for 

```
files
	"Return all the files (as opposed to folders) contained in the receiver"
	
	| reference |
	reference := self resolve.
	^ (reference fileSystem fileNamesAt: reference path) 
		collect: [ :aName | self withPath: self path / aName ]
```

**Comment by Ducasse** [comment]
the simplest solution is to introduce path as subclass responsibility.

**Comment by MarcusDenker** [comment]
I once looked at it and the real solution is to move the pah ivar (and accessor) up to AbstractFileReference.

This has to be done directly changing the source, though, as the code is used while doing the change and it breaks the image.

**Comment by sic-f** [comment]
@MarcusDenker how does one change directly in the source? I looked at this and it did break the image moving the `path` ivar and getter up to `AbstractFileReference`

**Comment by MarcusDenker** [comment]
It needs to be done in the checked out sources from git. (in the text files). One should be able to checkout the latest version, do the changes, and then do a PR with the change. As this PR then is bootstrapped, it will not have the problem of breaking the image.
