### ISSUE TITLE
Introduce isSpecific to avoid to have isKindOf: in hasSpecific layout

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6512]
AbstractLayout>>#isSpecific 

to avoid to have isKindOf: in 

```
Behavior >> hasSpecificLayout [
 	"Return true whether the receiver has a layout that is not a fixed one (which is the default linear layout for default classes."
 	"Point hasSpecificLayout >>> false"
 	"Array hasSpecificLayout >>> true"

 	^ (self classLayout isKindOf: FixedLayout) not
```

**Comment by bencoman** [comment]
Hi Stef,  What I don't understand is the substitution of the word "specific" for the word "fixed"?
Why not `AbstractLayout>>#isFixed`  ?

**Comment by bencoman** [comment]
Whoops. Cancel that.  I get it.  Sorry I only just noticed the "not" FixedLayout.

**Comment by MarcusDenker** [comment]
but it could test for isFixed not
