### ISSUE TITLE
Avoid duplicating reference to Smalltalk within the same class

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6515]
RBDumpVIsitorTest is hardcoding around 20 times 

```
dumpedNode := Smalltalk compiler evaluate: node dump.
```

It can be better.

**Comment by MarcusDenker** [comment]
We need an expression that returns the image default compiler.

Not the compiler of the environment of the test class (self class environment). Not the compiler of the test class itself. The image level default compiler.

I need an expression for that *and* I need to be allowed to write that.

**Comment by MarcusDenker** [comment]
Maybe we really should add thisImage like we have thisContext.

**Comment by MarcusDenker** [comment]
" Smalltalk compiler" is the only way to get the image default compiler. Yes, the rule complains. The rule is wrong.
