### ISSUE TITLE
SDL2TouchGestureExample2 -> SDL Assertion Failure and VM Crash

### ISSUE THREAD

**Issue by seandenigris** [guillep/pharo-core#6518]
**Describe the bug**
Happens after closing window and seems to be related to garbage collection (`10 timesRepeat: [ Smalltalk garbageCollect ]` seems to expedite its appearance)

**To Reproduce**
1. `SDL2TouchGestureExample2  example`
2. Close external native window
3. If error doesn't happen immediately, try `10 timesRepeat: [ Smalltalk garbageCollect ]`

**Screenshots**
<img width="626" alt="SDL assert error" src="https://user-images.githubusercontent.com/184176/84051268-e0c0ec00-a97c-11ea-8f93-8ffd10074f7d.png">

**Version information:**
 - OS: MacOS 10.14.6
 - Version: Pharo 9 w. headless VM (both via Launcher)

**Expected development cost**
Unknown

**Comment by tesonep** [comment]
It has been fixed when fixing SDL
