### ISSUE TITLE
Due to strange logic of RPackageTag

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6519]
Epicea creates different packages when replaying class defined with different tags. 
Instead of one package with multiple tags. 
This idea of RPackageTag is bogus. 
A tag is a tag and not the name of the package when there is no tag. 
This is just one way to introduce bugs!

**Comment by tinchodias** [comment]
This is not Epicea, right? 
I just tried this code and it creates two packages:
```Smalltalk
ShiftClassInstaller new makeWithBuilder: 
	(Object << #ClA
		tag: 'TagA';
		package: 'BasePackage') shiftClassBuilder.

ShiftClassInstaller new makeWithBuilder: 
	(Object << #ClB
		tag: 'TagB';
		package: 'BasePackage') shiftClassBuilder.
```

**Comment by hernanmd** [comment]
It is still reproducible in a fresh Pharo 11 image: I created a package as @tinchodias

```smalltalk
ShiftClassInstaller new makeWithBuilder: 
	(Object << #ClA
		tag: 'TagA';
		package: 'BasePackage') shiftClassBuilder.

ShiftClassInstaller new makeWithBuilder: 
	(Object << #ClB
		tag: 'TagB';
		package: 'BasePackage') shiftClassBuilder.
```
Closed the image without saving. Then re-opened the image, go to Epicea and replay all the changes.
Then this happens:

```smalltalk
RPackageOrganizer default includesPackageNamed: 'BasePackage'. "false"
RPackageOrganizer default includesPackageNamed: 'BasePackage-TagA'. "true"
RPackageOrganizer default includesPackageNamed: 'BasePackage-TagB'. "true"
```

So in Epicea the package definition includes the Tag name:

```smalltalk
Object subclass: #ClA
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'BasePackage-TagA'.

ClA class
	instanceVariableNames: ''
```

**Comment by jecisc** [comment]
Epicea now relies on packages and tags instead of categories so this should be fixed

**Comment by tinchodias** [comment]
I guess this means .ombu files are not compatible
