### ISSUE TITLE
Progress bar should not happen below the toolbar.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6520]
It is annoying
![Screenshot 2020-06-08 at 22 29 38](https://user-images.githubusercontent.com/432549/84077404-915bd980-a9d7-11ea-9b8b-42127c688b9d.png)

**Comment by astares** [comment]
There is a setting where you can change
![image](https://user-images.githubusercontent.com/5980033/84085270-7d1ed900-a9e5-11ea-901c-a2f4d45a5763.png)

but yes - there should be more distance to the toolbar / border

**Comment by Ducasse** [comment]
Ok so my next fix is probably stupid.

**Comment by Ducasse** [comment]
I will keep this issue open to see how to improve the one I blindly did. 
#6530 but we should push this other one. Because this glitch went on my nerves for real.

**Comment by astares** [comment]
@Ducasse  Agree - thanks for caring!
