### ISSUE TITLE
Iceberg/libgit asking history from calypso crashed or hangs 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6521]
May be we should remove the history button from calypso because the first time I tried
pharo crashed and the second time Pharo hangs until i'm forced to kill it.
- On mac os 14 (Mojave)

**Comment by guillep** [comment]
I'll take a look today at this.
The crash means we don't have tests for it, so I'll try to add one/some.

**Comment by Ducasse** [comment]
Cool!
