### ISSUE TITLE
Rule Super and Self Messages sent but not implemented is bogus

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6527]
![Screenshot 2020-06-09 at 21 11 06](https://user-images.githubusercontent.com/432549/84189617-d2b2be80-aa95-11ea-86d5-da56fef6ec93.png)

**Comment by Ducasse** [comment]
The rule reports that rawResultItems is not implemented but it is!. 
So we cannot trust this rule anymore :(

**Comment by dionisiydk** [comment]
It is correct Stef.
#rawResultItems is missing abstract method (#subclassResponsibility) in
superclass.

вт, 9 июн. 2020 г. в 20:12, StéphaneDucasse <notifications@github.com>:
