### ISSUE TITLE
Incomplete state of method AST

### ISSUE THREAD

**Issue by dionisiydk** [guillep/pharo-core#6532]
**Describe the bug**
I noticed a duplicated compilation of the method when it is accessed from its ast:
```Smalltalk
(Point >> #x) ast compiledMethod == (Point >> #x) " ==> false "
```
It is caused by the fact that IR instance of ast does not contain an original method instance (it's nil). 
It slows down some of critiques which access a method during ast nodes analysis.
**Expected behavior**
The script should return true.

**Version information:**
Issue exists even in Pharo 7.
**Expected development cost**
It should be simple fix: #parseAST should ensure that method is set into IR.

**Comment by Ducasse** [comment]
Thanks denis!

**Comment by MarcusDenker** [comment]
Yes.. but the problem is that "aMethod ast" does not trigger IR generation (and should not).

So the ir is not the right place to cache it.

I will check if we can do that on the AST level (or maybe as part of the CompilationContext?)

**Comment by dionisiydk** [comment]
> I will check if we can do that on the AST level (or maybe as part of the CompilationContext?)

yes. We do not have much options where to put it.

**Comment by MarcusDenker** [comment]
This has been done! https://github.com/pharo-project/pharo/pull/6669
