### ISSUE TITLE
SDL Assertion violation for OSWindowGenericRendererDrawingExample 

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#6533]
I run 

```Smalltalk
OSWindowGenericRendererDrawingExample new open
```
in Pharo 9 with latest VM. The window opens and shows the example - but when I close the second window with the rendering it the following error message is shown:

![image](https://user-images.githubusercontent.com/5980033/84240630-9d8e8680-aafe-11ea-8041-35ad51dc5ad4.png)

**Comment by astares** [comment]
Platform is Windows 
**IMAGE**
Pharo9.0.0 Build information: Pharo-9.0.0+build.340.sha.13413d82fa5875d39ac234aa2ce5939496d14a32 (64 Bit)


**VIRTUAL MACHINE**
CoInterpreter VMMaker.oscog-eem.2509 uuid: 91e81f64-95de-4914-a960-8f842be3a194 Sep 13 2019
StackToRegisterMappingCogit VMMaker.oscog-eem.2509 uuid: 91e81f64-95de-4914-a960-8f842be3a194 Sep 13 2019
VM: 201907031441-pharo Guille@DESKTOP-MG6660L:projects/vm7/opensmalltalk-vm Date: Wed Jul 3 16:41:39 2019 CommitHash: 4e4c5b5a0 Plugins: 201907031441-pharo Guille@DESKTOP-MG6660L:projects/vm7/opensmalltalk-vm

Win32 built on Sep 13 2019 15:13:35 CEST Compiler: 4.2.1 Compatible Clang 5.0.1 (tags/RELEASE_501/final)
VMMaker versionString VM: 201907031441-pharo Guille@DESKTOP-MG6660L:projects/vm7/opensmalltalk-vm Date: Wed Jul 3 16:41:39 2019 CommitHash: 4e4c5b5a0 Plugins: 201907031441-pharo Guille@DESKTOP-MG6660L:projects/vm7/opensmalltalk-vm
CoInterpreter VMMaker.oscog-eem.2509 uuid: 91e81f64-95de-4914-a960-8f842be3a194 Sep 13 2019
StackToRegisterMappingCogit VMMaker.oscog-eem.2509 uuid: 91e81f64-95de-4914-a960-8f842be3a194 Sep 13 2019

**Comment by voxkmp** [comment]
Looks like th same issue I reported
https://github.com/pharo-project/pharo/issues/6406

**Comment by MarcusDenker** [comment]
I close this as a duplicate
