### ISSUE TITLE
Welcome screen is corrupted

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#6540]
**Describe the bug**
![image](https://user-images.githubusercontent.com/4706329/84267196-f6254a00-ab25-11ea-88ac-c735a7ad085f.png)

**To Reproduce**
open image

**Expected behavior**
![image](https://user-images.githubusercontent.com/4706329/84267291-1b19bd00-ab26-11ea-9460-f493edc75a30.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/4706329/84267229-00474880-ab26-11ea-903d-24727642a044.png)

**Version information:**
 - OS: win10
 - Version: Pharo9.0.0
build: 348, commit: 9675774 - last vm for the image

**Expected development cost**
IDK

**Comment by kasperosterbye** [comment]
I am on mac. Not able to reproduce it in Pharo9.0.0 build: 386, commit: 0b06d20.

**Comment by MarcusDenker** [comment]
This seems to be happen for some builds but not others.

**Comment by astares** [comment]
Mentioned it on Discord on the 11th, had it on Ubuntu

![image](https://user-images.githubusercontent.com/5980033/85116061-040d5600-b21d-11ea-9741-f8a8d7c06232.png)

**Comment by MarcusDenker** [comment]
this is now ok
