### ISSUE TITLE
#defaultTimeout has no senders. The method for tests is called defaultTimeLimit

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#6541]
You can implement #defaultTimeLimit on the class side of a test. The default is 10 seconds.

But there are #defaultTimeout methods that should have been defaultTimeLimit instead.

TODO: remove all defaultTimeLimit that make no sense, change the ones in tests to be #defaultTimeLimit

It would be nice to have a pragma to set it per tests, too (but that is another TODO)

**Comment by dionisiydk** [comment]
> It would be nice to have a pragma to set it per tests, too (but that is another TODO)

Maybe pragma is good to have but currently you can just call "self timeLimit: 1 minutes" directly in the test or setUp (at any time during test)
