### ISSUE TITLE
Browser selects default tab when selection is changed instead of current one

### ISSUE THREAD

**Issue by dionisiydk** [guillep/pharo-core#6571]
**Describe the bug**
Browser does not keep the selected tab when selection in lists is changed.
**To Reproduce**
- Browse Announcer class.
- Select Comment tab
- Select Announcement class

Browser will show definition tab for Announcement class
**Expected behavior**
Browser should show a Comment tab as previously selected.

**Version information:**
Pharo 9.

**Expected development cost**
It is related to new notebook widget which does not support some of expected API in same way like it was with old widget.
It should not be difficult to fix. It just requires a debugging session.

**Comment by Ducasse** [comment]
Denis do you have an idea where this bug can come from?

**Comment by dionisiydk** [comment]
@Ducasse if fixed it in PR #6716. See commits f459b8e and 1c2fdee :
New notebook widget incorrectly passed selection indexes in notification methods (the argument with old index was always a current one).
Can I ask why a new widget was implemented instead of improving current one? We also loose multiple tab selection with this change (no comment+method or two methods at same time now)
