### ISSUE TITLE
SpDemoTest should close the open windows

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#6595]
**Describe the problem**
If the test fails for timeout reasons, the window IV is not set and the window is not closed

**Classes involved**
SpDemoTest 

**Proposal**
Use the presenter IV to close the window

**Version information:**
Latest

**Expected development cost**
done

**Comment by MarcusDenker** [comment]
I reverted the change, it lead to the tests not finishing (very strange)

**Comment by MarcusDenker** [comment]
this is fixed, the window is closed
