### ISSUE TITLE
Inconsistent Unit test results once "become:" is part of source code

### ISSUE THREAD

**Issue by HeSe** [guillep/pharo-core#6597]
The usage of become: within a testcase results in asserts to fail or pass after modifying the test sourcecode and/or browsing within the same system browser. 

1. load the attached source code into the image.
2. run the test contained in ValueHolderTestCase (it may pass or fail with: "TestFailure: Got '13' instead for 'Test3'")
3. Remove the comment within the test method and save method.
4. Within the System Browser navigate to the ValueHolderTestClass and
back to ValueHolderTestCase again.
5. run the test contained in ValueHolderTestCase (it may pass or fail with: "TestFailure: Got '13' instead for 'Test3'")

This issue appeared in:
 - OS: Windows 10
 - Pharo base image: Pharo-8.0.0+build.1124.sha.0932da82f08175e906b0e2a8052120c823374e9f (64 Bit)

`'From Pharo8.0.0 of 22 January 2020 [Build information: Pharo-8.0.0+build.1124.sha.0932da82f08175e906b0e2a8052120c823374e9f (64 Bit)] on 13 June 2020 at 10:20:33.617211 pm'!
TestCase subclass: #ValueHolderTestCase
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Become-Test'!

!ValueHolderTestCase methodsFor: 'tests' stamp: 'SebastianHeidbrink 6/13/2020 22:20'!
testValueChangeBasicType
	| holder1 holder2 string |
	holder1 := ValueHolderTestClass new.
	holder2 := ValueHolderTestClass new.
	
	string := 'Test'.
	holder1 value1: string.
	holder2 value1: string.
	self assert: holder1 value1 equals: 'Test'.
	self assert: holder2 value1 equals: 'Test'.
	
	string become: '1'.
	self deny: holder1 value1 equals: '1'.
	self deny: holder2 value1 equals: '1'.
	
	string := '2'.
	self deny: holder1 value1 equals: '2'.
	self deny: holder2 value1 equals: '2'.
	
	self deny: holder1 value1 equals: '1'.
	self deny: holder2 value1 equals: '1'.
	
	holder1 value1: holder1 value1 , '3'.
	holder2 value1: holder2 value1 , '3'. 
	"remove or replace this comment with cr.
	Switch to ValueHolderTestClass in same system browser and back.
	Rerun this test
	The following assert will fail with '13' 
	Reintroducing the comment may make this test pass again"
	self assert: holder1 value1 equals: 'Test3'.
	self assert: holder2 value1 equals: 'Test3'! !
`
`'From Pharo8.0.0 of 22 January 2020 [Build information: Pharo-8.0.0+build.1124.sha.0932da82f08175e906b0e2a8052120c823374e9f (64 Bit)] on 13 June 2020 at 10:12:08.905211 pm'!
Object subclass: #ValueHolderTestClass
	instanceVariableNames: 'holder1 holder2 holder3'
	classVariableNames: ''
	package: 'Become-Test'!

!ValueHolderTestClass methodsFor: 'accessing' stamp: 'SebastianHeidbrink 6/13/2020 20:10'!
value2: anObject
	holder2 value: anObject! !

!ValueHolderTestClass methodsFor: 'accessing' stamp: 'SebastianHeidbrink 6/13/2020 21:33'!
value1
	^holder1 value! !

!ValueHolderTestClass methodsFor: 'accessing' stamp: 'SebastianHeidbrink 6/13/2020 20:08'!
holder1: anObject
	holder1 := anObject! !

!ValueHolderTestClass methodsFor: 'accessing' stamp: 'SebastianHeidbrink 6/13/2020 20:10'!
value1: anObject
	holder1 value: anObject! !

!ValueHolderTestClass methodsFor: 'accessing' stamp: 'SebastianHeidbrink 6/13/2020 21:33'!
value2
	^holder2 value! !

!ValueHolderTestClass methodsFor: 'accessing' stamp: 'SebastianHeidbrink 6/13/2020 21:33'!
value3
	^holder3 value! !

!ValueHolderTestClass methodsFor: 'accessing' stamp: 'SebastianHeidbrink 6/13/2020 20:08'!
holder2: anObject
	holder2 := anObject! !

!ValueHolderTestClass methodsFor: 'accessing' stamp: 'SebastianHeidbrink 6/13/2020 20:08'!
holder2
	^ holder2! !

!ValueHolderTestClass methodsFor: 'accessing' stamp: 'SebastianHeidbrink 6/13/2020 20:08'!
holder1
	^ holder1! !

!ValueHolderTestClass methodsFor: 'accessing' stamp: 'SebastianHeidbrink 6/13/2020 20:11'!
initialize

	super initialize.
	holder1 :=  NewValueHolder new.
	holder2 :=  NewValueHolder new.
	holder3 :=  NewValueHolder new.! !

!ValueHolderTestClass methodsFor: 'accessing' stamp: 'SebastianHeidbrink 6/13/2020 20:08'!
holder3
	^ holder3! !

!ValueHolderTestClass methodsFor: 'accessing' stamp: 'SebastianHeidbrink 6/13/2020 20:08'!
holder3: anObject
	holder3 := anObject! !

!ValueHolderTestClass methodsFor: 'accessing' stamp: 'SebastianHeidbrink 6/13/2020 20:10'!
value3: anObject
	holder3 value: anObject! !
`

**Comment by svenvc** [comment]
Aren't you changing literal constants ?

Try making copies of your constant strings.

```
string := 'test' copy.
```

**Comment by MarcusDenker** [comment]
Back in the days I managed to waste a day on something like this...  (we should again look into making strings read only that are literals, the code is there...)
