### ISSUE TITLE
CI: not running on all three platforms

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#6600]
**Describe the bug**
CI does not run

**Additional context**
See https://github.com/pharo-project/pharo/pull/6596

2 issues on the CI:

- OSX: wget is not in the PATH of the slave. But it is installed on the server when logging is as the ci user. The right path should be added to the jenkins slave agent. I do not know how to do that properly.

- Unix + Windows: the build takes more than 35 mins to run so fall into timeout. We could increase the timeout period but I'm not sure that is what we would like.

**Comment by MarcusDenker** [comment]
seems to work again

**Comment by guillep** [comment]
@demarey installed two new slaves (one windows 10, one osx) so may be due to that
