### ISSUE TITLE
"#commonSuperclassWith: was sent to nil" windows opens after each character typed in

### ISSUE THREAD

**Issue by riVDM** [guillep/pharo-core#6631]
**Describe the bug**
While editing say a method a (debug??) window opens after each character typed in (except space or backspace..)

**To Reproduce**
1. Select one instance method
2. Start editing it
3. Window opens

**Expected behavior**
Nothing, just continue source edition

**Screenshots**
![PharoBugReport](https://user-images.githubusercontent.com/67067876/84927356-ffd22300-b0cc-11ea-8600-da6d6b1714dd.png)
**Version information:**
 - MAC OS X Sierra
 - Version: Pharo 8 64bits (stable)
 - Launched by PharoLauncher (GToolkitOSX64 version)

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? No idea!
In addition, are you willing to help because after all Pharo is yours too? I am willing to provide any information about the bug but i could not do more than that

**Additional context**
This bug appeared after weeks of using Pharo.

**Comment by MarcusDenker** [comment]
can you try to add this method to UndefinedObject:


commonSuperclassWith: aClass 
	^ self


(I think this is already fixed in Pharo8 "latest" (that is the last code base, which is not yet tagged "stable")

**Comment by riVDM** [comment]
Just to be sure, i add this method as instance method in UndefinedClasses -> core?

**Comment by MarcusDenker** [comment]
UndefinedObject, the class fo nil. In the class hierarchy, we terminate with nil as the superclass.

**Comment by riVDM** [comment]
I added 

commonSuperclassWith: aClass
^ self

to UndefinedObject

and the problem seems to be disappeared.

Thanks!

Richard
  Van de Moosdijk

**Comment by MarcusDenker** [comment]
Good! This means we can close the issue as this method in both in Pharo8 latest and Pharo9
