### ISSUE TITLE
Introduce prefix for reflection related classes

### ISSUE THREAD

**Issue by dionisiydk** [guillep/pharo-core#6648]
I think it would be better to have reflectivity prefix RF (or another one) for all related classes like RBWatch, RFBreakpoint, RFMetalink, RFPermalink, ...
Maybe some of them deserve "naked" name like Metalink and Breakpoint. But for example  recently introduced (renamed) Watch class could lead to conflict to some domain.
For consistency I would push prefix for all of them. 
  
**Expected development cost**
It will be simple rename refactoring which probably does not require deprecation as it is very specific part of system.

**Comment by Ducasse** [comment]
Yes I like the idea!

**Comment by guillep** [comment]
This issue looks more like a small project than an actionable issue.
I propose we move it to a wiki with potential projects for people to contribute.
I'm collecting all these.
Could be a great basis for GSOC.

**Comment by astares** [comment]
Pharo and namespaces? 😉
