### ISSUE TITLE
PanelMorph does not implement table and crashes the image

### ISSUE THREAD

**Issue by oliveiraallex** [guillep/pharo-core#6659]
**Describe the bug**
PanelMorph does not implement table. You send #table to self, but that then sends it on

**To Reproduce**
Even the example in the FTCellMorph crashes the image with
```
FTCellMorph new
	addMorphBack: 'Example' asMorph;
	withTopSeparator;
	openInWindow.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/39618015/85403860-5c668f80-b55e-11ea-8c0c-107dea477eed.png)

**Version information:**
 - Pharo8/9

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 
Easy
In addition, are you willing to help because after all Pharo is yours too? 
Yes

**Additional context**
This is broken the PharoThings board inspector on Pharo8/9.

**Comment by MarcusDenker** [comment]
Not a bug, as described in https://github.com/pharo-project/pharo/pull/6660
