### ISSUE TITLE
Loading Spec generates an error

### ISSUE THREAD

**Issue by riVDM** [guillep/pharo-core#6672]
**Describe the bug**
Hi,
I tried to install Spec by running the following script (found on "https://github.com/pharo-spec/Spec") but i get this error and the installation hangs up

Metacello new
        githubUser: 'pharo-spec' project: 'Spec' commitish: 'master' path: 'src';
        baseline: 'Spec2';
        onConflict: [ :e | e useIncoming ];
        onUpgrade: [ :e | e useIncoming ];
        ignoreImage;
        load

**To Reproduce**
1. Open a Playground
2. Paste the script
3. Do it

**Expected behavior**
Installation should complete

**Screenshots**
![SpecError](https://user-images.githubusercontent.com/67067876/85557602-36a5bd00-b628-11ea-9341-c4b3e6222c59.png)

**Version information:**
 - OS: Mac OS X Sierra
 - Pharo 8 64 bit stable

**Expected development cost**

**Additional context**

Thanks for any help

Richard

**Comment by estebanlm** [comment]
Spec2 will not load in Pharo 8, you need Pharo 9.

**Comment by riVDM** [comment]
Problem solved: Spec2 runs only on Pharo 9
