### ISSUE TITLE
SyntaxErrorDebugger does not work properly

### ISSUE THREAD

**Issue by dionisiydk** [guillep/pharo-core#6674]
**Describe the bug**
I found that syntax error debugger does not really work for a long time (I checked from Pharo 4).
The debugger allows to fix the problem source code in the editor. But accepting changes produces incorrect result:
- it does not close the editor (like it was in Pharo 8 and early)
- it compiles the method but with original bad sources. (you can see it in the browser and check #decompile to prove that fixed text was used to compile it) .

**To Reproduce**
In playground call: 
```Smalltalk
Announcer compile: 'badMethod
^'
```
In opened editor fix the text to make it correct smalltalk syntax (add any literal at the end)
Now accept changes (cmd+s).
Browse Announcer and select new method. You will see bad sources and get another syntax error (from highlighting). 

**Expected behavior**
- Accepting changes should close editor and proceed compilation.
- compiled method should point to actual sources which it was created with.

**Expected development cost**
It should not be difficult if you are familiar with SyntaxErrorNotification and compiler.

**Comment by MarcusDenker** [comment]
One idea: why do we not allow these to be loaded?


If we add to OpalCompiler:

isInteractive
	^self isInteractiveFor: compilationContext requestor

and then change the method:		
		
parseMethod
	
	^ (self compilationContext optionParseErrors or: [ self isInteractive not ])
		ifTrue: [self parserClass parseFaultyMethod: source contents]
		ifFalse: [self parserClass parseMethod: source contents]

==> methods like that can just be loaded. The syntax error is compiled to be raised at runtime (and there it is not working, too).
But 99% of all cases where we load syntactically incorrect code we will not execute it, so it would be a huge step even without fixing the the tool (which we should do, too)

**Comment by dionisiydk** [comment]
I definitely agree about it. Users will fix incorrect syntax in the browser like any other issue.
+100 for removing all this complex machinery for syntax correction in fly. It did not work for a long time and nobody complain.

**Comment by dionisiydk** [comment]
Also it will help to resolve circular dependency between AST and Compiler (which is why I really found this problem)

**Comment by MarcusDenker** [comment]
and at runtime we can just raise a RuntimeSyntaxError, which would be a subclass of Halt.

**Comment by MarcusDenker** [comment]
I merged the PR... there are of course lots of cleanup steps and lots of "next steps", but this issue is fixed.

(the SyntaxErrorDebugger itself is not yet removed, but it is only used for expressions (doit) where it is used even less and it actually works...)
