### ISSUE TITLE
MetaLinkAnonymousClassBuilderTest>>#testWeakMigratedObjectsRegistry failing randomly on CI

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#6677]
After merging https://github.com/pharo-project/pharo/pull/6673

MetaLinkAnonymousClassBuilderTest>>#testWeakMigratedObjectsRegistry  fails sometimes

"value nil not found in MetaLinkAnonymousClassBuilder"

Error
value nil not found in MetaLinkAnonymousClassBuilder
Stacktrace
ValueNotFound
value nil not found in MetaLinkAnonymousClassBuilder
MetaLinkAnonymousClassBuilder>>soleInstanceOf:
[builder soleInstanceOf: anonClass] in MetaLinkAnonymousClassBuilderTest>>testWeakMigratedObjectsRegistry
[aBlock value.
false] in MetaLinkAnonymousClassBuilderTest(TestAsserter)>>executeShould:inScopeOf:
FullBlockClosure(BlockClosure)>>on:do:
MetaLinkAnonymousClassBuilderTest(TestAsserter)>>executeShould:inScopeOf:
MetaLinkAnonymousClassBuilderTest(TestAsserter)>>should:raise:
MetaLinkAnonymousClassBuilderTest>>testWeakMigratedObjectsRegistry
MetaLinkAnonymousClassBuilderTest(TestCase)>>performTest

@StevenCostiou

**Comment by StevenCostiou** [comment]
I'm on it. Strange because the test **is** supposed to raise a `ValueNotFound`.

**Comment by StevenCostiou** [comment]
Ok I got it :)
Making an PR asap.
