### ISSUE TITLE
Menu bar vanishes when installing with catalog browser

### ISSUE THREAD

**Issue by SebastianMpl** [guillep/pharo-core#6679]
Hello,

Just tried Pharo v 9.0 b 418 64bit (on Gnu/Linux) and when I try to install something (Teapod - it fails) via catalog browser, when installation fails the menu bar is gone.

How to reproduce:
1. Just use catalog browser to install something (in my case Teapot) via Catalog browser
2. Look at the menu bar - it should disappear.

**Comment by Ducasse** [comment]
Thanks for the report.

**Comment by MarcusDenker** [comment]
as the catalog was removed, this can be closed
