### ISSUE TITLE
Dictionary creation API should accept associations too.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6719]
Often we have list of key value pairs and we do not have have to 

```
Dictionary class >> newFromAssociations: anAssocCollection
	"return a dictionary with the Associations in anAssocCollection.
	If the same key appears twice in anAssocCollection, the last one enumerated will win"
	
	^ anAssocCollection 
		inject: Dictionary new 
		into: [ :dict :assoc | dict add: assoc. dict ]
```

**Comment by Ducasse** [comment]
We should also add a test in the vein of 

```
testNewFromAssociations
 
	| newDict |
        pairs := OrderedCollection new. 
	pairs := self nonEmptyDict keysAndValuesDo: [:k :v | pairs add: (k -> v) ].
	newDict := self classToBeTested newFromAssociations: pairs.
	self nonEmptyDict keysAndValuesDo: [:k :v|
		self assert: (newDict at: k) equals: v ]. 
```

**Comment by dionisiydk** [comment]
Maybe we should fix #withAll: which works quite strange:
```Smalltalk
Dictionary withAll: { #key1->#value1. #key2->#value2 }
```
Now the result is a dictionary with new associations: 1->(#key1 -> value1), 2-> (#key2 -> #value2).

**Comment by weslleymberg** [comment]
Hi @Ducasse  and @dionisiydk .

Today `Dictionary>>add:` expects an association as a parameter while `Dictionary>>addAll:` expects a keyed collection. I think this makes the dictionary's api a little inconsistent.
If we change `addAll:` to accept a collection of associations, we will make the api more intuitive; at the same time, `withAll:` will work correctly and we won't need a new method to create a dictionary from associations.

What do you think?
