### ISSUE TITLE
Dictionary >> newFrom: logic can be improved. 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6720]
```
Dictionary >> newFrom: aDict 
	"Answer an instance of me containing the same associations as aDict.
	 Error if any key appears twice."
	| newDictionary |
	newDictionary := self new: aDict size.
	aDict associationsDo:
		[:x |
		(newDictionary includesKey: x key)
			ifTrue: [self error: 'Duplicate key: ', x key printString]
			ifFalse: [newDictionary add: x]].
	^ newDictionary
```

I do not get why we test because how the source dictionary can contain two keys with the same name. 
Since newFrom: expects a dictionary then it is not possible. 
Am'I missing something obvious?

In addition we could change this method to take advantage of #6719

**Comment by bstjean** [comment]
Another curious point : what's the difference besides #newFrom: and a copy of the dictionary?  Am I missing something too?

**Comment by Ducasse** [comment]
:) yes I have no idea. And it would be good to have executable comments and not bogus one.

**Comment by Ducasse** [comment]
I checked and copy does not work because some tests are passing an empty array. 
So for now I just removed the extra test

**Comment by Ducasse** [comment]
Related to #6945

**Comment by Ducasse** [comment]
I think that we should check and add newFromAssociation: and newFrom: aDict should just perform a copy.

**Comment by MarcusDenker** [comment]
```
Dictionary newFrom: {1->#a. 2->#b. 3->#c}
```
Works, too. Array implements associationsDo:

So it seems to be just a matter of updating the documentation.

The duplication check is there if the argument is not a Dictionary, but an array of associations.

**Comment by MarcusDenker** [comment]
#11166 improved the argument name and adds an example that shows that it works already to take an association.

But the error I do not like: we should think of doing the same as newFromAssociations: 
"If the same key appears twice in anAssocCollection, the last one enumerated will win"
