### ISSUE TITLE
The completion menu on wrong position

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#6721]
**Describe the bug**
With some method AST shape, the completion menu can appear on a wrong position and effectively cover the text cursor. Very likely, coments are involved.

**To Reproduce**
1. start with a new method with this content:
```smalltalk
testIssue
	"co"	
	self issue
```
2. move your cursor at the end of the comment text `co` and type something, e.g. the letter `o`
3. the completion menu covers the text cursor position

**Expected behavior**

**Screenshots**
![9TnlapUnTf](https://user-images.githubusercontent.com/572494/85954648-52d39200-b979-11ea-9ce4-b90add9350c9.gif)

**Version information:**
- Pharo-9.0.0+build.429.sha.f6ec1c1c84a72a96948b1556071612747675448f (64 Bit)

**Comment by guillep** [comment]
Yes, I was about to take a look at it on friday but I got out of time.
I plan to work on it this week.

**Comment by guillep** [comment]
I've a fix to propose that gives the following feeling:

![image](https://user-images.githubusercontent.com/708322/86000392-c921d400-ba0d-11ea-988a-b2192a05e6a1.png)

The problem behind this is that the token used to complete (and thus its position in the text) is determined by the AST.
And comments are not part of the AST, so it messes up with selection, caret positioning and it impacts also in the position popup (which is decided based on the current completion token).

I'll propose a fix that uses the actual current token (i.e., the text between the caret and the first separator that precedes it) independently of the AST. Then AST nodes are then used to give semantic meaning to that token (e.g., is this a variable? a message?), and propose what to search from that semantic meaning.

**Comment by MarcusDenker** [comment]
another idea (indpended) is to turn off completion for comments...

**Comment by guillep** [comment]
Yes, but the AST does not tell us so far if we are in a comment or not.

**Comment by MarcusDenker** [comment]
offsetIsComment: anOffset
	"check is the offset in the source part of a comment"

	^ self allComments
		anySatisfy: [ :comment | anOffset between: comment start and: comment stop ]


I will do a PR with tests... (and think about a better method name)

**Comment by guillep** [comment]
Maybe `nodeForOffset:` could return a comment node if we are in a comment... I understand that comments are semantically no-ops, and that they are kind of unstructured as they can be anywhere. But today they are not first class citizens as the other AST pals, and I think they should be :) In a smart way, but they should be.

**Comment by MarcusDenker** [comment]
Yes, nodeForOffset: could just return the Comment (we have all the infos for that), we could even enable visiting the comments with the visitor.

I will for now do the #offsetIsComment: as it is much less intrusive
