### ISSUE TITLE
Browsing any class in Calypso raises a debugger

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#6722]
**Describe the bug**
Selecting any class raises an error in `SpNotebookMorph>>#updatePageIndex:oldIndex:`

**To Reproduce**
1. Open Calypso
2. Select any class
3. `SubscriptOutOfBounds: 2` 

**Version information:**
 - Pharo-9.0.0+build.429.sha.f6ec1c1c84a72a96948b1556071612747675448f (64 Bit)

**Comment by estebanlm** [comment]
this is weird and clearly not a problem of `SpNotebookMorph` (since it didn't change since a lot).
Something related to re

**Comment by estebanlm** [comment]
this is weird and clearly not a problem of `SpNotebookMorph` (since it didn't change since a lot).
Something related to recent changes?

**Comment by estebanlm** [comment]
(sorry, closing it was a kb problem)

**Comment by dionisiydk** [comment]
Hm, it is related to my recent fix. Probably not all changes were committed somehow.
