### ISSUE TITLE
ShiftClassBuilder does not recompile SharedPool users when it changes

### ISSUE THREAD

**Issue by dionisiydk** [guillep/pharo-core#6778]
**To Reproduce**
Check in playground that following is true: 
```Smalltalk
(Duration>>#asNanoSeconds) literals first == 
(ChronologyConstants classPool associationAt: #NanosInSecond )
```
Go to ChronologyConstants and add new class variable (TestClassVar).
Now check the first expression. It will be false. That is the bug. 
Class builder creates new instances of class variables when definition is changed and all users of shared pool ChronologyConstants become pointing to old ClassVariable instances. 
**Expected behavior**
System should either keep existing variable instances or recompile methods to maintain consistent state.
**Expected development cost**
For those who are familiar with ShiftClassBuilder it should not be difficult to do. First add test (we have a good test suite for such cases)

**Comment by dionisiydk** [comment]
Another scenario: 
- try to add some new class var into pool (like before)
- create using method in Duration (it imports this pool)
- remove this class var from the pool definition

Now check that Duration method will keep ClassVariable instance inside literals. But it should be recompiled with UndeclaredVariable

**Comment by MarcusDenker** [comment]
this was fixed
