### ISSUE TITLE
literalsDo: check all senders as it omits full blocks

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#6791]
With the full block model, we have a problem: low level methods like #literalsDo: now just check the main method.

This is a general problem: the CompiledMethod now stands for two concepts: the bytecode of the method itself, and the "concept of being a method in the system".

**Comment by Ducasse** [comment]
Ok I understand the point is that the literal/byte analysis does not take into account full block closure. 
It means that we should have tests for such methods.

**Comment by MarcusDenker** [comment]
ups, no: all the literals* methods should *not* dive deep, we should keep that as the "this shows reality" level of the API.

(this would all be soooo much easier if we would model CompiledMethod better: have a true source ivar, have a ByteArray for the bytecode, add *all* symbols of sends to the literal array... and most of the code would be trivial.
