### ISSUE TITLE
Replace the catalog by Pharo-Compendium

### ISSUE THREAD

**Issue by bergel** [guillep/pharo-core#6808]
**Describe the request**
The catalog tool is outdated and not really useful.

**Expected behavior**
Fetch Pharo projects to be installed from GitHub.

**Expected development cost**
Nothing: the Pharo Compendium exist and is close (if not ready) to be included in the image: https://github.com/astares/Pharo-Compendium 
I will be happy to test 

**Screenshots**
https://github.com/astares/Pharo-Compendium has plenty of screenshots

**Comment by guillep** [comment]
This issue looks more like a small project than an actionable issue.
I propose we move it to a wiki with potential projects for people to contribute.
I'm collecting all these.
Could be a great basis for GSOC.
