### ISSUE TITLE
Metacello does not look like it is managed on Squeaksource anymore

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6843]
So we could remove the old logic pointing to squeaksource.

Look for string
`http://www.squeaksource.com/MetacelloRepository`

Check  for example 
```
defaultRepositoryDescription
    ^ 'http://www.squeaksource.com/MetacelloRepository'
```

**Comment by jecisc** [comment]
This was removed with the Metacello cleanup of this Pharo release I think.
