### ISSUE TITLE
Update Microdown packages

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6849]
Now that the baselines of microdown and pillar have been fixed and locally saved (but not in their repo since they break travis builds). 
I will update the Pillar package to fix the tests.

**Comment by Ducasse** [comment]
In addition 

spec baseline: 'Microdown' with: [ 
			spec 
				repository: repository;
				loads: #('Microdown-RichTextComposer' 'Microdown-Tests' 'Microdown-Pillar-Tests')].

should add 'Microdown-Calypso'

**Comment by MarcusDenker** [comment]
this was done
