### ISSUE TITLE
"run tests" on a package or a tag

### ISSUE THREAD

**Issue by hogoww** [guillep/pharo-core#6877]
**Describe the request**
The ctrl+T/right click + "run tests" on a package allows to run tests of all classes in the package.
It would be great to have it for tags as well.

**Expected behavior**
Be able to "run tests" on a package or a tag.

**Expected development cost**
It doesn't look that complicated to do, but with very little knowledge of calypso, it took me quite a while to just start to grasp the necessary concepts.
If nobody else does it, I'll pick this up later.

**Comment by hogoww** [comment]
@dionisiydk I'll try do it for tomorrow's sprint, unless you want to take it =)

**Comment by dionisiydk** [comment]
Hi @hogoww . I do not have time for this. 
It is not very trivial as you may think. You will need to implement something like ClyRunTestsFromClassGroupCommand.
But the trick to allow calypso to recognize tests in any kind of selected items is to annotate them with ClyTestResultProperty. See ClySUnitEnvironmentPlugin>>#decorateBrowserItem:ofPackage:. You will need to implement #decorateBrowserItem:ofClassGroup:.

**Comment by hogoww** [comment]
I do not know if it's trivial as this is very dependent on how this is coded (which I don't know) and that I have very little experience with GUI.

But thanks for the answer and the hints !

**Comment by hogoww** [comment]
@dionisiydk is there some sort of cache for query classes or something?
I tried to put my code on a new image twice, and it doesn't work *right away*
it starts working after a *while* (I wasn't able to narrow it down).
The general problem is that the item selected is wrongly a package instead of a tag.

It works after a while with those changes:
https://github.com/hogoww/pharo/commit/b10a7b81acab98d2ee6ec3027fc0143eb7522c6c

**Comment by dionisiydk** [comment]
> @dionisiydk is there some sort of cache for query classes or something?

Yes. There is a cache of queries. In context menu there is a command Extra/Update to forcibly update it.

**Comment by hogoww** [comment]
My apologies, I don't know where the context menu is ^^"

**Comment by dionisiydk** [comment]
On any list (class list, method list, ...)

пн, 27 июл. 2020 г., 14:19 hogoww <notifications@github.com>:

**Comment by hogoww** [comment]
Thank you :) 
It seems unrelated.
I'm back on : "The general problem is that the item selected is wrongly a package instead of a tag" (until it's correctly typed)
I have no idea where that can come from currently.
(and reaching that conclusion is super weird to me..)

**Comment by dionisiydk** [comment]
Try reset annotation cache: ClassAnnotation resetCache.  
It's possible that when you override #contextClass method the annotations were already collected for new command and therefore method change did not take affect.

**Comment by hogoww** [comment]
That was it, Thanks a lot @dionisiydk ! 
I'll PR it, and hopefully we'll be able to use it :)
I don't know how to test it thought.
