### ISSUE TITLE
Dictionary withAll: should behave better

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6884]
Once we have #6719 (newFromAssociations:) we can easily fix withAll: to do what we expect

```
Dictionary withAll: { #key1->#value1. #key2->#value2 }
```
right now returns `Dictionary(1->#key1->#value1 2->#key2->#value2 )`

and this is not good.

**Comment by MarcusDenker** [comment]
the PR #6985 discusses this further and implements a withAll: as described here. 

I close this Issue
