### ISSUE TITLE
testStDefineMissingEntityCommandExecution is failing

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6898]
/ testStDefineMissingEntityCommandExecution – Windows64.NewTools.Debugger.Tests.Model.StDebuggerCommandTest

**Comment by MarcusDenker** [comment]
Error
2
Stacktrace
SubscriptOutOfBounds
2
Context(Object)>>errorSubscriptBounds:
Context>>at:
Context>>tempAt:
StDebuggerActionModel>>isInterruptedContextMissingClassException
StDebugger>>canExecuteCreateMissingClassCommand
StDefineClassCommand>>appliesTo:
StDefineClassCommand(StDebuggerCommand)>>canBeExecuted
[ :subCommand | subCommand canBeExecuted ] in StDefineMissingEntityCommand>>applicableCommand
[ :each |
(aBlock value: each)
ifTrue: [ ^ foundBlock cull: each ] ] in OrderedCollection(Collection)>>detect:ifFound:ifNone:
OrderedCollection>>do:
OrderedCollection(Collection)>>detect:ifFound:ifNone:
OrderedCollection(Collection)>>detect:ifNone:
StDefineMissingEntityCommand>>applicableCommand
StDebuggerCommandTest>>testStDefineMissingEntityCommandExecution
StDebuggerCommandTest(TestCase)>>performTest

**Comment by StevenCostiou** [comment]
Thanks. I'll fix that tomorrow.

**Comment by StevenCostiou** [comment]
Should be fixed by the next new tools integration

**Comment by StevenCostiou** [comment]
Should be fixed. Could you check?
