### ISSUE TITLE
Opening a Browser from a message list that contains class side methods

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#6937]
**Describe the bug**
Subscript out of bounds exception when browsing code

**To Reproduce**
1. implementors message list tat contains class methods (e.g. Go to the Playground, type "uniqueInstances", implementors of)
2. Click on one of the class side methods
3. Try to Browse (e.g. via the menu)

**Comment by guillep** [comment]
In a new image I can easily reproduce this one too doing:

1. Open a playground and type `PopoverAdapter`
2. Look for senders doing `Cmd+n` => a message browser will open with a single entry
3. Do `Cmd+b` to browse the class

**Comment by guillep** [comment]
This seems to be caused by commits 4621d4341f762becad7e24e873ed25a148ead98b and c975c16b269ad01e73035659c1af2a9a2710d196

**Comment by guillep** [comment]
Introduced by #6716
