### ISSUE TITLE
Syntax highlighter doesn't like blocks with arguments

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#6943]
**Describe the bug**
![image](https://user-images.githubusercontent.com/4706329/88078218-7a82d800-cb7c-11ea-9e12-47065fc2f967.png)

**To Reproduce**
1. Browse: RPackageOrganizer >> #packageMatchingExtensionName:

**Expected behavior**
![image](https://user-images.githubusercontent.com/4706329/88078321-a00fe180-cb7c-11ea-8e9e-3eaf209633e0.png)

**Version information:**
 - OS: win 10
 - Version: Pharo9.0.0
build: 536, commit: d59067f

**Comment by Ducasse** [comment]
Vincent so that I'm clear on it. It worked before and now it did not work?

**Comment by Ducasse** [comment]
Marcus this may be related to your changes on block var?
Last time I checked the syntax higthlight I saw that there is just one dull test. 
And when I wanted to define alternate coloring for my themes I saw that we will need
to do a pass on it.

**Comment by VincentBlondeau** [comment]
> 
> 
> Vincent so that I'm clear on it. It worked before and now it did not work?

Couple month ago it was working nice. Maybe it is due to the integration of the full blocks?

**Comment by MarcusDenker** [comment]
i am sure it is a side effect of my change, i will fix it

**Comment by MarcusDenker** [comment]
The fix is to remove the "variable" in methodOrBlockArgStyleFor:

it should be:

`methodOrBlockArgStyleFor: anArgumentNode
	^ anArgumentNode isBlockVar
		ifTrue: [ anArgumentNode isDefinition 
				ifTrue: [ #blockPatternArg ]
				ifFalse: [ #blockArg ] ]
		ifFalse: [ #methodArg ]`
