### ISSUE TITLE
Debugger line location is uncorrect when using a Breakonce

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#6952]
**Describe the bug**
I put a break there:
![image](https://user-images.githubusercontent.com/4706329/88176395-7e1f6900-cc27-11ea-952d-198e4c068dcd.png)

And the debugger opens there:
![image](https://user-images.githubusercontent.com/4706329/88176412-837cb380-cc27-11ea-85cf-937726b78648.png)

Clicking on restart doesn't change the position of the "Where is" selection (screenshot after clicking on restart):
![image](https://user-images.githubusercontent.com/4706329/88176566-c63e8b80-cc27-11ea-8ff2-6b072c2fc7ef.png)

And clicking on over just changes the stack top in the var list

**To Reproduce**
1. Execute:
```
Object compile:  'systemIconName
	self class isMeta ifTrue: [ ^ self class printString].
	^ #classIcon '.
```
2. Set a Break once breakpoint between "^" and "self". See up screenshot
3. Click on another class to refresh the browser icon list
4. See debugger

**Expected behavior**
The good frame should be selected in the method source code pane at the beginning, on restart and on step in.

**Version information:**
 - OS: win 10
 - Version: Pharo9.0.0
build: 541, commit: a3a6597

**Comment by StevenCostiou** [comment]
Seems that breakpoint Once uninstall themselves right after they are hit, and then the method is rolled back in its original version where it does not find anymore the correct node.
@MarcusDenker what do you think?
It works perfectly with standard breakpoints.

**Comment by MarcusDenker** [comment]
Yes, I think we should instead just disable the once breakpoint via a condition.
