### ISSUE TITLE
ZipArchive Extraction `errorBadBlock`

### ISSUE THREAD

**Issue by seandenigris** [guillep/pharo-core#6956]
**Describe the bug**
`MessageNotUnderstood: ZipReadStream>> #errorBadBlock in ZipReadStream(InflateStream)>>pastEndRead` when extracting a `ZipArchive`.

**To Reproduce**
```smalltalk
target := FileLocator imageDirectory / 'GT.zip'.
ZnClient new
	url: 'https://github.com/feenkcom/gtoolkit/releases/latest/download/GT.zip';
	downloadTo: target.
ZipArchive new
	readFrom: target;
	extractAllTo: target parent / 'tmp'
```
**Version information:**
 - macOS 10.14.6
 - Version: Pharo-9.0.0+build.541.sha.a3a65972dfce86005a9798ea7f819b7cede73d35 (64 Bit)

**Expected development cost**
Unknown

**Additional Information**
The zip file unzips okay via Safari/Mac Finder

**Comment by weslleymberg** [comment]
On Windows 10 1904 I always get `SubscriptOutOfBounds: 273`

Tested on:
Pharo-9.0.0+build.545.sha.8ec08511e3d55476e160795ffa9a582ab81dde59 (64 Bit)
Pharo-9.0.0+build.297.sha.b3d801c46b7de6bec6d6c26f7e107f924b1b158b (64 Bit)
Pharo-8.0.0+build.1124.sha.0932da82f08175e906b0e2a8052120c823374e9f (64 Bit)

**Comment by StephanEggermont** [comment]
Zip 64 problem?

**Comment by MarcusDenker** [comment]
for Zip64 we have:  https://github.com/pharo-project/pharo/issues/6405
