### ISSUE TITLE
Ed fails related to syntax highlight or completion

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6958]
editing strem in the following method inside the new debugger led to the attach screenshot

```
MicMicrodownTextualBuilder >> metaDataFromAssociation: aCollection 
	stream nextPutAll: '{ '.
	aCollection do: [ :each | 
		 ]
		separatedBy: [ strem ]
	stream nextPutAll: '}'.
```

<img width="1185" alt="Screenshot 2020-07-22 at 22 41 04" src="https://user-images.githubusercontent.com/432549/88226785-e7759b00-cc6c-11ea-9c9e-f89d4f7843d6.png">

To reproduce load pillarMicro from Pillar 

```
Metacello new
   baseline: 'PillarMicroCitezen';
   repository: 'github://pillar-markup/Pillar';
   load.
```

**Comment by StevenCostiou** [comment]
I cannot load the repo, is it private?
Could you tell more about how to reproduce?
- load the repo
- execute the code above?

**Comment by StevenCostiou** [comment]
To me this is closed: Ed has been improved and the new debugger infrastructure (Oups) makes the system more resilient to error-handling errors such as that one.
