### ISSUE TITLE
Selecting a { in the slot definition breaks the menu

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6959]
<img width="423" alt="Screenshot 2020-07-22 at 22 57 21" src="https://user-images.githubusercontent.com/432549/88228000-c7df7200-cc6e-11ea-9090-9254385e82fa.png">

**Comment by MarcusDenker** [comment]
I can not reproduce.

is https://github.com/pharo-project/pharo/pull/6955 already in your image?

**Comment by MarcusDenker** [comment]
this is fixed
