### ISSUE TITLE
Context with block argument looks strange.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6960]
<img width="1009" alt="Screenshot 2020-07-22 at 23 51 47" src="https://user-images.githubusercontent.com/432549/88232573-63281580-cc76-11ea-96f3-3027c918ef0e.png">

**Comment by Ducasse** [comment]
In addition I do not understand what I'm reading because replaceAll does not use a block with :presenter so I'm totally confused and no idea how to fix it. 

<img width="1011" alt="Screenshot 2020-07-22 at 23 53 14" src="https://user-images.githubusercontent.com/432549/88232677-95d20e00-cc76-11ea-8d6b-75667b67c609.png">

**Comment by Ducasse** [comment]
I do not get why I do not get a DNU in the title too. 
Here is the way to reproduce the error. See #6961

<img width="627" alt="Screenshot 2020-07-22 at 23 56 08" src="https://user-images.githubusercontent.com/432549/88233092-52c46a80-cc77-11ea-9ec1-07d66725fa8b.png">

**Comment by StevenCostiou** [comment]
> In addition I do not understand what I'm reading because replaceAll does not use a block with :presenter so I'm totally confused and no idea how to fix it.
> 
> <img alt="Screenshot 2020-07-22 at 23 53 14" width="1011" src="https://user-images.githubusercontent.com/432549/88232677-95d20e00-cc76-11ea-8d6b-75667b67c609.png">

Could that be a full block called with `cull` and no args from the context below?

**Comment by StevenCostiou** [comment]
I checked: it is indeed because you have a block in the caller.
In `InitializeDialogWindow:` there is a block that is called with a `:presenter` argument.
Now with fullblocks it seems it's somehow hidden. I need to check how it was before.

**Comment by StevenCostiou** [comment]
Just a printing question it seems

**Comment by StevenCostiou** [comment]
I'm fixing it like this: in method, you explicitly see it's a block, then on the context above it's more logical to have that block as sender.

<img width="772" alt="Screenshot 2020-07-29 at 15 25 47" src="https://user-images.githubusercontent.com/26929529/88805710-c9012980-d1af-11ea-85f1-24e69e34b011.png">
