### ISSUE TITLE
Find replace produces an error when there is no occurrence in the text

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6961]
<img width="627" alt="Screenshot 2020-07-22 at 23 56 08" src="https://user-images.githubusercontent.com/432549/88232958-17c23700-cc77-11ea-8f24-c8d35979e881.png">

**Comment by StevenCostiou** [comment]
I cannot reproduce this one.
Does it still happens in latest Pharo?

**Comment by MarcusDenker** [comment]
I can not reproduce it either
