### ISSUE TITLE
[Feature Request] SpBoxLayout should have "add:expand:fill" method

### ISSUE THREAD

**Issue by jordanmontt** [guillep/pharo-core#6962]
I think that it will be useful to have an `add:expand:fill` in the SpBoxLayout class. I have experienced some cases where I want to add a presenter with `expand` and `fill` properties but not modifying padding. So, I have the following situation:
```
^ SpBoxLayout new
        add: #aPresenter 
        expand: true
        fill: true
        padding: 0
```
Which I found that will be better just to call `add:expand:fill`.

**Comment by MarcusDenker** [comment]
merged

**Comment by estebanlm** [comment]
but I will remove the fill:padding: thingy ;)
