### ISSUE TITLE
Playground's menus malformed caused by font sizes

### ISSUE THREAD

**Issue by kogiokka** [guillep/pharo-core#6964]
**Describe the bug**
Playground's `saved-pages` menu and `bindings` menu are malformed when the predefined styles of standard fonts is set as `Medium`, `Large`, or `Huge`. The malformed menu is inoperable except closing it.

**To Reproduce**
1. `Ctrl+O+S` to open Settings
2. Under `Appearance > Standard fonts`, choose `Medium`.
3. `Ctrl+O+W` to open Playground
4. Click on saved-pages and bindings menu on the top-right corner to see the bug
5. `Ctrl+W` to close Playground, repeat Step 2 to Step 5 with different font sizes.

**Screenshots**
![Pharo_playground_menus_bug](https://user-images.githubusercontent.com/36656205/88244029-f38d4700-ccc4-11ea-82e3-759fa4c9e73b.png)

**Version information:**
 - OS: Fedora 32 KDE
 - Version: Pharo 8.0.0 (stable)
 - Build information: Pharo-8.0.0+build.1124.sha.0932da82f08175e906b0e2a8052120c823374e9f (64 Bit)

**Comment by astares** [comment]
@kogiokka 
Pharo 9 will have NewTools included with a new Playground. Did you check that already?

**Comment by kogiokka** [comment]
I just realized this bug had been solved for a long time, since Github didn't send me any notice. I'll definitely check it out sometime. Thanks for the great work!
