### ISSUE TITLE
Debugger: in code pane Browse class should browse the class of receiver

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6973]
In the code pane of the debugger browse class should open a browser on the class.

**Comment by StevenCostiou** [comment]
After a short investigation, the current command model seems unadapted.
It actually parses the selection then tries to find a class with the same name as the parsed string.

**What we want is, when selecting a string in a code pane and doing browse**: 
- If the string is in the bindings of the interaction model, or is a variable known by the context, then browse that object
- Or, evaluate the selection in the current context/interaction model, then browse the result

However for now, the evaluation logic is not in the browse command but in the doit command. In addition, there is no variable lookup logic yet to know if the interaction model knows the string as a variable.

**Comment by StevenCostiou** [comment]
This seems to work now?

**Comment by StevenCostiou** [comment]
![Screenshot 2021-04-30 at 09 42 32](https://user-images.githubusercontent.com/26929529/116664176-66d09180-a998-11eb-82f4-b5ca17f75a12.png)

I did this test: select `1 squared` and *Browse class* and it browses  the `SmallInteger` class. 
So as far as I understand, this issue is fixed.
