### ISSUE TITLE
RubTextEditor >> nextWord: and shift+forward delete shortcut

### ISSUE THREAD

**Issue by Landraitis** [guillep/pharo-core#6997]
The shift+forward delete key shortcut is meant to delete the next word after the cursor, but is not working: when you do it when the cursor is at the beginning of a text area, it raises a SubscriptOutOfBounds error. Besides that, if you do it when the cursor is at the start of a word, it won't delete anything. The problem appears to be that `RubTextEditor >> forwardDelete:` calls `RubTextEditor >> nextWord: position`, which looks for the end of the word starting at `position - 1`, rather than `position`.

That behavior, in turn, appears to be an adaptation to how `nextword:` is used to implement the meta+right arrow shortcut by `RubTextEditor >> cursorRight:`. `cursorRight:` calls `RubTextEditor >> moveCursor: forward: specialBlock: event:`, which executes the default behavior of adding one to the current cursor position before checking whether meta is pressed, and only then calling `nextword:` on the incremented cursor position, so `nextWord:` compensates by decrementing its input position to get back the original cursor position.

I also noticed that the meta+right arrow shortcut behaves strangely when the cursor is before the second-to-last character in a text area: it moves the cursor one character forward, whereas it should move the cursor to the end of the text area, if the word after the cursor extends to the end of the text area. I think this is due to the same off-by-one error triggering the conditional clause
```
     position >= string size ifTrue: [ ^ position ].
```
in `nextWord:`.

**Version information:**
 - MacOS 10.15.6 Catalina
 - Version: Pharo 8.0 and 9.0

**Comment by pavel-krivanek** [comment]
The shortcut was replaced by Ctrl+Delete and the issue with deletion at the beginning of the text area was fixed. 

The issue can be closed.
