### ISSUE TITLE
Debugger: cmd + M does not identify correctly message to be looked for implementors

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7003]
In the dbeugger pane if you place the cursor inside includes: 
it does not find assertWriting:includes: but consider the complete expression. 
May be this is a spec20 problem,

```

	self assertWriting: sample bold include: self boldFormat

```

**Comment by maxwills** [comment]
I could not reproduce the issue. Might be already or indirectly solved. Can someone else verify this, so the issue can be closed?

**Comment by MarcusDenker** [comment]
Yes, I tried it: this is solved!
