### ISSUE TITLE
Add a comment to explain why it is better to have  [aBlock value] instead of aBlock

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7015]
```
keyAtIndex: anIndex ifAbsent: aBlock
	^ (anIndex > 0 and: [ anIndex <= self size ])
		ifTrue: [ orderedKeys at: anIndex ]
		ifFalse: [ aBlock value ]
```

=> 

```
keyAtIndex: anIndex ifAbsent: aBlock
	^ (anIndex > 0 and: [ anIndex <= self size ])
		ifTrue: [ orderedKeys at: anIndex ]
		ifFalse: aBlock
```

**Comment by MarcusDenker** [comment]
No, the ifTrue:iFalse: compiled to jumps.. if the block is removed, it does not.

**Comment by Ducasse** [comment]
If we never document this nobody will ever be able to grow knowledge. 
We should add a comment to the method. This is the minimum. 
I hate all this crap in Pharo that never lets me learn. 


That is the problem: only if the compiler statically sees blocks, it can compile #ifTrue: and friends to jumps.

So if you remove the block here, it will instead compile a real send and this compile a block for the #ifTrue: case, and a send #ifTrue:ifFalse:
making this very very slow.

This means this is a valid transformation for all the cases where it is *not* an optimised send. There it would speed things up (e.g. imagine do:),
as it would avoid a block creation.

For the optimised case, it slows things down.

The nice thing is that all this is statically decidable. e.g. I have already on my TODO do do a Rule that warns you when you use ifTrue: and friends
without blocks.

Bytecode:


'41 <40> pushTemp: 0
42 <50> pushConstant: 0
43 <63> send: >
44 <C4> jumpFalse: 50
45 <40> pushTemp: 0
46 <4C> self
47 <72> send: size
48 <64> send: <=
49 <B0> jumpTo: 51
50 <4E> pushConstant: false
51 <C3> jumpFalse: 56
52 <01> pushRcvr: 1
53 <40> pushTemp: 0
54 <70> send: at:
55 <B1> jumpTo: 58
56 <41> pushTemp: 1
57 <79> send: value
58 <5C> returnTop’

vs.

'49 <40> pushTemp: 0
50 <50> pushConstant: 0
51 <63> send: >
52 <C4> jumpFalse: 58
53 <40> pushTemp: 0
54 <4C> self
55 <72> send: size
56 <64> send: <=
57 <B0> jumpTo: 59
58 <4E> pushConstant: false
59 <40> pushTemp: 0
60 <F9 00 01> fullClosure:a CompiledBlock: [ orderedKeys at: anIndex ] NumCopied: 1
63 <41> pushTemp: 1
64 <79> send: value
65 <A1> send: ifTrue:ifFalse:
66 <5C> returnTop'

**Comment by MarcusDenker** [comment]
as one step I added a first rule: https://github.com/pharo-project/pharo/pull/7018

(this is just for ifTrue, need to add more rules to cover the others (e.g. ifNil:)

**Comment by guillep** [comment]
I added a comment in #7018.
We think the compiler could be enhanced to optimize both cases and have no effect from a user point of view, so we have the nice code, the fast path, and no need to make users concious about silly "optimizations".

> We were just discussing with Pablo:
> 
> since it should hold that x == x value, particularly for blocks
> And that the message send to ifTrue:ifFalse: will send value to the argument
> then the compiler could transform automatically condition ifTrue: […] ifFalse: x into condition ifTrue: […] ifFalse: [ x value ]
> And we get the best of both worlds, right?
> We write it nicely, and it avoids always the slow path.
> 
> We will work on that in the sprint :)

**Comment by bencoman** [comment]
Rather than have a quality rule creating noise and telling the user there is something wrong with their code because our Compiler isn't smart enough, it would be much-much better for the Compiler to identify that only one path of #ifTrue:ifFalse has a literal-block and optimize that path independent of the other.

**Comment by MarcusDenker** [comment]
There is now https://github.com/pharo-project/pharo/pull/7037 so this one is not needed anymore
