### ISSUE TITLE
SmalltalkImage should point to (custom) PackageOrganizer

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#7025]
At ESUG 2019 I discussed with @MarcusDenker about having own environments within a single image. Basically you could use that to have another Smalltalk dialect / custom environment within the same image or other. Be it to bootstrap and save another fresh image or to create a custom Smalltalk or whatever.

There is some support for this already:  if you ask a class for its environment it currently returns the global SystemDictionary (which is held to by the global variable "Smalltalk", which itself is an instance of SmalltalkImage). 

So beside the default "Smalltalk" SmalltalkImage instance you could have an own "MySmalltalk" instance.

```Smalltalk
Smalltalk class.        "returns SmalltalkImage"
String environment "returns a SystemDictionary(lots of globals)"
```
One could now basically start to construct an own second image in memory:

```Smalltalk
"Evaluate line by line"
Smalltalk at: #MySmalltalk put: SmalltalkImage basicNew.

MySmalltalk  globals: SystemDictionary new.
MySmalltalk  specialObjectsArray: Smalltalk specialObjectsArray copy.
```

If one wants to have own classes with own packages in an own SmalltalkImage instance then this is currently not
possible because the method

```Smalltalk
packages

	^ (RPackageOrganizer default packages) sorted
```
always returns the default package organizer,

Can we introduce an instance variable *packageOrganizer* in class SmalltalkImage that holds a
(custom) organizer instance?

Might be interesting for @ErikOnBike or @carolahp as well

**Comment by astares** [comment]
Maybe we can somehow manager to build and switch within an image to a new in-memory created bootstrapped image. The code would allow for such experiments

**Comment by astares** [comment]
```Smalltalk
Smalltalk at: #MySmalltalk put: (SmalltalkImage new
							packageOrganizer: RPackageOrganizer new;
					                yourself)
																							 
MySmalltalk packages   "gives an own image with empty packages, only unpackaged"
```

**Comment by MarcusDenker** [comment]
"Smalltalk environment" now returns a RPackageOrganizer 

https://github.com/pharo-project/pharo/pull/13403

**Comment by jecisc** [comment]
Next step is to remove all hardcoded `RPackageOrganizer default` everywhere and this is on my todo
