### ISSUE TITLE
Instance of OpalCompiler did not understand #allowParseErrorsNonInteractive

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#7031]
Latest Pharo 9 image (freshly downloaded a minute ago using ZeroConf) when I checkout updated Pharo9.0 branch from Iceberg. from forked Pharo repo:

Instance of OpalCompiler did not understand #allowParseErrorsNonInteractive
OpalCompiler(Object)>>doesNotUnderstand: #allowParseErrorsNonInteractive
OpalCompiler>>parseMethod
OpalCompiler>>parse
CompiledMethod>>parseTree
RFReflectivityASTCacheStrategy>>getASTFor:
Instance of OpalCompiler did not understand #allowParseErrorsNonInteractive
OpalCompiler(Object)>>doesNotUnderstand: #allowParseErrorsNonInteractive
OpalCompiler>>parseMethod
OpalCompiler>>parse
CompiledMethod>>parseTree
RFReflectivityASTCacheStrategy>>getASTFor:
Instance of OpalCompiler did not understand #allowParseErrorsNonInteractive
OpalCompiler(Object)>>doesNotUnderstand: #allowParseErrorsNonInteractive
OpalCompiler>>parseMethod
OpalCompiler>>parse
CompiledMethod>>parseTree
RFReflectivityASTCacheStrategy>>getASTFor:

**Comment by MarcusDenker** [comment]
checking out from GitHub can fail if the change that you load is not loadable (requires a bootstrap)

This does not happen often, but compiler changes like this are often non loadable by loading from GitHub, they require a full bootstrap

**Comment by astares** [comment]
Ok - tried with a fresh download of the repo and fresh download of image - works. I guess we can close this
