### ISSUE TITLE
Fuel tests are red on Pharo 8 when the image file is dropped on the Pharo App icon

### ISSUE THREAD

**Issue by varvello** [guillep/pharo-core#7040]
**To Reproduce**
Run Fuel tests, they are red.
Probably it is due to this bug: https://github.com/pharo-project/pharo/issues/7039

**Version information:**
Pharo 8 on OsX 10.14.6

**Comment by Ducasse** [comment]
Running the tests in tmp would make sure that they do not break when the OS changes the semantics of FileLocator.

**Comment by MarcusDenker** [comment]
as #7039 is fixed, I guess this fixed, too.

if it still hapens, please reopen the issue.
