### ISSUE TITLE
Better comment for CompiledBlock and FullBlock

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7042]
CompiledBlock is what is created for every FullBlock. The bytecode takes that from the stack and creates a FullBock at Runtime. (this is why it is so slow)
FullBlocks have a pointer then to the compiledBlock
CleanBlocks are just FullBlockClosures that are created at compile time. They are then, like the CompiledBlock, as Literals in the literalframe

**Comment by dionisiydk** [comment]
Also it's interesting to know why BlockClosure is variableSubclass and is it still required for FullBlockClosure

**Comment by dionisiydk** [comment]
Another point: FullBlockClosure contains CompiledBlock inside startpc variable for some compatibility. 
- Is it VM expectation to have it in second variable?
- Is there an idea to merge FullBlockClosure and BlockClosure at the end (with variable renamings)? 
- Or in other word do we need to keep old block closure implementation in the image?

**Comment by MarcusDenker** [comment]
The idea is to clean up, but not in Pharo9...
