### ISSUE TITLE
MessageBrowser browse raises a DNU

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7055]
<img width="1009" alt="Screenshot 2020-08-07 at 09 38 59" src="https://user-images.githubusercontent.com/432549/89621588-e611b880-d891-11ea-8b7f-14ce9ae07a1e.png">

**Comment by VincentBlondeau** [comment]
To me, it happens when browsing the implementors of a class side method and then clicking on browse:
![image](https://user-images.githubusercontent.com/4706329/89770084-83712480-dafe-11ea-928d-3baab2213fc3.png)

**Comment by MarcusDenker** [comment]
is this not the same as #6937  ?  There is a fix https://github.com/pharo-project/pharo/pull/7028

**Comment by MarcusDenker** [comment]
#7028 has been merged
