### ISSUE TITLE
Commenting out a piece of code containing comments should maintain the inside comments

### ISSUE THREAD

**Issue by dupriezt** [guillep/pharo-core#7057]
Right now, if one selects the following piece of code and presses " to comment it, then the comment inside is no longer a comment and the piece of code does not compile.

```Smaltlalk
code.
"comment"
code.
```
-> select all and press " ->
```Smalltalk
"code.
"comment"
code."
```
-> this code does not compile because the inside comment is interpreted as code
**Expected Behaviour**
```Smalltalk
"code.
""comment""
code."
```

**Comment by ackerleytng** [comment]
I'm a Pharo beginner but I'd like to give this a shot! How should I find out the method responsible for prepending and appending the double quote?

Where should I set the breakpoints...?

**Comment by dupriezt** [comment]
Hello @ackerleytng 
I tracked the method responsible for this behaviour to `CompletionEngine>>#smartCharacterWithEvent:` (shown below). More specifically, it's in the first `ifTrue:` branch.

```Smalltalk
smartCharacterWithEvent: anEvent
	"char is extracted from anEvent, anEvent is passed because we may need it.
	We may remove char if this is not costly."

	| opposite previous next char insertion insertionCenter matchingPair |
	
	char := anEvent keyCharacter.
	editor hasSelection
		ifTrue: [ 
			"we selected a piece of text and we type the same character that previously, so
		we unwrap it"
			"we selected a piece of text if the character is not a special one we do nothing."
			matchingPair := self smartCharacterPairFor: char ifAbsent: [  ^nil ].	"else we wrap the selection"	"editor replaceSelectionWith: (String with: char) , (editor selection) , (String with: opposite)."	"ugly logic it should be encapsulated in the editor "
			editor encloseWith: matchingPair.
			self invalidateEditorMorph.
			^ true ].	"we are not in a selection"
			
	(self smartCharacterShouldClose: char)	
		ifFalse: [ 
			"if the character is not a special character"
			self smartInverseMapping at: char ifAbsent: [ ^ nil ].	"if the character is not a closing special character do nothing"	"The character is special"
			editor blinkPrevParen: char.
			(editor nextCharacterIfAbsent: [ ^ nil ]) = char
				ifFalse: [ ^ nil ].	"do not get this test but if we comment it out we cannot type closing ) anymore"
			editor selectFrom: editor startIndex + 1 to: editor startIndex.
			self invalidateEditorMorph.
			^ true ].
		
	opposite := self smartCharacterOppositeOf: char ifAbsent: [ ^nil ].
	previous := editor previousCharacterIfAbsent: [ Character space ].
	next := editor nextCharacterIfAbsent: [ Character space ].
	insertion := next isSeparator
				ifFalse: [ char asString ]
				ifTrue: [ 
					previous isSeparator
						ifFalse: [ char asString ]
						ifTrue: [ self newSmartCharacterInsertionStringForLeft: char right: opposite ]].
	editor replaceSelectionWith: insertion.
	insertionCenter := insertion size // 2 max: 1.
	editor selectFrom: editor startIndex + insertionCenter to: editor startIndex + (insertionCenter - 1).
	self invalidateEditorMorph.
	^ true
```

**Comment by ackerleytng** [comment]
Thanks! @dupriezt

I want to learn how you tracked this method down!

How did you track it down to this method? Where did you start looking? Did you already know that it had to do with completions?

**Comment by dupriezt** [comment]
I'll skip the "fumbling around in the dark" part, because I don't recall exactly what I did there.

The starting point was that I wanted to see where the right-click menu of text editors was defined.
I opened a code browser on a random method, and right-clicked on the text editor to get the right-click menu.
![image](https://user-images.githubusercontent.com/32486709/89878774-48d0c000-dbc2-11ea-87fd-dc7e6dc3f056.png)
I figured "Paste..." would not be a commonly used string in the image, so I typed it in a playground, and used "Browse methods containing string".
![image](https://user-images.githubusercontent.com/32486709/89879580-7702cf80-dbc3-11ea-8e8e-5b77eb98e8f4.png)
This was the result:
![image](https://user-images.githubusercontent.com/32486709/89879058-a533df80-dbc2-11ea-9613-21b217075b2c.png)
I looked a bit at all the classes, and felt the "TextEditor" class looked promising, so I took a look at all of its method. I found the `TextEditor>>#encloseWith:` method that seemed responsible for enclosing selected pieces of text in brackets, braces, ...
![image](https://user-images.githubusercontent.com/32486709/89879265-f643d380-dbc2-11ea-863c-b617b09e67d6.png)
I looked at the senders (callers) of this method, and there was only one: `CompletionEngine>>#smartCharacterWithEvent:`
![image](https://user-images.githubusercontent.com/32486709/89879361-1ffcfa80-dbc3-11ea-8602-5e32ee941783.png)
I looked at this method and found that it was indeed responsible for the enclosing behaviour I was looking for.

**Comment by ackerleytng** [comment]
Thanks for your help, and thanks for the detailed explanation! I've started working on this issue in pull request #7082

**Comment by MarcusDenker** [comment]
This is now working as described
