### ISSUE TITLE
obsolete method reference to WorldMorph>>initialize

### ISSUE THREAD

**Issue by j-brant** [guillep/pharo-core#7059]
There are two WorldMorph>>initialize methods in the image. It appears that one was run which hooked up two blocks to be run when tools were (un)registered. After the code was run, the method was recompiled, but the blocks remain hooked up in the registry. You can find the reference path to the uninstalled initialize method using: 
```
ReferenceFinder findPathTo: 
    (CompiledMethod allInstances 
        select: [:each | 
            each methodClass = WorldMorph 
                and: [each selector = #initialize 
                and: [WorldMorph>>#initialize ~~ each]]]) first
```

This returns a path: 
```
1 - Smalltalk
2 - a SystemDictionary(lots of globals)...etc...
3 - an Array(#HEPragma->HEPragma #LGitP...etc...
4 - #SmalltalkImage->SmalltalkImage
5 - SmalltalkImage
6 - a Dictionary(#CompilerClass->OpalCo...etc...
7 - an Array(#CompilerClass->OpalCompil...etc...
8 - #Tools->a PharoCommonTools
9 - a PharoCommonTools
10 - an Announcer
11 - a SubscriptionRegistry
12 - an IdentitySet(a WeakAnnouncementSu...etc...
13 - an Array(nil a WeakAnnouncementSubs...etc...
14 - a WeakAnnouncementSubscription(init...etc...
15 - initialize worldState := WorldSta...etc...
16 - WorldMorph>>initialize
17 - WorldMorph>>#initialize
```

This happens in both 8 & 9 images. The method's source is different in 9, but the effect is the same.

Pharo 9.0.0
Build information: Pharo-9.0.0+build.578.sha.a20ed8a531064fac7e141b13565f92eaa1bb584e (64 Bit)

Pharo 8.0.0
Build information: Pharo-8.0.0+build.1124.sha.0932da82f08175e906b0e2a8052120c823374e9f (64 Bit)

There are likely several other methods with the same issue as there are around 80 compiled methods in my 9 image that are not installed in their classes: 
```
CompiledMethod allInstances 
	select: [ :each | 
		[ each methodClass >> each selector ~~ each ] 
			on: Error
			do: [ :ex | ex return: true ] ]
```

**Comment by Ducasse** [comment]
Thanks John. This may be related to the use of fullBlockclosures!

**Comment by MarcusDenker** [comment]
The WorldMorph>>initialize goes away after resetting the ToolRegistry announcer:

ToolRegistry allSubInstances do: #resetAnnouncer.

There are some cleanup methods:

ImageCleaner new cleanUpProcesses.
ImageCleaner new cleanUpMethods.

to restart processes / cleanup cases like this 

After running them I am down to 60, most of them related to worldMenu methods... will explore more
