### ISSUE TITLE
CoTypeInferencer DNU when editing code after removing instance variables

### ISSUE THREAD

**Issue by dupriezt** [guillep/pharo-core#7060]
See below for a fix and a green test!

Error: `MessageNotUnderstood: CoTypeInferencer>> #visitVariableNode: in RBVariableNode>>acceptVisitor:`

**To Reproduce**
1. Execute:
```Smalltalk
Metacello new
    	baseline: 'SpecAppSkeleton';
    	repository: 'github://dupriezt/SpecAppSkeleton';
    	load.
```
2. Execute:
```Smalltalk
SpecAppSkeleton browse
```
3. Remove all the instance variables of the class SpecAppSkeleton
4. Go to the #initializePresenters method
![image](https://user-images.githubusercontent.com/32486709/89658053-576f5c80-d8ce-11ea-9441-41aac9a11c29.png)

5. start typing a new line of code under the temp variables declaration
![image](https://user-images.githubusercontent.com/32486709/89657966-3a3a8e00-d8ce-11ea-908a-a2f546cec4aa.png)

6. A debugger opens, on: `MessageNotUnderstood: CoTypeInferencer>> #visitVariableNode: in RBVariableNode>>acceptVisitor:`
![image](https://user-images.githubusercontent.com/32486709/89658003-46bee680-d8ce-11ea-966c-c0b8462748a8.png)

**Version information:**
 - Ubuntu 20.04

**Comment by Ducasse** [comment]
Thanks for your bug report. It is really nice and I could reproduce it.

**Comment by Ducasse** [comment]
Apparently the parser is creating a cascade message with the following messages:
 RBCascadeNode(pointTable
	addColumn: indexColumn;
	addColumn: xColumn;
	addColumn: yColumn)

I extracted them from aRBCascadeNode messages in the following method. 

```
visitCascadeNode: aRBCascadeNode 
	
	| receiverType last |
	receiverType := aRBCascadeNode receiver acceptVisitor: self.
	aRBCascadeNode messages do: [ :each |
		last := self
			visitMessageNode: each
			receiverType: receiverType ].
	^ last
```

this is called from the first aRBMethodNode statements in the following method.

```
visitMethodNode: aRBMethodNode 
	
	aRBMethodNode arguments withIndexDo: [ :each :index |
		(self ensureTypeOfArgumentVariable: each name)
			addAll: (arguments at: index)
	].
	aRBMethodNode statements do: [ :each |
		each acceptVisitor: self ].
	aRBMethodNode statements ifNotEmpty: [ :statements |
		statements last isReturn
			ifFalse: [ returnType add: method methodClass ] ]
```

 the statements shows that we have indeed a cascade.


 "an OrderedCollection(
RBAssignmentNode(pointTable := self newTable) 
RBAssignmentNode(indexColumn := SpIndexTableColumn new
	               width: 40;
	               title: 'Index';
	               yourself) RBAssignmentNode(xColumn := SpStringTableColumn new
	           evaluated: [ :item | item x ];
	           title: 'X';
	           width: 60;
	           yourself) 
RBAssignmentNode(yColumn := SpStringTableColumn new
	           evaluated: [ :item | item y ];
	           title: 'Y';
	           width: 60;
	           yourself) 

RBCascadeNode(pointTable
	addColumn: indexColumn;
	addColumn: xColumn;
	addColumn: yColumn)

RBMessageNode(pointTable items: self collectionOfPoints) 

RBAssignmentNode(textField := self newText) RBCascadeNode(textField
	placeholder: 'placeholder text';
	autoAccept: true) RBAssignmentNode(inspectButton := self newButton) RBCascadeNode(inspectButton
	label: 'Inspect Selected';
	icon: (self iconManager iconNamed: #glamorousInspect)) RBAssignmentNode(executeButton := self newButton) RBCascadeNode(executeButton
	label: 'Execute';
	icon: (self iconManager iconNamed: #glamorousGo)))"

**Comment by Ducasse** [comment]
So may be the bug is when we do a cascade to a variable. 
I got the same problems just sending a message to an argument:

```
setModelBeforeInitialization: anObject

	anObject foo
```

**Comment by Ducasse** [comment]
I wonder if this is not a side effect of the change of Marcus on variables.

**Comment by Ducasse** [comment]
Thomas I found the bug and the solution

```
CoTypeInferencer >> visitVariableNode: aRBVariableNode 
		
	^ self ensureTypeOfVariable: aRBVariableNode name
```

**Comment by Ducasse** [comment]
With this fix all the tests are still green!
Now writing a text to see if I can.

**Comment by Ducasse** [comment]
```
CoTypeInferencer >> testInferUndefinedInstanceVariableUsedInInitialize

	| types |
	types := CoTypeInferencer new
		inferFrom: (CoMockClass new
			methodAt: #initialize put: (CoMockMethod new
				source: 'initialize
					a'
				yourself);
			instanceVariables: #();
			yourself);
		variables.
		
	self assertCollection: (types at: #a) hasSameElements: Set new
```

**Comment by guillep** [comment]
I just reproduced this bug, with an undeclared variable.
In the debugger, if we compile for example:

```smalltalk
initialize 
	super initialize.
	undeclared = nil.
```

it does not ask to define `undeclared and gets instead declared as an undeclared.
And completion was certainly not thought to manage undeclareds :/

**Comment by guillep** [comment]
See also https://github.com/pharo-spec/NewTools/issues/86

**Comment by guillep** [comment]
And yes, looking at the instructions of @dupriezt, this happens if we remove the variables, leaving undeclared bindings.
