### ISSUE TITLE
[Debugger] Cannot select a piece of code in the code pane and do a doit.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7069]
May be this has been fixed but right now I cannot do a cmd d on a piece of code that I selected.

**Comment by StevenCostiou** [comment]
Can you reproduce? If I try like this, it works.

![debugger-doit](https://user-images.githubusercontent.com/26929529/89796204-9e0cc300-db29-11ea-9b2c-9e929702a7b6.gif)

**Comment by Ducasse** [comment]
Can you try with self or a variable of the receiver?

**Comment by Ducasse** [comment]
I retried and all my attempts are working but now I'm with latest version of Pharo.

**Comment by StevenCostiou** [comment]
I'm closing it, the problem seems solved.
We can reopen if we reproduce it.
