### ISSUE TITLE
Deadlock while debugging GUI on spec 2 - SemaphorecriticalReleasingOnError - FullBlocks

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#7071]
**Describe the bug**
Image is frozen, CTRL + . doesn't have any impact.

**To Reproduce**
No idea yet

**Expected behavior**
No freeze, Emergency debugger

**Stack trace**

Both exports of "F2 -> export all the process" + PharoDebug.log
[debug.log](https://github.com/pharo-project/pharo/files/5050791/debug.log)

**Version information:**
 - OS: win 10
 - Version: latest at 10 aug 2020

**Expected development cost**
Several weeks - may be linked with FreeType too

**Additional context**
Using the GT debugger

**Comment by StevenCostiou** [comment]
Did you manage to reproduce it?
Also, when you mean "debugging", what do you mean exactly? Stepping...?

**Comment by VincentBlondeau** [comment]
It has been a long time... I do not remember anymore... You can close the issue. I'll reopen it if needed

**Comment by StevenCostiou** [comment]
Thanks!
