### ISSUE TITLE
Do not use asClass please!!!

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7079]
```
subjectUnderTest 
	^(self class name allButLast: 4) asClass
```
 
=> self class environment at: (self class name allButLast: 4)

**Comment by kasperosterbye** [comment]
What is the schedule for namespaces? I mean, this only matters if those are there, or did I misunderstand something?

**Comment by noha** [comment]
Why don't you add a rewrite rule for #asClass ?

**Comment by MarcusDenker** [comment]
duplicate with https://github.com/pharo-project/pharo/issues/4732
