### ISSUE TITLE
After removing an instance variable from a class, code using this instance variable still *works*

### ISSUE THREAD

**Issue by StevenCostiou** [guillep/pharo-core#7083]
In any class, create this method:
```Smalltalk
someMethod
  i := i + 1.
  ^i squared
```
Then save, and as `i` does not exist, create an instance variable.
Now go into the class definition, remove `i` and execute in the playground:

`YourClass new someMethod`

It *works*! Or at least it does *not not work*.
If you `debugIt` and step into, it lets you step over the assignment and the return of the undeclared variable without problem (values are clearly wrong if you look at `stackTop`).

Happens in both `GTDebugger` and `StDebugger`, from both `GTPlayground` and `StPlayground`.

**Comment by StevenCostiou** [comment]
![Screenshot 2020-08-12 at 09 02 38](https://user-images.githubusercontent.com/26929529/89984982-94df3b80-dc7a-11ea-9a69-95e4f1d7e247.png)

It seems that undeclared variables are considered to be small integers at run time

**Comment by dionisiydk** [comment]
Hi Steven.

It's all consequences of how an undeclared variable works. It's simply a
global var now,
So if somewhere in any code (even in the method of another  class) it will
be assigned to the value (during some test for example) then this value
will be accessed anywhere in the system using this variable.

We should really make undeclared variables read only and failing any
accessing code. We have all infrastructure for this.



ср, 12 авг. 2020 г. в 08:03, Steven Costiou <notifications@github.com>:

**Comment by StevenCostiou** [comment]
Hi Denis, thanks for the tips.
Can someone look at it? It is a really important problem, and I will not have time to fix it before my (long) holidays.

**Comment by MarcusDenker** [comment]
I do not think that we have to change how Undeclared are handled now to get the debugger to work.

We used the current way forever and it was not a problem.

note: I do not say that we should not change undeclared handling, but that is a quite intrusive change in itself with *lots* of side effects.

**Comment by StevenCostiou** [comment]
It does not work with GT either, it is not a problem with NewTools.
We should check how it worked in debuggers in P8, I do not remember.

**Comment by StevenCostiou** [comment]
I've just checked in Pharo 7 and 8, actually it never worked at all.
So if you remove an instance variable of a class and execute compiled code still referencing this variable, then the execution will continue unless there is a bug with using that undeclared variable.

I do not see what we can do debugger side : the execution is not breaking in any way...

**Comment by MarcusDenker** [comment]
I wrote a larger document about it: https://github.com/pharo-project/pharo/wiki/02-PhIP-Undeclared-Variables

<blockquote><img src="https://repository-images.githubusercontent.com/64123480/451beb80-d08b-11e9-9ade-21d166d787d9" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">pharo-project/pharo</a></strong></div><div>Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk. - pharo-project/pharo</div></blockquote>

**Comment by MarcusDenker** [comment]
I close this as we have the large PhiP document about this for Pharo10
