### ISSUE TITLE
Debugger : step into doesn't work in this case.

### ISSUE THREAD

**Issue by lesueur-philippe** [guillep/pharo-core#7087]
**Describe the bug**
When doing step into inside visitNode:, the debugger redirect to a dictionary error

**To Reproduce**
1. Load commit 4a0b9b6
2. Put an halt inside RBParser>>parseIncompleteExpression
3. Open Playground and type: )
4. Step over until doSemanticAnalysis
5. Step into
6. Repeat step 4 and 5
7. Step into analyse:
8. Step into until visitMethodNode:
9. Step into visitNode:
10. Step into until visitSequenceNode:
11. Step through the block
12. Step into visitNode:
13. The next step into should cause the error

**Expected behavior**
KeyNotFound: key 57 not found in Dictionary

**Comment by StevenCostiou** [comment]
Thanks for the report.
It seems that in the case of fullblocks the bytecode-AST mapping is not working properly.
I'll investigate.

**Comment by StevenCostiou** [comment]
@lesueur-philippe could you copy/paste the stack here, with the code of the method in which you step in in step 12?
