### ISSUE TITLE
Performances: Building of WorldMenu executes two times the builder

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#7089]
**Describe the problem**

I have an image with a lot of items in the world menu and some of them take some times to build. 
While doing some time profiling to speed up some menu building I found that the creation of the world menu builds two times the menu. 

To detect the problem you can add a transcript print in any method with the #worldMenu pragma and you'll see that the logs happen two times/build. 

**Proposal**
Refactoring of the World Menu building to not execute two times the building.

**Version information:**
Tested in Pharo 8 and 9

**Comment by Ducasse** [comment]
oh this is really great. Thanks cyril

**Comment by MarcusDenker** [comment]
MenubarMorph class should  not do "WorldState new menuBuilder", it can just reuse the already existing one:

open
	<script>
	self showMenubar ifFalse: [ ^ self ].

	self new
		menuBarItems: self currentWorld worldState menuBuilder menuSpec items;
		open.

This way, we only call it once.

**Comment by MarcusDenker** [comment]
What is interesting: the MenubarMorph is reset when recompiling a method with worldMenu pragma, but the world menu itself is not.
It is just recreated when a tool is added or removed, it seems.

In a second step, we should unify the two and remove the recompile need for the MenubarMorph as it was done for the WorldMenu itself.
