### ISSUE TITLE
Test failing in CI in Pharo9:PRRichTextComposerTest>>testMonospaceFormat

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#7101]
PRRichTextComposerTest>>testMonospaceFormat fails

**Comment by MarcusDenker** [comment]
Reason: a PR with this test failing was merged.

**Comment by Ducasse** [comment]
I already tried to fix this. But I really do not understand because in latest images I run all the tests and they are all green. 
I do not understand how to reproduce it and it does not fail on any of my images. 
I do not understand either why this test would be failing only on server.

S
