### ISSUE TITLE
Code is being "rewritten"

### ISSUE THREAD

**Issue by robkuz** [guillep/pharo-core#7121]
**Describe the bug**
When I am saving my image in a specific location and later on I launch that image using the Launcher "From Disk" some of my instance methods have been rewritten (and are constantly rewritten even if I change the code)

**To Reproduce**
for example if I write this code 

     initializeDialogWindow: aDialogPresenter
          aDialogPresenter centered.
          aDialogPresenter
                addButton: 'Cancel' do: [ :presenter | presenter close ];
                addButton: 'Save Film' do: [ :presenter | presenter beOk; close].

The moment I save this as an instance method it gets "converted" into

      initializeDialogWindow: arg1
      | tmp2 |
           arg1 centered.
           tmp2 := arg1.
           tmp2
                addButton: 'Cancel' do: [ :arg2 | arg2 close ];
                addButton: 'Save Film'
                    do: [ :arg3 | 
                      | tmp4 |
                      tmp4 := arg3.
                      tmp4
                      beOk;
                close ]

The semantics stay the same but the actual code changes.

**Screenshots**

**Version information:**
 - OS: Windows 10
 - Version: Pharo 8 | Launcher 2.2

**Comment by estebanlm** [comment]
this looks a lot like a problem accessing changes file (is it in R/O? is it in a "weird" windows path?).

**Comment by guillep** [comment]
Yes, this means that the system cannot find the sources. Very probably an issue in the Pharo Launcher.
The issue should be moved to:

https://github.com/pharo-project/pharo-launcher

<blockquote><img src="https://avatars3.githubusercontent.com/u/1838382?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-launcher">pharo-project/pharo-launcher</a></strong></div><div>Lets you manage your pharo images and download new ones - pharo-project/pharo-launcher</div></blockquote>

**Comment by MarcusDenker** [comment]
I close this issue
