### ISSUE TITLE
code completion

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7122]
Right now we need to enter space to avoid that the completion picks the first element of the list. 
It means that enter and tab are doing the same. They select the first element. 

I'm wondering if enter should not be the same as space and that we only keep tab for taking the first element proposed. 
I do not know how other systems are doing it.

**Comment by Ducasse** [comment]
I checked intellJ and they map tab and cr. 
Now this looks strange because I'm often finding myself with completion entry when I do not want.

**Comment by hogoww** [comment]
I have the same problem, but I tend to want the other way around. 
I often start a selector, then hit "tab" to trigger code completion.
Whereas when I hit "enter", it's to kind of "accept" the current suggestion.
I don't know which one would be the most intuitive.

**Comment by demarey** [comment]
I think the current behaviour is not so bad. Most IDE's do like that.
If you do not want the completion, you just need to press a character not part of the suggestions to close the suggestions.
