### ISSUE TITLE
UFFI deprecated classes should be validated

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7146]
Because for example FFITypeArray is in the tag deprecated but it should not.

**Comment by guillep** [comment]
Hi Stef, I believe the class is correctly deprecated as I did it myself.
Please see comment in #7144. I could have done it by mistake, but I recall
I did it on purpoae and it is explained in the class comment...

Le mer. 19 août 2020 à 18:32, StéphaneDucasse <notifications@github.com> a
écrit :

**Comment by estebanlm** [comment]
this issue has been solved in #7144
