### ISSUE TITLE
[Spotter] Changing the search text in a subquery raises a DNU in GTSpotterCandidatesListProcessor >> itemFilterNameFor:

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#7149]
**Describe the bug**
Do a query in spotter, click on the arrow in the search result, change the search text field.

![g9o7jOZvaa](https://user-images.githubusercontent.com/4706329/90766524-f5f6b700-e2eb-11ea-8378-69a57c02337f.gif)

**To Reproduce**
See screencast.

**Expected behavior**
No bug

**Screenshots**
See above

**Version information:**
 - OS: Win 10
 - Version: Pharo9.0.0 build: 578, commit: a20ed8a

**Expected development cost**
30 mins

**Additional context**

**Comment by MarcusDenker** [comment]
not happening anymore
