### ISSUE TITLE
[EFFormater ] Copy a pragma raise DNU: FFormatter>>formatSelectorAndArguments:firstSeparator:restSeparator:

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#7150]
**Describe the bug**

**To Reproduce**
Browse WorldState >> screenShotCommandOn:
Double click on screenShotCommandOn: world menu
Press CTRL + C

**Expected behavior**
No crash

**Screenshots**
![image](https://user-images.githubusercontent.com/4706329/90767689-e5474080-e2ed-11ea-965b-7a02ba316e8c.png)

**Version information:**
 - OS: Win 10
 - Version: Pharo9.0.0 build: 602, commit: dba4379

**Expected development cost**
5 min or 2 hours

**Comment by Ducasse** [comment]
Thanks vincent for the report. Now I cannot reproduce it. 
- I browsed WorldState class >> screenShotCommandOn:
- then when I bring the world menu and select screenshot menu item, it works. I did not succeed to doubleclick on it. 
- I do not get the DNU and I do not understand how it is related to the formatter. 



![Screenshot 2020-08-22 at 17 58 24](https://user-images.githubusercontent.com/432549/90960319-2a5fa400-e4a1-11ea-970b-e9bc8c258bc1.png)

**Comment by Ducasse** [comment]
I tried to copy the method and paste. or copy it and renamed it. but I could not make it fail.

**Comment by MarcusDenker** [comment]
I have just seen the bug, too. What is strange is: why do we end up in the pretty printer at all here?

**Comment by VincentBlondeau** [comment]
I cannot reproduce the bug anymore too. I guess it has been solved. @MarcusDenker If you cannot reproduce it too you can close this issue.

**Comment by MarcusDenker** [comment]
I checked with the latest image: I can not reproduce it anymore, either
