### ISSUE TITLE
[Parser] Faulty code AST generation raise DNU Text >>findLastOccurrenceOfString:startingAt:

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#7151]
**Describe the bug**
Getting an DNU when navigating in a faulty code method:
```
test
	 ((Object new //2) min: 10.
```

**To Reproduce**
1. Open the browser
2. Compile in any Class:
```
test
	 ((Object new //2) min: 10).
```
3. Place the cursor between ) and .
4. Press BACKSPACE

**Expected behavior**
No bug

**Screenshots**
![image](https://user-images.githubusercontent.com/4706329/90784310-6cea7a80-e301-11ea-93d8-79b01f8bac3b.png)

**Version information:**
 - OS: win 10
 - Version:Pharo9.0.0
build: 602, commit: dba4379

**Expected development cost**
?

**Comment by Ducasse** [comment]
Thanks Vincent. We were aware of this problem. We were trying to integrate a larger PR with a fix but we did not want to break other tests. Now in latest version this is fixed. I will close the bug but if on your side it is still present let us know. 
With this bug I could nearly not work.
