### ISSUE TITLE
[NewTools][Debbugger] Cannot proceed further when a DNU is risen

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#7152]
**Describe the bug**
Execute: `Object foobar`, foobar is not a valid call on Object, and a DNU is raised. 
Implement foobar on Object.
In the debugger, it is not possible to continue / proceed with the error despite the fact that, in between, the foobar method has been implemented.

I concede that there is a break of the "coding in the debugger flow" but the previously described debugging pattern happens.

**To Reproduce**
See above

**Expected behavior**
We can click on proceed and the DNU call is sent again

**Screenshots**

**Version information:**
 - OS: win 10
 - Version:Pharo9.0.0
build: 602, commit: dba4379

**Expected development cost**
30 mins for the debugger development master

**Additional context**

**Comment by StevenCostiou** [comment]
Hi @VincentBlondeau this is not a bug, the buttons are frozen to avoid proceeding when we get a DNU.
Problem is if you proceed (or do anything else) while in such error context and that you did not define the missing method, then it gets less smooth (another debugger opens with another error, etc.). And this is normal.

However there is indeed a regression.
So, opened debuggers could listen to method changes and dynamically update themselves accordingly. 
I think that is a good option: it would unfreeze the actions only if the missing method is defined.

**Comment by StevenCostiou** [comment]
Until then, you can click `create` when in a DNU, and work from the debugger.

**Comment by VincentBlondeau** [comment]
@StevenCostiou I think it is a good proposal. 
"Until then, you can click create when in a DNU, and work from the debugger."
Yeah I know, but sometimes you do something else.
