### ISSUE TITLE
IMPORTANT: selector extraction DOES NOT work anymore!

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7165]
in P8 

selecting `between: 2 and:` in the following and press Cmd-M  find between:and: 
```
1 between: 2
and: 3
```

This is not the case in P9.

**Comment by Ducasse** [comment]
A systematic analysis

## in P8
in Playground
-selecting all expression works
-selecting between: 2 and: works
-placing caret inside between: or and: works

In calypso method pane replacing fully the method body
-selecting all expression works
-selecting between: 2 and: works
-placing caret inside between: or and: works

In calypso class pane replacing fully the class body
-selecting all expression works
-selecting between: 2 and: works
-placing caret inside between: or and: works

In calypso class comment pane replacing fully the comment
-selecting all expression works
-selecting between: 2 and: works
-placing caret inside between: or and: works

In calypso class comment pane replacing with a free text  comment starting
-selecting all expression works
-selecting between: 2 and: works
-placing caret inside between: or and: works

**Comment by Ducasse** [comment]
## in P9
in Playground
-selecting all expression DOES NOT work
-selecting `between: 2 and:` DOES NOT work
-placing caret inside `between:` or `and:` DOES NOT work

In calypso method pane replacing fully the method body
-selecting all expression DOES NOT work
-selecting `between: 2 and:` DOES NOT work
-placing caret inside `between:` or `and:`  DOES NOT work

In calypso class pane replacing fully the class body
-selecting all expression works
-selecting `between: 2 and:` DOES NOT work
-placing caret inside `between:` or `and:` DOES NOT work different version

In calypso class comment pane replacing fully the comment
-selecting all expression works
-selecting `between: 2 and:` DOES NOT work
-placing caret inside `between:` or `and:` (because parseNode: is not implemented on comment)

In calypso class comment pane replacing with a free text  comment starting
-selecting all expression works
-selecting `between: 2 and:` DOES NOT work
-placing caret inside `between:` or `and:` raise an error (because parseNode: is not implemented on comment)

**Comment by Ducasse** [comment]
I started to extract the logic of selector extraction from Rubric so that it can be reused in commands for example. 
The first attempt is available at: 
https://github.com/Ducasse/mybecher/tree/master/myBecher-Xtractor

<blockquote><img src="https://avatars2.githubusercontent.com/u/432549?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Ducasse/mybecher">Ducasse/mybecher</a></strong></div><div>to hold experiences. Contribute to Ducasse/mybecher development by creating an account on GitHub.</div></blockquote>

**Comment by MarcusDenker** [comment]
this seems to be a result of the parser related changed (it worked before I went on holidays)

**Comment by guillep** [comment]
No, this is the new tools or spec

Le mar. 25 août 2020 à 10:52, Marcus Denker <notifications@github.com> a
écrit :

**Comment by tesonep** [comment]
I have just fixed the problem for Rubric and Calypso, the new tools have other logic and we need to integrate the existing logic on Rubric to work with it. We need to get the selection from the AST to correctly handling spaces and new lines.
