### ISSUE TITLE
Strange red : from time to time

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7181]
I get from time to time a red colon while the selector is valid.
It may be an interaction between a faulty node and the syntax coloring. 
Here is a typical sequence. 

![Screenshot 2020-08-25 at 14 16 02](https://user-images.githubusercontent.com/432549/91173396-0e951180-e6de-11ea-9ebe-45152f4d2bc1.png)
![Screenshot 2020-08-25 at 14 16 07](https://user-images.githubusercontent.com/432549/91173403-10f76b80-e6de-11ea-83a0-c554e9e67c04.png)
![Screenshot 2020-08-25 at 14 16 21](https://user-images.githubusercontent.com/432549/91173407-1359c580-e6de-11ea-9088-ae71d6878d99.png)

**Comment by Ducasse** [comment]
The method ba:bar: exists.
during the third figure I removed the argument and not the : is correctly displayed which is strange.

**Comment by guillep** [comment]
With the fix to #7219 and #7222 I cannot reproduce it anymore. Let's wait until those are integrated to re-test.

**Comment by MarcusDenker** [comment]
I checked and I can not reproduce it anymore
