### ISSUE TITLE
Remove System Reporter

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7187]
It uses old morphic lists and it got rewritten in spec2.

**Comment by sic-f** [comment]
@Ducasse how do you do this? Did you mean delete the whole package?

![Issues_image](https://user-images.githubusercontent.com/17798988/92989705-bc8b2300-f508-11ea-9fe2-78daa263180c.png)

**Comment by Ducasse** [comment]
Yes we should wait for the next integration of Spec20 because the system reporter got fully reimplemented at the level of Spec20.

**Comment by sic-f** [comment]
> Yes we should wait for the next integration of Spec20 because the system reporter got fully reimplemented at the level of Spec20.

Ok so nothing can be done here until the next integration of Spec20?

**Comment by estebanlm** [comment]
next integration of newtools, in fact :)
