### ISSUE TITLE
UI frozen on image startup due to missing font file

### ISSUE THREAD

**Issue by ro6** [guillep/pharo-core#7199]
Pharo 8.0 expected a font file at `/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf` but it wasn't there and the UI froze on startup before I could do anything. I discovered the issue by checking `PharoDebug.log`. The file was actually located at `/usr/share/fonts/TTF/DejaVuSansMono.ttf` on my system (Arch Linux), so I just created a symlink from where Pharo looked to the actual location and that resolved.

This was my first ever image, created and loaded from the Pharo-Launcher. How does the image decide what font to use and where to look for it?

**Expected development cost**
I might be able to fix, but it looks like contributions are encouraged towards Pharo 9.0, which didn't have the same startup issue, but failed to install the Zinc package when I tried.

**Comment by astares** [comment]
There is no reference to such a font in the source code of Pharo 9

![image](https://user-images.githubusercontent.com/5980033/101684999-873e9480-3a67-11eb-94e5-ff4ee5c7f04a.png)

**Comment by MarcusDenker** [comment]
Pharo8 is now very old, I think we can close this (especially as this was already not a problem in Pharo9)
