### ISSUE TITLE
Strange behavior of Formatter while editing code... 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7210]
handleSharedPoolsFromNode: aNode
	| shareds sharedPoolNodes sharedPoolString |
	sharedPoolNodes := aNode children
		collect: [ :aPoolNode | 
			self sharedPoolNodeClass
				node: aNode
				name: aNode name
			].
	definition sharedPools: sharedPoolNodes

This code is not compiled. 
I’m editing it in the debugger (glamour) in latest Pharo 90
When I doubleclick on aPoolNode and press copy

I get an error  
RBSequence DNU name 
areArgumentsTooLong: anArray

	| size |
	size := anArray sum: [ :each | each name size ].
                                                               ^^^^^^^^

	^ self isLineTooLongWithNewCharacters: size

I do not know why.
I guess that the problem is that the text editor is parsing the code to get the range of the selection
and calling the formatter.

**Comment by guillep** [comment]
I cannot reproduce after my changes in #7219 and #7222. Let's wait until those are integrated to re-test.

**Comment by MarcusDenker** [comment]
I cannot reproduce this anymore, either
