### ISSUE TITLE
escaping strings and symbols in copy paste

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7214]
If I type

``` 
l'idiot
```
and select it and type '
I get 

``` 
'l''idiot'
```
and this is good

Now if I have '' and paste it inside strings are not escaped.

**Comment by guillep** [comment]
This is the same problem as #7219. The paste, based on the AST, is not correctly done because the AST is wrongly built.

**Comment by Ducasse** [comment]
cool :)
