### ISSUE TITLE
CDClassDefinitionParser raises an error when copying ProtoObject definition

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7218]
```
ProtoObject subclass: #ProtoObject
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Kernel-Objects'.
ProtoObject superclass: nil
```

but the new fluid syntax parser handles it well.

**Comment by guillep** [comment]
Is this the error?

![image](https://user-images.githubusercontent.com/708322/91982921-382be980-ed2b-11ea-8340-3b0e6a3c064f.png)

**Comment by guillep** [comment]
That happens when selecting all

**Comment by guillep** [comment]
This reproduces the problem:

```smalltalk
CDClassDefinitionParser parse: 'ProtoObject subclass: #ProtoObject
	instanceVariableNames: ''
	classVariableNames: ''
	package: ''Kernel-Objects''.
ProtoObject superclass: nil'
```

**Comment by guillep** [comment]
The parser uses `parseExpression:` but that is not an expression!

```smalltalk
CDClassDefinitionParser >> parse: aString 
	
	| expressionTree |
	expressionTree := RBParser parseExpression: aString.
	expressionTree doSemanticAnalysis.
	
	^ self parseRootNode: expressionTree
```

Also, there is another bug: parsing that code as an expression returns a sequence node!

**Comment by guillep** [comment]
https://github.com/pharo-project/pharo/issues/7233

**Comment by guillep** [comment]
I'm looking at CDClassDefinitionParser and it seems very fragile.

**Comment by Ducasse** [comment]
Yes. ;(

**Comment by Ducasse** [comment]
Yes this parser is super fragile. 
It breaks also in fluid.

**Comment by MarcusDenker** [comment]
I would like to change the class definition of nil subclasses to use the normal style... this means having some API on nil for class creation, but it is in the end simpler than the two expression defintion.
