### ISSUE TITLE
Copy paste raises error

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7219]
```
asFluidDefinitionString

	^ String streamContents: 
		[:strm |
		strm nextPutAll: self name.
		
		self hasTraitComposition ifTrue: [
			strm
				crtab;
				nextPutAll: 'uses: ';
				print: self traitComposition ].
		self slots ifNotEmpty: [  
			strm
				crtab;
				nextPutAll: 'slots: ';
				nextPutAll: self slotDefinitionString]]
```

when I copy paste `nextPutAll: self slotDefinitionString` I get a dnu

**Comment by guillep** [comment]
The AST of that method seems broken. Look at this.

![image](https://user-images.githubusercontent.com/708322/91981648-732d1d80-ed29-11ea-89b9-dad929b6a7d5.png)

The message node has as a child a variable and a sequence!
And the sequence has some strange errors...

**Comment by guillep** [comment]
This code seems wrong:

```smalltalk
RubSmalltalkEditor >> bestNodeInTextAreaWithoutSelection
...
	[node := RBParser parseMethod: intervalTrimmedText  onError: [ 
		RBParser parseFaultyExpression: intervalTrimmedText]
	] on: Error do: [^nil].
```

`parseMethod:onError:` will retry the parsing on an error but embed the result on the error node....

**Comment by guillep** [comment]
I don't understand why there is a parse method, and then try to parse a faulty expression. First, the code does not return the right thing. But that aside, this could never have a faulty method.

**Comment by guillep** [comment]
@Ducasse is this the same case as the copy-pasting of arguments?
