### ISSUE TITLE
Completion error when writing a block inside existing code

### ISSUE THREAD

**Issue by dupriezt** [guillep/pharo-core#7222]
**Describe the bug**
A debugger opens on a code completion error when I am adding a block with argument inside existing code

**To Reproduce**
1. Open a playground
2. Copy this code:
```Smalltalk
SpBoxLayout newVertical
	add: #label;
	yourself.
```
3. Place your cursor between `#label` and the semicolon
4. Type ` withConstraints: `. Your code should look like this:
```Smalltalk
SpBoxLayout newVertical
	add: #label withConstraints: ;
	yourself.
```
5. Type `[:cstr`, as if you were starting to write a block to be used as argument for the `withConstraints:`. Your code should look like this:
```Smalltalk
SpBoxLayout newVertical
	add: #label withConstraints: [:cstr;
	yourself.
```
6. A debugger opens on the error:
![image](https://user-images.githubusercontent.com/32486709/91831272-2885a580-ec44-11ea-8e01-3a7b9c49c698.png)

**Expected behavior**
No debugger should open while the user edits code.

**Additional Information**
If you type and close the block quickly enough, no error occur.

**Version information:**
 - OS: Ubuntu 20.04

**Comment by dupriezt** [comment]
If you first write the boundaries of the block (`[]`) and then fill the inside of the block, no error occur.

**Comment by Ducasse** [comment]
Thanks Thomas Guille will do a pass on many bugs this afternoon. 
I add it to the list.

**Comment by guillep** [comment]
I'm working on it.

**Comment by guillep** [comment]
Fix proposed in: https://github.com/pharo-project/pharo/pull/7228
This is a problem of the AST.

I do not entirely agree on the way the error is handled in the method, but that should be fixed in another issue.

**Comment by guillep** [comment]
See https://github.com/pharo-project/pharo/issues/7230
