### ISSUE TITLE
RBEnglobingErrorNode>>acceptVisitor: should not caught error

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#7230]
**Describe the problem**

The following method has a strange error management. I think we should at some point remove that handling

```smalltalk
RBEnglobingErrorNode>>acceptVisitor: aVisitor

	^ [ aVisitor visitEnglobingErrorNode: self ]
		on: Error
		do: [super acceptVisitor: aVisitor ].
```

https://github.com/pharo-project/pharo/issues/7222
https://github.com/pharo-project/pharo/issues/7228

**Version information:**
 - Version [e.g. Pharo 9.0]
 - Commit [e.g. 22]  Pharo-9.0.0+build.634.sha.658326a3eb4f26b45dc0efe988aa945d5470876b (64 Bit)

**Expected development cost**
Should be careful with AST users (e.g., completion)

**Comment by MarcusDenker** [comment]
PR https://github.com/pharo-project/pharo/pull/7348 removes it

**Comment by MarcusDenker** [comment]
merged
