### ISSUE TITLE
CompiledMethod #pragmaAt: returns method properties

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#7252]
**Describe the bug**
pragmaAt: returns both a pragma and a property with that key. 

**To Reproduce**

(Object>>#halt) propertyAt: #hello put: true.

(Object>>#halt) pragmaAt: #hello. "--> true"

(Object>>#halt) hasPragmaNamed: #hello "--> false".

**Expected behavior**
properties and pragmas are two distinct concepts. #pragmaAt: should *never* return a property value!

pragmaAt: seems to be wrong in general, as there can be multiple pragmas with the same key but different arguments in a method.

**Comment by MarcusDenker** [comment]
test:


testPragmaAt
	| method |
	method := (SmallInteger>>#+) copy.
	self assert: (method pragmaAt: #primitive:) selector equals: #primitive:.
	self assert: (method pragmaAt: #hello) equals: nil.
	method propertyAt: #hello put: true.
	"Pragmas are not Properties!"
	self assert: (method pragmaAt: #hello) equals: nil.

**Comment by MarcusDenker** [comment]
the whole idea of Pragmas being stored in AdditonalMethodState together with the associations is just wrong.

**Comment by dionisiydk** [comment]
> the whole idea of Pragmas being stored in AdditonalMethodState together with the associations is just wrong.

I wonder why they are not simply encoded as other literals

**Comment by MarcusDenker** [comment]
I think because the number of possible literals with the old bytecode set was quite small...

adding them as literals does have some problems
-> slows down senders of a tiny bit
-> accession them needs a select:
-> there was some aversion against adding non-literals to the literal array (there is quite some machinery in Slots and MetaLinks
to use Literal Variables instead, but I am thinking of removing that to simplify as I do not see the point anymore)

An alternative could be to add a subclass of AdditionalMethodState with a pragma instance variable that stores all Pragmas of the method. We know if a method has Pragmas or not at compile time, so we can create at special CompiledMethod (we could even have a dedicated Subclass)
