### ISSUE TITLE
Copy pasting pragma body with argument inside another pragma raises error

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7257]
I will try to reproduce it.

**Comment by Ducasse** [comment]
Ok to reproduce we should copy and paster replacing the contents inside the < >.

**Comment by MarcusDenker** [comment]
I tracked it down to this:

RBMethodNode>>#stop
	^ self newSource size

This makes no sense: it forces a reformat and the stop (end) of the source... but the AST should have all the text mapping infos based on the *current* source, not the reformatted one.

changing it to "self sourceCode size" fixes the problem.

**Comment by demarey** [comment]
I confirm the fix is working for pragmas
