### ISSUE TITLE
Debugger's botton panel doesn't update parameters when steping into a recursive call

### ISSUE THREAD

**Issue by weslleymberg** [guillep/pharo-core#7286]
**Describe the bug**
The bottom panel of the debugger does not update parameters when steping into a recursive call

**To Reproduce**
1. Call 'debug it' on a recursive function
2. Step into the recursive call
3. Temp variables will still show the parameters for the first call

**Expected behavior**
Temp variables should reflect the parameters of the call.

**Screenshots**
![image](https://user-images.githubusercontent.com/647154/92725405-7e440700-f342-11ea-87c0-5ec8c8c98875.png)

**Version information:**
 - OS: Windows 10
 - Version: 1904
 - Pharo-9.0.0+build.652.sha.713b9dbf032dfb9c09406e86323a21624bfa149f (64 Bit)

**Additional context**
The bytecode debugger's extension shows the correct temp variables as shown in the print.

**Comment by Ducasse** [comment]
Thanks a lot. We are experiencing some regression in this moment.
