### ISSUE TITLE
Debugger: Class column shows class of receiver, but not class of method

### ISSUE THREAD

**Issue by martinmcclure** [guillep/pharo-core#7295]
**Description**
The debugger's stack has columns "Class" and "Method". Method shows the selector of the method. Class, currently, shows the name of the class of the _receiver_. The class of the _method_ is not shown. Traditionally, both are shown -- receiver class, then the method's class in parentheses if not the same. 

Both classes are probably useful, but if only one were to be shown, I'd find the method's class to be much more useful than the receiver's class.

**To Reproduce**
Create a hierarchy of three classes, A, B, and C.
![image](https://user-images.githubusercontent.com/2240523/93007180-ad14d580-f51a-11ea-8a03-3fd99bf85bcf.png)

Add initialize methods
A>>initialize self halt
B>>initialize super initialize. self b
C>>initialize super initialize.self c

In a Playground, evaluate 
C new

**Expected behavior**
Debugger opens with three #initialize methods at top, with class shown as either C(A), C(B), and C, or as A, B, and C. Instead, all three are labeled C.

**Screenshots**
![image](https://user-images.githubusercontent.com/2240523/93007241-87d49700-f51b-11ea-8d63-68a851f58810.png)

In this image, note that although B>>initialize is the actual selected method, the inspector incorrectly believes that thisContext is C>>initialize. This problem might or might not be separate.

**Version information:**
 - OS: Linux (Gentoo stable)
 - Version: Pharo9.0.0 build 657

**Comment by martinmcclure** [comment]
Not sure of the full fix, but the class display issue appears to be in StDebugger>>initializeStack. Replacing this:

		addColumn: (SpStringTableColumn
				 title: 'Class'
				 evaluated: [ :item | item receiver class ]);

with this

		addColumn: (SpStringTableColumn
				 title: 'Class'
				 evaluated: [ :item | item methodClass]);

gives something more useful. But if you want the traditional "receiverClass (methodClass)" presentation, that will be slightly more complicated.

Also, this change does not seem to affect the problem with "thisContext" in the inspector not updating when a different context is selected that has the same receiver and the same selector, but the implementation is in a different class due to a super send. So that must be in code elsewhere.

**Comment by StevenCostiou** [comment]
Hi @martinmcclure 
so the inspector problem is already fixed in latest new tools (I did nothing, just checked). 
It's just waiting for the next merge (probably next week).

![Screenshot 2020-09-15 at 09 25 10](https://user-images.githubusercontent.com/26929529/93179002-5df6bc80-f735-11ea-9c24-71ee9987b0c9.png)

I will do a similar fix for the columns of the stack panel, and this will be included in the next merge.

**Comment by StevenCostiou** [comment]
The fix will look like this: (next week)
![Screenshot 2020-09-15 at 09 45 28](https://user-images.githubusercontent.com/26929529/93181000-32290600-f738-11ea-9c19-e79fd8d3384a.png)

**Comment by martinmcclure** [comment]
Great, thanks! I'll close this once I see the merge, unless you'd rather close it now.

**Comment by martinmcclure** [comment]
Fixed as @StevenCostiou reported. Closing, thanks!
The "Receiver in:..." line is still able to be confused as to which of the initialize methods it's in, but it looks like that line is likely still under development.
