### ISSUE TITLE
Close all Debuggers menu option is not working. 

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#7313]
If you have many open debuggers, and you do right button on the taskbar and then in close all debuggers it generates DNUs.

**Comment by dupriezt** [comment]
OupsDebuggerSystem class>>#closeAllDebuggers expects all users of the TDebugger trait to understand #closeAllDebuggers but it is not the case.
These users are:
- EDEmergencyDebugger
- TDebuggerTest
- GTGenericStackDebugger
- StDebugger

StDebugger and GTGenericStackDebugger understand the #closeAllDebuggers message.
I'll see if I can implement a #closeAllDebuggers method on the remaining two users

**Comment by MarcusDenker** [comment]
I merged the PR, but it is just an intermediate step, therefore: re-opened

**Comment by StevenCostiou** [comment]
I tagged it with sprint, I would like phd students to look at that and pair-program during next sprint @dupriezt @maxwills

**Comment by dupriezt** [comment]
I don't see what more to do here.

**Comment by StevenCostiou** [comment]
The idea was to brainstorm and possibly improve the design of the solution but I think when we merged we lost all the discussion. I do not see it anymore, do you know where to find it?

**Comment by dupriezt** [comment]
> 
> 
> The idea was to brainstorm and possibly improve the design of the solution but I think when we merged we lost all the discussion. I do not see it anymore, do you know where to find it?

It's there: https://github.com/pharo-project/pharo/pull/7328#discussion_r490418730

**Comment by StevenCostiou** [comment]
Up! Can someone work on this during next sprint?
