### ISSUE TITLE
Enhance New debugger to show the instance variable of self

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#7318]
**Describe the request**
In the screenshot, as the 'temps', there should be a 'self' that could be extended and see the Instance variables
![image](https://user-images.githubusercontent.com/4706329/93325886-4a705200-f818-11ea-9a14-fb09031ccfee.png)

**Version information:**
 - OS: win10
 - Version: Pharo9.0.0 build: 665, commit: cb36ee8

Suggested by @ToshRaka

**Comment by Ducasse** [comment]
Yes steven already changed it in the dev branch because we are not happy with the current schema
We tried many different approaches and we are not really satisfied.

**Comment by StevenCostiou** [comment]
It will be fixed by https://github.com/pharo-project/pharo/pull/7311

**Comment by MarcusDenker** [comment]
merged
