### ISSUE TITLE
completion scope failure with unfinished brackets and temp

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#7344]
**Describe the bug**
When you write a method that contains a temporary variable and use unfinished brackets during typing (it is more easily discoverable with _smart characters_ setting turned off), you get a nil scope of the code completion

**To Reproduce**
To any class, write this method code: 
```smalltalk
test 

	| temp |
	[ [  ]
```

It will produce an error: `MessageNotUnderstood: receiver of "lookupVar:" is nil`

**Comment by MarcusDenker** [comment]
This seems to be fixed by this PR: https://github.com/pharo-project/pharo/pull/7348

**Comment by MarcusDenker** [comment]
merged
