### ISSUE TITLE
Improve Exception description API

### ISSUE THREAD

**Issue by StevenCostiou** [guillep/pharo-core#7347]
Following https://github.com/pharo-project/pharo/pull/7335 integration.
`Exception` implements a `description` method and a `smartDescription` method that returns more detailed information.
Instead a better naming should be chosen:
- use `description`to provide the *smart description*
- use `defaultDescrption`when there is no *smart description* implmented

**Comment by samakhov** [comment]
@StevenCostiou according to what you have said in #7335 `defaultDescription`  should be called by description, but I don't figure how to deal with what that considering the role of `description` here. A bit confusing for me :)
