### ISSUE TITLE
DNU #text when doing a printIt in the Playground

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#7357]
**Describe the bug**
The requestor used when executing code in the workspace misses a #text method

**To Reproduce**
Try to "print it" in a playground:

   [:each | [ :each ] ]

**Comment by MarcusDenker** [comment]
@estebanlm

**Comment by estebanlm** [comment]
and what has to be that text?

**Comment by MarcusDenker** [comment]
it seems to be the code. In general, it looks like all this could be refactored and be much simpler...

**Comment by MarcusDenker** [comment]
SpCodeInteractionModel>>#text needs to be implemented as:

text
	^self owner text


and it works

**Comment by MarcusDenker** [comment]
another method I need:


SpCodeInteractionModel>>#bindings


bindings
	"no additional bindings provided by the Requestor"
	^#() asDictionary

**Comment by MarcusDenker** [comment]
This has been fixed!
