### ISSUE TITLE
Spec: some tests modify literal arrays

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#7359]
**Describe the bug**
Recompile the image with #optionReadOnlyLiterals enabled, these methods modify literal arrays:

SpAbstractListPresenterTest>>#setUp
SpAbstractListPresenterTest>>#testSetSortingBlockBeforeItems
SpAbstractListPresenterTest>>#testSortingBlock
SpComponentListPresenterTest>>#testSetSortingBlockBeforeItems
SpComponentListPresenterTest>>#testSortingBlock
SpDropListPresenterTest>>#testSortingBlock

A trivial way of solving the failing test is to add a "copy" after the literal array.

**Comment by MarcusDenker** [comment]
How to reproduce: add this pragma to the method:

	<compilerOptions: #(+ optionReadOnlyLiterals )>

**Comment by demarey** [comment]
Now on hold until PR is integrated into Spec, then merged into Pharo
