### ISSUE TITLE
Selected text from SystemBrowser 

### ISSUE THREAD

**Issue by SchweinchenFuntik** [guillep/pharo-core#7361]
**Describe the bug**
when pressing the key combination Ctrl + A. Mouse selection is ok

**To Reproduce**
1. Go to 'Comment'
2. Click on 'Ctrl + A
3. See error

**Screenshots**
![зображення](https://user-images.githubusercontent.com/22637705/94169083-08d64b80-fe97-11ea-8ad6-ed47360f064d.png)

**Version information:**
 - OS: Linux 5.4.64-1-MANJARO
 - Version: Pharo 9.0

**Comment by MarcusDenker** [comment]
This is fixed, I can select with Ctrl-A
