### ISSUE TITLE
Failin on CI: RSBarPlotTest>>test2BarPlots

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#7370]
**Describe the bug**
RSBarPlotTest>>test2BarPlots started failing on the CI 25/09/2020.

Error
Got (220.0731707317073@200.0) instead of (203@200).
Stacktrace
TestFailure
Got (220.0731707317073@200.0) instead of (203@200).
RSBarPlotTest(TestAsserter)>>assert:description:resumable:
RSBarPlotTest(TestAsserter)>>assert:description:
RSBarPlotTest(TestAsserter)>>assert:equals:
RSBarPlotTest>>test2BarPlots

Strangely It is not failing when running it in the image interactively in the same version.

**Comment by MarcusDenker** [comment]
I wonder if we should skip the test for now on the CI... to much work to make the CI green and from one day to the next this breaks and it is completely not clear why.

A green CI would even make sure that this would not happen: we should *never* integrate if the ci is not green. But if the CI is "known to be not green" it is so easy to add even more failure...

**Comment by MarcusDenker** [comment]
@akevalion can you check? This test just started to fail last friday.

**Comment by akevalion** [comment]
Hi @MarcusDenker I have fixed this issue with a rollback in https://github.com/ObjectProfile/NumericScales.
Roassal3 release will depend on releases to avoid this issue in a future 

<blockquote><img src="https://avatars1.githubusercontent.com/u/2318368?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/ObjectProfile/NumericScales">ObjectProfile/NumericScales</a></strong></div><div>Numerical scales for Pharo. Contribute to ObjectProfile/NumericScales development by creating an account on GitHub.</div></blockquote>

**Comment by MarcusDenker** [comment]
Thanks!
