### ISSUE TITLE
Error when tring to copy text from code pane: MNU receiver of #getCommentsFor: isNil

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#7389]
**Describe the bug**
MNU receiver of #getCommentsFor: isNil

**To Reproduce**
1. Open the browser
2. Create a class `A`
3. add a method to this class:
```smalltalk
test

	| a b |

	a := (Object
		name: 'a') a: #().
	b := (Foo
		name: 'b').
```
4. try to copy (CTRL+C) the text `) a: #().`

**Expected behavior**
The text should be copied without any try to parse it.

**Version information:**
Pharo-9.0.0+build.699.sha.2ac6d670db10b42b7404cf629042b611f4c6e8ec (64 Bit)

**Comment by MarcusDenker** [comment]
this should be fixed by https://github.com/pharo-project/pharo/pull/7373

**Comment by MarcusDenker** [comment]
(review needed)

**Comment by demarey** [comment]
> this should be fixed by #7373

No, the fix does not apply to this issue

**Comment by MarcusDenker** [comment]
Ups... I looked at it again and did a fix for #7375 that seems to fix this one, too.

**Comment by demarey** [comment]
I can confirm 2618803 fixes this issue. Thanks Marcus.

**Comment by MarcusDenker** [comment]
Nice! I will merge it
