### ISSUE TITLE
Debug It is broken

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#7405]
**Describe the bug**
`Debug it` functionality raises a DNU related to Pragma changes

**To Reproduce**
1. open Playground
2. paste some code, e.g. `self yourself`
3. perform `Debug it` from the context menu
4. `MessageNotUnderstood: RBMessageNode>> #hasPragmaNamed:`

(notice that hot-fixing it to the `ast methodNode` leads to another issues)

**Comment by MarcusDenker** [comment]
this is a side-effect of the change to have a distinct code path for compiling doit and non-doits.

SpCodeDebugItCommand>>#compile:for:in:, change #compile to #compileDoit 

there should be a way to have #compile do the right thing automatically, I will check that.
