### ISSUE TITLE
Fileout a protocol raises a DNU

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7416]
```
fileOut
	| internalStream class |
	internalStream := (String new: 1000) writeStream.
	internalStream
		header;
		timeStamp;
		cr.
	self methods do: [ :each | each origin printMethodChunk: each selector on: internalStream ].
	internalStream trailer.
	class := methodQuery scope basisObjects anyOne.
	^ CodeExporter writeSourceCodeFrom: internalStream baseName: class name , '-' , self name isSt: true
```

trailer is unknown.

**Comment by guillep** [comment]
> El 4 oct 2020, a las 13:47, StéphaneDucasse <notifications@github.com> escribió:
> 
> 
> fileOut
> 	| internalStream class |
> 	internalStream := (String new: 1000) writeStream.
> 	internalStream
> 		header;
> 		timeStamp;
> 		cr.
> 	self methods do: [ :each | each origin printMethodChunk: each selector on: internalStream ].
> 	internalStream trailer.
> 	class := methodQuery scope basisObjects anyOne.
> 	^ CodeExporter writeSourceCodeFrom: internalStream baseName: class name , '-' , self name isSt: true
> trailer is unknown.
> 
I’d also ask myself why a write stream on a string understands stuff such as #header or #timeStamp :)
And why it did not break ^^

**Comment by MarcusDenker** [comment]
header is just empty:

header
	"If the stream requires a standard header, override this message.  See HtmlFileStream"


I suggest a two step approach: remove senders of trailer and header, this will make it work (thus people can use it)

CodeExporter later should be the place for the methods (I guess) related to file-out, not the stream classes.
