### ISSUE TITLE
Renaming a method in a Trait does not propagate changes to the Trait users

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#7429]
**Describe the bug**
Renaming a method in a Trait does not propagate changes to the Trait users.
The method is only renamed in the trait. Methods in trait users are kept unchanged.

**To Reproduce**
1. Find a Trait with users (ex: TCopySequenceableWithReplacement)
2. Click on a method
3. Hit CMD+R to trigger the rename refactoring.
4. Rename and accept

**Expected behavior**
I expect the rename to be propagated to the trait users.

**Version information:**
Pharo 9.0

**Comment by jecisc** [comment]
I fixed that a while ago
