### ISSUE TITLE
ZnBufferedWriteStream>>truncate results in corrupted file

### ISSUE THREAD

**Issue by akgrant43** [guillep/pharo-core#7449]
**Describe the bug**
Calling `ZnBufferedWriteStream>>truncate` when the underlying stream is to a disk file can result in a corrupted file.

**To Reproduce**

```
	'truncate.test' asFileReference writeStreamDo: [ :stream |
		1 to: 12764 do: [ :i |
			stream 
				<< (i printPaddedWith: $0 to: 9);
				lf ].
	stream truncate ].
```

will normally cause the problem.

**Expected behavior**

The file is truncated to 0 bytes (I actually think this is wrong, it should be truncated to the current position, but that's an issue with `BinaryFileStream`.

**Version information:**
 - OS: Ubuntu 20.04.
 - Version: Pharo-9.0.0+build.730.sha.3c31ba34ab77d89ee6203b8e36f1c4f12affe741 (64 Bit)

**Expected development cost**

The issue appears to be that `ZnBufferedWriteStream>>truncate` doesn't flush the buffers before truncating the underlying stream, see `ZnBufferedWriteStream>>truncate:`.

The development cost is trivial, since it is adding one known line of code.

I'm happy to do this, but would appreciate some feedback from Sven.

**Additional context**

**Comment by svenvc** [comment]
Hi Alistair,

I am not very sure what the exact semantics of truncate on a stream (as opposed to a file). I never use it.

Furthermore, truncate without an argument would seem to be equal to truncate: 0 which would effectively delete everything, no ?

But again, on a file yes, but on a general stream ?

Apart from that, doing a flush first would seem logical (but again, why if you throw everything away ?).

Maybe I am not seeing this correctly. How would you expect to use truncate on a stream ?

Sven

**Comment by akgrant43** [comment]
Hi Sven,

I'll try and answer the semantics through an example:

File streams are positionable, so if I want to maintain a structured file, e.g. some sort of database, and update records in the middle of the file, positioning the stream and writing to it is how that will be achieved.

If the database is modified in such a way that the last x records are no longer required, or the contents are compacted, the file should be truncated back to the end of the last record.  If that isn't done, the file has no way of shrinking as the database contents shrink.

So there's no real different between the semantics of truncate on a stream vs. file, since the stream is the only way of accessing the file.

I think the definition of `BinaryFileStream>>truncate` is wrong.  Instead of truncating to 0, it should truncate to the current stream position.  This is the definition of `WriteStream>>truncate`.  But that is a separate issue.

So while I agree that the current definition seems not particularly useful, it should still work.

> Apart from that, doing a flush first would seem logical (but again, why if you throw everything away ?).

Because without flushing first, I've asked to throw everything away, but end up with garbage instead, i.e. a non-empty file. :-)

If I execute the 'To Reproduce' code above, I should end up with an empty file.  What I get is one that has a corrupted version of what was written before.  If the flush is added, I do get an empty file (and will then probably want to submit a change request to Pharo to change the definition of `BinaryFileStream>>truncate` :-)).

**Comment by svenvc** [comment]
I am not a big fan of file positioning, but it exists.

I don't see WriteStream>>#truncate in my 7.0.5 image

So concretely, I am guessing you want ZnBufferedWriteStream>>#truncate to call either #truncate:0 or #truncate: self position, right ? Is #flushBuffer enough or do you really need #flush ?

I would suggest that you try changing it locally and see if it solves your issues and if it does not break anything.

**Comment by akgrant43** [comment]
Hi Sven,

My apologies for my slow response.

The only change I'm looking for here is adding `#flushBuffer` to `ZnBufferedWriteStream>>truncate` (so that it matches `ZnBufferedWriteStream>>truncate:`):

```
truncate

	self flushBuffer.
	stream truncate
```

This solves my issue (the code snippet above behaves as expected), all the tests in `Zinc-Character-Encoding-Tests` continue to pass, and I haven't noticed any detrimental behaviour.

**Comment by svenvc** [comment]
Applied upstream

https://github.com/svenvc/zinc/commit/0ad6a269b4ea467385760ebcf9dcbf20f508e386

Thx,

Sven

**Comment by akgrant43** [comment]
Thanks, Sven!

Cheers,
Alistair
