### ISSUE TITLE
[Debugger] Get "I am an Oups NULL debugging exception" when debug it

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#7453]
**Describe the bug**
Get "I am an Oups NULL debugging exception" as title of the debugger when doing a **debug it**

**To Reproduce**
1. Open a playground
2. type 1 + 2
3. select 1 + 2 and **debug it**

**Expected behavior**
I expect to have a message like "Debug it session".

**Screenshots**
![debugger-oups-on-do-it](https://user-images.githubusercontent.com/2494203/95565169-13105200-0a20-11eb-885e-1cdc18c3aa6c.gif)

**Comment by StevenCostiou** [comment]
Fixed, this will be present in the next merge.
