### ISSUE TITLE
[Spec][Debugger][Inspector] no visual feedback that a new panel is added to the right of the Miller list

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#7454]
**Describe the request**
There is no visual feedback that a new panel is added to the right of the Miller list when inspecting in the debugger.
Also, when navigating the miller list, you cannot know where you are in the list.

**Expected behavior**
Inspector should scroll automatically to the newly created panel.
Miller list should also provide a visual feedback: create a dotted list with one dot for each pane and show the current selection in the list.

**Screenshots**
![debugger-enh-inspector](https://user-images.githubusercontent.com/2494203/95566953-92068a00-0a22-11eb-96e8-b9cdad22883a.gif)

**Comment by StevenCostiou** [comment]
This is not a debugger problem, could you tag it as spec or NewTools instead?

**Comment by demarey** [comment]
I will open an issue for this on Spec issue tracker.
I think we should keep this issue open because inspector is used in the debugger, so there is also a problem in the debugger.
The fix has to be done in Spec but the issue is present in the debugger.

**Comment by demarey** [comment]
related to https://github.com/pharo-spec/Spec/issues/954

**Comment by StevenCostiou** [comment]
But it is not the debugger, it is the spec miller list. Every tool using miller lists have that bug (it's the inspector actually so probably in NewTools).

**Comment by demarey** [comment]
I know that the problem has to be solved in spec but for a Pharo user, it is a problem showing up in the debugger. Inspector is still GTInspector, the problem is not there.
Keeping the issue open and linked to the spec issue allow Pharo users to see that the problem is identified.

**Comment by StevenCostiou** [comment]
I think this is solved now since the last NewTools merges.
