### ISSUE TITLE
[Spec][NewTools] some icons are hidden until mouse over them and exit

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#7455]
**Describe the bug**
In the debugger, inspectors miss some icons (inspect, refresh, browse) until one mouse over the area and exit it.

**To Reproduce**
Open the debugger and inspect an element

**Expected behavior**
All icons should be there at inspector opening.

**Screenshots**
![debugger-bug-inspector-icons](https://user-images.githubusercontent.com/2494203/95569333-bb74e500-0a25-11eb-848c-d99d7ca228ff.gif)

**Comment by StevenCostiou** [comment]
This is not a debugger problem, could you tag it as spec or NewTools instead?

**Comment by StevenCostiou** [comment]
I think this is solved now since the last NewTools merges.
