### ISSUE TITLE
Fluid Class: use <| instead of < for class definition

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7471]
As denis reported < is a bit too intrusive since it will eat potential errors...
let us say that we will get the errors on classBuilder instead of nil. 
So may be we could use <| instead of < since it looks like the UML triangle. 

To be discussed.

**Comment by Ducasse** [comment]
Denis wrote 

```
#< is really bad message for nil object. It will eat errors in many comparison cases when variables are nil:

aNumber < 10
aString < 'anotherString'
```
I do not really see the point because writing aNumber < 10 and expecting that it will work for nil 
is really a bad idea.

**Comment by Ducasse** [comment]
Now I'm open to discussion.

**Comment by dionisiydk** [comment]
> ```
> #< is really bad message for nil object. It will eat errors in many comparison cases when variables are nil:
> 
> aNumber < 10
> aString < 'anotherString'
> ```
> 
> 
> I do not really see the point because writing aNumber < 10 and expecting that it will work for nil
> 
> is really a bad idea.

If expression will not break immediately it can fail at very unexpected time in future. Therefore it will be difficult to debug. For example: 
```Smalltalk
MyClass>>myMethodWith: aNumberArgument
   boolInstVar := aNumberArgument < 10
MyClass>>anotherMethod
   boolInstVar ifTrue: []
``` 
Just imagine what user will think about Pharo seeing aClassDefinition in the boolInstVar in the debugger on #anotherMethod. Yet another WHAT! from JS world.
