### ISSUE TITLE
testSharedSlotNodeArePolymorphicToRBVariableNodes is failing in default image

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7481]
And this is not related to fluid class definition (it happens when it is not enabled).

**Comment by MarcusDenker** [comment]
it seems that class variables are not parsed when parsing fluid class definitions.

**Comment by Ducasse** [comment]
The solution is to use the adequate parser and not a random one. 

classDefinitionString

	^ (ClassDefinitionPrinter oldPharo for: CDClassWithFullDefinitionExample) definitionString
