### ISSUE TITLE
[ Fluid ] Adding Setting for fluid Syntax

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7522]
Yes this is needed.

**Comment by MarcusDenker** [comment]
There is already a setting for the old  style in Slot class>>#slotSetting: , I think this could be moved / renamed:

slotSetting: aBuilder 
	<systemsettings>
	(aBuilder setting: #showSlotClassDefinition) 
		label: 'Class Template with Slots';
		default: false;
		description: 'If checked then browsers show always the slot class definition';
		parent: #codeBrowsing; 
		target: self

**Comment by Ducasse** [comment]
Thanks I will have a look.
