### ISSUE TITLE
Potential regression around anonymous subclass

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7525]
Hello, when following lecture
[W7S4](https://www.youtube.com/watch?v=viQYrmnrTUw&list=PL2okA_2qDJ-kCHVcNXdO5wsUZJCY31zwf&index=89)
I tried to run the example for adding spying to the Set class using an anonymous class.

However, running the code logClass superclass: Set. (to set the superclass of the anonymous class) in Pharo 8.0 raises the error "Instance of Behavior did not understand #classInstaller". This happens in the method Behavior>>#superclass: aClass.

To be sure, I tried running this in Pharo 9.0 (latest build) and it fails too, whereas in Pharo 6.1 and it works.

I asked for the script so that we can reproduce it.

**Comment by aronfiechter** [comment]
Here is the code snippet:

```smalltalk
| logClass set |
logClass := Behavior new.
logClass superclass: Set;
    setFormat: Set format.
logClass compile: 'add: anObject
    Transcript show: ''adding '', anObject printString; cr.
    ^ super add: anObject'.
set := Set new.
set add: 1.
set class. "Set"
set primitiveChangeClassTo: logClass basicNew.
set add: 2. "adding 2"
```

This more generic example of this snippet also fails (at [6:25](https://youtu.be/viQYrmnrTUw?t=385) in the video):

```smalltalk
testInstanceSpecificBehavior
  | behavior model |
  behavior := Behavior new.
  behavior superclass: Model.
  behavior setFormat: Model format.
  model := Model new.
  model primitiveChangeClassTo: behavior new.
  self assert: model class = behavior.
  self assert: model class superclass = Model.
  behavior compile: 'foo ^ 2'.
  self assert: model foo = 2.
  self should: [ Model new foo ] raise: MessageNotUnderstood.
```

**Comment by MarcusDenker** [comment]
With the new class builder I always use #newAnonymousSubclass to create anonymous subclasses

**Comment by Ducasse** [comment]
Ok I will still have a look at the snippet to check and we will update the mooc.

**Comment by MarcusDenker** [comment]
It might be even possible to fix it. What happens is that it calls #classInstaller on the Behaviour, but that is only defined in Class

**Comment by jecisc** [comment]
Should we keep this open or do we close it since there is a new way and the issue is 4yo?

**Comment by Ducasse** [comment]
Close
