### ISSUE TITLE
[ Fluid ] Propose a small class template and a full

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7536]
The small class template should be. 
```
Object < #MyClass
	slots: {};
	sharedVariables: {};
	package: 'A package'
```

while the full should be 

```
Object < #MyClass
	layout: FixedLayout;
	uses: {};
	slots: {};
	sharedVariables: {};
	sharedPools: {};
	tag: '' ;
	package: 'A package'
```

**Comment by dionisiydk** [comment]
I think the trait definition should also be proposed here for discussion.

**Comment by dionisiydk** [comment]
@Ducasse Are you going to use |> instead of  <  symbol?

**Comment by dionisiydk** [comment]
Could you also describe a decision to use superclass as receiver against what I proposed in past.
My idea was to avoid the case with nil superclass using "static" receiver Class. I am talking about this case: 
```Smalltalk
nil |> #ProtoObject 
        slots: {};
	package: 'A package'
```
I guess you have a reason to prefer superclass based version even with this problem. It's interesting to know and I think it should be explained in some public docs (why Pharo chooses this "syntax"). Do you actually agree that the nil case is an issue? 
To remind you, my proposal was:
```Smalltalk
Class < #MyClass
        superclass: #Object;
	slots: {};
	sharedVariables: {};
	package: 'A package'
```

**Comment by Ducasse** [comment]
We will use <| so that this is like UML.

**Comment by Ducasse** [comment]
To me nil <| #ProtoObject is nice and there is no issue.
