### ISSUE TITLE
KeyNotFound error in class comments for BaselineOf subclasses

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#7539]
- create a package "BaselineOfFoo"
- create a class **BaselineOfFoo** as subclass of **BaselineOf**
- click on the comment

=> KeyNotFound error is thrown as the MicroDown default comment builder wants to use the #baseline: method
      **which is not there yet**

**Comment by Ducasse** [comment]
Yes this is fixed in the new release.

**Comment by astares** [comment]
@Ducasse Thanks!
