### ISSUE TITLE
Polygon Morphs have holes in them

### ISSUE THREAD

**Issue by riverdusty** [guillep/pharo-core#7595]
**Describe the bug**
Create 2 objects of type Polygon morph with a mouseDown: handler.
Add one as a submorph to the other.
When clicking in certain places on the submorph the event goes 'through' the submorph to the parent morph.
These holes can be seen by running 
```
(PolygonMorph vertices: {261@400. 388@519. 302@595. 	222@500.	141@583. 34@444}
		color: Color blue
		borderWidth: 3
		borderColor: Color black) filledForm
```
I've created a small package to show this issue more clearly.
https://github.com/riverdusty/MorphicBugs
Load into latest Pharo9 image.
Run `FilledFormBug open`
Try clicking on the blue morph where the left hand side shows these 'holes'.
You'll see the background morph click event is triggered instead of the foreground morph.

**Comment by Ducasse** [comment]
Thanks!

**Comment by jecisc** [comment]
We plan to move from Morphic to Bloc.

I'm not sure anybody will work on this, should we keep it open?

**Comment by riverdusty** [comment]
> We plan to move from Morphic to Bloc.
> 
> I'm not sure anybody will work on this, should we keep it open?

Please clarify this.
You mean Pharo is going to do away with morphic and all support for morphic?
Or that development would be focused more on Bloc but Morphic is still an option?

In the latter (or either case) the above bug is still relevant. Firstly, not everybody is planning on moving to Bloc, and secondly, this should be kept in mind when developing Bloc to ensure Bloc does not suffer the same problem.
