### ISSUE TITLE
 buildTextMorph is called twice on every single browser opening :(

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7600]
Simple 
Edit  buildTextMorph on ClyTextEditorToolMorph and place an halt and count :(

**Comment by Ducasse** [comment]
This method is called even more on opening :(

**Comment by hernanmd** [comment]
Checked in the latest Pharo 12 and this couldn't be reproduced anymore:

![Screenshot 2024-03-18 at 13 30 39](https://github.com/pharo-project/pharo/assets/4825959/3f3e74de-0b41-487b-847c-a3ac67ed537e)

So I close the issue for now.
