### ISSUE TITLE
Skew selection boxes in the help

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#7614]
**Describe the bug**
In some special cases, the selection box in the class comment view can have skew border.

**To Reproduce**
Create a class with this comment:
<pre>
To open me, evaluate:

```language=Pharo
ApedFormEditor openWithGtk.
```
</pre>

Try to do selection like this:
![ko5dPZh8pR](https://user-images.githubusercontent.com/572494/97553000-330ab400-19d5-11eb-810c-9fd5fcc483f4.gif)

**Comment by astares** [comment]
Bug or feature?

**Comment by MarcusDenker** [comment]
Duplicate of https://github.com/pharo-project/pharo/issues/7361

**Comment by MarcusDenker** [comment]
This now works!
