### ISSUE TITLE
Automatic deprecations do not work with message sent as symbols.

### ISSUE THREAD

**Issue by chisandrei** [guillep/pharo-core#7625]
When the deprecated message it sent using #perform asa symbol the automatic deprecation fails. For example `self deprecatedValue ifNotNil: #deprecatedMessage`.  Here if `deprecatedMessage` has a rewrite there will be a failure.

The code below reproduces the problem:
```
Object subclass: #TestDeprecation
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'TestDeprecation'.
	
TestDeprecation compile: 'deprecatedMessage
	self
		deprecated: ''Please use #nonDeprecatedMessage instead''
		transformWith: ''`@receiver deprecatedMessage'' -> ''`@receiver nonDeprecatedMessage''.
	^ self nonDeprecatedMessage'.
	
TestDeprecation compile: 'deprecatedValue
	^ self'.
	
TestDeprecation compile: 'nonDeprecatedMessage
	^ 42'.

TestDeprecation compile: 'startMethod
	self deprecatedValue ifNotNil: #deprecatedMessage'.


Deprecation activateTransformations: true.
TestDeprecation new startMethod
```

Tested on Pharo-9.0.0+build.797.sha.9df2a84198ad75a440aa9672cde0443bdfce18d8 (64 Bit)

**Comment by MarcusDenker** [comment]
I add this to the issue about Deprecation transform and perform: https://github.com/pharo-project/pharo/issues/11419
