### ISSUE TITLE
When creating a method with the debugger receiving a Boolean argument, aBoolean should be the name of the argument

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#7627]
**Description**

When having a Do-not-understood message is possible to create a new method in the debugger. If the method receives a boolean as an argument the name of the argument is aTrue or aFalse, it would be better if it is aBoolean. 

**Expected development cost**
Easy

**Version information:**
 - Version: Pharo 9
- OS: all operating systems

**Comment by tinchodias** [comment]
I loaded it and works perfectly
