### ISSUE TITLE
Running tests in the TestRunner should not popup any debugger

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#7628]
**Describe the bug**
If failing with PotentialOutDatedDependencyWarning, the test DATarjanAlgorithmTest >> #testNoOutgoingDependenciesAfterTarjan will open a debugger despite it is run within the test runner without the debug mode.

The issue is that PotentialOutDatedDependencyWarning is a subclass of Warning that is not caught by the test runner

**To Reproduce**
0. You may have to force the test to raise PotentialOutDatedDependencyWarning
1. Open the test runner
2. Run the tests
3. Wait

**Expected behavior**
No debug window

**Screenshots**

**Version information:**
 - OS: win 10
 - Version: build: 797, commit: 9df2a84

**Comment by MarcusDenker** [comment]
PotentialOutDatedDependencyWarning have been fixed

**Comment by MarcusDenker** [comment]
https://github.com/pharo-project/pharo/pull/8279
