### ISSUE TITLE
What is the purpose of testObjectFormatInstSize?

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7652]
```
testObjectFormatInstSize
	| classes offending |
	"check that #instSize is in sync with #allInstVarNames"
	offending := SystemNavigation default allBehaviors reject: [ :cls | cls instSize = (cls allSlots reject: #isVirtual) size ].
	self assertCollection: offending hasSameElements: {}.

	"instSpec is only 0 for classes without any inst vars or variable fields"
	classes := SystemNavigation default allBehaviors select: [ :cls | cls isTrait not and: [ cls instSpec = 0 ] ].
	offending := classes reject: [ :each | each instVarNames isEmpty or: [ each isVariable not ] ].
	self assertCollection: offending hasSameElements: {}.
```

This test breaks with 

```
Object << #MockWithComplexSlot
	slots: { #aComplexSlot => PropertySlot };
	tag: 'Fluid';
	package: 'Kernel-Tests'
```

Yes I'm not stupid and I got that PropertySlot is a virtualSlot even it I do not understand why 
because there should be at least one instance named aComplexSlot.

**Comment by MarcusDenker** [comment]
I think the test is I think quite old and was checking that the instSize is in sync with the saved instVarNames (the instVarNames was originally just  additional information, there was the possibility to have that information be not correct, e.g. when creating classes yourself.

Maybe we should rewrite this test, it is not that useful anymore.

PropertySlot adds a hidden slot (where the properties are stored). all the PropertySlots themselves are virtual (they do not use space).
