### ISSUE TITLE
Removal of SystemReporter breaks smalltalkCI

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#7653]
**Describe the bug**
SystemReporter was removed from the system (https://github.com/pharo-project/pharo/pull/7637) but it is used by SmalltalkCI that is now unusable.
```bash
NewUndeclaredWarning: SmalltalkCIPharo>>imageInfo (SystemReporter is Undeclared)

NewUndeclaredWarning: SmalltalkCIPharo>>imageInfo (SystemReporter is Undeclared)

VariableNotDeclared: receiver of "new" is nil
```

**To Reproduce**
Run a build with Pharo 9 and Smalltalk CI

**Comment by Ducasse** [comment]
OK we should define a subclass of StSystemReporter called SystemReporter.

**Comment by Ducasse** [comment]
I will do it. 
Shit.

**Comment by Ducasse** [comment]
So it means that SmalltalkCI relies on a morphic tool :( and now it will rely on a Spec tool.
There is something wrong there.

**Comment by Ducasse** [comment]
Do you know where I can see the code of SmalltalkCI?

**Comment by Ducasse** [comment]
Ok SystemReporter was not a Morphic object (not inheriting from Morph) but it was relying on graphic list. 
Berk.

**Comment by Ducasse** [comment]
So it means that StSystemReporter should call a little object called SystemReporter but that &(^*&^ object should not rely on graphical objects!

**Comment by guillep** [comment]
@demarey is working on updating SmalltalkCI right now. Maybe the update should make it not depend on morphic?

**Comment by demarey** [comment]
Only one method is used: #reportImage 
It is only used to report information from the image.
Maybe #reportImage should be moved to Smalltalk class:
```smalltalk
reportImage: aStream
	self header: 'Image' on: aStream.
	aStream 
		nextPutAll: Smalltalk image imagePath; cr;
		nextPutAll: SystemVersion current version; cr;
		nextPutAll: Smalltalk image lastUpdateString; cr;
		nextPutAll: ChangeSet current name; cr
```
https://github.com/demarey/smalltalkCI/commit/677ec08dcf10284915fc758eb7cbe6dc9fb9588c#diff-16ca3b0248a2ef73d19cdcd2efb10e71c6db59e106ce2684ced23e1210b36958R3

**Comment by guillep** [comment]
Maybe that method can be inlined in smalltalk ci?

**Comment by demarey** [comment]
> Maybe that method can be inlined in smalltalk ci?

also. I do not know if it is used elsewhere

**Comment by Ducasse** [comment]
To me SmalltalkCI should not rely on user interface level classes.
So I would inline such call.

**Comment by Ducasse** [comment]
How do we contribute to SmalltalkCI?
Do we use the main one or do we have our own version?

**Comment by Ducasse** [comment]
first I will create a subclass of StSystemReporter.

**Comment by svenvc** [comment]
This is breaking all Pharo 9 builds for me as well

**Comment by demarey** [comment]
@Ducasse you can check #7659 
I split the business logic from the UI, keeping the old name for the logic.

**Comment by svenvc** [comment]
It is working again, thank you !
