### ISSUE TITLE
Epicea fileout should produce Pharo code and not ombu definition

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7655]
When we want to file out code we do not want to get ombu. 
I have no idea how I can reload ombu definitions BTW.

**Comment by tinchodias** [comment]
Hi, the ombu file that is created in the image directory can be opened by either :
- drag&drop from Finder
- File browser shows a button to open the log
afterwards you can select all, right click and "apply all".

I remember I had a importer from .st (or .changes) to epicea log, but don't remember if in the other way...


BTW: I'd like to receive some automatic notification when "epicea" or "ombu" or "fuel" appears in issues, but don't know how... do you?
