### ISSUE TITLE
Must be boolean deoptimization targeting wrong or: block

### ISSUE THREAD

**Issue by rko281** [guillep/pharo-core#7662]
Deoptimization of inlined blocks in response to `mustBeBoolean` is targeting the wrong block in certain circumstances.

**To Reproduce**
Add the following test method to MustBeBooleanTest

```
testMultipleOrsInMethod

	| values r1 r2 |

	values := OrderedCollection new.
	10 timesRepeat: [values add: MyBooleanObject new].

	r1 := values select: [  :each | each or: [ false ] ].
	self assert: r1 isEmpty.

	r2 := values select: [  :each | each or: [  true ] ].
	self assert: r2 size equals: 10
```

The test should pass (and does so in Pharo 8) but fails on the second assert - "Test Failure: Got 0 instead of 10".

Adding some instrumentation to the code illustrates the problem:

```
testMultipleOrsInMethod

	| values r1 r2 |

	values := OrderedCollection new.
	10 timesRepeat: [values add: MyBooleanObject new].

	r1 := values select: [  :each | each or: [ Transcript cr; show: 'block one'. false ] ].
	self assert: r1 isEmpty.

	r2 := values select: [  :each | each or: [ Transcript cr; show: 'block two'. true ] ].
	self assert: r2 size equals: 1.
```

The Transcript shows 20 lines of 'block one', illustrating that the first or: block is being evaluated during the second select:

Instrumenting the code programmatically can actually fix the problem, example:

```
testMultipleOrsInMethod

	| values r1 r2 hits |

	values := OrderedCollection new.
	10 timesRepeat: [values add: MyBooleanObject new].

	hits := OrderedCollection new.
	r1 := values select: [  :each | each or: [ hits add: 1. false ] ].
	self assert: r1 isEmpty.
	self assertCollection: hits asArray equals: #(1 1 1 1 1 1 1 1 1 1).

	hits := OrderedCollection new.
	r2 := values select: [  :each | each or: [ hits add: 2. true ] ].
	self assert: r2 size equals: 10.
	self assertCollection: hits asArray equals: #(2 2 2 2 2 2 2 2 2 2)
```

This version of the test code succeeds, I'm guessing due to a different form of block being created due to the reference to a method temporary(?). 

Changing the test code to use assignment (resulting in a full block?) causes the problem to reoccur:

```
testMultipleOrsInMethod

	| values r1 r2 hits |

	values := OrderedCollection new.
	10 timesRepeat: [values add: MyBooleanObject new].

	hits := #().
	r1 := values select: [  :each | each or: [ hits := hits, #(1). false ] ].
	self assert: r1 isEmpty.
	self assertCollection: hits equals: #(1 1 1 1 1 1 1 1 1 1).

	hits := #().
	r2 := values select: [  :each | each or: [ hits := hits, #(2). true ] ].
	self assert: r2 size equals: 10.
	self assertCollection: hits equals: #(2 2 2 2 2 2 2 2 2 2)
```

In this last case, when the test failure occurs the `hits` temporary can be seen to have been assigned 10 x 1s from the first or: block.

In all cases, the test succeeds with the "Full Block Closure" compiler option disabled. 

**Version information:**
 - MacOS 10.13.6 
 - Pharo-9.0.0+build.796.sha.31b556115e5944801de30876d72de9c660285ac7 (64 Bit)

**Comment by MarcusDenker** [comment]
Thanks for the tests! I will have a look

**Comment by MarcusDenker** [comment]
I understand what is happening: we store the generated de-optimized compiled method for the expression per pc. But we do that in the method as block methods can not have properties. This leads to wrong cache hits if the pc is the same, which happens if there are multiple blocks that are similar.

Solution I think is to make the cache two levels: method->indexed by block -> indexed by PC
