### ISSUE TITLE
Iceberg: Implement token authentication credentials

### ISSUE THREAD

**Issue by tinchodias** [guillep/pharo-core#7674]
Implement token authentication credentials for using Iceberg with GitHub repositories. AFAIR, not only GH but also Gitlab and BitBucket support this kind of authentication using a token.

[GitHub is deprecating password authentication](https://developer.github.com/changes/2/#--deprecating-password-authentication). The problem and solutions for Pharo 8 and 9 are described here:
https://github.com/pharo-vcs/iceberg/issues/1390

**Comment by guillep** [comment]
I think we need to update the Jenkins CI too, which is using password auth to get the repository's data to build.

**Comment by tinchodias** [comment]
Fixed by separate:
P8: https://github.com/pharo-project/pharo/pull/7732
P9: https://github.com/pharo-project/pharo/pull/7733
