### ISSUE TITLE
Iceberg Git Push Fails with a C++ Error

### ISSUE THREAD

**Issue by dupriezt** [guillep/pharo-core#7678]
**Describe the bug**
Pushing a git commit with iceberg on a Pharo 9 image on windows raises a C++ assertion failure.

**To Reproduce**
1. Create a new github repository
2. Create a new Pharo 9 image
3. Clone the repository in the image (HTTPS)
4. Click the "repair" button to create meta-data for the repo
5. Commit
6. Provide git with user.name and user.email
7. Push 
8. The following windows opens up
![2020-11-05_PharoBug_CannotPush](https://user-images.githubusercontent.com/32486709/98235749-8b582d80-1f62-11eb-8cad-8f98d21b1f9b.jpg)
The three options are "Abandon", "Retry" and "Ignore".
- "Retry" crashes the image

**Version information:**
 - OS: Windows 10
 - Version: Pharo 9.0.0 Build information: Pharo-9.0.0+build.817.sha.3f758fb9b0fc00deaffdcf26d2772e34f4ba6dbe (64 Bit)

**Additional context**
Pushing the same commit to the same github repository works on a Pharo 9 image from 3 days ago (2020-11-02)

**Comment by dupriezt** [comment]
@guillep I don't know if you're the right person to tag for this, but there's your name in the error :)
(The file containing the failed assertion is C:\...\guillep\...)

**Comment by artem-bochkarev** [comment]
@tesonep 
I still have this issue in version
Pharo-9.0.0+build.1141.sha.52858aa78ba53f37200510df2cfc3e386f80d341

**Comment by Ducasse** [comment]
Did you update the virtual machine?

**Comment by artem-bochkarev** [comment]
@Ducasse i tried to push repo with VM builds 1141 and 1145, both failing with the same c++ error.
8.0 version pushes repository without any troubles.
P.S. I didn't try SSH. It is only about HTTPS case.
