### ISSUE TITLE
"New trait" UI wizard cannot display the package name in 'apostrophe'

### ISSUE THREAD

**Issue by labordep** [guillep/pharo-core#7684]
**Describe the bug**
When I am using the wizard to create a new traits the package is not writed correctly, apostrophe are missing. When 'ok' an exception appear.

**To Reproduce**
1. Right clic on a class to display the contextual menu 
2. Click on 'New trait'
3. Enter your trait name in the wizard window
4. Click OK
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/49183340/98443864-8cc65900-210e-11eb-8233-3c2bd4ab2615.png)
![image](https://user-images.githubusercontent.com/49183340/98443890-a071bf80-210e-11eb-9bb8-b85da18eb84e.png)

**Version information:**
 - OS: Windows 10 Pro x64 version 2004 (19041.572)
- Pharo 9.0.0
- Build information: Pharo-9.0.0+build.821.sha.8b6e0282f26bf46f1d691a51ca34ab1e488623c6 (64 Bit)

Thanks.

**Comment by Ducasse** [comment]
Thanks I will check.

**Comment by Ducasse** [comment]
In the latest version I have 

```
Trait << #TMyTrait
	uses: {};
	slots: {};
	tag: '' ;
	package: 'Athens-Core-Tests'
```

**Comment by Ducasse** [comment]
Can you check if you use the latest version?
Tx

**Comment by labordep** [comment]
Hi Stephane,

I created a new image with the Pharo Launcher with "Official distributions" and "Pharo 9.0 - 64 bits development version, latest"

You can see in the issue the config information:

    OS: Windows 10 Pro x64 version 2004 (19041.572)
    Pharo 9.0.0
    Build information: Pharo-9.0.0+build.821.sha.8b6e0282f26bf46f1d691a51ca34ab1e488623c6 (64 Bit)

It's appear that is the last snapshot (in the pahro launcher) : Pharo9.0-SNAPSHOT.build.821.sha.8b6e028.arch.64bit.

Thanks.

**Comment by labordep** [comment]
I created a new image from scratch (same version) and I find a possible cause, I have a Tag with a space, "GPS Example".
I recreate with that example :
![image](https://user-images.githubusercontent.com/49183340/98448654-decaa700-212d-11eb-9050-6255b605fc23.png)

**Comment by Ducasse** [comment]
Bizarre car je n'arrive pas a le reproduire. 
Je vais reessayer.

**Comment by labordep** [comment]
Je viens de voir que pour "New class" ça fonctionne bien, c'est dans la fenêtre "New trait" que je n'ai pas les apostrophes.

**Comment by Ducasse** [comment]
Ok je vois que c'est avec la syntaxe courante et je testais avec la nouvelle.
Donc je vais proposer une correction.

**Comment by Ducasse** [comment]
Oops sorry in French
