### ISSUE TITLE
Debugger-Test result comparison deserves more space

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7693]
Right now it is tedious to see the comparison of the tests in the debugger. 
![Screenshot 2020-11-08 at 12 34 22](https://user-images.githubusercontent.com/432549/98463849-c0f95280-21be-11eb-8415-7ff658e3b2e6.png)

**Comment by Ducasse** [comment]
We have to all the time resize the pane.... at each rerun!!!
If at least the size would be kept once we place it.

**Comment by Ducasse** [comment]
![Screenshot 2020-11-08 at 12 30 54](https://user-images.githubusercontent.com/432549/98463865-dff7e480-21be-11eb-96d9-b7b1c4eb93f6.png)

**Comment by StevenCostiou** [comment]
This is complicated surprisingly: remembering how layout are changed for the next tool opening should not be an ad-hoc thing in the tool but supported at the framework level (i.e., spec). Which is not :'(

What I could do is lowering the space of the code pane and of the inspector in the case of a test failure, or adding the diff in a notebook tab which implies it's going to hide something (either the code or the bottom inspector).

The other possibility is to open a dedicated window with the diff and put that window on front.

**Comment by StevenCostiou** [comment]
@Ducasse This is my proposition, it will be integrated after next NewTools merge (I will see if we can do it soon).
This option to maximize the diff pane only appear when you have an assertion failure, and the setting is kept for next assertion failures (until you change it).
We will see how it feel with time.
https://user-images.githubusercontent.com/26929529/106790688-2fca3880-6654-11eb-827e-aa26e507023f.mp4



<blockquote></blockquote>

**Comment by StevenCostiou** [comment]
Fixed by https://github.com/pharo-project/pharo/pull/8501
