### ISSUE TITLE
Why Enlumineur is invoked when copying and paste code????

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7694]
In following method, when I select a piece of texte I get a DNU!
Why the formatter is invoked on copy and paste?

I select `s nextPutAll: 'uses:` in the following method and press copy and I get a DNU!
WHY?

```
expandedTraitDefinitionString
	
	^ String streamContents: [ :s |		
		| tag |
		s nextPutAll: 'Trait'.
		self msgAndClassNameOn: forClass name.
		
		s crtab.
		forClass hasTraitComposition
			ifTrue: [ self traitCompositionOn: s. ]
			ifFalse: [ s nextPutAll: 'uses: {};' ].
		self slotsOn: s.

		s 	
			nextPutAll: 'sharedVariables: ';
			nextPutAll: forClass classVariableDefinitionString;
			nextPutAll: ';'; crtab.
							
		s nextPutAll: 'sharedPools: {'.
		self sharedPoolsOn: s.
		s nextPutAll: '};' ; crtab.
						
		(forClass package classTagForClass: forClass) ifNotNil: [:t | 
							tag := t name.
							tag = forClass package name
								ifFalse:  [
									s nextPutAll: 'tag: '; 
					nextPut: $'; 
					nextPutAll: tag asString ; 
					nextPutAll: ''';'.
					s crtab
				]].
				
				s 
					nextPutAll: 'package: ''';
					nextPutAll: forClass package packageName;
					nextPutAll: '''' ]
```

**Comment by MarcusDenker** [comment]
RBEnglobingErrorNode>>#createValue calls the pretty printer.

This is called as in #copySelection we call getNestingCharacterFromAst: to do something clever when copying nested parenthesis.. 

I have the impression that we should not anything clever on copy, it's bit strange that the copied text is modified.

Maybe could instead do clever things on paste instead?

In addition, we should check if we need to pretty print in #createValue... that looks strange, too.
