### ISSUE TITLE
roundTo: 0.1 does not work on a SmallFloat64

### ISSUE THREAD

**Issue by labordep** [guillep/pharo-core#7695]
**Describe the bug**
The method roundTo: 0.1 return a not rounded point.

**To Reproduce**
Do It :

point := (0.26469029405372696@0.6497721609891263).
roundedPoint := point roundTo: 0.1.
roundedPoint inspect. "(0.30000000000000004@0.6000000000000001)"

float := 0.26469029405372696.
roundedFloat := float roundTo: 0.1.
roundedFloat inspect. "0.30000000000000004"

**Screenshots**
![image](https://user-images.githubusercontent.com/49183340/98469932-b0f36a00-21e2-11eb-8c73-d7b501f416fe.png)

**Version information:**
 - OS: Windows 10 Pro x64 version 20H2 (19042.572)
 - Pharo-9.0.0+build.822.sha.c9fef9e1343a4e3c16dd8d809edc9a530b955b0e (64 Bit)

Thanks.

**Comment by astares** [comment]
http://forum.world.st/Unexpected-behavior-of-roundTo-td3436887.html

<blockquote><div><strong><a href="http://forum.world.st/Unexpected-behavior-of-roundTo-td3436887.html">Pharo Smalltalk Developers - Unexpected behavior of roundTo:</a></strong></div><div>Unexpected behavior of roundTo:. 2.8011416510246336 roundTo: 0.01 returns 2.8000000000000003 Tested with 1.2 Should I fill a ticket, I don't see anythings similar? Hilaire --...</div></blockquote>

**Comment by labordep** [comment]
Ok thanks.
I conclude that "the real solution to these "problems" is to implement decimal floating point as per IEEE-754/2008" ?

**Comment by labordep** [comment]
I resolve my problem with that (find in the post) : 

`point := (0.26469029405372696@0.6497721609891263).`
`roundedPoint := point roundTo: 0.1.`
`text := (roundedPoint x printShowingDecimalPlaces: 2), '@', (roundedPoint y printShowingDecimalPlaces: 2).`
`text inspect. ` ==> 0.30@0.60

No problem for me to use a text because it is in fact for a UI display.
Thanks !
