### ISSUE TITLE
The Debugger stack view is missing package column

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#7699]
**Describe the bug**
The new debugger stack view is missing package column that was added this year in this commit to the GTDebugger:
https://github.com/pharo-project/pharo/commit/d854d60ee6c3500863d96f177ac81dbf41124d2e

**Comment by estebanlm** [comment]
sorry, but... why do we want package column in debugger?

**Comment by pavel-krivanek** [comment]
Because then you may see where the stack may not be important for you... See the typical usage of moldable debugger when you use debugger plugins to group/hide announcements processing logic. If you see the package in stack, you clearly see where the flow returned to your code you are interesting in.
