### ISSUE TITLE
Morph colour with alpha is inconsistent

### ISSUE THREAD

**Issue by riverdusty** [guillep/pharo-core#7702]
**Describe the bug**
When setting a morph colour (with alpha) the morph colour is different from the actual colour.

Morph new 
	color: ((Color red) alpha: 0.5);
	bounds: ((0@0) corner: (1000@1000))

![image](https://user-images.githubusercontent.com/572263/98517379-83f09700-2276-11eb-8d9f-4da607c72410.png)

**Comment by astares** [comment]
This is not a bug - it then is mixed with whatever is behind in background due to being more translucent.
So if you open it in an inspector it is mixed with the inspector background color. Thats why it looks different
than the full color without an alpha value.

Try 

```Smalltalk
Morph new
   color: ((Color red) alpha: 0.5);
   bounds: ((0@0) corner: (500@500));
    openInWorld
```

**Comment by riverdusty** [comment]
Thanks, I'll close this as a non-issue
