### ISSUE TITLE
Build 817 has broken parser

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#7703]
The Pharo 9 build 817 cannot compile this method from P3 package:
```smalltalk
printOn: stream
	stream nextPut: (self isOpen ifTrue: [ $[ ] ifFalse: [ $( ]).
	self printPointsOn: stream.
	stream nextPut: (self isOpen ifTrue: [ $] ] ifFalse: [ $) ])	
```

Related to this PR: https://github.com/pharo-project/pharo/pull/7660
@guillep

**Comment by pavel-krivanek** [comment]
this is broken:
```
RBParser parseExpression: '[ $] ]' 
```

**Comment by pavel-krivanek** [comment]
I guess it is related to this change:

![chrome_VY5moB6Nd0](https://user-images.githubusercontent.com/572494/98539473-ad1c2200-228c-11eb-9c8e-3a4db0872815.png)

**Comment by guillep** [comment]
Thanks for the issue @pavel-krivanek ! I'll take a look during the afternoon, and add a test for it too!
