### ISSUE TITLE
CI: Need to use access token for GitHub

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#7741]
**Describe the bug**
Github finally turned off the old API. 

The CI uses it, when triggering a build we now get:

Caused: org.kohsuke.github.GHFileNotFoundException: https://api.github.com/ {"message":"Bad credentials. The API can't be accessed using username/password authentication. Please create a personal access token to access this endpoint: http://github.com/settings/tokens","documentation_url":"https://docs.github.com/articles/creating-a-personal-access-token-for-the-command-line"}

**Comment by guillep** [comment]
I have updated the CI to use auth tokens.
I'll close it for now, if this persists, please reopen.
