### ISSUE TITLE
Broken class definitions combining traits and slots

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#7756]
**Describe the bug**
It is not possible to accept class definitions that combine traits and slots

**To Reproduce**
1. Install this trait:
```smalltalk
Trait named: #TAPartPresenter
	 uses: {}
	 slots: { #aspectSymbol . #id . #builder . #ignoreUpdates . #model . #enablementHelp . #storedHelp }
	 package: 'APart Pharo'
``` 
2. try to create this class:
```smalltalk
SpAbstractWidgetPresenter << #APartStatusBarPresenter
	uses: { TAPartPresenter };
	slots: { #message => SpObservableSlot };
	package: 'APart Pharo'
```
It is silently ignored.

**Version information:**
 - Version: Pharo 9.0.0
Build information: Pharo-9.0.0+build.847.sha.c4346ad4c0fb762dbe689e6d06945c939019c032 (64 Bit)

**Comment by MarcusDenker** [comment]
This is working now for me

**Comment by pavel-krivanek** [comment]
to reproduce this issue, the fluid class definition must not be enabled in the image

**Comment by Ducasse** [comment]
I will check I thought that I fixed it. Now I did not try not using fluid. 
I cannot do magic :) yet. 
Now I cannot understand calypso code and I cannot fix calypso. 
I'm sorry but this is my limit. 
So may be it will stay like this.

**Comment by pavel-krivanek** [comment]
are fluid definitions ready to be set as default?

**Comment by Ducasse** [comment]
Not totally. 
We fixed a lot of rougth edges but changeSorter and other a still hardcoding and manipulating strings.
Now I always wanted to modify Calypso so that it is able to guess that we are editing a method or a class but I got always discouraged and right now I have barely no time for Pharo :(

**Comment by Ducasse** [comment]
I found a trick. I scan the class definition source and set the fluid class parser on. 
And this solves the issue.

**Comment by Ducasse** [comment]
```
	| oldClass class newClassName defTokens keywdIx classCompiler |
 	"for now make it work!"
 	('*<<*' match: aString)
 		ifTrue: [ ClassDefinitionPrinter showFluidClassDefinition: true ].
```
