### ISSUE TITLE
Browser DNU when using "+ Inst Method" tabs

### ISSUE THREAD

**Issue by darth-cheney** [guillep/pharo-core#7787]
**Describe the bug**
When interacting with the Browser's "+ Inst methods" tab, you can get it to a state where there are multiple tabs and where editing and saving a new method in one of them throws a DNU.

**To Reproduce**
1. Open a browser and create a new class, save it
2. Click the "+ Inst side method" tab
3. Write a new method, do Ctrl+s to save it. You will then see __two other tabs__ called "+ Inst side method" appear (see screenshot)
4. Attempt to write a new method in the __right-most__ of those new tabs, and also save with Ctrl+s. You'll get the DNU

**Expected behavior**
What we'd normally expect is to be able to just save a method in the tab without error.

**Screenshots**
![MyClass first](https://user-images.githubusercontent.com/1640299/99824361-9f378e00-2b23-11eb-8d66-60a35629551b.png)
  
![browser-dnu](https://user-images.githubusercontent.com/1640299/99824373-a2cb1500-2b23-11eb-8f4d-59455eac8375.png)

**Version information:**
 - OS: Pop_os 20.04 (Ubuntu, basically)
 - Version: Pharo9.0 64

**Comment by estebanlm** [comment]
I sneaked a fix for this in my current merge of Spec2 / NewTools. 
I am sorry for not being cleaner :(
