### ISSUE TITLE
ClassDescription contains dead code related to slots printing. 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7820]
Now that classDefinitionPrinter was introduced we can clean classDescription and children. 
For example 
- classVariablesDottedString, classVariablesDottedOn: are unused.

**Comment by astares** [comment]
why not deprecate?

**Comment by Ducasse** [comment]
Because this is internal. Tools and users should use definition (and definitionWithoutSlots and definitionWithSlots are INTERNAL). 
If people use internal methods then this is their fault. Else we will have such methods for about 2 years and I will not jump over them during two more years.

**Comment by Ducasse** [comment]
And dottedStrings are internal too probably only used in P9. deprecation should be used with care.

**Comment by Ducasse** [comment]
issue #7826 should also be resolved but I will merged this one as soon as the bar is green.
