### ISSUE TITLE
Broken Changelist tool when opened from FileList

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#7825]
Scenario
- open file list
- select the file "Pharo.changes"
- click on "Changes"

 
![image](https://user-images.githubusercontent.com/5980033/99917883-8f7e9c00-2d13-11eb-8702-1fea1c1dd7ea.png)

![image](https://user-images.githubusercontent.com/5980033/99917898-aa511080-2d13-11eb-8d38-575936fe8e6c.png)

**Comment by MarcusDenker** [comment]
fixed by https://github.com/pharo-project/pharo/pull/8480
