### ISSUE TITLE
Ring: remove definitionWithSlots

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7826]
HI marcus

I do not really understand the logic of 

```
checkClassRebuild
	"break the recursion while rebuilding"
	classIsRebuild ifTrue: [ ^ self].
	(self definingClass environment hasClassNamed: self slotClassName) ifFalse: [ ^ self ].
	classIsRebuild := true.
	"we rebuild the class, this triggers instance migration"
	self definingClass compiler evaluate: self definingClass definitionWithSlots.
	"recompile all methods that access me to generat code for the loaded definition"
	self usingMethods do: [:each | each recompile].
```

Why we could ask the class?.
To me this is strange to really on a textual representation to recreate the class.

**Comment by MarcusDenker** [comment]
It should be possible to remove the #definitionWithSlots and replace it with just #definition: the idea is that we re-compile the class definition to update the class.

When I do that change, it does not work (test fails). This seems to be the same problem as we saw with running the Epicea tests with fluid definitions enabled: something is not correct when re-evaluating class definitions to update a class.

**Comment by MarcusDenker** [comment]
This is now just in Ring (one user, implementation)
