### ISSUE TITLE
Breakpoints cannot be set clicking on the side of a method

### ISSUE THREAD

**Issue by QDucasse** [guillep/pharo-core#7832]
Breakpoints cannot be set by simply clicking on the side panel of a method body. 
Pharo 8 allows the following:
![breakpoint_p8](https://user-images.githubusercontent.com/32014573/99960949-e7f27f80-2d8d-11eb-9107-3579edd26ccc.gif)

Pharo 9 makes the breakpoint blink then disappear on certain lines:
![breakpoint_p9](https://user-images.githubusercontent.com/32014573/99961014-fc367c80-2d8d-11eb-82a0-f6831f43b0f7.gif)

OS: Ubuntu 20.04

**Comment by pavel-krivanek** [comment]
in P9, you sometimes need to press the LMB for breakpoint installation for longer time

**Comment by MarcusDenker** [comment]
I think this is fixed in Pharo10 (at least I never saw it). 

(I close this, but please re-open if needed)
