### ISSUE TITLE
cleanup hasPropertyNamed:

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#7840]
**Describe the problem**

all classes implementing a property api use #hasProperty: for checking. But there is one that uses hasPropertyNamed:
instead.

**Classes involved**
RGObject and the test

**Proposal**
Deprecate hasPropertyNamed: with a rewriting deprecation. Implement #hasProperty and change the test.

**Comment by carolahp** [comment]
I'm working on it
