### ISSUE TITLE
0 . 1 using finder example freezes the system 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7860]
**Describe the bug**

0 . 1 using finder example freezes the system

**Comment by MarcusDenker** [comment]
If do cmd-dot quickly, I am in #tinyBenchmarks.

But the idea to just call all methods is a bit strange... who guarantees that there are no bad side effects?

**Comment by Ducasse** [comment]
I fixed it in the other PR and I blacklisted tinyBenchmarks as well as benchFib and fixed others little glitches

**Comment by Ducasse** [comment]
So I close this issue.
