### ISSUE TITLE
Dropping a source file with a class does not create the class.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7877]
So it means that the class method are not installed in the system

**Comment by Ducasse** [comment]
[Funky2.st.zip](https://github.com/pharo-project/pharo/files/5607364/Funky2.st.zip)

**Comment by MarcusDenker** [comment]
Works here... I tried both with fluid class def enabled and not, and both times the class is created.

There are no class side methods in the .st file
