### ISSUE TITLE
Exception : Instance of StrikeFont did not understand #realFont

### ISSUE THREAD

**Issue by labordep** [guillep/pharo-core#7899]
**Describe the bug**
The exception appears when I try to select a class in the Pharo Browser and I leave my mouse cursor on the name of the class to wait for the display of the tooltip (probably).
For information, I'm trying to find the font "Bitmap DejaVu Sans" in my system (Windows) but without success... (in the font repository) may be it's normal, I don't know if Pharo have embedded Fonts.
![PharoExceptionFont](https://user-images.githubusercontent.com/49183340/100527156-ee3e8c80-31cf-11eb-824e-6de304b131e4.gif)

**To Reproduce**
Hard to explain, I send to you an animated Gif.

**Screenshots**
The error :
![image](https://user-images.githubusercontent.com/49183340/100527005-96535600-31ce-11eb-9cb2-f8864e167786.png)

My Settings Fonts Configuration :
![image](https://user-images.githubusercontent.com/49183340/100527017-c26ed700-31ce-11eb-942a-a46878c1a9ac.png)

**Version information:**
 - OS: Windows 10 Pro 20H2 (19042.630)
 - Pharo : Pharo-9.0.0+build.904.sha.c34688efb968a8145fa44a655780f44c872b248b (64 Bit)

Thanks !

**Comment by labordep** [comment]
Probably linked with #8525.
This is strange because it's in a new image, some configuration persists between image repositories ?

**Comment by Ducasse** [comment]
Pierre do you still have this problem with the latest VM and latest image?

**Comment by labordep** [comment]
Thanks Stephane. I update the VM. I was in 2020/06 version updated to 2021-02-16. When I create a new image I always have the same problem with a new message on opening (see my screenshots).

![image](https://user-images.githubusercontent.com/49183340/108121218-bb0aeb80-70a2-11eb-9aca-e785a8d14301.png)
![image](https://user-images.githubusercontent.com/49183340/108121250-c827da80-70a2-11eb-9d96-c86f48167ee1.png)
![image](https://user-images.githubusercontent.com/49183340/108121300-dc6bd780-70a2-11eb-8ddc-959d75c33567.png)

**Comment by Ducasse** [comment]
I will ask @tesonep Pablo because may be the VM is not publicly available.

**Comment by MarcusDenker** [comment]
Would the solution not be to remove the send to #realFont and use isTTCFont directly> 

```
privateFontName
	^ font realFont isTTCFont
		ifTrue: [ font familyName ] 
		ifFalse: [ self class familyFontName ]
```

#realFont ist just implemented on LogicalFont, while isTTCFont is implemented on StrikeFont, too.

**Comment by MarcusDenker** [comment]
I opened https://github.com/ObjectProfile/Roassal3/issues/490

**Comment by labordep** [comment]
Thanks @MarcusDenker :)

**Comment by MarcusDenker** [comment]
Fix is merged in Roassal repo, will be in Pharo when Roassal is updated next

**Comment by MarcusDenker** [comment]
fixed by merging https://github.com/pharo-project/pharo/pull/12430
