### ISSUE TITLE
How can we get back halos?

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7920]
I cannot close red window of death... I cannot get the halos. 

I can get a menu using Cmd+Control+ shot click so. and there there is a delete menu

**Comment by MarcusDenker** [comment]
I think this is because the CTRL click is not recognised as the second mouse click anymore.

https://github.com/pharo-project/pharo/issues/7895

Maybe this one is related, too: https://github.com/pharo-project/pharo/issues/7900

**Comment by Alisu** [comment]
The hypothesis of Marcus is right.
Now try with option-shift-click and you will have the halo. (option = alt)
With control-shift-click you will have the menu not the halo.
Something have change for mac only if it was with command instead of control.

**Comment by MarcusDenker** [comment]
For halos via alt-shift-click: in OSSDL2BackendWindow>>#convertButtonState:modState:modifiers:, remove the special code makes it work for me:

```
    "The ALT-GR is used to enter special characters, so it should be handled as a keypress.
    In OSX, both alt keys are used to enter special characters. 
    This is hack because we need to handle the TextInput event and do not enter text in the 
    keypress / keydown events."
    "OSPlatform current isMacOSX " false
        ifTrue: [ (alt or: ralt) ifTrue: [ ^ self ] ]
        ifFalse: [ ralt ifTrue: [ ^ self ] ].

```

**Comment by guillep** [comment]
Yes, that is right. We have been working on it. The problem with removing that line is that it breaks non english keyboards (https://github.com/pharo-project/pharo/pull/7673).

We are working on a solution that restores the halos while maintaining the correct behaviour of keyboard events and text input.
