### ISSUE TITLE
Broken traits definitions

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#7923]
Traits in build 911 (and some earlier) have broken traits definitions. The definition uses unknown message and has wrong formatting.

![Pharo_e56Em7zRR6](https://user-images.githubusercontent.com/572494/100709088-c4db5780-33ad-11eb-9b11-976387df0824.png)

See `SpTAlignable` for another example present in the standard Pharo image.

**Comment by pavel-krivanek** [comment]
The method `OldPharoClassDefinitionPrinter>>#traitCompositionOn:` checks if the trait definition should use `uses:` part by checking if the trait uses another traits. Originally, the trait definition with slots always used the `uses:` part.

**Comment by MarcusDenker** [comment]
now it raises an error instead:

  self error:
				  'Invalid Printer for stateful traits. Please detect and use a more modern printer'

**Comment by Ducasse** [comment]
Yes because slots were not official in Pharo 80. 
Slots are only possible with the fluid class definition. 
I will check the problem, thanks for the example.

Now what can I do? Because to be slots should not be displayed
So I should get 

```
Trait named: #SpTAlignable
    instanceVariableNames: 'vAlign hAlign'
```

I have no idea why the old definition was touched to pay attention to slots. 
We should not this kind. Else everything will be terrible mess. 

Now I have no idea what is `forClass classLayout visibleSlots`

So I will just produces an instanceVariableNames: 
and old defnition

I do not even understand why oldDefinition is used by the browser.

**Comment by Ducasse** [comment]
I do not get it....
![Screenshot 2020-12-08 at 21 28 51](https://user-images.githubusercontent.com/432549/101537823-6c531e00-399c-11eb-9733-3aa58026b14d.png)

**Comment by Ducasse** [comment]
In Pharo so we cannot have instance variables because it did not exist in trait.

**Comment by Ducasse** [comment]
We really did a mess with the changes in class definition.
We should have done before what I'm doing with fluid because it is becoming an epic mess.

**Comment by Ducasse** [comment]
So I will introduce the corresponding method to slots and deprecated the slot based ones. Because we should use the fluid one for (complex) slots.

**Comment by Ducasse** [comment]
Ok back to it.

**Comment by Ducasse** [comment]
Pavel I have tests in T2CommonClassDefinitionPrinterTest and I'm trying to understand what is the problem. 
Is it not the same as the problem with SpTAlignable?

**Comment by Ducasse** [comment]
How did you produce this because when I browse `TMockWithComplexSlot` I get 

```
Trait << #TMockWithComplexSlot
	slots: { #aComplexSlot => ObservableSlot };
	package: 'TraitsV2-Tests'
```

which is correct.

**Comment by Ducasse** [comment]
OK I see that this is related to SpTAlignable and that I do not have a test with a complex slot in the old definition.

**Comment by Ducasse** [comment]
The problem is that from calypso if I select the class and asked its definition without fluid it returns me a fluid version which is correct.

**Comment by Ducasse** [comment]
I have hard time to reproduce it. It looks like if I type SpTAlignable and press browse I get it. But only I press the fluid button before. If I unselect the fluid button after displaying it is working correctly.

**Comment by Ducasse** [comment]
And I do not get because this test passes

```
T2OldPharoClassDefinitionPrinterTest >> testClassDefinitionWithComplexSlotShouldBeDisplayedAsFluid

	ClassDefinitionPrinter showFluidClassDefinition: false.
	self assert: TMockWithComplexSlot needsSlotClassDefinition.

	self 
		assert: (self forClass: TMockWithComplexSlot) 
		equals: 'Trait << #TMockWithComplexSlot
	slots: { #aComplexSlot => ObservableSlot };
	package: ''TraitsV2-Tests''' 
```

**Comment by Ducasse** [comment]
In fact this test is not equivalent because the trait uses complex slots.
Now what I found is that SpTAlignable needsSlotClassDefinition is false. 
So I start to get it.

**Comment by pavel-krivanek** [comment]
great :-)

**Comment by Ducasse** [comment]
Pavel can you have a look at my PR. Now I would prefer that you use fluid 👍
