### ISSUE TITLE
Enhance CodeImporter with better comment

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#7924]
**Describe the request**

We should enhance `CodeImporter` class comment with something like this:

> CodeImporter reads chunk format. The chunk format is a code format where elements are delimited by exclamation marks. An element is preceded by some kind of annotation that says what kind of element it is / how it should be read.
For example, the annotation CodeImportTestCaseTestClass #methodsFor: 'some protocol' #stamp: 'GuillermoPolito 5/2/2012 13:35 says that the thing that follows is a method for the class CodeImportTestCaseTestClass, its protocol, and some other metadata like the last modification stamp.
> A chunk can then contain a method, a class comment, a "package organization" which is like a package definition, or an arbitrary "doIt" expression. The definition of classes are integrated within arbitrary expressions.

**Comment by Bajger** [comment]
I made pull request directly from GitHub (for some reason, Iceberg keeps me asking my credentials), so I don't know if PR is correctly linked to the issue.

**Comment by guillep** [comment]
> so I don't know if PR is correctly linked to the issue.

Yes, the PR was correctly linked.

> I made pull request directly from GitHub (for some reason, Iceberg keeps me asking my credentials), 

Iceberg is in a phase of UI redesign, the Github integration will see some love later probably. Sorry for the noise
