### ISSUE TITLE
Refactoring - Some refactorings not work

### ISSUE THREAD

**Issue by Lin777** [guillep/pharo-core#7949]
The refactorings that don't work are: 
 - RBRealizeClassRefactoring
 - RBSwapMethodRefactoring
 - RBCreateCascadeRefactoring

None of these classes have tests, however when trying to test these refactorings, they never finish and the only way to finish their execution is by stopping the process.

@Ducasse

**Comment by Ducasse** [comment]
Evelyn I would split this issue in three one for each refactorings.

**Comment by Lin777** [comment]
@Ducasse  yes, I'll split this issue in 3 by the moment, then maybe we split those issues in more.
