### ISSUE TITLE
ASTCache can cause huge leaks

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#7955]
**Describe the bug**
ASTCache can keep instances that may survive memory cleanups

**To Reproduce**
1. in Playground, evaluate `RGEnvironment new halt.`, this will open a debugger and cause leaking `StPharoApplication`. Close the debugger.
2. in the same Playground, evaluate: `RGEnvironment someInstance.`
3. reset StPharoApplication: `StPharoApplication classVarNamed: #Current put: nil.` (in the same Playground). This should remove the momory leak with exception of the Playground that is still keeping reference to its old application.
4. Close this Playground
5. Open a new Playground and do GC: `Smalltalk garbageCollect`
6. Evaluate `ReferenceFinder findPathTo: RGEnvironment someInstance.` 

This will show that the old instances are still kept because AST cache record for DoIt `ReferenceFinder findPathTo: RGEnvironment someInstance` keeps compilation context that points to the old playground (that points to the old application that holds the old debugger that holds the old RGEnvironment instance)

![Pharo_rlO4wEyMJi](https://user-images.githubusercontent.com/572494/100995289-de200780-3557-11eb-96bb-c1b8aba431fa.png)

All code:
```smalltalk
"in the first Playground:"
RGEnvironment new halt.
RGEnvironment someInstance.
StPharoApplication classVarNamed: #Current put: nil.

"in the second Playground after closing of the first one"
Smalltalk garbageCollect.
ReferenceFinder findPathTo: RGEnvironment someInstance.
```

**Comment by pavel-krivanek** [comment]
One big problem here is that there is a new cache record for every DoIt

![Pharo_d8ycq9IfX6](https://user-images.githubusercontent.com/572494/100996557-7a96d980-3559-11eb-8540-2a50b49a0316.png)

**Comment by pavel-krivanek** [comment]
To prove it:
```smalltalk
"print it line by line:"
ASTCache reset.
1+1.

"inspect it:"
ASTCache default.
```
![Pharo_YMpWEFQvXX](https://user-images.githubusercontent.com/572494/100996872-e416e800-3559-11eb-9e9c-b78b6decc307.png)

**Comment by MarcusDenker** [comment]
I will have a look

**Comment by MarcusDenker** [comment]
so we found:
- the entries with nil keys should be removed but are not (or very very slowly). There might be some problem there.
- the AST of the doit holds on to the Requestor. We should change it to hold on to the bindings shared with the requestor instead

As a workaround, I will for now not put the DoIt in the cache (then it will be like it was in Pharo8 from that aspect).

**Comment by dionisiydk** [comment]
Hi @MarcusDenker .

It is maybe a time to get rid of this cache. The AST can be a simple property of a method. Method gone -> ast gone. 
Do you see any issues with such approach?

**Comment by MarcusDenker** [comment]
For the DoIt that seems like a good idea: I did a version now where instead of caching, we add the AST as a method property (just to DoIts). Then the AST cache checks that first.

We can sadly not do that for all methods as then they would be saved and the AST for the whole Pharo9 image is ~800MB...

**Comment by dionisiydk** [comment]
> We can sadly not do that for all methods as then they would be saved and the AST for the whole Pharo9 image is ~800MB...

Hm, that is interesting. Do you know what makes it different than keeping asts in global cache?

**Comment by guillep** [comment]
Another solution is to not cache ASTs at all. Users/apps that need caching
could implement their own.
