### ISSUE TITLE
Modify heading Describe the bug , Describe the request

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#7957]
The issue report content template uses first heading as 

**Describe the bug**
or
**Describe the request**

It looks strange if the reporter does not modify it, keeps the heading there and writes the issue description. I propose to change the names to "Bug description" and "Request description". Please, chech the rest of templates as well.

**Comment by Ducasse** [comment]
Hi pavel

Sorry but I could not understand what you want.

S.

**Comment by pavel-krivanek** [comment]
When you start a bug report, you will get this template:

![chrome_egqNxJiZJD](https://user-images.githubusercontent.com/572494/101596022-a5b77800-39f4-11eb-80a1-5c68260f1e68.png)

If you do not touch the heading, it will still say "Describe the bug" which is strange in the finished bug report. "Bug description" would be better. There is a similar pattern for the other issue reports like feature requests
