### ISSUE TITLE
New SystemReporter crashes on Windows

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#7963]
Take latest Pharo 9 and open System reporter on Windows

![image](https://user-images.githubusercontent.com/5980033/101069775-bb631280-359a-11eb-80ac-66de86e60feb.png)

**Comment by astares** [comment]
Old system reporter reported it like this:

![image](https://user-images.githubusercontent.com/5980033/101184699-4e5e8400-3651-11eb-9f81-9cd1132301fc.png)

**Comment by Ducasse** [comment]
I do not get why it is crashing because the same bad code was copied from the old system reporter. 
BTW I do not have a windows machine to reproduce it. So if you can send us a fix it will help.

**Comment by Ducasse** [comment]
I tried it on latest image on mac.

**Comment by astares** [comment]
It only happens on Windows - looks like the code was copied from old System reporter without testing on the various platforms.

The screenshot shows what was called on Windows (#reportOS) - the code with the primitive 10002 did not even work before (and seems to have never been called before)
