### ISSUE TITLE
Check defineClass: to see how we can avoid passing a string but passing a classBuilder configured object

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7964]

**Comment by Ducasse** [comment]
@evelyn I assigned it to you but this is not urgent. This is just that we do not forget.

**Comment by evelyn** [comment]
> @evelyn I assigned it to you but this is not urgent. This is just that we do not forget.

While I appreciate the thought, I don't think I'm quite the right person you're looking for.

**Comment by guillep** [comment]
Ahah, sorry, that should have been @Lin777 !

**Comment by Ducasse** [comment]
We did it with cyril
