### ISSUE TITLE
File class >> openAndTruncateForWriteFileNamed: is a clunky name

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7974]
I'm sure that we can do better.

**Comment by noha** [comment]
I hope, too. truncate and forWrite is redundant. You cannot truncate a file you cannot write. And I'm not sure we need the libc naming in smalltalk. So a

#writableFileNamed: 

is intention revealing enough. As truncating implies writing 

#truncatedFileNamed: 

would be feasible.
