### ISSUE TITLE
Class definition should not be evaluated if it contains a syntax error

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#7987]
**Describe the bug**
The accepting of the class definition with broken syntax tries to evaluate the definition which causes a confusing DNU

**To Reproduce**
1. Go to to some class in Calypso, e.g. `RBPragmaNode`
2. remove the closing quotes from the end of instance variables definition so the definition now looks like: 
```
RBProgramNode subclass: #RBPragmaNode
	instanceVariableNames: 'selector keywordsPositions arguments left right
	classVariableNames: ''
	package: 'AST-Core-Nodes'
```
3. The syntax highlighting will complain
4. Accept it
5. DNU: ```PrimitiveFailed: primitive #withArgs:executeMethod: in UndefinedObject failed```

**Comment by Ducasse** [comment]
Thanks I will have a look. Now I have the impression that it was already like that in P8.0.
I will check.

**Comment by Ducasse** [comment]
But it will take some times because I'm super busy.
