### ISSUE TITLE
TestSkip should be TestSkipped

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#7996]
the name is misleading
- its not a test that it should start with "Test..."
- It is an exception that is signaled 

```Smalltalk
SkippingTest signal 
```

would be better

**Comment by Ducasse** [comment]
May be we should rename it SkippingTextException because SkippingTest looking like a testcase.

**Comment by gcotelli** [comment]
Why not TestSkipped ?

**Comment by svenvc** [comment]
> Why not TestSkipped ?
> […](#)

Yes.

**Comment by astares** [comment]
I changed the PR to follow the majority and use TestSkipped
