### ISSUE TITLE
Rule required for shadowed variables

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#8009]
In the CI output log for PRs on Pharo 9 issues I see the following warnings on Roassal classes:

SystemNotification: RSCanvas>>numberOfEdges(edges is shadowed)
SystemNotification: RSCanvas>>numberOfEdges(edges is shadowed)
SystemNotification: RSCanvas>>numberOfNodes(nodes is shadowed)
SystemNotification: RSCanvas>>numberOfNodes(nodes is shadowed)
SystemNotification: RSComposite>>numberOfEdges(edges is shadowed)
SystemNotification: RSComposite>>numberOfEdges(edges is shadowed)
SystemNotification: RSComposite>>numberOfNodes(nodes is shadowed)
SystemNotification: RSComposite>>numberOfNodes(nodes is shadowed)
SystemNotification: RSShape>>printOn:(model is shadowed)
SystemNotification: RSShape>>printOn:(model is shadowed)

which means we have local variables (or block variable) in a method with the same name as an existing ivar in the class.

These cases should be cleaned in Rossal3 for the Pharo 9 image - for that I opened https://github.com/ObjectProfile/Roassal3/issues/321 on Roassal3 issue tracker.

But it would be good if we could have a Lint rule that shows that problem so one can avoid it:

**Side note:** Yes - there already is a rule called ReTempVarOverridesInstVarRuleTest - but this is only for temps
                  and does not cover variables in blocks like in

```Smalltalk
numberOfEdges
	"Return the number of edges contained in the container"
	^ self privateEdges
		ifNil: [ 0 ]
		ifNotNil: [ :edges | edges size ]
```
when "edges" is already an instance variable

**Comment by bencoman** [comment]
Further, it would be better to have the QA text to say "shadowed" rather existing "overriden" shown here...
![image](https://user-images.githubusercontent.com/1713447/103216159-58258f80-4950-11eb-9ede-1263c947753a.png)

methods "overridden" ==> okay 
variables "shadowed" ==> bad

**Comment by Ducasse** [comment]
Good idea.

**Comment by astares** [comment]
Roassal issues have been cleaned today: https://github.com/ObjectProfile/Roassal3/issues/321#issuecomment-780036358

**Comment by akevalion** [comment]
Hi @MarcusDenker, this issue has already been corrected.

**Comment by MarcusDenker** [comment]
Yes, but we need to add a Code Critique rule *and* a release test
