### ISSUE TITLE
Small cleanup in BaselineOfEnlumineurFormatter and BaselineOfMicrodown

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#8016]
- small cleanup in these two baseline packages: tag the uncategorized baseline packages with tag "Base" 
  (as they have a manifest in that package which is tagged they are uncategorized)

**Comment by Ducasse** [comment]
No baselines for two classes should not have tag.

**Comment by astares** [comment]
@Ducasse please do not be so quick in your decisions. You might think it is not worth to spend a tag here and therefore closed the issue. In my opinion too quickly. 

PLEASE:
This is not dependent on the number of classes - we should stay consistent otherwise cleaning makes no sense at all. 

**To explain in detail:** there is a manifest in these two packages which is always in Tag 'Manifest' (like in any other package) leaving the baseline class uncategorized. This fixes the uncategorized baseline classes it even when it might not be obvious in the first place. 

![image](https://user-images.githubusercontent.com/5980033/101748043-55134e00-3acc-11eb-89ed-1247053c69fe.png)

Look at other places where we have this accepted and cleaned already - for instance "BaselineOfAthens" (similar issue, also with two tags only):

![image](https://user-images.githubusercontent.com/5980033/101748183-84c25600-3acc-11eb-8b98-90c206edd5ab.png)

This cleanup also helps to prepare adding a Release test that no package has uncategorized classes. This is important not only to clean and get better quality but also to assure that quality level with tests afterwards.

So please try to understand my POV - we should provide a consistent image so people find their way easily and not being surprised that it is done differently all the time. This is how we should work: to act more professionally and give Pharo packages and the overall image a consistent feel. We should not decide case by case whatever we like most depending on mood or personal preference.

Please reopen the issue and check the PR again. Thanks in advance!

**Comment by astares** [comment]
@Ducasse Are you able to check again my comment?
