### ISSUE TITLE
Rename all polymorphic methods #definition to #definitionString

### ISSUE THREAD

**Issue by olekscode** [guillep/pharo-core#8026]
`ClassDescription >> definition` was renamed to `definitionString` and deprecated.

```Smalltalk
ClassDescription >> definition
	"Answer a String that defines the receiver."
	self
		deprecated: #definition
		transformWith: '`@receiver definition' -> '`@receiver definitionString'.
	^ self definitionString
```

`CompiledCode >> definition` that is supposed to be polymorphic should also be renamed and deprecated.

```Smalltalk
CompiledCode >> definition
	"Polymorphic to class definition"
	
	^ self sourceCode
```

Also, we need to check for other polymorphic methods.

**Comment by astares** [comment]
@olekscode 
Be aware of https://github.com/pharo-project/pharo/issues/8023 and https://github.com/pharo-project/pharo/issues/8020

**Comment by olekscode** [comment]
Actually, the deprecation has a transformation rule.
So all senders can be automatically rewritten by running the tests.

**Comment by astares** [comment]
I just faced two of them (when running tests for other PRs) and fixed them.

**Comment by MarcusDenker** [comment]
I think due the automatic rewrite, and the changes people did, we can close this
