### ISSUE TITLE
We lost the possibility to debug a red square of death

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8038]
In Pharo 80 we could get the stack and in P90 we are blind.

**Comment by StevenCostiou** [comment]
Stéphane, if I do ctrl+click on a red square of death, I get a menu with at the bottom the debug it action, and it opens a debugger.

Could you try it? 

I think it might only be a change in the shortcut to get that menu?

**Comment by MarcusDenker** [comment]
It works for me

**Comment by guillep** [comment]
With the fix for the halos we are working on for #7920 this is not an issue anymore
