### ISSUE TITLE
Typo in method name Path class >> #delimeter

### ISSUE THREAD

**Issue by jvalteren** [guillep/pharo-core#8047]
**Describe the problem**
Path class >> #delimeter is spelled incorrectly.

**Classes involved**
Path

**Proposal**
Small refactoring with deprecate transform.

**Version information:**
 - Pharo 9.0, 8.0, 7.0... earlier?

**Expected development cost**
Zero, I will provide fix.

**Additional context**
Pull request incoming...

**Comment by MarcusDenker** [comment]
was merged
