### ISSUE TITLE
RGClassStrategy is the last caller of definitionWithSlots

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8055]
So we should clean it probably call ClassDefinitionPrinter fluid for:....

**Comment by MarcusDenker** [comment]
This is just used internally to Ring2... and I wonder how much sense it makes to manually update Ring2 all the time... it diverged a lot from the meta model (e.g. the method calling it is called #defintion, this is already deprecated on ClassDescription.

I tried to copy over the code, but this is far from easy as the models are just so different.
