### ISSUE TITLE
RB - Remove Method Refactoring Commmand doesn't use Refactoring class

### ISSUE THREAD

**Issue by Lin777** [guillep/pharo-core#8068]
This command use a strategy class (SycSilentlyRemoveMethodStrategy) to remove method, and this causes that undo refactoring not work well in remove method. 

Could I change so that this command uses the refactoring class or is it important that it use this strategy for some reason?

**Comment by Ducasse** [comment]
We fixed this. Now a driver is calling the RBRemoveMethodRefactoring. So I close the issue.
