### ISSUE TITLE
glitch in package template

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8073]
Create an empty package and click on its comment!

![Screenshot 2020-12-13 at 12 03 34](https://user-images.githubusercontent.com/432549/102009969-526a6000-3d3b-11eb-97ff-fe226b13a6b1.png)

**Comment by Ducasse** [comment]
Apparently creating a random problem. 
This is creating a package with the same name than a class.

**Comment by astares** [comment]
How do you get this? In recent Pharo 9 when I create a new package I get this as a package comment:

![image](https://user-images.githubusercontent.com/5980033/102097871-bfa6ef80-3e26-11eb-9e9f-fbb0db08e97c.png)

**Comment by astares** [comment]
Ah OK, now I can reproduce:
 - create a class "Foo" in a package "Something"
 - create a package "Foo" and click on it's comment
