### ISSUE TITLE
Code import does not with fluid class definition

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8082]
Loading files by dropping it fails. 

Long way to make sure fluid will work 100% but let us take one step at the time.

**Comment by Ducasse** [comment]
[RunArray.st.zip](https://github.com/pharo-project/pharo/files/5684808/RunArray.st.zip)

**Comment by MarcusDenker** [comment]
The reason is that >> is implemented on the class side of SequenceableCollection as an alias for #streamContents:

**Comment by MarcusDenker** [comment]
The # >>  problem is fixed.

What is now not working is that the code import just evaluates the definitions to a builder, but no class is created

see CodeImporter>>#evaluate

**Comment by MarcusDenker** [comment]
So what happens: 

- Fileouts do not distinguish between DoIts and Class Definitions. 
- This means that it just executes the Fluid class def code, but that creates the builder, no the class

We can not use the ideas that solved other cases:
- we can not detect #>>, as it might be in another Doit that is not a  class definition
- we can not send #install as this would break Doits that are not class definitions.

I think the only real solution is to write out not the fluid class definition, but the definition plus a #install. (thus an expression that when evaluated creates the class)

**Comment by MarcusDenker** [comment]
Another idea, especially for Pharo10:

We could just force the CodeExporter to write old style class definitions.
