### ISSUE TITLE
RB - Undo refactoring sometimes not only undo the last changes of refactoring

### ISSUE THREAD

**Issue by Lin777** [guillep/pharo-core#8103]
To replicate:
- Create a class called ClassX  with a #exampleMethod method.
- Create superclass by refactoring.
- Do Push Up #exampleMethod method.
- Do Undo last refactoring.

So, undo refactoring undo push up changes and create superclass changes

**Comment by carolahp** [comment]
I will close this issue since it was solved in [PR#16285](https://github.com/pharo-project/pharo/pull/16285)
