### ISSUE TITLE
asAccessor

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8115]
We need to have 

```
#set: asAccessor
>>> set
``` 

the contrary to asMutator

**Comment by Ducasse** [comment]
```
#set1:set: asAccessor
should be invalid
```

**Comment by Bajger** [comment]
Hi Stephane, 
I understand that:
```
#set: asAccessor >>> #set 
#set asAccessor >>> #set
```
my questions: 
1) What about: `#set1:set:` should raise either Error, or rather return `#set1set` or self?
2) What about binary selectors? Should raise Error or rather return self?

**Comment by Ducasse** [comment]
In fact I always used accessors for both getter and setter. 
So it would be good to have asGetter and asSetter like that there will be no ambiguity.
