### ISSUE TITLE
RPackageOrganizer and RPackage should report about if a package is a test package.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8120]
To avoid string manipulation everywhere we should introduce 
`RPackageOrganizer >> testPackages` and `RPackage >> isTestPackage`

**Comment by Bajger** [comment]
I hope I understood your request in correct way. New method #isTestPackage is based on string (substring) occurence in package name. Please share, if proposed changes are implemented right way. Thanks!
