### ISSUE TITLE
#call:options: send in LGitDiff>>#diff_find_similar:diff_find_options:

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#8128]
**Describe the bug**
LGitDiff>>#diff_find_similar:diff_find_options: uses #call:options:, but that method does not exist anymore

**Comment by Alisu** [comment]
LibGit-Core is an iceberg package.
Open an iceberg issue:
https://github.com/pharo-vcs/iceberg/issues/1398

**Comment by MarcusDenker** [comment]
In Pharo9
