### ISSUE TITLE
RB push up with SharedPools is breaking.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8132]
It turns the shared pools in symbols.

**Comment by guillep** [comment]
To reproduce:

```smalltalk
SharedPool subclass: #TotoSharedPool
	instanceVariableNames: ''
	classVariableNames: 'SP'
	package: ''
	
Object subclass: #TotoSuperclass
	instanceVariableNames: ''
	classVariableNames: ''
	package: ''

TotoSuperclass subclass: #Toto
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: 'TotoSharedPool'
	package: ''

Toto >> foo [
    ^ SP
]
```

Then Push up method `foo`:

![image](https://user-images.githubusercontent.com/708322/102466295-20187580-404f-11eb-9a98-a39eaa6ef00e.png)

Click on `Refactor` and you'll get a warning:

![image](https://user-images.githubusercontent.com/708322/102466343-3292af00-404f-11eb-8771-e15b8254f7fb.png)

Go `YES` and apply the changes.

=> Now class `TotoSuperclass` is broken
It's shared pools dictionary contains the **name** of the pool dictionary and not the pool dictionary itself.

![image](https://user-images.githubusercontent.com/708322/102466528-6c63b580-404f-11eb-9959-ff55728a2555.png)
