### ISSUE TITLE
PerformMessageCommandLineHandler should not be in its own package

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#8133]
**Describe the problem**
We have one package just for the class PerformMessageCommandLineHandler. I vote to move this to be e.g. close to EvaluateCommandLineHandler

**Comment by MarcusDenker** [comment]
ah, no, EvaluateCommandLineHandler needs the compiler, PerformMessageCommandLineHandler does not.

maybe it could be part of the base package?

**Comment by guillep** [comment]
Nope, it should stay like that. We don't want the core to depend on command line stuff either.
We have worked on this for years, and we have **though** this.
There are lots of room for improvements, but this is not one.
