### ISSUE TITLE
Image Crash when using Ephemerons

### ISSUE THREAD

**Issue by rko281** [guillep/pharo-core#8153]
Whilst implementing some code using Ephemeron-based finalization I've been experiencing occasional image crashes. The following script demonstrates the issue:

```
r := EphemeronRegistry new.
k := Object new.
v := Object new.
r at: k put: v.
k := nil.
Smalltalk garbageCollect.
```
This fairly reliably causes an image crash in Pharo 8 and 9, 32 and 64 bit, on Windows and Mac. 

Occasionally I'll get a Debugger; the error is `Not found: anObject->anObject->anObject in IdentitySet>>remove:`; the object being removed isn't an Ephemeron but `an IRSequence (3)`. Stack trace:
```
IdentitySet(Collection)>>errorNotFound:
[ self errorNotFound: oldObject ] in IdentitySet(Collection)>>remove: in Block: [ self errorNotFound: oldObject ]
IdentitySet(Set)>>remove:ifAbsent:
IdentitySet(Collection)>>remove:
EphemeronRegistry>>removeEphemeron:
IRSequence(Ephemeron)>>mourn
WeakArray class>>mournLoopWith:
[ throttle signal.
self mournLoopWith: firstMourner ] in WeakArray class>>finalizationProcess in Block: [ throttle signal....
[ self value.
Processor terminateActive ] in BlockClosure>>newProcess in Block: [ self value....
```

**Comment by Ducasse** [comment]
Thanks, john.  The ephemeron never worked. Mainly because in Squeak nobody used them. 
So we could never use them up until we gain deep knowledge of the VM.
Now I know that the guys were starting to tell me that they want to fix them for real.

**Comment by rko281** [comment]
Thanks for the info; I've worked around the issue by using WeakRegistry.

**Comment by MarcusDenker** [comment]
Ephemerons have been now implemented in Pharo11.

 I close this issue
