### ISSUE TITLE
Failing to pass FloatArray and family through the new FFI 

### ISSUE THREAD

**Issue by ronsaldo** [guillep/pharo-core#8155]
**Describe the bug**
Passing a FloatArray, WordArray, IntegerArray through the FFI to a function that expects a pointer to data is failing. In the previous version this was not failing.

**To Reproduce**
Try the following in a playground:
```smalltalk
dest := ByteArray new: 4.
source := FloatArray with: 42.5.
LibC memCopy: source to: dest size: 4.
dest floatAt: 1.
```

**Expected behavior**
Printing the script should yield 42.5.

**Version information:**
 - OS: Ubuntu
 - Version: 19.10

**Expected development cost**
This seems to be due to the following missing method in those classes:
```smalltalk
tfPointerAddress

	self pinInMemory.
	^ PointerUtils oopForObject: self
```
However, it is not clear on whether this is an accidental or an intended omission (i.e. deprecation).

**Comment by hogoww** [comment]
@guillep @Ducasse PR merged, so issue to close (I'm assuming)
