### ISSUE TITLE
Step to return failure when a method contains a closure

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#8167]
**Bug description**
The `Step to return` context menu debugger action causes infinite recursion when the method contains a closure (after the breakpoint place).

**To Reproduce**
1. create and run following method:
``` smalltalk
message 

	| var | 
	
	self halt.
	var := self class environment allClasses.
        var := var select: [ :each | each beginsWith: 'S' ].
	var := var reversed.
	^ var
```
2. do single _Step Through_
3. In the debugger, do `Step to return` from the context menu. 
4. The system will hang, if you to user interrupt, it ends with tons of debuggers `[Post-mortem] Context(Object)>>errorSubscriptBounds:`

**Comment by tesonep** [comment]
Fixed in #8400
