### ISSUE TITLE
CompiledMethod>>#referencedClasses should not take class variables into account

### ISSUE THREAD

**Issue by chisandrei** [guillep/pharo-core#8168]
`CompiledMethod>>#referencedClasses ` also takes into account the values of class variables. Ideally it should not as the results can change depending on the value of class variables. 

This creates a class with a class variable

```
Object subclass: #AATest
	instanceVariableNames: ''
	classVariableNames: 'VarA'
	package: 'AST-Core-Tokens'.
	
#AATest asClass class compile: 'initializeVar
	VarA := Object'.
	
#AATest asClass class compile: 'varA
	^ VarA'.
```

The method `#varA` has no referenced classes
```
(AATest class >> #varA) referencedClasses .  "an IdentitySet()"
```

Now we initialize the variable to point to a class.
```
AATest initializeVar.
```

If we call now `referencedClasses` we get a dependency to `Object` just because it is stored inside the class variable.
```
(AATest class >> #varA) referencedClasses. "an IdentitySet(Object)" .
```

Happens in Pharo 8 / Pharo 9

**Comment by MarcusDenker** [comment]
I did a PR 22 days ago. It waits for a review to be merged.
