### ISSUE TITLE
Pharo latest on Mac: input broken

### ISSUE THREAD

**Issue by dvmason** [guillep/pharo-core#8171]
I tried to type "dvmason" in a playground and this is what I got:
<img width="211" alt="Screen Shot 2020-12-24 at 8 45 49 AM" src="https://user-images.githubusercontent.com/2913975/103092478-5b71f180-45c5-11eb-94a0-4bc82a03035a.png">

This was on the official version (64bit) as of this moment (refreshed PharoLauncher)... also Pharo Development version build 997 exhibits exact same behaviour.
MacOS Mojave 10.14.6
(borked is another word for fubar or afu or snafu or f****d)

**Comment by guillep** [comment]
Hi Dave, could you please tell us what version of the VM you're using?

My Pharo launcher shows me I'm using the VM from 2020-11-02, and that my Pharo9 images are using by default that VM:

![image](https://user-images.githubusercontent.com/708322/103092912-1a93d000-45f9-11eb-8a37-a34d843573f2.png)
![image](https://user-images.githubusercontent.com/708322/103092867-f637f380-45f8-11eb-8449-578c9c1fc8db.png)

And keyboard is working ok for me.

**Comment by dvmason** [comment]
I did a binary search on versions, and build 989 works, build 990 fails.

**Comment by kasperosterbye** [comment]
I get this strange behaviour - here shown in playground, but it appears in any textfield I have tried. In the attached video I type 'abcdef....'

Build: 1026, commit: 93d6505

[Video of the problem](https://user-images.githubusercontent.com/17723745/103912194-46d64300-5107-11eb-80f8-30ea67c99c22.mov)

**Comment by kasperosterbye** [comment]
I have located the error to have been introduced in build Pharo9.0-SNAPSHOT.build.990.sha.3e99899.arch.64bit, the 989 build is OK on my Mac (Catalina 10.15.7, Macbook Pro 2018)

**Comment by pavel-krivanek** [comment]
which means https://github.com/pharo-project/pharo/pull/8156
