### ISSUE TITLE
SearchMorph does not understand searchKeyStroke:

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8173]
Hi guille

I suspect that this is a side effect of the keystroke: refactorings. 

```
buildSearchMorph
	^ searchMorph := SearchMorph new
			model: self;
			acceptSelector: #searchAccept:;
			updateSelector: #searchUpdate:;
			searchList: self class searchList;
			keystrokeSelector: #searchKeystroke:
			yourself.	
```

To reproduce 
- open calypso
- try to rename initialize-release protocol.

**Comment by hgranthorner** [comment]
I'm getting the same error whenever I try to create a protocol.

If I just create a basic class inheriting from Object

`Object subclass: #FizzBuzzer

	instanceVariableNames: ''

	classVariableNames: ''

	package: 'My-Scratch'`

I am unable to create any protocols, whether I have any methods defined or not.

**Comment by astares** [comment]
@hgranthorner Just comment the line out as a workaround until it is fixed:
```Smalltalk
buildSearchMorph
	^ searchMorph := SearchMorph new
			model: self;
			acceptSelector: #searchAccept:;
			updateSelector: #searchUpdate:;
			searchList: self class searchList;
			"keystrokeSelector: #searchKeystroke:"
			yourself.	
```
