### ISSUE TITLE
printString warning fix does not solve the problem. 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8178]
```
Counter >> printOn: aStream
    super printOn: aStream.
    aStream nextPutAll: ' with value: ', count printString.
```

But it produces two warnings:

*  [printString] No printString inside printOn
*   Use cascaded nextPutAll:’s instead of #, in #nextPutAll:

It has the option to automatically resolve the cascaded nextPutAll: which results in:

```
printOn: aStream
   super printOn: aStream.
   aStream 
         nextPutAll: ' with value: ';
         nextPutAll: count printString
```

But it still has the warning about printString.

**Comment by MarcusDenker** [comment]
there is still a printString, the idea is to force people to use printOn: instead:   "count printOn: aStream"
