### ISSUE TITLE
When FluidClass on Epicea Tests break

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8179]
So I will fix them :)

**Comment by Ducasse** [comment]
So far I failed to fix them :(
I published in my repo what I found

**Comment by Ducasse** [comment]
Notes with Pablo in the train

For the fluid class builder on class side

We should return a builder prefilled with information from the instance side. 

For this we should 

Object << #Point

=> 

Object class << #Point class
	slots: {#uniqueInstance}
	traits: {TFlying + }
	package: ....
The steps to get there are:

- grab the instance (Point)
- create a class side builder to prefilled itself from the instance side
- then fill up the slots

**Comment by MarcusDenker** [comment]
After https://github.com/pharo-project/pharo/pull/10882 is merged, we have just two failing tests:

EpRevertTest>>#testClassRemoval
EpRevertTest>>#testTraitRemoval

The mechanism to create a revertion of a removal (class and trait), which would be an adding of that class, is not working.

**Comment by MarcusDenker** [comment]
I tracked down the cause: EpMonitor>>#behaviorRemoved: has workarounds that do not work for Fluid

- for Obsolete classes, the code after "Fix class name (remove AnObsolete prefix)
- for the category, see the code after "Fix category"
