### ISSUE TITLE
When fluid class on some ReleaseTest tests are breaking.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8184]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version information:**
 - Version: [e.g. 1.6.1]

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 
In addition, are you willing to help because after all Pharo is yours too?

**Additional context**

**Comment by MarcusDenker** [comment]
Works now!
