### ISSUE TITLE
We should clean so that testNoUnusedTemporaryVariablesLeft is green

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8188]
testNoUnusedTemporaryVariablesLeft

>>>
GTGenericStackDebugger SpTestPresenterWithToolbar DiskDirectoryEntry MCMockClassF ClySubclassLOfClass2FromP1 RSKeyboardEvent CP1253TextConverter FT2Handle AthensCurveFlattener WindowsStore TextEditorDialogWindow SystemSystemSettings OSKeySymbols RBTransformationRuleTestData1 MCMockClassB JobProgressMorph ClyClass2FromP1 SDL2Constants LiteralVariableTest StObjectInspectorPresenter FTSizeRec FooSharedPool ZnConstants MetacelloConfigTemplateExample SystemProgressItemMorph JobProgressBarMorph RBLintRuleTestData AthensCairoDefinitions ISO88597TextConverter CDClassWithFullDefinitionExample FFIStringCalloutTest MetacelloConfigTemplate IceLibgitTonelFileUtils BalloonMorph Locale FileList BalloonEngineConstants Character LGitExternalObject RBDummyLintRuleTest FFICallbackParametersTest StHaltCacheChanged MenuItemMorph Unicode IceLibgitFiletreeFileUtils HandMorph LanguageEnvironment ShTestSharedPool

**Comment by MarcusDenker** [comment]
It is not failing in my image.

Mayne it was the test about class variables? That one is skipped as we need to clean up before we can turn it on

**Comment by Ducasse** [comment]
No it is not failing because skipped but we should clean all these.

**Comment by MarcusDenker** [comment]
testNoUnusedTemporaryVariablesLeft is not skipped in my image

**Comment by MarcusDenker** [comment]
testNoUnusedClassVariablesLeft and testNoUnusedInstanceVariablesLeft are skipped as we can only enable them when everything is fixed. For *temps* we fixed it already.

**Comment by Ducasse** [comment]
Ah ok so we can remove the skip then?
When I tried to fix the unused instance variables I got a build crash.

**Comment by MarcusDenker** [comment]
There is not skip in testNoUnusedTemporaryVariablesLeft

**Comment by astares** [comment]
I guess @Ducasse was wrong in the title and description of this issue. I guess he means 
 - **#testNoUnusedClassVariablesLeft** (which is skipped at the moment still and not yet cleaned) 
 - and not #testNoUnusedTemporaryVariablesLeft (which is cleaned already and green)

Yes - we need to clean these unused class vars. Is there an issue for this already as this one here is closed already?
