### ISSUE TITLE
Breakpoints make mess in bytecodes

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#8200]
**Bug description**
In some methods with closures, installation of a breakpoint can make the bytecodes overcomplicated and after removing of the breakpoint, 

**To Reproduce**
1. install this method to a class (e.g. ASTCache, the method does not make sense, the structure is important):
```smalltalk
translatableErrorMessage
	
	self yourself do: [ :e | e name ifNotNil: [ :pm | ^pm ] ].
	^nil
```
2. check the method bytecode, it looks ok
![Pharo_Wfqep5lOoH](https://user-images.githubusercontent.com/572494/103279012-243c7f80-49cd-11eb-9ea9-f032468f3e99.png)

3. put cursor on `self` and install a breakpoint, check the bytecode. 
![Pharo_ATbSYUS8jd](https://user-images.githubusercontent.com/572494/103279267-af1d7a00-49cd-11eb-9ae9-53228ab841e4.png)

4. uninstall the breakpoint and see the bytecode again 
![Pharo_9ciNh5fg18](https://user-images.githubusercontent.com/572494/103279373-eab84400-49cd-11eb-9c51-87b6b5e7ec57.png)

**Version information:**

Pharo 9.0.0
Build information: Pharo-9.0.0+build.999.sha.843f585b3bcb84a0efdb3884aa8a968f342e32fe (64 Bit)

**Comment by Ducasse** [comment]
Thanks Pavel. Indeed with the fullblock and recent changes we got real instabilities.

**Comment by Ducasse** [comment]
We will have to really address this in january.

**Comment by MarcusDenker** [comment]
This is fixed by https://github.com/pharo-project/pharo/pull/10177

**Comment by pavel-krivanek** [comment]
thanks!
