### ISSUE TITLE
RPackageOrganizer >> packageMatchingExtensionName: seems to be very slow

### ISSUE THREAD

**Issue by chisandrei** [guillep/pharo-core#8202]
We were profiling the loading of code in Metacello and noticed that during loading  of GT the method RPackageOrganizer >> packageMatchingExtensionName: was taking a significant amount of time:

<img width="976" alt="Screenshot 2020-12-30 at 11 16 18" src="https://user-images.githubusercontent.com/3534711/103345016-89a57480-4a90-11eb-8c14-a1bc24c4b9f8.png">

The slowdown seems to come from the concatenation `aSymbol, '-'` which creates a new symbol every time. Symbol creation however is an expensive operation.

In the GT loading build replacing that with `aSymbol asString, '-'` reduced the loading time on the CI from 30 minutes to 16 minutes!

This was observed in Pharo 8: Pharo-8.0.0+build.1145.sha.7dc39ed9e28dda58cf139f1723f350d5361d9b0f (64 Bit)
Unnamed

CoInterpreter * VMMaker-CompatibleUserName.1580983506 uuid: 7aff73cb-5a2e-5002-a356-37de4e762a49 Feb 12 2020
StackToRegisterMappingCogit * VMMaker-CompatibleUserName.1580983506 uuid: 7aff73cb-5a2e-5002-a356-37de4e762a49 Feb 12 2020
VM: 202002121007 https://github.com/pharo-project/opensmalltalk-vm.git Date: Wed Feb 12 11:07:12 2020 CommitHash: 2bd9e39 Plugins: 202002121007 https://github.com/pharo-project/opensmalltalk-vm.git

**Comment by Ducasse** [comment]
Thanks andrei.

**Comment by MarcusDenker** [comment]
Similar report: https://github.com/pharo-project/pharo/issues/6944

**Comment by MarcusDenker** [comment]
next step: from @syrel:

We could also avoid concatenation all together, which would be more than 50% faster.

Since we always concatenate `aSymbol` with `'-'` we do not have to care about empty string (`withEmpty:` part of `beginsWithEmpty:`). Next since `-` is constant we can directly compare the value at a destination index with `-`

```smalltalk
aSymbol := #Package.
anExtensionName := 'Package-Tag-Examples'.

aSymbolIndex := anExtensionName findString: aSymbol startingAt: 1 caseSensitive: false.
aMinusIndex := aSymbolIndex + aSymbol size.
hasPrefix := aSymbolIndex > 0
	and: [ (aMinusIndex <= anExtensionName size)
		and: [ (anExtensionName at: aMinusIndex) = $- ] ]
```

**Comment by astares** [comment]
@MarcusDenker: lets handle this in a new issue, no?

**Comment by MarcusDenker** [comment]
with https://github.com/pharo-project/pharo/issues/8242 we can close this
