### ISSUE TITLE
Slot rename in Stateful Traits in Pharo 7 and 8 is broken (prevents compilation)

### ISSUE THREAD

**Issue by SimonXHolland** [guillep/pharo-core#8205]
**Describe the bug**
The slot rename operation in the Stateful Traits implementation  in Pharo 7 and 8 does not work  (compilation failure)

**To Reproduce**

Trait named: #MyTrait
	 uses: {}
	 slots: { #name }

Object subclass: #MyClass
   uses: (MyTrait >> { #name -> #otherlName })

Any attempt to create a traited class using the  >> (or @@ if you prefer) composition algebra operator fails to compile

**Expected behavior**
Should compile

**What the problem appears to be**

The problem is that, (unlike #@, #- and #-- which are all present and correct)  #>> is not present in Trait

It's easy to fix this immediate problem in Trait 
(which I tried guided by analogy with the other composition algebra methods)  with a new instance method:

>> anArray
"   I return myself with an aliased method. 
     Check TaAbstractComposition >> #>> for more details"
    ^ self asTraitComposition >> anArray

And this gets us past the first road block, because TaAbstractComposition does already implement
   #>> (along with  @, - and --) as follows:

    >> anAssociation
         "This operation creates a new trait composition element with a slot renamed.
         The parameter is an association, where the key is the old name and the value the new name."
        ^ TaRenameSlot from:anAssociation key to: anAssociation value on: self.

But, minor problem, TaRenameSlot  is only equipped to deal with a single association, but is handed an array.
This looks simple to repair, by analogy with TaAliasMethod, 
and I tried one or two naïve fixes and work arounds, but these caused other problems so no good. A proper fix would benefit from more knowledge of the relevant co-operating classes and methods.

**Version information:**
 - MacOS  Mojave 10.14.6
 -  Pharo8.0.0  build: 1124, commit: 0932da8
 - Pharo7.0.5.  build: 177, commit: fd8c156

**Expected development cost**
From looking at the analogous TaAliasMethod,  for a person who knows the Trait v2 compositions category, 
I am guessing  5 -  30 mins work.  I don't think its any worse than that,  given that Pablo Tesone et al's  paper: "A new modular implementation for Stateful Traits"  and  Delplanque's helpful note at:
https://github.com/pharo-open-documentation/pharo-wiki/blob/master/General/Traits.md
both indicate that slot renaming was working  at some unknown point in Pharo 7.

I would be really happy to try  fixing this, but would need to be able to consult someone with some knowledge of the Trait v2 compositions category, or perhaps general Pharo smarts. 

**Additional context**
So happy that Pharo has stateful traits - looking forward to using them.

**Comment by SimonXHolland** [comment]
**Additional notes from newbie point of view:**
In order to understand what is needed a bit more,
in a local copy I temporarily kluged:

 TaAbstractionComposition >> >>     “(or @@ if you prefer)”
	“to temporarily take  just the first association from the array it is passed
	and to pass this on to TaRename Slot”

Then I tried: 
TaRename Slot  >> traitCompositionExpression
	^ self inner traitCompositionExpressionWithParens , ' @@ '
		, (Array with: (Association key: oldName value: newName)) printString

Which looks about right and allows class definition assembly to begin with the  CDTraitCompositionBuilder 

But then we immediately hit the problem that 

CDAbstractTraitCompositionNode does not know  @@,  
and, more to the point, there is no CDTraitRenameNode  class defined yet.

Looking at CDTraitAliasNode for guidance by analogy to how this might be coded
it looks like there are further things a newbie could try to explore what is needed, and the various papers on 
Opal and AST look relevant, though I don’t know of any paper discussing this level of detail that takes into account the changes reflected in the Tesone at al 2020 paper. 

But that’s all the time I have for this weekend. I’ll try to have a further look whenever I can.

**Comment by SimonXHolland** [comment]
**Apparent partial fix**

There appears to be a simple fix for the special case where there is only a single variable to be renamed.  (It’s  less clear how to deal with an _array_ of renames in a way that fits cleanly with the  class parsing process) 

We need a method in CDAbstractTraitCompositionNode
   @@ aCollection
	“Transcript show: 'Parse Tree built'.”
	^ CDTraitRenameNode new
		subject: self;
		renames: aCollection

But then we also need a new class CDTraitRenameNode  

Going by analogy with CDTraitAliasNode,  It appears we need the following two slots,

CDTraitCompositionNode subclass: #CDTraitRenameNode
	slots: { #renames. #newName }
	classVariables: {  }
	package: 'ClassParser-Model'

(where #renames is the whole array of all the renames, and this node deals with just one 
of them which we indicate using #newName)

Now we just  need  variable accessor methods for this class, and methods #toString and  #isTraitRenameNode   
(by analogy with CDTraitAliasNode)

_As a notational aside, in the Tesone  et al 2020 paper, the notational convention for specifying  aliases and renames  appears to be  inconsistent :
   For methods  		 	 newname  -> oldname
       whereas
  For instance variables	        oldName -> new name

Maybe there is a good reason for this, but from a cognitive ergonomics point of view this looks unfortunate. _

Remarkably this is all we need. The composed Class now compiles, and instances deal with the new instance variable name correctly.

But note, if we try to compile a composed class where more than one variable is renamed, we still get a compilation failure. It's unclear how to  best untangle the plumbing.

**Comment by SimonXHolland** [comment]
Ah, no, it does compile,  but only the first variable is renamed. So we still need to work out how to get the correct compilation parse tree to be built.

**Comment by SimonXHolland** [comment]
This fix must be totally wrong. It does the rename alright, but executes it on the globally accessible Trait class, not just in the scope of  the  composed class. Highly educational, but not what is needed.

**Comment by MarcusDenker** [comment]
Hello, I have done a PR that in the end just implements the things along the lines as you describe

With this, I can now define a trait with state (using the instanceVariable syntax, below it uses slots)

```
Trait named: #MyTrait
	uses: {}
	instanceVariableNames: 'otherName'
	package: 'ForTesting'
```
The I add accessors:

```
otherName: aName
	otherName := aName
	
otherName
	^otherName	
```

Now create a class:

```
Object subclass: #MyClass
	uses: MyTrait @@ {#otherName->#name}
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'ForTesting'
```

there I can now add an accessor for the variable but using the the name:

```
name
	^name
```

And it seems to work:

```
MyClass new  otherName: 1 ; name
```

this sets the var using the accessor it got from the trait, but reads it using "name", and it seems to work.

**Comment by MarcusDenker** [comment]
What it does:

- add tests for slot renaming. I added them to T2TraitWithAliasTest to be close to the method alias tests
- change the selector to @@. We can not use >> as that one returns compiledMethod on a Trait (like it does on a class)
- implement @@ on Trait
- change TaRenameSlot to support multiple renames. This way TaRenameSlot works like TaAliasMethod

Fix classparser so the tool can make sense of the definion:

- add CDTraitSlotRenameNode
- implement @@ so it gets created

**Comment by SimonXHolland** [comment]
Hi Marcus — Sounds excellent !
— forgive me while still learning iceberg —
But the two key points I would like to double check are: 
         1/  What happens when  more than one variable is being  renamed
        2/ Whether the rename happens correctly in the scope of the composed class, or on the global Trait class.
These were both issues with my exploratory code
Thanks

**Comment by MarcusDenker** [comment]
1) should work, I have already a test where the second var is renamed, will commit a version that really renames two at the same time.
2) looking at it again, we still have a problem: the original code was just updating the slot... but that modifies the original slot! What we need to do is to create a wrapper slot. Which would give a new name, but delegates code generation to the original slot. I will have a look at that.

**Comment by MarcusDenker** [comment]
I found an easy fix: we can just copy the Slot before we change the name.

I updated the PR with that

**Comment by SimonXHolland** [comment]
Nice one!

**Comment by SimonXHolland** [comment]
Should be easy to fix instance variable removal too ( -- )  - I tweaked my local code yesterday  and it looked like a very quick job

**Comment by MarcusDenker** [comment]
The PR has been merged. I will close this and open a new one for the removal

**Comment by MarcusDenker** [comment]
I added https://github.com/pharo-project/pharo/issues/8503 for the ivar removal

**Comment by SimonXHolland** [comment]
Great — thanks !
