### ISSUE TITLE
Global shortcuts only works when a Pharo window is focused

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#8214]
**Describe the bug**
Global shortcuts like CTRL + O + I, SHIFT + ENTER or CTRL + O + T only works when a Pharo window is focused or outside of the initial extent of the native window.
You need to give the focus to an open window to be able to perform it. Giving the focus to the World or the Windows Pharo native window is not enough

In addition, if the pointer is in the initial extent of the native window it is working. Meaning that if you give the focus to the world and go to the initial extent, it is working. In the green zone there:
![image](https://user-images.githubusercontent.com/4706329/103406034-8629f000-4b59-11eb-991d-399af48da2ea.png)

**To Reproduce**
1. Go to pharo
2. Enlarge the native window
3. Click on the world (maybe twice to close the world menu)
4. Try the shortcut CTRL + o +i in the new extent zone -> does not work
5. Move the pointer to the initial extent
6. Try the shortcut CTRL + o +i in the new extent zone -> works

**Expected behavior**
works everywhere

**Version information:**
Pharo9.0.0
build: 1000, commit: f92e709
Windows 10

**Expected development cost**
Not too much

**Additional context**
Reproducible in vanilla Pharo image with the headless VM

**Comment by Ducasse** [comment]
Nice catch

**Comment by Ducasse** [comment]
Oh super nice analysis. 
This would explain some of our frustration.

**Comment by Ducasse** [comment]
Do you have the same behavior with Saving the image. 
Because I tried it in the complete area and it worked (but on mac).
