### ISSUE TITLE
Debugger stack menu is completely broken

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#8218]
**Describe the bug**
This menu:
![image](https://user-images.githubusercontent.com/4706329/103462374-1bc5ab00-4d25-11eb-9db2-cb5ff4aa381d.png)
is broken for all the important entries:
- method:
![image](https://user-images.githubusercontent.com/4706329/103462402-3b5cd380-4d25-11eb-9552-85badde472ce.png)
expected:
![image](https://user-images.githubusercontent.com/4706329/103462418-53ccee00-4d25-11eb-9d54-4b6f4a9d5e1f.png)

- receiver:
![image](https://user-images.githubusercontent.com/4706329/103462402-3b5cd380-4d25-11eb-9552-85badde472ce.png)
expected:
![image](https://user-images.githubusercontent.com/4706329/103462418-53ccee00-4d25-11eb-9d54-4b6f4a9d5e1f.png)

- method inheritance:
![image](https://user-images.githubusercontent.com/4706329/103462438-6f37f900-4d25-11eb-8d02-b8c2ab068a91.png)

- method version: ok

- implementors:
![image](https://user-images.githubusercontent.com/4706329/103462454-8e368b00-4d25-11eb-8b1a-8e7d62bfe18d.png)

- senders:
![image](https://user-images.githubusercontent.com/4706329/103462460-9a224d00-4d25-11eb-95ec-aabaa7139b69.png)

- references:
![image](https://user-images.githubusercontent.com/4706329/103462467-a4dce200-4d25-11eb-8322-0c468f5c4a3d.png)

- class references:
![image](https://user-images.githubusercontent.com/4706329/103462475-b3c39480-4d25-11eb-866e-5c12dede6fdf.png)

- class hierarchy:
same missing doBrowseHierarchy

- class variables: ok

-class variable references: ok

- inst var refs: ok

**To Reproduce**
See screenshots

**Expected behavior**
No DNU and the right method selected.

**Version information:**
Pharo9.0.0
build: 1003, commit: e7b4087
Win10

**Expected development cost**
Not too much 
+ a lot more on testing

**Comment by Ducasse** [comment]
Some of the points are related to the SymbolExtractor logic (that extract a selector from a piece of code). 
We extracted it from rubric. We tested and made it better for selectors. 
x selector...

But we should improve it for x because for the receiver it is not working.

**Comment by MarcusDenker** [comment]
The top menu has nothing to do with the SymbolExtractor.

The menu entries for "browse methods" and browse receiver are fixed. We have just not yet merged the code.

See: https://github.com/pharo-spec/NewTools/pull/142

Fixed sice 20!! Days!

**Comment by VincentBlondeau** [comment]
Since it is not integrated in the released image, I'd not consider this issue solved. Did I miss sth?
And shouldn't the last build of the image consider the pharo-spec:master branch?
