### ISSUE TITLE
Browse button in the debugger bottom pane directs to STDebuggerContext

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#8219]
**Describe the bug**
That:
![image](https://user-images.githubusercontent.com/4706329/103462577-79a6c280-4d26-11eb-819c-4c650b60c486.png)
Opens:
![image](https://user-images.githubusercontent.com/4706329/103462582-83c8c100-4d26-11eb-8443-af420b7e2a78.png)
And should open:
![image](https://user-images.githubusercontent.com/4706329/103462590-917e4680-4d26-11eb-8e51-a36db7a03449.png)

**To Reproduce**

**Version information:**
Pharo9.0.0
build: 1003, commit: e7b4087
Win 10

**Expected development cost**
Not too much + a lot more on testing

**Comment by MarcusDenker** [comment]
fixed since 20 days: https://github.com/pharo-spec/NewTools/pull/142

**Comment by MarcusDenker** [comment]
(maybe not that I need to check)

**Comment by MarcusDenker** [comment]
The inspector on the left is inspecting a STDebuggerContext. The button to inspect opens a free-standing inspector on it. As it is a normal inspector, it has a browse button, too.

Maybe we should remove the browse button as it is not really something you would ever do
