### ISSUE TITLE
Warning: PotentialOutDatedDependencyWarning: Kernel: FFI-Kernel dependency declared in the package Manifest as manuallyResolvedDependencies not detected as a dependency!

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#8241]
**Describe the problem**
We get on the CI a lot:

Warning: PotentialOutDatedDependencyWarning: Kernel: FFI-Kernel dependency declared in the package Manifest as manuallyResolvedDependencies not detected as a dependency!

**Comment by Ducasse** [comment]
Yes we get the same when running the tests locally.
