### ISSUE TITLE
Cannot type a pipe | character on an azerty keyboard

### ISSUE THREAD

**Issue by dupriezt** [guillep/pharo-core#8300]
**Describe the bug**
Typing a pipe | character on an azerty keyboard (Alt-Gr + 6) in any text editor brings up a "choose color..." dialog (screenshot below) instead of typing |. Typing a | on a qwerty keyboard works normally.

![image](https://user-images.githubusercontent.com/32486709/103709749-96a3f580-4fb3-11eb-859c-0f77e25c35a7.png)

First exploration:
The "choose color..." dialog is created by `RubTextEditor>>#changeEmphasis:`, when it is called by `RubTextEditor>>#performCmdActionsWith: aKeyboardEvent shifted: aBoolean return: return`.
![image](https://user-images.githubusercontent.com/32486709/103710073-690b7c00-4fb4-11eb-96db-83778fb0a9f7.png)

The most recent changes to the RubTextEditor class are commits 0cadbda9173e00b65f0d5bb65afc12b20781846e ("restore Rubric events") and fdb02f7c29f7089f9b38fcdca4ab5d02b44be0aa ("Fix shortcuts in Rubric"), both from pull request #8156 by @guillep. Maybe that's what introduced this bug.

By the way, I don't know what this color dialog is supposed to do. Picking a color does not have an effect...

**Version information:**
 - OS: Windows 10

**Comment by Ducasse** [comment]
Thomas do you use the latest headless VM?
Because on Linux it is clear that we have a regression since the SDL handlers got cleaned (and people cannot use the latest vm but on windows it should not happen). 

Thanks

**Comment by Ducasse** [comment]
But may be this is not related to that. Still related to the SDL events.

**Comment by dupriezt** [comment]
I don't know exactly how to check which VM an image is running on, but Pharo-launcher says I only have 90-x64 installed for Pharo 9 (and not 90-x64-headless).
![image](https://user-images.githubusercontent.com/32486709/103750425-10190380-5007-11eb-965c-0434815fae28.png)

**Comment by MarcusDenker** [comment]
maybe related to https://github.com/pharo-project/pharo/issues/8171
