### ISSUE TITLE
Cog VM crash 'COG SPUR has stopped working'

### ISSUE THREAD

**Issue by davejordan** [guillep/pharo-core#8304]
**Describe the bug**
When opening a particular image, the VM crashes and shows the message "COG SPUR has stopped working"

**To Reproduce**
I can't reproduce on a new image, but on the corrupted image, reproduce by opening the image in Pharo.

**Expected behavior**
Expect the Image to open and I can continue where I left off.

**Screenshots**
![image](https://user-images.githubusercontent.com/7408882/103817196-1b4b4e00-505e-11eb-8596-c0608989df0c.png)

**Version information:**
- OS: Window 8.1 Enterprise
- Pharo Template: (Pharo 8.0 - 64bit (stable) _ Logistic Map 2)
- imageFormatNumber: 68021
- imageVersion: 80

**Expected development cost**
I don't know. Willing to help if I can.

**Additional context**
A copy of my [PharoDebug.log](https://pastebin.com/uWfE8PSy)

The windows crash message details are:
Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: Pharo.exe
  Application Version:  5.0.0.0
  Application Timestamp:    00000000
  Fault Module Name:    StackHash_e5fb
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   00000000
  Exception Code:   c0000005
  Exception Offset: PCH_94
  OS Version:   6.3.9600.2.0.0.256.4
  Locale ID:    2057
  Additional Information 1: e5fb
  Additional Information 2: e5fbb79501a5ec44936c965495b7ed9d
  Additional Information 3: 87e1
  Additional Information 4: 87e19eaa5875c71ec8875aadb1c1eca7

**Comment by Ducasse** [comment]
Thanks for the report. 
We are sorry about it. 
We are working on more stable version.

**Comment by Alisu** [comment]
The bounds of all the graphical elements are Points instead of a Rectangles. At least for the LabelMorph and the SystemWindow. It must start a recursive DNU.
As for what it happens I did not find.

**Comment by MarcusDenker** [comment]
It seems that the image was saved in a broken state somehow. Not sure what we can do for this.

 I propose to close the issue (please open a new one if this happens again)
