### ISSUE TITLE
Tab stops to work for completion

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#8320]
**Describe the bug**
With (non-standard) setting when you disable _CodeBrowsing-Code Completion-Popus is automatic_ option, pressing of Tab key stopped to work. Probably related to https://github.com/pharo-project/pharo/pull/8156

**Version information:**
Pharo 9.0.0
Build information: Pharo-9.0.0+build.942.sha.96f4fbd26164cc31e2e68bdc201c32559f604bc5 (64 Bit)

**Comment by guillep** [comment]
Could you give more details? I've checked in builds 942 and build 1027 and a tab character gets inserted.
What do you mean by "tab key stopped to work"? it does not insert the tab key or it does not open the completion menu?

**Comment by pavel-krivanek** [comment]
with the option disabled _CodeBrowsing-Code Completion-Popus is automatic_ , the Tab key should show the completion popup. In older images it does.
