### ISSUE TITLE
Debugger is confused

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8330]
Hi guys

I do not get self is $s. I do not understand anything in fact.
Check the video.

2021-01-10-DebuggerGlitch.mov

**Comment by VincentBlondeau** [comment]
Video is not attached :(

**Comment by StevenCostiou** [comment]
@Ducasse the video seems not to be attached. Could you upload it again?
Could you specify the pharo version?

**Comment by StevenCostiou** [comment]
Could you add the video? I'm in the dark here :)

**Comment by Ducasse** [comment]
http://rmod-files.lille.inria.fr/?dir=Tmp
I forgot the path

<blockquote><div><strong><a href="http://rmod-files.lille.inria.fr/?dir=Tmp">Tmp • Directory Lister</a></strong></div></blockquote>

**Comment by StevenCostiou** [comment]
Aaah ok! 
Self is not wrong, it is the test assertion failure presenter that displays nonsense.
Do you know how to reproduce the same failure? Because now your test is passing so I cannot reproduce the exact same problem.

**Comment by StevenCostiou** [comment]
Ok I was able to reproduce: it tries to show you the diff for a `shouldnt:raise:`, while it has no sense to do that.
