### ISSUE TITLE
Home key (return to the start of the line) does not work

### ISSUE THREAD

**Issue by dupriezt** [guillep/pharo-core#8334]
**Describe the bug**
Pressing the home key ("début" on french keyboard) does not bring the cursor to the start of the line as it should.

**Version information:**
 - OS: Windows 10. Azerty french keyboard

**Comment by dupriezt** [comment]
Maybe another problem related to keys and morphic events? @guillep

**Comment by guillep** [comment]
Probably, I'll check it. This one will be more complicated to test as I don't have a keyboard with a home key :). I'll find a keyboard simulator
