### ISSUE TITLE
Error when typing <  and > on azerty keyboard

### ISSUE THREAD

**Issue by dupriezt** [guillep/pharo-core#8348]
**Describe the bug**
When I type < or > on a french Azerty keyboard, the character does get typed, but a debugger opens.
No issue when typing these 2 characters on a Qwerty layout.

Debugger when typing <:
![image](https://user-images.githubusercontent.com/32486709/104307357-6ab2d380-54cf-11eb-8453-3cbefa4c37ad.png)

Debugger when typing >:
![image](https://user-images.githubusercontent.com/32486709/104307394-77372c00-54cf-11eb-8678-a436b7d5ac5c.png)

**To Reproduce**
Here is a drawing of the key used to type < and > on an Azerty layout:
![image](https://user-images.githubusercontent.com/32486709/104307666-ced59780-54cf-11eb-80d6-f101c7dc08d9.png)

This key types <. Shift+this key types >

**Version information:**
 - OS: Windows 10. French Azerty keyboard

**Comment by dupriezt** [comment]
@guillep This is maybe another consequence of the morphic event changes.

**Comment by guillep** [comment]
What version of Pharo are you using? Please state that on every issue, otherwise this is very difficult to track.

**Comment by guillep** [comment]
Fixed in https://github.com/pharo-project/pharo/pull/8350
