### ISSUE TITLE
Error when typing [ on Qwerty keyboard

### ISSUE THREAD

**Issue by dupriezt** [guillep/pharo-core#8349]
**Describe the bug**
When I type [ on a Qwerty layout the character does get typed, but a debugger opens.
No issue when typing this character on an Azerty layout.
Also no issue when typing ] on a Qwerty layout

Debugger that opens when typing [ on a Qwerty layout:
![image](https://user-images.githubusercontent.com/32486709/104320002-077e6c80-54e2-11eb-9fd3-285a4fd1b8ed.png)

**Version information:**
 - OS: Windows 10, Qwerty layout

**Comment by dupriezt** [comment]
@guillep Another keyboard issue.

**Comment by guillep** [comment]
What version of Pharo are you using? Please state that on every issue, otherwise this is very difficult to track.

**Comment by guillep** [comment]
Fixed in https://github.com/pharo-project/pharo/pull/8350
