### ISSUE TITLE
Inspecting a Text no longer shows the formatted text

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#8352]
**Describe the bug**
It used to be (before "newtools" I  believe) that `'An all bold text' asText allBold inspect` would bring up an inspector which would show the rendered text as first presentation.

**To Reproduce**
doing this in a playground: `'An all bold text' asText allBold inspect` 

**Screenshots**
Old behaviour:
![image](https://user-images.githubusercontent.com/17723745/104337158-76b18c00-54f5-11eb-84f7-2a3bae52de77.png)

New behaviour:
![image](https://user-images.githubusercontent.com/17723745/104337065-5eda0800-54f5-11eb-951b-675caf978de0.png)

**Version information:**
 - The error manifests itself in Pharo 9, build 1030, and not in build 6 (sorry, it was just a random old image I had)

**Expected development cost**
I expect some method has to be implemented in class Text, with the right pragma. I just do not know which pragma and which method.

**Comment by estebanlm** [comment]
well... this is not so easy since we do not have a RichTextPresenter yet and doing one right is a lot of effort and time. 
We could workaround the issue adding a "morphic specific" presenter that will receive a Text instead a String  and it would behave as (more or less) expected. 
will that work for you?

**Comment by estebanlm** [comment]
.. or I can workaround the issue even heavier, and just use the TextMorph (as we can add morphs). Since Text is kind-of Morphic exclusive... this will not be a real inconvenient I think.

**Comment by kasperosterbye** [comment]
I might suggest you use the same mechanism that is currently used for the comment field of the classes in the browser. I just do not know if that is a TextMorph, I have just recently returned from the pits of teaching java concurrency, and is just slowly getting up to speed again.

**Comment by kasperosterbye** [comment]
I have a solution (not sure it is the right one though). I will make a PR sometime tomorrow

**Comment by estebanlm** [comment]
make it to pharo-spec/newtools, please :)
