### ISSUE TITLE
testOpenLog should not let files on disk

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#8377]
**Describe the problem**
SmalltalkImageTest >> #testOpenLog  creates a file (file.log) in the current folder but do not clean it in the teardown or in the test

**Classes involved**
SmalltalkImageTest 

**Proposal**
Delete the file after run

**Version information:**
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1053.sha.563ebe674856edb3e123dfa00961097066506f01 (64 Bit)

**Expected development cost**
5 mins

**Comment by samakhov** [comment]
Clean the log file created on the disk by test #8457 
I delete the file directly in the test. The creation of the file is local to that precise test.
I consider creating a teardown to delete the file can be less readable. We could see a file delete without knowing which test created that file.

**Comment by MarcusDenker** [comment]
PR merged
