### ISSUE TITLE
[Debugger] "Context>>at:" infinite loop when pressing Through in a test case condition

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#8379]
-- Maybe duplicate of https://github.com/pharo-project/pharo/issues/8146 --
**Describe the bug**
Debugger crash see below

**To Reproduce**
1. Execute:
`ReNoPrintStringInPrintOnRuleTest  compile: 'testHalt self halt'.`
2. Execute
`ReNoPrintStringInPrintOnRuleTest buildSuite run`
3. In the debugger scroll in the stack to the frame right after the "Undefined Object  >> Doit" which is "TestSuite >> run".
4. Click on 'Through'
5. Enjoy the firework in PharoDebug.log  [PharoDebug-1.log](https://github.com/pharo-project/pharo/files/5826564/PharoDebug-1.log)
6. Press Alt + . to see all the debug windows opening

**Expected behavior**
No 🎆 🎆 🎆 🎆 

**Screenshots**
![m5S9EEY0QM](https://user-images.githubusercontent.com/4706329/104851916-1907b000-58f8-11eb-9cbc-48afc3e1b839.gif)

**Version information:**
Pharo9.0.0
build: 1053, commit: 563ebe6

**Expected development cost**

**Additional context**

**Comment by tesonep** [comment]
This issue is related to #2410 #7394
It is a problem in the step-through operation and it is also present in Pharo 8.
I am trying to have a small test to reproduce it.
