### ISSUE TITLE
Source code copying is confused by the doc expressions

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#8405]
**Bug description**
Source code copying is confused by the doc expressions. When you copy a whole line that contains it, like: 
```smalltalk
	"true not >>> false"
```
only the text without quotes is put into the clipboard. 

![idEK4BSkR6](https://user-images.githubusercontent.com/572494/105505860-bc2a4200-5cc9-11eb-8eed-d66b11089136.gif)

**Comment by pavel-krivanek** [comment]
For the last expression, it behaves normally (which is strange)

**Comment by Ducasse** [comment]
I cannot reproduce it in 
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1058.sha.e401ee6361b964d021bd7dd3aee55fab26e9029f (64 Bit)

I tried with shortcut and with menus.

**Comment by pavel-krivanek** [comment]
I tried the very latest Pharo and I can still reproduce it. 

It is on Windows 10 (so differences in clipboard processing are not unfeasible).

Pharo 9.0.0
Build information: Pharo-9.0.0+build.1070.sha.7d2ee8b6f39454528b60c56589965741328f851d (64 Bit)

**Comment by guillep** [comment]
I've reproduced it. It happens when the selection spans to the next line (as in the screenshot).
If the selection does arrive only at the end of the line, it works!

I'm checking it
