### ISSUE TITLE
[VM][Crash] Pharo random crashes when using parallel testing framework

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#8406]
**Describe the bug**
(Follow up of  but in another reproduceable context).

When testing the testWorker framework of Pablo (https://github.com/tesonep/pharo-testWorkers) on a Vanilla Pharo image, I had some image crashes happening of the same kind of https://github.com/pharo-project/pharo/issues/7401 but not with our code loaded.

I suspect some memory corruption since the crash is not constant. Also, I also got a BSOD right after.

Another point is that the "getVMGMTOffset" method seems to be linked to the failure but it is just a getter method.

[crash-1.dmp.txt](https://github.com/pharo-project/pharo/files/5857276/crash-1.dmp.txt)
[crash-2.dmp.txt](https://github.com/pharo-project/pharo/files/5857277/crash-2.dmp.txt)
[crash-3.dmp.txt](https://github.com/pharo-project/pharo/files/5857278/crash-3.dmp.txt)
[crash-4.dmp.txt](https://github.com/pharo-project/pharo/files/5857279/crash-4.dmp.txt)
[crash-5.dmp.txt](https://github.com/pharo-project/pharo/files/5857280/crash-5.dmp.txt)
[pharoCrashWindows.zip](https://github.com/pharo-project/pharo/files/5857373/pharoCrashWindows.zip)

Some extracts:
> EXCEPTION_ACCESS_VIOLATION(-1073741819) at 0x000000006fb65b47 - 2021-01-18 01:23:35.815
> EXCEPTION_BREAKPOINT(-2147483645) at 0x000000007013e75b - 2021-01-18 00:35:55.251
> C Callstack:
> [0x000000007013E75B] not a method[0x0000000000000800] not a method[0x000000000000092C] not a method[0x000000000075FC60] not a method[0x000000006FB5E154] getVMGMTOffset
> [0x000000006FB4D1BC] getVMGMTOffset
> [0x0000000000758960] not a method[0x00000000700EB2E2]         0x700eb1e0 <->         0x700eb2f8: method:         0x732fbc18 selector:         0x71b796d8 referencesOf:do:
> [0x000000007143B010] not a method[0x0000000070EF99C0] not a method[0x0000000070EF7B30] not a method[0x000000007143AF58] not a method[0x00000000700EB1E1]         0x700eb1e0 <->         0x700eb2f8: method:         0x732fbc18 selector:         0x71b796d8 referencesOf:do:

We also have some crash with the lifeware code installed: no crash.dmp generated but there is some errors in the Windows event log.

**To Reproduce**
1. Install https://github.com/tesonep/pharo-testWorkers
2. Set up Rabbit mq so the testWorkers can work correctly.
3. Execute this:
```
watchdog := TWWatchdog new
		rootDirectory: 'tmp' asFileReference;
		useCreationStrategy: TWCurrentPharoCommitCreationStrategy ;
		numberOfInstances: 15;
		yourself.
		
watchdog start.
	
(TWWatchdogPresenter on: watchdog)
	openWithSpec.
watchdog startInstances.
```

4. Then this:
```
packages := RPackageOrganizer default packages.
	conf := DTPluginConfiguration
		items:
			(packages
				flatCollect:
					[ :p | p definedClasses select: [ :c | c allSuperclasses includes: TestCase ] ])
		packages:packages.
	plugin := TWRemoteTests . 
	drTest := DrTests on:(Array with: plugin).
	drTest openWithSpec.
	(drTest runPluginFor: conf).
```
5. If no crash seen: Clean the generated folders and goto 3.
6. Please add a comment if you can reproduce :)

**Expected behavior**
No crash

**Version information:**
Pharo9.0.0
build: 1053, commit: 563ebe6

**Expected development cost**
High

**Additional context**
App Crash dumps are available on demand for rmod team

**Comment by Ducasse** [comment]
Thanks thanks thanks vincent.
