### ISSUE TITLE
Update Pharo 9 with Roassal 0.9.6

### ISSUE THREAD

**Issue by bergel** [guillep/pharo-core#8407]
We have produced a new release of Pharo 0.9.6, with essentially some improvement related to documentation and cleaning. It should be easy to review this change

**Comment by Ducasse** [comment]
Ok thanks. We will have a look.
Did you introduce a setting to be able to disable the UML view because I know people that find it useless.

**Comment by bergel** [comment]
Yes, it has and uses setting to enable or disable the UML view
