### ISSUE TITLE
Wrong receiver when running code (P8)

### ISSUE THREAD

**Issue by hogoww** [guillep/pharo-core#8411]
Pharo 8

**Describe the bug**
Wrong receiver when running code.
The first message returns a Set.
The message send to this Set is actually send to the receiver of the first message.
(see screenshot)

**To Reproduce**
I have no idea :/

**Expected behavior**
That the right receiver is used.

**Screenshots**
![image](https://user-images.githubusercontent.com/21278554/105571910-f8a28000-5d53-11eb-9532-3d59908f6da4.png)

**Version information:**
 - OS: Ubuntu 16.04 LTS 64 bits
Latest Pharo 8 (Build information: Pharo-8.0.0+build.1124.sha.0932da82f08175e906b0e2a8052120c823374e9f (64 Bit))
Tested in both Headless & regular VM.

**Expected development cost**
No idea

**Additional context**
Happened post merge, with 2 big different projects that are not loaded at the same time.
Code works fine in doIt.
Recompiling it in the debugger seems to fix *this* execution (50+ executions after recompilation).
Fails with the same bug when restarting a "new" execution from the playground.

**Comment by Ducasse** [comment]
There was a huge amount of time and dev in P9 so I do not think that we will check this bug.

**Comment by hogoww** [comment]
Agreed, I was mostly reporting it in case other people encounter this.
Plus, I don't even have a reproducible case..
