### ISSUE TITLE
ToolRegistry creates a weak subscription with a BlockClosure

### ISSUE THREAD

**Issue by syrel** [guillep/pharo-core#8415]
https://github.com/pharo-project/pharo/blob/7d2ee8b6f39454528b60c56589965741328f851d/src/Tool-Registry/ToolRegistry.class.st#L243

**Comment by syrel** [comment]
The only in-image sender of the method is in `WorldMorph>>#initialize`:
```
WorldMorph>>#initialize 
	worldState := WorldState new.
 	super initialize.

	SystemAnnouncer uniqueInstance weak when: FullscreenAnnouncement send: #fullscreenChanged: to: self.	
	
	"subscribe to the tools registry to update the world menu when needed"
	Smalltalk tools whenToolRegistered: [ :tool :toolName | WorldState defaultWorldMenu ].
	Smalltalk tools whenToolUnregistered: [ :tool :toolName | WorldState defaultWorldMenu ].
```
It is not clear what `WorldState defaultWorldMenu` does as it just sets some class variables:
```
WorldState>>#defaultWorldMenu
	self desktopMenuTitle: 'World'.
	self desktopMenuPragmaKeyword: 'worldMenu'.
```

Maybe they should be removed all together?

**Comment by MarcusDenker** [comment]
yes, it looks like this is not needed: it just sets a class var to it's default value, there is no reset done

**Comment by MarcusDenker** [comment]
I added a PR yesterday. The PR can only be merged after it gets reviewed.
