### ISSUE TITLE
Roassal: classes with unused ivas

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#8424]
**Describe the problem**
Roassal has some classes with ivars that are not referenced:

RSAbstractContext
RSAbstractContainerBuilder
RSAbstractFlowLayout
RSAbstractLineLayout

**Comment by MarcusDenker** [comment]
Fixing this is a step for issue #8189

**Comment by astares** [comment]
Related to an issue I already opened on https://github.com/ObjectProfile/Roassal3/issues/329

**Comment by akevalion** [comment]
I have removed unused ivars. We will create a new release with these fixes
