### ISSUE TITLE
Headless VM latest crashes when class methods are selected in Pharo 9

### ISSUE THREAD

**Issue by voxkmp** [guillep/pharo-core#8435]
I get an illegal instruction VM crash when trying to use the latest headless VM to view class side methods.

I download the image and VM like this -

curl https://get.pharo.org/64/90+vmHeadlessLatest | bash

I open the image with ./pharo-ui Pharo.image

I open a system browser and pick a class

I click to view class side methods and crash!

I'm using Xubuntu 20.04.

I've tried this on two computers both running Xubuntu 20.04. Same thing.

It's perhaps no coincidence that I get an illegal instruction crash if I try to load the pharo GTK bindings.

Does this mean that the headless VM has a serious problem with some chip sets?

Crash file attached - 
[crash.txt](https://github.com/pharo-project/pharo/files/5882006/crash.txt)

**Comment by Ducasse** [comment]
Thanks for the report. 
What is the image you are using? 
In fact this is more complex than that. 
We should release new version of the vm because one some linuxes (because there is no such thing as one linux)
the TFFI and VM should be updated.

**Comment by voxkmp** [comment]
Now fixed in latest headless and Pharo 9

home/kmp/Documents/Technical/Pharo/mars6000/Pharo.image
Pharo9.0.0
Build information: Pharo-9.0.0+build.1379.sha.41c784432d862fe44618f04ac8a6ab502e737df3 (64 Bit)
Unnamed

Virtual Machine
/home/kmp/Documents/Technical/Pharo/mars6000/pharo-vm/lib/pharo
CoInterpreter VMMaker-tonel.1 uuid: 286e9806-8e7d-0d00-ab06-4e280faf8631 Apr 30 2021
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 286e9806-8e7d-0d00-ab06-4e280faf8631 Apr 30 2021
5125110 - Commit: 5125110 - Date: 2021-04-30 10:05:04 +0200

Pharo 9.0.0 built on Apr 30 2021 10:22:47 Compiler: 5.4.0 20160609
VMMaker versionString 5125110 - Commit: 5125110 - Date: 2021-04-30 10:05:04 +0200
CoInterpreter VMMaker-tonel.1 uuid: 286e9806-8e7d-0d00-ab06-4e280faf8631 Apr 30 2021
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 286e9806-8e7d-0d00-ab06-4e280faf8631 Apr 30 2021
