### ISSUE TITLE
P9 Seaside Control Panel throws walkback

### ISSUE THREAD

**Issue by sanjayminni** [guillep/pharo-core#8439]
Running Menu->Tools->Seaside control panel throws a walkbak in P9, works fine in P8 

![p9SeasideControlPanelErr](https://user-images.githubusercontent.com/12030766/106231286-597bfd80-6217-11eb-9006-7e658707d04c.jpg)

**Comment by svenvc** [comment]
The control panel itself (its code) is part of Seaside, so it will have to be fixed there (eventually).

Other than that, this looks like an issue with the transition from SPEC1 to SPEC2, but I would not known how to fix it.

**Comment by astares** [comment]
The panel was already adopted for Pharo 9 and Spec 2 and worked a month ago. I guess a new spec2 version was integrated 
with further changes that broke the panel again.

You should open a ticket on https://github.com/SeasideSt/Seaside nonetheless as this is a problem of Seaside and not Pharo itself.

<blockquote><img src="https://avatars.githubusercontent.com/u/8545049?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/SeasideSt/Seaside">SeasideSt/Seaside</a></strong></div><div>The framework for developing sophisticated web applications in Smalltalk. - SeasideSt/Seaside</div></blockquote>

**Comment by astares** [comment]
For me this works perfectly and without a problem. 

Might be a bad setup of @sanjayminni  at the moment similar to what he reported yesterday in [https://github.com/astares/Seaside-Bootstrap4/issues/7](https://github.com/astares/Seaside-Bootstrap4/issues/7)

@MarcusDenker 
As this is not a Pharo issue, seems to be working and is about Seaside we should close this one here.
