### ISSUE TITLE
Crash on step over

### ISSUE THREAD

**Issue by Alisu** [guillep/pharo-core#8443]
**Describe the bug**
The image froze on some step over.

**To Reproduce**
1. Open an image
2. Open a playground
3. Type [ 'pouet'. [ ^42 ] value ] ensure: [ ^ 'popouet' ] in the playground
4. Now step over, step over, step into, step over, step over, step over and image is frozen.

**Expected behavior**
Image does not froze.

**Version information:**
 - OS: OSX mojave
On Pharo 9 and Pharo 8

Additionnal:

It looks like an infinite debugger opening loop.

**Comment by Alisu** [comment]
It looks like the same.
Another way to reproduce:
-Open an image
-Open a playground
-Type [ 'pouet'. [ ^42 ] value ] ensure: [ ^ 'popouet' ] in the playground
-Step over, over, into, into, into, into, over

**Comment by StevenCostiou** [comment]
Thanks for the report Théo!
I will have a look next week.

**Comment by Ducasse** [comment]
I hope that this is not another one of the instruction stream bugs.

**Comment by StevenCostiou** [comment]
The stack (thousands of them) from the log, it does not go deeper.

```
Context>>cannotReturn:
	Receiver: Process>>doTerminationFromYourself
	Arguments and temporary variables: 
		result: 	a Process in ni
	Receiver's instance variables: 
		sender: 	nil
		pc: 	nil
		stackp: 	1
		method: 	Process>>#doTerminationFromYourself
		closureOrNil: 	nil
		receiver: 	a Process in nil


Process>>doTerminationFromYourself
	Receiver: a Process in nil
	Arguments and temporary variables: 

	Receiver's instance variables: 
		nextLink: 	nil
		suspendedContext: 	nil
		priority: 	40
		myList: 	nil
		name: 	nil
		env: 	nil
		effectiveProcess: 	nil
		terminating: 	true
		level: 	nil
```
It is obvious it cannot return, but it should not loop like that.
Started investigating, @Alisu any idea what it could be?

**Comment by StevenCostiou** [comment]
So what I did:
- I disabled all debuggers
- I cut the Oups entry point to log to the Transcript instead of doing anything like trying to open debuggers
This example still hangs with the same stack. So it's at the level of the interpreter and not the debugger infrastructure.
More: the debugger infrastructure can do nothing about it, it is never sollicitated in that execution (if I did not miss anything).

**Comment by StevenCostiou** [comment]
Because it was too easy: I stepped the `stepOver` to find where the hanging starts.
It does not hang :)
It hangs if I step over `interruptedProcess completeStep: aContext` but if I step in until the end there is no hanging.
See the code where I step over below:

![Screenshot 2021-02-03 at 09 53 15](https://user-images.githubusercontent.com/26929529/106721944-a55ae800-6605-11eb-8574-d35c6d85b79b.png)

**Comment by StevenCostiou** [comment]
More specifically, it hangs when executing this jump in `runUntilErrorOrReturnFrom: aSender`:

![Screenshot 2021-02-03 at 10 06 08](https://user-images.githubusercontent.com/26929529/106723487-72195880-6607-11eb-8f29-4c5a5084acd2.png)

**Comment by StevenCostiou** [comment]
Well actually, stepping in the jump seems to work until we get there: a step over that freezes. 
I will investigate again the debugger lead because I want to be sure it does not come from there.
![Screenshot 2021-02-03 at 10 17 43](https://user-images.githubusercontent.com/26929529/106724907-10f28480-6609-11eb-9e39-5edf2ec4d183.png)

**Comment by StevenCostiou** [comment]
And it is still the same stack:

```
Context>>cannotReturn:
Process>>doTerminationFromYourself
```

@guillep @tesonep the cannot return is not called from the VM right? All that is in the simulator?
I fail to get there by stepping the execution.

**Comment by StevenCostiou** [comment]
I do not get why stepping over would freeze the image with that stack while stepping in finishes the execution to its end.

**Comment by StevenCostiou** [comment]
I will come back to that later this week or next week.

**Comment by Alisu** [comment]
From what you show in your messages.
We are stepping an unwind protect and the ```Process>>doTerminationFromYourself``` try to unwind too (and certainly fails).
Thus I did not check yet but the vm sends a cannotReturn. From there we have different possibilities that I did not check:

-The blockClosure at the context field contains something else than a context.
-The unwind don't find the home context.
-The homeContext frame is dead.

edit: The Context>>cannotReturn should not fail.

**Comment by dionisiydk** [comment]
It's old bug. I get same freeze on Pharo 7. 
So it is not related to any Debugger changes

**Comment by dionisiydk** [comment]
So I found the fix. The bug is in the context return simulation: when a return is executed from an unwind block (critical:, curtail: arguments):
```Smalltalk
Context>>return: value from: aSender 
	"For simulation.  Roll back self to aSender and return value from it.  Execute any unwind blocks on the way.  ASSUMES aSender is a sender of self"

	| newTop context |
	aSender isDead ifTrue: [
		^ self send: #cannotReturn: to: self with: {value} super: false ].
	newTop := aSender sender.
	context := self findNextUnwindContextUpTo: newTop.
	(context notNil and: [ context unwindBlock = closureOrNil ]) ifTrue: [ 
		"Here the return happens inside the unwind block like in following example: 
			[ #test ] ensure: [ ^ #returnFromUnwindBlock ] 
		In such cases #findNextUnwindContextUpTo: returns the corresponding #ensure context 
		because it is always a sender of unwind block.
		Here we detect this case and lookup the next unwind context after the current ensure section (current unwind)"
		context := context findNextUnwindContextUpTo: newTop ].
	context ifNotNil: [
			^ self send: #aboutToReturn:through: to: self with: {value. context} super: false ].
	self releaseTo: newTop.
	newTop ifNotNil: [ newTop push: value ].
	^ newTop
```
See the comment inside **(context notNil and: [ context unwindBlock = closureOrNil ]) ifTrue:**
