### ISSUE TITLE
Interval >> rangeIncludes: should be private and have a better comment

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#8444]
**Describe the bug**

`Interval >> rangeIncludes:` checks only if the number is withing the upper and lower bounds of the interval.
However, in the presence of a step, this is not enough to check inclusion.
And there are many users in the image of this method, that we should review.

For example, the following expressions are true:
```
(1 to: 10 by: 2) rangeIncludes: 4.
(10 to: 1 by: -2) rangeIncludes: 3.
```

In some places rangeIncludes is used seemingly as an optimization when you know that the interval will have step = 1 or -1.
That should be **at least** properly documented in the method and the users.

Also, current tests are not testing the cases above.

**Comment by cdlm** [comment]
Why is it not `includes:` ?
