### ISSUE TITLE
Implement a rule that #printOn: messages should not use printString

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#8469]
see  https://github.com/pharo-project/pharo/issues/4856

**Comment by MarcusDenker** [comment]
There is ReNoPrintStringInPrintOnRule

**Comment by astares** [comment]
![image](https://user-images.githubusercontent.com/5980033/106482056-5d28b200-64ad-11eb-9d60-dcf6b8206752.png)


Ah ... OK. Then we can close this one.

**Comment by kasperosterbye** [comment]
Perhaps the error message should contain "(use aStream print: anObject instead)". As I went through issue #4856 almost all could be fixed that way, and I believe I am not the only one who overlooks that streams has a `print:` method.
