### ISSUE TITLE
Has KMCategoryTarget been superseded by KMCategoryBinding?

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#8485]
KMCategoryTarget looks like a previous version of KMCategoryBinding which is no longer used (no references to the class). 
I believe KMCategoryTarget was copied from KMCategoryTarget.

**Comment by kasperosterbye** [comment]
Still present - They have not been touched for four years. I just do not know how to mark `KMCategoryTarget` as obsolete.

**Comment by MarcusDenker** [comment]
For now we do:
-> Move the class to deprecated package
-> implement #isDeprecated on the class side (not really needed, as the package is deprecated already)
-> if API classes, try to deprecate the API so people get an error message so they can fix their code (not needed here)

I made a PR
