### ISSUE TITLE
Sorting of variables in the Inspector confuses items selection

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#8490]
**Describe the bug**
If you sort variables in the Inspector by name and then click on some of them, it shows the item that was located at that position before sorting. It is probably related to the table so I do not report it to the NewTools repository.

**To Reproduce**
1. Inspect `Object`˛ (the class)
2. click on `category` inst. var. - it shows `Kernel-Objects` string in the right pane
3. click on table column header _Variable_ to sort the instance variables
4. click on `superclass` inst. var. - it shows `Kernel-Objects` string
5. the other variabless are wrong as well

**Version information:**
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1097.sha.df32f2328fdb5ed9ba59abb598b82b22427a6f23 (64 Bit)

**Comment by estebanlm** [comment]
yes, this is fixed upstream
