### ISSUE TITLE
Slot remove in Stateful Traits

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#8503]
**Describe the bug**
instance variable removal ( -- ), see TaRemoveSlot needs a test an fix

**Comment by SimonXHolland** [comment]
Hi Marcus 
As far as I can see, composed classes that use anything other than simple + will not file in.

**Comment by SimonXHolland** [comment]
I could be wrong - it could be that I am misunderstanding other possible bugs in the development image

**Comment by SimonXHolland** [comment]
Apologies - I am wrong - it seems to work if you file them in one at a time - I'm not sure why they didn't file in as part of a package, but I don't have clear unambiguous evidence of a bug, so please ignore

**Comment by SimonXHolland** [comment]
AH! perhaps you need to file in the traits before the classes? Sorry I will stop making an unnecessary  mess in the bug reports & go away & investigate

**Comment by SimonXHolland** [comment]
False alarm! It was finger trouble in typing package names. I hang my head in shame.

**Comment by MarcusDenker** [comment]
The PR does:
- add tests for deletion of slots from a Trait: #testChangingDeleteSlot and #testChangingDeleteSlot2Slots
- TaRemoveSlot: change TaRemoveSlot to use a collection of vars to delete from the Trait (as it can define multiple slots)
- add CDTraitSlotRemoveNode to make the classparser work

This now works:

```
Trait named: #MyTrait
	instanceVariableNames: 'ivar'
	package: 'ForTesting'
```

we can now use it in a class but remove the traits ivar:


```
Object subclass: #MyClass
	uses: MyTrait -- {#ivar}
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'ForTesting'
```

If we ask MyClass which slots it defines, we get:

```
MyClass slots 

	--> "#()"
```

**Comment by MarcusDenker** [comment]
I updated the PR:
- I added back support for "uses: MyTrait -- #ivar", that is, if you delete one ivar, it does not need to be specified as an array
- added a test where the same var is added by the class that was deleted from the trait: testChangingDeleteSlotAddVar
- added a test for deleting from one Trait and rename from another: testChangingDeleteSlotAndAlias
