### ISSUE TITLE
Renaming should let me decide....

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8513]
Imagine that you have two classes with method foo

When you do rename foo -> bar
The system says there are two implementors yes/no
if you say no

then you are stuck.
It would be interesting to have scoped rename that ask you the scope (package that should be impacted
by your refactoring). 

I can do it work in with scope package. 
But it would be good to have it as a menu item.

**Comment by fxgallego** [comment]
Hi guys, I can't believe how far you have got without this 😄 

Here is an example of Dolphin Smalltalk
![image](https://user-images.githubusercontent.com/2080171/108545932-2fbe6f80-72c7-11eb-8b3d-cb2fd9e28550.png)

**Comment by Ducasse** [comment]
You know only half of the story :) Indeed we are missing some of these but this is not at the implementation level.
Did you see the scoped button or the fact that we can do it via the setup scope menu? I do not like the way it is proposed to the user. In the past we could select image, hierarchy or a single package but it was always something that did not work.

**Comment by Ducasse** [comment]
You see to me often I want a refactoring scoped to two set of packages. 
Or a hierarchy. Never to a single method. 
But it means that we should revisit how this is exposed to the users because we need to support

PackageS
Classes
Hierarchy
Potentially methods. 
And the point is that it should be easy and fast to select them.

Evelyn esteban have been developed some widgets for the selection of classes, packages using tick and not just a selection because you do not want to have to press command on I do not know which keys to select all kind of patterns. 
So this is important that we invest in having a good set of customizable selection widgets for all kinds of scope. @estebanlm Did you push such widgets in Pharo or Evelyn should look at them in NewTools-Dependency analysis.

**Comment by fxgallego** [comment]
>Did you see the scoped button or the fact that we can do it via the setup scope menu?

I didn't see any button/select to do this in Pharo? There is one hidden or I misunderstood you?
I know that at the implementation level the Refactoring Browser has a scope or at least the RB that I know.

**Comment by Ducasse** [comment]
I think that we removed the image/single package (or I cannot find it anymore) I use scope view all the time because I want to apply a refactoring only my code and often I have Pillar + Microdown and they are 6 packages with different names. 

![Screenshot 2021-02-19 at 23 09 03](https://user-images.githubusercontent.com/432549/108566958-93688d00-7307-11eb-8260-5cfd0fcddc78.png)
![Screenshot 2021-02-19 at 23 08 49](https://user-images.githubusercontent.com/432549/108566959-94012380-7307-11eb-8ee1-1b01cddc893d.png)
![Screenshot 2021-02-19 at 23 08 59](https://user-images.githubusercontent.com/432549/108566961-9499ba00-7307-11eb-903e-ed45735843cf.png)

**Comment by fxgallego** [comment]
I see, not very intuitive the fact that I need to set the scope before trying to do the refactoring. It worked but no more options than packages.

**Comment by Ducasse** [comment]
It depends how you work. I like to work with a scope view upfront. 

Now this is not by accident that Evelyn is working on improving refactorings or that I open this issue.  This is because we know that the UI part got never good and we rewrote two full code browser in around 8 years and the refactorings integration was never that good in the details. So Evelyn is working and she has one year to improve the situation. So this is good.

**Comment by Ducasse** [comment]
We have the options to scope but they are totally obscure to me and I could never use them. I never understood why denis place them in the message browser. May be this is what you are looking for but I could never work with them.

**Comment by Ducasse** [comment]
![Uploading Screenshot 2021-02-19 at 23.34.40.png…]()

**Comment by Ducasse** [comment]
![Screenshot 2021-02-19 at 23 34 40](https://user-images.githubusercontent.com/432549/108568883-2eaf3180-730b-11eb-8f54-266a9c223fc3.png)
