### ISSUE TITLE
Version Browser DNU: on revert when you select "source" in the dropdown menu

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8514]
I'm fed up this is 10 times that I report it and also fix it. 
When can we get rid of the revert bug?

![Screenshot 2021-02-05 at 09 35 56](https://user-images.githubusercontent.com/432549/107009740-ba668100-6795-11eb-8c8c-db9ae0871bcf.png)

**Comment by Ducasse** [comment]
Is it fixed in new tools?
When can we get a new version?

**Comment by estebanlm** [comment]
that was fixed and in image, I do not understand why is again there.

**Comment by MarcusDenker** [comment]
The strange thing is that it works for me in the latest image

**Comment by MarcusDenker** [comment]
This only happens when you select "source" in the dropdown menu. I never do that.

**Comment by MarcusDenker** [comment]
See https://github.com/pharo-project/pharo/issues/6699

I close the other as a duplicate

**Comment by MarcusDenker** [comment]
I added a better title for the issue (so that it is directly clear what the problem is)

**Comment by MarcusDenker** [comment]
This has been fixed with merging https://github.com/pharo-project/pharo/pull/8589
