### ISSUE TITLE
Process>>#priority: allows lower priority process run while higher priority one scheduled

### ISSUE THREAD

**Issue by isCzech** [guillep/pharo-core#8524]
In the following example a higher priority process keeps waiting in the ProcessorScheduler queue until a lower priority process gets suspended!
```
Transcript flush; cr.
Processor activeProcess priority: 42.
[ Transcript nextPut: $A ] forkAt: 41.
Processor activeProcess priority: 40.
Transcript nextPut: $B; flush.
500 factorial.
Transcript nextPut: $C; flush.
500 factorial.
Transcript nextPut: $D; flush.
10 milliSeconds wait.   "suspends the active process"
Transcript nextPut: $E; flush.
```
Answers:

BCDAE
BCDAE
BCADE
BCDAE
BCDAE
BACDE
BCDAE
(A never appears before B; interrupts may change the order of C, D and A which is expected)

Reason: the `#priority:` method won't make sure the active process doesn't jump over a scheduled process when lowering it's priority - as a result the active process will continue running until it suspends and won't let the higher priority process a chance to run.

Current implementation:
```
priority: anInteger
	"Set the receiver's priority to anInteger."

	(anInteger between: Processor lowestPriority and: Processor highestPriority)
		ifTrue: [ priority := anInteger ]
		ifFalse: [ self error: 'Invalid priority: ' , anInteger printString ]
```
Proposed solution:
```
priority: anInteger
	"Set the receiver's priority to anInteger."

	(anInteger between: Processor lowestPriority and: Processor highestPriority)
		ifTrue: [
			priority := anInteger.
			(self isActiveProcess and: [anInteger < Processor nextReadyProcess priority])
				ifTrue: [ [self resume] fork. self suspend ] ]
		ifFalse: [ self error: 'Invalid priority: ' , anInteger printString ]
```
The problem with this solution is the #nextReadyProcess may get interrupted in the middle which may make it's answer usless. So I guess either this whole method should run as a primitive or in the interim, always force the active process suspend momentarily to let ProcessorScheduler do the job:
```
priority: anInteger
	"Set the receiver's priority to anInteger."

	(anInteger between: Processor lowestPriority and: Processor highestPriority)
		ifTrue: [
			priority := anInteger.
			self isActiveProcess ifTrue: [ [self resume] fork. self suspend ] ]
		ifFalse: [ self error: 'Invalid priority: ' , anInteger printString ]
```

Impact: at least two methods use this type of priority switching: #valueUnpreemptively and #valueAt: and their behavior is impacted the same way; #valueUnpreemptively already uses a workaround that suspends the active process momentarily and for #valueAt I issued a PR #8522  to apply a similar workaround. However the fact remains the `#priority:`'s behavior is flawed and may introduce unintended effects.

Note: preempting the active process rather than suspending would be more appropriate but at the moment I'm not sure how that could be achieved easily.

Build information: Pharo-9.0.0+build.1110.sha.cea57d5a282796e03048cfdeaa851c99b8ee6c52 (64 Bit)

Related to Issue #8491

**Comment by Ducasse** [comment]
Hi Ben 
Could you have a look when you have time?
Tx

**Comment by isCzech** [comment]
I should have included a simple test, sorry:
```
ProcessTest >> testPriority

	| val oldPriority |
	val := 0.
	oldPriority := Processor activePriority.
	Processor activeProcess priority: oldPriority + 2.
	[ val := 1 ] forkAt: oldPriority + 1.
	Processor activeProcess priority: oldPriority.

	self assert: val equals: 1
```
Shall I update or issue as separate PR - pls advise, thanks!

Best,
Jaromir

**Comment by isCzech** [comment]
There's a fundamental question how a process coming down from a higher priority should be treated:

(A) as a 'regular' process trying to run at a given priority - i.e. send it to the back of the queue
(B) as a sort of 'privileged' process deserving the front of the queue, as if previously 'preempted' by itself

Now, as I can see only two usage examples - #valueUnpreemptively and #valueAt, the question is how are these two supposed to work ideally? At the moment they behave like (A) and the solution in this PR preserves this behavior.

However, I wouldn't rule out behavior (B) because it would provide a nice choice based on #processPreemptionYields setting:
- for `true` (default) the active process would yield and go to the end of the queue and 
- for `false` the active process wouldn't yield and "stay" at the front of the queue.

For this scenario `[self resume] fork. self suspend` would only be replaced by e.g. `[ ] forkAt: Processor highestPriority`

Here's a test for this type of `#priority` behavior:
```
testPriority2
	"test whether #priority: preempts active process to allow higher priority processes run;
	#priority behavior reflects the processPreemptionYields setting - for false the active 
	process gets to the front of the queue while for true (default) it goes to the end"

	| val oldPriority |
	val := nil.
	oldPriority := Processor activePriority.
	Processor activeProcess priority: oldPriority + 2.
	[ val := false ] forkAt: oldPriority + 1.
	[ val := true ] forkAt: oldPriority.
	Processor activeProcess priority: oldPriority.
	
	self assert: val equals: Smalltalk vm processPreemptionYields
```

**Comment by isCzech** [comment]
Hi Ben,

I was wondering if you had a chance to take a look at the issue. I discussed the same issue with Eliot and Levente (Squeak suffers the same problem) and it seems the best solution might be a new #priority primitive, however I'd very much like to know your opinion whether the interim solution I'm proposing is viable and most of all what the desired semantics of **decreasing** a priority on-the-fly should actually be - (A) sending the active process to the back of its new priority queue, (B) granting it the front of the queue or, what I'd like to suggest, to respect the #processPreemptionYields setting - i.e. behave like (A) for true and like (B) for false.

I appreciate your time and look forward to hearing from you.

Best regards,

Jaromir

**Comment by guillep** [comment]
Hi @isCzech , thanks for the issue and the PR, and sorry for the delay. We are taking a look at this right now.
We will probably issue a new PR updated for the latest branch and using as a base the tests you proposed in the comments too.
