### ISSUE TITLE
Errors : Insufficient buffer size to read current working directory, at the launch of a new image, with 'not supported yet. and ever' StrikeFont error.

### ISSUE THREAD

**Issue by labordep** [guillep/pharo-core#8525]
I create a new Pharo 9 image with the launcher (Pharo 9.0 - 64bit (development version, latest)). 
When I start the freshly created image with the play button I have two errors 'Insufficient buffer size to read current working directory' (See my gif to check the problem).
I'm on Windows 10 Pro x64 version 19042.746.

When I close these errors and I navigate in the browser, I have rapidly a new StrikeFont>>asFreetypeFont error called 'not supported yet. and ever' (See my gif to check the problem).

**Screenshots**
![image](https://user-images.githubusercontent.com/49183340/107118509-d47d8d80-6881-11eb-9cf4-cc556a5620a0.png)
![image](https://user-images.githubusercontent.com/49183340/107118526-e7905d80-6881-11eb-8bc6-45f975450f07.png)
![image](https://user-images.githubusercontent.com/49183340/107118543-f840d380-6881-11eb-84f8-6350737cb0ed.png)

** Video (gif) **
![PharoError](https://user-images.githubusercontent.com/49183340/107118608-3d650580-6882-11eb-9481-67169ab68b8a.gif)

**Version information:**
 - OS: Windows 10 Pro x64 version 19042.746.
 - Version: Pharo-9.0.0+build.1110.sha.cea57d5a282796e03048cfdeaa851c99b8ee6c52 (64 Bit)

**Comment by MideAkin** [comment]
Try reducing the length of your image name.

**Comment by labordep** [comment]
Hello,

Thanks for the reply.

Same problem with an image rename « P.image ».

The patch is not very long : C:\Users\xxxxx\Documents\Pharo\images\P\P.image


Pierre
 

De : MideAkin <notifications@github.com> 


Try reducing the length of your image name.

**Comment by Ducasse** [comment]
Thanks pierre we will come back to you with Pablo.

**Comment by labordep** [comment]
Hi all, a little update about this problem : 

- VMs updated today
![image](https://user-images.githubusercontent.com/49183340/111029457-f330f000-83fc-11eb-9635-7a53875eb174.png)

- Pharo Launcher 2.2 already up to date

- Pharo 9 - 664 bits image created today
![image](https://user-images.githubusercontent.com/49183340/111029486-22476180-83fd-11eb-90bf-8580fa36e16f.png)

When I start the image for the first time I have a little message about TFFI Callbacks (I don't know if it's normal) : 
![PharoTFFI](https://user-images.githubusercontent.com/49183340/111029623-f8426f00-83fd-11eb-8a14-b8276df9ad18.gif)

When I navigate to the code with the browser, fonts are alive (they changes :-s), and the font error appears : 
![PharoFonts](https://user-images.githubusercontent.com/49183340/111029739-8fa7c200-83fe-11eb-8e94-a03903a8f1b5.gif)

Here my Pharo font configuration : 
![image](https://user-images.githubusercontent.com/49183340/111029775-c1208d80-83fe-11eb-8fd2-b3812978c0a0.png)

I could try to re-install totaly my pharo environment but I think this is not a good solution to solve the problem, this probleme could be not re-appear right now.

**Comment by labordep** [comment]
Here, the list of my default Font conf and the update action : 
![PharoFontsList](https://user-images.githubusercontent.com/49183340/111030076-b2d37100-8400-11eb-9525-874b450ad087.gif)

**Comment by labordep** [comment]
An update, when I trying to change the font with a system font (in this example Comic Sans Ms font), the problem seems to be resolve :-/
I save and restart the image and the image is ok (but the TFFI error message is already here).
![PharoFontsComics](https://user-images.githubusercontent.com/49183340/111030272-81a77080-8401-11eb-88a8-b2d856255f71.gif)

**Comment by labordep** [comment]
So, it's appear to be have a link between "original Pharo fonts" (I don't know how it works, Pharo have embedded fonts ?) and "system fonts".

**Comment by labordep** [comment]
Unfortunately there is a new similar problem is appear after a few moment (~1hour of coding), that's very interesting.  

Fonts are dirty : my previous settings (I choose Arial font, not Comic font :) ) is overrided with another font (see my gif to see the problem) **in same time of the TFFI message** (at the bottom left) :
![PharoFontsDirty](https://user-images.githubusercontent.com/49183340/111031740-4c9f1c00-8409-11eb-905d-45aac042a3e7.gif)

New font settings (not from me), previously I have Arial font all over :
![image](https://user-images.githubusercontent.com/49183340/111031733-44df7780-8409-11eb-95a1-4a6e5ea6deae.png)

Previous exception is back : 
![image](https://user-images.githubusercontent.com/49183340/111031910-23cb5680-840a-11eb-82bb-4dc9284ea2e5.png)

**Comment by labordep** [comment]
A new problem apper just before the font change problem : some keys on my keyboard no longer work in pharo :-/
See my gif with the Windows virtual keyboard to see the problem : 

![PharoKeyboard](https://user-images.githubusercontent.com/49183340/111032025-b8ce4f80-840a-11eb-8eba-233aeab49762.gif)

No problems outside Pharo (Word ok, Firefox ok, etc.).

**Comment by svenvc** [comment]
Step one would be *NOT* to try to change the font.

The standard fonts, Source Sans & Source Code, should work, see the screenshot (I did switch from small to medium).

![Screenshot 2021-03-13 at 19 31 01](https://user-images.githubusercontent.com/870089/111040356-f050f200-8432-11eb-8cf1-db6889640a21.png)

Make sure that no global preferences are used, these might switch your fonts behind your back.

I am on macOS, not Windows.

**Comment by Ducasse** [comment]
This is super strange. 
Thanks for the report. I saw some strange behavior recently but not at this level.

**Comment by tesonep** [comment]
Hi Pierre, thanks a lot for the report. 
Have you tried with the latest headless VM?
To do so you can change the configuration of the pharo launcher.

- Selecting Edit Configurations:
![image](https://user-images.githubusercontent.com/355455/112125811-1bbaa600-8bc4-11eb-83b3-209e5323407f.png)

- Changing the VM to 90-x64-headless
![image](https://user-images.githubusercontent.com/355455/112125928-3b51ce80-8bc4-11eb-99d6-2852bc083648.png)

- Click on Save and Select

- Now it will execute with the new VM. 

I will check the error in the stable VM.
Thanks a lot.

**Comment by labordep** [comment]
Hi Pablo,
I have try your instructions. 
Now I haven't the TFFI error message but I have already the "font problem" :

![image](https://user-images.githubusercontent.com/49183340/112758443-b8c77580-8fee-11eb-8556-f2c692de9b86.png)

If it's possible for you I can allow you a remote access to my PC (with desktop shared on Discord) to explore that problem and have a better knowledge on my env. !
Thanks!

**Comment by tesonep** [comment]
@labordep I have been checking the GIF. I have found some issues when handling special characters in the path. 
One thing I see from the GIF is that the image is not able to open the source file, I don't know if that is because the same image was launched twice or because there is another error with the paths. 

Can you send me the PharoDebug.log? 

I will see if we can have a work around for this.

**Comment by MarcusDenker** [comment]
PR was merged
