### ISSUE TITLE
RB - Check deprecation refactoring

### ISSUE THREAD

**Issue by Lin777** [guillep/pharo-core#8534]
Check RBDeprecateMethodRefactoring, if all transformations and logic work correctly

**Comment by MarcusDenker** [comment]
What is very important: it should not do too much.

We had a student implementing Deprecate method, but it was trying to change all senders of the method... which is not what you want. It was completely un-usable.

The *only* thing that a "deprecate this method" refactoring should do what you would do if you decrecate a method: It modifies just this one method, adds the call to "self deprecated...".

**Comment by Lin777** [comment]
Wow, I'll check the current implementation to work on that with what you told me
