### ISSUE TITLE
Replace old FileList with Harbour File Browser

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#8536]
I wrote a new File Browser called "Harbour" as a replacement for FileList. 

https://github.com/astares/Pharo-Harbour

Code is MIT. If wished we could bring it into the standard image and throw away the old file list.

![image](https://user-images.githubusercontent.com/5980033/107233871-548f2900-6a23-11eb-9457-afc67c525969.png)

**Comment by Ducasse** [comment]
Yes this is a good idea. 
And I would like to enhance it. 
Now just a question is it on Spec2?

**Comment by Ducasse** [comment]
Torsten may be the best is to do the following: 
clone the project, turn all the classes to follow the same pattern than NewTools 
ie start with st for example. This way we do not break existing users. 

We could package the windows specific code to be in the platform package if this is general enough.

**Comment by astares** [comment]
@Ducasse Its Spec2, yes. Not sure about the patterns.

**Comment by guillep** [comment]
Maybe @estebanlm should be put in the loop, he for sure can tell how this fits into NewTools / Spec2 organization

**Comment by Ducasse** [comment]
Good idea.!

**Comment by hernanmd** [comment]
Closing this issue as the core functionality of the old morphic-based FileList is now ported to Spec 2, and it reused part of the code provided by Harbour.

It is accessible by evaluating:

```smalltalk
StFileSystemPresenter open.
```

Feel free to further discuss and open new issues.
