### ISSUE TITLE
P9 - Problem with copy and paste from Windows to ClassBrowser method panel 

### ISSUE THREAD

**Issue by fxgallego** [guillep/pharo-core#8554]
**Describe the bug**
If I copy text from Windows into the class browser method panel, when the method is saved, a lot of critics shows that there are `lf` characters in the code.

One workaround for this is to format the source code and save the method again but this doesn't take care of the method comment so it is not a definitive solution.

**Also this doesn't happens on P8**

**To Reproduce**
1. Copy some method with several lines from Pharo to Notepad++ for instance
2. Copy back from Notepad++ to Pharo and save the method.

**Expected behavior**
No critics about `lf` should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/2080171/107645379-5d684080-6c57-11eb-8c4f-a352ccd6bb6c.png)

**Version information:**
 - OS: Windows 10
 - Pharo 9

**Comment by Ducasse** [comment]
Thanks we will have a look. 
It means that the copy paste should pay attention to make sure that it is coherent on all platform.

**Comment by Ducasse** [comment]
@tesonep I introduced a new label to follow windows specific issues.

**Comment by astares** [comment]
I've seen the effect when I copy from PR's from GitHub into Pharo (where GitHub contents is based on Unix line ending conventions). One can always **Accept** the method source code and use the "**Format source code**" menu item.
But sometimes formatting the method is not wished - only conversion of linefeeds.

We now should not blindly "autoconvert" the Clipboard contents from Windows line ending conventions - as this could have other bad side effects. Normally as user I would not expect the Clipboard to not being manipulated - so I assume the current behavior is now correct. 

Maybe the way to solve it is:
 - accept the original line ending from the source and 
 - but additionally allow the lint rule to have an "auto fix it" which converts the line ending by removing the line feeds

**Comment by guillep** [comment]
Well, the thing is that the "line ending convention" in the image has nothing to do with windows, mac or linux. Inside the image it has been decided (kind of de-facto) that the standard line ending convention is *cr*, regardless the platform we are on.

This is a case where I'd try to mimic existing tools, see what visual studio code, eclipse, notepad++ or textmate are working for example.

**Comment by MarcusDenker** [comment]
On the mac I have the same problem: every code I paste from an editor has wrong line endings, which means I have to fix every line or have to pretty print the code to fix it.

It used to not be a problem: I was able to use copy and paste on the mac and it just worked.

**Comment by astares** [comment]
Yes - sure there is a convention in the image (CR only) and that's why the rule is lamenting as the copied content (coming from a platform using other convention) does not follow it. So this is not depending on where Pharo is running but where and how the clipped content was created.

    fxgallego wrote: "Expected behavior  No critics about lf should appear."

If we follow what fxgallego requests here, it would mean that Pharo needs to MANIPULATE the clipboard contents when inserting into method pane (and remove the linefeeds to bring it in alignment with the convent ion). 

But sometimes one wants to insert the RAW contents without manipulation (for instance when copy/pasting data with line feeds to a string or other)...

**Comment by fxgallego** [comment]
In P8 works OK.
I would expect WYSIWYG. Sometimes the clipboard has several formats and it's the destination window the responsible to choose the best format. If the RAW copy & paste is a must then you can provide with an alternative paste method, for example, using "Paste special..."

**Comment by Ducasse** [comment]
Indeed :)
There are many things I would expect too. But it takes time. 
I would like to have editor I can decide the encodings and also see the encoding.

**Comment by fxgallego** [comment]
In P8 this works because P8 uses `Clipboard` as default clipboard manager. P9 is using `OSWindowClipboard` and the problem is in `OSWindowClipboard>>clipboardText` method which is defined as

```smalltalk
clipboardText
	^ self worldRenderer clipboardText
```

the solution is as simple as changing the method to

```smalltalk
clipboardText
	^ self worldRenderer clipboardText withInternalLineEndings
```

Also is there the setter `OSWindowClipboard>>clipboardText:`, and it does no replacement but seems Windows is handling the line ending automatically so I would not worry about the setter.

**Comment by guillep** [comment]
I think restoring the previous behaviour (even though we can argue and discuss about it 😄  ) is a good solution for the time being. What do the others think?

**Comment by MarcusDenker** [comment]
yes, I would restore the old behaviour for now.

And I would like to switch to unix line endings in general...

**Comment by astares** [comment]
+1
