### ISSUE TITLE
Ctrl+Shift+End runs Debug it keybinding instead of selecting text

### ISSUE THREAD

**Issue by fxgallego** [guillep/pharo-core#8566]
**Describe the bug**
Pressing `Ctrl+Shift+End` in workspace and method editors in Browsers runs `Debug it` keybinding instead of selecting text from the cursor position to the end (this is the default behavior, at least in Windows).
It's the same in P8 and P9.

**To Reproduce**
1. Try the `Ctrl+Shift+End` combination in a workspace or method editor

**Expected behavior**
`Ctrl+Shift+End` should select text from the cursor position down to the last character in editor.
`Ctrl+Shift+Home` should select text from the cursor position to the beginning of the editor.
`Shift+End` should select text from the cursor position to the end of the line.
`Shift+Home` should select text from the cursor position to the beginning of the line.

**Version information:**
 - OS: Windows 10
 - Version: [e.g. 1.6.1]

**Comment by Ducasse** [comment]
Thanks we will have a look. 
Just to make sure, when you are mentioning End and Home I imagine that you are referring to special keys 
because on some keyboards like mine and most mac keyboards there is no End and Home. We have arrows.
Ctrl+Shift+ <- and -> are working. 
but not 
Ctrl + Shift + upArrow and downArrow are not doing anything. 
Now 
Shift + upArrow is selecting the previous line while keeping the selection and going up
Shift + down is selecting the next line while keeping the selection and going up
Shift + leftArrow/right is just selecting a character.

**Comment by fxgallego** [comment]
Home/End or Inicio/Fin in spanish are special keys but present in all PC keyboards.
If I open Text app in OSX it is the same behavior you have with `Shit+Cmd+UpArrow` and `Shit+Cmd+DownArrow`. In Pharo in OSX this combination does nothing.

**Comment by Ducasse** [comment]
Thanks. We are busy fighting bugs in Clang :( and they are not fun (when valid VM C code generates ud2 = undefined and crash even the dissambler...). :(

**Comment by fxgallego** [comment]
The problem seems to be in `RubSmalltalkEditor class>>buildPatchShortcutsForDoItInWindowsOn:` which is defined as:
```smalltalk
buildPatchShortcutsForDoItInWindowsOn: aBuilder
	"this is because for some reason Ctrl+d means Ctrl+end on Windows"
	<keymap>
	(aBuilder shortcut: #doItPatchForWindows) 
		category: RubSmalltalkEditor name
		default: Character end ctrl win
		do: [ :target | target editor doIt: nil ]
		description: 'Do it'.
	
	(aBuilder shortcut: #debugItPatchForWindows) 
		category: RubSmalltalkEditor name
		default: Character end shift ctrl win
		do: [ :target | target editor debugIt: nil ]
		description: 'Debug it'
```

The last shortcut, `#debugItPatchForWindows`, overrides the Windows `Ctrl+Shift+End` default behavior. If you remove that shortcut definition, reset the keybindings, save the image and restart then `Ctrl+Shift+End` works flawlessly.
Also `Ctrl-D` (doIt) and `Ctrl+Shift+D` (debugIt) work after the removal.

The comment in the code _"this is because for some reason Ctrl+d means Ctrl+end on Windows"_ is quite confusing but the code seems to be there at least 3 years ago as far I can see in the git blame.

**Comment by guillep** [comment]
> The last shortcut, `#debugItPatchForWindows`, overrides the Windows `Ctrl+Shift+End` default behavior. If you remove that shortcut definition, reset the keybindings, save the image and restart then `Ctrl+Shift+End` works flawlessly.
> Also `Ctrl-D` (doIt) and `Ctrl+Shift+D` (debugIt) work after the removal.
> 
> The comment in the code _"this is because for some reason Ctrl+d means Ctrl+end on Windows"_ is quite confusing but the code seems to be there at least 3 years ago as far I can see in the git blame.

Yes, this is because in the previous window manager we used some events were "broken".
With the new SDL windows backend this should work properly.
And your test seems to show that :).

I support your proposal to remove those overrides.

**Comment by Ducasse** [comment]
@fxgallego if you remove this method does it work for you?

**Comment by fxgallego** [comment]
@Ducasse yes, removing the entire patch method works!

**Comment by Ducasse** [comment]
So we can say that you fix it :).
