### ISSUE TITLE
Add menu item to get all the classes/traits using a trait

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8569]
![Screenshot 2021-02-14 at 11 09 49](https://user-images.githubusercontent.com/432549/107873771-2d1ddd80-6eb5-11eb-8115-1f3d23b70d42.png)

We should get a menu item: Users under Class refs. 

```
TBlChildrenExample traitUsers 
```

**Comment by MarcusDenker** [comment]
This has been fixed: there is now a menu
