### ISSUE TITLE
Cannot run newly created Pharo 9 images

### ISSUE THREAD

**Issue by dupriezt** [guillep/pharo-core#8572]
**Describe the bug**
Trying to run new Pharo 9 images does not work: no window opens.
A VM process is started, that consumes more and more memory (I've seen it reach 10+ GB of RAM) until I force-quit it.

Running a newly created Pharo 8 image works.
The most recent Pharo 9 image I have that runs was created on February 12th (Build information: Pharo-9.0.0+build.1126.sha.73e5a3b1575d661d39536b00448915de73795374 (64 Bit))

Using the Pharo-launcher or the command line to run the images does not affect the result.
My VM is up-to-date as of February 16th.

**Version information:**
 - OS: Windows 10, 64 bits

*Edit*
I'm trying out the recent Pharo 9 builds to find the one where images stop running for me.
- 1126 runs
- 1127 runs
- 1128 runs
- 1129 runs but there's a red rectangle error in the welcome menu
- 1130 runs
- **1131 does not run**
- 1132 does not run

**Comment by dupriezt** [comment]
I tried out the recent Pharo 9 builds to find the one after which I can no longer run images.
Looks like build 1131 is the culprit.
I don't know what more I can do from here.

**Comment by MarcusDenker** [comment]
On macOS it seems to work fine. changes in 1131 were:

- Adding deprecations that were recommended by DepMiner (accepted by 1 reviewer)
- Adding a work around to for getting the environment variables in Windows. https://github.com/pharo-project/pharo/pull/8547
- Form class>>#services changed to allow easy extension of the options when an image file is drag'n'dropped onto the image 
- This PR removed the tests cases from Deprecated90.

**Comment by tesonep** [comment]
I have integrated a fix 
It was there since yesterday. Waiting the image to be generated.
