### ISSUE TITLE
IRTempVector issue when installing breakpoints on some methods

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#8575]
**Bug description**
When a breakpoint is installed on some methods, it fails with message `Instance of OrderedDictionary did not understand #indexOf:`. The switching of the method elsewhere and back shows installed breakpoint but its removal raises next DNUs.

**To Reproduce**
- create method with this code:
```smalltalk
acceptMemberGroup: aGroup	
 
	aGroup id = #searchActions ifTrue: [ 
		| path anAspect |
		
		aGroup members do: [ :each |
				path := aGroup part pathFromRoot, each name.
				anAspect := self description createAspectNamed: each name redirectTo: path.
		] ]
```
- try to install a breakpoint by clicking on the bar next to the third line (aGroup id =...)

**Comment by pavel-krivanek** [comment]
it fails for the third line of this method as well: 
```smalltalk
acceptededMemberGroupTypes

	^ #(
		#searchActions )
```

The error is different: Instance of RFThisContextReification did not understand #genForRBLiteralArrayNode

It does not fail if the code is on a single line

**Comment by MarcusDenker** [comment]
I added a PR that has a test and fix for the second problem
