### ISSUE TITLE
Inspector on a FileReference does not allow to use cmd-s to save

### ISSUE THREAD

**Issue by noha** [guillep/pharo-core#8585]
**Describe the bug**
In the old inspector when inspecting a file there is a contents pane. This enabled to edit the contents and use the usual cmd-s to store the file's content on disk. In the new pharo9 this behavior is gone.

**To Reproduce**
1. inspect a file reference
2. edit content in script or content pane
3. press cmd-s
4. reopen file reference to see it is unchanged

**Expected behavior**
Using the shortcut cms-s on an inspected file reference should write the file

**Version information:**
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1136.sha.8dff87c75189b79fba980294e12efbfc7dc77cde (64 Bit)

**Comment by Ducasse** [comment]
BTW I think that we need to help esteban because the inspector is already a lot of work.

**Comment by MarcusDenker** [comment]
Was this fixed by https://github.com/pharo-project/pharo/pull/9293 ?

**Comment by estebanlm** [comment]
yes :)
