### ISSUE TITLE
Calypso or FluidClassPrinter get confused with metaclass with subclass having slots.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8586]
When a class has a slot the class side gets strange.

**Comment by Ducasse** [comment]
Did not get the time to look, will try later next week.

**Comment by Ducasse** [comment]
How to reproduce

- Look at the class def: 
```
AbstractLayout << #EmptyLayout
	tag: 'Layout';
	package: 'Kernel'
```
everything is ok

- Look at the class side: everything is ok
```
EmptyLayout class
	slots: { #instance }
```

- Create a subclass of EmptyLayout

```
EmptyLayout << #EmptyLayout2
	tag: 'Layout';
	package: 'Kernel'
```
Everything is ok

**Comment by Ducasse** [comment]
- Look at class side 
```
EmptyLayout2 class
```
(doing a copy paste break but this is not that bug)

- Click on the superclass and we get the class instance side definition displayed!!!!
Argggggghhhhhhh

**Comment by MarcusDenker** [comment]
this is now working
