### ISSUE TITLE
Removing class instance variable in fluid breaks.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8587]
Imagine the following definition
```
PharoLightTheme << #CzDayAtTheBeachThemeUsingUIPalette
	slots: { #uiPalette };
	package: 'CozyTheme'
```
and the metaclass having one slots

```
CzDayAtTheBeachThemeUsingUIPalette class
	slots: { #whatever }
```

Removing #whatever breaks

**Comment by Ducasse** [comment]
```
DoIt

	^ (CzDayAtTheBeachThemeUsingUIPalette class slots: {  }) install
```

Does not work becayse the slots: message does not return a builder.
So it means that all the fluid stuff should return a builder.

**Comment by Ducasse** [comment]
Why 

Metaclass >> slots: is defined as: 


```
slots: slotCollection 

	| theClass |
	theClass := self instanceSide.
		
	theClass := theClass classInstaller update: theClass to: [ :builder |
		builder
			fillFor: theClass;
			classSlots: slotCollection ].
	^ theClass classSide
```

**Comment by Ducasse** [comment]
Marcus do you think that we can change the result of slots:?

**Comment by MarcusDenker** [comment]
I will check. I dimly remember even adding it, but i do not remember why.

**Comment by MarcusDenker** [comment]
I think the reason is that adding a slot creates a *new* class. If we return self, we would return the *old* class.

**Comment by MarcusDenker** [comment]
But it might now be used... to add a slot we use #addSlot:, not this method.

I think we do not use the return value. It is used just once, I could just find a test
#testRedefinitionKeepsSlots

It is called by the backward compatibility #instanceVariableNames:, but nobody cared about the return value there.

So  it might be possible to change it to be the "switch" to get to the builder object (like what >> does on the instance side).

**Comment by Ducasse** [comment]
Thanks I will check because this is really annoying and it is not linked to fluid per se. 
The previous bug is also super strange.

**Comment by Ducasse** [comment]
I cannot reproduce the problems so I close it for now.

**Comment by Ducasse** [comment]
So I close it.
