### ISSUE TITLE
Not possible to create new class or new trait via menu on empty package

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#8623]
- open Calypso browser
- add a new empty package
- right click in the class pane **does not show any menu**

So it is not possible to create new class or new trait via menu on **empty packages**. But this is often the use case when developing: create a package and then a class or trait in it.

![image](https://user-images.githubusercontent.com/5980033/109125273-26605780-774c-11eb-9034-542347878dc3.png)

(Bad) Workaround:
The only option *at the moment* is to add least a single class to the package:
When you add a class first then you can right click and select "New Class" and "New Trait":

![image](https://user-images.githubusercontent.com/5980033/109125156-04ff6b80-774c-11eb-8744-99d1e8287af4.png)

**Comment by Ducasse** [comment]
Does the package menu let us create a class? Because creating a menu on an empty list looks strange.

**Comment by astares** [comment]
@Ducasse No - it does not as you can see on the following picture. 

![image](https://user-images.githubusercontent.com/5980033/109203394-62270b80-77a4-11eb-84b2-2a2039106d5e.png)

And what you call "strange" to be able to **open a menu on an empty list** is regular behavior (and makes perfectly sense) in many applications and operating systems. Here an example of Windows explorer opened on a list (with empty contents in a fresh folder):

![image](https://user-images.githubusercontent.com/5980033/109203763-d8c40900-77a4-11eb-8376-a024d928e968.png)

or here an example of Nemo in Linux:

![image](https://user-images.githubusercontent.com/5980033/109204581-d1512f80-77a5-11eb-87d8-830cf13702d2.png)

**Comment by tesonep** [comment]
It is fixed 
![image](https://user-images.githubusercontent.com/355455/218076690-7ae4dbe7-57f6-40b3-9470-c8bc48d182b0.png)

**Comment by astares** [comment]
@tesonep Great, thanks!
