### ISSUE TITLE
OSDL2 binding is instable and creates infinite loops

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#8627]
**Describe the bug**
It seems that it can happend that OSDL tried to pin null pointer to memory and of course it doesn't work.
The framework should catch the exception and recovers from it.

```
THERE_BE_DRAGONS_HERE
PrimitiveFailed: primitive #setPinnedInMemory: in ByteArray failed
25 February 2021 10:52:20.634 am

VM: Win32 - x86_64 - Win64 - CoInterpreter VMMaker-tonel.1 uuid: 3a3d3ee5-3177-0d00-a4b2-b647092688ce Feb  8 2021
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 3a3d3ee5-3177-0d00-a4b2-b647092688ce Feb  8 2021
f519c4cf - Commit: f519c4cf - Date: 2021-02-08 10:23:36 +0100

Image: Pharo9.0.0 [Build information: Pharo-9.0.0+build.1145.sha.2990df55516591fb04b356db0953b1205c208ab3 (64 Bit)]

ByteArray(ProtoObject)>>primitiveFailed:
	Receiver: #[0 0 0 0]
	Arguments and temporary variables: 
		selector: 	#setPinnedInMemory
	Receiver's instance variables: 
#[0 0 0 0]

```
[PharoDebug.log](https://github.com/pharo-project/pharo/files/6042082/PharoDebug.log)

**Version information:**
 - OS: Win10
 - Pharo 9.0.0
Build information: Pharo-9.0.0+build.1145.sha.2990df55516591fb04b356db0953b1205c208ab3 (64 Bit)

**Comment by Ducasse** [comment]
Hi Vincent 
do you have any idea how we could reproduce it?
I will flag it as important because we are now using SDL for real.

S

**Comment by VincentBlondeau** [comment]
Hi Stef,

I do not really know how to reproduce. But you could try to:
- let the image open quite long
- lock the session, unlock
- change the screen size
- deconnect connect the screen
- change the resolution

By the way I caught another bug with the headless and the SurfacePlugin dll. Maybe linked to #8655

**Comment by guillep** [comment]
> It seems that it can happend that OSDL tried to pin null pointer to memory and of course it doesn't work.

It's not trying to pin a null pointer but a `ByteArray` instance with four 0s (that could be representing a null pointer)... Nevertheless, pinning *should work*.

If we check the stack, what is happenning is that OSWindow is trying to get the extent of the window.
For that, it sends to SDL two byte arrays that act as value holders, so SDL puts the height and the width inside those byte arrays.

I'm not sure if this is an infinite loop, or simply that the UI loop is broken and cannot render because it cannot get the size of the window.

We should check why pinning is failing

**Comment by Ducasse** [comment]
Do we rename the issue?

**Comment by fedemennite** [comment]
I have a workaround that can possibly help to avoid hitting this issue more frequently while working with RDP:
Perform an explicit windows logout (not just a disconnect) and reconnect again.

Also, I have scenario that can possibly increase the chance of getting this bug.
- Connect to an open windows session via from a device with screen resolution A. 
- Disconnect
- Connect again to the same open session from a device with screen resolution B.
- Disconnect and try again with device with screen resolution A
- continue working with Pharo.

**Comment by Ducasse** [comment]
Hi fede 
Thanks for the scenario !!! because reproduction is what slow us down to fix them. 
I just made sure we can reproduce a bug in the debugger and it is good because we will be able to fix it now. 
:)

**Comment by tesonep** [comment]
It looks like the pin primitive has failed with "insufficient object memory"

ByteArray(Object)>>setPinnedInMemory:
	Receiver: #[0 0 0 0]
	Arguments and temporary variables: 
		aBoolean: 	true
		ec: 	#'insufficient object memory
	Receiver's instance variables: 
#[0 0 0 0]

I will check this error and retry after requesting more memory.
