### ISSUE TITLE
#allInstVarNames should be #allInstanceVariableNames

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#8631]
We should rename allInstVarNames into #allInstanceVariableNames and deprecated #allInstVarNames (if possible)

**Comment by MarcusDenker** [comment]
we use the abbreviated forms for compatibility with the "old" ivars, too. (e.g. to have instVarAt:), while the long form is for "Variables as Objects".

It used to be that allInstVarNames maps to the offsets of ivars, while slots do not (there can be slots that have no index). 

That is, the offset in #allInstVarNames should be a valid argument for #instVarAt:, while #allInstanceVariableNames should be in sync with #allInstanceVariables which is #allSlots.

**Comment by MarcusDenker** [comment]
The todo here is:
- add allInstanceVariableNames to ClassDescription
- make sure all users of #allInstVarNames that are not reasoning about offsets use it
- change #allInstVarNames to only return slots with offsets to be in sync with #instVarAt:
- Check all users of #instVarAt: --> all clients should be rewritten in terms of the first-class variable API. 

(this is not for Pharo10)

**Comment by MarcusDenker** [comment]
I was looking at this again and I think for now it is better to keep it as it is: short names -> old API, compatible with ST80.

With Variables being objects, we need the ...names methods less, and I would not add things like allSlotNames. Just use #allSlots and #slots (and get the name from there if needed).
