### ISSUE TITLE
SelectorNavigation: pressing Cmd-M/N on a line should not give the method but the line contents

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8634]
```
buildMapOfExtent: aPoint 
 caretHERE	map := Array2D rows: aPoint y columns: aPoint x 
```

Here we should get rows:columns: 
Or may be as a specific command to distinguish between method level and code level.

**Comment by dupriezt** [comment]
For Cmd-M, in the calypso browser, the responsible method is this one:
`ClyTextEditor>>#implementorsOfIt`
```smalltalk
implementorsOfIt
	| selector |

	"self lineSelectAndEmptyCheck: [^ self]."
	(selector := self selectedSelector) == nil ifTrue: [^ textArea flash].
	selector 	isCharacter ifTrue: [ ^ textArea flash ].
	self browser browseImplementorsOf: selector
```

**Comment by dupriezt** [comment]
Uncommenting the first line gives the intended behavior of selecting the whole line.
But I wonder what the reason for commenting it was?

**Comment by dupriezt** [comment]
Git blame on that line isn't very instructive
![image](https://user-images.githubusercontent.com/32486709/109288562-4fa0e680-7825-11eb-8b18-7adc1dc3411d.png)

**Comment by dupriezt** [comment]
Exact same thing for Cmd-n
`ClyTextEditor>>#sendersOfIt`
```smalltalk
sendersOfIt
	| selector |
	self lineSelectAndEmptyCheck: [^ self].
	(selector := self selectedSelector) == nil ifTrue: [^ textArea flash].
	
	self sendersOf: selector 
```
