### ISSUE TITLE
Package level comments

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#8639]
The package level comments can be seen in the browser when no class is selected.
The comment is stored as the class comment of the corresponding Manifest file.

However, if the manifest file is created by other means, the generic class comment of the manifest file:

> I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser

is presented as the package comment. It is a somewhat obscure way to tell that there is no package comment written yet.

One solution would be to store the package comment in the Manifest class as now, but not as the class comment of the manifest. A class side instance variable in `PackageManifest` named `packageComment` should work.

**Comment by astares** [comment]
One would need to migrate all internal and external package manifests into a #packageComment using the current solution.

Really a problem we need to solve? I would stay with the solution that the class comment of Manifest is (ab)used.


I guess a way to solve this is to improve the predefined text of TheManifestBuilder class>>#manifestClassComment into

```
Please describe the package using the class comment of the included manifest class. The manifest class also includes other additional metadata for the package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
```
so in both cases one is less confused
