### ISSUE TITLE
ZipArchiveError 'can''t find EOCD position' while using Tabular XLSL importer

### ISSUE THREAD

**Issue by terpon** [guillep/pharo-core#8657]
Looks like the same as https://github.com/VincentBlondeau/Tabular/issues/2

Trying to import an XLSL file with tabular. The file is somewhat big (around 1MB), and opens fine as a zip file. Looking in an hex editor, the End Of Central Directory is there.

 - OS: Windows10
 - Version: Pharo 8 and also latest 9.

Issue happens in `ZipArchive class>>#findEndOfCentralDirectoryFrom:
`
to get the size of the file, it does:
```
	stream setToEnd.
	fileLength := stream position.
```

`ZnBufferedReadStream>>#setToEnd` does not set the buffered position when called. The size reported is smaller than it is actually and the EOCD is beyond that position.

**Comment by svenvc** [comment]
My opinion is that it is next to impossible to get positioning right with true streams (like network or IO streams where a begin or end are often hard to define), let alone with buffered streams.

The way this code is written is assumes one can freely move forwards and backwards to go search for something, that is not stream processing.

One way to make this possible is to just take everything in memory, either as bytes or as a read stream on those bytes.

**Comment by terpon** [comment]
True, I found out why the XLSX importer is working in many cases. I passed to the import method a stream. It is used twice. Once in ZipArchive class method isZipArchive, which returns true, but the second time in ZipArchive readFrom, the stream has already been used and the same findEndOfCentralDirectoryFrom: fails.
Passing a FileReference, a new binary stream is created for every EOCD check, so no problem there.

Also, ZnBufferedReadStream claims:

> By design I do not implement #position and #position: or anything based on that.

but does ;) except for setToEnd and probably other places.
Fighting with Iceberg on Win10 and latest Pharo to try to do a PR that would fix that specific issue.

**Comment by guillep** [comment]
Yes, I agree with @svenvc . It's a bit my fault, I forced `position:` et al into Zn streams to make them usable in the context of files... I'd like to think of a solution that works for files too, without having to rewrite everything while keeping the original clean design goals...

**Comment by seandenigris** [comment]
There's also IMHO the question of whether it makes sense for `#isZipArchive:` to be destructive i.e. use up the stream it is given. After skimming the code, I get the sense it is trying to be too flexible by accepting either a file or a stream and massaging the argument to end up at the same place. As alluded to above, files are a simplified subset of streams and so seemingly should be handled separately. In effect, one probably should never send `#isZipArchive:` with a generic stream, because, what if the stream data cannot be recovered after it is effectively thrown away?
