### ISSUE TITLE
When opening the debugger, the executed code is not highlighted

### ISSUE THREAD

**Issue by StevenCostiou** [guillep/pharo-core#8667]
Nothing is highlighted in the text, while the next instruction to execute should be highlighted.
This is a regression.

**Comment by StevenCostiou** [comment]
duplicate of https://github.com/pharo-project/pharo/issues/8659

**Comment by Ducasse** [comment]
Steven in the latest version I have now it looks like it is fixed.

**Comment by estebanlm** [comment]
why you assigning this one to me?
