### ISSUE TITLE
Got some bugs with Calypso... :(

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8673]
on class TraitsTestCase edit the method 

```
createTraitNamed: aSymbol uses: aTraitComposition
	| trait |

	trait := self class classInstaller make: [ :aBuilder |
		aBuilder 
			name: aSymbol;
			traitComposition: aTraitComposition asTraitComposition;
			package: self categoryName;
			beTrait ].			

	self createdClassesAndTraits add: trait.
	^trait
```

and changed createTraitNamed: aSymbol uses: aTraitComposition into createTraitNamed: aSymbol trait: aTraitComposition

The new method does not show up.
Get a DNU 
<img width="787" alt="Screenshot 2021-03-01 at 14 33 03" src="https://user-images.githubusercontent.com/432549/109503855-12de2500-7a9b-11eb-9913-1788b2ab0555.png">

**Comment by guillep** [comment]
@Ducasse I could not reproduce it, have you fixed it in the meantime? Maybe there is some other previous change that makes this problem to kick-in

**Comment by Ducasse** [comment]
I do not remember and I did not get recently. So I will close it.
