### ISSUE TITLE
Clean unused Class Vars so we can un-skip #testNoUnusedClassVariablesLeft

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#8678]
**Describe the problem**
testNoUnusedClassVariablesLeft is now doing a "self skip" as there are indeed used class vars in the system

**What remains to be fixed**

- StHaltCacheChanged, SpTestPresenterWithToolbar, StObjectInspectorPresenter. PR is here: https://github.com/pharo-spec/NewTools/pull/174
- IceLibgitFiletreeFileUtils, IceTipCommitSettings, IceLibgitTonelFileUtils. PR was merged but it is not yet in Pharo9. https://github.com/pharo-project/pharo/issues/8612
- Character:  https://github.com/pharo-project/pharo/issues/5275
- FTSizeRec: we tried to remove (see https://github.com/pharo-project/pharo/pull/8601 ) , but they seem to be auto-generated

**Comment by MarcusDenker** [comment]
Current TODO:

- SpTestPresenterWithToolbar https://github.com/pharo-spec/Spec/issues/1012
- Character: #5275
- FTSizeRec: we tried to remove (see #8601 ) , but they seem to be auto-generated: https://github.com/pharo-project/pharo/issues/8695

**Comment by MarcusDenker** [comment]
With just 3 variables left, I propose to de-skip and test for <=3, this way we avoid to constantly add new cases.
The "3" then can be lowered as we fix the remaining cases.

**Comment by MarcusDenker** [comment]
I merged the PR

**Comment by astares** [comment]
Yes, otherwise we would get more cases and never be clean

**Comment by MarcusDenker** [comment]
I will do the same for the ivar case, we have a bit more there (~30)

**Comment by astares** [comment]
Step by step it goes (down)
