### ISSUE TITLE
Revisit World Scaling [WAS: Blurry Render on retina display]

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#8688]
**Describe the bug**

Render is Blurry on retina display.
Compare

![image](https://user-images.githubusercontent.com/708322/109945762-dea37800-7cd7-11eb-91d8-3adf394d5bed.png)

to the expected

![image](https://user-images.githubusercontent.com/708322/109945842-f1b64800-7cd7-11eb-829e-5f95b9614e48.png)

**Version information:**

I tracked this to build 839
 - build 838 works ok
 - build 839 already shows the problem (but there are scaling issues on my retina)

**More information**

I tracked this to the change in https://github.com/pharo-project/pharo/blob/099690e06c28b1d6836db93c8e724a7044c69844/src/OSWindow-SDL2/SDL2.class.st#L256

Removing that hint makes it work again, however, then scaling the image looks too pixeled:

![image](https://user-images.githubusercontent.com/708322/109946729-d7c93500-7cd8-11eb-9693-6603ffc1a454.png)

In contrast with this scaling that looks blurry:

![image](https://user-images.githubusercontent.com/708322/109946835-f7f8f400-7cd8-11eb-8084-738da5e08acd.png)

** Related Links**

https://wiki.libsdl.org/SDL_HINT_RENDER_SCALE_QUALITY
https://discourse.libsdl.org/t/sdl-sethint-or-another-way-to-use-different-scaling-quality/21239

**Comment by tesonep** [comment]
@guillep do we close this issue? Or you want let it open to future reference?

**Comment by guillep** [comment]
I would prefer to let it open for reference, and to work on it in Pharo 10.
Next steps would involve:
 - check if/how the form scene graph solves it https://github.com/ronsaldo/form-scene-graph. I was talking yesterday with @ronsaldo and there is a potential there to chose the font points/size depending on the scaling, instead of scaling the small glyphs
 - another possiblility to explore is to disable SDL_HINT_RENDER_SCALE_QUALITY when no scaling is used (this requires some refactoring, as OSWindow does not actually know how morphic is scaled
 - Extend morphic so users can scale/zoom with pre-defined scalings
 - We need to extend the full IDE to choose between different size icons depending on the scaling

<blockquote><img src="https://avatars.githubusercontent.com/u/1550655?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/ronsaldo/form-scene-graph">ronsaldo/form-scene-graph</a></strong></div><div>A Gtk Scene Graph inspired rendering framework for Pharo - ronsaldo/form-scene-graph</div></blockquote>
