### ISSUE TITLE
DropListBox is rendering the text on top of the button

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#8689]
Actual: 

![image](https://user-images.githubusercontent.com/355455/109951386-ec5bfc00-7cdd-11eb-86d2-6b3c8204ac74.png)

Expected:

![image](https://user-images.githubusercontent.com/355455/109951464-0564ad00-7cde-11eb-8a9e-76ab02ebbbf4.png)

**Comment by guillep** [comment]
This seems to be working now.

![image](https://user-images.githubusercontent.com/708322/111166690-a259fc80-85a0-11eb-975a-6e8679c4867c.png)

Has it been fixed? Can I close? @tesonep
