### ISSUE TITLE
[Spotter] In Pharo 9, Spotter doesn't show categories anymore

### ISSUE THREAD

**Issue by sonibla** [guillep/pharo-core#8705]
**Describe the request**
In Pharo 8, the spotter separates different result categories (Classes, Packages, Implementors...), which can be selected with shortcuts (for example Ctrl+B for classes)

![Spotter Pharo 8](https://user-images.githubusercontent.com/49032546/110234125-15bc9800-7f29-11eb-90a3-327b7108296e.png)

But in Pharo 9, the spotter puts every source code results (Classes, Packages, Implementors...) in the category "Results" (shortcuts still work but are not shown on the screen anymore)

![Spotter Pharo 9](https://user-images.githubusercontent.com/49032546/110234190-6502c880-7f29-11eb-8e43-f70697e12dab.png)

**Expected behavior**
Have the possibility to show different Categories instead of just "Results", similarly to Pharo 8. Currently, in Pharo 9 settings, it's only possible to restrict the results, but not to show them explicitly in different categories.

**Expected development cost**
I guess less than a day, as the source code already exists in Pharo 8

**Version information:**
 - OS: tested on Linux and Windows 10
 - Version:
Pharo 8.0.0
Build information: Pharo-8.0.0+build.1124.sha.0932da82f08175e906b0e2a8052120c823374e9f (64 Bit)
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1180.sha.f231ce798fc37b44fd415566fc30fa00ec7dc831 (64 Bit)

**Comment by Ducasse** [comment]
Thanks for the feedback. Please pay attention that Spotter is completely being rewritten and it will not be 100% the same.

**Comment by MarcusDenker** [comment]
This is fixed in the latest Pharo9
