### ISSUE TITLE
Remove / Deprecate unfinished Rules Profiles

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#8717]
There is 
 - unused abstract class "ReExclusivelyBeginnersRule" without any subclasses
 - a setting #ruleProfileSettingsOn: with a #rulesProfile and a distinction between #isDefaultRule and #isBeginnerRule methods (also unused)

But this seem to no effect at all on displayed or used rules.

I think the idea was that the rules manager could handle a default and a beginner profile with specific rules only.
I guess it is just some unfinished legacy - we should remove it...

**Comment by astares** [comment]
seems to be from January 2020, unfinished work from Esteban Villalobos and some methods are from @Ducasse

**Comment by Ducasse** [comment]
Yes this is strange because I thought that it was in place.

**Comment by MarcusDenker** [comment]
There is now https://github.com/pharo-project/pharo/issues/9314, I close this issue
