### ISSUE TITLE
Pharo should follow UML rules

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#8718]
Pharo includes now an UML pane, but it does not follow UML rules:

 - the classes in Calypso are displayed using a round rectangle - but in UML there is a non-rounded regular rectangle used
        => use regular rectangle
 - when a class is abstract the class name is displayed in italic font in the class diagrams.
        => use italic font for the class name when the class returns true for #isAbstract   

![image](https://user-images.githubusercontent.com/5980033/110335690-6bc23600-8024-11eb-8fd1-7025068e3e4d.png)

**REFERENCE**
The UML Spec - on Page 101:
https://www.omg.org/spec/UML/2.5.1/PDF

![image](https://user-images.githubusercontent.com/5980033/110336829-8b0d9300-8025-11eb-8cfd-785177babb61.png)

![image](https://user-images.githubusercontent.com/5980033/110336540-3ff38000-8025-11eb-9a1d-72bf5623066b.png)

We should follow the UML notation strictly as this is an international standard in software engineering.

**Comment by akevalion** [comment]
@astares I have change it for rectangular classes and abstract classes are with italic

![image](https://user-images.githubusercontent.com/10532890/110577853-49263f00-8142-11eb-8fc1-0df79ce5512c.png)

**Comment by astares** [comment]
Wonderful, thanks a lot! 👍
