### ISSUE TITLE
Class AbstractTool is not really abstract

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#8732]
- AbstractTool has "Abstract" in its name, it is a subclass of Model
- but I think it is not really an abstract class as it is instantiated in
-- MessageList>>#initialize in New Tools
-- SpMethodToolbar>>#initialize in Spec2
-- MethodToolbar>>#initialize in deprecated Spec PolyWidgets

=> I propose to rename the class into "ToolModel" and deprecate class AbstractTool for Pharo P9 as a first step for further cleanup (Spec2 and NewTools should then use ToolModel)

@MarcusDenker, @estebanlm What do you think

**Comment by estebanlm** [comment]
Honestly, I would not lose my time on it, since it has to be removed anyway :)

**Comment by astares** [comment]
Will we remove it in P9 already - if not we can easily fix it the proposed way. It's easy and not much.
