### ISSUE TITLE
Add a release test for unclassified methods

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#8761]
**Describe the problem**

There are quite someme classes with unclassified methods (270).

We could add a release test to make sure that the situation at least does not get worse.
(and then slowly clean them)

```
Smalltalk globals allBehaviors select: [ :class | class  protocols includes: #'as yet unclassified'. ]
```

**Comment by astares** [comment]
Yes - we should do that. Otherwise cleaning would be endless.

**Comment by Ducasse** [comment]
We should add a rule too. 
This happens since we let people not categorize methods.
