### ISSUE TITLE
New playground does not describe commands

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#8771]
The menu items in new playground are represented by commands that are not described. Just hover over the menu items and wait a little bit.

![image](https://user-images.githubusercontent.com/5980033/110686417-b340f180-81df-11eb-8924-f11207dcea40.png)

Same for
 - Do it
 - Debug it
 - Inspect it
 - Print it
 - ...

**Comment by MarcusDenker** [comment]
this has been fixed
