### ISSUE TITLE
print-it label in a Playground with a medium font is not lisible

### ISSUE THREAD

**Issue by SergeStinckwich** [guillep/pharo-core#8776]
**Describe the bug**
This is not possible to read the result of a print-it (CTRL-P) with a medium font in a Playground

**To Reproduce**
1. Change the default font to medium in settings.
2. Open a Playground
3. Select and evaluate: 'hello' with CTRL-P
4. the result of the print-it in the yellow label is not visible.

**Expected behavior**
The result should be readable whatever the font selected.

**Screenshots**

![](https://cdn.discordapp.com/attachments/809704795887501312/819557069157302332/Screenshot_2021-03-11_at_21.07.05.png)

**Version information:**
 - MacOS Big Sur 11.2.3
 - Version: Pharo-9.0.0+build.1180.sha.f231ce798fc37b44fd415566fc30fa00ec7dc831 (64 Bit)

**Comment by VincentBlondeau** [comment]
Can be reproduced on Windows too.

**Comment by svenvc** [comment]
I can confirm, very annoying

**Comment by Ducasse** [comment]
Yes we know it :)
