### ISSUE TITLE
[Feature Request] Close hidden windows

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#8792]
For people like me, who have quickly tons of opened windows in Pharo, it would be handy to have a taskbar command for losing windows that are not visible because they are fully overlapped by others that are above them.

Code sketch: 
```smalltalk
windows := (World submorphs select: [:each | each isSystemWindow ]) reversed.
invisible := windows withIndexSelect: [ :win :index |
	bounds := win fullBoundsInWorld.
	parts := OrderedCollection new.
	other := (windows copyFrom: index+1 to: windows size) collect: [:each | each fullBoundsInWorld] .
	bounds allAreasOutsideList: other do: [ :each | parts add: each  ].
	parts isEmpty
].
invisible do: [ :each | each close ].
```

The code sketch should be improved to handle edge cases like minimized windows, windows that are marked as unclosable etc.

**Comment by Ducasse** [comment]
Good idea. 
It was the idea behind "autumn leaves" 
No time for fun stuff.

**Comment by Ducasse** [comment]
If you look we do not have a command for trait users...yet
