### ISSUE TITLE
some settings for code completion are not working

### ISSUE THREAD

**Issue by Gobi-one** [guillep/pharo-core#8793]
**Describe the bug**
 

A. Code completion is always case sensitive even if the checkbox is unchecked.
B. "Popup appears with this shortcut" doesn't work, if I uncheck "popup is automatic", I can't make the popup appears with shortcuts.

**To Reproduce**
A) Steps to reproduce the behavior:
1. Go to 'settings'
2. Verify 'Case sensitive' checkbox is unchecked
3. Inside playground type : 'TranscrI'
4. See the popup for autocompletion disappears

B) Steps to reproduce the behavior:
1. Go to 'settings'
2. uncheck 'Popup is automatic
3. Inside playground type : 'Transcr'
4. Press the shortcut for autocompletion
5. Nothing happens.

**Expected behavior**
A) The popup is still open with 3 suggestions (Transcript, TranscriptLogger, TranscriptDebugger).
B) The popup opens with 3 suggestions  (Transcript, TranscriptLogger, TranscriptDebugger).

**Version information:**
 - OS: Windows 10 pro
 - Pharo Version: 
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1203.sha.35f9e3d0024bccf46c3928d9f195e26bbe97f563 (64 Bit)

**Comment by Gobi-one** [comment]
I should have added that code completion isn't executed when you erase characters from a word.
Let's say I write 'Transcri', I have a popup with suggestions.
Then I add a 'm' character ('Transcrim'), I don't have suggestions anymore which is logical.
But if I erase the 'm' to go back to the state I was before ('Transcri') the suggestions aren't displayed again.

**Comment by Ducasse** [comment]
Thanks for the report.

**Comment by Ducasse** [comment]
We may have a look during the next sprint.

**Comment by Gobi-one** [comment]
I took a look at the pull request and I'm not sure that it solves the problem I described in the comment above (about backspace key not resetting the completion engine).
My apologies if it does.

**Comment by guillep** [comment]
We did not work on the backspace issue (I think we did not see it), only on the main comment

**Comment by Gobi-one** [comment]
Ok I just deleted my message to post it on the pull request.
I paste it here so it's not confusing.

"I took a look at the pull request and I'm not sure that it solves the problem I described in the comment above (about backspace key not resetting the completion engine).
My apologies if it does."
