### ISSUE TITLE
Check packaging of #affectsCritiques

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#8813]
This issue is a reminder: check the implementor of #affectsCritiques regarding method protocol / method packaging:
1. one of them is in an SUnit related package (ClyTestCaseRan>>#affectsCritiques)
2. two of them are extension methods of Calypso Critiq packages (Announcement>>#affectsCritiques and ClyAsyncQueryIsDone>>#affectsCritiques)

Is this correctly - I would have expected the first to be packaged like the other two. But I may be wrong

![image](https://user-images.githubusercontent.com/5980033/111648255-768a8100-8803-11eb-947b-bec026d28ae5.png)

**Comment by MarcusDenker** [comment]
The reason is that this class itself is in the package Calypso-SystemPlugins-SUnit-Queries
