### ISSUE TITLE
Categorize uncategorized methods in classes starting with M

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#8833]
```Smalltalk
Smalltalk globals allBehaviors select: [ :class | class  protocols includes: #'as yet unclassified'. ]
```
- MCFileRepositoryInspector
- MCFileTreeStSnapshotWriter
- MCMergeBrowser
- MCMock
- MCMockASubclass
- MCMockClassA
- MCMockClassD
- MCMockClassE
- MCRepositoryInspector
- MCTestCase
- MFClassA
- MFClassB
- MagnitudeTest
- ManifestSlotCore
- MergeJoinSection
- MetacelloMCBaselineProject
- MetacelloMCProject
- MicArgumentsSplitter
- MicRootBlock
- MockSourceEditor
- ModelDependentDialogWindow
- MorphTest
- MorphTreeMorph
- MorphTreeResizerMorph
- MorphicFastTableAdapter
- MulticolumnLazyListMorph

**Comment by astares** [comment]
see https://github.com/pharo-project/pharo/pull/8806

**Comment by MarcusDenker** [comment]
I added https://github.com/pharo-project/pharo/issues/9705
