### ISSUE TITLE
SerialPort cannot be opened in Pharo 9

### ISSUE THREAD

**Issue by artem-bochkarev** [guillep/pharo-core#8846]
**Bug description**
Opening SerialPort with arduino worked in Pharo 8.0, but fails in Pharo 9.0

**To Reproduce**
1. Attach Arduino to PC
2. Check COM number in device manager(COM7 in my case)
3. Do it in Playground:
|myPort|
myPort :=
    SerialPort new
        baudRate: 9600;
        dataBits: 8;
        stopBitsType: 1;
        parityType: 0;
        yourself.
(myPort openPort: 'COM7') isNil ifFalse: [ myPort inspect ].

**Expected behavior**
Port should be opened, but i get error "Cannot open port" in Pharo 9.
This works well in Pharo 8.0 so this is a regression.

**Version information:**
 - Windows 10
 - Version: [20H2]
 - Pharo Version [9.0-SNAPSHOT.build.1229]

**Comment by Ducasse** [comment]
Thanks for the report!

**Comment by MarcusDenker** [comment]
This seems to be the same issue as https://github.com/pharo-project/pharo/issues/7721

**Comment by pavel-krivanek** [comment]
SerialPort was removed and replaced by an FFI implementation in an external package, see https://github.com/pharo-project/pharo/issues/12767

Issue can be closed.

**Comment by astares** [comment]
For the records, repo is on:  github.com/tesonep/SerialPort
