### ISSUE TITLE
Closing all windows like Iceberg closes Playground too

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#8850]
**Bug description**
If you now, in Pharo 9 after the Iceberg Spec conversion, do in the taskbar `RMB - Close all - windows like this` for any Iceberg window, it closes all Playgrounds as well. Actually, it closes all Spec windows.

**To Reproduce**
1. open Playground
2. evaluate `(SpButtonPresenter new label: 'Button') openWithSpec ` to open another Spec window
3. open Iceberg
4. on Iceberg window in taskbar do:  RMB - Close all - windows like this
5. all these windows are closed

**Expected behavior**
Only Icberg related windows are closed

**Version information:**
 - Pharo Version Pharo9.0.0, build: 1229, commit: 5c758a7

**Comment by Alisu** [comment]
```
taskbarCloseAllLikeThis
	
	(SystemWindow allSubInstances select: [ :w | w model isKindOf: self model class ]) do: [ :w | w delete ].
```
Most of Spec applications  answer the same SpWindowPresenter for model which means there are all deleted.

**Comment by estebanlm** [comment]
yes... and I do not see an easy way to re-implement this functionality (since SpWindowPresenter will have an SpPresenter inside, transmitting the problem, not solving it).

**Comment by Alisu** [comment]
I see that all windows have names. A bad temporarly fix could be to change the taskbarCloseAllLikeThis to check for similar name ?
