### ISSUE TITLE
Transcript noise from RubShoutStylerDecorator 

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#8854]
**Bug description**
When there is a syntax error. the Shout Styler messes the Transcript with messages
`SubscriptOutOfBounds: 0`
on every keystroke, The logging is caused by this method:
`RubShoutStylerDecorator>>#style:`

**To Reproduce**
1. open Transcript
2. open Calypso
3. start to write a completely empty method but without a method selector, start the method text with a number, for example.
4. write something

![pppEVTxijM](https://user-images.githubusercontent.com/572494/111998711-94febe00-8b1c-11eb-81e2-faf2fb9c9927.gif)

**Comment by olekscode** [comment]
I can not reproduce this issue.
I think it was already fixed.

Steps to reproduce:
1. Open Transcript
2. Open System Browser (Calypso)
3. Choose any method, delete everything, start typing
(nothing happens in Transcript)

Alternatively
3. Create a new method, delete everything, start typing
(nothing happens in Transcript)

**Comment by MarcusDenker** [comment]
it needs to start with a number

**Comment by olekscode** [comment]
Ah, indeed!

**Comment by MarcusDenker** [comment]
fixed by merging https://github.com/pharo-project/pharo/pull/9292
