### ISSUE TITLE
Segmentation fault cloning repo in Iceberg using latest headless vm and Pharo 9 on Manjaro Linux

### ISSUE THREAD

**Issue by gcotelli** [guillep/pharo-core#8860]
**Bug description**
The system segfaults trying to clone a repository using Iceberg

**To Reproduce**
1. Download pharo version with 
```bash
curl https://get.pharo.org/64/90+vmHeadlessLatest | bash 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3146  100  3146    0     0   2688      0  0:00:01  0:00:01 --:--:--  2688
Downloading the latest 90 Image:
    http://files.pharo.org/get-files/90/pharo64.zip
Pharo.image
Downloading the latest pharoVM:
        http://files.pharo.org/get-files/90/pharo64-linux-headless-latest.zip
pharo-vm/pharo
Creating starter scripts pharo and pharo-ui
```
2. Start with `./pharo-ui Pharo.image`
3. Open Iceberg and `Clone From github.com` a new project using SSH, owner name: `ba-st`, Project Name `Buoy`
4. Click Ok
5. The image segfaults (find attached the dump info)

**Expected behavior**
To not segfault and clone the repository

**Version information:**
 - **OS**: 
 ```
Manjaro Linux
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.0
DISTRIB_CODENAME=Ornara
DISTRIB_DESCRIPTION="Manjaro Linux"
Linux version 5.10.23-1-MANJARO (builduser@LEGION) (gcc (GCC) 10.2.0, GNU ld (GNU Binutils) 2.36.1) #1 SMP PREEMPT Thu Mar 11 18:47:18 UTC 2021
```
 - **Pharo Version**: 
```
Pharo 9.0.0 
Build information: Pharo-9.0.0+build.1236.sha.5c9b8c3ad1eb1041eff2f97b7f5bf3dd36c039ab (64 Bit)
```
- **Virtual Machine**
```
/home/gcotelli/Programming/Pharo-9/pharo-vm/lib/pharo
CoInterpreter VMMaker-tonel.1 uuid: 40f42ea2-327a-0d00-aafb-3b340faf8631 Mar 18 2021
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 40f42ea2-327a-0d00-aafb-3b340faf8631 Mar 18 2021
66a54a8 - Commit: 66a54a8 - Date: 2021-03-18 15:54:25 +0100
Pharo 9.0.0 built on Mar 18 2021 16:05:05 Compiler: 5.4.0 20160609
VMMaker versionString 66a54a8 - Commit: 66a54a8 - Date: 2021-03-18 15:54:25 +0100
CoInterpreter VMMaker-tonel.1 uuid: 40f42ea2-327a-0d00-aafb-3b340faf8631 Mar 18 2021
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 40f42ea2-327a-0d00-aafb-3b340faf8631 Mar 18 2021
```
- **Loaded VM Modules**
```/lib/libgit2.so.1.1
B2DPlugin VMMaker.oscog-eem.2480 (e)
BitBltPlugin VMMaker.oscog-eem.2493 (e)
FileAttributesPlugin FileAttributesPlugin.oscog-akg.49 (e)
FilePlugin VMMaker-tonel.1 (e)
LargeIntegers v2.0 VMMaker.oscog-eem.2495 (e)
LocalePlugin VMMaker.oscog-eem.2495 (e)
MiscPrimitivePlugin VMMaker.oscog-eem.2480 (e)
SDL2
SocketPlugin VMMaker.oscog-eem.2495 (e)
SurfacePlugin Mar 18 2021 (e)
libc.so.6
libfreetype.so.6
```

**Expected development cost**
No idea

**Additional context**
Crash dump:
[crash.dmp.txt](https://github.com/pharo-project/pharo/files/6189571/crash.dmp.txt)

**Comment by Ducasse** [comment]
Thanks for the report.

**Comment by gcotelli** [comment]
Another crash dump in case it helps: 
[crash.dmp.txt](https://github.com/pharo-project/pharo/files/6237922/crash.dmp.txt)

**Comment by gcotelli** [comment]
A crash dump is also produced using the stable VM downloaded by:

`curl https://get.pharo.org/64/90+vm | bash`

[crash.dmp.txt](https://github.com/pharo-project/pharo/files/6237939/crash.dmp.txt)

**Image**
-----
/home/gcotelli/Programming/Pharo-9/Pharo.image
Pharo9.0.0
Build information: Pharo-9.0.0+build.1264.sha.ec76afa775599c7fcf5b85cefee36843d54fc244 (64 Bit)
Unnamed

**Virtual Machine**
---------------
/home/gcotelli/Programming/Pharo-9/pharo-vm/lib/pharo/5.0-202002121043/pharo
CoInterpreter * VMMaker-CompatibleUserName.1580983506 uuid: 7aff73cb-5a2e-5002-a356-37de4e762a49 Feb 12 2020
StackToRegisterMappingCogit * VMMaker-CompatibleUserName.1580983506 uuid: 7aff73cb-5a2e-5002-a356-37de4e762a49 Feb 12 2020
VM: 202002121043 https://github.com/pharo-project/opensmalltalk-vm.git Date: Wed Feb 12 11:43:20 2020 CommitHash: 52202d8 Plugins: 202002121043 https://github.com/pharo-project/opensmalltalk-vm.git

Unix built on Feb 12 2020 11:06:28 Compiler: 5.4.0 20160609
VMMaker versionString VM: 202002121043 https://github.com/pharo-project/opensmalltalk-vm.git Date: Wed Feb 12 11:43:20 2020 CommitHash: 52202d8 Plugins: 202002121043 https://github.com/pharo-project/opensmalltalk-vm.git
CoInterpreter * VMMaker-CompatibleUserName.1580983506 uuid: 7aff73cb-5a2e-5002-a356-37de4e762a49 Feb 12 2020
StackToRegisterMappingCogit * VMMaker-CompatibleUserName.1580983506 uuid: 7aff73cb-5a2e-5002-a356-37de4e762a49 Feb 12 2020

**Loaded VM Modules**
-----------------
/lib/libgit2.so.1.1
B2DPlugin VMMaker.oscog-eem.2480 (i)
BitBltPlugin VMMaker.oscog-eem.2493 (i)
FileAttributesPlugin FileAttributesPlugin.oscog-akg.49 (e)
FilePlugin VMMaker.oscog-eem.2498 (i)
FloatArrayPlugin VMMaker.oscog-eem.2480 (i)
LargeIntegers v2.0 VMMaker.oscog-eem.2495 (i)
LocalePlugin VMMaker.oscog-eem.2495 (i)
MiscPrimitivePlugin VMMaker.oscog-eem.2480 (i)
SDL2
SecurityPlugin VMMaker.oscog-eem.2480 (i)
SocketPlugin VMMaker.oscog-eem.2495 (i)
SqueakFFIPrims
SurfacePlugin Feb 12 2020 (e)
libc.so.6
libfreetype.so.6

**Operating System Details**
------------------------
Manjaro Linux \r  (\n) (\l)


DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.0
DISTRIB_CODENAME=Ornara
DISTRIB_DESCRIPTION="Manjaro Linux"
Linux version 5.10.23-1-MANJARO (builduser@LEGION) (gcc (GCC) 10.2.0, GNU ld (GNU Binutils) 2.36.1) #1 SMP PREEMPT Thu Mar 11 18:47:18 UTC 2021

The console output is:
```
Instance of Array did not understand #(#SqueakFFIPrims #primitiveCalloutWithArgs 4 21)
Array(Object)>>doesNotUnderstand: #(#SqueakFFIPrims #primitiveCalloutWithArgs 4 21)
Array(ExternalFunction)>>invokeWithArguments:
LGitRepository>>clone:url:local_path:options:
FFICalloutAPI>>function:library:
LGitRepository(Object)>>ffiCall:library:options:
LGitRepository(Object)>>ffiCall:options:
LGitRepository>>clone:url:local_path:options:
[ 
                self 
                        clone: self
                        url: aString
                        local_path: aFileReference pathString
                        options: cloneOptions getHandle ] in LGitRepository>>clone:options:to: in Block: [ ...
LGitRepository(LGitExternalObject)>>withReturnHandlerDo:
LGitRepository>>clone:options:to:
LGitRepository>>clone:options:
[location ensureCreateDirectory.

        repo := LGitRepository on: location.
        cloneOptions := repo cloneOptionsStructureClass withCredentialsProvider: (IceCredentialsProvider defaultForRemoteUrl: url).

        "Keeping references, because if not the GC take them."
        checkoutOptions := cloneOptions checkoutOptions.
        callbacks := cloneOptions fetchOptions callbacks.
        callbacks transferProgress: IceGitTransferProgress new.

        checkoutOptions checkoutStrategy: LGitCheckoutStrategyEnum git_checkout_force.
        checkoutOptions progressCallback: IceGitCheckoutProgress new.

        repo clone: url options: cloneOptions.

        (LGitRemote of: repo named: 'origin')
                lookup;
                setUrl: url.

        ] in IceGitClone>>execute in Block: [location ensureCreateDirectory....
FullBlockClosure(BlockClosure)>>on:do:
IceGitClone>>execute
IceRepositoryCreator>>cloneRepository
[
                self validate.
                self isCloning
                        ifTrue: [ self cloneRepository ]
                        ifFalse: [ self addLocalRepository ] ] in IceRepositoryCreator>>createRepository in Block: [...
FullBlockClosure(BlockClosure)>>on:do:
IceRepositoryCreator>>createRepository
[ repository := builder createRepository ] in MCGitHubRepository(MCGitBasedNetworkRepository)>>createIcebergRepositoryFor: in Block: [ repository := builder createRepository ]
FullBlockClosure(BlockClosure)>>on:do:
MCGitHubRepository(MCGitBasedNetworkRepository)>>createIcebergRepositoryFor:
[ ^ self createIcebergRepositoryFor: urlToUse ] in MCGitHubRepository(MCGitBasedNetworkRepository)>>createIcebergRepositoryWithFallbackFor:url: in Block: [ ^ self createIcebergRepositoryFor: urlToUse ]
FullBlockClosure(BlockClosure)>>on:do:
MCGitHubRepository(MCGitBasedNetworkRepository)>>createIcebergRepositoryWithFallbackFor:url:
[ | remote |
                        remote := IceGitRemote url: remoteUrl.
                        self createIcebergRepositoryWithFallbackFor: remote url: remoteUrl ] in MCGitHubRepository(MCGitBasedNetworkRepository)>>getOrCreateIcebergRepository in Block: [ | remote |...
OrderedCollection(Collection)>>detect:ifFound:ifNone:
OrderedCollection(Collection)>>detect:ifNone:
MCGitHubRepository(MCGitBasedNetworkRepository)>>getOrCreateIcebergRepository
IceGithubRepositoryType>>mcRepository
Iceberg class>>mcRepositoryFor:
./pharo-ui: line 11: 1859423 Aborted                 (core dumped) "$DIR"/"pharo-vm/pharo" "$@"



```

<blockquote><img src="https://avatars.githubusercontent.com/u/1838382?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/opensmalltalk-vm">pharo-project/opensmalltalk-vm</a></strong></div><div>This is the VM used by Pharo. Contribute to pharo-project/opensmalltalk-vm development by creating an account on GitHub.</div></blockquote>

**Comment by gcotelli** [comment]
It also happens in the VM compiled on 2021-05-21

```
/home/gcotelli/Programming/Pharo-9/pharo-vm/lib/pharo
PharoVM version:5.0-Pharo 9.0.0 built on May 21 2021 21:44:15 Compiler: 5.4.0 20160609 5.4.0 20160609 [Production Spur 64-bit VM]
Built from: CoInterpreter * VMMaker-tonel.1 uuid: 527d40fe-3d7f-0d00-ab0b-29d80aa96449 May 21 2021
 With:StackToRegisterMappingCogit * VMMaker-tonel.1 uuid: 527d40fe-3d7f-0d00-ab0b-29d80aa96449 May 21 2021
 Revision: c62f356 - Commit: c62f356 - Date: 2021-05-21 21:28:11 +0200
```

[crash.dmp.txt](https://github.com/pharo-project/pharo/files/6557156/crash.dmp.txt)

I've just downloaded a new VM and image with:\

```
curl https://get.pharo.org/64/90+vmLatest | bash 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3084  100  3084    0     0   2587      0  0:00:01  0:00:01 --:--:--  2585
Downloading the latest 90 Image:
    http://files.pharo.org/get-files/90/pharoImage-x86_64.zip
Pharo.image
Downloading the latest pharoVM:
        http://files.pharo.org/get-files/90/pharo-vm-Linux-x86_64-latest.zip
pharo-vm/pharo
Creating starter scripts pharo and pharo-ui
```

opened the image and evaluated in a Playground
```
Metacello new
	baseline: 'WillowBootstrap';
	repository: 'github://ba-st/Willow-Bootstrap:release-candidate/source';
	load: 'Development'.
```

**Comment by gcotelli** [comment]
Ok.. some updates here. The problem seems to be with Linux distros using a new version of libgit2 that is not compatible (like Manjaro). Esteban sent me a VM compiled for Manjaro and it worked flawlessly. 

The short-term solution is to compile your own VM.
The long-term solution to this problem is to finish the work on OBS (Open Build System), so the VM will be packaged for each supported distro.
