### ISSUE TITLE
When we extract a method if there is a method already with the same body we should not enter the name of the extracted method

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8869]
When we extract a method if there is a method already with the same body we should not enter the name of the extracted method

**Comment by Lin777** [comment]
The extract method refactoring, looks for a method that has the same body as the extracted code.

- In case of finding it (either in the same class or in the superclasses), it uses this method name for the extraction
- If it doesn’t find any method, it asks for a new name, and then creates the new extracted method.

**Comment by Ducasse** [comment]
Ok. So probably it did not find it because of the other issue. So I think that we can close this issue.
