### ISSUE TITLE
Calypso and PanelMorph are still breaking

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8875]
![Screenshot 2021-03-25 at 12 33 49](https://user-images.githubusercontent.com/432549/112466741-75f36c80-8d66-11eb-9461-7507dc75d64e.png)

**Comment by Ducasse** [comment]
[Debugger-Stack-PanelMorph-2021-03-25-123526.fuel.zip](https://github.com/pharo-project/pharo/files/6204319/Debugger-Stack-PanelMorph-2021-03-25-123526.fuel.zip)

**Comment by Ducasse** [comment]
PanelMorph(Object)>>error:
PanelMorph(Morph)>>privateAddMorph:atIndex:
PanelMorph(Morph)>>replaceSubmorph:by:
ClyNotebookMorph(SpNotebookMorph)>>updateContentMorph:with:
ClyNotebookMorph(SpNotebookMorph)>>updatePageIndex:
ClyNotebookMorph(TabGroupMorph)>>update:with:
MorphChangedWithArguments>>deliverTo:
ClyNotebookMorph(Morph)>>handleUpdate:
MessageSend>>value:
MessageSend>>cull:
MessageSend>>cull:cull:
[action cull: anAnnouncement cull: announcer] in AnnouncementSubscription>>deliver: in Block: [action cull: anAnnouncement cull: announcer]
FullBlockClosure(BlockClosure)>>on:do:
[ Processor terminateActive ] in BlockClosure>>on:fork: in Block: [ Processor terminateActive ]

**Comment by Alisu** [comment]
Hello Stéphane,
I tried loading the image you linked but it requires at least Bloc and then I don't have "#ClyGtExampleScript".
Could you send the dependencies ?

**Comment by Ducasse** [comment]
I do not have it anymore. Else this is a pharo90 + newBloc baseline loaded.

**Comment by estebanlm** [comment]
I think this is fixed
