### ISSUE TITLE
Senders browses wrongly

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#8886]
```
   results := results select: [ :e | self does: e matches: aString ] ]
```

- put cursor on "does"
- cmd + n
- => wrongly search senders of #select: instead of `#does:matches`

**Comment by guillep** [comment]
I've tracked this down, the problem seems to be only happening in Spec based text editors.
In spec, if there is no text selection, it selects the entire line, thus it does not matter where the cursor is, the whole line is selected.

**Comment by guillep** [comment]
```smalltalk
SpCodePresenter >> selectedSelector
	
    ^ CNSelectorExtractor new extractSelectorFromSelection: self selectedTextOrLine
```

**Comment by guillep** [comment]
and this method, that calls `selectedSelector` forces also the selection of the line:

```smalltalk
doBrowseSenders
	| env variableOrClassName |

>>>	variableOrClassName := self selectedTextOrLine trimmed asSymbol.
	variableOrClassName ifEmpty: [ ^ self ].
	 
	env := self environment.
	env isBehavior ifTrue: [
		(env hasSlotNamed: variableOrClassName) ifTrue: [
		 ^ self systemNavigation browseAllAccessesTo: variableOrClassName from: env ] ].

	(env bindingOf: variableOrClassName) 
		ifNotNil: [ :ref | ^ self systemNavigation browseAllSendersOf: ref ].
	
	"If this is not a class, behave as SpBrowseMethodReferencesCommand"
	self basicBrowseSenders
```

**Comment by maxwills** [comment]
> ```smalltalk
> SpCodePresenter >> selectedSelector
> 	
>     ^ CNSelectorExtractor new extractSelectorFromSelection: self selectedTextOrLine
> ```

I remember addressing that problem in https://github.com/pharo-project/pharo/pull/8462
It seems that the fix was overwritten, and don't know why. (Should it be re-fixed?)

For the second comment, I don't remember working in doBrowseSenders. I'd say it's a different but related issue (about using selectedTextOrLine instead of the "word" under the cursor if there is no selection).

**Comment by guillep** [comment]
Hi @maxwills I checked your PR #8462.
From what I understand, your changes to `CNSelectorExtractor` are still there in the latest image, luckily.
It seems the changes in Spec have been overwritten, probably due to a new merge of Spec without harvesting previously changes from Pharo, I'm sorry for that.

**Comment by MarcusDenker** [comment]
I made a PR for spec with the lost code:

https://github.com/pharo-spec/Spec/pull/1056
