### ISSUE TITLE
Doing a Step Over an assert in a test breaks the debugger

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#8892]
- Have a test with a failing assert
- Restart the method
- Do Over until the assert fails and open a new window
- Close the newly open window.
- Restart the original test
- Click on over or where is and nothing happens.

**Comment by StevenCostiou** [comment]
Interesting, that also happens in Pharo 7 (so I guess Pharo 8 too).
It seems that the assertion failures somehow trigger the opening of a new debugger with incomplete debugging information (context, etc.).
