### ISSUE TITLE
BestNodeFor: barks!

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8899]
Hi pablo

I have the impression that we have a regression due to recent changes in bestNodeFor:

When I try to edit the string (like adding the missing ) in the string 
I get a lot of error. 

```
testImportFromStringCreateSeries

	self importFromString: '(author : Wolfe, Gene
		(serie : books
			(title : le sortilege de Castelview (price : 2.4) (read :false))
			(title : toutes les couleurs de l''enfer (comments : nouvelles) (read : false)))
		(serie : le Live du long soleil
			(title : Cote nuit (price : 2.4) (number : 1) (read :false)))'
```

**Comment by Ducasse** [comment]
It looks like the system is working on the previous version of the method.

When I started to code I wrote

```
testImportFromStringCreateSeries

	self importFromString: ''
```

Then modified the string.

**Comment by Ducasse** [comment]
I reverted bestNodeFor: changes.

**Comment by noha** [comment]
Thanks. This drove me mad yesterday
