### ISSUE TITLE
Merge of NewTools let a lot of methods that are overriden in the original places

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#8910]
These are extensions that are also in Spotter and methods that are defined in Reflectivity, and now they are extensions.

**Comment by MarcusDenker** [comment]
the recent gtDisplayString string changes where touching Newtools, too, but were done in the image, not the newtools (see https://github.com/pharo-project/pharo/pull/8938 )

**Comment by pavel-krivanek** [comment]
I guess this can be closed
