### ISSUE TITLE
The "whenX" events of SpLabelledTextInput produce does not understand problems

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#8916]
In class `SpLabelledTextInput` the two methods `whenTextChanged:`and `whenTextIsAccepted:` produce message not understood. The reason is that the delegation in those methods to the underlying `SpTextInputFieldPresenter` fails because the two methods do not exist in class `SpTextInputFieldPresenter`.

The problem is in the code:
```smalltalk
SpLabelledTextInput>>whenTextIsAccepted: aBlock

	self input whenTextIsAccepted: aBlock
```
It seems like the original implementors of `whenTextIsAccepted` are classes which are now deprecated. 

One possible _temporary_ solution is to let `whenTextIsAccepted:` delegate to 'whenSubmitDo:' which works.

Regarding the `whenTextChanged:`, it is a simple problem, namely that the naming is inconsistent throughout the system. Sometimes the method is named `whenTextChanged:` and sometimes it is named `whenTextChangedDo:`. In this case it is necessary to make the name change in the delegation:

```smalltalk
whenTextChanged: aBlock

	self input whenTextChanged: aBlock "should call whenTextChangedDo: instead"
```

Further, the `whenTextChangedDo:' passes the new and old texts as its block arguments, where the 'whenSubmitDo:' is passed the underlying morph. 

All in all, it is relatively simple to fix, but I am uncertain about what choices to make here.

**Comment by estebanlm** [comment]
fixed upstream (this thing was removed)
