### ISSUE TITLE
System browser or Calypso editor and line numbers

### ISSUE THREAD

**Issue by akevalion** [guillep/pharo-core#8925]
The method code editor uses a toolbar icon labeld with `+L`, this button adds line numbers to the code editor.

**Expected behavior**
Use the line number should be the default behavior

Change the method `fillStatusBar` with `toggle` lines numbers will appear for all new system browsers.
```Smalltalk
fillStatusBar
	| position |
	super fillStatusBar.
	
	position := statusBar addContextItem: (ClyCursorPositionLabelMorph of: textMorph).
	position comeToFront.
	statusBar addCommandItem: (ClyTextWrapModeSwitchMorph of: textMorph).
	statusBar addCommandItem: ((ClyTextLineNumbersSwitchMorph of: textMorph)
		toggle;
		yourself).
	statusBar addCommandItem: (ClyFormatAsReadSwitchMorph of: textMorph).
	
	statusBar addCommandItem: (ClyMethodTagsAndPackageEditorMorph for: self).
	
```

Another way to enable this feature could be use a Setting configuration in pharo, then users in pharo can choose between use or not line numbers in all new system browsers.

**Comment by MarcusDenker** [comment]
I do not think that this should be the default.. but a setting would be nice

**Comment by akevalion** [comment]
Hi, I have added a setting I forgot to remove the issue.
<img width="546" alt="image" src="https://github.com/pharo-project/pharo/assets/10532890/ac9409db-4693-4a80-a770-4a99468af69f">
