### ISSUE TITLE
Strange selection interaction

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8933]
- open Playground
- type
- Iterator
- browse class you get the pop up shown 
- select one of them.... 
- nothing happen.
![Screenshot 2021-04-01 at 13 43 14](https://user-images.githubusercontent.com/432549/113289532-a00dd700-92f0-11eb-85c4-ed7a865bfea7.png)

**Comment by MarcusDenker** [comment]
this is now working correctly: it adds a binding to the requestor for "Iterator"
