### ISSUE TITLE
Urgent: Please fix NoMoreBitsLeftException on 8bit platform today

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#8934]
**Bug description**
When multiplying 8 bits with itself Pharo throws a NoMoreBitsLeftException

**To Reproduce**
1. Compile the MOS Technology 6510 virtual machine for Commodore 64
2. use Load "Pharo",8,1 to load it from floppy disk
3. Start with "Pharo Pharo.image" on the central command line
4. Now evaluate 

```Smalltalk
   8 bit * 8 bit 
```   
in a Pharo playground 
5. See error in debugger

**Expected behavior**
We should support more bits. It should at least give 64 bits on a C64. Maybe it is a VM problem

**Screenshots**

![image](https://user-images.githubusercontent.com/5980033/113325717-158d9d80-9319-11eb-9894-4a3618c76b95.png)

**Version information:**
 - OS: Commodore 64 Native platform
 - Version: from 1981
 - Pharo Version Pharo 10

*Important side note:*
On the same platform
```Smalltalk
   Date today 
```   
returns **1 April 2021** today. Strange - looks like someone was fooling around

**Comment by MarcusDenker** [comment]
Fixed :-)
