### ISSUE TITLE
Navigating overridden methods is broken

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#8957]
In calypso there are the little arrows that allow to look for overridden methods.

![image](https://user-images.githubusercontent.com/708322/113508696-b8306100-9551-11eb-9c3b-03e0aae09363.png)

In Pharo 9.0.0
Build information: Pharo-9.0.0+build.1278.sha.325e1924aab0781936bb59e421acee3753a33098 (64 Bit)

Clicking in the arrow does not lead us to the overridden methods, but does something strange. Clicking the arrow up asks something about selecting another scope (?) (don't mind the button colors, I'm playing with that).
![image](https://user-images.githubusercontent.com/708322/113508722-d9914d00-9551-11eb-8723-ff854f253da0.png)

I don't understand what this is, I never selected a scope before, so this kind of gets in my way.

**Comment by MarcusDenker** [comment]
the same happend to me when I tried to copy/paste the name of a method with the button

**Comment by MarcusDenker** [comment]
This might be cause by https://github.com/pharo-project/pharo/pull/8950

**Comment by Ducasse** [comment]
Yes probably. I will ask evelyn to have a look.

**Comment by Ducasse** [comment]
Hello evelyn can you have a look because one of your changes got more impact than necessary.

**Comment by Lin777** [comment]
Yes, sorry I modified a superclass and caused that. I have corrected most of it, I will review all the other commands to see if they were affected. At the moment the first corrections are in a PR

**Comment by Ducasse** [comment]
Thanks evelyn
