### ISSUE TITLE
hidden Undeclared instance variables after renaming

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#8966]
**Bug description**
When you rename or remove instance variable in the class definition, normally, all methods that use it are highlighted as red becuase they use Undeclared variable. But it is not the case for usages of the instance variables that are inside closures. 

**To Reproduce**
1. Define following class with variable named var1:
```smalltalk
Object subclass: #MyClass
	instanceVariableNames: 'var1'
	classVariableNames: ''
	package: 'Issue'
```

2. create these two methods:

```
var1 
	^ var1

msg 
	self in: [ :anObject | var1 := 1 ]
```

3. change `var1` in the class definition to `var2`
4. The methods list then looks like this

![Pharo_gZjDBskVnx](https://user-images.githubusercontent.com/572494/113726484-90c5c980-96f4-11eb-959f-ba74f9119314.png)

**Version information:**
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1284.sha.2037e82beccc07fb1537c592f76f64731cbae029 (64 Bit)

**Comment by MarcusDenker** [comment]
The method in CompiledMethod needs to be updated to iterate over all nested literals


```Smalltalk
usesUndeclareds
	"this is mixing Undeclareds and Obsoletes, maybe we should have two methods"
	self withAllNestedLiteralsDo: [:each |
				each class == UndeclaredVariable ifTrue: [^true].
				(each value isBehavior and: [ each value isObsolete ]) ifTrue: [^true]].
	^false
```
