### ISSUE TITLE
Adding a breakpoint using the context menu does not work in the latest build

### ISSUE THREAD

**Issue by rolandbernard** [guillep/pharo-core#8974]
**Bug description**
When trying to add a Breakpoint from the context menu in the method source code editor, the latest build will not add a breakpoint. No breakpoint is visible on the side of the editor nor in the 'Browse breakpoints'-window. The code will also not break when executing, so I think there is a problem adding the breakpoint.

**To Reproduce**
1. Open the latest Pharo image
2. Open any method
3. Try to add a breakpoint using the context menu (Right click->'Debugging'->'Add breakpoint')
4. See that no breakpoint was added

**Expected behavior**
A breakpoint should be created and visible on the left of the code and in the list of all breakpoints.

**Version information:**
 - OS: Windows 10 64bit
 - Pharo Version: Pharo9.0.0 build: 1289, commit: 2fed4c7, date: 7 April 2021

**Expected development cost**
I do not know. I am currently not sure where the problem is.

**Additional context**
After doing some git bisection, it seems the issue starts with commit 71a5c21719c27beae2ab6a83c744e6c5c1fdc29e.

**Comment by MarcusDenker** [comment]
Thanks for the report.. very odd. All the breakpoint tests are green... and the code to set the breakpoint in the AST is called. But then it is not there. I will investigate.

**Comment by MarcusDenker** [comment]
The reason seems to be that we now always compile a *new* AST in ClyMethodEditorToolMorph>>#currentEditedAST

```Smalltalk
currentEditedAST

	^ self getASTFor: self pendingText
```

Then we set the breakpoint in that new AST, which means that the Metalink mechanism does not see the annotation, because we will on accept compile again another AST from source.

**Comment by guillep** [comment]
The API at the calypso level is very confusing.
 - you want to do syntax highlighting, code navigation, (maybe even refactorings) on the code you are editing and not the original code of the method.
 - for the breakpoint this is a blurry line :) a breakpoint will only work on compiled code. Other IDEs bind breakpoints to the original code and let breakpoints be out-of-sync with the code you are looking at...

An alternative would be that installing a breakpoint forces you to accept/compile the code, but I wouldn't do that without asking for confirmation to the user, and that would be a bit disruptive...

**Comment by MarcusDenker** [comment]
Maybe the ClyMethodEditorToolMorph needs to have an ivar for the AST. It will start with the "aMethod ast", then it will be updated with each keystroke. And then, when we accept, we compile that AST, not the text. 

This should make all the cases work: if you just browse and add a breakpoint, if you edit and add a breakpoint you can save, but changing more will remove the breakpoint again (as it is AST based, not line based)

**Comment by MarcusDenker** [comment]
PR: https://github.com/pharo-project/pharo/pull/9045
