### ISSUE TITLE
Selector extraction for browsing senders/implementors does not work for for multi-line calls

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#8978]
**Bug description**
Selector extraction for browsing senders/implementors does not work for for multi-line calls. It only takes into account code on the line with cursor.

**To Reproduce**
1. In some class, create this method:
```smalltalk
msg 

	self print: 'a' 
		prefix: 'p'  on: self 
```
2. go with cursor inside the first keyword part - `print:`
3. pres Ctrl + M or platform equivalent to browse implementors
4. implementors for `print:` are shown

**Expected behavior**
Implementors for `print:prefix:on:` are snown.

Interesting is that `Shift + mouse move` above the selector determines all lines correctly

**Comment by guillep** [comment]
Hi @pavel, is this a spec based tool or a non-spec based tool?

This is probably related to https://github.com/pharo-spec/Spec/pull/1020

**Comment by pavel-krivanek** [comment]
this is in Calypso so non-Spec tool

**Comment by guillep** [comment]
Looks like this comes from:

```smalltalk
ClyTextEditor>>sendersOfIt
	| selector |
>>	self lineSelectAndEmptyCheck: [^ self].
	(selector := self selectedSelector) == nil ifTrue: [^ textArea flash].
	
	self sendersOf: selector
```

```smalltalk
ClyTextEditor>>implementorsOfIt
	| selector |

>>	self lineSelectAndEmptyCheck: [^ self].
	(selector := self selectedSelector) == nil ifTrue: [^ textArea flash].
	selector 	isCharacter ifTrue: [ ^ textArea flash ].
	self browser browseImplementorsOf: selector
```

Removing the call to `lineSelectAndEmptyCheck:` seems to do the trick, I'm not sure what side effect that could have...

**Comment by MarcusDenker** [comment]
as much as I understand it, we do not need it anymore: #selectedSelector will use the CNSelectorExtractor which does the right thing.

**Comment by pavel** [comment]
@guillep Thanks for notifying me, but it does not seem that I'm involved in this project in any way.

https://blog.github.com/2011-03-23-mention-somebody-they-re-notified/

<blockquote><img src="https://github.blog/wp-content/uploads/2011/03/8c7c75d8-bb5c-11e4-9f5a-67e10e98cf8e.jpeg" width="48" align="right"><div><img src="https://github.blog/wp-content/uploads/2019/01/cropped-github-favicon-512.png?fit=192%2C192" height="14"> The GitHub Blog</div><div><strong><a href="https://github.blog/2011-03-23-mention-somebody-they-re-notified/">Mention @somebody. They're notified. | The GitHub Blog</a></strong></div><div>Ever wish you could summon a particular someone to take a look at an issue or pull request? Now you can: When you @mention a GitHub username anywhere in the context of an issue or</div></blockquote>
