### ISSUE TITLE
Pharo finds incorrect cairo library in windows.

### ISSUE THREAD

**Issue by lopezca** [guillep/pharo-core#8985]
In windows, Pharo comes with its own cairo libray, called `libcairo-2.dll`, but when searching for it, it first looks for `cairo.dll` and then looks for `libcairo-2.dll`.

If there is a program on the system path with a `cairo.dll`, then Pharo will find the incorrect library and show an error.

In the following line, either flip the order of the libraries, or better yet, remove `cairo.dll` from the search items.

https://github.com/pharo-project/pharo/blob/a9b11d3dd063d98b26ad49e9c8daef862427e179/src/Athens-Cairo/CairoLibrary.class.st#L57

**Comment by Ducasse** [comment]
Thanks! for your contribution!

**Comment by tinchodias** [comment]
Aham! I recently changed that line

**Comment by tinchodias** [comment]
I can create a PR.

In my windows I don't have the cairo.dll so no problem:
```
CairoLibrary uniqueInstance versionString. "'1.14.12'"
CairoLibrary uniqueInstance libraryName asFileReference relativeToPath: FileSystem workingDirectory. "Path * 'pharo-vm' / 'libcairo-2.dll'" 
```

**Comment by tinchodias** [comment]
BTW, it's another version for Mac (vmHeadlessLatest in both):

```
CairoLibrary uniqueInstance versionString. "'1.15.4'"
CairoLibrary uniqueInstance libraryName asFileReference relativeToPath: FileSystem workingDirectory.
 "Path * 'pharo-vm' / 'Pharo.app' / 'Contents' / 'MacOS' / 'Plugins' / 'libcairo.2.dylib'"
```
