### ISSUE TITLE
Unwind mechanism during termination is broken - skips multiple unwind blocks and corrupts the image

### ISSUE THREAD

**Issue by isCzech** [guillep/pharo-core#8992]
Try the following example (three nested #ensure:):
```
| p |
p := [
	[
		[ ] ensure: [
			[ ] ensure: [
				Processor activeProcess suspend. 
				Transcript show: 'x1']. 
			Transcript show: 'x2']
	] ensure: [
		Transcript show: 'x3']
] fork.
Processor yield.
p terminate
```
===> x1

The unwind procedure is broken in that it prints just x1 and skips not only x2 but x3 as well ! You'd like to see them all.

I'll try to explain:

To terminate a suspended process we use two different mechanisms:
(1) we try to complete the inner-most unwind block halfway through its execution, and then
(2) we use simulation (!) to unwind the remaining unwind blocks that haven't started their execution yet

This approach introduces three bugs (or at least an undesirable outcome):

(i) Current implementation only attempts to complete the inner-most unwind block halfway through unwind (this part prints 'x1' in the example above). In my opinion it's desirable to attempt to complete the outer-most unwind block under currently evaluation (that would print 'x2').

(ii) What's even more disturbing is the termination unwind skips an outer unwind block that haven't even been started yet when it immediately precedes an inner unwind block (this is where 'x3' was skipped).

(iii) The worst part is #popTo is unable to deal with non-local returns during unwinds and the execution ends up in the wrong stack. This is causing the Unwind errors and the semantics of non-local returns is completely nonsensical as a result. It may be argued non-local returns shouldn't be used in unwind blocks in the first place (because they are 'dangerous') but that doesn't mean we shouldn't fix the procedure :)

If you execute (but first save your image):
```
[ self error ] valueUninterruptably

"and later:"

Semaphore new waitTimeoutMSecs: 50
```
it'll completely ruin your image - why? The termination via #popTo will leave the image in a corrupted state with an effective process still set rendering the image almost unusable. The worst part is the user won't notice anything and a simple code will run as usual - until an error or a crash happens. One of a few ways to see something's off is e.g.
`Processor activeProcess = UIManager default uiProcess` answers false (!)
or inspecting `Processor` to see the effective process is set during 'normal' work (no debugging involved).

My proposal:

Unless there's a serious reason I overlooked miserably, using simulation to complete unwinds is a mistake. It looks like it's not only complicated but also wrong. The easiest and most consistent solution is to simply extend the existing mechanism for completing halfway-through unwind blocks and let it deal with *all* unwind blocks - and that's it. The resulting  unwind (and non-local return) semantics is clean and intuitive, even consistent with e.g. VisualWorks. Check out the code in the PR.

I have to mention there are two tests failing with the new approach:

#testTerminationShouldProceedAllEnsureBlocksIfSomeWasFailed

The test uses the Unwind error as a means to achieve the projected result. Fixing the Unwind errors makes this test indeed fail :) The test's name suggests it tries to show the unwind should continue after an error during unwind but at the moment this logic more or less requires the presence of the unwind error. Other situations involving errors covered in (i) or (ii) don't follow the logic anyway - which is ok and can be adjusted to cover all reasonable cases and not just the unwind errors situations. 

#testIsTerminatingForcedTermination

As I understand it, this test does `process terminate` and should prove it unwinds correctly but it in some very convoluted way generates an exception and ends up terminating the process via #doTerminationFromYourself which in my opinion partly beats the purpose of the test to show the `terminator` is indeed NOT identical to `process`. I suspect it uses the Unwind error again and so it fails when the unwind error bug is fixed. The tested process is simple so no exception should be involved during termination unwind.

If I have misunderstood the purpose of these two tests could the author please correct me? Thanks!
best,
Jaromir

PS: so far tests are green but changing the approach from simulated termination (i.e. as if 'direct') to true 'indirect' termination may affect how some test are designed.

PPS: the role of #isTerminating is unclear to me - what did the author try to achieve exactly? I'd appreciate if someone could enlighten me :) Thanks!

PPPS: I'm aware #isTerminated is horribly wrong and I suggested a quick fix in Issue #2978 here: https://github.com/pharo-project/pharo/issues/2978#issuecomment-787130744. As Denis noted however, he's pushing another fix as part of a big PR #8567, so I'm sending a PR only for #doTerminationFromAnotherProcess.

Build information: Pharo-9.0.0+build.1295.sha.fbc079ba405c0b7289fdc7dc8dbc7f1f4fac3daa (64 Bit)
(Win 10 Pro 20H2)

**Comment by dionisiydk** [comment]
Hi @isCzech .

That's definitely super interesting :).

But I can't reproduce the x3 case. I modified your script to avoid "no update" in the transcript:
```Smalltalk
log := OrderedCollection new.
p := [
	[
		[ ] ensure: [
			[Processor activeProcess suspend.  ] ensure: [
				
				log add: #x1]. 
			log add: #x2] 
	] ensure: [
		log add: #x3]
] fork.
log
```
When I terminate this process I got #x1 and #x3 in the #log. It's really unbelievable that outer unwinds would not work as it would break too many assumptions.
So are you sure about this problem or what did I wrong?

I will check the halfway unwinds later.

**Comment by isCzech** [comment]
Hi @dionisiydk ,
thanks for your reply! The "x3 case" happens when the process gets suspended **inside** the ensure:
```
log := OrderedCollection new.
p := [
	[
		[ ] ensure: [
			[ ] ensure: [
				Processor activeProcess suspend.
				log add: #x1]. 
			log add: #x2] 
	] ensure: [
		log add: #x3]
] fork.
log 
p terminate
```
