### ISSUE TITLE
Iceberg should ask permission before saving the image on commit

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#8996]
**Describe the request**
A commit to a repo by iceberg triggers automatically a save of the image. it is quite problematic when:
- the image is heavy
- the image is in an instable state

However, is there maybe a valid reason to force the save of the image on commit?

**Expected behavior**
No save or ask the user for save.

**Expected development cost**
Low

**Version information:**
 - OS: Win
 - Version: 10
 - Pharo Version Build information: Pharo-9.0.0+build.1293.sha.a9b11d3dd063d98b26ad49e9c8daef862427e179 (64 Bit)

Label: Large-Images

**Comment by Ducasse** [comment]
Vincent there is a tick to say that you want to automatically save or not.

**Comment by Ducasse** [comment]
![Screenshot 2021-04-09 at 10 02 35](https://user-images.githubusercontent.com/432549/114149025-baf8d080-991a-11eb-8556-f6458c6e2742.png)

**Comment by Ducasse** [comment]
And I checked there is a setting to control the two behavior.
![Screenshot 2021-04-09 at 10 03 39](https://user-images.githubusercontent.com/432549/114149213-f4c9d700-991a-11eb-9986-48f429bd2c75.png)

**Comment by Ducasse** [comment]
So let us know if this solves your concerns.

**Comment by MarcusDenker** [comment]
It seems this is suddenly enabled by default, while it was off before.

We should change it  to be off by default again.

**Comment by VincentBlondeau** [comment]
I haven't see it... Thanks! It will solve it.

I join Marcus there: I think it should be disabled by default.

**Comment by Ducasse** [comment]
That should not be difficult :)

**Comment by pavel-krivanek** [comment]
Can be closed
