### ISSUE TITLE
Pharo 9: Cursor shown twice on recent Windows Insider Preview 21354 ISO

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#8998]
I tried today latest Pharo 9 freshly on the latest "Windows Insider Preview" version.
 - https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso 
 - https://docs.microsoft.com/en-us/windows-insider 

The ISO image download was announced recently (see https://blogs.windows.com/windows-insider/2021/04/07/announcing-windows-10-insider-preview-build-21354/)

Scenario:
So I used VirtualBox on the host Windows machine to install the ISO and setup a fresh "Windows 10 Preview" virtual machine for VirtualBox. Then I used Edge to download and install launcher.

Using Launcher I installed the latest Pharo 9 image to find the mouse pointer doubled:

![image](https://user-images.githubusercontent.com/5980033/114090426-b222e300-98b7-11eb-8a98-2ba614567267.png)

![image](https://user-images.githubusercontent.com/5980033/114090440-b8b15a80-98b7-11eb-8291-39485e73dbf2.png)

Clicking and mousing around is possible - so using menus and other is possible. But the cursor is shown two times...

**Comment by Ducasse** [comment]
Thanks for the report. A question: When you change the cursor like resizing a pharo window, the two copies are changing too?

**Comment by astares** [comment]
@Ducasse / @tesonep 

Yes, they change both equally and are doubled too.

![image](https://user-images.githubusercontent.com/5980033/114538029-31673c80-9c53-11eb-975f-0825adacbd09.png)

Must be a VM problem because the Pharo cursor within Pharo Launcher (which itself is also a Pharo app from a VM/image combination) is normal

**Comment by astares** [comment]
https://user-images.githubusercontent.com/5980033/114539301-a8510500-9c54-11eb-9e1f-5ed13c021098.mp4

**Comment by astares** [comment]
**Info for the Pharo 9 image that is not working**:

Virtual Machine
---------------
C:\Users\Admin\Documents\Pharo\vms\90-x64\Pharo.exe
CoInterpreterWithQueueFFI VMMaker-tonel.1 uuid: be795315-f06d-0d00-aab5-813a0e395221 Oct 13 2020
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: be795315-f06d-0d00-aab5-813a0e395221 Oct 13 2020
e829a1da - Commit: e829a1da - Date: 2020-10-13 15:43:09 +0200

Pharo 8.6.1 built on Oct 13 2020 07:39:23 Compiler: 4.2.1 Compatible Clang 8.0.1 (tags/RELEASE_801/final)
VMMaker versionString e829a1da - Commit: e829a1da - Date: 2020-10-13 15:43:09 +0200
CoInterpreterWithQueueFFI VMMaker-tonel.1 uuid: be795315-f06d-0d00-aab5-813a0e395221 Oct 13 2020
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: be795315-f06d-0d00-aab5-813a0e395221 Oct 13 2020

Image
-------
Pharo9.0.0
Build information: Pharo-9.0.0+build.1300.sha.0d9f5119fb264913405fc4f78fa2789f7776d475 (64 Bit)
Unnamed

![image](https://user-images.githubusercontent.com/5980033/114539968-eba77580-9c4c-11eb-99ba-cd0f56faee44.png)

**Comment by astares** [comment]
Alternativeley I tried to launch the same image with the *headless VM*

```
"C:\Users\Admin\Documents\Pharo\vms\90-x64-headless\Pharo.exe" --interactive
```
and select the  same image. 

This is a newer VM (than the non-headless VM the Launcher downloaded when starting the fresh Pharo 9 image the first time)

C:\Users\Admin\Documents\Pharo\vms\90-x64-headless\Pharo.exe
CoInterpreter VMMaker-tonel.1 uuid: c3ea3b0a-b87b-0d00-ab77-e134071fb71c Apr  6 2021
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: c3ea3b0a-b87b-0d00-ab77-e134071fb71c Apr  6 2021
215f9a3b - Commit: 215f9a3b - Date: 2021-04-06 16:43:00 -0400

Pharo 9.0.0 built on Apr  6 2021 16:40:59 Compiler: 4.2.1 Compatible Clang 8.0.1 (tags/RELEASE_801/final)
VMMaker versionString 215f9a3b - Commit: 215f9a3b - Date: 2021-04-06 16:43:00 -0400
CoInterpreter VMMaker-tonel.1 uuid: c3ea3b0a-b87b-0d00-ab77-e134071fb71c Apr  6 2021
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: c3ea3b0a-b87b-0d00-ab77-e134071fb71c Apr  6 2021

but I get the same result: the cursor is shown twice.

**Comment by astares** [comment]
The Pharo launcher (where the cursor is shown regular only a single time) is having the following VM/image combination:

Image
-----
C:\Users\Admin\AppData\Local\PharoLauncher\Pharo.image
Pharo8.0.0
Build information: Pharo-8.0.0+build.1140.sha.5e328f2d7e8ed65fbddfb761624df5a19d0400f7 (64 Bit)
Unnamed

Virtual Machine
---------------
C:\Users\Admin\AppData\Local\PharoLauncher\Pharo.exe
CoInterpreter VMMaker.oscog-eem.2509 uuid: 91e81f64-95de-4914-a960-8f842be3a194 Sep 13 2019
StackToRegisterMappingCogit VMMaker.oscog-eem.2509 uuid: 91e81f64-95de-4914-a960-8f842be3a194 Sep 13 2019
VM: 201907031441-pharo Guille@DESKTOP-MG6660L:projects/vm7/opensmalltalk-vm Date: Wed Jul 3 16:41:39 2019 CommitHash: 4e4c5b5a0 Plugins: 201907031441-pharo Guille@DESKTOP-MG6660L:projects/vm7/opensmalltalk-vm

Win32 built on Sep 13 2019 15:13:35 CEST Compiler: 4.2.1 Compatible Clang 5.0.1 (tags/RELEASE_501/final)
VMMaker versionString VM: 201907031441-pharo Guille@DESKTOP-MG6660L:projects/vm7/opensmalltalk-vm Date: Wed Jul 3 16:41:39 2019 CommitHash: 4e4c5b5a0 Plugins: 201907031441-pharo Guille@DESKTOP-MG6660L:projects/vm7/opensmalltalk-vm
CoInterpreter VMMaker.oscog-eem.2509 uuid: 91e81f64-95de-4914-a960-8f842be3a194 Sep 13 2019
StackToRegisterMappingCogit VMMaker.oscog-eem.2509 uuid: 91e81f64-95de-4914-a960-8f842be3a194 Sep 13 2019

**Comment by astares** [comment]
When I use the VM from the Launcher - but not with the launcher image but with the freshly downloaded Pharo 9 image

```
C:\Users\Admin\AppData\Local\PharoLauncher\Pharo.exe "C:\Users\Admin\Documents\Pharo\images\Pharo 9.0 - 64bit (development version, latest)\Pharo 9.0 - 64bit (development version, latest).image"
```
the cursor is normal and works. So it really looks like a problem of the newer VMs.

**Comment by pavel-krivanek** [comment]
Is it still relevant? I have never seen such behavior.

**Comment by astares** [comment]
Maybe it was that specific OS/Pharo combination. Lets close and only check if it reappears
