### ISSUE TITLE
MethodFinder class works as expected but not in the Finder tool / error in Finder documentation

### ISSUE THREAD

**Issue by readyready15728** [guillep/pharo-core#9000]
I was messing around with the examples in Finder concerning finding methods by expected output, which is very cool over all, but the attached screenshot explains two problems here:

![PharoScreenshot](https://user-images.githubusercontent.com/30027848/114106547-fce33180-989c-11eb-9fc0-1eccdd1993d8.png)

1. Running the `MethodFinder` code depicted in the Playground works properly but the proper expected result is not `'Friday'` but `#Friday`.
2. As said, running the Playground snippet works but attempting to do the same in Finder does not work.

I've had the same thing happen on both Pharo 8.0 and Pharo 9.0.

Here is my VM version info:

```
5.0-202002121043  Wed Feb 12 11:06:45 UTC 2020 gcc 5.4.0 [Production Spur 64-bit VM]
CoInterpreter * VMMaker-CompatibleUserName.1580983506 uuid: 7aff73cb-5a2e-5002-a356-37de4e762a49 Feb 12 2020
StackToRegisterMappingCogit * VMMaker-CompatibleUserName.1580983506 uuid: 7aff73cb-5a2e-5002-a356-37de4e762a49 Feb 12 2020
VM: 202002121043 https://github.com/pharo-project/opensmalltalk-vm.git
Date: Wed Feb 12 11:43:20 2020 CommitHash: 52202d8
Plugins: 202002121043 https://github.com/pharo-project/opensmalltalk-vm.git
Linux travis-job-93347cf3-9798-4672-8c23-706b9ceb049b 4.15.0-1028-gcp #29~16.04.1-Ubuntu SMP Tue Feb 12 16:31:10 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
plugin path: ./lib/pharo/5.0-202002121043 [default: /home/readyready15728/Pharo/vms/90-x64/lib/pharo/5.0-202002121043/]
```

And the output of `lsb_release -a` (though I doubt it's the problem, `CONTRIBUTING.md` said to include it):

```
No LSB modules are available.
Distributor ID: Linuxmint
Description:    Linux Mint 20.1
Release:        20.1
Codename:       ulyssa
```

**Comment by Ducasse** [comment]
Thanks for the report. This is indeed strange.
