### ISSUE TITLE
Introduce class Deprecation as Refactoring

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9033]
Basically 
Rename X into Z
+ define X empty as Z subclass
+ define isDeprecated as class method of empty X

**Comment by Ducasse** [comment]
I was thinking that deprecate could be just 
- define X empty as Z subclass
- define isDeprecated as class method of empty X
and not the rename part because like that we have two separate actions. 
But if I have rename Icon into IconMorph 
once it is renamed I do not know that IconMorph was named before Icon. 
As a developer I would have to remember.... so probably deprecate should be also doing a rename. 
Because if there is no rename, deprecation is just adding isDeprecated on the class side. 

So we should probably 
```
deprecate (oldClass, newName)
      rename(oldClass, newName)
      createSubclassOf(newName, oldClass name)
      basicDeprecateClass(oldClass name)
```

**Comment by Lin777** [comment]
Hi @Ducasse I created a refactoring with the previous specifications,

The new refactoring is called: RBDeprecateClassRefactoring and following I show its description

I am a refactoring to mark a class as deprecated. 
I am rename deprecated class references with the new class, then I add a subclass of deprecated class and finally I add #isDeprecated method in subclass created
	
Example
--------

Script:

```
(RBDeprecateClassRefactoring deprecated: #MyClassDeprecated in: #MyClassReplacement) execute
```
Before refactoring:
```
Object subclass: #MyClassDeprecated
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Example'

MyClassDeprecated subclass: #MyClassDeprecatedSubclass
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Example'

Object subclass: #MyClassReplacement
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Example'
	
Object subclass: #OtherClass
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Example'
	
OtherClass >> referenceToClass
	^ MyClassDeprecated new

OtherClass >> symbolReference
	#MyClassDeprecated
```
After refactoring:
```
Object subclass: #MyClassDeprecated
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Example'
	
MyClassDeprecated subclass: #MyClassDeprecated1
	instanceVariableNames: ''''
	classVariableNames: ''''
	package: ''Example''

MyClassDeprecated1 subclass: #MyClassDeprecatedSubclass
	instanceVariableNames: ''''
	classVariableNames: ''''
	package: ''Example''

Object subclass: #MyClassReplacement
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Example'
	
Object subclass: #OtherClass
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Example'

MyClassDeprecated1 class >> isDeprecated
	" Uses MyClassReplacement instead of MyClassDeprecated"
	^ true

OtherClass >> referenceToClass
	^ MyClassReplacement new

OtherClass >> symbolReference
	#MyClassReplacement
```

**Comment by Lin777** [comment]
But I found a class with similar functionality, this class is: RBApplyClassDeprecationRefactoring, and for the same example, this gets these results

After refactoring:
```
Object subclass: #MyClassDeprecated
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Example'

Object subclass: #MyClassReplacement
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Example'

MyClassReplacement subclass: #MyClassDeprecatedSubclass
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Example'

Object subclass: #OtherClass
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Example'

OtherClass >> referenceToClass
	^ MyClassReplacement new

OtherClass >> symbolReference
	#MyClassReplacement
```

**Comment by Lin777** [comment]
RBApplyClassDeprecationRefactoring does these tasks 

- all subclasses of the deprecated class will use the new class as superclass (optional)
 - rename all references in the code
 - move extensions of the deprecated class owned by other packages to the new class (optional)
 - remove the extensions (optional)

**Comment by Lin777** [comment]
So my question is, do we preserve the behavior of this class and just add the option to create a subclass of the deprecated class (which will have the method #isDeprecated)?

**Comment by Ducasse** [comment]
Yes it sounds a good idea. 
It was nearly good. But the subclass is important to ease migration
