### ISSUE TITLE
Forward delete does not work in Pharo 9 on macOS in RubTextFieldArea

### ISSUE THREAD

**Issue by rjriv** [guillep/pharo-core#9034]
**Bug description**
In macOS on P9, you are unable to forward delete (fn+delete) in the RubTextFieldArea (RubAbstractTextArea).

**To Reproduce**
1. Open a Playground.
2. Type in some text, like "abcdef".
3. Put the cursor between two letters.
4. Press fn+delete.
5. Notice that what actually happens is a backspace.

**Expected behavior**
The letter in front of the cursor should be removed.

**Screenshots**
N/A

**Version information:**
 - OS: macOS 11.2.3
 - Pharo Version 9.0 build 1302

**Expected development cost**
I thought it would be possible to add a #keyUp: method to RubAbstractTextArea and send #forwardDelete: to its editor, but I can't figure out how to stop the backspace message from being passed on as well, so it's possible this needs to be handled somewhere else deep in the keyboard event handling.

Interestingly, you can replace:

		at: 16r33 put: (self value: 16rFF08); "  kVK_Backspace                 = 0x33" 

with:

		at: 16r33 put: (self value: 16rffff);   "kVK_Delete                    = 0x33"	

in KeyboardKey>>initializeMacOSVirtualKeyTable and get forward delete, but then you can't backspace.

Hopefully these are some good clues for someone more familiar with the Keyboard handling.

**Comment by guillep** [comment]
This seems working in the following build

Pharo-9.0.0+build.1378.sha.b6da83ea31abe5f7404c48306785acdd7f305233 (64 Bit)

Were you using the latest VM?

**Comment by rjriv** [comment]
Hi @guillep, no, I was using the "default" PharoLauncher VM, but it does indeed seem to be working with the "headless" VM, once I figured out how to use it!

Thank you.
