### ISSUE TITLE
We should be able to remove a class even if it has a reference!!!

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9048]
![Screenshot 2021-04-12 at 22 06 39](https://user-images.githubusercontent.com/432549/114454995-84051200-9bdb-11eb-889f-93ce93709cff.png)

**Comment by Ducasse** [comment]
We should be able to remove a class and show the references!!!!!

**Comment by Ducasse** [comment]
Integrating the PR of giovanni was my mistake. :(

**Comment by gcorriga** [comment]
@Ducasse looking at this now.

FYI - the entry point for investigating this is ClyBrowserMorph>>#requestRemoveClassStrategyFor:
