### ISSUE TITLE
The 'meta' keyboard shortcut modifier should not be used in the UI

### ISSUE THREAD

**Issue by gcorriga** [guillep/pharo-core#9056]
**Bug description**
A few tools such as the system browser and the Iceberg repository browsers are showing the keyboard shortcuts of various items as 'Meta+'. This hurts discoverability since no modern, common keyboard layout includes a physical meta key.

Furthermore things are not consistent since the Transcript, the WorldMenu, and the main pane of the System browser still refer to physical keys such as Ctrl, Shift, or Alt.

Meta should be mapped to the key used by the platform (e.g. Cmd on mac keyboards, Ctrl on Windows keyboards).

**To Reproduce**
Open a system browser, bring up the context menu for a package or class.

**Expected behavior**
Shortcuts make use of the 'Ctrl' or 'Cmd' label.

**Screenshots**
![image](https://user-images.githubusercontent.com/7032660/114605505-0ea84880-9c92-11eb-94d9-f4a7876e540d.png)

**Version information:**
 - OS: Windows 10
 - Version: October 2020
 - Pharo Version Pharo-9.0.0+build.1310.sha.13e3f92b58f12217bf420f6a81621af3a54bb2e0 

**Expected development cost**
I can look into fixing this if someone points me to the right place in the code.

**Comment by guillep** [comment]
In OSX we have the correct character:

![image](https://user-images.githubusercontent.com/708322/114893134-b39b6080-9e0d-11eb-9171-af570258b867.png)

I'll check for windows

**Comment by guillep** [comment]
The code doing this seems to be around

```smalltalk
ToggleMenuItemShortcut >> normalize: aString
	"This is a hack to show better explained menu commands. 
	 WARNING: This is now really good, but is an easy and fast way to enhance accesibility of 
	 menu commands."

	self keyTextShortcuts do: [ :each |
		(aString includesSubstring: each caseSensitive: false)
			ifTrue: [ ^ self normalizeFullStyle: aString ] ].   
	^ self normalizeCondensedStyle: aString

ToggleMenuItemShortcut >> keyTextShortcuts
	^ #('cmd'. 'alt'. 'shift'.'ctrl'. 'meta' '⌘' '⇧')
```

**Comment by guillep** [comment]
But the string that arrives there is already "preformatted" for the platform by `KMShortcutPrinter`

**Comment by guillep** [comment]
And, shortcuts also define `printOsRepresentation` that seems to be doing something similar

**Comment by guillep** [comment]
To test these things we could use

```
$a command printOsRepresentation.
KMShortcutPrinter toString: $a command.
KMShortcutPrinter toString: $a meta.
```

And there is the class `KMShortcutPrinterTest` that has in the class side several configurations.

**Comment by estebanlm** [comment]
> In OSX we have the correct character:
> 
> ![image](https://user-images.githubusercontent.com/708322/114893134-b39b6080-9e0d-11eb-9171-af570258b867.png)
> 
> I'll check for windows

Notice that in mac correct way to show shortcut is with capital letter (and "shift" requires the ^ symbol). 
Maybe this is just an issue in the screenshot you're showing, I'm just pointing it because this would be the good moment to fix it ;)
