### ISSUE TITLE
Syntax highlighting confused by extra dot after temporaries definition

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#9063]
**Bug description**
When you have a comment after a temporaries definition with an additional dot at the end ( `| tmp | . "comment"` ), it confuses syntax highlighting, so it is not able to correctly set the comments color. It looks like only comments are affected by that.

I'm mentioning that just because it may be a sign of some deeper problems and other AST misinterpretation.

![CKCzQGZWK7](https://user-images.githubusercontent.com/572494/114826667-0c480a80-9dc8-11eb-8679-7ba5d3bf1d1a.gif)

**Comment by guillep** [comment]
It seems the problem is that when you add the dot the comment does not get parsed (or it does not get added into the sequence node).

![image](https://user-images.githubusercontent.com/708322/114875582-b9894580-9dfd-11eb-964b-3f7ad4e11e8b.png)

To check you can inspect and compare:

```smalltalk
RBParser parseFaultyMethod: 'msg

	| temp |
	
	"some comment"'
```

with

```smalltalk
RBParser parseFaultyMethod: 'msg

	| temp |.
	
	"some comment"'
```

**Comment by guillep** [comment]
Thing is, if we get picky in Pharo's grammar, the dot is a statement separator.
This means that the method with the dot has two statements, and the comment is in the second statement!

However, the AST does not model "empty statements". So I guess the comment should be attached to the sequence node. :)

However, when parsing the statements, it seems the comments at the end are only handled when the method has actual statements. See for example:

```smalltalk
>> parseStatementList: pragmaBoolean into: sequenceNode untilAnyCloserOf: aCollectionOfClosers
	...
>>>	statements notEmpty ifTrue: [ self addCommentsTo: statements last ].
	sequenceNode
		statements: statements;
		periods: periods.
	^ sequenceNode
```

That line should maybe read

```smalltalk
     statements 
            ifEmpty: [ self addCommentsTo: sequenceNod ].
            ifNotEmpty: [ self addCommentsTo: statements last ].
```

I'll write a test :)

**Comment by pavel-krivanek** [comment]
Thank you very much, Guille!
