### ISSUE TITLE
Categorize uncategorized methods in classes: GPolygon

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9080]
looks like GPolygon has been forgotten in https://github.com/pharo-project/pharo/pull/8824

**Comment by MarcusDenker** [comment]
I think this is loaded with Roassal

**Comment by astares** [comment]
@akevalion / @bergel Could you have a look?

**Comment by akevalion** [comment]
Hi I will review it

**Comment by akevalion** [comment]
Hi I have review it and I can not find uncategorized methods for GPolygon

https://github.com/pharo-contributions/Geometry

<blockquote><img src="https://opengraph.githubassets.com/16c27cb3b72e0391c0edb690aff61566609e6af5656c1c05f381cf1fe0d7a664/pharo-contributions/Geometry" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-contributions/Geometry">pharo-contributions/Geometry</a></strong></div><div>A simple geometry library for Pharo. Contribute to pharo-contributions/Geometry development by creating an account on GitHub.</div></blockquote>

**Comment by MarcusDenker** [comment]
{ #category : #'as yet unclassified' }
GPolygon class >> convexHullOn: aCollection [

https://github.com/pharo-contributions/Geometry/blob/master/src/Geometry/GPolygon.class.st

**Comment by MarcusDenker** [comment]
the method is on the class side

**Comment by akevalion** [comment]
I have created a PR on geometry, then this should be appear in the next roassal3 release I think
