### ISSUE TITLE
+ in floatArray changes the second array 

### ISSUE THREAD

**Issue by jmari** [guillep/pharo-core#9093]
do:

a :={ 1.2. 2.3. } asFloatArray.
b := { 1.2. 2.3. } asFloatArray.
c := a + b.
b 

cmd+p a FloatArray(2.4000000953674316 4.599999904632568)

it works right on Pharo 8

**Comment by MarcusDenker** [comment]
This seems to be introduced by https://github.com/pharo-project/pharo/pull/7622

I will commit a fix
