### ISSUE TITLE
Instance of SpCommand DNU #transform: in new inspector

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9094]
- inspect the following expression

```Smalltalk
ZnEasy get: 'https://www.pharo.org'
```
and click on "Breakpoints" in the new inspector:

![image](https://user-images.githubusercontent.com/5980033/115156279-ca4aed00-a083-11eb-8c9b-42314389be49.png)

this will give the following debugger:

![image](https://user-images.githubusercontent.com/5980033/115156295-dc2c9000-a083-11eb-916a-dba9e8b3c3ea.png)

**Comment by Ducasse** [comment]
Steven I taged for you but I do not know if this is correct.

**Comment by MarcusDenker** [comment]
This seems to be fixed with the latest newtools merge
