### ISSUE TITLE
Create button is greyed out on a class that is not defined 

### ISSUE THREAD

**Issue by ghost** [guillep/pharo-core#9099]
**Bug description**
When a run a test on a class that is not defined I expect that I can create the class 

**To Reproduce**
run this test : 
```
test01_ShouldBeAbleToScoreAGameWithAllZeros
	| result |

	result := bowlingCalculator scoreAfterRolling: #(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ) .
	self assert: result equals: 0
```  

and see in the debugger the create button greyed out. 

**Expected behavior**
I can create the class in the debugger 

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/76750970/115229697-a46d2900-a113-11eb-92b1-f7436f41a77c.png)

**Version information:**
 - OS: Windows 10 
 - Version: 
 - Pharo Version  9

**Comment by ghost** [comment]
Just thinking aloud
Can the problem be that the test is a menber of the ExercismTest and not a member of the Testclass ?
ExercismTest is a member of the TestClass

**Comment by StevenCostiou** [comment]
Is this with the latest Pharo?
Can you put the image version?

**Comment by StevenCostiou** [comment]
I just tested, from the playground and froma failing test case, and it works.
I downloaded a fresh image.

![Screenshot 2021-04-20 at 09 41 45](https://user-images.githubusercontent.com/26929529/115357161-a0e1ac80-a1bc-11eb-9726-279b98a6a3f9.png)

It could be that the image you are using is too old?
Can you go to help>about and copy/paste the build number?

**Comment by ghost** [comment]
yep I think so 

When I do help -> about pharo I see this : 

Pharo 9.0.0
Build information: Pharo-9.0.0+build.1335.sha.05eecc36981bdaaae2a32ad8e06c4217eff1dc3f (64 Bit)

**Comment by StevenCostiou** [comment]
hmm, odd, mine is 1340, so there is not much difference.
I will try to put that in the setup method to see if any difference.

**Comment by StevenCostiou** [comment]
One thing: we don't have the same syntax highlighting. My undeclared variable is red (even with the white theme) and not "blue italic" like yours.
Does "blue italic" has another meaning? 
Trying to check...

**Comment by ghost** [comment]
I tried on 1340 and I see the same problem

**Comment by StevenCostiou** [comment]
How can I reproduce your exact case?

**Comment by ghost** [comment]
Hmm, have you ever worked with exercism ?
I can tell you the exact steps and you need a key. I can give you my key but not in public

**Comment by ghost** [comment]
I told you onm discord the exact steps
I can also put the classes on github if you like

**Comment by ghost** [comment]
Use this files :  https://www.dropbox.com/t/rOg9pXvgKGw1Gy9G

and run the first test of Exercism@Bowling

<blockquote><img src="None" width="48" align="right"><div>Dropbox</div><div><strong><a href="https://www.dropbox.com/transfer/AAAAAP9CaoWkP0wxaaYr2SvusFnCXmjUn3k3Yef6UxlRZp_lZSdI4is">r. wobben sent you 2 items</a></strong></div><div>exercism.changes + 1 more item</div></blockquote>

**Comment by ghost** [comment]
Wierd 

When I do 

Bob new.  in the playground . Bob is red 

When I do 

Bowling new.   Bowling is blue..

Both on build 1340

![afbeelding](https://user-images.githubusercontent.com/76750970/115376064-a811b600-a1ce-11eb-8a73-bb6679dedd52.png)

**Comment by ghost** [comment]
I think I found the culprit.

As soon as I deleted the Pharo70 class everything works fine

but also then the class is not made only the new method

**Comment by StevenCostiou** [comment]
> Wierd
> 
> When I do
> 
> Bob new. in the playground . Bob is red
> 
> When I do
> 
> Bowling new. Bowling is blue..
> 
> Both on build 1340
> 
> ![afbeelding](https://user-images.githubusercontent.com/76750970/115376064-a811b600-a1ce-11eb-8a73-bb6679dedd52.png)

Ah! then `Bowling` is not an undeclared class but a `nil` object, a global variable maybe?
For now if it's nil, then it gives a DNU but there is no support for creating methods in the nil class (from the debugger I mean).

**Comment by ghost** [comment]
???

Why schould the debugger think it's a nil object.
at that point I expect to see that the class is made

**Comment by StevenCostiou** [comment]
Your error in your original screenshot was `new was sent to nil` and the receiver was `Bowling`.
Select `Bowling` and  try *inspect*.
Maybe try a right click and browse references if it is somewhere in the menus.
I don't think this is a class, or that class is nil (which is odd...).

**Comment by ghost** [comment]
then I see this 

![afbeelding](https://user-images.githubusercontent.com/76750970/115397480-6d1b7c80-a1e6-11eb-971e-d981bfa015a6.png)

**Comment by ghost** [comment]
Create is still greyed out but when I choose there the create class the right class is made

**Comment by StevenCostiou** [comment]
There is a problem with your image.
You miss reflective operations in the `UndefinedObject` class.

![Screenshot 2021-04-27 at 16 42 37](https://user-images.githubusercontent.com/26929529/116261101-9e142800-a777-11eb-95da-7013954f647f.png)

So, regarding the issue:
- I started a fresh P9 image: I have the reflective protocol in `UndefinedObject` and the class creation button works
- I loaded Exercism using the same link as in the image you provided: the reflective protocol in `UndefinedObject` disappeared and the class creation button does not work anymore
 
Loading Exercism messes with the `UndefinedObject` class when it is loaded... this issue needs to be checked out by Exercism people.

For now, you can use this workaround:
- manually copy paste these two methods from a fresh image into your image
- It seems sometimes there is another problem and no debugger opens, but I will open a new issue for that. For TDD to work properly you have to go into settings>tools>debugging and select *OupsDebuggerSelector* in the *Debugger Selection Strategy* combo box.

**Comment by Bajger** [comment]
@StevenCostiou Hello Steven! Could you please refer to proper method or commit that fixes this issue to Pharo 9 (is it just `UndefinedObject>>doesNotUnderstand:` or more? ) We'd cherrypick your fix to the Exercism package and create Pharo version dependent baseline for P9 of Exercism project. 
Thanks in advance!
Current implementation of DNU on Exercism package (that works on P7) looks following.
```
doesNotUnderstand: aMessage
	<debuggerCompleteToSender>
	"Handle the fact that there was an attempt to send the given message to an Undeclared variable (nil), hence the receiver does not understand this message (typically #new)."
	"Testing: (3 activeProcess)"

	| exception resumeValue node |
	
	(node := self findUndeclaredVariableIn: thisContext sender sourceNodeExecuted) ifNil: [ 
		 ^super doesNotUnderstand: aMessage ].
				
	(exception := ClassNotUnderstood new)
			message: aMessage;
			variableNode: node;
			receiver: self.
			
	resumeValue := exception signal.
	^ exception reachedDefaultHandler
			ifTrue: [ aMessage sentTo: self ]
			ifFalse: [ resumeValue ] .
			
	
```

**Comment by StevenCostiou** [comment]
Hi, I am sorry there is no fix :/
The base Pharo 9 implementation is correct.
Loading Exercism packages overrides part of the Pharo 9 kernel.
The problem is this overriding from Exercism.

The methods you are missing can be found in Pharo 9:
- browse `UndefinedObject`class
- look at the `reflective operations` protocol

You need these two methods, that are removed by Exercism. You can copy paste them and it should work (let me know.

The cleanest way to solve this would be to have a baseline for Pharo 9, in which you do not override the `UndefinedObject`class at all.

**Comment by StevenCostiou** [comment]
And this is the DNU implementation that should be used in Pharo 9 (also in `UndefinedObject`): 

```Smalltalk
doesNotUnderstand: aMessage

	"Handle the fact that there was an attempt to send the given message to an Undeclared variable (nil), hence the receiver does not understand this message (typically #new)."

	"Testing: (nil activeProcess)"

	<debuggerCompleteToSender>
	| exception resumeValue node |
	[ 
	node := self findUndeclaredVariableIn:
		        thisContext outerContext sender sourceNodeExecuted ] onErrorDo: [ :ex | 
				"This is ugly, but we have a dependency with Opal compiler and 
				it should be extracted. If there is a failure during the bootstrap, this
				dependency produces an infinite loop"
		 ].
	node ifNil: [ ^ super doesNotUnderstand: aMessage ].

	(exception := VariableNotDeclared new)
		message: aMessage;
		variableNode: node;
		receiver: self.

	resumeValue := exception signal.
	^ exception reachedDefaultHandler
		  ifTrue: [ aMessage sentTo: self ]
		  ifFalse: [ resumeValue ]
```

**Comment by Bajger** [comment]
Thanks! Sorry for my confusion. We found that ExercismToolsV70 is no longer needed in P9 (which did method override). It helped to be removed from baseline for P9 on Exercism, but another story is recently reported issue, which you've already seen and is relevant for P9: https://github.com/pharo-project/pharo/issues/9956. Thanks for your insight so far.
