### ISSUE TITLE
AthensCanvas is not thread safe

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#9110]
**Bug description**
The `AthensCanvas` is not thread safe. It uses a global `PaintCache` (as a class variable) that is not protected by any Mutex.  When you try to render on multiple canvases in parallel, it can cause collisions. It is not easy to reproduce.

Possible solutions:
- make the paint cache for every canvas
- add a Mutex

What do you prefer?

**Comment by estebanlm** [comment]
mmm, @tinchodias, what do you think ?

**Comment by guillep** [comment]
I think caching per canvas is a neat idea
