### ISSUE TITLE
Spec2 example "Forms", dateInput not defined (nil)

### ISSUE THREAD

**Issue by labordep** [guillep/pharo-core#9117]
**Bug description**
In the Spec2 example "Forms" (the first).
When I click on the button "Submit" an error appears : #date was sent to nil.

**To Reproduce**
1. Help > Spec2 examples
2. Click on "Forms" example on the left
3. Click on Submit button

**Screenshots**
![Spec2Bug](https://user-images.githubusercontent.com/49183340/115534136-c2fc2d00-a297-11eb-9658-c69b72f32ea5.gif)
![image](https://user-images.githubusercontent.com/49183340/115533896-7fa1be80-a297-11eb-82a7-4f41516737a2.png)

**Version information:**
 - OS: Windows 10 Enterprise 
 - Version: version 1809
 - Pharo-9.0.0+build.1340.sha.74131739ce8164d0cd3fd66c843d7a4ecc823247 (64 Bit) 

Thanks.

**Comment by MarcusDenker** [comment]
in SpDemoStandaloneFormPresenter>>#initializePresenters there is some commented code:

	"dateLabel := self newLabel label: 'date:'.
	dateInput := self instantiate: SpDatePresenter.
	dateInput display: [ :item | item yyyymmdd ]."

After enabeling that again, the Forms example works for me

**Comment by MarcusDenker** [comment]
fixed upstream
