### ISSUE TITLE
RubTextEditor>>#unescapeCharacter:inString: should be implemented in String

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#9129]
**Describe the problem**
RubTextEditor>>#unescapeCharacter:inString: should be implemented in String

This looks like a method that is generally useful. 

- Implement on String (and check if we do not have a method that does that)
- add test

**Comment by guillep** [comment]
There are tests for that indirectly in 

![image](https://user-images.githubusercontent.com/708322/115725140-e00d2a80-a381-11eb-8199-f8323376002c.png)

**Comment by guillep** [comment]
But maybe some direct test would be nice, I don't know
