### ISSUE TITLE
Inconsistent explicit and implicit exception return 

### ISSUE THREAD

**Issue by isCzech** [guillep/pharo-core#9136]
Exception `return` should be handled the same whether it's called explicitly or not: The last line should send return: value to the exception instead of self - the exception return calls handlerContext return and although at the moment it's true the self is the handlerContext, in theory someone can e.g. change `return` definition and then the two returns won't be the same... Plus I think this is more consistent and readable. Thanks,
```
evaluateSignal: exception
	"The following primitive is just a marker used to find the evaluation context. 
	See MethodContext>>#isHandlerOrSignalingContext. "

	<primitive: 199>
	<debuggerCompleteToSender>
	| value |
	exception privHandlerContext: self contextTag.
	value := self exceptionHandlerBlock cull: exception.	
	"default return if not otherwise directed in handle block"
-	self return: value
+	exception return: value
```

**Comment by Ducasse** [comment]
The code of this method is not executed. It displays the logic of the primitive. 
We should check the primitive implementation to see.

**Comment by isCzech** [comment]
apologies, completely overlooked the primitive :)

**Comment by isCzech** [comment]
Actually, I thought it was a marker only...

**Comment by Ducasse** [comment]
Yes this one and 198 are markers only. 
So probably that code is executed. I'm fuzzy on it.

**Comment by isCzech** [comment]
Hi Stephane, I think I only applied what you wrote in Deep Into Pharo (2013 edition) on page 278 about the two returns being equivalent in Pharo - unless you do want to keep the two distinct: 'abandon' as simply returning the block's value and explicit 'return' as defined in Exception>>return (which may lead potentially to diverging behavior if someone modifies 'return'). Thanks

**Comment by isCzech** [comment]
Apologies, the two kinds of return as in
```
[] on: Error do: [:ex | ex return]
```
and
```
[] on: Error do: []
```
really are two distinct operations (and probably should remain as such). They are equivalent in Pharo thanks to their current implementation. I'm closing the PR.

**Comment by isCzech** [comment]
closed

**Comment by isCzech** [comment]
Reopened - sorry for confusion - see explanation / comments at #9137
