### ISSUE TITLE
New spotter is not able to report potential issues in the StSpotter >> #updateResultList: critical block

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#9138]
**Bug description**
Errors should be always be able to be debugged even if it is in a deferred action encapsulated in a mutex.

This piece of code here should be able to handle an exception coming from #queuedUpdateResultList.
```
updateResultList: aCandidateLink

	mutex critical: [ queue add: aCandidateLink ].
	updating ifTrue: [ ^ self ].
	
	self model schedule: [
		self application defer: [ 
			
			mutex critical: [self queuedUpdateResultList ] ] ]
```

**To Reproduce**
1. Put an halt as first statement in #queuedUpdateResultList 
2. Open the spotter
3. Write anything
4. Enjoy the freeze

**Expected behavior**
A debugger should open.
ALT + . should be able to unfreeze all.

**Version information:**
 - OS: Win10
Pharo9.0.0
build: 1354, commit: 1846e54, date: 23 April 2021

**Expected development cost**
High for me, low for @tesonep or @guillep 

**Additional context**
This tends to show some potential issues (or limitations?) in the ALT + .  mechanism that needs to be solved.

**Comment by Ducasse** [comment]
Hello vincent

Pablo and guille are usually not working on the debugger or new tools. Of course they help and they fixed a lot of issues in the past. They are often facing bugs since they live in the cutting edge. 

S.

**Comment by VincentBlondeau** [comment]
I tagged them since it is liked with some process management and I thought they were working on this. But you know better than me :)

Also, this issue is linked to: https://github.com/pharo-project/largeImages/issues/5
