### ISSUE TITLE
Cursor is too small when using display scaling

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#9145]
**Bug description**
The cursor is not scaling according to the parameters in the options.

<img width="1022" alt="mstsc_a7gVOeVHBG" src="https://user-images.githubusercontent.com/4706329/116055627-2f52a400-a67d-11eb-9a11-5fcbfb1b8902.png">

**To Reproduce**
![image](https://user-images.githubusercontent.com/4706329/116055915-7e98d480-a67d-11eb-8f86-1f1c305620de.png)

**Expected behavior**
bigger cursor

**Version information:**
 - OS: Win 10
Pharo9.0.0
build: 1354, commit: 1846e54, date: 23 April 2021

**Expected development cost**
Not too much

**Additional context**
Linked with https://github.com/pharo-project/pharo/issues/2883 ?

**Comment by VincentBlondeau** [comment]
Change to the VM seems to be needed in primitiveBeCursor to handle a bigger form for the cursor

**Comment by astares** [comment]
Possibly workaround: use VistaCursor package and change size in settings

**Comment by VincentBlondeau** [comment]
It would be nice :) 
But it doesn't want to execute the primitive:
```
Cursor(ProtoObject)>>primitiveFailed:
Cursor(ProtoObject)>>primitiveFailed
Cursor>>primitiveBeCursor
Cursor>>beCursor
VistaCursors class>>setResizeLeftCursor
VistaCursors class>>set
VistaCursors class>>initialize
MCMethodDefinition>>postloadOver:

```
I guess it could be linked with the headless VM or some latest changes in Pharo9?

**Comment by astares** [comment]
Ah ... yes. This is due to changes in headless VM in Pharo 9

**Comment by VincentBlondeau** [comment]
@estebanlm suggest to use a binding to GTK to use the native cursors

**Comment by estebanlm** [comment]
well, not exactly :)
I was suggesting to take what we did for the Gtk backend and use it also for the SDL2 backend.
But indeed, in windows using the Gtk backend is an option (but maybe overkilling, if you are not using the rest of the Gtk stack)

**Comment by estebanlm** [comment]
well, not exactly :)
I was suggesting to take what we did for the Gtk backend and use it also for the SDL2 backend.
But indeed, in windows using the Gtk backend is an option (but maybe overkilling, if you are not using the rest of the Gtk stack)

**Comment by astares** [comment]
SqueakVM had support for large cursors (and my VistaCursor package used this). This was introduced by Andreas Raab back at the time. 

See http://lists.squeakfoundation.org/pipermail/vm-dev/2009-March/002399.html

Somehow this got removed now in Pharo VM (due to the switch to headless VM I guess).

<blockquote><div><strong><a href="http://lists.squeakfoundation.org/pipermail/vm-dev/2009-March/002399.html">[Vm-dev] New Window VM (Closures, FT2Plugin, Large Cursors)</a></strong></div></blockquote>

**Comment by VincentBlondeau** [comment]
Fixed

**Comment by Ducasse** [comment]
Nice
