### ISSUE TITLE
Ctrl on ProtoObject definition causes DNU

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#9147]
**Bug description**
Pressing Ctrl on `ProtoObject`definition causes DNU `Instance of RBSequenceNode did not understand #receiver`

**To Reproduce**
1. Go to `ProtoObject` class definition in Calypso and click into the definition pane to set the focus there
2. press Ctrl
3. DNU `Instance of RBSequenceNode did not understand #receiver`

**Version information:**
 - OS: Windows 10
 - Pharo 9.0.0
Build information: Pharo-9.0.0+build.1356.sha.f2e26ea4a61c1d3eb2f0c4024e027d6df3b992f7 (64 Bit)

**Comment by MarcusDenker** [comment]
Duplicate: https://github.com/pharo-project/pharo/issues/7218
