### ISSUE TITLE
Text does understand unescapeCharacter:

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9188]
RubSmalltalkEditor >> copySelection
	"Copy the current selection and store it in the paste buffer, unless a caret.  Undoer & Redoer: undoCutCopy"

	| node escapingCharacter selection |
	"Research of selected node for eventual nesting of comment or string."
	self lineSelectAndEmptyCheck: [^ self].
	node := self bestNodeInTextArea.
	escapingCharacter := self getEscapeCharacterFromAst: node.
	
	selection := (escapingCharacter notNil and: [ 
		"The node, if a comment or a string, should entirely contain the selection.
		We convert the node source interval to an open interval to ignore the node delimiters."
		node sourceInterval asOpenInterval includesAll: self selectionInterval ])
			ifTrue: [ self selection unescapeCharacter: escapingCharacter ]
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
			ifFalse: [ self selection ].
	self clipboardTextPut: selection.
	self editingState previousInterval: self selectionInterval.

**Comment by Ducasse** [comment]
How to reproduce....
select and copy Point >> #setX:setY:  in the following method comment!!

computeEntity
	"Try to guess what the text is:
		Point
		Point >> #setX:setY: 
		Point class >> #setX:setY: 
		#'PackageNameWithDashes'
		"
	| size |
	size := tokens size.

**Comment by Ducasse** [comment]
Please write tests else we will die!!!!!

**Comment by MarcusDenker** [comment]
ups, my fault. Introduced by  https://github.com/pharo-project/pharo/pull/9131

**Comment by Ducasse** [comment]
I added a asString and it seems to work. At least I could continue to work.

**Comment by MarcusDenker** [comment]
not easy to test... this is green:

```
testCopySelection

	| textArea editor |
	textArea := RubEditingArea new.
	textArea editingMode: RubSmalltalkCodeMode new.

	editor := RubSmalltalkEditor new
		          textArea: textArea;
		          addString: 'aa "asdfasdf"';
		          selectInterval: (4 to: 13). 
	self assert: editor selection equals: '"asdfasdf"'.
	self assert: editor selection class equals: Text.
	editor copySelection.
```

**Comment by MarcusDenker** [comment]
Found what to select to have a failing test. made a PR with the test and the fix

**Comment by Ducasse** [comment]
Cool
The first test is the key one. 
For the symbol extraction we did that and it really pays off. 
Else we will always run after bug.

**Comment by kasperosterbye** [comment]
Bug is still there today 
build: 1423, commit: 46d47e8, date: 20 May 2021

It manifest itself when I want to uncomment some code in the browser editor, that is, selecting everything inside a comment and pressing ".

**Comment by kasperosterbye** [comment]
There are several approaches to this thing:

- Make text understand `unescapeCharacter:`, which is actually hard as it has to preserve attributes.
- The only place `unescapeCharacter:` is used is in `RubTextEditor>>encloseWith:` and `RubSmalltalkEditor>>copySelection`. In one example the text is converted to string, which should be done in the other case as well.

The second solution is the right one I think, as the problem seems to be isolated to the RubEditors.

**Comment by kasperosterbye** [comment]
Unfortunately I do not have the time to make a PR now as I am on my way out. But in `RubTextEditor>>encloseWith:` this line: 

```smalltalk
 ifTrue: [ oldSelection unescapeCharacter: left ]
```

should be changed to:
```smalltalk
 ifTrue: [ oldSelection asString unescapeCharacter: left ]
```

There are no other senders of `unescapeCharacter:` in the image code

**Comment by MarcusDenker** [comment]
thanks, I will do a PR
