### ISSUE TITLE
Enhance the inspector on FullBlockClosure with browsing the method instead of the FullBlockClosure class

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#9195]
**Describe the request**
When inspecting a FullBlockClosure, clicking on the browse button will open a browser on the FullBlockClosure. Opening the method containing the block will be more helping.

![image](https://user-images.githubusercontent.com/4706329/116278839-2c43da80-a787-11eb-9592-dd5ba5c0dacf.png)

**Expected development cost**
Low

**Version information:**
 - OS: win10
Pharo9.0.0
build: 1364, commit: f856a55, date: 27 April 2021

**Comment by MarcusDenker** [comment]
Similar to https://github.com/pharo-project/pharo/issues/8219

"browse" seems to be interpreted by users not as a fixed "browse the class of this instance" but a context specific action.

**Comment by MarcusDenker** [comment]
I do not think that we can do this change: the bottom "Browse" means exactly that: "Browse the class of this object that I inspect".  If I inspect a  closure, of course the browse will browse the class of this closure, not the code of the instance.

**Comment by VincentBlondeau** [comment]
Make sense. Thanks Marcus!
