### ISSUE TITLE
Enter key in the numpad does not work

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#9196]
**Bug description**
A press on the numpad enter key (the enter on the right of the keyboard) does not trigger any visible event in Pharo.

Key board layout
![image](https://user-images.githubusercontent.com/4706329/116280732-467eb800-a789-11eb-934f-7c97fce2abbf.png)

**Version information:**
 - OS: win10
Pharo9.0.0
build: 1364, commit: f856a55, date: 27 April 2021

**Expected development cost**
VM or not VM?

**Comment by tesonep** [comment]
Image 😄

**Comment by VincentBlondeau** [comment]
Working! Thanks!
