### ISSUE TITLE
Trying to get back the new Playground brings the old workspace.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9199]
![Screenshot 2021-04-28 at 10 10 33](https://user-images.githubusercontent.com/432549/116369840-1d523c00-a80a-11eb-97fa-ceeb75a40cf7.png)

**Comment by Ducasse** [comment]
And not the SpPlayground

**Comment by estebanlm** [comment]
what means "trying to get back the new playground", how can I reproduce the problem ?
