### ISSUE TITLE
Debugger stack disappears when debugging Set>>asSet

### ISSUE THREAD

**Issue by sonibla** [guillep/pharo-core#9201]
**Bug description**
Stack disappear and impossible to proceed in debugger

**To Reproduce**
1. In a playground, inspect `#(#anything) asSet`
2. In the inspector, debug `self asSet`
3. In the debugger, press into, then restart

**Expected behavior**
Should be able to proceed and see the normal stack

**Screenshots**
![no-stack-debugger](https://user-images.githubusercontent.com/49032546/116378505-7cb44a00-a812-11eb-8487-b04820662253.png)

**Version information:**
 - OS: Win10
 - Version: 9.0.0+build.1370.sha.3a6af8740652245a6e2a848dd5b14e5586849f7f (64 Bit)

**Additional context**
This bug apparently doesn't depend on what's inside the set
I also got this bug with `Array>>asArray`, but not `Array>>size` for example

**Comment by MarcusDenker** [comment]
might be related to https://github.com/pharo-project/pharo/pull/9185

**Comment by sonibla** [comment]
Yes sorry, I didn't see issue https://github.com/pharo-project/pharo/issues/8897, it's the same bug

**Comment by MarcusDenker** [comment]
I close it as a duplicate
