### ISSUE TITLE
save method - corrupted code (multiple times a day)

### ISSUE THREAD

**Issue by SabineMa** [guillep/pharo-core#9206]
**Bug description** 
I work a lot with shortcuts. Especially saving code. About 5-10 times a day I have an annoying problem:
I work, save and suddenly I get the following situation:

![Bildschirmfoto 2021-04-29 um 07 52 52](https://user-images.githubusercontent.com/13763544/116507723-26054980-a8c0-11eb-84b6-7d3a36795b66.png)

In this situation, I was adding an inspect in the onComplete block. The code starting from this line is missing.

Then I have to go to the code changes, get the old version of this method and paste it.
![Bildschirmfoto 2021-04-29 um 07 57 00](https://user-images.githubusercontent.com/13763544/116508231-28b46e80-a8c1-11eb-84e5-8823873ebfe6.png)

**To Reproduce**
It is coming regularly but there is no exact way. My feeling is, that the longer the method is, the more likely it is.
And that it comes if I work fast. It seems that the time of entering code and saving with shortcut is short. But this is only a feeling.
...

this is very annoying because each time I save code I fear that I have to repair.
And it costs my time. It slows me down.
I hope it disappears in Pharo 9
   

**Version information:**
 - OS:  . iOS 
 - Version: 10.15.7
 - Pharo Version Pharo8.0.0
Build information: Pharo-8.0.0+build.1124.sha.0932da82f08175e906b0e2a8052120c823374e9f (64 Bit)

**Comment by SabineMa** [comment]
after creating a new imags the problem disappeared

**Comment by astares** [comment]
OK - so can we/you close it ?

**Comment by SabineMa** [comment]
yes
