### ISSUE TITLE
RBSequenceNode periods, statements, temporaries point to the same instance

### ISSUE THREAD

**Issue by enwiro** [guillep/pharo-core#9208]
**Bug description**
We try to import from sourcecode to FAST pharo. But the RBSequenceNode raised a DNU on isReturn.

**To Reproduce**
1. Import FASTPharo 
2. ```Smalltalk FASTSmalltalkImporterVisitor new runWithSource: (Object >> #at:) sourceCode ``` execute it

**Expected behavior**
The error come from RBSequenceNode periods, statements, temporaries point to the same instance.

**Version information:**
 - OS: Linux
 - Pharo Version 9

**Expected development cost**
PR in progress

**Comment by enwiro** [comment]
Working on it

**Comment by MarcusDenker** [comment]
merged
