### ISSUE TITLE
Ctrl + R to rename a variable in a System Browser does not work

### ISSUE THREAD

**Issue by anneetien** [guillep/pharo-core#9215]
**Bug description**
Ctrl + R shortcut  to rename a variable in a System Browser does not work

**To Reproduce**
Open a Pharo 9 64 image.
Open a System Browser on a method that uses an instance variable for example on AthensCairoPathBuilder >> context: 
Highlight the instance variable and click on Ctrl + R  and it raises an error. Instance of ClyMethodSourceCodeContext did not understand #requestSimpleVariable:from:
If we right click on the variable and rename it it works.

**Expected behavior**
Open the window dialog to rename the variable

**Screenshots**
<img width="981" alt="image" src="https://user-images.githubusercontent.com/17824579/116665938-abf5c300-a99a-11eb-8fc0-333e6f3a7ea7.png">

**Comment by hogoww** [comment]
I'm assuming @Lin777 will fix that better than me.

To document this a bit:
Ctrl + R is the same shortcut for both Rename & Merge Into another (which I'm unsure of what it does).
Therefore, it's using the Merge Into Another command instead of the rename.

**Comment by Lin777** [comment]
Hi @hogoww,

thanks to report this issue, this week I was fixing these types of issues in commands and previews. Also I'm doing an introduction post for all new features of refactoring. Any suggestions o issue report is welcome
