### ISSUE TITLE
Some class methods are saved with classSide instead of class.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9228]
I do not know how to reproduce it but it looks like some people are confused and use classSide instead of class.
And the fileout (at least the code displayed on github for some issues is showing classSide).

have a look at https://github.com/pharo-project/pharo/pull/9075/files

**Comment by astares** [comment]
The PR was saved with Iceberg regulary.

The only place I see where a class vs. classSide is used is in TonelWriter>>#classNameFor:parent:

```Smalltalk
classNameFor: aMethodDefinition parent: aClassDefinition
	aClassDefinition ifNil: [ ^ aMethodDefinition fullClassName ].
	^ aMethodDefinition classIsMeta
		ifFalse: [ aMethodDefinition className ]
		ifTrue: [ 
			aClassDefinition isTraitDefinition
				ifFalse: [aMethodDefinition className, ' class']
				ifTrue: [aMethodDefinition className, ' classSide'] ]
```

**Comment by MarcusDenker** [comment]
I think that was a bug in TonelWriter that was fixed in the meantime.

**Comment by astares** [comment]
But I used a recent image this week like ever when I do PR's

https://github.com/pharo-project/pharo/pull/9075 was opened and provided 18days ago using a fresh image. Then I again used a recent image and had to go back to my branch 3 days ago (again with a fresh zeroconf image) to provide what gcotelli suggested and remove the help button completely.

**Comment by astares** [comment]
Invested some time this evening to bring it back to the same state to better reproduce - but was not lucky yet.

**Comment by Ducasse** [comment]
I would close it for now. And if we can reproduce it we reopen it.
