### ISSUE TITLE
No understable message

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9229]
I wanted to rename 

isCFGInstr into isCFGInstruction 
and this method is defined in two classes and I got this totally unclear message. 

![Screenshot 2021-05-01 at 21 08 51](https://user-images.githubusercontent.com/432549/116792550-9c24ce80-aac1-11eb-955d-ac795d3f71ec.png)

**Comment by Ducasse** [comment]
I see the message should be 
We want to rename method isCFGInstr to isCFGInstruction but we want to warn you that this method is already defined in this hierarchy. Do you want to browse it?
![Screenshot 2021-05-01 at 21 12 20](https://user-images.githubusercontent.com/432549/116792614-135a6280-aac2-11eb-8cdf-78e8063409a4.png)

**Comment by MarcusDenker** [comment]
this seems to be not related to the refactoring engine or any code in Pharo.

I suggest to close the issue
