### ISSUE TITLE
RB - Cmd+T doesn't work in Browser method context

### ISSUE THREAD

**Issue by Lin777** [guillep/pharo-core#9241]
**Bug description**
When we select a method and then a shortcut cmd+t, doesn't appear the "Refactoring" submenu options

**To Reproduce**
1. Select a method in browser (meethod context)
2. Press cmd+t

**Expected behavior**
Show  "Refactoring" submenu options

**Version information:**
 - OS: MacOS Mojave
 - Version: 10.14.6
 - Pharo Version 9.0

**Comment by Alisu** [comment]
@Lin777 I removed it in https://github.com/pharo-project/pharo/pull/9225 we can revert it. I did not check your own fix.

**Comment by Lin777** [comment]
@Alisu Don't worry, there was this error before your change, so they are not related.

**Comment by MarcusDenker** [comment]
This was fixed by https://github.com/pharo-project/pharo/pull/9251
