### ISSUE TITLE
NullWorldRenderer did not understand #convertWindowMouseEventPosition

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9244]
- downloaded a fresh image today (Pharo 9)
- installed master branch of Seaside, open a system browser and **SAVE THE IMAGE** you will 
get following error:

![image](https://user-images.githubusercontent.com/5980033/116969576-cb506100-acb6-11eb-82a1-a8492c59f0fb.png)

**Comment by astares** [comment]
OSWorldRenderer provides this method while NullWorldRenderer does not. They are not in the same hierarchy

![image](https://user-images.githubusercontent.com/5980033/116969722-06eb2b00-acb7-11eb-9338-644bb4799b67.png)

**Comment by astares** [comment]
I guess a possible fix is to push the implementation

```Smalltalk
convertWindowMouseEventPosition: aPosition
	^ (aPosition / self screenScaleFactor) rounded
```

from **OSWorldRenderer** up into **AbstractWorldRenderer** class

**Comment by estebanlm** [comment]
hi, 
why?
NullWorldRenderer is Null (means there will not be a world at all). 
it should just return aPosition

**Comment by estebanlm** [comment]
btw, this should be an event arriving before the initialization of the world..
