### ISSUE TITLE
Shortcut conflict on UML-class tab with CTRL + SHIFT + S

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#9248]
**Bug description**
The UML view on a browser captures the CTRL + SHIFT + S which is also used for the save of the image.

Also, the action triggered on the UML by CTRL + SHIFT + S is not reachable by a menu (or it is well hidden).

**To Reproduce**
1. Open a browser to a class
2. Click on the UML diagram
3. Do CTRL + SHIFT + S
4. See: 
![image](https://user-images.githubusercontent.com/4706329/116992472-5ab93c80-acd6-11eb-83e2-7f66d567c3fd.png)

**Expected behavior**
The shortcut shouldn't be the same. I guess the UML one should be changed.

**Version information:**
 - OS: win10
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1356.sha.f2e26ea4a61c1d3eb2f0c4024e027d6df3b992f7 (64 Bit)

**Expected development cost**
easy

**Additional context**
Vanilla Pharo image

**Comment by astares** [comment]
@akevalion / @bergel  I guess this is a conflict in keymappings (Pharo vs. Roassal)

**Comment by akevalion** [comment]
I have removit from Roassal3 last version, will be present in a new pharo release
