### ISSUE TITLE
Adding Pharo to awesome-for-beginners/goodfirstissues/etc.

### ISSUE THREAD

**Issue by marcor** [guillep/pharo-core#9253]
See [Awesome for beginners ](https://github.com/MunGell/awesome-for-beginners#readme), https://goodfirstissues.com/, ...

([Taken here from pharo#development.](https://discord.com/channels/223421264751099906/278558427796602882/839780147213107240).)

There's already an "easy" label on the issue tracker that seems suitable; "good first issue" would also be a good alternative label (it's [very popular](https://github.com/search?q=label%3A%22good+first+issue%22+is%3Aissue+is%3Aopen) on github - ha! [here's why](https://github.blog/2020-01-22-browse-good-first-issues-to-start-contributing-to-open-source/) I guess, it's part of a feature).

I am available to submit a PR for inclusion to MunGell/awesome-for-beginners when I receive your ok on a chosen label. (_If the label does not clearly state it's "beginner friendly" purpose, please make sure to confirm with the maintainer that it is used for such issues. Please include the link to where the maintainer approves it in the PR._)

**Comment by MarcusDenker** [comment]
Yes, I think having a second label is a good thing: "good first issues" are a bit different than easy issues. Easy issues should be fixed, and often we should not wait too long. A "good first issue" might be an issue that is easy, yes, but in addition it has a good description *and* we keep it open for a beginner explicitly.

Taking into account that there is a github feature, I suggest we use "good first issue"

**Comment by marcor** [comment]
Thanks Marcus. I've sent along the request with the new label.

**Comment by MarcusDenker** [comment]
Thanks, I close this issue as fixed. I have added the tag to a simple to do issue: https://github.com/pharo-project/pharo/issues/8953
