### ISSUE TITLE
Selector resolving and selection in code editor not working 

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#9267]
**Bug description**
Before, if you tried to find senders or implementors without explicit selection, Pharo tried to find the last one in the expression (select current line). Now it does not do that.

**To Reproduce**
1. open Playground
2. write `yourself` and stay with the cursor after the `f`character
3. press `Ctrl+N` to browse senders
4. Error: `#asSymbol was sent to nil`

It seems to try to interpret it as a Playground variable.

There is a very strange case when you put the cursor **inside** the given selector. Then it tries to find senders of `noMethod`

**Comment by MarcusDenker** [comment]
This seems to the problem this is described here,too : https://github.com/pharo-project/pharo/issues/9213

There is a fix: https://github.com/pharo-project/pharo/pull/9220
