### ISSUE TITLE
SpMethodToolbarPresenter not available

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9268]
- go to Calypso and select "Versions" on a method

![image](https://user-images.githubusercontent.com/5980033/117718438-5c09ce00-b1dc-11eb-8e10-d3cb8525b0d3.png)

**Comment by MarcusDenker** [comment]
In the latest Pharo9 image this is no a problem: it uses SpMethodToolbar, not SpMethodToolbarPresenter there.
