### ISSUE TITLE
SpTableWithFilter does not work

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9273]
Run
```Smalltalk
SpTableWithFilter new openWithSpec
```
now try to enter something in the filter:

![image](https://user-images.githubusercontent.com/5980033/117870977-224ccc00-b29d-11eb-84a6-b23b07686c44.png)

**Comment by estebanlm** [comment]
duh! In fact that is a remaining of old times and needs to be removed (the correct class for filtering, etc. is `SpFilteringListPresenter`. There is no table equivalent but it can be implemented in the same way)
