### ISSUE TITLE
CompiledMethod >> #valueWithReceiver: aReceiver arguments: anArray comments is arcane

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9280]
valueWithReceiver: aReceiver arguments: anArray 
	"This should be changed when all the VM will support passign of extra arguments
		^self receiver: aReceiver withArguments: anArray executeMethod: self"

**Comment by MarcusDenker** [comment]
I think the idea is that in current vms, we can use the primitive that is now used in ProtoObject>>#withArgs:executeMethod: in CompiledMethod if we add one more argument:

```
receiver: aReceiver withArguments: anArray executeMethod: anObject
	<primitive: 188>
	self primitiveFailed
```

if we then change #valueWithReceiver:#arguments: to be

```
valueWithReceiver: aReceiver arguments: anArray 
	^self receiver: aReceiver withArguments: anArray executeMethod: self
```

tests are green.

The nice aspect of this is that this allows you to execute a compiled method without sending a message to the object that you execute against.

**Comment by guillep** [comment]
Also take into account that both methods are useful :). The method in `ProtoObject` requires to send a message to the receiver to be able to execute. And for some corner cases, we want to avoid messages to the object themselves (for example, with proxies).

**Comment by MarcusDenker** [comment]
Yes, in additon. I suggest we do this not for Pharo9, though, but early in Pharo10. (Even though I do not think that it would create any problems, but that is the nature of real bugs: that something happens that you did not think would happen)

**Comment by Ducasse** [comment]
At least we should remove the comment.
