### ISSUE TITLE
Many SortedCollection methods return potentially mis-sorted results

### ISSUE THREAD

**Issue by daniels220** [guillep/pharo-core#9286]
Basically, lots of inherited methods use `self species` to decide what class of collection to produce, and for SortedCollection this is _sometimes_ appropriate, but very often not. For a very basic example:

```Smalltalk
#(4 1 7) asSortedCollection reversed "=> SortedCollection(7 4 1)"
"BUT:"
#(4 1 7) asSortedCollection reversed reSort "=> SortedCollection(1 4 7)"
```

Seems like `#reversed` should answer an `OrderedCollection`. Other methods affected include pretty much anything with `collect` somewhere in the selector _other than_ basic `#collect:` (which _is_ overridden to produce an `OrderedCollection`). It seems like, rather than override all of these, it would be ideal to dispatch the creation of a thing-we-will-`#collect:`-into to a method and then override just that. Not sure what to call it. `copyEmptyForTransformation` or `...ForCollect` is dumb but at least it's clear, but I'm open to better ideas.

A couple related notes:
* Seems like `SortedCollection` should override `#addLast:`, either with `self shouldNotImplement`, similar to how it disallows `#addFirst:`, or to redirect back to regular `#add:`. Personally I tend towards making it an error, but I'm not familiar with the existing design philosophy or existing uses.
* I see a comment in `#join:` noting that `#addAllLast:` doesn't re-sort—it will naturally follow the choice made re: `#addLast:`, though if we choose to have `#addLast:` re-sort, it would be a worthwhile optimization to re-sort only _once_ (which means calling `super addLast:` initially).
* As for #join: itself, I'm not familiar with that method, but I wonder if it should also fall back to an OrderedCollection?

**Comment by kasperosterbye** [comment]
I am not sure I understand - `asSortedCollection` is explicitly there to convert the array `#(4 1 7)` into a SortedCollection. It does not have anything to do with reverse or resort. If you just want to sort the array you might do `myArray sort`, or go the long way to convert back to array as in `myArray asSortedCollection reversed asArray`

**Comment by daniels220** [comment]
The use of `asSortedCollection`, and for that matter `reSort`, is entirely for the sake of a concise example. The bug is in `reverse` and the `collect` family. The fundamental problem is that no public method should ever produce a `SortedCollection` which is not, in fact, sorted, yet this is exactly what happens.
