### ISSUE TITLE
Improve loading of extensions to reduce dependency order issues

### ISSUE THREAD

**Issue by theseion** [guillep/pharo-core#9287]
**Is your feature request related to a problem? Please describe.**
Many of the loading issues we face are related to dependency order and a large quantity of these exist only because project A has an extension for project B, which, today, requires B be loaded before A.

**Describe the solution you'd like**
Many times the class that will receive an extension will be loaded eventually. Therefore, it should be possible to
- delay extension loading until all classes of all packages have been loaded or
- retry failed loads of extensions at the.

**Describe alternatives you've considered**
There isn't really an alternative. These issues often arise because no dependency is defined in the baseline of project A for project B, even though an extension for project B exists. While this isn't ideal it also is understandable as it can lead to extremely complex dependency graphs. Other times the extensions are "nice additions" but not required and adding a dependency would be overkill.
Also, it is sometimes not trivial to predict the load order in a large project (like Pharo).

**Expected development cost**
It seems straight forward but knowing the loading mechanics a bit I'm sure there are a couple of non-trivial cases that will crop up. I estimate 1 week (full time).

**[Optional]Additional context**
One example for why this would be nice:
In Pharo GT has an extension for `FuelOutStackDebugAction`. This class is part of the NewTools project. Unfortunately, GT is being loaded before NewTools, so the loader will issue a warning.
- The class clearly does not belong to GT so the method needs to remain an extension. 
- I don't want to modify the load order in Pharo because I can't predict the consequences (I'm sure, there would be some).
- I know for certain that the NewTools project will be loaded
- GT has no class dependencies on NewTools

**Comment by theseion** [comment]
I don't think this needs to remain open. I know there's work being done on this front. Is there anywhere I should link to here @estebanlm @MarcusDenker?

**Comment by estebanlm** [comment]
Yeah, we are working slowly but steady in the correct modularization of what is inside Pharo.
this does not addresses already all problem we have, but we are doing steps in that direction (this will be a long term effer, however)

**Comment by theseion** [comment]
Ok, thanks. I'll close this.
