### ISSUE TITLE
 Multiple selection on list is not working on Windows 10 #1071 

### ISSUE THREAD

**Issue by estebanlm** [guillep/pharo-core#9288]
**Bug description**
In a a list, with multiple selection enabled, you cannot select several items while pressing meta key (ctrl on Windows). Only shifts key works, but this is for selecting a range.
In Mac and Linux all works fine.

**To Reproduce**
In windows, just open the system browser (or any tool with a list and multiple selection) and try to select multiple items with ctrl+click.

**Expected behavior**
there should be several items selected.

first reported by @jordanmontt here: https://github.com/pharo-spec/Spec/issues/1071 (but is not spec specific)

**Comment by jordanmontt** [comment]
I just checked and it is still valid for Pharo 10.

**Comment by jordanmontt** [comment]
We checked again and multiple selection works in Windows 10 without any problem in both Pharo 11 and Pharo 10.

We should close this issue

**Comment by jordanmontt** [comment]
@MarcusDenker
