### ISSUE TITLE
Undo undoes the second to last change if the last change is new line

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#9291]
**Bug description**
The **undo** command undoes the second to last change if the last chnage in the editor was pressing Enter to do a new line.

![BA0Xi5JWRy](https://user-images.githubusercontent.com/572494/118778743-b107ad00-b88a-11eb-8110-0ec04938024b.gif)

**Comment by MarcusDenker** [comment]
This might be fixed with merging https://github.com/pharo-project/pharo/pull/9544

**Comment by MarcusDenker** [comment]
I tested it and it seems to work now
