### ISSUE TITLE
CodeCritics - Improving Critic Description (API Change, API Hints, Architectural)

### ISSUE THREAD

**Issue by Lin777** [guillep/pharo-core#9308]
For example, kernel is displayed twice, but it is not known how it differs or it is just a duplicate critic  

<img width="915" alt="imagen" src="https://user-images.githubusercontent.com/15729309/119155584-56548980-ba21-11eb-886e-8ed620498abe.png">

**Comment by AleCossioCh** [comment]
It is said that they (Kernel, System-Support, Collections-Unordered and others) are duplicated and I checked already, they are not. It's because they reference different dependencies but the critic doesn't show all the information.
