### ISSUE TITLE
CodeCritics - Improving Critic Description (Design flaws, optimization)

### ISSUE THREAD

**Issue by Lin777** [guillep/pharo-core#9310]
Example (RBSmallintTestObject >> searchingLiteral) is showed twice:

<img width="913" alt="imagen" src="https://user-images.githubusercontent.com/15729309/119156573-5acd7200-ba22-11eb-8ccd-4ec1e606fd02.png">

**Comment by AleCossioCh** [comment]
I reviewed every critique of Design flaws and Optimization rule groups. Not found descriptions for improvement. 
There are repeated critiques but it refers to different parts of the code that violate the rule and it is display on the Critized source code.  
Suggest close this issue.

**Comment by Lin777** [comment]
Okay I'll close it, but it would be nice to know with a single glance that each row refers to another part of the code and not have duplicate messages
