### ISSUE TITLE
 CodeCritics - Improving Critic Description (SUnit, Style)

### ISSUE THREAD

**Issue by Lin777** [guillep/pharo-core#9312]
CodeCritics - Improving Critic Description (SUnit, Style)

**Comment by AleCossioCh** [comment]
I reviewed every critique of the SUnit and Style rule groups and not found descriptions for improvement. Suggest close this issue.

However, something curious is the 'criticized source code' shows removeClassVarName: and addClassVarName: all in green. This to 'Class (or pool) variable not capitalized'. Maybe it can have a better view. I leave the example. 
![Screenshot from 2021-06-09 09-27-38](https://user-images.githubusercontent.com/23039347/121363557-0e7ca000-c905-11eb-93c9-12490cc44b3c.png)

**Comment by Lin777** [comment]
Hi Alejandra, thanks. If there are no improvements to do the best thing is to close the issue
