### ISSUE TITLE
CC - Add placeholders in the text editor (FP)

### ISSUE THREAD

**Issue by Lin777** [guillep/pharo-core#9327]
Add placeholders in the text editor to facilitate the edition of keyword messages

**Comment by privat** [comment]
not sure what "*placeholders*" means.

**Comment by Ducasse** [comment]
I think that what would be cool is to have the following behavior

if I have 
```
1 between: 3 | 
```
and I invoke the completion
I would get
```
1 between: 3 and: |
```
S

**Comment by Ducasse** [comment]
where | is the caret

**Comment by privat** [comment]
This is interesting. I have no idea what the model should be to enable this short of thing.
The AST should contain most needed information. For instance, it knows the individual position of each keyword and parenthesis. But maybe is not the best object to talk to and something more intermediate, that knows positions and have some kind of multi-level view could be more handy.
