### ISSUE TITLE
Category cleanup in OCNewCompilerWithChangesFunctionalTest

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9355]
![image](https://user-images.githubusercontent.com/5980033/119978840-67ba0a80-bfba-11eb-9411-7d0e70ad5e00.png)

it should be "tests - other"

**Comment by astares** [comment]
Final results looks like:

![image](https://user-images.githubusercontent.com/5980033/119978959-90da9b00-bfba-11eb-9c81-10f3a495086d.png)

**Comment by MarcusDenker** [comment]
commit is missing a PR

**Comment by astares** [comment]
@MarcusDenker Yes - always the same problem: one reverts to Pharo 9 branch and then forgets to open a new branch for the next issue. If one then accidentially commits into Pharo 9 and pushes the "#fix" statement references the bad commit in Pharo9 branch.

Hard to revert such a case using Iceberg - one has to go back to commandline to reset back Pharo 9 branch to original state (discarding the wrong commit) and force a push to github
