### ISSUE TITLE
A non-headless P9 image is considered headless

### ISSUE THREAD

**Issue by ClotildeToullec** [guillep/pharo-core#9357]
**Bug description**
A non-headless image returns `true` to `#isHeadless` and `false` to `#isInteractive`.

**To Reproduce**
Fresh Pharo9 image from the launcher, not headless.
Evaluate in a playground: 
```smalltalk
Smalltalk isHeadless. "true"
Smalltalk isInteractive "false"
```

**Version information:**
 - OS:  iOS
 - Version: 10.15.7
 - Pharo 9
 - VM 90-x86 last update on 2020-02-12

**Comment by MarcusDenker** [comment]
seems to be the same issue as https://github.com/pharo-project/pharo/issues/8593

**Comment by MarcusDenker** [comment]
I close this as a duplicate for #8593
