### ISSUE TITLE
Typo in category names: refresing => refreshing

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9364]
![image](https://user-images.githubusercontent.com/5980033/120034638-a0c79e80-bffd-11eb-9c3a-f09e74efcb47.png)

Method category name in 

- RSTransitionAnimation 
- RSParallelAnimation 
- RSAbstractAnimation 
- RSSequentialAnimation

needs to be "refreshing and not "refresing"

**Comment by astares** [comment]
@akevalion looks like this needs to be fixed in Roassal, not in Pharo itself

**Comment by astares** [comment]
```Smalltalk
violating:= Set new.
SystemNavigation default
	allClasses do: [ :class | 
		(((class protocols ifNil: #()), 
		(class class protocols ifNil: #())) includes: 'refresing') 
			ifTrue: [ violating add: class ].
		 ].
violating 
 
```

**Comment by akevalion** [comment]
Done in roassal3, will be present in the next release for pharo

**Comment by astares** [comment]
@akevalion Thanks!
