### ISSUE TITLE
Add argument refactoring asks useless default value

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#9378]
**Bug description**
Add argument refactoring does not work at least for two argument methods

**To Reproduce**

1. create a two arguments method
```smalltalk
x: x y: y 

	^ y + y
```
2. method context menu - Refactorings -  Add argument
3. click on `+` button, add default value `10`
4. the selector changed to `x:y:artg:` and arguments list has new item labeled `anObject`, The default value the user entered is ignored, the argument name must be renamed manually and the selector as well. during the generation, the default value is ignored

![image](https://user-images.githubusercontent.com/572494/120218581-3f404380-c23a-11eb-9e66-ee627b0c51e7.png)

**Comment by Lin777** [comment]
Hi @pavel-krivanek I tried to replicate the error but was unsuccessful,

the points to highlight are:
- the default value is used in the senders of the method that you want to add a parameter (see figure)
<img width="774" alt="imagen" src="https://user-images.githubusercontent.com/15729309/121011674-df2f2d00-c764-11eb-8142-a69a7ffb1a7d.png">
- the name of the argument is given by default as well as the name of the method when adding an argument, both can be changed manually.

@pavel-krivanek , @Ducasse 
are you suggest when we adding an argument prompts the user for a name with a floating window, just like the default value?

**Comment by Ducasse** [comment]
Pavel there are two points here:

- The new method name should be x:x y:y arg: anObject
- And the new call site should be self foo x: 33 y: (what was before) arg: 10. 
So it looks ok.

**Comment by Ducasse** [comment]
Let me know if what we describe is not working for you.

**Comment by pavel-krivanek** [comment]
ok, invalid
