### ISSUE TITLE
AthensCairoCanvas missing code for fillRuleEvenOdd

### ISSUE THREAD

**Issue by akevalion** [guillep/pharo-core#9381]
**Bug description**
For some reason the code of fillRuleEvenOdd has been removed in this commit
https://github.com/pharo-project/pharo/commit/e939613baa25b898a93be15c4c85635463a52b2d#diff-65ab15f88a6d29664c8f3691988c93dba50125c65e02a49e4894e858bf427042

**Expected result**
Do a rollback in this method to recover the old code.
```Smalltalk
fillRuleEvenOdd
	self setFillRule: CAIRO_FILL_RULE_EVEN_ODD
```

**Version information:**
 All versions os

**Comment by MarcusDenker** [comment]
merged
