### ISSUE TITLE
Fuel tests started failing on the CI due to failing #setUpClassFactory

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#9389]
**Bug description**
Fuel tests started failing on the CI. 

**To Reproduce**

see https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-9387/1/tests

Strangely, the tests are fine if I download the latest image and run them.

```
Error
receiver of "new" is nil
Stacktrace
MessageNotUnderstood
receiver of "new" is nil
UndefinedObject(Object)>>doesNotUnderstand: #new
UndefinedObject>>doesNotUnderstand: #new
FLBasicSerializationTest(FLSerializationTest)>>setUpClassFactory
FLBasicSerializationTest(FLSerializationTest)>>setUp
FLBasicSerializationTest>>setUp
```

**Comment by MarcusDenker** [comment]
The reason is that class FLClassFactoryForTestCase does not exist

**Comment by MarcusDenker** [comment]
interestingly, the image I get when downloading the latest Pharo:



```
classFactoryForTestCaseClass
	^ ClassFactoryForTestCase
```

while the build artefact of the CI that you download for the PRs we see the problem:

```
classFactoryForTestCaseClass
	^ FLClassFactoryForTestCase
```

**Comment by MarcusDenker** [comment]
This means that somehow, Fuel is different depending on if we run on the CI or not. How can that be?
Doe the CI run load another version?

**Comment by estebanlm** [comment]
this is weird... @theseion, we need some feedback here.

**Comment by theseion** [comment]
Oh wow! Sorry about that! I know why that happened and will fix it ASAP.

**Comment by theseion** [comment]
Should be fixed. I may open another PR for Pharo 9 to make this kind of thing impossible but I'll have to think about how I'm going to do that first.

Why this happened: Fuel loads FuelPlatform from `master` intentionally, so that I can easily adapt across all platforms. However, this means that it will likely break things while I'm developing.
I'm thinking of using a separate branch to mark the platform as "stable".

**Comment by MarcusDenker** [comment]
Thanks!
