### ISSUE TITLE
Cmd+I in an empty Playground signals a "#+ was sent to nil" exception

### ISSUE THREAD

**Issue by olekscode** [guillep/pharo-core#9391]
1. Open an empty Playground in Pharo 9
2. Position a cursor inside it
3. Press Cmd+I (on Mac) or Ctrl+I (on Linux or Windows)

It will signal a _"#+ was sent to nil"_ exception

 - OS: Mac OS BigSur
 - Version: 11.4
 - Pharo 9

<img width="1432" alt="Screenshot 2021-06-03 at 14 44 07" src="https://user-images.githubusercontent.com/8271691/120647312-c0861900-c47a-11eb-8806-3565a279927e.png">

**Comment by MarcusDenker** [comment]
We need to add an empty check for the line, I will do a PR

**Comment by MarcusDenker** [comment]
Fix is here: https://github.com/pharo-spec/Spec/pull/1082
