### ISSUE TITLE
RBParser parseExpression: '<foo>' raises a syntax error

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9404]
I do not really get why we cannot just get a pragma node.

**Comment by Ducasse** [comment]
I needed that to produce a dump of AST to avoid to have to rely on stupid formatting checks that breaks on 
other settings. I wanted to create less brittle tests in PetitParser 

```
assert: aNode format: aString
	aNode isCollection
		ifFalse: [ ^ self assert: (Array with: aNode) format: (Array with: aString) ].
	self assert: aNode size equals: aString size.
	aNode with: aString do: [ :node :string | 
		self 
			assert: node dump
			equals: (RBParser parseExpression: string) dump ]
```

But I cannot use this because the parser breaks on pragma

**Comment by guillep** [comment]
Stef, `RBParser parseExpression: xxx` is meant for expressions only.
And as expression it is meant, informally, as a piece of code that has a value and can be for example, assigned or returned.

This is not the case of pragmas. For example, the two pieces of code here are invalid:

```smalltalk
a := <asd>
or
^ <asd>
```

What this means is that we are probably missing an API exposing the parsing of pragmas

**Comment by Ducasse** [comment]
Yes for the tests I wrapped the code in 
foo 
   prag
   ^ self

I think that we do not really need to parse pragma it was just for PParser.
