### ISSUE TITLE
Push down to only one subclass is a nice operation

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9407]
Push down a method is pushing the methods to all subclasses and often this is not something we need. 
Of course Push down to Single Subclass is not a refactoring in the same that it can break the program 
but this is a super handy transformation when we need it.

**Comment by Lin777** [comment]
Hi @Ducasse 

In fact now for both methods and instance variables push down refactoring copies either methods or variables to their direct subclasses.

Do you think it would be better to give the option to copy only in some of its subclasses? (using a view to select the subclasses where the methods or instance variables will be copied)

**Comment by Ducasse** [comment]
Hi 

I think that push down is correct. But it would be nice to have Push to a Single Subclass that would be another "Refactoring". The one would not be behavior preserving in presence of multiple subclasses.
