### ISSUE TITLE
Crash in Calypso for new baseline class (Error: no #baseline pragma found)

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9419]
Scenario:
 - download latest Pharo 9
 - create a package "BaselineOfMyKillerApp"
 - create a tag "Base" in the package
 - create a class BaselineOfMyKillerApp as subclass of BaselineOf
 
 ```Smalltalk
 BaselineOf subclass: #BaselineOfMyKillerApp
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'BaselineOfMyKillerApp-Base'
 ```
  - add a method category "baseline" and click on it
  
  => CALYPSO will throw an error

![image](https://user-images.githubusercontent.com/5980033/121178951-6234ae00-c85f-11eb-992f-ce515d8e2593.png)

**Comment by MarcusDenker** [comment]
This has been fixed
