### ISSUE TITLE
Can we have a short cut for expand class definition command?

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9429]

**Comment by Ducasse** [comment]
The following command makes possible the expansion of the class definition body. 
![Screenshot 2021-06-11 at 09 59 15](https://user-images.githubusercontent.com/432549/121652205-b330e600-ca9b-11eb-8869-36435595420f.png)

```
SycSingleClassCommand << #ClyExpandClassDefinitionCommand
	tag: 'Commands-Classes';
	package: 'Calypso-SystemTools-Core'
```

```
applyResultInContext: aToolContext

	super applyResultInContext: aToolContext.
	aToolContext tool pendingText: targetClass expandedDefinitionString
```

It is in the source code. Now the short cut do not work.

**Comment by MarcusDenker** [comment]
This was done: CMD-e
