### ISSUE TITLE
RB - Broken test ReSmallintTest>>#testReturnInEnsure

### ISSUE THREAD

**Issue by Lin777** [guillep/pharo-core#9443]
test broken due to update to look for occurrences in method's extraction refactoring

**Comment by MarcusDenker** [comment]
Fails as https://github.com/pharo-project/pharo/pull/9423 was merged where the CI showed that it introduced this error.

I propose to revert that PR for now.

**Comment by Lin777** [comment]
I already understand why the construction in the CI failed, it also seems to me the best option to revert the PR until I correct the error
