### ISSUE TITLE
RBChildrenToSiblingsRefactoring can not handle traits

### ISSUE THREAD

**Issue by rolandbernard** [guillep/pharo-core#9447]
**Bug description**
When using `RBChildrenToSiblingsRefactoring` on classes that use a trait, the `execute` fails halfway through. This error does not happen when the classes are not using any trait.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create the following two empty classes (the package and trait are not important, it also happens with an empty trait):
```smalltalk
Object subclass: #TestClass1
	uses: TLifeware
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Lifeware-DeveloperExtensions'

TestClass1 subclass: #TestClass2
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Lifeware-DeveloperExtensions'
```
2. Execute the following, e.g. in the playground
```smalltalk
refactoring := RBChildrenToSiblingsRefactoring
			name: #TestClassParent
			class: TestClass1
			subclasses: (Array with: TestClass2).
refactoring execute
```

**Expected behavior**
The parent class should be created, methods moved up, and the subclass moved successfully. (The same way it is done when not using the trait)

**Screenshots**
Error that is thrown: 
![image](https://user-images.githubusercontent.com/18496639/121912092-919c5c80-cd30-11eb-9276-6b9d636650ec.png)

Half finished state (with some methods that did not exist on the original classes):
![image](https://user-images.githubusercontent.com/18496639/121912413-db854280-cd30-11eb-9b68-8c1bb132c90c.png)

**Version information:**
 - OS: Windows 10
 - Pharo Version: last tested on 9.0.0 build 1470, commit: 575e39c

**Expected development cost**
I don't know what the problem is exactly, but I assume development cost will be relatively high?

**Comment by Ducasse** [comment]
Thanks for the report. Refactoprings were never revisited to take into account traits. We will check this.

**Comment by carolahp** [comment]
Proposed fix in [PR](https://github.com/pharo-project/pharo/pull/11168)

**Comment by MarcusDenker** [comment]
PR was merged
