### ISSUE TITLE
CodeCritics - Update button wrong behavior

### ISSUE THREAD

**Issue by Lin777** [guillep/pharo-core#9449]
**Bug description**
Update add the same broken critics every time you push the button

**To Reproduce**
1. Open code critics browser
2.  load a  configuration
3. push update button 

**Expected behavior**
If there aren't changes or new broken critics in the selected packages, the same view (now it duplicates broken critics)

**Screenshots**

https://user-images.githubusercontent.com/15729309/122066827-1040da80-cdc1-11eb-882f-5bf15fd2a569.mov

**Version information:**
 - OS: MacOs Mojave
 - Version: 10.14.6
 - Pharo Version Pharo 9.0

**Comment by jordanmontt** [comment]
This issue refers to the old version of the Critics Browser. Now we have in Pharo the new version that developed by @AleCossioCh. We propose to close this issue

**Comment by AleCossioCh** [comment]
I Fixed this issue on the new version of the tool. Thanks for reviewing it @jordanmontt
