### ISSUE TITLE
canonicalize generates invalid FileLocator

### ISSUE THREAD

**Issue by akgrant43** [guillep/pharo-core#9469]
**Bug description**

Sending `#canonicalize` to a `FileLocator` resolves the path, causing the answered `FileLocator` to have an absolute path, which is invalid (the path must always be relative to the origin).

**To Reproduce**

Send `#canonicalize` to a `FileLocator`, .e.g. (on linux):

```
(FileLocator documents / 'dir1' / 'dir2') canonicalize path pathString.
"/home/user/Documents/dir1/dir2"
```

**Expected behavior**

```
(FileLocator documents / 'dir1' / 'dir2') canonicalize path pathString.
"dir1/dir2"
```

(note that the examples chosen don't change when canonicalized since `..` isn't present in the path, it is working correctly).

**Screenshots**

**Version information:**
 - OS: Ubuntu
 - Version: 20.04
 - Pharo Version: 9

**Expected development cost**

PR on the way.

**Additional context**

None.

**Comment by Ducasse** [comment]
Thanks alistair. This is good to bulletproof and enhance this library.
