### ISSUE TITLE
add roundOut to number + comments + tests

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9470]
```
Number>>roundOut
  ^self negative
     ifTrue:  [((self * 2 - 1) / 2) ceiling]
     ifFalse: [((self * 2 + 1) / 2) floor]
```

**Comment by Ducasse** [comment]
I do not really understand what roundOut is doing.
And I could not understand the difference with 

rounded
	"Answer the integer nearest the receiver."
	
	"1.4 rounded >>> 1"
	"1.5 rounded >>> 2"
	"2 rounded >>> 2"
	"-1.5 rounded >>> -2"

	^(self + (self sign / 2)) truncated


roundOut
	"Answer the closest integer"
	
	"1.4 roundOut >>> 1"
	"(10/3) roundOut >>> 3"
	"(10/3) asFloat roundOut >>> 3"
	"1.5 roundOut >>> 2"
	"1.49 roundOut >>> 1"
	"2 roundOut >>> 2"
	"-1.5 roundOut >>> -2"

  ^self negative
     ifTrue:  [((self * 2 - 1) / 2) ceiling]
     ifFalse: [((self * 2 + 1) / 2) floor]

**Comment by svenvc** [comment]
I never heard of round out, maybe it is an alternative name.

It also does not seem to occur in https://en.wikipedia.org/wiki/Rounding

We need to understand what it is and why it is needed before adding it else it will only confuse more people.

<blockquote><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Comparison_rounding_graphs_SMIL.svg/1200px-Comparison_rounding_graphs_SMIL.svg.png" width="48" align="right"><div><strong><a href="https://en.wikipedia.org/wiki/Rounding">Rounding - Wikipedia</a></strong></div></blockquote>

**Comment by Ducasse** [comment]
I agree :)

**Comment by Ducasse** [comment]
So I think that we will not include since we already have rounded

**Comment by astares** [comment]
Normally one works with rounding modes 

For examples see:
 - https://unicode-org.github.io/icu/userguide/format_parse/numbers/rounding-modes.html
 - https://docs.oracle.com/javase/7/docs/api/java/math/RoundingMode.html

<blockquote><img src="/icu/favicon.ico" width="48" align="right"><div>ICU Documentation</div><div><strong><a href="https://unicode-org.github.io/icu/userguide/format_parse/numbers/rounding-modes.html">Rounding Modes</a></strong></div><div>ICU is a mature, widely used set of C/C++ and Java libraries providing Unicode and Globalization support for software applications. The ICU User Guide provides documentation on how to use ICU.</div></blockquote>
<blockquote><div><strong><a href="https://docs.oracle.com/javase/7/docs/api/java/math/RoundingMode.html">RoundingMode (Java Platform SE 7 )</a></strong></div></blockquote>
