### ISSUE TITLE
ReConsistencyCheckRule description is not fully correct

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#9488]
**Bug description**
ReConsistencyCheckRule description is not fully correct and may provide strange results in some cases that the rule checks.

![image](https://user-images.githubusercontent.com/572494/122540921-631ccb00-d029-11eb-9210-4690f8b3f0e0.png)

**To Reproduce**
create a method like:
```smalltalk
msg 

	self = self class ifTrue: [ 
		^ self size >= 1 ]
```

**Comment by MarcusDenker** [comment]
the name "ReConsistencyCheckRule" is not good, either
