### ISSUE TITLE
Compiler error when using whileTrue

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#9493]
**Bug description**

When having the following

```smalltalk
[ [  ​] whileTrue.
   ​^
   | cursor here after the second brackets
```

type a colon (`:`)

And there is an exception

![image](https://user-images.githubusercontent.com/708322/122772054-4a214d80-d2a7-11eb-820b-868161e74968.png)

Looks like a semantic analysis bug?

**Comment by guillep** [comment]
Same happens if I just do


```smalltalk
[  ​] whileTrue.
 ​^
 | cursor here after the first bracket
```

and type colon (`:`)

**Comment by MarcusDenker** [comment]
Yes! I will have a look... the notify is odd. It should just answer false...
