### ISSUE TITLE
Color selection dialog broken

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9495]
```Smalltalk
(ColorSelectorDialogWindow new
		title: 'Choose color';
		selectedColor: Color red) openModal.
```

gives a broken dialog

![image](https://user-images.githubusercontent.com/5980033/122792171-30d5cc80-d2ba-11eb-850f-5f025ac65598.png)

**Comment by MarcusDenker** [comment]
fix was merged: https://github.com/pharo-project/pharo/pull/9575
