### ISSUE TITLE
PharoCommandLineHandler should mention --interactive

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#9512]
**Bug description**
The default command line handler `PharoCommandLineHandler` should probably mention the `--interactive` command line argument in its help (class comment) If the user runs `PharoConsole.exe` just with the image name as an argument, he gets no advice how to start Pharo with the UI now.

**Comment by MarcusDenker** [comment]
related to https://github.com/pharo-project/pharo/issues/8594

**Comment by pavel-krivanek** [comment]
VMs are headful by default, no? @tesonep?

**Comment by pavel-krivanek** [comment]
Since now the interactive mode is the default one, user needs to use `--headless` (as VM argument) to do not run it without GUI and the option is described in the quick help, these two issues can be closed
