### ISSUE TITLE
Spotter produces a DNU when invoked from Calypso

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9513]
How to reproduce.
- Click on the zoom icon
- Type enter
-> DNU activate was sent to nil

**Comment by Ducasse** [comment]
Also the close button does not work.

**Comment by estebanlm** [comment]
yeah, in calypso is fixed (just waiting for a PR to pass and it will be there).
the close button is not a close button but a "remove text"... is just the icon who is wrong :)

**Comment by MarcusDenker** [comment]
is this fixes? I sadly can not test as I do not understand how to reproduce (e.g. I don't know where the "zoom" icon can be found)

**Comment by estebanlm** [comment]
you just press cmd+h
it should be fixed, yes.

**Comment by MarcusDenker** [comment]
on the mac cmd-h hides the window

**Comment by estebanlm** [comment]
ouch. Anyway is fixed :)

**Comment by estebanlm** [comment]
what we need is a way to invoke it. It was cmd+/ in a time, but people complained because the / is in different places of the kb.
