### ISSUE TITLE
DrTests should show 'expected failures' and 'passed unexpectedly'

### ISSUE THREAD

**Issue by ClotildeToullec** [guillep/pharo-core#9545]
**Describe the request**
DrTests should show expected failures and unexpected pass separately. For now it shows expected failures as failures and unexpected pass as passing tests.

**Expected behavior**
Both DrTests and MiniDrTests should have `expected failure`and `unexpected pass` categories in the result tree (maybe only when there actually are some tests in theses categories). 

**Expected development cost**
This could be great for a sprint?

**Screenshot**
Example: how DrTests displays results of these dummy tests for now:
```Smalltalk
testExpectedFailure

	<expectedFailure>
	self assert: false
```
```Smalltalk
testUnexpectedPass

	<expectedFailure>
	self assert: true
```
![Capture d’écran 2021-07-05 à 12 17 02](https://user-images.githubusercontent.com/39184695/124461386-dc8a1c80-dd90-11eb-9dfb-23ce975362f5.png)
As a user seeing this result, I would consider`#testExpectedFailure` a wrong behavior and would not explore `#testUnexpectedPass`. More precise categories would help understanding the results.

**Comment by MarcusDenker** [comment]
fixed by mergeing https://github.com/pharo-project/pharo/pull/11495
