### ISSUE TITLE
Fix and enable SycDeprecateClassCommand 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9551]
I want to deprecate a class and first I'm forced to give an existing class.
Second if I give a class name I get DNU.

S

**Comment by MarcusDenker** [comment]
PR #9569 disables the menu for now, see the commented out pragmas in 

```
SycDeprecateClassCommand class >> browserContextMenuActivation
SycDeprecateClassCommand class >> sourceCodeMenuActivation
```

**Comment by Ducasse** [comment]
Deprecate a class is
- rename class X with NewName (so that all refs are updated)
- create a new subclass of NewName named X (this class is totally empty)

**Comment by MarcusDenker** [comment]
We now have a "Deprecate class" refactoring... it works (used it last week).

I change the title to remove the SycDeprecateClassCommand instead, which is not needed anymore

**Comment by MarcusDenker** [comment]
Ah, no, that was "make Abstract..."

**Comment by MarcusDenker** [comment]
I removed the pharo10 milestone: nice to have but not critical
