### ISSUE TITLE
Typing in the help browser DNU

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#9577]
**Bug description**
- Open the help browser
- type something
- an exception `Does not understand #bindings` happens when trying to autocomplete

![image](https://user-images.githubusercontent.com/708322/125250527-a4d22600-e2f6-11eb-8473-44ef2c15cfd7.png)

Looking a bit, it seems that we should adapt the help browser to be polymorphic with the spec interaction models?

```smalltalk
HelpBrowser >> bindings
	"no additional bindings provided by the Requestor"
	^#() asDictionary
```

I'd need a pair of eyes with some experience in these changes. @MarcusDenker ? @estebanlm ? is a change like that ok?

**Comment by MarcusDenker** [comment]
Yes, change looks good.

For Pharo10 we should do a bit of thinking about the requestor API... e.g. it feels a bit brittle: it is never clear what is used a requestor and then we have problems like this.
