### ISSUE TITLE
RB - Add Refactoring transformation to make class abstract

### ISSUE THREAD

**Issue by miguelcamp** [guillep/pharo-core#9587]
Add a refactoring transformation to be able to make a class abstract through the use of refactoring tools.
Using this would add a method isAbstract like this:
```
MyClass>>isAbstract
    ^self = myClass
```

**Comment by dionisiydk** [comment]
In past I raised a question about abstract classes in ML. But I did not receive any support.
I believe we should model abstract classes explicitly. It can be a normal property of a class and be exposed to the class definition like in in other languages:
```Smalltalk
Superclass < #MyObject
   abstract;
   slots: { #a. #b };
```
(It is a new class definition targeting future Pharo versions).
The current approach with #abstract method is really a hack to cover the lack of proper model for abstract classes.

**Comment by MarcusDenker** [comment]
Yes, for me the methods are a workaroud, we should tag the class as abstract in the class definition. We should think about how to do that, the way shown would be one idea... another could be to have some kind of general "pragma" concept for class definitions (that then can be used for more than just tagging classes as abstract)

**Comment by MarcusDenker** [comment]
(We can add the refactoring that adds the method now and then later change it to add the tag, so this issue is not blocked by the discussion)

**Comment by MarcusDenker** [comment]
this has been done!
