### ISSUE TITLE
Pharo 9: Error during opening newly created P9 stable image

### ISSUE THREAD

**Issue by Bajger** [guillep/pharo-core#9595]
**Bug description**
Exception occurs when new P9 - 64b image is started for first time (freshly downloaded via Pharo Launcher). 

**To Reproduce**
1. Download new Pharo 9.0 - 64bit (stable) image from official distributions
2. Open newly created image
3. Exception with open debugger occurs.
4. TaskbarMorph>>worldMorphs calls `self world` which returns nil. Probably not initialized properly.

**Expected behavior**
P9 normally starts.

**Screenshots**
![image](https://user-images.githubusercontent.com/45875448/125810665-0219dd6f-b3f2-47a7-887d-e49dc174e9cc.png)

**Version information:**
 - OS: macOS Big Sur
 - Version: 11.4
 - HW: MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports) - 2,8 GHz Quad-Core Intel Core i7
 - Pharo Version: P9.0.0, build 1532, 64b

**Expected development cost**
Probably not a big deal, just to fix initializing world in submorph instance?

**Additional context**
[Debugger-Stack-UndefinedObject-2021-07-15-171129.fuel.txt](https://github.com/pharo-project/pharo/files/6824211/Debugger-Stack-UndefinedObject-2021-07-15-171129.fuel.txt)

**Comment by tesonep** [comment]
It is now resolved.
It requires updating the VM. 

From PharoLauncher, click in the VM button and then select the VM and click update.

![image](https://user-images.githubusercontent.com/355455/125932721-90827a4a-0a80-4ea5-b3d5-bd87f197d2e3.png)

**Comment by Bajger** [comment]
Thank you. Update resolved this!
