### ISSUE TITLE
Pharo 9: Error during opening newly created P9 stable image - missing font

### ISSUE THREAD

**Issue by Bajger** [guillep/pharo-core#9596]
**Bug description**
Exception FontSubstitutionDuringLoading occurs during opening new P9 image. 
`StrikeFont class>>familyName:size:` tries to load Source Sans Pro, which is missing.

**To Reproduce**
1. Download new Pharo 9.0 - 64bit (stable) image from official distributions
2. Open newly created image
3. Exception with opened debugger occurs.

**Expected behavior**
New image is opened without any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/45875448/125813855-df6fdf22-1f30-44e5-a334-ac2c905cc9f3.png)

**Version information:**
 - OS: macOS Big Sur
 - Version: 11.4
 - HW: MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports) - 2,8 GHz Quad-Core Intel Core i7
 - Pharo Version: P9.0.0, build 1532, 64b

**Expected development cost**
Probably not a big deal, but I don't know how fonts are being initialized or loaded.

**Additional context**
If needed, I can fuel out stack.

**Comment by astares** [comment]
As a short workaround: open settings in world menu and select other fonts

![image](https://user-images.githubusercontent.com/5980033/125825557-c2a55506-fcd6-4f03-a5ad-42d520e2ec90.png)

**Comment by astares** [comment]
Try settings like 
 - "Use Free type" (select it twice then fonts get loaded)
 - "Update fonts at startup"
 
![image](https://user-images.githubusercontent.com/5980033/125825669-e106ef45-aa84-40be-a791-25cb7fb295fc.png)

**Comment by Bajger** [comment]
@astares : Hi Torsten, would be the solution to have in startup script of Pharo image to call on-time loading of fonts? I don't know however, if it makes sense to load each time image gets started. Is there a way to test, if fonts are loaded already?

**Comment by astares** [comment]
For me it is working - so I can not reproduce. But I do not "macOS Big Sur".

Maybe other people with that OS can try the same to see if it is a general problem or a local issue.

Check in classes like FreeTypeFontProvider: 
```Smalltalk
FreeTypeFontProvider current inspect
```

**Comment by tesonep** [comment]
Fixed, It requires updating the VM. 
Check #9595 for instructions
