### ISSUE TITLE
Pharo 9: Error loading Freetype module when opening Settings Browser -> Appearance tab

### ISSUE THREAD

**Issue by Bajger** [guillep/pharo-core#9597]
**Bug description**
Exception PrimitiveFailed during loading  during opening Settings Browser -> appearance tab.

**To Reproduce**
1. Download new Pharo 9.0 - 64bit (stable) image from official distributions
2. Open newly created image
3. Open Settings Browser -> Appearance tab
4. Error occurs.

**Expected behavior**
Settings Browser -> Appearance tab is opened without any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/45875448/125818523-48f79a02-a1d9-418a-8b2a-66044db0854d.png)

**Version information:**
 - OS: macOS Big Sur
 - Version: 11.4
 - HW: MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports) - 2,8 GHz Quad-Core Intel Core i7
 - Pharo Version: P9.0.0, build 1532, 64b

**Expected development cost**
Something with missing Freetype module. Don't know if it is matter of OS?

**Additional context**
If needed, I can fuel out stack.

**Comment by tesonep** [comment]
Fixed, It requires updating the VM. 
Check #9595 for instructions
