### ISSUE TITLE
Crash on "Workspace with contents"

### ISSUE THREAD

**Issue by bjorn3** [guillep/pharo-core#9609]
**Bug description**
The file browser gave an exception when trying to use "Workspace with contents".

**To Reproduce**
1. Open a directory in the file browser
2. Right click on empty space in the top pane of the file browser
3. Click on "Workspace with contents"
4. A debugger pops up

Same thing happens when right clicking on a text file, though with a different error message.

**Expected behavior**
It doesn't crash.

**Screenshots**

![image](https://user-images.githubusercontent.com/17426603/126144483-05353061-b88b-4200-b844-3b52f1450304.png)

![image](https://user-images.githubusercontent.com/17426603/126144497-8824c53e-dce4-4cb7-a72a-4f863bb28716.png)

**Version information:**
 - OS: Linux
 - Version: [e.g. 1.6.1]
 - Pharo Version: 9

**Expected development cost**
No idea. I guess not a lot.

**Additional context**
Originally reported at https://discord.com/channels/223421264751099906/305208145020715019/865534363545763850

**Comment by MarcusDenker** [comment]
This was fixed
