### ISSUE TITLE
CleanBlockChecker looks to be used before it is loaded

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9612]
Hi marcus

Do you have an idea because it is blocking the context cleaning PR?
https://github.com/pharo-project/pharo/pull/9573

```
isClean
	"Answer if the receiver does not close-over any variables other than globals, and does
	 not ^-return (does not close over the home context).  Clean blocks are amenable to
	 being created at compile-time."
	self numCopiedValues > 0 ifTrue:
		[^false].

	^ CleanBlockChecker check: self method
```

**Comment by MarcusDenker** [comment]
CleanBlockChecker is in the same package as it's superclass: InstructionClient. This is all in Debugging-Core, which, to me, does not make sense.

The whole InstructionClient stuff is *not* just debugging. InstructionClient should be moved close to 
InstructionStream and CleanBlockChecker and some of the other subclasses of InstructionClient should be part of the Kernel (or some "extendend Kernel").
