### ISSUE TITLE
[Download Page] Points to old version of the VM

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#9616]
Section Pharo Standalone of the download page (https://pharo.org/download) points to an old download link of the VM. Update to use the new locations.

**Comment by MarcusDenker** [comment]
can you add to the issue what needs to be edited? Then I can do the change

**Comment by MarcusDenker** [comment]
I think they are now pointing to the right place.

win: http://files.pharo.org/get-files/100/pharo-vm-Windows-x86_64-stable.zip
Mac: http://files.pharo.org/get-files/100/pharo-vm-Darwin-x86_64-stable.zip
Linux: http://files.pharo.org/get-files/100/pharo-vm-Linux-x86_64-stable.zip


If this is still wrong, please open a new issue
