### ISSUE TITLE
Forward Port Pharo10: #9606 changes in pharo 9 in welcome window points to version 8 instead of 9

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#9619]
This PR needs to be merged in Pharo 10:   https://github.com/pharo-project/pharo/pull/9606

**Comment by astares** [comment]
Really? I guess we would need to adopt it to point to Pharo 10.0 changelog directly, no?

**Comment by MarcusDenker** [comment]
Ah yes, even better...

**Comment by astares** [comment]
Initial changelog prepared:   https://github.com/pharo-project/pharo-changelogs/blob/master/Pharo100ChangeLogs.md

<blockquote><img src="https://opengraph.githubassets.com/665532d3c155891fc784e4df57a3e44222647683ccd433e74048555109fd815f/pharo-project/pharo-changelogs" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-changelogs">pharo-project/pharo-changelogs</a></strong></div><div>To describe each version. Contribute to pharo-project/pharo-changelogs development by creating an account on GitHub.</div></blockquote>
