### ISSUE TITLE
changes in pharo 10 in welcome window points to version 8 instead of 10

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#9620]
We need to do the change https://github.com/pharo-project/pharo/pull/9606  but pointing to the Pharo10 changelog

**Comment by astares** [comment]
Initial changelog prepared:   https://github.com/pharo-project/pharo-changelogs/blob/master/Pharo100ChangeLogs.md

<blockquote><img src="https://opengraph.githubassets.com/665532d3c155891fc784e4df57a3e44222647683ccd433e74048555109fd815f/pharo-project/pharo-changelogs" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-changelogs">pharo-project/pharo-changelogs</a></strong></div><div>To describe each version. Contribute to pharo-project/pharo-changelogs development by creating an account on GitHub.</div></blockquote>

**Comment by MarcusDenker** [comment]
this is now fixed

**Comment by MarcusDenker** [comment]
ups, wrong issue

**Comment by MarcusDenker** [comment]
This now needs to be done *after* https://github.com/pharo-project/pharo/pull/9641

**Comment by Ducasse** [comment]
Marcus we should integrate the new microdown based tools and we will manage the help and welcome using MD.
