### ISSUE TITLE
Class documentation contains bogus Factory method

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#9622]
I have a subclass of `SpNotebookPage` named `OvinaOverviewPresenter`. In its class documentation I get this part added automagically:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/17723745/126330566-2d40c05b-d441-4e88-b139-4feb8142c6dd.png">

Which is obviously not the case.

**Comment by Ducasse** [comment]
Thanks for the report. Could you open a ticket in the Spec2 project?

**Comment by kasperosterbye** [comment]
I have moved this issue to the Spec project.
