### ISSUE TITLE
Code finder example gets stuck in fibBench - e.g. 5000. '5,000'

### ISSUE THREAD

**Issue by timm-mwp** [guillep/pharo-core#9624]
**Bug description**
When trying to find a method that prints 1000's seperatators, I entered: 5000. '5,000' into the code Finder examples tab and picked search. It started a progress dialog that just kept going. Pressing cmd -. showed it stuck in fibBench.

**To Reproduce**
1. Go to code Finder and entered: 5000. '5,000' into the code Finder examples tab and picked search
2. Click on search
3. See the progess dialog start and it gets stuck

**Expected behavior**
Should finish quickly like 'a'.'b'.'ab'

**Screenshots**

**Version information:**
 - Version: [e.g. 1.6.1]
 - Pharo Version [e.g 9] 9

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 
In addition, are you willing to help because after all Pharo is yours too?

**Additional context**

**Comment by MarcusDenker** [comment]
the method should normally not be called as #benchFib is explicitly in a black list:

Integer class>>#forbiddenSelectorsForMethodFinder

```
forbiddenSelectorsForMethodFinder

	^ #(#benchFib #tinyBenchmarks)
```

**Comment by MarcusDenker** [comment]
When I try to reproduce, I do not get a problem. The example terminates fast and finds #asStringWithCommas

**Comment by timm-mwp** [comment]
I've gone back and checked and it seems that my Pharo 9 image downloaded via PharoLauncher 2 days ago wasn't the latest one - I had:
Pharo9.0.0
build: 13, commit: 9ad3324
Build information: Pharo-9.0.0+build.13.sha.9ad3324bf8aff11ef0a3af00c1393c6bfd12e201 (64 Bit)

But in creating a new image from PharoLauncher today I now get:
Pharo9.0.0
build: 10, commit: 732baca, date: 20 July 2021
Build information: Pharo-9.0.0+build.10.sha.732baca7eaabf2a5031b2f7d731a781544158b10 (64 Bit)

The latter version works correctly - so I'll close and this helpfully stops me reporting other oddities.
