### ISSUE TITLE
RB Clicking on Refactoring on dropdown menu sends error

### ISSUE THREAD

**Issue by miguelcamp** [guillep/pharo-core#9629]
**Bug description**
When you right click on a method, in the dropdown menu there is a "Refactorings" line that on being hovered over displays a submenu with the different refactorings available. Clicking on this specific line sends an error instead of just displaying the available refactorings. Additionally, the shortcut "Ctrl+T" does not work.

**To Reproduce**
1. Go to any class on the System Browser
2. Right click on any method in the rightmost column
3. Click on "Refactorings"

**Expected behavior**
Clicking on "Refactorings" should only display the submenu

**Screenshots**
![image](https://user-images.githubusercontent.com/45406261/126395337-db82e3d8-c41a-48c0-952c-cce02c713141.png)
![image](https://user-images.githubusercontent.com/45406261/126395440-8d7bd3d1-4f10-4304-9919-cf4c581232cf.png)

**Version information:**
 - OS: Windows 10
 - Version: 10.0.19043
 - Pharo Version 9

**Comment by Ducasse** [comment]
Thanks for the report!

**Comment by Ducasse** [comment]
Fixed
