### ISSUE TITLE
CommandLineUIManager should not setup stderr transcript

### ISSUE THREAD

**Issue by syrel** [guillep/pharo-core#9630]
Here is a code reference:
https://github.com/pharo-project/pharo/blob/ae0e2bfd3468c1cfad5b036a6d5bc7d7ce9866ea/src/UIManager/CommandLineUIManager.class.st#L71

Most likely it would be better to initialize it for stdout. What do you think?

<img width="416" alt="9279E50F-C428-4F55-87C9-3643AEA72D0B" src="https://user-images.githubusercontent.com/5487042/126398700-b62bf51a-cb53-4c41-b3a7-7a76cb2317f0.png">

**Comment by svenvc** [comment]
Yes, I also think it should be stdout
