### ISSUE TITLE
Sources should not contain NUL character

### ISSUE THREAD

**Issue by syrel** [guillep/pharo-core#9631]
Hi 🙂 Stable Pharo9 sources (`Pharo9.0-64bit-e58ef49.sources`) contain `<NUL>` characters on lines `642448` and `834535`.

```
SystemNavigation default allMethods select: [ :m | m sourceCode includes: Character null ]
```
<img width="592" alt="05566EBA-0E14-4A6F-9ED7-169C19CD493E" src="https://user-images.githubusercontent.com/5487042/126398942-251ee4f5-4e01-4770-a555-a702fed74c5c.png">
<img width="726" alt="734C7E71-92A5-4CCF-9A65-602800D92CDA" src="https://user-images.githubusercontent.com/5487042/126398956-8e3147f5-e8da-448d-8ffa-5da70387a530.png">
<img width="1263" alt="BA17D391-5319-4EB2-8952-FEB8551B08B1" src="https://user-images.githubusercontent.com/5487042/126398962-36280cf9-541a-45b1-95be-4096666d8897.png">

**Comment by astares** [comment]
Confirmed:

![image](https://user-images.githubusercontent.com/5980033/126401942-c34e3fa1-4bb4-4f5c-8011-9d0a8e710e84.png)

**Comment by astares** [comment]
Confirmed:

![image](https://user-images.githubusercontent.com/5980033/126402135-2d486565-d0a5-4645-ad6e-dc05daea680d.png)

**Comment by astares** [comment]
![image](https://user-images.githubusercontent.com/5980033/126402206-3432e54f-da6b-4b39-8df9-2a2971ee0c87.png)
