### ISSUE TITLE
Red box of death in Epicea

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#9638]
**Bug description**
Sometimes, when going through changes in Epicea, I get a red box of death like this:

![epicea](https://user-images.githubusercontent.com/572494/126478957-6964e64a-373d-4b23-b7bf-f204cae5640c.png)

It stays there even if you change method to some other. I tried to reproduce it expecting that it does not like some specific AST but next time, it is able to display the same changes without issue. It looks like some race condition. 

As a workaround, I tried in `RubParagraph>>#drawOn:using:at:` to limit the place where the error appears like this:
```smalltalk
line := self lines at: (i min: self lines size).
```
With this, I was not, at least, able to reproduce it at all (which may be just "bad" luck)

**Comment by tinchodias** [comment]
I have an image where I reproduce it easily:

https://github.com/pharo-project/pharo/assets/3044265/8615e88d-bb9e-430c-8c92-e5e6bcd96cff

... and a small change seems to be enough to fix it :)

**Comment by Rinzwind** [comment]
Great to see this fixed! I often encounter it when quickly going through my changes in a ‘Code Changes’ window. Can I suggest opening a pull request to fix it in Pharo 11 as well?

There’s another issue that seems closely related: #15106.
