### ISSUE TITLE
Windows VM missing for Launcher start of Pharo 10.0

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9640]
Launcher can not download a new VM for Pharo 10.0 on Windows:

![image](https://user-images.githubusercontent.com/5980033/126599404-292af65c-fe61-4ca4-aabe-54d295e9f10b.png)

Looks like there is no Windows VM yet in this folder:

![image](https://user-images.githubusercontent.com/5980033/126599502-90ec555a-4bc8-4982-8461-64933937df5d.png)

**Comment by tesonep** [comment]
I have fixed it, sorry I didn't see this issue before.

**Comment by astares** [comment]
Confirm that it works after @tesonep has put the files there.

For the records:
 - when Launcher searches for "../100/pharo64-win-stable.zip" as in the above screenshot then also Launcher needs to be updated by downloading and installing latest version from www.pharo.org
  - because latest launcher will search for "/get-files/100/pharo-vm-Windows-x86_64-stable.zip" which is now there
