### ISSUE TITLE
analyzeRead:by: sent to nil

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9644]
- Type the beginning of a class
- Press Browse
- In the Selector pick up the full class.
- you get the error

**Comment by Ducasse** [comment]
<img width="1036" alt="Capture 2021-07-22 at 12 15 07" src="https://user-images.githubusercontent.com/432549/126624056-98508493-26fe-41bb-bd68-802492ee0089.png">

**Comment by MarcusDenker** [comment]
This is a side effect of "browse it" evaluating a doit... it is very hard to get that right... e.g. showing the menu here is wrong in general, as you just do not want to e.g. add global from doing a "browse it" interaction.

**Comment by MarcusDenker** [comment]
This is one of the things that will be much much simpler when we remove the fixing-dialog from the exception.

**Comment by MarcusDenker** [comment]
I think a fix is to make sure that the evaluation of code that "browse it" does is done non-interactively.

**Comment by MarcusDenker** [comment]
I think a fix for this issue is to not compile with a requestor, but in "non intereractive" mode.

**Comment by MarcusDenker** [comment]
I close this as we have the newer #10695
