### ISSUE TITLE
unload package "Spec-Deprecated" in Pharo10

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#9647]
We should remove the package "Spec-Deprecated"

**Comment by Ducasse** [comment]
We need to migrate Dependency Analyser before.

 ComposablePresenter << #DAPackageTreePresenter
	slots: { #tree . #buttonRefresh . #open . #browser };
	tag: 'Core';
	package: 'Tool-DependencyAnalyser-UI'
