### ISSUE TITLE
FileLocator uninitialised

### ISSUE THREAD

**Issue by svenvc** [guillep/pharo-core#9682]
It seems that in the latest Pharo 9 (downloaded minutes ago) the following:

FileLocator desktop resolve.

Pops up a dialog asking to set the location of {desktop} manually.

I am guessing FileLocator did not properly initialise at startup. It seems it is missing from the session manager. 

This is bad.

Maybe the full list of classes that are supposed to be part of the session manager's start up sequence need to be checked. Such a failure to initialise are sometimes hard to find and can lead to subtle bugs.

**Comment by JanBliznicenko** [comment]
The error seems caused by `PlatformResolver>>#desktop` method missing pragma `<origin>`
