### ISSUE TITLE
FTExamples>>#exampleTree1 menu item Expand All freezes image

### ISSUE THREAD

**Issue by bpieber** [guillep/pharo-core#9697]
1. Do 'FTExamples exampleTree1'
2. Select context menu item 'Expand All'
3. The image freezes. (Most of the times Cmd-Dot works, at least one time it did not.)

Version information:
- Pharo9

**Comment by MarcusDenker** [comment]
It seems to be just very slow. Changing "ProtoObject sublasses" to "Collection allSubclasses" shows that it works
