### ISSUE TITLE
Clean up unicode handling while searching for FFI libraries

### ISSUE THREAD

**Issue by marvin-littlewood** [guillep/pharo-core#9712]
Thank you for Pharo Smalltalk. With Iceberg it is an elegant software development environment. I hope to see it on Android and iOS soon.

**Proposal**
Clean up unicode handling while searching for FFI libraries.

When Pharo is started on a machine where DropBox is used to back-up user folders and the Pharo image and the VM are in these folders, the following occurs during start-up:

`[Post-mortem] Error: Cannot locate any of #('libgit2.1.0.1.dylib' 'libgit2.1.0.0.dylib' 'libgit2.0.25.1.dylib'). Please check if it installed on your system`

When DropBox is no longer used for back-ups the system starts flawlessly, provided the VM is the headless version.

**To Reproduce**
Start PharoLauncher
Create image: **Pharo 9.0 - 64bit (stable)** 
**PS**: _"Launching this image with the default (non-headless) configuration results in Pharo crashing with no windows open."_

VMs update: 90-x64 headless
Edit **Pharo 9.0 - 64bit (stable)** image configuration to use:  **90-x64-headless**
Launch image either using _Basic Launch_ or _Launch_

**Expected behavior**
Flawless start

**Version information:**
 - OS: MacOS Catalina
 - Version: 10.15.7
 - Pharo Version 9.0

**Additional context**
Consider what happens to `~/Documents` when Dropbox is used to back it up. All folders are copied into: `~/Dropbox/My Mac (Marvâs iMac/Documents/`. The computer's name (`Marv's iMac`) contains a unicode apostrophe, added by default by Apple as part of its usual naming convention. 

`FFIMacLibraryFinder>>basePaths` is implemented as follows:

```Smalltalk
basePaths

	^ {
	Smalltalk imageDirectory fullName.
	(Smalltalk vm binary parent / 'Plugins') fullName. 
	(Smalltalk vm binary parent parent / 'Resources' / 'lib') fullName }
```

On Marv's iMac, the following are true:

```Smalltalk
Smalltalk imageDirectory
>>>
"File @ /Users/marv/Dropbox/My Mac (Marv’s iMac)/Documents/Pharo/images/Pharo 9.0 - 64bit (stable)"

Smalltalk vm binary parent
>>>
"{vmBinary}//Users/marv/Dropbox/My Mac (Marvâs iMac)/Documents/Pharo/vms/90-x64-headless/Pharo.app/Contents/MacOS"
```

I suspect the unicode apostrophe in `(Marv's iMac)` may mean that no folders are added to the dynamic array created in `basePaths`, thereby causing errors finding `libGit2` and `libCairo` even though both libraries are installed in the `Plugins` folder. Since Pharo uses unicode internally, this is against expectations.

**Expected development cost**
I expect this is an issue with how the VM reports folder names and how they are processed by the image. While I speculate that may be an uncommon scenario among developers, I suggest that it is worth cleaning up unicode path handling so that newbies are not caught out by this issue. 

(BTW I have searched for similar issues but can only find old, closed issues or an enhancement request to unify the process of finding FFI libraries, to which this may be related.)

**Comment by Ducasse** [comment]
Thanks!

**Comment by Ducasse** [comment]
closed as https://github.com/pharo-project/pharo/pull/9761

**Comment by Ducasse** [comment]
We published it for Pharo 10 and we will issue it soon in Pharo90.
Thanks again for the report.
