### ISSUE TITLE
Pharo 9 looks bad on Windows HiDPI Devices (Microsoft Surface)

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9715]
**DEVICE:** Microsoft Surface Laptop with Windows 10

The Fonts in Pharo 9 look washed out - while the fonts in Pharo 8 look very sharp in comparision. Maybe that is related to

![image](https://user-images.githubusercontent.com/5980033/127747215-98347d2d-18ad-46eb-82da-658976b4089a.png)

**Comment by astares** [comment]
I guess this is due to some changes in Pharo 9 for HiDPI Support.

What works for me better is when I follow the instructions from @KubaO as given in 
https://github.com/pharo-project/pharo/issues/2833

and changing OSSDL2BackendWindow>>#fetchDPI method by adding 

```Smalltalk
fetchDPI
	| displayIndex ddpi hdpi vdpi newDiagonalDPI newScreenScaleFactor |
	"In OS X disable the computation of a DPI based scale factor. These values
	are completely wrong and we are getting scale factors that are very large
	even in non-retina display. This workaround does not affect the support for
	retina display because that is handled by fetching the size of the drawing surface."
	Smalltalk os isMacOSX ifTrue: [ 
		diagonalDPI := verticalDPI := horizontalDPI := self screenScaleFactorBaseDPI.
		screenScaleFactor := 1.0.
		^ false
	].

	displayIndex := sdl2Window getDisplayIndex.
	displayIndex < 0 ifTrue: [ ^ false ].
	
	ddpi := ByteArray new: 4.
	hdpi := ByteArray new: 4.
	vdpi := ByteArray new: 4.
	(SDL2 getDisplay: displayIndex ddpi: ddpi hdpi: hdpi vdpi: vdpi) = 0 ifFalse: [ ^ false ].
	
 	ddpi floatAt: 1 put: 96.0.
	ddpi floatAt: 1 put: 96.0.
	ddpi floatAt: 1 put: 96.0.
	
	newDiagonalDPI := ddpi floatAt: 1.
	"Allow automatic scale of factor increments of 5%. We need to
	round due to precision issues which may result in an almost 1 scale factor, but not exactly one.
	This has to be at least a divisor of 25% which are normal scale factor increments that are selectable in Windows.
	"
	newScreenScaleFactor := newDiagonalDPI / self screenScaleFactorBaseDPI roundTo: 0.05.
	(screenScaleFactor closeTo: newScreenScaleFactor) ifTrue: [ ^ false ].

	horizontalDPI := hdpi floatAt: 1.
	verticalDPI := vdpi floatAt: 1.
	diagonalDPI := newDiagonalDPI.
	screenScaleFactor := newScreenScaleFactor.
	^ true
```

It then looks **sharp** again - but the Windows within Pharo are very small

![image](https://user-images.githubusercontent.com/5980033/127747662-578dcddb-40a6-4d86-a961-2eb37f233b7c.png)

which then could be improved by setting a higher scale factor in the settings:

![image](https://user-images.githubusercontent.com/5980033/127747744-a0b36306-1585-4668-8a84-ae6531bfa516.png)

**Comment by astares** [comment]
I also double checked on two other Windows devices (non-high res) - the change has no effect there.
But it definitely improves the situations on Windows devices with high-res.

So I propose to integrate the PR #9716 into the Pharo 9 branch (and then also merge it into the Pharo 10 branch)

**Comment by dharmatech** [comment]
Here's a screenshot showing some text in Pharo and the same text in Notepad on Windows:

![image](https://user-images.githubusercontent.com/20816/176225123-d0924f19-c62d-43be-a74e-d11ff139723b.png)

As you can see, the text in Pharo is noticeably blurrier.

# Pharo Version

![image](https://user-images.githubusercontent.com/20816/176225481-cf44a67f-c95c-456b-84c0-83e004e9c2ca.png)

# Windows settings

The Pharo window above is on an external display. Windows display settings for this monitor:

![image](https://user-images.githubusercontent.com/20816/176225812-a82db458-ad9d-4029-87ee-dadc16fbd173.png)

# Note

If I should report this in a separate issue, let me know.

Thanks!
