### ISSUE TITLE
Keyboard shortcuts does not work on Pharo 9.0 - Linux

### ISSUE THREAD

**Issue by joao-pedro-braz** [guillep/pharo-core#9722]
**Bug description**
As the title says, I can't open the Playground, System Browser or any other application through keyboard shortcuts.

**To Reproduce**
1. Open a clean Pharo 9.0 Image
2. Try pressing Ctrl + O + W

**Expected behavior**
I expected that the application associated with the shortcut would open. 

**Screenshots**
Not applicable.

**Version information:**
 - OS: Linux KDE Plasma
 - Version: 5.22.3 x64
 - Pharo Version 9.0

**Expected development cost**
This seems to have been fixed in Pharo 10.0 Development Version (Tried the x64  version from PharoLauncher at the "Official Distribution" tab), so I would think is something relatively easy to backport.

**Additional context**
I tested this using 2 Images available in the PharoLauncher, from "https://files.pharo.org/image/90/stable-64.zip" and "https://github.com/pharo-ide/TelePharo/releases/download/continuous/Pharo9.0-64bit-TelePharo.zip"

**Comment by joao-pedro-braz** [comment]
Just updated Pharo 9.0 sources on Pharo Launcher and now the shortcuts work!

**Comment by MarcusDenker** [comment]
Good, I close this as fixed
