### ISSUE TITLE
Roassal baseline notebook should not break!!

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9726]
```
addNotebookPageOn: aNotebook 
	| menu |
	
	menu := CmdMenu activatedBy: ClyBrowserTabCommandActivation.
	menu buildInContext: context.
	
	containerTab := ClyNotebookPageMorph 
		newLabel: self defaultTitle
		icon: self defaultIcon
		provider: [ self buildPageAndDecorate ].
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this can break
	containerTab beCloseable.
	containerTab actions: menu buildBrowserNotebookActions.
	containerTab model: self.
	
	aNotebook 
		addPage: containerTab 
		label: containerTab labelMorph.
	
	^ containerTab
```

It may happen that the baseline is not correct and the roassal pane should not break!!!
So the `buildPageAndDecorate` should be guarded by exception handlers and the page should take actions.

**Comment by Ducasse** [comment]
![Capture 2021-08-03 at 11 32 44](https://user-images.githubusercontent.com/432549/127993290-9fbe005a-fa04-4759-ad6d-ce00f500f7c1.png)

**Comment by akevalion** [comment]
Hi, sorry for the delay and how is this related to roassal3?

How can I reproduce the bug? could you please provide an example, to fix this issue

**Comment by Ducasse** [comment]
Put an 1/0 in `buildPageAndDecorate`.

**Comment by akevalion** [comment]
Ok I have this
![image](https://user-images.githubusercontent.com/10532890/129822185-d0c4933d-d0cd-4352-bc28-b88225b16789.png)
And error in geometry baseline

![image](https://user-images.githubusercontent.com/10532890/129822238-4fcc17be-f61f-4cee-8854-55c4a5cb2bf7.png)

now this graph shows a star to represent error in the baseline

This should not stop the opening of the system browser

**Comment by Ducasse** [comment]
Cool :)

**Comment by MarcusDenker** [comment]
this was fixed
