### ISSUE TITLE
[Ph9] Spec2 List items cannot be selected when medium font is used

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#9731]
**Bug description**
List items cannot be selected once the font size have been changed to medium.

**To Reproduce**
1. Go to the options and change the font size to medium (only medium triggers the bug)
2. Open the spec examples
![image](https://user-images.githubusercontent.com/4706329/128145502-93db84de-4f9c-415a-a40c-1f9b367ef5a3.png)
3. Click on "Lists"
5. None of the list on the right can be selected by clicking but scrolling works...
![image](https://user-images.githubusercontent.com/4706329/128145611-4c5d006a-c5ed-4860-92b2-26f5ca729d5f.png)

**Expected behavior**
Being able to select items

**Version information:**
 - OS: win10
 - Version: 19042.1110
 - Pharo Version Pharo9.0.0
build: 1542, commit: 7864e16, date: 1 August 2021

**Expected development cost**
Fast, it should be a relatively fresh issue.

**Additional context**
Workaround: but the font back to small or large..

**Comment by MarcusDenker** [comment]
backport was merged
