### ISSUE TITLE
Pharo Download page - connection is not private (Certificate issue on OHV Service)

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9732]
Open Download page https://www.pharo.org/download.html

![image](https://user-images.githubusercontent.com/5980033/128158790-57394e2d-2ba4-4dae-8969-a6ba46e1b727.png)

then click on Windows download:

![image](https://user-images.githubusercontent.com/5980033/128158984-b3a70b23-8cff-4e8f-80bb-c3a0a469c33d.png)

**Comment by astares** [comment]
Certificate is not expired:

![image](https://user-images.githubusercontent.com/5980033/128159531-47b7bcb7-c330-4bac-96f1-5f91e5711d09.png)

**Comment by Ducasse** [comment]
Thanks Pablo is fixing this. It may take some times because of internal issues.

**Comment by tesonep** [comment]
@astares can you see if you have still the problem?
Thanks

**Comment by astares** [comment]
@tesonep Confirm that it is working now again. Thanks!
