### ISSUE TITLE
Zeroconf for https://get.pharo.org/90-minimal is broken

### ISSUE THREAD

**Issue by fuhrmanator** [guillep/pharo-core#9734]
**Bug description**
The Zeroconf to download Pharo 9 miminal, e.g., `curl https://get.pharo.org/90-minimal | bash` is broken

**To Reproduce**
1. Open bash shell 
2. `curl https://get.pharo.org/90-minimal | bash`
3. See error

```
curl https://get.pharo.org/90-minimal | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3294  100  3294    0     0   9631      0 --:--:-- --:--:-- --:--:--  9631
Downloading the latest 90 Image:
    http://files.pharo.org/get-files/90/pharo-minimal-x86_64.zip
[image.ZdQSo6/image.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of image.ZdQSo6/image.zip or
        image.ZdQSo6/image.zip.zip, and cannot find image.ZdQSo6/image.zip.ZIP, period.
```
Looking at http://files.pharo.org/get-files/90/ shows that the **pharo-minimal-x86_64.zip** file does not exist. It should be downloading (I think?) **http://files.pharo.org/get-files/90/pharo64-minimal.zip** ?

**Expected behavior**
Unzipping of the minimal image, etc.

**Screenshots**

**Version information:**
 - OS: Ubuntu (WSL2 on Windows 10)
 - Version: 20.04 
 - Pharo Version 9

**Expected development cost**
Just point to the proper image zip file on files.pharo.org

**Context**

This problem was happening *before* #9732

**Comment by astares** [comment]
Source code for ZeroConf is at:  https://github.com/pharo-project/pharo-zeroconf 

<blockquote><img src="https://opengraph.githubassets.com/fb26475826d500d6bd1fdd51555694077af63456f7493f4dfeeb2b6a07970be8/pharo-project/pharo-zeroconf" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-zeroconf">GitHub - pharo-project/pharo-zeroconf: ZeroConf script generator for http://get.pharo.org</a></strong></div><div>ZeroConf script generator for http://get.pharo.org - GitHub - pharo-project/pharo-zeroconf: ZeroConf script generator for http://get.pharo.org</div></blockquote>

**Comment by fuhrmanator** [comment]
@astares TIL... Apologies! 

<del>Can someone help to transfer this?</del> Creating a new issue there...
