### ISSUE TITLE
Missing Class cannot be created in the Debugger from a Unit Test in Pharo 9

### ISSUE THREAD

**Issue by gypsydave5** [guillep/pharo-core#9738]
A class which is missing in a test method cannot be created in the debugger when running the test. Although this situation should be fairly hard to achieve (as the Unknown variable dialogue will appear when the code is accepted), it is possible (the Pharo exercises on Exercism are a good example).

### **To Reproduce**

1. create a new test class in a new package
2. create a new test in that test class
3. in that test class reference an undeclared variable as a class - ie `MissingClass new`.
4. accept the code
5. when the dialogue box appears, select `Leave variable undeclared`
6. Run the test

### **Expected behavior**
Expect a dialogue to appear offering to create the missing class.

Instead the debugger informs that `#new was sent to nil` and offers no way to create the missing class.

### **Screenshots**

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/5469544/128383243-add7fd10-e1e4-4a01-a0e3-27af2871f887.png">

### **Version information:**
 - OS: iOS
 - Chip: Apple M1
 - Version: 11.4 (20F71)
 - Pharo Version: 9

### **Expected development cost**
I'm willing to help, but I don't know how much effort this would be, or where to start!

**Comment by Ducasse** [comment]
Thanks for the suggestion.

**Comment by StevenCostiou** [comment]
This feature does not work with Exercism because Exercism modifies the Pharo kernel.

**Comment by StevenCostiou** [comment]
I'm reopening, I'll try it again from a base image to be sure, but this feature was perfectly working.

**Comment by StevenCostiou** [comment]
Ok it works :)
Exercism need to be fixed :)

**Comment by StevenCostiou** [comment]
For information: details here https://github.com/pharo-project/pharo/issues/9099

**Comment by gypsydave5** [comment]
Thanks for your help on this!
