### ISSUE TITLE
Pharo 10: Playground missing in menu after GT removal

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9749]
After removal of GTTools the **Playground** is gone/not visible from world menu

![image](https://user-images.githubusercontent.com/5980033/128633196-69adaa18-1abc-4e34-be05-55f6fedc5b8b.png)

but it is possible to open using

```Smalltalk
StPlayground open
```

**Comment by Ducasse** [comment]
Yes. I could not find how it was done before because it is not based on <worldMenu> and registering it as a tools did not make it work.

**Comment by Ducasse** [comment]
Fixed
