### ISSUE TITLE
Inspecting a collection in Pharo 10 generate an error

### ISSUE THREAD

**Issue by SergeStinckwich** [guillep/pharo-core#9751]
**Bug description**

When you open an inspector on a Collection there is an error message: did not understand #gtCollectionSizeThreshold
Apparently ``gtCollectionSizeThreshold`` is not implement anymore after Glamour removal, but still used in 2 methods.

**To Reproduce**

```Smalltalk
#(1 2 3) inspect.
```
**Version information:**
 - Pharo Version 10

**Comment by Ducasse** [comment]
Fixed
