### ISSUE TITLE
Black screen using full-screen

### ISSUE THREAD

**Issue by axlgithub** [guillep/pharo-core#9758]
**Bug description**
Locked in a black screen with the mouse only when using the full screen mode of Pharo 10. Can't shutdown the app, can't switch between app. Need to kill Pharo in non ui linux event then the app were not working correctly ( crash when the reduce or shutdown app button were used ).  

**To Reproduce**
1. start Pharo 10 
2. click on dark theme in the startup's popup 
3. in the same popup click on full-screen

**Expected behavior**
Full screen of Paro

**Version information:**
 - OS: Linux 
 - Version: Debian 10 buster ( KDE, X11) / kernel: 4.19.0-17-amd64
 - Pharo Version : 10

**Comment by smokey-panda** [comment]
On Ubuntu 21.10, Pharo 8 stable goes into fullscreen without issue, 9 stable fullscreen toggle causes some kind of loop attempting to maximize, then goes black. Killing or ending the process crashes the Gnome session.

**Comment by Ducasse** [comment]
Thanks for this report.

**Comment by astares** [comment]
@tesonep @estebanlm 
Any update on this one? This prevents linux users from using the full screen mode and the bad thing is that Linux becomes unusable once switched to it.

**Comment by ipsmile** [comment]
CPU:  AMD Ryzen 7 5700G with Radeon Graphics
Motherboard: B550M DS3H
Operating System: Linux Mint 20.3
Kernel: Linux 5.15.0-52-generic
Architecture: x86-64
Pharo Version : 10

Bug experienced is exactly the same as what [axlgithub] has reported on Aug 10, 2021 above.

Would love to know if there is any fixes.

**Comment by ipsmile** [comment]
CPU: AMD Ryzen 7 5700G with Radeon Graphics
Motherboard: B550M DS3H
Operating System: Linux Mint 20.3 / Cinnamon Desktop
Kernel: Linux 5.15.0-52-generic
Architecture: x86-64
Pharo Version : 10

Bug experienced is exactly the same as what [axlgithub] has reported on Aug 10, 2021 above.

Would love to know if there are any fixes.

**Comment by cmkoch** [comment]
Brand/Model: Tuxedo Infinity Book Pro 13
CPU: Intel Core i7-7500U with IntelGraphics 620
Operating System: Ubuntu 22.04 / KDE Desktop
Kernel: Linux 5.15.0-56-generic
Architecture: x86-64
Pharo Version : 10

Same experience as  [axlgithub] ans [ipsmile]. 
Happy too help with testing.

**Comment by smokey-panda** [comment]
'switch-fullscreen' currently works on Pharo 10 with endeavouros-gnome, but not Pharo 9 or 11. As with last year's report, machine is an XPS-13 9310.

**Comment by smokey-panda** [comment]
Fullscreen works fine with Pharo 12 on endeavouros - kde.

**Comment by astares** [comment]
@smokey-panda So can we close? For me it is working.

**Comment by smokey-panda** [comment]
I don't follow Pharo's development closely (I also wasn't OP, but he seems inactive), but I would say close the issue. I don't know what caused the regression from 10 to 11 or if anything was done in 12 to stop the glitch from reoccurring in future versions.
