### ISSUE TITLE
Playground fails on nil result handling

### ISSUE THREAD

**Issue by sharpcoder7** [guillep/pharo-core#9759]
**Bug description**
Playground fails on nil result handling

**To Reproduce**
1. Open Playground
2. Type: `|v| v`
3. Run the code 
4. Exception (Instance of StPlaygroundPagePresenter did not understand #whenClosedDo:) raised in StPlayground
5. ![Screenshot_13](https://user-images.githubusercontent.com/16559744/128953354-011f336d-1bbc-4922-acdc-37d86d4ecbf6.png)

**Expected behavior**
Inspector should show nil value

**Version information:**
 - OS: Windows 10
 - Version: 20H2 (Build 19042.1110)
 - Pharo Version 9.0.0+build.1543

**Details**
StPlayground has newInspectorFor method implementation which checks if aModel is Nil and replaces it to StPlaygroundPage instance (thru newDefaultPlaygroundPage method). Base Implementation of StInspector trying to send a message to whenClosedDo of instantiated inspector of StPlaygroundPage, inspector of StPlaygroundPage instance is StPlaygroundPagePresenter, it does not have required method. 

**Expected development cost**
I like the idea of Pharo language and integrated environment too much, and I can join your community and become a contributor, but I learning Pharo just few days and I need more details:
1. Why default nil inspector is not used in Playground, it works pretty well
2. StPlaygroundPage has it's own inspector (StPlaygroundPagePresenter) with the comment "...playground can be the starting point of an inspection...". I am not clear with that, can someone explain, please?
3. I can not find source code of these classes like StPlayground, StInspector etc on github (I tried to search on current repository and, on current "Organization" and had no results)

**Comment by Ducasse** [comment]
Thanks this is indeed a bug.
I will open an issue on the NewTools of the Spec project.

**Comment by Ducasse** [comment]
https://github.com/pharo-spec/NewTools/issues/269
