### ISSUE TITLE
Debugger should show breakpoints

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#9770]
In the debugger, the source code pane does not show breakpoints (as does the code browser).
It should be nice to show breakpoints so that we know if we will break or not when we proceed

**Comment by StevenCostiou** [comment]
Duplicate of https://github.com/pharo-project/pharo/issues/5211.
Notes:
- showing could be easy (depend on the spec code presenter)
- modifying breakpoints will be hard
