### ISSUE TITLE
Spotter crashes when click on "See all" because of glamour method

### ISSUE THREAD

**Issue by jordanmontt** [guillep/pharo-core#9784]
1. Search for something on the Spotter.
2. Click on the arrow to see all the results
![Screenshot 2021-08-17 at 11 15 24](https://user-images.githubusercontent.com/33934979/129699697-b1f95793-0368-4f27-bc78-987eadccf937.png)
3. The spotter crashes and the debugger is opened with this error:
![Screenshot 2021-08-17 at 11 17 43](https://user-images.githubusercontent.com/33934979/129699760-9ff9d019-2d72-4a32-9756-cda88101ffda.png)

**Comment by Ducasse** [comment]
In Pharo X? Because I fixed it. But may be the package was not loaded.

**Comment by Ducasse** [comment]
Ok I forgot to push it.

```
spotterItemsFor: aStep
	<stSpotterOrder: 10>
	| processor |

	(self isEmpty or: [ self size > self collectionSizeThreshold ]) ifTrue: [ ^ self ].
	processor := aStep previousProcessorFrom: self.
	^ aStep listProcessor
		title: processor title;
		candidatesLimit: 100;
		items: [ self collect: [ :each | each asStSpotterCandidateLink value ] as: OrderedCollection ];
		itemName: processor itemName;
		itemIcon: processor itemIcon;
		actLogic: processor actLogic; 
		filter: processor filter stListFilter;
		wantsToDisplayOnEmptyQuery: true
```

**Comment by MarcusDenker** [comment]
This is now fixed (the method is in the latest build)
