### ISSUE TITLE
Pharo 9 Playground or Testing classes error.

### ISSUE THREAD

**Issue by quorum325** [guillep/pharo-core#9786]
**Bug description**
In the latest Pharo, either the Playground or the Testing classes have a bug when testing classes containing strings
The string contained in the tested class may be split at a line break in the test screen, but that break may be interpreted as being in the tested string.It gives a false negative for the test. I proved this by putting a line break in the tested class code at exactly the same spot, and the false negative test disappeared.

**To Reproduce**

**Expected behavior**
pass test, no error.

**Screenshots**
![Screenshot (3)](https://user-images.githubusercontent.com/8905070/129822410-77a98366-2fc4-4ab6-a3d8-c2d3fee6e4bb.png)

**Version information:**
 - OS: [e.g. iOS] Windows 10
 - Version: [e.g. 1.6.1]
 - Pharo Version [e.g 9]  version 9

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 
In addition, are you willing to help because after all Pharo is yours too?
Yes can help.
Cost unknown.

**Additional context**
I was doing a test class from the book:

"TinyBlog: Develop your First
Web App with Pharo
Olivier Auverlot, Stéphane Ducasse and Luc Fabresse
April 1, 2020"

at: https://lms.fun-mooc.fr/asset-v1:inria+41024+session01+type@asset+block/TinyBlog-EN.pdf#chapter.2

when this error occurred.
The exercise was to create a TinyBlog class and a class to test it (TBTestPost).

The string is in the method:

testPostIsCreatedCorrectly
| post |
post := TBPost
title: 'Welcome to TinyBlog'
text: 'TinyBlog is a small blog engine made with Pharo.'
category: 'TinyBlog'.
self assert: post title equals: 'Welcome to TinyBlog' .
self assert: post text equals: 'TinyBlog is a small blog engine
made with Pharo.' .

and the false line break is after the word "engine".

**Comment by MarcusDenker** [comment]
If you put the line break in the string, it is part of the string. You need to make sure that the string in the code is really the string that you want to test for (that is, does not contain the line break).

**Comment by Ducasse** [comment]
Indeed I will close this bug entry :). If they would be all that easy :)
