### ISSUE TITLE
Intermitent Pharo 9 CI errors: I cannot find a good memory address starting from `{{address}}`

### ISSUE THREAD

**Issue by gcotelli** [guillep/pharo-core#9790]
**Bug description**
For a few days, we're randomly getting errors in our builds with the following message:
`2021-08-20 15:38:17.000 sqAllocateMemory (src/memoryUnix.c:157):I cannot find a good memory address starting from: 0x7faf581ff000`
Find attached the full log
[4_Load group in image.txt](https://github.com/pharo-project/pharo/files/7022719/4_Load.group.in.image.txt)

It looks like no stack trace is generated.

**Version information:**
 - OS:   Ubuntu  20.04.2  LTS
 - Pharo Version 9

**Additional context**
Example failed build:  https://github.com/ba-st/Stargate/pull/127/checks?check_run_id=3383512430

**Comment by Ducasse** [comment]
Thanks for the report!
