### ISSUE TITLE
Deprecated class TextConverter is still used

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#9798]
**Bug description**
TextConverter is deprecated, but it is used bu the method 
- String>>#convertFromEncoding:
- String>>#convertToEncoding:

These are still used in Monticello and by the Method Trailer encoding

**Comment by guillep** [comment]
We can probably replace the implementation of those methods with usages of Zn encoders. And they should be deprecated too because String>>#convertFromEncoding is conceptually wrong

**Comment by svenvc** [comment]
Yes these are conceptually wrong, the senders/users should be fixed. The solution is to either start from bytes in the first place, or go to bytes as a result.

**Comment by axlgithub** [comment]
Hi @svenvc do we have Zinc converter for: (CP1250TextConverter CP1252TextConverter CP1253TextConverter
ISO885915TextConverter ISO88592TextConverter ISO88597TextConverter
KOI8RTextConverter Latin1TextConverter MacRomanTextConverter).
We can not remove the deprecated methods without them...

**Comment by svenvc** [comment]
Sure, I think they are all supported. If you miss any, let me know.
```
ZnCharacterEncoder knownEncodingIdentifiers sorted.

#cp1250 asZnCharacterEncoder.

'Some string' encodeWith: #cp1250.
```
Note also that these mappings are all based on official specs (check for example ZnByteEncoder class>>#cp1250Mapping to see what I mean).

**Comment by axlgithub** [comment]
Thanks @svenvc , indeed every thing needed was here

**Comment by demarey** [comment]
PR #9845 submitted by @axlgithub
