### ISSUE TITLE
Dead outdated code of dependencies are in the Pharo repo 

### ISSUE THREAD

**Issue by dionisiydk** [guillep/pharo-core#9822]
Check the Sindarin packages. They still present in Pharo repo but they are downloaded at every built.
Probably there are other garbage.

It's really important to sort it. Because it is super confusing. Any code changes in such bad dependencies are shown in the Iceberg as Pharo changes.
Then you don't notice it and get super "fun" time trying to understand why the final image does not include your  code (while it is shown as normal changes in diff).

**Comment by astares** [comment]
@dionisiydk 
I'm not sure I understand what you mean here. The Sindarin packages are in the sources of Pharo 10 branch:
https://github.com/pharo-project/pharo/tree/Pharo10/src

![image](https://user-images.githubusercontent.com/5980033/130754510-a298ca73-eabf-4d74-a9cb-192d0ef3904a.png)

as well as in the image:

![image](https://user-images.githubusercontent.com/5980033/130754555-9effd55a-9409-4548-9552-871b9f990800.png)

are they not used?


<blockquote><img src="https://repository-images.githubusercontent.com/64123480/451beb80-d08b-11e9-9ade-21d166d787d9" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">pharo/src at Pharo10 · pharo-project/pharo</a></strong></div><div>Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk. - pharo/src at Pharo10 · pharo-project/pharo</div></blockquote>

**Comment by dionisiydk** [comment]
Yes. That's the problem. Sindarin is always loaded and it overrides the code in this repo. See BaselineOfNewTools>>#sindarin: and users.

**Comment by astares** [comment]
Ah - OK. So it is managed "externally" (loaded from another repo) and "internally" (pharo repo)

**Comment by MarcusDenker** [comment]
added a newer entry: https://github.com/pharo-project/pharo/issues/13966
