### ISSUE TITLE
Inspector columns cannot be resized

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#9828]
**Bug description**
Try inspecting any object with instance variables. You get 2 columns named "Variable" and "Value". For long instvar names, you might want to drag the column border to the right - which is possible, but the final position is always reset to the initial default after releasing the drag.

![3HQIL8VcLd](https://user-images.githubusercontent.com/572494/130793397-f68b690f-0733-4110-abbd-7dbed1ce40ea.gif)

**Comment by MarcusDenker** [comment]
fixed by merging https://github.com/pharo-project/pharo/pull/11262
