### ISSUE TITLE
ProperMethodCategorizationTest(TestAsserter) should report violation and not just oh there is a problem

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9830]
osx-64 / Tests-osx-64 / testNoUncategorizedMethods – MacOSX64.ReleaseTests.Categorization.ProperMethodCategorizationTest
<1s
Error

Assertion failed
Stacktrace

TestFailure
Assertion failed
ProperMethodCategorizationTest(TestAsserter)>>assert:description:resumable:
ProperMethodCategorizationTest(TestAsserter)>>assert:description:
ProperMethodCategorizationTest(Object)>>assert:
ProperMethodCategorizationTest>>testNoUncategorizedMethods
ProperMethodCategorizationTest(TestCase)>>performTest

**Comment by MarcusDenker** [comment]
yes, this will be done as soon as we have fixed all the problems. Right now we do not know which is the new case and which was there already.

**Comment by MarcusDenker** [comment]
I added this to the TODO list in https://github.com/pharo-project/pharo/issues/9705
