### ISSUE TITLE
EmbeddedFreeTypeFontInstaller class >> initialize should not do a super initialize.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9854]
```
EmbeddedFreeTypeFontInstaller class >> initialize
	super initialize.
	self resetCurrent.
	self current.
```

**Comment by astares** [comment]
No - the subject is wrong. It should **NOT** do the super initialize:

![image](https://user-images.githubusercontent.com/5980033/131471265-4a1f2270-71eb-4d2c-a7e8-1bd67c7acf83.png)
