### ISSUE TITLE
Unknown message sent in RBEnvironmentVisitor>>#visitPackageEnv:

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9857]
RBEnvironmentVisitor>>#visitPackageEnv: sends the message #openOn:accept: which is not available in a Pharo 10 image

**Comment by astares** [comment]
![image](https://user-images.githubusercontent.com/5980033/131479547-3ff13d5c-28c8-4988-bba9-91824ddc3961.png)

**Comment by MarcusDenker** [comment]
Duplicate of https://github.com/pharo-project/pharo/issues/14721
