### ISSUE TITLE
Remove unnecessary methods from Microdown package

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9870]
Some methods in Microdown package are unnecessary as they are equivalently defined in superclass:

- MicAnnotatedBlock>>#label
- MicAnnotatedBlock>>#addLineAndReturnNextNode:
- MicAnnotatedBlock>>#canConsumeLine:

The method too
- MicHorizontalLineBlock>>#addLineAndReturnNextNode:
but we keep it due to the different comment depicting how line is written

**Comment by MarcusDenker** [comment]
upstream PR was merged
