### ISSUE TITLE
Small cleanups - class side initialize and other

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9882]
- class side #initialize methods should be in 'class initialization'  category (fixes lint issue)
- methods called from class side #initialize method should be in 'private - initialization' category
- formatting
- removal of dots
- remove unnecessary dots

Side note for first point:
This should reduce the number of methods lint is lamenting about. One can find them using:
```Smalltalk
(SystemNavigation default allImplementorsOf: #initialize) select: [:each |	
	each methodClass isMeta and: [each category ~= #'class initialization'] ]
```

**Comment by Ducasse** [comment]
For the class initialization, it would be nice to enhance the automatic categorizer.
We should pay attention because the recategorisations can make the merging more difficult.

**Comment by astares** [comment]
Merging should be fine - I do it stepwise (this is classes from Z to P if I'm not mistaken)
