### ISSUE TITLE
Release test for #new categorization

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9894]
The #new method on class side should be categorized in 'instance creation'.

Actually this is already OK except 4 cases that will be fixed with PR 9893 and PR 9891.

So we should add a release test to check this. It then will actually be green when 
- https://github.com/pharo-project/pharo/pull/9893
- https://github.com/pharo-project/pharo/pull/9891
are merged.

**Comment by Inao0** [comment]
According to a discussion in #9895, having a rule for this was deemed too strict.
