### ISSUE TITLE
error in printing FileReference

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9898]
```
FileReference 
	fileSystem: FileSystem workingDirectory 
	path: (Path from: '/tmp')
```

**Comment by Ducasse** [comment]
This is just to make printOn: more robust to bogus object.
Because 

```
FileReference 
	fileSystem: FileSystem workingDirectory 
	path: (Path from: '/tmp')
```

is wrong
 and should be 

```
FileReference 
	fileSystem: FileSystem root
	path: (Path from: '/tmp')
```

**Comment by Ducasse** [comment]
So it is a question of design of what we want for printOn:

**Comment by marcor** [comment]
_FileSystem root_ and _Filesystem workingDirectory_ are both FileReference objects not FileSystems. I don't understand why should this be expected to work?

**Comment by olekscode** [comment]
I believe this issue should be closed 
@MarcusDenker @Ducasse
