### ISSUE TITLE
Enhance DoesNotUnderstand exception with a better message text

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#9907]
**Describe the request**

Right now, the message text of a does not understand is `Class>> #selector`.
Printing it is not very useful as it does not say that there was a DNU.
Also, it adds an extra space which feels random and ugly.

**Expected behavior**
A better message in the style of `Message not understood: Class>>#selector`

**Version information:**
 - Pharo 10

**Additional information**
This is important to give better inspector feedback. See https://github.com/pharo-spec/NewTools/issues/276

**Comment by StevenCostiou** [comment]
If I do `1 a`, I see `Instance of SmallInteger did not understand #a`. 
In which case does it only shows ` Class>> #selector`?

**Comment by guillep** [comment]
Sorry, I should have been more precise. This is not a debugger problem, but an error in the base library.
To reproduce:

```smalltalk
[ 1 a ] on: Error do: [ :e | e messageText ]
```
