### ISSUE TITLE
Pharo 9 + Seaside - Process dying when Exception raised in AJAX callback

### ISSUE THREAD

**Issue by yannij** [guillep/pharo-core#9919]
The image exits due to a compiler error in the attached test case. The code signals an exception during the handling of an AJAX callback, made through a Seaside app.

Steps to reproduce:
See next issue comment

**Version information:**
 OS: macOS and Ubuntu
 Pharo Version 9 + Seaside - get a debugger in non-headless, but image exit on headless

**Additional context**
Possibly related to issue #9565

**Comment by yannij** [comment]
Steps to reproduce:
1. In a fresh Pharo9 image, load:
```
Metacello new
	repository: 'github://yannij/MaterialComponentsWeb/src';
	baseline: 'MaterialComponentsWeb';
	onConflictUseLoaded;
	load.
```
Note: With only Seaside loaded, I could not reproduce the compiler parse error appearing in the stack trace, even though the image would exit.
2. File-in the following:
[code-9919.zip](https://github.com/pharo-project/pharo/files/7122851/code-9919.zip)
3. Save the image, and start image with:
`./pharo --logLevel=5 Pharo.image --no-quit > run.log 2>&1`
4. In a web browser go to: http://localhost:8080/issue9919, and click the button there. The image should exit, leaving a PharoDebug.log

**Comment by yannij** [comment]
After the image exits, you should see in PharoDebug.log something like:
```
--- The full stack ---
RBParser>>parserError:
RBParser>>parseVariableNode
RBParser>>parseKeywordPattern
RBParser>>parseMessagePattern
RBParser>>parseMethod
[ parser parseMethod ] in RBParser class>>parseMethod:onError:
FullBlockClosure(BlockClosure)>>on:do:
RBParser class>>parseMethod:onError:
RBParser class>>parseMethod:
OpalCompiler>>parseMethod
[ast := self compilationContext noPattern 
		ifTrue: [ self parseExpression ]
		ifFalse: [ self parseMethod ].
	ast methodNode compilationContext: self compilationContext.
	self doSemanticAnalysis] in OpalCompiler>>parse
FullBlockClosure(BlockClosure)>>on:do:
OpalCompiler>>parse
CompiledMethod>>parseTree
RFReflectivityASTCacheStrategy>>getASTFor:
[ 
			  self class cacheMissStrategy getASTFor: aCompiledMethod ] in [ 
		  self
			  at: aCompiledMethod
			  ifAbsentPut: [ 
			  self class cacheMissStrategy getASTFor: aCompiledMethod ] ] in ASTCache>>at:
[self at: key put: aBlock value] in ASTCache(Dictionary)>>at:ifAbsentPut:
ASTCache(Dictionary)>>at:ifAbsent:
ASTCache(Dictionary)>>at:ifAbsentPut:
[ 
		  self
			  at: aCompiledMethod
			  ifAbsentPut: [ 
			  self class cacheMissStrategy getASTFor: aCompiledMethod ] ] in ASTCache>>at:
AdditionalMethodState>>propertyAt:ifAbsent:
CompiledMethod>>propertyAt:ifAbsent:
ASTCache>>at:
ASTCache class>>at:
CompiledMethod>>ast
CompiledMethod>>sourceNode
```
Lower in the stack is the source code that is failing to parse. The code that fails to parse seems unrelated to the whatever other exception handling is happening. In earlier attempts to reproduce the problem, I was seeing CSS from the Seaside tools code (which of course would cause a parse error).

**Comment by astares** [comment]
Note that @jbrichau fixed https://github.com/SeasideSt/Seaside/issues/1282 - might be the case that the exception problem is not reproducible this way anymore

**Comment by jbrichau** [comment]
@yannij Sorry about that :-)

It's easy to either check out the specific commit before the fix, or just put some mumbo-jumbo dependency declaration in the grPackages. For example, replace the `greaseTestsCore` method with this one. 

```Smalltalk
greaseTestsCore
	^ self new
		name: 'Grease-Tests-Core';
		description: 'Unit tests for the package Grease-Core.';
		addDependency: 'mumbojumbo';
		url: #greaseUrl;
		yourself
```
Having an easily reproducible case is important :-)

**Comment by yannij** [comment]
The fix https://github.com/pharo-project/pharo/issues/9565#issuecomment-921818808 to CommandLineUIManager>>handleDebugRequest: fixes this issue too. I now get a short stacktrace from the ajax callback to the bugTrigger method (instead of the strange CSS content in a stacktrace), and the image no longer exits.

This issue can be closed

**Comment by MarcusDenker** [comment]
Issue can be closed
