### ISSUE TITLE
Implementors in Playground selection gives DNU

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9943]
Pharo 10-64 bit

Open a Pharo playground and enter
```Smalltalk
Smalltalk garbageCollect.
Smalltalk garbageCollectMost.
```

now double click the selector #garbageCollectMost using the mouse so it is selected as text. 
Now hit CTRL + M (which usually should show Implementors) - but it gives a debugger:

![image](https://user-images.githubusercontent.com/5980033/132707058-24d3efa1-4338-440a-a7c6-455b5c294da0.png)

**Comment by astares** [comment]
StPlaygroundInteractionModel(Object)>>doesNotUnderstand: #ast
SpCodePresenter>>browsePoolVarNode:
SpCodePresenter>>browseImplementorOfPoolVar
SpCodePresenter>>doBrowseImplementors
SpBrowseImplementorsCommand>>execute
SpCommand(CmCommandDecorator)>>execute
[ self decoratedCommand execute ] in SpToolCurrentApplicationCommand>>execute in Block: [ self decoratedCommand execute ]
[ activeProcess
			psValueAt: index
			put: anObject.
		aBlock value ] in SpToolCurrentApplication(DynamicVariable)>>value:during: in Block: [ activeProcess...
FullBlockClosure(BlockClosure)>>ensure:
SpToolCurrentApplication(DynamicVariable)>>value:during:
SpToolCurrentApplication class(DynamicVariable class)>>value:during:
SpToolCurrentApplicationCommand>>execute
[ 
			aCmCommand canBeExecuted 
				ifTrue: [ aCmCommand execute ] ] in SpKMCategoryBuilder>>visitCommand: in Block: [ ...
FullBlockClosure(BlockClosure)>>cull:
FullBlockClosure(BlockClosure)>>cull:cull:
FullBlockClosure(BlockClosure)>>cull:cull:cull:
KMCategoryBinding>>completeMatch:buffer:
[ :l | l completeMatch: self buffer: aBuffer ] in KMKeymap>>notifyCompleteMatchTo:buffer: in Block: [ :l | l completeMatch: self buffer: aBuffer ]
Array(SequenceableCollection)>>do:
KMKeymap>>notifyCompleteMatchTo:buffer:
KMKeymap>>onMatchWith:notify:andDo:
[ :entry | 
		entry onMatchWith: anEventBuffer 
			notify: aMatchListener 
			andDo: aBlock ] in KMCategory>>onMatchWith:notify:andDo: in Block: [ :entry | ...
Set>>do:
KMCategory>>onMatchWith:notify:andDo:
KMCategoryBinding>>verifyMatchWith:notifying:thenDoing:
[ :aTarget | 
		"nice hack to stop in the first listener"
		aTarget 
			verifyMatchWith: anEventBuffer 
			notifying: self
			thenDoing: [ ^self ] ] in KMDispatcher>>dispatch: in Block: [ :aTarget | ...
OrderedCollection>>do:
KMDispatcher>>dispatch:
KMTarget>>dispatch:
[ :targetToDispatch |
		targetToDispatch dispatch: KMBuffer uniqueInstance buffer copy.
		aKeyboardEvent wasHandled ifTrue: [ ^self ].
	] in KMDispatchChain>>dispatch: in Block: [ :targetToDispatch |...

**Comment by astares** [comment]
**Side note:** doube clicking the first selector and using CTRL+M shows the implementors correctly:

![image](https://user-images.githubusercontent.com/5980033/132707465-15150060-9d55-4619-8eb4-23bc34f34c4d.png)

**Comment by MarcusDenker** [comment]
I really wonder why "implementors of" tries to be clever and do references to variables?  Is that a good idea? To me "implementors of" should just show methods, or not?

(see doBrowseImplementors)

**Comment by guillep** [comment]
Here's my take on this:

From a UI perspective, we should have only two menu items:
 - go to definition/implementation
 - go to references

And they **should work** regardless of what I'm selecting.

**Comment by MarcusDenker** [comment]
yes, this would be a nice model that goes beyond implementing ST80 "senders" and "implementors". I really like that, because the other is too low level (and guided more by implementation than need).

**Comment by Ducasse** [comment]
I agree when I tried to implement that in the past I did the following

X implementors => X browse, then if absent: basic implementors
X senders =>  X reference then if absent: basic senders
X browse => basicImplementors ifasbent browse

**Comment by MarcusDenker** [comment]
This only happens if there is a requestor binding for the selector, that is, you did e.g. a "print it" of garbageCollectMost, which is understood as printing a var, which then creates it.

**Comment by MarcusDenker** [comment]
The code in browsePoolVarNode: looks too complicated to me... we should rewrite this in terms of delegating to the AST.

-> we have a way to get the AST at a selection or cursor position
-> tell this node what you want
-> a RBVariableNode would delegate to the Variable, for example.

**Comment by MarcusDenker** [comment]
What I find odd... how can a SpCodeInteractionModel *ever* find a pool binding in it's bindings?  The bindings of a Requestor are *only* the binding that it defines. The other ones are coming from the #outerScope (that is, are looked up starting from the class)

**Comment by MarcusDenker** [comment]
Fixed by merging the Spec PR
