### ISSUE TITLE
SycSourceCodeRefactoringCommand is shown in menu

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9947]
![image](https://user-images.githubusercontent.com/5980033/133065124-49812309-0ff6-4729-9768-cf9aba4a382b.png)

**Comment by astares** [comment]
In method pane of Calypso go to "Source code" and you will find an entry "SycSourceCodeRefactoringCommand"

**Comment by MarcusDenker** [comment]
It seems that it adds the abstract superclass SycSourceCodeRefactoringCommand as a command. It is not tagged abstract, but the system seems to not have any scheme to ignore abstract commands, so adding it did not help.

**Comment by astares** [comment]
Yes - same thoughts here. I also tried adding #isAbstract yesterday to return true without any effect.

**Comment by MarcusDenker** [comment]
If we look at other implementors of #canBeExecutedInContext:, in cases that there is an Abstract class they all seem to check for  #isAbtract.

For this case herem, it seems that we can fix it by changing CmdCommand class>>#canBeExecutedInContext: to be:

```
canBeExecutedInContext: anObject

^self isAbstract not
```

I think the other subclasses could be simplified to then always do a check of "super canBeExecutedInContext:". But that is a cleanup that should be done independently from this fix.

**Comment by MarcusDenker** [comment]
pull request is ready for review
