### ISSUE TITLE
Colisions of Calypso edits and refactorings can break the image

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#9950]
**Bug description**
When you edit a method changed in meantime by a refactoring, it can break the package pointer and put system in inconsistent state

**To Reproduce**
1. create a method
```smalltalk
ASTCache class>>#msg1Orig
  ^ 1
```
2. do a modification to this method but do not save it
3. do a refactoring to rename this method to `#msg1Renamed`
4. save the unsaved method, you will be warned about changes elsewhere, accept anyway
5. DNU: `#asSymbol was sent to nil`, only closing possible

As the result, the message `msg1Orig` is not shown in the browser (even a new instance of it) but it can be called and has `nil` as the pacakge, try: 
```smalltalk
(ASTCache class >> #msg1Orig) package.
(ASTCache class >> #msg1Renamed) package.
```

I expect it may be just one of many similar ways how to get such inconsistent state.

**Comment by MarcusDenker** [comment]
wow.. I will have a look.

**Comment by pavel-krivanek** [comment]
seems to be fixed
