### ISSUE TITLE
The inspector overuses exclamation mark

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#9951]
**Bug description**
The inspector changed original "C" icons to exclamation marks and it uses them everywhere. Such icons should be used only for indication of an issue.

![image](https://user-images.githubusercontent.com/572494/133115835-56f73eec-550e-43ee-bc7d-6bf7f9436553.png)

**Comment by Ducasse** [comment]
Yes this is bug and I thought that guille already fixed it.

**Comment by Ducasse** [comment]
@estebanlm I do not know if the fix of guille was integrated.

**Comment by estebanlm** [comment]
yes, I accepted it, but the error is still there.

**Comment by Ducasse** [comment]
this is probably in the ifAbsent block or something like that. 
Related to gtIcons

**Comment by guillep** [comment]
Yes, I did a fix in here, but it was effectively not enough. https://github.com/pharo-spec/NewTools/pull/280
I tested it on morphs only, and I did not realize that there were missing extensions on `ProtoObject` and/or `Object` that were removed during GT's removal.

I think defining `ProtoObject>> inspectorIcon ^nil` should be enough. I'll issue a PR during the day
