### ISSUE TITLE
Iceberg will not work with latest stable installation

### ISSUE THREAD

**Issue by ghost** [guillep/pharo-core#9953]
**Bug description**
Iceberg fails to run with TFFIBackend failed error when trying to make a new repository

**To Reproduce**
0. Install the latest pharo for  x86_64 linux  [stable latest image]
1. Write some code and start Iceberg
2. Add a new repository from scratch
3. See error

**Expected behavior**
A new git repository

**Screenshots**
![image](https://user-images.githubusercontent.com/83974575/133190136-1d8a23d9-950e-4595-bd75-947468f88c38.png)

**Version information:**
 - OS: Void Linux x86_64
 - Version: 5.13
 - Pharo Version: 9

**Additional context**
It looks like an error caused due to no libgit2 linked with the installation

**Comment by JanBliznicenko** [comment]
Hello, what Linux distro do you use?
Do you use Pharo Launcher or download VM and images directly?

**Comment by ghost** [comment]
i used voidlinux and i tried both methods, pharo launcher and download vm n images directly. Sorry for commenting late

**Comment by estebanlm** [comment]
Well... Void Linux is a very alien (new?) distribution. 
Right now we are committed to provide our Linux users (I am one of them!) available VMs for distributions that can be built using Open Build Service, you can see current built VMs here: https://build.opensuse.org/project/show/devel:languages:pharo:latest.

But Void Linux is not one of the possible distributions we could add :(

Which means... you will need to tweak things by your own (and I hope you can commit later a PR with some notes, so we do not lose the knowledge for future Void users).

- You do are not finding libgit2 1.x, so first of all you need to check your system for it and install it in case is not there.
- If you have it, then you need to go to LGitLibrary>>#unix64LibraryName and replace what you have there with: 

```Smalltalk
unix64LibraryName

	^ FFIUnix64LibraryFinder 
		userPaths: { '/path/to/your/lib' };
		findAnyLibrary: #(
			"This name is wrong, but some versions of the VM has this library shipped with the bad name"
			'libgit2.1.0.0.so' 
			'libgit2.so.1.0.0' 
			'libgit2.so.1.0'
			'libgit2.so.1.1'
			'libgit2.so.1.2' 
			'libgit2.so.0.25.1')
```
the good thing is: **if** the problem  is in how the image finds the library, then we can easily submit a patch and you do not have to do this all the time :)

if none of this options works... well, we have a problem. Let me know.

Edit: I just remember, Arch and arch based distros are already moving to libgit2 1.2 and there are some problems there... if that's the case with Void, then  I am working on the patch and it will hit the image soon :)
