### ISSUE TITLE
Different behavior in Playground for deprecated method (transformed vs. nontransformed deprecations)

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9973]
1. Create a simple class Foo

```Smalltalk
Object subclass: #Foo
	instanceVariableNames: '' 
	classVariableNames: ''
	package: 'MyKillerApp'
```

2. Now implement on class side a **class method with a deprecation** like:

```Smalltalk
foo

	self deprecated: 'this is deprecated'
``` 	
When you interactively evaluate this in a Playground you get a **deprecation notification** and can step into the debugger.
![image](https://user-images.githubusercontent.com/5980033/133608857-a1743c50-0b37-4cef-835e-8d93d8672d65.png)

Now when you implement the method using a **deprecation with a transformation** then

```Smalltalk
foo

       self deprecated:  'Please use #bar instead' transformWith:  '`@receiver foo' 
						-> '`@receiver bar'
```
then it will just run **without any depreaction notice**

![image](https://user-images.githubusercontent.com/5980033/133609376-29a9c4b7-3e42-47cd-b95a-0780a3996924.png)

For sure the transformation catches the signal to perform the task of changing the sender method.

But in interactive playing in Playground it might be wished to also get a deprecation notification for the 
methods with a transformation.

**Comment by MarcusDenker** [comment]
the problem is that executing in the playground creates a new method for each execution. That method is not connected to the code in the playground... 

This means that this problem is runs deeper than you would expect, solving it might be very interesting as it would require to have a better code model for playground code and it's execution.

But the first step, falling back to the behavior of a normal deprecation (non-transforming) should be an easy to do first step.

**Comment by astares** [comment]
Cant we find using #DoIt check like in:

![image](https://user-images.githubusercontent.com/5980033/133611436-4bfb12b0-7aba-4e85-83b6-18e4d1bad133.png)

which seem to fix the problem in a hackish way. 

It signals the exception when evaluated from Playground. And if you have other methods like
```Smalltalk
foo

       self deprecated:  'Please use #bar instead' transformWith:  '`@receiver foo' 
						-> '`@receiver bar'.
						
		self bar			
```
and
```Smalltalk
hi

	self foo
```
and
```Smalltalk
bar 

	1 inspect
```
it seems to properly still transform #hi to use # bar instead of #foo when I run it in Playground: 

![image](https://user-images.githubusercontent.com/5980033/133612133-5fc2adb0-6bfe-4ce0-b2f4-191bb05f7200.png)

**Comment by astares** [comment]
To make it also working in Debugger (beside Playground) one needs to check for two selectors:  #DoItIn: and #DoIt

![image](https://user-images.githubusercontent.com/5980033/133613327-df7cc07c-23e5-4528-9294-f09b6fa748fa.png)

**Comment by dionisiydk** [comment]
I think my PR will provide some hooks for this proposal: https://github.com/pharo-project/pharo/pull/9588.

**Comment by MarcusDenker** [comment]
There is #isDoIt on CompiledMethod for a simpler check. We could first do this (fall back to normal Deprecation) and then explore slowly how to build a better connection of code to the AST in the playground after merging #9588

**Comment by MarcusDenker** [comment]
the transform method does alread do:

```
aMethod isDoIt ifTrue:[^ self]. "no need to transform doits"
```

I think this is as simple as changing the :[^ self] to :[^ self signal]
