### ISSUE TITLE
Windows: Limited amount of socket connections

### ISSUE THREAD

**Issue by JanBliznicenko** [guillep/pharo-core#9990]
**Bug description**
After moving to Pharo 9 with my application using Postgres, I noticed it often does not connect to database with all its connection (there is a connection pool) on Windows. This issue is not present on Linux. After investigation, I found out it has nothing to do with Postgres, but rather socket connections from Pharo itself.
It stops after certain amount of connections, no matter the host, port or whether all connections are to the same host or not.

**To Reproduce**
1. Get fresh Pharo 9 or 10 image.
2. Paste following code to Playground - you may change host or port to your localhost service or whatever:
```
1 to: 100 do: [ :index |
	[ 
		socket := Socket newTCP.
		ip := NetNameResolver addressForName: 'google.com' timeout: 5.
		socket connectTo: ip port: 80 waitForConnectionFor: 5.
		"socket disconnect."
	] on: ConnectionTimedOut do: [ ^ 'Stopped at ', index asString ]	
].
^ 'Connected all'.
```
3. Execute with print it or inspect it.

**Expected behavior**
'Connected all' - all connections are made.

**Actual behavior**
'Stopped at 31' or 30 or 60. 
The exact number differs, but usually is 30 or 31. 
It behaves same way to whatever I connect - Postgres on localhost, local web server or google.com. Also, if I make 15 to localhost and 15 to google.com, it stops as well.
If I uncomment the disconnect line, it works, so it does not seem to be limited by amount of connection attemps, but concurrent connections?

**Version information:**
 - OS: Windows 10
 - Pharo Version 9 or 10 with VM downloaded via Launcher
 
Note that I don't actually NEED that many connection and thanks to this bug, I found out I create way more connections than I want due to race conditions.

**Comment by Ducasse** [comment]
Thanks Jan. This is great that you help us with a reproducible case. 
Pablo is actually working on Socket. So he will certainly have a look. @tesonep

**Comment by svenvc** [comment]
Hi Jan,

1. Which PostgreSQL client are you using ?
2. Socket>>#disconnect is not very clean, you need something like Socket>>#closeAndDestroy (which is what higher level socket streams use) 
3. Each socket uses 3 entries of the ExternalSemaphore table, they need cleanup (as does the socket itself, of course)
4. Smalltalk vm maxExternalSemaphores gives you the current limit (divide by 3 for the socket limit) - in my recent 9.0 image, I get 256 entries for about max 80 concurrently existing sockets
5. Unclosed sockets will normally get cleaned up after GC due to finalization (Socket>>#finalize) (if they are indeed garbage, i.e. not held/referenced by anything)

Sven

**Comment by JanBliznicenko** [comment]
> 
> 
> Hi Jan,
> 
>     1. Which PostgreSQL client are you using ?
Hello, I use PostgresV2 used by custom Querier-like tool. However, this problem is unrelated to Postgres. Even connections to google.com via port 80 behave the same way.
> 
>     2. Socket>>#disconnect is not very clean, you need something like Socket>>#closeAndDestroy (which is what higher level socket streams use)
Thanks for the tip. However, not much changes even if I put `Socket allInstancesDo: #closeAndDestroy. 
self assert: (Socket allInstances noneSatisfy: #isConnected)` before the script.
> 
>     3. Each socket uses 3 entries of the ExternalSemaphore table, they need cleanup (as does the socket itself, of course)
> 
>     4. Smalltalk vm maxExternalSemaphores gives you the current limit (divide by 3 for the socket limit) - in my recent 9.0 image, I get 256 entries for about max 80 concurrently existing sockets
Might be related, don't know. However, I do not face this issue on Linux - is it different there?
> 
>     5. Unclosed sockets will normally get cleaned up after GC due to finalization (Socket>>#finalize) (if they are indeed garbage, i.e. not held/referenced by anything)
> 
> 
> Sven

**Comment by svenvc** [comment]
What is the value of Smalltalk vm maxExternalSemaphores on Windows ?

Yes, there might be subtle platform differences.

As author and maintainer of P3 (https://github.com/svenvc/P3) I quickly tried the following (macOS 11.6, Pharo 9, Pharo VM 7.0.4, local PostgreSQL 13.4):

```
Metacello new
   baseline: 'P3';
   repository: 'github://svenvc/P3';
   load.

Smalltalk vm maxExternalSemaphores. "256"

((1 to: 75) collect: [ :each | | client |
	client := P3Client new url: 'psql://sven@localhost'.
	self assert: client isWorking.
	self assert: (Socket allInstances size >= each).
	client ])
	collect: [ :each | | session |
		self assert: each isConnected.
		session := each session.
		each close.
		session ].

Socket allInstances.

3 timesRepeat: [ Smalltalk garbageCollect ].
```

This creates 75 open clients/connections, then tests them all again (isWorking does an actual query) and closes them. So at one point at least 75 sockets are open. It returns all unique PG assigned session IDs. After that expression, no socket instances remain (I started from 0, YMMV). Note that 75 *3 = 225 < 256 max external semaphores.

I know this is not PostgresV2, but this at least gives a high level example of what you probably want to achieve against an actual PG database instance.


<blockquote><img src="https://opengraph.githubassets.com/9d1475e6879afe6df11e53c048583bdd46ca5ca0c0f12b26028f6a015396381e/svenvc/P3" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/svenvc/P3">GitHub - svenvc/P3: A lean and mean PostgreSQL client for Pharo</a></strong></div><div>A lean and mean PostgreSQL client for Pharo. Contribute to svenvc/P3 development by creating an account on GitHub.</div></blockquote>

**Comment by svenvc** [comment]
BTW, you can also do it without P3, but against a real local PostgreSQL database:

```
((1 to: 75) collect: [ :each | | socket |
	socket := Socket newTCP.
	socket connectTo: NetNameResolver localHostAddress port: 5432. 
	self assert: socket isConnected.
	self assert: (Socket allInstances size >= each).
	socket ])
	collect: [ :each |
		self assert: each isConnected.
		each closeAndDestroy.
		#ok ].
```

**Comment by JanBliznicenko** [comment]
maxExternalSemaphores says 256 in all versions of Pharo on Windows as well. That Scripts you provided (after changing username and providing password) cause ConnectionTimedOut on 32nd iteration (just like my scripts and usage) in Pharo 9 and 10 on Windows. Work in Pharo 8. Also work in Pharo 9 and 10 on Linux.

Also, when I want more external objects in Pharo 8, it just gives me error that there is not enough space for external objects, but when I click proceed, it increases this amount and finishes. 

```
	Socket allInstancesDo: #closeAndDestroy.
	self assert: (Socket allInstances noneSatisfy: #isConnected).
	sockets := OrderedCollection new.
	1 to: 260 do: [ :index | 
		[ 
		socket := Socket newTCP.
		ip := NetNameResolver addressForName: 'localhost' timeout: 5.
		socket connectTo: ip port: 5432 waitForConnectionFor: 5.
		sockets add: socket ]
			on: ConnectionTimedOut
			do: [ 
				result := 'Stopped at index ' , index asString
				          , '. External objects: '
				          ,
				          (ExternalSemaphoreTable externalObjects reject: #isNil)
					          size asString , '. Connected sockets: '
				          , (sockets count: #isConnected) asString.
				Socket allInstancesDo: #closeAndDestroy.
				self assert: (Socket allInstances noneSatisfy: #isConnected).
				^ result ] ].
	result := 'Finished. External objects: '
	          ,
	          (ExternalSemaphoreTable externalObjects reject: #isNil)
		          size asString , '. Connected sockets: '
	          , (sockets count: #isConnected) asString.
	Socket allInstancesDo: #closeAndDestroy.
	self assert: (Socket allInstances noneSatisfy: #isConnected).
	^ result
```
returns `Finished. External objects:  783. Connected sockets: 260` on Pharo 8
and `Stopped at index 32. External objects: 103. Connected sockets: 31` on Pharo 9 and 10

And yes, I would like to move to P3 from PostgresV2, I just did not find time in those years :)

**Comment by svenvc** [comment]
Seems like a Windows related problem, maybe @astares can give this a quick try.

In any case, there seems to be enough here to isolate the problem.

I have the feeling that something is wrong growing the table (it starts smaller than its maximum on every platform).

**Comment by tesonep** [comment]
I have released a new version of the VM v9.0.8, this has been fixed in this version

**Comment by svenvc** [comment]
Thank you, @tesonep !

**Comment by astares** [comment]
@tesonep Thank you for taking care of that so quickly.

@JanBliznicenko 
Yes - I can reproduce the issue on Windows too:

![image](https://user-images.githubusercontent.com/5980033/134422653-9eb0e5fb-6031-4430-8681-d2008a9227a0.png)

and can confirm the "Connected all" **after updating the Windows VM for Pharo 10** today

![image](https://user-images.githubusercontent.com/5980033/134422847-3e219d24-a79a-4a58-92eb-cf42fb525d89.png)

**Comment by JanBliznicenko** [comment]
I confirm the problem is fixed as well, thank you for fixing it so quickly
