### ISSUE TITLE
Another DNU when browsing class

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9991]
![Capture 2021-09-19 at 11 20 55](https://user-images.githubusercontent.com/432549/133922226-1a0bb620-0cc8-4382-8be4-8c93a3f39258.png)

**Comment by Ducasse** [comment]
How to reproduce
- select BeautifulComments
- press browse 
- when asked about select BaselineOfBeautifulComments 
-> DNU

Can we get this code more robust?

**Comment by Ducasse** [comment]
And BaselineOfBeautifulComments IS loaded in my image.

**Comment by MarcusDenker** [comment]
There are lots of issue tracker entriy for "Browse it".. it is not working correctly.

- Browse it" evaluates code. Can lead to bad side effects #8515
- Browse Class in code pane only works if entire class selected (senders/implementors correctly looks at AST) #9615

**Comment by MarcusDenker** [comment]
can you copy the text? it is hard to reproduce and the debugger stack in the picture shows just one method.

**Comment by Ducasse** [comment]
The code is in the image in loadExtraTools. 
May be to reproduce you have to execute the commented code once before

**Comment by MarcusDenker** [comment]
This is this issue: https://github.com/pharo-project/pharo/issues/9644

The problem here is that we, at some point, change "browse it" to blindly evaluate code. But this is not a good idea, as the compiler now wants to propose how to fix the code if it sees an undeclared variable, but this makes no sense at all in the context of the "browse it". So for sure evaluation on that level should not be interactive.

But the problem is deeper: see #8515: it just makes no sense for "browse it" to evaluate code the way it does. E.g. if have code like

```
Smalltalk snapshot: true andQuit: true
```

put the cursor on "Smalltalk", it quits the image.

**Comment by MarcusDenker** [comment]
as this is a duplicate of #9644, I close this as a duplicate

**Comment by dionisiydk** [comment]
I agree with Marcus: the code navigation should not lead to the code execution.
It is a security hole. Imagine environment where you allow users to see the code but you want to lock the arbitrary code evaluation. It will be impossible with current behaviour

**Comment by Ducasse** [comment]
For security sorry but this is a joke.

**Comment by dionisiydk** [comment]
@Ducasse So you don't think that browseIt should be safe to execute.
```Smalltalk
myPrivateFile delete
```
```Smalltalk
myPrivateKey showInFacebook
```
Marcus example with snapshotAndQuite. Whatever side effect from the selected expression. 
Why you do not think it is important to be protected from this?

I never hear from anybody except you that browseIt should evaluate the code. But this is essential function for the system navigation and your wish is to make it unsafe to use.

**Comment by Ducasse** [comment]
But if you do silly things then of course. Now what is nice with the current behavior is that I do not have to open an inspector to just to self class browse and this is something that I do all the time.

**Comment by Ducasse** [comment]
So then propose that Browse can be smart enough to see that when I have an object I can just browse its class. 
Because without this it breaks the flow.

**Comment by dionisiydk** [comment]
But your example with "10@30" does not fit to this.
It's easy to add the analysis of a selected variable but what we can do with an arbitrary expression?

**Comment by dionisiydk** [comment]
> But if you do silly things then of course. 

silly thinks is what can easily happen under a deep debugging session when you can incidentally browseIt over wrong expression. And it's not only dangerous. It can just interrupt your work flow by implicitly breaking some objects state. Even worse if you will not notice it continuing debugging over wrong objects state and trying to figure out this.

**Comment by Ducasse** [comment]
How easy?
I want to be able to browse the result of an expression because I want to browse the class of this resulting expression
When I'm programming I'm the boss. 
If I do something silly then this is MY fault. Now the system cuts my finger.

**Comment by dionisiydk** [comment]
> How easy?

We know the ast and the context so we can have a live variable value from the selected code. It is already used in some places.

> I want to be able to browse the result of an expression because I want to browse the class of this resulting expression
> When I'm programming I'm the boss.
> If I do something silly then this is MY fault. Now the system cuts my finger.

I understand your point. And I hope you also see mine. Maybe the best is to have a setting for such behavior.
